------------------------------------------------------------------------------------------------------------
-- World Generation
------------------------------------------------------------------------------------------------------------

-- WORLDGEN RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES = "Aloes"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES = "Asparaguses"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS = "Fennels"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS = "Giant Parsnips"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS = "Mushroom Stumps"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES = "Truffles"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS = "Parsnips"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES = "Radishes"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES = "Stone Slabs"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES = "Sweet Potatoes"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS = "Turnips"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS = "Wild Wheats"

-- WORLDGEN OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS = "Lotus Flowers"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES = "Watery Crates"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS = "Wrecks"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS = "Sea Cucumbers"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS = "Taro Roots"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES = "Watercresses"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA = "Seaweeds"

-- WORLDGEN SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.SERENITYISLAND = "Pig Elder"
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS = "Chickens"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS = "Pebble Crabs"
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS = "Salt Ponds"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES = "Spotty Shrubs"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES = "Sugarflies"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS = "Sugar Flowers"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES = "Sugarwood Trees"

-- WORLDGEN MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.MEADOWISLAND = "Sammy"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS = "Fishermerms"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMHUTS = "Fishermerm's Huts"
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES = "Crates"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES = "Palm Trees"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS = "Limpet Rocks"
STRINGS.UI.CUSTOMIZATIONSCREEN.MERMHUTS = "Mermhuts"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS = "Pikos"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE = "Orange Pikos"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOTREES = "Infested Tea Trees"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES = "Pineapple Bushes"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS = "Sandy Piles"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES = "Tea Trees"
STRINGS.UI.CUSTOMIZATIONSCREEN.TIDALPOOLS = "Tidal Pools"

------------------------------------------------------------------------------------------------------------
-- World Settings
------------------------------------------------------------------------------------------------------------

-- WORLDSETTINGS RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES_SETTING = "Aloes"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES_SETTING = "Asparaguses"
STRINGS.UI.CUSTOMIZATIONSCREEN.COFFEEBUSHES_SETTING = "Coffee Plants"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS_SETTING = "Fennels"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS_SETTING = "Giant Parsnips"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS_SETTING = "Mushroom Stumps"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES_SETTING = "Truffles"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS_SETTING = "Parsnips"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES_SETTING = "Radishes"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES_SETTING = "Stone Slabs"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES_SETTING = "Sweet Potatoes"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS_SETTING = "Turnips"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS_SETTING = "Wild Wheats"

-- WORLDSETTINGS OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS_SETTING = "Lotus Flowers"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES_SETTING = "Watery Crates"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS_SETTING = "Wrecks"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS_SETTING = "Sea Cucumbers"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS_SETTING = "Taro Roots"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES_SETTING = "Watercresses"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA_SETTING = "Seaweeds"

-- WORLDSETTINGS SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS_SETTING = "Chickens"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS_SETTING = "Pebble Crabs"
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS_SETTING = "Salt Racks"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES_SETTING = "Spotty Shrubs"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES_SETTING = "Sugarflies"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS_SETTING = "Sweet Flowers"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES_SETTING = "Sugarwood Trees"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAPSUGARTREES_SETTING = "Saps"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAP2SUGARTREES_SETTING = "Ruined Saps"
STRINGS.UI.CUSTOMIZATIONSCREEN.RUINEDSUGARTREES_SETTING = "Ruined Sugarwood Trees"

-- WORLDSETTINGS MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS_SETTING = "Fishermerms"
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES_SETTING = "Crates"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES_SETTING = "Palm Trees"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS_SETTING = "Limpet Rocks"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS_SETTING = "Pikos"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE_SETTING = "Orange Pikos"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES_SETTING = "Pineapple Bushes"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS_SETTING = "Sandy Piles"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES_SETTING = "Tea Trees"