STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_COFFEEBUFF_START =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_COFFEEBUFF_END =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_HASTEBUFF_START =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_HASTEBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_POPBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_POPBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_FROGBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_FROGBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_PIRATEBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_PIRATEBUFF_END =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_FREEZEBUFF_START =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_FREEZEBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_FIREBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_FIREBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_FISHINGBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_FISHINGBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_SANITYRATEBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_SANITYRATEBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_EATERBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_EATERBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_WORMBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_WORMBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_CRABBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_CRABBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_STEALTHBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_STEALTHBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_FEARBUFF_START = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_FEARBUFF_END = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_TRUFFLESBUFF_START =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_TRUFFLESBUFF_END =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_CRAFTINGBUFF_START =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_CRAFTINGBUFF_END =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_MAXHEALTHBUFF_START =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_MAXHEALTHBUFF_END =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_MAXHUNGERBUFF_START =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_MAXHUNGERBUFF_END =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_MAXSANITYBUFF_START =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_MAXSANITYBUFF_END =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY =

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_HUNT_LOST_TRAIL =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN =
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROE_COOKED =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SHARK_FIN =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BEANBUGS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BEANBUGS_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_GUMMYBUG = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_GUMMYBUG_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WHEAT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WHEAT_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FLOUR = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SPOTSPICE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SAP = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SAP_SPOILED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SYRUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COFFEEBEANS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COFFEEBEANS_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COFFEEBUSH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_KYNO_SPOTBUSH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SPOTBUSH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SPOTSPICE_LEAF = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MUSSEL = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MUSSEL_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_KYNO_COFFEEBUSH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HUMANMEAT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HUMANMEAT_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HUMANMEAT_DRIED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.COFFEE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BISQUE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYOPOP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKFINSOUP =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TROPICALBOUILLABAISSE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSSELBOUILLABAISE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWEETPOTATOSOUFFLE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.FEIJOADA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GUMMY_CAKE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.HARDSHELL_TACOS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICEDTEA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.NETTLELOSANGE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SNAKEBONESOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.STEAMEDHAMSANDWICH =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUBBLETEA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRENCHONIONSOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SLAW = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOTUSBOWL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.POI = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYBEAN_HUNGER = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYBEAN_SUPER = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.JELLYBEAN_SANITY = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOWLOFGEARS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LONGPIGMEAL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUCUMBERSALAD = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WILDWHEAT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_KYNO_WILDWHEAT =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEALGRINDER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_BREAD = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_SWEET_CHIPS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_VEGETABLE_SOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_JELLY_SANDWICH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_FISH_STEW = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_MEAT_STEW = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_ONION_CAKE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_POTATO_PANCAKES = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_POTATO_SOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_FISHBALL_SKEWERS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_MEAT_SKEWERS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_STONE_SOUP =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CROQUETTE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_ROAST_VEGETABLES = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_MEATLOAF = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CARROT_SOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_FISHPIE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_FISHCHIPS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_MEATPIE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_SLIDERS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_JELLY_ROLL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CARROT_CAKE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_GARLICMASHED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_GARLICBREAD = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_TOMATO_SOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_SAUSAGE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CANDIEDFISH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_STUFFEDMUSHROOM = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_BRUSCHETTA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_HAMBURGER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_FISHBURGER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_MUSHROOMBURGER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_FISH_STEAK = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CURRY = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_SPAGHETTI = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_POACHEDFISH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_SHEPHERD_PIE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CANDY = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_BREAD_PUDDING = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_BERRY_TART = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_MACARONI = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_BAGEL_AND_FISH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_GRILLED_CHEESE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CREAMMUSHROOM = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_MANICOTTI = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CHEESEBURGER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_FETTUCCINE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_ONION_SOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_BREADED_CUTLET = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CREAMY_FISH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_PIZZA =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_POT_ROAST = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CRAB_CAKE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_STEAK_FRITES = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_SHOOTER_SANDWICH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_BACON_WRAPPED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CRAB_ROLL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_MEAT_WELLINGTON = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CRAB_RAVIOLI = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CARAMEL_CUBE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_SCONE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_TRIFLE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GORGE_CHEESECAKE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUCKYOUGLERMZ = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ALOE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ALOE_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ALOE_GROUND = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ALOE_SEEDS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_KYNO_ALOE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ALOE_OVERSIZED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RADISH = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RADISH_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RADISH_GROUND = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RADISH_SEEDS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_KYNO_RADISH = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RADISH_OVERSIZED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FENNEL = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FENNEL_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FENNEL_GROUND = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FENNEL_SEEDS =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_KYNO_FENNEL = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FENNEL_OVERSIZED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SWEETPOTATO = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SWEETPOTATO_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SWEETPOTATO_GROUND = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PARZNIP = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PARZNIP_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PARZNIP_EATEN = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PARZNIP_GROUND = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PARZNIP_BIG = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PARZNIP_SEEDS =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PARZNIP_OVERSIZED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TURNIP =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TURNIP_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TURNIP_GROUND =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TURNIP_SEEDS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_KYNO_TURNIP = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TURNIP_OVERSIZED =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RICE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RICE_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RICE_SEEDS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_KYNO_RICE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RICE_OVERSIZED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEEDS_KIT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LOTUS_OCEAN = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LOTUS_FLOWER = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEAWEEDS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEAWEEDS_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEAWEEDS_DRIED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SEAWEEDS_ROOT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LIMPETROCK = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LIMPETS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_LIMPETS_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TAROROOT_OCEAN =
 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TAROROOT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TAROROOT_COOKED =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CUCUMBER = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CUCUMBER_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CUCUMBER_GROUND = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CUCUMBER_SEEDS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WATERYCRESS_OCEAN =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WATERYCRESS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERYCRESSBOWL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SALT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MUSSELSTICK_ITEM =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CATFOOD = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KATFOOD = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BANANATREE =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BANANA = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BANANA_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_KOKONUTTREE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_KOKONUT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_KOKONUT_HALVED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_KOKONUT_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOWLOFPOPCORN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.FIGJUICE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUTWATER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.EYEBALLSPAGHETTI = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.FORGETMELOTS_SEEDS =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.FIRENETTLES_SEEDS =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TILLWEED_SEEDS =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FLOATILIZER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TWIGGYNUTS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_REPAIRTOOL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_KOI = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_KOI_COOKED =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TROPICALFISH = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TROPICALFISH_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEONFISH = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NEONFISH_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_GROUPER = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_GROUPER_COOKED =
 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIERROTFISH = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIERROTFISH_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SALMONFISH = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SALMONFISH_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SALTRACK_INSTALLER = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_SALTRACK_FAIL =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_PINKPARK = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_STONECITY = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_RAINFOREST = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_FIELDS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_JUNGLE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TIDALMARSH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_SAPBUCKET_FAIL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SUGARTREE_BUD = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SUGARTREE_FLOWER =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SUGARTREE_PETALS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CRABTRAP_INSTALLER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PEBBLECRAB =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CRABMEAT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CRABMEAT_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CRABMEAT_DRIED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CRABKINGMEAT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SLAUGHTERTOOL = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_PIGELDER_FAIL = 

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_SUGARTREE_TOOSMALL = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_PIKOTREE_TOOSMALL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CHICKEN2 = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CHICKEN_EGG = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_KIT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_SYRUP = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_BIG_POT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_BIG = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_SMALL_POT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_SMALL = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_GRILL = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_ELDER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_CASSEROLE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_OVEN = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE =
 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_FIREPITINSTALL_FAIL = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_POTHANGER_FAIL = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_CASSEROLE_FAIL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCKFLIPPABLE =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ROCKFLIPPABLE_CAVE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SERENITYISLAND_CRATE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SUGARFLY = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SUGARFLYWINGS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WATERY_CRATE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TUNACAN = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TUNACAN_OPEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CANNEDFOOD = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CANNEDFOOD_OPEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_POP = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MYSTERYMEAT =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BOTTLE_SOUL = 
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_OPENBOTTLESOUL_FAIL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SOULSTEW = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.FORTUNECOOKIE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.HORNOCUPIA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHEESE_YELLOW = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHEESE_WHITE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHEESE_KOALEFANT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MILK_BOX = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WATERCUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.HONEYJAR = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRAB_ARTICHOKE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PEPPERROLLS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SAPHEALER =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_OCEAN_WRECK = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_GHOST_PIRATE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BUCKET_EMPTY = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BUCKET_METAL =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BUCKET_WATER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MILK_BEEFALO = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MILK_KOALEFANT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_CAP_DRIED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PLANTMEAT_DRIED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIGSKIN_DRIED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BREWBOOK = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WOODENKEG = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PRESERVESJAR = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ANTCHEST = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_NECTAR_POD = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_TREE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_OAKTREE_POD = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_OAKTREE_POD_COOKED =
 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIKO = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PIKO_ORANGE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_CRATE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_SELLER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SAMMYHAT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_POND = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KINGFISHER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOUCAN = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOUCAN_CHUBBY =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WETGOOP2 = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BEER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PALEALE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEAGREEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEARED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEAD = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JELLY = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MAYONNAISE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TARTARSAUCE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PICKLES = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WINE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JUICE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_POISON_FROGLEGS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONFROGGLEBUNWICH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BREWINGRECIPECARD =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_OIL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BERRYSUNDAE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHOCOLATE_BLACK = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHOCOLATE_WHITE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRICOLORDANGO =
 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRIESFRENCH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIRATERUM = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TWISTEDTEQUILA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONSTERMEATBALLS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DONUTS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.ONIONRINGS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DONUTS_CHOCOLATE_BLACK =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DONUTS_CHOCOLATE_WHITE =
 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CINNAMONROLL =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GUMMYBEARGERS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PRETZEL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CORNINCUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.COTTONCANDY = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROASTEDHAZELNUTS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONSTERMUFFIN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PINKCAKE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHIPSBAG = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LITTLEBREAD = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.HOTHOUND = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MILKSHAKE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MILKSHAKE_PRISMATIC = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.NACHOS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BANANA_PUDDING = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEA_PUDDING = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOM_KHA_SOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MINERTREAT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.RADISHSALAD = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PUMPKIN_SOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALGAE_SOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PARZNIP_SOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.NETTLEMEATED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SUGAR = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BOTTLECAP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.NUKACOLA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.NUKACOLA_QUANTUM = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIVINGSANDWICH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DURIANSPLIT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DURIANSOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUNARSOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PURPLEWOBSTERSOUP = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOBSTERMONSTER =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DURIANMEATED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DURIANCHICKEN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIDERCAKE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUGARBOMBS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BERRYBOMBS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.ONIGIRIS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.OMURICE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PAELLA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.RISOTTO = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.RICESAKE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PINEAPPLEBUSH = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PINEAPPLE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PINEAPPLE_HALVED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PINEAPPLE_COOKED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIZZA_TROPICAL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PINACOLADA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHIMAS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_GARDEN_SPRINKLER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FOODSACK = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GUMMYWORMS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SMORES = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.STRAWBERRYGRINDER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.NUKASHINE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTSLOG = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WORM_BONE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOOKY_BRAIN_NOODLES =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOOKY_BURGERZILLA = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOOKY_DEADBREAD = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOOKY_JELLYBEANS = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOOKY_POPSICLE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOOKY_PUMPKINCREAM = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOOKY_SKULLCANDY = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOOKY_TACODILE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUTTER_BEEFALO = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUTTER_GOAT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BUTTER_KOALEFANT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICE_CURE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICE_COLD = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICE_FIRE = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICE_FED = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPICE_MIND = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUGARFLYMUFFIN = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.EELTACOS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEATSKILLET = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MEATWALTZ = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.COMPLETEBREAKFAST = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUMPLINGS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WARLYICEDTEA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WARLYTEA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TEALEAF = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ITEMSLICER = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ITEMSLICER_GOLD = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.COXINHA =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAZYDESSERT = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRABKINGFEAST = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PIENAPPLE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.JAWSBREAKER = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.AVOCADOTOAST = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.RICEPUDDING = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKSUSHI = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOBSTERBREADED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAZYPURRITO = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.HORCHATA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOBSTERCOCKTAIL = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAEEGGBOILED = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.POMEGRANATETEA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TIRAMISU = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOADSTOOLCOLA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TEPACHE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUNARTEQUILA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MIMICMOSA = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.POMEGRANATEPIE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PINEAPPLECAKE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.PASTY_MEAT = 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PASTY_CHEESE = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BRIGADEIRO = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.REGULARLASAGNA =
 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TRUFFLES = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLTSANDWICH = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.RICEANDBEANS = 

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TRUFFLES_GROUND =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TRUFFLES =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_TRUFFLES_COOKED =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ITEMSHOWCASER =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SPORECAP =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SPORECAP_COOKED =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SPORECAP_DARK =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SPORECAP_DARK_COOKED =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_GOLDENAPPLE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRUFFLESGRINDER =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPORECAPPIE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPORECAP_SKEWERS =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRUFFLEOIL =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FISHFARMPLOT_KIT =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FISHFARMPLOT =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ANTCHOVY =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_ANTCHOVY_SPAWNER =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.AGEDROE =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.AGEDROE_OCEANFISH_STURGEON =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SWORDFISH_BLUE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JELLYFISH =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JELLYFISH_DEAD =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JELLYFISH_COOKED =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JELLYFISH_DRIED =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JELLYFISH_RAINBOW =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_OCEANTRAP =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_PUFFERFISH =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANFISH_STURGEON =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SWORDFISH =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SWORDFISH_DEAD =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SWORDFISHFEAST =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DOGFISH =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_DOGFISH_DEAD =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_SPOILED_FISH_LARGE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOBSTER_MONKEYISLAND =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PUFFERMONSTER =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WHALE_BLUE_OCEAN =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WHALE_WHITE_OCEAN =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BLUBBER =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_FISHMEAT_DRIED =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEYISLANDMEAL =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BRAINROCK_LARVAE =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BRAINROCK_NUBBIN =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BRAINROCK_CORAL =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_BRAINROCK_ROCK =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BRAINMETTERSOUP =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_OCTOPUSKING_OCEAN =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_PACKIMBAGGIMS =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE =
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE =

STRINGS.CHARACTERS.GENERIC.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN =