-- Common Dependencies.
-- local _G      = GLOBAL
-- local require = _G.require
-- local STRINGS = _G.STRINGS

-- Datas. (Unused)
STRINGS.SCRAPBOOK.DATA_BREWER = "CAN PREPARE DRINK"
STRINGS.SCRAPBOOK.FOODTYPE.PREPAREDPOOP = "HORRIBLE"
STRINGS.SCRAPBOOK.FOODTYPE.PREPAREDSOUL = "SOUL"
STRINGS.SCRAPBOOK.FOODTYPE.ALCOHOLIC = "ALCOHOLIC"

-- Categories.
STRINGS.SCRAPBOOK.CATS.ARTISAN = "Artisan\nGoods"

-- Sub Categories.
STRINGS.SCRAPBOOK.SUBCATS.CHICKEN = "Chicken"
STRINGS.SCRAPBOOK.SUBCATS.PIKO = "Piko"
STRINGS.SCRAPBOOK.SUBCATS.CANNED = "Canned"
STRINGS.SCRAPBOOK.SUBCATS.COOKWARE = "Cookware"
STRINGS.SCRAPBOOK.SUBCATS.SEASONALFOOD = "Seasonal Food"
STRINGS.SCRAPBOOK.SUBCATS.ARTISANGOODS = "Artisan Goods"
STRINGS.SCRAPBOOK.SUBCATS.WINE = "Wine"
STRINGS.SCRAPBOOK.SUBCATS.JUICE = "Juice"
STRINGS.SCRAPBOOK.SUBCATS.JAM = "Jam"
STRINGS.SCRAPBOOK.SUBCATS.PICKLES = "Pickles"

-- Food Effects.
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SPEED = "Increased movement speed for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_COFFEE = "Increased movement speed and sleep resistance for a certain amount of time. Briefly increases the temperature.\n\nHasta la vista, baby!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SLEEP = "Increased sleep resistance for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HEALTHREGEN = "Gives off health regeneration for a short period."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HUNGERREGEN = "Gives off hunger regeneration for a short period."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SANITYREGEN = "Gives off sanity regeneration for a short period."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SUPERREGEN = "Gives off super body regeneration for a short period."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WORMLIGHT = "Gives off a healthy glow for a short period."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ALCOHOL = "Increased damage and decreased movement speed for a certain amount of time. Drink in moderation."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ALCOHOL2 = "Increased damage resistance and decreased movement speed for a certain amount of time. Drink in moderation."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_RUM = "Increased damage against pirates for a certain amount of time.\n\nNeither the flames nor the depths could claim me."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_TEQUILA = "Teleports the survivor to a random location in the map."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKACOLA = "The unique taste of Nuka-Cola is the result of a combination of seventeen fruit essences, balanced to enhance the classic cola flavor. Zap that thirst!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_QUANTUM = "The unique taste of Nuka-Cola is the result of a combination of seventeen fruit essences, balanced to enhance the classic cola flavor. Zap that thirst!\n\nNuka-Cola Quantum has twice the calories, twice the carbohydrates, twice the caffeine, and twice the taste!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_INSANITY = "Indulces insanity for a short period."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NIGHTVISION = "Gives off night vision for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NAUGHTY = "Eating this food made with parts from a poor and innocent soul will cause \"Him\" to spawn nearby."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HASTE = "Increased speed for all performed actions for a certain amount of time. Winona does not benefit from this effect."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BLOOM = "A mix of composts thrown together in a cooking pot that can estimulate bloomness to its maximum potentital.\n\n\"Art!\" - Wormwood."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SOUL = "A special food made with a harvested Soul.\n\nWortox can eat this food to gain the full benefits of it with no penalties unlike other mundane foods."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_DEERCLOPS = "Eating this food will cause Deerclops to spawn nearby."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BEARGER = "Eating this food will cause Bearger to spawn nearby."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FORTUNE = "Crack one to see what the destiny has reserved for you."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WATER = "Cleanses all the current active food effects of the survivor."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FROG = "Eating this food will make all Frogs friendly towards your for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_CURSE = "Woodie can eat this food to force one of his transformations chosen randomly."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FEARLESS = "This food can make a survivor be fearless for a certain amount of time. Insanity auras will have no effect during this period."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MONSTERFOOD = "Webber can eat this food without any penalties."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WURTFOOD = "Wurt will gain extra benefits from eating this food."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLAYERMONSTER = "Webber can eat this food without any penalties.\nWurt will gain extra benefits from eating this food."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SPIDERCAKE = "Webber can eat this food without any penalties.\n\nDon't Starve Together x Cult of the Lamb - Collab 2023."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SUGARBOMBS = "A pack of sugary cereal that holds 100% of the recommended daily amount of sugar, Sugar Bombs have been preserved for 25 years after the Great War. However, this also caused a bit of radiation to slip in for most of them."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKASHINE = "Nukashine was created by Lewis of the Eta Psi fraternity at Vault-Tec University in November 2076. The spirit itself is incredibly potent, causes blackouts, severe hangovers, and is potentially lethal, as the fellow Pi Mu fraternity found out during their \"eviction party.\"\n\nA sugar-free version also existed, with the lack of sugar allowing the beverage to be consumed without any risk of blackouts."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKASHINE2 = "Now without any risk of blackouts! Enjoy the party!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BONESOUP = "Increased damage against worms for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_REVIVER = "Instantly revives a dead player when haunted."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MOCHA = "Increased movement speed, sleep resistance and decreased hunger loss rate for a certain amount of time.\n\nBriefly increases the temperature."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_LESSFREEZING = "Briefly increases temperature and become less susceptible to Freezing."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_LESSOVERHEAT = "Briefly decreases temperature and become less susceptible to Overheat."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FISHING = "Increased fishing yields for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MIGHTNESS = "Gives off a bit of mightness."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_INSPIRATION = "Gives off a bit of inspiration."

-- Items & Foods.
STRINGS.SCRAPBOOK.SPECIALINFO.SALT = "Using a pinch of salt on a crock pot food will refresh its spoilage time by 30%. Don't worry about eating stale dishes again!"
STRINGS.SCRAPBOOK.SPECIALINFO.SALTRACK = "This rack will collect a small rock of salt every few days."
STRINGS.SCRAPBOOK.SPECIALINFO.CRABTRAP = "Once set on the ground, it will trigger when a crab move nearby, capturing them.\n\nCollecting a captured trap will put the creature inside your inventory.\n\nCrab Traps can be baited with meats."
STRINGS.SCRAPBOOK.SPECIALINFO.CARAMELCUBE = "This dish is a delicacy, a solid block of pure sweetness and love. It's a special entry for someone with sugar addiction, very, very popular with elderly folk."
STRINGS.SCRAPBOOK.SPECIALINFO.NECTAR = "Bees that have pollinated enough flowers will drop nectar when killed.\n\nNectar will be transformed into honey when stored the Honey Deposit."
STRINGS.SCRAPBOOK.SPECIALINFO.BOTTLESOUL = "A bottled Soul doesn't count towards the total amount inside Wortox's inventory."
STRINGS.SCRAPBOOK.SPECIALINFO.BOTTLECAP = "Durable, portable, and instantly recognizable bottle caps from the Nuka-Cola Corporation!"
STRINGS.SCRAPBOOK.SPECIALINFO.CANNEDFOOD = "A remarkable source of emergency food. It will never perish unless you open it!"
STRINGS.SCRAPBOOK.SPECIALINFO.BREWBOOK = "A record of all the beverages brewed and/or drank, as well as the ingredients used to brew them."
STRINGS.SCRAPBOOK.SPECIALINFO.BUCKET = "A bucket can be used to gather milk from animals.\n\nBe careful because some of them might get angry when you try to do it. Remember to always wear safety clothing.\n\nIt's easier to get milk from domesticated animals as they yield more units."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_HANGER_ITEM = "This hanger can be installed above Fire Pits to hold cooking pots."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_POT_ITEM = "This cooking pot requires a hanger placed above Fire Pits."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_OVEN_ITEM = "This oven can be installed on Fire Pits to place casserole dishes inside."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_CASSEROLE_ITEM = "This casserole dish requires an oven placed on Fire Pits."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_GRILL_ITEM = "This grill can be installed on Fire Pits to prepare foods."
STRINGS.SCRAPBOOK.SPECIALINFO.HUMANMEAT = "The campaign can wait, for now carnage calls.\n\nLog Ping can be harvested from the corpses of your fellow survivors."
STRINGS.SCRAPBOOK.SPECIALINFO.MUSSELSTICK_ITEM = "Can be placed in the water to catch mussels over time."
STRINGS.SCRAPBOOK.SPECIALINFO.REPAIRTOOLKIT = "Used to repair destroyed structures."
STRINGS.SCRAPBOOK.SPECIALINFO.SAPBUCKET = "Tap it to Sugarwood Trees to produce fresh Sap every few days."
STRINGS.SCRAPBOOK.SPECIALINFO.SLAUGHTERTOOL = "Butchering tools that instantly kills the animal."
STRINGS.SCRAPBOOK.SPECIALINFO.SAPHEALER = "Powerful antidote with healing capabilities for trees.\n\nUsing it on Ruined Sugarwood Trees will revert them back to their normal stage."

-- Creatures.
STRINGS.SCRAPBOOK.SPECIALINFO.FEEDCHICKEN = "Can be feed with seeds to lay down an egg."
STRINGS.SCRAPBOOK.SPECIALINFO.PIKO = "Fluffy little buddies that loves to steal your most valuable items!"
STRINGS.SCRAPBOOK.SPECIALINFO.KINGFISHER = "Kingfishers will often drop Tropical Kois from above. It's raining fish, literally!"

-- Structures, Misc & Point of Interest.
STRINGS.SCRAPBOOK.SPECIALINFO.PIGELDER = "A Merchant from a distant archipelago. He's willing to trade his best cooking utensils and other useful items for delicious meals.\n\nThe Elder is craving for a meal with extreme sweetness or Butter mescled with seafood. He will reward you accordingly.\n\nBringing Elder's favourtie meal will unlock more trade deals."
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMY = "Looks like someone is moving in to this old and abandoned house. His stuff is scattered all around.\n\nCome back in the next major update and stay tuned for news!"
STRINGS.SCRAPBOOK.SPECIALINFO.SALTPOND = "Ponds rich in salt. Salt Racks can be installed for an easy source of salt rocks every few days."
STRINGS.SCRAPBOOK.SPECIALINFO.MEALGRINDER = "Standing near this device will provide the survivor with new ingredients they can grind.\n\nYou'll need to be near the mealing stone every time you want to grind a new ingredient."
STRINGS.SCRAPBOOK.SPECIALINFO.PIKOTREE = "Standing near a tree offers 35% protection from rain and cools survivor a small amount.\n\nThese Tea Trees are infested with little creatures known as Piko, and they are ready to cause trouble."
STRINGS.SCRAPBOOK.SPECIALINFO.ANTCHEST = "This special chest can only store honey-based items, up to 7 items simultaneously. It also gives off a healthy glow.\n\nIf honey-based foods are stored inside, the chest will refresh their spoilage time as well keep them fresh forever.\n\nNectar stored inside will eventually turn into honey."
STRINGS.SCRAPBOOK.SPECIALINFO.BREWER = "A 3 slot container that will receive ingredients for brewing.\n\nPlacing 3 items in the container will allow them to be brewed creating some kind of food depending on the items put in to begin with.\n\nThis process usually takes some days to finish."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_HANGER = "Use to hold a cooking pot."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_POT = "A 4 slot container that will receive ingredients for food.\n\nPlacing 4 items in the container will allow them to be cooked creating some kind of food depending on the items put to begin with.\n\nThis cooking pot cooks faster than regular ones and also have a chance to yield multiple units of the cooked food."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_SYRUP_POT = "A 4 slot container that will receive ingredients for Syrup.\n\nPlacing 4 Sap in the container will allow them to be cooked creating Syrup.\n\nThis pot can only cook Syrup and always give an extra unit."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_OVEN = "Use to place a casserole dish inside."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_CASSEROLE = "A 4 slot container that will receive ingredients for food.\n\nPlacing 4 items in the container will allow them to be cooked creating some kind of food depending on the items put to begin with.\n\nThis cooking pot cooks faster than regular ones and also have a chance to yield multiple units of the cooked food."
STRINGS.SCRAPBOOK.SPECIALINFO.KOKONUTTREE = "Standing near a tree offers 35% protection from rain and cools survivor a small amount.\n\nBe aware of falling Coconuts!"
STRINGS.SCRAPBOOK.SPECIALINFO.MUSSELSTICK = "This stick is irresistible to mussels, leave it be for a while and it will be filled with mussels for you to collect."
STRINGS.SCRAPBOOK.SPECIALINFO.MUSHSTUMP = "This stump has a special kind of fungus growing considered by many as a delicacy.\n\nIt takes nearly 5 days for it to grow."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE = "Standing near a tree offers 35% protection from rain and cools survivor a small amount.\n\nThese trees can be tapped using a Tree Tapping Kit to produce fresh Sap every few days."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_SAPPED = "Standing near a tree offers 35% protection from rain and cools survivor a small amount.\n\nIt takes nearly 3 days to produce Sap.\n\nDon't let the Sap overflow otherwise it will become ruined."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_RUINED = "Standing near a tree offers 35% protection from rain and cools survivor a small amount.\n\nRuined Sugarwood Trees can't produce fresh Sap, they will produce Ruined Sap instead.\n\nYou can heal ruined trees using a Musty Antidote."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_RUINED2 = "Standing near a tree offers 35% protection from rain and cools survivor a small amount.\n\nYou can heal ruined trees using a Musty Antidote."
STRINGS.SCRAPBOOK.SPECIALINFO.RUBBLE = "Elder wants your help to repair his Old Pot so he can start making delicious Syrup again."
STRINGS.SCRAPBOOK.SPECIALINFO.PINEAPPLEBUSH = "Pineapple Bushes takes nearly 6 days to fully grow. They take longer to grow in all seasons except for Summer.\n\nDuring Summer they will start growing every 2 days."
STRINGS.SCRAPBOOK.SPECIALINFO.GARDENSPRINKLER = "Can be turned on and off. While fueled and on, will automatically water farm plants within its range."