-- Common Dependencies.
-- local _G      = GLOBAL
-- local require = _G.require
-- local STRINGS = _G.STRINGS

-- Datas. (Unused)
STRINGS.SCRAPBOOK.DATA_BREWER = "PUEDE PREPARAR BEBIDA"
STRINGS.SCRAPBOOK.FOODTYPE.PREPAREDPOOP = "HORRIBLE"
STRINGS.SCRAPBOOK.FOODTYPE.PREPAREDSOUL = "ALMA"
STRINGS.SCRAPBOOK.FOODTYPE.ALCOHOLIC = "ALCOHÓLICO"

-- Categorías.
STRINGS.SCRAPBOOK.CATS.ARTISAN = "Productos\nArtesanales"

-- Subcategorías.
STRINGS.SCRAPBOOK.SUBCATS.CHICKEN = "Pollo"
STRINGS.SCRAPBOOK.SUBCATS.PIKO = "Piko"
STRINGS.SCRAPBOOK.SUBCATS.CANNED = "Enlatados"
STRINGS.SCRAPBOOK.SUBCATS.COOKWARE = "Utensilios de Cocina"
STRINGS.SCRAPBOOK.SUBCATS.SEASONALFOOD = "Comida Estacional"
STRINGS.SCRAPBOOK.SUBCATS.ARTISANGOODS = "Productos Artesanales"
STRINGS.SCRAPBOOK.SUBCATS.WINE = "Vino"
STRINGS.SCRAPBOOK.SUBCATS.JUICE = "Jugo"
STRINGS.SCRAPBOOK.SUBCATS.JAM = "Mermelada"
STRINGS.SCRAPBOOK.SUBCATS.PICKLES = "Encurtidos"

-- Efectos de la comida.
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SPEED = "Aumenta la velocidad de movimiento por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_COFFEE = "Aumenta la velocidad de movimiento y la resistencia al sueño por un tiempo determinado. Incrementa brevemente la temperatura.\n\n¡Hasta la vista, baby!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SLEEP = "Aumenta la resistencia al sueño por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HEALTHREGEN = "Proporciona regeneración de salud durante un breve periodo."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HUNGERREGEN = "Proporciona regeneración de hambre durante un breve periodo."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SANITYREGEN = "Proporciona regeneración de cordura durante un breve periodo."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SUPERREGEN = "Proporciona regeneración corporal superior durante un breve periodo."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WORMLIGHT = "Proporciona un resplandor saludable durante un breve periodo."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ALCOHOL = "Aumenta el daño y disminuye la velocidad de movimiento por un tiempo determinado. Bebe con moderación."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ALCOHOL2 = "Aumenta la resistencia al daño y disminuye la velocidad de movimiento por un tiempo determinado. Bebe con moderación."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_RUM = "Aumenta el daño contra piratas por un tiempo determinado.\n\nNi las llamas ni las profundidades podrían reclamarme."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_TEQUILA = "Teletransporta al superviviente a una ubicación aleatoria en el mapa."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKACOLA = "El sabor único de Nuka-Cola es el resultado de la combinación de diecisiete esencias de frutas, equilibradas para realzar el sabor clásico de la cola. ¡Calma esa sed!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_QUANTUM = "El sabor único de Nuka-Cola es el resultado de la combinación de diecisiete esencias de frutas, equilibradas para realzar el sabor clásico de la cola. ¡Calma esa sed!\n\n¡Nuka-Cola Quantum tiene el doble de calorías, carbohidratos, cafeína y sabor!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_INSANITY = "Provoca locura durante un breve periodo."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NIGHTVISION = "Proporciona visión nocturna por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NAUGHTY = "Comer este alimento hecho con partes de un alma pobre e inocente hará que \"Él\" aparezca cerca."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HASTE = "Aumenta la velocidad de todas las acciones realizadas por un tiempo determinado. Winona no se beneficia de este efecto."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BLOOM = "Una mezcla de compost lanzada en una olla de cocina que puede estimular la floración al máximo potencial.\n\n\"¡Arte!\" - Wormwood."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SOUL = "Un alimento especial hecho con un Alma recolectada.\n\nWortox puede comer este alimento para obtener todos sus beneficios sin penalizaciones, a diferencia de otros alimentos comunes."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_DEERCLOPS = "Comer este alimento hará que Deerclops aparezca cerca."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BEARGER = "Comer este alimento hará que Bearger aparezca cerca."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FORTUNE = "Ábrelo para ver lo que el destino te tiene reservado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WATER = "Elimina todos los efectos secundarios de alimentos activos del superviviente.\nDisminuye brevemente la temperatura."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FROG = "Comer este alimento hará que todas las ranas sean amigables contigo durante un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_CURSE = "Woodie puede comer este alimento para forzar una de sus transformaciones elegida aleatoriamente."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FEARLESS = "Este alimento puede hacer que un superviviente sea intrépido por un tiempo determinado. Las auras de locura no tendrán efecto durante este periodo."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MONSTERFOOD = "Webber puede comer este alimento sin ninguna penalización."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MONSTERFOOD2 = "Webber puede comer este alimento sin ninguna penalización.\nIncrementa brevemente la temperatura."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WURTFOOD = "Wurt obtendrá beneficios adicionales al comer este alimento."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLAYERMONSTER = "Webber puede comer este alimento sin penalizaciones.\nWurt obtendrá beneficios adicionales al comerlo."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLAYERMONSTER2 = "Webber puede comer este alimento sin penalizaciones.\nWurt obtendrá beneficios adicionales al comerlo.\nDisminuye brevemente la temperatura."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLAYERMONSTER3 = "Webber puede comer este alimento sin penalizaciones.\nWurt obtendrá beneficios adicionales al comerlo.\nIncrementa brevemente la temperatura."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SPIDERCAKE = "Webber puede comer este alimento sin penalizaciones.\n\nDon't Starve Together x Cult of the Lamb - Colaboración 2023."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SUGARBOMBS = "Un paquete de cereales azucarados que contiene el 100% de la cantidad diaria recomendada de azúcar. Las Sugar Bombs se han conservado durante 25 años después de la Gran Guerra. Sin embargo, esto también causó que algo de radiación se filtrara en la mayoría de ellas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKASHINE = "Nukashine fue creado por Lewis de la fraternidad Eta Psi en la Universidad Vault-Tec en noviembre de 2076. El espíritu en sí es increíblemente potente, causa desmayos, resacas severas y puede ser letal, como descubrió la fraternidad Pi Mu durante su \"fiesta de desalojo\".\n\nTambién existía una versión sin azúcar, que permitía consumirla sin riesgo de desmayos."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKASHINE2 = "¡Ahora sin riesgo de desmayos! ¡Disfruta la fiesta!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BONESOUP = "Aumenta el daño contra gusanos por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_REVIVER = "Revive instantáneamente a un jugador muerto cuando está encantado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MOCHA = "Aumenta la velocidad de movimiento, la resistencia al sueño y disminuye la pérdida de hambre por un tiempo determinado.\n\nIncrementa brevemente la temperatura."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_LESSFREEZING = "Incrementa brevemente la temperatura y reduce la susceptibilidad a la congelación."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_LESSOVERHEAT = "Disminuye brevemente la temperatura y reduce la susceptibilidad al sobrecalentamiento."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FISHING = "Aumenta la pesca por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MIGHTINESS = "Incrementa ligeramente la fuerza."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_INSPIRATION = "Incrementa ligeramente la inspiración."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WARLYTEA = "Disminuye la pérdida de cordura por un tiempo determinado.\nIncrementa brevemente la temperatura."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_INCREASETEMP = "Incrementa brevemente la temperatura."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_DECREASETEMP = "Disminuye brevemente la temperatura."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BOUILLABAISSE = "Aumenta la resistencia al sueño por un tiempo determinado.\nDisminuye brevemente la temperatura."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MOISTURE = "Seca al superviviente y le otorga inmunidad a la humedad por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SUGARBOMBS_EXPLOSIVE = "¡Estas Sugar Bombs están llenas de un sabor explosivo!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_EATER = "Hace que la comida sea más suave y fácil de comer por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_CRABKINGFEAST = "Aumenta el daño contra cangrejos por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ANTLION = "Satisface al Antlion por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_JAWSBREAKER = "Atrae y mata Rockjaws y Gnarwails cuando se lanza al océano. No funciona si está demasiado cerca."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FIREIMMUNITY = "Este alimento puede hacer que un superviviente sea inmune al fuego por un tiempo determinado. Incrementa brevemente la temperatura."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_TIRAMISU = "Aumenta la velocidad de movimiento por un tiempo determinado.\n\nSeca al superviviente y le otorga inmunidad a la humedad por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_AMPHIBIAN = "Aumenta el daño contra anfibios por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ENLIGHTENMENT = "Ilumina al superviviente por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_STEALTH = "Hace que el superviviente sea invisible e indetectable para trampas y criaturas por un tiempo determinado."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLANARDEFENSE = "Aumenta la defensa planar por un tiempo determinado."

-- Efectos de las especias.
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_CURE = "Se puede agregar a la comida de la Olla de Cocina usando una Estación de Condimentos Portátil.\n\nComer un plato sazonado con Polvo Conservador reduce a la mitad el tiempo de descomposición y anula las penalizaciones por comida en mal estado."
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_MIND = "Se puede agregar a la comida de la Olla de Cocina usando una Estación de Condimentos Portátil.\n\nComer un plato sazonado con Azúcar Calmante otorga un 25% más de cordura."
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_FED = "Se puede agregar a la comida de la Olla de Cocina usando una Estación de Condimentos Portátil.\n\nComer un plato sazonado con Almidón Relleno otorga un 25% más de hambre."
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_FIRE = "Se puede agregar a la comida de la Olla de Cocina usando una Estación de Condimentos Portátil.\n\nComer un plato sazonado con Cristales de Llama hace que tus ataques enciendan a los objetivos.\n\nDuración: 4 minutos.\n\nTambién aumenta la temperatura 15 grados durante 15 segundos."
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_COLD = "Se puede agregar a la comida de la Olla de Cocina usando una Estación de Condimentos Portátil.\n\nComer un plato sazonado con Copos Congelados hace que tus ataques congelen a los objetivos.\n\nDuración: 4 minutos.\n\nTambién disminuye la temperatura 15 grados durante 15 segundos."

-- Ítems y Comidas.
STRINGS.SCRAPBOOK.SPECIALINFO.SALT = "Usar una pizca de sal en la comida de la Olla de Cocina refrescará su tiempo de descomposición en un 30%. ¡No te preocupes por comer platos pasados otra vez!"
STRINGS.SCRAPBOOK.SPECIALINFO.SALTRACK = "Este estante recolectará un pequeño trozo de sal cada pocos días."
STRINGS.SCRAPBOOK.SPECIALINFO.CRABTRAP = "Una vez colocada en el suelo, se activará cuando un cangrejo se acerque, capturándolo.\n\nRecoger una trampa capturada pondrá a la criatura dentro de tu inventario.\n\nLas trampas de cangrejo pueden cebarse con carnes."
STRINGS.SCRAPBOOK.SPECIALINFO.CARAMELCUBE = "Este plato es una delicadeza, un bloque sólido de pura dulzura y amor. Es una entrada especial para alguien con adicción al azúcar, muy, muy popular entre los ancianos."
STRINGS.SCRAPBOOK.SPECIALINFO.NECTAR = "Las abejas que han polinizado suficientes flores soltarán néctar al ser eliminadas.\n\nEl néctar se transformará en miel cuando se almacene en el Depósito de Miel."
STRINGS.SCRAPBOOK.SPECIALINFO.BOTTLESOUL = "Un Alma embotellada no cuenta para el total dentro del inventario de Wortox."
STRINGS.SCRAPBOOK.SPECIALINFO.BOTTLECAP = "Tapas de botella duraderas, portátiles e instantáneamente reconocibles de la Corporación Nuka-Cola."
STRINGS.SCRAPBOOK.SPECIALINFO.CANNEDFOOD = "Una fuente notable de comida de emergencia. ¡Nunca se echará a perder a menos que la abras!"
STRINGS.SCRAPBOOK.SPECIALINFO.BREWBOOK = "Registro de todas las bebidas elaboradas y/o consumidas, así como de los ingredientes usados para prepararlas."
STRINGS.SCRAPBOOK.SPECIALINFO.BUCKET = "Un balde puede usarse para recolectar leche de los animales.\n\nTen cuidado, porque algunos pueden enfadarse al intentarlo. Recuerda siempre usar ropa de seguridad.\n\nEs más fácil obtener leche de animales domesticados, ya que producen más unidades y no te hacen daño."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_HANGER_ITEM = "Este colgador puede instalarse sobre Fogatas para sostener ollas de cocina."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_POT_ITEM = "Esta olla requiere un colgador colocado sobre Fogatas."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_OVEN_ITEM = "Este horno puede instalarse sobre Fogatas para colocar platos de cazuela dentro."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_CASSEROLE_ITEM = "Este plato de cazuela requiere un horno colocado sobre Fogatas."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_GRILL_ITEM = "Esta parrilla puede instalarse sobre Fogatas para preparar alimentos."
STRINGS.SCRAPBOOK.SPECIALINFO.HUMANMEAT = "La campaña puede esperar, por ahora el carnicería llama.\n\nSe puede recolectar Ping de los cadáveres de tus compañeros supervivientes."
STRINGS.SCRAPBOOK.SPECIALINFO.MUSSELSTICK_ITEM = "Puede colocarse en el agua para atrapar mejillones con el tiempo."
STRINGS.SCRAPBOOK.SPECIALINFO.REPAIRTOOLKIT = "Se usa para reparar estructuras destruidas."
STRINGS.SCRAPBOOK.SPECIALINFO.SAPBUCKET = "Conéctalo a los Árboles de Azúcar para producir Savia fresca cada pocos días."
STRINGS.SCRAPBOOK.SPECIALINFO.SLAUGHTERTOOL = "Herramientas de matanza que eliminan al animal al instante."
STRINGS.SCRAPBOOK.SPECIALINFO.SAPHEALER = "Antídoto poderoso con capacidades curativas para árboles.\n\nUsarlo en Árboles de Azúcar Arruinados los revertirá a su estado normal."
STRINGS.SCRAPBOOK.SPECIALINFO.ITEMSLICER = "Para cortar trozos de carne y otras cosas."
STRINGS.SCRAPBOOK.SPECIALINFO.ITEMSLICER2 = "Para cortar trozos de carne y otras cosas, ¡más rápido!"
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMYHAT = "Reduce el hambre en un 15%."
STRINGS.SCRAPBOOK.SPECIALINFO.POTATOSACK = "Un contenedor de 6 ranuras que puede almacenar objetos relacionados con la papa y mantenerlos frescos por más tiempo.\n\n\"¡Las papas son fuertes para el estómago!\" - Wolfgang."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODSACK = "Un contenedor impermeable de 8 ranuras que mantiene tus ingredientes frescos sin importar el clima.\n\nSu diseño inteligente no solo ralentiza la descomposición, sino que incluso puede restaurar la frescura de ingredientes que comenzaron a echarse a perder.\n\nLate con un poder mágico helado, congelando todo en su interior."
STRINGS.SCRAPBOOK.SPECIALINFO.BOOK_GARDENING = "Hace crecer rápidamente todo tipo de plantas cercanas.\n\n\"Un tomo antiguo encuadernado en raíces vivas, desterrado por su abrumador poder para doblar la voluntad de la naturaleza. Sus páginas susurran palabras olvidadas que pueden despertar la tierra misma, convirtiendo la simple tierra en un salvaje y vivo desierto.\" - Autor Desconocido."

-- Criaturas.
STRINGS.SCRAPBOOK.SPECIALINFO.FEEDCHICKEN = "Puede alimentarse con semillas para que ponga un huevo."
STRINGS.SCRAPBOOK.SPECIALINFO.PIKO = "Pequeños amigos esponjosos que aman robar tus objetos más valiosos."
STRINGS.SCRAPBOOK.SPECIALINFO.KINGFISHER = "Los martines pescadores a menudo dejarán caer Koi Tropicales desde arriba. ¡Está lloviendo peces, literalmente!"

-- Estructuras, Miscelánea y Puntos de Interés.
STRINGS.SCRAPBOOK.SPECIALINFO.PIGELDER = "Un Comerciante de un archipiélago lejano. Está dispuesto a intercambiar sus mejores utensilios de cocina y otros objetos útiles por comidas deliciosas.\n\nEl Anciano anhela una comida extremadamente dulce o mantequilla mezclada con mariscos. Te recompensará en consecuencia.\n\nLlevar la comida favorita del Anciano desbloqueará más tratos comerciales."
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMY = "Un comerciante de un reino de otro mundo. De alguna manera quedó varado en una de las Islas Constantes y ha construido una tienda para intercambiar mientras tanto.\n\nSammy comercia con una variedad de objetos raros durante las temporadas y en ocasiones especiales. Asegúrate de revisar sus productos de vez en cuando para ver qué tiene para ofrecer.\n\nSammy te recompensará generosamente si le traes un regalo que le recuerde a su hogar."
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMYHOUSE = "El Emporio de Sammy alberga una variedad de objetos extraños y antigüedades de tierras lejanas y reinos de otro mundo."
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMYWAGON = "El preciado carro de Sammy. No dejes que su tamaño te engañe, se pueden almacenar muchas cosas allí."
STRINGS.SCRAPBOOK.SPECIALINFO.SALTPOND = "Estanques ricos en sal. Se pueden instalar estantes de sal para obtener rocas de sal fácilmente cada pocos días."
STRINGS.SCRAPBOOK.SPECIALINFO.MEALGRINDER = "Estar cerca de este dispositivo proporcionará al superviviente nuevos ingredientes que podrá moler.\n\nNecesitarás estar cerca de la piedra de moler cada vez que quieras triturar un nuevo ingrediente."
STRINGS.SCRAPBOOK.SPECIALINFO.PIKOTREE = "Estar cerca de un árbol ofrece un 35% de protección contra la lluvia y refresca ligeramente al superviviente.\n\nEstos Árboles de Té están infestados de pequeñas criaturas conocidas como Piko, y están listas para causar problemas."
STRINGS.SCRAPBOOK.SPECIALINFO.ANTCHEST = "Este cofre especial solo puede almacenar objetos basados en miel, hasta 7 objetos simultáneamente. También emite un resplandor saludable.\n\nSi se almacenan alimentos basados en miel, el cofre renovará su tiempo de descomposición y los mantendrá frescos para siempre.\n\nEl néctar almacenado dentro eventualmente se convertirá en miel."
STRINGS.SCRAPBOOK.SPECIALINFO.BREWER = "Un contenedor de 3 ranuras que recibirá ingredientes para elaborar bebidas.\n\nColocar 3 objetos en el contenedor permitirá elaborarlos, creando algún tipo de alimento según los objetos introducidos.\n\nEste proceso suele tardar algunos días en completarse."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_HANGER = "Usado para sostener una olla de cocina."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_POT_SMALL = "Un contenedor de 3 ranuras que recibirá ingredientes para comida.\n\nColocar 3 objetos en el contenedor permitirá cocinarlos, creando algún tipo de alimento según los objetos introducidos.\n\nEsta olla cocina más rápido que las regulares y produce una unidad extra del alimento cocido."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_POT = "Un contenedor de 4 ranuras que recibirá ingredientes para comida.\n\nColocar 4 objetos en el contenedor permitirá cocinarlos, creando algún tipo de alimento según los objetos introducidos.\n\nEsta olla cocina más rápido que las regulares y produce 2 unidades extra del alimento cocido."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_SYRUP_POT = "Un contenedor de 4 ranuras que recibirá ingredientes para jarabe.\n\nColocar 4 unidades de savia en el contenedor permitirá cocinarlas para crear jarabe.\n\nEsta olla solo puede cocinar jarabe y produce 3 unidades extra."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_OVEN = "Usado para colocar un plato de cazuela dentro."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_CASSEROLE_SMALL = "Un contenedor de 3 ranuras que recibirá ingredientes para comida.\n\nColocar 3 objetos en el contenedor permitirá cocinarlos, creando algún tipo de alimento según los objetos introducidos.\n\nEsta olla cocina más rápido que las regulares y conserva la comida cocida dentro."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_CASSEROLE = "Un contenedor de 4 ranuras que recibirá ingredientes para comida.\n\nColocar 4 objetos en el contenedor permitirá cocinarlos, creando algún tipo de alimento según los objetos introducidos.\n\nEsta olla cocina más rápido que las regulares y conserva la comida cocida dentro."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_GRILL_SMALL = "Un contenedor de 3 ranuras que recibirá ingredientes para comida.\n\nColocar 3 objetos en el contenedor permitirá cocinarlos, creando algún tipo de alimento según los objetos introducidos.\n\nEsta parrilla cocina más rápido que las regulares y siempre produce comida fresca cocida."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_GRILL = "Un contenedor de 4 ranuras que recibirá ingredientes para comida.\n\nColocar 4 objetos en el contenedor permitirá cocinarlos, creando algún tipo de alimento según los objetos introducidos.\n\nEsta parrilla cocina más rápido que las regulares y siempre produce comida fresca cocida."
STRINGS.SCRAPBOOK.SPECIALINFO.KOKONUTTREE = "Estar cerca de un árbol ofrece un 35% de protección contra la lluvia y refresca ligeramente al superviviente.\n\n¡Cuidado con los cocos que caen!"
STRINGS.SCRAPBOOK.SPECIALINFO.MUSSELSTICK = "Este palo es irresistible para los mejillones, déjalo un tiempo y se llenará de mejillones para que los recolectes."
STRINGS.SCRAPBOOK.SPECIALINFO.MUSHSTUMP = "Este tocón tiene un tipo especial de hongo considerado por muchos como una delicadeza.\n\nTarda casi 5 días en crecer."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE = "Estar cerca de un árbol ofrece un 35% de protección contra la lluvia y refresca ligeramente al superviviente.\n\nEstos árboles pueden ser conectados con un Kit de Extracción de Savia para producir savia fresca cada pocos días."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_SAPPED = "Estar cerca de un árbol ofrece un 35% de protección contra la lluvia y refresca ligeramente al superviviente.\n\nTarda casi 3 días en producir savia.\n\nNo dejes que la savia se desborde, de lo contrario se arruinará."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_RUINED = "Estar cerca de un árbol ofrece un 35% de protección contra la lluvia y refresca ligeramente al superviviente.\n\nLos Árboles de Azúcar Arruinados no pueden producir savia fresca, producirán savia arruinada en su lugar.\n\nPuedes curar los árboles arruinados usando un Antídoto Mohoso."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_RUINED2 = "Estar cerca de un árbol ofrece un 35% de protección contra la lluvia y refresca ligeramente al superviviente.\n\nPuedes curar los árboles arruinados usando un Antídoto Mohoso."
STRINGS.SCRAPBOOK.SPECIALINFO.RUBBLE = "El Anciano quiere tu ayuda para reparar su Vieja Olla para que pueda volver a hacer delicioso jarabe."
STRINGS.SCRAPBOOK.SPECIALINFO.PINEAPPLEBUSH = "Los Arbustos de Piña tardan casi 6 días en crecer completamente. Tardan más en todas las estaciones excepto en verano.\n\nDurante el verano comenzarán a crecer cada 2 días."
STRINGS.SCRAPBOOK.SPECIALINFO.GARDENSPRINKLER = "Se puede encender y apagar. Mientras esté encendido y con combustible, regará automáticamente las plantas de la granja dentro de su alcance."