------------------------------------------------------------------------------------------------------------
-- World Generation
------------------------------------------------------------------------------------------------------------

-- WORLDGEN RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES = "알로에"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES = "아스파라거스"
STRINGS.UI.CUSTOMIZATIONSCREEN.CAVETUBERTREES = "동굴 덩이줄기 나무"
STRINGS.UI.CUSTOMIZATIONSCREEN.COFFEEBUSHES = "커피나무"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS = "펜넬"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS = "거대 파스닙"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS = "버섯 밑동"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES = "송로버섯"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS = "파스닙"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES = "무"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES = "납작한 돌"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES = "고구마"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS = "순무"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS = "야생 밀"

-- WORLDGEN OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.BRAINROCKS = "뇌 싹"
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS = "연꽃"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES = "침수된 상자"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS = "난파선"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS = "해삼"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS = "타로"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES = "물냉이"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA = "해초"

-- WORLDGEN SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.SERENITYISLAND = "돼지 장로"
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS = "소금 연못"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES = "향신료 관목"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS = "설탕꽃"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES = "설탕나무"

-- WORLDGEN MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.MEADOWISLAND = "새미"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMHUTS = "낚시꾼 어인 집"
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES = "상자"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES = "야자수"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS = "삿갓조개 바위"
STRINGS.UI.CUSTOMIZATIONSCREEN.MERMHUTS = "어인 집"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOTREES = "피코가 사는 차나무"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES = "파인애플 덤불"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS = "모래 더미"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES = "차나무"
STRINGS.UI.CUSTOMIZATIONSCREEN.TIDALPOOLS = "조수 웅덩이"

-- WORLDGEN CREATURES
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS = "닭"
STRINGS.UI.CUSTOMIZATIONSCREEN.DOGFISHES = "물개기"
STRINGS.UI.CUSTOMIZATIONSCREEN.ELDERMANDRAKES = "고대 맨드레이크"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS = "낚시꾼 어인"
STRINGS.UI.CUSTOMIZATIONSCREEN.HERMITWOBSTERS = "은둔자 왑스터"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES = "해파리"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES2 = "무지개 해파리"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS = "조약돌게"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS = "피코"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE = "오렌지 피코"
STRINGS.UI.CUSTOMIZATIONSCREEN.PUFFERMONSTERS = "퍼퍼노트"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES = "설탕나비"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWORDFISHES = "황새치"

------------------------------------------------------------------------------------------------------------
-- World Settings
------------------------------------------------------------------------------------------------------------

-- GLOBALSETTINGS
STRINGS.UI.CUSTOMIZATIONSCREEN.HOFBIRTHDAY = "풍족한 요리 주년기념일"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANHUNTS_SETTING = "바다 사냥"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANHUNTALTS_SETTING = "바다 사냥 돌발상황"

-- WORLDSETTINGS RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES_SETTING = "알로에"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES_SETTING = "아스파라거스"
STRINGS.UI.CUSTOMIZATIONSCREEN.CAVETUBERTREES_SETTING = "동굴 덩이줄기 나무"
STRINGS.UI.CUSTOMIZATIONSCREEN.CAVETUBERTREES2_SETTING = "꽃핀 동굴 덩이줄기 나무"
STRINGS.UI.CUSTOMIZATIONSCREEN.COFFEEBUSHES_SETTING = "커피나무"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS_SETTING = "펜넬"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS_SETTING = "거대 파스닙"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS_SETTING = "버섯 밑동"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES_SETTING = "송로버섯"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS_SETTING = "파스닙"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES_SETTING = "무"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES_SETTING = "납작한 돌"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES_SETTING = "고구마"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS_SETTING = "순무"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS_SETTING = "야생 밀"

-- WORLDSETTINGS OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.BRAINROCKS_SETTING = "뇌 싹"
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS_SETTING = "연꽃"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES_SETTING = "침수된 상자"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS_SETTING = "난파선"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS_SETTING = "해삼"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS_SETTING = "타로 토란"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES_SETTING = "물냉이"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA_SETTING = "해초"

-- WORLDSETTINGS SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS_SETTING = "소금 건조대"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES_SETTING = "점박이 관목"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS_SETTING = "단 꽃"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES_SETTING = "설탕단풍나무"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAPSUGARTREES_SETTING = "수액 채취기"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAP2SUGARTREES_SETTING = "망가진 수액 채취기"
STRINGS.UI.CUSTOMIZATIONSCREEN.RUINEDSUGARTREES_SETTING = "망가진 설탕단풍나무"

-- WORLDSETTINGS MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES_SETTING = "상자"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES_SETTING = "야자수"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS_SETTING = "삿갓조개 바위"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES_SETTING = "파인애플 덤불"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS_SETTING = "모래 더미"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES_SETTING = "차나무"

-- WORLDSETTINGS CREATURES
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS_SETTING = "닭"
STRINGS.UI.CUSTOMIZATIONSCREEN.DOGFISHES_SETTING = "물개기"
STRINGS.UI.CUSTOMIZATIONSCREEN.ELDERMANDRAKES_SETTING = "고대 맨드레이크"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS_SETTING = "낚시꾼 어인"
STRINGS.UI.CUSTOMIZATIONSCREEN.HERMITWOBSTERS_SETTING = "은둔자 왑스터"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES_SETTING = "해파리"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES2_SETTING = "무지개 해파리"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS_SETTING = "조약돌게"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS_SETTING = "피코"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE_SETTING = "오렌지 피코"
STRINGS.UI.CUSTOMIZATIONSCREEN.PUFFERMONSTERS_SETTING = "퍼퍼노트"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES_SETTING = "설탕나비"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWORDFISHES_SETTING = "황새치"