------------------------------------------------------------------------------------------------------------
-- World Generation
------------------------------------------------------------------------------------------------------------

-- WORLDGEN RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES = "Babosas"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES = "Asparagos"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS = "Funchos"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS = "Chirívias Gigantes"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS = "Tocos de Cogumelos"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES = "Trufas"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS = "Chirívias"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES = "Rabanetes"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES = "Lajes de Pedras"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES = "Batatas Doces"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS = "Nabos"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS = "Trigos"

-- WORLDGEN OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS = "Flores de Lótus"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES = "Caixotes Aquáticos"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS = "Destroços"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS = "Pepinos-do-Mar"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS = "Raízes de Taros"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES = "Agriões"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA = "Algas Marinhas"

-- WORLDGEN SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.SERENITYISLAND = "Porco Ancião"
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS = "Galinhas"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS = "Caranguejos"
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS = "Poças de Sal"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES = "Arbustos Folhosos"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES = "Borboletas de Açúcar"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS = "Flores Doces"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES = "Árvores Açucaradas"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAPSUGARTREES_SETTING = "Seivas"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAP2SUGARTREES_SETTING = "Seivas Arruinas"
STRINGS.UI.CUSTOMIZATIONSCREEN.RUINEDSUGARTREES_SETTING = "Árvores Açucaradas Arruinadas"

-- WORLDgen MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.MEADOWISLAND = "Sammy"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS = "Merm Pescadores"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMHUTS = "Barracos de Merm Pescador"
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES = "Caixotes"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES = "Palmeiras"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS = "Rochas de Lapas"
STRINGS.UI.CUSTOMIZATIONSCREEN.MERMHUTS = "Barracos de Merm"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS = "Esquilos"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE = "Esquilos Laranjas"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOTREES = "Árvores Chá Infestadas"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES = "Arbustos de Abacaxi"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS = "Pilhas de Areia"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES = "Árvores Chá"
STRINGS.UI.CUSTOMIZATIONSCREEN.TIDALPOOLS = "Poças de Maré"

------------------------------------------------------------------------------------------------------------
-- World Settings
------------------------------------------------------------------------------------------------------------

-- WORLDSETTINGS RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES_SETTING = "Babosas"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES_SETTING = "Asparagos"
STRINGS.UI.CUSTOMIZATIONSCREEN.COFFEEBUSHES_SETTING = "Plantas de Café"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS_SETTING = "Funchos"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS_SETTING = "Chirívias Gigantes"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS_SETTING = "Tocos de Cogumelos"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES_SETTING = "Trufas"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS_SETTING = "Chirívias"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES_SETTING = "Rabanetes"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES_SETTING = "Lajes de Pedras"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES_SETTING = "Batatas Doces"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS_SETTING = "Nabos"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS_SETTING = "Trigos"

-- WORLDSETTINGS OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS_SETTING = "Flores de Lótus"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES_SETTING = "Caixotes Aquáticos"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS_SETTING = "Destroços"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS_SETTING = "Pepinos-do-Mar"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS_SETTING = "Raízes de Taros"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES_SETTING = "Agriões"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA_SETTING = "Algas Marinhas"

-- WORLDSETTINGS SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS_SETTING = "Galinhas"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS_SETTING = "Caranguejos"
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS_SETTING = "Varais de Sal"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES_SETTING = "Arbustos Folhosos"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES_SETTING = "Borboletas de Açúcar"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS_SETTING = "Flores Doces"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES_SETTING = "Árvores Açucaradas"

-- WORLDSETTINGS MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS_SETTING = "Merm Pescadores"
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES_SETTING = "Caixotes"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES_SETTING = "Palmeiras"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS_SETTING = "Rochas de Lapas"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS_SETTING = "Esquilos"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE_SETTING = "Esquilos Laranjas"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES_SETTING = "Arbustos de Abacaxi"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS_SETTING = "Pilhas de Areia"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES_SETTING = "Árvores Chá"