-- Common Dependencies.
local _G       = GLOBAL
local require  = _G.require
local TechTree = require("techtree")

-- Mod Tunings.
TUNING.HOF_DEBUG_MODE = false
TUNING.HOF_RETROFIT_ENABLED = true

TUNING.HOF_RESOURCES = .06
TUNING.HOF_FLOATER = {"med", nil, 0.65}

TUNING.HOF_MIN_OCEANSETPIECES = 1
TUNING.HOF_MAX_OCEANSETPIECES = 3

-- Setting this to true will force our Special Event. It must be false during off-season.
TUNING.HOF_SPECIAL_EVENTS_BIRTHDAY = true -- Anniversary Event | Period: December - January.

TUNING.HOF_COFFEEBUFF_DURATION = GetModConfigData("COFFEEDURATION") or 480

TUNING.HOF_LANGUAGE_CODE = GetModConfigData("LANGUAGE") or "en"

TUNING.HOF_IS_TAP_ENABLED = _G.KnownModIndex:IsModEnabled("workshop-2428854303")
TUNING.HOF_IS_NET_ENABLED = _G.KnownModIndex:IsModEnabled("workshop-2528541304")
TUNING.HOF_IS_TCP_ENABLED = _G.KnownModIndex:IsModEnabled("workshop-2174681153")
TUNING.HOF_IS_HSP_ENABLED = _G.KnownModIndex:IsModEnabled("workshop-3438589036")
TUNING.HOF_IS_CTW_ENABLED = _G.KnownModIndex:IsModEnabled("workshop-3424375006")

TUNING.PROTOTYPER_TREES.MEALING_ONE      = TechTree.Create({ MEALING      = 1 })
TUNING.PROTOTYPER_TREES.MEALING_TWO      = TechTree.Create({ MEALING      = 2 })

TUNING.PROTOTYPER_TREES.SERENITYSHOP_ONE = TechTree.Create({ SERENITYSHOP = 1 })
TUNING.PROTOTYPER_TREES.SERENITYSHOP_TWO = TechTree.Create({ SERENITYSHOP = 2 })

TUNING.PROTOTYPER_TREES.MEADOWSHOP       = TechTree.Create({ MEADOWSHOP   = 1 })
TUNING.PROTOTYPER_TREES.MEADOWSHOP_ONE   = TechTree.Create({ MEADOWSHOP   = 1 })
TUNING.PROTOTYPER_TREES.MEADOWSHOP_TWO   = TechTree.Create({ MEADOWSHOP   = 2 })

TUNING.HOF_COOKPOTS =
{
	"cookpot",
	"portablecookpot",
	"archive_cookpot",
	"portablespicer",
	
	"kyno_cookware_syrup",
	"kyno_cookware_small",
	"kyno_cookware_big",
	"kyno_cookware_elder",
	"kyno_cookware_small_grill",
	"kyno_cookware_grill",
	"kyno_cookware_oven_small_casserole",
	"kyno_cookware_oven_casserole",
}

TUNING.HOF_MEATRACKS = 
{	
	"meatrack", 
	"meatrack_hermit"
}

TUNING.KYNO_FLOATILIZER_USES = 20
TUNING.KYNO_FLOATILIZER_SOILCYCLES = TUNING.POOP_SOILCYCLES
TUNING.KYNO_FLOATILIZER_FERTILIZE = TUNING.POOP_FERTILIZE * 2
TUNING.KYNO_FLOATILIZER_WITHEREDCYCLES = TUNING.POOP_WITHEREDCYCLES
TUNING.KYNO_FLOATILIZER_NUTRIENTS = { 16,  16,  16 }

TUNING.ASH_NUTRIENTS = { 4,  4,  0 }

TUNING.KYNO_MYSTERYMEAT_NUTRIENTS = { 16, 0, 16 }

TUNING.KYNO_SAP_SPOILED_NUTRIENTS = { 8, 0, 8 }

TUNING.WETGOOP2_NUTRIENTS = { 32, 8, 8 }

TUNING.DUCKYOUGLERMZ_NUTRIENTS = { 24, 24, 24 }
TUNING.DUCKYOUGLERMZ_NUTRIENTS_INDEX = 4

TUNING.KYNO_SPOILED_FISH_LARGE_NUTRIENTS = { 24, 0, 0 }

TUNING.KYNO_BANANATREE_GROWTIME = 480 * 4
TUNING.KYNO_BANANATREE_WORKLEFT = 3
TUNING.KYNO_BANANATREE_STUMP_WORKLEFT = 1

TUNING.KYNO_BANANA_HEALTH = 1
TUNING.KYNO_BANANA_HUNGER = 12.5
TUNING.KYNO_BANANA_SANITY = 0
TUNING.KYNO_BANANA_COOKED_HEALTH = 3
TUNING.KYNO_BANANA_COOKED_HUNGER = 12.5
TUNING.KYNO_BANANA_COOKED_SANITY = 0

TUNING.KYNO_BUCKET_EMPTY_USES = 10
TUNING.KYNO_BUCKET_WATER_USES = 20
TUNING.KYNO_BUCKET_WATER_AMOUNT = 25 / 2
TUNING.KYNO_BUCKET_WATER_EXTINGUISH_HEAT_PERCENT = -1
TUNING.KYNO_BUCKET_WATER_TEMP_REDUCTION = 5 / 2
TUNING.KYNO_BUCKET_WATER_PROTECTION_TIME = 30 / 2
TUNING.KYNO_BUCKET_WATER_PROTECTION_DIST = 2.25 / 2

TUNING.KYNO_BEANBUGS_HEALTH = 0
TUNING.KYNO_BEANBUGS_HUNGER = 9.375
TUNING.KYNO_BEANBUGS_SANITY = -10
TUNING.KYNO_BEANBUGS_COOKED_HEALTH = 1
TUNING.KYNO_BEANBUGS_COOKED_HUNGER = 12.5
TUNING.KYNO_BEANBUGS_COOKED_SANITY = -5

TUNING.KYNO_TOMATOCAN_HEALTH = 12.5
TUNING.KYNO_TOMATOCAN_HUNGER = 20 
TUNING.KYNO_TOMATOCAN_SANITY = 0

TUNING.KYNO_BEANCAN_HEALTH = 0
TUNING.KYNO_BEANCAN_HUNGER = 20 
TUNING.KYNO_BEANCAN_SANITY = 10 

TUNING.KYNO_MEATCAN_HEALTH = 5
TUNING.KYNO_MEATCAN_HUNGER = 25 
TUNING.KYNO_MEATCAN_SANITY = 0 

TUNING.KYNO_CHICKEN2_HEALTH = 75
TUNING.KYNO_CHICKEN_RELEASE_TIME = 10
TUNING.KYNO_CHICKEN_REGEN_TIME = 960
TUNING.KYNO_CHICKEN_AMOUNT = 3
TUNING.KYNO_CHICKEN_ENABLED = true

TUNING.KYNO_CHICKEN_EGG_HEALTH = 2
TUNING.KYNO_CHICKEN_EGG_HUNGER = 9.375
TUNING.KYNO_CHICKEN_EGG_SANITY = 0
TUNING.KYNO_CHICKEN_EGG_COOKED_HEALTH = 3
TUNING.KYNO_CHICKEN_EGG_COOKED_HUNGER = 12.5
TUNING.KYNO_CHICKEN_EGG_COOKED_SANITY = 0

TUNING.KYNO_COFFEEBUFF_SPEED = 1.83 -- GetModConfigData("HOF_COFFEESPEEDMULTIPLIER")
TUNING.KYNO_COFFEEBUFF_DURATION_SMALL = 30
TUNING.KYNO_COFFEEBUFF_DURATION_MEDSMALL = 240
TUNING.KYNO_COFFEEBUFF_DURATION_MED = 480
TUNING.KYNO_COFFEEBUFF_DURATION_LARGE = 640
TUNING.KYNO_COFFEEBUFF_DURATION_MEDLARGE = 960
TUNING.KYNO_COFFEEBUFF_DURATION_HUGE = 1920

TUNING.KYNO_COFFEEBEANS_HEALTH = 0
TUNING.KYNO_COFFEEBEANS_HUNGER = 9.375
TUNING.KYNO_COFFEEBEANS_SANITY = 0
TUNING.KYNO_COFFEEBEANS_COOKED_HEALTH = 0
TUNING.KYNO_COFFEEBEANS_COOKED_HUNGER = 9.375
TUNING.KYNO_COFFEEBEANS_COOKED_SANITY = -5

TUNING.KYNO_SALTRACK_REGROW_TIME = 1920

TUNING.KYNO_COOKWARE_COOKTIMEMULT = .5
TUNING.KYNO_COOKWARE_COOKTIMEMULT_SYRUP = .3
TUNING.KYNO_COOKWARE_BONUSHARVEST = 1
TUNING.KYNO_COOKWARE_BONUSHARVEST_SYRUP = 3 -- 3 to keep consistent with 2 from cooking pot.

TUNING.KYNO_DMGREDUCTIONBUFF_SPEED = .70
TUNING.KYNO_ALCOHOL_SPEED = .70
TUNING.KYNO_ALCOHOL_DURATION_SMALL = 480
TUNING.KYNO_ALCOHOL_DURATION_MEDSMALL = 520
TUNING.KYNO_ALCOHOL_STRENGTH_SMALL = 1.2
TUNING.KYNO_ALCOHOL_STRENGTH_MEDSMALL = 1.5

TUNING.KYNO_FISH_LARGE_HEALTH = 4
TUNING.KYNO_FISH_LARGE_HUNGER = 25
TUNING.KYNO_FISH_LARGE_SANITY = 0

TUNING.KYNO_FISH_LARGE_COOKED_HEALTH = 8
TUNING.KYNO_FISH_LARGE_COOKED_HUNGER = 25
TUNING.KYNO_FISH_LARGE_COOKED_SANITY = 5

TUNING.KYNO_FISH_SMALL_HEALTH = 1
TUNING.KYNO_FISH_SMALL_HUNGER = 12.5
TUNING.KYNO_FISH_SMALL_SANITY = 0

TUNING.KYNO_FISH_SMALL_COOKED_HEALTH = 3
TUNING.KYNO_FISH_SMALL_COOKED_HUNGER = 12.5
TUNING.KYNO_FISH_SMALL_COOKED_SANITY = 1

TUNING.KYNO_HASTEBUFF_DURATION = 480

TUNING.KYNO_WHEAT_HEALTH = 0
TUNING.KYNO_WHEAT_HUNGER = 4.6875
TUNING.KYNO_WHEAT_SANITY = 0
TUNING.KYNO_WHEAT_COOKED_HEALTH = 1
TUNING.KYNO_WHEAT_COOKED_HUNGER = 4.6875
TUNING.KYNO_WHEAT_COOKED_SANITY = 0

TUNING.KYNO_SAP_HEALTH = 1
TUNING.KYNO_SAP_HUNGER = 3 
TUNING.KYNO_SAP_SANITY = 0

TUNING.KYNO_SYRUP_HEALTH = 3 
TUNING.KYNO_SYRUP_HUNGER = 9.375
TUNING.KYNO_SYRUP_SANITY = 0

TUNING.KYNO_SPOTSPICE_LEAF_HEALTH = 0
TUNING.KYNO_SPOTSPICE_LEAF_HUNGER = 4.6875
TUNING.KYNO_SPOTSPICE_LEAF_SANITY = 0 

TUNING.KYNO_BACON_HEALTH = 0
TUNING.KYNO_BACON_HUNGER = 12.5
TUNING.KYNO_BACON_SANITY = -10
TUNING.KYNO_BACON_COOKED_HEALTH = 3
TUNING.KYNO_BACON_COOKED_HUNGER = 12.5
TUNING.KYNO_BACON_COOKED_SANITY = 5

TUNING.KYNO_WHITE_CAP_HEALTH = -10
TUNING.KYNO_WHITE_CAP_HUNGER = 9.375
TUNING.KYNO_WHITE_CAP_SANITY = 0
TUNING.KYNO_WHITE_CAP_COOKED_HEALTH = -5
TUNING.KYNO_WHITE_CAP_COOKED_HUNGER = 12.5
TUNING.KYNO_WHITE_CAP_COOKED_SANITY = 0

TUNING.KYNO_FOLIAGE_HEALTH = 1
TUNING.KYNO_FOLIAGE_HUNGER = 0
TUNING.KYNO_FOLIAGE_SANITY = 0
TUNING.KYNO_FOLIAGE_COOKED_HEALTH = 1 
TUNING.KYNO_FOLIAGE_COOKED_HUNGER = 1 
TUNING.KYNO_FOLIAGE_COOKED_SANITY = 0

TUNING.KYNO_CRABMEAT_HEALTH = 5 
TUNING.KYNO_CRABMEAT_HUNGER = 5 
TUNING.KYNO_CRABMEAT_SANITY = -10 
TUNING.KYNO_CRABMEAT_COOKED_HEALTH = 10 
TUNING.KYNO_CRABMEAT_COOKED_HUNGER = 10 
TUNING.KYNO_CRABMEAT_COOKED_SANITY = 5
TUNING.KYNO_CRABMEAT_DRIED_HEALTH = 25
TUNING.KYNO_CRABMEAT_DRIED_HUNGER = 25
TUNING.KYNO_CRABMEAT_DRIED_SANITY = 10

TUNING.KYNO_CRABKINGMEAT_HEALTH = -10
TUNING.KYNO_CRABKINGMEAT_HUNGER = 10
TUNING.KYNO_CRABKINGMEAT_SANITY = -10
TUNING.KYNO_CRABKINGMEAT_COOKED_HEALTH = 20
TUNING.KYNO_CRABKINGMEAT_COOKED_HUNGER = 20
TUNING.KYNO_CRABKINGMEAT_COOKED_SANITY = 0
TUNING.KYNO_CRABKINGMEAT_DRIED_HEALTH = 40
TUNING.KYNO_CRABKINGMEAT_DRIED_HUNGER = 40
TUNING.KYNO_CRABKINGMEAT_DRIED_SANITY = 20

TUNING.KYNO_HUMANMEAT_HEALTH = -20 
TUNING.KYNO_HUMANMEAT_HUNGER = 12.5
TUNING.KYNO_HUMANMEAT_SANITY = -33
TUNING.KYNO_HUMANMEAT_COOKED_HEALTH = -3
TUNING.KYNO_HUMANMEAT_COOKED_HUNGER = 18.75
TUNING.KYNO_HUMANMEAT_COOKED_SANITY = -20
TUNING.KYNO_HUMANMEAT_DRIED_HEALTH = -3 
TUNING.KYNO_HUMANMEAT_DRIED_HUNGER = 25
TUNING.KYNO_HUMANMEAT_DRIED_SANITY = -15

TUNING.KYNO_KOKONUT_HEALTH = 1 
TUNING.KYNO_KOKONUT_HUNGER = 4.6875 
TUNING.KYNO_KOKONUT_SANITY = 0
TUNING.KYNO_KOKONUT_COOKED_HEALTH = 3
TUNING.KYNO_KOKONUT_COOKED_HUNGER = 9.375
TUNING.KYNO_KOKONUT_COOKED_SANITY = 0 

TUNING.KYNO_KOKONUTTREE_GROWTIME = 480 * 5
TUNING.KYNO_KOKONUTTREE_REGROWTH_TIME_MULT = 1
TUNING.KYNO_KOKONUTTREE_SHORT_WORKLEFT = 5
TUNING.KYNO_KOKONUTTREE_NORMAL_WORKLEFT = 10
TUNING.KYNO_KOKONUTTREE_TALL_WORKLEFT = 15
TUNING.KYNO_KOKONUTTREE_STUMP_WORKLEFT = 1
TUNING.KYNO_KOKONUTTREE_KOKONUT_CHANCE = 0.03
TUNING.KYNO_KOKONUTTREE_REGROWTH_TIME = 480 * 3

TUNING.KYNO_LIMPETROCK_GROWTIME = 1440
TUNING.KYNO_LIMPETROCK_REGROWTH_TIME_MULT = 1

TUNING.KYNO_LIMPETS_HEALTH = 0 
TUNING.KYNO_LIMPETS_HUNGER = 12.5
TUNING.KYNO_LIMPETS_SANITY = -10
TUNING.KYNO_LIMPETS_COOKED_HEALTH = 1 
TUNING.KYNO_LIMPETS_COOKED_HUNGER = 12.5
TUNING.KYNO_LIMPETS_COOKED_SANITY = 0

TUNING.KYNO_LOTUS_GROWTIME = 480 * 3
TUNING.KYNO_LOTUS_REGROWTH_TIME_MULT = 1

TUNING.KYNO_LOTUS_HEALTH = 1
TUNING.KYNO_LOTUS_HUNGER = 12.5
TUNING.KYNO_LOTUS_SANITY = 5
TUNING.KYNO_LOTUS_COOKED_HEALTH = 3
TUNING.KYNO_LOTUS_COOKED_HUNGER = 12.5
TUNING.KYNO_LOTUS_COOKED_SANITY = 15

TUNING.KYNO_MEALGRINDER_WORKLEFT = 4

TUNING.KYNO_MILK_BEEFALO_HEALTH = 3
TUNING.KYNO_MILK_BEEFALO_HUNGER = 3
TUNING.KYNO_MILK_BEEFALO_SANITY = -10

TUNING.KYNO_MILK_KOALEFANT_HEALTH = 6
TUNING.KYNO_MILK_KOALEFANT_HUNGER = 6
TUNING.KYNO_MILK_KOALEFANT_SANITY = -10

TUNING.KYNO_MILK_DEER_HEALTH = 0 
TUNING.KYNO_MILK_DEER_HUNGER = 5 
TUNING.KYNO_MILK_DEER_SANITY = -10

TUNING.KYNO_MILK_SPAT_HEALTH = 8 
TUNING.KYNO_MILK_SPAT_HUNGER = 8 
TUNING.KYNO_MILK_SPAT_SANITY = -20

TUNING.KYNO_MUSHSTUMP_GROWTIME = 480 * 5
TUNING.KYNO_MUSHSTUMP_REGROWTH_TIME_MULT = 1
TUNING.KYNO_MUSHSTUMP_WORKLEFT = 1

TUNING.KYNO_MUSSEL_HEALTH = 0
TUNING.KYNO_MUSSEL_HUNGER = 12.5
TUNING.KYNO_MUSSEL_SANITY = -15 
TUNING.KYNO_MUSSEL_COOKED_HEALTH = 1
TUNING.KYNO_MUSSEL_COOKED_HUNGER = 12.5
TUNING.KYNO_MUSSEL_COOKED_SANITY = 0

TUNING.KYNO_MUSSELSTICK_GROWTIME = 1440
TUNING.KYNO_MUSSELSTICK_WORKLEFT = 4

TUNING.KYNO_MYSTERYMEAT_HEALTH = -1
TUNING.KYNO_MYSTERYMEAT_HUNGER = -10
TUNING.KYNO_MYSTERYMEAT_SANITY = 0

TUNING.KYNO_OCEANWRECK_WORKLEFT = 4
TUNING.KYNO_OCEAN_WRECK_GROWTIME = 1440
TUNING.KYNO_OCEAN_WRECK_REGROWTH_TIME_MULT = 1
TUNING.KYNO_OCEAN_WRECK_GHOST_CHANCE = .33

TUNING.KYNO_SODACAN_HEALTH = -8
TUNING.KYNO_SODACAN_HUNGER = 0
TUNING.KYNO_SODACAN_SANITY = 33

TUNING.KYNO_COKECAN_HEALTH = -8
TUNING.KYNO_COKECAN_HUNGER = 0
TUNING.KYNO_COKECAN_SANITY = 33

TUNING.KYNO_ENERGYCAN_HEALTH = -8
TUNING.KYNO_ENERGYCAN_HUNGER = 0
TUNING.KYNO_ENERGYCAN_SANITY = 33

TUNING.KYNO_COFFEEBUSH_GROWTIME = 480 * 4
TUNING.KYNO_COFFEEBUSH_GROWTIME_SUMMER = 480 * 2
TUNING.KYNO_COFFEEBUSH_GROWTIME_SPRING = 480 * 8
TUNING.KYNO_COFFEEBUSH_WORKLEFT = 1
TUNING.KYNO_COFFEEBUSH_CYCLES = 3

TUNING.KYNO_FLIPPABLE_GROWTIME = 480 * 7
TUNING.KYNO_FLIPPABLE_REGROWTH_TIME_MULT = 1
TUNING.KYNO_FLIPPABLE_ROCK_REPOPULATE_TIME = 2400
TUNING.KYNO_FLIPPABLE_ROCK_REPOPULATE_INCREASE = 240
TUNING.KYNO_FLIPPABLE_ROCK_REPOPULATE_VARIANCE = 960
TUNING.KYNO_FLIPPABLE_ROCK_CYCLES = 3
TUNING.KYNO_FLIPPABLE_WORKLEFT = 3

TUNING.KYNO_ROE_HEALTH = 1
TUNING.KYNO_ROE_HUNGER = 4.6875
TUNING.KYNO_ROE_SANITY = 0
TUNING.KYNO_ROE_COOKED_HEALTH = 3
TUNING.KYNO_ROE_COOKED_HUNGER = 4.6875
TUNING.KYNO_ROE_COOKED_SANITY = 0

TUNING.KYNO_ROE_OCEANFISH_PUFFERFISH_HEALTH = -10
TUNING.KYNO_ROE_OCEANFISH_PUFFERFISH_HUNGER = 9.375
TUNING.KYNO_ROE_OCEANFISH_PUFFERFISH_SANITY = -10
TUNING.KYNO_PUFFERFISH_KILL_CHANCE = .5

TUNING.KYNO_ROE_TEMPERATURE_HOT = 20
TUNING.KYNO_ROE_TEMPERATURE_COLD = 20
TUNING.KYNO_ROE_TEMPERATURE_DURATION = 10

TUNING.KYNO_PEBBLECRAB_HEALTH = 50
TUNING.KYNO_PEBBLECRAB_WALKSPEED = 1
TUNING.KYNO_PEBBLECRAB_RUNSPEED = 6
TUNING.KYNO_PEBBLECRAB_RELEASE_TIME = 10
TUNING.KYNO_PEBBLECRAB_REGEN_TIME = 960
TUNING.KYNO_PEBBLECRAB_AMOUNT = 2
TUNING.KYNO_PEBBLECRAB_ENABLED = true

TUNING.KYNO_SUGARFLY_HEALTH = 1
TUNING.MAX_KYNO_SUGARFLIES = 4

TUNING.KYNO_SUGARFLYWINGS_HEALTH = 0
TUNING.KYNO_SUGARFLYWINGS_HUNGER = 9.375
TUNING.KYNO_SUGARFLYWINGS_SANITY = 8

TUNING.KYNO_CRABTRAP_USES = 8

TUNING.KYNO_SLAUGHTERTOOLS_USES = 6
TUNING.KYNO_SLAUGHTERTOOLS_COOLDOWN = 30
TUNING.KYNO_SLAUGHTERTOOLS_AVOID_DIST = 5
TUNING.KYNO_SLAUGHTERTOOLS_AVOID_STOP = 15
TUNING.KYNO_SLAUGHTERTOOLS_MAXDIST = 25

TUNING.KYNO_SAP_GROWTIME = 1440
TUNING.KYNO_SAP_RUINED_GROWTIME = 1440
TUNING.KYNO_SAP_SPOILTIME = 4800
TUNING.KYNO_SAP_SPOILTIME_MAX = 4800
TUNING.KYNO_SAP_SPOILS = true

TUNING.KYNO_SUGARFLOWER_REGROWTH_TIME_MULT = 1

TUNING.KYNO_SUGARTREE_WORKLEFT = 15
TUNING.KYNO_SUGARTREE_STUMP_WORKLEFT = 1
TUNING.KYNO_SUGARTREE_TAPPED_WORKLEFT = 1
TUNING.KYNO_SUGARTREE_SHORT_WORKLEFT = 5
TUNING.KYNO_SUGARTREE_NORMAL_WORKLEFT = 10
TUNING.KYNO_SUGARTREE_SHORT_GROWTIME = 240
TUNING.KYNO_SUGARTREE_NORMAL_GROWTIME = 720
TUNING.KYNO_SUGARTREE_REGROWTH_TIME = 480 * 3
TUNING.KYNO_SUGARTREE_REGROWTH_TIME_MULT = 1

TUNING.KYNO_SHARKFIN_HEALTH = 20
TUNING.KYNO_SHARKFIN_HUNGER = 25
TUNING.KYNO_SHARKFIN_SANITY = -10

TUNING.KYNO_SPOTBUSH_GROWTIME = 480 * 3
TUNING.KYNO_SPOTBUSH_REGROWTH_TIME_MULT = 1

TUNING.KYNO_TAROSEA_GROWTIME = 480 * 4
TUNING.KYNO_TAROROOT_REGROWTH_TIME_MULT = 1

TUNING.KYNO_TAROROOT_HEALTH = 8
TUNING.KYNO_TAROROOT_HUNGER = 25
TUNING.KYNO_TAROROOT_SANITY = 0
TUNING.KYNO_TAROROOT_COOKED_HEALTH = 20
TUNING.KYNO_TAROROOT_COOKED_HUNGER = 25
TUNING.KYNO_TAROROOT_COOKED_SANITY = 0

TUNING.KYNO_TUNACAN_HEALTH = 10
TUNING.KYNO_TUNACAN_HUNGER = 25
TUNING.KYNO_TUNACAN_SANITY = 0

TUNING.KYNO_TWIGGYNUTS_HEALTH = 5
TUNING.KYNO_TWIGGYNUTS_HUNGER = 0
TUNING.KYNO_TWIGGYNUTS_SANITY = 5

TUNING.KYNO_WATERBUFF_DURATION = 60

TUNING.KYNO_WATERYCRESS_GROWTIME = 480 * 5
TUNING.KYNO_WATERYCRESS_REGROWTH_TIME_MULT = 1

TUNING.KYNO_WATERYCRESS_HEALTH = 1
TUNING.KYNO_WATERYCRESS_HUNGER = 12.5
TUNING.KYNO_WATERYCRESS_SANITY = 5
TUNING.KYNO_WATERYCRESS_COOKED_HEALTH = 3
TUNING.KYNO_WATERYCRESS_COOKED_HUNGER = 12.5
TUNING.KYNO_WATERYCRESS_COOKED_SANITY = 5

TUNING.KYNO_WEEDSEA_GROWTIME = 480 * 3
TUNING.KYNO_WEEDSEA_REGROWTH_TIME_MULT = 1

TUNING.KYNO_WEEDSEA_HEALTH = 1
TUNING.KYNO_WEEDSEA_HUNGER = 9.375
TUNING.KYNO_WEEDSEA_SANITY = -10
TUNING.KYNO_WEEDSEA_COOKED_HEALTH = 3
TUNING.KYNO_WEEDSEA_COOKED_HUNGER = 9.375
TUNING.KYNO_WEEDSEA_COOKED_SANITY = 0
TUNING.KYNO_WEEDSEA_DRIED_HEALTH = 3
TUNING.KYNO_WEEDSEA_DRIED_HUNGER = 12.5
TUNING.KYNO_WEEDSEA_DRIED_SANITY = 5

TUNING.KYNO_WILDWHEAT_GROWTIME = 480 * 3
TUNING.KYNO_WILDWHEAT_REGROWTH_TIME_MULT = 1

TUNING.KYNO_RADISH_REGROWTH_TIME_MULT = 1

TUNING.KYNO_RADISH_HEALTH = 1
TUNING.KYNO_RADISH_HUNGER = 12.5
TUNING.KYNO_RADISH_SANITY = 0
TUNING.KYNO_RADISH_COOKED_HEALTH = 3
TUNING.KYNO_RADISH_COOKED_HUNGER = 12.5
TUNING.KYNO_RADISH_COOKED_SANITY = 0

TUNING.KYNO_CUCUMBER_REGROWTH_TIME_MULT = 1

TUNING.KYNO_CUCUMBER_HEALTH = 1
TUNING.KYNO_CUCUMBER_HUNGER = 12.5
TUNING.KYNO_CUCUMBER_SANITY = -5
TUNING.KYNO_CUCUMBER_COOKED_HEALTH = 1
TUNING.KYNO_CUCUMBER_COOKED_HUNGER = 25
TUNING.KYNO_CUCUMBER_COOKED_SANITY = 5

TUNING.KYNO_SWEETPOTATO_REGROWTH_TIME_MULT = 1

TUNING.KYNO_SWEETPOTATO_HEALTH = 1
TUNING.KYNO_SWEETPOTATO_HUNGER = 12.5
TUNING.KYNO_SWEETPOTATO_SANITY = 0
TUNING.KYNO_SWEETPOTATO_COOKED_HEALTH = 3
TUNING.KYNO_SWEETPOTATO_COOKED_HUNGER = 12.5
TUNING.KYNO_SWEETPOTATO_COOKED_SANITY = 0

TUNING.KYNO_PARZNIP_REGROWTH_TIME_MULT = 1

TUNING.KYNO_PARZNIP_HEALTH = 1
TUNING.KYNO_PARZNIP_HUNGER = 6
TUNING.KYNO_PARZNIP_SANITY = 0
TUNING.KYNO_PARZNIP_EATEN_HEALTH = 1
TUNING.KYNO_PARZNIP_EATEN_HUNGER = 6 
TUNING.KYNO_PARZNIP_EATEN_SANITY = 0
TUNING.KYNO_PARZNIP_COOKED_HEALTH = 3
TUNING.KYNO_PARZNIP_COOKED_HUNGER = 18.5
TUNING.KYNO_PARZNIP_COOKED_SANITY = 1

TUNING.KYNO_PARZNIP_BIG_WORKLEFT = 10
TUNING.KYNO_PARZNIP_BIG_REGROWTH_TIME_MULT = 1

TUNING.KYNO_TURNIP_REGROWTH_TIME_MULT = 1

TUNING.KYNO_TURNIP_HEALTH = 5
TUNING.KYNO_TURNIP_HUNGER = 9.375
TUNING.KYNO_TURNIP_SANITY = 0
TUNING.KYNO_TURNIP_COOKED_HEALTH = 10
TUNING.KYNO_TURNIP_COOKED_HUNGER = 18.5
TUNING.KYNO_TURNIP_COOKED_SANITY = 0

TUNING.KYNO_FENNEL_REGROWTH_TIME_MULT = 1

TUNING.KYNO_FENNEL_HEALTH = 1
TUNING.KYNO_FENNEL_HUNGER = 12.5
TUNING.KYNO_FENNEL_SANITY = -5
TUNING.KYNO_FENNEL_COOKED_HEALTH = 3
TUNING.KYNO_FENNEL_COOKED_HUNGER = 12.5
TUNING.KYNO_FENNEL_COOKED_SANITY = 5

TUNING.KYNO_ALOE_REGROWTH_TIME_MULT = 1

TUNING.KYNO_ALOE_HEALTH = 8
TUNING.KYNO_ALOE_HUNGER = 9.375
TUNING.KYNO_ALOE_SANITY = 0
TUNING.KYNO_ALOE_COOKED_HEALTH = 8
TUNING.KYNO_ALOE_COOKED_HUNGER = 12.5
TUNING.KYNO_ALOE_COOKED_SANITY = 0

TUNING.KYNO_RICE_HEALTH = 3
TUNING.KYNO_RICE_HUNGER = 9.375
TUNING.KYNO_RICE_SANITY = 0
TUNING.KYNO_RICE_COOKED_HEALTH = 3
TUNING.KYNO_RICE_COOKED_HUNGER = 18.5
TUNING.KYNO_RICE_COOKED_SANITY = 1

TUNING.KYNO_ASPARGOS_REGROWTH_TIME_MULT = 1

TUNING.SOULSTEW_HEALTH = 5
TUNING.SOULSTEW_HUNGER = 31.25
TUNING.SOULSTEW_SANITY = -10

TUNING.KYNO_DRIEDCAP_RED_HEALTH = -10
TUNING.KYNO_DRIEDCAP_RED_HUNGER = 25
TUNING.KYNO_DRIEDCAP_RED_SANITY = 0

TUNING.KYNO_DRIEDCAP_GREEN_HEALTH = -10
TUNING.KYNO_DRIEDCAP_GREEN_HUNGER = 0
TUNING.KYNO_DRIEDCAP_GREEN_SANITY = 25

TUNING.KYNO_DRIEDCAP_BLUE_HEALTH = 25
TUNING.KYNO_DRIEDCAP_BLUE_HUNGER = 0
TUNING.KYNO_DRIEDCAP_BLUE_SANITY = -10

TUNING.KYNO_DRIEDCAP_MOON_HEALTH = 5
TUNING.KYNO_DRIEDCAP_MOON_HUNGER = 5
TUNING.KYNO_DRIEDCAP_MOON_SANITY = 5

TUNING.KYNO_PLANTMEAT_DRIED_HEALTH = 15
TUNING.KYNO_PLANTMEAT_DRIED_HUNGER = 25
TUNING.KYNO_PLANTMEAT_DRIED_SANITY = 20

TUNING.KYNO_ANTCHEST_PERISH_MULT = -0.7

TUNING.NECTAR_TO_HONEY_TIME = 60

TUNING.KYNO_NECTAR_POD_HEALTH = 3
TUNING.KYNO_NECTAR_POD_HUNGER = 9.375
TUNING.KYNO_NECTAR_POD_SANITY = 0

TUNING.KYNO_OAKTREE_POD_COOKED_HEALTH = 0
TUNING.KYNO_OAKTREE_POD_COOKED_HUNGER = 9.375
TUNING.KYNO_OAKTREE_POD_COOKED_SANITY = 3

TUNING.KYNO_MEADOWISLAND_TREE_SHORT_GROWTIME = 240
TUNING.KYNO_MEADOWISLAND_TREE_NORMAL_GROWTIME = 720
TUNING.KYNO_MEADOWISLAND_TREE_SHORT_WORKLEFT = 5
TUNING.KYNO_MEADOWISLAND_TREE_NORMAL_WORKLEFT = 10
TUNING.KYNO_MEADOWISLAND_TREE_TALL_WORKLEFT = 15
TUNING.KYNO_MEADOWISLAND_TREE_STUMP_WORKLEFT = 1
TUNING.KYNO_MEADOWISLAND_TREE_BURNT_WORKLEFT = 1
TUNING.KYNO_MEADOWISLAND_TREE_DROP_CHANCE = .12 -- Low because each hit procs the chance.
TUNING.KYNO_MEADOWISLAND_TREE_REGROWTH_TIME = 480 * 3
TUNING.KYNO_MEADOWISLAND_TREE_REGROWTH_TIME_MULT = 1

TUNING.KYNO_MEADOWISLAND_POND_MAX_FISH = 15

TUNING.KYNO_MEADOWISLAND_SAND_REGROW = 480 * 6
TUNING.KYNO_MEADOWISLAND_SAND_REGROW_VARIANCE = 480
TUNING.KYNO_MEADOWISLAND_SAND_REGROWTH_TIME_MULT = 1
TUNING.KYNO_MEADOWISLAND_SAND_DEPLETE = 0.25

TUNING.KYNO_PIKO_HEALTH = 100
TUNING.KYNO_PIKO_SPAWN_TIME = 480 * 4
TUNING.KYNO_PIKO_RUN_SPEED = 4
TUNING.KYNO_PIKO_DAMAGE = 2
TUNING.KYNO_PIKO_ATTACK_PERIOD = 2
TUNING.KYNO_PIKO_TARGET_DIST = 20
TUNING.KYNO_PIKO_PERISH_TIME = 480 * 5
TUNING.KYNO_PIKO_SPAWNDELAY = 10
TUNING.KYNO_PIKO_ORANGE_CHANCE = .40
TUNING.KYNO_PIKO_ENABLED = true
TUNING.KYNO_PIKO_ORANGE_ENABLED = true

TUNING.DUCKYOUGLERMZ_HEALTH = 60
TUNING.DUCKYOUGLERMZ_HUNGER = 12.5
TUNING.DUCKYOUGLERMZ_SANITY = 33

TUNING.MILKABLE_NORMAL_TIME = 3360
TUNING.MILKABLE_SPRING_TIME = 4800
TUNING.MILKABLE_NORMAL_DAMAGE = 30
TUNING.MILKABLE_SPRING_DAMAGE = 60
TUNING.MILKABLE_KOALEFANT_DAMAGE = 50
TUNING.MILKABLE_LIGHTNINGGOAT_DAMAGE = 25

TUNING.KYNO_POISON_FROGLEGS_HEALTH = -10
TUNING.KYNO_POISON_FROGLEGS_HUNGER = 20
TUNING.KYNO_POISON_FROGLEGS_SANITY = -10
TUNING.KYNO_POISON_FROGLEGS_COOKED_HEALTH = -5
TUNING.KYNO_POISON_FROGLEGS_COOKED_HUNGER = 20
TUNING.KYNO_POISON_FROGLEGS_COOKED_SANITY = 0

TUNING.KYNO_MOON_FROGLEGS_HEALTH = 0
TUNING.KYNO_MOON_FROGLEGS_HUNGER = 12.5
TUNING.KYNO_MOON_FROGLEGS_SANITY = -5
TUNING.KYNO_MOON_FROGLEGS_COOKED_HEALTH = 1
TUNING.KYNO_MOON_FROGLEGS_COOKED_HUNGER = 12.5
TUNING.KYNO_MOON_FROGLEGS_COOKED_SANITY = 15

TUNING.KYNO_FROGBUFF_DURATION = 480

TUNING.KYNO_BREWINGRECIPECARD_CHANCE = 0.04 -- It needs to be this low.

TUNING.KYNO_OIL_HEALTH = 1
TUNING.KYNO_OIL_HUNGER = 9.375
TUNING.KYNO_OIL_SANITY = -10

TUNING.KYNO_PLANT_REGROWTH_TIME_MULT = 1
TUNING.KYNO_PLANT_REGROWTH_TIME = 480 * 15
TUNING.KYNO_TREE_REGROWTH_TIME = 480 * 25
TUNING.KYNO_DESOLATION_RESPAWN_TIME = 480 * 50

TUNING.KYNO_FEARBUFF_DURATION = 480

TUNING.KYNO_PIRATEBUFF_DURATION = 720
TUNING.KYNO_PIRATEBUFF_EXTRADAMAGE = 50

TUNING.KYNO_WORMBUFF_DURATION = 720
TUNING.KYNO_WORMBUFF_EXTRADAMAGE = 50

TUNING.KYNO_CRABBUFF_DURATION = 720
TUNING.KYNO_CRABBUFF_EXTRADAMAGE = 50

TUNING.KYNO_PINEAPPLE_HEALTH = 3
TUNING.KYNO_PINEAPPLE_HUNGER = 12.5
TUNING.KYNO_PINEAPPLE_SANITY = 0

TUNING.KYNO_PINEAPPLE_COOKED_HEALTH = 15
TUNING.KYNO_PINEAPPLE_COOKED_HUNGER = 12.5
TUNING.KYNO_PINEAPPLE_COOKED_SANITY = 3

TUNING.KYNO_PINEAPPLEBUSH_GROWTIME = 480 * 6
TUNING.KYNO_PINEAPPLEBUSH_GROWTIME_SUMMER = 480 * 2
TUNING.KYNO_PINEAPPLEBUSH_GROWTIME_SPRING = 480 * 6
TUNING.KYNO_PINEAPPLEBUSH_REGROWTH_TIME_MULT = 1
TUNING.KYNO_PINEAPPLEBUSH_WORKLEFT = 1

TUNING.KYNO_NIGHTVISIONBUFF_DURATION = 480 

TUNING.KYNO_GARDEN_SPRINKLER_MAXFUEL = 350
TUNING.KYNO_GARDEN_SPRINKLER_FUELSECTIONS = 10

TUNING.KYNO_FOODSACK_PERISH_MULT = -0.3

TUNING.KYNO_NUKASHINE_BLACKOUT = 520

TUNING.KYNO_COLDBUFF_DURATION = 480 * 1.5
TUNING.KYNO_HEATBUFF_DURATION = 480 * 1.5

TUNING.KYNO_FIREBUFF_DURATION = 480 / 2

TUNING.KYNO_FREEZEBUFF_DURATION = 480 / 2
TUNING.KYNO_FREEZEBUFF_FREEZING = .50

TUNING.KYNO_PRESERVERBUFF_DURATION = 960
TUNING.KYNO_PRESERVERBUFF_RATE = .90
TUNING.KYNO_PRESERVERBUFF_PERISHTIME = 2.5 -- 30000 lol don't do it again. Powdercake had "1687499679" days spoil time.

TUNING.SPICE_MULTIPLIERS =
{
	SPICE_SALT = { HEALTH = .25 },
	SPICE_FED  = { HUNGER = .25 },
	SPICE_MIND = { SANITY = .25 },
}

TUNING.KYNO_FISHINGBUFF_DURATION = 480 * 1.5
TUNING.KYNO_FISHINGBUFF_EXTRA_FISH_CHANCE = .33

TUNING.KYNO_MOCHABUFF_DURATION = 480
TUNING.KYNO_MOCHABUFF_SPEED = 1.43

TUNING.KYNO_HUNGERRATEBUFF_MODIFIER = .75

TUNING.KYNO_SANITYRATEBUFF_DURATION = 480 / 2
TUNING.KYNO_SANITYRATEBUFF_MODIFIER = .75

TUNING.KYNO_INSPIRATIONBUFF = 40
TUNING.KYNO_MIGHTINESSBUFF = 50

TUNING.KYNO_TEALEAF_HEALTH = 0
TUNING.KYNO_TEALEAF_HUNGER = 4.6875
TUNING.KYNO_TEALEAF_SANITY = 1

TUNING.KYNO_ITEMSLICER_USES = 200

TUNING.KYNO_EATERBUFF_DURATION = 480 * 1.5

TUNING.SUGARBOMBS_DAMAGE = 9999

TUNING.KYNO_MERMFISHER_TIMER = 400
TUNING.KYNO_MERMFISHER_HEALTH = 300
TUNING.KYNO_MERMFISHER_ROYAL_HEALTH = 600
TUNING.KYNO_MERMFISHER_RUNSPEED = 7
TUNING.KYNO_MERMFISHER_WALKSPEED = 4
TUNING.KYNO_MERMFISHER_TIMERMULT = 1
TUNING.KYNO_MERMFISHER_TIMERMULT_ROYAL = 0.75
TUNING.KYNO_MERMFISHER_RELEASE_TIME = 10
TUNING.KYNO_MERMFISHER_REGEN_TIME = 480 * 3
TUNING.KYNO_MERMFISHER_AMOUNT = 2
TUNING.KYNO_MERMFISHER_ENABLED = true

TUNING.KYNO_MEADOWISLANDTRADER_RUNSPEED = 7
TUNING.KYNO_MEADOWISLANDTRADER_WALKSPEED = 4
TUNING.KYNO_MEADOWISLANDTRADER_REFRESHWARES = 480 / 1.5
TUNING.KYNO_MEADOWISLANDTRADER_UNCOMMONS_ODDS = .25
TUNING.KYNO_MEADOWISLANDTRADER_RARES_ODDS = .10
TUNING.KYNO_MEADOWISLANDTRADER_ULTRARARES_ODDS = .05

TUNING.KYNO_SAMMYHAT_PERISHTIME = 4800
TUNING.KYNO_SAMMYHAT_HUNGERRATE = .85

TUNING.KYNO_MERMCART_USES = 25
TUNING.KYNO_MERMCART_COOLDOWN = 4800
TUNING.KYNO_MERMCART_CRITTER_CHANCE = .10

TUNING.JAWSBREAKER_TAGS = {"shark", "gnarwail"} -- In case someone wants to add their mob.

TUNING.KYNO_FIREIMMUNITYBUFF_DURATION = 480 * 2

TUNING.KYNO_TIRAMISUBUFF_DURATION = 480
TUNING.KYNO_TIRAMISUBUFF_SPEED = 1.43

TUNING.KYNO_AMPHIBIANBUFF_EXTRADAMAGE = 100
TUNING.KYNO_AMPHIBIANBUFF_DURATION = 480 * 2

TUNING.KYNO_ENLIGHTENMENTBUFF_DURATION = 480

TUNING.KYNO_STEALTHBUFF_DURATION = 480

TUNING.KYNO_TRUFFLES_GROWTIME = 480 * 10
TUNING.KYNO_TRUFFLES_REGROWTH_TIME_MULT = 1
TUNING.KYNO_TRUFFLES_HEALTH = 0
TUNING.KYNO_TRUFFLES_HUNGER = 9.375
TUNING.KYNO_TRUFFLES_SANITY = -10
TUNING.KYNO_TRUFFLES_COOKED_HEALTH = 5
TUNING.KYNO_TRUFFLES_COOKED_HUNGER = 12.5
TUNING.KYNO_TRUFFLES_COOKED_SANITY = -5
TUNING.KYNO_TRUFFLES_PIG_LOYALTY_MAXTIME = 480 * 3.5

TUNING.KYNO_PLANARDEFENSEBUFF_BONUS = 10 -- Should we use multiplicative or additive? - 1.2 for mult / 10 for add
TUNING.KYNO_PLANARDEFENSEBUFF_DURATION = 480

TUNING.KYNO_CRATE_GROWTIME = 3360
TUNING.KYNO_CRATE_REGROWTH_TIME_MULT = 1

TUNING.KYNO_ISLANDCRATE_GROWTIME = 3360
TUNING.KYNO_ISLANDCRATE_REGROWTH_TIME_MULT = 1

TUNING.KYNO_CHICKEN_LAYEGG_COOLDOWN = 480

TUNING.KYNO_GROWTH_OVERSIZED_CHANCE = .20

TUNING.KYNO_SPORECAP_HEALTH = -10
TUNING.KYNO_SPORECAP_HUNGER = 12.5
TUNING.KYNO_SPORECAP_SANITY = -10
TUNING.KYNO_SPORECAP_COOKED_HEALTH = -5
TUNING.KYNO_SPORECAP_COOKED_HUNGER = 18.75
TUNING.KYNO_SPORECAP_COOKED_SANITY = -5

TUNING.KYNO_SPORECAP_DARK_HEALTH = -20
TUNING.KYNO_SPORECAP_DARK_HUNGER = 18.75
TUNING.KYNO_SPORECAP_DARK_SANITY = -20
TUNING.KYNO_SPORECAP_DARK_COOKED_HEALTH = -10
TUNING.KYNO_SPORECAP_DARK_COOKED_HUNGER = 25
TUNING.KYNO_SPORECAP_DARK_COOKED_SANITY = -10

TUNING.KYNO_SPORECAP_SPORECLOUD_CHANCE = .15

TUNING.KYNO_GOLDENAPPLE_HEALTH = 100
TUNING.KYNO_GOLDENAPPLE_HUNGER = 100
TUNING.KYNO_GOLDENAPPLE_SANITY = 100
TUNING.KYNO_GOLDENAPPLEBUFF_DURATION = 640
TUNING.KYNO_GOLDENAPPLEBUFF_SLEEPDURATION = 20

TUNING.KYNO_TRUFFLESBUFF_DURATION = 480 / 2

TUNING.KYNO_POISONIMMUNITYBUFF_DURATION = 480
TUNING.KYNO_POISONIMMUNITYALTBUFF_DURATION = 480 * 1.5

TUNING.KYNO_ACIDIMMUNITYBUFF_DURATION = 480
TUNING.KYNO_ACIDIMMUNITYALTBUFF_DURATION = 480 * 1.5

TUNING.KYNO_FISHFARMLAKE_FUEL_MAX = 480 * 2
TUNING.KYNO_FISHFARMLAKE_SECTIONS = 3
TUNING.KYNO_FISHFARMLAKE_ROE_CONSUMPTION = 10
TUNING.KYNO_FISHFARMLAKE_BABY_CONSUMPTION = 15
TUNING.KYNO_FISHFARMLAKE_PRESERVER_RATE = -1/3
TUNING.KYNO_FISHFARMLAKE_SLOT_START = 3
TUNING.KYNO_FISHFARMLAKE_SLOT_END = 8

TUNING.PONDFISH_ROETIME = 480 / 2
TUNING.PONDFISH_BABYTIME = 480 * 1.5

TUNING.PONDEEL_ROETIME = 660
TUNING.PONDEEL_BABYTIME = 480 * 2

TUNING.WOBSTER_ROETIME = 480 * 3
TUNING.WOBSTER_BABYTIME = 480 * 5

TUNING.WOBSTER_MOONGLASS_ROETIME = 480 * 2
TUNING.WOBSTER_MOONGLASS_BABYTIME = 480 * 3

TUNING.WOBSTER_MONKEYISLAND_ROETIME = 480 * 3
TUNING.WOBSTER_MONKEYISLAND_BABYTIME = 480 * 5

TUNING.NEONFISH_ROETIME = 480 * 2
TUNING.NEONFISH_BABYTIME = 480 * 3

TUNING.PIERROTFISH_ROETIME = 630
TUNING.PIERROTFISH_BABYTIME = 480 * 3

TUNING.GROUPER_ROETIME = 480 * 2
TUNING.GROUPER_BABYTIME = 480 * 3

TUNING.TROPICALFISH_ROETIME = 630
TUNING.TROPICALFISH_BABYTIME = 480 * 3

TUNING.JELLYFISH_ROETIME = 630
TUNING.JELLYFISH_BABYTIME = 480 * 3

TUNING.JELLYFISH_RAINBOW_ROETIME = 750
TUNING.JELLYFISH_RAINBOW_BABYTIME = 480 * 3 + 100

TUNING.SALMONFISH_ROETIME = 800
TUNING.SALMONFISH_BABYTIME = 480 * 3

TUNING.TROPICALKOI_ROETIME = 800
TUNING.TROPICALKOI_BABYTIME = 480 * 3

TUNING.ANTCHOVY_ROETIME = 480 / 2
TUNING.ANTCHOVY_BABYTIME = 480 / 2

TUNING.SWORDFISH_BLUE_ROETIME = 480 * 2
TUNING.SWORDFISH_BLUE_BABYTIME = 480 * 4

TUNING.OCEANFISH_SMALL_ROETIME = 480 * 2
TUNING.OCEANFISH_SMALL_BABYTIME = 480 * 3

TUNING.OCEANFISH_MEDIUM_ROETIME = 480 * 3
TUNING.OCEANFISH_MEDIUM_BABYTIME = 480 * 5

TUNING.KYNO_ANTCHOVY_MAX_FISH = 10
TUNING.KYNO_ANTCHOVY_REGROW_TIME = 50

TUNING.KYNO_ANTCHOVY_MIN_WEIGHT = 3.25
TUNING.KYNO_ANTCHOVY_MAX_WEIGHT = 5.85

TUNING.KYNO_ANTCHOVY_HEALTH = 0
TUNING.KYNO_ANTCHOVY_HUNGER = 9.375
TUNING.KYNO_ANTCHOVY_SANITY = 3

TUNING.KYNO_GROTTO_POOL_MAX_FISH = 10

TUNING.KYNO_SWORDFISH_BLUE_REGROW_TIME = 150
TUNING.KYNO_SWORDFISH_BLUE_MIN_WEIGHT = 237.21
TUNING.KYNO_SWORDFISH_BLUE_MAX_WEIGHT = 410.56

TUNING.KYNO_JELLYFISH_DAMAGE = 5 / 1.5
TUNING.KYNO_JELLYFISH_WALKSPEED = 2
TUNING.KYNO_JELLYFISH_OCEAN_HEALTH = 50
TUNING.KYNO_JELLYFISH_MIN_WEIGHT = 10.60
TUNING.KYNO_JELLYFISH_MAX_WEIGHT = 40.25
TUNING.KYNO_JELLYFISH_HEALTH = 10
TUNING.KYNO_JELLYFISH_HUNGER = 10
TUNING.KYNO_JELLYFISH_SANITY = 0
TUNING.KYNO_JELLYFISH_COOKED_HEALTH = 10
TUNING.KYNO_JELLYFISH_COOKED_HUNGER = 18.75
TUNING.KYNO_JELLYFISH_COOKED_SANITY = 0
TUNING.KYNO_JELLYFISH_DRIED_HEALTH = 15
TUNING.KYNO_JELLYFISH_DRIED_HUNGER = 25
TUNING.KYNO_JELLYFISH_DRIED_SANITY = 5
TUNING.KYNO_JELLYFISH_RELEASE_TIME = 10
TUNING.KYNO_JELLYFISH_REGEN_TIME = 960
TUNING.KYNO_JELLYFISH_AMOUNT = 4
TUNING.KYNO_JELLYFISH_RADIUS = 4
TUNING.KYNO_JELLYFISH_ENABLED = true

TUNING.KYNO_JELLYFISH_RAINBOW_WALKSPEED = 2
TUNING.KYNO_JELLYFISH_RAINBOW_OCEAN_HEALTH = 50
TUNING.KYNO_JELLYFISH_RAINBOW_MIN_WEIGHT = 15.60
TUNING.KYNO_JELLYFISH_RAINBOW_MAX_WEIGHT = 50.25
TUNING.KYNO_JELLYFISH_RAINBOW_HEALTH = 10
TUNING.KYNO_JELLYFISH_RAINBOW_HUNGER = 10
TUNING.KYNO_JELLYFISH_RAINBOW_SANITY = 10
TUNING.KYNO_JELLYFISH_RAINBOW_COOKED_HEALTH = 10
TUNING.KYNO_JELLYFISH_RAINBOW_COOKED_HUNGER = 18.75
TUNING.KYNO_JELLYFISH_RAINBOW_COOKED_SANITY = 10
TUNING.KYNO_JELLYFISH_RAINBOW_LIGHT_DURATION = 90
TUNING.KYNO_JELLYFISH_RAINBOW_LIGHT_GREATER_DURATION = 240
TUNING.KYNO_JELLYFISH_RAINBOW_LIGHT_RADIUS = 2
TUNING.KYNO_JELLYFISH_RAINBOW_RELEASE_TIME = 10
TUNING.KYNO_JELLYFISH_RAINBOW_REGEN_TIME = 1260
TUNING.KYNO_JELLYFISH_RAINBOW_AMOUNT = 3
TUNING.KYNO_JELLYFISH_RAINBOW_RADIUS = 4
TUNING.KYNO_JELLYFISH_RAINBOW_ENABLED = true

TUNING.KYNO_OCEANTRAP_USES = 10
TUNING.KYNO_OCEANTRAP_RANGE = 2

-- Ocean prefab -> Inventory prefab. This supports non inventory-able creatures too.
-- Need to make support to allow multiple prefab loot.
TUNING.HOF_OCEANTRAP_PREFAB_INDEX =
{
	cookiecutter = "kyno_mussel",
	wobster_sheller = "wobster_sheller_land",
	wobster_monkeyisland = "wobster_monkeyisland_land",
	wobster_moonglass = "wobster_moonglass_land",
	
	-- Don't let it trap jellyfishes.
	-- kyno_jellyfish_ocean = "kyno_jellyfish",
	-- kyno_jellyfish_rainbow_ocean = "kyno_jellyfish_rainbow",
}

TUNING.KYNO_OCEANFISH_PUFFERFISH_WALKSPEED = 1.5
TUNING.KYNO_OCEANFISH_PUFFERFISH_RUNSPEED = 3.0
TUNING.KYNO_OCEANFISH_PUFFERFISH_MIN_WEIGHT = 43.11
TUNING.KYNO_OCEANFISH_PUFFERFISH_MAX_WEIGHT = 64.97

TUNING.KYNO_OCEANFISH_STURGEON_WALKSPEED = 2.2
TUNING.KYNO_OCEANFISH_STURGEON_RUNSPEED = 3.5
TUNING.KYNO_OCEANFISH_STURGEON_MIN_WEIGHT = 305.37
TUNING.KYNO_OCEANFISH_STURGEON_MAX_WEIGHT = 412.11

TUNING.KYNO_SWORDFISH_TARGET_DIST = 10
TUNING.KYNO_SWORDFISH_SHARE_TARGET_DIST = 20
TUNING.KYNO_SWORDFISH_CHASE_DIST = 20
TUNING.KYNO_SWORDFISH_WALKSPEED = 5
TUNING.KYNO_SWORDFISH_RUNSPEED = 8
TUNING.KYNO_SWORDFISH_HEALTH = 500
TUNING.KYNO_SWORDFISH_DAMAGE = 50
TUNING.KYNO_SWORDFISH_HULLDAMAGE = 25
TUNING.KYNO_SWORDFISH_ATTACK_PERIOD = 2
TUNING.KYNO_SWORDFISH_SPAWN_TIME = 480
TUNING.KYNO_SWORDFISH_ENABLED = true

TUNING.KYNO_SWORDFISH_DEAD_HEALTH = 16
TUNING.KYNO_SWORDFISH_DEAD_HUNGER = 37.5
TUNING.KYNO_SWORDFISH_DEAD_SANITY = 0

TUNING.KYNO_PUFFERMONSTER_TARGET_DIST = 20
TUNING.KYNO_PUFFERMONSTER_SHARE_TARGET_DIST = 20
TUNING.KYNO_PUFFERMONSTER_CHASE_DIST = 20
TUNING.KYNO_PUFFERMONSTER_WALKSPEED = 3
TUNING.KYNO_PUFFERMONSTER_RUNSPEED = 4
TUNING.KYNO_PUFFERMONSTER_HEALTH = 350
TUNING.KYNO_PUFFERMONSTER_DAMAGE = 30
TUNING.KYNO_PUFFERMONSTER_HULLDAMAGE = 15
TUNING.KYNO_PUFFERMONSTER_ATTACK_PERIOD = 3
TUNING.KYNO_PUFFERMONSTER_RANGE = 3
TUNING.KYNO_PUFFERMONSTER_AOE_RANGE = 3
TUNING.KYNO_PUFFERMONSTER_AOE_SCALE = 1
TUNING.KYNO_PUFFERMONSTER_SPAWN_TIME = 480
TUNING.KYNO_PUFFERMONSTER_ENABLED = true

TUNING.KYNO_DOGFISH_AVOID_DIST = 6
TUNING.KYNO_DOGFISH_AVOID_DIST_STOP = 8
TUNING.KYNO_DOGFISH_WANDER_DIST = 15
TUNING.KYNO_DOGFISH_WALKSPEED = 4
TUNING.KYNO_DOGFISH_RUNSPEED = 6
TUNING.KYNO_DOGFISH_HEALTH = 250
TUNING.KYNO_DOGFISH_SPAWN_TIME = 480 * 4
TUNING.KYNO_DOGFISH_ENABLED = true

TUNING.KYNO_DOGFISH_DEAD_HEALTH = 8
TUNING.KYNO_DOGFISH_DEAD_HUNGER = 25
TUNING.KYNO_DOGFISH_DEAD_SANITY = 0

TUNING.KYNO_WOBSTER_MONKEYISLAND_MIN_WEIGHT = 153.67
TUNING.KYNO_WOBSTER_MONKEYISLAND_MAX_WEIGHT = 307.34
TUNING.KYNO_WOBSTER_MONKEYISLAND_DEAD_HEALTH = 3
TUNING.KYNO_WOBSTER_MONKEYISLAND_DEAD_HUNGER = 12.5
TUNING.KYNO_WOBSTER_MONKEYISLAND_DEAD_SANITY = 5
TUNING.KYNO_WOBSTER_MONKEYISLAND_DEAD_COOKED_HEALTH = 9
TUNING.KYNO_WOBSTER_MONKEYISLAND_DEAD_COOKED_HUNGER = 18.75
TUNING.KYNO_WOBSTER_MONKEYISLAND_DEAD_COOKED_SANITY = 5

TUNING.KYNO_WOBSTER_MONKEYISLAND_DEN_SPAWN_TIME = 100 
TUNING.KYNO_WOBSTER_MONKEYISLAND_DEN_REGEN_TIME = 150
TUNING.KYNO_WOBSTER_MONKEYISLAND_DEN_AMOUNT = 2
TUNING.KYNO_WOBSTER_MONKEYISLAND_DEN_RADIUS = 4
TUNING.KYNO_WOBSTER_MONKEYISLAND_DEN_ENABLED = true

TUNING.KYNO_WHALE_WAKE_TO_RUN_DISTANCE = 10
TUNING.KYNO_WHALE_SLEEP_NEAR_ENEMY_DISTANCE = 14
TUNING.KYNO_WHALE_ATTACK_PERIOD = 3.5
TUNING.KYNO_WHALE_BOAT_PUSH = 0.75
TUNING.KYNO_WHALE_PIRATE_CHANCE = 0.10
TUNING.KYNO_WHALE_ENEMY_CHANCE = 0.30
TUNING.KYNO_WHALE_SHARK_CHANCE = 0.40
TUNING.KYNO_WHALE_EXPLOSION_CHOPS = 3

TUNING.KYNO_WHALE_BLUE_CHASE_DIST = 20
TUNING.KYNO_WHALE_BLUE_TARGET_DIST = 10
TUNING.KYNO_WHALE_BLUE_FOLLOW_TIME = 60
TUNING.KYNO_WHALE_BLUE_WALKSPEED = 4 * 0.5
TUNING.KYNO_WHALE_BLUE_RUNSPEED = 4
TUNING.KYNO_WHALE_BLUE_HEALTH = 1300
TUNING.KYNO_WHALE_BLUE_DAMAGE = 50
TUNING.KYNO_WHALE_BLUE_HULLDAMAGE = 25
TUNING.KYNO_WHALE_BLUE_EXPLOSION_CHOPS = 3
TUNING.KYNO_WHALE_BLUE_EXPLOSION_DAMAGE = 25

TUNING.KYNO_WHALE_WHITE_CHASE_DIST = 30
TUNING.KYNO_WHALE_WHITE_TARGET_DIST = 15
TUNING.KYNO_WHALE_WHITE_FOLLOW_TIME = 90
TUNING.KYNO_WHALE_WHITE_WALKSPEED = 5 * 0.5
TUNING.KYNO_WHALE_WHITE_RUNSPEED = 5
TUNING.KYNO_WHALE_WHITE_HEALTH = 1600
TUNING.KYNO_WHALE_WHITE_DAMAGE = 75
TUNING.KYNO_WHALE_WHITE_HULLDAMAGE = 37.5
TUNING.KYNO_WHALE_WHITE_EXPLOSION_CHOPS = 4
TUNING.KYNO_WHALE_WHITE_EXPLOSION_DAMAGE = 50

TUNING.KYNO_WHALE_ROT_TIME = 
{
	{ base = 2 * TUNING.TOTAL_DAY_TIME, random = 0.5 * TUNING.TOTAL_DAY_TIME },
	{ base = 2 * TUNING.TOTAL_DAY_TIME, random = 0.5 * TUNING.TOTAL_DAY_TIME },
	{ base = 1 * TUNING.TOTAL_DAY_TIME, random = 0.5 * TUNING.TOTAL_DAY_TIME },
}

-- Public loot tables for Whales in case someone wants it.
TUNING.HOF_WHALE_BLUE_LOOT = 
{
	"fishmeat",
	"fishmeat",
	"fishmeat",
	"fishmeat",

	"kyno_blubber",
	"kyno_blubber",
	"kyno_blubber",
	"kyno_blubber",
}

TUNING.HOF_WHALE_WHITE_LOOT =
{
	"fishmeat",
	"fishmeat",
	"fishmeat",
	"fishmeat",
	
	"boneshard",
	
	"kyno_blubber",
	"kyno_blubber",
	"kyno_blubber",
	"kyno_blubber",
}

TUNING.HOF_WHALE_LOOT =
{
	-- High Tier
	{
		"bullkelp_root",
		"monkey_mediumhat",
		"polly_rogershat",
		"stash_map",
		"chum",
		"messagebottle",
	},
	
	-- Medium Tier
	{
		"wobster_sheller_dead",
		"wobster_monkeyisland_dead",
		"oceanfishinglure_hermit_heavy",
		"waterplant_planter",
		"monkey_smallhat",
		"messagebottle",
		"puffin",
		"kyno_kokonut",
		"kyno_oceantrap",
		"kyno_dogfish_dead",
    },
	
	-- Low Tier
	{
		"kelp",
		"fishmeat",
		"boneshard",
		"kyno_seaweeds",
		"kyno_jellyfish",
		"kyno_blubber",
		"kyno_spoiled_fish_large",
	},
}

TUNING.WATERFOWLHUNT_ALTERNATE_BEAST_CHANCE_MIN = 0.05
TUNING.WATERFOWLHUNT_ALTERNATE_BEAST_CHANCE_MAX = 0.33
TUNING.WATERFOWLHUNT_SPAWN_DIST = 20
TUNING.WATERFOWLHUNT_BEAST_SPAWN_DIST = 30
TUNING.WATERFOWLHUNT_COOLDOWN = 480 * 1.5
TUNING.WATERFOWLHUNT_COOLDOWN_DEVIATION = 480 * 0.3
TUNING.WATERFOWLHUNT_MIN_TRACKS = 4
TUNING.WATERFOWLHUNT_MAX_TRACKS = 8
TUNING.WATERFOWLHUNT_RESET_TIME = 5
TUNING.WATERFOWLHUNT_TRACK_ANGLE_DEVIATION = 15
TUNING.WATERFOWLHUNT_MIN_DISTANCE = 300
TUNING.WATERFOWLHUNT_MAX_DISTANCE = 200

TUNING.KYNO_BLUBBLER_HEALTH = 10
TUNING.KYNO_BLUBBLER_HUNGER = 10
TUNING.KYNO_BLUBBLER_SANITY = 0
TUNING.KYNO_BLUBBLER_MOISTURE = -10

TUNING.KYNO_FISHMEAT_SMALL_DRIED_HEALTH = 25
TUNING.KYNO_FISHMEAT_SMALL_DRIED_HUNGER = 20
TUNING.KYNO_FISHMEAT_SMALL_DRIED_SANITY = 15

TUNING.KYNO_FISHMEAT_DRIED_HEALTH = 40
TUNING.KYNO_FISHMEAT_DRIED_HUNGER = 35
TUNING.KYNO_FISHMEAT_DRIED_SANITY = 25

TUNING.KYNO_BRAINROCK_ROCK_MINE = 6
TUNING.KYNO_BRAINROCK_ROCK_GROWTIME = 480 * 10
TUNING.KYNO_BRAINROCK_ROCK_REGROWTH_TIME_MULT = 1
TUNING.KYNO_BRAINROCK_ROCK_SPROUT_GROWTIME = 480 * 3

TUNING.KYNO_BRAINROCK_CORAL_HEALTH = -10
TUNING.KYNO_BRAINROCK_CORAL_HUNGER = 10
TUNING.KYNO_BRAINROCK_CORAL_SANITY = 50

TUNING.KYNO_CRAFTINGBUFF_DURATION = 240
TUNING.KYNO_CRAFTINGBUFF_SANITY_PENALTY = -10

TUNING.OCTOPUS_VALUES = 
{
	SEAFOOD          = 1 + 3,
	SEAFOOD_RARE     = 5 + 3,

	TRINKETS         = 
	{
		-- RoG Trinkets 1-12
		6 + 3, 8 + 3, 6 + 3, 7 + 3, 6 + 3, 7 + 3, 
		6 + 3, 9 + 3, 9 + 3, 4 + 3, 7 + 3, 9 + 3, 
		
		-- DST Trinkets 13+
		7 + 3, 4 + 3, 4 + 3, 2 + 3, 6 + 3, 6 + 3,
		7 + 3, 5 + 3, 4 + 3, 3 + 3, 8 + 3, 2 + 3,
		9 + 3, 4 + 3, 4 + 3, 4 + 3, 4 + 3, 4 + 3,
		1 + 3, 1 + 3, 1 + 3, 1 + 3, 1 + 3, 1 + 3,
	},

	ANTLIONTRINKET   = 8,
	COTLTRINKET      = 8,
	BOTTLECAPTRINKET = 25,
}

TUNING.OCTOPUSKING_OCEAN_LOOT = 
{
	randomchestloot =
	{
		"kyno_seaweeds",
		"kyno_seaweeds",
		"kyno_seaweeds",
		"kyno_seaweeds",
		"kyno_seaweeds",
		"kyno_waterycress",
		"kyno_waterycress",
		"kyno_waterycress",
		"kelp",
		"kelp",
		"kelp",
		"kyno_shark_fin",
		"kyno_blubber",
		"fireflies",
		"fireflies",
		"saltrock",
		"saltrock",
	},
	
	chestloot =
	{
		agedroe_oceanfish_sturgeon = { prefab = "messagebottle",         amount = 2 },
		barnaclepita               = { prefab = "waterplant_planter",    amount = 1 },
		barnaclestuffedfishhead    = { prefab = "bullkelp_root",         amount = 2 },
		barnaclesushi              = { prefab = "dug_trap_starfish",     amount = 1 },
		barnaclinguine             = { prefab = "megaflare",             amount = 1 },
		bisque                     = { prefab = "boatpatch",             amount = 5 },
		californiaroll             = { prefab = "anchor_item",           amount = 1 },
		ceviche                    = { prefab = "flotationcushion",      amount = 1 },
		crabkingfeast              = { prefab = "nukashine_sugarfree",   amount = 1 },
		eeltacos                   = { prefab = "monkey_mediumhat",      amount = 1 },
		festive_pickledherring     = { prefab = "telestaff",             amount = 1 },
		fishsticks                 = { prefab = "kyno_beancan",          amount = 3 },
		fishtacos                  = { prefab = "raincoat",              amount = 1 },
		gorge_candiedfish          = { prefab = "honeycomb",             amount = 2 },
		gorge_crab_cake            = { prefab = "molehat",               amount = 1 },
		gorge_crab_ravioli         = { prefab = "saddle_race",           amount = 1 },
		gorge_crab_roll            = { prefab = "treegrowthsolution",    amount = 3 },
		gorge_creamy_fish          = { prefab = "kyno_cokecan",          amount = 3 },
		gorge_fish_steak           = { prefab = "purpleamulet",          amount = 1 },
		gorge_fish_stew            = { prefab = "kyno_energycan",        amount = 3 },
		gorge_fishchips            = { prefab = "blueamulet",            amount = 1 },
		gorge_fishpie              = { prefab = "kyno_sodacan",          amount = 3 },
		gorge_poachedfish          = { prefab = "kyno_meatcan",          amount = 3 },
		jellyopop                  = { prefab = "kyno_oceantrap",        amount = 1 },
		lobsterbisque              = { prefab = "kyno_brainrock_larvae", amount = 1 },
		lobsterdinner              = { prefab = "boat_bumper_shell_kit", amount = 8 },
		musselbouillabaise         = { prefab = "panflute",              amount = 1 },
		seafoodgumbo               = { prefab = "mast_item",             amount = 1 },
		sharksushi                 = { prefab = "gnarwail_horn",         amount = 1 },
		surfnturf                  = { prefab = "ocean_trawler_kit",     amount = 1 },
		swordfishfeast             = { prefab = "kyno_malbatrossfood",   amount = 3 },
		tropicalbouillabaisse      = { prefab = "saddle_war",            amount = 1 },
		unagi                      = { prefab = "monkey_smallhat",       amount = 1 },
		wobsterbreaded             = { prefab = "antliontrinket",        amount = 1 },
		wobstercocktail            = { prefab = "kyno_tomatocan",        amount = 3 },
	},
}

TUNING.KYNO_PACKIMBAGGIMS_HEALTH = 450
TUNING.KYNO_PACKIMBAGGIMS_REGEN_AMOUNT = 22.5
TUNING.KYNO_PACKIMBAGGIMS_REGEN_PERIOD = 3
TUNING.KYNO_PACKIMBAGGIMS_WALKSPEED = 8
TUNING.KYNO_PACKIMBAGGIMS_SPAWN_DIST = 30
TUNING.KYNO_PACKIMBAGGIMS_RESPAWN_TIME = 480 * 1

TUNING.KYNO_PACKIMBAGGIMS_CHARCOAL_ITEMS =
{
	"log",
	"driftwood_log",
	"livinglog",
	"boards",
	"boat_item",
	"boat_ancient_item",
	"boatpatch",
	"dock_woodposts_item",
	"wall_wood_item",
	"turf_woodfloor",
	"dock_kit",
}

TUNING.KYNO_BEEFRIENDLYBUFF_DURATION = 480 * 1.5

TUNING.HOFBIRTHDAY_CAKE_CONSTRUCTION_LOOT =
{
	"log",
	"log",
	"twigs",
	"twigs",
}

-- These are recipes that won't give you Anniversary Cheer.
TUNING.HOFBIRTHDAY_BLOCKED_RECIPES =
{
	beefalofeed   = true,
	duckyouglermz = true,
	dustmeringue  = true,
	gorge_bread   = true,
	littlebread   = true,
	watercup      = true,
	wetgoop       = true,
	wetgoop2      = true,
}

TUNING.HOFBIRTHDAY_CHEER_CHANCE = 1.00--0.20
TUNING.HOFBIRTHDAY_CAKE_USES = 30

TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE1_HEALTH = 10
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE1_HUNGER = 32.5
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE1_SANITY = 5
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE1_BONUS = 15
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE1_DURATION = 480 / 2

TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE2_HEALTH = 30
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE2_HUNGER = 12.5
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE2_SANITY = 10
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE2_BONUS = 15
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE2_DURATION = 480 / 2

TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE3_HEALTH = 5
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE3_HUNGER = 18.75
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE3_SANITY = 30
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE3_BONUS = 15
TUNING.KYNO_HOFBIRTHDAY_CAKE_SLICE3_DURATION = 480 / 2

TUNING.KYNO_HOFBIRTHDAY_POPCORN_HEALTH = 5
TUNING.KYNO_HOFBIRTHDAY_POPCORN_HUNGER = 12.5
TUNING.KYNO_HOFBIRTHDAY_POPCORN_SANITY = 15

TUNING.KYNO_HOFBIRTHDAY_POPCORNMACHINE_SECTIONS = 3
TUNING.KYNO_HOFBIRTHDAY_POPCORNMACHINE_FUEL_MAX = 800
TUNING.KYNO_HOFBIRTHDAY_POPCORNMACHINE_INTERVAL = 10
TUNING.KYNO_HOFBIRTHDAY_POPCORNMACHINE_CONSUME_FUEL = -20
TUNING.KYNO_HOFBIRTHDAY_POPCORNMACHINE_CONSUME_CORN = 5

TUNING.KYNO_MEADOWISLAND_POND_TICK_PERIOD = 5
TUNING.KYNO_MEADOWISLAND_POND_BATHBOMB_DURATION = 480 / 2
TUNING.KYNO_MEADOWISLAND_POND_HEALTH_PER_SECOND = 1
TUNING.KYNO_MEADOWISLAND_POND_SANITY_PER_SECOND = 1

TUNING.KYNO_WINTERTREE_GIFT1 =
{
	moonrocknugget = 2.0,
	gears          = 1.0,
	compass        = 0.3,
	sewing_kit     = 0.2,

	redgem         = 0.2,
	bluegem        = 0.2,
	greengem       = 0.1,
	orangegem      = 0.1,
	yellowgem      = 0.1,

	beefalohat     = 0.5,
	winterhat      = 0.5,
	earmuffshat    = 0.5,
	catcoonhat     = 0.5,
	molehat        = 0.5,
}

TUNING.KYNO_WINTERTREE_GIFT2 =
{
	gears               = 0.2,
	moonrocknugget      = 0.2,

	redgem              = 0.1,
	bluegem             = 0.1,
	greengem            = 0.1,
	orangegem           = 0.1,
	yellowgem           = 0.1,

	walrushat           = 0.2,
	cane                = 0.2,
	panflute            = 0.1,
	nukashine_sugarfree = 0.1,
}

TUNING.KYNO_WINTERTREE_GIFT3 =
{
	festive_berrysauce     = 0.3,
	festive_bibingka       = 0.3,
	festive_cabbagerolls   = 0.3,
	festive_fishdish       = 0.3,
	festive_goodgravy      = 0.3,
	festive_latkes         = 0.3,
	festive_lutefisk       = 0.3,
	festive_mulledpunch    = 0.3,
	festive_panettone      = 0.3,
	festive_pavlova        = 0.3,
	festive_pickledherring = 0.3,
	festive_polishcookies  = 0.3,
	festive_pumpkinpie     = 0.3,
	festive_roastedturkey  = 0.3,
	festive_stuffing       = 0.3,
	festive_sweetpotato    = 0.3,
	festive_tamales        = 0.3,
	festive_tourtiere      = 0.3,
}