-- Mod Tunings.
TUNING.HOF_RESOURCES = .06
TUNING.HOF_RETROFIT = GetModConfigData("RETROFIT") or 0
TUNING.HOF_RETROFIT_FORCE = GetModConfigData("RETROFIT_FORCE") or false
TUNING.HOF_FLOATER = {"med", nil, 0.65}

TUNING.HOF_MIN_OCEANSETPIECES = 2
TUNING.HOF_MAX_OCEANSETPIECES = 4

TUNING.HOF_COOKPOTS =
{
	"cookpot",
	"portablecookpot",
	"archive_cookpot",
	"portablespicer",
	
	"kyno_cookware_syrup",
	"kyno_cookware_small",
	"kyno_cookware_big",
	"kyno_cookware_elder",
	"kyno_cookware_small_grill",
	"kyno_cookware_grill",
	"kyno_cookware_oven_small_casserole",
	"kyno_cookware_oven_casserole",
}

TUNING.HOF_MEATRACKS = 
{	
	"meatrack", 
	"meatrack_hermit"
}

TUNING.KYNO_FLOATILIZER_USES = 20
TUNING.KYNO_FLOATILIZER_SOILCYCLES = TUNING.POOP_SOILCYCLES
TUNING.KYNO_FLOATILIZER_FERTILIZE = TUNING.POOP_FERTILIZE * 2
TUNING.KYNO_FLOATILIZER_WITHEREDCYCLES = TUNING.POOP_WITHEREDCYCLES
TUNING.KYNO_FLOATILIZER_NUTRIENTS = { 16,  16,  16 }

TUNING.ASH_NUTRIENTS = { 4,  4,  0 }

TUNING.KYNO_MYSTERYMEAT_NUTRIENTS = { 16, 0, 16 }

TUNING.KYNO_SAP_SPOILED_NUTRIENTS = { 8, 0, 8 }

TUNING.WETGOOP2_NUTRIENTS = { 32, 8, 8 }

TUNING.DUCKYOUGLERMZ_NUTRIENTS = { 24, 24, 24 }

TUNING.DUCKYOUGLERMZ_NUTRIENTS_INDEX = 4

TUNING.KYNO_BANANATREE_GROWTIME = 480 * 4
TUNING.KYNO_BANANATREE_WORKLEFT = 3
TUNING.KYNO_BANANATREE_STUMP_WORKLEFT = 1

TUNING.KYNO_BANANA_HEALTH = 1
TUNING.KYNO_BANANA_HUNGER = 12.5
TUNING.KYNO_BANANA_SANITY = 0
TUNING.KYNO_BANANA_COOKED_HEALTH = 3
TUNING.KYNO_BANANA_COOKED_HUNGER = 12.5
TUNING.KYNO_BANANA_COOKED_SANITY = 0

TUNING.KYNO_BUCKET_EMPTY_USES = 10
TUNING.KYNO_BUCKET_WATER_USES = 20
TUNING.KYNO_BUCKET_WATER_AMOUNT = 25 / 2
TUNING.KYNO_BUCKET_WATER_EXTINGUISH_HEAT_PERCENT = -1
TUNING.KYNO_BUCKET_WATER_TEMP_REDUCTION = 5 / 2
TUNING.KYNO_BUCKET_WATER_PROTECTION_TIME = 30 / 2
TUNING.KYNO_BUCKET_WATER_PROTECTION_DIST = 2.25 / 2

TUNING.KYNO_BEANBUGS_HEALTH = 0
TUNING.KYNO_BEANBUGS_HUNGER = 9.375
TUNING.KYNO_BEANBUGS_SANITY = -10
TUNING.KYNO_BEANBUGS_COOKED_HEALTH = 1
TUNING.KYNO_BEANBUGS_COOKED_HUNGER = 12.5
TUNING.KYNO_BEANBUGS_COOKED_SANITY = -5

TUNING.KYNO_TOMATOCAN_HEALTH = 12.5
TUNING.KYNO_TOMATOCAN_HUNGER = 20 
TUNING.KYNO_TOMATOCAN_SANITY = 0

TUNING.KYNO_BEANCAN_HEALTH = 0
TUNING.KYNO_BEANCAN_HUNGER = 20 
TUNING.KYNO_BEANCAN_SANITY = 10 

TUNING.KYNO_MEATCAN_HEALTH = 5
TUNING.KYNO_MEATCAN_HUNGER = 25 
TUNING.KYNO_MEATCAN_SANITY = 0 

TUNING.KYNO_CHICKEN2_HEALTH = 75
TUNING.KYNO_CHICKEN_RELEASE_TIME = 10
TUNING.KYNO_CHICKEN_REGEN_TIME = 960
TUNING.KYNO_CHICKEN_AMOUNT = 3
TUNING.KYNO_CHICKEN_ENABLED = true

TUNING.KYNO_CHICKEN_EGG_HEALTH = 2
TUNING.KYNO_CHICKEN_EGG_HUNGER = 9.375
TUNING.KYNO_CHICKEN_EGG_SANITY = 0
TUNING.KYNO_CHICKEN_EGG_COOKED_HEALTH = 3
TUNING.KYNO_CHICKEN_EGG_COOKED_HUNGER = 12.5
TUNING.KYNO_CHICKEN_EGG_COOKED_SANITY = 0

TUNING.KYNO_COFFEEBUFF_SPEED = 1.83 -- GetModConfigData("HOF_COFFEESPEEDMULTIPLIER")
TUNING.KYNO_COFFEEBUFF_DURATION_SMALL = 30
TUNING.KYNO_COFFEEBUFF_DURATION_MEDSMALL = 240
TUNING.KYNO_COFFEEBUFF_DURATION_MED = 480
TUNING.KYNO_COFFEEBUFF_DURATION_LARGE = 640
TUNING.KYNO_COFFEEBUFF_DURATION_MEDLARGE = 960
TUNING.KYNO_COFFEEBUFF_DURATION_HUGE = 1920

TUNING.KYNO_COFFEEBEANS_HEALTH = 0
TUNING.KYNO_COFFEEBEANS_HUNGER = 9.375
TUNING.KYNO_COFFEEBEANS_SANITY = 0
TUNING.KYNO_COFFEEBEANS_COOKED_HEALTH = 0
TUNING.KYNO_COFFEEBEANS_COOKED_HUNGER = 9.375
TUNING.KYNO_COFFEEBEANS_COOKED_SANITY = -5

TUNING.KYNO_SALTRACK_REGROW_TIME = 1920

TUNING.KYNO_COOKWARE_COOKTIMEMULT = .5
TUNING.KYNO_COOKWARE_COOKTIMEMULT_SYRUP = .3
TUNING.KYNO_COOKWARE_BONUSHARVEST = 2
TUNING.KYNO_COOKWARE_BONUSHARVEST_SYRUP = 3 -- 3 to keep consistent with 2 from cooking pot.

TUNING.KYNO_DMGREDUCTIONBUFF_SPEED = .70
TUNING.KYNO_ALCOHOL_SPEED = .70
TUNING.KYNO_ALCOHOL_DURATION_SMALL = 480
TUNING.KYNO_ALCOHOL_DURATION_MEDSMALL = 520
TUNING.KYNO_ALCOHOL_STRENGTH_SMALL = 1.2
TUNING.KYNO_ALCOHOL_STRENGTH_MEDSMALL = 1.5

TUNING.KYNO_FISH_LARGE_HEALTH = 4
TUNING.KYNO_FISH_LARGE_HUNGER = 25
TUNING.KYNO_FISH_LARGE_SANITY = 0

TUNING.KYNO_FISH_LARGE_COOKED_HEALTH = 8
TUNING.KYNO_FISH_LARGE_COOKED_HUNGER = 25
TUNING.KYNO_FISH_LARGE_COOKED_SANITY = 5

TUNING.KYNO_FISH_SMALL_HEALTH = 1
TUNING.KYNO_FISH_SMALL_HUNGER = 12.5
TUNING.KYNO_FISH_SMALL_SANITY = 0

TUNING.KYNO_FISH_SMALL_COOKED_HEALTH = 3
TUNING.KYNO_FISH_SMALL_COOKED_HUNGER = 12.5
TUNING.KYNO_FISH_SMALL_COOKED_SANITY = 1

TUNING.KYNO_HASTEBUFF_DURATION = 480

TUNING.KYNO_WHEAT_HEALTH = 0
TUNING.KYNO_WHEAT_HUNGER = 4.6875
TUNING.KYNO_WHEAT_SANITY = 0
TUNING.KYNO_WHEAT_COOKED_HEALTH = 1
TUNING.KYNO_WHEAT_COOKED_HUNGER = 4.6875
TUNING.KYNO_WHEAT_COOKED_SANITY = 0

TUNING.KYNO_SAP_HEALTH = 1
TUNING.KYNO_SAP_HUNGER = 3 
TUNING.KYNO_SAP_SANITY = 0

TUNING.KYNO_SYRUP_HEALTH = 3 
TUNING.KYNO_SYRUP_HUNGER = 9.375
TUNING.KYNO_SYRUP_SANITY = 0

TUNING.KYNO_SPOTSPICE_LEAF_HEALTH = 0
TUNING.KYNO_SPOTSPICE_LEAF_HUNGER = 4.6875
TUNING.KYNO_SPOTSPICE_LEAF_SANITY = 0 

TUNING.KYNO_BACON_HEALTH = 0
TUNING.KYNO_BACON_HUNGER = 12.5
TUNING.KYNO_BACON_SANITY = -10
TUNING.KYNO_BACON_COOKED_HEALTH = 3
TUNING.KYNO_BACON_COOKED_HUNGER = 12.5
TUNING.KYNO_BACON_COOKED_SANITY = 5

TUNING.KYNO_WHITE_CAP_HEALTH = -10
TUNING.KYNO_WHITE_CAP_HUNGER = 9.375
TUNING.KYNO_WHITE_CAP_SANITY = 0
TUNING.KYNO_WHITE_CAP_COOKED_HEALTH = -5
TUNING.KYNO_WHITE_CAP_COOKED_HUNGER = 12.5
TUNING.KYNO_WHITE_CAP_COOKED_SANITY = 0

TUNING.KYNO_FOLIAGE_HEALTH = 1
TUNING.KYNO_FOLIAGE_HUNGER = 0
TUNING.KYNO_FOLIAGE_SANITY = 0
TUNING.KYNO_FOLIAGE_COOKED_HEALTH = 1 
TUNING.KYNO_FOLIAGE_COOKED_HUNGER = 1 
TUNING.KYNO_FOLIAGE_COOKED_SANITY = 0

TUNING.KYNO_CRABMEAT_HEALTH = 5 
TUNING.KYNO_CRABMEAT_HUNGER = 5 
TUNING.KYNO_CRABMEAT_SANITY = -10 
TUNING.KYNO_CRABMEAT_COOKED_HEALTH = 10 
TUNING.KYNO_CRABMEAT_COOKED_HUNGER = 10 
TUNING.KYNO_CRABMEAT_COOKED_SANITY = 5
TUNING.KYNO_CRABMEAT_DRIED_HEALTH = 25
TUNING.KYNO_CRABMEAT_DRIED_HUNGER = 25
TUNING.KYNO_CRABMEAT_DRIED_SANITY = 10

TUNING.KYNO_CRABKINGMEAT_HEALTH = -10
TUNING.KYNO_CRABKINGMEAT_HUNGER = 10
TUNING.KYNO_CRABKINGMEAT_SANITY = -10
TUNING.KYNO_CRABKINGMEAT_COOKED_HEALTH = 20
TUNING.KYNO_CRABKINGMEAT_COOKED_HUNGER = 20
TUNING.KYNO_CRABKINGMEAT_COOKED_SANITY = 0
TUNING.KYNO_CRABKINGMEAT_DRIED_HEALTH = 40
TUNING.KYNO_CRABKINGMEAT_DRIED_HUNGER = 40
TUNING.KYNO_CRABKINGMEAT_DRIED_SANITY = 20

TUNING.KYNO_HUMANMEAT_HEALTH = -20 
TUNING.KYNO_HUMANMEAT_HUNGER = 12.5
TUNING.KYNO_HUMANMEAT_SANITY = -33
TUNING.KYNO_HUMANMEAT_COOKED_HEALTH = -3
TUNING.KYNO_HUMANMEAT_COOKED_HUNGER = 18.75
TUNING.KYNO_HUMANMEAT_COOKED_SANITY = -20
TUNING.KYNO_HUMANMEAT_DRIED_HEALTH = -3 
TUNING.KYNO_HUMANMEAT_DRIED_HUNGER = 25
TUNING.KYNO_HUMANMEAT_DRIED_SANITY = -15

TUNING.KYNO_KOKONUT_HEALTH = 1 
TUNING.KYNO_KOKONUT_HUNGER = 4.6875 
TUNING.KYNO_KOKONUT_SANITY = 0
TUNING.KYNO_KOKONUT_COOKED_HEALTH = 3
TUNING.KYNO_KOKONUT_COOKED_HUNGER = 9.375
TUNING.KYNO_KOKONUT_COOKED_SANITY = 0 

TUNING.KYNO_KOKONUTTREE_GROWTIME = 480 * 5
TUNING.KYNO_KOKONUTTREE_REGROWTH_TIME_MULT = 1
TUNING.KYNO_KOKONUTTREE_SHORT_WORKLEFT = 5
TUNING.KYNO_KOKONUTTREE_NORMAL_WORKLEFT = 10
TUNING.KYNO_KOKONUTTREE_TALL_WORKLEFT = 15
TUNING.KYNO_KOKONUTTREE_STUMP_WORKLEFT = 1
TUNING.KYNO_KOKONUTTREE_KOKONUT_CHANCE = 0.03
TUNING.KYNO_KOKONUTTREE_REGROWTH_TIME = 480 * 3

TUNING.KYNO_LIMPETROCK_GROWTIME = 1440
TUNING.KYNO_LIMPETROCK_REGROWTH_TIME_MULT = 1

TUNING.KYNO_LIMPETS_HEALTH = 0 
TUNING.KYNO_LIMPETS_HUNGER = 12.5
TUNING.KYNO_LIMPETS_SANITY = -10
TUNING.KYNO_LIMPETS_COOKED_HEALTH = 1 
TUNING.KYNO_LIMPETS_COOKED_HUNGER = 12.5
TUNING.KYNO_LIMPETS_COOKED_SANITY = 0

TUNING.KYNO_LOTUS_GROWTIME = 480 * 3
TUNING.KYNO_LOTUS_REGROWTH_TIME_MULT = 1

TUNING.KYNO_LOTUS_HEALTH = 1
TUNING.KYNO_LOTUS_HUNGER = 12.5
TUNING.KYNO_LOTUS_SANITY = 5
TUNING.KYNO_LOTUS_COOKED_HEALTH = 3
TUNING.KYNO_LOTUS_COOKED_HUNGER = 12.5
TUNING.KYNO_LOTUS_COOKED_SANITY = 15

TUNING.KYNO_MEALGRINDER_WORKLEFT = 4

TUNING.KYNO_MILK_BEEFALO_HEALTH = 3
TUNING.KYNO_MILK_BEEFALO_HUNGER = 3
TUNING.KYNO_MILK_BEEFALO_SANITY = -10

TUNING.KYNO_MILK_KOALEFANT_HEALTH = 6
TUNING.KYNO_MILK_KOALEFANT_HUNGER = 6
TUNING.KYNO_MILK_KOALEFANT_SANITY = -10

TUNING.KYNO_MILK_DEER_HEALTH = 0 
TUNING.KYNO_MILK_DEER_HUNGER = 5 
TUNING.KYNO_MILK_DEER_SANITY = -10

TUNING.KYNO_MILK_SPAT_HEALTH = 8 
TUNING.KYNO_MILK_SPAT_HUNGER = 8 
TUNING.KYNO_MILK_SPAT_SANITY = -20

TUNING.KYNO_MUSHSTUMP_GROWTIME = 480 * 5
TUNING.KYNO_MUSHSTUMP_REGROWTH_TIME_MULT = 1
TUNING.KYNO_MUSHSTUMP_WORKLEFT = 1

TUNING.KYNO_MUSSEL_HEALTH = 0
TUNING.KYNO_MUSSEL_HUNGER = 12.5
TUNING.KYNO_MUSSEL_SANITY = -15 
TUNING.KYNO_MUSSEL_COOKED_HEALTH = 1
TUNING.KYNO_MUSSEL_COOKED_HUNGER = 12.5
TUNING.KYNO_MUSSEL_COOKED_SANITY = 0

TUNING.KYNO_MUSSELSTICK_GROWTIME = 1440
TUNING.KYNO_MUSSELSTICK_WORKLEFT = 4

TUNING.KYNO_MYSTERYMEAT_HEALTH = -1
TUNING.KYNO_MYSTERYMEAT_HUNGER = -10
TUNING.KYNO_MYSTERYMEAT_SANITY = 0

TUNING.KYNO_OCEANWRECK_WORKLEFT = 4
TUNING.KYNO_OCEAN_WRECK_GROWTIME = 1440
TUNING.KYNO_OCEAN_WRECK_REGROWTH_TIME_MULT = 1

TUNING.KYNO_SODACAN_HEALTH = -8
TUNING.KYNO_SODACAN_HUNGER = 0
TUNING.KYNO_SODACAN_SANITY = 33

TUNING.KYNO_COKECAN_HEALTH = -8
TUNING.KYNO_COKECAN_HUNGER = 0
TUNING.KYNO_COKECAN_SANITY = 33

TUNING.KYNO_ENERGYCAN_HEALTH = -8
TUNING.KYNO_ENERGYCAN_HUNGER = 0
TUNING.KYNO_ENERGYCAN_SANITY = 33

TUNING.KYNO_COFFEEBUSH_GROWTIME = 480 * 4
TUNING.KYNO_COFFEEBUSH_GROWTIME_SUMMER = 480 * 2
TUNING.KYNO_COFFEEBUSH_GROWTIME_SPRING = 480 * 6
TUNING.KYNO_COFFEEBUSH_WORKLEFT = 1

TUNING.KYNO_FLIPPABLE_GROWTIME = 480 * 7
TUNING.KYNO_FLIPPABLE_REGROWTH_TIME_MULT = 1
TUNING.KYNO_FLIPPABLE_ROCK_REPOPULATE_TIME = 2400
TUNING.KYNO_FLIPPABLE_ROCK_REPOPULATE_INCREASE = 240
TUNING.KYNO_FLIPPABLE_ROCK_REPOPULATE_VARIANCE = 960
TUNING.KYNO_FLIPPABLE_ROCK_CYCLES = 3
TUNING.KYNO_FLIPPABLE_WORKLEFT = 3

TUNING.KYNO_ROE_HEALTH = 1
TUNING.KYNO_ROE_HUNGER = 4.6875
TUNING.KYNO_ROE_SANITY = 0
TUNING.KYNO_ROE_COOKED_HEALTH = 3
TUNING.KYNO_ROE_COOKED_HUNGER = 4.6875
TUNING.KYNO_ROE_COOKED_SANITY = 0

TUNING.KYNO_PEBBLECRAB_HEALTH = 50
TUNING.KYNO_PEBBLECRAB_WALKSPEED = 1
TUNING.KYNO_PEBBLECRAB_RUNSPEED = 6
TUNING.KYNO_PEBBLECRAB_RELEASE_TIME = 10
TUNING.KYNO_PEBBLECRAB_REGEN_TIME = 960
TUNING.KYNO_PEBBLECRAB_AMOUNT = 2
TUNING.KYNO_PEBBLECRAB_ENABLED = true

TUNING.KYNO_SUGARFLY_HEALTH = 1
TUNING.MAX_KYNO_SUGARFLIES = 4

TUNING.KYNO_SUGARFLYWINGS_HEALTH = 0
TUNING.KYNO_SUGARFLYWINGS_HUNGER = 9.375
TUNING.KYNO_SUGARFLYWINGS_SANITY = 8

TUNING.KYNO_CRABTRAP_USES = 8

TUNING.KYNO_SLAUGHTERTOOLS_USES = 6
TUNING.KYNO_SLAUGHTERTOOLS_COOLDOWN = 30
TUNING.KYNO_SLAUGHTERTOOLS_AVOID_DIST = 5
TUNING.KYNO_SLAUGHTERTOOLS_AVOID_STOP = 15
TUNING.KYNO_SLAUGHTERTOOLS_MAXDIST = 25

TUNING.KYNO_SAP_GROWTIME = 1440
TUNING.KYNO_SAP_RUINED_GROWTIME = 1440
TUNING.KYNO_SAP_SPOILTIME = 4800
TUNING.KYNO_SAP_SPOILTIME_MAX = 4800
TUNING.KYNO_SAP_SPOILS = true

TUNING.KYNO_SUGARFLOWER_REGROWTH_TIME_MULT = 1

TUNING.KYNO_SUGARTREE_WORKLEFT = 15
TUNING.KYNO_SUGARTREE_STUMP_WORKLEFT = 1
TUNING.KYNO_SUGARTREE_TAPPED_WORKLEFT = 1
TUNING.KYNO_SUGARTREE_SHORT_WORKLEFT = 5
TUNING.KYNO_SUGARTREE_NORMAL_WORKLEFT = 10
TUNING.KYNO_SUGARTREE_SHORT_GROWTIME = 240
TUNING.KYNO_SUGARTREE_NORMAL_GROWTIME = 720
TUNING.KYNO_SUGARTREE_REGROWTH_TIME = 480 * 3
TUNING.KYNO_SUGARTREE_REGROWTH_TIME_MULT = 1

TUNING.KYNO_SHARKFIN_HEALTH = 20
TUNING.KYNO_SHARKFIN_HUNGER = 25
TUNING.KYNO_SHARKFIN_SANITY = -10

TUNING.KYNO_SPOTBUSH_GROWTIME = 480 * 3
TUNING.KYNO_SPOTBUSH_REGROWTH_TIME_MULT = 1

TUNING.KYNO_TAROSEA_GROWTIME = 480 * 4

TUNING.KYNO_TAROROOT_HEALTH = 8
TUNING.KYNO_TAROROOT_HUNGER = 25
TUNING.KYNO_TAROROOT_SANITY = 0
TUNING.KYNO_TAROROOT_COOKED_HEALTH = 20
TUNING.KYNO_TAROROOT_COOKED_HUNGER = 25
TUNING.KYNO_TAROROOT_COOKED_SANITY = 0

TUNING.KYNO_TUNACAN_HEALTH = 10
TUNING.KYNO_TUNACAN_HUNGER = 25
TUNING.KYNO_TUNACAN_SANITY = 0

TUNING.KYNO_TWIGGYNUTS_HEALTH = 5
TUNING.KYNO_TWIGGYNUTS_HUNGER = 0
TUNING.KYNO_TWIGGYNUTS_SANITY = 5

TUNING.KYNO_WATERBUFF_DURATION = 60

TUNING.KYNO_WATERYCRESS_GROWTIME = 480 * 5

TUNING.KYNO_WATERYCRESS_HEALTH = 1
TUNING.KYNO_WATERYCRESS_HUNGER = 12.5
TUNING.KYNO_WATERYCRESS_SANITY = 5
TUNING.KYNO_WATERYCRESS_COOKED_HEALTH = 3
TUNING.KYNO_WATERYCRESS_COOKED_HUNGER = 12.5
TUNING.KYNO_WATERYCRESS_COOKED_SANITY = 5

TUNING.KYNO_WEEDSEA_GROWTIME = 480 * 3

TUNING.KYNO_WEEDSEA_HEALTH = 1
TUNING.KYNO_WEEDSEA_HUNGER = 9.375
TUNING.KYNO_WEEDSEA_SANITY = -10
TUNING.KYNO_WEEDSEA_COOKED_HEALTH = 3
TUNING.KYNO_WEEDSEA_COOKED_HUNGER = 9.375
TUNING.KYNO_WEEDSEA_COOKED_SANITY = 0
TUNING.KYNO_WEEDSEA_DRIED_HEALTH = 3
TUNING.KYNO_WEEDSEA_DRIED_HUNGER = 12.5
TUNING.KYNO_WEEDSEA_DRIED_SANITY = 5

TUNING.KYNO_WILDWHEAT_GROWTIME = 480 * 3
TUNING.KYNO_WILDWHEAT_REGROWTH_TIME_MULT = 1

TUNING.KYNO_RADISH_REGROWTH_TIME_MULT = 1

TUNING.KYNO_RADISH_HEALTH = 1
TUNING.KYNO_RADISH_HUNGER = 12.5
TUNING.KYNO_RADISH_SANITY = 0
TUNING.KYNO_RADISH_COOKED_HEALTH = 3
TUNING.KYNO_RADISH_COOKED_HUNGER = 12.5
TUNING.KYNO_RADISH_COOKED_SANITY = 0

TUNING.KYNO_CUCUMBER_REGROWTH_TIME_MULT = 1

TUNING.KYNO_CUCUMBER_HEALTH = 1
TUNING.KYNO_CUCUMBER_HUNGER = 12.5
TUNING.KYNO_CUCUMBER_SANITY = -5
TUNING.KYNO_CUCUMBER_COOKED_HEALTH = 1
TUNING.KYNO_CUCUMBER_COOKED_HUNGER = 25
TUNING.KYNO_CUCUMBER_COOKED_SANITY = 5

TUNING.KYNO_SWEETPOTATO_REGROWTH_TIME_MULT = 1

TUNING.KYNO_SWEETPOTATO_HEALTH = 1
TUNING.KYNO_SWEETPOTATO_HUNGER = 12.5
TUNING.KYNO_SWEETPOTATO_SANITY = 0
TUNING.KYNO_SWEETPOTATO_COOKED_HEALTH = 3
TUNING.KYNO_SWEETPOTATO_COOKED_HUNGER = 12.5
TUNING.KYNO_SWEETPOTATO_COOKED_SANITY = 0

TUNING.KYNO_PARZNIP_REGROWTH_TIME_MULT = 1

TUNING.KYNO_PARZNIP_HEALTH = 1
TUNING.KYNO_PARZNIP_HUNGER = 6
TUNING.KYNO_PARZNIP_SANITY = 0
TUNING.KYNO_PARZNIP_EATEN_HEALTH = 1
TUNING.KYNO_PARZNIP_EATEN_HUNGER = 6 
TUNING.KYNO_PARZNIP_EATEN_SANITY = 0
TUNING.KYNO_PARZNIP_COOKED_HEALTH = 3
TUNING.KYNO_PARZNIP_COOKED_HUNGER = 18.5
TUNING.KYNO_PARZNIP_COOKED_SANITY = 1

TUNING.KYNO_PARZNIP_BIG_WORKLEFT = 10
TUNING.KYNO_PARZNIP_BIG_REGROWTH_TIME_MULT = 1

TUNING.KYNO_TURNIP_REGROWTH_TIME_MULT = 1

TUNING.KYNO_TURNIP_HEALTH = 5
TUNING.KYNO_TURNIP_HUNGER = 9.375
TUNING.KYNO_TURNIP_SANITY = 0
TUNING.KYNO_TURNIP_COOKED_HEALTH = 10
TUNING.KYNO_TURNIP_COOKED_HUNGER = 18.5
TUNING.KYNO_TURNIP_COOKED_SANITY = 0

TUNING.KYNO_FENNEL_REGROWTH_TIME_MULT = 1

TUNING.KYNO_FENNEL_HEALTH = 1
TUNING.KYNO_FENNEL_HUNGER = 12.5
TUNING.KYNO_FENNEL_SANITY = -5
TUNING.KYNO_FENNEL_COOKED_HEALTH = 3
TUNING.KYNO_FENNEL_COOKED_HUNGER = 12.5
TUNING.KYNO_FENNEL_COOKED_SANITY = 5

TUNING.KYNO_ALOE_REGROWTH_TIME_MULT = 1

TUNING.KYNO_ALOE_HEALTH = 8
TUNING.KYNO_ALOE_HUNGER = 9.375
TUNING.KYNO_ALOE_SANITY = 0
TUNING.KYNO_ALOE_COOKED_HEALTH = 8
TUNING.KYNO_ALOE_COOKED_HUNGER = 12.5
TUNING.KYNO_ALOE_COOKED_SANITY = 0

TUNING.KYNO_RICE_HEALTH = 3
TUNING.KYNO_RICE_HUNGER = 9.375
TUNING.KYNO_RICE_SANITY = 0
TUNING.KYNO_RICE_COOKED_HEALTH = 3
TUNING.KYNO_RICE_COOKED_HUNGER = 18.5
TUNING.KYNO_RICE_COOKED_SANITY = 1

TUNING.KYNO_ASPARGOS_REGROWTH_TIME_MULT = 1

TUNING.SOULSTEW_HEALTH = 5
TUNING.SOULSTEW_HUNGER = 31.25
TUNING.SOULSTEW_SANITY = -10

TUNING.KYNO_DRIEDCAP_RED_HEALTH = -10
TUNING.KYNO_DRIEDCAP_RED_HUNGER = 25
TUNING.KYNO_DRIEDCAP_RED_SANITY = 0

TUNING.KYNO_DRIEDCAP_GREEN_HEALTH = -10
TUNING.KYNO_DRIEDCAP_GREEN_HUNGER = 0
TUNING.KYNO_DRIEDCAP_GREEN_SANITY = 25

TUNING.KYNO_DRIEDCAP_BLUE_HEALTH = 25
TUNING.KYNO_DRIEDCAP_BLUE_HUNGER = 0
TUNING.KYNO_DRIEDCAP_BLUE_SANITY = -10

TUNING.KYNO_DRIEDCAP_MOON_HEALTH = 5
TUNING.KYNO_DRIEDCAP_MOON_HUNGER = 5
TUNING.KYNO_DRIEDCAP_MOON_SANITY = 5

TUNING.KYNO_PLANTMEAT_DRIED_HEALTH = 15
TUNING.KYNO_PLANTMEAT_DRIED_HUNGER = 25
TUNING.KYNO_PLANTMEAT_DRIED_SANITY = 20

TUNING.KYNO_ANTCHEST_PERISH_MULT = -0.7

TUNING.NECTAR_TO_HONEY_TIME = 60

TUNING.KYNO_NECTAR_POD_HEALTH = 3
TUNING.KYNO_NECTAR_POD_HUNGER = 9.375
TUNING.KYNO_NECTAR_POD_SANITY = 0

TUNING.KYNO_OAKTREE_POD_COOKED_HEALTH = 0
TUNING.KYNO_OAKTREE_POD_COOKED_HUNGER = 9.375
TUNING.KYNO_OAKTREE_POD_COOKED_SANITY = 3

TUNING.KYNO_MEADOWISLAND_TREE_SHORT_GROWTIME = 240
TUNING.KYNO_MEADOWISLAND_TREE_NORMAL_GROWTIME = 720
TUNING.KYNO_MEADOWISLAND_TREE_SHORT_WORKLEFT = 5
TUNING.KYNO_MEADOWISLAND_TREE_NORMAL_WORKLEFT = 10
TUNING.KYNO_MEADOWISLAND_TREE_TALL_WORKLEFT = 15
TUNING.KYNO_MEADOWISLAND_TREE_STUMP_WORKLEFT = 1
TUNING.KYNO_MEADOWISLAND_TREE_BURNT_WORKLEFT = 1
TUNING.KYNO_MEADOWISLAND_TREE_DROP_CHANCE = .12 -- Low because each hit procs the chance.
TUNING.KYNO_MEADOWISLAND_TREE_REGROWTH_TIME = 480 * 3
TUNING.KYNO_MEADOWISLAND_TREE_REGROWTH_TIME_MULT = 1

TUNING.MEADOWISLAND_POND_MAX_FISH = 15

TUNING.KYNO_MEADOWISLAND_SAND_REGROW = 480 * 6
TUNING.KYNO_MEADOWISLAND_SAND_REGROW_VARIANCE = 480
TUNING.KYNO_MEADOWISLAND_SAND_REGROWTH_TIME_MULT = 1
TUNING.KYNO_MEADOWISLAND_SAND_DEPLETE = 0.25

TUNING.KYNO_PIKO_HEALTH = 100
TUNING.KYNO_PIKO_SPAWN_TIME = 480 * 4
TUNING.KYNO_PIKO_RUN_SPEED = 4
TUNING.KYNO_PIKO_DAMAGE = 2
TUNING.KYNO_PIKO_ATTACK_PERIOD = 2
TUNING.KYNO_PIKO_TARGET_DIST = 20
TUNING.KYNO_PIKO_PERISH_TIME = 480 * 5
TUNING.KYNO_PIKO_SPAWNDELAY = 10
TUNING.KYNO_PIKO_ORANGE_CHANCE = .40
TUNING.KYNO_PIKO_ENABLED = true
TUNING.KYNO_PIKO_ORANGE_ENABLED = true

TUNING.DUCKYOUGLERMZ_HEALTH = 60
TUNING.DUCKYOUGLERMZ_HUNGER = 12.5
TUNING.DUCKYOUGLERMZ_SANITY = 33

TUNING.MILKABLE_NORMAL_TIME = 3360
TUNING.MILKABLE_SPRING_TIME = 4800
TUNING.MILKABLE_NORMAL_DAMAGE = 30
TUNING.MILKABLE_SPRING_DAMAGE = 60
TUNING.MILKABLE_KOALEFANT_DAMAGE = 50
TUNING.MILKABLE_LIGHTNINGGOAT_DAMAGE = 25

TUNING.KYNO_POISON_FROGLEGS_HEALTH = -10
TUNING.KYNO_POISON_FROGLEGS_HUNGER = 20
TUNING.KYNO_POISON_FROGLEGS_SANITY = -10
TUNING.KYNO_POISON_FROGLEGS_COOKED_HEALTH = -5
TUNING.KYNO_POISON_FROGLEGS_COOKED_HUNGER = 20
TUNING.KYNO_POISON_FROGLEGS_COOKED_SANITY = 0

TUNING.KYNO_MOON_FROGLEGS_HEALTH = 0
TUNING.KYNO_MOON_FROGLEGS_HUNGER = 12.5
TUNING.KYNO_MOON_FROGLEGS_SANITY = -5
TUNING.KYNO_MOON_FROGLEGS_COOKED_HEALTH = 1
TUNING.KYNO_MOON_FROGLEGS_COOKED_HUNGER = 12.5
TUNING.KYNO_MOON_FROGLEGS_COOKED_SANITY = 15

TUNING.KYNO_FROGBUFF_DURATION = 480

TUNING.KYNO_BREWINGRECIPECARD_CHANCE = 0.04 -- It needs to be this low.

TUNING.KYNO_OIL_HEALTH = 1
TUNING.KYNO_OIL_HUNGER = 9.375
TUNING.KYNO_OIL_SANITY = -10

TUNING.KYNO_PLANT_REGROWTH_TIME_MULT = 1
TUNING.KYNO_PLANT_REGROWTH_TIME = 480 * 15
TUNING.KYNO_TREE_REGROWTH_TIME = 480 * 25
TUNING.KYNO_DESOLATION_RESPAWN_TIME = 480 * 50

TUNING.KYNO_FEARBUFF_DURATION = 480

TUNING.KYNO_PIRATEBUFF_DURATION = 720
TUNING.KYNO_PIRATEBUFF_EXTRADAMAGE = 50

TUNING.KYNO_WORMBUFF_DURATION = 720
TUNING.KYNO_WORMBUFF_EXTRADAMAGE = 50

TUNING.KYNO_CRABBUFF_DURATION = 720
TUNING.KYNO_CRABBUFF_EXTRADAMAGE = 50

TUNING.KYNO_PINEAPPLE_HEALTH = 3
TUNING.KYNO_PINEAPPLE_HUNGER = 12.5
TUNING.KYNO_PINEAPPLE_SANITY = 0

TUNING.KYNO_PINEAPPLE_COOKED_HEALTH = 15
TUNING.KYNO_PINEAPPLE_COOKED_HUNGER = 12.5
TUNING.KYNO_PINEAPPLE_COOKED_SANITY = 3

TUNING.KYNO_PINEAPPLEBUSH_GROWTIME = 480 * 6
TUNING.KYNO_PINEAPPLEBUSH_GROWTIME_SUMMER = 480 * 2
TUNING.KYNO_PINEAPPLEBUSH_GROWTIME_SPRING = 480 * 6
TUNING.KYNO_PINEAPPLEBUSH_REGROWTH_TIME_MULT = 1
TUNING.KYNO_PINEAPPLEBUSH_WORKLEFT = 1

TUNING.KYNO_NIGHTVISIONBUFF_DURATION = 480 

TUNING.KYNO_GARDEN_SPRINKLER_MAXFUEL = 350
TUNING.KYNO_GARDEN_SPRINKLER_FUELSECTIONS = 10

TUNING.KYNO_FOODSACK_PERISH_MULT = -0.3

TUNING.KYNO_NUKASHINE_BLACKOUT = 520

TUNING.KYNO_COLDBUFF_DURATION = 480 * 1.5
TUNING.KYNO_HEATBUFF_DURATION = 480 * 1.5

TUNING.KYNO_FIREBUFF_DURATION = 480 / 2

TUNING.KYNO_FREEZEBUFF_DURATION = 480 / 2
TUNING.KYNO_FREEZEBUFF_FREEZING = .50

TUNING.KYNO_PRESERVERBUFF_DURATION = 960
TUNING.KYNO_PRESERVERBUFF_RATE = .90
TUNING.KYNO_PRESERVERBUFF_PERISHTIME = 2.5 -- 30000 lol don't do it again. Powdercake had "1687499679" days spoil time.

TUNING.SPICE_MULTIPLIERS =
{
	SPICE_SALT = { HEALTH = .25 },
	SPICE_FED  = { HUNGER = .25 },
	SPICE_MIND = { SANITY = .25 },
}

TUNING.KYNO_FISHINGBUFF_DURATION = 480 * 1.5

TUNING.KYNO_MOCHABUFF_DURATION = 480
TUNING.KYNO_MOCHABUFF_SPEED = 1.43

TUNING.KYNO_HUNGERRATEBUFF_MODIFIER = .75

TUNING.KYNO_SANITYRATEBUFF_DURATION = 480 / 2
TUNING.KYNO_SANITYRATEBUFF_MODIFIER = .75

TUNING.KYNO_INSPIRATIONBUFF = 40
TUNING.KYNO_MIGHTINESSBUFF = 50

TUNING.KYNO_TEALEAF_HEALTH = 0
TUNING.KYNO_TEALEAF_HUNGER = 4.6875
TUNING.KYNO_TEALEAF_SANITY = 1

TUNING.KYNO_ITEMSLICER_USES = 200

TUNING.KYNO_EATERBUFF_DURATION = 480 * 1.5

TUNING.SUGARBOMBS_DAMAGE = 9999

TUNING.KYNO_MERMFISHER_TIMER = 400
TUNING.KYNO_MERMFISHER_HEALTH = 300
TUNING.KYNO_MERMFISHER_ROYAL_HEALTH = 600
TUNING.KYNO_MERMFISHER_RUNSPEED = 7
TUNING.KYNO_MERMFISHER_WALKSPEED = 4
TUNING.KYNO_MERMFISHER_TIMERMULT = 1
TUNING.KYNO_MERMFISHER_TIMERMULT_ROYAL = 0.75
TUNING.KYNO_MERMFISHER_RELEASE_TIME = 10
TUNING.KYNO_MERMFISHER_REGEN_TIME = 480 * 3
TUNING.KYNO_MERMFISHER_AMOUNT = 2
TUNING.KYNO_MERMFISHER_ENABLED = true

TUNING.KYNO_MEADOWISLANDTRADER_RUNSPEED = 7
TUNING.KYNO_MEADOWISLANDTRADER_WALKSPEED = 4
TUNING.KYNO_MEADOWISLANDTRADER_REFRESHWARES = 480 / 1.5
TUNING.KYNO_MEADOWISLANDTRADER_UNCOMMONS_ODDS = .25
TUNING.KYNO_MEADOWISLANDTRADER_RARES_ODDS = .10
TUNING.KYNO_MEADOWISLANDTRADER_ULTRARARES_ODDS = .05

TUNING.KYNO_SAMMYHAT_PERISHTIME = 4800
TUNING.KYNO_SAMMYHAT_HUNGERRATE = .85

TUNING.KYNO_MERMCART_USES = 25
TUNING.KYNO_MERMCART_COOLDOWN = 4800
TUNING.KYNO_MERMCART_CRITTER_CHANCE = .10

TUNING.JAWSBREAKER_TAGS = {"shark", "gnarwail"} -- In case someone wants to add their mob.

TUNING.KYNO_FIREIMMUNITYBUFF_DURATION = 480 * 2

TUNING.KYNO_TIRAMISUBUFF_DURATION = 480
TUNING.KYNO_TIRAMISUBUFF_SPEED = 1.43

TUNING.KYNO_AMPHIBIANBUFF_EXTRADAMAGE = 100
TUNING.KYNO_AMPHIBIANBUFF_DURATION = 480 * 2

TUNING.KYNO_ENLIGHTENMENTBUFF_DURATION = 480

TUNING.KYNO_STEALTHBUFF_DURATION = 480

TUNING.KYNO_TRUFFLES_GROWTIME = 480 * 10

TUNING.KYNO_PLANARDEFENSEBUFF_BONUS = 10 -- Should we use multiplicative or additive? - 1.2 for mult / 10 for add
TUNING.KYNO_PLANARDEFENSEBUFF_DURATION = 480

TUNING.KYNO_CRATE_GROWTIME = 3360
TUNING.KYNO_CRATE_REGROWTH_TIME_MULT = 1

TUNING.KYNO_ISLANDCRATE_GROWTIME = 3360
TUNING.KYNO_ISLANDCRATE_REGROWTH_TIME_MULT = 1

TUNING.KYNO_CHICKEN_LAYEGG_COOLDOWN = 480 