-- Mod Tunings.
TUNING.HOF_RESOURCES = .07

TUNING.KYNO_FLOATILIZER_USES = 20
TUNING.KYNO_FLOATILIZER_SOILCYCLES = TUNING.POOP_SOILCYCLES
TUNING.KYNO_FLOATILIZER_FERTILIZE = TUNING.POOP_FERTILIZE * 2
TUNING.KYNO_FLOATILIZER_WITHEREDCYCLES = TUNING.POOP_WITHEREDCYCLES
TUNING.KYNO_FLOATILIZER_NUTRIENTS = { 16,  16,  16 }

TUNING.ASH_NUTRIENTS = { 4,  4,  0 }

TUNING.KYNO_MYSTERYMEAT_NUTRIENTS = { 16, 0, 16 }

TUNING.KYNO_SAP_SPOILED_NUTRIENTS = { 8, 0, 8 }

TUNING.WETGOOP2_NUTRIENTS = { 32, 8, 8 }

TUNING.DUCKYOUGLERMZ_NUTRIENTS = { 24, 24, 24 }

TUNING.DUCKYOUGLERMZ_NUTRIENTS_INDEX = 4

TUNING.KYNO_BANANATREE_GROWTIME = 480 * 4
TUNING.KYNO_BANANATREE_WORKLEFT = 3
TUNING.KYNO_BANANATREE_STUMP_WORKLEFT = 1

TUNING.KYNO_BANANA_HEALTH = 1
TUNING.KYNO_BANANA_HUNGER = 12.5
TUNING.KYNO_BANANA_SANITY = 0
TUNING.KYNO_BANANA_COOKED_HEALTH = 3
TUNING.KYNO_BANANA_COOKED_HUNGER = 12.5
TUNING.KYNO_BANANA_COOKED_SANITY = 0

TUNING.KYNO_BUCKET_EMPTY_USES = 10
TUNING.KYNO_BUCKET_WATER_USES = 20
TUNING.KYNO_BUCKET_WATER_AMOUNT = 25 / 2
TUNING.KYNO_BUCKET_WATER_EXTINGUISH_HEAT_PERCENT = -1
TUNING.KYNO_BUCKET_WATER_TEMP_REDUCTION = 5 / 2
TUNING.KYNO_BUCKET_WATER_PROTECTION_TIME = 30 / 2
TUNING.KYNO_BUCKET_WATER_PROTECTION_DIST = 2.25 / 2

TUNING.KYNO_BEANBUGS_HEALTH = 0
TUNING.KYNO_BEANBUGS_HUNGER = 9.375
TUNING.KYNO_BEANBUGS_SANITY = -10
TUNING.KYNO_BEANBUGS_COOKED_HEALTH = 1
TUNING.KYNO_BEANBUGS_COOKED_HUNGER = 12.5
TUNING.KYNO_BEANBUGS_COOKED_SANITY = -5

TUNING.KYNO_TOMATOCAN_HEALTH = 12.5
TUNING.KYNO_TOMATOCAN_HUNGER = 20 
TUNING.KYNO_TOMATOCAN_SANITY = 0

TUNING.KYNO_BEANCAN_HEALTH = 0
TUNING.KYNO_BEANCAN_HUNGER = 20 
TUNING.KYNO_BEANCAN_SANITY = 10 

TUNING.KYNO_MEATCAN_HEALTH = 5
TUNING.KYNO_MEATCAN_HUNGER = 25 
TUNING.KYNO_MEATCAN_SANITY = 0 

TUNING.KYNO_CHICKEN2_HEALTH = 75

TUNING.KYNO_CHICKEN_EGG_HEALTH = 2
TUNING.KYNO_CHICKEN_EGG_HUNGER = 9.375
TUNING.KYNO_CHICKEN_EGG_SANITY = 0
TUNING.KYNO_CHICKEN_EGG_COOKED_HEALTH = 3
TUNING.KYNO_CHICKEN_EGG_COOKED_HUNGER = 12.5
TUNING.KYNO_CHICKEN_EGG_COOKED_SANITY = 0

TUNING.KYNO_COFFEEBUFF_SPEED = 1.83
TUNING.KYNO_COFFEEBUFF_DURATION_SMALL = 30
TUNING.KYNO_COFFEEBUFF_DURATION_MEDSMALL = 240
TUNING.KYNO_COFFEEBUFF_DURATION_MED = 480
TUNING.KYNO_COFFEEBUFF_DURATION_LARGE = 640
TUNING.KYNO_COFFEEBUFF_DURATION_MEDLARGE = 960
TUNING.KYNO_COFFEEBUFF_DURATION_HUGE = 1920

TUNING.KYNO_COFFEEBEANS_HEALTH = 0
TUNING.KYNO_COFFEEBEANS_HUNGER = 9.375
TUNING.KYNO_COFFEEBEANS_SANITY = 0
TUNING.KYNO_COFFEEBEANS_COOKED_HEALTH = 0
TUNING.KYNO_COFFEEBEANS_COOKED_HUNGER = 9.375
TUNING.KYNO_COFFEEBEANS_COOKED_SANITY = -5

TUNING.KYNO_COOKWARE_COOKTIMEMULT = .5
TUNING.KYNO_COOKWARE_COOKTIMEMULT_SYRUP = .3

TUNING.KYNO_DMGREDUCTIONBUFF_SPEED = .70
TUNING.KYNO_ALCOHOL_SPEED = .70
TUNING.KYNO_ALCOHOL_DURATION_SMALL = 480
TUNING.KYNO_ALCOHOL_DURATION_MEDSMALL = 520
TUNING.KYNO_ALCOHOL_STRENGTH_SMALL = 1.2
TUNING.KYNO_ALCOHOL_STRENGTH_MEDSMALL = 1.5

TUNING.KYNO_PARZNIP_EATEN_HEALTH = 1
TUNING.KYNO_PARZNIP_EATEN_HUNGER = 6 
TUNING.KYNO_PARZNIP_EATEN_SANITY = 0

TUNING.KYNO_PARZNIP_BIG_WORKLEFT = 10

TUNING.KYNO_FISH_LARGE_HEALTH = 8
TUNING.KYNO_FISH_LARGE_HUNGER = 25

TUNING.KYNO_FISH_SMALL_HEALTH = 1
TUNING.KYNO_FISH_SMALL_HUNGER = 12.5

TUNING.KYNO_HASTEBUFF_DURATION = 480

TUNING.KYNO_WHEAT_HEALTH = 0
TUNING.KYNO_WHEAT_HUNGER = 4.6875
TUNING.KYNO_WHEAT_SANITY = 0
TUNING.KYNO_WHEAT_COOKED_HEALTH = 1
TUNING.KYNO_WHEAT_COOKED_HUNGER = 4.6875
TUNING.KYNO_WHEAT_COOKED_SANITY = 0

TUNING.KYNO_SAP_HEALTH = 1
TUNING.KYNO_SAP_HUNGER = 3 
TUNING.KYNO_SAP_SANITY = 0

TUNING.KYNO_SYRUP_HEALTH = 3 
TUNING.KYNO_SYRUP_HUNGER = 9.375
TUNING.KYNO_SYRUP_SANITY = 0

TUNING.KYNO_SPOTSPICE_LEAF_HEALTH = 0
TUNING.KYNO_SPOTSPICE_LEAF_HUNGER = 4.6875
TUNING.KYNO_SPOTSPICE_LEAF_SANITY = 0 

TUNING.KYNO_BACON_HEALTH = 0
TUNING.KYNO_BACON_HUNGER = 12.5
TUNING.KYNO_BACON_SANITY = -10
TUNING.KYNO_BACON_COOKED_HEALTH = 3
TUNING.KYNO_BACON_COOKED_HUNGER = 12.5
TUNING.KYNO_BACON_COOKED_SANITY = 5

TUNING.KYNO_WHITE_CAP_HEALTH = -10
TUNING.KYNO_WHITE_CAP_HUNGER = 9.375
TUNING.KYNO_WHITE_CAP_SANITY = 0
TUNING.KYNO_WHITE_CAP_COOKED_HEALTH = -5
TUNING.KYNO_WHITE_CAP_COOKED_HUNGER = 12.5
TUNING.KYNO_WHITE_CAP_COOKED_SANITY = 0

TUNING.KYNO_FOLIAGE_HEALTH = 1
TUNING.KYNO_FOLIAGE_HUNGER = 0
TUNING.KYNO_FOLIAGE_SANITY = 0
TUNING.KYNO_FOLIAGE_COOKED_HEALTH = 1 
TUNING.KYNO_FOLIAGE_COOKED_HUNGER = 0 
TUNING.KYNO_FOLIAGE_COOKED_SANITY = 0

TUNING.KYNO_CRABMEAT_HEALTH = 5 
TUNING.KYNO_CRABMEAT_HUNGER = 5 
TUNING.KYNO_CRABMEAT_SANITY = -10 
TUNING.KYNO_CRABMEAT_COOKED_HEALTH = 10 
TUNING.KYNO_CRABMEAT_COOKED_HUNGER = 10 
TUNING.KYNO_CRABMEAT_COOKED_SANITY = 5

TUNING.KYNO_HUMANMEAT_HEALTH = -20 
TUNING.KYNO_HUMANMEAT_HUNGER = 12.5
TUNING.KYNO_HUMANMEAT_SANITY = -33
TUNING.KYNO_HUMANMEAT_COOKED_HEALTH = -3
TUNING.KYNO_HUMANMEAT_COOKED_HUNGER = 18.75
TUNING.KYNO_HUMANMEAT_COOKED_SANITY = -20
TUNING.KYNO_HUMANMEAT_DRIED_HEALTH = -3 
TUNING.KYNO_HUMANMEAT_DRIED_HUNGER = 25
TUNING.KYNO_HUMANMEAT_DRIED_SANITY = -15

TUNING.KYNO_KOKONUT_HEALTH = 1 
TUNING.KYNO_KOKONUT_HUNGER = 4.6875 
TUNING.KYNO_KOKONUT_SANITY = 0
TUNING.KYNO_KOKONUT_COOKED_HEALTH = 3
TUNING.KYNO_KOKONUT_COOKED_HUNGER = 9.375
TUNING.KYNO_KOKONUT_COOKED_SANITY = 0 

TUNING.KYNO_KOKONUTTREE_GROWTIME = 480 * 5
TUNING.KYNO_KOKONUTTREE_WORKLEFT = 15
TUNING.KYNO_KOKONUTTREE_STUMP_WORKLEFT = 1
TUNING.KYNO_KOKONUTTREE_KOKONUT_CHANCE = 0.01

TUNING.KYNO_LIMPETROCK_GROWTIME = 1440

TUNING.KYNO_LIMPETS_HEALTH = 0 
TUNING.KYNO_LIMPETS_HUNGER = 12.5
TUNING.KYNO_LIMPETS_SANITY = -10
TUNING.KYNO_LIMPETS_COOKED_HEALTH = 1 
TUNING.KYNO_LIMPETS_COOKED_HUNGER = 12.5
TUNING.KYNO_LIMPETS_COOKED_SANITY = 0

TUNING.KYNO_LOTUS_GROWTIME = 480 * 3

TUNING.KYNO_LOTUS_HEALTH = 1
TUNING.KYNO_LOTUS_HUNGER = 12.5
TUNING.KYNO_LOTUS_SANITY = 5
TUNING.KYNO_LOTUS_COOKED_HEALTH = 3
TUNING.KYNO_LOTUS_COOKED_HUNGER = 12.5
TUNING.KYNO_LOTUS_COOKED_SANITY = 15

TUNING.KYNO_MEALGRINDER_WORKLEFT = 4

TUNING.KYNO_MILK_BEEFALO_HEALTH = 3
TUNING.KYNO_MILK_BEEFALO_HUNGER = 3
TUNING.KYNO_MILK_BEEFALO_SANITY = -10

TUNING.KYNO_MILK_KOALEFANT_HEALTH = 6
TUNING.KYNO_MILK_KOALEFANT_HUNGER = 6
TUNING.KYNO_MILK_KOALEFANT_SANITY = -10

TUNING.KYNO_MILK_DEER_HEALTH = 0 
TUNING.KYNO_MILK_DEER_HUNGER = 5 
TUNING.KYNO_MILK_DEER_SANITY = -10

TUNING.KYNO_MILK_SPAT_HEALTH = 8 
TUNING.KYNO_MILK_SPAT_HUNGER = 8 
TUNING.KYNO_MILK_SPAT_SANITY = -20

TUNING.KYNO_MUSHSTUMP_GROWTIME = 480 * 5
TUNING.KYNO_MUSHSTUMP_WORKLEFT = 1

TUNING.KYNO_MUSSEL_HEALTH = 0
TUNING.KYNO_MUSSEL_HUNGER = 12.5
TUNING.KYNO_MUSSEL_SANITY = -15 
TUNING.KYNO_MUSSEL_COOKED_HEALTH = 1
TUNING.KYNO_MUSSEL_COOKED_HUNGER = 12.5
TUNING.KYNO_MUSSEL_COOKED_SANITY = 0

TUNING.KYNO_MUSSELSTICK_GROWTIME = 1440
TUNING.KYNO_MUSSELSTICK_WORKLEFT = 4

TUNING.KYNO_MYSTERYMEAT_HEALTH = -1
TUNING.KYNO_MYSTERYMEAT_HUNGER = -10
TUNING.KYNO_MYSTERYMEAT_SANITY = 0

TUNING.KYNO_OCEANWRECK_WORKLEFT = 4

TUNING.KYNO_SODACAN_HEALTH = -8
TUNING.KYNO_SODACAN_HUNGER = 0
TUNING.KYNO_SODACAN_SANITY = 33

TUNING.KYNO_COKECAN_HEALTH = -8
TUNING.KYNO_COKECAN_HUNGER = 0
TUNING.KYNO_COKECAN_SANITY = 33

TUNING.KYNO_ENERGYCAN_HEALTH = -8
TUNING.KYNO_ENERGYCAN_HUNGER = 0
TUNING.KYNO_ENERGYCAN_SANITY = 33

TUNING.KYNO_COFFEEBUSH_GROWTIME = 480 * 2
TUNING.KYNO_COFFEEBUSH_WORKLEFT = 1

TUNING.FLIPPABLE_GROWTIME = 480 * 7
TUNING.FLIPPABLE_ROCK_REPOPULATE_TIME = 2400
TUNING.FLIPPABLE_ROCK_REPOPULATE_INCREASE = 240
TUNING.FLIPPABLE_ROCK_REPOPULATE_VARIANCE = 960
TUNING.FLIPPABLE_ROCK_CYCLES = 3
TUNING.FLIPPABLE_WORKLEFT = 3

TUNING.KYNO_ROE_HEALTH = 1
TUNING.KYNO_ROE_HUNGER = 4.6875
TUNING.KYNO_ROE_SANITY = 0
TUNING.KYNO_ROE_COOKED_HEALTH = 0
TUNING.KYNO_ROE_COOKED_HUNGER = 4.6875
TUNING.KYNO_ROE_COOKED_SANITY = 0

TUNING.KYNO_PEBBLECRAB_HEALTH = 50
TUNING.KYNO_PEBBLECRAB_WALKSPEED = 1
TUNING.KYNO_PEBBLECRAB_RUNSPEED = 6

TUNING.KYNO_SUGARFLY_HEALTH = 1

TUNING.KYNO_SUGARFLYWINGS_HEALTH = 0
TUNING.KYNO_SUGARFLYWINGS_HUNGER = 9.375
TUNING.KYNO_SUGARFLYWINGS_SANITY = 8

TUNING.KYNO_CRABTRAP_USES = 5

TUNING.KYNO_SLAUGHTERTOOLS_USES = 4

TUNING.KYNO_SAP_GROWTIME = 1440
TUNING.KYNO_SAP_SPOILTIME = 2880

TUNING.KYNO_SUGARTREE_WORKLEFT = 15
TUNING.KYNO_SUGARTREE_STUMP_WORKLEFT = 1
TUNING.KYNO_SUGARTREE_TAPPED_WORKLEFT = 3
TUNING.KYNO_SUGARTREE_SHORT_WORKLEFT = 5
TUNING.KYNO_SUGARTREE_NORMAL_WORKLEFT = 10

TUNING.KYNO_SUGARTREE_SHORT_GROWTIME = 240
TUNING.KYNO_SUGARTREE_NORMAL_GROWTIME = 720

TUNING.KYNO_SHARKFIN_HEALTH = 20
TUNING.KYNO_SHARKFIN_HUNGER = 25
TUNING.KYNO_SHARKFIN_SANITY = -10

TUNING.KYNO_SPOTBUSH_GROWTIME = 480 * 3

TUNING.KYNO_TAROSEA_GROWTIME = 480 * 4

TUNING.KYNO_TAROROOT_HEALTH = 8
TUNING.KYNO_TAROROOT_HUNGER = 25
TUNING.KYNO_TAROROOT_SANITY = 0
TUNING.KYNO_TAROROOT_COOKED_HEALTH = 20
TUNING.KYNO_TAROROOT_COOKED_HUNGER = 25
TUNING.KYNO_TAROROOT_COOKED_SANITY = 0

TUNING.KYNO_TUNACAN_HEALTH = 10
TUNING.KYNO_TUNACAN_HUNGER = 25
TUNING.KYNO_TUNACAN_SANITY = 0

TUNING.KYNO_TWIGGYNUTS_HEALTH = 5
TUNING.KYNO_TWIGGYNUTS_HUNGER = 0
TUNING.KYNO_TWIGGYNUTS_SANITY = 5

TUNING.KYNO_WATERBUFF_DURATION = 60

TUNING.KYNO_WATERYCRESS_GROWTIME = 480 * 5

TUNING.KYNO_WATERYCRESS_HEALTH = 1
TUNING.KYNO_WATERYCRESS_HUNGER = 12.5
TUNING.KYNO_WATERYCRESS_SANITY = 5
TUNING.KYNO_WATERYCRESS_COOKED_HEALTH = 3
TUNING.KYNO_WATERYCRESS_COOKED_HUNGER = 12.5
TUNING.KYNO_WATERYCRESS_COOKED_SANITY = 5

TUNING.KYNO_WEEDSEA_GROWTIME = 480 * 3

TUNING.KYNO_WEEDSEA_HEALTH = 1
TUNING.KYNO_WEEDSEA_HUNGER = 9.375
TUNING.KYNO_WEEDSEA_SANITY = -10
TUNING.KYNO_WEEDSEA_COOKED_HEALTH = 3
TUNING.KYNO_WEEDSEA_COOKED_HUNGER = 9.375
TUNING.KYNO_WEEDSEA_COOKED_SANITY = 0
TUNING.KYNO_WEEDSEA_DRIED_HEALTH = 3
TUNING.KYNO_WEEDSEA_DRIED_HUNGER = 12.5
TUNING.KYNO_WEEDSEA_DRIED_SANITY = 5

TUNING.KYNO_WILDWHEAT_GROWTIME = 480 * 3

TUNING.KYNO_RADISH_HEALTH = 1
TUNING.KYNO_RADISH_HUNGER = 12.5
TUNING.KYNO_RADISH_SANITY = 0
TUNING.KYNO_RADISH_COOKED_HEALTH = 3
TUNING.KYNO_RADISH_COOKED_HUNGER = 12.5
TUNING.KYNO_RADISH_COOKED_SANITY = 0

TUNING.KYNO_CUCUMBER_HEALTH = 1
TUNING.KYNO_CUCUMBER_HUNGER = 12.5
TUNING.KYNO_CUCUMBER_SANITY = -5

TUNING.KYNO_SWEETPOTATO_HEALTH = 1
TUNING.KYNO_SWEETPOTATO_HUNGER = 12.5
TUNING.KYNO_SWEETPOTATO_SANITY = 0
TUNING.KYNO_SWEETPOTATO_COOKED_HEALTH = 3
TUNING.KYNO_SWEETPOTATO_COOKED_HUNGER = 12.5
TUNING.KYNO_SWEETPOTATO_COOKED_SANITY = 0

TUNING.KYNO_PARZNIP_HEALTH = 1
TUNING.KYNO_PARZNIP_HUNGER = 6
TUNING.KYNO_PARZNIP_SANITY = 0
TUNING.KYNO_PARZNIP_COOKED_HEALTH = 3
TUNING.KYNO_PARZNIP_COOKED_HUNGER = 18.5
TUNING.KYNO_PARZNIP_COOKED_SANITY = 1

TUNING.KYNO_TURNIP_HEALTH = 4
TUNING.KYNO_TURNIP_HUNGER = 9.375
TUNING.KYNO_TURNIP_SANITY = 0
TUNING.KYNO_TURNIP_COOKED_HEALTH = 8
TUNING.KYNO_TURNIP_COOKED_HUNGER = 18.5
TUNING.KYNO_TURNIP_COOKED_SANITY = 0

TUNING.KYNO_FENNEL_HEALTH = 1
TUNING.KYNO_FENNEL_HUNGER = 12.5
TUNING.KYNO_FENNEL_SANITY = -5
TUNING.KYNO_FENNEL_COOKED_HEALTH = 3
TUNING.KYNO_FENNEL_COOKED_HUNGER = 12.5
TUNING.KYNO_FENNEL_COOKED_SANITY = 5

TUNING.KYNO_ALOE_HEALTH = 8
TUNING.KYNO_ALOE_HUNGER = 9.375
TUNING.KYNO_ALOE_SANITY = 0
TUNING.KYNO_ALOE_COOKED_HEALTH = 3
TUNING.KYNO_ALOE_COOKED_HUNGER = 12.5
TUNING.KYNO_ALOE_COOKED_SANITY = 0

TUNING.SOULSTEW_HEALTH = 5
TUNING.SOULSTEW_HUNGER = 31.25
TUNING.SOULSTEW_SANITY = -10

TUNING.KYNO_DRIEDCAP_RED_HEALTH = -10
TUNING.KYNO_DRIEDCAP_RED_HUNGER = 25
TUNING.KYNO_DRIEDCAP_RED_SANITY = 0

TUNING.KYNO_DRIEDCAP_GREEN_HEALTH = -10
TUNING.KYNO_DRIEDCAP_GREEN_HUNGER = 0
TUNING.KYNO_DRIEDCAP_GREEN_SANITY = 25

TUNING.KYNO_DRIEDCAP_BLUE_HEALTH = 25
TUNING.KYNO_DRIEDCAP_BLUE_HUNGER = 0
TUNING.KYNO_DRIEDCAP_BLUE_SANITY = -10

TUNING.KYNO_DRIEDCAP_MOON_HEALTH = 5
TUNING.KYNO_DRIEDCAP_MOON_HUNGER = 5
TUNING.KYNO_DRIEDCAP_MOON_SANITY = 5

TUNING.KYNO_PLANTMEAT_DRIED_HEALTH = 15
TUNING.KYNO_PLANTMEAT_DRIED_HUNGER = 25
TUNING.KYNO_PLANTMEAT_DRIED_SANITY = 20

TUNING.KYNO_ANTCHEST_PERISH_MULT = -0.7

TUNING.NECTAR_TO_HONEY_TIME = 60

TUNING.KYNO_NECTAR_POD_HEALTH = 3
TUNING.KYNO_NECTAR_POD_HUNGER = 9.375
TUNING.KYNO_NECTAR_POD_SANITY = 0

TUNING.KYNO_OAKTREE_POD_COOKED_HEALTH = 0
TUNING.KYNO_OAKTREE_POD_COOKED_HUNGER = 9.375
TUNING.KYNO_OAKTREE_POD_COOKED_SANITY = 3

TUNING.KYNO_MEADOWISLAND_TREE_WORKLEFT = 15
TUNING.KYNO_MEADOWISLAND_TREE_STUMP_WORKLEFT = 1
TUNING.KYNO_MEADOWISLAND_TREE_BURNT_WORKLEFT = 1

TUNING.MEADOWISLAND_POND_MAX_FISH = 15

TUNING.KYNO_MEADOWISLAND_SAND_REGROW = 480 * 2
TUNING.KYNO_MEADOWISLAND_SAND_REGROW_VARIANCE = 480
TUNING.KYNO_MEADOWISLAND_SAND_DEPLETE = 0.25

TUNING.KYNO_PIKO_HEALTH = 100
TUNING.KYNO_PIKO_RESPAWN_TIME = 480 * 4
TUNING.KYNO_PIKO_RUN_SPEED = 4
TUNING.KYNO_PIKO_DAMAGE = 2
TUNING.KYNO_PIKO_ATTACK_PERIOD = 2
TUNING.KYNO_PIKO_TARGET_DIST = 20
TUNING.KYNO_PIKO_PERISH_TIME = 480 * 5

TUNING.DUCKYOUGLERMZ_HEALTH = 60
TUNING.DUCKYOUGLERMZ_HUNGER = 12.5
TUNING.DUCKYOUGLERMZ_SANITY = 33

TUNING.MILKABLE_NORMAL_TIME = 2880
TUNING.MILKABLE_SPRING_TIME = 3840
TUNING.MILKABLE_NORMAL_DAMAGE = 30
TUNING.MILKABLE_SPRING_DAMAGE = 60
TUNING.MILKABLE_KOALEFANT_DAMAGE = 50
TUNING.MILKABLE_LIGHTNINGGOAT_DAMAGE = 25

TUNING.KYNO_POISON_FROGLEGS_HEALTH = -10
TUNING.KYNO_POISON_FROGLEGS_HUNGER = 20
TUNING.KYNO_POISON_FROGLEGS_SANITY = -10
TUNING.KYNO_POISON_FROGLEGS_COOKED_HEALTH = -10
TUNING.KYNO_POISON_FROGLEGS_COOKED_HUNGER = 20
TUNING.KYNO_POISON_FROGLEGS_COOKED_SANITY = 0

TUNING.KYNO_FROGBUFF_DURATION = 480