-- Common Dependencies.
local _G               = GLOBAL
local require          = _G.require
local resolvefilepath  = _G.resolvefilepath
local ScrapbookPrefabs = require("scrapbook_prefabs")
local ScrapbookData    = require("screens/redux/scrapbookdata")

--[[ SAMPLES:
	TUNING.PERISH_SUPERFAST  = 1440 - 3 DAYS
	TUNING.PERISH_FAST       = 2880 - 6 DAYS
	TUNING.PERISH_FASTISH    = 3840 - 8 DAYS
	TUNING.PERISH_MED        = 4800 - 10 DAYS
	TUNING.PERISH_SLOW       = 7200 - 15 DAYS
	TUNING.PERISH_PRESERVED  = 9600 - 20 DAYS
	TUNING.PERISH_SUPERSLOW  = 19200 - 40 DAYS
	TUNING.RABBIT_PERISHTIME = 2400 - 5 DAYS
]]--

-- Scrapbook code done by LeWasp: https://steamcommunity.com/id/mpinheiro19

-- Scrapbook Entries tables.
local HOF_SCRAPBOOK_ITEMS =
{
	kyno_saltrack_installer =
	{
		name           = "kyno_saltrack_installer",
		speechname     = "quagmire_salt_rack",
		type           = "item",
		subcat         = "structure",
		tex            = "kyno_saltrack_installer.tex",
		prefab         = "kyno_saltrack_installer",
		fueltype       = "BURNABLE",
		fuelvalue      = 45,
		burnable       = true,
		stacksize      = 10,
		bank           = "quagmire_salt_rack",
		build          = "quagmire_salt_rack",
		anim           = "idle",
		deps           = {"kyno_serenityisland_shop", "kyno_pond_salt", "saltrock"},
		specialinfo    = "SALTRACK",
	},
	
	kyno_crabtrap_installer =
	{
		name           = "kyno_crabtrap_installer",
		type           = "item",
		tex            = "kyno_crabtrap_installer.tex",
		prefab         = "kyno_crabtrap_installer",
		finiteuses     = 8,
		bank           = "quagmire_crab_trap",
		build          = "quagmire_crab_trap",
		anim           = "idle",
		deps           = {"kyno_serenityisland_shop", "kyno_pebblecrab"},
		specialinfo    = "CRABTRAP",
	},
	
	dug_kyno_spotbush  = 
	{
		name           = "dug_kyno_spotbush",
		type           = "item",
		tex            = "dug_kyno_spotbush.tex",
		prefab         = "dug_kyno_spotbush",
		fueltype       = "BURNABLE",
		fuelvalue      = 180,
		burnable       = true,
		stacksize      = 10,
		bank           = "kyno_spotbush",
		build          = "kyno_spotbush",
		anim           = "dropped",
		scale          = 1.7,
		animoffsetx    = 60,
		animoffsety    = 10,
		animoffsetbgy  = -20,
		deps           = {"kyno_spotbush"},
		specialinfo    = "PLANTABLE_FERTILIZE",
	},
	
	dug_kyno_wildwheat = 
	{
		name           = "dug_kyno_wildwheat",
		type           = "item",
		tex            = "dug_kyno_wildwheat.tex",
		prefab         = "dug_kyno_wildwheat",
		fueltype       = "BURNABLE",
		fuelvalue      = 180,
		burnable       = true,
		stacksize      = 10,
		bank           = "kyno_wheat",
		build          = "kyno_wheat",
		anim           = "dropped",
		animoffsetbgy  = -20,
		deps           = {"kyno_wildwheat"},
		specialinfo    = "PLANTABLE_FERTILIZE",
	},
	
	kyno_bottle_soul   =
	{
		name           = "kyno_bottle_soul",
		type           = "item",
		tex            = "kyno_bottle_soul.tex",
		prefab         = "kyno_bottle_soul",
		bank           = "kyno_bottle_soul",
		build          = "kyno_bottle_soul",
		anim           = "idle_empty",
		deps           = {"wortox_soul"},
		specialinfo    = "BOTTLESOUL",
	},
	
	kyno_bottlecap     =
	{
		name           = "kyno_bottlecap",
		type           = "item",
		tex            = "kyno_bottlecap.tex",
		prefab         = "kyno_bottlecap",
		stacksize      = 60,
		bank           = "kyno_bottlecap",
		build          = "kyno_bottlecap",
		anim           = "idle",
		--deps           = {"nukacola", "nukacola_quantum"}
		specialinfo    = "BOTTLECAP",
	},
		
	kyno_mysterymeat   =
	{
		name           = "kyno_mysterymeat",
		type           = "item",
		tex            = "kyno_mysterymeat.tex",
		prefab         = "kyno_mysterymeat",
		stacksize      = 40,
		burnable       = true,
		bank           = "mysterymeat",
		build          = "mystery_meat",
		anim           = "idle",
		deps           = {"kyno_meadowisland_crate"},
	},
	
	kyno_brewbook      =
	{
		name           = "kyno_brewbook",
		type           = "item",
		tex            = "kyno_brewbook.tex",
		prefab         = "kyno_brewbook",
		fueltype       = "BURNABLE",
		fuelvalue      = 45,
		burnable       = true,
		bank           = "kyno_brewbook",
		build          = "kyno_brewbook",
		anim           = "idle",
		deps           = {"kyno_wheat", "papyrus"},
	},
	
	kyno_tunacan       =
	{
		name           = "kyno_tunacan",
		type           = "item",
		subcat         = "canned",
		tex            = "kyno_tunacan.tex",
		prefab         = "kyno_tunacan",
		bank           = "kyno_tuna",
		build          = "kyno_tuna",
		anim           = "idle",
		--deps           = {"sunkenchest", "kyno_serenityisland_crate", "kyno_meadowisland_crate", "kyno_tunacan_open"},
		specialinfo    = "CANNEDFOOD",
	},
	
	kyno_tomatocan       =
	{
		name           = "kyno_tomatocan",
		type           = "item",
		subcat         = "canned",
		tex            = "kyno_tomatocan.tex",
		prefab         = "kyno_tomatocan",
		bank           = "kyno_cannedfoods",
		build          = "kyno_cannedfoods",
		anim           = "tomato_closed",
		--deps           = {"hermitcrab", "sunkenchest", "kyno_serenityisland_crate", "kyno_meadowisland_crate", "kyno_tomatocan_open"},
		specialinfo    = "CANNEDFOOD",
	},
	
	kyno_beancan       =
	{
		name           = "kyno_beancan",
		type           = "item",
		subcat         = "canned",
		tex            = "kyno_beancan.tex",
		prefab         = "kyno_beancan",
		bank           = "kyno_cannedfoods",
		build          = "kyno_cannedfoods",
		anim           = "bean_closed",
		--deps           = {"hermitcrab", "sunkenchest", "kyno_serenityisland_crate", "kyno_meadowisland_crate", "kyno_beancan_open"},
		specialinfo    = "CANNEDFOOD",
	},
	
	kyno_meatcan       =
	{
		name           = "kyno_meatcan",
		type           = "item",
		subcat         = "canned",
		tex            = "kyno_meatcan.tex",
		prefab         = "kyno_meatcan",
		bank           = "kyno_cannedfoods",
		build          = "kyno_cannedfoods",
		anim           = "meat_closed",
		--deps           = {"hermitcrab", "sunkenchest", "kyno_serenityisland_crate", "kyno_meadowisland_crate", "kyno_meatcan_open"},
		specialinfo    = "CANNEDFOOD",
	},
}

local HOF_SCRAPBOOK_FOODS =
{
	kyno_coffeebeans   = 
	{
        name           = "kyno_coffeebeans",
        type           = "food",
		tex            = "kyno_coffeebeans.tex",
        prefab         = "kyno_coffeebeans",
        hungervalue    = 9.735,
		healthvalue    = 0,
		sanityvalue    = 0,
        perishable     = 2880,
        foodtype       = "VEGGIE",
		burnable       = true,
		stacksize      = 40,
		bank           = "coffeebeans",
		build          = "coffeebeans",
		anim           = "idle",
        deps           = {"kyno_coffeebeans_cooked", "spoiled_food"},
    },
	
	kyno_coffeebeans_cooked = 
	{
        name           = "kyno_coffeebeans_cooked",
        type           = "food",
		tex            = "kyno_coffeebeans_cooked.tex",
        prefab         = "kyno_coffeebeans_cooked",
		healthvalue    = 0,
        hungervalue    = 9.735,
		sanityvalue    = -5,
        perishable     = 7200,
        foodtype       = "VEGGIE",
		burnable       = true,
		stacksize      = 40,
		bank           = "coffeebeans",
		build          = "coffeebeans",
		anim           = "cooked",
		deps           = {"kyno_coffeebeans", "coffee", "spoiled_food"},
        specialinfo    = "FOODEFFECTS_SPEED",
    },
	
	kyno_wheat         =
	{
		name           = "kyno_wheat",
		type           = "food",
		tex            = "kyno_wheat.tex",
		prefab         = "kyno_wheat",
		healthvalue    = 0,
		hungervalue    = 4.6875,
		sanityvalue    = 0,
		perishable     = 4800,
		foodtype       = "SEEDS",
		burnable       = true,
		stacksize      = 40,
		bank           = "quagmire_crop_wheat",
		build          = "quagmire_crop_wheat",
		anim           = "idle",
		animoffsety    = 40,
		animoffsetbgy  = -80,
		deps           = {"kyno_mealgrinder", "kyno_wildwheat", "kyno_wheat_cooked", "spoiled_food"},
	},
	
	kyno_wheat_cooked  =
	{
		name           = "kyno_wheat_cooked",
		type           = "food",
		tex            = "kyno_wheat_cooked.tex",
		prefab         = "kyno_wheat_cooked",
		healthvalue    = 1,
		hungervalue    = 4.6875,
		sanityvalue    = 0,
		perishable     = 7200,
		foodtype       = "SEEDS",
		burnable       = true,
		stacksize      = 40,
		bank           = "quagmire_crop_wheat",
		build          = "quagmire_crop_wheat",
		anim           = "cooked",
		animoffsety    = 40,
		animoffsetbgy  = -80,
		deps           = {"kyno_wildwheat", "kyno_wheat", "spoiled_food"},
	},
	
	kyno_flour         =
	{
		name           = "kyno_flour",
		type           = "food",
		tex            = "kyno_flour.tex",
		prefab         = "kyno_flour",
		stacksize      = 40,
		bank           = "quagmire_flour",
		build          = "quagmire_flour",
		anim           = "idle",
		animoffsety    = 15,
		animoffsetbgy  = -80,
		deps           = {"kyno_mealgrinder", "kyno_wheat"},
	},
	
	kyno_spotspice_leaf =
	{
		name           = "kyno_spotspice_leaf",
		type           = "food",
		tex            = "kyno_spotspice_leaf.tex",
		prefab         = "kyno_spotspice_leaf",
		healthvalue    = 0,
		hungervalue    = 4.6875,
		sanityvalue    = 0,
		perishable     = 4800,
		foodtype       = "SEEDS",
		burnable       = true,
		stacksize      = 40,
		bank           = "quagmire_spotspice_sprig",
		build          = "quagmire_spotspice_sprig",
		anim           = "idle",
		deps           = {"kyno_mealgrinder", "kyno_spotbush", "spoiled_food"},
	},
	
	kyno_spotspice     =
	{
		name           = "kyno_spotspice",
		type           = "food",
		tex            = "kyno_spotspice.tex",
		prefab         = "kyno_spotspice",
		stacksize      = 40,
		bank           = "quagmire_spotspice_ground",
		build          = "quagmire_spotspice_ground",
		anim           = "idle",
		animoffsety    = 1,
		animoffsetbgy  = -30,
		deps           = {"kyno_mealgrinder", "kyno_spotspice_leaf"},
	},
	
	kyno_salt          =
	{
		name           = "kyno_salt",
		type           = "food",
		tex            = "kyno_salt.tex",
		prefab         = "kyno_salt",
		stacksize      = 40,
		bank           = "quagmire_salt",
		build          = "quagmire_salt",
		anim           = "idle",
		animoffsety    = 30,
		animoffsetbgx  = -20,
		animoffsetbgy  = -150,
		deps           = {"kyno_pond_salt", "kyno_saltrack_installer", "saltrock"},
		specialinfo    = "SALT",
	},
	
	kyno_bacon         =
	{
		name           = "kyno_bacon",
		speechname     = "smallmeat",
		type           = "food",
		tex            = "kyno_bacon.tex",
		prefab         = "kyno_bacon",
		healthvalue    = 0,
		hungervalue    = 12.5,
		sanityvalue    = -10,
		perishable     = 4800,
		foodtype       = "MEAT",
		stacksize      = 40,
		bank           = "quagmire_meat_small",
		build          = "quagmire_meat_small",
		anim           = "raw",
		animoffsetx    = 5,
		animoffsety    = -10,
		animoffsetbgy  = -20,
		deps           = {"kyno_mealgrinder", "smallmeat", "cookedsmallmeat", "kyno_bacon_cooked", "spoiled_food"},
	},
	
	kyno_bacon_cooked  =
	{
		name           = "kyno_bacon_cooked",
		speechname     = "cookedsmallmeat",
		type           = "food",
		tex            = "kyno_bacon_cooked.tex",
		prefab         = "kyno_bacon_cooked",
		healthvalue    = 3,
		hungervalue    = 12.5,
		sanityvalue    = 5,
		perishable     = 7200,
		foodtype       = "MEAT",
		stacksize      = 40,
		bank           = "quagmire_meat_small",
		build          = "quagmire_meat_small",
		anim           = "cooked",
		animoffsety    = -8,
		animoffsetbgy  = -20,
		deps           = {"smallmeat", "cookedsmallmeat", "kyno_bacon", "spoiled_food"},
	},

	kyno_oil           = 
	{
		name           = "kyno_oil",
		type           = "food",
		tex            = "kyno_oil.tex",
		prefab         = "kyno_oil",
		healthvalue    = 1,
		hungervalue    = 9.375,
		sanityvalue    = -10,
		foodtype       = "VEGGIE",
		stacksize      = 40,
		bank           = "kyno_cookingoil",
		build          = "kyno_cookingoil",
		anim           = "idle",
		scale          = .70,
		animoffsetx    = -10,
		animoffsety    = 20,
		animoffsetbgx  = -15,
		animoffsetbgy  = -130,
		deps           = {"kyno_mealgrinder", "corn", "seeds", "petals"},
	},
	
	kyno_sugar         =
	{
		name           = "kyno_sugar",
		type           = "food",
		tex            = "kyno_sugar.tex",
		prefab         = "kyno_sugar",
		stacksize      = 40,
		bank           = "kyno_sugar",
		build          = "kyno_sugar",
		anim           = "idle",
		animoffsetbgx  = -20,
		animoffsetbgy  = -50,
		deps           = {"kyno_mealgrinder", "kyno_sugartree_petals"},
	},
	
	kyno_sugartree_petals =
	{
		name           = "kyno_sugartree_petals",
		type           = "food",
		tex            = "kyno_sugartree_petals.tex",
		prefab         = "kyno_sugartree_petals",
		healthvalue    = 0,
		hungervalue    = 0,
		sanityvalue    = 5,
		perishable     = 4800,
		foodtype       = "GOODIES",
		stacksize      = 40,
		burnable       = true,
		bank           = "kyno_serenityisland_bud",
		build          = "kyno_serenityisland_bud",
		anim           = "idle",
		deps           = {"kyno_serenityisland_shop", "kyno_sugartree_flower", "kyno_sugar", "spoiled_food"},
	},
	
	kyno_sugarflywings =
	{
		name           = "kyno_sugarflywings",
		type           = "food",
		tex            = "kyno_sugarflywings.tex",
		prefab         = "kyno_sugarflywings",
		healthvalue    = 0,
		hungervalue    = 9.375,
		sanityvalue    = 8,
		perishable     = 2880,
		foodtype       = "VEGGIE",
		stacksize      = 40,
		burnable       = true,
		bank           = "kyno_sugarflywings",
		build          = "kyno_sugarflywings",
		anim           = "idle",
		animoffsetx    = 20,
		animoffsety    = -20,
		deps           = {"kyno_sugarfly"},
	},
	
	kyno_chicken_egg   =
	{
		name           = "kyno_chicken_egg",
		type           = "food",
		tex            = "kyno_chicken_egg.tex",
		prefab         = "kyno_chicken_egg",
		healthvalue    = 2,
		hungervalue    = 9.375,
		sanityvalue    = 0,
		perishable     = 2880,
		foodtype       = "MEAT",
		stacksize      = 40,
		bank           = "kyno_chicken_eggs",
		build          = "kyno_chicken_eggs",
		anim           = "idle",
		animoffsetx    = 20,
		animoffsety    = 30,
		animoffsetbgx  = -30,
		animoffsetbgy  = -120,
		deps           = {"kyno_chicken2", "kyno_chicken_egg_cooked", "rottenegg"},
	},
	
	kyno_chicken_egg_cooked   =
	{
		name           = "kyno_chicken_egg_cooked",
		type           = "food",
		tex            = "kyno_chicken_egg_cooked.tex",
		prefab         = "kyno_chicken_egg_cooked",
		healthvalue    = 3,
		hungervalue    = 12.5,
		sanityvalue    = 0,
		perishable     = 7200,
		foodtype       = "MEAT",
		stacksize      = 40,
		bank           = "kyno_chicken_eggs",
		build          = "kyno_chicken_eggs",
		anim           = "cooked",
		animoffsetx    = -60,
		animoffsety    = 15,
		animoffsetbgx  = -20,
		animoffsetbgy  = -20,
		deps           = {"kyno_chicken2", "kyno_chicken_egg", "rottenegg"},
	},
	
	kyno_crabmeat      =
	{
		name           = "kyno_crabmeat",
		type           = "food",
		tex            = "kyno_crabmeat.tex",
		prefab         = "kyno_crabmeat",
		healthvalue    = 5,
		hungervalue    = 5,
		sanityvalue    = -10,
		perishable     = 4800,
		foodtype       = "MEAT",
		stacksize      = 40,
		bank           = "quagmire_crabmeat",
		build          = "quagmire_crabmeat",
		anim           = "idle",
		deps           = {"kyno_pebblecrab", "crabking_mob", "crabking_mob_knight", "kyno_crabmeat_cooked", "kyno_crabmeat_dried", "meatrack", "meatrack_hermit", "spoiled_food"},
	},
	
	kyno_crabmeat_cooked =
	{
		name           = "kyno_crabmeat_cooked",
		type           = "food",
		tex            = "kyno_crabmeat_cooked.tex",
		prefab         = "kyno_crabmeat_cooked",
		healthvalue    = 10,
		hungervalue    = 10,
		sanityvalue    = 5,
		perishable     = 7200,
		foodtype       = "MEAT",
		stacksize      = 40,
		bank           = "quagmire_crabmeat",
		build          = "quagmire_crabmeat",
		anim           = "cooked",
		animoffsetbgy  = -30,
		deps           = {"kyno_crabmeat", "spoiled_food"},
	},
	
	kyno_crabmeat_dried =
	{
		name           = "kyno_crabmeat_dried",
		type           = "food",
		tex            = "kyno_crabmeat_dried.tex",
		prefab         = "kyno_crabmeat_dried",
		healthvalue    = 25,
		hungervalue    = 25,
		sanityvalue    = 10,
		perishable     = 9600,
		foodtype       = "MEAT",
		stacksize      = 20,
		bank           = "kyno_meatrack_crabmeat",
		build          = "kyno_meatrack_crabmeat",
		anim           = "kyno_crabmeat_dried",
		deps           = {"kyno_crabmeat", "meatrack", "meatrack_hermit", "spoiled_food"},
	},
	
	kyno_crabkingmeat  =
	{
		name           = "kyno_crabkingmeat",
		type           = "food",
		tex            = "kyno_crabkingmeat.tex",
		prefab         = "kyno_crabkingmeat",
		healthvalue    = -10,
		hungervalue    = 10,
		sanityvalue    = -10,
		perishable     = 4800,
		foodtype       = "MEAT",
		stacksize      = 20,
		bank           = "kyno_crabkingmeat",
		build          = "kyno_crabkingmeat",
		anim           = "idle",
		animoffsety    = 5,
		animoffsetbgy  = -40,
		deps           = {"crabking", "kyno_crabmeat_cooked", "kyno_crabmeat_dried", "meatrack", "meatrack_hermit", "spoiled_food"},
	},
	
	kyno_twiggynuts    =
	{
		name           = "kyno_twiggynuts",
		type           = "food",
		tex            = "kyno_twiggynuts.tex",
		prefab         = "kyno_twiggynuts",
		healthvalue    = 5,
		hungervalue    = 0,
		sanityvalue    = 5,
		perishable     = 19200,
		foodtype       = "VEGGIE",
		stacksize      = 40,
		burnable       = true,
		bank           = "kyno_twiggynuts",
		build          = "kyno_twiggynuts",
		anim           = "idle",
		deps           = {"twiggy_tall", "kyno_meadowisland_tree", "spoiled_food"},
	},
	
	kyno_oaktree_pod   =
	{
		name           = "kyno_oaktree_pod",
		type           = "food",
		tex            = "kyno_oaktree_pod.tex",
		prefab         = "kyno_oaktree_pod",
		perishable     = 7200,
		stacksize      = 40,
		burnable       = true,
		bank           = "kyno_meadowisland_tree_sapling",
		build          = "kyno_meadowisland_tree_sapling",
		anim           = "idle",
		animoffsetx    = -15,
		animoffsety    = 10,
		animoffsetbgx  = -20,
		animoffsetbgy  = -50,
		deps           = {"kyno_oaktree_pod_cooked", "kyno_meadowisland_tree_sapling", "kyno_meadowisland_tree", "spoiled_food"},
	},
	
	kyno_oaktree_pod_cooked =
	{
		name           = "kyno_oaktree_pod_cooked",
		type           = "food",
		tex            = "kyno_oaktree_pod_cooked.tex",
		prefab         = "kyno_oaktree_pod",
		healthvalue    = 0,
		hungervalue    = 9.375,
		sanityvalue    = 3,
		perishable     = 4800,
		stacksize      = 40,
		foodtype       = "RAW",
		burnable       = true,
		bank           = "kyno_meadowisland_tree_sapling",
		build          = "kyno_meadowisland_tree_sapling",
		anim           = "cooked",
		animoffsetx    = -10,
		animoffsetbgx  = -20,
		animoffsetbgy  = -30,
		deps           = {"kyno_oaktree_pod", "spoiled_food"},
	},
	
	kyno_nectar_pod    =
	{
		name           = "kyno_nectar_pod",
		type           = "food",
		tex            = "kyno_nectar_pod.tex",
		prefab         = "kyno_nectar_pod",
		healthvalue    = 3,
		hungervalue    = 9.375,
		sanityvalue    = 0,
		perishable     = 19200,
		stacksize      = 40,
		bank           = "nectar_pod",
		build          = "nectar_pod",
		anim           = "idle",
		deps           = {"beequeen", "bee", "kyno_antchest", "spoiled_food"},
		specialinfo    = "NECTAR",
	},
	
	kyno_koi           = 
	{
		name           = "kyno_koi",
		type           = "food",
		tex            = "kyno_koi.tex",
		prefab         = "kyno_koi",
		healthvalue    = 8,
		hungervalue    = 25,
		sanityvalue    = 0,
		perishable     = 1440,
		foodtype       = "MEAT",
		bank           = "koi",
		build          = "koi",
		anim           = "idle",
		animoffsetx    = -45,
		animoffsety    = 30,
		animoffsetbgy  = -60,
		deps           = {"kingfisher", "kyno_meadowisland_pond", "kyno_koi_cooked", "fishmeat", "fishmeat_cooked", "spoiled_fish"},
	},
	
	kyno_koi_cooked    = 
	{
		name           = "kyno_koi_cooked",
		type           = "food",
		tex            = "kyno_koi_cooked.tex",
		prefab         = "kyno_koi_cooked",
		healthvalue    = 8,
		hungervalue    = 25,
		sanityvalue    = 5,
		perishable     = 1440,
		foodtype       = "MEAT",
		stacksize      = 20,
		bank           = "koi_cooked",
		build          = "koi_cooked",
		anim           = "cooked",
		deps           = {"kingfisher", "kyno_koi", "spoiled_fish"},
	},
	
	kyno_neonfish      =
	{
		name           = "kyno_neonfish",
		type           = "food",
		tex            = "kyno_neonfish.tex",
		prefab         = "kyno_neonfish",
		healthvalue    = 8,
		hungervalue    = 25,
		sanityvalue    = 0,
		perishable     = 1440,
		foodtype       = "MEAT",
		bank           = "neonfish",
		build          = "neonfish",
		anim           = "idle",
		animoffsetx    = -50,
		animoffsety    = 30,
		animoffsetbgy  = -40,
		deps           = {"kyno_meadowisland_pond", "kyno_neonfish_cooked", "fishmeat", "fishmeat_cooked", "spoiled_fish"},
	},
	
	kyno_neonfish_cooked = 
	{
		name           = "kyno_neonfish_cooked",
		type           = "food",
		tex            = "kyno_neonfish_cooked.tex",
		prefab         = "kyno_neonfish_cooked",
		healthvalue    = 8,
		hungervalue    = 25,
		sanityvalue    = 5,
		perishable     = 1440,
		foodtype       = "MEAT",
		stacksize      = 20,
		bank           = "neonfish_cooked",
		build          = "neonfish_cooked",
		anim           = "cooked",
		animoffsety    = -15,
		animoffsetbgy  = -30,
		deps           = {"kyno_neonfish", "spoiled_fish"},
	},
	
	kyno_grouper       =
	{
		name           = "kyno_grouper",
		type           = "food",
		tex            = "kyno_grouper.tex",
		prefab         = "kyno_grouper",
		healthvalue    = 8,
		hungervalue    = 25,
		sanityvalue    = 0,
		perishable     = 1440,
		foodtype       = "MEAT",
		bank           = "grouper",
		build          = "grouper",
		anim           = "idle",
		animoffsetx    = -50,
		animoffsety    = 40,
		animoffsetbgy  = -70,
		deps           = {"pond_mos", "kyno_grouper_cooked", "fishmeat", "fishmeat_cooked", "spoiled_fish"},
	},
	
	kyno_grouper_cooked = 
	{
		name           = "kyno_grouper_cooked",
		type           = "food",
		tex            = "kyno_grouper_cooked.tex",
		prefab         = "kyno_grouper_cooked",
		healthvalue    = 8,
		hungervalue    = 25,
		sanityvalue    = 5,
		perishable     = 1440,
		foodtype       = "MEAT",
		stacksize      = 20,
		bank           = "grouper_cooked",
		build          = "grouper_cooked",
		anim           = "cooked",
		deps           = {"kyno_grouper", "spoiled_fish"},
	},
	
	kyno_tropicalfish  =
	{
		name           = "kyno_tropicalfish",
		type           = "food",
		tex            = "kyno_tropicalfish.tex",
		prefab         = "kyno_tropicalfish", 
		healthvalue    = 1,
		hungervalue    = 12.5,
		sanityvalue    = 0,
		perishable     = 1440,
		foodtype       = "MEAT",
		bank           = "tropicalfish",
		build          = "tropicalfish",
		anim           = "idle2",
		animoffsetx    = -20,
		animoffsety    = -50,
		deps           = {"kyno_meadowisland_pond", "kyno_tropicalfish_cooked", "fishmeat_small", "fishmeat_small_cooked", "spoiled_fish_small"},
	},
	
	kyno_tropicalfish_cooked =
	{
		name           = "kyno_tropicalfish_cooked",
		type           = "food",
		tex            = "kyno_tropicalfish_cooked.tex",
		prefab         = "kyno_tropicalfish_cooked",
		healthvalue    = 8,
		hungervalue    = 25,
		sanityvalue    = 5,
		perishable     = 1440,
		foodtype       = "MEAT",
		bank           = "tropicalfish_cooked",
		build          = "tropicalfish_cooked",
		anim           = "cooked",
		animoffsety    = 20,
		animoffsetbgy  = -40,
		deps           = {"kyno_tropicalfish", "spoiled_fish_small"},
	},
	
	kyno_pierrotfish   =
	{
		name           = "kyno_pierrotfish",
		type           = "food",
		tex            = "kyno_pierrotfish.tex",
		prefab         = "kyno_pierrotfish",
		healthvalue    = 1,
		hungervalue    = 12.5,
		sanityvalue    = 0,
		perishable     = 1440,
		foodtype       = "MEAT",
		bank           = "pierrotfish",
		build          = "pierrotfish",
		anim           = "idle",
		animoffsetx    = -45,
		animoffsety    = 30,
		animoffsetbgy  = -30,
		deps           = {"kyno_meadowisland_pond", "kyno_pierrotfish_cooked", "fishmeat_small", "fishmeat_small_cooked", "spoiled_fish_small"},
	},
	
	kyno_pierrotfish_cooked =
	{
		name           = "kyno_pierrotfish_cooked",
		type           = "food",
		tex            = "kyno_pierrotfish_cooked.tex",
		prefab         = "kyno_pierrotfish_cooked",
		healthvalue    = 8,
		hungervalue    = 25,
		sanityvalue    = 5,
		perishable     = 1440,
		foodtype       = "MEAT",
		stacksize      = 20,
		bank           = "pierrotfish_cooked",
		build          = "pierrotfish_cooked",
		anim           = "cooked",
		deps           = {"kyno_pierrotfish", "spoiled_fish_small"},
	},
	
	kyno_salmonfish    =
	{
		name           = "kyno_salmonfish",
		type           = "food",
		tex            = "kyno_salmonfish.tex",
		prefab         = "kyno_salmonfish",
		healthvalue    = 1,
		hungervalue    = 12.5,
		sanityvalue    = 0,
		perishable     = 1440,
		foodtype       = "MEAT",
		bank           = "salmonfish",
		build          = "salmonfish",
		anim           = "idle2",
		animoffsetx    = -10,
		animoffsetbgy  = -30,
		deps           = {"kyno_pond_salt", "kyno_salmonfish_cooked", "fishmeat_small", "fishmeat_small_cooked", "spoiled_fish_small"},
	},
	
	kyno_salmonfish_cooked =
	{
		name           = "kyno_salmonfish_cooked",
		type           = "food",
		tex            = "kyno_salmonfish_cooked.tex",
		prefab         = "kyno_salmonfish_cooked",
		healthvalue    = 8,
		hungervalue    = 25,
		sanityvalue    = 5,
		perishable     = 1440,
		foodtype       = "MEAT",
		stacksize      = 20,
		bank           = "salmonfish_cooked",
		build          = "salmonfish_cooked",
		anim           = "cooked",
		animoffsety    = -10,
		deps           = {"kyno_salmonfish", "spoiled_fish_small"},
	},
	
	kyno_banana        =
	{
		name           = "kyno_banana",
		type           = "food",
		tex            = "kyno_banana.tex",
		prefab         = "kyno_banana",
		healthvalue    = 1,
		hungervalue    = 12.5,
		sanityvalue    = 0,
		perishable     = 2880,
		foodtype       = "VEGGIE",
		burnable       = true,
		stacksize      = 40,
		bank           = "kyno_banana",
		build          = "kyno_banana",
		anim           = "idle",
		deps           = {"bananabush", "kyno_meadowisland_crate", "kyno_banana_cooked", "spoiled_food"},
	},
	
	kyno_banana_cooked =
	{
		name           = "kyno_banana_cooked",
		type           = "food",
		tex            = "kyno_banana_cooked.tex",
		prefab         = "kyno_banana_cooked",
		healthvalue    = 3,
		hungervalue    = 12.5,
		sanityvalue    = 0,
		perishable     = 2880,
		foodtype       = "VEGGIE",
		burnable       = true,
		stacksize      = 40,
		bank           = "kyno_banana",
		build          = "kyno_banana",
		anim           = "cooked",
		deps           = {"kyno_banana", "spoiled_food"},
	},
	
	kyno_tunacan_open  = 
	{
		name           = "kyno_tunacan_open",
		type           = "food",
		subcat         = "canned",
		tex            = "kyno_tunacan_open.tex",
		prefab         = "kyno_tunacan_open",
		healthvalue    = 10,
		hungervalue    = 25,
		sanityvalue    = 0,
		perishable     = 7200,
		foodtype       = "MEAT",
		bank           = "kyno_tuna",
		build          = "kyno_tuna",
		anim           = "opened",
		--deps           = {"kyno_tunacan", "spoiled_fish"},
	},
	
	kyno_tomatocan_open  = 
	{
		name           = "kyno_tomatocan_open",
		type           = "food",
		subcat         = "canned",
		tex            = "kyno_tomatocan_open.tex",
		prefab         = "kyno_tomatocan_open",
		healthvalue    = 12.5,
		hungervalue    = 20,
		sanityvalue    = 0,
		perishable     = 7200,
		foodtype       = "VEGGIE",
		bank           = "kyno_cannedfoods",
		build          = "kyno_cannedfoods",
		anim           = "tomato_opened",
		--deps           = {"kyno_tomatocan", "spoiled_food"},
	},
	
	kyno_beancan_open  = 
	{
		name           = "kyno_beancan_open",
		type           = "food",
		subcat         = "canned",
		tex            = "kyno_beancan_open.tex",
		prefab         = "kyno_beancan_open",
		healthvalue    = 0,
		hungervalue    = 20,
		sanityvalue    = 10,
		perishable     = 7200,
		foodtype       = "VEGGIE",
		bank           = "kyno_cannedfoods",
		build          = "kyno_cannedfoods",
		anim           = "bean_opened",
		--deps           = {"kyno_beancan", "spoiled_food"},
	},
	
	kyno_meatcan_open  = 
	{
		name           = "kyno_meatcan_open",
		type           = "food",
		subcat         = "canned",
		tex            = "kyno_meatcan_open.tex",
		prefab         = "kyno_meatcan_open",
		healthvalue    = 5,
		hungervalue    = 25,
		sanityvalue    = 0,
		perishable     = 7200,
		foodtype       = "MEAT",
		bank           = "kyno_cannedfoods",
		build          = "kyno_cannedfoods",
		anim           = "meat_opened",
		--deps           = {"kyno_meatcan", "spoiled_food"},
	},
	
	kyno_sodacan       =
	{
		name           = "kyno_sodacan",
		type           = "food",
		subcat         = "canned",
		tex            = "kyno_sodacan.tex",
		prefab         = "kyno_sodacan",
		healthvalue    = -8,
		hungervalue    = 0,
		sanityvalue    = 33,
		perishable     = 19200,
		foodtype       = "GOODIES",
		bank           = "kyno_pops",
		build          = "kyno_pops",
		anim           = "sodacan",
		--deps           = {"sunkenchest", "kyno_serenityisland_crate", "kyno_meadowisland_crate"},
	},
	
	kyno_cokecan       =
	{
		name           = "kyno_cokecan",
		type           = "food",
		subcat         = "canned",
		tex            = "kyno_cokecan.tex",
		prefab         = "kyno_cokecan",
		healthvalue    = -8,
		hungervalue    = 0,
		sanityvalue    = 33,
		perishable     = 19200,
		foodtype       = "GOODIES",
		bank           = "kyno_pops",
		build          = "kyno_pops",
		anim           = "cokecan",
		--deps           = {"sunkenchest", "kyno_serenityisland_crate", "kyno_meadowisland_crate"},
	},
	
	kyno_energycan     =
	{
		name           = "kyno_energycan",
		type           = "food",
		subcat         = "canned",
		tex            = "kyno_energycan.tex",
		prefab         = "kyno_energycan",
		healthvalue    = -8,
		hungervalue    = 0,
		sanityvalue    = 33,
		perishable     = 19200,
		foodtype       = "GOODIES",
		bank           = "kyno_pops",
		build          = "kyno_pops",
		anim           = "energycan",
		--deps           = {"sunkenchest", "kyno_serenityisland_crate", "kyno_meadowisland_crate"},
	},
}

local HOF_SCRAPBOOK_PREPAREDFOODS =
{
	coffee             = 
	{
        name           = "coffee",	
        type           = "food",
		tex            = "coffee.tex",
        prefab         = "coffee",
		healthvalue    = 5,
		hungervalue    = 9.735,
		sanityvalue    = -10,
        perishable     = 4800,
        foodtype       = "GOODIES",
		burnable       = true,
		stacksize      = 40,
		bank           = "coffee",
		build          = "coffee",
		overridesymbol = {"swap_food", "swap_food", "coffee"},
		anim           = "idle",
		animoffsetx    = -10,
		animoffsety    = 30,
		animoffsetbgx  = -30,
		animoffsetbgy  = -110,
        deps           = {"cookpot", "portablecookpot", "archive_cookpot", "spoiled_food"},
		specialinfo    = "FOODEFFECTS_COFFEE",
    },
	
	gorge_caramel_cube =
	{
		name           = "gorge_caramel_cube",	
        type           = "food",
		tex            = "gorge_caramel_cube.tex",
        prefab         = "gorge_caramel_cube",
		healthvalue    = 60,
		hungervalue    = 40,
		sanityvalue    = 50,
        perishable     = 19200,
        foodtype       = "GOODIES",
		burnable       = true,
		stacksize      = 40,
		bank           = "gorge_caramel_cube",
		build          = "gorge_caramel_cube",
		overridesymbol = {"swap_food", "swap_food", "gorge_caramel_cube"},
		anim           = "idle",
		animoffsetx    = 65,
		animoffsety    = -70,
		animoffsetbgx  = -30,
		animoffsetbgy  = -40,
        deps           = {"cookpot", "portablecookpot", "archive_cookpot", "kyno_serenityisland_shop", "spoiled_food"},
		specialinfo    = "CARAMELCUBE",
	},
}

local HOF_SCRAPBOOK_CREATURES =
{
	kyno_chicken2      =
	{
		name           = "kyno_chicken2",
		type           = "creature",
		tex            = "kyno_chicken2.tex",
		prefab         = "kyno_chicken2",
		health         = 75,
		perishable     = 2400,
		bank           = "chicken",
		build          = "chicken",
		anim           = "idle",
		animoffsety    = 40,
		animoffsetbgy  = -65,		
		deps           = {"drumstick", "drumstick_cooked", "goose_feather", "kyno_chicken_egg"},
		specialinfo    = "FEEDCHICKEN",
	},
	
	kyno_piko          =
	{
		name           = "kyno_piko",
		type           = "creature",
		subcat         = "piko",
		tex            = "kyno_piko.tex",
		prefab         = "kyno_piko",
		health         = 100,
		perishable     = 2400,
		bank           = "squirrel",
		build          = "squirrel_build",
		hidesymbol     = {"eye_red", "eye2_red"},
		anim           = "idle",
		animoffsety    = 40,
		animoffsetx    = -10,
		animoffsetbgx  = -20,
		animoffsetbgy  = -75,
		deps           = {"kyno_meadowisland_pikotree", "smallmeat", "cookedsmallmeat"},
		specialinfo    = "PIKO",
	},
	
	kyno_piko_orange   =
	{
		name           = "kyno_piko_orange",
		type           = "creature",
		subcat         = "piko",
		tex            = "kyno_piko_orange.tex",
		prefab         = "kyno_piko_orange",
		health         = 100,
		perishable     = 2400,
		bank           = "squirrel",
		build          = "orange_squirrel_build",
		hidesymbol     = {"eye_red", "eye2_red"},
		anim           = "idle",
		animoffsetx    = -15,
		animoffsety    = 25,
		animoffsetbgx  = -20,
		animoffsetbgy  = -30,
		deps           = {"kyno_meadowisland_pikotree", "smallmeat", "cookedsmallmeat"},
		specialinfo    = "PIKO",
	},
	
	kingfisher         =
	{
		name           = "kingfisher",
		type           = "creature",
		subcat         = "bird",
		tex            = "kingfisher.tex",
		prefab         = "kingfisher",
		health         = 25,
		perishable     = 2400,
		bank           = "crow",
		build          = "kingfisher_build",
		anim           = "idle",
		scale          = .85,
		animoffsetx    = -10,
		deps           = {"cutgrass", "twigs", "feather_robin_winter", "kyno_bacon", "kyno_bacon_cooked", "kyno_koi"},
		specialinfo    = "KINGFISHER",
	},
	
	toucan             =
	{
		name           = "toucan",
		type           = "creature",
		subcat         = "bird",
		tex            = "toucan.tex",
		prefab         = "toucan",
		health         = 25,
		perishable     = 2400,
		bank           = "crow",
		build          = "toucan_build",
		anim           = "idle",
		animoffsetx    = -20,
		animoffsety    = 20,
		deps           = {"cutgrass", "twigs", "feather_crow", "smallmeat", "cookedsmallmeat"},
	},
	
	quagmire_pigeon    =
	{
		name           = "quagmire_pigeon",
		type           = "creature",
		subcat         = "bird",
		tex            = "quagmire_pigeon.tex",
		prefab         = "quagmire_pigeon",
		health         = 25,
		perishable     = 2400,
		bank           = "crow",
		build          = "quagmire_pigeon_build",
		anim           = "idle",
		deps           = {"cutgrass", "twigs", "feather_robin_winter", "kyno_bacon", "kyno_bacon_cooked"},
	},
	
	kyno_sugarfly      =
	{
		name           = "kyno_sugarfly",
		type           = "creature",
		subcat         = "insect",
		tex            = "kyno_sugarfly.tex",
		prefab         = "kyno_sugarfly",
		health         = 1,
		perishable     = 1440,
		stacksize      = 20,
		workable       = "NET",
		bank           = "kyno_sugarfly",
		build          = "kyno_sugarfly",
		anim           = "idle",
		animoffsetbgy  = -30,
		deps           = {"kyno_sugarflywings"},
	},
	
	kyno_pebblecrab    =
	{
		name           = "kyno_pebblecrab",
		type           = "creature",
		tex            = "kyno_pebblecrab.tex",
		prefab         = "kyno_pebblecrab",
		health         = 50,
		perishable     = 2400,
		bank           = "quagmire_pebble_crab",
		build          = "quagmire_pebble_crab",
		anim           = "idle",
		animoffsety    = 20,
		deps           = {"kyno_crabtrap_installer", "kyno_crabmeat", "kyno_crabmeat_cooked"},
	},
}

local HOF_SCRAPBOOK_OTHERS =
{
	kyno_mealgrinder   = 
	{
		name           = "kyno_mealgrinder",
		type           = "thing",
		subcat         = "craftingstation",
		tex            = "kyno_mealgrinder.tex",
		prefab         = "kyno_mealgrinder",
		workable       = "HAMMER",
		bank           = "quagmire_mealingstone",
		build          = "quagmire_mealingstone",
		anim           = "idle",
		deps           = {"kyno_flour", "kyno_spotspice", "kyno_salt", "kyno_bacon", "kyno_oil", "kyno_sugar"},
		specialinfo    = "MEALGRINDER",
	},
	
	kyno_antchest      =
	{
		name           = "kyno_antchest",
		type           = "thing",
		subcat         = "container",
		tex            = "kyno_antchest.tex",
		prefab         = "kyno_antchest",
		workable       = "HAMMER",
		burnable       = true,
		bank           = "ant_chest",
		build          = "ant_chest_honey_build",
		anim           = "closed",
		deps           = {"beequeen", "honey", "honeycomb", "kyno_nectar_pod", "boards"},
		specialinfo    = "ANTCHEST",
	},

	kyno_serenityisland_shop =
	{
		name           = "kyno_serenityisland_shop",
		type           = "POI",
		tex            = "kyno_serenityisland_shop.tex",
		prefab         = "kyno_serenityisland_shop",
		bank           = "quagmire_elderswampig",
		build          = "quagmire_elderswampig",
		anim           = "idle",
		deps           = {"kyno_saltrack_installer", "kyno_crabtrap_installer", "kyno_sugartree_petals", "lobsterdinner", "gorge_caramel_cube", "dug_kyno_spotbush", "dug_kyno_wildwheat"},
		specialinfo    = "PIGELDER",
	},
	
	kyno_pond_salt     = 
	{
		name           = "kyno_pond_salt",
		speechname     = "quagmire_pond_salt",
		type           = "thing",
		tex            = "kyno_pond_salt.tex",
		prefab         = "kyno_pond_salt",
		fishable       = true,
		bank           = "quagmire_salt_pond",
		build          = "quagmire_salt_pond",
		anim           = "idle",
		scale          = 1.5, 
		animoffsetx    = 40,
		animoffsety    = -37,
		deps           = {"saltrock", "kyno_saltrack_installer", "kyno_salmonfish"},
		specialinfo    = "SALTPOND",
	},
	
	kyno_sugartree_flower =
	{
		name           = "kyno_sugartree_flower",
		type           = "thing",
		tex            = "kyno_sugartree_flower.tex",
		prefab         = "kyno_sugartree_flower",
		pickable       = true,
		burnable       = true,
		bank           = "kyno_serenityisland_bud",
		build          = "kyno_serenityisland_bud",
		anim           = "idle1",
		scale          = 2,
		animoffsetx    = 77,
		animoffsety    = -15,
		animoffsetbgy  = -75,
		deps           = {"kyno_sugartree_petals"},
	},
	
	--[[
	kyno_serenityisland_crate =
	{
		name           = "kyno_serenityisland_crate",
		type           = "thing",
		tex            = "kyno_serenityisland_crate.tex",
		prefab         = "kyno_serenityisland_crate",
		workable       = "HAMMER",
		pickable       = true,
		burnable       = true,
		bank           = "graves_water",
		build          = "graves_water",
		anim           = "idle1",
		deps           = {"cutgrass", "twigs", "log", "rope", "boards", "seeds", "kelp", "meat_dried", "silk", "livinglog", "batwing", "saltrock", "wormlight", 
		"wormlight_lesser", "boneshard", "purplegem", "bluegem", "orangegem", "yellowgem", "greengem", "mandrake", "kyno_tunacan", "kyno_tomatocan", "kyno_beancan",
		"kyno_meatcan", "kyno_waterycress", "kyno_taroroot", "kyno_seaweeds", "kyno_limpets", "kyno_sodacan", "kyno_cokecan", "kyno_energycan", "kyno_oil",
		"kyno_lotus_flower", "kyno_cucumber", "kyno_roe", "kyno_mysterymeat", "kyno_fishpackage"},
	},
	]]--
	
	kyno_meadowisland_pond =
	{
		name           = "kyno_meadowisland_pond",
		type           = "thing",
		tex            = "kyno_meadowisland_pond.tex",
		prefab         = "kyno_meadowisland_pond",
		fishable       = true,
		bank           = "kyno_meadowisland_pond",
		build          = "kyno_meadowisland_pond",
		anim           = "med_idle",
		scale          = 1.4,
		animoffsetx    = 60,
		animoffsety    = 30,
		animoffsetbgy  = -75,
		deps           = {"kyno_koi", "kyno_tropicalfish", "kyno_pierrotfish", "kyno_neonfish"},
	},
	
	kyno_meadowisland_tree_sapling =
	{
		name           = "kyno_meadowisland_tree_sapling",
		speechname     = "pinecone",
		type           = "thing",
		tex            = "kyno_meadowisland_tree_sapling.tex",
		prefab         = "kyno_meadowisland_tree_sapling",
		workable       = "DIG",
		burnable       = true,
		bank           = "kyno_meadowisland_tree_sapling",
		build          = "kyno_meadowisland_tree_sapling",
		anim           = "planted",
		animoffsetbgy  = -65,
		deps           = {"twigs", "kyno_oaktree_pod", "kyno_meadowisland_tree"}
	},
	
	kyno_meadowisland_tree =
	{
		name           = "kyno_meadowisland_tree",
		type           = "thing",
		subcat         = "tree",
		tex            = "kyno_meadowisland_tree.tex",
		prefab         = "kyno_meadowisland_tree",
		workable       = "CHOP",
		burnable       = true,
		bank           = "tree_leaf",
		build          = "teatree_trunk_build",
		overridesymbol = {"swap_leaves", "teatree_build", "swap_leaves"},
		anim           = "idle_tall",
		animoffsety    = -20,
		scale          = .90,
		deps           = {"charcoal", "driftwood_log", "kyno_meadowisland_tree_sapling", "kyno_twiggynuts", "kyno_oaktree_pod"},
		specialinfo    = "TREE",
	},
	
	kyno_meadowisland_pikotree =
	{
		name           = "kyno_meadowisland_pikotree",
		type           = "thing",
		subcat         = "tree",
		tex            = "kyno_meadowisland_pikotree.tex",
		prefab         = "kyno_meadowisland_pikotree",
        workable       = "CHOP",
		burnable       = true,
		bank           = "tree_leaf",
		build          = "teatree_trunk_build",
		overridesymbol = {"swap_leaves", "teatree_build", "swap_leaves"},
		anim           = "idle_tall",
		animoffsety    = -20,
		scale          = .90,
		deps           = {"kyno_piko", "kyno_piko_orange", "charcoal", "driftwood_log", "kyno_meadowisland_tree_sapling", "kyno_twiggynuts", "kyno_oaktree_pod"},
		specialinfo    = "PIKOTREE",
	},
	
	kyno_meadowisland_crate =
	{
		name           = "kyno_meadowisland_crate",
		type           = "thing",
		tex            = "kyno_meadowisland_crate.tex",
		prefab         = "kyno_meadowisland_crate",
		workable       = "HAMMER",
		burnable       = true,
		bank           = "kyno_meadowisland_crate",
		build          = "kyno_meadowisland_crate",
		anim           = "idle4",
		deps           = {"boards", "cutreeds", "rope", "goldnugget", "mandrake", "trinket_4", "trinket_11", "trinket_13", "trinket_26", 
		"kyno_tunacan", "kyno_tomatocan", "kyno_meatcan", "kyno_beancan", "kyno_sodacan", "kyno_cokecan", "kyno_energycan", "kyno_oil", 
		"kyno_banana", "kyno_mysterymeat"},
	},
	
	kyno_spotbush      = 
	{
		name           = "kyno_spotbush",
		type           = "thing",
		tex            = "kyno_spotbush.tex",
		prefab         = "kyno_spotbush",
		workable       = "DIG",
		pickable       = true,
		burnable       = true,
		bank           = "quagmire_spiceshrub",
		build          = "quagmire_spiceshrub",
		anim           = "idle",
		deps           = {"dug_kyno_spotbush", "kyno_spotspice_leaf"},
		specialinfo    = "NEEDFERTILIZER",
	},
	
	kyno_wildwheat     =
	{
		name           = "kyno_wildwheat",
		type           = "thing",
		tex            = "kyno_wildwheat",
		prefab         = "kyno_wildwheat",
		workable       = "DIG",
		pickable       = true,
		burnable       = true,
		bank           = "kyno_wheat",
		build          = "kyno_wheat",
		anim           = "idle",
		animoffsety    = 20,
		animoffsetbgy  = -30,
		deps           = {"dug_kyno_wildwheat", "kyno_wheat"},
		specialinfo    = "NEEDFERTILIZER",
	},
}

-- Register the entries in the Scrapbook.
local function AddExtraScrapBookItem(sbdata, sbprefab, sbtable)
    for k, v in pairs(sbtable) do
        sbprefab[k] = true
        sbdata[k] = v
    end
end

-- Add our entries to the Scrapbook.
AddExtraScrapBookItem(ScrapbookData, ScrapbookPrefabs, HOF_SCRAPBOOK_ITEMS)
AddExtraScrapBookItem(ScrapbookData, ScrapbookPrefabs, HOF_SCRAPBOOK_FOODS)
AddExtraScrapBookItem(ScrapbookData, ScrapbookPrefabs, HOF_SCRAPBOOK_PREPAREDFOODS)
AddExtraScrapBookItem(ScrapbookData, ScrapbookPrefabs, HOF_SCRAPBOOK_CREATURES)
AddExtraScrapBookItem(ScrapbookData, ScrapbookPrefabs, HOF_SCRAPBOOK_OTHERS)