local WORMWOOD = STRINGS.CHARACTERS.WORMWOOD

WORMWOOD.ANNOUNCE_KYNO_COFFEEBUFF_START = "Wziuuum!"
WORMWOOD.ANNOUNCE_KYNO_COFFEEBUFF_END = "Szybkość... poszła?"

WORMWOOD.ANNOUNCE_KYNO_HASTEBUFF_START = "Zuuuumm!"
WORMWOOD.ANNOUNCE_KYNO_HASTEBUFF_END = "Gdzie zniknął Zuuum?"

WORMWOOD.ANNOUNCE_KYNO_POPBUFF_START = "(Buuurp)"
WORMWOOD.ANNOUNCE_KYNO_POPBUFF_END = "Bąbelki... poszły?"

WORMWOOD.ANNOUNCE_KYNO_FROGBUFF_START = "Żabki!"
WORMWOOD.ANNOUNCE_KYNO_FROGBUFF_END = "Nie ma żabki?"

WORMWOOD.ANNOUNCE_KYNO_PIRATEBUFF_START = "(Buurp)"
WORMWOOD.ANNOUNCE_KYNO_PIRATEBUFF_END = "Bąbelki nie ma?"

WORMWOOD.ANNOUNCE_KYNO_FREEZEBUFF_START = "Brrr"
WORMWOOD.ANNOUNCE_KYNO_FREEZEBUFF_END = "Mróz minął"

WORMWOOD.ANNOUNCE_KYNO_FIREBUFF_START = "Gorąco!"
WORMWOOD.ANNOUNCE_KYNO_FIREBUFF_END = "Płomień minął"

WORMWOOD.ANNOUNCE_KYNO_FISHINGBUFF_START = "Czas na ryby!"
WORMWOOD.ANNOUNCE_KYNO_FISHINGBUFF_END = "Ryby?"

WORMWOOD.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "Relaks!"
WORMWOOD.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "Relaks minął"

WORMWOOD.ANNOUNCE_KYNO_EATERBUFF_START = "Silny brzuch!"
WORMWOOD.ANNOUNCE_KYNO_EATERBUFF_END = "Brzuch normalny?"

WORMWOOD.ANNOUNCE_KYNO_WORMBUFF_START = "Jupi"
WORMWOOD.ANNOUNCE_KYNO_WORMBUFF_END = "Koniec?"

WORMWOOD.ANNOUNCE_KYNO_CRABBUFF_START = "Jupi"
WORMWOOD.ANNOUNCE_KYNO_CRABBUFF_END = "Koniec?"

WORMWOOD.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(Buuurp)"
WORMWOOD.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "Bąbelki wyjęte?"

WORMWOOD.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "Czuję się dziwnie"
WORMWOOD.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "Czuję się lepiej"

WORMWOOD.ANNOUNCE_KYNO_STEALTHBUFF_START = "Cicho teraz"
WORMWOOD.ANNOUNCE_KYNO_STEALTHBUFF_END = "Koniec skradania?"

WORMWOOD.ANNOUNCE_KYNO_FEARBUFF_START = "Czuję... spokój"
WORMWOOD.ANNOUNCE_KYNO_FEARBUFF_END = "Złe uczucie... wróciło!"

WORMWOOD.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "Łaskocze! Hee-hee!"
WORMWOOD.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "Nie ma już błyszczącej mocy..."

WORMWOOD.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "Robienie przyjaciół Świnek"
WORMWOOD.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "Świnki zniknęły"

WORMWOOD.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "Deszcz już nie boli!"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WORMWOOD.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "Nie chory! Dobrze czuć!"
WORMWOOD.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "Znowu źle czuć."

WORMWOOD.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "Mózg Duży Teraz"
WORMWOOD.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "Mózg Zmęczony Teraz"

WORMWOOD.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "Bzz Bzz Przyjaciele! Yay!"
WORMWOOD.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "Bzz Bzz Złe!"

WORMWOOD.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "Silny! Bardzo silny!"
WORMWOOD.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "Już nie silny..."

WORMWOOD.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "Brzuszek rośnie!"
WORMWOOD.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "Brzuszek znów mały..."

WORMWOOD.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "Głowa dobra!"
WORMWOOD.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "Głowa kręci znowu..."

WORMWOOD.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "Twardy! Bezpieczny!"
WORMWOOD.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "Miękki znowu."

WORMWOOD.ANNOUNCE_KYNO_BERSERKERBUFF_START = "Uderza mocniej. Boli bardziej."
WORMWOOD.ANNOUNCE_KYNO_BERSERKERBUFF_END = "Już nie boli tak bardzo."

WORMWOOD.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "Nie głodny szybko."
WORMWOOD.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "Głodny znowu."

WORMWOOD.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "Nie"

WORMWOOD.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "Chce Rocky'ego Gluba Gluba"

WORMWOOD.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "Przyjaciel za młody?"

WORMWOOD.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "Nie chcesz?"

WORMWOOD.ANNOUNCE_KYNO_POTHANGER_FAIL = "Chce czegoś innego"

WORMWOOD.ANNOUNCE_KYNO_CASSEROLE_FAIL = "Nie to?"

WORMWOOD.ANNOUNCE_KYNO_SAPHEALER_USED = "Sok pomaga przyjacielowi!"

WORMWOOD.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "Och... Przestań się ruszać..."

WORMWOOD.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "Wszystko zniknęło."

WORMWOOD.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "Bąbelki Znikły?"
WORMWOOD.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "Woda spadła... Bąbelki Znikły"
WORMWOOD.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "Duża Rzecz Pływa... Niebezpieczeństwo?"

WORMWOOD.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "Duża Słodkość gotowa!"

WORMWOOD.ANNOUNCE_KYNO_FISH_RESEARCHED = "Glub Glub Powiedział Mi Rzeczy!"
WORMWOOD.ANNOUNCE_KYNO_ROE_RESEARCHED = "Teraz Wie O Małych Glub Glubach"

WORMWOOD.DESCRIBE.KYNO_ROE = "Małe Plums Plums"
WORMWOOD.DESCRIBE.KYNO_ROE_COOKED = "Równe rządki."

WORMWOOD.DESCRIBE.KYNO_SHARK_FIN = "Wodny nóż"

WORMWOOD.DESCRIBE.KYNO_BEANBUGS = "Skaczące"
WORMWOOD.DESCRIBE.KYNO_BEANBUGS_COOKED = "Dlaczego już nie skaczą?"

WORMWOOD.DESCRIBE.KYNO_GUMMYBUG = "Śliskie"
WORMWOOD.DESCRIBE.KYNO_GUMMYBUG_COOKED = "Witaj, małe patyczki!"

WORMWOOD.DESCRIBE.KYNO_WHEAT = "Och! Śliczne nasionka!"
WORMWOOD.DESCRIBE.KYNO_WHEAT_COOKED = "Och! Śliczne nasionka!"

WORMWOOD.DESCRIBE.KYNO_FLOUR = "Zmielona rzecz."

WORMWOOD.DESCRIBE.KYNO_SPOTSPICE = "Sprawia, że jedzenie smakuje lepiej."

WORMWOOD.DESCRIBE.KYNO_SAP = "Wnętrze przyjaciela na wierzchu"
WORMWOOD.DESCRIBE.KYNO_SAP_SPOILED = "Nie nie nie!"

WORMWOOD.DESCRIBE.KYNO_SYRUP = "Robi słodkie rzeczy"

WORMWOOD.DESCRIBE.KYNO_COFFEEBEANS = "Błyskawiczne jagody!"
WORMWOOD.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "Ładnie pachnie."

WORMWOOD.DESCRIBE.DUG_KYNO_COFFEEBUSH = "Przyjaciel Zoomberry potrzebuje ziemi"

WORMWOOD.DESCRIBE.KYNO_COFFEEBUSH =
{
	GENERIC = "Przyjaciel Zoomberry",
	PICKED = "Pusty",
	WITHERED = "Przyjaciel potrzebuje pomocy",
}

WORMWOOD.DESCRIBE.DUG_KYNO_SPOTBUSH = "Cześć, przyjacielu"

WORMWOOD.DESCRIBE.KYNO_SPOTBUSH =
{
	GENERIC = "Przyjaciel ma fioletowe włosy",
	PICKED = "Gdzie podziały się włosy przyjaciela?",
	BURNING = "Przyjaciel cierpi!",
}

WORMWOOD.DESCRIBE.KYNO_SPOTSPICE_LEAF = "Mały listek."

WORMWOOD.DESCRIBE.KYNO_MUSSEL = "Chowa się."
WORMWOOD.DESCRIBE.KYNO_MUSSEL_COOKED = "Dla brzuszka."

WORMWOOD.DESCRIBE.KYNO_HUMANMEAT = "Rzecz do brzucha"
WORMWOOD.DESCRIBE.KYNO_HUMANMEAT_COOKED = "Mmmm..."
WORMWOOD.DESCRIBE.KYNO_HUMANMEAT_DRIED = "Ciężkie do pogryzienia"

WORMWOOD.DESCRIBE.COFFEE = "Wheee!!!"

WORMWOOD.DESCRIBE.BISQUE = "Pływające jedzenie do brzuszka."

WORMWOOD.DESCRIBE.JELLYOPOP = "Zimny Glub Glub Blob"

WORMWOOD.DESCRIBE.SHARKFINSOUP = "Wciąż pływa"

WORMWOOD.DESCRIBE.TROPICALBOUILLABAISSE = "Glub Gluby?"

WORMWOOD.DESCRIBE.MUSSELBOUILLABAISE = "Dobre dla brzuszka."

WORMWOOD.DESCRIBE.SWEETPOTATOSOUFFLE = "Rzecz na brzuszek"

WORMWOOD.DESCRIBE.FEIJOADA = "Pełne Jumpów"

WORMWOOD.DESCRIBE.GUMMY_CAKE = "Mięciutkie"

WORMWOOD.DESCRIBE.HARDSHELL_TACOS = "Chrupiące Bzztery"

WORMWOOD.DESCRIBE.ICEDTEA = "Zimna Złota Woda"

WORMWOOD.DESCRIBE.NETTLELOSANGE = "Mmm..."

WORMWOOD.DESCRIBE.SNAKEBONESOUP = "Woda z robakami."

WORMWOOD.DESCRIBE.STEAMEDHAMSANDWICH = "O rany!"

WORMWOOD.DESCRIBE.TEA = "Ciepła zippowata woda"

WORMWOOD.DESCRIBE.BUBBLETEA = "Zimna zippowata woda"

WORMWOOD.DESCRIBE.FRENCHONIONSOUP = "Wodna wijka."

WORMWOOD.DESCRIBE.SLAW = "Brzuchowa imprezka!"

WORMWOOD.DESCRIBE.LOTUSBOWL = "Dobre dla brzuszka."

WORMWOOD.DESCRIBE.POI = "Jedzenie dla brzuszka."

WORMWOOD.DESCRIBE.JELLYBEAN_HUNGER = "Mmmmm!"
WORMWOOD.DESCRIBE.JELLYBEAN_SUPER = "Mmmmm!"
WORMWOOD.DESCRIBE.JELLYBEAN_SANITY = "Mmmmm!"

WORMWOOD.DESCRIBE.BOWLOFGEARS = "Metalowe rzeczy."

WORMWOOD.DESCRIBE.LONGPIGMEAL = "Mmm...."

WORMWOOD.DESCRIBE.CUCUMBERSALAD = "Chcę to zjeść"

WORMWOOD.DESCRIBE.DUG_KYNO_WILDWHEAT = "Przyjaciel potrzebuje ziemi"

WORMWOOD.DESCRIBE.KYNO_WILDWHEAT =
{
	GENERIC = "Przyjaciel",
	PICKED = "Pusty",
	WITHERED = "Przyjaciel niezadowolony",
	BURNING = "Boli!!",
}

WORMWOOD.DESCRIBE.KYNO_MEALGRINDER = "Maszyna kamienna"

WORMWOOD.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "Przyjaciele! Impreza!",
	PICKED = "Och. Przyjaciele odeszli",
	BURNING = "Boli!",
}

WORMWOOD.DESCRIBE.GORGE_BREAD = "Puszyste"
WORMWOOD.DESCRIBE.GORGE_SWEET_CHIPS = "Chipsy"
WORMWOOD.DESCRIBE.GORGE_VEGETABLE_SOUP = "Warzywa!"
WORMWOOD.DESCRIBE.GORGE_JELLY_SANDWICH = "Dla Brzuszka"
WORMWOOD.DESCRIBE.GORGE_FISH_STEW = "Rybne"
WORMWOOD.DESCRIBE.GORGE_MEAT_STEW = "Dla Brzucha"
WORMWOOD.DESCRIBE.GORGE_ONION_CAKE = "Ciasto!"
WORMWOOD.DESCRIBE.GORGE_POTATO_PANCAKES = "Gdzie poszły ziemniaki?"
WORMWOOD.DESCRIBE.GORGE_POTATO_SOUP = "Pływające w brzuchu rzeczy."
WORMWOOD.DESCRIBE.GORGE_FISHBALL_SKEWERS = "Rybne"
WORMWOOD.DESCRIBE.GORGE_MEAT_SKEWERS = "Mięsne"
WORMWOOD.DESCRIBE.GORGE_STONE_SOUP = "Pływające w brzuchu rzeczy."
WORMWOOD.DESCRIBE.GORGE_CROQUETTE = "Brzuszkowe jedzenie."
WORMWOOD.DESCRIBE.GORGE_ROAST_VEGETABLES = "Zielone Brzuszkowe Jedzenie"
WORMWOOD.DESCRIBE.GORGE_MEATLOAF = "Mięsne."
WORMWOOD.DESCRIBE.GORGE_CARROT_SOUP = "Pływająca rzecz w brzuchu."
WORMWOOD.DESCRIBE.GORGE_FISHPIE = "Zatopiona ryba?"
WORMWOOD.DESCRIBE.GORGE_FISHCHIPS = "Zapycha brzuch."
WORMWOOD.DESCRIBE.GORGE_MEATPIE = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_SLIDERS = "Małe Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_JELLY_ROLL = "Zapycha brzuch"
WORMWOOD.DESCRIBE.GORGE_CARROT_CAKE = "Ciasto!"
WORMWOOD.DESCRIBE.GORGE_GARLICMASHED = "Zapycha brzuch."
WORMWOOD.DESCRIBE.GORGE_GARLICBREAD = "Zapycha Brzuch."
WORMWOOD.DESCRIBE.GORGE_TOMATO_SOUP = "Pływająca rzecz dla brzucha."
WORMWOOD.DESCRIBE.GORGE_SAUSAGE = "Rzecz dla brzucha."
WORMWOOD.DESCRIBE.GORGE_CANDIEDFISH = "Słodkie jedzenie dla brzucha."
WORMWOOD.DESCRIBE.GORGE_STUFFEDMUSHROOM = "Jedzenie dla brzucha."
WORMWOOD.DESCRIBE.GORGE_BRUSCHETTA = "Jedzenie dla brzucha."
WORMWOOD.DESCRIBE.GORGE_HAMBURGER = "Burger"
WORMWOOD.DESCRIBE.GORGE_FISHBURGER = "Burger"
WORMWOOD.DESCRIBE.GORGE_MUSHROOMBURGER = "Burger"
WORMWOOD.DESCRIBE.GORGE_FISH_STEAK = "Rybne"
WORMWOOD.DESCRIBE.GORGE_CURRY = "Ciepłe rzeczy do brzucha"
WORMWOOD.DESCRIBE.GORGE_SPAGHETTI = "Kule rzeczy do brzucha"
WORMWOOD.DESCRIBE.GORGE_POACHEDFISH = "Brzuchowa rzecz"
WORMWOOD.DESCRIBE.GORGE_SHEPHERD_PIE = "Brzuchowa rzecz"
WORMWOOD.DESCRIBE.GORGE_CANDY = "Lepkie Goo"
WORMWOOD.DESCRIBE.GORGE_BREAD_PUDDING = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_BERRY_TART = "Słodkie Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_MACARONI = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_BAGEL_AND_FISH = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_GRILLED_CHEESE = "Żółte Brzuchowe Coś"
WORMWOOD.DESCRIBE.GORGE_CREAMMUSHROOM = "Brzuchowe Coś"
WORMWOOD.DESCRIBE.GORGE_MANICOTTI = "Brzuchowe Coś"
WORMWOOD.DESCRIBE.GORGE_CHEESEBURGER = "Burger"
WORMWOOD.DESCRIBE.GORGE_FETTUCCINE = "Białe jedzenie dla brzucha."
WORMWOOD.DESCRIBE.GORGE_ONION_SOUP = "Śmierdzące jedzenie dla brzucha"
WORMWOOD.DESCRIBE.GORGE_BREADED_CUTLET = "Jedzenie dla brzucha"
WORMWOOD.DESCRIBE.GORGE_CREAMY_FISH = "Jedzenie dla brzucha"
WORMWOOD.DESCRIBE.GORGE_PIZZA = "Hmm..."
WORMWOOD.DESCRIBE.GORGE_POT_ROAST = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CRAB_CAKE = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_STEAK_FRITES = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_SHOOTER_SANDWICH = "Strzelać?"
WORMWOOD.DESCRIBE.GORGE_BACON_WRAPPED = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CRAB_ROLL = "Krab?"
WORMWOOD.DESCRIBE.GORGE_MEAT_WELLINGTON = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CRAB_RAVIOLI = "Krab?"
WORMWOOD.DESCRIBE.GORGE_CARAMEL_CUBE = "Słodkie!"
WORMWOOD.DESCRIBE.GORGE_SCONE = "Słodkie"
WORMWOOD.DESCRIBE.GORGE_TRIFLE = "Słodkie"
WORMWOOD.DESCRIBE.GORGE_CHEESECAKE = "Serowe Jedzenie w Brzuchu"

WORMWOOD.DESCRIBE.DUCKYOUGLERMZ = "Mniam!"

WORMWOOD.DESCRIBE.KYNO_ALOE = "Klejący przyjaciel"
WORMWOOD.DESCRIBE.KYNO_ALOE_COOKED = "Miękki"
WORMWOOD.DESCRIBE.KYNO_ALOE_GROUND = "Grudkowaty przyjaciel"
WORMWOOD.DESCRIBE.KYNO_ALOE_SEEDS = "Robi pomarańczowe brzuchowe rzeczy"
WORMWOOD.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "Robi pomarańczowe brzuchowe rzeczy"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_ALOE = "Zbrylony przyjaciel."
WORMWOOD.DESCRIBE.KYNO_ALOE_OVERSIZED = "Zbrylony przyjaciel."
WORMWOOD.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "Nieee!"

WORMWOOD.DESCRIBE.KYNO_CUCUMBER = "Jedzonko?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_COOKED = "Mmmm... Śliskie!"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_GROUND = "Brzuchowe jedzonko?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_SEEDS = "Robi pomarańczowe brzuchowe jedzonko."
WORMWOOD.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "Robi pomarańczowe brzuchowe jedzonko."
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "Brzuchowe jedzonko?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "Brzuchowe jedzonko?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "Nieeee!"

WORMWOOD.DESCRIBE.KYNO_RADISH = "Czerwone kulki dla brzuszka"
WORMWOOD.DESCRIBE.KYNO_RADISH_COOKED = "Gdzie zielona część?"
WORMWOOD.DESCRIBE.KYNO_RADISH_GROUND = "Czerwone kulki do brzuszka."
WORMWOOD.DESCRIBE.KYNO_RADISH_SEEDS = "Robią pomarańczowe jedzonko."
WORMWOOD.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "Robią pomarańczowe jedzonko."
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_RADISH = "Czerwone kulki do brzuszka."
WORMWOOD.DESCRIBE.KYNO_RADISH_OVERSIZED = "Duże czerwone kulki do brzuszka."
WORMWOOD.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "Nieee!"

WORMWOOD.DESCRIBE.KYNO_FENNEL = "Cześć!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_COOKED = "Mniam, mniam."
WORMWOOD.DESCRIBE.KYNO_FENNEL_GROUND = "Cześć!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_SEEDS = "Robi pomarańczowe brzuszkowe rzeczy."
WORMWOOD.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "Robi pomarańczowe brzuszkowe rzeczy."
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "Cześć!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_OVERSIZED = "Cześć!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "Nieee!"

WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO = "Słodka rzecz w brzuszku"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "Mmmm..."
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "Słodkie brzuchowe jedzonko"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "Z nich będzie pomarańczowe brzuchowe jedzonko!"
WORMWOOD.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "Z nich będzie pomarańczowe brzuchowe jedzonko!"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "Słodkie brzuchowe jedzonko!"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "Słodkie brzuchowe jedzonko!"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "Nieee!"

WORMWOOD.DESCRIBE.KYNO_PARZNIP = "Dzięki, ziemio!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_COOKED = "Dzięki, ziemio!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_EATEN = "Dzięki, ziemio!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_GROUND = "Dzięki, ziemio!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_BIG = "Wee Woo!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_SEEDS = "Tworzy pomarańczową rzecz w brzuszku"
WORMWOOD.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "Tworzy pomarańczową rzecz w brzuszku"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "Dzięki, ziemio!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "Dzięki, ziemio!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "Nieee!"

WORMWOOD.DESCRIBE.KYNO_TURNIP = "Uroczy mały przyjaciel ziemi"
WORMWOOD.DESCRIBE.KYNO_TURNIP_COOKED = "Tworzy dobrą zawartość brzucha"
WORMWOOD.DESCRIBE.KYNO_TURNIP_GROUND = "Uroczy Mały Przyjaciel Z Brudku"
WORMWOOD.DESCRIBE.KYNO_TURNIP_SEEDS = "Tworzy pomarańczowe jedzenie."
WORMWOOD.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "Tworzy pomarańczowe jedzenie."
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "Uroczy ziemny przyjaciel."
WORMWOOD.DESCRIBE.KYNO_TURNIP_OVERSIZED = "Uroczy ziemny przyjaciel."
WORMWOOD.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "Nieee!"

WORMWOOD.DESCRIBE.KYNO_RICE = "Małe kiełki"
WORMWOOD.DESCRIBE.KYNO_RICE_COOKED = "Małe kiełki"
WORMWOOD.DESCRIBE.KYNO_RICE_SEEDS = "Robi pomarańczowe rzeczy do brzuszka."
WORMWOOD.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "Robi pomarańczowe rzeczy do brzuszka."
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_RICE = "Słodki mały przyjaciel ziemi."
WORMWOOD.DESCRIBE.KYNO_RICE_OVERSIZED = "Słodki mały przyjaciel ziemi."
WORMWOOD.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "Nieee!"

WORMWOOD.DESCRIBE.KYNO_SEEDS_KIT = "Przyjaciele w środku?"

WORMWOOD.DESCRIBE.KYNO_LIMPETROCK =
{
	GENERIC = "Skały, które rosną jedzenie",
	PICKED = "Ślimaki zniknęły",
	WITHERED = "Brak życia",
}

WORMWOOD.DESCRIBE.KYNO_LIMPETS = "Skałowe Glub Gluby"
WORMWOOD.DESCRIBE.KYNO_LIMPETS_COOKED = "Wchodzi do Brzucha"

WORMWOOD.DESCRIBE.KYNO_LOTUS_OCEAN =
{
	GENERIC = "Cześć!",
	PICKED = "Odpoczywa",
	BURNING = "Boli!",
}

WORMWOOD.DESCRIBE.KYNO_LOTUS_ROOT = "Potrzeba morza"
WORMWOOD.DESCRIBE.KYNO_LOTUS_FLOWER = "Brzuszkowe rzeczy!"
WORMWOOD.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "Dobre w brzuszku"

WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_OCEAN =
{
	GENERIC = "Mniam",
	PICKED = "Na razie zniknęło?",
	BURNING = "Boli bardzo!",
}

WORMWOOD.DESCRIBE.KYNO_SEAWEEDS = "Mniam"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_COOKED = "Piłka Morskiej Pyzy"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_DRIED = "Już nie ma morza w morskiej pyzie"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_ROOT = "Potrzebuje Morza"

WORMWOOD.DESCRIBE.KYNO_TAROROOT_OCEAN =
{
	GENERIC = "Cześć, przyjacielu!",
	PICKED = "Przyjaciel dobrze rośnie",
	BURNING = "Boli!!",
}

WORMWOOD.DESCRIBE.KYNO_TAROROOT_ROOT = "Potrzeba morza"
WORMWOOD.DESCRIBE.KYNO_TAROROOT = "Mmm... Purpurowe"
WORMWOOD.DESCRIBE.KYNO_TAROROOT_COOKED = "Brzuszek zadowolony"

WORMWOOD.DESCRIBE.KYNO_WATERYCRESS_OCEAN =
{
	GENERIC = "Cześć",
	PICKED = "Przyjaciel śpi",
	BURNING = "Ogień!!!",
}

WORMWOOD.DESCRIBE.KYNO_WATERYCRESS_ROOT = "Potrzeba morza"
WORMWOOD.DESCRIBE.KYNO_WATERYCRESS = "Jedzenie do brzuszka."

WORMWOOD.DESCRIBE.WATERYCRESSBOWL = "Woda ze sticków"

WORMWOOD.DESCRIBE.KYNO_SALT = "Hmm..."

WORMWOOD.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "Patyk z jedzeniem",
	PICKED = "Pusty",
	BURNING = "Boli patyk!",
}

WORMWOOD.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "Patyk pływa!"

WORMWOOD.DESCRIBE.CATFOOD = "Jedzenie dla kotów."

WORMWOOD.DESCRIBE.KATFOOD = "Jedzenie dla kotów."

WORMWOOD.DESCRIBE.KYNO_BANANATREE =
{
	GENERIC = "Przyjaciel ze słodkimi włosami",
	PICKED = "Potrzebuje odpoczynku",
	CHOPPED = "Przyjaciel zniknął",
	BURNING = "Przyjaciel cierpi!",
	BURNT = "Zniknął na zawsze",
}

WORMWOOD.DESCRIBE.KYNO_BANANA = "Słodkie włosy od przyjaciela!"
WORMWOOD.DESCRIBE.KYNO_BANANA_COOKED = "Mmm..."

WORMWOOD.DESCRIBE.KYNO_KOKONUTTREE =
{
	GENERIC = "Ładne włosy!",
	PICKED = "Przyjaciel potrzebuje odpoczynku",
	CHOPPED = "Och nie",
	BURNING = "Przyjaciel cierpi",
	BURNT = "Przyjaciel zniknął",
}

WORMWOOD.DESCRIBE.KYNO_KOKONUT = "Piłka pełna rzeczy do jedzenia"
WORMWOOD.DESCRIBE.KYNO_KOKONUT_HALVED = "Rzeczy do brzucha"
WORMWOOD.DESCRIBE.KYNO_KOKONUT_COOKED = "Ciepłe."

WORMWOOD.DESCRIBE.BOWLOFPOPCORN = "Pop! Pop!"

WORMWOOD.DESCRIBE.FIGJUICE = "Zimna, rześka woda."

WORMWOOD.DESCRIBE.COCONUTWATER = "Słodka woda."

WORMWOOD.DESCRIBE.EYEBALLSPAGHETTI = "Małe Oczko Jedzenie"

WORMWOOD.DESCRIBE.FORGETMELOTS_SEEDS = "Robi pomarańczowe rzeczy w brzuszku."

WORMWOOD.DESCRIBE.FIRENETTLES_SEEDS = "Robi pomarańczowe rzeczy w brzuszku."

WORMWOOD.DESCRIBE.TILLWEED_SEEDS = "Robi pomarańczowe rzeczy w brzuszku."

WORMWOOD.DESCRIBE.KYNO_FLOATILIZER = "Łajno! Hurra!"

WORMWOOD.DESCRIBE.KYNO_TWIGGYNUTS = "Hmmm..."

WORMWOOD.DESCRIBE.KYNO_REPAIRTOOL = "Naprawiaj rzeczy."

WORMWOOD.DESCRIBE.KYNO_KOI = "Ładny Glub Glub"
WORMWOOD.DESCRIBE.KYNO_KOI_COOKED = "Ładny Glub Glub"

WORMWOOD.DESCRIBE.KYNO_TROPICALFISH = "Ładny Glub Glub"
WORMWOOD.DESCRIBE.KYNO_TROPICALFISH_COOKED = "Glub?"

WORMWOOD.DESCRIBE.KYNO_NEONFISH = "Glub Glub z dużymi ustami."
WORMWOOD.DESCRIBE.KYNO_NEONFISH_COOKED = "Płetwy są pyszne."

WORMWOOD.DESCRIBE.KYNO_GROUPER = "Fioletowy Glub Glub"
WORMWOOD.DESCRIBE.KYNO_GROUPER_COOKED = "Nie ma już pływania"
 
WORMWOOD.DESCRIBE.KYNO_PIERROTFISH = "Glub Glub"
WORMWOOD.DESCRIBE.KYNO_PIERROTFISH_COOKED = "Glub Glub dla brzuszka"

WORMWOOD.DESCRIBE.KYNO_SALMONFISH = "Glub Glub z ziemi"
WORMWOOD.DESCRIBE.KYNO_SALMONFISH_COOKED = "Glub Glub do brzuszka"

WORMWOOD.DESCRIBE.TURF_PINKPARK = "Różowy"
WORMWOOD.DESCRIBE.TURF_STONECITY = "Nie Ziemia"
WORMWOOD.DESCRIBE.TURF_FIELDS = "Ziemia"
WORMWOOD.DESCRIBE.TURF_TIDALMARSH = "Mokry Piasek"

WORMWOOD.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "Gotowe!",
	PICKED = "Zbieram pyszne kamienie",
}

WORMWOOD.DESCRIBE.KYNO_SALTRACK_INSTALLER = "Zbiera Smaczne Kamyki"

WORMWOOD.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "Złośliwa Metalowa Rzecz"

WORMWOOD.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "Ziemny więzień szczypczyków"

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_SHOP =
{
	GENERIC = "Owinięte ramię, kręcący się ogon",
	SLEEPING = "Śpi",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "Słodki przyjaciel!",
	CHOPPED = "Przepraszam!",
	SAPPED = "Pełne wnętrzności przyjaciela",
	PICKED = "Och, przyjacielu. Przepraszam",
	BURNING = "Boli bardzo!",
	BURNT = "Zniknęło...",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "AUĆ! Przyjaciel cierpi",
	CHOPPED = "Zniknęło",
	SAPPED = "Zły sok",
	PICKED = "Robaki zraniły przyjaciela!",
	BURNING = "Boli",
	BURNT = "Zniknęło na zawsze",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_BUD = "Chcesz to w brzuchu? Czy w ziemi?"

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_FLOWER = "Przyjaciel!"
WORMWOOD.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "Przyjaciel!"

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_PETALS = "Przyjaciel!"

WORMWOOD.DESCRIBE.KYNO_PEBBLECRAB = "Ziemny szczypczyk!"

WORMWOOD.DESCRIBE.KYNO_CRABMEAT = "Gałązka Z Ziemnego Szczypczyka"
WORMWOOD.DESCRIBE.KYNO_CRABMEAT_COOKED = "Pinchy Robi Dobre Jedzenie"
WORMWOOD.DESCRIBE.KYNO_CRABMEAT_DRIED = "Gałązka z Ziemi Pinchy'ego"

WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT = "Gałązka z Ziemi Pinchy'ego"
WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "Gałąź spod ziemi, szczypiorek."
WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "Gałąź spod ziemi, szczypiorek."

WORMWOOD.DESCRIBE.KYNO_SLAUGHTERTOOL = "Złe rzeczy"

WORMWOOD.DESCRIBE.KYNO_CHICKEN2 =
{
	GENERIC = "Ba-gawk!",
	COOP = "Ba-gawk teraz bezpieczny",
}

WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG = "Mały Klik Klik"
WORMWOOD.DESCRIBE.KYNO_CHICKEN_LARGE = "Wielkie kliknięcie, kliknięcie w środku?"
WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "Wchodzi do brzuszka"

WORMWOOD.DESCRIBE.KYNO_CHICKENHOUSE =
{
	GENERIC = "Dom Ba-gawk",
	FULL = "Jajka gotowe!",
	BURNT = "Ba-gawk zniknął?",
}

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "Zepsute."

WORMWOOD.DESCRIBE.KYNO_COOKWARE_KIT = "Drewniane pudełko."
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SYRUP = "Robi słodką breję"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "Robi słodką breję"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_BIG_POT = "Hoo! Robi bąbelki w wodzie!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_BIG = "Hoo! Robi bąbelki w wodzie!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "Hoo! Robi bąbelki w wodzie!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL = "Hoo! Robi bąbelki w wodzie!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_GRILL = "Gorące paski!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "Potrzebuje ognia"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "Maleńkie Gorące Pręty"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "Potrzebuje ognia"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_ELDER = "Robi słodkie bąbelki."
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "Robi Gorące Brzuszkowe"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "Robi Brzuszkowe Piękności"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "Tu wkładać Brzuszkowe Rzeczy"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN = "Daje Jedzonku Ognistą Kąpiel"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "Daje Jedzonku Ognistą Kąpiel"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "Daje Jedzonku Ognistą Kąpiel"

WORMWOOD.DESCRIBE.KYNO_ROCKFLIPPABLE =
{
	GENERIC = "Coś się chowa?",
	FLIPPED = "Znalazłem rzeczy",
}

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "Drewniane tonące!"

WORMWOOD.DESCRIBE.KYNO_SUGARFLY = "Przyjaciel dla przyjaciół."
WORMWOOD.DESCRIBE.KYNO_SUGARFLYWINGS = "Nie do latania."

WORMWOOD.DESCRIBE.KYNO_WATERY_CRATE = "Drewniane Tonące!"

WORMWOOD.DESCRIBE.KYNO_TUNACAN = "Glub Glub w środku?"
WORMWOOD.DESCRIBE.KYNO_TUNACAN_OPEN = "Glub Glub Martwa"

WORMWOOD.DESCRIBE.KYNO_CANNEDFOOD = "Coś w brzuszku?"
WORMWOOD.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "Mniam"

WORMWOOD.DESCRIBE.KYNO_POP = "Psht"

WORMWOOD.DESCRIBE.KYNO_MYSTERYMEAT = "Hmm... Co to?"

WORMWOOD.DESCRIBE.KYNO_BOTTLE_SOUL = "Hmm..."

WORMWOOD.DESCRIBE.SOULSTEW = "Hmm..."

WORMWOOD.DESCRIBE.FORTUNECOOKIE = "Dziwne jedzenie"

WORMWOOD.DESCRIBE.HORNOCUPIA = "Brzuchowe rzeczy"

WORMWOOD.DESCRIBE.CHEESE_YELLOW = "Śmierdzące brzuchowe rzeczy"
WORMWOOD.DESCRIBE.CHEESE_WHITE = "Śmierdzące brzuchowe rzeczy"
WORMWOOD.DESCRIBE.CHEESE_KOALEFANT = "Śmierdzące brzuchowe rzeczy"

WORMWOOD.DESCRIBE.MILK_BOX = "Brzuchowe rzeczy?"

WORMWOOD.DESCRIBE.WATERCUP = "Woda"

WORMWOOD.DESCRIBE.HONEYJAR = "Słodkie brzuszkowe rzeczy"

WORMWOOD.DESCRIBE.CRAB_ARTICHOKE = "Zniknęły małe skały?"

WORMWOOD.DESCRIBE.PEPPERROLLS = "Pyszne kawałki"

WORMWOOD.DESCRIBE.KYNO_SAPHEALER = "Naprawiacz chorób"

WORMWOOD.DESCRIBE.KYNO_OCEAN_WRECK =
{
	GENERIC = "Ratuj drewno!",
	PICKED = "Czekam",
	BURNING = "Boli",
}

WORMWOOD.DESCRIBE.KYNO_GHOST_PIRATE = "Latający Człowiek"

WORMWOOD.DESCRIBE.KYNO_BUCKET_EMPTY = "Drewniana rzecz"
WORMWOOD.DESCRIBE.KYNO_BUCKET_METAL = "Metalowa Rzecz"
WORMWOOD.DESCRIBE.KYNO_BUCKET_WATER = "Woda dla Przyjaciół"

WORMWOOD.DESCRIBE.KYNO_MILK_BEEFALO = "Moo Moo?"
WORMWOOD.DESCRIBE.KYNO_MILK_KOALEFANT = "Moo Moo?"

WORMWOOD.DESCRIBE.KYNO_CAP_DRIED = "Rzecz do brzuszka"

WORMWOOD.DESCRIBE.KYNO_PLANTMEAT_DRIED = "Wysuszone rzeczy do brzuszka"

WORMWOOD.DESCRIBE.KYNO_BREWBOOK = "Rzeczy do brzuszka"

WORMWOOD.DESCRIBE.KYNO_WOODENKEG =
{
	EMPTY = "Drewniane pudełko?",
	BREWING_LONG = "Pracuje",
	BREWING_SHORT = "Prawie gotowe?",
	DONE = "Gotowe!",
	BURNT = "Zniknęło",
}

WORMWOOD.DESCRIBE.KYNO_PRESERVESJAR =
{
	EMPTY = "Drewniane pudełko?",
	BREWING_LONG = "Pracuje",
	BREWING_SHORT = "Prawie gotowe?",
	DONE = "Gotowe!",
	BURNT = "Zniknęło",
}

WORMWOOD.DESCRIBE.KYNO_ANTCHEST =
{
	GENERIC = "Sok od bzyczenia! Gdzie jest Bzyczenie?",
	HONEY = "Słodkości!",
	NECTAR = "Nie gotowe",
	BURNING = "Boli!",
}

WORMWOOD.DESCRIBE.KYNO_NECTAR_POD = "Słodkie!"

WORMWOOD.DESCRIBE.KYNO_OAKTREE_POD = "Witaj"
WORMWOOD.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "Nie dla Ziemi teraz."

WORMWOOD.DESCRIBE.KYNO_PIKO = "Puchaty Rabuszek"
WORMWOOD.DESCRIBE.KYNO_PIKO_ORANGE = "Puchaty Rabuszek"

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_TREE =
{
	GENERIC = "Śpi?",
	CHOPPED = "Przyjaciel dał kawałki włosów",
	BURNING = "Boli!",
	BURNT = "Zniknęło",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE =
{
	GENERIC = "Śpi z przyjaciółmi?",
	BURNING = "Boli!",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "Drewniani przyjaciele zrobili pudełko!"

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT =
{
	GENERIC = "Dom Glub Glub Człowieka",
	BURNT = "Dom Glub Glub Człowieka zniknął",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT =
{
	GENERIC = "Dom Glub Glub Człowieka",
	CRAFTED = "Lepszy dom",
	BURNT = "Śmierdzi źle",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SHOP =
{
	GENERIC = "W środku dużo rzeczy",
	OCCUPIED = "Śpi?",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMCART =
{
	GENERIC = "Rzeczy",
	EMPTY = "Nic",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "Cześć!"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_POND = "Dom dla Glub Glub"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "Cześć, mały!"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "Kupa ziemi."
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "Glub Glub Człowiek"

WORMWOOD.DESCRIBE.KYNO_SAMMYHAT = "Zakurzona"

WORMWOOD.DESCRIBE.KINGFISHER = "Dziobiasty ćwierkacz."

WORMWOOD.DESCRIBE.TOUCAN = "Duży nosowy ćwierkacz."
WORMWOOD.DESCRIBE.TOUCAN_CHUBBY = "Wielkonosy Ćwierkacz"

WORMWOOD.DESCRIBE.WETGOOP2 = "Pyszne"

WORMWOOD.DESCRIBE.BEER = "Śmieszny smak"

WORMWOOD.DESCRIBE.PALEALE = "Śmieszny smak"

WORMWOOD.DESCRIBE.TEAGREEN = "Mmmm... Ahh"

WORMWOOD.DESCRIBE.TEARED = "Mmmm... Ahh"

WORMWOOD.DESCRIBE.MEAD = "Słodkie brzuchate jedzenie"

WORMWOOD.DESCRIBE.KYNO_JELLY = "Słodkie Brzuszkowe Jedzenie"

WORMWOOD.DESCRIBE.KYNO_MAYONNAISE = "Mmm..."

WORMWOOD.DESCRIBE.TARTARSAUCE = "Pikantne Brzuszkowe Rzeczy"

WORMWOOD.DESCRIBE.KYNO_PICKLES = "Brzuszkowe Rzeczy"

WORMWOOD.DESCRIBE.KYNO_WINE = "Gorzka woda"

WORMWOOD.DESCRIBE.KYNO_JUICE = "Słodka rzecz do brzuszka."

WORMWOOD.DESCRIBE.KYNO_POISON_FROGLEGS = "Nogaty"
WORMWOOD.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "(wącha, wącha) Pachnie w porządku"

WORMWOOD.DESCRIBE.POISONFROGGLEBUNWICH = "Napełnia Brzuch"

WORMWOOD.DESCRIBE.KYNO_BREWINGRECIPECARD = "Hmm. Bezużyteczne."

WORMWOOD.DESCRIBE.KYNO_OIL = "Rzeczy do brzucha?"

WORMWOOD.DESCRIBE.BERRYSUNDAE = "Chłodne"

WORMWOOD.DESCRIBE.CHOCOLATE_BLACK = "Słodkie!"
WORMWOOD.DESCRIBE.CHOCOLATE_WHITE = "Słodkie!"

WORMWOOD.DESCRIBE.TRICOLORDANGO = "Słodkie"
 
WORMWOOD.DESCRIBE.FRIESFRENCH = "Chrupiące"

WORMWOOD.DESCRIBE.PIRATERUM = "Zło?"

WORMWOOD.DESCRIBE.TWISTEDTEQUILA = "Brzuchowe rzeczy?"

WORMWOOD.DESCRIBE.ONIONRINGS = "Chrupiąca Cebulka"

WORMWOOD.DESCRIBE.DONUTS = "Słodkie Brzuchowe Rzeczy"
WORMWOOD.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "Słodka Jedzonka"
WORMWOOD.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "Słodka Jedzonka"
 
WORMWOOD.DESCRIBE.CINNAMONROLL = "Jedzonka Brzuszkowa"

WORMWOOD.DESCRIBE.GUMMYBEARGERS = "Dziwne"

WORMWOOD.DESCRIBE.PRETZEL = "Jedzonka Brzuszkowa"

WORMWOOD.DESCRIBE.CORNINCUP = "Dobre dla brzuszka."

WORMWOOD.DESCRIBE.COTTONCANDY = "Powietrze?"

WORMWOOD.DESCRIBE.ROASTEDHAZELNUTS = "Orzechy!"

WORMWOOD.DESCRIBE.MONSTERMUFFIN = "Dziwne rzeczy do brzuszka."

WORMWOOD.DESCRIBE.PINKCAKE = "Słodkie, brzuszkowe rzeczy"

WORMWOOD.DESCRIBE.CHIPSBAG = "Brzuszkowe rzeczy."

WORMWOOD.DESCRIBE.LITTLEBREAD = "Puszyste."

WORMWOOD.DESCRIBE.HOTHOUND = "Gdzie pies?"

WORMWOOD.DESCRIBE.MILKSHAKE = "Wstrząśnij!"
WORMWOOD.DESCRIBE.MILKSHAKE_PRISMATIC = "Wstrząśnij!"

WORMWOOD.DESCRIBE.NACHOS = "Serowy"

WORMWOOD.DESCRIBE.BANANA_PUDDING = "Banany"

WORMWOOD.DESCRIBE.SEA_PUDDING = "Rybki?"

WORMWOOD.DESCRIBE.TOM_KHA_SOUP = "Warzywa"

WORMWOOD.DESCRIBE.MINERTREAT = "Dziwne"

WORMWOOD.DESCRIBE.RADISHSALAD = "Chcę to zjeść"

WORMWOOD.DESCRIBE.PUMPKIN_SOUP = "Pływające w brzuszku rzeczy"

WORMWOOD.DESCRIBE.ALGAE_SOUP = "Pływające w brzuszku rzeczy"

WORMWOOD.DESCRIBE.PARZNIP_SOUP = "Pływające w brzuszku rzeczy"

WORMWOOD.DESCRIBE.NETTLEMEATED = "Mmmm..."

WORMWOOD.DESCRIBE.KYNO_SUGAR = "Słodki proszek"

WORMWOOD.DESCRIBE.KYNO_BOTTLECAP = "Zakrętka"

WORMWOOD.DESCRIBE.NUKACOLA = "Puszyste"
WORMWOOD.DESCRIBE.NUKACOLA_QUANTUM = "Puszyste"

WORMWOOD.DESCRIBE.LIVINGSANDWICH = "Dziwna Bułka"

WORMWOOD.DESCRIBE.DURIANSPLIT = "Zimne"

WORMWOOD.DESCRIBE.DURIANSOUP = "Śliskowa woda"

WORMWOOD.DESCRIBE.DURIANMEATED = "Śmierdząca Trzewiowa Zupa"

WORMWOOD.DESCRIBE.DURIANCHICKEN = "Zjedzenie Trzewi"

WORMWOOD.DESCRIBE.LUNARSOUP = "Księżyc!"

WORMWOOD.DESCRIBE.PURPLEWOBSTERSOUP = "Biedny Wobster"

WORMWOOD.DESCRIBE.WOBSTERMONSTER = "Potwór"

WORMWOOD.DESCRIBE.SPIDERCAKE = "Ciasto z Pająkami"

WORMWOOD.DESCRIBE.SUGARBOMBS = "Kaboom"

WORMWOOD.DESCRIBE.BERRYBOMBS = "Słodkie jedzonko"

WORMWOOD.DESCRIBE.ONIGIRIS = "Ziarna"

WORMWOOD.DESCRIBE.OMURICE = "Smażone ziarna"

WORMWOOD.DESCRIBE.PAELLA = "Ziarna!"

WORMWOOD.DESCRIBE.RISOTTO = "Ziarna i Przyjaciele"

WORMWOOD.DESCRIBE.RICESAKE = "Wodny zbożek?"

WORMWOOD.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "Przyjaciel potrzebuje ziemi"

WORMWOOD.DESCRIBE.KYNO_PINEAPPLEBUSH =
{
	GENERIC = "Cześć, przyjacielu!",
	PICKED = "Gdzie podziały się kolce przyjaciela?",
	WITHERED = "Zbyt suche",
	BURNING = "Przyjaciel cierpi!",
}

WORMWOOD.DESCRIBE.KYNO_PINEAPPLE = "Kłuje."
WORMWOOD.DESCRIBE.KYNO_PINEAPPLE_HALVED = "Brzuchociesz."
WORMWOOD.DESCRIBE.KYNO_PINEAPPLE_COOKED = "Brzuszkowe jedzonko."

WORMWOOD.DESCRIBE.PIZZA_TROPICAL = "Przyjaciel?"

WORMWOOD.DESCRIBE.PINACOLADA = "Przyjaciel?"

WORMWOOD.DESCRIBE.CHIMAS = "Trawa?"

WORMWOOD.DESCRIBE.KYNO_GARDEN_SPRINKLER =
{
	OFF = "Pomaga przyjaciołom",
	ON = "Przyjaciele szczęśliwi dzięki chlapiącej metalowej rzeczy",
}

WORMWOOD.DESCRIBE.KYNO_FOODSACK = "Trzyma Jedzonko Świeże"

WORMWOOD.DESCRIBE.GUMMYWORMS = "Robaki?"

WORMWOOD.DESCRIBE.SMORES = "Czekolada?"

WORMWOOD.DESCRIBE.NUKASHINE = "Dziwny napój"

WORMWOOD.DESCRIBE.ANTSLOG = "Woody"

WORMWOOD.DESCRIBE.KYNO_WORM_BONE = "Oh"

WORMWOOD.DESCRIBE.SPOOKY_BRAIN_NOODLES = "Mózg?"
WORMWOOD.DESCRIBE.SPOOKY_BURGERZILLA = "Potwór!"
WORMWOOD.DESCRIBE.SPOOKY_DEADBREAD = "Puszyste"
WORMWOOD.DESCRIBE.SPOOKY_JELLYBEANS = "Przerażające"
WORMWOOD.DESCRIBE.SPOOKY_POPSICLE = "Smaczne"
WORMWOOD.DESCRIBE.SPOOKY_PUMPKINCREAM = "Pachnący przyjaciel?"
WORMWOOD.DESCRIBE.SPOOKY_SKULLCANDY = "Straszne"
WORMWOOD.DESCRIBE.SPOOKY_TACODILE = "Przyjaciel?"

WORMWOOD.DESCRIBE.BUTTER_BEEFALO = "Śliskie"
WORMWOOD.DESCRIBE.BUTTER_GOAT = "Śliskie?"
WORMWOOD.DESCRIBE.BUTTER_KOALEFANT = "Śliskie!"

WORMWOOD.DESCRIBE.SPICE_CURE = "Chroni jedzenie"
WORMWOOD.DESCRIBE.SPICE_COLD = "Zimno!"
WORMWOOD.DESCRIBE.SPICE_FIRE = "Palić!"
WORMWOOD.DESCRIBE.SPICE_FED = "Głodny"
WORMWOOD.DESCRIBE.SPICE_MIND = "Śpiący"

WORMWOOD.DESCRIBE.SUGARFLYMUFFIN = "Mniam..."

WORMWOOD.DESCRIBE.EELTACOS = "Dla Brzucha"

WORMWOOD.DESCRIBE.MEATSKILLET = "Dla Brzucha!"

WORMWOOD.DESCRIBE.MEATWALTZ = "Dla Brzucha?"

WORMWOOD.DESCRIBE.COMPLETEBREAKFAST = "Dużo jedzenia dla brzucha"

WORMWOOD.DESCRIBE.DUMPLINGS = "Jedzenie dla brzucha"

WORMWOOD.DESCRIBE.WARLYICEDTEA = "Zimna, energiczna woda"

WORMWOOD.DESCRIBE.WARLYTEA = "Ciepła, energetyczna woda"

WORMWOOD.DESCRIBE.KYNO_TEALEAF = "Przytulny przyjaciel"

WORMWOOD.DESCRIBE.KYNO_ITEMSLICER = "Tasak. Do strzyżenia przyjaciela."
WORMWOOD.DESCRIBE.KYNO_ITEMSLICER_GOLD = "Tasak. Do strzyżenia przyjaciela."

WORMWOOD.DESCRIBE.COXINHA = "Pełny Brzuch"

WORMWOOD.DESCRIBE.LAZYDESSERT = "Kamienny"

WORMWOOD.DESCRIBE.CRABKINGFEAST = "Gigantyczne!"

WORMWOOD.DESCRIBE.PIENAPPLE = "Przyjaciel ma kolczaste włosy!"

WORMWOOD.DESCRIBE.JAWSBREAKER = "Twarde"

WORMWOOD.DESCRIBE.AVOCADOTOAST = "Smaczne"

WORMWOOD.DESCRIBE.RICEPUDDING = "Mieszanka"

WORMWOOD.DESCRIBE.SHARKSUSHI = "Belly Stuff"

WORMWOOD.DESCRIBE.WOBSTERBREADED = "Chrupiący smażony Glub Glub"

WORMWOOD.DESCRIBE.LAZYPURRITO = "Głupi kot"

WORMWOOD.DESCRIBE.HORCHATA = "Zimne!"

WORMWOOD.DESCRIBE.WOBSTERCOCKTAIL = "Płonący Glub Glub"

WORMWOOD.DESCRIBE.LAVAEEGGBOILED = "Gorące!"

WORMWOOD.DESCRIBE.POMEGRANATETEA = "Zimna Żwawa Woda"

WORMWOOD.DESCRIBE.TIRAMISU = "Honk! Honk!"

WORMWOOD.DESCRIBE.TOADSTOOLCOLA = "Śmierdzący Psht"

WORMWOOD.DESCRIBE.TEPACHE = "Słodki Sok Przyjaciela"

WORMWOOD.DESCRIBE.LUNARTEQUILA = "Księżycowe rzeczy?"

WORMWOOD.DESCRIBE.MIMICMOSA = "Ciemny Sok Przyjaciela"

WORMWOOD.DESCRIBE.POMEGRANATEPIE = "Czerwony Belly Stuff"

WORMWOOD.DESCRIBE.PINEAPPLECAKE = "Belly Stuff"

WORMWOOD.DESCRIBE.PASTY_MEAT = "Chrupiące"
WORMWOOD.DESCRIBE.PASTY_CHEESE = "Chrupiące"

WORMWOOD.DESCRIBE.BRIGADEIRO = "Wiórki"

WORMWOOD.DESCRIBE.REGULARLASAGNA = "Dla Brzuszka"

WORMWOOD.DESCRIBE.FLTSANDWICH = "Żabcia"

WORMWOOD.DESCRIBE.RICEANDBEANS = "Coś do Brzuszka"

WORMWOOD.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "Stary dom... może wkrótce nowe życie..."

WORMWOOD.DESCRIBE.KYNO_TRUFFLES_GROUND =
{
	GENERIC = "Przyjaciel rośnie w ziemi!",
	PICKED = "Zniknęło",
	BURNING = "Przyjaciel cierpi!",
}

WORMWOOD.DESCRIBE.KYNO_TRUFFLES = "Pachnący przyjaciel pokarm."
WORMWOOD.DESCRIBE.KYNO_TRUFFLES_COOKED = "Ciepłe jedzenie przyjaciela!"

WORMWOOD.DESCRIBE.KYNO_ITEMSHOWCASER =
{
	EMPTY = "Pokaż jedzenie przyjaciołom",
	FULL = "Jedzenie wygląda ładnie",
}

WORMWOOD.DESCRIBE.KYNO_SPORECAP = "Przyjaciel... chory..."
WORMWOOD.DESCRIBE.KYNO_SPORECAP_COOKED = "Ciepły przyjaciel! Lepszy?"

WORMWOOD.DESCRIBE.KYNO_SPORECAP_DARK = "Przyjaciel boli przyjaciela..."
WORMWOOD.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "Wciąż rani przyjaciela..."

WORMWOOD.DESCRIBE.KYNO_GOLDENAPPLE = "Świeci! Jabłko przyjaciel!"

WORMWOOD.DESCRIBE.TRUFFLESGRINDER = "Mniam! Ziemna kanapka!"

WORMWOOD.DESCRIBE.SPORECAPPIE = "Miękkie Ciasto"

WORMWOOD.DESCRIBE.SPORECAP_SKEWERS = "Przyjaciele... smaczne teraz!"

WORMWOOD.DESCRIBE.TRUFFLEOIL = "Silny zapach."

WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "Plany Jeziora"
WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "Rosnący Wodny Domek!"

WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT =
{
	GENERIC = "Dom Glub Glub",
	FUEL_HIGH = "Glub Glub szczęśliwy!",
	FUEL_MED = "Glub Glub je",
	FUEL_LOW = "Potrzebuje przekąsek wkrótce",
	EMPTY = "Brak przekąsek",
}

WORMWOOD.DESCRIBE.KYNO_ANTCHOVY = "Przyjaciel rybo-owad! Cześć!"
WORMWOOD.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "Wielu przyjaciół rybo-owadów!"

WORMWOOD.DESCRIBE.AGEDROE = "Małe Glub Gluby uwięzione?"
WORMWOOD.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "Glub Glub Dzieci"

WORMWOOD.DESCRIBE.KYNO_SWORDFISH_BLUE = "Nie Pływa Dobrze?"

WORMWOOD.DESCRIBE.KYNO_JELLYFISH = "Glub Glub Klocek"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_DEAD = "Biedny Klocek"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_COOKED = "Ciepła Klocek"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_DRIED = "Twardy Klocek"

WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "Ładna Glub Glub Galaretka"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "Bez Poof"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "Ładne Kółka"

WORMWOOD.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "Aw. Nic w środku."

WORMWOOD.DESCRIBE.KYNO_OCEANTRAP = "Mokra Pułapka"

WORMWOOD.DESCRIBE.OCEANFISH_PUFFERFISH = "Kłujący Glub Glub"
WORMWOOD.DESCRIBE.OCEANFISH_STURGEON = "Stary Glub Glub"

WORMWOOD.DESCRIBE.KYNO_SWORDFISH = "Ostry Nos Glub Glub"
WORMWOOD.DESCRIBE.KYNO_SWORDFISH_DEAD = "(płacz)"

WORMWOOD.DESCRIBE.SWORDFISHFEAST = "Szykowny Glub Glub"

WORMWOOD.DESCRIBE.KYNO_DOGFISH = "Glub Glub Hau Hau"
WORMWOOD.DESCRIBE.KYNO_DOGFISH_DEAD = "Cześć, Glub Glub"

WORMWOOD.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "Dobrze pachnie. Mmmmm."

WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND = "Błyszczący wodny przyjaciel!"
WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "Koniec błyszczących ruchów..."
WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "Przyjaciel?"

WORMWOOD.DESCRIBE.KYNO_PUFFERMONSTER = "Kolczasta rybka! Nie kłuj, przyjacielu!"

WORMWOOD.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "Glub Glub czy Barrooooo?"
WORMWOOD.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "Barrooooo!"
WORMWOOD.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "Pale Barrooooo"
WORMWOOD.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "Ogromny!"

WORMWOOD.DESCRIBE.KYNO_BLUBBER = "Miękki"

WORMWOOD.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "Suchy Glub Glub, Mmm!"
WORMWOOD.DESCRIBE.KYNO_FISHMEAT_DRIED = "Suchy Glub Glub"

WORMWOOD.DESCRIBE.MONKEYISLANDMEAL = "Glub Glub i Przyjaciel"

WORMWOOD.DESCRIBE.KYNO_BRAINROCK_LARVAE = "Potrzebuje kamienia"
WORMWOOD.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "Słodki mokry kamień-bobasek"
WORMWOOD.DESCRIBE.KYNO_BRAINROCK_CORAL = "Myślę..."

WORMWOOD.DESCRIBE.KYNO_BRAINROCK_ROCK =
{
	GENERIC = "Myśląca skała",
	PICKED = "Myśląca skała zmęczona",
}

WORMWOOD.DESCRIBE.BRAINMETTERSOUP = "Przemyślany brzuszek"

WORMWOOD.DESCRIBE.KYNO_OCTOPUSKING_OCEAN =
{
	GENERIC = "Duży gość z ramionami",
	SLEEPING = "Śpi",
}

WORMWOOD.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "Rzeczy od Faceta z Dużymi Ramionami!"

WORMWOOD.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE =
{
	GENERIC = "Przyjaciel Tweeter cię lubi!",
	WAITING = "Gdzie podział się Tweeter?",
}

WORMWOOD.DESCRIBE.KYNO_PACKIMBAGGIMS = "Przyjaciel Tweet"

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "Brak Rzeczy"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "Potrzeba Więcej Rzeczy"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "Duży! Biiig!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "Światło dla Wielkiego Tortu!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "Przyjaciele..."
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "Słodkie Brzusio Jedzonko!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "Latający przyjaciele! Cześć!"

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE =
{
	GENERIC = "Maszynka do popcornu",
	FUEL_HIGH = "Maszynka do popcornu szczęśliwa",
	FUEL_MED = "Działa",
	FUEL_LOW = "Maszynka wygląda na głodną",
	EMPTY = "Pusta",
}

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "Pop pop!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "Imprezowy Kapelusz! Jupi!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "Kapelusz Przyjaciela!"

WORMWOOD.DESCRIBE.KYNO_FISHREGISTRYHAT = "Kapelusz Znający Ryby"

WORMWOOD.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "Miejsce na jedzenie",
	FUEL_HIGH = "Dużo jedzenia",
	FUEL_MED = "Trochę jedzenia",
	FUEL_LOW = "Mało jedzenia",
	EMPTY = "Brak jedzenia",
	BURNT = "Zniknęło",
}

WORMWOOD.DESCRIBE.CHICKENNUGGETS = "Ba-gawk kawałki"

WORMWOOD.DESCRIBE.CHICKENWINGS = "Boli brzuch"

WORMWOOD.DESCRIBE.CHICKENBURGER = "Kurczak przytula chleb."

WORMWOOD.DESCRIBE.CHICKENEGGSOUP = "Ciepła woda z jajka."

WORMWOOD.DESCRIBE.CHICKENEGGSTEW = "Kąpiel jajka i ptaka."

WORMWOOD.DESCRIBE.CHICKENROTISSERIE = "Gorący, kręcący się ptak."