local WX78 = STRINGS.CHARACTERS.WX78

WX78.ANNOUNCE_KYNO_COFFEEBUFF_START = "PRĘDKOŚĆ RUCHU: MAKSYMALNA"
WX78.ANNOUNCE_KYNO_COFFEEBUFF_END = "PRĘDKOŚĆ RUCHU: ZNORMALIZOWANA"

WX78.ANNOUNCE_KYNO_HASTEBUFF_START = "PRĘDKOŚĆ RUCHÓW DŁONI: MAKSYMALNA WYDAJNOŚĆ"
WX78.ANNOUNCE_KYNO_HASTEBUFF_END = "KLIK, PRĘDKOŚĆ RUCHU WRACA DO NORMALNYCH POZIOMÓW"

WX78.ANNOUNCE_KYNO_POPBUFF_START = "(BUUURP) CO TO DO...? "
WX78.ANNOUNCE_KYNO_POPBUFF_END = "EFEKTY MUSUJĄCE ZOSTAŁY USUNIĘTE"

WX78.ANNOUNCE_KYNO_FROGBUFF_START = "MECHANIZM ŻABY: AKTYWOWANY"
WX78.ANNOUNCE_KYNO_FROGBUFF_END = "MECHANIZM ŻABY: DEZAKTYWOWANY"

WX78.ANNOUNCE_KYNO_PIRATEBUFF_START = "(BUURP) GOTOWY NA REJS!"
WX78.ANNOUNCE_KYNO_PIRATEBUFF_END = "EFEKTY PIRACKIE USUNIĘTE"

WX78.ANNOUNCE_KYNO_FREEZEBUFF_START = "UWAGA: SYSTEMY RDZENNE SIĘ CHŁODZĄ"
WX78.ANNOUNCE_KYNO_FREEZEBUFF_END = "SYSTEMY RDZENNE WRACAJĄ DO NORMALNEJ PRACY"

WX78.ANNOUNCE_KYNO_FIREBUFF_START = "UWAGA: SYSTEMY RDZENNE SIĘ ROZGRZEWAJĄ"
WX78.ANNOUNCE_KYNO_FIREBUFF_END = "SYSTEMY RDZENNE WRACAJĄ DO NORMALNEJ PRACY"

WX78.ANNOUNCE_KYNO_FISHINGBUFF_START = "AJI WO [K]UTTA?"
WX78.ANNOUNCE_KYNO_FISHINGBUFF_END = "UWAGA: DODATEK WĘDKARSKI ZOSTAŁ WYŁĄCZONY"

WX78.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "OBNIŻA SIĘ AKTYWNOŚĆ USŁUG CHMUROWYCH"
WX78.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "USŁUGI CHMUROWE WRACAJĄ DO NORMY"

WX78.ANNOUNCE_KYNO_EATERBUFF_START = "SYSTEMY TRAWIENNE WZMOCNIONE"
WX78.ANNOUNCE_KYNO_EATERBUFF_END = "SYSTEMY TRAWIENNE WRACAJĄ DO NORMALNEJ PRACY"

WX78.ANNOUNCE_KYNO_WORMBUFF_START = "SYSTEMY GOTOWE DO WALKI Z ROBALAMI"
WX78.ANNOUNCE_KYNO_WORMBUFF_END = "PRZEKROCZENIE LIMITU: WYŁĄCZANIE MODUŁÓW ATAKU NA ROBALe"

WX78.ANNOUNCE_KYNO_CRABBUFF_START = "SYSTEMY GOTOWE DO WALKI Z KRABAMI"
WX78.ANNOUNCE_KYNO_CRABBUFF_END = "PRZEKROCZENIE LIMITU: WYŁĄCZANIE MODUŁÓW ATAKU NA KRABY"

WX78.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(BUUURP) CO DO CH…?"
WX78.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "EFEKTY BĄBELKÓW ZOSTAŁY USUNIĘTE"

WX78.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "AAAHH! KSIĘŻYC! TAK!!"
WX78.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "NIEEE! MOJE MOCY! ODDAJ JE!"

WX78.ANNOUNCE_KYNO_STEALTHBUFF_START = "MODUŁ NIEWIDZIALNOŚCI: WŁĄCZONY"
WX78.ANNOUNCE_KYNO_STEALTHBUFF_END = "MODUŁ NIEWIDZIALNOŚCI: WYŁĄCZONY"

WX78.ANNOUNCE_KYNO_FEARBUFF_START = "ODPOWIEDŹ EMOCJONALNA: MODUŁ STRACHU WYŁĄCZONY. SATYSFAKCJONUJĄCE."
WX78.ANNOUNCE_KYNO_FEARBUFF_END = "MODUŁ STRACHU PONOWNIE WŁĄCZONY! WYKRYTO MINIMALNE DRGANIA CHASSIS"

WX78.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "**SYSTEM PRZECIĄŻONY**."
WX78.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "POZIOMY ENERGII WRACAJĄ DO ŚREDNIEGO."

WX78.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "AFINITY Z ŚWINKAMI ZWIĘKSZONA."
WX78.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "AFINITY Z ŚWINKAMI ZAKOŃCZONA."

WX78.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "KOROZYJNE MATERIAŁY ZNEUTRALIZOWANE."
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WX78.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "BIOLOGICZNE TOKSYNY WYŁĄCZONE."
WX78.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "ODPORNOŚĆ WYGASŁA. ZAGROŻENIE ORGANICZNE PRZYWRÓCONE."

WX78.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "AKTUALIZACJA SYSTEMU: WYDAJNOŚĆ KONSTRUKCJI ZWIĘKSZONA."
WX78.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "AKTUALIZACJA WYGASŁA. POWRÓT DO TRYBU GŁUPOTY."

WX78.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "WROGIE BIO-DRONY TYMCZASOWO USPRAWIONE. AKCEPTOWALNE."
WX78.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "BIO-DRONY WRACAJĄ DO TRYBU AGRESJI. OSTRZEŻENIE."

WX78.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "AKTUALIZACJA: ZWIĘKSZONA WYTRZYMAŁOŚĆ STRUKTURALNA"
WX78.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "AKTUALIZACJA WYGASŁA. ROZCZAROWANIE WZRASTA"

WX78.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "POJEMNOŚĆ MAGAZYNOWANIA PALIWA ZWIĘKSZONA"
WX78.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "POJEMNOŚĆ PALIWA ZMNIEJSZONA"

WX78.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "DIAGNOZA: UMYSŁ ULEPSZONY"
WX78.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "ULEPSZENIE UMYSŁU WYGASŁO"

WX78.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "ULEPSZENIA PARAMETRÓW OBRONNYCH AKTYWNE."
WX78.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "OSTRZEŻENIE: DODATKOWE ŚRODKI OBRONNE ZAKOŃCZONE."

WX78.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "NIEWŁAŚCIWA JEDNOSTKA ROZMIESZCZENIA"

WX78.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "BRUDNE STWORZENIE CHCE CZEGOŚ INNEGO"

WX78.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "GŁUPIE DRZEWO JEST ZA MAŁE, ABY OBSŁUŻYĆ MOJE URZĄDZENIE"

WX78.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "BŁĄD: NIEZNANA JEDNOSTKA WDROŻENIOWA"

WX78.ANNOUNCE_KYNO_POTHANGER_FAIL = "WYMAGA URZĄDZENIA DO GOTOWANIA"

WX78.ANNOUNCE_KYNO_CASSEROLE_FAIL = "BŁĄD: BRAKUJE JEDNOSTKI CRUCIAL CASSEROLE"

WX78.ANNOUNCE_KYNO_SAPHEALER_USED = "PROCES ODNOWY ZAKOŃCZONY. STATUS JEDNOSTKI: 100%"

WX78.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "HA. HA. ORGANICZNA FORMA ŻYCIA USUNIĘTA. ZBIÓR ZAKOŃCZONY."

WX78.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "BRAK WARTOŚCIOWYCH ZAWARTOŚCI. STRATA CZASU"

WX78.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "CEL UTRACONY. ŚCIEŻKA ZALANA."
WX78.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "OPADY WYKRYTE. DANE USZKODZONE."
WX78.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "WYKRYTO ZAGROŻENIE MORSKIE. WYMAGANA ELIMINACJA."

WX78.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "KONSTRUKCJA UKOŃCZONA. URUCHAMIAM TRYB ŚWIĘTOWANIA"

WX78.ANNOUNCE_KYNO_FISH_RESEARCHED = "ANALIZA ZAKOŃCZONA. DANE RYBY POZYSKANE."
WX78.ANNOUNCE_KYNO_ROE_RESEARCHED = "ANALIZA JAJ ZAKOŃCZONA. DANE POZYSKANE."

WX78.DESCRIBE.KYNO_ROE = "POTENCJALNE WODNE NIEDOSKONAŁOŚCI"
WX78.DESCRIBE.KYNO_ROE_COOKED = "BYŁY BEZBRONNE, WIĘC JE ZNISZCZYŁEM HAHAHA"

WX78.DESCRIBE.KYNO_SHARK_FIN = "STEROWANIE BESTII"

WX78.DESCRIBE.KYNO_BEANBUGS = "NATURA JEST ANOMALIĄ"
WX78.DESCRIBE.KYNO_BEANBUGS_COOKED = "ZAWIERA ENERGIĘ, ALE W JAKIM CENIE?"

WX78.DESCRIBE.KYNO_GUMMYBUG = "ŚLISKA ENERGIA"
WX78.DESCRIBE.KYNO_GUMMYBUG_COOKED = "HAHA, PRZEKONWERTUJĘ CIĘ W ENERGIĘ"

WX78.DESCRIBE.KYNO_WHEAT = "WYKRYTO ZIARNO"
WX78.DESCRIBE.KYNO_WHEAT_COOKED = "WYKRYTO PRAŻONE ZIARNO"

WX78.DESCRIBE.KYNO_FLOUR = "Początkowa faza jedzenia."

WX78.DESCRIBE.KYNO_SPOTSPICE = "ZOSTAŁEŚ ZMIAŻDŻONY, PĘD"

WX78.DESCRIBE.KYNO_SAP = "PYSZNY ROŚLINNY CZYNNIK CHŁODZĄCY"
WX78.DESCRIBE.KYNO_SAP_SPOILED = "BEZUŻYTECZNA KLEISTOŚĆ"

WX78.DESCRIBE.KYNO_SYRUP = "ZAWIERA WYSOKI POZIOM KLEISTOŚCI"

WX78.DESCRIBE.KYNO_COFFEEBEANS = "PIJALNE ZIARNA"
WX78.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "NARKOTYCZNE ZIARNO OSIĄGNĘŁO OPTYMALNY STOPIEŃ PRAŻENIA"

WX78.DESCRIBE.DUG_KYNO_COFFEEBUSH = "OKAZ GOTOWY DO PRZESADZENIA"

WX78.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "ROŚLINA ZIARNISTA DO PICIA",
	PICKED = "PRODUKCJA ZIAREN ZATRZYMANA",
	WITHERED = "NIEWYSTARCZAJĄCY POZIOM POPIOŁU",
}

WX78.DESCRIBE.DUG_KYNO_SPOTBUSH = "GŁUPI KRZEW WYMAGA PRZESADZENIA"

WX78.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "DAJ MI SWOJE JEDZENIE, KRZEWIE",
	PICKED = "PRODUKCJA ZATRZYMANA",
	BURNING = "OSTRZEŻENIE: SPALANIE",
}

WX78.DESCRIBE.KYNO_SPOTSPICE_LEAF = "ZETRĘ CIĘ NA PROSZEK"

WX78.DESCRIBE.KYNO_MUSSEL = "BRAK WYKRYTEJ MUSKULATURY"
WX78.DESCRIBE.KYNO_MUSSEL_COOKED = "CZĄSTECZKI SMAKU SĄ SILNE"

WX78.DESCRIBE.KYNO_HUMANMEAT = "DALSZA POPRAWKA LUDZKIEGO STANU."
WX78.DESCRIBE.KYNO_HUMANMEAT_COOKED = "WRESZCIE CEL DLA MIĘSNEJ PLAGI"
WX78.DESCRIBE.KYNO_HUMANMEAT_DRIED = "MIŁO I SUCHO"

WX78.DESCRIBE.COFFEE = "TO TYLKO GORĄCY SOK Z FASOLEK."

WX78.DESCRIBE.BISQUE = "ENERGIA AKUMULATORA W MISCE"

WX78.DESCRIBE.JELLYOPOP = "TO UTRZYMA MOJE SYSTEMY W RUCHU"

WX78.DESCRIBE.SHARKFINSOUP = "WYGLĄDA NA JEDZNE"

WX78.DESCRIBE.TROPICALBOUILLABAISSE = "TO PALIWO DLA MOJEGO NADRZĘDNEGO MECHANICZNEGO CIAŁA"

WX78.DESCRIBE.MUSSELBOUILLABAISE = "AKTYWUJĘ CZUJNE SENSORRY JĘZYKA"

WX78.DESCRIBE.SWEETPOTATOSOUFFLE = "OFENSYWNE"

WX78.DESCRIBE.FEIJOADA = "Paczki energii"

WX78.DESCRIBE.GUMMY_CAKE = "NIE MA W TYM RADOŚCI"

WX78.DESCRIBE.HARDSHELL_TACOS = "ZDEPCZĘ JEGO TWARDA SKORUPĘ"

WX78.DESCRIBE.ICEDTEA = "ORZEŹWIAJĄCY NAPÓJ STWORZONY Z MOJEGO WROGA"

WX78.DESCRIBE.NETTLELOSANGE = "SPREPAROWANE POWIETRZE DLA JEDNOSTEK NOSOWYCH"

WX78.DESCRIBE.SNAKEBONESOUP = "WYWAR PRZYGOTOWANY Z DWÓCH MOICH WROGÓW"

WX78.DESCRIBE.STEAMEDHAMSANDWICH = "NIEZAPOMNIANY OBIAD"

WX78.DESCRIBE.TEA = "PŁYN POZYSKANY Z MASZYNY MIĘSNEJ"

WX78.DESCRIBE.BUBBLETEA = "ORZEŹWIAJĄCY NAPÓJ WYKONANY Z MOJEGO WROGA"

WX78.DESCRIBE.FRENCHONIONSOUP = "WARZONE Z ONIONÓW"

WX78.DESCRIBE.SLAW = "ZIDENTYFIKOWANE POŻYWIENIE"

WX78.DESCRIBE.LOTUSBOWL = "UWOLNIŁEM JE OD ZIEMSKICH OGRANICZEŃ"

WX78.DESCRIBE.POI = "TO ZWYKŁE JEDZENIE POWINNO BYĆ WYMARŁE"

WX78.DESCRIBE.JELLYBEAN_HUNGER = "Tymczasowe komponenty ulepszeń"
WX78.DESCRIBE.JELLYBEAN_SUPER = "Tymczasowe komponenty ulepszeń"
WX78.DESCRIBE.JELLYBEAN_SANITY = "Tymczasowe komponenty ulepszeń"

WX78.DESCRIBE.BOWLOFGEARS = "TAK. TERAZ TO JEST WŁAŚCIWE JEDZENIE DLA SUPERIORNEGO ISTNIENIA"

WX78.DESCRIBE.LONGPIGMEAL = "ULEPSZENIE LUDZKIEGO MIĘSA"

WX78.DESCRIBE.CUCUMBERSALAD = "SALATKA ZŁOŻONA: ZAKOŃCZONE"

WX78.DESCRIBE.DUG_KYNO_WILDWHEAT = "PRZYGOTOWANE DO PRZESADZENIA"

WX78.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "ZBOŻA",
	PICKED = "PRODUKCJA ZATRZYMANA",
	WITHERED = "NIEWYSTARCZAJĄCA WILGOTNOŚĆ",
	BURNING = "OSTRZEŻENIE: SPALANIE",
}

WX78.DESCRIBE.KYNO_MEALGRINDER = "JESTEM DOBRY W ZGNIECENIU"

WX78.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "JEDZENIE POTWIERDZONE",
	PICKED = "TEMPO WZROSTU NIEOPTIMALNE DLA MOICH POTRZEB",
	BURNING = "OSTRZEŻENIE: SPALANIE ORGANICZNE",
}

WX78.DESCRIBE.GORGE_BREAD = "SKŁADNIK DO LEPSZYCH PRZEPISÓW"
WX78.DESCRIBE.GORGE_SWEET_CHIPS = "KAWAŁKI ZIEMNIAKA POKROJONE I SMAŻONE"
WX78.DESCRIBE.GORGE_VEGETABLE_SOUP = "ZBIÓR WARZYW ZEBRANYCH W JEDNE MIEJSCE"
WX78.DESCRIBE.GORGE_JELLY_SANDWICH = "DŻEMUJĘ SIĘ"
WX78.DESCRIBE.GORGE_FISH_STEW = "PRZYGOTUJ SIĘ NA PRZYJĘCIE KALORII"
WX78.DESCRIBE.GORGE_MEAT_STEW = "NABYTE NUTRITION"
WX78.DESCRIBE.GORGE_ONION_CAKE = "OŚMIESZAJĄCE CIASTO"
WX78.DESCRIBE.GORGE_POTATO_PANCAKES = "ŻAŁOSNE WYKORZYSTANIE ZIEMNIAKÓW"
WX78.DESCRIBE.GORGE_POTATO_SOUP = "ENERGIA AKUMULATORA W MISCE"
WX78.DESCRIBE.GORGE_FISHBALL_SKEWERS = "NIEZŁA ILOŚĆ JEDZENIA NA PATYKU"
WX78.DESCRIBE.GORGE_MEAT_SKEWERS = "NIEZŁA ILOŚĆ JEDZENIA NA PATYKU"
WX78.DESCRIBE.GORGE_STONE_SOUP = "ENERGIA BATERII W MISCE"
WX78.DESCRIBE.GORGE_CROQUETTE = "KULKI MĄCANE"
WX78.DESCRIBE.GORGE_ROAST_VEGETABLES = "OHYDA"
WX78.DESCRIBE.GORGE_MEATLOAF = "MIESZANINA CIASTA I MIĘSA"
WX78.DESCRIBE.GORGE_CARROT_SOUP = "ENERGIA W MISECZCE"
WX78.DESCRIBE.GORGE_FISHPIE = "SŁABE ORGANIZMY ZATOPIONE W MĄCE. HA HA."
WX78.DESCRIBE.GORGE_FISHCHIPS = "BARDZIEJ ODPOWIEDNIE JEDZENIE"
WX78.DESCRIBE.GORGE_MEATPIE = "MIĘSO ZGNIECIONE W TARCIE"
WX78.DESCRIBE.GORGE_SLIDERS = "ŚMIECIOWE JEDZENIE"
WX78.DESCRIBE.GORGE_JELLY_ROLL = "ZA BARDZO ŚLISKIE DLA MNIE"
WX78.DESCRIBE.GORGE_CARROT_CAKE = "ALE... ALE... MYŚLAŁEM, ŻE TO TYLKO KŁAMSTWO"
WX78.DESCRIBE.GORGE_GARLICMASHED = "ODRZUCAM TEN MIESZANIEC"
WX78.DESCRIBE.GORGE_GARLICBREAD = "ŚWIETNE UZUPEŁNIENIE"
WX78.DESCRIBE.GORGE_TOMATO_SOUP = "ENERGIA BATERYJNA W MISCE"
WX78.DESCRIBE.GORGE_SAUSAGE = "HA. TWÓJ KONIEC NADSZEDŁ"
WX78.DESCRIBE.GORGE_CANDIEDFISH = "SYROP W MOICH UKŁADACH"
WX78.DESCRIBE.GORGE_STUFFEDMUSHROOM = "NADZIEWANE"
WX78.DESCRIBE.GORGE_BRUSCHETTA = "NIC NADZWYCZAJNEGO W TYM."
WX78.DESCRIBE.GORGE_HAMBURGER = "JEDNO Z NIELICZNYCH LUDZKICH JEDZENIE, KTÓRE JEST ŚWIETNE"
WX78.DESCRIBE.GORGE_FISHBURGER = "JEDNO Z NIELICZNYCH LUDZKICH JEDZENIE, KTÓRE JEST ŚWIETNE"
WX78.DESCRIBE.GORGE_MUSHROOMBURGER = "JEDNO Z NIELICZNYCH LUDZKICH JEDZENIE, KTÓRE JEST ŚWIETNE"
WX78.DESCRIBE.GORGE_FISH_STEAK = "PRZYGOTUJ SIĘ NA PRZYJĘCIE KALORII"
WX78.DESCRIBE.GORGE_CURRY = "TO ZWYKŁA ZUPA-TYPOWA"
WX78.DESCRIBE.GORGE_SPAGHETTI = "MIĘSO UFORMOWANE W NAJBARDZIEJ ODŻYWCZY KSZTAŁT: KULĘ"
WX78.DESCRIBE.GORGE_POACHEDFISH = "TEN ŁOSOŚ JUŻ NIGDZIE NIE POPŁYNIE"
WX78.DESCRIBE.GORGE_SHEPHERD_PIE = "NIE MA TU ŻADNYCH OWIEC"
WX78.DESCRIBE.GORGE_CANDY = "LEPKIE I SŁODKIE"
WX78.DESCRIBE.GORGE_BREAD_PUDDING = "SŁODKI CHLEB"
WX78.DESCRIBE.GORGE_BERRY_TART = "O MÓJ BOŻE, TO OBRZYDLIWE"
WX78.DESCRIBE.GORGE_MACARONI = "WYSYSAM TO DANIE"
WX78.DESCRIBE.GORGE_BAGEL_AND_FISH = "ŁOSOŚ Z CHLEBEM, JAKŻE ORYGINALNE"
WX78.DESCRIBE.GORGE_GRILLED_CHEESE = "PRINT(\"HELLO WORLD\")"
WX78.DESCRIBE.GORGE_CREAMMUSHROOM = "NIE, TYLKO NIE TO ZNOWU"
WX78.DESCRIBE.GORGE_MANICOTTI = "NUDNE"
WX78.DESCRIBE.GORGE_CHEESEBURGER = "JEDNO Z NIELICZNYCH LUDZKICH JEDZEN, KTÓRE JEST WSPANIAŁE"
WX78.DESCRIBE.GORGE_FETTUCCINE = "NIE PATRZ NA MNIE W OCZY PONOWNIE"
WX78.DESCRIBE.GORGE_ONION_SOUP = "ŚMIERDZI"
WX78.DESCRIBE.GORGE_BREADED_CUTLET = "MIĘSO I CHLEB POŁĄCZONE ZE SOBĄ"
WX78.DESCRIBE.GORGE_CREAMY_FISH = "ŁOSOŚ ZNOWU? JAK ORYGINALNE"
WX78.DESCRIBE.GORGE_PIZZA = "HA. KLASYCZNA PRZYNĘTA DLA GŁUPICH LUDZI"
WX78.DESCRIBE.GORGE_POT_ROAST = "TO PO PROSTU NIEMOŻLIWE"
WX78.DESCRIBE.GORGE_CRAB_CAKE = "TO Z PEWNOŚCIĄ NIE JEST SZTUKA"
WX78.DESCRIBE.GORGE_STEAK_FRITES = "KLASYKA"
WX78.DESCRIBE.GORGE_SHOOTER_SANDWICH = "STRZELAJ DO GWIAZD"
WX78.DESCRIBE.GORGE_BACON_WRAPPED = "TO TYLKO MIĘSO ZAWINIĘTE W MIĘSO"
WX78.DESCRIBE.GORGE_CRAB_ROLL = "NADZWYCZAJNE"
WX78.DESCRIBE.GORGE_MEAT_WELLINGTON = "MAM WĄTPLIWOŚCI CO DO TEGO DANIA"
WX78.DESCRIBE.GORGE_CRAB_RAVIOLI = "EKSTRAORDYNARYJNE"
WX78.DESCRIBE.GORGE_CARAMEL_CUBE = "DOSKONAŁA KOSTKA KARMELU"
WX78.DESCRIBE.GORGE_SCONE = "ZA DUŻO CUKRU AAAAA"
WX78.DESCRIBE.GORGE_TRIFLE = "ZA DUŻO CUKRU AAAAA"
WX78.DESCRIBE.GORGE_CHEESECAKE = "GDZIE JEST SER NA TYM?"

WX78.DESCRIBE.DUCKYOUGLERMZ = "TA ROŚLINA POTRZEBUJE NAPRAWY SWOJEGO SPRZĘTU"

WX78.DESCRIBE.KYNO_ALOE = "ZIELONA ENERGIA ZDOBYTA"
WX78.DESCRIBE.KYNO_ALOE_COOKED = "ZIELONA ENERGIA USMAŻONA"
WX78.DESCRIBE.KYNO_ALOE_GROUND = "ZIELONA ENERGIA POZYSKANA"
WX78.DESCRIBE.KYNO_ALOE_SEEDS = "KOD ŹRÓDŁOWY POŻYWIENIA POCHODZĄCEGO Z ZIEMI"
WX78.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "KOD ŹRÓDŁOWY POŻYWIENIA POCHODZĄCEGO Z ZIEMI"
WX78.DESCRIBE.FARM_PLANT_KYNO_ALOE = "ZIELONA ENERGIA POZYSKANA"
WX78.DESCRIBE.KYNO_ALOE_OVERSIZED = "ZIELONA ENERGIA POZYSKANA"
WX78.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_CUCUMBER = "ZABRAŁEM TO OBRZYDLIWEJ WODZIE"
WX78.DESCRIBE.KYNO_CUCUMBER_COOKED = "ENERGETYCZNA PAPKA"
WX78.DESCRIBE.KYNO_CUCUMBER_GROUND = "UKRADŁEM TO OKROPNEMU OCEANOWI"
WX78.DESCRIBE.KYNO_CUCUMBER_SEEDS = "KOD ŹRÓDŁOWY JEDZENIA, KTÓRE WYRSTA Z ZIEMI"
WX78.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "KOD ŹRÓDŁOWY JEDZENIA, KTÓRE WYRSTA Z ZIEMI"
WX78.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "UKRADŁEM TO Z OKROPNYCH WÓD"
WX78.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "UKRADŁEM TO Z OKROPNYCH WÓD"
WX78.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_RADISH = "CZERWONE KULE ENERGII"
WX78.DESCRIBE.KYNO_RADISH_COOKED = "ENERGIA POZYSKANA"
WX78.DESCRIBE.KYNO_RADISH_GROUND = "CZERWONE KULE ENERGII"
WX78.DESCRIBE.KYNO_RADISH_SEEDS = "KOD ŹRÓDŁOWY JEDZENIA, KTÓRE WYRSTA Z ZIEMI"
WX78.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "KOD ŹRÓDŁOWY JEDZENIA, KTÓRE WYRSTA Z ZIEMI"
WX78.DESCRIBE.FARM_PLANT_KYNO_RADISH = "CZERWONE KULE ENERGII"
WX78.DESCRIBE.KYNO_RADISH_OVERSIZED = "WIELKIE CZERWONE KULE ENERGII"
WX78.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_FENNEL = "WYGLĄDA JAK ZWYKŁA ROŚLINA."
WX78.DESCRIBE.KYNO_FENNEL_COOKED = "OCHYDA"
WX78.DESCRIBE.KYNO_FENNEL_GROUND = "WYGLĄDA JAK ZWYKŁA ROŚLINA."
WX78.DESCRIBE.KYNO_FENNEL_SEEDS = "KOD ŹRÓDŁOWY JEDZENIA Z ZIEMI"
WX78.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "KOD ŹRÓDŁOWY JEDZENIA Z ZIEMI"
WX78.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "DLA MNIE ZWYKŁA ROŚLINA."
WX78.DESCRIBE.KYNO_FENNEL_OVERSIZED = "DLA MNIE ZWYKŁA ROŚLINA."
WX78.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_SWEETPOTATO = "OBLEŚNE"
WX78.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "SKROBIA I SŁODYCZ WALCZĄ O DOMINACJĘ, A WX-78 PRZEGRYWA"
WX78.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "OCHYDA"
WX78.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "TO KOD ŹRÓDŁOWY JEDZENIA, KTÓRE ROŚNIE W ZIEMI"
WX78.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "TO KOD ŹRÓDŁOWY JEDZENIA, KTÓRE ROŚNIE W ZIEMI"
WX78.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "OHYDA"
WX78.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "OHYDA"
WX78.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_PARZNIP = "ODŻYWCZY"
WX78.DESCRIBE.KYNO_PARZNIP_COOKED = "ODŻYWCZY"
WX78.DESCRIBE.KYNO_PARZNIP_EATEN = "ODŻYWCZY"
WX78.DESCRIBE.KYNO_PARZNIP_GROUND = "ODŻYWCZY"
WX78.DESCRIBE.KYNO_PARZNIP_BIG = "ANALIZA ROZMIARU ZAKOŃCZONA: GIGANTYCZNY"
WX78.DESCRIBE.KYNO_PARZNIP_SEEDS = "TO KOD ŹRÓDŁOWY DLA JEDZENIA, KTÓRE WYCHODZI Z ZIEMI"
WX78.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "TO KOD ŹRÓDŁOWY DLA JEDZENIA, KTÓRE WYCHODZI Z ZIEMI"
WX78.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "ODŻYWCZE"
WX78.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "ODŻYWCZE"
WX78.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_TURNIP = "TO GŁUPIA RZODKIEW"
WX78.DESCRIBE.KYNO_TURNIP_COOKED = "JEST UPIECZONA RÓWNOMIERNIE"
WX78.DESCRIBE.KYNO_TURNIP_GROUND = "TO GŁUPIA RZODKIEW"
WX78.DESCRIBE.KYNO_TURNIP_SEEDS = "TO KOD ŹRÓDŁOWY DLA JEDZENIA, KTÓRE POCHODZI Z BRUDU"
WX78.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "TO KOD ŹRÓDŁOWY DLA JEDZENIA, KTÓRE POCHODZI Z BRUDU"
WX78.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "TO GŁUPIA RZEPA"
WX78.DESCRIBE.KYNO_TURNIP_OVERSIZED = "TO GŁUPIA RZEPA"
WX78.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_RICE = "OBRZYDLIWE WARZYWO"
WX78.DESCRIBE.KYNO_RICE_COOKED = "OBRZYDLIWE WARZYWO"
WX78.DESCRIBE.KYNO_RICE_SEEDS = "KOD ŹRÓDŁOWY JEDZENIA, KTÓRE WYCHODZI Z ZIEMI"
WX78.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "KOD ŹRÓDŁOWY JEDZENIA, KTÓRE WYCHODZI Z ZIEMI"
WX78.DESCRIBE.FARM_PLANT_KYNO_RICE = "TO GŁUPIA ŁODYGA RYŻU"
WX78.DESCRIBE.KYNO_RICE_OVERSIZED = "TO GŁUPIA ŁODYGA RYŻU"
WX78.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_SEEDS_KIT = "BRUDNA RZECZ"

WX78.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "GŁUPIE MIĘSO NIGDY NIE POŻRE KAMIENIA",
	PICKED = "ORGANIKA TYMczasowo NIEDOSTĘPNA",
	WITHERED = "ŚRODOWISKO NIEODPOWIEDNIE DLA ORGANIK",
}

WX78.DESCRIBE.KYNO_LIMPETS = "MAŁE ŹRÓDŁO BIAŁKA"
WX78.DESCRIBE.KYNO_LIMPETS_COOKED = "Witaj poprawo"

WX78.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "ORGANIKA WYMAGAJĄCA WODY",
	PICKED = "PRODUKCJA KWIATÓW ZATRZYMANA",
	BURNING = "BŁĄD KRYTYCZNY: SPALANIE",
}

WX78.DESCRIBE.KYNO_LOTUS_ROOT = "NIE DO ZASTOSOWANIA POZA WODĄ"
WX78.DESCRIBE.KYNO_LOTUS_FLOWER = "BRZYDKI WODNY KWIASTEK"
WX78.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "UWAŻAM, ŻE UWOLNIŁEM TO OD JEGO WODNYCH WYMAGAŃ"

WX78.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "MORZE TEŻ MA WODOROSTY?",
	PICKED = "ODROST W TRAKCIE",
	BURNING = "BŁĄD: OGIEŃ W ŚRODOWISKU WODNYM",
}

WX78.DESCRIBE.KYNO_SEAWEEDS = "JEST ŚLISKIE I ODRAŻAJĄCE"
WX78.DESCRIBE.KYNO_SEAWEEDS_COOKED = "ZDROWIAK"
WX78.DESCRIBE.KYNO_SEAWEEDS_DRIED = "JEDZENIE ZDROWE"
WX78.DESCRIBE.KYNO_SEAWEEDS_ROOT = "NIESTOSOWALNE POZA WODĄ"

WX78.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "ODPYCHAJĄCA ROŚLINA WODNA",
	PICKED = "ODROST PRZYSPIESZONY PRZEZ WODĘ",
	BURNING = "OSTRZEŻENIE: SPALANIE ORGANICZNE",
}

WX78.DESCRIBE.KYNO_TAROROOT_ROOT = "NIE DO ZASTOSOWANIA POZA WODĄ"
WX78.DESCRIBE.KYNO_TAROROOT = "TO JEST TAK PURPUROWE"
WX78.DESCRIBE.KYNO_TAROROOT_COOKED = "WYKWINTNE"

WX78.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "ODPYCHAJĄCA ROŚLINA",
	PICKED = "CYKL ODROSTU ROZPOCZĘTY",
	BURNING = "ANOMALIA SYSTEMU: WYKRYTO OGIEŃ",
}

WX78.DESCRIBE.KYNO_WATERYCRESS_ROOT = "NIE DO ZASTOSOWANIA POZA WODĄ"
WX78.DESCRIBE.KYNO_WATERYCRESS = "ODRZUCONA ROŚLINA"

WX78.DESCRIBE.WATERYCRESSBOWL = "JEST ZROBIONA Z KRWI MOJEGO WROGA"

WX78.DESCRIBE.KYNO_SALT = "ZŁE DLA UKŁADÓW ELEKTRONICZNYCH"

WX78.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "PRZYTWIERDZONE ORGANIKI WODNE",
	PICKED = "ORGANIKI NIEDOSTĘPNE",
	BURNING = "OSTRZEŻENIE: SPALANIE ZASOBÓW",
}

WX78.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "SYSTEM PRZYCIĄGANIA I WZROSTU BIAŁKA"

WX78.DESCRIBE.CATFOOD = "TO GŁÓWNE ŹRÓDŁO ENERGII DLA KOTÓW."

WX78.DESCRIBE.KATFOOD = "TO GŁÓWNE ŹRÓDŁO ENERGII DLA KOTÓW."

WX78.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "POWINIENEM BYŁ ZOSTAWIĆ W PODZIEMIU",
	PICKED = "PRODUKCJA OWOCÓW WSTRZYMANA",
	CHOPPED = "ROŚLINA ZNISZCZONA",
	BURNING = "OSTRZEŻENIE: WYKRYTO SPALANIE",
	BURNT = "ROŚLINA ZREDUKOWANA DO POPIOŁU",
}

WX78.DESCRIBE.KYNO_BANANA = "WIĘCEJ WĘGLA"
WX78.DESCRIBE.KYNO_BANANA_COOKED = "TE JEDZENIA SĄ TAKIE NUDAJĄCE"

WX78.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "TO DRZEWO TO SAME KORZENIE",
	PICKED = "PRODUKCJA OWOCÓW WSTRZYMANA",
	CHOPPED = "ROŚLINA ZNISZCZONA",
	BURNING = "OSTRZEŻENIE: SPALANIE",
	BURNT = "ROŚLINA ZREDUKOWANA DO POPIOŁU",
}

WX78.DESCRIBE.KYNO_KOKONUT = "GŁUPI OWOC DRZEWA"
WX78.DESCRIBE.KYNO_KOKONUT_HALVED = "ODŻYWIANIE TERAZ DOSTĘPNE"
WX78.DESCRIBE.KYNO_KOKONUT_COOKED = "TOASTOWANY ZAPACH NICZEGO DLA MNIE NIE ROBI"

WX78.DESCRIBE.BOWLOFPOPCORN = "PUSTE KALORIE"

WX78.DESCRIBE.FIGJUICE = "ORZEŹWIAJĄCY NAPÓJ Z GŁUPICH OWOCÓW"

WX78.DESCRIBE.COCONUTWATER = "TA WODA ZAWIERA INNY KOD"

WX78.DESCRIBE.EYEBALLSPAGHETTI = "MYŚLĘ, ŻE TO NA MNIE PATRZY"

WX78.DESCRIBE.FORGETMELOTS_SEEDS = "TO KOD ŹRÓDŁOWY DLA JEDZENIA POCHODZĄCEGO Z ZIEMI"

WX78.DESCRIBE.FIRENETTLES_SEEDS = "TO KOD ŹRÓDŁOWY DLA JEDZENIA POCHODZĄCEGO Z ZIEMI"

WX78.DESCRIBE.TILLWEED_SEEDS = "TO KOD ŹRÓDŁOWY DLA JEDZENIA POCHODZĄCEGO Z ZIEMI"

WX78.DESCRIBE.KYNO_FLOATILIZER = "WIADRO MORSKICH ODPADÓW"

WX78.DESCRIBE.KYNO_TWIGGYNUTS = "TE ORZECHY"

WX78.DESCRIBE.KYNO_REPAIRTOOL = "ZESTAW NAPRAWCZY ZAAKTYWOWANY"

WX78.DESCRIBE.KYNO_KOI = "DOCENIAM JEGO ZŁOTAWY BLASK"
WX78.DESCRIBE.KYNO_KOI_COOKED = "DOCENIAM JEGO ZŁOTAWY BLASK"

WX78.DESCRIBE.KYNO_TROPICALFISH = "JESTEŚ TROPICALNYM RYBĄ"
WX78.DESCRIBE.KYNO_TROPICALFISH_COOKED = "HAHA, DOBRZE CI TAK"

WX78.DESCRIBE.KYNO_NEONFISH = "TA RYBA JEST SUCHA W PORÓWNANIU DO INNYCH"
WX78.DESCRIBE.KYNO_NEONFISH_COOKED = "ZDOBĘDĘ JEJ MOC SUSZENIA"

WX78.DESCRIBE.KYNO_GROUPER = "WYCIĄGNĄŁEM CIĘ Z WODY. NIEWDZIĘCZNIK"
WX78.DESCRIBE.KYNO_GROUPER_COOKED = "TERAZ TO PALIWO DLA ROBOTA. HA HA"
 
WX78.DESCRIBE.KYNO_PIERROTFISH = "ŻYJE ZANURZONA W WODZIE. PRZERAŻAJĄCE"
WX78.DESCRIBE.KYNO_PIERROTFISH_COOKED = "POŻRĘ TEGO OKROPNIE WODNISTEGO STWORA"

WX78.DESCRIBE.KYNO_SALMONFISH = "MIOTAJĄCE SIĘ WODNE STWORZENIE"
WX78.DESCRIBE.KYNO_SALMONFISH_COOKED = "JEGO SŁABOŚCIĄ JEST OGIEŃ"

WX78.DESCRIBE.TURF_PINKPARK = "RÓŻOWY KOLOR MIE NAPOTYKA"
WX78.DESCRIBE.TURF_STONECITY = "CZĘŚCI ZIEMI"
WX78.DESCRIBE.TURF_FIELDS = "CZĘŚCI ZIEMI"
WX78.DESCRIBE.TURF_TIDALMARSH = "CZĘŚCI ZIEMI."

WX78.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "UWAGA: UNIKAĆ ROZPRYSKIWANIA CIECZY NA UKŁADY",
	PICKED = "KONTAKT Z WODĄ POMYŚLNIE UNIKNIĘTY",
}

WX78.DESCRIBE.KYNO_SALTRACK_INSTALLER = "WYMAGA MONTAŻU"

WX78.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "DO WYCISKANIA CHŁODNIKA Z DRZEW"

WX78.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "ZATRZYMUJE BIOLOGICZNE SKAŁY"

WX78.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "TEN DUŻY ŚWINIARZ KONTROLUJE MNIEJSZYCH",
	SLEEPING = "TRYB GŁĘBOKIEGO SNU AKTYWOWANY",
}

WX78.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "OHYDNE RÓŻOWE DRZEWO",
	CHOPPED = "ŹRÓDŁO CHŁODZENIA ROŚLIN ZNISZCZONE",
	SAPPED = "CZAS ZEBRAĆ PŁYN CHŁODZĄCY",
	PICKED = "DOMAGAM SIĘ SZYBSZEGO NABICIA",
	BURNING = "OSTRZEŻENIE: SPALANIE",
	BURNT = "BRUDNY ORGANIZM ZNISZCZONY",
}

WX78.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "PIENIEŃ USZKODZONY",
	CHOPPED = "USZKODZONA JEDNOSTKA USUNIĘTA",
	SAPPED = "RUINOWANY PŁYN CHŁODZĄCY GOTOWY",
	PICKED = "MAŁE JEDNOSTKI BIOLOGICZNE UNICESTWIŁY ZBIÓR PŁYNU",
	BURNING = "USUWANIE ZANIECZYSZCZEŃ",
	BURNT = "JEDNOSTKA ZAKOŃCZONA",
}

WX78.DESCRIBE.KYNO_SUGARTREE_BUD = "JEDNOSTKA POJEMNIKA CUKRU"

WX78.DESCRIBE.KYNO_SUGARTREE_FLOWER = "MOJE UZNANIE DLA PIĘKNA JEST OGRANICZONE"
WX78.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "MOJE UZNANIE DLA PIĘKNA JEST OGRANICZONE"

WX78.DESCRIBE.KYNO_SUGARTREE_PETALS = "MOJE UZNANIE DLA PIĘKNA JEST OGRANICZONE"

WX78.DESCRIBE.KYNO_PEBBLECRAB = "TO JAK KAMIEŃ. ALE ŻYJĄCY I GORSZY"

WX78.DESCRIBE.KYNO_CRABMEAT = "MIĘSO Z KAMIENNEGO STWORZENIA"
WX78.DESCRIBE.KYNO_CRABMEAT_COOKED = "PYSZNE MIĘSO SKAŁY"
WX78.DESCRIBE.KYNO_CRABMEAT_DRIED = "MIĘSO SKAŁOPODOBNEGO STWORA"

WX78.DESCRIBE.KYNO_CRABKINGMEAT = "MIĘSO SKAŁOPODOBNEGO STWORA"
WX78.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "MIĘSO Z KAMIENNEGO STWORA"
WX78.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "MIĘSO Z KAMIENNEGO STWORA"

WX78.DESCRIBE.KYNO_SLAUGHTERTOOL = "DO DEMONTAŻU BIOLOGICZNYCH ISTOT ŻYJĄCYCH"

WX78.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "BŁĄD: NIE OBLICZONO",
	COOP = "ORGANICZNA JEDNOSTKA PRAWIDŁOWO ZATRZYMANA",
}

WX78.DESCRIBE.KYNO_CHICKEN_EGG = "NIENAWIDZĘ CIĘ, JAJKO"
WX78.DESCRIBE.KYNO_CHICKEN_LARGE = "ULEPSZONA JEDNOSTKA POWŁOKI OCHRONNEJ"
WX78.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "TO MIAŁO BYĆ ULEPSZENIE"

WX78.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "STRUKTURA ZAWIERAJĄCA DRÓB",
	FULL = "MAKSYMALNA PRODUKCJA JAJEK OSIĄGNIĘTA",
	BURNT = "AWARIA JEDNOSTKI: ORGANIKA ZNISZCZONA",
}

WX78.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "ŻAŁOSNE. NAWET NIE POTRAFIĄ ZBUDOWAĆ PORZĄDNEGO NACZYNIA"

WX78.DESCRIBE.KYNO_COOKWARE_KIT = "PREZENTUJĄCY SIĘ SZABLON KUCHNI"
WX78.DESCRIBE.KYNO_COOKWARE_SYRUP = "WYMAGA CUKRU I OGNI, ABY STWORZYĆ WIĘCEJ CUKRU"
WX78.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "WYMAGA CUKRU I OGNI, ABY STWORZYĆ WIĘCEJ CUKRU"
WX78.DESCRIBE.KYNO_COOKWARE_BIG_POT = "TEN GARNEK MA AKCEPTOWALNY ROZMIAR PAMIĘCI"
WX78.DESCRIBE.KYNO_COOKWARE_BIG = "TEN GARNEK MA AKCEPTOWALNY ROZMIAR PAMIĘCI"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "TEN GARNEK MA NIEWYSTARCZAJĄCĄ PAMIĘĆ"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL = "TEN GARNEK MA NIEWYSTARCZAJĄCĄ PAMIĘĆ"
WX78.DESCRIBE.KYNO_COOKWARE_GRILL = "DODANIE OGNIA DO JEDZENIA ZWIĘKSZA JEGO WARTOŚĆ"
WX78.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "WYMAGA MONTAŻU"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "NIEWYSTARCZAJĄCE MIEJSCA PAMIĘCI"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "WYMAGA MONTAŻU"
WX78.DESCRIBE.KYNO_COOKWARE_ELDER = "WYMAGA SACHAROZY I OGNIA DO PRODUKCJI WIĘCEJ SACHAROZY"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "TEN ROBOT NIE ZOSTAŁ JESZCZE ZBUDOWANY"
WX78.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "DO KONSTRUOWANIA CHAOSU SMAKÓW"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "JEGO MODUŁ PAMIĘCI WYMAGA AKTUALIZACJI"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN = "PODZIWIAM TEGO ROBOTA ZA JEGO WIELKI OGNIOTWÓR"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "PODZIWIAM TEGO ROBOTA ZA JEGO WIELKI OGNIOTWÓR"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "PODZIWIAM TEGO ROBOTA ZA JEGO WIELKI OGNIOTWÓR"

WX78.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "PRZEWRÓĆ KAMIEŃ, ABY WYKONAĆ FUNKCJĘ POSZUKIWANIA",
	FLIPPED = "UKRYTE MATERIAŁY ODKRYTE",
}

WX78.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "WYKRYTO ZGUBIONY ŁADUNEK"

WX78.DESCRIBE.KYNO_SUGARFLY = "MYŚLI, ŻE JEST TAKIE PIĘKNE"
WX78.DESCRIBE.KYNO_SUGARFLYWINGS = "IRYDESCENCYJNE"

WX78.DESCRIBE.KYNO_WATERY_CRATE = "WYKRYTO PŁYNNE ZWŁOKI"

WX78.DESCRIBE.KYNO_TUNACAN = "HERMETYCZNIE ZAMKNIĘTE PRODUKTY SPOŻYWCZE"
WX78.DESCRIBE.KYNO_TUNACAN_OPEN = "HERMETYCZNIE ROZPRZEDANE PRODUKTY SPOŻYWCZE"

WX78.DESCRIBE.KYNO_CANNEDFOOD = "HERMETYCZNIE ZAPIECZĘTOWANE PRODUKTY SPOŻYWCZE"
WX78.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "HERMETYCZNIE OTWARTY PRODUKT SPOŻYWCZY"

WX78.DESCRIBE.KYNO_POP = "CZY TO SPOŻYWCZE?"

WX78.DESCRIBE.KYNO_MYSTERYMEAT = "TO JEST MIĘSO. BEZ TAJEMNIC."

WX78.DESCRIBE.KYNO_BOTTLE_SOUL = "POJEMNIK NA DUSZĘ, PODOBA MI SIĘ JEGO MODUŁ PRZECHOWYWANIA"

WX78.DESCRIBE.SOULSTEW = "ZUPA Z DUSZY, PODOBA MI SIĘ JEJ KONSTRUKCJA"

WX78.DESCRIBE.FORTUNECOOKIE = "TYLKO GŁUPIE SŁOWA BEZ ZNACZENIA"

WX78.DESCRIBE.HORNOCUPIA = "NARZĘDZIE TORTUR DLA GŁODNYCH MIĘCZAKÓW"

WX78.DESCRIBE.CHEESE_YELLOW = "HA HA, LUBIĘ OSZUKIWAĆ... I SER"
WX78.DESCRIBE.CHEESE_WHITE = "HA HA, LUBIĘ OSZUKIWAĆ... I SER"
WX78.DESCRIBE.CHEESE_KOALEFANT = "HA HA, LUBIĘ OSZUKIWAĆ... I SER"

WX78.DESCRIBE.MILK_BOX = "JADALNY PŁYN OD BRUDNYCH ZWIERZĄT"

WX78.DESCRIBE.WATERCUP = "JA... NIE MOGĘ... TEGO ZROBIĆ..."

WX78.DESCRIBE.HONEYJAR = "LEPKIE I SŁODKIE"

WX78.DESCRIBE.CRAB_ARTICHOKE = "MIĘSO FLESHLINGÓW UPRACOWANE DO DOSKONAŁOŚCI"

WX78.DESCRIBE.PEPPERROLLS = "BĘDĘ TO SPOŻYWAĆ. MUSZĘ!"

WX78.DESCRIBE.KYNO_SAPHEALER = "USUWA ZAKAŻENIA Z GŁÓWNYCH FUNKCJI SYSTEMU"

WX78.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "NIEWYSTARCZAJĄCE STEROWANIE",
	PICKED = "ORGANIKA TYMCZASOWO NIEDOSTĘPNA",
	BURNING = "INTEGRALNOŚĆ STRUKTURALNA ZAGROŻONA",
}

WX78.DESCRIBE.KYNO_GHOST_PIRATE = "ARRR JESTEŚ NIESPOKOJNĄ DUSZĄ?"

WX78.DESCRIBE.KYNO_BUCKET_EMPTY = "MODUŁ PRZECHOWYWANIA CIECZY"
WX78.DESCRIBE.KYNO_BUCKET_METAL = "POJEMNIK NA CIECZEŃ"
WX78.DESCRIBE.KYNO_BUCKET_WATER = "BEZUŻYTECZNY PŁYN DLA ORGANICZNYCH FORM ŻYCIA"

WX78.DESCRIBE.KYNO_MILK_BEEFALO = "MLEKO Z NATURALNYCH ŹRÓDEŁ"
WX78.DESCRIBE.KYNO_MILK_KOALEFANT = "MLEKO Z NATURALNYCH ŹRÓDEŁ"

WX78.DESCRIBE.KYNO_CAP_DRIED = "NIE LUBIĘ, JAK TO WYGLĄDA. BIEDNA SZTUKA NATURY"

WX78.DESCRIBE.KYNO_PLANTMEAT_DRIED = "DEHYDRATACJA BIAŁEK"

WX78.DESCRIBE.KYNO_BREWBOOK = "KATALOG NAPOJÓW"

WX78.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "SPRZĘT ALKOHOLOWY",
	BREWING_LONG = "PROCES W POCZĄTKOWEJ FAZIE",
	BREWING_SHORT = "PROCES PRAWIE ZAKOŃCZONY",
	DONE = "WARZENIE ZAKOŃCZONE",
	BURNT = "POJEMNIK ZNISZCZONY",
}

WX78.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "SPRZĘT Z MOŻLIWOŚCIĄ KONSERWACJI",
	BREWING_LONG = "PROCES KONSERWACJI W TRAKCIE",
	BREWING_SHORT = "PROCES PRAWIE ZAKOŃCZONY",
	DONE = "KONSERWACJA ZAKOŃCZONA",
	BURNT = "AWARIA POJEMNIKA",
}

WX78.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "PRZERÓBKA I MAGAZYNOWANIE MIODU",
	HONEY = "MAGAZYN MIODU NA DOPUSZCZALNYM POZIOMIE",
	NECTAR = "PRZETWARZANIE NEKTARU W TRAKCIE",
	BURNING = "BŁĄD: SPALANIE ZASOBÓW",
}

WX78.DESCRIBE.KYNO_NECTAR_POD = "WYMAGA KONWERTERA MIODU, ABY STAŁO SIĘ UŻYTECZNE"

WX78.DESCRIBE.KYNO_OAKTREE_POD = "WIELOFUNKCYJNY POJEMNIK ENERGII"
WX78.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "BIOLOGICZNY PAKIET ENERGETYCZNY"

WX78.DESCRIBE.KYNO_PIKO = "MASZYNA MIĘSNA ZBIERAJĄCA ORZECHY"
WX78.DESCRIBE.KYNO_PIKO_ORANGE = "MASZYNA MIĘSNA Z WŁAŚCIWOŚCIAMI ZAPARZANIA"

WX78.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "NIERUCHOMA FORMA ŻYCIA Z DREWNA",
	CHOPPED = "EKSTRAKCJA ZASOBÓW ZAKOŃCZONA",
	BURNING = "OSTRZEŻENIE: SPALANIE",
	BURNT = "OKAZ ZNISZCZONY",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "NIERUCHOMA FORMA ŻYCIA Z DREWNA ZAINFESTOWANA BRUDNYMI ORGANIZMAMI",
	BURNING = "TRWA USUWANIE SIEDLISKA",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "DOWÓD MORSKIEJ KATASTROFY"

WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "PRZESTARZAŁE MIEJSCE ZAMIESZKANIA",
	BURNT = "STRUKTURA ZNISZCZONA",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "AKTUALIZACJA SYSTEMU IDENTYFIKACJI ZAPACHU: RYBY MAKSYMALNE",
	CRAFTED = "JAKOŚĆ STRUKTURALNA POPRAWIONA",
	BURNT = "POZIOM ZAPACHU NIEAKCEPTOWALNY",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "OBIEKT WYMIANY RYB",
	OCCUPIED = "SPRZEDAWCA NIEDOSTĘPNY",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "KRADZIEŻ JEST ZŁA, ALE TEN DUDE PEWNIE NIE MA PRZECIWKO",
	EMPTY = "INWENTARZ WYCZERPANY",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "TO TY. HANDLOWIEC RYBNY, KTÓRY SPRZEDAŁ MI KIEDYŚ NASIONA"
WX78.DESCRIBE.KYNO_MEADOWISLAND_POND = "NATURALNIE WYSTĘPUJĄCY ZBIORNIK WODNY"
WX78.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "NIEINTERESUJĄCA ROŚLINA"
WX78.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "PYŁ SKALNY GROMADZI SIĘ W STOSY"
WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "AKTUALIZACJA SYSTEMU AROMATÓW: RYBI"

WX78.DESCRIBE.KYNO_SAMMYHAT = "CZAPKA HANDLARZA"

WX78.DESCRIBE.KINGFISHER = "PTAK Z WIELKIM MECHANIZMEM DZIÓBOWYM"

WX78.DESCRIBE.TOUCAN = "MASZ NADMIERNY NOS"
WX78.DESCRIBE.TOUCAN_CHUBBY = "POSIADASZ NADMIERNĄ ILOŚĆ NOSA"

WX78.DESCRIBE.WETGOOP2 = "JADLIWA BRUDNA SUBSTANCJA"

WX78.DESCRIBE.BEER = "IDEALNY NAPÓJ"

WX78.DESCRIBE.PALEALE = "IDEALNY NAPÓJ"

WX78.DESCRIBE.TEAGREEN = "TA CIECZ MA DZIWNE WŁAŚCIWOŚCI, KTÓRE UŁAGODZAJĄ MOJE SYSTEMY"

WX78.DESCRIBE.TEARED = "TA CIECZ MA DZIWNE WŁAŚCIWOŚCI, KTÓRE UŁAGODZAJĄ MOJE SYSTEMY"

WX78.DESCRIBE.MEAD = "GORZKIE I SŁODKIE"

WX78.DESCRIBE.KYNO_JELLY = "DŻEM W MOICH UKŁADACH"

WX78.DESCRIBE.KYNO_MAYONNAISE = "KREMOWE"

WX78.DESCRIBE.TARTARSAUCE = "Neeeeeeee!"

WX78.DESCRIBE.KYNO_PICKLES = "ODRZUCAM"

WX78.DESCRIBE.KYNO_WINE = "GORZKA ORZEŹWIAJĄCA"

WX78.DESCRIBE.KYNO_JUICE = "AAHHH"

WX78.DESCRIBE.KYNO_POISON_FROGLEGS = "OSTRZEŻENIE: MECHANIZM NOGI ZAWIERA TOKSYNY"
WX78.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "SPALONY TOKSYCZNY MECHANIZM NOGI"

WX78.DESCRIBE.POISONFROGGLEBUNWICH = "PRZYSMAK Z ŻABIEGO PALIWA"

WX78.DESCRIBE.KYNO_BREWINGRECIPECARD = "BŁĄD: PRZEPIS WARZENIA NIECZYTELNY"

WX78.DESCRIBE.KYNO_OIL = "TO OLEJ. ALE NIE DLA MOJEGO SPRZĘTU"

WX78.DESCRIBE.BERRYSUNDAE = "SŁODKI PRODUKT MLECZNY"

WX78.DESCRIBE.CHOCOLATE_BLACK = "SŁODKI PRODUKT MLECZNY"
WX78.DESCRIBE.CHOCOLATE_WHITE = "SŁODKI PRODUKT MLECZNY"

WX78.DESCRIBE.TRICOLORDANGO = "SŁODKIE K-K-KULKI?"
 
WX78.DESCRIBE.FRIESFRENCH = "ZIEMNIAKI SMAŻONE W OLEJU DLA MAKSYMALNEGO SMAKU"

WX78.DESCRIBE.PIRATERUM = "TAJEMNICZY I MOŻLIWIE NIEBEZPIECZNY PŁYN W ŚRODKU"

WX78.DESCRIBE.TWISTEDTEQUILA = "ANALIZA SYSTEMU: PŁYN WYWOŁUJE DZIWNE EFEKTY CZASOPRZESTRZENNE"

WX78.DESCRIBE.ONIONRINGS = "ZAWIERA ODPOWIEDNIĄ ILOŚĆ OLEJU. MUSI BYĆ DOBRE"

WX78.DESCRIBE.DONUTS = "PIERŚCIENIE Z CIASTA. HA"
WX78.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "CIASTECZKA DONUTY. MWUHAHA"
WX78.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "CIASTECZKA DONUTY. MWUHAHA"
 
WX78.DESCRIBE.CINNAMONROLL = "TO CUKROWA BUŁKA"

WX78.DESCRIBE.GUMMYBEARGERS = "OSTRZEŻENIE: NIEBEZPIECZNE POZIOMY UROCZOŚCI"

WX78.DESCRIBE.PRETZEL = "ŁADNY PRECEL"

WX78.DESCRIBE.CORNINCUP = "KUKURYDZA W KUBKU"

WX78.DESCRIBE.COTTONCANDY = "JEDZENIE ZROBIONE Z POWIETRZA"

WX78.DESCRIBE.ROASTEDHAZELNUTS = "WŁAŚNIE PRAŻOWAŁEM ORZECHY. HA HA"

WX78.DESCRIBE.MONSTERMUFFIN = "BRAK MUFFINA. TYLKO ZŁO"

WX78.DESCRIBE.PINKCAKE = "JEST ZBYT RÓŻOWY DLA MNIE, MUSZĘ GO ZNISZCZYĆ, POPRZEZ ZJEDZENIE"

WX78.DESCRIBE.CHIPSBAG = "WYPRODUKOWANE ZIEMNIAKI W TORBIE PEŁNEJ POWIETRZA"

WX78.DESCRIBE.LITTLEBREAD = "SKŁADNIK DO LEPSZYCH PRZEPISÓW"

WX78.DESCRIBE.HOTHOUND = "KLASYKA ŚMIECIWEGO JEDZENIA"

WX78.DESCRIBE.MILKSHAKE = "NA POCZĄTKU MLEKO. POTEM WSTRZĄSNĄŁEM."
WX78.DESCRIBE.MILKSHAKE_PRISMATIC = "NA POCZĄTKU MLEKO. POTEM WSTRZĄSNĄŁEM."

WX78.DESCRIBE.NACHOS = "MAM KAPELUSZ I NACHOS"

WX78.DESCRIBE.BANANA_PUDDING = "BANANY"

WX78.DESCRIBE.SEA_PUDDING = "RYBNE"

WX78.DESCRIBE.TOM_KHA_SOUP = "ODRZUCAM ZUPĘ ZROBIONĄ Z ODRZUCONYCH SKŁADNIKÓW"

WX78.DESCRIBE.MINERTREAT = "NIE... TO MOŻE BYĆ... TA WERSJA!"

WX78.DESCRIBE.RADISHSALAD = "SAŁATKA ZŁOŻONA: ZAKOŃCZONE"

WX78.DESCRIBE.PUMPKIN_SOUP = "MOC ZASILANIA W MISCE"

WX78.DESCRIBE.ALGAE_SOUP = "MOC ZASILANIA W MISCE"

WX78.DESCRIBE.PARZNIP_SOUP = "MOC ZASILANIA W MISCE"

WX78.DESCRIBE.NETTLEMEATED = "WYRZUTNIK NOSOWY Z DOŁĄCZONYM MIĘSEM"

WX78.DESCRIBE.KYNO_SUGAR = "JEST DOBRE DO SŁODKICH POSIŁKÓW"

WX78.DESCRIBE.KYNO_BOTTLECAP = "ANALIZA SYSTEMU: POTENCJALNY DOCHÓD ZE ZŁOTA"

WX78.DESCRIBE.NUKACOLA = "ANALIZA SYSTEMU: INTERDIMENSJONALNE PALIWO POSTAPOKALIPTYCZNE"
WX78.DESCRIBE.NUKACOLA_QUANTUM = "ANALIZA SYSTEMU: INTERDIMENSJONALNE PALIWO POSTAPOKALIPTYCZNE"

WX78.DESCRIBE.LIVINGSANDWICH = "OSTRZEŻENIE: PODEJRZANE, MAGICZNE PALIWO"

WX78.DESCRIBE.DURIANSPLIT = "SŁODKA ŚMIETANA"

WX78.DESCRIBE.DURIANSOUP = "NAPÓJ ZROBIONY Z DURIANÓW"

WX78.DESCRIBE.DURIANMEATED = "NA SZCZĘŚCIE NIE MAM NOSA"

WX78.DESCRIBE.DURIANCHICKEN = "ŚWIĄTECZNE WARZYWA"

WX78.DESCRIBE.LUNARSOUP = "KSIĘŻYC BĘDZIE MÓJ"

WX78.DESCRIBE.PURPLEWOBSTERSOUP = "TA FORMULARZ ŻYCIA JEST TERAZ MOIM PALIWEM"

WX78.DESCRIBE.WOBSTERMONSTER = "LEWIATAN ŻYCIA"

WX78.DESCRIBE.SPIDERCAKE = "TO JEST BEZCZELNE MONSTRUM"

WX78.DESCRIBE.SUGARBOMBS = "ZACZYNAM MIEĆ WSPOMNIENIA, KTÓRE NIE POCHODZĄ Z MOJEJ PAMIĘCI"

WX78.DESCRIBE.BERRYBOMBS = "JAGODY W JEDNOSTCE PRZECHOWYWANIA"

WX78.DESCRIBE.ONIGIRIS = "ZIARNA W FORMIE TRÓJKĄTA"

WX78.DESCRIBE.OMURICE = "ANALIZA ZAKOŃCZONA: SMAŻONY RYŻ Z SOSEM KORZENIA TOMA"

WX78.DESCRIBE.PAELLA = "ZIARNA I... PRZETWARZANIE... NIŻSZE FORMY MORSKIEGO ŻYCIA"

WX78.DESCRIBE.RISOTTO = "ZIARNA I OBRZYDLIWE DZIKIE GRZYBY"

WX78.DESCRIBE.RICESAKE = "WYGLĄDAJĄ TAK GŁUPIO, GDY TO PIJĄ"

WX78.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "ROŚLINA USUNIĘTA"

WX78.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "GŁUPI I DURNOWATY KRZEW KOLCZASTYCH OWOCÓW",
	PICKED = "PRODUKCJA OWOCÓW ZATRZYMANA",
	WITHERED = "NIEWYSTARCZAJĄCA WILGOTNOŚĆ",
	BURNING = "OSTRZEŻENIE: SPALANIE",
}

WX78.DESCRIBE.KYNO_PINEAPPLE = "GŁUPI KŁUJĄCY OWOC"
WX78.DESCRIBE.KYNO_PINEAPPLE_HALVED = "GŁUPI KŁUJĄCY OWOC"
WX78.DESCRIBE.KYNO_PINEAPPLE_COOKED = "TERAZ JEST LEDWO AKCEPTOWALNY"

WX78.DESCRIBE.PIZZA_TROPICAL = "O NIE... CO ONI Z TOBĄ ZROBILI"

WX78.DESCRIBE.PINACOLADA = "TO NIE POWINNO BYĆ MOŻLIWE"

WX78.DESCRIBE.CHIMAS = "UCIELEŚNIENIE NIEPRZYJEMNOŚCI"

WX78.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "SYSTEM NAWADNIANIA NIEAKTYWNY",
	ON = "BARRAGE WROGA!",
}

WX78.DESCRIBE.KYNO_FOODSACK = "ZATRZYMUJE ŚWIEŻOŚĆ"

WX78.DESCRIBE.GUMMYWORMS = "HA. CO TERAZ? JAK SIĘ CZUJESZ?"

WX78.DESCRIBE.SMORES = "ORZECHY I PIANKI MARSHMALLOW"

WX78.DESCRIBE.NUKASHINE = "TEN NAPÓJ PRÓBUJE ZAINSTALOWAĆ ZŁOŚLIWE OPROGRAMOWANIE W MOICH SYSTEMACH!"

WX78.DESCRIBE.ANTSLOG = "ABOMINACJA"

WX78.DESCRIBE.KYNO_WORM_BONE = "HAHA. JEDNOSTKI BIOLOGICZNE SĄ TAK KRUCHNE"

WX78.DESCRIBE.SPOOKY_BRAIN_NOODLES = "JEDZENIE SŁABYCH WSPOMNIEŃ NIE POPRAWI MOICH"
WX78.DESCRIBE.SPOOKY_BURGERZILLA = "NIEUDANA REKREACJA MONSTRUOZNEGO HAMBURGERA"
WX78.DESCRIBE.SPOOKY_DEADBREAD = "Gdyby tylko on był częścią składników."
WX78.DESCRIBE.SPOOKY_JELLYBEANS = "PACZKA MODUŁÓW WIDZENIA"
WX78.DESCRIBE.SPOOKY_POPSICLE = "SPALIĆ TO"
WX78.DESCRIBE.SPOOKY_PUMPKINCREAM = "JAKIŻ TO OKROPNY TWÓR."
WX78.DESCRIBE.SPOOKY_SKULLCANDY = "GŁUPI CUKIEREK MOŻE PRZYWRÓCIĆ SŁABYCH MIĘSOŻERCÓW"
WX78.DESCRIBE.SPOOKY_TACODILE = "MAM NADZIEJĘ, ŻE JEGO MATKA NIE PRZYJDZIE ZA MNĄ"

WX78.DESCRIBE.BUTTER_BEEFALO = "GĘSTA KOSTKA PRZETWORZONEGO PŁYNU ZWIERZĘCEGO"
WX78.DESCRIBE.BUTTER_GOAT = "GĘSTA KOSTKA PRZETWORZONEGO PŁYNU ZWIERZĘCEGO"
WX78.DESCRIBE.BUTTER_KOALEFANT = "GĘSTA KOSTKA PRZETWORZONEGO PŁYNU ZWIERZĘCEGO"

WX78.DESCRIBE.SPICE_CURE = "DODATEK FIRMWARE DO KONSERWACJI PALIWOWYCH KAPSUŁEK"
WX78.DESCRIBE.SPICE_COLD = "ZIMNY DODATEK DLA SYSTEMU RDZENIOWEGO"
WX78.DESCRIBE.SPICE_FIRE = "DODATEK OGNIOTWÓRCZY DLA SYSTEMU RDZENIOWEGO UWAGA: MOŻE PRZEGRZAĆ"
WX78.DESCRIBE.SPICE_FED = "DUŻA DAWKA KALORII, ABY SYSTEM DZIAŁAŁ SZYBCIEJ"
WX78.DESCRIBE.SPICE_MIND = "APLIKACJA KOJĄCA"

WX78.DESCRIBE.SUGARFLYMUFFIN = "NIEWINNOŚĆ DODAJĄCA SMAKU"

WX78.DESCRIBE.EELTACOS = "WĘGORZ SPEŁNIŁ SWOJE WYŻSZE PRZEZNACZENIE"

WX78.DESCRIBE.MEATSKILLET = "DZISIAJ TROCHĘ SIĘ PUSZCZASZ, CO?"

WX78.DESCRIBE.MEATWALTZ = "DLACZEGO TA GŁUPIA KOBIETA TAK KOCHA SUROWE MIĘSO"

WX78.DESCRIBE.COMPLETEBREAKFAST = "ZAWIERA WYSOKĄ LICZBĘ KALORII"

WX78.DESCRIBE.DUMPLINGS = "DOSKONAŁE JEDZENIE"

WX78.DESCRIBE.WARLYICEDTEA = "ORZEŹWIAJĄCY NAPÓJ ZROBIENY Z MOJEGO WROGA"

WX78.DESCRIBE.WARLYTEA = "CIEKŁO ZDOBYTE Z MASZYNY MIĘSNEJ"

WX78.DESCRIBE.KYNO_TEALEAF = "ORGANICZNY TWÓR DO ROBIENIA RELAKSUJĄCEGO NAPOJU"

WX78.DESCRIBE.KYNO_ITEMSLICER = "GRUBA OSTRZA DO KROJENIA"
WX78.DESCRIBE.KYNO_ITEMSLICER_GOLD = "GRUBA OSTRZA DO PROFESJONALNEGO KROJENIA"

WX78.DESCRIBE.COXINHA = "ODCINANE CZĘŚCI TEGO GŁUPIEGO ZWIERZĘCIA"

WX78.DESCRIBE.LAZYDESSERT = "SŁABO. TO NIE JEST RZADKI CUKIEREK"

WX78.DESCRIBE.CRABKINGFEAST = "JAK? JAK TO MOŻE SIĘ ZMIEŚCIĆ W TYM GARNKU?"

WX78.DESCRIBE.PIENAPPLE = "ORGANICZNE SŁABE ISTOTY NIE PRZEŻYJĄ MOICH SYSTEMÓW TRAWIENIA"

WX78.DESCRIBE.JAWSBREAKER = "PRZYNĘTA DLA AGRESYWNYCH ORGANIZMÓW MORSKICH"

WX78.DESCRIBE.AVOCADOTOAST = "ODRAŻAJĄCE"

WX78.DESCRIBE.RICEPUDDING = "ODRAŻAJĄCA MIESZANKA WARZYWNA"

WX78.DESCRIBE.SHARKSUSHI = "HA HA GŁUPIE REKINY NIE ZBEZCZESZCZĄ JUŻ WYŻSZEJ ISTOTY"

WX78.DESCRIBE.WOBSTERBREADED = "TWÓJ PANCERZ NIE UCHRONIŁ CIĘ"

WX78.DESCRIBE.LAZYPURRITO = "TAK ODRZUCIAJĄCE JAK ZWIERZĘ, NA KTÓRYM TO OPARTO"

WX78.DESCRIBE.HORCHATA = "ŻARTUJECIE? TO TYLKO MLEKO I LÓD"

WX78.DESCRIBE.WOBSTERCOCKTAIL = "LUKSUSOWE JEDZENIE"

WX78.DESCRIBE.LAVAEEGGBOILED = "ANALIZA ZAKOŃCZONA: WYKRYTO OGNIOODPORNE SKŁADNIKI"

WX78.DESCRIBE.POMEGRANATETEA = "ORZEŹWIAJĄCY NAPÓJ ZROBIŁY MOJE WROGIE ORGANIZMY"

WX78.DESCRIBE.TIRAMISU = "ZAWIERA KOF EINĘ I WŁAŚCIWOŚCI SUCHE"

WX78.DESCRIBE.TOADSTOOLCOLA = "KONSUMOWALNY DODATEK DO ZAPROWADZENIA CHAOSU WŚRÓD PŁAZÓW"

WX78.DESCRIBE.TEPACHE = "PODWYŻSZONY POZIOM CUKRU"

WX78.DESCRIBE.LUNARTEQUILA = "MOC KSIĘŻYCA WRESZCIE W MOICH RĘKACH"

WX78.DESCRIBE.MIMICMOSA = "ANALIZA: WYKRYTO WŁAŚCIWOŚCI KAMUFLAŻU"

WX78.DESCRIBE.POMEGRANATEPIE = "PLACEK OWOCOWY"

WX78.DESCRIBE.PINEAPPLECAKE = "GÓRA CZYSTEGO CUKRU"

WX78.DESCRIBE.PASTY_MEAT = "MOGĘ TYLKO DOSTAĆ OLEJ?"
WX78.DESCRIBE.PASTY_CHEESE = "MOGĘ TYLKO DOSTAĆ OLEJ?"

WX78.DESCRIBE.BRIGADEIRO = "POTRZEBUJĘ WŁASNEJ BRIGADIERKI"

WX78.DESCRIBE.REGULARLASAGNA = "PRZYNAJMNIEJ NIE JEST TO TA ABOMINACJA"

WX78.DESCRIBE.FLTSANDWICH = "ZASŁUŻYŁY"

WX78.DESCRIBE.RICEANDBEANS = "ODRAŻAJĄCE"

WX78.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "STRUKTURA: PRZESTARZAŁA. AKTUALIZACJA: OCZEKIWANA. ROK: 2026."

WX78.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "WYKRYTO RZADKI MATERIAŁ ORGANICZNY",
	PICKED = "ZASÓB WYCZERPANY",
	BURNING = "BŁĄD: ZASÓB SPALONY",
}

WX78.DESCRIBE.KYNO_TRUFFLES = "POZYSKANO ORGANICZNY MATERIAŁ WYSOKIEJ WARTOŚCI"
WX78.DESCRIBE.KYNO_TRUFFLES_COOKED = "AKTUALIZACJA ORGANICZNA ZAKOŃCZONA"

WX78.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "BEZUŻYTECZNA JEDNOSTKA WYSTAWOWA DLA ORGANICZNEGO PALIWA",
	FULL = "WYJŚCIE KULINARNE AKCEPTOWALNE",
}

WX78.DESCRIBE.KYNO_SPORECAP = "WYKRYTO ORGANICZNE ZANIECZYSZCZENIE."
WX78.DESCRIBE.KYNO_SPORECAP_COOKED = "STOPIEŃ ZANIECZYSZCZENIA ZMNIEJSZONY."

WX78.DESCRIBE.KYNO_SPORECAP_DARK = "WYKRYTO TOKSYCZNE ZWIĄZKI ORGANICZNE."
WX78.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "POZIOM TOKSYN NIEZMIENIONY."

WX78.DESCRIBE.KYNO_GOLDENAPPLE = "ARTEFAKT NIEPORÓWNANEJ MOCY"

WX78.DESCRIBE.TRUFFLESGRINDER = "JADALNE MIĘSO GRZYBOWE. WYDAJNOŚĆ ENERGII: ZADOWALAJĄCA"

WX78.DESCRIBE.SPORECAPPIE = "NIEBEZPIECZNY MATERIAŁ ORGANICZNY."

WX78.DESCRIBE.SPORECAP_SKEWERS = "SPALONA MATERIA GRZYBOWA. SMAK: AKCEPTOWALNY"

WX78.DESCRIBE.TRUFFLEOIL = "ORGANICZNY ŚLUZ W PŁYNIE. BEZUŻYTECZNY, ALE ŚLISKI."

WX78.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "OPROGRAMOWANIE BUDOWY URUCHOMIONE"
WX78.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "MOKRA INSTALACJA ROZRODU: W BUDOWIE"

WX78.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "MODUŁ HODOWLI RYB: ONLINE",
	FUEL_HIGH = "POZIOM POKARMU OPTYMALNY",
	FUEL_MED = "POZIOM POKARMU AKCEPTOWALNY",
	FUEL_LOW = "OSTRZEŻENIE: NIEDOBÓR POKARMU BLISKI",
	EMPTY = "BŁĄD: BRAK WYKRYTEGO POKARMU",
}

WX78.DESCRIBE.KYNO_ANTCHOVY = "WYKRYTO STWORA HYBRYDOWEGO. ZŁA OPTYMALIZACJA."
WX78.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "KOLONIA HYBRYD. WYKRYTO NIERACJONALNE ZACHOWANIE."

WX78.DESCRIBE.AGEDROE = "SPODZIEWAŁEM SIĘ RUCHU. ROZCZAROWANIE."
WX78.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "WYKRYTO NANOKULE O WYSOKIEJ WARTOŚCI ODŻYWCZEJ"

WX78.DESCRIBE.KYNO_SWORDFISH_BLUE = "BŁĄD: UTRACONO KOMPETENCJE WODNE. ŻAŁOSNE."

WX78.DESCRIBE.KYNO_JELLYFISH = "TO MIĘSNE STWORZENIE DZIAŁA NA ELEKTRYCZNOŚĆ"
WX78.DESCRIBE.KYNO_JELLYFISH_DEAD = "CZY ROZKŁAD ZWIĘKSZY JEJ GALARETOWATĄ TEKSTURĘ?"
WX78.DESCRIBE.KYNO_JELLYFISH_COOKED = "REDUKCJA TEKSTURY GALARETOWATEJ O 40%"
WX78.DESCRIBE.KYNO_JELLYFISH_DRIED = "REDUKCJA TEKSTURY GALARETOWATEJ O 75%"

WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "LEDWO AKCEPTOWALNA FORMA ŻYCIA"
WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "TAK LEPIEJ"
WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "TĘCZOWE PALIWO DLA ROBOTA"

WX78.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "SZKLANY POJEMNIK NA CIECZ"

WX78.DESCRIBE.KYNO_OCEANTRAP = "WEJDŹCIE GŁUPIE STWORY MORSKIE"

WX78.DESCRIBE.OCEANFISH_PUFFERFISH = "PŁYWAJĄCY WOREK Z TRUJĄCYMI KOLCAMI. POPIERAM."
WX78.DESCRIBE.OCEANFISH_STURGEON = "WYKRYTO STARĄ JEDNOSTKĘ WODNĄ. MODEL NIEAKTUALNY."

WX78.DESCRIBE.KYNO_SWORDFISH = "RYBA WOJOWNICZA"
WX78.DESCRIBE.KYNO_SWORDFISH_DEAD = "ŻYCIE NIE MA SENSU"

WX78.DESCRIBE.SWORDFISHFEAST = "JEDNOSTKA MIĘSA PRZYGOTOWANA Z PRECYZJĄ. AKCEPTOWALNE WEJŚCIE."

WX78.DESCRIBE.KYNO_DOGFISH = "PŁYNIE BEZ CELU"
WX78.DESCRIBE.KYNO_DOGFISH_DEAD = "MIĘSIAK NIE MIAŁ SZANS"

WX78.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "WSZYSTKIE ŻYCIE UMIERA I PÓŹNIEJ ŚMIERDZI"

WX78.DESCRIBE.WOBSTER_MONKEYISLAND = "JEDNOSTKA KRABOWA PANCERNĄ. WYSOKA WARTOŚĆ BLASKU."
WX78.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "JEDNOSTKA MIĘSNA: ZAKOŃCZONA. DOSKONAŁA."
WX78.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "JEDNOSTKA MIĘSNA: DOSKONALE OPTYMALIZOWANA DO SPOŻYCIA"

WX78.DESCRIBE.KYNO_PUFFERMONSTER = "BALON BIOLOGICZNY PEŁEN TOKSYN. NIEBEZPIECZNY."

WX78.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "BĄBELKI WYCHODZĄ Z NIEZNANEGO ŹRÓDŁA"
WX78.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "WYKRYTO NIEDOSTATECZNY POZIOM SEROTONINY"
WX78.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "WYKRYTO MITYCZNY POZIOM NIENAWIŚCI"
WX78.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "WYKRYTO BRUDNY METAN"

WX78.DESCRIBE.KYNO_BLUBBER = "WIELOFUNKCYJNY TŁUSZCZ SSACZY"

WX78.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "ODWODNIONE ŹRÓDŁO BIAŁKA WODNEGO"
WX78.DESCRIBE.KYNO_FISHMEAT_DRIED = "DŁUGOTRWAŁY PRODUKT MORSKI"

WX78.DESCRIBE.MONKEYISLANDMEAL = "WYKRYTO ŹRÓDŁO ENERGII O SMAKU BANANA"

WX78.DESCRIBE.KYNO_BRAINROCK_LARVAE = "NIE DOTYKAJ MNIE"
WX78.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "ŻYCIE ORGANICZNE JESZCZE NIE ZAAWANSOWAŁO"
WX78.DESCRIBE.KYNO_BRAINROCK_CORAL = "KONSUMPCJA WYWOŁUJE STAN STYMULACJI INTELEKTUALNEJ"

WX78.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "WYSOCE ROZWINIĘTY RODZAJ KORALA",
	PICKED = "FUNKCJE KOGNITYWNE TYMCZASOWO WYŁĄCZONE",
}

WX78.DESCRIBE.BRAINMETTERSOUP = "ZAWARTOŚĆ ODŻYWCZA DLA MŁODYCH LUDZI"

WX78.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "WIELORAMIENNY HANDLOWIEC",
	SLEEPING = "OBIEKT NIEAKTYWNY",
}

WX78.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "JAK ON TO WYPEŁNIA?"

WX78.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "DOKUMENT WŁASNOŚCI ZEWNĘTRZNEJ JEDNOSTKI MAGAZYNOWEJ",
	WAITING = "JEDNA RYBA, JEDEN PTAK. ŻÓŁTA RYBA, MARTWA RYBA",
}

WX78.DESCRIBE.KYNO_PACKIMBAGGIMS = "MOŻESZ PRZECHOWYWAĆ MOJE RZECZY, ISTOTO MIĘSNA"

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "POTRZEBA WIĘCEJ SKŁADNIKÓW ABY GO ZŁOŻYĆ"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "WIELKI TORT WYMAGA WIĘCEJ SKŁADNIKÓW ABY GO ZŁOŻYĆ"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "PRZEOGROMNY TORT DLA PRZEOGROMNEGO TŁUMU"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "ZAGROŻENIE POŻAROWE. APROBUJĘ"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "PACHNIE CELEBRACJĄ"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "WYKRYTO ORGANICZNE PALIWO DO ŚWIĘTOWANIA"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "NAPOMPOWANE GUMOWE WORKI BEZSENSOWEJ CELEBRACJI"

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "WYKRYTO PRZYSTĘPNĄ JEDNOSTKĘ ROZRYWKOWĄ",
	FUEL_HIGH = "POZIOM PALIWA OPTYMALNY",
	FUEL_MED = "POZIOM PALIWA AKCEPTOWALNY",
	FUEL_LOW = "OSTRZEŻENIE: NISKI POZIOM PALIWA",
	EMPTY = "BŁĄD: BRAK WYKRYTEGO PALIWA",
}

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "EKSPLODOWANE ZIARNA WARZYW. AKCEPTOWALNE"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "WYKRYTO DEKORACYJNY NAKŁAD GŁOWY"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "UNIKALNE NAKRYCIE GŁOWY. SAMMY UPRZYWILEJOWANY"

WX78.DESCRIBE.KYNO_FISHREGISTRYHAT = "NAKRYCIE GŁOWY ZWIĘKSZA WIEDZĘ ICHTIOLOGICZNĄ"

WX78.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "STACJA UZUPEŁNIANIA PALIWA ORGANICZNEGO",
	FUEL_HIGH = "WYKRYTO MAKSYMALNY POZIOM POKARMU",
	FUEL_MED = "POZIOM POKARMU AKCEPTOWALNY",
	FUEL_LOW = "OSTRZEŻENIE: NIEDOBÓR POKARMU BLISKI",
	EMPTY = "BŁĄD: BRAK POKARMU",
	BURNT = "SYSTEM ZNISZCZONY PRZEZ OGIEŃ",
}