-- Auto-generated from data/recipes_cookpot_warly.json
return {
    "musselbouillabaise",
    "sweetpotatosouffle",
    "gorge_meat_stew",
    "gorge_cheeseburger",
    "gorge_pizza",
    "gorge_meat_wellington",
    "gorge_trifle",
    "bubbletea",
    "frenchonionsoup",
    "jellybean_sanity",
    "jellybean_hunger",
    "jellybean_super",
    "berrysundae",
    "cinnamonroll",
    "milkshake_prismatic",
    "nachos",
    "tom_kha_soup",
    "risotto",
    "meatskillet",
    "warlyicedtea",
    "warlytea",
    "lazydessert",
    "lavaeeggboiled",
    "tiramisu",
}
