-- This is a template for character strings. Replace "GENERIC" with your character's name.

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_COFFEEBUFF_START = "Isso me ajuda a ficar acordada."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_COFFEEBUFF_END = "Vou sentir falta da cafeína."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_HASTEBUFF_START = "Posso ler livros duas vezes mais rápido agora."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_HASTEBUFF_END = "Queria poder usar mais dessas \"mãos jovens\"."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_POPBUFF_START = "(buurp!) Oh, querido, me perdoe."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_POPBUFF_END = "Preciso beber com moderação da próxima vez."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FROGBUFF_START = "Curioso... cheiro de anfíbio."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FROGBUFF_END = "O aroma estranho desapareceu."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_PIRATEBUFF_START = "Interessante... sinto-me mais ousada."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_PIRATEBUFF_END = "Voltei ao meu estado normal."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FREEZEBUFF_START = "O gelo não me afeta mais."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FREEZEBUFF_END = "De volta à minha rotina habitual."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FIREBUFF_START = "O fogo não pode mais me prejudicar."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FIREBUFF_END = "De volta à minha rotina habitual."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FISHINGBUFF_START = "A pesca nos espera!"
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FISHINGBUFF_END = "Pescar requer paciência, não dá para acelerar mais."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "Acalmando a mente."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "Pensamento de volta ao normal."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_EATERBUFF_START = "Sinto uma mudança no meu sistema digestivo."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_EATERBUFF_END = "A sensação estranha no estômago sumiu."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_WORMBUFF_START = "Fica mais fácil caçar vermes."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_WORMBUFF_END = "Retirada por enquanto, podemos lutar depois."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_CRABBUFF_START = "Fica mais fácil caçar caranguejos."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_CRABBUFF_END = "Retirada por enquanto, podemos lutar depois."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(argh!) Oh, céus, perdão."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "Preciso beber com moderação da próxima vez."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "Fui iluminada."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "A lua dorme, por enquanto."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_STEALTHBUFF_START = "Estou mais discreta do que nunca."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_STEALTHBUFF_END = "Parece que não sou mais invisível."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FEARBUFF_START = "O medo perdeu seu domínio sobre mim."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FEARBUFF_END = "O medo retorna, inevitável como sempre."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "Notável! Uma fruta transmutadora de potência extraordinária."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "Ah, os efeitos do encantamento se dissiparam."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "Fascinante! Minha presença atrai porcos companheiros."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "Lamentavelmente, meus companheiros suínos se dispersaram."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "Fascinante! Uma resistência química temporária!"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "Uma resistência admirável às toxinas! Impressionante."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "Ah, o efeito dissipou. Hora de cautela novamente."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "Ah, minha mente está transbordando de possibilidades!"
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "Ah, bem, ninguém pode permanecer inspirado para sempre."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "Notável. As apídeas parecem totalmente dóceis."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "A docilidade delas acabou. Atenção redobrada."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "Minha vitalidade está claramente melhor."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "Vitalidade retornou ao normal."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "Minha capacidade estomacal parece ampliada."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "Estômago retornou ao tamanho padrão."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "Minha capacidade mental está muito melhor."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "Minha cognição voltou ao normal."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "Fascinante. Energias estão reforçando meu corpo."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "Uma pena. Meu reforço se dissipou."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "Precisa de algo diferente."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "Não. Acho que ele mencionou wobsters."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "Preciso esperar um pouco para ela crescer."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "Não pertence aqui."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_POTHANGER_FAIL = "Precisa de uma panela de cozinha."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_CASSEROLE_FAIL = "Oh céus, precisa de uma caçarola para cozinhar."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "Um fim rápido e necessário. A natureza é pragmática."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "Parece estar completamente esgotado."

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "Ah, as correntes apagaram todos os rastros. Que pena."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "A chuva apagou completamente as evidências."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "Ah, parece que nossa presa está próxima!"

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "Uma esplêndida conquista confeiteira!"

STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_FISH_RESEARCHED = "Fascinante. Esta espécie oferece novos conhecimentos."
STRINGS.CHARACTERS.WICKERBOTTOM.ANNOUNCE_KYNO_ROE_RESEARCHED = "As ovas possuem propriedades biológicas notáveis."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ROE = "O primeiro estágio do ciclo de vida do peixe."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ROE_COOKED = "O primeiro e o último estágio deste ciclo de vida."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SHARK_FIN = "A barbatana dorsal funciona como estabilizador aquático."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BEANBUGS = "Meu Deus! Uma Fabaceae ambulante!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BEANBUGS_COOKED = "Tenho certeza que contém bastante proteína."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_GUMMYBUG = "Um gastrópode que nunca vi antes."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_GUMMYBUG_COOKED = "Tenho dúvidas sobre seu valor nutricional."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WHEAT = "Triticum aestivum fresco."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WHEAT_COOKED = "Triticum aestivum cozido."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FLOUR = "Posso preparar algumas receitas com isso."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SPOTSPICE = "Processado e pronto para cozinhar."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SAP = "Esta seiva tem conteúdo de glicose extraordinário."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SAP_SPOILED = "Não é mais de qualidade alimentar."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SYRUP = "Um adoçante."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COFFEEBEANS = "Muito ricos em cafeína."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "Ahh, a torra cheira delicioso."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_KYNO_COFFEEBUSH = "Gênero Coffea."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COFFEEBUSH = "Gênero Coffea."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_KYNO_SPOTBUSH = "Não estou familiarizada com essa espécie de planta."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SPOTBUSH = "Não estou familiarizada com essa espécie de planta."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SPOTSPICE_LEAF = "Passa no teste universal de comestibilidade."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MUSSEL = "Clamus wetus. Muito nutritivo."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MUSSEL_COOKED = "Não coma a concha."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HUMANMEAT = "A autólise dará lugar à putrefação em breve."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HUMANMEAT_COOKED = "A metamioglobina dá sua cor única."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HUMANMEAT_DRIED = "Carne humana seca por osmose."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COFFEE = "Adoro uma xícara de café com um bom livro."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BISQUE = "Exatamente o que eu precisava."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.JELLYOPOP = "Me lembra minha juventude. Mais ou menos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SHARKFINSOUP = "Talvez tenha mexido num ecossistema delicado para isso."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TROPICALBOUILLABAISSE = "Um toque inventivo em prato tradicional de Marselha."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MUSSELBOUILLABAISE = "Sopa de mexilhão."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SWEETPOTATOSOUFFLE = "Muito saboroso."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FEIJOADA = "Um banquete entomofágico!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GUMMY_CAKE = "Bastante gomoso."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HARDSHELL_TACOS = "Tenho quase certeza de que essas não são cascas de taco normais."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ICEDTEA = "Revigorante."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NETTLELOSANGE = "Nutrição medicinal."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SNAKEBONESOUP = "Um caldo robusto."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.STEAMEDHAMSANDWICH = "Preparada para um almoço inesquecível."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEA = "Me dê chá e um bom livro."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUBBLETEA = "Revigorante."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FRENCHONIONSOUP = "Um caldo robusto."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SLAW = "Nicoise, tão nutritivo!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LOTUSBOWL = "Os benefícios à saúde são numerosos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.POI = "Nunca vi isso nos meus livros de culinária."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.JELLYBEAN_HUNGER = "Doces, emulsificados com cera de abelha."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.JELLYBEAN_SUPER = "Doces, emulsificados com cera de abelha."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.JELLYBEAN_SANITY = "Doces, emulsificados com cera de abelha."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BOWLOFGEARS = "Acho que é invenção do WX."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LONGPIGMEAL = "Sem palavras."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CUCUMBERSALAD = "Cheia de nutrientes!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WILDWHEAT = "Um agrupamento de caules gramíneos."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_KYNO_WILDWHEAT = "Um agrupamento de caules gramíneos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEALGRINDER = "Para moer mecanicamente nossos ingredientes."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_BREAD = "Eu poderia transformar isso em algo bom."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_SWEET_CHIPS = "Uma maravilha culinária."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_VEGETABLE_SOUP = "Isso deve te encher rápido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_JELLY_SANDWICH = "Um toque de geleia e voilà!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_FISH_STEW = "O prato perfeito."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_MEAT_STEW = "Não é bem como a mamãe fazia, mas cheira superbamente!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_ONION_CAKE = "Este tipo de bolo também pode ser apreciado."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_POTATO_PANCAKES = "Panquecas são boas para a primeira refeição da manhã."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_POTATO_SOUP = "Exatamente o que eu precisava."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_FISHBALL_SKEWERS = "Bolinho de peixe artesanal preso no palito."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_MEAT_SKEWERS = "Pedaços de carne presos no palito."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_STONE_SOUP = "Exatamente o que eu precisava."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CROQUETTE = "Um bom prato de entrada."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_ROAST_VEGETABLES = "Prato saudável e revigorante."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_MEATLOAF = "Um bom rolo de carne."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CARROT_SOUP = "Exatamente o que eu precisava."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_FISHPIE = "Torta feita com peixe, embora não muito charmosa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_FISHCHIPS = "Uma mistura clássica de peixe e vegetais."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_MEATPIE = "Uma boa torta, devo dizer."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_SLIDERS = "Comumente usados como fast food ou entrada."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_JELLY_ROLL = "Rolinhos de geleia."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CARROT_CAKE = "Um bom bolo de cenoura, muito nutritivo."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_GARLICMASHED = "Uma mistura de batatas e alho, muito nutritiva."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_GARLICBREAD = "Combina bem com outros pratos."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_TOMATO_SOUP = "Exatamente o que eu precisava."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_SAUSAGE = "Uma variedade de pedaços de carne reunidos."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CANDIEDFISH = "A doçura do xarope melhora ainda mais."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_STUFFEDMUSHROOM = "Champignons com vegetais formando um recheio."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_BRUSCHETTA = "Um prato italiano muito especial."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_HAMBURGER = "Almoço clássico."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_FISHBURGER = "Almoço clássico."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_MUSHROOMBURGER = "Almoço clássico."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_FISH_STEAK = "O prato perfeito."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CURRY = "Um prato popular ao redor do mundo."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_SPAGHETTI = "Um monte de carne processada. Quem sabe o que foi colocado nisso."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_POACHEDFISH = "Um salmão escalfado com perfeição."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_SHEPHERD_PIE = "Recheio de carne de ovelha."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CANDY = "Não ligo muito para doces, mas... tempos desesperados."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_BREAD_PUDDING = "Um pedaço de pão doce."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_BERRY_TART = "Uma boa combinação de frutas e doces."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_MACARONI = "Um prato simples, mas satisfatório."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_BAGEL_AND_FISH = "Este salmão é da mais alta qualidade."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_GRILLED_CHEESE = "Uma opção popular de café da manhã em alguns lugares."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CREAMMUSHROOM = "Uma iguaria para amantes de sopas."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_MANICOTTI = "Um tipo de massa na culinária ítalo-americana."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CHEESEBURGER = "Almoço clássico."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_FETTUCCINE = "O creme compensa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_ONION_SOUP = "Melhor lavar a boca depois disso."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_BREADED_CUTLET = "Esplêndido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CREAMY_FISH = "Um bom creme com salmão."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_PIZZA = "Clássico."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_POT_ROAST = "A espera vale a pena."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CRAB_CAKE = "Precisa de algumas melhorias."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_STEAK_FRITES = "O bife combina muito bem com as fritas."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_SHOOTER_SANDWICH = "Um clássico sanduíche de bife da Inglaterra."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_BACON_WRAPPED = "Seria melhor com alguns ovos."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CRAB_ROLL = "Uma iguaria."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_MEAT_WELLINGTON = "Uma recriação perfeita do Meat Wellington."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CRAB_RAVIOLI = "Uma iguaria."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CARAMEL_CUBE = "Muita bala pode fazer mal."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_SCONE = "Isso é incrivelmente delicioso."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_TRIFLE = "Isso é incrivelmente delicioso."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GORGE_CHEESECAKE = "Ah, cheesecake. Uma boa sobremesa da tarde."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUCKYOUGLERMZ = "Isso é simplesmente..."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ALOE = "Babosa. Uma planta com muitos usos."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ALOE_COOKED = "Sabe-se que possui propriedades laxativas."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ALOE_GROUND = "Babosa. Uma planta com muitos usos."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ALOE_SEEDS = "Não pode começar a crescer até ser plantada, querida."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "Não pode começar a crescer até ser plantada, querida."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_ALOE = "Babosa. Uma planta com muitos usos."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ALOE_OVERSIZED = "Babosa. Uma planta com muitos usos."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "Que resultado terrível."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER = "É uma espécie comestível de pepino."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER_COOKED = "Com certeza não melhorou a textura."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER_GROUND = "É uma espécie comestível de pepino."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER_SEEDS = "Não pode começar a crescer até ser plantada, querido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "Não pode começar a crescer até ser plantada, querido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "É uma espécie comestível de pepino."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "É uma espécie comestível de pepino."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "Que resultado terrível."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_RADISH = "Da família Brassicaceae, creio eu."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_RADISH_COOKED = "Um pouco picante para meu gosto."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_RADISH_GROUND = "Da família Brassicaceae, creio eu."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_RADISH_SEEDS = "Não pode crescer até ser plantada, querida."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "Não pode crescer até ser plantada, querida."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_RADISH = "Da família Brassicaceae, acredito eu."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_RADISH_OVERSIZED = "Da família Brassicaceae, acredito eu."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "Que resultado terrível."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FENNEL = "Foeniculum vulgare."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FENNEL_COOKED = "Foeniculum vulgare."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FENNEL_GROUND = "Foeniculum vulgare."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FENNEL_SEEDS = "Não pode crescer até ser plantada, querido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "Não pode crescer até ser plantada, querido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "Foeniculum vulgare."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FENNEL_OVERSIZED = "Foeniculum vulgare."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "Que resultado terrível."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO = "Kumara!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "Kumara grelhada."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "Kumara!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "Não pode começar a crescer até ser plantada, querido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "Não pode começar a crescer até ser plantada, querido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "Kumara!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "Kumara!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "Que resultado terrível."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP = "Pastinaca sativa. Comestível e deliciosa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_COOKED = "Pastinaca sativa. Comestível e deliciosa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_EATEN = "Pastinaca sativa. Comestível e deliciosa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_GROUND = "Pastinaca sativa. Comestível e deliciosa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_BIG = "Uma Pastinaca sativa gigante, curioso."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_SEEDS = "Não pode crescer até ser plantada, querido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "Não pode crescer até ser plantada, querido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "Pastinaca sativa. Comestível e deliciosa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "Pastinaca sativa gigante, curiosa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "Que resultado terrível."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TURNIP = "Raiz comestível de Brassica rapa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TURNIP_COOKED = "Assar Brassica rapa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TURNIP_GROUND = "Raiz comestível de Brassica rapa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TURNIP_SEEDS = "Não pode começar a crescer até ser plantada, querida."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "Não pode começar a crescer até ser plantada, querida."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "Raiz comestível de Brassica rapa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TURNIP_OVERSIZED = "Raiz comestível de Brassica rapa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "Que resultado terrível."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_RICE = "Combina bem com pratos simples."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_RICE_COOKED = "Combina bem com pratos simples."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_RICE_SEEDS = "Não pode começar a crescer até ser plantada, querido(a)."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "Não pode começar a crescer até ser plantada, querido(a)."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_RICE = "Raiz comestível de Oryza sativa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_RICE_OVERSIZED = "Raiz comestível de Oryza sativa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "Que resultado terrível."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SEEDS_KIT = "Um prático pacotinho de sementes de vegetais."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_LIMPETROCK = "Este rochedo é lar de vários gastrópodes."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_LIMPETS = "Patella vulgata."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_LIMPETS_COOKED = "Patella vulgata cozida."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_LOTUS_OCEAN = "Nelumbo nucifera, bastante bonita."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_LOTUS_ROOT = "Sempre quis me tornar uma horticultora aquática."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_LOTUS_FLOWER = "A flor de Nelumbo nucifera. É bastante inspiradora."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "Os benefícios à saúde são inúmeros."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SEAWEEDS_OCEAN = "Algas marinhas."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SEAWEEDS = "Confesso que não sou muito de ficologia."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SEAWEEDS_COOKED = "Muito rico em proteínas."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SEAWEEDS_DRIED = "Eu sequei as algas."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SEAWEEDS_ROOT = "Sempre quis ser um horticultor aquático."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TAROROOT_OCEAN = "Colocasia esculenta!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TAROROOT_ROOT = "Sempre quis me tornar uma horticultora aquática."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TAROROOT = "Colocasia esculenta!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TAROROOT_COOKED = "Apresento: Colocasia esculenta cozida."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WATERYCRESS_OCEAN = "Nasturtium officinale!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WATERYCRESS_ROOT = "Sempre quis me tornar uma horticultora aquática."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WATERYCRESS = "Nasturtium officinale!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WATERYCRESSBOWL = "Cheira mal, mas é bem nutritivo."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SALT = "Cloreto de sódio. Também conhecido como sal de cozinha."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "Para colher moluscos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CATFOOD = "Um lanche para gatos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KATFOOD = "Um lanche para gatos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BANANATREE = "O sol ajudará os frutos a crescerem melhor."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BANANA = "Uma Musa paradisiaca Linn!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BANANA_COOKED = "Um pouco melhor."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_KOKONUTTREE = "Gostaria de sentar embaixo dela com um bom livro."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_KOKONUT = "Que semente enorme!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_KOKONUT_HALVED = "Consegui superar suas defesas externas."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_KOKONUT_COOKED = "Polpa de coco, bastante deliciosa."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BOWLOFPOPCORN = "Milho estourado!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FIGJUICE = "Revigorante."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COCONUTWATER = "Revigorante."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.EYEBALLSPAGHETTI = "Não acho que esta comida seja segura."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FORGETMELOTS_SEEDS = "Não pode começar a crescer até ser plantada, querido."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FIRENETTLES_SEEDS = "Não pode começar a crescer até ser plantada, querido."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TILLWEED_SEEDS = "Não pode começar a crescer até ser plantada, querido."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FLOATILIZER = "Um balde de fezes de animais marinhos. Fétido."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TWIGGYNUTS = "Nozes de uma árvore cheia de galhos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_REPAIRTOOL = "Prolonga a vida das coisas."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_KOI = "Parece ser uma subespécie de Cyprinus carpio."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_KOI_COOKED = "Parece ser uma subespécie de Cyprinus carpio."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TROPICALFISH = "Que colorido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TROPICALFISH_COOKED = "Uma iguaria tropical."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_NEONFISH = "Parente próximo do Paracheirodon innesi."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_NEONFISH_COOKED = "Um primo do Paracheirodon innesi, pronto para o jantar."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_GROUPER = "Parte da família Epinephelinae."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_GROUPER_COOKED = "Comer peixe cru não seria seguro."
 
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PIERROTFISH = "Hmm... Não consigo identificar esta espécie."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PIERROTFISH_COOKED = "Peixes hospedam todo tipo de parasitas, sabia?"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SALMONFISH = "Mmmm! Oncorhynchus nerka!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SALMONFISH_COOKED = "Oncorhynchus nerka grelhado."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TURF_PINKPARK = "Bem bonito."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TURF_STONECITY = "O chão. Você pisa nele."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TURF_FIELDS = "O chão. Você pisa nele."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TURF_TIDALMARSH = "O chão. Você pisa nele."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SALTRACK_INSTALLER = "Devemos colocá-lo perto da fonte de sódio."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "Um simples instrumento para extrair seiva das árvores."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "Para capturar criaturas marinhas."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SERENITYISLAND_SHOP = "Sua sociedade tem papéis sociais muito rígidos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SUGARTREE_BUD = "Um broto misturado com açúcar."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SUGARTREE_FLOWER = "É uma flor silvestre, não conheço a espécie."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "É uma flor silvestre, não conheço a espécie."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SUGARTREE_PETALS = "É uma flor silvestre, não conheço a espécie."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PEBBLECRAB = "Gostaria de estudar sua concha mais de perto."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CRABMEAT = "Carne crua de Paralithodes."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CRABMEAT_COOKED = "Não apresenta mais risco de salmonela."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CRABMEAT_DRIED = "Carne crua de Paralithodes."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CRABKINGMEAT = "Carne crua de Paralithodes."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "Carne de Paralithodes cozida."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "Carne crua de Paralithodes."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SLAUGHTERTOOL = "Macabro."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CHICKEN2 = "Um Gallus Gallus domesticado."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CHICKEN_EGG = "Talvez esteja fertilizado."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "Se ao menos eu tivesse um pouco de torrada."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CHICKENHOUSE = "Um recinto simples adequado para aves domésticas."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "Está aqui há tanto tempo."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_KIT = "Este kit deve nos ajudar a montar a cozinha."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SYRUP = "Precisa de seiva."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "Precisa de seiva."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_BIG_POT = "Uma panela maior demora mais para ferver."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_BIG = "Uma panela maior demora mais para ferver."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "Hmm, o que faremos a seguir?"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SMALL = "Hmm, o que faremos a seguir?"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_GRILL = "Talvez um churrasco seja apropriado."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "Precisa estar no chão."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "Menor que o normal, mas serve."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "Preciso colocá-la em algum lugar para usar."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_ELDER = "Precisa de seiva."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "Todas as peças são necessárias para construir um forno totalmente funcional."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "Adoro uma boa caçarola."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "Suficiente para uma pessoa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_OVEN = "É melhor para assar doces."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "É melhor para assar doces."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "É melhor para assar doces."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ROCKFLIPPABLE = "Os insetos mais interessantes estão debaixo das pedras."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ROCKFLIPPABLE_CAVE = "Os insetos mais interessantes estão debaixo das pedras."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "Quanto tempo isso deve ter flutuado no mar?"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SUGARFLY = "Um lepidóptero rosa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SUGARFLYWINGS = "Asas de uma sugarfly capturada"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WATERY_CRATE = "Me pergunto há quanto tempo está à deriva."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TUNACAN = "Peixe preservado."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TUNACAN_OPEN = "Peixe preservado."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CANNEDFOOD = "Comida preservada."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "Comida preservada."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_POP = "Uma lata de bebida gaseificada."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MYSTERYMEAT = "Vida marinha regurgitada. Nada para mim, obrigado."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BOTTLE_SOUL = "Uma alma de algo, presa dentro de uma garrafa."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SOULSTEW = "Uma alma de algo, agora comida."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FORTUNECOOKIE = "Supostamente revela a sorte de alguém."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HORNOCUPIA = "Um símbolo de abundância."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CHEESE_YELLOW = "Queijo feito a partir de leite animal."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CHEESE_WHITE = "Queijo branco feito a partir de leite animal."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CHEESE_KOALEFANT = "Queijo feito a partir do leite de coalefante."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MILK_BOX = "Uma caixa comum de leite, produzida em grande escala em fábricas."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WATERCUP = "Um pouco de água."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HONEYJAR = "O resultado do trabalho extremamente bom das abelhas."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CRAB_ARTICHOKE = "Um bom prato de caranguejo com vegetais."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PEPPERROLLS = "Só um pouco picante para mim!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SAPHEALER = "O conteúdo deve fazer um antídoto muito útil."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_OCEAN_WRECK = "Este navio foi pego por uma tempestade. Agora pertence ao mar."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_GHOST_PIRATE = "Atividade paranormal marítima."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BUCKET_EMPTY = "Um balde de madeira para ajudar nas tarefas diárias."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BUCKET_METAL = "Um balde mais resistente para tarefas diárias."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BUCKET_WATER = "Um simples recipiente metálico cheio de di-hidrogênio monóxido."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MILK_BEEFALO = "Tentador!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MILK_KOALEFANT = "Tentador!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_CAP_DRIED = "Um cogumelo seco para alcançar mais níveis de sabor."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PLANTMEAT_DRIED = "Salgada, mas satisfatória."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BREWBOOK = "Uma coleção de observações sobre fermentação."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WOODENKEG = "Um barril perfeito para fazer bebidas."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PRESERVESJAR = "Possui muitos usos, além de picles ou geleias."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ANTCHEST = "Um facilitador particularmente pegajoso de mel."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_NECTAR_POD = "Me pergunto se isso pode ser transformado em mel."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_OAKTREE_POD = "Uma semente de árvore. Crescerá em uma árvore bem grande."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "Prefiro uma boa xícara de chá."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PIKO = "Um adorável bolinho de pelos mamífero."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PIKO_ORANGE = "Um bolinho de pelos mamífero com nome engraçado."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_TREE = "Um ótimo exemplar de Camellia Sinensis."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = "Um ótimo exemplar de Camellia Sinensis."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "O que tem dentro?"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = "Obviamente dilapidada."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = "Um barraco anfíbio."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_SHOP = "Acho que é aí que ele guarda todo o estoque."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = "Um vagão cheio de mercadorias."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "Parece que nos encontramos de novo, querido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_POND = "Poças de maré são micro ecossistemas fascinantes!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "Um rizoma que habita pântanos."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "A forma icônica da duna é formada pelos ventos."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "Este possui habilidades sofisticadas de pesca."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SAMMYHAT = "Um chapéu simples e antigo."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KINGFISHER = "Que querido Chlorocerlye Amazona!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TOUCAN = "Uma espécie conhecida pelo bico colorido."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TOUCAN_CHUBBY = "Uma espécie conhecida por seu bico colorido e grande."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WETGOOP2 = "Oh não. Não, não, não. Isso não serve de jeito nenhum."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BEER = "Uma bebida alcoólica, beba com moderação."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PALEALE = "Uma bebida alcoólica, beba com moderação."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEAGREEN = "Tudo que preciso para ler, uma boa xícara de chá."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEARED = "Tudo que preciso para ler, uma boa xícara de chá."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MEAD = "Preciso beber com moderação, demais seria ruim."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_JELLY = "Gostaria de ter torradas para colocar essa geleia. Ah, bem."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MAYONNAISE = "Um creme feito de ovos e dijon."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TARTARSAUCE = "Molho tártaro, uma variação da maionese."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PICKLES = "Picles feitos a partir de vegetais."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WINE = "Gostaria de um pedaço de queijo agora."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_JUICE = "Um suco feito de vegetais."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_POISON_FROGLEGS = "Agalychnis callidryas não é venenosa, mas pode não ser Agalychnis callidryas."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "Não estou convencida de que o veneno se foi."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.POISONFROGGLEBUNWICH = "Não é tipicamente servido em sanduíches, mas vou experimentar!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BREWINGRECIPECARD = "Oh céus, não consigo dar sentido algum a isso."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_OIL = "Um óleo multiuso, bom para cozinhar pratos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BERRYSUNDAE = "Nada como um livro e uma tigela de sundae."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CHOCOLATE_BLACK = "Estranho, parece que falta cacau."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CHOCOLATE_WHITE = "Estranho, parece que falta cacau."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TRICOLORDANGO = "Um lanchinho macio e pegajoso."
 
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FRIESFRENCH = "Um prato clássico de fast food. Rápido e relativamente delicioso."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIRATERUM = "É Rum, mas por que me sinto tão insegura com ele?"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TWISTEDTEQUILA = "Um coquetel clássico, na verdade este contém algo a mais."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ONIONRINGS = "Cebolas fatiadas banhadas em óleo, um ótimo lanche da tarde."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DONUTS = "Comida de massa. Um clássico na América."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "Comida de massa. Um clássico na América."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "Comida de massa. Um clássico na América."
 
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CINNAMONROLL = "Massa polvilhada sobre uma fina camada de manteiga."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GUMMYBEARGERS = "Doce infantil em formato de urso."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PRETZEL = "Massa assada, comumente em formato de nó."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CORNINCUP = "Um lanche tradicional mexicano."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COTTONCANDY = "Um prato comum entre crianças, muito usado em festividades."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ROASTEDHAZELNUTS = "Nozes perfeitamente assadas, um ótimo lanche da tarde."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONSTERMUFFIN = "Consigo sentir uma aura maligna nele."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PINKCAKE = "Um bolo de festa, bem comum."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CHIPSBAG = "Batatas fritas, geralmente servidas como aperitivo ou lanche."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LITTLEBREAD = "Posso transformar isso em algo bom."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HOTHOUND = "Ainda lembro dos carrinhos vendendo isso em todo lugar."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MILKSHAKE = "Escolha muito popular em cafeterias."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MILKSHAKE_PRISMATIC = "Escolha muito popular em cafeterias."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NACHOS = "O molho de queijo deixa ainda melhor!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BANANA_PUDDING = "Um pudim de banana simples, mas saboroso."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SEA_PUDDING = "Ugh. O cheiro disso..."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TOM_KHA_SOUP = "Um prato clássico da Tailândia."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MINERTREAT = "Posso ver minha criança interior pedindo por isso."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.RADISHSALAD = "Cheia de nutrientes!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PUMPKIN_SOUP = "Exatamente o que eu precisava."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ALGAE_SOUP = "Exatamente o que eu precisava."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PARZNIP_SOUP = "Exatamente o que eu precisava."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NETTLEMEATED = "Nutrição medicinal, com proteína adicional."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SUGAR = "Condimento adoçado."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BOTTLECAP = "Potencial moeda para cenários pós-apocalípticos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NUKACOLA = "Mesmo no fim do mundo, vou beber algo agradável."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NUKACOLA_QUANTUM = "Mesmo no fim do mundo, vou beber algo agradável."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LIVINGSANDWICH = "Oh céus, isso não é adequado para comer."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DURIANSPLIT = "Nada como um livro e uma tigela de sorvete."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DURIANSOUP = "Um caldo reforçado."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DURIANMEATED = "Esse cheiro..."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DURIANCHICKEN = "Que assado agradável."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LUNARSOUP = "Está cheirando bem."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PURPLEWOBSTERSOUP = "Uma sopa chique e extravagante."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WOBSTERMONSTER = "Essa é uma comida a evitar, com certeza."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPIDERCAKE = "Oh céus, que ponto atingimos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SUGARBOMBS = "Um cereal com design de bombas."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BERRYBOMBS = "Eu adoraria um pouco de torrada agora."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ONIGIRIS = "Um prato popular em outros países."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.OMURICE = "Uma refeição popular entre crianças em outros países."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PAELLA = "Símbolo de uma comunidade! Um prato renomado."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.RISOTTO = "Uma maneira muito popular de cozinhar arroz em alguns lugares."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.RICESAKE = "Beba com moderação."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "Um arbusto de Ananas comosus. Incrível."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PINEAPPLEBUSH = "Um arbusto de Ananas comosus. Incrível."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PINEAPPLE = "Que abacaxi espinhoso!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PINEAPPLE_HALVED = "Quase pronto para comer."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PINEAPPLE_COOKED = "Fatias de abacaxi cozidas no vapor."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIZZA_TROPICAL = "É uma adição interessante."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PINACOLADA = "Uma boa bebida feita com Ananas comosus e Cocos nucifera."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CHIMAS = "É uma bebida clássica do Sul."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_GARDEN_SPRINKLER = "Hidratação necessária."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FOODSACK = "Mantém minhas provisões frescas!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.GUMMYWORMS = "Doce que lembra minhocas profundas."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SMORES = "Uma mistura de marshmallow e chocolate."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.NUKASHINE = "Cuidado ao beber essa bebida estranha."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ANTSLOG = "Uma imitação."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WORM_BONE = "Espécime interessante."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPOOKY_BRAIN_NOODLES = "Uma recriação de cérebro humano em forma de miojo."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPOOKY_BURGERZILLA = "Parece um monstro."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPOOKY_DEADBREAD = "Contém propriedades estranhas."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPOOKY_JELLYBEANS = "Doces de olho."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPOOKY_POPSICLE = "Um picolé de limão disfarçado de folha."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPOOKY_PUMPKINCREAM = "Não sei se combinar vegetal com sorvete é bom."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPOOKY_SKULLCANDY = "Doce com propriedades mágicas."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPOOKY_TACODILE = "Um taco com dentes afiados."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUTTER_BEEFALO = "Manteiga feita com leite de bífalo selvagem."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUTTER_GOAT = "Queijo feito com leite das cabras locais."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BUTTER_KOALEFANT = "O leite de coalefante dá um sabor único."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICE_CURE = "Cura de alimentos é uma técnica muito antiga e tradicional."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICE_COLD = "Flocos congelados capazes de congelar ao contato."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICE_FIRE = "Cristais de chamas capazes de queimar ao contato."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICE_FED = "Alta dose de calorias para tornar os pratos mais atraentes."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPICE_MIND = "Algo para acalmar a mente."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SUGARFLYMUFFIN = "Quem diria que sugarflies fariam tão bons bolinhos?"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.EELTACOS = "Ah, gosto de um pouco de tempero na enguia."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MEATSKILLET = "Um pedaço de carne e legumes perfeitamente fritos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MEATWALTZ = "Algumas pessoas preferem carne malpassada."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COMPLETEBREAKFAST = "Wolfgang realmente tem apetite."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.DUMPLINGS = "Massa cozida envolta em carne."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WARLYICEDTEA = "Revigorante."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WARLYTEA = "Me dê chá e um bom livro."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TEALEAF = "Ah, sim. Folhas para preparar chás doces."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ITEMSLICER = "Usado para cortar pedaços de carne e outros ingredientes."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ITEMSLICER_GOLD = "Usado para cortar pedaços de carne e outros ingredientes."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.COXINHA = "Um tipo comum de lanche do hemisfério sul."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LAZYDESSERT = "Parece caramelo, mas duro e sólido como uma pedra."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.CRABKINGFEAST = "Este banquete desafia as leis da física dentro dessa panela."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PIENAPPLE = "Uma torta feita com ingredientes tropicais."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.JAWSBREAKER = "Esse quebra-queixo é grande demais para um humano comer."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.AVOCADOTOAST = "Quem poderia imaginar que isso seria tão bom!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.RICEPUDDING = "Não é minha primeira escolha, mas serve."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SHARKSUSHI = "Que comida preciosa!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WOBSTERBREADED = "Deve resolver."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LAZYPURRITO = "Espero sinceramente que o rabo seja apenas decorativo."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.HORCHATA = "Ouvi dizer que é uma bebida local em algumas partes do mundo."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WOBSTERCOCKTAIL = "Coquetel de lagosta ornamentado."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LAVAEEGGBOILED = "Quente ao toque."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.POMEGRANATETEA = "Revigorante."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TIRAMISU = "Na verdade... Vários alces não são chamados de alceses, mas de alces."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TOADSTOOLCOLA = "Uma bebida suave... Feita com pernas de sapo venenoso."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TEPACHE = "Não coma muito açúcar em pouco tempo."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.LUNARTEQUILA = "Tanta energia poderosa em uma bebida tão pequena."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MIMICMOSA = "Posso usar para me esconder e ganhar tempo."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.POMEGRANATEPIE = "O trocadilho com romãs me pegou. Ha!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PINEAPPLECAKE = "Um bolo com fatias de abacaxi."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PASTY_MEAT = "Ouvi dizer que é um lanche muito popular na América do Sul."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.PASTY_CHEESE = "Ouvi dizer que é um lanche muito popular na América do Sul."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BRIGADEIRO = "É um doce popular de festa de aniversário na América do Sul."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.REGULARLASAGNA = "Bom, agora podemos nos manter longe daquela coisa."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.FLTSANDWICH = "Sapo é um bom substituto para bacon."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.RICEANDBEANS = "Um almoço muito saudável e nutritivo."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "Seu estado decadente indica restauração futura. Prevejo atividade em 2026."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TRUFFLES_GROUND = "Tuber melanosporum! Uma iguaria subterrânea valiosa."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TRUFFLES = "Trufas frescas — um ingrediente nobre na culinária."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_TRUFFLES_COOKED = "O calor liberou todo o potencial do seu sabor."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ITEMSHOWCASER = "Uma forma adequada de apresentar uma boa gastronomia."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SPORECAP = "Um espécime fúngico mostrando sinais de praga avançada."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SPORECAP_COOKED = "Leve melhora após aquecimento."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SPORECAP_DARK = "Esporos extremamente tóxicos. Cuidado."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "As toxinas resistem ao calor."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_GOLDENAPPLE = "Suspeito que este seja o fruto que iniciou tudo."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TRUFFLESGRINDER = "Uma fina iguaria feita de fungos subterrâneos. Exquisito."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPORECAPPIE = "Uma massa fúngica repleta de toxinas. Fascinante!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SPORECAP_SKEWERS = "Um espetinho improvisado mas nutritivo de cogumelos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.TRUFFLEOIL = "Um fino ingrediente culinário derivado de fungos subterrâneos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "Ah, que belo conjunto de construção."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "Um ótimo início para um ambiente de aquicultura controlado."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FISHFARMPLOT = "Um ambiente artificial para reprodução aquática."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ANTCHOVY = "Um espécime artrópode-pisciforme deveras peculiar!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "Uma rara congregação de comportamento interestadual de cardume!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.AGEDROE = "Difere dovas comuns principalmente pelo recipiente."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "Uma iguaria de ovas preservadas de esturjão. Exquisito."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SWORDFISH_BLUE = "Parece que a longa exposição à água doce prejudicou seus instintos marinhos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH = "Água-viva, a mais antiga das criaturas com múltiplos órgãos."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_DEAD = "Cuidado para não pisar nisso."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_COOKED = "Transformei em algo comestível através de uma reação química controlada."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_DRIED = "Que forma engenhosa de conservar alimentos."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "Acredito que se alimenta da bioluminescência local."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "Uma Medusozoa falecida."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "Um espécime de Medusozoa completamente cozido."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "Gosto quando há um manuscrito dentro."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_OCEANTRAP = "Coloque perto da toca da criatura."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.OCEANFISH_PUFFERFISH = "Ah, Tetraodontidae. Deve ser manuseado com extremo cuidado."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.OCEANFISH_STURGEON = "Acipenseridae! Linhagem incrivelmente antiga, fascinante!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SWORDFISH = "Não irrite o peixe-de-bico!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SWORDFISH_DEAD = "Parece um pouco menos feroz assim."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SWORDFISHFEAST = "Uma apresentação requintada da carne de Xiphias gladius."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_DOGFISH = "Canis fishus."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_DOGFISH_DEAD = "Uma pena."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "Essa matéria de peixe está virando um risco biológico."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WOBSTER_MONKEYISLAND = "Ah, um crustáceo com pigmentação incomum. Fascinante."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "Um espécime nobre, mesmo na morte."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "Um excelente exemplo da culinária de crustáceos, preparado com maestria."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PUFFERMONSTER = "Um espécime extremamente volátil da família Tetraodontidae."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "Algo grande se esconde lá embaixo."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "Eu adoro mamíferos marinhos!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "Baleia branca! Gdyby tylko był na ten temat jakiś podręcznik!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "Começa a decomposição."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BLUBBER = "Uma substância flutuante e rica em lipídios."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "Uma porção preservada de proteína de peixe."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FISHMEAT_DRIED = "Um pedaço bem preservado de proteína aquática."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.MONKEYISLANDMEAL = "Uma mistura fascinante de frutas e frutos do mar. Surpreendentemente eficaz contra maldições."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BRAINROCK_LARVAE = "O pólipo de um invertebrado marinho."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "A base de uma futura explosão cerebral."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BRAINROCK_CORAL = "Genial!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_BRAINROCK_ROCK = "Mussidae Brainus."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.BRAINMETTERSOUP = "Ah, é uma refeição clássica para crianças."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = "Ele é o centro deste ecossistema."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "Parece que ficou no fundo do oceano."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = "Que tipo de peixe era esse?"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_PACKIMBAGGIMS = "Olá, aprendiz emplumado!"

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "Precisamos de mais ingredientes para assá-lo."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "Está crescendo muito bem."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "Nosso bolo ficou impressionante!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "Velas decorativas e tradicionais de celebração."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "Me lembra as celebrações da biblioteca."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "Uma confeitaria tradicional de comemoração."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "Balões de látex. Festivos e biodegradáveis... espero."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = "Uma máquina que transforma milho em petiscos estourados."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "O calor faz a umidade expandir rapidamente. Fascinante!"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "Um acessório festivo tradicional, em formato cônico."
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "Um acessório de festa feito sob medida."

STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.KYNO_FISHREGISTRYHAT = "Um acessório útil para o estudo sistemático das espécies de peixes."