local WX78 = STRINGS.CHARACTERS.WX78

WX78.ANNOUNCE_KYNO_COFFEEBUFF_START = "VELOCIDADE DE MOVIMENTO: NÍVEIS ELEVADOS"
WX78.ANNOUNCE_KYNO_COFFEEBUFF_END = "VELOCIDADE DE MOVIMENTO: NORMALIZADA"

WX78.ANNOUNCE_KYNO_HASTEBUFF_START = "VELOCIDADE DE MOVIMENTO DAS MÃOS: EFICIÊNCIA MÁXIMA"
WX78.ANNOUNCE_KYNO_HASTEBUFF_END = "VELOCIDADE DE MOVIMENTO DOS CLIQUES VOLTOU AO NORMAL"

WX78.ANNOUNCE_KYNO_POPBUFF_START = "(BUURP) MAS O QUE...?"
WX78.ANNOUNCE_KYNO_POPBUFF_END = "EFEITOS BORBULHANTES FORAM REMOVIDOS"

WX78.ANNOUNCE_KYNO_FROGBUFF_START = "SISTEMA DE AROMA ALTERADO PARA SAPO"
WX78.ANNOUNCE_KYNO_FROGBUFF_END = "AROMA DE SAPO REMOVIDO"

WX78.ANNOUNCE_KYNO_PIRATEBUFF_START = "SUBROTINA PIRATA ATIVADA"
WX78.ANNOUNCE_KYNO_PIRATEBUFF_END = "SUBROTINA PIRATA: ENCERRADA"

WX78.ANNOUNCE_KYNO_FREEZEBUFF_START = "IMUNIDADE AO FRIO: ATIVADA"
WX78.ANNOUNCE_KYNO_FREEZEBUFF_END = "SISTEMAS CENTRAIS DE VOLTA À ROTINA NORMAL"

WX78.ANNOUNCE_KYNO_FIREBUFF_START = "IMUNIDADE AO FOGO: ATIVADA"
WX78.ANNOUNCE_KYNO_FIREBUFF_END = "SISTEMAS CENTRAIS DE VOLTA À ROTINA NORMAL"

WX78.ANNOUNCE_KYNO_FISHINGBUFF_START = "AJI WO [K]UTTA?"
WX78.ANNOUNCE_KYNO_FISHINGBUFF_END = "AVISO: ADDON DE PESCA DESLIGADO"

WX78.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "DIMINUINDO ATIVIDADE DOS SERVIÇOS DE NUVEM"
WX78.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "SERVIÇOS DE NUVEM DE VOLTA AO NORMAL"

WX78.ANNOUNCE_KYNO_EATERBUFF_START = "SISTEMAS DIGESTIVOS POTENCIALIZADOS"
WX78.ANNOUNCE_KYNO_EATERBUFF_END = "SISTEMAS DIGESTIVOS DE VOLTA À ROTINA NORMAL"

WX78.ANNOUNCE_KYNO_WORMBUFF_START = "SISTEMAS PRONTOS PARA COMBATER VERMES"
WX78.ANNOUNCE_KYNO_WORMBUFF_END = "SISTEMA ATRASADO: DESLIGANDO MÓDULOS DE ATAQUE A VERMES"

WX78.ANNOUNCE_KYNO_CRABBUFF_START = "SISTEMAS PRONTOS PARA COMBATER CARANGUEJOS"
WX78.ANNOUNCE_KYNO_CRABBUFF_END = "SISTEMA ATRASADO: DESLIGANDO MÓDULOS DE ATAQUE A CARANGUEJOS"

WX78.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(ARGH) O QUE É ISSO...?"
WX78.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "EFEITOS BORBULHANTES ELIMINADOS"

WX78.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "AAAHH! A LUA! SIM!!"
WX78.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "NÃOOO! MEUS PODERES! DEVOLVA!"

WX78.ANNOUNCE_KYNO_STEALTHBUFF_START = "MODO CAMUFLAGEM: ATIVADO"
WX78.ANNOUNCE_KYNO_STEALTHBUFF_END = "MÓDULO DE CAMUFLAGEM: DESLIGADO"

WX78.ANNOUNCE_KYNO_FEARBUFF_START = "MODO CORAJOSO: ATIVADO"
WX78.ANNOUNCE_KYNO_FEARBUFF_END = "CORAGEM: DESATIVADA"

WX78.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "**SISTEMA SOBRECARGADO**."
WX78.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "NÍVEIS DE ENERGIA RETORNANDO AO MEDÍOCRE."

WX78.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "AFINIDADE COM PORCOS AUMENTADA."
WX78.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "AFINIDADE COM PORCOS TERMINADA."

WX78.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "MATERIAIS CORROSIVOS NEUTRALIZADOS."
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WX78.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "TOXINAS BIOLÓGICAS DESATIVADAS."
WX78.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "IMUNIDADE EXPIRADA. AMEAÇA BIOLÓGICA REATIVADA."

WX78.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "ATUALIZAÇÃO DO SISTEMA: EFICIÊNCIA DE CONSTRUÇÃO AUMENTADA."
WX78.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "ATUALIZAÇÃO EXPIRADA. RETORNANDO AO MODO BURRO PADRÃO."

WX78.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "BIO-DRONES HOSTIS TEMPORARIAMENTE PACIFICADOS. ACEITÁVEL."
WX78.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "BIO-DRONES RETORNANDO AO MODO AGRESSIVO. AVISO."

WX78.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "ATUALIZAÇÃO: INTEGRIDADE ESTRUTURAL APRIMORADA"
WX78.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "UPGRADE EXPIRADO. NÍVEL DE DECEPÇÃO CRESCENTE"

WX78.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "CAPACIDADE DE ARMAZENAMENTO DE COMBUSTÍVEL AUMENTADA"
WX78.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "ARMAZENAMENTO DE COMBUSTÍVEL REBAIXADO"

WX78.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "DIAGNÓSTICO: PODER CEREBRAL APRIMORADO"
WX78.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "APrimoramento mental EXPIRADO"

WX78.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "PARÂMETROS DEFENSIVOS APRIMORADOS ATIVOS."
WX78.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "AVISO: MEDIDAS DEFENSIVAS EXTRAS ENCERRADAS."

WX78.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "UNIDADE DE IMPLEMENTAÇÃO ERRADA"

WX78.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "CRIATURA IMUNDA QUER OUTRA COISA"

WX78.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "ÁRVORE ESTÚPIDA É PEQUENA DEMAIS PARA MEU DISPOSITIVO"

WX78.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "ERRO: UNIDADE DE IMPLEMENTAÇÃO DESCONHECIDA"

WX78.ANNOUNCE_KYNO_POTHANGER_FAIL = "PRECISA DE UMA UNIDADE DE COZIMENTO"

WX78.ANNOUNCE_KYNO_CASSEROLE_FAIL = "ERRO: UNIDADE CRUCIAL DE CAÇAROLA AUSENTE"

WX78.ANNOUNCE_KYNO_SAPHEALER_USED = "PROCESSO DE RESTAURAÇÃO COMPLETO. STATUS DA UNIDADE: 100%"

WX78.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "HA. HA. ORGANISMO ORGÂNICO ELIMINADO. COLHEITA COMPLETA."

WX78.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "NENHUM ITEM VALIOSO ENCONTRADO. PERDA DE TEMPO"

WX78.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "ALVO PERDIDO. CAMINHO SUBMERSO."
WX78.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "PRECIPITAÇÃO DETECTADA. DADOS CORROMPIDOS."
WX78.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "AMEAÇA MARINHA DETECTADA. EXTERMÍNIO NECESSÁRIO."

WX78.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "CONSTRUÇÃO CONCLUÍDA. INICIANDO PROTOCOLOS DE FESTA"

WX78.ANNOUNCE_KYNO_FISH_RESEARCHED = "ANÁLISE CONCLUÍDA. DADOS DO PEIXE ADQUIRIDOS."
WX78.ANNOUNCE_KYNO_ROE_RESEARCHED = "ANÁLISE DE OVOS CONCLUÍDA. DADOS ADQUIRIDOS."

WX78.DESCRIBE.KYNO_ROE = "POTENCIAIS AQUÁTICOS INFERIORES"
WX78.DESCRIBE.KYNO_ROE_COOKED = "ERAM VULNERÁVEIS E EU OS DESTRUI HAHAHA"

WX78.DESCRIBE.KYNO_SHARK_FIN = "O LEME DA BESTA"

WX78.DESCRIBE.KYNO_BEANBUGS = "NATUREZA É ANÔMALA"
WX78.DESCRIBE.KYNO_BEANBUGS_COOKED = "CONTÉM ENERGIA, MAS A QUE CUSTO?"

WX78.DESCRIBE.KYNO_GUMMYBUG = "ENERGIA GELATINOSA"
WX78.DESCRIBE.KYNO_GUMMYBUG_COOKED = "HAHA EU VOU CONVERTER VOCÊ EM ENERGIA"

WX78.DESCRIBE.KYNO_WHEAT = "GRÃO DETECTADO"
WX78.DESCRIBE.KYNO_WHEAT_COOKED = "GRÃO TOSTADO DETECTADO"

WX78.DESCRIBE.KYNO_FLOUR = "ESTÁGIO INICIAL DE COMIDA"

WX78.DESCRIBE.KYNO_SPOTSPICE = "VOCÊ FOI MOÍDO, PIMPOLHO"

WX78.DESCRIBE.KYNO_SAP = "REFRIGERANTE VEGETAL DELICIOSO"
WX78.DESCRIBE.KYNO_SAP_SPOILED = "PEGUEJOSIDADE INÚTIL"

WX78.DESCRIBE.KYNO_SYRUP = "CONTÉM ALTA NÍVEL DE PEGUEJOSIDADE"

WX78.DESCRIBE.KYNO_COFFEEBEANS = "GRÃOS BEBÍVEIS"
WX78.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "GRÃO NARCÓTICO ALCANÇOU O NÍVEL ÓTIMO DE TORRA"

WX78.DESCRIBE.DUG_KYNO_COFFEEBUSH = "PLANTA PRECISA DE LUGAR QUENTE PARA SER PLANTADA"

WX78.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "PLANTA DE GRÃOS BEBÍVEIS",
	PICKED = "PRODUÇÃO DE GRÃOS INTERROMPIDA",
	WITHERED = "NÍVEIS DE CINZAS INSUFICIENTES",
}

WX78.DESCRIBE.DUG_KYNO_SPOTBUSH = "NECESSITA DE INSTALAÇÃO"

WX78.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "ENTREGUE SEUS RECURSOS, ARBUSTO",
	PICKED = "PRODUÇÃO DE RECURSOS INTERROMPIDA",
	BURNING = "AVISO: COMBUSTÃO",
}

WX78.DESCRIBE.KYNO_SPOTSPICE_LEAF = "EU VOU TE ESMAGAR"

WX78.DESCRIBE.KYNO_MUSSEL = "MUSCULATURA NÃO DETECTADA"
WX78.DESCRIBE.KYNO_MUSSEL_COOKED = "MOLÉCULAS DE SABOR FORTES"

WX78.DESCRIBE.KYNO_HUMANMEAT = "UMA MELHORIA ADICIONAL DA CONDIÇÃO HUMANA."
WX78.DESCRIBE.KYNO_HUMANMEAT_COOKED = "FINALMENTE, UM PROPÓSITO PARA A PESTE CARNEFAÇA"
WX78.DESCRIBE.KYNO_HUMANMEAT_DRIED = "SECA E PRONTA"

WX78.DESCRIBE.COFFEE = "É APENAS SUCO DE GRÃO QUENTE."

WX78.DESCRIBE.BISQUE = "POTÊNCIA DE BATERIA EM UMA TIGELA"

WX78.DESCRIBE.JELLYOPOP = "MANTERÁ MEUS SISTEMAS FUNCIONANDO"

WX78.DESCRIBE.SHARKFINSOUP = "APARENTA SER COMESTÍVEL"

WX78.DESCRIBE.TROPICALBOUILLABAISSE = "ISSO ALIMENTARÁ MEU CORPO MECÂNICO SUPERIOR"

WX78.DESCRIBE.MUSSELBOUILLABAISE = "ATIVANDO SENSORES DE LÍNGUA"

WX78.DESCRIBE.SWEETPOTATOSOUFFLE = "OFENSIVO"

WX78.DESCRIBE.FEIJOADA = "PACOTES DE ENERGIA"

WX78.DESCRIBE.GUMMY_CAKE = "NÃO HÁ ALEGRIA NISTO"

WX78.DESCRIBE.HARDSHELL_TACOS = "VOU ESMAGAR SUA CASCA DURA"

WX78.DESCRIBE.ICEDTEA = "BEBIDA REFRESCANTE FEITA PELO MEU INIMIGO"

WX78.DESCRIBE.NETTLELOSANGE = "AR COMPRIMIDO PARA UNIDADES NASAIS"

WX78.DESCRIBE.SNAKEBONESOUP = "UM BREW FEITO DE DOIS DOS MEUS INIMIGOS"

WX78.DESCRIBE.STEAMEDHAMSANDWICH = "UM ALMOÇO INESQUECÍVEL"

WX78.DESCRIBE.TEA = "LÍQUIDO ADQUIRIDO DE UMA MÁQUINA DE CARNE"

WX78.DESCRIBE.BUBBLETEA = "UMA BEBIDA REFRESCANTE FEITA PELO MEU INIMIGO"

WX78.DESCRIBE.FRENCHONIONSOUP = "UM BREW FEITO DE CEBOLAS"

WX78.DESCRIBE.SLAW = "SUSTENTO IDENTIFICADO"

WX78.DESCRIBE.LOTUSBOWL = "LIBEREI-OS DAS SUAS RESTRIÇÕES TERRENAS"

WX78.DESCRIBE.POI = "ESTA COMIDA COMUM DEVERIA ESTAR EXTINTA"

WX78.DESCRIBE.JELLYBEAN_HUNGER = "COMPONENTES DE MELHORIA TEMPORÁRIA"
WX78.DESCRIBE.JELLYBEAN_SUPER = "COMPONENTES DE MELHORIA TEMPORÁRIA"
WX78.DESCRIBE.JELLYBEAN_SANITY = "COMPONENTES DE MELHORIA TEMPORÁRIA"

WX78.DESCRIBE.BOWLOFGEARS = "SIM. AGORA ISSO É COMIDA ADEQUADA PARA UM SER SUPERIOR"

WX78.DESCRIBE.LONGPIGMEAL = "MELHORIA DE CARNE HUMANA"

WX78.DESCRIBE.CUCUMBERSALAD = "MONTAGEM DE SALADA: CONCLUÍDA"

WX78.DESCRIBE.DUG_KYNO_WILDWHEAT = "HARDWARE PARA INSTALAÇÃO"

WX78.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "GRÃOS",
	PICKED = "PRODUÇÃO DE GRÃOS INTERROMPIDA",
	WITHERED = "UMIDADE INSUFICIENTE",
	BURNING = "AVISO: COMBUSTÃO",
}

WX78.DESCRIBE.KYNO_MEALGRINDER = "SOU BOM EM ESMAGAR"

WX78.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "COMESTIBILIDADE CONFIRMADA",
	PICKED = "TAXA DE CRESCIMENTO INSUFICIENTE PARA MINHAS NECESSIDADES",
	BURNING = "AVISO: COMBUSTÃO ORGÂNICA",
}

WX78.DESCRIBE.GORGE_BREAD = "INGREDIENTE PARA RECEITAS MELHORES"
WX78.DESCRIBE.GORGE_SWEET_CHIPS = "FATIAS DE BATATA FRITAS"
WX78.DESCRIBE.GORGE_VEGETABLE_SOUP = "APENAS UM MONTE DE VEGETAIS REUNIDOS"
WX78.DESCRIBE.GORGE_JELLY_SANDWICH = "ESTÁ GELEIANDO PARA MIM"
WX78.DESCRIBE.GORGE_FISH_STEW = "PREPARAR PARA INGESTÃO CALÓRICA"
WX78.DESCRIBE.GORGE_MEAT_STEW = "NUTRIÇÃO ADQUIRIDA"
WX78.DESCRIBE.GORGE_ONION_CAKE = "BOLO REPUGNANTE"
WX78.DESCRIBE.GORGE_POTATO_PANCAKES = "USO PATÉTICO DE BATATAS"
WX78.DESCRIBE.GORGE_POTATO_SOUP = "POTÊNCIA DE BATERIA EM UMA TIGELA"
WX78.DESCRIBE.GORGE_FISHBALL_SKEWERS = "QUANTIDADE DECENTE DE COMIDA EM UM PALITO"
WX78.DESCRIBE.GORGE_MEAT_SKEWERS = "QUANTIDADE DECENTE DE COMIDA EM UM PALITO"
WX78.DESCRIBE.GORGE_STONE_SOUP = "POTÊNCIA DE BATERIA EM UMA TIGELA"
WX78.DESCRIBE.GORGE_CROQUETTE = "BOLAS DE FARINHA"
WX78.DESCRIBE.GORGE_ROAST_VEGETABLES = "NOJENTO"
WX78.DESCRIBE.GORGE_MEATLOAF = "CARNE MISTURADA COM MIGALHAS DE PÃO"
WX78.DESCRIBE.GORGE_CARROT_SOUP = "POTÊNCIA DE BATERIA EM UMA TIGELA"
WX78.DESCRIBE.GORGE_FISHPIE = "VIDAS FRACAS PRESAS NA FARINHA. HA HA."
WX78.DESCRIBE.GORGE_FISHCHIPS = "COMIDA MAIS ADEQUADA"
WX78.DESCRIBE.GORGE_MEATPIE = "CARNE ESMAGADA DENTRO DE UMA TORTA"
WX78.DESCRIBE.GORGE_SLIDERS = "COMIDA LIXO"
WX78.DESCRIBE.GORGE_JELLY_ROLL = "GOSMENTO DEMAIS PARA MIM"
WX78.DESCRIBE.GORGE_CARROT_CAKE = "MAS... MAS... EU PENSEI QUE ERA SÓ UMA MENTIRA"
WX78.DESCRIBE.GORGE_GARLICMASHED = "MISTURA REPUGNANTE"
WX78.DESCRIBE.GORGE_GARLICBREAD = "UMA ÓTIMA ADIÇÃO"
WX78.DESCRIBE.GORGE_TOMATO_SOUP = "POTÊNCIA DE BATERIA EM UMA TIGELA"
WX78.DESCRIBE.GORGE_SAUSAGE = "HA. SEU FIM CHEGOU"
WX78.DESCRIBE.GORGE_CANDIEDFISH = "TEM XAROPE EM MEUS SISTEMAS"
WX78.DESCRIBE.GORGE_STUFFEDMUSHROOM = "RECHEADO"
WX78.DESCRIBE.GORGE_BRUSCHETTA = "NADA DE ESPECIAL"
WX78.DESCRIBE.GORGE_HAMBURGER = "UMA DAS POUCAS COMIDAS HUMANAS QUE É ÓTIMA"
WX78.DESCRIBE.GORGE_FISHBURGER = "UMA DAS POUCAS COMIDAS HUMANAS QUE É ÓTIMA"
WX78.DESCRIBE.GORGE_MUSHROOMBURGER = "UMA DAS POUCAS COMIDAS HUMANAS QUE É ÓTIMA"
WX78.DESCRIBE.GORGE_FISH_STEAK = "PREPARE-SE PARA INGERIR CALORIAS"
WX78.DESCRIBE.GORGE_CURRY = "É APENAS UM SORO TIPO SOPA"
WX78.DESCRIBE.GORGE_SPAGHETTI = "CARNE COMPACTADA NA FORMA MAIS NUTRITIVA: ESFERA"
WX78.DESCRIBE.GORGE_POACHEDFISH = "ESSE SALMÃO NÃO VAI A LUGAR NENHUM AGORA"
WX78.DESCRIBE.GORGE_SHEPHERD_PIE = "NÃO HÁ OVELHAS POR AQUI"
WX78.DESCRIBE.GORGE_CANDY = "PEGAJOSO E DOCE"
WX78.DESCRIBE.GORGE_BREAD_PUDDING = "PÃO DOCINHO"
WX78.DESCRIBE.GORGE_BERRY_TART = "OH MEU DEUS, É NOJENTO"
WX78.DESCRIBE.GORGE_MACARONI = "VOU ABSORVER ESTE"
WX78.DESCRIBE.GORGE_BAGEL_AND_FISH = "SALMÃO COM PÃO, QUANTA ORIGINALIDADE"
WX78.DESCRIBE.GORGE_GRILLED_CHEESE = "PRINT(\"HELLO WORLD\")"
WX78.DESCRIBE.GORGE_CREAMMUSHROOM = "NÃO, DE NOVO NÃO"
WX78.DESCRIBE.GORGE_MANICOTTI = "ENFADADO"
WX78.DESCRIBE.GORGE_CHEESEBURGER = "UMA DAS POUCAS COMIDAS HUMANAS QUE SÃO ÓTIMAS"
WX78.DESCRIBE.GORGE_FETTUCCINE = "NÃO ME OLHE NOS OLHOS DE NOVO"
WX78.DESCRIBE.GORGE_ONION_SOUP = "ESTÁ FEDENDO"
WX78.DESCRIBE.GORGE_BREADED_CUTLET = "CARNE E PÃO COMBINADOS"
WX78.DESCRIBE.GORGE_CREAMY_FISH = "SALMÃO DE NOVO? QUE ORIGINAL"
WX78.DESCRIBE.GORGE_PIZZA = "HA. ISCA CLÁSSICA PARA HUMANOS BURROS"
WX78.DESCRIBE.GORGE_POT_ROAST = "ISSO SIMPLESMENTE NÃO É POSSÍVEL"
WX78.DESCRIBE.GORGE_CRAB_CAKE = "ISSO CERTAMENTE NÃO É ARTE"
WX78.DESCRIBE.GORGE_STEAK_FRITES = "CLÁSSICO"
WX78.DESCRIBE.GORGE_SHOOTER_SANDWICH = "MIRE NAS ESTRELAS"
WX78.DESCRIBE.GORGE_BACON_WRAPPED = "É SÓ CARNE ENVOLVIDA EM MAIS CARNE"
WX78.DESCRIBE.GORGE_CRAB_ROLL = "EXTRAORDINÁRIO"
WX78.DESCRIBE.GORGE_MEAT_WELLINGTON = "TENHO MINHAS DÚVIDAS SOBRE ESTE"
WX78.DESCRIBE.GORGE_CRAB_RAVIOLI = "EXTRAORDINÁRIO"
WX78.DESCRIBE.GORGE_CARAMEL_CUBE = "UM CUBO FINO DE CARAMELO"
WX78.DESCRIBE.GORGE_SCONE = "AÇÚCAR DEMAIS AAAA"
WX78.DESCRIBE.GORGE_TRIFLE = "AÇÚCAR DEMAIS AAAA"
WX78.DESCRIBE.GORGE_CHEESECAKE = "ONDE ESTÁ O QUEIJO?"

WX78.DESCRIBE.DUCKYOUGLERMZ = "AQUELA PLANTA MALDITA PRECISA DE UM REPARO NO HARDWARE"

WX78.DESCRIBE.KYNO_ALOE = "ENERGIA VERDE ADQUIRIDA"
WX78.DESCRIBE.KYNO_ALOE_COOKED = "ENERGIA VERDE FRICASSÊ"
WX78.DESCRIBE.KYNO_ALOE_GROUND = "ENERGIA VERDE ADQUIRIDA"
WX78.DESCRIBE.KYNO_ALOE_SEEDS = "É CÓDIGO FONTE PARA COMIDA QUE VEM DA TERRA"
WX78.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "É CÓDIGO FONTE PARA COMIDA QUE VEM DA TERRA"
WX78.DESCRIBE.FARM_PLANT_KYNO_ALOE = "ENERGIA VERDE ADQUIRIDA"
WX78.DESCRIBE.KYNO_ALOE_OVERSIZED = "ENERGIA VERDE ADQUIRIDA"
WX78.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_CUCUMBER = "EU ROUBEI ISSO DAS HORRÍVEIS ÁGUAS"
WX78.DESCRIBE.KYNO_CUCUMBER_COOKED = "GOSMA ENERGÉTICA"
WX78.DESCRIBE.KYNO_CUCUMBER_GROUND = "EU ROUBEI ISSO DAS HORRÍVEIS ÁGUAS"
WX78.DESCRIBE.KYNO_CUCUMBER_SEEDS = "CÓDIGO FONTE PARA COMIDA QUE VEM DA TERRA"
WX78.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "CÓDIGO FONTE PARA COMIDA QUE VEM DA TERRA"
WX78.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "ROUBEI ISSO DAS HORRÍVEIS ÁGUAS"
WX78.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "ROUBEI ISSO DAS HORRÍVEIS ÁGUAS"
WX78.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_RADISH = "BOLAS ESPERÍRICAS VERMELHAS DE ENERGIA"
WX78.DESCRIBE.KYNO_RADISH_COOKED = "ENERGIA ADQUIRIDA"
WX78.DESCRIBE.KYNO_RADISH_GROUND = "BOLAS ESPERÍRICAS VERMELHAS DE ENERGIA"
WX78.DESCRIBE.KYNO_RADISH_SEEDS = "CÓDIGO-FONTE DE COMIDA VINDO DA TERRA"
WX78.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "CÓDIGO-FONTE DE COMIDA VINDO DA TERRA"
WX78.DESCRIBE.FARM_PLANT_KYNO_RADISH = "BOLAS ESFÉRICAS VERMELHAS DE ENERGIA"
WX78.DESCRIBE.KYNO_RADISH_OVERSIZED = "BOLAS ESFÉRICAS VERMELHAS DE ENERGIA"
WX78.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_FENNEL = "PARECE UMA PLANTA COMUM PARA MIM."
WX78.DESCRIBE.KYNO_FENNEL_COOKED = "NOJENTO"
WX78.DESCRIBE.KYNO_FENNEL_GROUND = "PARECE UMA PLANTA COMUM PARA MIM."
WX78.DESCRIBE.KYNO_FENNEL_SEEDS = "CÓDIGO-FONTE DE COMIDA VINDO DA TERRA"
WX78.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "CÓDIGO-FONTE DE COMIDA VINDO DA TERRA"
WX78.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "PARECE UMA PLANTA ORDINÁRIA PARA MIM."
WX78.DESCRIBE.KYNO_FENNEL_OVERSIZED = "PARECE UMA PLANTA ORDINÁRIA PARA MIM."
WX78.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_SWEETPOTATO = "NOJENTO"
WX78.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "O AMIDO E O DOCE LUTAM PELA DOMINAÇÃO E WX-78 PERDE"
WX78.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "NOJENTO"
WX78.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "CÓDIGO-FONTE DE COMIDA QUE VEM DA TERRA"
WX78.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "CÓDIGO-FONTE DE COMIDA QUE VEM DA TERRA"
WX78.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "NOJENTO"
WX78.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "NOJENTO"
WX78.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_PARZNIP = "NUTRITIVO"
WX78.DESCRIBE.KYNO_PARZNIP_COOKED = "NUTRITIVO"
WX78.DESCRIBE.KYNO_PARZNIP_EATEN = "NUTRITIVO"
WX78.DESCRIBE.KYNO_PARZNIP_GROUND = "NUTRITIVO"
WX78.DESCRIBE.KYNO_PARZNIP_BIG = "ANÁLISE DE TAMANHO COMPLETA: GIGANTE"
WX78.DESCRIBE.KYNO_PARZNIP_SEEDS = "CÓDIGO-FONTE DE COMIDA VINDO DA TERRA"
WX78.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "CÓDIGO-FONTE DE COMIDA VINDO DA TERRA"
WX78.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "NUTRITIVO"
WX78.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "NUTRITIVO"
WX78.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_TURNIP = "É UM NABO BURRO"
WX78.DESCRIBE.KYNO_TURNIP_COOKED = "ESTÁ COZIDO DE FORMA UNIFORME"
WX78.DESCRIBE.KYNO_TURNIP_GROUND = "É UM NABO BURRO"
WX78.DESCRIBE.KYNO_TURNIP_SEEDS = "CÓDIGO-FONTE PARA COMIDA QUE VEM DA TERRA"
WX78.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "CÓDIGO-FONTE PARA COMIDA QUE VEM DA TERRA"
WX78.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "É UM NABO BURRO"
WX78.DESCRIBE.KYNO_TURNIP_OVERSIZED = "É UM NABO BURRO"
WX78.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_RICE = "VEGETAL REPUGNANTE"
WX78.DESCRIBE.KYNO_RICE_COOKED = "VEGETAL REPUGNANTE"
WX78.DESCRIBE.KYNO_RICE_SEEDS = "É CÓDIGO-FONTE PARA COMIDA QUE VEM DA TERRA"
WX78.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "É CÓDIGO-FONTE PARA COMIDA QUE VEM DA TERRA"
WX78.DESCRIBE.FARM_PLANT_KYNO_RICE = "É UM TALO DE ARROZ IDIOTA"
WX78.DESCRIBE.KYNO_RICE_OVERSIZED = "É UM TALO DE ARROZ IDIOTA"
WX78.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_SEEDS_KIT = "COISA IMUNDA"

WX78.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "CARNE ESTÚPIDA NUNCA DEVORARÁ PEDRA",
	PICKED = "ORGÂNICOS TEMPORARIAMENTE INDISPONÍVEIS",
	WITHERED = "AMBIENTE INADEQUADO PARA ORGÂNICOS",
}

WX78.DESCRIBE.KYNO_LIMPETS = "PEQUENA FONTE DE PROTEÍNA"
WX78.DESCRIBE.KYNO_LIMPETS_COOKED = "UMA MELHORIA BEM-VINDA"

WX78.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "UNIDADE ORGÂNICA DEPENDENTE DE ÁGUA",
	PICKED = "PRODUÇÃO DE FLORES INTERROMPIDA",
	BURNING = "ERRO CRÍTICO: COMBUSTÃO",
}

WX78.DESCRIBE.KYNO_LOTUS_ROOT = "NÃO APLICÁVEL FORA DA ÁGUA"
WX78.DESCRIBE.KYNO_LOTUS_FLOWER = "FLOR DE ÁGUA FEIA"
WX78.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "LIBEREI-A DE SUAS NECESSIDADES DE ÁGUA"

WX78.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "O MAR TAMBÉM POSSUI ERVAS?",
	PICKED = "RECRESCIMENTO PENDENTE",
	BURNING = "ERRO: FOGO EM AMBIENTE MARINHO",
}

WX78.DESCRIBE.KYNO_SEAWEEDS = "É GOSMENTO E NOJENTO"
WX78.DESCRIBE.KYNO_SEAWEEDS_COOKED = "UM LANCHE SAUDÁVEL"
WX78.DESCRIBE.KYNO_SEAWEEDS_DRIED = "ALIMENTO SAUDÁVEL"
WX78.DESCRIBE.KYNO_SEAWEEDS_ROOT = "NÃO APLICÁVEL FORA DA ÁGUA"

WX78.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "PLANTA AQUÁTICA REPUGNANTE",
	PICKED = "RECRESCIMENTO ACELERADO PELA ÁGUA",
	BURNING = "AVISO: COMBUSTÃO ORGÂNICA",
}

WX78.DESCRIBE.KYNO_TAROROOT_ROOT = "NÃO APLICÁVEL FORA DA ÁGUA"
WX78.DESCRIBE.KYNO_TAROROOT = "TÃO ROXO"
WX78.DESCRIBE.KYNO_TAROROOT_COOKED = "CHIQUE"

WX78.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "PLANTA REPUGNANTE",
	PICKED = "CICLO DE RECRESCIMENTO INICIADO",
	BURNING = "ANOMALIA DO SISTEMA: FOGO DETECTADO",
}

WX78.DESCRIBE.KYNO_WATERYCRESS_ROOT = "NÃO APLICÁVEL FORA DA ÁGUA"
WX78.DESCRIBE.KYNO_WATERYCRESS = "PLANTA NOJENTA"

WX78.DESCRIBE.WATERYCRESSBOWL = "É FEITO DO SANGUE DO MEU INIMIGO"

WX78.DESCRIBE.KYNO_SALT = "RUIM PARA CIRCUITOS"

WX78.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "ORGÂNICOS AQUÁTICOS CONECTADOS",
	PICKED = "ORGÂNICOS INDISPONÍVEIS",
	BURNING = "AVISO: COMBUSTÃO DE RECURSOS",
}

WX78.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "SISTEMA DE ATRAÇÃO E CRESCIMENTO DE PROTEÍNA"

WX78.DESCRIBE.CATFOOD = "É A PRINCIPAL FONTE DE ENERGIA PARA FELINOS."

WX78.DESCRIBE.KATFOOD = "É A PRINCIPAL FONTE DE ENERGIA PARA FELINOS."

WX78.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "EU DEVIA TER DEIXADO ISSO NO SUBSOLO",
	PICKED = "PRODUÇÃO DE FRUTOS TEMPORARIAMENTE INTERROMPIDA",
	CHOPPED = "PLANTA TERMINADA",
	BURNING = "AVISO: COMBUSTÃO DETECTADA",
	BURNT = "PLANTA REDUZIDA A CINZAS",
}

WX78.DESCRIBE.KYNO_BANANA = "MAIS CARBONO"
WX78.DESCRIBE.KYNO_BANANA_COOKED = "ESSAS COISAS COMIDA SÃO TÃO TEDIOSAS"

WX78.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "ESTA ÁRVORE É SÓ TRONCO",
	PICKED = "PRODUÇÃO DE FRUTOS PAUSADA",
	CHOPPED = "PLANTA TERMINADA",
	BURNING = "AVISO: COMBUSTÃO",
	BURNT = "PLANTA REDUZIDA A CINZAS",
}

WX78.DESCRIBE.KYNO_KOKONUT = "FRUTO BURRO"
WX78.DESCRIBE.KYNO_KOKONUT_HALVED = "NUTRIÇÃO AGORA ACESSÍVEL"
WX78.DESCRIBE.KYNO_KOKONUT_COOKED = "AROMA TOSTADO NÃO ME AJUDA"

WX78.DESCRIBE.BOWLOFPOPCORN = "CALORIAS VAZIAS"

WX78.DESCRIBE.FIGJUICE = "BEBIDA REFRESCANTE FEITA DE FRUTAS ESTÚPIDAS"

WX78.DESCRIBE.COCONUTWATER = "ESSA ÁGUA CONTÉM UM CÓDIGO DIFERENTE"

WX78.DESCRIBE.EYEBALLSPAGHETTI = "ACREDITO QUE ESTÁ ME OLHANDO"

WX78.DESCRIBE.FORGETMELOTS_SEEDS = "CÓDIGO-FONTE PARA COMIDA QUE VEM DA TERRA"

WX78.DESCRIBE.FIRENETTLES_SEEDS = "CÓDIGO-FONTE PARA COMIDA QUE VEM DA TERRA"

WX78.DESCRIBE.TILLWEED_SEEDS = "CÓDIGO-FONTE PARA COMIDA QUE VEM DA TERRA"

WX78.DESCRIBE.KYNO_FLOATILIZER = "BALDE DE RESÍDUOS MARINHOS"

WX78.DESCRIBE.KYNO_TWIGGYNUTS = "ESSAS NOZES"

WX78.DESCRIBE.KYNO_REPAIRTOOL = "UNIDADE DE REPARO MONTADA"

WX78.DESCRIBE.KYNO_KOI = "POSSO APRECIAR SEU BRILHO DOURADO"
WX78.DESCRIBE.KYNO_KOI_COOKED = "POSSO APRECIAR SEU BRILHO DOURADO"

WX78.DESCRIBE.KYNO_TROPICALFISH = "VOCÊ É TROPICAL E UM PEIXE"
WX78.DESCRIBE.KYNO_TROPICALFISH_COOKED = "HA! BOA RAZÃO PARA IR EMBORA"

WX78.DESCRIBE.KYNO_NEONFISH = "ESSE PEIXE ESTÁ MAIS SECO QUE OS OUTROS"
WX78.DESCRIBE.KYNO_NEONFISH_COOKED = "ABSORVEREI SEU PODER DE SECAGEM"

WX78.DESCRIBE.KYNO_GROUPER = "RESGATEI ELE DA ÁGUA. INGRATO"
WX78.DESCRIBE.KYNO_GROUPER_COOKED = "AGORA É COMBUSTÍVEL DE ROBÔ. HA HA"
 
WX78.DESCRIBE.KYNO_PIERROTFISH = "VIVE SUBMERGIDO NA ÁGUA. TERRÍVEL"
WX78.DESCRIBE.KYNO_PIERROTFISH_COOKED = "EU VOU COMER ESTE HABITANTE HORRÍVEL DA ÁGUA"

WX78.DESCRIBE.KYNO_SALMONFISH = "CRIATURA AQUÁTICA MOLENGA"
WX78.DESCRIBE.KYNO_SALMONFISH_COOKED = "SUA FRAQUEZA É O FOGO"

WX78.DESCRIBE.TURF_PINKPARK = "COR ROSA ESTÁ ME CORANDO"
WX78.DESCRIBE.TURF_STONECITY = "PARTES DO CHÃO"
WX78.DESCRIBE.TURF_FIELDS = "PARTES DO CHÃO"
WX78.DESCRIBE.TURF_TIDALMARSH = "PARTES DO CHÃO."

WX78.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "CUIDADO: EVITE RESPINGOS DE LÍQUIDO NOS CIRCUITOS",
	PICKED = "CONTATO COM ÁGUA EVITADO COM SUCESSO",
}

WX78.DESCRIBE.KYNO_SALTRACK_INSTALLER = "ALGUMA MONTAGEM NECESSÁRIA"

WX78.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "PARA SUGAR O LIQUIDO DAS ÁRVORES"

WX78.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "APREDE CRIATURAS ROCHOSAS"

WX78.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "ESTE SUÍNO DE GRANDE PORTE COMANDA OS MENORES",
	SLEEPING = "MODO DE SONO PROFUNDO ATIVADO",
}

WX78.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "UMA ÁRVORE ROSA HEDIONDA",
	CHOPPED = "FONTE DE REFRIGERANTE VEGETAL DESTRUÍDA",
	SAPPED = "HORA DE COLETAR O REFRIGERANTE",
	PICKED = "EXIJO QUE RECARREGUE MAIS RÁPIDO",
	BURNING = "AVISO: COMBUSTÃO",
	BURNT = "ORGANISMO IMUNDO DESTRUÍDO",
}

WX78.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "TRONCO SOFREU DANO",
	CHOPPED = "UNIDADE DEFEITUOSA REMOVIDA",
	SAPPED = "SEIVA ARRUINADA PRONTA",
	PICKED = "UNIDADES BIOLÓGICAS MINÚSCULAS SABOTARAM A COLETA",
	BURNING = "CONTAMINANTE SENDO PURGADO",
	BURNT = "UNIDADE TERMINADA",
}

WX78.DESCRIBE.KYNO_SUGARTREE_BUD = "UNIDADE CONTENEDORA DE AÇÚCAR"

WX78.DESCRIBE.KYNO_SUGARTREE_FLOWER = "MINHA APRECIAÇÃO PELA BELEZA É LIMITADA"
WX78.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "MINHA APRECIAÇÃO PELA BELEZA É LIMITADA"

WX78.DESCRIBE.KYNO_SUGARTREE_PETALS = "MINHA APRECIAÇÃO PELA BELEZA É LIMITADA"

WX78.DESCRIBE.KYNO_PEBBLECRAB = "PARECE UMA PEDRA. MAS VIVA E PIOR"

WX78.DESCRIBE.KYNO_CRABMEAT = "CARNE DA CRIATURA ROCHOSA"
WX78.DESCRIBE.KYNO_CRABMEAT_COOKED = "CARNE ROCHOSA DELICIOSA"
WX78.DESCRIBE.KYNO_CRABMEAT_DRIED = "CARNE DA CRIATURA ROCHOSA"

WX78.DESCRIBE.KYNO_CRABKINGMEAT = "CARNE DA CRIATURA ROCHOSA"
WX78.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "CARNE DA CRIATURA ROCHOSA"
WX78.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "CARNE DA CRIATURA ROCHOSA"

WX78.DESCRIBE.KYNO_SLAUGHTERTOOL = "PARA DESMONTAR FORMAS DE VIDA BIOLÓGICAS"

WX78.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "ERRO: NÃO COMPUTA",
	COOP = "UNIDADE ORGÂNICA CONTIDA COM SUCESSO",
}

WX78.DESCRIBE.KYNO_CHICKEN_EGG = "EU TE ODEIO, OVO"
WX78.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "UMA UNIDADE DE PROTEÇÃO SUPERIOR"
WX78.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "ISTO DEVERIA SER UMA MELHORIA"

WX78.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "ESTRUTURA DE CONTENÇÃO AVIÁRIA",
	FULL = "PRODUÇÃO MÁXIMA DE OVOS ATINGIDA",
	BURNT = "FALHA DA UNIDADE: MATÉRIA ORGÂNICA DESTRUÍDA",
}

WX78.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "PATÉTICO. NEM SABEM MONTAR UMA PANELA DECENTE"

WX78.DESCRIBE.KYNO_COOKWARE_KIT = "UM MODELO DE COZINHA PRONTO"
WX78.DESCRIBE.KYNO_COOKWARE_SYRUP = "PRECISA DE SACAROSE E FOGO PARA PRODUZIR MAIS SACAROSE"
WX78.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "PRECISA DE SACAROSE E FOGO PARA PRODUZIR MAIS SACAROSE"
WX78.DESCRIBE.KYNO_COOKWARE_BIG_POT = "ESTA PANELA TEM UM TAMANHO DE MEMÓRIA ACEITÁVEL"
WX78.DESCRIBE.KYNO_COOKWARE_BIG = "ESTA PANELA TEM UM TAMANHO DE MEMÓRIA ACEITÁVEL"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "ESTA PANELA TEM TAMANHO DE MEMÓRIA INADEQUADO"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL = "ESTA PANELA TEM TAMANHO DE MEMÓRIA INADEQUADO"
WX78.DESCRIBE.KYNO_COOKWARE_GRILL = "ADICIONAR FOGO À COMIDA AUMENTA SEU VALOR"
WX78.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "ALGUMA MONTAGEM NECESSÁRIA"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "SLOTS DE MEMÓRIA INADEQUADOS"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "ALGUMA MONTAGEM NECESSÁRIA"
WX78.DESCRIBE.KYNO_COOKWARE_ELDER = "EXIGE SACAROSE E FOGO PARA PRODUZIR MAIS SACAROSE"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "ESTE ROBÔ AINDA NÃO FOI CONSTRUÍDO"
WX78.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "PARA MONTAR UMA MISTURA"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "SEUS SLOTS DE MEMÓRIA PRECISAM DE UPGRADE"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN = "ADMIRO A GRANDE BOCA DE FOGO DESTE ROBÔ"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "ADMIRO A GRANDE BOCA DE FOGO DESTE ROBÔ"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "ADMIRO A GRANDE BOCA DE FOGO DESTE ROBÔ"

WX78.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "VIRE A PEDRA PARA EXECUTAR FUNÇÃO DE BUSCA",
	FLIPPED = "MATERIAIS OCULTOS REVELADOS",
}

WX78.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "RESÍDUOS DETECTADOS"

WX78.DESCRIBE.KYNO_SUGARFLY = "ACHA QUE É BONITA"
WX78.DESCRIBE.KYNO_SUGARFLYWINGS = "IRIDESCENTE"

WX78.DESCRIBE.KYNO_WATERY_CRATE = "DETALHES DE JETOSAM DETECTADOS"

WX78.DESCRIBE.KYNO_TUNACAN = "ALIMENTO HERMETICAMENTE SELADO"
WX78.DESCRIBE.KYNO_TUNACAN_OPEN = "ALIMENTO HERMETICAMENTE ABERTO"

WX78.DESCRIBE.KYNO_CANNEDFOOD = "ALIMENTO HERMETICAMENTE SELADO"
WX78.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "ALIMENTO HERMETICAMENTE ABERTO"

WX78.DESCRIBE.KYNO_POP = "ISSO É COMESTÍVEL?"

WX78.DESCRIBE.KYNO_MYSTERYMEAT = "É CARNE. SEM MISTÉRIO AQUI"

WX78.DESCRIBE.KYNO_BOTTLE_SOUL = "UMA ALMA-ENGARRAFADA, GOSTO DE SEU MÓDULO DE ARMAZENAMENTO"

WX78.DESCRIBE.SOULSTEW = "UMA SOPA-DE-ALMA, GOSTO DE SEU DESIGN"

WX78.DESCRIBE.FORTUNECOOKIE = "SOMENTE ALGUMAS PALAVRAS SEM SIGNIFICADO"

WX78.DESCRIBE.HORNOCUPIA = "ESTA PEÇA É PARA TORTURAR FLESHLINGS FAMINTOS"

WX78.DESCRIBE.CHEESE_YELLOW = "HA HA, ADORO COISAS DE QUEIJO"
WX78.DESCRIBE.CHEESE_WHITE = "HA HA, ADORO COISAS DE QUEIJO"
WX78.DESCRIBE.CHEESE_KOALEFANT = "HA HA, ADORO COISAS DE QUEIJO"

WX78.DESCRIBE.MILK_BOX = "FLUIDO COMESTÍVEL DE ANIMAIS IMUNDOSOS"

WX78.DESCRIBE.WATERCUP = "EU... EU SIMPLESMENTE NÃO CONSIGO..."

WX78.DESCRIBE.HONEYJAR = "PEGAJOSO E DOCINHO"

WX78.DESCRIBE.CRAB_ARTICHOKE = "CARNE DE PEQUENOS COLETA COM PRECISÃO"

WX78.DESCRIBE.PEPPERROLLS = "EU VOU CONSUMIR. EU PRECISO"

WX78.DESCRIBE.KYNO_SAPHEALER = "ELIMINA CONTÁGIOS DAS FUNÇÕES PRINCIPAIS"

WX78.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "CAPITANIA INSUFICIENTE",
	PICKED = "CRESCIMENTO ORGÂNICO TEMPORARIAMENTE AUSENTE",
	BURNING = "INTEGRIDADE ESTRUTURAL COMPROMETIDA",
}

WX78.DESCRIBE.KYNO_GHOST_PIRATE = "ARRR ÉS UMA ALMA INQUIETA?"

WX78.DESCRIBE.KYNO_BUCKET_EMPTY = "MÓDULO DE ARMAZENAMENTO PARA LÍQUIDOS"
WX78.DESCRIBE.KYNO_BUCKET_METAL = "CAIXA DE ARMAZENAMENTO PARA LÍQUIDOS"
WX78.DESCRIBE.KYNO_BUCKET_WATER = "LÍQUIDO INÚTIL PARA FORMAS DE VIDA BIOLÓGICAS"

WX78.DESCRIBE.KYNO_MILK_BEEFALO = "LEITE DE FONTES NATURAIS"
WX78.DESCRIBE.KYNO_MILK_KOALEFANT = "LEITE DE FONTES NATURAIS"

WX78.DESCRIBE.KYNO_CAP_DRIED = "ODEIO COMO PARECE. POBRE ARTE DA NATUREZA"

WX78.DESCRIBE.KYNO_PLANTMEAT_DRIED = "PROTEÍNAS DESIDRATADAS"

WX78.DESCRIBE.KYNO_BREWBOOK = "DIRECTÓRIO DE BEBIDAS"

WX78.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "HARDWARE PARA LÍQUIDOS",
	BREWING_LONG = "PROCESSO EM ESTÁGIO INICIAL",
	BREWING_SHORT = "PROCESSO PRÓXIMO DA CONCLUSÃO",
	DONE = "FERMENTAÇÃO COMPLETA",
	BURNT = "CONTÊINER DESTRUÍDO",
}

WX78.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "HARDWARE COM CAPACIDADE DE PRESERVAÇÃO",
	BREWING_LONG = "PROCESSO DE PRESERVAÇÃO EM ANDAMENTO",
	BREWING_SHORT = "PROCESSO PRÓXIMO DA CONCLUSÃO",
	DONE = "PRESERVAÇÃO COMPLETA",
	BURNT = "FALHA DO CONTÊINER",
}

WX78.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "CONVERSOR E ARMAZENAMENTO DE MEL",
	HONEY = "NÍVEL DE MEL ACEITÁVEL",
	NECTAR = "PROCESSAMENTO DE NÉCTAR EM ANDAMENTO",
	BURNING = "ERRO: COMBUSTÃO DE RECURSOS",
}

WX78.DESCRIBE.KYNO_NECTAR_POD = "PRECISA DE CONVERSOR DE MEL PARA SER ÚTIL"

WX78.DESCRIBE.KYNO_OAKTREE_POD = "CONTÊINER DE ENERGIA MULTIUSO"
WX78.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "PACOTE DE ENERGIA BIOLÓGICA"

WX78.DESCRIBE.KYNO_PIKO = "MÁQUINA DE RECOLHER NOZES"
WX78.DESCRIBE.KYNO_PIKO_ORANGE = "MÁQUINA DE CARNE COM PROPRIEDADES PARA FAZER CHÁ"

WX78.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "FORMA DE VIDA LENHOSA IMÓVEL",
	CHOPPED = "EXTRAÇÃO DE RECURSOS COMPLETA",
	BURNING = "AVISO: COMBUSTÃO",
	BURNT = "ESPÉCIME DESTRUÍDO",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "FORMA DE VIDA LENHOSA INFESTADA POR ORGANISMOS IMUNDOS",
	BURNING = "TERMINAÇÃO DE HABITAT EM ANDAMENTO",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "EVIDÊNCIA DE UMA CALAMIDADE MARINHA"

WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "HABITAÇÃO OBSOLETA",
	BURNT = "ESTRUTURA DESTRUÍDA",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "ATUALIZAÇÃO DO SISTEMA OLFATIVO: PEIXE MÁXIMO",
	CRAFTED = "QUALIDADE ESTRUTURAL MELHORADA",
	BURNT = "NÍVEIS DE ODOR INACEITÁVEIS",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "INSTALAÇÃO DE TROCA DE PEIXES",
	OCCUPIED = "FORNECEDOR INDISPONÍVEL",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "ROUBAR É ERRADO, MAS ESTE SUJEITO NÃO SE IMPORTARIA",
	EMPTY = "INVENTÁRIO ESGOTADO",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "É VOCÊ. O MERCADOR DE PEIXES QUE ME VENDU SEMENTES UMA VEZ"
WX78.DESCRIBE.KYNO_MEADOWISLAND_POND = "FORMA DE ÁGUA NATURALMENTE OCORRENTE"
WX78.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "É UMA PLANTA DESINTERESSANTE"
WX78.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "O PÓ DE ROCHA ESTÁ SE ACUMULANDO EM MONTES"
WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "ATUALIZAÇÃO DE SISTEMA DE IDENTIFICAÇÃO DE AROMA: CHEIRO DE PEIXE"

WX78.DESCRIBE.KYNO_SAMMYHAT = "CHAPÉU DO MERCADOR"

WX78.DESCRIBE.KINGFISHER = "UM PÁSSARO COM MECANISMO DE BICO GRANDE"

WX78.DESCRIBE.TOUCAN = "VOCÊ TEM UMA QUANTIDADE DESPROPORCIONAL DE NARIZ"
WX78.DESCRIBE.TOUCAN_CHUBBY = "VOCÊ POSSUI UMA QUANTIDADE DESPROPORCIONAL DE NARIZ"

WX78.DESCRIBE.WETGOOP2 = "IMUNDÍCIA COMESTÍVEL"

WX78.DESCRIBE.BEER = "A BEBIDA PERFEITA"

WX78.DESCRIBE.PALEALE = "A BEBIDA PERFEITA"

WX78.DESCRIBE.TEAGREEN = "ESTE LÍQUIDO TEM PROPRIEDADES ESTRANHAS QUE ACALMAM MEUS SISTEMAS"

WX78.DESCRIBE.TEARED = "ESTE LÍQUIDO TEM PROPRIEDADES ESTRANHAS QUE ACALMAM MEUS SISTEMAS"

WX78.DESCRIBE.MEAD = "AMARGO E DOCE"

WX78.DESCRIBE.KYNO_JELLY = "HÁ GELEIA EM MINHOS CIRCUITOS"

WX78.DESCRIBE.KYNO_MAYONNAISE = "CREMOSO"

WX78.DESCRIBE.TARTARSAUCE = "NÃOOOOOOOO!"

WX78.DESCRIBE.KYNO_PICKLES = "REPUGNANTE"

WX78.DESCRIBE.KYNO_WINE = "AMARGO E REFRESCANTE"

WX78.DESCRIBE.KYNO_JUICE = "AAHHH"

WX78.DESCRIBE.KYNO_POISON_FROGLEGS = "AVISO: MECANISMO DA PERNA CONTÉM TOXINA"
WX78.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "MECANISMO TÓXICO DA PERNA QUEIMADO"

WX78.DESCRIBE.POISONFROGGLEBUNWICH = "COMBUSTÍVEL DE SAPO DELICIOSO"

WX78.DESCRIBE.KYNO_BREWINGRECIPECARD = "ERRO: RECEITA DE CERVEJA ILEGÍVEL"

WX78.DESCRIBE.KYNO_OIL = "É ÓLEO. MAS NÃO PARA MINHA HARDWARE"

WX78.DESCRIBE.BERRYSUNDAE = "DOCE LÁCTEO"

WX78.DESCRIBE.CHOCOLATE_BLACK = "DOCE LÁCTEO"
WX78.DESCRIBE.CHOCOLATE_WHITE = "DOCE LÁCTEO"

WX78.DESCRIBE.TRICOLORDANGO = "B-B-BOLINHAS DOCES?"
 
WX78.DESCRIBE.FRIESFRENCH = "BATATAS FRITAS EM ÓLEO PARA ALCANÇAR SABOR MÁXIMO"

WX78.DESCRIBE.PIRATERUM = "LÍQUIDO MISTERIOSO E POSSIVELMENTE PERIGOSO DENTRO"

WX78.DESCRIBE.TWISTEDTEQUILA = "ANÁLISE DE SISTEMA: LÍQUIDO PROVOCA EFEITOS ESTRANHOS DE ESPAÇO E TEMPO"

WX78.DESCRIBE.ONIONRINGS = "CONTÉM QUANTIDADE ADEQUADA DE ÓLEO. ENTÃO DEVE SER BOA"

WX78.DESCRIBE.DONUTS = "MASSA DE ROSQUINHAS. MWUHAHA"
WX78.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "MASSA DE ROSQUINHAS. MWUHAHA"
WX78.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "MASSA DE ROSQUINHAS. MWUHAHA"
 
WX78.DESCRIBE.CINNAMONROLL = "É UM PÃO DE AÇÚCAR"

WX78.DESCRIBE.GUMMYBEARGERS = "AVISO: NÍVEIS PERIGOSOS DE FOFOCIDADE"

WX78.DESCRIBE.PRETZEL = "PRETZEL BONITO"

WX78.DESCRIBE.CORNINCUP = "MILHO EM COPO"

WX78.DESCRIBE.COTTONCANDY = "COMIDA FEITA DE AR"

WX78.DESCRIBE.ROASTEDHAZELNUTS = "ACABEI DE TORRAR ALGUMAS NOZES. HA HA"

WX78.DESCRIBE.MONSTERMUFFIN = "NÃO É UM MUFFIN. SOMENTE MALDADE"

WX78.DESCRIBE.PINKCAKE = "ESTÁ MUITO ROSA PARA MIM, DEVO DESTRUIR COMENDO"

WX78.DESCRIBE.CHIPSBAG = "BATATAS INDUSTRIALIZADAS DENTRO DE SACO CHEIO DE AR"

WX78.DESCRIBE.LITTLEBREAD = "INGREDIENTE PARA RECEITAS MELHORES"

WX78.DESCRIBE.HOTHOUND = "LANCHINHO CLÁSSICO"

WX78.DESCRIBE.MILKSHAKE = "PRIMEIRO EU MAMOU O LEITE. DEPOIS BATI"
WX78.DESCRIBE.MILKSHAKE_PRISMATIC = "PRIMEIRO EU MAMOU O LEITE. DEPOIS BATI"

WX78.DESCRIBE.NACHOS = "EU PEGUEI O MOLHO E OS NACHOS"

WX78.DESCRIBE.BANANA_PUDDING = "BANANAS"

WX78.DESCRIBE.SEA_PUDDING = "PEIXENTO"

WX78.DESCRIBE.TOM_KHA_SOUP = "SOPA REPULSIVA FEITA COM INGREDIENTES REPULSIVOS"

WX78.DESCRIBE.MINERTREAT = "NÃO... PODE SER... ESSA VERSÃO!"

WX78.DESCRIBE.RADISHSALAD = "SALADA MONTADA: CONCLUÍDA"

WX78.DESCRIBE.PUMPKIN_SOUP = "ENERGIA EM UMA TIGELA"

WX78.DESCRIBE.ALGAE_SOUP = "ENERGIA EM UMA TIGELA"

WX78.DESCRIBE.PARZNIP_SOUP = "ENERGIA EM UMA TIGELA"

WX78.DESCRIBE.NETTLEMEATED = "EJETOR DE IRRITAÇÃO NASAL COM ANEXO DE CARNE"

WX78.DESCRIBE.KYNO_SUGAR = "É BOM PARA REFEIÇÕES DOCES"

WX78.DESCRIBE.KYNO_BOTTLECAP = "ANÁLISE DE SISTEMA: POTENCIAL LUCRO EM OURO"

WX78.DESCRIBE.NUKACOLA = "ANÁLISE DO SISTEMA: COMBUSTÍVEL INTERDIMENSIONAL PÓS-APOCALÍPTICO"
WX78.DESCRIBE.NUKACOLA_QUANTUM = "ANÁLISE DO SISTEMA: COMBUSTÍVEL INTERDIMENSIONAL PÓS-APOCALÍPTICO"

WX78.DESCRIBE.LIVINGSANDWICH = "ATENÇÃO: COMBUSTÍVEL MÁGICO SUSPEITO"

WX78.DESCRIBE.DURIANSPLIT = "LATICÍNIO DOCE"

WX78.DESCRIBE.DURIANSOUP = "UM CALDO FEITO DE DURIANS"

WX78.DESCRIBE.DURIANMEATED = "BOM QUE EU NÃO TENHO NARIZ"

WX78.DESCRIBE.DURIANCHICKEN = "VEGETAIS FESTIVOS"

WX78.DESCRIBE.LUNARSOUP = "A LUA SERÁ MINHA"

WX78.DESCRIBE.PURPLEWOBSTERSOUP = "ESSA FORMA DE VIDA IMUNDA AGORA É MEU COMBUSTÍVEL"

WX78.DESCRIBE.WOBSTERMONSTER = "FORMA DE VIDA LEVIATÃ"

WX78.DESCRIBE.SPIDERCAKE = "ESSA É UMA MONSTRUOSIDADE ESCANDALOSA"

WX78.DESCRIBE.SUGARBOMBS = "ESTOU COMEÇANDO A TER FLASHBACKS QUE NÃO SÃO DO MEU BANCO DE MEMÓRIA"

WX78.DESCRIBE.BERRYBOMBS = "BAGAS DENTRO DA UNIDADE DE ARMAZENAMENTO"

WX78.DESCRIBE.ONIGIRIS = "GRÃOS EM FORMA TRIANGULAR"

WX78.DESCRIBE.OMURICE = "ANÁLISE COMPLETA: ARROZ FRITO COM MOLHO DE TOMATE"

WX78.DESCRIBE.PAELLA = "GRÃOS E... PROCESSAMENTO... FORMAS DE VIDA MARINHAS INFERIORES"

WX78.DESCRIBE.RISOTTO = "GRÃOS E COGUMELOS SELVAGENS IMUNDOS"

WX78.DESCRIBE.RICESAKE = "ELES PARECEM TÃO BOBOS QUANDO BEBEM ISSO"

WX78.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "ARBUSTO DE FRUTAS ESPINHOSAS ESTÚPIDO E BURRO"

WX78.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "ARBUSTO DE FRUTA ESPINHOSA ESTÚPIDO",
	PICKED = "PRODUÇÃO DE FRUTOS INTERROMPIDA",
	WITHERED = "UMIDADE INSUFICIENTE",
	BURNING = "AVISO: COMBUSTÃO",
}

WX78.DESCRIBE.KYNO_PINEAPPLE = "FRUTA ESPINHOSA BURRA"
WX78.DESCRIBE.KYNO_PINEAPPLE_HALVED = "FRUTA ESPINHOSA BURRA"
WX78.DESCRIBE.KYNO_PINEAPPLE_COOKED = "ACEITÁVEL AGORA"

WX78.DESCRIBE.PIZZA_TROPICAL = "OH MEU... O QUE FIZERAM COM VOCÊ"

WX78.DESCRIBE.PINACOLADA = "ISSO SIMPLESMENTE NÃO É POSSÍVEL"

WX78.DESCRIBE.CHIMAS = "ENCARNAÇÃO DO GOSTO RUIM"

WX78.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "SISTEMA DE HIDRATAÇÃO INATIVO",
	ON = "UMA BARRAGEM INIMIGA!",
}

WX78.DESCRIBE.KYNO_FOODSACK = "TRAVA A FRESCURA"

WX78.DESCRIBE.GUMMYWORMS = "HA. COMO VOCÊS SE SENTEM AGORA?"

WX78.DESCRIBE.SMORES = "NOZES E MARSHMALLOWS"

WX78.DESCRIBE.NUKASHINE = "ESSA BEBIDA ESTÁ TENTANDO INSTALAR MALWARE EM MEUS SISTEMAS!"

WX78.DESCRIBE.ANTSLOG = "ABOMINAÇÃO"

WX78.DESCRIBE.KYNO_WORM_BONE = "HAHA. UNIDADES BIOLÓGICAS SÃO TÃO FRÁGEIS"

WX78.DESCRIBE.SPOOKY_BRAIN_NOODLES = "COMER MEMÓRIAS DE FRACOS NÃO IRÁ MELHORAR MEUS SISTEMAS"
WX78.DESCRIBE.SPOOKY_BURGERZILLA = "UMA TENTATIVA FALHA DE RECRIAÇÃO MONSTRUOSA DE HAMBÚRGUER"
WX78.DESCRIBE.SPOOKY_DEADBREAD = "SE AO MENOS ELE FOSSE UM DOS INGREDIENTES"
WX78.DESCRIBE.SPOOKY_JELLYBEANS = "UM PACOTE DE MÓDULOS DE VISÃO"
WX78.DESCRIBE.SPOOKY_POPSICLE = "QUEIMEM-NOS"
WX78.DESCRIBE.SPOOKY_PUMPKINCREAM = "QUE CRIAÇÃO HIDEOUS É ESSA"
WX78.DESCRIBE.SPOOKY_SKULLCANDY = "DOCE ESTÚPIDO PODE TRAZER DE VOLTA FRACOS"
WX78.DESCRIBE.SPOOKY_TACODILE = "ESPEREM QUE A MÃE DELES NÃO ME PERCA"

WX78.DESCRIBE.BUTTER_BEEFALO = "CUBO DENSO DE FLUIDOS ANIMAIS PROCESSADOS"
WX78.DESCRIBE.BUTTER_GOAT = "CUBO DENSO DE FLUIDOS ANIMAIS PROCESSADOS"
WX78.DESCRIBE.BUTTER_KOALEFANT = "CUBO DENSO DE FLUIDOS ANIMAIS PROCESSADOS"

WX78.DESCRIBE.SPICE_CURE = "ADICIONAL DE FIRMWARE PARA PRESERVAR CÁPSULAS DE COMBUSTÍVEL"
WX78.DESCRIBE.SPICE_COLD = "ADICIONAL DE FRIO PARA O SISTEMA CENTRAL"
WX78.DESCRIBE.SPICE_FIRE = "ADICIONAL DE FOGO PARA O SISTEMA CENTRAL AVISO: PODE CAUSAR SOBREAQUECIMENTO"
WX78.DESCRIBE.SPICE_FED = "ALTAS CALORIAS PARA FAZER O SISTEMA TRABALHAR MAIS RÁPIDO"
WX78.DESCRIBE.SPICE_MIND = "APLICAÇÃO CALMANTE"

WX78.DESCRIBE.SUGARFLYMUFFIN = "A INOCÊNCIA ADICIONA SABOR"

WX78.DESCRIBE.EELTACOS = "A ENGUIA CUMPRIU SEU PROPÓSITO SUPERIOR"

WX78.DESCRIBE.MEATSKILLET = "SE SENTINDO AVENTUREIRO HOJE, NÃO É?"

WX78.DESCRIBE.MEATWALTZ = "POR QUE AQUELA MULHER ESTÚPIDA GOSTA TANTO DE CARNE CRUA"

WX78.DESCRIBE.COMPLETEBREAKFAST = "CONTÉM ALTAS CALORIAS"

WX78.DESCRIBE.DUMPLINGS = "COMIDA EXQUISITA"

WX78.DESCRIBE.WARLYICEDTEA = "BEBIDA REFRESCANTE FEITA PELO MEU INIMIGO"

WX78.DESCRIBE.WARLYTEA = "LÍQUIDO ADQUIRIDO DE UMA MÁQUINA DE CARNE"

WX78.DESCRIBE.KYNO_TEALEAF = "ORGANISMO ORGÂNICO PARA FAZER LÍQUIDO RELAXANTE"

WX78.DESCRIBE.KYNO_ITEMSLICER = "LÂMINA GROSSA PARA FATIAR"
WX78.DESCRIBE.KYNO_ITEMSLICER_GOLD = "LÂMINA GROSSA PARA FATIAR PROFISSIONALMENTE"

WX78.DESCRIBE.COXINHA = "PARTES SEPARADAS DESSE ANIMAL ESTÚPIDO"

WX78.DESCRIBE.LAZYDESSERT = "QUE PENA. NÃO É UM DOCE RARO"

WX78.DESCRIBE.CRABKINGFEAST = "COMO? COMO? COMO ISSA COISA PODE CABER NA PANELA?"

WX78.DESCRIBE.PIENAPPLE = "FRACOS ORGÂNICOS NÃO VENCERÃO MEUS SISTEMAS DIGESTIVOS"

WX78.DESCRIBE.JAWSBREAKER = "ISCA PARA ORGANISMOS MARINHOS AGRESSIVOS"

WX78.DESCRIBE.AVOCADOTOAST = "NOJENTO"

WX78.DESCRIBE.RICEPUDDING = "MISTURA DE VEGETAIS NOJENTA"

WX78.DESCRIBE.SHARKSUSHI = "HA HA TUBARÕES ESTÚPIDOS NÃO IRÃO MEXER COM O SER SUPERIOR DE NOVO"

WX78.DESCRIBE.WOBSTERBREADED = "SUA ARMADURA NÃO TE MANTEVE SEGURO"

WX78.DESCRIBE.LAZYPURRITO = "É TÃO NOJENTO QUANTO O ANIMAL EM QUE FOI BASEADO"

WX78.DESCRIBE.HORCHATA = "VOCÊ SÓ PODE ESTAR BRINCANDO? É SÓ LEITE E GELO"

WX78.DESCRIBE.WOBSTERCOCKTAIL = "COMIDA DE LUXO"

WX78.DESCRIBE.LAVAEEGGBOILED = "ANÁLISE COMPLETA: COMPONENTES À PROVA DE FOGO DETECTADOS"

WX78.DESCRIBE.POMEGRANATETEA = "BEBIDA REFRESCANTE FEITA DO MEU INIMIGO"

WX78.DESCRIBE.TIRAMISU = "CONTÉM CAFEÍNA E PROPRIEDADES SECAS"

WX78.DESCRIBE.TOADSTOOLCOLA = "UM ADICIONAL CONSUMÍVEL PARA CAUSAR CAOS EM ANFÍBIOS"

WX78.DESCRIBE.TEPACHE = "NÍVEIS DE AÇÚCAR AUMENTADOS"

WX78.DESCRIBE.LUNARTEQUILA = "O PODER DA LUA FINALMENTE EM MINHAS MÃOS"

WX78.DESCRIBE.MIMICMOSA = "ANÁLISE: PROPRIEDADES DE CAMUFLAGEM DETECTADAS"

WX78.DESCRIBE.POMEGRANATEPIE = "TORTA DE FRUTAS"

WX78.DESCRIBE.PINEAPPLECAKE = "MONTANHA DE AÇÚCAR PURO"

WX78.DESCRIBE.PASTY_MEAT = "POSSO PEGAR APENAS O ÓLEO?"
WX78.DESCRIBE.PASTY_CHEESE = "POSSO PEGAR APENAS O ÓLEO?"

WX78.DESCRIBE.BRIGADEIRO = "PRECISO DO MEU PRÓPRIO BRIGADEIRO"

WX78.DESCRIBE.REGULARLASAGNA = "PELO MENOS NÃO É AQUELE MONSTRO"

WX78.DESCRIBE.FLTSANDWICH = "ELAS MERECIAM"

WX78.DESCRIBE.RICEANDBEANS = "NOJENTO"

WX78.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "ESTRUTURA: OBSOLETA. ATUALIZAÇÃO: PENDENTE. PREVISTO: 2026."

WX78.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "MATERIAL ORGÂNICO RARO DETECTADO",
	PICKED = "RECURSO ESGOTADO",
	BURNING = "ERRO: RECURSO INCINERADO",
}

WX78.DESCRIBE.KYNO_TRUFFLES = "INGREDIENTE GOURMET DETECTADO"
WX78.DESCRIBE.KYNO_TRUFFLES_COOKED = "DADOS: SABOR APRIMORADO APÓS APLICAÇÃO DE CALOR"

WX78.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "UNIDADE DE EXIBIÇÃO INÚTIL PARA COMBUSTÍVEL ORGÂNICO",
	FULL = "RESULTADO CULINÁRIO ACEITÁVEL",
}

WX78.DESCRIBE.KYNO_SPORECAP = "CONTAMINAÇÃO ORGÂNICA DETECTADA"
WX78.DESCRIBE.KYNO_SPORECAP_COOKED = "NÍVEL DE BIOHAZARD REDUZIDO"

WX78.DESCRIBE.KYNO_SPORECAP_DARK = "COMPOSTOS ORGÂNICOS MORTAIS DETECTADOS"
WX78.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "NÍVEIS DE TOXINA INALTERADOS"

WX78.DESCRIBE.KYNO_GOLDENAPPLE = "ARTEFATO DE PODER INIGUALÁVEL DETECTADO"

WX78.DESCRIBE.TRUFFLESGRINDER = "CARNE FÚNGICA CONSUMÍVEL. SAÍDA DE ENERGIA: ACEITÁVEL"

WX78.DESCRIBE.SPORECAPPIE = "MATERIAL ORGÂNICO PERIGOSO."

WX78.DESCRIBE.SPORECAP_SKEWERS = "MASSA FÚNGICA QUEIMADA. PERFIL DE SABOR: ACEITÁVEL"

WX78.DESCRIBE.TRUFFLEOIL = "LÍQUIDO ORGÂNICO VISCOSO. INÚTIL, MAS ESCORREGADIO."

WX78.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "SOFTWARE DE CONSTRUÇÃO INICIADO"
WX78.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "INSTALAÇÃO DE REPRODUÇÃO AQUÁTICA: EM CONSTRUÇÃO"

WX78.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "MÓDULO DE DESOVA DE PEIXES: ONLINE",
	FUEL_HIGH = "NÍVEIS DE ALIMENTAÇÃO ÓTIMOS",
	FUEL_MED = "NÍVEIS DE ALIMENTAÇÃO ACEITÁVEIS",
	FUEL_LOW = "AVISO: COMIDA PRESTES A ACABAR",
	EMPTY = "ERRO: NENHUMA COMIDA DETECTADA",
}

WX78.DESCRIBE.KYNO_ANTCHOVY = "CRIATURA HÍBRIDA DETECTADA. DESIGN POUCO OTIMIZADO."
WX78.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "COLÔNIA DE HÍBRIDOS. COMPORTAMENTO IRRACIONAL DETECTADO."

WX78.DESCRIBE.AGEDROE = "ESPEREI MOVIMENTO. FUI DECEPCIONADO."
WX78.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "NANOESFERAS NUTRICIONAIS DE ALTO VALOR DETECTADAS"

WX78.DESCRIBE.KYNO_SWORDFISH_BLUE = "ERRO: COMPETÊNCIA AQUÁTICA PERDIDA. PATÉTICO."

WX78.DESCRIBE.KYNO_JELLYFISH = "ESSE SER ORGÂNICO PARECE FUNCIONAR À BASE DE ELETRICIDADE"
WX78.DESCRIBE.KYNO_JELLYFISH_DEAD = "A DECOMPOSIÇÃO AUMENTARÁ A TEXTURA GELATINOSA?"
WX78.DESCRIBE.KYNO_JELLYFISH_COOKED = "REDUÇÃO DE 40% NA TEXTURA GELATINOSA"
WX78.DESCRIBE.KYNO_JELLYFISH_DRIED = "REDUÇÃO DE 75% NA TEXTURA GELATINOSA"

WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "UMA FORMA DE VIDA MAL ACEITÁVEL"
WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "GOSTO MAIS ASSIM"
WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "COMBUSTÍVEL ROBÔ ARCO-ÍRIS"

WX78.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "RECIPIENTE DE VIDRO PARA LÍQUIDOS"

WX78.DESCRIBE.KYNO_OCEANTRAP = "ENTREM COISAS ESTÚPIDAS DO MAR"

WX78.DESCRIBE.OCEANFISH_PUFFERFISH = "SACO FLUTUANTE DE ESPINHOS VENENOSOS. APROVADO."
WX78.DESCRIBE.OCEANFISH_STURGEON = "UM PEIXE VELHO. QUE PATÉTICO"

WX78.DESCRIBE.KYNO_SWORDFISH = "PEIXE DE COMBATE"
WX78.DESCRIBE.KYNO_SWORDFISH_DEAD = "A VIDA NÃO VALE NADA"

WX78.DESCRIBE.SWORDFISHFEAST = "UNIDADE DE CARNE PREPARADA COM PRECISÃO. INSUMO ACEITÁVEL."

WX78.DESCRIBE.KYNO_DOGFISH = "NADA SEM PROPÓSITO"
WX78.DESCRIBE.KYNO_DOGFISH_DEAD = "A CRIATURA DE CARNE NÃO TINHA CHANCE"

WX78.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "TODOS OS SERES VIVOS MORREM E DEPOIS FEDERAM"

WX78.DESCRIBE.WOBSTER_MONKEYISLAND = "UNIDADE CRUSTÁCEA ARMORADA. ALTO VALOR DE BRILHO."
WX78.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "UNIDADE DE CARNE: TERMINADA. EXCELENTE."
WX78.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "UNIDADE DE CARNE: OTIMIZADA PERFEITAMENTE PARA INGESTÃO"

WX78.DESCRIBE.KYNO_PUFFERMONSTER = "BALÃO BIOLÓGICO CHEIO DE TOXINAS. PERIGOSO."

WX78.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "BOLHAS SOBEM DE UMA FONTE DESCONHECIDA"
WX78.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "NÍVEIS SUBÓTIMOS DE SEROTONINA DETECTADOS"
WX78.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "O ÓDIO TE CONSOME!"
WX78.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "HA! VOCÊ NUNCA FOI PÁREO PARA MIM"

WX78.DESCRIBE.KYNO_BLUBBER = "GORDURA DE MAMIFERO"

WX78.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "FONTE DE PROTEÍNA AQUÁTICA DESIDRATADA"
WX78.DESCRIBE.KYNO_FISHMEAT_DRIED = "PRODUTO MARÍTIMO DE LONGA DURAÇÃO"

WX78.DESCRIBE.MONKEYISLANDMEAL = "FONTE DE ENERGIA COM SABOR DE BANANA DETECTADA"

WX78.DESCRIBE.KYNO_BRAINROCK_LARVAE = "NÃO ME TOQUE"
WX78.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "VIDA ORGÂNICA AINDA NÃO SE ESTABELECEU"
WX78.DESCRIBE.KYNO_BRAINROCK_CORAL = "CONSUMO INDUZ ESTADO DE ESTIMULAÇÃO INTELECTUAL"

WX78.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "VARIEDADE DE CORAL ALTAMENTE EVOLUÍDA",
	PICKED = "FUNÇÕES COGNITIVAS TEMPORARIAMENTE DESATIVADAS",
}

WX78.DESCRIBE.BRAINMETTERSOUP = "NUTRIÇÃO PARA CRIANÇAS"

WX78.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "COMERCIANTE MULTIBRAÇOS",
	SLEEPING = "SUJEITO INATIVO",
}

WX78.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "COMO ELE CONSEGUE ENCHÊ-LO?"

WX78.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "ESCRITURA DE PROPRIEDADE DE ARMAZENAMENTO EXTERNO",
	WAITING = "UM PEIXE, UM PÁSSARO. PEIXE AMARELO, PEIXE MORTO",
}

WX78.DESCRIBE.KYNO_PACKIMBAGGIMS = "VOCÊ ESTÁ AUTORIZADO A GUARDAR MINHAS COISAS, SER DE CARNE"

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "PRECISA DE MAIS INGREDIENTES PARA SER MONTADO"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "BOLO GIGANTE EXIGE MAIS INGREDIENTES PARA SER FINALIZADO"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "UM BOLO GIGANTE PARA UMA MULTIDÃO GIGANTE"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "PERIGO DE INCÊNDIO. APROVADO"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "EXALA CELEBRAÇÃO"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "COMBUSTÍVEL ORGÂNICO DE CELEBRAÇÃO DETECTADO"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "SACOS DE BORRACHA INFLADOS DE CELEBRAÇÃO SEM PROPÓSITO"

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "UNIDADE DE ENTRETENIMENTO ACESSÍVEL DETECTADA",
	FUEL_HIGH = "NÍVEIS DE COMBUSTÍVEL ÓTIMOS",
	FUEL_MED = "NÍVEIS DE COMBUSTÍVEL ACEITÁVEIS",
	FUEL_LOW = "AVISO: COMBUSTÍVEL BAIXO",
	EMPTY = "ERRO: NENHUM COMBUSTÍVEL DETECTADO",
}

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "GRÃOS VEGETAIS EXPLODIDOS. APROVADO"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "CONE DECORATIVO DE CABEÇA DETECTADO"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "ACESSÓRIO DE CABEÇA ÚNICO. SAMMY É PRIVILEGIADO"

WX78.DESCRIBE.KYNO_FISHREGISTRYHAT = "COBERTURA CRANIANA AUMENTA CONHECIMENTO ICTIOLÓGICO"

WX78.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "ESTAÇÃO DE REABASTECIMENTO ORGÂNICO",
	FUEL_HIGH = "NÍVEL MÁXIMO DE ALIMENTO DETECTADO",
	FUEL_MED = "NÍVEL DE ALIMENTO ACEITÁVEL",
	FUEL_LOW = "AVISO: ALIMENTO PRESTES A ACABAR",
	EMPTY = "ERRO: SEM ALIMENTO",
	BURNT = "SISTEMA DESTRUÍDO PELO FOGO",
}