local WORMWOOD = STRINGS.CHARACTERS.WORMWOOD

WORMWOOD.ANNOUNCE_KYNO_COFFEEBUFF_START = "Zooomm!"
WORMWOOD.ANNOUNCE_KYNO_COFFEEBUFF_END = "Velocidade acabou?"

WORMWOOD.ANNOUNCE_KYNO_HASTEBUFF_START = "Zuuum!"
WORMWOOD.ANNOUNCE_KYNO_HASTEBUFF_END = "Onde Zoom foi?"

WORMWOOD.ANNOUNCE_KYNO_POPBUFF_START = "(Buurp)"
WORMWOOD.ANNOUNCE_KYNO_POPBUFF_END = "Borbulhas acabaram?"

WORMWOOD.ANNOUNCE_KYNO_FROGBUFF_START = "Cheiro de sapo!"
WORMWOOD.ANNOUNCE_KYNO_FROGBUFF_END = "Cheiro diferente, hmmm."

WORMWOOD.ANNOUNCE_KYNO_PIRATEBUFF_START = "Yarr! Wormwood pirata!"
WORMWOOD.ANNOUNCE_KYNO_PIRATEBUFF_END = "Yarr acabou..."

WORMWOOD.ANNOUNCE_KYNO_FREEZEBUFF_START = "Frio não dói!"
WORMWOOD.ANNOUNCE_KYNO_FREEZEBUFF_END = "Gelo acabou"

WORMWOOD.ANNOUNCE_KYNO_FIREBUFF_START = "Fogo não dói!"
WORMWOOD.ANNOUNCE_KYNO_FIREBUFF_END = "Fogo acabou"

WORMWOOD.ANNOUNCE_KYNO_FISHINGBUFF_START = "Hora de pescar!"
WORMWOOD.ANNOUNCE_KYNO_FISHINGBUFF_END = "Peixe?"

WORMWOOD.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "Relaxando!"
WORMWOOD.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "Relaxamento acabou"

WORMWOOD.ANNOUNCE_KYNO_EATERBUFF_START = "Barriga Forte!"
WORMWOOD.ANNOUNCE_KYNO_EATERBUFF_END = "Barriga Normal?"

WORMWOOD.ANNOUNCE_KYNO_WORMBUFF_START = "Iupi"
WORMWOOD.ANNOUNCE_KYNO_WORMBUFF_END = "Parar?"

WORMWOOD.ANNOUNCE_KYNO_CRABBUFF_START = "Iupi"
WORMWOOD.ANNOUNCE_KYNO_CRABBUFF_END = "Parar?"

WORMWOOD.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(Argh)"
WORMWOOD.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "Burbulhas saíram?"

WORMWOOD.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "Sentindo estranho"
WORMWOOD.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "Sentindo melhor"

WORMWOOD.ANNOUNCE_KYNO_STEALTHBUFF_START = "Sumiu!"
WORMWOOD.ANNOUNCE_KYNO_STEALTHBUFF_END = "Acabou a furtividade?"

WORMWOOD.ANNOUNCE_KYNO_FEARBUFF_START = "Sem medo!"
WORMWOOD.ANNOUNCE_KYNO_FEARBUFF_END = "Medo voltou?"

WORMWOOD.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "Formigando! Hee-hee!"
WORMWOOD.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "Sem mais poder brilhante..."

WORMWOOD.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "Fazendo amigos porquinhos"
WORMWOOD.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "Porquinhos sumiram"

WORMWOOD.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "Chuva não machuca mais!"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WORMWOOD.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "Sem ficar doente! Sentir bem!"
WORMWOOD.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "Sentir mal de novo..."

WORMWOOD.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "Cérebro Grande Agora"
WORMWOOD.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "Cérebro Cansado Agora"

WORMWOOD.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "Bzzz Bzzz Amigos! Iei!"
WORMWOOD.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "Bzzz Bzzz Bravo!"

WORMWOOD.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "Forte! Bem forte!"
WORMWOOD.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "Mais fraquinho..."

WORMWOOD.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "Barriga crescer!"
WORMWOOD.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "Barriga pequena de novo..."

WORMWOOD.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "Cabeça boa!"
WORMWOOD.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "Cabeça gira de novo..."

WORMWOOD.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "Duro! Seguro!"
WORMWOOD.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "Macio de novo."

WORMWOOD.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "Não"

WORMWOOD.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "Quer Glub Glub com Manteiga"

WORMWOOD.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "Amigo muito jovem?"

WORMWOOD.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "Não quer?"

WORMWOOD.ANNOUNCE_KYNO_POTHANGER_FAIL = "Quer outra coisa"

WORMWOOD.ANNOUNCE_KYNO_CASSEROLE_FAIL = "Não é isso?"

WORMWOOD.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "Oh... Parou de se mover agora..."

WORMWOOD.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "Tudo foi embora."

WORMWOOD.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "Bolhas Sumiram?"
WORMWOOD.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "Água caiu... Bolhas sumiu"
WORMWOOD.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "Coisa Grande Nadando... Perigo?"

WORMWOOD.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "Coisa Doce Grande terminada!"

WORMWOOD.ANNOUNCE_KYNO_FISH_RESEARCHED = "Glub Glub Me Contou Coisas!"
WORMWOOD.ANNOUNCE_KYNO_ROE_RESEARCHED = "Agora Sabe Sobre Pequenos Glub Glubs"

WORMWOOD.DESCRIBE.KYNO_ROE = "Pequenos Glub Glubs"
WORMWOOD.DESCRIBE.KYNO_ROE_COOKED = "Fileiras organizadas."

WORMWOOD.DESCRIBE.KYNO_SHARK_FIN = "Fatiador de Água"

WORMWOOD.DESCRIBE.KYNO_BEANBUGS = "Saltitantes"
WORMWOOD.DESCRIBE.KYNO_BEANBUGS_COOKED = "Por que não saltam?"

WORMWOOD.DESCRIBE.KYNO_GUMMYBUG = "Gosmentos"
WORMWOOD.DESCRIBE.KYNO_GUMMYBUG_COOKED = "Olá, palitinhos pequenos!"

WORMWOOD.DESCRIBE.KYNO_WHEAT = "Oh! Sementes bonitas!"
WORMWOOD.DESCRIBE.KYNO_WHEAT_COOKED = "Oh! Sementes bonitas!"

WORMWOOD.DESCRIBE.KYNO_FLOUR = "Coisa moída"

WORMWOOD.DESCRIBE.KYNO_SPOTSPICE = "Deixa a comida gostosa"

WORMWOOD.DESCRIBE.KYNO_SAP = "Amigo por dentro, agora por fora"
WORMWOOD.DESCRIBE.KYNO_SAP_SPOILED = "Não não não!"

WORMWOOD.DESCRIBE.KYNO_SYRUP = "Deixa as coisas doces"

WORMWOOD.DESCRIBE.KYNO_COFFEEBEANS = "Frutinhas velozes!"
WORMWOOD.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "Cheiro bom"

WORMWOOD.DESCRIBE.DUG_KYNO_COFFEEBUSH = "Amigo frutinha veloz"
WORMWOOD.DESCRIBE.KYNO_COFFEEBUSH = "Amigo frutinha veloz"

WORMWOOD.DESCRIBE.DUG_KYNO_SPOTBUSH = "Olá, amigo"
WORMWOOD.DESCRIBE.KYNO_SPOTBUSH = "Olá, amigo"

WORMWOOD.DESCRIBE.KYNO_SPOTSPICE_LEAF = "Galhinho"

WORMWOOD.DESCRIBE.KYNO_MUSSEL = "Escondendo"
WORMWOOD.DESCRIBE.KYNO_MUSSEL_COOKED = "Para barriga"

WORMWOOD.DESCRIBE.KYNO_HUMANMEAT = "Coisa de barriga"
WORMWOOD.DESCRIBE.KYNO_HUMANMEAT_COOKED = "Mmmm..."
WORMWOOD.DESCRIBE.KYNO_HUMANMEAT_DRIED = "Mastigável"

WORMWOOD.DESCRIBE.COFFEE = "Wheee!!!"

WORMWOOD.DESCRIBE.BISQUE = "Comida para barriga nadante"

WORMWOOD.DESCRIBE.JELLYOPOP = "Blob Glub Glub frio"

WORMWOOD.DESCRIBE.SHARKFINSOUP = "Ainda nadando"

WORMWOOD.DESCRIBE.TROPICALBOUILLABAISSE = "Glub Glubs?"

WORMWOOD.DESCRIBE.MUSSELBOUILLABAISE = "Bom para a barriga"

WORMWOOD.DESCRIBE.SWEETPOTATOSOUFFLE = "Comida para barriga"

WORMWOOD.DESCRIBE.FEIJOADA = "Cheio de pulantes"

WORMWOOD.DESCRIBE.GUMMY_CAKE = "Macio"

WORMWOOD.DESCRIBE.HARDSHELL_TACOS = "Crocrantes Bzzters"

WORMWOOD.DESCRIBE.ICEDTEA = "Água gelada zippy"

WORMWOOD.DESCRIBE.NETTLELOSANGE = "Mmm..."

WORMWOOD.DESCRIBE.SNAKEBONESOUP = "Água remexida"

WORMWOOD.DESCRIBE.STEAMEDHAMSANDWICH = "Socorro!"

WORMWOOD.DESCRIBE.TEA = "Água quente zippy"

WORMWOOD.DESCRIBE.BUBBLETEA = "Água gelada zippy"

WORMWOOD.DESCRIBE.FRENCHONIONSOUP = "Água remexida"

WORMWOOD.DESCRIBE.SLAW = "Festa na barriga!"

WORMWOOD.DESCRIBE.LOTUSBOWL = "Bom na barriga"

WORMWOOD.DESCRIBE.POI = "Coisa de barriga"

WORMWOOD.DESCRIBE.JELLYBEAN_HUNGER = "Mmmmm!"
WORMWOOD.DESCRIBE.JELLYBEAN_SUPER = "Mmmmm!"
WORMWOOD.DESCRIBE.JELLYBEAN_SANITY = "Mmmmm!"

WORMWOOD.DESCRIBE.BOWLOFGEARS = "Coisa de metal"

WORMWOOD.DESCRIBE.LONGPIGMEAL = "Mmm...."

WORMWOOD.DESCRIBE.CUCUMBERSALAD = "Quero comer"

WORMWOOD.DESCRIBE.KYNO_WILDWHEAT = "Amigo"
WORMWOOD.DESCRIBE.DUG_KYNO_WILDWHEAT = "Amigo"

WORMWOOD.DESCRIBE.KYNO_MEALGRINDER = "Máquina de pedra"

WORMWOOD.DESCRIBE.GORGE_BREAD = "Fofinho"
WORMWOOD.DESCRIBE.GORGE_SWEET_CHIPS = "Batatas"
WORMWOOD.DESCRIBE.GORGE_VEGETABLE_SOUP = "Vegetais!"
WORMWOOD.DESCRIBE.GORGE_JELLY_SANDWICH = "Para a barriga"
WORMWOOD.DESCRIBE.GORGE_FISH_STEW = "Peixudo"
WORMWOOD.DESCRIBE.GORGE_MEAT_STEW = "Para a barriga"
WORMWOOD.DESCRIBE.GORGE_ONION_CAKE = "Bolo!"
WORMWOOD.DESCRIBE.GORGE_POTATO_PANCAKES = "Cadê a batata?"
WORMWOOD.DESCRIBE.GORGE_POTATO_SOUP = "Coisa molinha para a barriga"
WORMWOOD.DESCRIBE.GORGE_FISHBALL_SKEWERS = "Peixinho"
WORMWOOD.DESCRIBE.GORGE_MEAT_SKEWERS = "Carne"
WORMWOOD.DESCRIBE.GORGE_STONE_SOUP = "Coisa molinha para a barriga"
WORMWOOD.DESCRIBE.GORGE_CROQUETTE = "Coisa para barriga"
WORMWOOD.DESCRIBE.GORGE_ROAST_VEGETABLES = "Coisa verde para barriga"
WORMWOOD.DESCRIBE.GORGE_MEATLOAF = "Carnudo."
WORMWOOD.DESCRIBE.GORGE_CARROT_SOUP = "Coisa de barriga molinha"
WORMWOOD.DESCRIBE.GORGE_FISHPIE = "Peixe preso?"
WORMWOOD.DESCRIBE.GORGE_FISHCHIPS = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_MEATPIE = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_SLIDERS = "Pequena comida de barriga"
WORMWOOD.DESCRIBE.GORGE_JELLY_ROLL = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_CARROT_CAKE = "Bolo!"
WORMWOOD.DESCRIBE.GORGE_GARLICMASHED = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_GARLICBREAD = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_TOMATO_SOUP = "Comida de barriga molinha"
WORMWOOD.DESCRIBE.GORGE_SAUSAGE = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_CANDIEDFISH = "Comida de barriga doce"
WORMWOOD.DESCRIBE.GORGE_STUFFEDMUSHROOM = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_BRUSCHETTA = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_HAMBURGER = "Hambúrguer"
WORMWOOD.DESCRIBE.GORGE_FISHBURGER = "Hambúrguer"
WORMWOOD.DESCRIBE.GORGE_MUSHROOMBURGER = "Hambúrguer"
WORMWOOD.DESCRIBE.GORGE_FISH_STEAK = "Peixinho"
WORMWOOD.DESCRIBE.GORGE_CURRY = "Comida quente de barriga"
WORMWOOD.DESCRIBE.GORGE_SPAGHETTI = "Bolas de comida para barriga"
WORMWOOD.DESCRIBE.GORGE_POACHEDFISH = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_SHEPHERD_PIE = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_CANDY = "Goma Mastigável"
WORMWOOD.DESCRIBE.GORGE_BREAD_PUDDING = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_BERRY_TART = "Comida de barriga doce"
WORMWOOD.DESCRIBE.GORGE_MACARONI = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_BAGEL_AND_FISH = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_GRILLED_CHEESE = "Comida amarela de barriga"
WORMWOOD.DESCRIBE.GORGE_CREAMMUSHROOM = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_MANICOTTI = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_CHEESEBURGER = "Hambúrguer"
WORMWOOD.DESCRIBE.GORGE_FETTUCCINE = "Comida de barriga branca"
WORMWOOD.DESCRIBE.GORGE_ONION_SOUP = "Comida de barriga fedida"
WORMWOOD.DESCRIBE.GORGE_BREADED_CUTLET = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_CREAMY_FISH = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_PIZZA = "Hmm..."
WORMWOOD.DESCRIBE.GORGE_POT_ROAST = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_CRAB_CAKE = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_STEAK_FRITES = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_SHOOTER_SANDWICH = "Atirar?"
WORMWOOD.DESCRIBE.GORGE_BACON_WRAPPED = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_CRAB_ROLL = "Caranguejo?"
WORMWOOD.DESCRIBE.GORGE_MEAT_WELLINGTON = "Comida de barriga"
WORMWOOD.DESCRIBE.GORGE_CRAB_RAVIOLI = "Caranguejo?"
WORMWOOD.DESCRIBE.GORGE_CARAMEL_CUBE = "Doce!"
WORMWOOD.DESCRIBE.GORGE_SCONE = "Doce"
WORMWOOD.DESCRIBE.GORGE_TRIFLE = "Doce"
WORMWOOD.DESCRIBE.GORGE_CHEESECAKE = "Bolo com queijo na barriga"

WORMWOOD.DESCRIBE.DUCKYOUGLERMZ = "Humm!"

WORMWOOD.DESCRIBE.KYNO_ALOE = "Amiguinha Grudenta"
WORMWOOD.DESCRIBE.KYNO_ALOE_COOKED = "Mole"
WORMWOOD.DESCRIBE.KYNO_ALOE_GROUND = "Amiguinha Grudenta"
WORMWOOD.DESCRIBE.KYNO_ALOE_SEEDS = "Faz a comida laranja para a barriga"
WORMWOOD.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "Faz a comida laranja para a barriga"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_ALOE = "Amiguinho pegajoso"
WORMWOOD.DESCRIBE.KYNO_ALOE_OVERSIZED = "Amiguinho pegajoso"
WORMWOOD.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "Nãããooo!"

WORMWOOD.DESCRIBE.KYNO_CUCUMBER = "Coisa pro estômago?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_COOKED = "Mmmm... Gosmento!"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_GROUND = "Coisa pro estômago?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_SEEDS = "Cria a comida laranja do estômago."
WORMWOOD.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "Cria a comida laranja do estômago."
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "Comida de barriga?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "Comida de barriga?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "Nããão!"

WORMWOOD.DESCRIBE.KYNO_RADISH = "Bolas vermelhas para a barriga"
WORMWOOD.DESCRIBE.KYNO_RADISH_COOKED = "Cadê a parte verde?"
WORMWOOD.DESCRIBE.KYNO_RADISH_GROUND = "Bolas vermelhas para a barriga"
WORMWOOD.DESCRIBE.KYNO_RADISH_SEEDS = "Faz a coisa laranja para a barriga"
WORMWOOD.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "Faz a coisa laranja para a barriga"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_RADISH = "Bolinhas vermelhas para a barriga"
WORMWOOD.DESCRIBE.KYNO_RADISH_OVERSIZED = "Bolinhas vermelhas para a barriga"
WORMWOOD.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "Nããão!"

WORMWOOD.DESCRIBE.KYNO_FENNEL = "Olá!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_COOKED = "Molenguinho"
WORMWOOD.DESCRIBE.KYNO_FENNEL_GROUND = "Olá!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_SEEDS = "Faz coisas para a barriga laranja"
WORMWOOD.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "Faz coisas para a barriga laranja"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "Olá!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_OVERSIZED = "Olá!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "Nããão!"

WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO = "Comida doce para barriga"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "Mmmm..."
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "Comida doce para barriga"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "Cria coisas laranjas para a barriga"
WORMWOOD.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "Cria coisas laranjas para a barriga"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "Comida doce para a barriga"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "Comida doce para a barriga"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "Nããão!"

WORMWOOD.DESCRIBE.KYNO_PARZNIP = "Obrigado, terra!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_COOKED = "Obrigado, terra!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_EATEN = "Obrigado, terra!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_GROUND = "Obrigado, terra!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_BIG = "Wee Woo!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_SEEDS = "Faz a comidinha laranja."
WORMWOOD.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "Faz a comidinha laranja."
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "Obrigado, terra!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "Uhuu!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "Nãããooo!"

WORMWOOD.DESCRIBE.KYNO_TURNIP = "Amiguinho da terra cortadinho"
WORMWOOD.DESCRIBE.KYNO_TURNIP_COOKED = "Faz Coisas Boas pro Barriga"
WORMWOOD.DESCRIBE.KYNO_TURNIP_GROUND = "Amiguinho da terra cortadinho"
WORMWOOD.DESCRIBE.KYNO_TURNIP_SEEDS = "Produz coisas laranja para a barriga"
WORMWOOD.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "Produz coisas laranja para a barriga"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "Amiguinho da terra"
WORMWOOD.DESCRIBE.KYNO_TURNIP_OVERSIZED = "Amiguinho da terra"
WORMWOOD.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "Nãooo!"

WORMWOOD.DESCRIBE.KYNO_RICE = "Pequenos brotinhos"
WORMWOOD.DESCRIBE.KYNO_RICE_COOKED = "Pequenos brotinhos"
WORMWOOD.DESCRIBE.KYNO_RICE_SEEDS = "Faz a coisa da barriga laranja."
WORMWOOD.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "Faz a coisa da barriga laranja."
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_RICE = "Amiguinho da terra fofo"
WORMWOOD.DESCRIBE.KYNO_RICE_OVERSIZED = "Amiguinho da terra fofo"
WORMWOOD.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "Nããão!"

WORMWOOD.DESCRIBE.KYNO_SEEDS_KIT = "Amiguinhos dentro?"

WORMWOOD.DESCRIBE.KYNO_LIMPETROCK = "Pedras que crescem coisas"
WORMWOOD.DESCRIBE.KYNO_LIMPETS = "Glub Glubs de Pedra"
WORMWOOD.DESCRIBE.KYNO_LIMPETS_COOKED = "Vai para a barriga"

WORMWOOD.DESCRIBE.KYNO_LOTUS_OCEAN = "Olá!"
WORMWOOD.DESCRIBE.KYNO_LOTUS_ROOT = "Precisa de mar"
WORMWOOD.DESCRIBE.KYNO_LOTUS_FLOWER = "Coisa gostosa pro estômago!"
WORMWOOD.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "Bom pro estômago."

WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_OCEAN = "Humm"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS = "Humm"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_COOKED = "Bola de Humm Marinho"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_DRIED = "Sem mais mar no Humm Marinho"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_ROOT = "Precisa de mar."

WORMWOOD.DESCRIBE.KYNO_TAROROOT_OCEAN = "Olá amigo!"
WORMWOOD.DESCRIBE.KYNO_TAROROOT_ROOT = "Precisa de mar"
WORMWOOD.DESCRIBE.KYNO_TAROROOT = "Mmm... Roxo"
WORMWOOD.DESCRIBE.KYNO_TAROROOT_COOKED = "Barriga gosta"

WORMWOOD.DESCRIBE.KYNO_WATERYCRESS_OCEAN = "Comida de barriga"
WORMWOOD.DESCRIBE.KYNO_WATERYCRESS_ROOT = "Precisa de mar"
WORMWOOD.DESCRIBE.KYNO_WATERYCRESS = "Comida de barriga"

WORMWOOD.DESCRIBE.WATERYCRESSBOWL = "Água Pegajosa"

WORMWOOD.DESCRIBE.KYNO_SALT = "Hmm..."

WORMWOOD.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "A vareta está nadando!"

WORMWOOD.DESCRIBE.CATFOOD = "Comida de gato"

WORMWOOD.DESCRIBE.KATFOOD = "Comida de gato"

WORMWOOD.DESCRIBE.KYNO_BANANATREE = "Amigo de Cabelos Doces"
WORMWOOD.DESCRIBE.KYNO_BANANA = "Cabelo Doce do Amigo!"
WORMWOOD.DESCRIBE.KYNO_BANANA_COOKED = "Mmm..."

WORMWOOD.DESCRIBE.KYNO_KOKONUTTREE = "Belo Cabelo!"
WORMWOOD.DESCRIBE.KYNO_KOKONUT = "Bola de Comida"
WORMWOOD.DESCRIBE.KYNO_KOKONUT_HALVED = "Comida para a barriga"
WORMWOOD.DESCRIBE.KYNO_KOKONUT_COOKED = "Quentinho."

WORMWOOD.DESCRIBE.BOWLOFPOPCORN = "Pop! Pop!"

WORMWOOD.DESCRIBE.FIGJUICE = "Água gelada zippy"

WORMWOOD.DESCRIBE.COCONUTWATER = "Água Doce"

WORMWOOD.DESCRIBE.EYEBALLSPAGHETTI = "Comida de Olhinho"

WORMWOOD.DESCRIBE.FORGETMELOTS_SEEDS = "Cria coisas laranjas para a barriga"

WORMWOOD.DESCRIBE.FIRENETTLES_SEEDS = "Cria coisas laranjas para a barriga"

WORMWOOD.DESCRIBE.TILLWEED_SEEDS = "Cria coisas laranjas para a barriga"

WORMWOOD.DESCRIBE.KYNO_FLOATILIZER = "Cocô! Yay!"

WORMWOOD.DESCRIBE.KYNO_TWIGGYNUTS = "Hmmm..."

WORMWOOD.DESCRIBE.KYNO_REPAIRTOOL = "Coisa de conserto"

WORMWOOD.DESCRIBE.KYNO_KOI = "Bonito Glub Glub"
WORMWOOD.DESCRIBE.KYNO_KOI_COOKED = "Bonito Glub Glub"

WORMWOOD.DESCRIBE.KYNO_TROPICALFISH = "Bonito Glub Glub"
WORMWOOD.DESCRIBE.KYNO_TROPICALFISH_COOKED = "Glub?"

WORMWOOD.DESCRIBE.KYNO_NEONFISH = "Boca Grande Glub Glub"
WORMWOOD.DESCRIBE.KYNO_NEONFISH_COOKED = "As nadadeiras são saborosas"

WORMWOOD.DESCRIBE.KYNO_GROUPER = "Roxo Glub Glub"
WORMWOOD.DESCRIBE.KYNO_GROUPER_COOKED = "Nada mais de nadar"
 
WORMWOOD.DESCRIBE.KYNO_PIERROTFISH = "Glub Glub"
WORMWOOD.DESCRIBE.KYNO_PIERROTFISH_COOKED = "Glub Glub Para a Barriga"

WORMWOOD.DESCRIBE.KYNO_SALMONFISH = "Glub Glub do chão"
WORMWOOD.DESCRIBE.KYNO_SALMONFISH_COOKED = "Glub Glub Para a Barriga"

WORMWOOD.DESCRIBE.TURF_PINKPARK = "Rosa"
WORMWOOD.DESCRIBE.TURF_STONECITY = "Não é terra"
WORMWOOD.DESCRIBE.TURF_FIELDS = "Terra"
WORMWOOD.DESCRIBE.TURF_TIDALMARSH = "Terra molenga"

WORMWOOD.DESCRIBE.KYNO_SALTRACK_INSTALLER = "Pega as Pedras Gostosas"

WORMWOOD.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "Coisa de Metal Malvada"

WORMWOOD.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "Cadeia Pinchy do Chão"

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_SHOP = "Braço Enrolado, Cauda Espiral"

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_BUD = "Quer na barriga? Ou no chão?"

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_FLOWER = "Amigo!"
WORMWOOD.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "Amigo!"

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_PETALS = "Amigo!"

WORMWOOD.DESCRIBE.KYNO_PEBBLECRAB = "Pinchy do Chão!"

WORMWOOD.DESCRIBE.KYNO_CRABMEAT = "Galho do Pinchy do Chão"
WORMWOOD.DESCRIBE.KYNO_CRABMEAT_COOKED = "Pinchy faz boa comida para a barriga"
WORMWOOD.DESCRIBE.KYNO_CRABMEAT_DRIED = "Galho do Pinchy do Chão"

WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT = "Galho do Pinchy do Chão"
WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "Galho do Pinchy do Chão"
WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "Galho do Pinchy do Chão"

WORMWOOD.DESCRIBE.KYNO_SLAUGHTERTOOL = "Coisas Más"

WORMWOOD.DESCRIBE.KYNO_CHICKEN2 = "Poc-gawk!"

WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG = "Pintinho Clique Clique"
WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "Vai para a barriga"

WORMWOOD.DESCRIBE.KYNO_CHICKENHOUSE = "Casa de Cocoricó"

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "Quebrado"

WORMWOOD.DESCRIBE.KYNO_COOKWARE_KIT = "Caixa de madeira"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SYRUP = "Faz Bolhas Doces"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "Faz Bolhas Doces"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_BIG_POT = "Hoo! Faz a água borbulhar!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_BIG = "Hoo! Faz a água borbulhar!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "Hoo! Faz a água borbulhar!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL = "Hoo! Faz a água borbulhar!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_GRILL = "Barras quentes!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "Precisa de fogo"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "Mini Barras Quentes"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "Precisa de fogo"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_ELDER = "Faz Bolhas Doces"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "Aquece a barriga"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "Deixa a comida bonita"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "Coloque comida aqui"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN = "Dá banho de fogo na comida"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "Dá banho de fogo na comida"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "Dá banho de fogo na comida"

WORMWOOD.DESCRIBE.KYNO_ROCKFLIPPABLE = "Coisas escondidas?"
WORMWOOD.DESCRIBE.KYNO_ROCKFLIPPABLE_CAVE = "Coisas escondidas?"

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "Madeira afundando!"

WORMWOOD.DESCRIBE.KYNO_SUGARFLY = "Amiga dos amigos"
WORMWOOD.DESCRIBE.KYNO_SUGARFLYWINGS = "Não é para voar"

WORMWOOD.DESCRIBE.KYNO_WATERY_CRATE = "Madeira se afogando!"

WORMWOOD.DESCRIBE.KYNO_TUNACAN = "Glub Glub dentro?"
WORMWOOD.DESCRIBE.KYNO_TUNACAN_OPEN = "Glub Glub morto"

WORMWOOD.DESCRIBE.KYNO_CANNEDFOOD = "Comida dentro?"
WORMWOOD.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "Delícia"

WORMWOOD.DESCRIBE.KYNO_POP = "Psht"

WORMWOOD.DESCRIBE.KYNO_MYSTERYMEAT = "Hmm... O que é isso?"

WORMWOOD.DESCRIBE.KYNO_BOTTLE_SOUL = "Hmm..."

WORMWOOD.DESCRIBE.SOULSTEW = "Hmm..."

WORMWOOD.DESCRIBE.FORTUNECOOKIE = "Coisa estranha na barriga"

WORMWOOD.DESCRIBE.HORNOCUPIA = "Coisas para barriga"

WORMWOOD.DESCRIBE.CHEESE_YELLOW = "Coisa fedida para barriga"
WORMWOOD.DESCRIBE.CHEESE_WHITE = "Coisa fedida para barriga"
WORMWOOD.DESCRIBE.CHEESE_KOALEFANT = "Coisa fedida para barriga"

WORMWOOD.DESCRIBE.MILK_BOX = "Coisa de barriga?"

WORMWOOD.DESCRIBE.WATERCUP = "Água"

WORMWOOD.DESCRIBE.HONEYJAR = "Coisa doce para barriga"

WORMWOOD.DESCRIBE.CRAB_ARTICHOKE = "Pedrinhas sumiram?"

WORMWOOD.DESCRIBE.PEPPERROLLS = "Pedacinhos Deliciosos"

WORMWOOD.DESCRIBE.KYNO_SAPHEALER = "Remédio de Doença"

WORMWOOD.DESCRIBE.KYNO_OCEAN_WRECK = "Salvem a madeira!"

WORMWOOD.DESCRIBE.KYNO_GHOST_PIRATE = "Homem Flutuante"

WORMWOOD.DESCRIBE.KYNO_BUCKET_EMPTY = "Coisa de Madeira"
WORMWOOD.DESCRIBE.KYNO_BUCKET_METAL = "Coisa de Metal"
WORMWOOD.DESCRIBE.KYNO_BUCKET_WATER = "Água pros Amigos"

WORMWOOD.DESCRIBE.KYNO_MILK_BEEFALO = "Muu Muu?"
WORMWOOD.DESCRIBE.KYNO_MILK_KOALEFANT = "Muu Muu?"

WORMWOOD.DESCRIBE.KYNO_CAP_DRIED = "Belly Stuff"

WORMWOOD.DESCRIBE.KYNO_PLANTMEAT_DRIED = "Belly Stuff Seco"

WORMWOOD.DESCRIBE.KYNO_BREWBOOK = "Coisas de Belly"

WORMWOOD.DESCRIBE.KYNO_WOODENKEG = "Caixa de Madeira?"

WORMWOOD.DESCRIBE.KYNO_PRESERVESJAR = "Caixa de Madeira?"

WORMWOOD.DESCRIBE.KYNO_ANTCHEST = "Suco de zumbido! Onde está o Buzz?"

WORMWOOD.DESCRIBE.KYNO_NECTAR_POD = "Doce!"

WORMWOOD.DESCRIBE.KYNO_OAKTREE_POD = "Olá"
WORMWOOD.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "Não é para a terra agora"

WORMWOOD.DESCRIBE.KYNO_PIKO = "Fofinho ladrão"
WORMWOOD.DESCRIBE.KYNO_PIKO_ORANGE = "Fofinho ladrão"

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_TREE = "Dormindo?"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = "Dormindo com amigos?"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "Amigos de madeira fizeram uma caixa!"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = "Casa do Glub Glub"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = "Casa do Glub Glub"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SHOP = "Tem muitas coisas dentro"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = "Coisas"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "Olá!"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_POND = "Lar de Glub Glub"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "Olá, amiguinho"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "Monte de terra"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "Glub Glub Homem"

WORMWOOD.DESCRIBE.KYNO_SAMMYHAT = "Empoeirado"

WORMWOOD.DESCRIBE.KINGFISHER = "Bico Apontador"

WORMWOOD.DESCRIBE.TOUCAN = "Bico Grande"
WORMWOOD.DESCRIBE.TOUCAN_CHUBBY = "Cantarolador de Nariz Grande"

WORMWOOD.DESCRIBE.WETGOOP2 = "Humm"

WORMWOOD.DESCRIBE.BEER = "Gosto Engraçado"

WORMWOOD.DESCRIBE.PALEALE = "Gosto Engraçado"

WORMWOOD.DESCRIBE.TEAGREEN = "Mmmm... Ahh"

WORMWOOD.DESCRIBE.TEARED = "Mmmm... Ahh"

WORMWOOD.DESCRIBE.MEAD = "Coisa Doce da Barriga"

WORMWOOD.DESCRIBE.KYNO_JELLY = "Coisa Doce da Barriga"

WORMWOOD.DESCRIBE.KYNO_MAYONNAISE = "Mmm..."

WORMWOOD.DESCRIBE.TARTARSAUCE = "Coisa Picante"

WORMWOOD.DESCRIBE.KYNO_PICKLES = "Comida da Barriga"

WORMWOOD.DESCRIBE.KYNO_WINE = "Água amarga"

WORMWOOD.DESCRIBE.KYNO_JUICE = "Comida da Barriga Doce"

WORMWOOD.DESCRIBE.KYNO_POISON_FROGLEGS = "Perna"
WORMWOOD.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "(sniff, sniff) Cheira bem"

WORMWOOD.DESCRIBE.POISONFROGGLEBUNWICH = "Enche a Barriga"

WORMWOOD.DESCRIBE.KYNO_BREWINGRECIPECARD = "Hmmm. Não serve pra nada"

WORMWOOD.DESCRIBE.KYNO_OIL = "Coisa pro estômago?"

WORMWOOD.DESCRIBE.BERRYSUNDAE = "Frio"

WORMWOOD.DESCRIBE.CHOCOLATE_BLACK = "Doce!"
WORMWOOD.DESCRIBE.CHOCOLATE_WHITE = "Doce!"

WORMWOOD.DESCRIBE.TRICOLORDANGO = "Doce"
 
WORMWOOD.DESCRIBE.FRIESFRENCH = "Crocante"

WORMWOOD.DESCRIBE.PIRATERUM = "Maligno?"

WORMWOOD.DESCRIBE.TWISTEDTEQUILA = "Coisa pro estômago?"

WORMWOOD.DESCRIBE.ONIONRINGS = "Cebolas crocantes"

WORMWOOD.DESCRIBE.DONUTS = "Doce para a barriga"
WORMWOOD.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "Doce para a barriga"
WORMWOOD.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "Doce para a barriga"
 
WORMWOOD.DESCRIBE.CINNAMONROLL = "Comida para barriga"

WORMWOOD.DESCRIBE.GUMMYBEARGERS = "Estranho"

WORMWOOD.DESCRIBE.PRETZEL = "Comida para barriga"

WORMWOOD.DESCRIBE.CORNINCUP = "Bom para a barriga"

WORMWOOD.DESCRIBE.COTTONCANDY = "Ar?"

WORMWOOD.DESCRIBE.ROASTEDHAZELNUTS = "Nozes!"

WORMWOOD.DESCRIBE.MONSTERMUFFIN = "Comida estranha"

WORMWOOD.DESCRIBE.PINKCAKE = "Bolo doce"

WORMWOOD.DESCRIBE.CHIPSBAG = "Comida para barriga"

WORMWOOD.DESCRIBE.LITTLEBREAD = "Fofo"

WORMWOOD.DESCRIBE.HOTHOUND = "Cadê o cachorro?"

WORMWOOD.DESCRIBE.MILKSHAKE = "Bate!"
WORMWOOD.DESCRIBE.MILKSHAKE_PRISMATIC = "Bate!"

WORMWOOD.DESCRIBE.NACHOS = "Queijudo"

WORMWOOD.DESCRIBE.BANANA_PUDDING = "Bananas"

WORMWOOD.DESCRIBE.SEA_PUDDING = "Peixinhos?"

WORMWOOD.DESCRIBE.TOM_KHA_SOUP = "Vegetais"

WORMWOOD.DESCRIBE.MINERTREAT = "Estranho"

WORMWOOD.DESCRIBE.RADISHSALAD = "Quero comer"

WORMWOOD.DESCRIBE.PUMPKIN_SOUP = "Coisa de barriga"

WORMWOOD.DESCRIBE.ALGAE_SOUP = "Coisa de barriga"

WORMWOOD.DESCRIBE.PARZNIP_SOUP = "Coisa de barriga"

WORMWOOD.DESCRIBE.NETTLEMEATED = "Mmmm..."

WORMWOOD.DESCRIBE.KYNO_SUGAR = "Pó Doce"

WORMWOOD.DESCRIBE.KYNO_BOTTLECAP = "Tampinha"

WORMWOOD.DESCRIBE.NUKACOLA = "Borbulhante"
WORMWOOD.DESCRIBE.NUKACOLA_QUANTUM = "Borbulhante"

WORMWOOD.DESCRIBE.LIVINGSANDWICH = "Pão estranho"

WORMWOOD.DESCRIBE.DURIANSPLIT = "Gelado"

WORMWOOD.DESCRIBE.DURIANSOUP = "Água squirmy"

WORMWOOD.DESCRIBE.DURIANMEATED = "Comida fedida"

WORMWOOD.DESCRIBE.DURIANCHICKEN = "Comida de barriga"

WORMWOOD.DESCRIBE.LUNARSOUP = "Lua!"

WORMWOOD.DESCRIBE.PURPLEWOBSTERSOUP = "Pobre Wobster"

WORMWOOD.DESCRIBE.WOBSTERMONSTER = "Monstro"

WORMWOOD.DESCRIBE.SPIDERCAKE = "Bolo de aranha"

WORMWOOD.DESCRIBE.SUGARBOMBS = "Kaboom"

WORMWOOD.DESCRIBE.BERRYBOMBS = "Doce para a barriga"

WORMWOOD.DESCRIBE.ONIGIRIS = "Grãos"

WORMWOOD.DESCRIBE.OMURICE = "Grãos fritos"

WORMWOOD.DESCRIBE.PAELLA = "Grãos!"

WORMWOOD.DESCRIBE.RISOTTO = "Grãos e amigos"

WORMWOOD.DESCRIBE.RICESAKE = "Água de grãos?"

WORMWOOD.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "Oi, amigo!"
WORMWOOD.DESCRIBE.KYNO_PINEAPPLEBUSH = "Oi, amigo!"

WORMWOOD.DESCRIBE.KYNO_PINEAPPLE = "Espinhosa"
WORMWOOD.DESCRIBE.KYNO_PINEAPPLE_HALVED = "Comida de barriga"
WORMWOOD.DESCRIBE.KYNO_PINEAPPLE_COOKED = "Comida de barriga"

WORMWOOD.DESCRIBE.PIZZA_TROPICAL = "Amigo?"

WORMWOOD.DESCRIBE.PINACOLADA = "Amigo?"

WORMWOOD.DESCRIBE.CHIMAS = "Grama?"

WORMWOOD.DESCRIBE.KYNO_GARDEN_SPRINKLER = "Transforma ar em água"

WORMWOOD.DESCRIBE.KYNO_FOODSACK = "Mantém a Comida Fresquinha"

WORMWOOD.DESCRIBE.GUMMYWORMS = "Minhocas?"

WORMWOOD.DESCRIBE.SMORES = "Choco?"

WORMWOOD.DESCRIBE.NUKASHINE = "Bebida Estranha"

WORMWOOD.DESCRIBE.ANTSLOG = "Woody"

WORMWOOD.DESCRIBE.KYNO_WORM_BONE = "Oh"

WORMWOOD.DESCRIBE.SPOOKY_BRAIN_NOODLES = "Mente?"
WORMWOOD.DESCRIBE.SPOOKY_BURGERZILLA = "Monstro!"
WORMWOOD.DESCRIBE.SPOOKY_DEADBREAD = "Fofinho"
WORMWOOD.DESCRIBE.SPOOKY_JELLYBEANS = "Assustador"
WORMWOOD.DESCRIBE.SPOOKY_POPSICLE = "Gostoso"
WORMWOOD.DESCRIBE.SPOOKY_PUMPKINCREAM = "Amigo cheirosinho?"
WORMWOOD.DESCRIBE.SPOOKY_SKULLCANDY = "Assustador"
WORMWOOD.DESCRIBE.SPOOKY_TACODILE = "Amigo?"

WORMWOOD.DESCRIBE.BUTTER_BEEFALO = "Pegajoso"
WORMWOOD.DESCRIBE.BUTTER_GOAT = "Pegajoso?"
WORMWOOD.DESCRIBE.BUTTER_KOALEFANT = "Pegajoso!"

WORMWOOD.DESCRIBE.SPICE_CURE = "Mantém alimentos seguros"
WORMWOOD.DESCRIBE.SPICE_COLD = "Frio!"
WORMWOOD.DESCRIBE.SPICE_FIRE = "Queimar!"
WORMWOOD.DESCRIBE.SPICE_FED = "Faminto"
WORMWOOD.DESCRIBE.SPICE_MIND = "Sonolento"

WORMWOOD.DESCRIBE.SUGARFLYMUFFIN = "Delicioso..."

WORMWOOD.DESCRIBE.EELTACOS = "Para Barriga"

WORMWOOD.DESCRIBE.MEATSKILLET = "Para Barriga!"

WORMWOOD.DESCRIBE.MEATWALTZ = "Para Barriga?"

WORMWOOD.DESCRIBE.COMPLETEBREAKFAST = "Comida para Barriga Grande"

WORMWOOD.DESCRIBE.DUMPLINGS = "Comida para Barriga"

WORMWOOD.DESCRIBE.WARLYICEDTEA = "Água fria e picante"

WORMWOOD.DESCRIBE.WARLYTEA = "Água quente e picante"

WORMWOOD.DESCRIBE.KYNO_TEALEAF = "Amigo aconchegante"

WORMWOOD.DESCRIBE.KYNO_ITEMSLICER = "Cortador. Para Cortes de Amigo"
WORMWOOD.DESCRIBE.KYNO_ITEMSLICER_GOLD = "Cortador. Para Cortes de Amigo"

WORMWOOD.DESCRIBE.COXINHA = "Comida para barriga"

WORMWOOD.DESCRIBE.LAZYDESSERT = "Pedregoso"

WORMWOOD.DESCRIBE.CRABKINGFEAST = "Gigante!"

WORMWOOD.DESCRIBE.PIENAPPLE = "Amigo tem cabelo espinhoso!"

WORMWOOD.DESCRIBE.JAWSBREAKER = "Duro"

WORMWOOD.DESCRIBE.AVOCADOTOAST = "Saboroso"

WORMWOOD.DESCRIBE.RICEPUDDING = "Mistura"

WORMWOOD.DESCRIBE.SHARKSUSHI = "Comida para Barriga"

WORMWOOD.DESCRIBE.WOBSTERBREADED = "Frito Crocante Glub Glub"

WORMWOOD.DESCRIBE.LAZYPURRITO = "Gato bobo."

WORMWOOD.DESCRIBE.HORCHATA = "Fria!"

WORMWOOD.DESCRIBE.WOBSTERCOCKTAIL = "Glub Glub em Chamas"

WORMWOOD.DESCRIBE.LAVAEEGGBOILED = "Quente!"

WORMWOOD.DESCRIBE.POMEGRANATETEA = "Água Gelada Zippy"

WORMWOOD.DESCRIBE.TIRAMISU = "Honk! Honk!"

WORMWOOD.DESCRIBE.TOADSTOOLCOLA = "Fedida Psht"

WORMWOOD.DESCRIBE.TEPACHE = "Suco Doce Amigo"

WORMWOOD.DESCRIBE.LUNARTEQUILA = "Coisa da lua?"

WORMWOOD.DESCRIBE.MIMICMOSA = "Suco Escuro"

WORMWOOD.DESCRIBE.POMEGRANATEPIE = "Coisa Vermelha"

WORMWOOD.DESCRIBE.PINEAPPLECAKE = "Comida de barriga"

WORMWOOD.DESCRIBE.PASTY_MEAT = "Crocante"
WORMWOOD.DESCRIBE.PASTY_CHEESE = "Crocante"

WORMWOOD.DESCRIBE.BRIGADEIRO = "Granulado"

WORMWOOD.DESCRIBE.REGULARLASAGNA = "Para barriga"

WORMWOOD.DESCRIBE.FLTSANDWICH = "Sapo"

WORMWOOD.DESCRIBE.RICEANDBEANS = "Para barriga"

WORMWOOD.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "Casa velha... talvez nova vida... em breve..."

WORMWOOD.DESCRIBE.KYNO_TRUFFLES_GROUND = "Amigos crescem no chão!"
WORMWOOD.DESCRIBE.KYNO_TRUFFLES = "Amigo saiu do chão!"
WORMWOOD.DESCRIBE.KYNO_TRUFFLES_COOKED = "Amigo quentinho agora!"

WORMWOOD.DESCRIBE.KYNO_ITEMSHOWCASER = "Mostrar comida pros amigos!"

WORMWOOD.DESCRIBE.KYNO_SPORECAP = "Amigo... doente..."
WORMWOOD.DESCRIBE.KYNO_SPORECAP_COOKED = "Amigo quente! Melhor?"

WORMWOOD.DESCRIBE.KYNO_SPORECAP_DARK = "Amigo machuca amigos..."
WORMWOOD.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "Ainda machuca amigo..."

WORMWOOD.DESCRIBE.KYNO_GOLDENAPPLE = "Brilhante! Fruta amiga!"

WORMWOOD.DESCRIBE.TRUFFLESGRINDER = "Humm! Sanduíche da terra!"

WORMWOOD.DESCRIBE.SPORECAPPIE = "Torta Mole"

WORMWOOD.DESCRIBE.SPORECAP_SKEWERS = "Amigos Maus... gostoso agora!"

WORMWOOD.DESCRIBE.TRUFFLEOIL = "Cheiro forte!"

WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "Planos do Lago"
WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "Casinha da Água Crescendo!"
WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT = "Casinha Glub Glub"

WORMWOOD.DESCRIBE.KYNO_ANTCHOVY = "Amigo peixe-inseto! Oi!"
WORMWOOD.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "Muitos amigos peixe-inseto!"

WORMWOOD.DESCRIBE.AGEDROE = "Bebês Glub Glub presos?"
WORMWOOD.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "Bebês Glub Glub"

WORMWOOD.DESCRIBE.KYNO_SWORDFISH_BLUE = "Não Nadar Bom?"

WORMWOOD.DESCRIBE.KYNO_JELLYFISH = "Glub Glub Bolha"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_DEAD = "Pobre Bolha"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_COOKED = "Bolha Quente"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_DRIED = "Bolha Dura"

WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "Bolha Glub Glub Bonita"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "Sem Poof"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "Anéis Bonitos"

WORMWOOD.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "Aw. Nada dentro."

WORMWOOD.DESCRIBE.KYNO_OCEANTRAP = "Armadilha Molhada"

WORMWOOD.DESCRIBE.OCEANFISH_PUFFERFISH = "Glub Glub Espetudo"
WORMWOOD.DESCRIBE.OCEANFISH_STURGEON = "Glub Glub Velho"

WORMWOOD.DESCRIBE.KYNO_SWORDFISH = "Glub Glub Nariz-Afiado"
WORMWOOD.DESCRIBE.KYNO_SWORDFISH_DEAD = "(snif)"

WORMWOOD.DESCRIBE.SWORDFISHFEAST = "Glub Glub Chique"

WORMWOOD.DESCRIBE.KYNO_DOGFISH = "Glub Glub Aum Aum"
WORMWOOD.DESCRIBE.KYNO_DOGFISH_DEAD = "Oi, Glub Glub"

WORMWOOD.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "Cheiro bom. Mmmmm."

WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND = "Amigo aquático brilhante!"
WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "Fim dos movimentos brilhantes..."
WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "Amigo?"

WORMWOOD.DESCRIBE.KYNO_PUFFERMONSTER = "Peixinho pontudo! Não cutuque, amigo!"

WORMWOOD.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "Glub Glub ou Barrooooo?"
WORMWOOD.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "Barrooooo!"
WORMWOOD.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "Pale Barrooooo"
WORMWOOD.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "Grandeee!"

WORMWOOD.DESCRIBE.KYNO_BLUBBER = "Mole"

WORMWOOD.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "Glub Glub seco, Mmm!"
WORMWOOD.DESCRIBE.KYNO_FISHMEAT_DRIED = "Glub Glub seco"

WORMWOOD.DESCRIBE.MONKEYISLANDMEAL = "Glub Glub e Amigo"

WORMWOOD.DESCRIBE.KYNO_BRAINROCK_LARVAE = "Precisa de pedra"
WORMWOOD.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "Pedrinha bebê molhada e fofa."
WORMWOOD.DESCRIBE.KYNO_BRAINROCK_CORAL = "Pensando..."
WORMWOOD.DESCRIBE.KYNO_BRAINROCK_ROCK = "Pedra Pensante"

WORMWOOD.DESCRIBE.BRAINMETTERSOUP = "Coisa pensante para barriga"

WORMWOOD.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = "Cara dos Braços Grandes"
WORMWOOD.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "Coisas do Cara dos Braços Grandes!"

WORMWOOD.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = "Amigo Pio gosta de você!"
WORMWOOD.DESCRIBE.KYNO_PACKIMBAGGIMS = "Amigo Pio"

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "Falta Coisa"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "Precisa de Mais Coisas"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "Muiiiito Grande!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "Luz para Bolo Grande!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "Amigos..."
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "Coisa Doce pra Barriga!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "Amigos flutuantes! Oi!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = "Faz Pipoca!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "Pop pop!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "Chapéu de Festa! Eba!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "Chapéu do Amigo!"

WORMWOOD.DESCRIBE.KYNO_FISHREGISTRYHAT = "Chapéu Que Sabe de Peixe"