------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- New Crock Pot Ingredients.
AddIngredientValues({"slurtle_shellpieces"}, 	{inedible=1, 					  shell=1})
AddIngredientValues({"rabbit"}, 				{rabbit=1})
AddIngredientValues({"firenettles"}, 			{veggie=0.5})
AddIngredientValues({"foliage"}, 				{veggie=0.5}, 						  true)
AddIngredientValues({"succulent_picked"}, 		{veggie=0.5})
AddIngredientValues({"robin_winter"}, 			{robin_winter=1})
AddIngredientValues({"petals"}, 				{veggie=0.5})
AddIngredientValues({"gears"}, 					{gears=1})
AddIngredientValues({"rocks"}, 					{rocks=1, 		elemental=1,   inedible=1})
AddIngredientValues({"poop"}, 					{poop=1, 		glermz=1})
AddIngredientValues({"guano"}, 					{poop=1, 		glermz=1})
AddIngredientValues({"glommerfuel"}, 			{poop=1, 		glermz=1})
AddIngredientValues({"deerclops_eyeball"},      {inedible=1, 	boss=1})
AddIngredientValues({"kyno_coffeebeans"}, 		{seeds=1, 		fruit=0.5}, 		  true)
AddIngredientValues({"kyno_shark_fin"}, 		{fish=1})
AddIngredientValues({"kyno_roe"}, 				{meat=0.5, 		roe=1}, 			  true)
AddIngredientValues({"kyno_mussel"}, 			{fish=0.5, 		mussel=1}, 		  	  true)
AddIngredientValues({"kyno_beanbugs"}, 			{bug=1, 		veggie=0.5}, 		  true)
AddIngredientValues({"kyno_gummybug"}, 			{bug=1, 		veggie=0.5}, 		  true)
AddIngredientValues({"kyno_humanmeat"}, 		{meat=1, 		monster=1}, 	true, true)
AddIngredientValues({"kyno_syrup"}, 			{sweetener=1, 	syrup=1})
AddIngredientValues({"kyno_flour"}, 			{inedible=1, 	flour=1})
AddIngredientValues({"kyno_spotspice"},			{spotspice=1})
AddIngredientValues({"kyno_bacon"}, 			{meat=0.5, 		bacon=1}, 			  true)
AddIngredientValues({"gorge_bread"}, 			{bread=1})
AddIngredientValues({"kyno_white_cap"}, 		{veggie=0.5, 	mushroom=1},		  true)
AddIngredientValues({"kyno_foliage"}, 			{veggie=0.5}, 						  true) -- This is a false Foliage. We just need it because Cooked Foliage icon doesn't display without it.
AddIngredientValues({"kyno_sap"}, 				{inedible=1, 	sap=1})
AddIngredientValues({"kyno_aloe"}, 				{veggie=1}, 						  true)
AddIngredientValues({"kyno_radish"}, 			{veggie=1}, 						  true)
AddIngredientValues({"kyno_fennel"}, 			{veggie=1}, 						  true)
AddIngredientValues({"kyno_sweetpotato"}, 		{veggie=1}, 						  true)
AddIngredientValues({"kyno_lotus_flower"}, 		{veggie=1}, 						  true)
AddIngredientValues({"kyno_seaweeds"}, 			{veggie=1}, 					true, true)
AddIngredientValues({"kyno_limpets"}, 			{fish=0.5}, 						  true)
AddIngredientValues({"kyno_taroroot"}, 			{veggie=1},                           true)
AddIngredientValues({"kyno_cucumber"}, 			{veggie=1})
AddIngredientValues({"kyno_waterycress"}, 		{veggie=1})
AddIngredientValues({"kyno_salt"}, 				{inedible=1})
AddIngredientValues({"kyno_parznip"}, 			{veggie=1},                           true)
AddIngredientValues({"kyno_parznip_eaten"}, 	{veggie=1},                           true)
AddIngredientValues({"kyno_turnip"}, 			{veggie=1},                           true)
AddIngredientValues({"kyno_banana"}, 			{fruit=1},                            true)
AddIngredientValues({"kyno_kokonut_halved"}, 	{fruit=1})
AddIngredientValues({"kyno_kokonut_cooked"}, 	{fruit=1})
AddIngredientValues({"kyno_twiggynuts"}, 		{seeds=1, 		fruit=0.5})
AddIngredientValues({"kyno_grouper"},			{fish=1,		meat=1},			  true)
AddIngredientValues({"kyno_neonfish"},			{fish=1,		meat=1},			  true)
AddIngredientValues({"kyno_koi"},			    {fish=1,		meat=1},			  true)
AddIngredientValues({"kyno_tropicalfish"},		{fish=0.5,		meat=0.5},			  true)
AddIngredientValues({"kyno_pierrotfish"},		{fish=0.5,		meat=0.5},			  true)
AddIngredientValues({"kyno_salmonfish"},		{fish=0.5, 		meat=0.5},			  true)
AddIngredientValues({"kyno_sugartree_petals"},	{sweetener=1})
AddIngredientValues({"kyno_crabmeat"},			{meat=0.5,		crab=1},			  true)
AddIngredientValues({"kyno_chicken_egg"},		{egg=1}, 							  true)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- Icons For Cookbook.
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_coffeebeans_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_coffeebeans.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_shark_fin.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "ecp_shark_fin.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_roe_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_roe.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_mussel_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_mussel.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_beanbugs_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_beanbugs.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_gummybug_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_gummybug.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_humanmeat_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_humanmeat.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_humanmeat_dried.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_syrup.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_flour.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_spotspice.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_bacon.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_bacon_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "gorge_bread.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_white_cap.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_white_cap_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_foliage.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_foliage_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_sap.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_aloe.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_aloe_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_radish.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_radish_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_fennel.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_fennel_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_sweetpotato.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_sweetpotato_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_lotus_flower.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_lotus_flower_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_seaweeds.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_seaweeds_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_seaweeds_dried.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_limpets.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_limpets_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_taroroot.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_taroroot_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_cucumber.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_waterycress.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_salt.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_parznip.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_parznip_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_parznip_eaten.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_turnip.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_turnip_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_banana.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_banana_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_kokonut.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_kokonut_halved.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_kokonut_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_twiggynuts.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_neonfish.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_neonfish_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_grouper.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_grouper_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_pierrotfish.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_pierrotfish_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_koi.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_koi_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_salmonfish.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_salmonfish_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_tropicalfish.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_sugartree_petals.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_crabmeat.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_crabmeat_cooked.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_chicken_egg.tex")
RegisterInventoryItemAtlas("images/inventoryimages/hof_inventoryimages.xml", "kyno_chicken_egg_cooked.tex")
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------