local _G            = GLOBAL
local require       = _G.require
local STRINGS       = _G.STRINGS
local WEIGHT_START  = _G.LOADING_SCREEN_TIP_CATEGORY_WEIGHTS_START
local WEIGHT_END    = _G.LOADING_SCREEN_TIP_CATEGORY_WEIGHTS_END
local TIPS_HOF      = STRINGS.UI.LOADING_SCREEN_OTHER_TIPS

-- New Loading Tips and Lore.
local LOADINGTIPS   =
{
	COFFEE1         = "Bạn có thể lấy Cây Cà Phê sau khi đánh bại Chuồn Chuồn. Hoặc nếu nó đáng sợ quá với ngươi, một chuyến ghé qua khu Lỗ Phun Khí cũng kiếm được vài cây!",
	COFFEE2         = "Cây Cà Phê không cần bón phân vào Mùa Hè. Chúng thậm chí còn tự bón phân cho mình!",
	COFFEE3         = "Cây Cà Phê chỉ có thể được trồng trên Nền Cát hoặc Nền Lỗ Phun Khí.",
	WEEDS           = "Bạn có thể trồng Cỏ Dại bằng chính sản phẩm của chúng, miễn là đưa chúng cho chim trước.",
	WALRY           = "Warly có những công thức độc quyền do chính tay anh ấy làm ra.",
	JELLYBEANS      = "\"Có vẻ Kẹo Đậu Thạch Sung Sức làm cơ thể ta thấy khỏe khoắn lắm!\" -W",
	INGREDIENTS     = "Có thêm nguyên liệu mới từ game gốc có thể dùng trong Nồi Nấu. Kể cả mấy thứ kỳ quặc nhất...",
	WX78            = "\"WX-78 muốn làm một món với Bánh Răng. Nếu ta có vài cái không dùng đến, có lẽ ta nên giúp cậu ấy một tay.\" -W",
	HUMANMEAT       = "Mỗi khi một Người Chơi chết, có một cơ hội nhỏ họ sẽ rơi ra một nguyên liệu nấu ăn rất đáng ngờ...",
	SALT            = "Muối có thể dùng để khôi phục thời gian hư hỏng của một món đã nấu. Đừng bao giờ để mất món ngon ngọt ấy nữa!",
	OLDMOD          = "Phiên bản đầu tiên của Vua Đầu Bếp có tên là The Foods Pack, nhưng đã bị ngừng phát triển vì lỗi. Về sau, nó được làm lại thành bản mod hoàn toàn mới này.",
	KYNOFOOD        = "Khối Caramel và Jawsbreaker là những món khoái khẩu của Kyno.",
	WHEAT           = "Lúa Mì có thể được nghiền tại Cối Nghiền để tạo ra Bột Mì.",
	FLOUR           = "Bạn có thể dùng Bột Mì để làm một Ổ Bánh Mì đơn giản. Tuy vậy, Bột Mì còn có rất nhiều công dụng khác ngoài bánh mì.",
	WORMWOOD        = "\"Wormwood nói cậu ấy đã làm một món từ... và Muối. Ta sẽ không ăn thứ đó đâu, Mon dieu!\" -W",
	PIGKING         = "Vua Heo trao đổi nhiều vật phẩm mới. Ví dụ như Bụi Cỏ lấy Bụi Lúa Mì, và Bụi Quả Mọng lấy Bụi Đốm.",
	SERENITYISLAND  = "\"Ta chắc chắn đã thấy một mảnh đất hồng hồng ngoài đại dương! Có lẽ những người đồng hương của ta sẽ đi tìm nó cùng ta...\" -W",
	PIGELDER        = "Trưởng Lão Heo trao đổi nhiều vật phẩm độc quyền để lấy thức ăn.",
	CRABTRAP        = "\"Mấy con cua đá đó cứ tránh hết bẫy của ta! Có lẽ một loại bẫy đặc biệt nào đó sẽ hiệu quả hơn chăng?\" -W",
	SAPTREE         = "Bạn có thể gắn vòi vào Cây Gỗ Đường bằng Bộ Gắn Vòi Cây, để chúng tạo ra Nhựa Cây ngọt ngào mỗi ba ngày.",
	RUINEDSAPTREE   = "Cẩn thận, Cây Gỗ Đường đã gắn vòi nếu tràn đầy Nhựa Cây mà không được thu hoạch thì có thể bị hỏng. Khi đó chúng sẽ tạo ra Nhựa Cây Hỏng!",
	PIGELDERFOODS   = "\"Ta nghe nói con Heo kỳ lạ trên hòn đảo hồng hồng kia muốn một loại thức ăn nào đó... Hình như có liên quan đến Caramel hoặc Wobster.\" -W",
	SALTPOND        = "Bạn có thể câu một loại cá khác trong Ao Muối của Quần Đảo Thanh Bình. Thử xem nào!",
	SALTRACK        = "Giá Muối có thể được lắp trên Ao Muối để tạo ra Tinh Thể Muối mỗi bốn ngày.",
	SPOTTYSHRUB     = "Bụi Đốm có thể được tìm thấy khắp Quần Đảo Thanh Bình. Và chúng có thể được mang về nhà bằng Xẻng.",
	SWEETFLOWER     = "Hoa Ngọt có thể được dùng trong Nồi Nấu như một lựa chọn chất tạo ngọt.",
	LIMPETROCK      = "Nơi duy nhất ngươi tìm được Đá Ốc Mũ là Mỏ Cua của Quần Đảo Thanh Bình hoặc bãi biển của Đảo Ven Biển!",
	SYRUPPOT        = "Xi-rô nấu trong Nồi Xi-rô sẽ cho ra bốn phần thay vì một phần như khi nấu bằng Nồi Nấu thường.",
	COOKWARE        = "Nồi Xi-rô, Nồi Nấu, Bếp Nướng và Lò Nướng nấu thức ăn nhanh hơn Nồi Nấu thường. Và mỗi loại đều có phần thưởng độc quyền riêng!",
	COOKWARE_PIT    = "Để nấu bằng các trạm Dụng Cụ Nấu đặc biệt, trước tiên bạn cần lắp chúng phía trên Hố Lửa.",
	COOKWARE_FIRE   = "Các trạm Dụng Cụ Nấu đặc biệt chỉ nấu thức ăn nếu mức lửa của Hố Lửa bên dưới đủ cao.",
	COOKWARE_OLDPOT = "Trưởng Lão Heo có thể cần ngươi giúp sửa chiếc Nồi Cũ của ông ấy.",
	SPEED_DURATION  = "Bạn có thể thay đổi thời gian kéo dài của Hiệu Ứng Tăng Tốc từ thức ăn trong Cấu Hình Mod.",
	WATERY_CRATE    = "\"Hôm qua khi đang đi thuyền, ta thấy một cái thùng lạ trôi dạt ngoài đại dương. Nếu gặp lại, ta nên kiểm tra thử.\" -W",
	SERENITYCRATE   = "Thùng Trôi Nước câu được ở Quần Đảo Thanh Bình sẽ xuất hiện lại tại cùng vị trí sau bảy ngày.",
	WATERY_CRATE2   = "Thùng Trôi Nước luôn cho ra một Rong Biển và thêm chiến lợi phẩm. Cứ phá chúng để xem ngươi tìm được gì!",
	TUNACAN         = "Cá Ngừ \"Ballphin Free\" sẽ không bao giờ hỏng, trừ khi ngươi mở nó ra.",
	CANNED_SOURCE   = "Bạn có thể lấy Đồ Ăn và Thức Uống Đóng Hộp từ Thùng Trôi Nước và Rương Chìm. Chúc săn kho báu vui vẻ!",
	CRABKING_LOOT   = "Hết Thịt Cua rồi à? Vua Cua có thể là một nguồn cung đáng tin cậy đấy.",
	REGROWTH        = "Các thực thể của mod như Cây Trồng, Cây Cối, v.v. sẽ mọc lại theo thời gian nếu số lượng của chúng trong thế giới quá thấp.",
	BOTTLE_SOUL     = "Wortox có thể cất Linh Hồn vào Chai Rỗng để dành cho những bữa sau.",
	BOTTLE_SOUL2    = "Mọi người sống sót đều có thể mang Linh Hồn Trong Chai trong hành trang, nhưng chỉ Wortox mới có thể Thả Linh Hồn.",
	SOULSTEW        = "Nếu Wortox ăn Hầm Linh Hồn, hắn sẽ nhận đầy đủ chỉ số từ món ăn thay vì chỉ một nửa như với mọi món khác.",
	MYSTERYMEAT     = "\"Ngươi nghe chưa? Có thứ gì đó kỳ lạ bên trong một trong những Thùng Trôi Nước. Có lẽ chúng ta nên đi tìm nó...\" -W",
	KEGANDJAR       = "Thùng Gỗ và Hũ Bảo Quản có thể được dùng để tạo ra các công thức đặc biệt. Chúng mất nhiều thời gian để hoàn thành hơn các công thức khác.",
	ANTIDOTE        = "Cây Gỗ Đường của ngươi bị hỏng rồi à? Đừng lo, chúng có thể được chữa lành! Chỉ cần dùng Thuốc Giải Mốc lên chúng là voilà!",
	MILKABLEANIMALS = "Một số động vật như Beefalo và Koalefant có thể được vắt sữa bằng Xô. Nhưng cẩn thận kẻo bị đá!",
	FORTUNECOOKIE   = "\"Ngươi thật sự tin mấy cái bánh quy ngốc nghếch đó nói được vận may của ngươi à? Hả? C-còn ta thì sao?! T-ta không tin chúng đâu, ta thề!\" -W",
	PINEAPPLEBUSH   = "Bụi Dứa mất nhiều thời gian để lớn hơn trong mọi mùa, trừ Mùa Hè.",
	BREWBOOK        = "Các công thức làm trong Thùng Gỗ hoặc Hũ Bảo Quản sẽ không xuất hiện trong Sách Nấu Ăn. Thay vào đó, bạn có thể xem chúng trong Sổ Ủ Rượu!",
	PIKOS           = "Cẩn thận Piko! Những sinh vật bé nhỏ này rất thích trộm thức ăn từ những con mồi dễ dãi.",
	TIDALPOOL       = "Ao Thủy Triều có nhiều loại cá có thể câu được xuyên suốt các Mùa! Nhớ mang theo Cần Câu Nước Ngọt!",
	GROUPER         = "Cá Mú Tím có thể được câu ở các ao trong Đầm Lầy.",
	MEADOWISLAND    = "\"Đi thuyền vòng quanh thế giới, ta đã khám phá được gần như mọi thứ... Trừ một hòn đảo kỳ lạ đầy Cây Cọ.\" -W",
	INFESTTREE      = "Cây Trà có thể bị Piko gây nhiễm. Nhờ vậy ngươi có thêm nguồn để kiếm mấy nhóc nhỏ đó!",
	POISONBUNWICH   = "Bánh Kẹp Ếch Độc Hại có thể khá khó nấu, nhưng nó có một điểm thú vị: ếch sẽ trở nên hiền với ngươi suốt cả ngày!",
	TWISTEDTEQUILE  = "\"Đêm qua trong bữa tiệc, khi ta uống thứ đồ đó, hình như nó tên là Tequila, đúng không? Thứ đó làm ta chóng mặt đến mức hôm sau ta thấy mình ở một nơi khác!\" -W",
	WATERCUP        = "Muốn thoát khỏi các hiệu ứng bất lợi à? Uống một Cốc Nước và giữ cơ thể đủ nước!",
	NUKACOLA        = "\"Thấy cái chai... \"Nuka-Cola\", tên nó vậy đúng không? Ta nghĩ Wortox đã mang thứ đó từ chiều không gian khác về trong một chuyến đi của hắn.\" -W",
	NUKACOLA2       = "Hương vị độc nhất của Nuka-Cola là kết quả từ sự kết hợp của mười bảy tinh chất trái cây, được cân bằng để nâng tầm vị cola cổ điển. Đánh bay cơn khát!",
	SUGARBOMBS      = "Một gói ngũ cốc ngọt chứa 100% lượng đường khuyến nghị mỗi ngày. Bom Đường đã được bảo quản suốt 25 năm sau Đại Chiến. Tuy nhiên, điều đó cũng khiến phần lớn chúng bị nhiễm một chút phóng xạ.",
	LUNARSOUP       = "\"Ta chẳng sợ gì khi món Sofrito Nấm Mặt Trăng đó trôi xuống bụng ta!\" -W",
	SPRINKLER       = "Mệt vì phải tự tay tưới cây à? Hãy xây ngay một Vòi Tưới Vườn và nói lời tạm biệt với lao động chân tay!",
	NUKASHINE       = "Lewis ban đầu tạo ra Nukashine để có tiền mua một nhà kho cho bộ sưu tập Nuka-Cola của mình, nhưng sự nổi tiếng của nó đã khiến chủ tịch hội Judy Lowell và các thành viên khác của hội Eta Psi cùng tham gia.",
	ITEMSLICER      = "Khối Thịt và một số loại trái cây cứng có thể được cắt lát bằng Dao Phay.",
	ITEMSLICER_GOLD = "Dao Phay Cao Cấp có số lần dùng vô hạn và có thể cắt vật phẩm nhanh hơn Dao Phay thường.",
	SAMMY1          = "Sammy có thể được tìm thấy trên Đảo Ven Biển, nơi anh ta bán đủ loại vật phẩm và nguyên liệu hiếm mà ngươi khó tìm được ngoài kia.",
	SAMMY2          = "Hàng hóa của Sammy thay đổi theo mùa và trong các dịp đặc biệt của thế giới. Nhớ kiểm tra kho hàng của anh ta thỉnh thoảng để xem có gì mới.",
	SAMMY3          = "Sau khi đánh bại Chúa Ruồi Giấm, ngươi nên ghé thăm Sammy. Anh ta sẽ thưởng cho những ai chứng minh được giá trị của mình bằng vài món đồ kỳ lạ!",
	SAMMY4          = "Nếu ngươi nhảy gần Sammy, anh ta cũng sẽ nhập hội!",
	JAWSBREAKER     = "Jawsbreaker có thể dùng để dụ Rockjaw và Gnarwail, giết chúng ngay lập tức. Nhưng đừng dùng nó quá gần bản thân.",
	METALBUCKET     = "Còn gì tốt hơn một cái Xô? Một cái xô kim loại chắc chắn sẽ không vỡ khi vắt sữa động vật!",
	LUNARTEQUILA    = "Cảm thấy hơi nghiêng về phía mặt trăng à? Sao không uống một ly Tequila Khai Sáng để mở tâm trí trước sự thật?",
	MIMICMONSA      = "Nếu ngươi muốn lẻn qua những kẻ địch nguy hiểm, hãy ủ một ly Sneakmosa và sẽ chẳng ai, chẳng thứ gì nhận ra ngươi!",
	RUMMAGEWAGON    = "\"Hôm nọ ta thấy Sammy lục lọi Xe Hàng của anh ta để tìm thứ gì đó. Ta nghĩ anh ta đang trao đổi với ai đó. Có lẽ ta nên xem anh ta cất gì trong đó, biết đâu ta tìm được thứ hữu ích...\" -W",
	RUMMAGEWAGON2   = "\"Đây không phải ăn trộm, ta thề! Sammy đang vứt đi cả đống đồ lặt vặt hữu ích mà chúng ta có thể dùng! Nhìn xem ta lấy được gì từ Xe Hàng của anh ta này!\" -W",
	SLAUGHTERHEAT   = "Cẩn thận! Một số động vật sẽ tấn công nếu ngươi làm thịt đồng loại của chúng khi còn nhiều con ở gần.",
	SLAUGHTERFLEE   = "Một số động vật có thể hoảng sợ bỏ chạy khi thấy ngươi dùng Dụng Cụ Làm Thịt để làm thịt đồng loại của chúng.",
	BOOKGARDENING1  = "Cuốn sách Làm Vườn Bậc Thầy của Wickerbottom có thể làm lớn mọi loại cây, kể cả vài loài cây đặc biệt mà bình thường ngươi không thể trồng!",
	BOOKGARDENING2  = "Cuốn sách Làm Vườn Bậc Thầy của Wickerbottom có cơ hội làm cây trồng nông trại phát triển thành dạng khổng lồ!",
	FARMPLOT        = "Nếu hệ thống trồng trọt mới quá phức tạp với ngươi, đừng lo! Sammy lo được, anh ta đang bán vài bản thiết kế cũ sẽ giúp ích đấy.",
	TRUFFLES1       = "Các vật phẩm liên quan đến Nấm Truffle có thể dùng để kết bạn với Heo, khiến chúng trung thành trong thời gian dài hơn.",
	TRUFFLES2       = "Các vật phẩm liên quan đến Nấm Truffle có thể đem trao đổi với Vua Heo để kiếm vài Cục Vàng dễ dàng.",
	GOLDENAPPLE     = "Táo Vàng Yểm Phép là vật phẩm hiếm có thể nhận được sau khi Hậu Duệ Thiên Thể đã bị đánh bại ít nhất một lần trong thế giới. Chúng cho nhiều hiệu ứng tích cực, với cái giá là sinh mạng của ngươi.",
	FISHROE         = "Trứng cá có thể thu được bằng cách đặt loại cá mong muốn vào Trại Ươm Cá. Một vài loại còn có công thức đặc biệt.",
	FISHFARMPLOT    = "Trại Ươm Cá có thể được dùng để nuôi cá nhằm tạo ra trứng cá và cá con.",
	FISHFARMPLOT2   = "Mỗi loài cá có sở thích riêng khi ở trong Trại Ươm Cá. Các yếu tố đó là: Giai Đoạn Ngày, Pha Trăng, Mùa và Vị Trí.",
	OCEANHUNTS      = "\"Bong Bóng Khả Nghi đang xuất hiện khắp đại dương. Ta tự hỏi mình sẽ tìm thấy gì nếu cứ tiếp tục đi theo chúng?\" -W.",
	OCTOPUSTRADER   = "\"Hôm qua khi đang đi thuyền, ta tìm thấy một con bạch tuộc cô độc đang ngủ gần một cụm cột đá biển. Ta tự hỏi liệu hắn có thứ gì hữu ích để trao đổi không.\" -W.",
	OCTOPUSTRADER2  = "Yaarctopus sẽ trao đổi vật phẩm để lấy Cá và Món Ăn Đã Nấu!",
	HULLBREAKER     = "Một số sinh vật đại dương như Cá Kiếm, Puffernaut và Cá Voi có thể làm hỏng thân Thuyền khi tấn công trúng.",
	CURSEREMOVER    = "\"Ta nghe nói có một món đặc sản của Đảo Bến Trăng có thể xóa lời nguyền! Ta phải thử mới được, công thức nói nó cần một loại wobster ngoại lai nào đó...\" -W.",
	BRAINMETTERSOUP = "\"Sau khi nếm món súp ngớ ngẩn đó, tự nhiên ta thấy mình thông minh hẳn ra, thậm chí chẳng cần trạm chế tạo nữa.\" -W.",
	MALBATROSSFOOD  = "Mồi Cá Mê Hoặc có thể được ném xuống đại dương để triệu hồi một kẻ thù đáng sợ tên là Malbatross.",
	PACKIMBAGGIMS   = "Người bạn đồng hành yêu thích của mọi người đã trở lại! Vật phẩm thân thương của nó có thể được tìm thấy tại Đảo Ven Biển.",
	PACKIMBAGGIMS2  = "Packim Baggims có thể biến đổi bằng cách cho nó ăn Cá Đại Dương Nặng hoặc Cá Thái Dương Cháy Rực.",
	PACKIMBAGGIMS3  = "Packim Baggims Lửa có thể nấu chín ngay lập tức mọi thức ăn bên trong nó. Nó cũng có thể đốt các vật phẩm liên quan đến gỗ thành than.",
	OTTERDENS       = "Có cơ hội Hang Marotter xuất hiện ở cuối một Cuộc Săn Đại Dương khi trời đang mưa.",
	SHARKBOIREWARD  = "Frostjaw đang thèm một bữa ăn tinh tế và hắn sẽ thưởng cho những ai hoàn thành được yêu cầu của hắn.",
	GHOSTPIRATE     = "Khám phá Xác Tàu của các thủy thủ đoàn trước vào Đêm Trăng Tròn có thể khá nguy hiểm, vì Ma Hải Tặc có thể lang thang quanh đó. Rợn người!",
	HERMITWOBSTER   = "Wobster Ẩn Sĩ chỉ có thể được tìm thấy tại Đảo Bến Trăng.",
	SALTEDFISH      = "Cá Khô Lâu Năm có thể thu được bằng cách để Khô Cá phơi lâu hơn.",
	BIRTHDAY5TH     = "Vua Đầu Bếp tròn năm tuổi! Cảm ơn vì tất cả những năm tháng tuyệt vời này!",
	BIRTHDAY_CAKE1  = "Hãy ăn mừng Kỷ Niệm 5 Năm Vua Đầu Bếp với một sự kiện giới hạn thời gian! Nướng và lắp ráp một chiếc bánh khổng lồ, đặt bóng bay và tiệc tùng thôi!",
	BIRTHDAY_CAKE2  = "Bánh Kỷ Niệm có thể được cắt lát bằng Dao Phay, mỗi miếng có một hương vị và hiệu ứng khác nhau.",
	BIRTHDAY_CAKE3  = "Bánh Kỷ Niệm tạo ra một luồng hào quang dịu nhẹ cho những ai ở gần nó.",
	BIRTHDAY_CHEER  = "Trong Sự Kiện Kỷ Niệm Vua Đầu Bếp, Niềm Vui Kỷ Niệm có thể nhận được bằng cách Nấu và Ủ thức ăn khi đang đội Mũ Kỷ Niệm.",
	BIRTHDAY_CORN   = "Máy Làm Bắp Rang có thể tạo ra năm Bắp Rang từ mỗi Bắp. Và trong dịp Kỷ Niệm Vua Đầu Bếp, nó sẽ tạo ra Bắp Rang Kỷ Niệm.",
	CHICKEN1        = "\"Ta tự hỏi liệu những con Gà đó có thể cho ta vài quả trứng không. Ta cần ít hạt giống để kích thích chúng!\" -W",
	CHICKEN2        = "Gà sống trong Chuồng có cơ hội đẻ Trứng Lớn cao hơn.",
	CHICKEN3        = "Gà tìm thấy ngoài tự nhiên có một cơ hội nhỏ đẻ Trứng sau khi ăn.",
	CHICKEN4        = "Gà sống trong Chuồng chỉ tạo ra Trứng nếu chúng ăn thứ gì đó mỗi ngày như Hạt Giống hoặc Ngũ Cốc. Chúng cũng có thể ăn từ Máng Cho Ăn.",
	ANIMALFEEDER    = "Máng Cho Ăn có thể được dùng để cho một số động vật nông trại ăn, chẳng hạn như Gà.",
	WEBSITE         = "Bạn có biết Vua Đầu Bếp có Website chính thức không? Giờ thì biết rồi đấy. Học cách nấu mọi công thức tại: https://heap-of-foods.com",
	DAILYRECIPES1   = "Công Thức Hôm Nay là các món nổi bật được chọn mỗi ngày từ kho công thức. Tất cả người chơi đều có cùng một công thức, bất kể thế giới nào. Mỗi ngày, một công thức sẽ được chọn ngẫu nhiên. Ăn công thức hôm nay sẽ nhận thêm máu, độ no và tinh thần, bên cạnh chỉ số gốc của món ăn. Nó cũng tăng May Mắn trong một khoảng thời gian.",
	DAILYRECIPES2   = "Bạn có thể xem Công Thức Hôm Nay hiện tại bằng cách xây Bảng Công Thức Hôm Nay hoặc thông qua Website chính thức của mod.",
}

for k, v in pairs(LOADINGTIPS) do
	AddLoadingTip(TIPS_HOF, "TIPS_HOF_"..k, v)
end

SetLoadingTipCategoryIcon("OTHER", "images/hof_loadingtips_icon.xml", "hof_loadingtips_icon.tex")

SetLoadingTipCategoryWeights(WEIGHT_START, {OTHER = 4, CONTROLS = 1, SURVIVAL = 1, LORE = 1, LOADING_SCREEN = 1})
SetLoadingTipCategoryWeights(WEIGHT_END,   {OTHER = 4, CONTROLS = 1, SURVIVAL = 1, LORE = 1, LOADING_SCREEN = 1})