------------------------------------------------------------------------------------------------------------
-- World Generation
------------------------------------------------------------------------------------------------------------

-- WORLDGEN RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES = "Nha Đam"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES = "Măng Tây"
STRINGS.UI.CUSTOMIZATIONSCREEN.COFFEEBUSHES = "Cây Cà Phê"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS = "Củ Thì Là"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS = "Củ Cải Vàng Khổng Lồ"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS = "Gốc Nấm"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES = "Nấm Truffle"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS = "Củ Cải Vàng"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES = "Củ Cải Đỏ"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES = "Phiến Đá"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES = "Khoai Lang"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS = "Cải Củ"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS = "Bụi Lúa Mì"

-- WORLDGEN OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.BRAINROCKS = "Mầm Não"
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS = "Hoa Sen"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES = "Thùng Ướt"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS = "Xác Tàu"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS = "Hải Sâm"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS = "Khoai Môn"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES = "Cải Xoong"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA = "Rong Biển"

-- WORLDGEN SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.SERENITYISLAND = "Trưởng Lão Heo"
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS = "Ao Muối"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES = "Bụi Đốm"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS = "Hoa Ngọt"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES = "Cây Gỗ Đường"

-- WORLDGEN MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.MEADOWISLAND = "Sammy"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMHUTS = "Lều Người Cá Câu Cá"
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES = "Thùng Hàng"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES = "Cây Cọ"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS = "Đá Ốc Mũ"
STRINGS.UI.CUSTOMIZATIONSCREEN.MERMHUTS = "Nhà Người Cá"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOTREES = "Cây Trà Bị Nhiễm"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES = "Bụi Dứa"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS = "Đống Cát"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES = "Cây Trà"
STRINGS.UI.CUSTOMIZATIONSCREEN.TIDALPOOLS = "Ao Thủy Triều"

-- WORLDGEN CREATURES
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS = "Gà"
STRINGS.UI.CUSTOMIZATIONSCREEN.DOGFISHES = "Cá Nhám Chó"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS = "Người Cá Câu Cá"
STRINGS.UI.CUSTOMIZATIONSCREEN.HERMITWOBSTERS = "Wobster Ẩn Sĩ"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES = "Sứa"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES2 = "Sứa Cầu Vồng"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS = "Cua Sỏi"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS = "Sóc Piko"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE = "Sóc Piko Cam"
STRINGS.UI.CUSTOMIZATIONSCREEN.PUFFERMONSTERS = "Puffernaut"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES = "Sugarfly"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWORDFISHES = "Cá Kiếm"

------------------------------------------------------------------------------------------------------------
-- World Settings
------------------------------------------------------------------------------------------------------------

-- GLOBALSETTINGS
STRINGS.UI.CUSTOMIZATIONSCREEN.HOFBIRTHDAY = "Kỷ Niệm Vua Đầu Bếp"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANHUNTS_SETTING = "Cuộc Săn Biển"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANHUNTALTS_SETTING = "Bất Ngờ Cuộc Săn Biển"

-- WORLDSETTINGS RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES_SETTING = "Nha Đam"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES_SETTING = "Măng Tây"
STRINGS.UI.CUSTOMIZATIONSCREEN.COFFEEBUSHES_SETTING = "Cây Cà Phê"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS_SETTING = "Củ Thì Là"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS_SETTING = "Củ Cải Vàng Khổng Lồ"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS_SETTING = "Gốc Nấm"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES_SETTING = "Nấm Truffle"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS_SETTING = "Củ Cải Vàng"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES_SETTING = "Củ Cải Đỏ"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES_SETTING = "Phiến Đá"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES_SETTING = "Khoai Lang"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS_SETTING = "Cải Củ"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS_SETTING = "Bụi Lúa Mì"

-- WORLDSETTINGS OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.BRAINROCKS_SETTING = "Mầm Não"
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS_SETTING = "Hoa Sen"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES_SETTING = "Thùng Ướt"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS_SETTING = "Xác Tàu"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS_SETTING = "Hải Sâm"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS_SETTING = "Khoai Môn"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES_SETTING = "Cải Xoong"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA_SETTING = "Rong Biển"

-- WORLDSETTINGS SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS_SETTING = "Giá Muối"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES_SETTING = "Bụi Đốm"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS_SETTING = "Hoa Ngọt"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES_SETTING = "Cây Gỗ Đường"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAPSUGARTREES_SETTING = "Nhựa Cây"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAP2SUGARTREES_SETTING = "Nhựa Cây Hỏng"
STRINGS.UI.CUSTOMIZATIONSCREEN.RUINEDSUGARTREES_SETTING = "Cây Gỗ Đường Đổ Nát"

-- WORLDSETTINGS MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES_SETTING = "Thùng Hàng"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES_SETTING = "Cây Cọ"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS_SETTING = "Đá Ốc Mũ"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES_SETTING = "Bụi Dứa"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS_SETTING = "Đống Cát"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES_SETTING = "Cây Trà"

-- WORLDSETTINGS CREATURES
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS_SETTING = "Gà"
STRINGS.UI.CUSTOMIZATIONSCREEN.DOGFISHES_SETTING = "Cá Nhám Chó"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS_SETTING = "Người Cá Câu Cá"
STRINGS.UI.CUSTOMIZATIONSCREEN.HERMITWOBSTERS_SETTING = "Wobster Ẩn Sĩ"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES_SETTING = "Sứa"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES2_SETTING = "Sứa Cầu Vồng"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS_SETTING = "Cua Sỏi"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS_SETTING = "Sóc Piko"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE_SETTING = "Sóc Piko Cam"
STRINGS.UI.CUSTOMIZATIONSCREEN.PUFFERMONSTERS_SETTING = "Puffernaut"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES_SETTING = "Sugarfly"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWORDFISHES_SETTING = "Cá Kiếm"