-- Common Dependencies.
-- local _G 			= GLOBAL
-- local require 		= _G.require
-- local STRINGS		= _G.STRINGS

-- Datas. (Unused)
STRINGS.SCRAPBOOK.DATA_BREWER = "可以喝酒"
STRINGS.SCRAPBOOK.FOODTYPE.PREPAREDPOOP = "可怕"
STRINGS.SCRAPBOOK.FOODTYPE.PREPAREDSOUL = "灵魂"
STRINGS.SCRAPBOOK.FOODTYPE.ALCOHOLIC = "酒精"

-- Categories.
STRINGS.SCRAPBOOK.CATS.ARTISAN = "工匠\n物品"

-- Sub Categories.
STRINGS.SCRAPBOOK.SUBCATS.CHICKEN = "鸡"
STRINGS.SCRAPBOOK.SUBCATS.PIKO = "异食松鼠"
STRINGS.SCRAPBOOK.SUBCATS.CANNED = "罐头"
STRINGS.SCRAPBOOK.SUBCATS.COOKWARE = "炊具"
STRINGS.SCRAPBOOK.SUBCATS.SEASONALFOOD = "季节性食物"
STRINGS.SCRAPBOOK.SUBCATS.ARTISANGOODS = "工匠物品"
STRINGS.SCRAPBOOK.SUBCATS.WINE = "酒"
STRINGS.SCRAPBOOK.SUBCATS.JUICE = "果汁"
STRINGS.SCRAPBOOK.SUBCATS.JAM = "果酱"
STRINGS.SCRAPBOOK.SUBCATS.PICKLES = "腌菜"

-- Food Effects.
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SPEED = "在一定时间内提高移动速度。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_COFFEE = "在一定时间内提高移动速度和催眠抗性。短暂升高温度。\n\n再见，宝贝！"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SLEEP = "在一定时间内增加催眠抗性。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HEALTHREGEN = "短时间内回复生命值。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HUNGERREGEN = "短时间内回复饥饿值。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SANITYREGEN = "短时间内回复理智值。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SUPERREGEN = "短时间内超强的身体回复。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WORMLIGHT = "短时间内焕发健康光彩。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ALCOHOL = "在一定时间内增加伤害和降低移动速度。适量饮用。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ALCOHOL2 = "在一定时间内提高防御能力并降低移动速度。适量饮用。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_RUM = "在一定时间内提高对海盗的伤害。\n\n火焰和深渊都无法吞噬我。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_TEQUILA = "将幸存者传送到地图中的随机位置。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKACOLA = "核子可乐的独特口味是由17种水果精华组合而成的，这些水果精华相互配合造就了可乐的经典口味。消除口渴！"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_QUANTUM = "核子可乐的独特口味是由17种水果精华组合而成的，这些水果精华相互配合造就了可乐的经典口味。消除口渴！\n\n量子核可乐的热量、碳水化合物、咖啡因和口味都是普通可乐的两倍！"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_INSANITY = "让人在短时间内精神错乱。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NIGHTVISION = "在一定时间内提供夜视效果。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NAUGHTY = "吃了这种用可怜无辜灵魂的器官做成的食物，附近就会产生 \"它\"。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HASTE = "在一定时间内提高所有行动的速度。薇诺娜不会从该效果中受益。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BLOOM = "将便便混在一起扔进锅里煮，可以将花期估算到最大限度。\n\n\"艺术!\" - 沃姆伍德."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SOUL = "用收获的灵魂制作的特殊食物。\n\n与其他普通食物不同，沃托克斯可以吃这种食物来获得它的全部益处，而不会受到任何惩罚。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_DEERCLOPS = "吃了这个食物，附近会出现独眼巨鹿。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BEARGER = "吃了这个食物，附近会出现熊大。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FORTUNE = "破解一个，看看命运为你保留了什么。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WATER = "清除幸存者当前的所有食物效果。\n短暂降低温度。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FROG = "吃了这种食物，所有青蛙都会在一定时间内对你友好。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_CURSE = "伍迪吃了这种食物后，就能随机选择一种变身方式。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FEARLESS = "这种食物能让幸存者在一定时间内无所畏惧。在此期间，精神错乱光环不会产生任何影响。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MONSTERFOOD = "韦伯可以吃这种食物，不会受到任何惩罚。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MONSTERFOOD2 = "韦伯可以吃这种食物而不会受到任何惩罚.\n短暂升高温度。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WURTFOOD = "吃这种食物会给沃特带来额外的好处。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLAYERMONSTER = "韦伯可以吃这种食物而不会受到任何惩罚\n吃这种食物会给沃特带来额外的好处。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLAYERMONSTER2 = "韦伯可以吃这种食物而不会受到任何惩罚。\n沃特会从吃这种食物中获得额外的好处。\n短暂降低温度。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLAYERMONSTER3 = "韦伯可以吃这种食物而不会受到任何惩罚。\n沃特会从吃这种食物中获得额外的好处。\n短暂升高温度。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SPIDERCAKE = "韦伯可以吃这种食物而不会受到任何惩罚。\n\n饥荒联机版x咩咩启示录 - 联动2023."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SUGARBOMBS = "甜麦炮弹是含糖量达到每日推荐量的一种麦片，在第一次大战之后保存了25年。不过，这也导致大部分甜麦炮弹受到了辐射。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKASHINE = "Nukashine是由Vault-Tec大学EtaPsi兄弟会的路易斯于2076年11月创造的。 这种烈酒本身效果惊人，会导致昏厥、严重宿醉，并有可能致命，Pi Mu兄弟会的同伴在他们的 \"驱逐派对\"上就发现了这一点。\n\n此外，还有一种无糖版本，由于不含糖，饮用这种饮料不会有停电的危险。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKASHINE2 = "现在没有任何混乱风险！尽情狂欢吧！"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BONESOUP = "在一定时间内提高对虫子的伤害。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_REVIVER = "在闹鬼时立即复活死去的玩家。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MOCHA = "在一定时间内，提高移动速度，增加催眠抗性，饱食度消耗降低。\n\n短暂升高温度。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_LESSFREEZING = "温度短暂升高，不易受冷。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_LESSOVERHEAT = "短暂降低温度，不易过热。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FISHING = "在一定时间内提高捕捞产量。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MIGHTINESS = "稍微增强力量。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_INSPIRATION = "略微激发灵感。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WARLYTEA = "在一定时间内减少理智损失。\n短暂升高温度。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_INCREASETEMP = "短暂升高温度。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_DECREASETEMP = "短暂降低温度。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BOUILLABAISSE = "在一定时间内增加催眠抗性。\n短暂降低温度。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MOISTURE = "清空潮湿值并在一定时间内保持干燥。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SUGARBOMBS_EXPLOSIVE = "这些糖衣炸弹内藏引爆味蕾的惊喜！"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_EATER = "使食物在一段时间内保持松软易食。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_CRABKINGFEAST = "在一定时间内对螃蟹造成额外伤害。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ANTLION = "在一定时间内满足蚁狮的需求。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_JAWSBREAKER = "当被扔进海洋时，可以吸引并击杀岩石大白鲨和一角鲸。如果距离太近则无效。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FIREIMMUNITY = "这种食物可以在一定时间内对火焰免疫。短暂提升温度。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_TIRAMISU = "在一定时间内提升移动速度。\n\n干燥，在一定时间内免疫潮湿效果。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_AMPHIBIAN = "在一定时间内对两栖生物造成额外伤害。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ENLIGHTENMENT = "在一定时间内提供启迪。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_STEALTH = "在一定时间内对陷阱和生物不可见且无法被探测到。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLANARDEFENSE = "在一定时间内提升位面防御能力。"

-- Spice Effects.
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_CURE = "可通过便携调味站添加至烹饪锅料理中。\n\n食用含防腐粉末的料理可使腐败速率减半，并免除食用变质食物的惩罚。"
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_MIND = "可通过便携调味站添加至烹饪锅料理中。\n\n食用含舒缓糖粉调味的料理可获得25%额外精神值。"
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_FED = "可通过便携调味站添加至烹饪锅料理中。\n\n食用含淀粉调味的料理可获得25%额外饱食度"
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_FIRE = "可通过便携调味站添加至烹饪锅料理中。\n\n食用含烈焰水晶调味的料理会使你的攻击点燃目标。\n\n持续时间4分钟。\n\n还将温度升高15度，持续15秒。"
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_COLD = "可通过便携调味站添加至烹饪锅料理中。\n\n食用含冰霜水晶调味的料理会使你的攻击冻结目标。\n\n持续时间4分钟。\n\n还将温度降低15度，持续15秒。"

-- Items & Foods.
STRINGS.SCRAPBOOK.SPECIALINFO.SALT = "在烹饪锅里放一小撮盐，食物的变质时间就会缩短30%。再也不用担心吃到变质的菜肴了！"
STRINGS.SCRAPBOOK.SPECIALINFO.SALTRACK = "这个架子每隔几天就会收集一小块盐石。"
STRINGS.SCRAPBOOK.SPECIALINFO.CRABTRAP = "一旦设置在地面上后，当螃蟹移动到附近时，它就会触发，捕捉它们。\n\n收集捕获的陷阱会将该生物放入你的库存中。\n\n捕蟹笼可以用肉类作为诱饵。"
STRINGS.SCRAPBOOK.SPECIALINFO.CARAMELCUBE = "这道菜是一道美味佳肴，是甜美和爱的结晶。对于嗜糖的人来说，这是一道特殊的菜肴，非常非常受老年人的欢迎。"
STRINGS.SCRAPBOOK.SPECIALINFO.NECTAR = "为足够多的花朵授粉的蜜蜂被杀死后会掉落花蜜。\n\n花蜜储存在蜂蜜储藏室后就会变成蜂蜜。"
STRINGS.SCRAPBOOK.SPECIALINFO.BOTTLESOUL = "瓶装灵魂不计入沃托克斯的库存总量。"
STRINGS.SCRAPBOOK.SPECIALINFO.BOTTLECAP = "核子可乐公司生产的瓶盖经久耐用、便于携带，而且一眼就能辨认出来！"
STRINGS.SCRAPBOOK.SPECIALINFO.CANNEDFOOD = "非凡的应急食物来源。除非你打开它，否则它永远不会腐烂！"
STRINGS.SCRAPBOOK.SPECIALINFO.BREWBOOK = "记录酿造和/或饮用的所有饮料，以及用于酿造这些饮料的原料。"
STRINGS.SCRAPBOOK.SPECIALINFO.BUCKET = "可以用木桶从动物身上收集牛奶。\n\n要小心，因为当你尝试这样做时，有些人可能会生气。记住一定要穿安全服。\n\n从驯养的动物身上更容易获得牛奶，因为它们的产量更高。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_HANGER_ITEM = "该吊架可安装在火坑上方，用于放置烹饪锅具。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_POT_ITEM = "这种烹饪锅需要在火坑上方放置一个吊架。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_OVEN_ITEM = "这种烤箱可以安装在火盆上，在里面放置平底锅。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_CASSEROLE_ITEM = "这种平底锅需要一个放在火坑上的烤箱。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_GRILL_ITEM = "这种烤架可安装在火塘上，用于烹制食物。"
STRINGS.SCRAPBOOK.SPECIALINFO.HUMANMEAT = "该战役需延后。请先完成当前杀戮。\n\n人肉可以从幸存者的尸体上获得。"
STRINGS.SCRAPBOOK.SPECIALINFO.MUSSELSTICK_ITEM = "可长期放置在水中捕捉贻贝。"
STRINGS.SCRAPBOOK.SPECIALINFO.REPAIRTOOLKIT = "用于修复被破坏的结构。"
STRINGS.SCRAPBOOK.SPECIALINFO.SAPBUCKET = "把它安装到糖木树上，每隔几天就会产生新鲜的树液。"
STRINGS.SCRAPBOOK.SPECIALINFO.SLAUGHTERTOOL = "可立即杀死动物的屠宰工具。"
STRINGS.SCRAPBOOK.SPECIALINFO.SAPHEALER = "强大的解毒剂，具有治疗树木的功能。\n\n对被感染的糖木树使用它可以使其恢复到正常阶段。"
STRINGS.SCRAPBOOK.SPECIALINFO.ITEMSLICER = "用于切肉块和其他东西。"
STRINGS.SCRAPBOOK.SPECIALINFO.ITEMSLICER2 = "切肉块和其他东西，更快！"
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMYHAT = "减少饥饿感15%。"
STRINGS.SCRAPBOOK.SPECIALINFO.POTATOSACK = "一个拥有6个格位的容器，可以存放土豆相关的物品，并延长它们的新鲜度。\n\n\"土豆让肚子更强壮！\" - 沃尔夫冈。"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODSACK = "一个8格防水容器，无论天气如何都能保持食材新鲜。\n\n它巧妙的设计不仅减缓食材腐败，还能恢复已经开始变质的食材的新鲜度。\n\n它散发着神秘的冰霜魔力，冻结容器内的一切。"
STRINGS.SCRAPBOOK.SPECIALINFO.BOOK_GARDENING = "快速催熟附近的各种植物。\n\n\"一本用活根装订的古老典籍，因其能扭曲自然意志的强大力量而被禁。书页低语着被遗忘的咒语，能够唤醒大地本身，将普通土壤变为无法驯服的生机盎然之地。\" - 未知作者。"

-- Creatures.
STRINGS.SCRAPBOOK.SPECIALINFO.FEEDCHICKEN = "可以用种子喂它，让它下蛋。"
STRINGS.SCRAPBOOK.SPECIALINFO.PIKO = "毛茸茸的小家伙，喜欢偷你最值钱的东西！"
STRINGS.SCRAPBOOK.SPECIALINFO.KINGFISHER = "翠鸟经常会从上空投下热带锦鲤。真是一场鱼雨！"

-- Structures, Misc & Point of Interest.
STRINGS.SCRAPBOOK.SPECIALINFO.PIGELDER = "来自遥远群岛的商人。他愿意用最好的炊具和其他有用的物品换取美味佳肴。\n\n长老想吃极甜的食物或黄油海鲜。他会给你相应的奖励。\n\n把长老最喜欢的食物带过来会解锁更多交易"
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMY = "来自异世界的商人。他不知何故流落到永恒领域群岛之一，并在那里开了一家以物易物的店铺。\n\n萨米在各个季节以及一些特殊场合都会交易各种稀有物品。记得时不时去看看他的商品，看看他有什么好东西。\n\n如果你带一份让他想起家乡的礼物，萨米会给你丰厚的奖励。"
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMYHOUSE = "萨米的小店陈列着来自遥远国度和异世界的神奇物品与古董。"
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMYWAGON = "萨米的宝贝小推车。别被它的大小迷惑了，里面能装很多东西呢。"
STRINGS.SCRAPBOOK.SPECIALINFO.SALTPOND = "富含盐分的池塘。可以安装盐架，每隔几天就能轻松获得盐晶。"
STRINGS.SCRAPBOOK.SPECIALINFO.MEALGRINDER = "站在这个装置附近，幸存者就能获得可以研磨的新原料。\n\n每次要研磨新的食材时，您都需要在碾磨石附近。"
STRINGS.SCRAPBOOK.SPECIALINFO.PIKOTREE = "站在树旁可为幸存者提供35%的防雨保护和少量降温。\n\n这些茶树上有一种被称为异食松鼠的小生物，它们随时准备制造麻烦。"
STRINGS.SCRAPBOOK.SPECIALINFO.ANTCHEST = "这种特殊的箱子只能存放蜂蜜类物品，最多可同时存放7件物品。它还会散发出健康的光芒。\n\n如果把蜂蜜类食品存放在里面，箱子就会刷新它们的变质时间，并使它们永远保持新鲜。\n\n储存在里面的花蜜最终会变成蜂蜜。"
STRINGS.SCRAPBOOK.SPECIALINFO.BREWER = "一个有3个插槽的容器，可以接收酿酒原料。\n\n在容器中放入3件物品，就可以根据最初放入的物品酿造出某种食物。\n\n这个过程通常需要几天才能完成。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_HANGER = "用来装烹饪锅。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_POT_SMALL = "一個有 3 個欄位的容器，可用於放入烹飪食材。\n\n放入 3 種材料後即可開始烹飪，最終產出取決於所放入的材料。\n\n此鍋烹飪速度比普通鍋更快，並額外產出一份料理。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_POT = "一個有 4 個欄位的容器，可用於放入烹飪食材。\n\n放入 4 種材料後即可開始烹飪，最終產出取決於所放入的材料。\n\n此鍋烹飪速度比普通鍋更快，並額外產出 2 份料理。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_SYRUP_POT = "一個有 4 個欄位的容器，可用於製作糖漿。\n\n放入 4 份樹液後即可烹煮成糖漿。\n\n此鍋僅可製作糖漿，並會額外產出 3 份糖漿。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_OVEN = "用於放置烤盤。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_CASSEROLE_SMALL = "一個有 3 個欄位的容器，可用於放入烹飪食材。\n\n放入 3 種材料後即可開始烹飪，最終產出取決於所放入的材料。\n\n此鍋烹飪速度比普通鍋更快，並可在內部保存已煮熟的食物。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_CASSEROLE = "一個有 4 個欄位的容器，可用於放入烹飪食材。\n\n放入 4 種材料後即可開始烹飪，最終產出取決於所放入的材料。\n\n此鍋烹飪速度比普通鍋更快，並可在內部保存已煮熟的食物。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_GRILL_SMALL = "一個有 3 個欄位的容器，可用於放入烹飪食材。\n\n放入 3 種材料後即可開始烹飪，最終產出取決於所放入的材料。\n\n此烤架烹飪速度比普通鍋更快，並總是產出新鮮料理。"
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_GRILL = "一個有 4 個欄位的容器，可用於放入烹飪食材。\n\n放入 4 種材料後即可開始烹飪，最終產出取決於所放入的材料。\n\n此烤架烹飪速度比普通鍋更快，並總是產出新鮮料理。"
STRINGS.SCRAPBOOK.SPECIALINFO.KOKONUTTREE = "站在树旁可为幸存者提供35%的防雨保护和少量降温。\n\n注意掉落的椰子！"
STRINGS.SCRAPBOOK.SPECIALINFO.MUSSELSTICK = "这根棍子对贻贝来说是不可抗拒的，放置一段时间后，它就会长满贻贝，供你采集。"
STRINGS.SCRAPBOOK.SPECIALINFO.MUSHSTUMP = "这种树桩上生长着一种特殊的菌类，被许多人视为美味佳肴。\n\n它的生长需要近5天的时间。"
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE = "站在树旁可为幸存者提供35%的防雨保护和少量降温。\n\n这些树木可以使用树木挖掘工具包进行挖掘，每隔几天就能产出新鲜树液。"
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_SAPPED = "站在树旁可为幸存者提供35%的防雨保护和少量降温。\n\n生产汁液需要近3天的时间。\n\n不要让汁液溢出来，否则会毁坏它。"
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_RUINED = "站在树旁可为幸存者提供35%的防雨保护和少量降温。\n\n被毁坏的糖木树无法生产新鲜树液，只能生产被毁坏的树液。\n\n您可以使用解毒剂治愈被毁坏的树木。"
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_RUINED2 = "站在树旁可为幸存者提供35%的防雨保护和少量降温。\n\n您可以使用解毒剂治愈被毁坏的树木。"
STRINGS.SCRAPBOOK.SPECIALINFO.RUBBLE = "长老希望您能帮助他修复旧锅，让他重新开始制作美味的糖浆。"
STRINGS.SCRAPBOOK.SPECIALINFO.PINEAPPLEBUSH = "菠萝丛需要近6天才能完全生长。除夏季外，其他季节都需要更长的生长时间。\n\n在夏季，它们每两天就会开始生长一次。"
STRINGS.SCRAPBOOK.SPECIALINFO.GARDENSPRINKLER = "可以开启和关闭。加满燃料并开启时，会自动为范围内的农作物浇水。"
STRINGS.SCRAPBOOK.SPECIALINFO.FARMPLOT = "允许种植和生长种子。\n\n种下的种子会随机生长为作物。使用作物种子可以种出特定作物。\n\n农场在收获一定次数后会耗尽，需要施肥才能继续种植。正在生长的作物可以施肥以加快生长速度。\n\n此施肥仅影响作物本身，不会影响农场本身的施肥状态。"
STRINGS.SCRAPBOOK.SPECIALINFO.SURFACEBANANATREE = "一种稀有而难觅的奇异树木，能够在地下环境之外生长。\n\n据说在自然中已灭绝，仅有少数被专门的看护者照料。"
STRINGS.SCRAPBOOK.SPECIALINFO.DECIDUOUSSHOP = "一座神秘的住宅，长久沉寂，其门或许有一天会打开……揭示其中的秘密。\n\n请在2026年的下一次重大更新中再来探访！"