------------------------------------------------------------------------------------------------------------
-- World Generation
------------------------------------------------------------------------------------------------------------

-- WORLDGEN RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES = "芦荟"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES = "芦笋"
STRINGS.UI.CUSTOMIZATIONSCREEN.COFFEEBUSHES = "咖啡丛"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS = "茴香"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS = "巨型防风草"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS = "蘑菇桩"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES = "松露"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS = "防风草"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES = "红萝卜"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES = "石板"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES = "红薯"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS = "芜菁"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS = "小麦"

-- WORLDGEN OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.BRAINROCKS = "智慧小穗"
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS = "莲花"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES = "水箱"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS = "沉船"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS = "海黄瓜"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS = "芋头"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES = "西洋菜"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA = "海藻"

-- WORLDGEN SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.SERENITYISLAND = "猪长老"
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS = "盐池"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES = "斑点灌木"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS = "甜花"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES = "糖木树"

-- WORLDGEN MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.MEADOWISLAND = "萨米"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMHUTS = "渔人的小屋"
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES = "箱子"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES = "椰子树"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS = "帽贝岩"
STRINGS.UI.CUSTOMIZATIONSCREEN.MERMHUTS = "鱼人小屋"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOTREES = "受侵害的茶树"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES = "菠萝丛"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS = "沙堆"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES = "茶树"
STRINGS.UI.CUSTOMIZATIONSCREEN.TIDALPOOLS = "潮汐池"

-- WORLDGEN CREATURES
STRINGS.UI.CUSTOMIZATIONSCREEN.ANTCHOVIES = "蚁头凤尾小鱼"
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS = "鸡"
STRINGS.UI.CUSTOMIZATIONSCREEN.DOGFISHES = "狗鱼"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS = "渔人"
STRINGS.UI.CUSTOMIZATIONSCREEN.HERMITWOBSTERS = "寄居龙虾"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES = "水母"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES2 = "彩虹水母"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS = "卵石蟹"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS = "异食松鼠"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE = "橙色异食松鼠"
STRINGS.UI.CUSTOMIZATIONSCREEN.PUFFERMONSTERS = "河豚"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES = "糖蝴蝶"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWORDFISHES = "剑鱼"

------------------------------------------------------------------------------------------------------------
-- World Settings
------------------------------------------------------------------------------------------------------------

-- GLOBALSETTINGS
STRINGS.UI.CUSTOMIZATIONSCREEN.HOFBIRTHDAY = "更多料理周年庆"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANHUNTS_SETTING = "海洋狩猎"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANHUNTALTS_SETTING = "海洋猎奇之旅"

-- WORLDSETTINGS RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES_SETTING = "芦荟"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES_SETTING = "芦笋"
STRINGS.UI.CUSTOMIZATIONSCREEN.COFFEEBUSHES_SETTING = "咖啡丛"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS_SETTING = "茴香"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS_SETTING = "巨型防风草"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS_SETTING = "蘑菇桩"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES_SETTING = "松露"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS_SETTING = "防风草"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES_SETTING = "红萝卜"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES_SETTING = "石板"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES_SETTING = "红薯"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS_SETTING = "芜菁"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS_SETTING = "小麦"

-- WORLDSETTINGS OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.BRAINROCKS_SETTING = "智慧小穗"
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS_SETTING = "莲花"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES_SETTING = "水箱"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS_SETTING = "沉船"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS_SETTING = "海黄瓜"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS_SETTING = "芋头"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES_SETTING = "西洋菜"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA_SETTING = "海藻"

-- WORLDSETTINGS SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS_SETTING = "盐池"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES_SETTING = "斑点灌木"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS_SETTING = "甜花"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES_SETTING = "糖木树"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAPSUGARTREES_SETTING = "树液"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAP2SUGARTREES_SETTING = "变质的树液"
STRINGS.UI.CUSTOMIZATIONSCREEN.RUINEDSUGARTREES_SETTING = "被感染的糖木树"

-- WORLDSETTINGS MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES_SETTING = "箱子"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES_SETTING = "椰子树"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS_SETTING = "帽贝岩"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES_SETTING = "菠萝丛"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS_SETTING = "沙堆"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES_SETTING = "茶树"

-- WORLDSETTINGS CREATURES
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS_SETTING = "鸡"
STRINGS.UI.CUSTOMIZATIONSCREEN.DOGFISHES_SETTING = "狗鱼"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS_SETTING = "渔人"
STRINGS.UI.CUSTOMIZATIONSCREEN.HERMITWOBSTERS_SETTING = "寄居龙虾"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES_SETTING = "水母"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES2_SETTING = "彩虹水母"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS_SETTING = "卵石蟹"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS_SETTING = "异食松鼠"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE_SETTING = "橙色异食松鼠"
STRINGS.UI.CUSTOMIZATIONSCREEN.PUFFERMONSTERS_SETTING = "河豚"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES_SETTING = "糖蝴蝶"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWORDFISHES_SETTING = "剑鱼"