STRINGS.BREWBOOK_TITLE = "酿造手册"
STRINGS.BREWBOOK_DESC = "新手的酿造指南"

STRINGS.UI.CRAFTING_FILTERS.MEALING = "食物成分"
STRINGS.UI.CRAFTING_FILTERS.SERENITYSHOP = "长者的补给品"
STRINGS.UI.CRAFTING_FILTERS.MEADOWSHOP = "萨米的小店"
STRINGS.UI.CRAFTING.NEEDSMEALING_ONE = "使用碾磨石研磨这种成分！"
STRINGS.UI.CRAFTING.NEEDSMEALING_TWO = "使用碾磨石研磨这种成分！"
STRINGS.UI.CRAFTING.NEEDSSERENITYSHOP = "找一个非常友好的人来完成这个交易！"
STRINGS.UI.CRAFTING.NEEDSSERENITYSHOP_ONE = "找一个非常友好的人来完成这个交易！"
STRINGS.UI.CRAFTING.NEEDSSERENITYSHOP_TWO = "找一个非常友好的人来完成这个交易！"
STRINGS.UI.CRAFTING.NEEDSMEADOWSHOP = "寻找萨米完成交易！"
STRINGS.UI.CRAFTING.NEEDSMEADOWSHOP_ONE = "寻找萨米完成交易！"
STRINGS.UI.CRAFTING.NEEDSMEADOWSHOP_TWO = "寻找萨米完成交易！"
STRINGS.UI.CRAFTING.NEEDSHOFBIRTHDAY = "更多料理周年庆期间限量供应！"
STRINGS.UI.CRAFTING.RECIPEACTION.MEALGRINDER = "研磨"
STRINGS.UI.CRAFTING.RECIPEACTION.SERENITYSHOP = "交易"
STRINGS.UI.CRAFTING.RECIPEACTION.MEADOWSHOP = "兑换" -- Trade?

STRINGS.UI.SPECIAL_EVENT_NAMES.HOFBIRTHDAY = "更多料理周年庆纪念"

STRINGS.UI.FOOD_TYPES.PREPAREDSOUL = "灵魂"
STRINGS.UI.FOOD_TYPES.PREPAREDPOOP = "可怕" -- 使用可怕只是为了模仿食谱。
STRINGS.UI.FOOD_TYPES.ALCOHOLIC = "好东西" -- 只是为了模仿。

STRINGS.UI.COOKBOOK.TAB_TITLE_MOD_WARLY = "大厨的Mod特色菜"
STRINGS.UI.COOKBOOK.TAB_TITLE_KEG = "酿造配方"
STRINGS.UI.COOKBOOK.TAB_TITLE_JAR = "腌制配方"
STRINGS.UI.COOKBOOK.TAB_TITLE_ARTISAN = "工匠配方"
STRINGS.UI.COOKBOOK.BREWINGTIME_TITLE = "制作时长"
STRINGS.UI.COOKBOOK.FILTER_GOODIES = "好东西"
STRINGS.UI.COOKBOOK.LOCKED_STATS_ARTISAN = "这种饮品需要饮用后才能了解更多信息。"
STRINGS.UI.COOKBOOK.LOCKED_RECIPE.KEG = "使用精酿桶酿造食材来发现新的饮品并扩充你的酿造手册。"
STRINGS.UI.COOKBOOK.LOCKED_RECIPE.JAR = "使用罐头瓶腌制食材来发现新的罐头并扩展你的酿造手册。"
STRINGS.UI.COOKBOOK.LOCKED_RECIPE.ARTISAN = "在酿造站中酿造食材来发现新的配方并扩展你的酿造手册。"
STRINGS.UI.COOKBOOK.LOCKED_RECIPE.MOD = "在烹饪站用食材烹饪来发现新食谱并扩充你的食谱。"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SPEED = "提升移速"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SPEEDSLEEP = "提升移速并抵御催眠"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_CAKE = "蛋糕是个谎言"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_NAUGHTINESS = "增加淘气值"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_REHEALTH = "随着时间回复生命值"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_REHUNGER = "随着时间回复饥饿值"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_RESANITY = "随着时间回复理智值"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_REALL = "一段时间内回复所有状态"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_GEARS = "机甲进化"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_HURT = "伤害身体"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_GLERMZ = "刺激开花"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_KYNO = "Kyno的最爱"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_CAT = "给你的小猫咪"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_KAT = "给你毛茸茸的小猫"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SOUL = "灵魂饥饿杀手"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_BOSS = "召唤boss"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_FORTUNE = "告诉你的未来"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_HANDS = "提高工作效率"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_ALCOHOL = "增强力量\n适度饮酒"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_DESANITY = "持续降低理智值"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_DAMAGEREDUCTION = "增加防御\n适度饮酒"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_CLEAR = "清除所有死亡影响"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_FROG = "无视青蛙仇恨"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_RUM = "提高对海盗的伤害"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_BONESOUP = "增加对蠕虫的伤害"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_TEQUILA = "扭曲时空"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_CURSE = "激活诅咒"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_FEAR = "抵御恐惧"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_FEARSLEEP = "抵御恐惧和催眠"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_NIGHTVISION = "提供夜视能力"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_NUKASHINE = "可能导致混乱"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_FISHING = "提高捕鱼量"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_HUNGERRATE = "降低饥饿消耗"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SANITYRATE = "降低精神消耗"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_MIGHTINESS = "略微增强力量"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_INSPIRATION = "略微激发灵感"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SUGARBOMBS = "引爆味蕾！"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_EATER = "加速消化"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_ANTLION = "安抚boss"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_CRAB = "增加对螃蟹的伤害"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_JAWSBREAKER = "吸引海洋生物"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_FIREIMMUNITY = "火焰免疫能力"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_AMPHIBIAN = "增加对青蛙的伤害" -- "amphibians" is too large for Cookbook.
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_ENLIGHTENMENT = "启迪心智"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_STEALTH = "隐藏你的存在"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_PLANARDEFENSE = "提升位面防御力"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_TRUFFLES = "引诱猪人"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SPORECAP = "赋予毒素免疫力"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_SPORECAP_DARK = "赋予酸性免疫力"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_PUFFERFISH = "可能有毒"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_EXQUISITE = "精致的餐点"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_CURSE_MONKEY = "打破猴子诅咒"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_CRAFTING = "刺激大脑"
STRINGS.UI.COOKBOOK.FOOD_EFFECTS_BEEFRIENDLY = "安抚附近的蜜蜂"

STRINGS.UI.PLANTREGISTRY.DESCRIPTIONS.KYNO_ALOE = "绿色蔬菜，草原之王"
STRINGS.UI.PLANTREGISTRY.DESCRIPTIONS.KYNO_CUCUMBER = "许多海洋礼物之一，深受有文化的人喜爱。-W"
STRINGS.UI.PLANTREGISTRY.DESCRIPTIONS.KYNO_RADISH = "鲜红如血，美味无双。 -W"
STRINGS.UI.PLANTREGISTRY.DESCRIPTIONS.KYNO_FENNEL = "一种来自地下的经典苦味块茎。 -W"
STRINGS.UI.PLANTREGISTRY.DESCRIPTIONS.KYNO_SWEETPOTATO = "比普通土豆甜十倍。 -W"
STRINGS.UI.PLANTREGISTRY.DESCRIPTIONS.KYNO_PARZNIP = "一种根茎类蔬菜，与胡萝卜关系密切，但更甜。 -W"
STRINGS.UI.PLANTREGISTRY.DESCRIPTIONS.KYNO_TURNIP = "圆圆的，紫色的好吃！-W"
STRINGS.UI.PLANTREGISTRY.DESCRIPTIONS.KYNO_RICE = "是许多健康菜肴中常用的谷物！ -W"

STRINGS_INGREDIENTS_PIKO = "异食松鼠"
STRINGS_INGREDIENTS_SPOTSPICE = "斑点香料"
STRINGS_INGREDIENTS_MAYONNAISE = "蛋黄酱"
STRINGS_INGREDIENTS_ALGAE = "藻类"
STRINGS_INGREDIENTS_CHEESE = "奶酪"
STRINGS_INGREDIENTS_CRAB = "蟹肉"
STRINGS_INGREDIENTS_FOLIAGE = "树叶"
STRINGS_INGREDIENTS_MILK = "牛奶"
STRINGS_INGREDIENTS_MUSSEL = "贻贝"
STRINGS_INGREDIENTS_ROE = "鱼子"
STRINGS_INGREDIENTS_SALMON = "鲑鱼"
STRINGS_INGREDIENTS_BEANBUG = "豆虫"
STRINGS_INGREDIENTS_GUMMYBUG = "糖蛞蝓"
STRINGS_INGREDIENTS_BERRIES = "浆果"
STRINGS_INGREDIENTS_BACON = "培根"
STRINGS_INGREDIENTS_LIMPET = "帽贝"
STRINGS_INGREDIENTS_CHOCOLATE = "巧克力"
STRINGS_INGREDIENTS_BANANA = "香蕉"
STRINGS_INGREDIENTS_BREAD = "面包"
STRINGS_INGREDIENTS_SUGAR = "糖"
STRINGS_INGREDIENTS_BUTTER = "黄油"
STRINGS_INGREDIENTS_FLOUR = "面粉"
STRINGS_INGREDIENTS_SYRUP = "糖浆"
STRINGS_INGREDIENTS_WOBSTER = "龙虾"
STRINGS_INGREDIENTS_OIL = "油类"
STRINGS_INGREDIENTS_JELLYFISH = "水母"
STRINGS_INGREDIENTS_JELLYFISH2 = "彩虹水母"
STRINGS_INGREDIENTS_SWORDFISH = "剑鱼"
STRINGS_INGREDIENTS_SUCCULENT = "多肉植物"
STRINGS_INGREDIENTS_FIREWEED = "Fire Nettle Fronds"
STRINGS_INGREDIENTS_FORGETWEED = "Forget-Me-Lots"
STRINGS_INGREDIENTS_TILLWEED = "Tillweeds"

STRINGS.KYNO_HARVEST_POTSMALL = "拿锅"
STRINGS.KYNO_HARVEST_POTLARGE = "拿大型锅具"
STRINGS.KYNO_HARVEST_POTSYRUP = "拿糖浆罐"
STRINGS.KYNO_HARVEST_SUGARTREE = "收获糖木树"
STRINGS.KYNO_HARVEST_SUGARTREE_RUINED = "收获感染的糖木树"
STRINGS.KYNO_HARVEST_SALTRACK = "收获盐架"
STRINGS.KYNO_HARVEST_FISHFARMPLOT = "收获养鱼场"

STRINGS.KYNO_INSTALL_POT = "放置"
STRINGS.KYNO_INSTALL_SALTRACK = "安装盐架"
STRINGS.KYNO_INSTALL_INSTALLER = "安装"
STRINGS.KYNO_INSTALL_TAPPER = "点击"
STRINGS.KYNO_PICKUP_ROCKFLIPPABLE = "翻石板"
STRINGS.KYNO_DRINK_FOOD = "喝"
STRINGS.KYNO_CONSUME_FOOD = "吸收"
STRINGS.KYNO_REPAIR_TOOL = "修复"
STRINGS.KYNO_OPEN_CAN = "打开"
STRINGS.KYNO_OPEN_BOTTLE_SOUL = "释放灵魂"
STRINGS.KYNO_STORE_SOUL = "储存灵魂"
STRINGS.KYNO_INFEST_TREE = "感染"
STRINGS.KYNO_FEED_CHICKEN = "喂食"
STRINGS.KYNO_BAKE_CAKE = "烘焙周年庆蛋糕"
STRINGS.KYNO_BAKE_CAKE_STOP = "停止烘焙周年庆蛋糕"

STRINGS.ACTIONS.OPEN_CRAFTING.MEALING = "研磨 在"
STRINGS.ACTIONS.ACTIVATE.DESTROY = "摧毁"
STRINGS.ACTIONS.SALT = "加盐"
STRINGS.ACTIONS.STORESOUL = "储存灵魂"
STRINGS.ACTIONS.FLAY = "剥" -- This doesn't matter ACTIONS.SLAUGHTER2 overrides it. But it's necessary for the AddAction.
STRINGS.ACTIONS.SAPHEAL = "治疗"
STRINGS.ACTIONS.PULLMILK = "牛奶"
STRINGS.ACTIONS.BREWER = "酿造"
STRINGS.ACTIONS.READBREWBOOK = "阅读"
STRINGS.ACTIONS.INSTALLCOOKWARE = "安装炊具"
STRINGS.ACTIONS.SLICE = "切分"
STRINGS.ACTIONS.SLICESTACK = "切分堆叠"
STRINGS.ACTIONS.LEARNRECIPECARD = "添加到烹饪指南"
STRINGS.ACTIONS.LEARNRECIPECARD2 = "添加到酿造手册"
STRINGS.ACTIONS.BREEDFISH = "品种"
STRINGS.ACTIONS.MAKEPOPCORN = "制作爆玉米花"
STRINGS.ACTIONS.FISHREGISTRY_RESEARCH = "研究"
STRINGS.ACTIONS.SLAUGHTER2 =
{
	DISEMBOWEL = "轻轻开膛",
	MURDER = "高雅的谋杀",
	BUTCHER = "礼貌的屠夫",
	KILL = "巧妙地杀手",
	EVISCERATE = "轻柔剔骨",
	SLAUGHTER = "小心屠宰",
}

STRINGS.PIGELDER_TALK_FAR =
{
	"..呼~..",
	"(打鼾) ...天..天平...",
	"...zzzZZzzz...",
	"...天..天空...",
	"...侵蚀...",
	"...瘟疫...",
}

STRINGS.PIGELDER_TALK_NEAR1 =
{
	"老人的眼皮感觉很重",
	"你交易？ 补给品?",
	"咦呕! 对猪生气",
	"咦呕? 睡觉……给长辈做噩梦",
	"小山羊，如果你愿意，可以给你我的旧锅！",
	"咦呕! 大多数山羊对猪没有帮助",
	"咦呕!长者想吃龙虾……黄色的东西!",
	"...焦...焦糖..",
}

STRINGS.PIGELDER_TALK_NEAR2 =
{
	"长者的眼皮感觉很重",
	"咦呕? 你交易？ 补给品?",
	"咦呕! 对猪生气",
	"咦呕? 睡觉……给长辈做噩梦",
	"小山羊，如果你愿意，可以给你我的旧锅",
	"咦呕! 大多数山羊对猪没有帮助",
	"谢谢你的礼物，小山羊",
	"长者喜欢小山羊，谢谢你的礼物！",
}

STRINGS.PIGELDER_TALK_BUY =
{
	"谢谢你",
	"来了， 你好山羊",
	"谢谢你。 现在让长老休息",
	"谢谢你，小山羊",
	"咦呕! 感谢!",
	"长者的眼皮感觉很重",
}

STRINGS.PIGELDER_TALK_THANK =
{
	"谢谢你",
	"来了， 你好山羊",
	"谢谢你。 现在让长老休息",
	"谢谢你，小山羊",
	"咦呕! 感谢!",
}

STRINGS.PIGELDER_TALK_REPAIRPOT =
{
	"谢谢你修理我的旧锅，小山羊！",
	"谢谢小山羊！",
	"非常感谢，这对我有很大帮助！",
	"咦呕！小山羊固定长辈的旧锅，谢谢！",
}

STRINGS.FORTUNE_COOKIE_QUOTES =
{
	"上面写着\"你寻找的财富在另一个饼干里。\"",
	"它说\"闭口不聚足。\"",
	"它说：\"愚蠢的人听从自己的内心。聪明人听饼干的话。\"",
	"上面写着\"如果你回头看，你很快就会走上那条路。\"",
	"上面写着\"你会活得足够长，可以打开很多幸运饼干。\"",
	"上面写着\"每个人都应该玩女武神而不是旺达或大力士。\"",
	"它说\"自嘲的人，永远没有笑不出来的东西。\"",
	"上面写着\"论坛是最好笑的地方。\"",
	"它说\"扔泥土的人正在失去阵地。\"",
	"上面写着\"你一小时后又会饿了。\"",
	"上面写着\"你总能在周五的工作中找到快乐。\"",
	"上面写着\"未找到财富？中止、重试、忽略。\"",
	"它说\"救命！我被囚禁在一个幸运饼干工厂里。\"",
	"上面写着\"我该离开那个饼干了。\"",
	"它说\"永远不要忘记一个朋友。特别是如果他欠你的。\"",
	"上面写着\"我很值钱。\"",
	"上面写着\"你会收到一个幸运饼干。\"",
	"上面写着\"有些幸运饼干不含幸运成分。\"",
	"它说\"避免不必要的赌博。幸运数字：12、15、23、28、37。\"",
	"上面写着\"这个饼干含有117卡路里。\"",
	"它说\"问你妈妈而不是饼干。\"",
	"它说\"努力工作在未来会有回报。懒惰现在得到回报。\"",
	"上面写着\"不要吃纸。\"",
	"上面写着\"如果乌龟没有壳，它是赤身裸体还是无家可归？\"",
	"上面写着\"Alt+F4 避免死亡。\"",
	"上面写着\"󰀅󰀆󰀅\"",
	"上面写着\"12个活木不见了，你能找到它们吗？\"",
	"上面写着\"我知道你知道什么，你不能对我隐瞒。\"",
	"上面写着\"这个饼干有另一个秘密。\"",
}

STRINGS.FORTUNE_COOKIE_GOOD =
{
	"上面写着\"你今天太幸运了，太好了！\"",
	"上面写着\"今天是你的幸运日！\"",
	"上面写着\"你今天应该试试彩票。 幸运数字：1、2、3、4、5。\"",
}

STRINGS.FORTUNE_COOKIE_BAD =
{
	"它说\"即将到来的厄运逼近...\"",
	"它说\"你是个坏孩子。\"",
	"它说\"末日降临。\"",
}

STRINGS.NAMES.KYNO_WRECK_OF = " %s 的残骸"
STRINGS.KYNO_WRECK_NAMES =
{
	"鹦鹉螺",
	"麦凯-贝内特",
	"玛丽·塞莱斯特",
	"比格犬",
	"监视器",
	"圣玛丽亚",
	"黑爵士",
	"伊斯帕尼奥拉",
	"鹈",
	"金后",
	"弗兰希尔顿",
	"帕米尔",
	"列奥尼达",
	"若德",
	"弗朗西顿",
	"帕米",
	"德米特里",
	"斯特拉卢兹",
	"佩普",
}

STRINGS.KYNO_SUGARFLY_NAMES =
{
	"糖蝴蝶",
	"糖蛾",
	"甜蝴蝶",
	"甜蛾",
	"糖蝴蝶",
	"糖蛾",
	"甜蝴蝶",
	"甜蛾",
}

STRINGS.KYNO_SUGARFLYWINGS_NAMES =
{
	"糖蝴蝶翅膀",
	"糖蛾翅膀",
	"甜蝴蝶翅膀",
	"甜蛾翅膀",
	"糖蝴蝶翅膀",
	"糖蛾翅膀",
	"甜蝴蝶翅膀",
	"甜蛾翅膀",
}

STRINGS.KYNO_CHICKEN_NAMES =
{
	"小棒槌",
	"小泰西",
	"小夜洋",
	"小面条",
	"小土豆",
	"小卡瑞",
	"小点心",
	"小瑞达",
	"小玛塔",
	"小麦纳",
	"小萝卜",
	"小阿哈",
	"小普哈",
	"小盖哈",
	"小皮蓬",
	"小如威",
	"小罐吉",
	"小马拉",
	"小依达",
	"小佩达",
	"小伊莎",
	"小如哈",
	"小卡仁",
	"小潘萨",
	"小毕达",
	"小莓饼",
	"小索巴",
	"小卢瓦",
	"小奥特",
	"小美纳",
	"小熙宛",
	"小赛纳",
	"小瑞加",
	"小马瑞",
	"小腼腆",
	"小吉索",
}

STRINGS.KYNO_WHALE_WHITE_OCEAN_NAMES =
{
	-- Feel free to add more names.
	"鲸鱼",
	"多比·米克",
	"恶魔",
	"复仇之鲸",
	"白鲸",
	"可怕的鲸鱼",
}

STRINGS.KYNO_GOLDENAPPLE_NAMES =
{
	-- Feel free to add more names.
	"附魔金苹果",
	"永恒智慧之果",
	"禁果",
	"诅咒之果",
	"Kyno的苹果",
	"Leonidas苹果",
}

STRINGS.MEADOWISLANDTRADER = "萨米\n一位 %s"
STRINGS.MEADOWISLANDTRADER_TITLES = 
{
	"商人", 
	"友善的鱼人", 
	"经验丰富的商人", 
	"奇异的商人",
	"沼泽交易商",
}

STRINGS.MEADOWISLANDTRADER_OUTOFSTOCK =
{
	"我现在没什么东西可以拿来交换！",
	"还没呢，朋友，你过会儿再来吧。",
	"朋友，我需要点时间来补货。",
}

STRINGS.MEADOWISLANDTRADER_OUTOFSTOCKTRADES = 
{
	"你把我掏空了！得花点时间再进货。",
	"我就这些了！下次再来吧",
	"朋友，你刚清空了我那些好货。我现在需要休息一下。",
	"稍后回来继续进行更多交换。",
}
    
STRINGS.MEADOWISLANDTRADER_STARTTRADING = 
{
	"你怎么还没交换东西呢？",
	"嘿，朋友，你需要什么？",
	"我不管你买什么，总之要买点什么！",
	"嘿，想来点什么吗？",
	"选点东西吧！不要浪费时间！",
	"想要点什么？",
	"我现在就想吃点东西，知道吗？",
	"我有点想念我的家乡和那里的人们...",
}

STRINGS.MEADOWISLANDTRADER_ENDTRADING_NOTRADES = 
{
	"我在做什么？ ...哦，这里有种子！",
	"也许下次吧。",
	"你什么都不感兴趣吗？待会儿来看看我采购回来了什么。",
	"那就别浪费我的时间，听到了吗？",
	"哎，不可能让每个人都满意！",
	"就待在那儿别动！",
	"那你应该试试我的朋友皮普顿那里！",
}

STRINGS.MEADOWISLANDTRADER_ENDTRADING_MADETRADE = 
{
	"现在回来，听到了吗？",
	"谢谢，陌生人。",
	"很高兴！",
	"哪位？",
	"你们总是匆匆忙忙。",
	"好吧，好吧，行动起来。",
	"快回来！我有点孤独！嘿，有点孤独。",
}

STRINGS.MEADOWISLANDTRADER_DOTRADE = 
{
	"啊，不错的选择！还有什么能让你感兴趣的吗？",
	"马上来！你还需要什么？",
	"不错，不错！让我们继续吧！",
	"你想要的东西很有品味。",
	"哇，有人真的为此花钱了？",
	"哈，我是从我朋友的仓库里弄来的。",
	"希望这能帮到你。",
	"加油，加油，继续！",
	"宝贝，现金是小丑才用的！",
}

STRINGS.MEADOWISLANDTRADER_DOTRADEHAT =
{
	"你想要我的帽子？好吧，你可以拿走。",
	"我的旧帽子？嗯，拿去吧。",
	"拿着我的帽子，别担心，我有很多。",
	"我家里总是还有存货的。",
	"你可以拿走我的帽子。如果你想要更多，请稍后再来！",
	"谢谢。它让我想起了家，你可以用这个代替。",
}

STRINGS.MEADOWISLANDTRADER_REFUSE =
{
	"不想要那个！",
	"不，我很好。",
	"给我拿点别的，不是这个！",
	"那可不行，伙计！",
	"不感兴趣，那就走吧。",
}

STRINGS.MEADOWISLANDTRADER_GOHOME =
{
	"是时候回家休息了。",
	"接下来，我需要休息一会儿。",
	"下班啦！",
	"再见！",
	"我不加班！",
	"你知道在哪里能找到我。",
}

STRINGS.MEADOWISLANDTRADER_STARTDANCING = 
{
	"耶！开派对啦！",
	"呼呼！来跳舞吧，朋友！",
	"陌生人，你可真会让我心情变好！",
	"跳吧，跳吧，宝贝！",
	"派对时间到啦！",
}

STRINGS.FISHREGISTRY =
{
	TAB_FISH = "鱼类",
	TAB_ROE = "鱼卵",
	
	MYSTERY_FISH = "未知的鱼",
	MISSING_FISH = "缺失的鱼",
	
	MYSTERY_ROE = "未知的鱼卵",
	MISSING_ROE = "缺失的鱼卵",
	
	MYSTERY_BABY = "未知的后代",
	MISSING_BABY = "缺失的后代",
	
	MISSING_ROE_TIME = "未知鱼卵时间",
	MISSING_BABY_TIME = "未知后代时间",
	
	PHASE_DAY = "白天",
	PHASE_DUSK = "黄昏",
	PHASE_NIGHT = "夜晚",
	
	MOONPHASE_NEW = "新月",
	MOONPHASE_QUARTER = "上弦月",
	MOONPHASE_HALF = "半月",
	MOONPHASE_THREEQUARTER = "下弦月",
	MOONPHASE_FULL = "满月",
	MOONPHASE_GLASSED = "月暴",
	
	SEASON_AUTUMN = "秋季",
	SEASON_WINTER = "冬季",
	SEASON_SPRING = "春季",
	SEASON_SUMMER = "夏季",
	
	WORLD_FOREST = "森林",
	WORLD_CAVE = "洞穴",
	
	ROE_TIME = "鱼卵时间",
	BABY_TIME = "后代时间",
	
	ROE_TIME_HALF_DAY = "大约半天",
	ROE_TIME_ONE_DAY = "大约一天",
	ROE_TIME_ONE_HALF_DAY = "多于一天",
	ROE_TIME_TWO_DAY = "大约两天",
	ROE_TIME_THREE_DAY = "大约三天",
	ROE_TIME_MORE_DAY = "多于三天",
	
	BABY_TIME_HALF_DAY = "大约半天",
	BABY_TIME_ONE_DAY = "大约一天",
	BABY_TIME_ONE_HALF_DAY = "多于一天",
	BABY_TIME_TWO_DAY = "大约两天",
	BABY_TIME_THREE_DAY = "大约三天",
	BABY_TIME_FOUR_DAY = "大约四天",
	BABY_TIME_FIVE_DAY = "大约五天",
	BABY_TIME_SIX_DAY = "大约六天",
	BABY_TIME_MORE_DAY = "多于六天",
}

STRINGS.FISHERMERM_TALK_RUNAWAY = "快跑 快跑 快跑!"
STRINGS.FISHERMERM_TALK_PANIC = "可怕 可怕 可怕!"
STRINGS.FISHERMERM_TALK_GO_HOME = "回家 回家 回家。"
STRINGS.FISHERMERM_TALK_FISH = "需要耐心。"

-- Edited strings for skill trees.
STRINGS.SKILLTREE_WORMWOOD_MUSHROOMPLANTER_RATEBONUS_2_DESC = "在蘑菇农场中种植的蘑菇生长速度更快。\n学习如何在蘑菇农场中种植新种类的蘑菇。"

STRINGS.NAMES.KYNO_ROE = "鱼卵" -- Deprecated but kept for old worlds.
STRINGS.NAMES.KYNO_ROE_PONDFISH = "淡水鱼卵"
STRINGS.NAMES.KYNO_ROE_PONDEEL = "鳗鱼卵"
STRINGS.NAMES.KYNO_ROE_WOBSTER = "龙虾卵"
STRINGS.NAMES.KYNO_ROE_WOBSTER_MOONGLASS = "月光龙虾卵"
STRINGS.NAMES.KYNO_ROE_WOBSTER_MONKEYISLAND = "寄居龙虾卵"
STRINGS.NAMES.KYNO_ROE_NEONFISH = "霓虹鱼卵"
STRINGS.NAMES.KYNO_ROE_PIERROTFISH = "小丑鱼卵"
STRINGS.NAMES.KYNO_ROE_GROUPER = "紫石斑鱼卵"
STRINGS.NAMES.KYNO_ROE_TROPICALFISH = "热带鱼卵"
STRINGS.NAMES.KYNO_ROE_JELLYFISH = "水母卵"
STRINGS.NAMES.KYNO_ROE_JELLYFISH_RAINBOW = "彩虹水母卵"
STRINGS.NAMES.KYNO_ROE_SALMONFISH = "鲑鱼卵"
STRINGS.NAMES.KYNO_ROE_KOI = "热带锦鲤卵"
STRINGS.NAMES.KYNO_ROE_ANTCHOVY = "蚁头凤尾鱼卵"
STRINGS.NAMES.KYNO_ROE_SWORDFISH_BLUE = "冷冻剑鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_SMALL_1 = "小孔雀鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_SMALL_2 = "针鼻喷墨鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_SMALL_3 = "小饵鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_SMALL_4 = "三文鱼苗卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_SMALL_5 = "爆米花鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_SMALL_6 = "落叶比目鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_SMALL_7 = "花朵金枪鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_SMALL_8 = "炽热太阳鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_SMALL_9 = "口水鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_MEDIUM_1 = "泥鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_MEDIUM_2 = "斑鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_MEDIUM_3 = "浮夸狮子鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_MEDIUM_4 = "黑鲶鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_MEDIUM_5 = "玉米鳕鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_MEDIUM_6 = "花锦鲤卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_MEDIUM_7 = "金锦鲤卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_MEDIUM_8 = "冰鲷鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_MEDIUM_9 = "甜味鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_PUFFERFISH = "河豚鱼卵"
STRINGS.NAMES.KYNO_ROE_OCEANFISH_STURGEON = "鲟鱼卵"

STRINGS.RECIPE_DESC.KYNO_ROE_M = "准备烹饪的鱼卵。"

STRINGS.NAMES.KYNO_ROE_COOKED = "熟鱼子"

STRINGS.NAMES.KYNO_SHARK_FIN = "鱼翅"
STRINGS.RECIPE_DESC.KYNO_SHARK_FIN_M = "一条可恶的鲨鱼的鳍被扯了下来。"

STRINGS.NAMES.KYNO_BEANBUGS = "豆虫"
STRINGS.NAMES.KYNO_BEANBUGS_COOKED = "烤豆虫"

STRINGS.NAMES.KYNO_GUMMYBUG = "糖蛞蝓"
STRINGS.NAMES.KYNO_GUMMYBUG_COOKED = "烤糖蛞蝓"

STRINGS.NAMES.KYNO_WHEAT = "小麦"
STRINGS.NAMES.KYNO_WHEAT_COOKED = "熟小麦"

STRINGS.NAMES.KYNO_FLOUR = "面粉"
STRINGS.NAMES.KYNO_FLOUR_P = "面粉"
STRINGS.RECIPE_DESC.KYNO_FLOUR = "小麦粉还是草？"

STRINGS.NAMES.KYNO_SPOTSPICE = "斑点香料"
STRINGS.RECIPE_DESC.KYNO_SPOTSPICE = "一茶匙美味香料。"

STRINGS.NAMES.KYNO_SAP = "树液"
STRINGS.NAMES.KYNO_SAP_SPOILED = "变质的树液"

STRINGS.NAMES.KYNO_SYRUP = "糖浆"
STRINGS.RECIPE_DESC.KYNO_SYRUP = "树液混合到最大甜度。"

STRINGS.NAMES.KYNO_COFFEEBEANS = "咖啡豆"
STRINGS.NAMES.KYNO_COFFEEBEANS_COOKED = "烘培咖啡豆"

STRINGS.NAMES.DUG_KYNO_COFFEEBUSH = "咖啡丛"
STRINGS.RECIPE_DESC.DUG_KYNO_COFFEEBUSH_M = "一种珍稀而奇特的植物，深受许多人珍爱。"

STRINGS.NAMES.KYNO_COFFEEBUSH = "咖啡丛"
STRINGS.NAMES.DUG_KYNO_SPOTBUSH = "斑点灌木"
STRINGS.NAMES.DUG_KYNO_SPOTBUSH_P = "斑点灌木"
STRINGS.RECIPE_DESC.DUG_KYNO_SPOTBUSH_P = "把它们种在我家以外的任何地方！"

STRINGS.NAMES.KYNO_SPOTBUSH = "斑点灌木"
STRINGS.NAMES.KYNO_SPOTSPICE_LEAF = "斑点树枝"

STRINGS.NAMES.KYNO_MUSSEL = "贻贝"
STRINGS.NAMES.KYNO_MUSSEL_COOKED = "烤贻贝"

STRINGS.NAMES.KYNO_HUMANMEAT = "人肉"
STRINGS.NAMES.KYNO_HUMANMEAT_COOKED = "烤人肉"
STRINGS.NAMES.KYNO_HUMANMEAT_DRIED = "人肉干"

STRINGS.NAMES.COFFEE = "咖啡"

STRINGS.NAMES.BISQUE = "鲜贝浓汤"

STRINGS.NAMES.JELLYOPOP = "水母冻"

STRINGS.NAMES.SHARKFINSOUP = "鱼翅汤"

STRINGS.NAMES.TROPICALBOUILLABAISSE = "热带鱼汤"

STRINGS.NAMES.MUSSELBOUILLABAISE = "法式贻贝浓汤"

STRINGS.NAMES.SWEETPOTATOSOUFFLE = "甘薯蛋奶酥"

STRINGS.NAMES.FEIJOADA = "八宝饭"

STRINGS.NAMES.GUMMY_CAKE = "软糖蛋糕"

STRINGS.NAMES.HARDSHELL_TACOS = "硬壳玉米卷饼"

STRINGS.NAMES.ICEDTEA = "冰茶"

STRINGS.NAMES.NETTLELOSANGE = "火荨麻卷"

STRINGS.NAMES.SNAKEBONESOUP = "虫骨汤"

STRINGS.NAMES.STEAMEDHAMSANDWICH = "蒸火腿三明治"

STRINGS.NAMES.TEA = "茶"

STRINGS.NAMES.BUBBLETEA = "珍珠奶茶"

STRINGS.NAMES.FRENCHONIONSOUP = "法式洋葱汤"

STRINGS.NAMES.SLAW = "蔬菜沙拉"

STRINGS.NAMES.LOTUSBOWL = "莲花薯片"

STRINGS.NAMES.POI = "夏威夷芋头泥"

STRINGS.NAMES.JELLYBEAN_HUNGER = "奶油软糖"
STRINGS.NAMES.JELLYBEAN_SUPER = "超级软糖"
STRINGS.NAMES.JELLYBEAN_SANITY = "薄荷软糖"

STRINGS.NAMES.BOWLOFGEARS = "齿轮交响曲"

STRINGS.NAMES.LONGPIGMEAL = "致命盛宴"

STRINGS.NAMES.CUCUMBERSALAD = "黄瓜沙拉"

STRINGS.NAMES.KYNO_BACON = "培根"
STRINGS.NAMES.KYNO_BACON_P = "培根"
STRINGS.RECIPE_DESC.KYNO_BACON = "垃圾食品的经典成分。"

STRINGS.NAMES.KYNO_BACON_COOKED = "烤培根"

STRINGS.NAMES.KYNO_WHITE_CAP = "香菇"
STRINGS.NAMES.KYNO_WHITE_CAP_COOKED = "烤熟的香菇"

STRINGS.NAMES.KYNO_MUSHSTUMP = "蘑菇桩"
STRINGS.NAMES.KYNO_MUSHSTUMP_NATURAL = "蘑菇桩"
STRINGS.NAMES.KYNO_MUSHSTUMP_CAVE = "蘑菇桩"
STRINGS.RECIPE_DESC.KYNO_MUSHSTUMP = "一大堆蘑菇。"

STRINGS.NAMES.KYNO_FOLIAGE = "树叶"
STRINGS.NAMES.KYNO_FOLIAGE_COOKED = "烤熟的树叶"

STRINGS.NAMES.KYNO_WILDWHEAT = "小麦"
STRINGS.NAMES.KYNO_WILDWHEAT_P = "小麦簇"

STRINGS.NAMES.DUG_KYNO_WILDWHEAT = "小麦簇"
STRINGS.RECIPE_DESC.DUG_KYNO_WILDWHEAT_P = "啊哈！小麦是制作食物的好材料！"

STRINGS.NAMES.KYNO_MEALGRINDER = "碾磨石"
STRINGS.RECIPE_DESC.KYNO_MEALGRINDER = "研磨烹饪配料。"

STRINGS.NAMES.GORGE_BREAD = "吐司"
STRINGS.NAMES.GORGE_SWEET_CHIPS = "红薯片"
STRINGS.NAMES.GORGE_VEGETABLE_SOUP = "蔬菜汤"
STRINGS.NAMES.GORGE_JELLY_SANDWICH = "果酱三明治"
STRINGS.NAMES.GORGE_FISH_STEW = "鱼汤"
STRINGS.NAMES.GORGE_MEAT_STEW = "特制炖肉汤"
STRINGS.NAMES.GORGE_ONION_CAKE = "芜菁糕"
STRINGS.NAMES.GORGE_POTATO_PANCAKES = "土豆煎饼"
STRINGS.NAMES.GORGE_POTATO_SOUP = "土豆汤"
STRINGS.NAMES.GORGE_FISHBALL_SKEWERS = "鱼丸串"
STRINGS.NAMES.GORGE_MEAT_SKEWERS = "培根串"
STRINGS.NAMES.GORGE_STONE_SOUP = "石头汤"
STRINGS.NAMES.GORGE_CROQUETTE = "炸丸子"
STRINGS.NAMES.GORGE_ROAST_VEGETABLES = "烤蔬菜"
STRINGS.NAMES.GORGE_MEATLOAF = "肉饼"
STRINGS.NAMES.GORGE_CARROT_SOUP = "胡萝卜汤"
STRINGS.NAMES.GORGE_FISHPIE = "鱼派"
STRINGS.NAMES.GORGE_FISHCHIPS = "炸鱼薯条"
STRINGS.NAMES.GORGE_MEATPIE = "肉派"
STRINGS.NAMES.GORGE_SLIDERS = "迷你汉堡"
STRINGS.NAMES.GORGE_JELLY_ROLL = "果冻卷"
STRINGS.NAMES.GORGE_CARROT_CAKE = "胡萝卜蛋糕"
STRINGS.NAMES.GORGE_GARLICMASHED = "土豆泥"
STRINGS.NAMES.GORGE_GARLICBREAD = "蒜香面包"
STRINGS.NAMES.GORGE_TOMATO_SOUP = "番茄汤"
STRINGS.NAMES.GORGE_SAUSAGE = "香肠"
STRINGS.NAMES.GORGE_CANDIEDFISH = "糖渍鱼"
STRINGS.NAMES.GORGE_STUFFEDMUSHROOM = "蘑菇包菜"
STRINGS.NAMES.GORGE_BRUSCHETTA = "意式烤面包"
STRINGS.NAMES.GORGE_HAMBURGER = "汉堡包"
STRINGS.NAMES.GORGE_FISHBURGER = "鱼肉汉堡"
STRINGS.NAMES.GORGE_MUSHROOMBURGER = "蘑菇汉堡"
STRINGS.NAMES.GORGE_FISH_STEAK = "鱼排"
STRINGS.NAMES.GORGE_CURRY = "咖喱"
STRINGS.NAMES.GORGE_SPAGHETTI = "意式肉丸面"
STRINGS.NAMES.GORGE_POACHEDFISH = "水煮鱼"
STRINGS.NAMES.GORGE_SHEPHERD_PIE = "肉馅薯派"
STRINGS.NAMES.GORGE_CANDY = "糖果"
STRINGS.NAMES.GORGE_BREAD_PUDDING = "布丁"
STRINGS.NAMES.GORGE_BERRY_TART = "莓果挞"
STRINGS.NAMES.GORGE_MACARONI = "通心粉"
STRINGS.NAMES.GORGE_BAGEL_AND_FISH = "鱼肉面包圈"
STRINGS.NAMES.GORGE_GRILLED_CHEESE = "烤奶酪"
STRINGS.NAMES.GORGE_CREAMMUSHROOM = "奶油蘑菇汤"
STRINGS.NAMES.GORGE_MANICOTTI = "意式通心粉"
STRINGS.NAMES.GORGE_CHEESEBURGER = "芝士汉堡"
STRINGS.NAMES.GORGE_FETTUCCINE = "意式宽面条"
STRINGS.NAMES.GORGE_ONION_SOUP = "洋葱汤"
STRINGS.NAMES.GORGE_BREADED_CUTLET = "炸肉排"
STRINGS.NAMES.GORGE_CREAMY_FISH = "奶油鱼"
STRINGS.NAMES.GORGE_PIZZA = "披萨"
STRINGS.NAMES.GORGE_POT_ROAST = "罐炖烤肉"
STRINGS.NAMES.GORGE_CRAB_CAKE = "蟹饼"
STRINGS.NAMES.GORGE_STEAK_FRITES = "肉排薯条"
STRINGS.NAMES.GORGE_SHOOTER_SANDWICH = "射手三明治"
STRINGS.NAMES.GORGE_BACON_WRAPPED = "培根卷肉"
STRINGS.NAMES.GORGE_CRAB_ROLL = "蟹肉卷"
STRINGS.NAMES.GORGE_MEAT_WELLINGTON = "威灵顿肉排"
STRINGS.NAMES.GORGE_CRAB_RAVIOLI = "蟹肉馄饨"
STRINGS.NAMES.GORGE_CARAMEL_CUBE = "焦糖方糕"
STRINGS.NAMES.GORGE_SCONE = "司康饼"
STRINGS.NAMES.GORGE_TRIFLE = "乳脂松糕"
STRINGS.NAMES.GORGE_CHEESECAKE = "奶酪蛋糕"
STRINGS.NAMES.GORGE_WAFFLES = "幸福华夫饼"

STRINGS.NAMES.DUCKYOUGLERMZ = "便便饭"

STRINGS.NAMES.KYNO_ASPARGOS_GROUND = "芦笋"

STRINGS.NAMES.KYNO_ALOE = "芦荟"
STRINGS.NAMES.KYNO_ALOE_COOKED = "烤熟的芦荟"
STRINGS.NAMES.KYNO_ALOE_GROUND = "芦荟"
STRINGS.NAMES.KYNO_ALOE_SEEDS = "芦荟种子"
STRINGS.NAMES.KYNO_ALOE_SEEDS_P = "芦荟种子包"
STRINGS.NAMES.KNOWN_KYNO_ALOE_SEEDS = "芦荟种子"
STRINGS.NAMES.FARM_PLANT_KYNO_ALOE = "芦荟植物"
STRINGS.NAMES.KYNO_ALOE_OVERSIZED = "巨型芦荟"
STRINGS.NAMES.KYNO_ALOE_OVERSIZED_WAXED = "打蜡的巨型芦荟"
STRINGS.NAMES.KYNO_ALOE_OVERSIZED_ROTTEN = "腐烂的巨型芦荟"

STRINGS.NAMES.KYNO_CUCUMBER = "海黄瓜"
STRINGS.NAMES.KYNO_CUCUMBER_COOKED = "烤海黄瓜"
STRINGS.NAMES.KYNO_CUCUMBER_GROUND = "海黄瓜"
STRINGS.NAMES.KYNO_CUCUMBER_SEEDS = "海黄瓜种子"
STRINGS.NAMES.KYNO_CUCUMBER_SEEDS_P = "海黄瓜种子包"
STRINGS.NAMES.KNOWN_KYNO_CUCUMBER_SEEDS = "海黄瓜种子"
STRINGS.NAMES.FARM_PLANT_KYNO_CUCUMBER = "海黄瓜茎"
STRINGS.NAMES.KYNO_CUCUMBER_OVERSIZED = "巨型海黄瓜茎"
STRINGS.NAMES.KYNO_CUCUMBER_OVERSIZED_WAXED = "打蜡的巨型海黄瓜茎"
STRINGS.NAMES.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "腐烂的巨型海黄瓜茎"

STRINGS.NAMES.KYNO_RADISH = "红萝卜"
STRINGS.NAMES.KYNO_RADISH_COOKED = "烤红萝卜"
STRINGS.NAMES.KYNO_RADISH_GROUND = "红萝卜"
STRINGS.NAMES.KYNO_RADISH_SEEDS = "红萝卜种子"
STRINGS.NAMES.KYNO_RADISH_SEEDS_P = "萝卜种子包"
STRINGS.NAMES.KNOWN_KYNO_RADISH_SEEDS = "红萝卜种子"
STRINGS.NAMES.FARM_PLANT_KYNO_RADISH = "红胡萝卜植物"
STRINGS.NAMES.KYNO_RADISH_OVERSIZED = "巨型红萝卜"
STRINGS.NAMES.KYNO_RADISH_OVERSIZED_WAXED = "打蜡的巨型红萝卜"
STRINGS.NAMES.KYNO_RADISH_OVERSIZED_ROTTEN = "腐烂的巨型红萝卜"

STRINGS.NAMES.KYNO_FENNEL = "茴香"
STRINGS.NAMES.KYNO_FENNEL_COOKED = "烤茴香"
STRINGS.NAMES.KYNO_FENNEL_GROUND = "茴香"
STRINGS.NAMES.KYNO_FENNEL_SEEDS = "茴香种子"
STRINGS.NAMES.KYNO_FENNEL_SEEDS_P = "茴香种子包"
STRINGS.NAMES.KNOWN_KYNO_FENNEL_SEEDS = "茴香种子"
STRINGS.NAMES.FARM_PLANT_KYNO_FENNEL = "茴香蕨"
STRINGS.NAMES.KYNO_FENNEL_OVERSIZED = "巨型茴香蕨"
STRINGS.NAMES.KYNO_FENNEL_OVERSIZED_WAXED = "打蜡的巨型茴香蕨"
STRINGS.NAMES.KYNO_FENNEL_OVERSIZED_ROTTEN = "腐烂的巨型茴香蕨"

STRINGS.NAMES.KYNO_SWEETPOTATO = "红薯"
STRINGS.NAMES.KYNO_SWEETPOTATO_COOKED = "烤红薯"
STRINGS.NAMES.KYNO_SWEETPOTATO_GROUND = "红薯"
STRINGS.NAMES.KYNO_SWEETPOTATO_SEEDS = "红薯种子"
STRINGS.NAMES.KYNO_SWEETPOTATO_SEEDS_P = "红薯种子包"
STRINGS.NAMES.KNOWN_KYNO_SWEETPOTATO_SEEDS = "红薯种子"
STRINGS.NAMES.FARM_PLANT_KYNO_SWEETPOTATO = "红薯植物"
STRINGS.NAMES.KYNO_SWEETPOTATO_OVERSIZED = "巨型红薯"
STRINGS.NAMES.KYNO_SWEETPOTATO_OVERSIZED_WAXED = "打蜡的巨型红薯"
STRINGS.NAMES.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "腐烂的巨型红薯"

STRINGS.NAMES.KYNO_PARZNIP = "防风草"
STRINGS.NAMES.KYNO_PARZNIP_COOKED = "烤防风草"
STRINGS.NAMES.KYNO_PARZNIP_EATEN = "吃过的防风草"
STRINGS.NAMES.KYNO_PARZNIP_GROUND = "防风草"
STRINGS.NAMES.KYNO_PARZNIP_BIG = "巨型防风草"
STRINGS.NAMES.KYNO_PARZNIP_SEEDS = "防风草种子"
STRINGS.NAMES.KYNO_PARZNIP_SEEDS_P = "防风草种子包"
STRINGS.NAMES.KNOWN_KYNO_PARZNIP_SEEDS = "防风草种子"
STRINGS.NAMES.FARM_PLANT_KYNO_PARZNIP = "防风草"
STRINGS.NAMES.KYNO_PARZNIP_OVERSIZED = "巨型防风草"
STRINGS.NAMES.KYNO_PARZNIP_OVERSIZED_WAXED = "打蜡的巨型防风草"
STRINGS.NAMES.KYNO_PARZNIP_OVERSIZED_ROTTEN = "腐烂的巨型防风草"

STRINGS.NAMES.KYNO_TURNIP = "芜菁"
STRINGS.NAMES.KYNO_TURNIP_COOKED = "烤芜菁"
STRINGS.NAMES.KYNO_TURNIP_GROUND = "芜菁"
STRINGS.NAMES.KYNO_TURNIP_SEEDS = "芜菁种子"
STRINGS.NAMES.KYNO_TURNIP_SEEDS_P = "芜菁种子包"
STRINGS.NAMES.KNOWN_KYNO_TURNIP_SEEDS = "芜菁种子"
STRINGS.NAMES.FARM_PLANT_KYNO_TURNIP = "芜菁蕨"
STRINGS.NAMES.KYNO_TURNIP_OVERSIZED = "巨型芜菁蕨"
STRINGS.NAMES.KYNO_TURNIP_OVERSIZED_WAXED = "打蜡的巨型萝卜蕨"
STRINGS.NAMES.KYNO_TURNIP_OVERSIZED_ROTTEN = "腐烂的巨型芜菁蕨"

STRINGS.NAMES.KYNO_RICE = "稻米"
STRINGS.NAMES.KYNO_RICE_COOKED = "烤稻米"
STRINGS.NAMES.KYNO_RICE_SEEDS = "稻米种子"
STRINGS.NAMES.KYNO_RICE_SEEDS_P = "稻米种子包"
STRINGS.NAMES.KNOWN_KYNO_RICE_SEEDS = "稻米种子"
STRINGS.NAMES.FARM_PLANT_KYNO_RICE = "稻米植物"
STRINGS.NAMES.KYNO_RICE_OVERSIZED = "巨型稻米"
STRINGS.NAMES.KYNO_RICE_OVERSIZED_WAXED = "打蜡的巨型稻米"
STRINGS.NAMES.KYNO_RICE_OVERSIZED_ROTTEN = "腐烂的巨型稻米"

STRINGS.NAMES.KYNO_SEEDS_KIT = "种子包"

STRINGS.NAMES.KYNO_SEEDS_KIT_ALOE = "芦荟种子包"
STRINGS.RECIPE_DESC.KYNO_SEEDS_KIT_ALOE_P = "大量的芦荟种子！"

STRINGS.NAMES.KYNO_SEEDS_KIT_CUCUMBER = "海黄瓜种子包"
STRINGS.RECIPE_DESC.KYNO_SEEDS_KIT_CUCUMBER_P = "大量的海黄瓜种子！"

STRINGS.NAMES.KYNO_SEEDS_KIT_FENNEL = "茴香种子包"
STRINGS.RECIPE_DESC.KYNO_SEEDS_KIT_FENNEL_P = "大量的茴香种子！"

STRINGS.NAMES.KYNO_SEEDS_KIT_PARZNIP = "防风草种子包"
STRINGS.RECIPE_DESC.KYNO_SEEDS_KIT_PARZNIP_P = "大量的防风草种子！"

STRINGS.NAMES.KYNO_SEEDS_KIT_RADISH = "红萝卜种子包"
STRINGS.RECIPE_DESC.KYNO_SEEDS_KIT_RADISH_P = "大量的红萝卜种子！"

STRINGS.NAMES.KYNO_SEEDS_KIT_SWEETPOTATO = "红薯种子包"
STRINGS.RECIPE_DESC.KYNO_SEEDS_KIT_SWEETPOTATO_P = "大量的红薯种子！"

STRINGS.NAMES.KYNO_SEEDS_KIT_TURNIP = "芜菁种子包"
STRINGS.RECIPE_DESC.KYNO_SEEDS_KIT_TURNIP_P = "大量的芜菁种子！"

STRINGS.NAMES.KYNO_SEEDS_KIT_RICE = "稻米种子包"
STRINGS.RECIPE_DESC.KYNO_SEEDS_KIT_RICE_M = "一捆包装得很好的稻种子。"

STRINGS.NAMES.KYNO_SEEDS_KIT_FIRENETTLES = "火荨麻种子包"
STRINGS.RECIPE_DESC.KYNO_SEEDS_KIT_FIRENETTLES_M = "凶猛而炽热的种子。"

STRINGS.NAMES.KYNO_SEEDS_KIT_FORGETMELOTS = "必忘我种子包"
STRINGS.RECIPE_DESC.KYNO_SEEDS_KIT_FORGETMELOTS_M = "别忘了在你可以的时候种植它们！"

STRINGS.NAMES.KYNO_SEEDS_KIT_TILLWEED = "犁地草种子包"
STRINGS.RECIPE_DESC.KYNO_SEEDS_KIT_TILLWEED_M = "准备好种植的幼芽。"

STRINGS.NAMES.KYNO_LIMPETROCK = "帽贝岩"
STRINGS.NAMES.KYNO_LIMPETS = "帽贝"
STRINGS.NAMES.KYNO_LIMPETS_COOKED = "烤帽贝"

STRINGS.NAMES.KYNO_LOTUS_OCEAN = "莲花植物"
STRINGS.NAMES.KYNO_LOTUS_ROOT = "莲藕茎"
STRINGS.NAMES.KYNO_LOTUS_FLOWER = "莲花"
STRINGS.NAMES.KYNO_LOTUS_FLOWER_COOKED = "烤莲藕"

STRINGS.NAMES.KYNO_SEAWEEDS_OCEAN = "海藻植物"
STRINGS.NAMES.KYNO_SEAWEEDS = "海藻"
STRINGS.NAMES.KYNO_SEAWEEDS_COOKED = "烤海藻"
STRINGS.NAMES.KYNO_SEAWEEDS_DRIED = "干海藻"
STRINGS.NAMES.KYNO_SEAWEEDS_ROOT = "海藻茎"

STRINGS.NAMES.KYNO_TAROROOT_OCEAN = "芋头植物"
STRINGS.NAMES.KYNO_TAROROOT_ROOT = "芋头茎"
STRINGS.NAMES.KYNO_TAROROOT = "芋头"
STRINGS.NAMES.KYNO_TAROROOT_COOKED = "烤芋头"

STRINGS.NAMES.KYNO_WATERYCRESS_OCEAN = "西洋菜植物"
STRINGS.NAMES.KYNO_WATERYCRESS_ROOT = "西洋菜茎"
STRINGS.NAMES.KYNO_WATERYCRESS = "西洋菜"

STRINGS.NAMES.WATERYCRESSBOWL = "西洋菜汤"

STRINGS.NAMES.KYNO_SALT = "盐"
STRINGS.NAMES.KYNO_SALT_P = "盐"
STRINGS.RECIPE_DESC.KYNO_SALT = "一瓶盐。"

STRINGS.NAMES.FESTIVE_BERRYSAUCE = "快乐浆果酱"
STRINGS.NAMES.FESTIVE_BIBINGKA = "比宾卡米糕"
STRINGS.NAMES.FESTIVE_CABBAGEROLLS = "白菜卷"
STRINGS.NAMES.FESTIVE_FISHDISH = "节日鱼料理"
STRINGS.NAMES.FESTIVE_GOODGRAVY = "好肉汁"
STRINGS.NAMES.FESTIVE_LATKES = "土豆饼"
STRINGS.NAMES.FESTIVE_LUTEFISK = "苏打鱼"
STRINGS.NAMES.FESTIVE_MULLEDPUNCH = "香料潘趣酒"
STRINGS.NAMES.FESTIVE_PANETTONE = "托尼甜面包"
STRINGS.NAMES.FESTIVE_PAVLOVA = "巴甫洛娃蛋糕"
STRINGS.NAMES.FESTIVE_PICKLEDHERRING = "腌鲱鱼"
STRINGS.NAMES.FESTIVE_POLISHCOOKIES = "波兰饼干"
STRINGS.NAMES.FESTIVE_PUMPKINPIE = "南瓜派"
STRINGS.NAMES.FESTIVE_ROASTEDTURKEY = "烤火鸡"
STRINGS.NAMES.FESTIVE_STUFFING = "烤火鸡面包馅"
STRINGS.NAMES.FESTIVE_SWEETPOTATO = "红薯焗饭"
STRINGS.NAMES.FESTIVE_TAMALES = "塔马利"
STRINGS.NAMES.FESTIVE_TOURTIERE = "饕餮馅饼"

STRINGS.NAMES.KYNO_MUSSELSTICK = "贻贝棒"
STRINGS.NAMES.KYNO_MUSSELSTICK_ITEM = "贻贝棒"
STRINGS.RECIPE_DESC.KYNO_MUSSELSTICK_ITEM = "贻贝待在上面！"

STRINGS.NAMES.CATFOOD = "小猫零食"

STRINGS.NAMES.KATFOOD = "Kitty零食"

STRINGS.NAMES.KYNO_BANANATREE = "金色香蕉树"
STRINGS.NAMES.KYNO_BANANATREE_SAPLING = "金色香蕉树苗"

-- Renaming it to not be confused with our bananas.
STRINGS.NAMES.CAVE_BANANA = "洞穴香蕉"
STRINGS.NAMES.CAVE_BANANA_COOKED = "熟洞穴香蕉"

STRINGS.NAMES.KYNO_BANANA = "金色香蕉"
STRINGS.NAMES.KYNO_BANANA_COOKED = "熟金色香蕉"

STRINGS.NAMES.KYNO_KOKONUTTREE = "椰子树"
STRINGS.NAMES.KYNO_KOKONUTTREE_SAPLING = "椰子树苗"

STRINGS.NAMES.KYNO_KOKONUT = "椰子"
STRINGS.NAMES.KYNO_KOKONUT_HALVED = "半个椰子"
STRINGS.NAMES.KYNO_KOKONUT_COOKED = "烤椰子"

STRINGS.NAMES.BOWLOFPOPCORN = "马戏团爆玉米花"

STRINGS.NAMES.FIGJUICE = "无花果汁"

STRINGS.NAMES.COCONUTWATER = "椰子水"

STRINGS.NAMES.EYEBALLSPAGHETTI = "眼球意大利面"

STRINGS.NAMES.FORGETMELOTS_SEEDS = "勿忘我种子"

STRINGS.NAMES.FIRENETTLES_SEEDS = "火荨麻种子"

STRINGS.NAMES.TILLWEED_SEEDS = "犁地草种子"

STRINGS.NAMES.KYNO_FLOATILIZER = "漂浮物"
STRINGS.RECIPE_DESC.KYNO_FLOATILIZER = "海洋肥料。"

STRINGS.NAMES.KYNO_TWIGGYNUTS = "坚果"

STRINGS.NAMES.KYNO_POND_SALT = "盐池"
STRINGS.NAMES.KYNO_POND_RACK = "盐池"
STRINGS.NAMES.KYNO_SALTRACK = "盐架"

STRINGS.NAMES.KYNO_REPAIRTOOL = "修复工具"

STRINGS.NAMES.KYNO_KOI = "热带锦鲤"
STRINGS.NAMES.KYNO_KOI_COOKED = "烤熟的热带锦鲤"

STRINGS.NAMES.KYNO_TROPICALFISH = "热带鱼"
STRINGS.NAMES.KYNO_TROPICALFISH_COOKED = "烤熟的热带鱼"

STRINGS.NAMES.KYNO_NEONFISH = "霓虹鱼"
STRINGS.NAMES.KYNO_NEONFISH_COOKED = "烤熟的霓虹鱼"

STRINGS.NAMES.KYNO_GROUPER = "紫石斑鱼"
STRINGS.NAMES.KYNO_GROUPER_COOKED = "烤熟的紫石斑鱼"

STRINGS.NAMES.KYNO_PIERROTFISH = "小丑鱼"
STRINGS.NAMES.KYNO_PIERROTFISH_COOKED = "烤熟的小丑鱼"

STRINGS.NAMES.KYNO_SALMONFISH = "鲑鱼"
STRINGS.NAMES.KYNO_SALMONFISH_COOKED = "烤熟的鲑鱼"

STRINGS.NAMES.KYNO_SALTRACK_INSTALLER = "盐架"
STRINGS.NAMES.KYNO_SALTRACK_INSTALLER_P = "盐架"
STRINGS.RECIPE_DESC.KYNO_SALTRACK_INSTALLER_P = "为了放置在池塘上，小伙计！"

STRINGS.NAMES.TURF_PINKPARK = "粉红公园草皮"
STRINGS.NAMES.TURF_PINKPARK_P = "粉红公园草皮蓝图"

STRINGS.NAMES.TURF_STONECITY = "白石路"
STRINGS.NAMES.TURF_STONECITY_P = "白石路蓝图"

STRINGS.NAMES.TURF_FIELDS = "人工草皮"

STRINGS.NAMES.TURF_TIDALMARSH = "潮汐沼泽草皮"
STRINGS.NAMES.WURT_TURF_TIDALMARSH = "潮汐沼泽草皮"
STRINGS.RECIPE_DESC.TURF_TIDALMARSH = "沼泽地。"

STRINGS.NAMES.KYNO_SERENITYISLAND_ROCK1 = "岩石"
STRINGS.NAMES.KYNO_SERENITYISLAND_ROCK2 = "岩石"
STRINGS.NAMES.KYNO_SERENITYISLAND_ROCK3 = "岩石"
STRINGS.NAMES.KYNO_SERENITYISLAND_ROCK3_MED = "岩石"
STRINGS.NAMES.KYNO_SERENITYISLAND_ROCK3_LOW = "岩石"

STRINGS.NAMES.KYNO_SUGARTREE = "糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_SAPLING = "糖木树苗"
STRINGS.NAMES.KYNO_SUGARTREE_SAPPED = "糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_SAPPED_SCRAPBOOK = "采集过的糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_STUMP = "糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_RUINED = "被感染的糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_RUINED_SCRAPBOOK = "被感染的采集过的糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_RUINED2 = "被感染的糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_STUMP_RUINED = "被感染的糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_SHORT = "糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_NORMAL = "糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_SHORT_STUMP = "糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_NORMAL_STUMP = "糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_SHORT_BURNT = "糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_NORMAL_BURNT = "糖木树"
STRINGS.NAMES.KYNO_SUGARTREE_BURNT = "糖木树"

STRINGS.NAMES.KYNO_SAPBUCKET_INSTALLER = "树液收集桶"
STRINGS.NAMES.KYNO_SAPBUCKET_INSTALLER_P = "树液收集桶"
STRINGS.RECIPE_DESC.KYNO_SAPBUCKET_INSTALLER_P = "适合粉红树！"

STRINGS.NAMES.KYNO_SERENITYISLAND_SHOP = "猪长老"

STRINGS.NAMES.KYNO_SUGARTREE_BUD = "糖芽"
STRINGS.NAMES.KYNO_SUGARTREE_BUD_P = "糖芽"
STRINGS.RECIPE_DESC.KYNO_SUGARTREE_BUD_P = "把那些树种在这里！"

STRINGS.NAMES.KYNO_SUGARTREE_FLOWER = "甜花"
STRINGS.NAMES.KYNO_SUGARTREE_FLOWER_PLANTED = "甜花"

STRINGS.NAMES.KYNO_SUGARTREE_PETALS = "甜花"
STRINGS.NAMES.KYNO_SUGARTREE_PETALS_P = "甜花"
STRINGS.RECIPE_DESC.KYNO_SUGARTREE_PETALS_P = "将带的糖花做成糖果!"

STRINGS.NAMES.KYNO_CRABTRAP_INSTALLER = "蟹笼"
STRINGS.NAMES.KYNO_CRABTRAP_INSTALLER_P = "蟹笼"
STRINGS.RECIPE_DESC.KYNO_CRABTRAP_INSTALLER_P = "用于捕捉小生物！"

STRINGS.NAMES.KYNO_PEBBLECRAB = "卵石蟹"

STRINGS.NAMES.KYNO_CRABMEAT = "蟹肉"
STRINGS.NAMES.KYNO_CRABMEAT_COOKED = "烤熟的蟹肉"
STRINGS.NAMES.KYNO_CRABMEAT_DRIED = "蟹肉干"

STRINGS.NAMES.KYNO_CRABKINGMEAT = "帝王蟹肉"
STRINGS.RECIPE_DESC.KYNO_CRABKINGMEAT_M = "来自稀有螃蟹标本的高贵肉类。"
STRINGS.NAMES.KYNO_CRABKINGMEAT_COOKED = "烤熟的帝王蟹肉"
STRINGS.NAMES.KYNO_CRABKINGMEAT_DRIED = "帝王蟹肉干"

STRINGS.NAMES.KYNO_SLAUGHTERTOOL = "屠宰工具"
STRINGS.NAMES.KYNO_SLAUGHTERTOOL_P = "屠宰工具"
STRINGS.RECIPE_DESC.KYNO_SLAUGHTERTOOL_P = "可怜的动物，但这是必须的！"

STRINGS.NAMES.KYNO_CHICKEN2 = "鸡"
STRINGS.NAMES.KYNO_CHICKEN_COOP = "鸡"
STRINGS.RECIPE_DESC.KYNO_CHICKEN_M = "一种用于家禽养殖的鸟类。"

STRINGS.NAMES.KYNO_CHICKEN_EGG = "鸡蛋"
STRINGS.NAMES.KYNO_CHICKEN_EGG_GIANT = "Giant Chicken Egg"
STRINGS.NAMES.KYNO_CHICKEN_EGG_COOKED = "熟鸡蛋"

STRINGS.NAMES.KYNO_CHICKENHOUSE = "鸡舍"
STRINGS.RECIPE_DESC.KYNO_CHICKENHOUSE = "用于饲养家禽的小房子。"

STRINGS.NAMES.KYNO_COOKWARE_HANGER = "锅架"
STRINGS.NAMES.KYNO_COOKWARE_HANGER_ITEM = "锅架"

STRINGS.NAMES.KYNO_COOKWARE_KIT_HANGER = "炊具套件"
STRINGS.RECIPE_DESC.KYNO_COOKWARE_KIT_HANGER_P = "设置炊具套件所需的一切！"

STRINGS.NAMES.KYNO_COOKWARE_KIT_SYRUP = "糖浆套件"
STRINGS.RECIPE_DESC.KYNO_COOKWARE_KIT_SYRUP_P = "准备糖浆套件所需的一切！"

STRINGS.NAMES.KYNO_COOKWARE_KIT_OVEN = "烤箱套件"
STRINGS.RECIPE_DESC.KYNO_COOKWARE_KIT_OVEN_P = "设置烤箱所需的一切！"

STRINGS.NAMES.KYNO_COOKWARE_KIT_SMALL_GRILL = "烧烤套件"
STRINGS.RECIPE_DESC.KYNO_COOKWARE_KIT_SMALL_GRILL_P = "设置烧烤套件所需的一切！"

STRINGS.NAMES.KYNO_COOKWARE_KIT_GRILL = "大型烧烤套件"
STRINGS.RECIPE_DESC.KYNO_COOKWARE_KIT_GRILL_P = "设置大型烧烤套件需的一切！"

STRINGS.NAMES.KYNO_KIT_HANGER_P = "炊具套件"
STRINGS.NAMES.KYNO_KIT_SYRUP_P = "糖浆套件"
STRINGS.NAMES.KYNO_KIT_OVEN_P = "烤箱套件"
STRINGS.NAMES.KYNO_KIT_SMALL_GRILL_P = "烧烤套件"
STRINGS.NAMES.KYNO_KIT_GRILL_P = "大型烧烤套件"

STRINGS.NAMES.KYNO_COOKWARE_SYRUP = "糖浆罐"
STRINGS.NAMES.KYNO_COOKWARE_SYRUP_POT = "糖浆罐"
STRINGS.NAMES.KYNO_COOKWARE_SYRUP_POT_SCRAPBOOK = "糖浆罐条目"
STRINGS.NAMES.KYNO_COOKWARE_BIG_POT = "大锅"
STRINGS.NAMES.KYNO_COOKWARE_BIG_POT_SCRAPBOOK = "大锅条目"
STRINGS.NAMES.KYNO_COOKWARE_BIG = "大锅"
STRINGS.NAMES.KYNO_COOKWARE_SMALL_POT = "小锅"
STRINGS.NAMES.KYNO_COOKWARE_SMALL_POT_SCRAPBOOK = "小锅条目"
STRINGS.NAMES.KYNO_COOKWARE_SMALL = "小锅"
STRINGS.NAMES.KYNO_COOKWARE_GRILL = "大烤架"
STRINGS.NAMES.KYNO_COOKWARE_GRILL_ITEM = "大烤架"
STRINGS.NAMES.KYNO_COOKWARE_GRILL_ITEM_SCRAPBOOK = "大烤架条目"
STRINGS.NAMES.KYNO_COOKWARE_SMALL_GRILL = "小烤架"
STRINGS.NAMES.KYNO_COOKWARE_SMALL_GRILL_ITEM = "小烤架"
STRINGS.NAMES.KYNO_COOKWARE_SMALL_GRILL_ITEM_SCRAPBOOK = "小烤架条目"
STRINGS.NAMES.KYNO_COOKWARE_ELDER = "长老的旧锅"
STRINGS.NAMES.KYNO_COOKWARE_OVEN_ITEM = "烤箱"
STRINGS.NAMES.KYNO_COOKWARE_OVEN_ITEM_SCRAPBOOK = "烤箱条目"
STRINGS.NAMES.KYNO_COOKWARE_CASSEROLE = "大砂锅"
STRINGS.NAMES.KYNO_COOKWARE_SMALL_CASSEROLE = "小砂锅"
STRINGS.NAMES.KYNO_COOKWARE_OVEN = "烤箱"
STRINGS.NAMES.KYNO_COOKWARE_OVEN_SCRAPBOOK = "空烤箱"
STRINGS.NAMES.KYNO_COOKWARE_OVEN_CASSEROLE = "烤箱"
STRINGS.NAMES.KYNO_COOKWARE_OVEN_CASSEROLE_SCRAPBOOK = "带大砂锅的烤箱"
STRINGS.NAMES.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "烤箱"
STRINGS.NAMES.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE_SCRAPBOOK = "带小砂锅的烤箱"

STRINGS.NAMES.KYNO_ROCKFLIPPABLE = "石板"
STRINGS.NAMES.KYNO_ROCKFLIPPABLE_CAVE = "石板"

STRINGS.NAMES.KYNO_SERENITYISLAND_DECOR2 = "瓦砾"
STRINGS.NAMES.KYNO_SERENITYISLAND_CRATE = "水箱"

STRINGS.NAMES.KYNO_SUGARFLY = "糖蝴蝶"
STRINGS.NAMES.KYNO_SUGARFLY1 = "糖蝴蝶"
STRINGS.NAMES.KYNO_SUGARFLY2 = "糖蛾"
STRINGS.NAMES.KYNO_SUGARFLY3 = "甜蝴蝶"
STRINGS.RECIPE_DESC.KYNO_SUGARFLY = "帮助他们重温荣耀。" -- HRF! LITTLE SUGAR FRIENDS TO MAKE GOODIES!

STRINGS.NAMES.KYNO_SUGARFLYWINGS = "糖蝴蝶翅膀"
STRINGS.NAMES.KYNO_SUGARFLYWINGS1 = "糖蝴蝶翅膀"
STRINGS.NAMES.KYNO_SUGARFLYWINGS2 = "糖蛾翅膀"
STRINGS.NAMES.KYNO_SUGARFLYWINGS3 = "甜蝴蝶翅膀"

STRINGS.NAMES.KYNO_WATERY_CRATE = "水箱"

STRINGS.NAMES.KYNO_TUNACAN = "金枪鱼罐头"
STRINGS.RECIPE_DESC.KYNO_TUNACAN_M = "为海外旅行而保存的鱼。"
STRINGS.NAMES.KYNO_TUNACAN_OPEN = "被打开的金枪鱼罐头"

STRINGS.NAMES.KYNO_TOMATOCAN = "番茄罐头"
STRINGS.RECIPE_DESC.KYNO_TOMATOCAN_M = "当你感到沮丧时。"
STRINGS.NAMES.KYNO_TOMATOCAN_OPEN = "打开番茄罐头"

STRINGS.NAMES.KYNO_BEANCAN = "豆类罐头"
STRINGS.RECIPE_DESC.KYNO_BEANCAN_M = "满足你做汤需求。"
STRINGS.NAMES.KYNO_BEANCAN_OPEN = "打开的罐装豆子"

STRINGS.NAMES.KYNO_MEATCAN = "罐装肉排"
STRINGS.RECIPE_DESC.KYNO_MEATCAN_M = "可以永远保存的罐头肉！"
STRINGS.NAMES.KYNO_MEATCAN_OPEN = "打开的罐头肉排"

STRINGS.NAMES.KYNO_ANTCHOVYCAN = "蚁头凤尾小鱼罐头"
STRINGS.RECIPE_DESC.KYNO_ANTCHOVYCAN_M = "许多蚁头凤尾小鱼"
STRINGS.NAMES.KYNO_ANTCHOVYCAN_OPEN = "打开的蚁头凤尾小鱼罐头"

STRINGS.NAMES.KYNO_SODACAN = "橘子苏打水"
STRINGS.RECIPE_DESC.KYNO_SODACAN_M = "不知道里面是不是真正的橘子。"

STRINGS.NAMES.KYNO_COKECAN = "可乐"
STRINGS.RECIPE_DESC.KYNO_COKECAN_M = "一种经典的好喝饮料。"

STRINGS.NAMES.KYNO_ENERGYCAN = "能量饮料"
STRINGS.RECIPE_DESC.KYNO_ENERGYCAN_M = "充满力量"

STRINGS.NAMES.KYNO_FISHPACKAGE = "神秘礼包"
STRINGS.NAMES.KYNO_MOBPACKAGE = "奇怪的包裹"

STRINGS.NAMES.KYNO_MYSTERYMEAT = "粘液覆盖的残渣"

STRINGS.NAMES.KYNO_BOTTLE_SOUL = "瓶子里的灵魂"

STRINGS.NAMES.SOULSTEW = "灵魂炖菜"

STRINGS.NAMES.FORTUNECOOKIE = "幸运饼干"

STRINGS.NAMES.HORNOCUPIA = "丰收之角"

STRINGS.NAMES.CHEESE_YELLOW = "奶酪"
STRINGS.NAMES.CHEESE_WHITE = "白奶酪"
STRINGS.NAMES.CHEESE_KOALEFANT = "考拉象奶酪"

STRINGS.NAMES.MILK_BOX = "牛奶盒"

STRINGS.NAMES.WATERCUP = "凉白开"

STRINGS.NAMES.HONEYJAR = "蜜罐"

STRINGS.NAMES.CRAB_ARTICHOKE = "洋蓟蟹"

STRINGS.NAMES.PEPPERROLLS = "胡椒卷"

STRINGS.NAMES.KYNO_SAPHEALER = "发霉解毒剂"
STRINGS.RECIPE_DESC.KYNO_SAPHEALER_P = "治愈不新鲜的糖！"

STRINGS.NAMES.KYNO_OCEAN_WRECK = "沉船"

STRINGS.NAMES.KYNO_GHOST_PIRATE = "海盗幽灵"

STRINGS.NAMES.KYNO_BUCKET_EMPTY = "空水桶"
STRINGS.RECIPE_DESC.KYNO_BUCKET_EMPTY = "用于储存液体或其他东西。"

STRINGS.NAMES.KYNO_BUCKET_METAL = "结实的水桶"
STRINGS.RECIPE_DESC.KYNO_BUCKET_METAL_M = "一个能够承受最艰巨任务的金属桶。"

STRINGS.NAMES.KYNO_BUCKET_WATER = "水桶"

STRINGS.NAMES.KYNO_MILK_BEEFALO = "皮弗娄牛奶"
STRINGS.NAMES.KYNO_MILK_KOALEFANT = "考拉象奶"

STRINGS.NAMES.KYNO_RED_CAP_DRIED = "红蘑菇干"
STRINGS.NAMES.KYNO_GREEN_CAP_DRIED = "绿蘑菇干"
STRINGS.NAMES.KYNO_BLUE_CAP_DRIED = "蓝蘑菇干"
STRINGS.NAMES.KYNO_MOON_CAP_DRIED = "月亮蘑菇干"

STRINGS.NAMES.KYNO_PLANTMEAT_DRIED = "叶肉干"

STRINGS.NAMES.KYNO_PIGSKIN_DRIED = "猪皮干"

STRINGS.NAMES.KYNO_BREWBOOK = "酿造手册"
STRINGS.RECIPE_DESC.KYNO_BREWBOOK = "查看你收集的配方。"

STRINGS.NAMES.KYNO_WOODENKEG = "精酿桶"
STRINGS.RECIPE_DESC.KYNO_WOODENKEG = "配料最终会变成饮料。"

STRINGS.NAMES.KYNO_PRESERVESJAR = "罐头瓶"
STRINGS.RECIPE_DESC.KYNO_PRESERVESJAR = "把蔬菜变成泡菜，把水果变成果酱。"

STRINGS.NAMES.KYNO_ANTCHEST = "蜂蜜储存盒"
STRINGS.RECIPE_DESC.KYNO_ANTCHEST = "保护蜂蜜制品的腐败。"

STRINGS.NAMES.KYNO_NECTAR_POD = "花蜜"

STRINGS.NAMES.KYNO_OAKTREE_POD = "种子荚"
STRINGS.NAMES.KYNO_OAKTREE_POD_COOKED = "烤豆荚"

STRINGS.NAMES.KYNO_PIKO = "异食松鼠"
STRINGS.RECIPE_DESC.KYNO_PIKO_M = "讨厌的小松鼠，什么都偷。"

STRINGS.NAMES.KYNO_PIKO_ORANGE = "橙色异食松鼠"
STRINGS.RECIPE_DESC.KYNO_PIKO_ORANGE_M = "讨厌的小松鼠，什么都偷。"

STRINGS.NAMES.KYNO_MEADOWISLAND_TREE = "茶树"
STRINGS.NAMES.KYNO_MEADOWISLAND_TREE_SAPLING = "茶树树苗"

STRINGS.NAMES.KYNO_MEADOWISLAND_PIKOTREE = "被感染的茶树"

STRINGS.NAMES.KYNO_MEADOWISLAND_CRATE = "箱子"

STRINGS.NAMES.KYNO_MEADOWISLAND_MERMHUT = "人鱼屋"
STRINGS.NAMES.KYNO_MEADOWISLAND_FISHERMERMHUT = "渔民小屋"
STRINGS.NAMES.KYNO_MEADOWISLAND_MERMFISHER = "渔民"

STRINGS.NAMES.KYNO_FISHERMERMHUT_WURT = "工匠小屋"
STRINGS.RECIPE_DESC.KYNO_FISHERMERMHUT_WURT = "适合渔民居住的房子。"

STRINGS.NAMES.KYNO_MEADOWISLAND_SHOP = "萨米的小店"
STRINGS.NAMES.KYNO_MEADOWISLAND_MERMCART = "萨米的小推车"
STRINGS.NAMES.KYNO_MEADOWISLAND_SELLER = "萨米\n商人" -- Placeholder.
STRINGS.NAMES.KYNO_MEADOWISLAND_SELLER_SCRAPBOOK = "萨米"
STRINGS.NAMES.KYNO_MEADOWISLAND_POND = "潮汐池"
STRINGS.NAMES.KYNO_MEADOWISLAND_PLANTY = "植物"
STRINGS.NAMES.KYNO_MEADOWISLAND_SANDHILL = "沙堆"

-- RECIPE_DESC for Sammy's Emporium.
STRINGS.RECIPE_DESC.FOLIAGE_M = "紫色蕨类植物。"
STRINGS.RECIPE_DESC.BARNACLE_M = "喜欢搭便车的家伙。"
STRINGS.RECIPE_DESC.TALLBIRDEGG_M = "来自独眼生物巨大的蛋。"
STRINGS.RECIPE_DESC.BUTTER_M = "信不信由你，这是黄油。"
STRINGS.RECIPE_DESC.MANDRAKE_M = "具有催眠特性的活根。"
STRINGS.RECIPE_DESC.OCEANFISH_SMALL_6_INV_M = "秋季水域的珍稀鱼类。"
STRINGS.RECIPE_DESC.OCEANFISH_MEDIUM_8_INV_M = "冬季水域的珍稀鱼类。"
STRINGS.RECIPE_DESC.OCEANFISH_SMALL_7_INV_M = "春季水域的珍稀鱼类。"
STRINGS.RECIPE_DESC.OCEANFISH_SMALL_8_INV_M = "夏季水域的珍稀鱼类。"
STRINGS.RECIPE_DESC.SUCCULENT_PICKED_M = "夏季植物。"
STRINGS.RECIPE_DESC.MOON_CAP_M = "蘑菇充满了月亮的力量。"

STRINGS.NAMES.SLOW_FARMPLOT_BLUEPRINT = "基础农场蓝图"
STRINGS.RECIPE_DESC.SLOW_FARMPLOT_BLUEPRINT = "一次怀旧之旅。"

STRINGS.NAMES.FAST_FARMPLOT_BLUEPRINT = "改良农场蓝图"
STRINGS.RECIPE_DESC.FAST_FARMPLOT_BLUEPRINT = "一场穿越时光的旅行，回到更简单的年代。"

STRINGS.NAMES.KYNO_BOOK_GARDENING = "园艺学精通版"
STRINGS.RECIPE_DESC.KYNO_BOOK_GARDENING = "驾驭植物学的力量，让植物听命于你。"

STRINGS.NAMES.KYNO_SAMMYHAT = "萨米的帽子"

STRINGS.NAMES.KINGFISHER = "翠鸟"

STRINGS.NAMES.TOUCAN = "大嘴鸟"
STRINGS.NAMES.TOUCAN_CHUBBY = "胖胖的大嘴鸟"

STRINGS.NAMES.WETGOOP2 = "污泥"

STRINGS.NAMES.BEER = "啤酒"

STRINGS.NAMES.PALEALE = "淡啤酒"

STRINGS.NAMES.TEAGREEN = "绿茶"

STRINGS.NAMES.TEARED = "红茶"

STRINGS.NAMES.MEAD = "蜂蜜酒"

STRINGS.NAMES.KYNO_JELLY = "果酱"
STRINGS.NAMES.JELLY_BERRIES = "浆果酱"
STRINGS.NAMES.JELLY_BERRIES_JUICY = "多汁浆果酱"
STRINGS.NAMES.JELLY_POMEGRANATE = "石榴果酱"
STRINGS.NAMES.JELLY_DRAGONFRUIT = "火龙果酱"
STRINGS.NAMES.JELLY_CAVE_BANANA = "洞穴香蕉酱"
STRINGS.NAMES.JELLY_DURIAN = "榴莲果酱"
STRINGS.NAMES.JELLY_WATERMELON = "西瓜酱"
STRINGS.NAMES.JELLY_FIG = "无花果酱"
STRINGS.NAMES.JELLY_BANANA = "金色香蕉酱"
STRINGS.NAMES.JELLY_KOKONUT = "椰子酱"
STRINGS.NAMES.JELLY_GLOWBERRY = "发光浆果酱"
STRINGS.NAMES.JELLY_PINEAPPLE = "菠萝果酱"
STRINGS.NAMES.JELLY_NIGHTBERRY = "夜莓果酱"

STRINGS.NAMES.KYNO_MAYONNAISE = "蛋黄酱"
STRINGS.NAMES.MAYONNAISE = "蛋黄酱"
STRINGS.NAMES.MAYONNAISE_CHICKEN = "鸡肉蛋黄酱"
STRINGS.NAMES.MAYONNAISE_TALLBIRD = "高鸟蛋黄酱"
STRINGS.NAMES.MAYONNAISE_NIGHTMARE = "噩梦蛋黄酱"

STRINGS.NAMES.TARTARSAUCE = "鞑靼酱"

STRINGS.NAMES.KYNO_PICKLES = "泡菜"
STRINGS.NAMES.PICKLES_CARROT = "腌胡萝卜"
STRINGS.NAMES.PICKLES_CORN = "腌玉米"
STRINGS.NAMES.PICKLES_EGGPLANT = "腌茄子"
STRINGS.NAMES.PICKLES_PUMPKIN = "腌南瓜"
STRINGS.NAMES.PICKLES_LICHEN = "腌苔藓"
STRINGS.NAMES.PICKLES_CACTUS = "腌仙人掌"
STRINGS.NAMES.PICKLES_GARLIC = "腌大蒜"
STRINGS.NAMES.PICKLES_ASPARAGUS = "腌芦笋"
STRINGS.NAMES.PICKLES_ONION = "腌洋葱"
STRINGS.NAMES.PICKLES_TOMATO = "腌番茄"
STRINGS.NAMES.PICKLES_POTATO = "腌土豆"
STRINGS.NAMES.PICKLES_PEPPER = "泡椒"
STRINGS.NAMES.PICKLES_REDCAP = "腌红蘑菇"
STRINGS.NAMES.PICKLES_GREENCAP = "腌绿蘑菇"
STRINGS.NAMES.PICKLES_BLUECAP = "腌蓝蘑菇"
STRINGS.NAMES.PICKLES_MOONCAP = "腌月亮蘑菇"
STRINGS.NAMES.PICKLES_KELP = "腌海带"
STRINGS.NAMES.PICKLES_AVOCADO = "腌石果"
STRINGS.NAMES.PICKLES_WHITECAP = "腌香菇"
STRINGS.NAMES.PICKLES_ALOE = "腌芦荟"
STRINGS.NAMES.PICKLES_RADISH = "腌红萝卜"
STRINGS.NAMES.PICKLES_SWEETPOTATO = "腌红薯"
STRINGS.NAMES.PICKLES_LOTUS = "腌莲花"
STRINGS.NAMES.PICKLES_SEAWEEDS = "腌海藻"
STRINGS.NAMES.PICKLES_TAROROOT = "腌芋头"
STRINGS.NAMES.PICKLES_WATERYCRESS = "腌西洋菜"
STRINGS.NAMES.PICKLES_CUCUMBER = "腌海黄瓜"
STRINGS.NAMES.PICKLES_CUCUMBER_SCRAPBOOK = "腌过的海黄瓜"
STRINGS.NAMES.PICKLES_PARZNIP = "腌防风草"
STRINGS.NAMES.PICKLES_TURNIP = "腌芜菁"
STRINGS.NAMES.PICKLES_FENNEL = "腌茴香"
STRINGS.NAMES.PICKLES_RICE = "腌稻米"
STRINGS.NAMES.PICKLES_TRUFFLES = "腌松露"
STRINGS.NAMES.PICKLES_SPORECAP = "腌制枯萎病菌盖"
STRINGS.NAMES.PICKLES_SPORECAP_DARK = "腌制毒蕈"

STRINGS.NAMES.KYNO_WINE = "酒"
STRINGS.NAMES.WINE_BERRIES = "浆果酒"
STRINGS.NAMES.WINE_BERRIES_JUICY = "多汁浆果酒"
STRINGS.NAMES.WINE_POMEGRANATE = "石榴酒"
STRINGS.NAMES.WINE_DRAGONFRUIT = "火龙果酒"
STRINGS.NAMES.WINE_CAVE_BANANA = "洞穴香蕉酒"
STRINGS.NAMES.WINE_DURIAN = "榴莲酒"
STRINGS.NAMES.WINE_WATERMELON = "西瓜酒"
STRINGS.NAMES.WINE_FIG = "无花果酒"
STRINGS.NAMES.WINE_BANANA = "金色香蕉酒"
STRINGS.NAMES.WINE_KOKONUT = "椰子酒"
STRINGS.NAMES.WINE_GLOWBERRY = "发光浆果酒"
STRINGS.NAMES.WINE_PINEAPPLE = "菠萝啤"
STRINGS.NAMES.WINE_NIGHTBERRY = "夜莓酒"

STRINGS.NAMES.KYNO_JUICE = "果汁"
STRINGS.NAMES.JUICE_CARROT = "胡萝卜汁"
STRINGS.NAMES.JUICE_CORN = "玉米汁"
STRINGS.NAMES.JUICE_EGGPLANT = "茄子汁"
STRINGS.NAMES.JUICE_PUMPKIN = "南瓜汁"
STRINGS.NAMES.JUICE_LICHEN = "苔藓汁"
STRINGS.NAMES.JUICE_CACTUS = "仙人掌汁"
STRINGS.NAMES.JUICE_GARLIC = "大蒜汁"
STRINGS.NAMES.JUICE_ASPARAGUS = "芦笋汁"
STRINGS.NAMES.JUICE_ONION = "洋葱汁"
STRINGS.NAMES.JUICE_TOMATO = "番茄汁"
STRINGS.NAMES.JUICE_POTATO = "土豆汁"
STRINGS.NAMES.JUICE_PEPPER = "辣椒汁"
STRINGS.NAMES.JUICE_REDCAP = "红蘑菇汁"
STRINGS.NAMES.JUICE_GREENCAP = "绿蘑菇汁"
STRINGS.NAMES.JUICE_BLUECAP = "蓝蘑菇汁"
STRINGS.NAMES.JUICE_MOONCAP = "月亮蘑菇汁"
STRINGS.NAMES.JUICE_KELP = "海带汁"
STRINGS.NAMES.JUICE_AVOCADO = "石果汁"
STRINGS.NAMES.JUICE_WHITECAP = "香菇汁"
STRINGS.NAMES.JUICE_ALOE = "芦荟汁"
STRINGS.NAMES.JUICE_RADISH = "红萝卜汁"
STRINGS.NAMES.JUICE_SWEETPOTATO = "红薯汁"
STRINGS.NAMES.JUICE_LOTUS = "莲花汁"
STRINGS.NAMES.JUICE_SEAWEEDS = "海藻汁"
STRINGS.NAMES.JUICE_TAROROOT = "芋头汁"
STRINGS.NAMES.JUICE_WATERYCRESS = "西洋菜汁"
STRINGS.NAMES.JUICE_CUCUMBER = "海黄瓜汁"
STRINGS.NAMES.JUICE_PARZNIP = "防风草汁"
STRINGS.NAMES.JUICE_TURNIP = "芜菁汁"
STRINGS.NAMES.JUICE_FENNEL = "茴香汁"
STRINGS.NAMES.JUICE_TRUFFLES = "松露汁"
STRINGS.NAMES.JUICE_SPORECAP = "枯疫菌汁"
STRINGS.NAMES.JUICE_SPORECAP_DARK = "剧毒菌汁"

STRINGS.NAMES.KYNO_POISON_FROGLEGS = "毒蛙腿"
STRINGS.RECIPE_DESC.KYNO_POISON_FROGLEGS_M = "可能导致食物中毒。"

STRINGS.NAMES.KYNO_POISON_FROGLEGS_COOKED = "烤毒蛙腿"

STRINGS.NAMES.POISONFROGGLEBUNWICH = "毒蛙腿三明治"

STRINGS.NAMES.KYNO_BREWINGRECIPECARD = "{item} 酿造卡"
STRINGS.NAMES.KYNO_BREWINGRECIPECARD_SCRAPBOOK = "酿造卡"

STRINGS.NAMES.KYNO_OIL = "油"
STRINGS.RECIPE_DESC.KYNO_OIL = "可食用油。"

STRINGS.NAMES.BERRYSUNDAE = "圣代冰激凌"

STRINGS.NAMES.CHOCOLATE_BLACK = "黑巧克力"
STRINGS.NAMES.CHOCOLATE_WHITE = "白巧克力"

STRINGS.NAMES.TRICOLORDANGO = "三色团子"

STRINGS.NAMES.FRIESFRENCH = "炸薯条"

STRINGS.NAMES.PIRATERUM = "海盗朗姆酒"

STRINGS.NAMES.TWISTEDTEQUILA = "龙舌兰酒"

STRINGS.NAMES.ONIONRINGS = "洋葱圈"

STRINGS.NAMES.DONUTS = "甜甜圈"
STRINGS.NAMES.DONUTS_CHOCOLATE_BLACK = "黑巧克力甜甜圈"
STRINGS.NAMES.DONUTS_CHOCOLATE_WHITE = "白巧克力甜甜圈"

STRINGS.NAMES.CINNAMONROLL = "肉桂卷"

STRINGS.NAMES.GUMMYBEARGERS = "小熊软糖"

STRINGS.NAMES.PRETZEL = "椒盐卷饼"

STRINGS.NAMES.CORNINCUP = "墨西哥玉米杯"

STRINGS.NAMES.COTTONCANDY = "棉花糖"

STRINGS.NAMES.ROASTEDHAZELNUTS = "烤榛子"

STRINGS.NAMES.MONSTERMUFFIN = "怪物松饼"

STRINGS.NAMES.PINKCAKE = "粉色蛋糕"

STRINGS.NAMES.CHIPSBAG = "薯片"

STRINGS.NAMES.LITTLEBREAD = "面包"

STRINGS.NAMES.HOTHOUND = "热狗"

STRINGS.NAMES.MILKSHAKE = "奶昔"
STRINGS.NAMES.MILKSHAKE_PRISMATIC = "七彩潘趣酒"

STRINGS.NAMES.NACHOS = "玉米片"

STRINGS.NAMES.BANANA_PUDDING = "香蕉布丁"

STRINGS.NAMES.SEA_PUDDING = "海沫布丁"

STRINGS.NAMES.TOM_KHA_SOUP = "泰式椰子汤"

STRINGS.NAMES.MINERTREAT = "棒棒糖"

STRINGS.NAMES.RADISHSALAD = "红萝卜沙拉"

STRINGS.NAMES.PUMPKIN_SOUP = "南瓜汤"

STRINGS.NAMES.ALGAE_SOUP = "海藻汤"

STRINGS.NAMES.PARZNIP_SOUP = "防风草汤"

STRINGS.NAMES.NETTLEMEATED = "肉夹火荨麻"

STRINGS.NAMES.KYNO_SUGAR = "糖粉"
STRINGS.RECIPE_DESC.KYNO_SUGAR = "为糕点和糖果添加甜味。太多可能不健康。"

STRINGS.NAMES.KYNO_BOTTLECAP = "瓶盖"
STRINGS.NAMES.KYNO_BOTTLECAP1 = "盖子"
STRINGS.NAMES.KYNO_BOTTLECAP2 = "瓶盖"
STRINGS.NAMES.KYNO_BOTTLECAP3 = "瓶盖"
STRINGS.RECIPE_DESC.KYNO_BOTTLECAP_M = "末世货币。"

STRINGS.NAMES.NUKACOLA = "核子可乐"
STRINGS.NAMES.NUKACOLA_QUANTUM = "量子可乐"

STRINGS.NAMES.LIVINGSANDWICH = "活木三明治"

STRINGS.NAMES.DURIANSPLIT = "榴莲点心"

STRINGS.NAMES.DURIANSOUP = "榴莲汤"

STRINGS.NAMES.DURIANMEATED = "榴莲炒肉"

STRINGS.NAMES.DURIANCHICKEN = "火鸡榴莲"

STRINGS.NAMES.LUNARSOUP = "月牙汤"

STRINGS.NAMES.PURPLEWOBSTERSOUP = "薰衣草龙虾汤"

STRINGS.NAMES.WOBSTERMONSTER = "怪物龙虾"

STRINGS.NAMES.SPIDERCAKE = "蜘蛛蛋糕"

STRINGS.NAMES.SUGARBOMBS = "甜麦炮弹"
STRINGS.NAMES.SUGARBOMBS_EXPLOSIVE = "甜麦炮弹?"

STRINGS.NAMES.BERRYBOMBS = "浆果篮"

STRINGS.NAMES.ONIGIRIS = "饭团"

STRINGS.NAMES.OMURICE = "蛋包饭"

STRINGS.NAMES.PAELLA = "西班牙海鲜饭"

STRINGS.NAMES.RISOTTO = "意大利烩饭"

STRINGS.NAMES.RICESAKE = "米酒"

STRINGS.NAMES.KYNO_PINEAPPLEBUSH = "菠萝丛"
STRINGS.NAMES.DUG_KYNO_PINEAPPLEBUSH = "菠萝丛"
STRINGS.NAMES.DUG_KYNO_PINEAPPLEBUSH_P = "菠萝丛"
STRINGS.RECIPE_DESC.DUG_KYNO_PINEAPPLEBUSH = "测试"

STRINGS.NAMES.KYNO_PINEAPPLE = "菠萝"
STRINGS.RECIPE_DESC.KYNO_PINEAPPLE_M = "坚硬且有刺的水果。"
STRINGS.NAMES.KYNO_PINEAPPLE_HALVED = "菠萝片"
STRINGS.NAMES.KYNO_PINEAPPLE_COOKED = "烤熟的菠萝片"

STRINGS.NAMES.PIZZA_TROPICAL = "热带风味比萨"

STRINGS.NAMES.PINACOLADA = "凤梨可乐达"

STRINGS.NAMES.CHIMAS = "马黛茶"

STRINGS.NAMES.KYNO_GARDEN_SPRINKLER = "花园洒水器"
STRINGS.RECIPE_DESC.KYNO_GARDEN_SPRINKLER = "自动为农场植物浇水"

STRINGS.NAMES.KYNO_FOODSACK = "盐包"
STRINGS.RECIPE_DESC.KYNO_FOODSACK = "只需一小撮盐，就能让食材焕然一新！"

STRINGS.NAMES.GUMMYWORMS = "软糖蠕虫"

STRINGS.NAMES.SMORES = "棉花糖饼干"

STRINGS.NAMES.NUKASHINE = "核子佳酿"
STRINGS.NAMES.NUKASHINE_SUGARFREE = "\"无糖\" 核子佳酿"
STRINGS.RECIPE_DESC.NUKASHINE_SUGARFREE_M = "现在没有停电的风险!"

STRINGS.NAMES.ANTSLOG = "蚂蚁上树"

STRINGS.NAMES.KYNO_WORM_BONE = "虫骨"
STRINGS.RECIPE_DESC.KYNO_WORM_BONE_M = "绝对不是普通的骨头。"

STRINGS.NAMES.SPOOKY_BRAIN_NOODLES = "脑仁面"
STRINGS.NAMES.SPOOKY_BURGERZILLA = "鳄鱼汉堡"
STRINGS.NAMES.SPOOKY_DEADBREAD = "亡灵面包"
STRINGS.NAMES.SPOOKY_JELLYBEANS = "眼球糖豆"
STRINGS.NAMES.SPOOKY_POPSICLE = "活木冰"
STRINGS.NAMES.SPOOKY_PUMPKINCREAM = "杰克灯笼冰淇淋"
STRINGS.NAMES.SPOOKY_SKULLCANDY = "骷髅糖"
STRINGS.NAMES.SPOOKY_TACODILE = "鳄鱼卷饼"

STRINGS.NAMES.COFFEE_MOCHA = "摩卡咖啡"

STRINGS.NAMES.BUTTER_BEEFALO = "皮弗娄牛奶黄油"
STRINGS.NAMES.BUTTER_GOAT = "伏特山羊奶黄油"
STRINGS.NAMES.BUTTER_KOALEFANT = "考拉象奶黄油"

STRINGS.NAMES.SPICE_CURE = "防腐剂"
STRINGS.NAMES.SPICE_CURE_FOOD = "防腐 {food}"
STRINGS.RECIPE_DESC.SPICE_CURE = "少量的防腐剂来保存你的饭菜。"

STRINGS.NAMES.SPICE_COLD = "冰霜水晶"
STRINGS.NAMES.SPICE_COLD_FOOD = "冰冷 {food}"
STRINGS.RECIPE_DESC.SPICE_COLD = "冷静一下你的敌人！"

STRINGS.NAMES.SPICE_FIRE = "烈焰水晶"
STRINGS.NAMES.SPICE_FIRE_FOOD = "炽热 {food}"
STRINGS.RECIPE_DESC.SPICE_FIRE = "点燃你的敌人！"

STRINGS.NAMES.SPICE_FED = "玉米淀粉"
STRINGS.NAMES.SPICE_FED_FOOD = "饱腹 {food}"
STRINGS.RECIPE_DESC.SPICE_FED = "高热量摄入，高效工作。"

STRINGS.NAMES.SPICE_MIND = "舒缓糖粉"
STRINGS.NAMES.SPICE_MIND_FOOD = "提神 {food}"
STRINGS.RECIPE_DESC.SPICE_MIND = "一小撮舒缓身心的糖。"

STRINGS.NAMES.MOONBUTTERFLYMUFFIN = "月蛾松饼"

STRINGS.NAMES.SUGARFLYMUFFIN = "糖蛾松饼"

STRINGS.NAMES.EELTACOS = "鳗鱼玉米卷"

STRINGS.NAMES.MEATSKILLET = "干煸牛排锅"

STRINGS.NAMES.MEATWALTZ = "肉土司华尔兹"

STRINGS.NAMES.COMPLETEBREAKFAST = "完美早餐"

STRINGS.NAMES.DUMPLINGS = "蒸饺"

STRINGS.NAMES.WARLYICEDTEA = "母亲冰茶"

STRINGS.NAMES.WARLYTEA = "母亲热茶"

STRINGS.NAMES.KYNO_TEALEAF = "茶叶"

STRINGS.NAMES.KYNO_ITEMSLICER = "砍刀"
STRINGS.RECIPE_DESC.KYNO_ITEMSLICER = "用于将物体切成小块。"

STRINGS.NAMES.KYNO_ITEMSLICER_GOLD = "黄金砍刀"
STRINGS.RECIPE_DESC.KYNO_ITEMSLICER_GOLD_M = "这把精致的刀具可以迅速切割任何东西！"

STRINGS.NAMES.COXINHA = "吮指原味鸡"

STRINGS.NAMES.LAZYDESSERT = "懒人甜点"

STRINGS.NAMES.CRABKINGFEAST = "水煮蟹"

STRINGS.NAMES.PIENAPPLE = "菠萝派"

STRINGS.NAMES.JAWSBREAKER = "鲨鱼舔舔糖"

STRINGS.NAMES.AVOCADOTOAST = "鳄梨吐司"

STRINGS.NAMES.RICEPUDDING = "米布丁"

STRINGS.NAMES.SHARKSUSHI = "鲨鱼握寿司"

STRINGS.NAMES.WOBSTERBREADED = "至Q虾球"

STRINGS.NAMES.LAZYPURRITO = "喵喵饼"

STRINGS.NAMES.HORCHATA = "欧洽塔"

STRINGS.NAMES.WOBSTERCOCKTAIL = "龙虾鸡尾酒"

STRINGS.NAMES.LAVAEEGGBOILED = "溏心熔岩蛋"

STRINGS.NAMES.POMEGRANATETEA = "石榴气泡水"

STRINGS.NAMES.TIRAMISU = "提拉米苏咖啡"

STRINGS.NAMES.TOADSTOOLCOLA = "呱呱可乐"

STRINGS.NAMES.TEPACHE = "丹板奇酒"

STRINGS.NAMES.LUNARTEQUILA = "启明龙舌兰酒"

STRINGS.NAMES.MIMICMOSA = "潜行鸡尾酒"

STRINGS.NAMES.POMEGRANATEPIE = "石榴派"

STRINGS.NAMES.PINEAPPLECAKE = "菠萝蛋糕"

STRINGS.NAMES.PASTY_MEAT = "炸肉盒"
STRINGS.NAMES.PASTY_CHEESE = "奶酪馅饼"

STRINGS.NAMES.BRIGADEIRO = "巧克力球"

STRINGS.NAMES.REGULARLASAGNA = "意式千层饼"

STRINGS.NAMES.KYNO_MOON_FROGLEGS = "明眼蛙腿"
STRINGS.RECIPE_DESC.KYNO_MOON_FROGLEGS_M = "注入月之能量的青蛙腿。"
STRINGS.NAMES.KYNO_MOON_FROGLEGS_COOKED = "烤明眼蛙腿"

STRINGS.NAMES.FLTSANDWICH = "F.L.T.三明治"

STRINGS.NAMES.RICEANDBEANS = "豆虫饭"

STRINGS.NAMES.KYNO_DECIDUOUSFOREST_SHOP = "破旧的房子"

STRINGS.NAMES.KYNO_TRUFFLES_GROUND = "松露"
STRINGS.NAMES.KYNO_TRUFFLES = "松露"
STRINGS.NAMES.KYNO_TRUFFLES_COOKED = "烤松露"

STRINGS.NAMES.KYNO_ITEMSHOWCASER = "展示台"
STRINGS.RECIPE_DESC.KYNO_ITEMSHOWCASER = "一个精美的台座，用来展示你最珍贵的菜肴。"

STRINGS.NAMES.KYNO_SPORECAP = "枯萎菇"
STRINGS.NAMES.KYNO_SPORECAP_COOKED = "烤枯萎蘑菇"

STRINGS.NAMES.KYNO_SPORECAP_DARK = "剧毒菇"
STRINGS.NAMES.KYNO_SPORECAP_DARK_COOKED = "烤剧毒蘑菇"

STRINGS.NAMES.KYNO_GOLDENAPPLE = "魔法金苹果"
STRINGS.RECIPE_DESC.KYNO_GOLDENAPPLE_M = "传说它蕴藏着神圣的力量。"

STRINGS.NAMES.TRUFFLESGRINDER = "松露三明治"

STRINGS.NAMES.SPORECAPPIE = "枯疫派"

STRINGS.NAMES.SPORECAP_SKEWERS = "蘑菇串"

STRINGS.NAMES.TRUFFLEOIL = "松露油"

STRINGS.NAMES.KYNO_MALBATROSSFOOD = "迷人的鱼食"
STRINGS.RECIPE_DESC.KYNO_MALBATROSSFOOD = "一种特殊的鱼饵，能引来危险的敌人。"

STRINGS.NAMES.KYNO_FISHFARMPLOT_KIT = "鱼苗孵化基础套装"
STRINGS.RECIPE_DESC.KYNO_FISHFARMPLOT_KIT = "饲养自己的鱼类以繁殖后代并获取鱼卵。"

STRINGS.NAMES.KYNO_FISHFARMPLOT_CONSTRUCTION = "鱼苗孵化基地"

STRINGS.NAMES.KYNO_FISHFARMPLOT = "鱼苗孵化场"

STRINGS.NAMES.KYNO_ANTCHOVY = "蚁头凤尾小鱼"
STRINGS.NAMES.KYNO_ANTCHOVY_SPAWNER = "蚁头凤尾鱼"

STRINGS.NAMES.AGEDROE_PONDFISH = "陈年淡水鱼子酱"
STRINGS.NAMES.AGEDROE_PONDEEL = "陈年鳗鱼子酱"
STRINGS.NAMES.AGEDROE_WOBSTER = "陈年龙虾鱼子酱"
STRINGS.NAMES.AGEDROE_WOBSTER_MONKEYISLAND = "陈年寄居龙虾卵酱"
STRINGS.NAMES.AGEDROE_WOBSTER_MOONGLASS = "陈年月光龙虾卵酱"
STRINGS.NAMES.AGEDROE_NEONFISH = "陈年霓虹鱼鱼子酱"
STRINGS.NAMES.AGEDROE_PIERROTFISH = "陈年小丑鱼鱼子酱"
STRINGS.NAMES.AGEDROE_GROUPER = "陈年紫石斑鱼鱼子酱"
STRINGS.NAMES.AGEDROE_TROPICALFISH = "陈年热带鱼鱼子酱"
STRINGS.NAMES.AGEDROE_JELLYFISH = "陈年水母酱"
STRINGS.NAMES.AGEDROE_JELLYFISH_RAINBOW = "陈年彩虹水母酱"
STRINGS.NAMES.AGEDROE_SALMONFISH = "陈年鲑鱼鱼子酱"
STRINGS.NAMES.AGEDROE_KOI = "陈年热带锦鲤鱼子酱"
STRINGS.NAMES.AGEDROE_ANTCHOVY = "陈年蚁头凤尾鱼鱼子酱"
STRINGS.NAMES.AGEDROE_SWORDFISH_BLUE = "陈年冷冻剑鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_SMALL_1 = "陈年小孔雀鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_SMALL_2 = "陈年针鼻喷墨鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_SMALL_3 = "陈年小饵鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_SMALL_4 = "陈年三文鱼苗鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_SMALL_5 = "陈年爆米花鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_SMALL_6 = "陈年落叶比目鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_SMALL_7 = "陈年花朵金枪鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_SMALL_8 = "陈年炽热太阳鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_SMALL_9 = "陈年口水鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_MEDIUM_1 = "陈年泥鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_MEDIUM_2 = "陈年斑鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_MEDIUM_3 = "陈年浮夸狮子鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_MEDIUM_4 = "陈年黑鲶鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_MEDIUM_5 = "陈年玉米鳕鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_MEDIUM_6 = "陈年花锦鲤鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_MEDIUM_7 = "陈年金锦鲤鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_MEDIUM_8 = "陈年冰鲷鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_MEDIUM_9 = "陈年甜味鱼鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_PUFFERFISH = "陈年河豚鱼子酱"
STRINGS.NAMES.AGEDROE_OCEANFISH_STURGEON = "鱼子酱"

STRINGS.NAMES.KYNO_SWORDFISH_BLUE = "冷冻剑鱼"

STRINGS.NAMES.KYNO_JELLYFISH = "水母"
STRINGS.NAMES.KYNO_JELLYFISH_OCEAN = "水母"
STRINGS.NAMES.KYNO_JELLYFISH_DEAD = "死水母"
STRINGS.NAMES.KYNO_JELLYFISH_COOKED = "熟水母"
STRINGS.NAMES.KYNO_JELLYFISH_DRIED = "水母干"

STRINGS.NAMES.KYNO_JELLYFISH_RAINBOW = "彩虹水母"
STRINGS.NAMES.KYNO_JELLYFISH_RAINBOW_OCEAN = "彩虹水母"
STRINGS.NAMES.KYNO_JELLYFISH_RAINBOW_DEAD = "死彩虹水母"
STRINGS.NAMES.KYNO_JELLYFISH_RAINBOW_COOKED = "熟彩虹水母"

STRINGS.NAMES.KYNO_MESSAGEBOTTLE_EMPTY = "空玻璃瓶"
STRINGS.RECIPE_DESC.KYNO_MESSAGEBOTTLE_EMPTY = "别忘了回收利用！"

STRINGS.NAMES.KYNO_OCEANTRAP = "海上陷阱"
STRINGS.RECIPE_DESC.KYNO_OCEANTRAP = "这是捕获小型海洋生物的陷阱。"

STRINGS.NAMES.OCEANFISH_PUFFERFISH = "河豚"
STRINGS.NAMES.OCEANFISH_PUFFERFISH_INV = "河豚"

STRINGS.NAMES.OCEANFISH_STURGEON = "鲟鱼"
STRINGS.NAMES.OCEANFISH_STURGEON_INV = "鲟鱼"

STRINGS.NAMES.KYNO_SWORDFISH = "剑鱼"
STRINGS.NAMES.KYNO_SWORDFISH_DEAD = "死剑鱼"

STRINGS.NAMES.SWORDFISHFEAST = "鱼肉拼盘"

STRINGS.NAMES.KYNO_DOGFISH = "狗鱼"
STRINGS.NAMES.KYNO_DOGFISH_DEAD = "死狗鱼"

STRINGS.NAMES.KYNO_SPOILED_FISH_LARGE = "变质的大鱼"

STRINGS.NAMES.WOBSTER_MONKEYISLAND = "寄居龙虾"
STRINGS.NAMES.WOBSTER_MONKEYISLAND_LAND = "寄居龙虾"
STRINGS.NAMES.WOBSTER_MONKEYISLAND_DEAD = "死寄居龙虾"
STRINGS.NAMES.WOBSTER_MONKEYISLAND_DEAD_COOKED = "美味的寄居龙虾"

STRINGS.NAMES.KYNO_PUFFERMONSTER = "刺豚"

STRINGS.NAMES.KYNO_WHALE_OCEAN_BUBBLES = "神秘的泡泡"
STRINGS.NAMES.KYNO_WHALE_BLUE_OCEAN = "蓝鲸"
STRINGS.NAMES.KYNO_WHALE_WHITE_OCEAN = "白鲸"
STRINGS.NAMES.KYNO_WHALE_BLUE_OCEAN_CARCASS = "蓝鲸尸体"
STRINGS.NAMES.KYNO_WHALE_WHITE_OCEAN_CARCASS = "白鲸尸体"

STRINGS.NAMES.KYNO_BLUBBER = "鲸脂"

STRINGS.NAMES.KYNO_FISHMEAT_SMALL_DRIED = "小鳕鱼干"
STRINGS.NAMES.KYNO_FISHMEAT_DRIED = "鳕鱼干"

STRINGS.NAMES.MONKEYISLANDMEAL = "女王欢愉"

STRINGS.NAMES.KYNO_BRAINROCK_LARVAE = "智慧幼虫"
STRINGS.NAMES.KYNO_BRAINROCK_NUBBIN = "智慧小穗"
STRINGS.RECIPE_DESC.KYNO_BRAINROCK_NUBBIN = "再好不过了！"

STRINGS.NAMES.KYNO_BRAINROCK_CORAL = "智慧果"

STRINGS.NAMES.KYNO_BRAINROCK_ROCK = "智慧树"

STRINGS.NAMES.BRAINMETTERSOUP = "字母汤"

STRINGS.NAMES.KYNO_OCTOPUSKING_OCEAN = "海盗章鱼"
STRINGS.NAMES.KYNO_OCTOPUSKING_TREASURECHEST = "水箱"

STRINGS.NAMES.KYNO_PACKIMBAGGIMS_FISHBONE = "鱼骨"
STRINGS.NAMES.KYNO_PACKIMBAGGIMS = "帕克白克斯"

STRINGS.RECIPE_DESC.TRANSMUTE_RED_CAP = "将绿蘑菇转化为红蘑菇。"
STRINGS.RECIPE_DESC.TRANSMUTE_GREEN_CAP = "将红蘑菇转化为绿蘑菇。"
STRINGS.RECIPE_DESC.TRANSMUTE_BLUE_CAP = "将月亮蘑菇转化为蓝蘑菇。"
STRINGS.RECIPE_DESC.TRANSMUTE_MOON_CAP = "将蓝蘑菇转化为月亮蘑菇。"
STRINGS.RECIPE_DESC.TRANSMUTE_KYNO_SPORECAP = "将许多蘑菇转化为枯萎蘑菇。"
STRINGS.RECIPE_DESC.TRANSMUTE_BERRIES = "将多汁浆果转化为浆果。"
STRINGS.RECIPE_DESC.TRANSMUTE_BERRIES_JUICY = "将浆果转化为多汁浆果。"
STRINGS.RECIPE_DESC.TRANSMUTE_FISHMEAT_SMALL = "将生鱼肉转化为小鱼块。"
STRINGS.RECIPE_DESC.TRANSMUTE_FISHMEAT = "将小鱼块转化为生鱼肉。"
STRINGS.RECIPE_DESC.TRANSMUTE_KYNO_WHITE_CAP = "将松露转化为香菇。"
STRINGS.RECIPE_DESC.TRANSMUTE_KYNO_TRUFFLES = "将香菇转化为松露。"
STRINGS.RECIPE_DESC.TRANSMUTE_SUCCULENT = "将蕨类植物转化为多肉植物。"
STRINGS.RECIPE_DESC.TRANSMUTE_FOLIAGE = "将多肉植物转化为蕨类植物。"
STRINGS.RECIPE_DESC.TRANSMUTE_FOSSIL_PIECE = "将蠕虫骨骼转化为化石碎片。"
STRINGS.RECIPE_DESC.TRANSMUTE_KYNO_WORM_BONE = "将化石碎片转化为蠕虫骨骼。"

STRINGS.NAMES.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "周年庆蛋糕"
STRINGS.RECIPE_DESC.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "烤出史上最大的周年庆蛋糕！"

STRINGS.NAMES.KYNO_HOFBIRTHDAY_CAKE_STAGE = "周年庆蛋糕"

STRINGS.NAMES.KYNO_HOFBIRTHDAY_CAKE = "周年庆蛋糕"

STRINGS.NAMES.KYNO_HOFBIRTHDAY_CANDLE = "周年庆纪念蜡烛"
STRINGS.RECIPE_DESC.KYNO_HOFBIRTHDAY_CANDLE = "点亮蛋糕，庆祝吧！"

STRINGS.NAMES.KYNO_HOFBIRTHDAY_CHEER = "周年庆贺礼"

STRINGS.NAMES.KYNO_HOFBIRTHDAY_CAKE_SLICE1 = "一块周年庆蛋糕"
STRINGS.NAMES.KYNO_HOFBIRTHDAY_CAKE_SLICE2 = "一块周年庆蛋糕"
STRINGS.NAMES.KYNO_HOFBIRTHDAY_CAKE_SLICE3 = "一块周年庆蛋糕"

STRINGS.NAMES.KYNO_HOFBIRTHDAY_BALLOONS = "周年庆气球"
STRINGS.RECIPE_DESC.KYNO_HOFBIRTHDAY_BALLOONS = "每个派对都需要一些气球。"

STRINGS.NAMES.KYNO_HOFBIRTHDAY_POPCORNMACHINE = "爆米花机"
STRINGS.RECIPE_DESC.KYNO_HOFBIRTHDAY_POPCORNMACHINE = "没有爆米花的派对算什么派对？爆起来吧！"

STRINGS.NAMES.KYNO_HOFBIRTHDAY_POPCORN = "周年庆爆米花"

STRINGS.NAMES.KYNO_HOFBIRTHDAY_5HAT = "周年庆帽子"
STRINGS.RECIPE_DESC.KYNO_HOFBIRTHDAY_HAT = "戴上它，派对即刻开启！"

STRINGS.NAMES.KYNO_HOFBIRTHDAY_SAMMYHAT = "萨米的周年庆帽子"

STRINGS.NAMES.KYNO_FISHREGISTRYHAT = "钓鱼帽"
STRINGS.RECIPE_DESC.KYNO_FISHREGISTRYHAT = "每个水手都该知道什么在咬钩。"