local WORMWOOD = STRINGS.CHARACTERS.WORMWOOD

WORMWOOD.ANNOUNCE_KYNO_COFFEEBUFF_START = "Vùuu!"
WORMWOOD.ANNOUNCE_KYNO_COFFEEBUFF_END = "Hết nhanh rồi?"

WORMWOOD.ANNOUNCE_KYNO_HASTEBUFF_START = "Vùùù!"
WORMWOOD.ANNOUNCE_KYNO_HASTEBUFF_END = "Vùuu đi đâu rồi?"

WORMWOOD.ANNOUNCE_KYNO_POPBUFF_START = "(Ợợ)"
WORMWOOD.ANNOUNCE_KYNO_POPBUFF_END = "Hết sủi bọt rồi?"

WORMWOOD.ANNOUNCE_KYNO_FROGBUFF_START = "Ếch nhỏ!"
WORMWOOD.ANNOUNCE_KYNO_FROGBUFF_END = "Ếch nhỏ đâu rồi?"

WORMWOOD.ANNOUNCE_KYNO_PIRATEBUFF_START = "(Ợợ)"
WORMWOOD.ANNOUNCE_KYNO_PIRATEBUFF_END = "Hết sủi bọt rồi?"

WORMWOOD.ANNOUNCE_KYNO_FREEZEBUFF_START = "Brrr"
WORMWOOD.ANNOUNCE_KYNO_FREEZEBUFF_END = "Hết lạnh rồi"

WORMWOOD.ANNOUNCE_KYNO_FIREBUFF_START = "Nóng!"
WORMWOOD.ANNOUNCE_KYNO_FIREBUFF_END = "Lửa đi rồi"

WORMWOOD.ANNOUNCE_KYNO_FISHINGBUFF_START = "Tới giờ câu cá!"
WORMWOOD.ANNOUNCE_KYNO_FISHINGBUFF_END = "Cá đâu?"

WORMWOOD.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "Dễ chịu quá!"
WORMWOOD.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "Hết dễ chịu rồi"

WORMWOOD.ANNOUNCE_KYNO_EATERBUFF_START = "Bao tử khỏe!"
WORMWOOD.ANNOUNCE_KYNO_EATERBUFF_END = "Bao tử bình thường rồi?"

WORMWOOD.ANNOUNCE_KYNO_WORMBUFF_START = "Yippie"
WORMWOOD.ANNOUNCE_KYNO_WORMBUFF_END = "Hết rồi?"

WORMWOOD.ANNOUNCE_KYNO_CRABBUFF_START = "Yippie"
WORMWOOD.ANNOUNCE_KYNO_CRABBUFF_END = "Hết rồi?"

WORMWOOD.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(Ợợ)"
WORMWOOD.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "Hết sủi bọt rồi?"

WORMWOOD.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "Thấy lạ lạ"
WORMWOOD.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "Thấy ổn hơn rồi"

WORMWOOD.ANNOUNCE_KYNO_STEALTHBUFF_START = "Giờ im lặng"
WORMWOOD.ANNOUNCE_KYNO_STEALTHBUFF_END = "Không lén được nữa?"

WORMWOOD.ANNOUNCE_KYNO_FEARBUFF_START = "Thấy... bình tĩnh"
WORMWOOD.ANNOUNCE_KYNO_FEARBUFF_END = "Cảm giác xấu... tới rồi!"

WORMWOOD.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "Thấy tê tê!"
WORMWOOD.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "Hết sức mạnh lấp lánh rồi"

WORMWOOD.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "Kết bạn với đuôi xoắn"
WORMWOOD.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "Đuôi xoắn đi rồi"

WORMWOOD.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "Mưa không đau nữa!"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WORMWOOD.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "Không bệnh! Thấy khỏe!"
WORMWOOD.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "Lại thấy ghê ghê"

WORMWOOD.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "Não to lên"
WORMWOOD.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "Não mệt rồi"

WORMWOOD.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "Vo ve là bạn! Yay!"
WORMWOOD.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "Vo ve giận rồi!"

WORMWOOD.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "Thấy khỏe! Rất khỏe!"
WORMWOOD.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "Không còn cứng cáp..."

WORMWOOD.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "Bao tử to hơn!"
WORMWOOD.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "Bao tử nhỏ lại..."

WORMWOOD.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "Đầu thấy ổn!"
WORMWOOD.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "Đầu lại quay quay..."

WORMWOOD.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "Cứng! An toàn!"
WORMWOOD.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "Mềm lại rồi"

WORMWOOD.ANNOUNCE_KYNO_BERSERKERBUFF_START = "Đánh mạnh hơn! Đau cũng hơn!"
WORMWOOD.ANNOUNCE_KYNO_BERSERKERBUFF_END = "Không còn đau nhiều nữa"

WORMWOOD.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "Không đói nhanh"
WORMWOOD.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "Lại đói rồi"

WORMWOOD.ANNOUNCE_KYNO_DARKNESSBUFF_START = "Bóng tối thân thiện rồi"
WORMWOOD.ANNOUNCE_KYNO_DARKNESSBUFF_END = "Bóng tối hết thân thiện rồi"

WORMWOOD.ANNOUNCE_KYNO_LUCKBUFF_END = "Biến mất rồi..."

WORMWOOD.ANNOUNCE_KYNO_GREENTHUMBBUFF_START = "Bạn Bè Cho Thêm Quà!"
WORMWOOD.ANNOUNCE_KYNO_GREENTHUMBBUFF_END = "Bạn Bè Không Cho Thêm Nữa"

WORMWOOD.ANNOUNCE_KYNO_WETNESSBUFF_START = "Cảm Thấy Tuyệt!"
WORMWOOD.ANNOUNCE_KYNO_WETNESSBUFF_END = "Cảm Giác Tuyệt Đã Mất"

WORMWOOD.ANNOUNCE_KYNO_NIGHTKILLBUFF_START = "Đêm làm mạnh lên!"
WORMWOOD.ANNOUNCE_KYNO_NIGHTKILLBUFF_END = "Hết đêm..."

WORMWOOD.ANNOUNCE_KYNO_PANICBUFF_START = "Bạn Bè Chạy Mất?"
WORMWOOD.ANNOUNCE_KYNO_PANICBUFF_END = "Bạn Bè Không Chạy Nữa"

WORMWOOD.ANNOUNCE_KYNO_CUREBUFF_START = "Belly Stuff Last Longer" -- NEEDS TRANSLATION
WORMWOOD.ANNOUNCE_KYNO_CUREBUFF_END = "Belly Stuff Gets Old Fast" -- NEEDS TRANSLATION

WORMWOOD.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "Không được đâu"

WORMWOOD.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "Muốn Glub Glub đá"

WORMWOOD.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "Bạn còn nhỏ quá?"

WORMWOOD.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "Không muốn cái này?"

WORMWOOD.ANNOUNCE_KYNO_POTHANGER_FAIL = "Muốn thứ khác"

WORMWOOD.ANNOUNCE_KYNO_CASSEROLE_FAIL = "Không phải cái này?"

WORMWOOD.ANNOUNCE_KYNO_SAPHEALER_USED = "Nước giúp bạn khỏe!"

WORMWOOD.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "Ôi... hết cử động rồi..."

WORMWOOD.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "Hết rồi."

WORMWOOD.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "Bong bóng biến mất?"
WORMWOOD.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "Nước rơi... bong bóng biến mất"
WORMWOOD.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "Thứ to đang bơi... nguy hiểm?"

WORMWOOD.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "Bánh ngọt to xong rồi!"

WORMWOOD.ANNOUNCE_KYNO_FISH_RESEARCHED = "Glub Glub kể nhiều chuyện!"
WORMWOOD.ANNOUNCE_KYNO_ROE_RESEARCHED = "Giờ biết về Glub Glub nhỏ"

WORMWOOD.ANNOUNCE_KYNO_DAILYRECIPE_EATEN = "Ngon!"

WORMWOOD.ANNOUNCE_KYNO_ICENETTLE_TOXIN_START = -- NEEDS TRANSLATION
{
	"Feeling Cold!",
	"Ouch! Ouch!",
}

WORMWOOD.ANNOUNCE_KYNO_ICENETTLE_TOXIN_END = "Feel Better" -- NEEDS TRANSLATION

WORMWOOD.DESCRIBE.KYNO_ROE = "Glub Glub con"
WORMWOOD.DESCRIBE.KYNO_ROE_COOKED = "Nằm thành hàng rồi."

WORMWOOD.DESCRIBE.KYNO_SHARK_FIN = "Lưỡi cắt nước"

WORMWOOD.DESCRIBE.KYNO_BEANBUGS = "Mấy bạn nhảy"
WORMWOOD.DESCRIBE.KYNO_BEANBUGS_COOKED = "Sao không nhảy nữa?"

WORMWOOD.DESCRIBE.KYNO_GUMMYBUG = "Mấy bạn nhớt"
WORMWOOD.DESCRIBE.KYNO_GUMMYBUG_COOKED = "Chào, mấy que nhỏ!"

WORMWOOD.DESCRIBE.KYNO_WHEAT = "Ôi! Hạt xinh!"
WORMWOOD.DESCRIBE.KYNO_WHEAT_COOKED = "Ôi! Hạt thơm!"

WORMWOOD.DESCRIBE.KYNO_FLOUR = "Đồ nghiền mịn"

WORMWOOD.DESCRIBE.KYNO_SPOTSPICE = "Làm đồ ăn ngon hơn"

WORMWOOD.DESCRIBE.KYNO_SAP = "Ruột ngọt của bạn chảy ra rồi"
WORMWOOD.DESCRIBE.KYNO_SAP_SPOILED = "Không không không!"

WORMWOOD.DESCRIBE.KYNO_SYRUP = "Làm đồ ngọt"

WORMWOOD.DESCRIBE.KYNO_COFFEEBEANS = "Quả vù vù!"
WORMWOOD.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "Thơm quá"

WORMWOOD.DESCRIBE.DUG_KYNO_COFFEEBUSH = "Bạn quả vù vù cần đất"

WORMWOOD.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "Bạn quả vù vù",
	PICKED = "Trống trơn",
	WITHERED = "Bạn cần giúp",
}

WORMWOOD.DESCRIBE.DUG_KYNO_SPOTBUSH = "Chào bạn"

WORMWOOD.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "Bạn có tóc tím",
	PICKED = "Tóc bạn đâu rồi?",
	BURNING = "Bạn đau!",
}

WORMWOOD.DESCRIBE.KYNO_SPOTSPICE_LEAF = "Nhánh nhỏ"

WORMWOOD.DESCRIBE.KYNO_MUSSEL = "Đang trốn"
WORMWOOD.DESCRIBE.KYNO_MUSSEL_COOKED = "Cho bao tử"

WORMWOOD.DESCRIBE.KYNO_HUMANMEAT = "Đồ cho bao tử"
WORMWOOD.DESCRIBE.KYNO_HUMANMEAT_COOKED = "Mmmm..."
WORMWOOD.DESCRIBE.KYNO_HUMANMEAT_DRIED = "Dai dai"

WORMWOOD.DESCRIBE.COFFEE = "Vùuu!!!"

WORMWOOD.DESCRIBE.BISQUE = "Món nước có bạn bơi"

WORMWOOD.DESCRIBE.JELLYOPOP = "Cục Glub Glub lạnh"

WORMWOOD.DESCRIBE.SHARKFINSOUP = "Vẫn đang bơi"

WORMWOOD.DESCRIBE.TROPICALBOUILLABAISSE = "Glub Glub?"

WORMWOOD.DESCRIBE.MUSSELBOUILLABAISE = "Tốt cho bao tử"

WORMWOOD.DESCRIBE.SWEETPOTATOSOUFFLE = "Đồ mềm cho bao tử"

WORMWOOD.DESCRIBE.FEIJOADA = "Đầy mấy bạn nhảy"

WORMWOOD.DESCRIBE.GUMMY_CAKE = "Mềm dẻo"

WORMWOOD.DESCRIBE.HARDSHELL_TACOS = "Bzzter giòn rụm"

WORMWOOD.DESCRIBE.ICEDTEA = "Nước lạnh tỉnh tỉnh"

WORMWOOD.DESCRIBE.NETTLELOSANGE = "Mmm..."

WORMWOOD.DESCRIBE.SNAKEBONESOUP = "Nước ngọ nguậy"

WORMWOOD.DESCRIBE.STEAMEDHAMSANDWICH = "Ối chà!"

WORMWOOD.DESCRIBE.TEA = "Nước ấm tỉnh tỉnh"

WORMWOOD.DESCRIBE.BUBBLETEA = "Nước lạnh tỉnh tỉnh"

WORMWOOD.DESCRIBE.FRENCHONIONSOUP = "Nước hành ngọ nguậy"

WORMWOOD.DESCRIBE.SLAW = "Tiệc trong bao tử!"

WORMWOOD.DESCRIBE.LOTUSBOWL = "Vào bao tử là tốt"

WORMWOOD.DESCRIBE.POI = "Đồ cho bao tử"

WORMWOOD.DESCRIBE.JELLYBEAN_HUNGER = "Mmmmm!"
WORMWOOD.DESCRIBE.JELLYBEAN_SUPER = "Mmmmm!"
WORMWOOD.DESCRIBE.JELLYBEAN_SANITY = "Mmmmm!"

WORMWOOD.DESCRIBE.BOWLOFGEARS = "Đồ kim loại"

WORMWOOD.DESCRIBE.LONGPIGMEAL = "Mmm...."

WORMWOOD.DESCRIBE.CUCUMBERSALAD = "Muốn ăn nó"

WORMWOOD.DESCRIBE.DUG_KYNO_WILDWHEAT = "Bạn cần đất"

WORMWOOD.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "Bạn",
	PICKED = "Trống trơn",
	WITHERED = "Bạn không vui",
	BURNING = "Đau!!",
}

WORMWOOD.DESCRIBE.KYNO_MEALGRINDER = "Máy đá"

WORMWOOD.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "Bạn bè! Tiệc!",
	PICKED = "Ôi. Bạn đi rồi",
	BURNING = "Đau!",
}

WORMWOOD.DESCRIBE.GORGE_BREAD = "Mềm xốp"
WORMWOOD.DESCRIBE.GORGE_SWEET_CHIPS = "Lát giòn"
WORMWOOD.DESCRIBE.GORGE_VEGETABLE_SOUP = "Rau củ!"
WORMWOOD.DESCRIBE.GORGE_JELLY_SANDWICH = "Cho bao tử"
WORMWOOD.DESCRIBE.GORGE_FISH_STEW = "Có cá"
WORMWOOD.DESCRIBE.GORGE_MEAT_STEW = "Cho bao tử"
WORMWOOD.DESCRIBE.GORGE_ONION_CAKE = "Bánh!"
WORMWOOD.DESCRIBE.GORGE_POTATO_PANCAKES = "Khoai đâu rồi?"
WORMWOOD.DESCRIBE.GORGE_POTATO_SOUP = "Món nước cho bao tử"
WORMWOOD.DESCRIBE.GORGE_FISHBALL_SKEWERS = "Có cá"
WORMWOOD.DESCRIBE.GORGE_MEAT_SKEWERS = "Có thịt"
WORMWOOD.DESCRIBE.GORGE_STONE_SOUP = "Món nước cho bao tử"
WORMWOOD.DESCRIBE.GORGE_CROQUETTE = "Viên ngon"
WORMWOOD.DESCRIBE.GORGE_ROAST_VEGETABLES = "Đồ xanh thơm"
WORMWOOD.DESCRIBE.GORGE_MEATLOAF = "Có thịt."
WORMWOOD.DESCRIBE.GORGE_CARROT_SOUP = "Món nước cà rốt"
WORMWOOD.DESCRIBE.GORGE_FISHPIE = "Cá bị kẹt?"
WORMWOOD.DESCRIBE.GORGE_FISHCHIPS = "Cho bao tử"
WORMWOOD.DESCRIBE.GORGE_MEATPIE = "Bánh thịt"
WORMWOOD.DESCRIBE.GORGE_SLIDERS = "Bánh nhỏ"
WORMWOOD.DESCRIBE.GORGE_JELLY_ROLL = "Cuộn ngọt"
WORMWOOD.DESCRIBE.GORGE_CARROT_CAKE = "Bánh!"
WORMWOOD.DESCRIBE.GORGE_GARLICMASHED = "Mềm thơm"
WORMWOOD.DESCRIBE.GORGE_GARLICBREAD = "Bánh thơm"
WORMWOOD.DESCRIBE.GORGE_TOMATO_SOUP = "Món nước đỏ"
WORMWOOD.DESCRIBE.GORGE_SAUSAGE = "Cho bao tử"
WORMWOOD.DESCRIBE.GORGE_CANDIEDFISH = "Cá ngọt"
WORMWOOD.DESCRIBE.GORGE_STUFFEDMUSHROOM = "Nấm đầy đồ ăn"
WORMWOOD.DESCRIBE.GORGE_BRUSCHETTA = "Bánh giòn"
WORMWOOD.DESCRIBE.GORGE_HAMBURGER = "Burger"
WORMWOOD.DESCRIBE.GORGE_FISHBURGER = "Burger cá"
WORMWOOD.DESCRIBE.GORGE_MUSHROOMBURGER = "Burger nấm"
WORMWOOD.DESCRIBE.GORGE_FISH_STEAK = "Có cá"
WORMWOOD.DESCRIBE.GORGE_CURRY = "Ấm bao tử"
WORMWOOD.DESCRIBE.GORGE_SPAGHETTI = "Sợi dài với viên tròn"
WORMWOOD.DESCRIBE.GORGE_POACHEDFISH = "Cá mềm"
WORMWOOD.DESCRIBE.GORGE_SHEPHERD_PIE = "Bánh no"
WORMWOOD.DESCRIBE.GORGE_CANDY = "Kẹo dẻo"
WORMWOOD.DESCRIBE.GORGE_BREAD_PUDDING = "Bánh mềm ngọt"
WORMWOOD.DESCRIBE.GORGE_BERRY_TART = "Bánh quả mọng"
WORMWOOD.DESCRIBE.GORGE_MACARONI = "Sợi cong"
WORMWOOD.DESCRIBE.GORGE_BAGEL_AND_FISH = "Bánh với cá"
WORMWOOD.DESCRIBE.GORGE_GRILLED_CHEESE = "Bánh vàng"
WORMWOOD.DESCRIBE.GORGE_CREAMMUSHROOM = "Nấm béo"
WORMWOOD.DESCRIBE.GORGE_MANICOTTI = "Ống mềm"
WORMWOOD.DESCRIBE.GORGE_CHEESEBURGER = "Burger phô mai"
WORMWOOD.DESCRIBE.GORGE_FETTUCCINE = "Sợi trắng"
WORMWOOD.DESCRIBE.GORGE_ONION_SOUP = "Món nước hôi thơm"
WORMWOOD.DESCRIBE.GORGE_BREADED_CUTLET = "Miếng giòn"
WORMWOOD.DESCRIBE.GORGE_CREAMY_FISH = "Cá béo"
WORMWOOD.DESCRIBE.GORGE_PIZZA = "Hmm..."
WORMWOOD.DESCRIBE.GORGE_POT_ROAST = "Miếng to"
WORMWOOD.DESCRIBE.GORGE_CRAB_CAKE = "Bánh cua?"
WORMWOOD.DESCRIBE.GORGE_STEAK_FRITES = "Thịt với khoai"
WORMWOOD.DESCRIBE.GORGE_SHOOTER_SANDWICH = "Bắn?"
WORMWOOD.DESCRIBE.GORGE_BACON_WRAPPED = "Bọc thịt"
WORMWOOD.DESCRIBE.GORGE_CRAB_ROLL = "Cua?"
WORMWOOD.DESCRIBE.GORGE_MEAT_WELLINGTON = "Thịt mặc áo"
WORMWOOD.DESCRIBE.GORGE_CRAB_RAVIOLI = "Cua?"
WORMWOOD.DESCRIBE.GORGE_CARAMEL_CUBE = "Ngọt!"
WORMWOOD.DESCRIBE.GORGE_SCONE = "Ngọt"
WORMWOOD.DESCRIBE.GORGE_TRIFLE = "Ngọt"
WORMWOOD.DESCRIBE.GORGE_CHEESECAKE = "Bánh phô mai"

WORMWOOD.DESCRIBE.DUCKYOUGLERMZ = "Ngon!"

WORMWOOD.DESCRIBE.KYNO_ALOE = "Bạn mọng nước"
WORMWOOD.DESCRIBE.KYNO_ALOE_COOKED = "Mềm nhũn"
WORMWOOD.DESCRIBE.KYNO_ALOE_DRIED = "Bạn cần nước"
WORMWOOD.DESCRIBE.KYNO_ALOE_GROUND = "Bạn mọng nước"
WORMWOOD.DESCRIBE.KYNO_ALOE_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_ALOE = "Bạn mọng nước"
WORMWOOD.DESCRIBE.KYNO_ALOE_OVERSIZED = "Bạn mọng nước"
WORMWOOD.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "Khônggg!"

WORMWOOD.DESCRIBE.KYNO_CUCUMBER = "Đồ mát cho bao tử?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_COOKED = "Mmmm... nhớt!"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_GROUND = "Đồ mát cho bao tử?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "Đồ mát cho bao tử?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "Đồ mát cho bao tử?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "Khônggg!"

WORMWOOD.DESCRIBE.KYNO_RADISH = "Bóng đỏ cho bao tử"
WORMWOOD.DESCRIBE.KYNO_RADISH_COOKED = "Phần xanh đâu rồi?"
WORMWOOD.DESCRIBE.KYNO_RADISH_GROUND = "Bóng đỏ cho bao tử"
WORMWOOD.DESCRIBE.KYNO_RADISH_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_RADISH = "Bóng đỏ cho bao tử"
WORMWOOD.DESCRIBE.KYNO_RADISH_OVERSIZED = "Bóng đỏ cho bao tử"
WORMWOOD.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "Khônggg!"

WORMWOOD.DESCRIBE.KYNO_FENNEL = "Chào!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_COOKED = "Trơn tuột"
WORMWOOD.DESCRIBE.KYNO_FENNEL_GROUND = "Chào!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "Chào!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_OVERSIZED = "Chào!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "Khônggg!"

WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO = "Củ ngọt cho bao tử"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "Mmmm..."
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "Củ ngọt cho bao tử"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "Củ ngọt cho bao tử"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "Củ ngọt cho bao tử"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "Khônggg!"

WORMWOOD.DESCRIBE.KYNO_PARZNIP = "Cảm ơn, đất!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_COOKED = "Cảm ơn, đất!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_EATEN = "Cảm ơn, đất!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_GROUND = "Cảm ơn, đất!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_BIG = "Wee Woo!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "Cảm ơn, đất!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "Cảm ơn, đất!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "Khônggg!"

WORMWOOD.DESCRIBE.KYNO_TURNIP = "Bạn đất nhỏ dễ thương"
WORMWOOD.DESCRIBE.KYNO_TURNIP_COOKED = "Làm bao tử vui"
WORMWOOD.DESCRIBE.KYNO_TURNIP_GROUND = "Bạn đất nhỏ dễ thương"
WORMWOOD.DESCRIBE.KYNO_TURNIP_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "Bạn đất nhỏ dễ thương"
WORMWOOD.DESCRIBE.KYNO_TURNIP_OVERSIZED = "Bạn đất nhỏ dễ thương"
WORMWOOD.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "Khônggg!"

WORMWOOD.DESCRIBE.KYNO_RICE = "Mầm nhỏ"
WORMWOOD.DESCRIBE.KYNO_RICE_COOKED = "Mầm nhỏ"
WORMWOOD.DESCRIBE.KYNO_RICE_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "Hạt làm bạn cam mọc"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_RICE = "Bạn đất nhỏ dễ thương"
WORMWOOD.DESCRIBE.KYNO_RICE_OVERSIZED = "Bạn đất nhỏ dễ thương"
WORMWOOD.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "Khônggg!"

WORMWOOD.DESCRIBE.KYNO_SEEDS_KIT = "Bạn bè bên trong?"

WORMWOOD.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "Đá mọc đồ ăn",
	PICKED = "Ốc đi rồi",
	WITHERED = "Không còn sống",
}

WORMWOOD.DESCRIBE.KYNO_LIMPETS = "Glub Glub đá"
WORMWOOD.DESCRIBE.KYNO_LIMPETS_COOKED = "Vào bao tử"

WORMWOOD.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "Chào!",
	PICKED = "Đang nghỉ",
	BURNING = "Đau!",
}

WORMWOOD.DESCRIBE.KYNO_LOTUS_ROOT = "Cần biển"
WORMWOOD.DESCRIBE.KYNO_LOTUS_FLOWER = "Đồ cho bao tử!"
WORMWOOD.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "Tốt trong bao tử"

WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "Ngon",
	PICKED = "Tạm biến mất?",
	BURNING = "Đau quá!",
}

WORMWOOD.DESCRIBE.KYNO_SEAWEEDS = "Ngon"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_COOKED = "Viên ngon từ biển"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_DRIED = "Biển khô rồi"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_ROOT = "Cần biển"

WORMWOOD.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "Chào bạn!",
	PICKED = "Bạn đang lớn tốt",
	BURNING = "Đau!!",
}

WORMWOOD.DESCRIBE.KYNO_TAROROOT_ROOT = "Cần biển"
WORMWOOD.DESCRIBE.KYNO_TAROROOT = "Mmm... tím"
WORMWOOD.DESCRIBE.KYNO_TAROROOT_COOKED = "Bao tử thích nó"

WORMWOOD.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "Chào",
	PICKED = "Bạn đang ngủ",
	BURNING = "Lửa!!!",
}

WORMWOOD.DESCRIBE.KYNO_WATERYCRESS_ROOT = "Cần biển"
WORMWOOD.DESCRIBE.KYNO_WATERYCRESS = "Chào"

WORMWOOD.DESCRIBE.WATERYCRESSBOWL = "Nước que"

WORMWOOD.DESCRIBE.KYNO_SALT = "Hmm..."

WORMWOOD.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "Que gọi đồ ăn",
	PICKED = "Trống trơn",
	BURNING = "Que đau!",
}

WORMWOOD.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "Que đang bơi!"

WORMWOOD.DESCRIBE.CATFOOD = "Đồ ăn mèo"

WORMWOOD.DESCRIBE.KATFOOD = "Đồ ăn mèo"

WORMWOOD.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "Bạn có tóc ngọt",
	PICKED = "Cần nghỉ",
	CHOPPED = "Bạn đi rồi",
	BURNING = "Bạn đau!",
	BURNT = "Biến mất mãi mãi",
}

WORMWOOD.DESCRIBE.KYNO_BANANA = "Tóc ngọt từ bạn!"
WORMWOOD.DESCRIBE.KYNO_BANANA_COOKED = "Mmm..."

WORMWOOD.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "Tóc đẹp!",
	PICKED = "Bạn cần nghỉ",
	CHOPPED = "Ôi không",
	BURNING = "Bạn đau",
	BURNT = "Bạn đi rồi",
}

WORMWOOD.DESCRIBE.KYNO_KOKONUT = "Bóng đồ ăn"
WORMWOOD.DESCRIBE.KYNO_KOKONUT_HALVED = "Đồ cho bao tử"
WORMWOOD.DESCRIBE.KYNO_KOKONUT_COOKED = "Ấm."

WORMWOOD.DESCRIBE.BOWLOFPOPCORN = "Bốp! Bốp!"

WORMWOOD.DESCRIBE.FIGJUICE = "Nước lạnh tỉnh tỉnh"

WORMWOOD.DESCRIBE.COCONUTWATER = "Nước ngọt"

WORMWOOD.DESCRIBE.EYEBALLSPAGHETTI = "Đồ ăn mắt nhỏ"

WORMWOOD.DESCRIBE.WEED_SEEDS = "Hạt làm bạn cam mọc"

WORMWOOD.DESCRIBE.KYNO_FLOATILIZER = "Phân! Yay!"

WORMWOOD.DESCRIBE.KYNO_TWIGGYNUTS = "Hmmm..."

WORMWOOD.DESCRIBE.KYNO_REPAIRTOOL = "Đồ sửa chữa"

WORMWOOD.DESCRIBE.KYNO_KOI = "Glub Glub đẹp"
WORMWOOD.DESCRIBE.KYNO_KOI_COOKED = "Glub Glub đẹp"

WORMWOOD.DESCRIBE.KYNO_TROPICALFISH = "Glub Glub đẹp"
WORMWOOD.DESCRIBE.KYNO_TROPICALFISH_COOKED = "Glub?"

WORMWOOD.DESCRIBE.KYNO_NEONFISH = "Glub Glub môi to"
WORMWOOD.DESCRIBE.KYNO_NEONFISH_COOKED = "Vây ngon"

WORMWOOD.DESCRIBE.KYNO_GROUPER = "Glub Glub tím"
WORMWOOD.DESCRIBE.KYNO_GROUPER_COOKED = "Không bơi nữa"
 
WORMWOOD.DESCRIBE.KYNO_PIERROTFISH = "Glub Glub"
WORMWOOD.DESCRIBE.KYNO_PIERROTFISH_COOKED = "Glub Glub cho bao tử"

WORMWOOD.DESCRIBE.KYNO_SALMONFISH = "Glub Glub từ đất"
WORMWOOD.DESCRIBE.KYNO_SALMONFISH_COOKED = "Glub Glub cho bao tử"

WORMWOOD.DESCRIBE.TURF_PINKPARK = "Hồng"
WORMWOOD.DESCRIBE.TURF_STONECITY = "Không phải đất"
WORMWOOD.DESCRIBE.TURF_FIELDS = "Đất"
WORMWOOD.DESCRIBE.TURF_TIDALMARSH = "Đất mềm"

WORMWOOD.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "Xong!",
	PICKED = "Đang lấy đá ngon",
}

WORMWOOD.DESCRIBE.KYNO_SALTRACK_INSTALLER = "Lấy đá ngon"

WORMWOOD.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "Thứ kim loại xấu tính"

WORMWOOD.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "Nhà tù kẹp đất"

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "Đuôi xoắn tay quấn",
	SLEEPING = "Đang ngủ",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "Bạn ngọt!",
	CHOPPED = "Xin lỗi!",
	SAPPED = "Đầy ruột ngọt của bạn",
	PICKED = "Ôi, bạn. Xin lỗi",
	BURNING = "Đau quá!",
	BURNT = "Biến mất...",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "Ái! Bạn đau",
	CHOPPED = "Biến mất",
	SAPPED = "Nước xấu",
	PICKED = "Bọ làm bạn đau!",
	BURNING = "Đau",
	BURNT = "Biến mất mãi mãi",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_BUD = "Vào bao tử? Hay xuống đất?"

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_FLOWER = "Bạn!"
WORMWOOD.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "Bạn!"

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_PETALS = "Bạn!"
WORMWOOD.DESCRIBE.KYNO_SUGARTREE_PETALS_DRIED = "Bạn ổn chứ?"

WORMWOOD.DESCRIBE.KYNO_PEBBLECRAB = "Kẹp đất!"

WORMWOOD.DESCRIBE.KYNO_CRABMEAT = "Cành từ kẹp đất"
WORMWOOD.DESCRIBE.KYNO_CRABMEAT_COOKED = "Kẹp đất làm đồ ngon"
WORMWOOD.DESCRIBE.KYNO_CRABMEAT_DRIED = "Cành từ kẹp đất"

WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT = "Cành từ kẹp đất"
WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "Cành từ kẹp đất"
WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "Cành từ kẹp đất"

WORMWOOD.DESCRIBE.KYNO_SLAUGHTERTOOL = "Thứ xấu tính"

WORMWOOD.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "Cục tác!",
	COOP = "Cục tác an toàn rồi",
}

WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG = "Cục tác bé"
WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "Cục tác to bên trong?"
WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "Vào bao tử"

WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG_LARGE_CRACKED =
{
	GENERIC = "Cục tác vẫn đang ngủ?",
	HATCHING = "Cục tác đang tới!",
}

WORMWOOD.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "Nhà cục tác",
	FULL = "Trứng sẵn sàng!",
	BURNT = "Cục tác đi rồi?",
}

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "Hỏng rồi"

WORMWOOD.DESCRIBE.KYNO_COOKWARE_KIT = "Hộp gỗ"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SYRUP = "Làm nước ngọt sủi sủi"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "Làm nước ngọt sủi sủi"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_BIG_POT = "Hoo! Làm nước sôi ùng ục!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_BIG = "Hoo! Làm nước sôi ùng ục!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "Hoo! Làm nước sôi ùng ục!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL = "Hoo! Làm nước sôi ùng ục!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_GRILL = "Thanh nóng!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "Cần lửa"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "Thanh nóng bé xíu"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "Cần lửa"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_ELDER = "Làm nước ngọt sủi sủi"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "Làm đồ ăn nóng lên"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "Làm đồ ăn đẹp hơn"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "Đặt đồ ăn ở đây"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN = "Cho đồ ăn tắm lửa"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "Cho đồ ăn tắm lửa"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "Cho đồ ăn tắm lửa"

WORMWOOD.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "Có gì trốn dưới đó?",
	FLIPPED = "Tìm thấy rồi",
}

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "Gỗ đang chìm!"

WORMWOOD.DESCRIBE.KYNO_SUGARFLY = "Bạn cho bạn bè"
WORMWOOD.DESCRIBE.KYNO_SUGARFLYWINGS = "Không bay được nữa"

WORMWOOD.DESCRIBE.KYNO_WATERY_CRATE = "Gỗ đang chìm!"

WORMWOOD.DESCRIBE.KYNO_TUNACAN = "Có Glub Glub bên trong?"
WORMWOOD.DESCRIBE.KYNO_TUNACAN_OPEN = "Glub Glub chết rồi"

WORMWOOD.DESCRIBE.KYNO_CANNEDFOOD = "Có đồ ăn bên trong?"
WORMWOOD.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "Ngon"

WORMWOOD.DESCRIBE.KYNO_POP = "Psht"

WORMWOOD.DESCRIBE.KYNO_MYSTERYMEAT = "Hmm... là gì vậy?"

WORMWOOD.DESCRIBE.KYNO_BOTTLE_SOUL = "Hmm..."

WORMWOOD.DESCRIBE.SOULSTEW = "Hmm..."

WORMWOOD.DESCRIBE.FORTUNECOOKIE = "Đồ ăn kỳ lạ"

WORMWOOD.DESCRIBE.HORNOCUPIA = "Nhiều đồ ăn"

WORMWOOD.DESCRIBE.CHEESE_YELLOW = "Đồ ăn hôi hôi"
WORMWOOD.DESCRIBE.CHEESE_WHITE = "Đồ ăn hôi hôi"
WORMWOOD.DESCRIBE.CHEESE_KOALEFANT = "Đồ ăn hôi hôi"

WORMWOOD.DESCRIBE.MILK_BOX = "Cho bao tử?"

WORMWOOD.DESCRIBE.WATERCUP = "Nước"

WORMWOOD.DESCRIBE.HONEYJAR = "Đồ ngọt cho bao tử"

WORMWOOD.DESCRIBE.CRAB_ARTICHOKE = "Đá nhỏ đi đâu rồi?"

WORMWOOD.DESCRIBE.PEPPERROLLS = "Miếng ngon"

WORMWOOD.DESCRIBE.KYNO_SAPHEALER = "Đồ chữa bệnh"

WORMWOOD.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "Cứu gỗ!",
	PICKED = "Đang chờ",
	BURNING = "Đau",
}

WORMWOOD.DESCRIBE.KYNO_GHOST_PIRATE = "Người bay bay"

WORMWOOD.DESCRIBE.KYNO_BUCKET_EMPTY = "Thứ bằng gỗ"
WORMWOOD.DESCRIBE.KYNO_BUCKET_METAL = "Thứ bằng kim loại"
WORMWOOD.DESCRIBE.KYNO_BUCKET_WATER = "Nước cho bạn bè"

WORMWOOD.DESCRIBE.KYNO_MILK_BEEFALO = "Moo Moo?"
WORMWOOD.DESCRIBE.KYNO_MILK_KOALEFANT = "Moo Moo?"

WORMWOOD.DESCRIBE.KYNO_CAP_DRIED = "Đồ ăn"

WORMWOOD.DESCRIBE.KYNO_PLANTMEAT_DRIED = "Đồ ăn khô queo"

WORMWOOD.DESCRIBE.KYNO_BREWBOOK = "Sách đồ uống"

WORMWOOD.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "Hộp gỗ?",
	BREWING_LONG = "Đang làm",
	BREWING_SHORT = "Sắp xong?",
	DONE = "Xong rồi!",
	BURNT = "Biến mất",
}

WORMWOOD.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "Hộp gỗ?",
	BREWING_LONG = "Đang làm",
	BREWING_SHORT = "Sắp xong?",
	DONE = "Xong rồi!",
	BURNT = "Biến mất",
}

WORMWOOD.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "Nước vo ve! Vo ve đâu rồi?",
	HONEY = "Đồ ngọt!",
	NECTAR = "Chưa xong",
	BURNING = "Đau!",
}

WORMWOOD.DESCRIBE.KYNO_NECTAR_POD = "Ngọt!"

WORMWOOD.DESCRIBE.KYNO_OAKTREE_POD = "Chào"
WORMWOOD.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "Giờ không xuống đất được nữa"

WORMWOOD.DESCRIBE.KYNO_PIKO = "Bạn lông xù hay chôm đồ"
WORMWOOD.DESCRIBE.KYNO_PIKO_ORANGE = "Bạn lông xù hay chôm đồ"

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "Đang ngủ?",
	CHOPPED = "Bạn cho vài mảnh tóc",
	BURNING = "Đau!",
	BURNT = "Biến mất",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "Ngủ cùng bạn bè?",
	BURNING = "Đau!",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "Bạn gỗ làm thành hộp!"

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "Nhà của người Glub Glub",
	BURNT = "Nhà người Glub Glub mất rồi",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "Nhà của người Glub Glub",
	CRAFTED = "Nhà tốt hơn rồi",
	BURNT = "Mùi xấu",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "Có nhiều đồ bên trong",
	OCCUPIED = "Đang ngủ?",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "Đồ đạc",
	EMPTY = "Không có gì",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "Chào!"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_POND = "Nhà cho Glub Glub"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "Chào, bạn nhỏ"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "Đống đất"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "Người Glub Glub"

WORMWOOD.DESCRIBE.KYNO_SAMMYHAT = "Bụi bụi"

WORMWOOD.DESCRIBE.KINGFISHER = "Chim mỏ chọc"

WORMWOOD.DESCRIBE.TOUCAN = "Chim mỏ to"
WORMWOOD.DESCRIBE.TOUCAN_CHUBBY = "Chim mỏ to"

WORMWOOD.DESCRIBE.WETGOOP2 = "Ngon"

WORMWOOD.DESCRIBE.BEER = "Vị lạ lạ"

WORMWOOD.DESCRIBE.PALEALE = "Vị lạ lạ"

WORMWOOD.DESCRIBE.TEAGREEN = "Mmmm... Ahh"

WORMWOOD.DESCRIBE.TEARED = "Mmmm... Ahh"

WORMWOOD.DESCRIBE.MEAD = "Đồ ngọt cho bao tử"

WORMWOOD.DESCRIBE.KYNO_JELLY = "Đồ ngọt cho bao tử"

WORMWOOD.DESCRIBE.KYNO_MAYONNAISE = "Mmm..."

WORMWOOD.DESCRIBE.TARTARSAUCE = "Đồ cay cho bao tử"

WORMWOOD.DESCRIBE.KYNO_PICKLES = "Đồ ăn"

WORMWOOD.DESCRIBE.KYNO_WINE = "Nước đắng"

WORMWOOD.DESCRIBE.KYNO_JUICE = "Đồ ngọt cho bao tử"

WORMWOOD.DESCRIBE.KYNO_POISON_FROGLEGS = "Có chân"
WORMWOOD.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "(ngửi, ngửi) Mùi ổn"

WORMWOOD.DESCRIBE.POISONFROGGLEBUNWICH = "Làm đầy bao tử"

WORMWOOD.DESCRIBE.KYNO_BREWINGRECIPECARD = "Hmmm. Không tốt"

WORMWOOD.DESCRIBE.KYNO_OIL = "Cho bao tử?"

WORMWOOD.DESCRIBE.BERRYSUNDAE = "Mát lạnh"

WORMWOOD.DESCRIBE.CHOCOLATE_BLACK = "Ngọt!"
WORMWOOD.DESCRIBE.CHOCOLATE_WHITE = "Ngọt!"

WORMWOOD.DESCRIBE.TRICOLORDANGO = "Ngọt"
 
WORMWOOD.DESCRIBE.FRIESFRENCH = "Giòn"

WORMWOOD.DESCRIBE.PIRATERUM = "Xấu xa?"

WORMWOOD.DESCRIBE.TWISTEDTEQUILA = "Cho bao tử?"

WORMWOOD.DESCRIBE.ONIONRINGS = "Hành giòn"

WORMWOOD.DESCRIBE.DONUTS = "Đồ ngọt cho bao tử"
WORMWOOD.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "Đồ ngọt cho bao tử"
WORMWOOD.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "Đồ ngọt cho bao tử"
 
WORMWOOD.DESCRIBE.CINNAMONROLL = "Đồ ăn"

WORMWOOD.DESCRIBE.GUMMYBEARGERS = "Kỳ lạ"

WORMWOOD.DESCRIBE.PRETZEL = "Đồ ăn"

WORMWOOD.DESCRIBE.CORNINCUP = "Tốt cho bao tử"

WORMWOOD.DESCRIBE.COTTONCANDY = "Không khí?"

WORMWOOD.DESCRIBE.ROASTEDHAZELNUTS = "Hạt!"

WORMWOOD.DESCRIBE.MONSTERMUFFIN = "Đồ ăn kỳ lạ"

WORMWOOD.DESCRIBE.PINKCAKE = "Đồ ngọt cho bao tử"

WORMWOOD.DESCRIBE.CHIPSBAG = "Đồ ăn"

WORMWOOD.DESCRIBE.LITTLEBREAD = "Mềm xốp"

WORMWOOD.DESCRIBE.HOTHOUND = "Chó đâu?"

WORMWOOD.DESCRIBE.MILKSHAKE = "Lắc!"
WORMWOOD.DESCRIBE.MILKSHAKE_PRISMATIC = "Lắc!"

WORMWOOD.DESCRIBE.NACHOS = "Phô mai"

WORMWOOD.DESCRIBE.BANANA_PUDDING = "Chuối"

WORMWOOD.DESCRIBE.SEA_PUDDING = "Cá?"

WORMWOOD.DESCRIBE.TOM_KHA_SOUP = "Rau củ"

WORMWOOD.DESCRIBE.MINERTREAT = "Kỳ lạ"

WORMWOOD.DESCRIBE.RADISHSALAD = "Muốn ăn nó"

WORMWOOD.DESCRIBE.PUMPKIN_SOUP = "Món nước cho bao tử"

WORMWOOD.DESCRIBE.ALGAE_SOUP = "Món nước cho bao tử"

WORMWOOD.DESCRIBE.PARZNIP_SOUP = "Món nước cho bao tử"

WORMWOOD.DESCRIBE.NETTLEMEATED = "Mmmm..."

WORMWOOD.DESCRIBE.KYNO_SUGAR = "Bột ngọt"

WORMWOOD.DESCRIBE.KYNO_BOTTLECAP = "Nắp"

WORMWOOD.DESCRIBE.NUKACOLA = "Tê tê"
WORMWOOD.DESCRIBE.NUKACOLA_QUANTUM = "Tê tê"

WORMWOOD.DESCRIBE.LIVINGSANDWICH = "Bánh kỳ lạ"

WORMWOOD.DESCRIBE.DURIANSPLIT = "Mát lạnh"

WORMWOOD.DESCRIBE.DURIANSOUP = "Nước sầu riêng ngọ nguậy"

WORMWOOD.DESCRIBE.DURIANMEATED = "Đồ ăn hôi hôi"

WORMWOOD.DESCRIBE.DURIANCHICKEN = "Đồ ăn"

WORMWOOD.DESCRIBE.LUNARSOUP = "Trăng!"

WORMWOOD.DESCRIBE.PURPLEWOBSTERSOUP = "Wobster tội nghiệp"

WORMWOOD.DESCRIBE.WOBSTERMONSTER = "Quái vật"

WORMWOOD.DESCRIBE.SPIDERCAKE = "Bánh nhện"

WORMWOOD.DESCRIBE.SUGARBOMBS = "Bùm"

WORMWOOD.DESCRIBE.BERRYBOMBS = "Đồ ngọt cho bao tử"

WORMWOOD.DESCRIBE.ONIGIRIS = "Hạt"

WORMWOOD.DESCRIBE.OMURICE = "Hạt chiên"

WORMWOOD.DESCRIBE.PAELLA = "Hạt!"

WORMWOOD.DESCRIBE.RISOTTO = "Hạt với bạn bè"

WORMWOOD.DESCRIBE.RICESAKE = "Nước hạt?"

WORMWOOD.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "Bạn cần đất"

WORMWOOD.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "Chào bạn!",
	PICKED = "Gai bạn đâu rồi?",
	WITHERED = "Khô quá",
	BURNING = "Bạn đau!",
}

WORMWOOD.DESCRIBE.KYNO_PINEAPPLE = "Có gai"
WORMWOOD.DESCRIBE.KYNO_PINEAPPLE_HALVED = "Cho bao tử"
WORMWOOD.DESCRIBE.KYNO_PINEAPPLE_COOKED = "Cho bao tử"

WORMWOOD.DESCRIBE.PIZZA_TROPICAL = "Bạn?"

WORMWOOD.DESCRIBE.PINACOLADA = "Bạn?"

WORMWOOD.DESCRIBE.CHIMAS = "Cỏ?"

WORMWOOD.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "Giúp bạn bè",
	ON = "Bạn bè vui với thứ kim loại bắn nước",
}

WORMWOOD.DESCRIBE.KYNO_FOODSACK = "Giữ đồ ăn tươi"

WORMWOOD.DESCRIBE.GUMMYWORMS = "Sâu?"

WORMWOOD.DESCRIBE.SMORES = "Sô-cô-la?"

WORMWOOD.DESCRIBE.NUKASHINE = "Đồ uống kỳ lạ"

WORMWOOD.DESCRIBE.ANTSLOG = "Có gỗ"

WORMWOOD.DESCRIBE.KYNO_WORM_BONE = "Ôi"

WORMWOOD.DESCRIBE.SPOOKY_BRAIN_NOODLES = "Tâm trí?"
WORMWOOD.DESCRIBE.SPOOKY_BURGERZILLA = "Quái vật!"
WORMWOOD.DESCRIBE.SPOOKY_DEADBREAD = "Mềm xốp"
WORMWOOD.DESCRIBE.SPOOKY_JELLYBEANS = "Rợn rợn"
WORMWOOD.DESCRIBE.SPOOKY_POPSICLE = "Ngon"
WORMWOOD.DESCRIBE.SPOOKY_PUMPKINCREAM = "Bạn có mùi?"
WORMWOOD.DESCRIBE.SPOOKY_SKULLCANDY = "Đáng sợ"
WORMWOOD.DESCRIBE.SPOOKY_TACODILE = "Bạn?"

WORMWOOD.DESCRIBE.BUTTER_BEEFALO = "Nhớt"
WORMWOOD.DESCRIBE.BUTTER_GOAT = "Nhớt?"
WORMWOOD.DESCRIBE.BUTTER_KOALEFANT = "Nhớt!"

WORMWOOD.DESCRIBE.SPICE_CURE = "Giữ đồ ăn an toàn"
WORMWOOD.DESCRIBE.SPICE_COLD = "Lạnh!"
WORMWOOD.DESCRIBE.SPICE_FIRE = "Cháy!"
WORMWOOD.DESCRIBE.SPICE_FED = "Đói"
WORMWOOD.DESCRIBE.SPICE_MIND = "Buồn ngủ"

WORMWOOD.DESCRIBE.SUGARFLYMUFFIN = "Ngonnn..."

WORMWOOD.DESCRIBE.EELTACOS = "Cho bao tử"

WORMWOOD.DESCRIBE.MEATSKILLET = "Cho bao tử!"

WORMWOOD.DESCRIBE.MEATWALTZ = "Cho bao tử?"

WORMWOOD.DESCRIBE.COMPLETEBREAKFAST = "Bữa to cho bao tử"

WORMWOOD.DESCRIBE.DUMPLINGS = "Đồ ăn"

WORMWOOD.DESCRIBE.WARLYICEDTEA = "Nước lạnh tỉnh tỉnh"

WORMWOOD.DESCRIBE.WARLYTEA = "Nước ấm tỉnh tỉnh"

WORMWOOD.DESCRIBE.KYNO_TEALEAF = "Bạn ấm áp"

WORMWOOD.DESCRIBE.KYNO_ITEMSLICER = "Dao cắt. Cắt tóc cho bạn"
WORMWOOD.DESCRIBE.KYNO_ITEMSLICER_GOLD = "Dao cắt. Cắt tóc cho bạn"

WORMWOOD.DESCRIBE.COXINHA = "Đồ ăn"

WORMWOOD.DESCRIBE.LAZYDESSERT = "Đá cứng"

WORMWOOD.DESCRIBE.CRABKINGFEAST = "Khổng lồ!"

WORMWOOD.DESCRIBE.PIENAPPLE = "Bạn có tóc gai!"

WORMWOOD.DESCRIBE.JAWSBREAKER = "Cứng ghê"

WORMWOOD.DESCRIBE.AVOCADOTOAST = "Ngon"

WORMWOOD.DESCRIBE.RICEPUDDING = "Trộn mềm"

WORMWOOD.DESCRIBE.SHARKSUSHI = "Đồ ăn"

WORMWOOD.DESCRIBE.WOBSTERBREADED = "Glub Glub kẹp kẹp chiên giòn"

WORMWOOD.DESCRIBE.LAZYPURRITO = "Mèo ngốc"

WORMWOOD.DESCRIBE.HORCHATA = "Lạnh!"

WORMWOOD.DESCRIBE.WOBSTERCOCKTAIL = "Glub Glub rực lửa"

WORMWOOD.DESCRIBE.LAVAEEGGBOILED = "Nóng!"

WORMWOOD.DESCRIBE.POMEGRANATETEA = "Nước lạnh tỉnh tỉnh"

WORMWOOD.DESCRIBE.TIRAMISU = "Bíp! Bíp!"

WORMWOOD.DESCRIBE.TOADSTOOLCOLA = "Psht hôi hôi"

WORMWOOD.DESCRIBE.TEPACHE = "Nước ngọt từ bạn"

WORMWOOD.DESCRIBE.LUNARTEQUILA = "Đồ trăng?"

WORMWOOD.DESCRIBE.MIMICMOSA = "Nước mắt tối"

WORMWOOD.DESCRIBE.POMEGRANATEPIE = "Đồ đỏ cho bao tử"

WORMWOOD.DESCRIBE.PINEAPPLECAKE = "Đồ ăn"

WORMWOOD.DESCRIBE.PASTY_MEAT = "Giòn"
WORMWOOD.DESCRIBE.PASTY_CHEESE = "Giòn"

WORMWOOD.DESCRIBE.BRIGADEIRO = "Vụn ngọt"

WORMWOOD.DESCRIBE.REGULARLASAGNA = "Cho bao tử"

WORMWOOD.DESCRIBE.FLTSANDWICH = "Ếch nhỏ"

WORMWOOD.DESCRIBE.RICEANDBEANS = "Đồ ăn"

WORMWOOD.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP =
{
	GENERIC = "Nhà Hỏng",
	REPAIRED = "Nhà Tốt Hơn",
	OCCUPIED = "Bạn Heo Ngủ",
	OCCUPIED_REPAIRED = "Bạn Heo An Toàn",
}

WORMWOOD.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "Bạn mọc trong đất!",
	PICKED = "Biến mất rồi",
	BURNING = "Bạn đau!",
}

WORMWOOD.DESCRIBE.KYNO_TRUFFLES = "Đồ ăn có mùi của bạn."
WORMWOOD.DESCRIBE.KYNO_TRUFFLES_COOKED = "Đồ ăn ấm của bạn!"

WORMWOOD.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "Cho bạn bè xem đồ ăn",
	FULL = "Đồ ăn trông đẹp",
}

WORMWOOD.DESCRIBE.KYNO_SPORECAP = "Bạn? Bạn bị bệnh..."
WORMWOOD.DESCRIBE.KYNO_SPORECAP_COOKED = "Bạn nóng! Đỡ hơn chưa?"

WORMWOOD.DESCRIBE.KYNO_SPORECAP_DARK = "Bạn làm đau bạn khác"
WORMWOOD.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "Vẫn làm đau bạn"

WORMWOOD.DESCRIBE.KYNO_GOLDENAPPLE = "Lấp lánh!"

WORMWOOD.DESCRIBE.TRUFFLESGRINDER = "Ngon! Mùi đất!"

WORMWOOD.DESCRIBE.SPORECAPPIE = "Bánh nấm"

WORMWOOD.DESCRIBE.SPORECAP_SKEWERS = "Bạn xấu... giờ ngon rồi!"

WORMWOOD.DESCRIBE.TRUFFLEOIL = "Mùi mạnh"

WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "Kế hoạch làm hồ"
WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "Nhà nước đang lớn!"

WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "Nhà Glub Glub",
	FUEL_HIGH = "Glub Glub vui!",
	FUEL_MED = "Glub Glub đang ăn",
	FUEL_LOW = "Sắp cần đồ ăn vặt",
	EMPTY = "Hết đồ ăn vặt",
}

WORMWOOD.DESCRIBE.AGEDROE = "Glub Glub con bị nhốt?"
WORMWOOD.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "Glub Glub con"

WORMWOOD.DESCRIBE.KYNO_SWORDFISH_BLUE = "Bơi không giỏi?"

WORMWOOD.DESCRIBE.KYNO_JELLYFISH = "Cục Glub Glub"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_DEAD = "Cục tội nghiệp"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_COOKED = "Vòng cục"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_DRIED = "Cục dai"

WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "Cục Glub Glub đẹp"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "Không phồng nữa"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "Vòng đẹp"

WORMWOOD.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "Aw. Không có gì bên trong."

WORMWOOD.DESCRIBE.KYNO_OCEANTRAP = "Bẫy ướt"

WORMWOOD.DESCRIBE.OCEANFISH_MIDNIGHT_CARP = "Glub Glub đêm"
WORMWOOD.DESCRIBE.OCEANFISH_PUFFERFISH = "Glub Glub gai"
WORMWOOD.DESCRIBE.OCEANFISH_STURGEON = "Glub Glub già"

WORMWOOD.DESCRIBE.KYNO_SWORDFISH = "Glub Glub mũi sắc"
WORMWOOD.DESCRIBE.KYNO_SWORDFISH_DEAD = "(nức nở)"

WORMWOOD.DESCRIBE.SWORDFISHFEAST = "Glub Glub sang"

WORMWOOD.DESCRIBE.KYNO_DOGFISH = "Glub Glub gâu gâu"
WORMWOOD.DESCRIBE.KYNO_DOGFISH_DEAD = "Chào, Glub Glub"

WORMWOOD.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "Mùi thơm. Mmmmm."

WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND = "Bạn nước lấp lánh!"
WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "Không còn lấp lánh động đậy..."
WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "Bạn?"

WORMWOOD.DESCRIBE.KYNO_PUFFERMONSTER = "Cá gai! Đừng chọc bạn!"

WORMWOOD.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "Glub Glub hay Barrooooo?"
WORMWOOD.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "Barrooooo!"
WORMWOOD.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "Barrooooo nhợt nhạt"
WORMWOOD.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "Tooooooo!"

WORMWOOD.DESCRIBE.KYNO_BLUBBER = "Mềm nhũn"

WORMWOOD.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "Glub Glub khô, mmm!"
WORMWOOD.DESCRIBE.KYNO_FISHMEAT_DRIED = "Glub Glub khô"

WORMWOOD.DESCRIBE.MONKEYISLANDMEAL = "Glub Glub và bạn"

WORMWOOD.DESCRIBE.KYNO_BRAINROCK_LARVAE = "Cần đá"
WORMWOOD.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "Đá ướt bé dễ thương"
WORMWOOD.DESCRIBE.KYNO_BRAINROCK_CORAL = "Đang nghĩ..."

WORMWOOD.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "Đá biết nghĩ",
	PICKED = "Đá biết nghĩ mệt rồi",
}

WORMWOOD.DESCRIBE.BRAINMETTERSOUP = "Món suy nghĩ cho bao tử"

WORMWOOD.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "Người nhiều tay",
	SLEEPING = "Đang ngủ",
}

WORMWOOD.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "Đồ từ người nhiều tay!"

WORMWOOD.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "Bạn chim thích bạn!",
	WAITING = "Bạn chim đâu rồi?",
}

WORMWOOD.DESCRIBE.KYNO_PACKIMBAGGIMS = "Bạn chim"

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "Cần đồ"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "Cần thêm đồ"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "Nó tooooo!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "Ánh sáng cho bánh tooo"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "Bạn bè..."
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "Đồ ngọt cho bao tử!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "Bạn bay bay! Chào!"

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "Máy làm bốp",
	FUEL_HIGH = "Máy làm bốp vui",
	FUEL_MED = "Đang làm",
	FUEL_LOW = "Máy làm bốp đói rồi",
	EMPTY = "Trống trơn",
}

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "Bốp bốp"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "Mũ tiệc! Whee!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "Mũ bạn!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_PARTITIOHAT = "Mũ bạn!"

WORMWOOD.DESCRIBE.KYNO_FISHREGISTRYHAT = "Mũ biết cá"

WORMWOOD.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "Chỗ để đồ ăn",
	FUEL_HIGH = "Nhiều đồ ăn",
	FUEL_MED = "Có ít đồ ăn",
	FUEL_LOW = "Ít đồ ăn",
	EMPTY = "Không có đồ ăn",
	BURNT = "Biến mất",
}

WORMWOOD.DESCRIBE.CHICKENNUGGETS = "Miếng cục tác"

WORMWOOD.DESCRIBE.CHICKENWINGS = "Đau bao tử"

WORMWOOD.DESCRIBE.CHICKENBURGER = "Cục tác ôm bánh."

WORMWOOD.DESCRIBE.CHICKENEGGSOUP = "Nước trứng ấm."

WORMWOOD.DESCRIBE.CHICKENEGGSTEW = "Cục tác tắm"

WORMWOOD.DESCRIBE.CHICKENROTISSERIE = "Cục tác nóng"

WORMWOOD.DESCRIBE.KYNO_HERMITCRABTEA_ALOE = "Nước ấm"
WORMWOOD.DESCRIBE.KYNO_HERMITCRABTEA_SUGARTREE_PETALS = "Nước ngọt"
WORMWOOD.DESCRIBE.KYNO_HERMITCRABTEA_ICENETTLES = "Cold Water" -- NEEDS TRANSLATION

WORMWOOD.DESCRIBE.SOULJUICE = "Nước linh hồn"

WORMWOOD.DESCRIBE.KYNO_DAILYRECIPE = "Món hôm nay là %s"
WORMWOOD.DESCRIBE.KYNO_DAILYRECIPE_SIGN =
{
	GENERIC = "Món hôm nay là %s",
	NONE = "Hôm nay không có món",
	BURNING = "Nóng nóng nóng!",
	BURNT = "Hết sạch",
}

WORMWOOD.DESCRIBE.KYNO_DECIDUOUSFOREST_SELLER =
{
	GENERIC = "Nhà Đau. Muốn Giúp Trước.",
	HOUSE_REPAIRED = "Giờ Giao Dịch, Đúng Không?",
}

WORMWOOD.DESCRIBE.KYNO_CAVETUBERTREE =
{
	GENERIC = "Bạn Kỳ Lạ",
	CHOPPED = "Bạn Biến Mất",
	BLOOMING = "Bạn Vui!",
	BURNING = "Không! Lửa Xấu!",
	BURNT = "Bạn đau...",
}

WORMWOOD.DESCRIBE.KYNO_CAVETUBER = "Chưa Sẵn Sàng"
WORMWOOD.DESCRIBE.KYNO_CAVETUBER_COOKED = "Giờ Tốt Rồi"

WORMWOOD.DESCRIBE.KYNO_CAVETUBER_BLOOMING = "Sẵn Sàng!"
WORMWOOD.DESCRIBE.KYNO_CAVETUBER_BLOOMING_COOKED = "Xin Chào Bạn Hoa!"

WORMWOOD.DESCRIBE.CAVETUBERTEA = "Đồ Uống Rễ Lạnh"

WORMWOOD.DESCRIBE.KYNO_ELDERMANDRAKEHOUSE =
{
	GENERIC = "Xin chào? Có ai không?",
	OCCUPIED = "Đang ngủ?",
}

WORMWOOD.DESCRIBE.KYNO_ELDERMANDRAKE =
{
	GENERIC = "Hay La Hét",
	GRUMPY = "Cáu Kỉnh",
}

WORMWOOD.DESCRIBE.MANDRAKEBAOBUNS = "Bạn Ồn Ào Trong Bánh"

WORMWOOD.DESCRIBE.MANDRAKEPIE = "Bánh Có Bạn Ồn Ào"

WORMWOOD.DESCRIBE.MANDRAKEBEER = "Nước Uống Ngọt"

WORMWOOD.DESCRIBE.RAINPARFAIT = "Món Ngon Từ Bầu Trời Ướt"

WORMWOOD.DESCRIBE.MIDNIGHTFEAST = "Đồ ăn ban đêm"

WORMWOOD.DESCRIBE.KYNO_PLANTBOOSTER_GROWTH = "Làm Bạn Bè Vui Vẻ"
WORMWOOD.DESCRIBE.KYNO_PLANTBOOSTER_VITALITY = "Giữ Bạn Bè Khỏe Mạnh"
WORMWOOD.DESCRIBE.KYNO_PLANTBOOSTER_YIELD = "Bạn Bè Tặng Nhiều Quà Hơn"
WORMWOOD.DESCRIBE.KYNO_PLANTBOOSTER_SUPERGROWTH = "Lớn Lên Thật Nhiều Và Thật Nhanh!"

WORMWOOD.DESCRIBE.KYNO_PIGCOIN1 = "Đĩa để tiêu"
WORMWOOD.DESCRIBE.KYNO_PIGCOIN2 = "Đuôi xoáy nói \"Làm tốt!\""
WORMWOOD.DESCRIBE.KYNO_PIGCOIN3 = "Đĩa tiêu xịn to!"

WORMWOOD.DESCRIBE.KYNO_ICENETTLES = " Cold Cold Friend" -- NEEDS TRANSLATION
WORMWOOD.DESCRIBE.KYNO_ICENETTLES_DRIED = "Cold Withery Friend" -- NEEDS TRANSLATION

WORMWOOD.DESCRIBE.KYNO_SEEDSBAG = -- NEEDS TRANSLATION
{
	GENERIC = "Seeds Home",
	FULL = "Full",
}