local WX78 = STRINGS.CHARACTERS.WX78

WX78.ANNOUNCE_KYNO_COFFEEBUFF_START = "TỐC ĐỘ DI CHUYỂN: MỨC CAO"
WX78.ANNOUNCE_KYNO_COFFEEBUFF_END = "TỐC ĐỘ DI CHUYỂN: ĐÃ BÌNH THƯỜNG HÓA"

WX78.ANNOUNCE_KYNO_HASTEBUFF_START = "TỐC ĐỘ CHUYỂN ĐỘNG TAY: HIỆU SUẤT TỐI ĐA"
WX78.ANNOUNCE_KYNO_HASTEBUFF_END = "TỐC ĐỘ THAO TÁC NHẤP ĐÃ TRỞ VỀ MỨC BÌNH THƯỜNG"

WX78.ANNOUNCE_KYNO_POPBUFF_START = "(ỢỢỢ) CÁI QUÁI...?"
WX78.ANNOUNCE_KYNO_POPBUFF_END = "HIỆU ỨNG SỦI BỌT ĐÃ BỊ XÓA"

WX78.ANNOUNCE_KYNO_FROGBUFF_START = "CƠ CHẾ ẾCH: ĐÃ GẮN"
WX78.ANNOUNCE_KYNO_FROGBUFF_END = "CƠ CHẾ ẾCH: ĐÃ THÁO"

WX78.ANNOUNCE_KYNO_PIRATEBUFF_START = "(ỢỢỢ) SẴN SÀNG LÊN ĐƯỜNG!"
WX78.ANNOUNCE_KYNO_PIRATEBUFF_END = "HIỆU ỨNG ĐIỀU HƯỚNG ĐÃ BỊ XÓA"

WX78.ANNOUNCE_KYNO_FREEZEBUFF_START = "CẢNH BÁO: HỆ THỐNG LÕI ĐANG HẠ NHIỆT"
WX78.ANNOUNCE_KYNO_FREEZEBUFF_END = "HỆ THỐNG LÕI ĐÃ TRỞ LẠI CHU TRÌNH BÌNH THƯỜNG"

WX78.ANNOUNCE_KYNO_FIREBUFF_START = "CẢNH BÁO: HỆ THỐNG LÕI ĐANG TĂNG NHIỆT"
WX78.ANNOUNCE_KYNO_FIREBUFF_END = "HỆ THỐNG LÕI ĐÃ TRỞ LẠI CHU TRÌNH BÌNH THƯỜNG"

WX78.ANNOUNCE_KYNO_FISHINGBUFF_START = "ĐÃ NUỐT CÁ CHƯA?"
WX78.ANNOUNCE_KYNO_FISHINGBUFF_END = "CẢNH BÁO: PHỤ KIỆN CÂU CÁ ĐÃ TẮT"

WX78.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "ĐANG GIẢM HOẠT ĐỘNG DỊCH VỤ ĐÁM MÂY"
WX78.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "DỊCH VỤ ĐÁM MÂY ĐÃ TRỞ LẠI BÌNH THƯỜNG"

WX78.ANNOUNCE_KYNO_EATERBUFF_START = "HỆ THỐNG TIÊU HÓA ĐÃ ĐƯỢC TĂNG CƯỜNG"
WX78.ANNOUNCE_KYNO_EATERBUFF_END = "HỆ THỐNG TIÊU HÓA ĐÃ TRỞ LẠI CHU TRÌNH BÌNH THƯỜNG"

WX78.ANNOUNCE_KYNO_WORMBUFF_START = "HỆ THỐNG SẴN SÀNG XỬ LÝ LŨ SÂU"
WX78.ANNOUNCE_KYNO_WORMBUFF_END = "HỆ THỐNG QUÁ HẠN: ĐANG TẮT MÔ-ĐUN TẤN CÔNG SÂU"

WX78.ANNOUNCE_KYNO_CRABBUFF_START = "HỆ THỐNG SẴN SÀNG XỬ LÝ LŨ CUA"
WX78.ANNOUNCE_KYNO_CRABBUFF_END = "HỆ THỐNG QUÁ HẠN: ĐANG TẮT MÔ-ĐUN TẤN CÔNG CUA"

WX78.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(ỢỢỢ) CÁI QUÁI...?"
WX78.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "HIỆU ỨNG SỦI BỌT ĐÃ BỊ XÓA"

WX78.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "AAAHH! MẶT TRĂNG! ĐÚNG RỒI!!"
WX78.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "KHÔNGGGG! SỨC MẠNH CỦA TA! TRẢ LẠI ĐÂY!"

WX78.ANNOUNCE_KYNO_STEALTHBUFF_START = "MÔ-ĐUN NGỤY TRANG HỆ THỐNG: BẬT"
WX78.ANNOUNCE_KYNO_STEALTHBUFF_END = "MÔ-ĐUN NGỤY TRANG HỆ THỐNG: TẮT"

WX78.ANNOUNCE_KYNO_FEARBUFF_START = "PHẢN ỨNG CẢM XÚC: MÔ-ĐUN SỢ HÃI ĐÃ VÔ HIỆU. CHẤP NHẬN ĐƯỢC."
WX78.ANNOUNCE_KYNO_FEARBUFF_END = "MÔ-ĐUN SỢ HÃI ĐÃ KÍCH HOẠT LẠI! PHÁT HIỆN RUNG NHẸ Ở KHUNG MÁY"

WX78.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "**HỆ THỐNG QUÁ TẢI**."
WX78.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "MỨC NĂNG LƯỢNG ĐANG TRỞ VỀ TRẠNG THÁI TẦM THƯỜNG."

WX78.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "ĐỘ TƯƠNG THÍCH VỚI HEO ĐÃ TĂNG."
WX78.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "ĐỘ TƯƠNG THÍCH VỚI HEO ĐÃ CHẤM DỨT."

WX78.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "VẬT LIỆU ĂN MÒN ĐÃ BỊ VÔ HIỆU HÓA."
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WX78.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "ĐỘC TỐ SINH HỌC ĐÃ BỊ VÔ HIỆU."
WX78.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "MIỄN DỊCH ĐÃ HẾT HẠN. MỐI ĐE DỌA HỮU CƠ GHÊ TỞM ĐÃ ĐƯỢC KHÔI PHỤC."

WX78.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "NÂNG CẤP HỆ THỐNG: HIỆU SUẤT XÂY DỰNG ĐÃ TĂNG."
WX78.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "NÂNG CẤP ĐÃ HẾT HẠN. TRỞ VỀ CHẾ ĐỘ NGU NGỐC MẶC ĐỊNH."

WX78.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "MÁY BAY SINH HỌC THÙ ĐỊCH TẠM THỜI ĐƯỢC XOA DỊU. CHẤP NHẬN ĐƯỢC."
WX78.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "MÁY BAY SINH HỌC ĐANG TRỞ LẠI CHẾ ĐỘ HUNG HÃN. CẢNH BÁO."

WX78.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "NÂNG CẤP HỆ THỐNG: ĐỘ TOÀN VẸN CẤU TRÚC ĐÃ TĂNG"
WX78.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "NÂNG CẤP ĐÃ HẾT HẠN. MỨC THẤT VỌNG ĐANG TĂNG"

WX78.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "DUNG LƯỢNG CHỨA NHIÊN LIỆU ĐÃ TĂNG"
WX78.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "KHO CHỨA NHIÊN LIỆU ĐÃ BỊ HẠ CẤP"

WX78.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "CHẨN ĐOÁN HỆ THỐNG: NĂNG LỰC NÃO BỘ ĐÃ NÂNG CẤP"
WX78.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "NÂNG CẤP TINH THẦN ĐÃ HẾT HẠN"

WX78.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "CẢI TIẾN THAM SỐ PHÒNG THỦ ĐANG HOẠT ĐỘNG"
WX78.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "CẢNH BÁO: BIỆN PHÁP PHÒNG THỦ BỔ SUNG ĐÃ CHẤM DỨT"

WX78.ANNOUNCE_KYNO_BERSERKERBUFF_START = "SẢN LƯỢNG SÁT THƯƠNG ĐÃ TĂNG. GIAO THỨC PHÒNG THỦ ĐÃ GIẢM"
WX78.ANNOUNCE_KYNO_BERSERKERBUFF_END = "THAM SỐ CHIẾN ĐẤU ĐANG TRỞ LẠI BÌNH THƯỜNG"

WX78.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "MỨC TIÊU THỤ NĂNG LƯỢNG ĐÃ GIẢM"
WX78.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "MỨC TIÊU THỤ NĂNG LƯỢNG ĐÃ KHÔI PHỤC MẶC ĐỊNH"

WX78.ANNOUNCE_KYNO_DARKNESSBUFF_START = "MỨC ĐE DỌA BÓNG TỐI: KHÔNG ĐÁNG KỂ."
WX78.ANNOUNCE_KYNO_DARKNESSBUFF_END = "MỨC ĐE DỌA BÓNG TỐI: NGHIÊM TRỌNG."

WX78.ANNOUNCE_KYNO_LUCKBUFF_END = "TIỂU TRÌNH MAY MẮN ĐÃ CHẤM DỨT"

WX78.ANNOUNCE_KYNO_GREENTHUMBBUFF_START = "HIỆU SUẤT THU HOẠCH ĐÃ TĂNG"
WX78.ANNOUNCE_KYNO_GREENTHUMBBUFF_END = "TĂNG CƯỜNG THU HOẠCH ĐÃ KẾT THÚC"

WX78.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "ĐƠN VỊ TRIỂN KHAI SAI"

WX78.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "SINH VẬT BẨN THỈU MUỐN THỨ KHÁC"

WX78.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "CÁI CÂY NGU NGỐC QUÁ NHỎ ĐỂ XỬ LÝ THIẾT BỊ CỦA TA"

WX78.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "LỖI: ĐƠN VỊ TRIỂN KHAI KHÔNG XÁC ĐỊNH"

WX78.ANNOUNCE_KYNO_POTHANGER_FAIL = "YÊU CẦU MỘT ĐƠN VỊ NẤU ĂN"

WX78.ANNOUNCE_KYNO_CASSEROLE_FAIL = "LỖI: THIẾU ĐƠN VỊ ĐĨA HẦM THEN CHỐT"

WX78.ANNOUNCE_KYNO_SAPHEALER_USED = "QUÁ TRÌNH PHỤC HỒI HOÀN TẤT. TRẠNG THÁI ĐƠN VỊ: 100%"

WX78.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "HA. HA. DẠNG SỐNG HỮU CƠ ĐÃ BỊ XÓA. THU HOẠCH HOÀN TẤT."

WX78.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "KHÔNG TÌM THẤY NỘI DUNG CÓ GIÁ TRỊ. LÃNG PHÍ THỜI GIAN"

WX78.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "MẤT MỤC TIÊU. ĐƯỜNG DẪN ĐÃ BỊ NGẬP."
WX78.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "PHÁT HIỆN GIÁNG THỦY. DỮ LIỆU ĐÃ HỎNG."
WX78.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "PHÁT HIỆN MỐI ĐE DỌA BIỂN. CẦN TIÊU DIỆT."

WX78.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "XÂY DỰNG HOÀN TẤT. KHỞI ĐỘNG GIAO THỨC ĂN MỪNG"

WX78.ANNOUNCE_KYNO_FISH_RESEARCHED = "PHÂN TÍCH HOÀN TẤT. ĐÃ THU THẬP DỮ LIỆU CÁ."
WX78.ANNOUNCE_KYNO_ROE_RESEARCHED = "PHÂN TÍCH TRỨNG HOÀN TẤT. ĐÃ THU THẬP DỮ LIỆU."

WX78.ANNOUNCE_KYNO_DAILYRECIPE_EATEN = "DỮ LIỆU DINH DƯỠNG ĐÃ CẬP NHẬT"

WX78.DESCRIBE.KYNO_ROE = "CÁC THỰC THỂ THỦY SINH HẠ ĐẲNG TIỀM NĂNG"
WX78.DESCRIBE.KYNO_ROE_COOKED = "CHÚNG YẾU ỚT VÀ TA ĐÃ HỦY DIỆT CHÚNG HAHAHA"

WX78.DESCRIBE.KYNO_SHARK_FIN = "BÁNH LÁI CỦA CON QUÁI"

WX78.DESCRIBE.KYNO_BEANBUGS = "TỰ NHIÊN THẬT BẤT THƯỜNG"
WX78.DESCRIBE.KYNO_BEANBUGS_COOKED = "CHỨA NĂNG LƯỢNG NHƯNG VỚI CÁI GIÁ NÀO?"

WX78.DESCRIBE.KYNO_GUMMYBUG = "NĂNG LƯỢNG MỀM NHŨN"
WX78.DESCRIBE.KYNO_GUMMYBUG_COOKED = "HAHA TA SẼ CHUYỂN HÓA NGƯƠI THÀNH NĂNG LƯỢNG"

WX78.DESCRIBE.KYNO_WHEAT = "PHÁT HIỆN NGŨ CỐC"
WX78.DESCRIBE.KYNO_WHEAT_COOKED = "PHÁT HIỆN NGŨ CỐC ĐÃ NƯỚNG"

WX78.DESCRIBE.KYNO_FLOUR = "GIAI ĐOẠN BAN ĐẦU CỦA THỨC ĂN"

WX78.DESCRIBE.KYNO_SPOTSPICE = "NGƯƠI ĐÃ BỊ NGHIỀN NÁT, CÀNH NHỎ"

WX78.DESCRIBE.KYNO_SAP = "CHẤT LÀM MÁT THỰC VẬT NGON LÀNH"
WX78.DESCRIBE.KYNO_SAP_SPOILED = "ĐỘ DÍNH VÔ DỤNG"

WX78.DESCRIBE.KYNO_SYRUP = "CHỨA MỨC ĐỘ DÍNH CAO"

WX78.DESCRIBE.KYNO_COFFEEBEANS = "HẠT CÓ THỂ UỐNG"
WX78.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "HẠT GÂY NGHIỆN ĐÃ ĐẠT MỨC RANG TỐI ƯU"

WX78.DESCRIBE.DUG_KYNO_COFFEEBUSH = "MẪU VẬT SẴN SÀNG DI DỜI"

WX78.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "CÂY HẠT CÓ THỂ UỐNG",
	PICKED = "SẢN LƯỢNG HẠT ĐÃ DỪNG",
	WITHERED = "MỨC TRO KHÔNG ĐỦ",
}

WX78.DESCRIBE.DUG_KYNO_SPOTBUSH = "BỤI CÂY NGU NGỐC CẦN ĐƯỢC TRỒNG LẠI"

WX78.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "GIAO THỨC ĂN CỦA NGƯƠI CHO TA, BỤI CÂY",
	PICKED = "SẢN LƯỢNG TÀI NGUYÊN ĐÃ DỪNG",
	BURNING = "CẢNH BÁO: CHÁY",
}

WX78.DESCRIBE.KYNO_SPOTSPICE_LEAF = "TA SẼ NGHIỀN NÁT NGƯƠI"

WX78.DESCRIBE.KYNO_MUSSEL = "KHÔNG PHÁT HIỆN CƠ BẮP"
WX78.DESCRIBE.KYNO_MUSSEL_COOKED = "PHÂN TỬ HƯƠNG VỊ RẤT MẠNH"

WX78.DESCRIBE.KYNO_HUMANMEAT = "MỘT CẢI TIẾN NỮA CỦA TÌNH TRẠNG CON NGƯỜI."
WX78.DESCRIBE.KYNO_HUMANMEAT_COOKED = "CUỐI CÙNG, ĐÁM DỊCH HẠI ĐẦY THỊT CŨNG CÓ MỤC ĐÍCH"
WX78.DESCRIBE.KYNO_HUMANMEAT_DRIED = "ĐẸP VÀ KHÔ"

WX78.DESCRIBE.COFFEE = "CHỈ LÀ NƯỚC HẠT NÓNG."

WX78.DESCRIBE.BISQUE = "NĂNG LƯỢNG PIN TRONG MỘT CÁI BÁT"

WX78.DESCRIBE.JELLYOPOP = "NÓ SẼ GIỮ HỆ THỐNG CỦA TA VẬN HÀNH"

WX78.DESCRIBE.SHARKFINSOUP = "CÓ VẺ ĂN ĐƯỢC"

WX78.DESCRIBE.TROPICALBOUILLABAISSE = "THỨ NÀY SẼ CẤP NHIÊN LIỆU CHO CƠ THỂ CƠ KHÍ THƯỢNG ĐẲNG CỦA TA"

WX78.DESCRIBE.MUSSELBOUILLABAISE = "ĐANG KÍCH HOẠT CẢM BIẾN LƯỠI"

WX78.DESCRIBE.SWEETPOTATOSOUFFLE = "XÚC PHẠM"

WX78.DESCRIBE.FEIJOADA = "GÓI NĂNG LƯỢNG"

WX78.DESCRIBE.GUMMY_CAKE = "KHÔNG CÓ NIỀM VUI TRONG THỨ NÀY"

WX78.DESCRIBE.HARDSHELL_TACOS = "TA SẼ NGHIỀN NÁT LỚP VỎ CỨNG CỦA NÓ"

WX78.DESCRIBE.ICEDTEA = "THỨC UỐNG SẢNG KHOÁI LÀM TỪ KẺ THÙ CỦA TA"

WX78.DESCRIBE.NETTLELOSANGE = "KHÍ NÉN CHO ĐƠN VỊ MŨI"

WX78.DESCRIBE.SNAKEBONESOUP = "MÓN Ủ LÀM TỪ HAI KẺ THÙ CỦA TA"

WX78.DESCRIBE.STEAMEDHAMSANDWICH = "MỘT BỮA TRƯA KHÔNG THỂ QUÊN"

WX78.DESCRIBE.TEA = "CHẤT LỎNG THU ĐƯỢC TỪ MÁY THỊT"

WX78.DESCRIBE.BUBBLETEA = "THỨC UỐNG SẢNG KHOÁI LÀM TỪ KẺ THÙ CỦA TA"

WX78.DESCRIBE.FRENCHONIONSOUP = "MÓN Ủ LÀM TỪ HÀNH"

WX78.DESCRIBE.SLAW = "ĐÃ XÁC ĐỊNH CHẤT DUY TRÌ SỰ SỐNG"

WX78.DESCRIBE.LOTUSBOWL = "TA ĐÃ GIẢI PHÓNG NÓ KHỎI NHU CẦU BÁM ĐẤT"

WX78.DESCRIBE.POI = "THỨC ĂN TẦM THƯỜNG NÀY NÊN TUYỆT CHỦNG"

WX78.DESCRIBE.JELLYBEAN_HUNGER = "LINH KIỆN NÂNG CẤP TẠM THỜI"
WX78.DESCRIBE.JELLYBEAN_SUPER = "LINH KIỆN NÂNG CẤP TẠM THỜI"
WX78.DESCRIBE.JELLYBEAN_SANITY = "LINH KIỆN NÂNG CẤP TẠM THỜI"

WX78.DESCRIBE.BOWLOFGEARS = "ĐÚNG. GIỜ ĐÓ MỚI LÀ THỨC ĂN PHÙ HỢP CHO MỘT THỰC THỂ THƯỢNG ĐẲNG"

WX78.DESCRIBE.LONGPIGMEAL = "CẢI TIẾN THỊT NGƯỜI"

WX78.DESCRIBE.CUCUMBERSALAD = "LẮP RÁP SALAD: HOÀN TẤT"

WX78.DESCRIBE.DUG_KYNO_WILDWHEAT = "SẴN SÀNG CẤY GHÉP"

WX78.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "NGŨ CỐC",
	PICKED = "SẢN LƯỢNG NGŨ CỐC ĐÃ DỪNG",
	WITHERED = "ĐỘ ẨM KHÔNG ĐỦ",
	BURNING = "CẢNH BÁO: CHÁY",
}

WX78.DESCRIBE.KYNO_MEALGRINDER = "TA RẤT GIỎI NGHIỀN NÁT"

WX78.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "ĐÃ XÁC NHẬN CÓ THỂ ĂN",
	PICKED = "TỐC ĐỘ PHÁT TRIỂN DẠNG SỐNG KHÔNG ĐẠT NHU CẦU CỦA TA",
	BURNING = "CẢNH BÁO: CHÁY HỮU CƠ",
}

WX78.DESCRIBE.GORGE_BREAD = "NGUYÊN LIỆU CHO CÔNG THỨC TỐT HƠN"
WX78.DESCRIBE.GORGE_SWEET_CHIPS = "MẢNH KHOAI TÂY ĐÃ CẮT LÁT VÀ CHIÊN"
WX78.DESCRIBE.GORGE_VEGETABLE_SOUP = "CHỈ LÀ MỘT ĐỐNG RAU CỦ TẬP HỢP LẠI"
WX78.DESCRIBE.GORGE_JELLY_SANDWICH = "NÓ ĐANG LÀM TA DÍNH MỨT"
WX78.DESCRIBE.GORGE_FISH_STEW = "CHUẨN BỊ NẠP CALO"
WX78.DESCRIBE.GORGE_MEAT_STEW = "ĐÃ THU NHẬN DINH DƯỠNG"
WX78.DESCRIBE.GORGE_ONION_CAKE = "BÁNH KINH TỞM"
WX78.DESCRIBE.GORGE_POTATO_PANCAKES = "CÁCH DÙNG KHOAI TÂY THẬT THẢM HẠI"
WX78.DESCRIBE.GORGE_POTATO_SOUP = "NĂNG LƯỢNG PIN TRONG MỘT CÁI BÁT"
WX78.DESCRIBE.GORGE_FISHBALL_SKEWERS = "LƯỢNG THỨC ĂN CHẤP NHẬN ĐƯỢC TRÊN MỘT CÁI QUE"
WX78.DESCRIBE.GORGE_MEAT_SKEWERS = "LƯỢNG THỨC ĂN CHẤP NHẬN ĐƯỢC TRÊN MỘT CÁI QUE"
WX78.DESCRIBE.GORGE_STONE_SOUP = "NĂNG LƯỢNG PIN TRONG MỘT CÁI BÁT"
WX78.DESCRIBE.GORGE_CROQUETTE = "VIÊN BỘT"
WX78.DESCRIBE.GORGE_ROAST_VEGETABLES = "KINH TỞM"
WX78.DESCRIBE.GORGE_MEATLOAF = "THỊT TRỘN VỚI VỤN BÁNH MÌ"
WX78.DESCRIBE.GORGE_CARROT_SOUP = "NĂNG LƯỢNG PIN TRONG MỘT CÁI BÁT"
WX78.DESCRIBE.GORGE_FISHPIE = "DẠNG SỐNG YẾU ỚT BỊ KẸT TRONG BỘT. HA HA."
WX78.DESCRIBE.GORGE_FISHCHIPS = "THỨC ĂN PHÙ HỢP HƠN"
WX78.DESCRIBE.GORGE_MEATPIE = "THỊT BỊ NGHIỀN TRONG MỘT CÁI BÁNH"
WX78.DESCRIBE.GORGE_SLIDERS = "ĐỒ ĂN RÁC"
WX78.DESCRIBE.GORGE_JELLY_ROLL = "QUÁ NHỚT ĐỐI VỚI TA"
WX78.DESCRIBE.GORGE_CARROT_CAKE = "NHƯNG... NHƯNG... TA TƯỞNG ĐÓ CHỈ LÀ LỜI NÓI DỐI"
WX78.DESCRIBE.GORGE_GARLICMASHED = "HỖN HỢP KINH TỞM"
WX78.DESCRIBE.GORGE_GARLICBREAD = "MỘT PHẦN BỔ SUNG TỐT"
WX78.DESCRIBE.GORGE_TOMATO_SOUP = "NĂNG LƯỢNG PIN TRONG MỘT CÁI BÁT"
WX78.DESCRIBE.GORGE_SAUSAGE = "HA. KẾT CỤC CỦA NGƯƠI ĐÃ ĐẾN"
WX78.DESCRIBE.GORGE_CANDIEDFISH = "CÓ XI-RÔ TRONG HỆ THỐNG CỦA TA"
WX78.DESCRIBE.GORGE_STUFFEDMUSHROOM = "ĐÃ NHỒI"
WX78.DESCRIBE.GORGE_BRUSCHETTA = "KHÔNG CÓ GÌ ĐẶC BIỆT Ở MÓN NÀY"
WX78.DESCRIBE.GORGE_HAMBURGER = "MỘT TRONG SỐ ÍT THỨC ĂN CỦA CON NGƯỜI CÓ GIÁ TRỊ"
WX78.DESCRIBE.GORGE_FISHBURGER = "MỘT TRONG SỐ ÍT THỨC ĂN CỦA CON NGƯỜI CÓ GIÁ TRỊ"
WX78.DESCRIBE.GORGE_MUSHROOMBURGER = "MỘT TRONG SỐ ÍT THỨC ĂN CỦA CON NGƯỜI CÓ GIÁ TRỊ"
WX78.DESCRIBE.GORGE_FISH_STEAK = "CHUẨN BỊ NẠP CALO"
WX78.DESCRIBE.GORGE_CURRY = "CHỈ LÀ MỘT THỨ GIỐNG SÚP BÌNH THƯỜNG"
WX78.DESCRIBE.GORGE_SPAGHETTI = "THỊT ĐƯỢC ĐÓNG GÓI THÀNH HÌNH DẠNG DINH DƯỠNG NHẤT: HÌNH CẦU"
WX78.DESCRIBE.GORGE_POACHEDFISH = "CON CÁ HỒI ĐÓ SẼ KHÔNG ĐI ĐÂU ĐƯỢC NỮA"
WX78.DESCRIBE.GORGE_SHEPHERD_PIE = "Ở ĐÂY KHÔNG CÓ CON CỪU NÀO"
WX78.DESCRIBE.GORGE_CANDY = "DÍNH VÀ NGỌT"
WX78.DESCRIBE.GORGE_BREAD_PUDDING = "BÁNH MÌ KẸO"
WX78.DESCRIBE.GORGE_BERRY_TART = "ÔI CHỦ NHÂN CỦA TA THỨ NÀY KINH TỞM"
WX78.DESCRIBE.GORGE_MACARONI = "TA SẼ HÚT CẠN MÓN NÀY"
WX78.DESCRIBE.GORGE_BAGEL_AND_FISH = "CÁ HỒI VỚI BÁNH MÌ THẬT ĐỘC ĐÁO LÀM SAO"
WX78.DESCRIBE.GORGE_GRILLED_CHEESE = "PRINT(\"XIN CHÀO THẾ GIỚI\")"
WX78.DESCRIBE.GORGE_CREAMMUSHROOM = "KHÔNG, LẠI LÀ THỨ NÀY"
WX78.DESCRIBE.GORGE_MANICOTTI = "CHÁÁÁN"
WX78.DESCRIBE.GORGE_CHEESEBURGER = "MỘT TRONG SỐ ÍT THỨC ĂN CỦA CON NGƯỜI CÓ GIÁ TRỊ"
WX78.DESCRIBE.GORGE_FETTUCCINE = "ĐỪNG NHÌN VÀO MẮT TA NỮA"
WX78.DESCRIBE.GORGE_ONION_SOUP = "NÓ HÔI"
WX78.DESCRIBE.GORGE_BREADED_CUTLET = "THỊT VÀ BÁNH MÌ ĐƯỢC GHÉP CÙNG NHAU"
WX78.DESCRIBE.GORGE_CREAMY_FISH = "LẠI CÁ HỒI? THẬT ĐỘC ĐÁO"
WX78.DESCRIBE.GORGE_PIZZA = "HA. MỒI NHỬ KINH ĐIỂN CHO LŨ NGƯỜI NGU NGỐC"
WX78.DESCRIBE.GORGE_POT_ROAST = "ĐƠN GIẢN LÀ KHÔNG THỂ NÀO"
WX78.DESCRIBE.GORGE_CRAB_CAKE = "THỨ NÀY CHẮC CHẮN KHÔNG PHẢI NGHỆ THUẬT"
WX78.DESCRIBE.GORGE_STEAK_FRITES = "KINH ĐIỂN"
WX78.DESCRIBE.GORGE_SHOOTER_SANDWICH = "BẮN TỚI CÁC VÌ SAO"
WX78.DESCRIBE.GORGE_BACON_WRAPPED = "CHỈ LÀ THỊT BỌC THÊM THỊT"
WX78.DESCRIBE.GORGE_CRAB_ROLL = "EXTRAORDINAIRE"
WX78.DESCRIBE.GORGE_MEAT_WELLINGTON = "TA CÓ NGHI NGỜ VỀ MÓN NÀY"
WX78.DESCRIBE.GORGE_CRAB_RAVIOLI = "EXTRAORDINAIRE"
WX78.DESCRIBE.GORGE_CARAMEL_CUBE = "MỘT KHỐI CARAMEL TỐT"
WX78.DESCRIBE.GORGE_SCONE = "QUÁ NHIỀU ĐƯỜNG AAAA"
WX78.DESCRIBE.GORGE_TRIFLE = "QUÁ NHIỀU ĐƯỜNG AAAA"
WX78.DESCRIBE.GORGE_CHEESECAKE = "PHÔ MAI TRÊN NÓ Ở ĐÂU?"

WX78.DESCRIBE.DUCKYOUGLERMZ = "CÁI CÂY ĐÓ CẦN SỬA PHẦN CỨNG"

WX78.DESCRIBE.KYNO_ALOE = "ĐÃ THU NHẬN NĂNG LƯỢNG XANH"
WX78.DESCRIBE.KYNO_ALOE_COOKED = "NĂNG LƯỢNG XANH ĐÃ ÁP CHẢO"
WX78.DESCRIBE.KYNO_ALOE_DRIED = "NĂNG LƯỢNG XANH ĐÃ SẤY KHÔ"
WX78.DESCRIBE.KYNO_ALOE_GROUND = "ĐÃ THU NHẬN NĂNG LƯỢNG XANH"
WX78.DESCRIBE.KYNO_ALOE_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.FARM_PLANT_KYNO_ALOE = "ĐÃ THU NHẬN NĂNG LƯỢNG XANH"
WX78.DESCRIBE.KYNO_ALOE_OVERSIZED = "ĐÃ THU NHẬN NĂNG LƯỢNG XANH"
WX78.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_CUCUMBER = "TA ĐÃ CƯỚP NÓ KHỎI NƯỚC KINH KHỦNG"
WX78.DESCRIBE.KYNO_CUCUMBER_COOKED = "BÃ NĂNG LƯỢNG"
WX78.DESCRIBE.KYNO_CUCUMBER_GROUND = "TA ĐÃ CƯỚP NÓ KHỎI NƯỚC KINH KHỦNG"
WX78.DESCRIBE.KYNO_CUCUMBER_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "TA ĐÃ CƯỚP NÓ KHỎI NƯỚC KINH KHỦNG"
WX78.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "TA ĐÃ CƯỚP NÓ KHỎI NƯỚC KINH KHỦNG"
WX78.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_RADISH = "QUẢ CẦU NĂNG LƯỢNG ĐỎ"
WX78.DESCRIBE.KYNO_RADISH_COOKED = "ĐÃ THU NHẬN NĂNG LƯỢNG"
WX78.DESCRIBE.KYNO_RADISH_GROUND = "QUẢ CẦU NĂNG LƯỢNG ĐỎ"
WX78.DESCRIBE.KYNO_RADISH_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.FARM_PLANT_KYNO_RADISH = "QUẢ CẦU NĂNG LƯỢNG ĐỎ"
WX78.DESCRIBE.KYNO_RADISH_OVERSIZED = "QUẢ CẦU NĂNG LƯỢNG ĐỎ"
WX78.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_FENNEL = "VỚI TA NÓ TRÔNG NHƯ MỘT CÁI CÂY BÌNH THƯỜNG."
WX78.DESCRIBE.KYNO_FENNEL_COOKED = "GHÊ TỞM"
WX78.DESCRIBE.KYNO_FENNEL_GROUND = "VỚI TA NÓ TRÔNG NHƯ MỘT CÁI CÂY BÌNH THƯỜNG."
WX78.DESCRIBE.KYNO_FENNEL_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "VỚI TA NÓ TRÔNG NHƯ MỘT CÁI CÂY BÌNH THƯỜNG."
WX78.DESCRIBE.KYNO_FENNEL_OVERSIZED = "VỚI TA NÓ TRÔNG NHƯ MỘT CÁI CÂY BÌNH THƯỜNG."
WX78.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_SWEETPOTATO = "GHÊ TỞM"
WX78.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "TINH BỘT VÀ VỊ NGỌT ĐẤU TRANH QUYỀN THỐNG TRỊ VÀ WX-78 LÀ KẺ THUA"
WX78.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "GHÊ TỞM"
WX78.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "GHÊ TỞM"
WX78.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "GHÊ TỞM"
WX78.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_PARZNIP = "BỔ DƯỠNG"
WX78.DESCRIBE.KYNO_PARZNIP_COOKED = "BỔ DƯỠNG"
WX78.DESCRIBE.KYNO_PARZNIP_EATEN = "BỔ DƯỠNG"
WX78.DESCRIBE.KYNO_PARZNIP_GROUND = "BỔ DƯỠNG"
WX78.DESCRIBE.KYNO_PARZNIP_BIG = "PHÂN TÍCH KÍCH THƯỚC HOÀN TẤT: KHỔNG LỒ"
WX78.DESCRIBE.KYNO_PARZNIP_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "BỔ DƯỠNG"
WX78.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "BỔ DƯỠNG"
WX78.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_TURNIP = "ĐÓ LÀ MỘT CỦ CẢI NGU NGỐC"
WX78.DESCRIBE.KYNO_TURNIP_COOKED = "NÓ ĐƯỢC NẤU CHÍN ĐỀU TOÀN BỘ"
WX78.DESCRIBE.KYNO_TURNIP_GROUND = "ĐÓ LÀ MỘT CỦ CẢI NGU NGỐC"
WX78.DESCRIBE.KYNO_TURNIP_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "ĐÓ LÀ MỘT CỦ CẢI NGU NGỐC"
WX78.DESCRIBE.KYNO_TURNIP_OVERSIZED = "ĐÓ LÀ MỘT CỦ CẢI NGU NGỐC"
WX78.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_RICE = "RAU CỦ KINH TỞM"
WX78.DESCRIBE.KYNO_RICE_COOKED = "RAU CỦ KINH TỞM"
WX78.DESCRIBE.KYNO_RICE_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"
WX78.DESCRIBE.FARM_PLANT_KYNO_RICE = "ĐÓ LÀ MỘT THÂN LÚA NGU NGỐC"
WX78.DESCRIBE.KYNO_RICE_OVERSIZED = "ĐÓ LÀ MỘT THÂN LÚA NGU NGỐC"
WX78.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_SEEDS_KIT = "THỨ BẨN THỈU"

WX78.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "THỊT NGU NGỐC SẼ KHÔNG BAO GIỜ NUỐT ĐƯỢC ĐÁ",
	PICKED = "HỮU CƠ TẠM THỜI KHÔNG KHẢ DỤNG",
	WITHERED = "MÔI TRƯỜNG KHÔNG PHÙ HỢP CHO HỮU CƠ",
}

WX78.DESCRIBE.KYNO_LIMPETS = "NGUỒN PROTEIN NHỎ"
WX78.DESCRIBE.KYNO_LIMPETS_COOKED = "MỘT CẢI TIẾN ĐÁNG HOAN NGHÊNH"

WX78.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "ĐƠN VỊ HỮU CƠ CẦN NƯỚC",
	PICKED = "SẢN XUẤT HOA ĐÃ DỪNG",
	BURNING = "LỖI NGHIÊM TRỌNG: CHÁY",
}

WX78.DESCRIBE.KYNO_LOTUS_ROOT = "KHÔNG ÁP DỤNG NGOÀI NƯỚC"
WX78.DESCRIBE.KYNO_LOTUS_FLOWER = "HOA NƯỚC XẤU XÍ"
WX78.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "TA ĐÃ GIẢI PHÓNG NÓ KHỎI NHU CẦU CẦN NƯỚC"

WX78.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "BIỂN CŨNG CÓ CỎ DẠI SAO?",
	PICKED = "ĐANG CHỜ TÁI SINH TRƯỞNG",
	BURNING = "LỖI: LỬA TRONG MÔI TRƯỜNG BIỂN",
}

WX78.DESCRIBE.KYNO_SEAWEEDS = "NÓ NHỚT VÀ KINH TỞM"
WX78.DESCRIBE.KYNO_SEAWEEDS_COOKED = "MÓN ĂN VẶT LÀNH MẠNH"
WX78.DESCRIBE.KYNO_SEAWEEDS_DRIED = "THỰC PHẨM LÀNH MẠNH"
WX78.DESCRIBE.KYNO_SEAWEEDS_ROOT = "KHÔNG ÁP DỤNG NGOÀI NƯỚC"

WX78.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "CÂY NƯỚC KINH TỞM",
	PICKED = "TÁI SINH TRƯỞNG ĐƯỢC NƯỚC TĂNG TỐC",
	BURNING = "CẢNH BÁO: CHÁY HỮU CƠ",
}

WX78.DESCRIBE.KYNO_TAROROOT_ROOT = "KHÔNG ÁP DỤNG NGOÀI NƯỚC"
WX78.DESCRIBE.KYNO_TAROROOT = "NÓ TÍM QUÁ"
WX78.DESCRIBE.KYNO_TAROROOT_COOKED = "MÀU MÈ"

WX78.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "CÂY KINH TỞM",
	PICKED = "CHU KỲ TÁI SINH TRƯỞNG ĐÃ KHỞI ĐỘNG",
	BURNING = "DỊ THƯỜNG HỆ THỐNG: PHÁT HIỆN LỬA",
}

WX78.DESCRIBE.KYNO_WATERYCRESS_ROOT = "KHÔNG ÁP DỤNG NGOÀI NƯỚC"
WX78.DESCRIBE.KYNO_WATERYCRESS = "CÂY KINH TỞM"

WX78.DESCRIBE.WATERYCRESSBOWL = "NÓ ĐƯỢC LÀM TỪ MÁU CỦA KẺ THÙ CỦA TA"

WX78.DESCRIBE.KYNO_SALT = "KHÔNG TỐT CHO MẠCH ĐIỆN"

WX78.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "HỮU CƠ THỦY SINH ĐÃ BÁM VÀO",
	PICKED = "HỮU CƠ KHÔNG KHẢ DỤNG",
	BURNING = "CẢNH BÁO: TÀI NGUYÊN ĐANG CHÁY",
}

WX78.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "HỆ THỐNG THU HÚT VÀ TĂNG TRƯỞNG PROTEIN"

WX78.DESCRIBE.CATFOOD = "ĐÓ LÀ NGUỒN NĂNG LƯỢNG CHÍNH CHO LOÀI MÈO."

WX78.DESCRIBE.KATFOOD = "ĐÓ LÀ NGUỒN NĂNG LƯỢNG CHÍNH CHO LOÀI MÈO."

WX78.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "LẼ RA TA NÊN ĐỂ NÓ DƯỚI LÒNG ĐẤT",
	PICKED = "SẢN XUẤT TRÁI TẠM THỜI DỪNG",
	CHOPPED = "CÂY ĐÃ BỊ CHẤM DỨT",
	BURNING = "CẢNH BÁO: PHÁT HIỆN CHÁY",
	BURNT = "CÂY ĐÃ BỊ GIẢM THÀNH TRO",
}

WX78.DESCRIBE.KYNO_BANANA = "THÊM CARBON"
WX78.DESCRIBE.KYNO_BANANA_COOKED = "MẤY THỨ THỨC ĂN NÀY THẬT PHIỀN PHỨC"

WX78.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "CÁI CÂY NÀY TOÀN LÀ THÂN",
	PICKED = "SẢN XUẤT TRÁI ĐÃ TẠM DỪNG",
	CHOPPED = "CÂY ĐÃ BỊ CHẤM DỨT",
	BURNING = "CẢNH BÁO: CHÁY",
	BURNT = "CÂY ĐÃ BỊ GIẢM THÀNH TRO",
}

WX78.DESCRIBE.KYNO_KOKONUT = "TRÁI CÂY NGU NGỐC CỦA CÂY"
WX78.DESCRIBE.KYNO_KOKONUT_HALVED = "DINH-DƯỠNG HẠT GIỜ CÓ THỂ TRUY CẬP"
WX78.DESCRIBE.KYNO_KOKONUT_COOKED = "MÙI THƠM NƯỚNG KHÔNG CÓ TÁC DỤNG VỚI TA"

WX78.DESCRIBE.BOWLOFPOPCORN = "CALO RỖNG"

WX78.DESCRIBE.FIGJUICE = "THỨC UỐNG SẢNG KHOÁI LÀM TỪ TRÁI CÂY NGU NGỐC"

WX78.DESCRIBE.COCONUTWATER = "NƯỚC NÀY CHỨA MỘT MÃ KHÁC"

WX78.DESCRIBE.EYEBALLSPAGHETTI = "TA NGHĨ NÓ ĐANG NHÌN TA"

WX78.DESCRIBE.FORGETMELOTS_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"

WX78.DESCRIBE.FIRENETTLES_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"

WX78.DESCRIBE.TILLWEED_SEEDS = "ĐÓ LÀ MÃ NGUỒN CỦA THỨC ĂN ĐẾN TỪ ĐẤT"

WX78.DESCRIBE.KYNO_FLOATILIZER = "XÔ CHẤT THẢI BIỂN"

WX78.DESCRIBE.KYNO_TWIGGYNUTS = "MẤY HẠT NÀY"

WX78.DESCRIBE.KYNO_REPAIRTOOL = "ĐƠN VỊ SỬA CHỮA ĐÃ LẮP RÁP"

WX78.DESCRIBE.KYNO_KOI = "TA CÓ THỂ ĐÁNH GIÁ CAO ÁNH VÀNG CỦA NÓ"
WX78.DESCRIBE.KYNO_KOI_COOKED = "TA CÓ THỂ ĐÁNH GIÁ CAO ÁNH VÀNG CỦA NÓ"

WX78.DESCRIBE.KYNO_TROPICALFISH = "NGƯƠI NHIỆT ĐỚI VÀ LÀ CÁ"
WX78.DESCRIBE.KYNO_TROPICALFISH_COOKED = "HAHA, ĐÁNG ĐỜI NGƯƠI"

WX78.DESCRIBE.KYNO_NEONFISH = "CON CÁ NÀY KHÔ HƠN NHỮNG CON KHÁC"
WX78.DESCRIBE.KYNO_NEONFISH_COOKED = "TA SẼ THU NHẬN SỨC MẠNH LÀM KHÔ CỦA NÓ"

WX78.DESCRIBE.KYNO_GROUPER = "TA ĐÃ CỨU NÓ KHỎI NƯỚC. ĐỒ VÔ ƠN"
WX78.DESCRIBE.KYNO_GROUPER_COOKED = "GIỜ NÓ LÀ NHIÊN LIỆU ROBOT. HA HA"
 
WX78.DESCRIBE.KYNO_PIERROTFISH = "NÓ SỐNG NGẬP TRONG NƯỚC. ĐÁNG SỢ"
WX78.DESCRIBE.KYNO_PIERROTFISH_COOKED = "TA SẼ ĂN SINH VẬT SỐNG DƯỚI NƯỚC KINH KHỦNG NÀY"

WX78.DESCRIBE.KYNO_SALMONFISH = "SINH VẬT NƯỚC MỀM OẶT"
WX78.DESCRIBE.KYNO_SALMONFISH_COOKED = "ĐIỂM YẾU CỦA NÓ LÀ LỬA"

WX78.DESCRIBE.TURF_PINKPARK = "MÀU HỒNG ĐANG LÀM TA ĐỎ MẶT"
WX78.DESCRIBE.TURF_STONECITY = "BỘ PHẬN MẶT ĐẤT"
WX78.DESCRIBE.TURF_FIELDS = "BỘ PHẬN MẶT ĐẤT"
WX78.DESCRIBE.TURF_TIDALMARSH = "BỘ PHẬN MẶT ĐẤT."

WX78.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "THẬN TRỌNG: TRÁNH BẮN CHẤT LỎNG LÊN MẠCH ĐIỆN",
	PICKED = "ĐÃ TRÁNH TIẾP XÚC VỚI NƯỚC THÀNH CÔNG",
}

WX78.DESCRIBE.KYNO_SALTRACK_INSTALLER = "CẦN LẮP RÁP MỘT PHẦN"

WX78.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "ĐỂ HÚT CHẤT LÀM MÁT TỪ CÂY"

WX78.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "BẪY ĐÁ SINH HỌC"

WX78.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "CON HEO TO NÀY RA LỆNH CHO NHỮNG CON NHỎ HƠN",
	SLEEPING = "CHẾ ĐỘ NGỦ SÂU ĐÃ KÍCH HOẠT",
}

WX78.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "MỘT CÁI CÂY HỒNG GỚM GHIẾC",
	CHOPPED = "NGUỒN CHẤT LÀM MÁT THỰC VẬT ĐÃ BỊ PHÁ HỦY",
	SAPPED = "ĐÃ ĐẾN LÚC THU CHẤT LÀM MÁT",
	PICKED = "TA RA LỆNH NGƯƠI NẠP ĐẦY NHANH HƠN",
	BURNING = "CẢNH BÁO: CHÁY",
	BURNT = "SINH VẬT BẨN THỈU ĐÃ BỊ HỦY DIỆT",
}

WX78.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "THÂN CÂY ĐÃ CHỊU HƯ HẠI",
	CHOPPED = "ĐƠN VỊ LỖI ĐÃ BỊ LOẠI BỎ",
	SAPPED = "NHỰA CÂY HỎNG ĐÃ SẴN SÀNG",
	PICKED = "CÁC ĐƠN VỊ SINH HỌC TÍ HON ĐÃ PHÁ HOẠI VIỆC THU CHẤT LÀM MÁT",
	BURNING = "ĐANG THANH TẨY CHẤT BẨN",
	BURNT = "ĐƠN VỊ ĐÃ BỊ CHẤM DỨT",
}

WX78.DESCRIBE.KYNO_SUGARTREE_BUD = "ĐƠN VỊ CHỨA ĐƯỜNG"

WX78.DESCRIBE.KYNO_SUGARTREE_FLOWER = "KHẢ NĂNG THƯỞNG THỨC VẺ ĐẸP CỦA TA CÓ GIỚI HẠN"
WX78.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "KHẢ NĂNG THƯỞNG THỨC VẺ ĐẸP CỦA TA CÓ GIỚI HẠN"

WX78.DESCRIBE.KYNO_SUGARTREE_PETALS = "KHẢ NĂNG THƯỞNG THỨC VẺ ĐẸP CỦA TA CÓ GIỚI HẠN"
WX78.DESCRIBE.KYNO_SUGARTREE_PETALS_DRIED = "CÁNH HOA XẤU XÍ"

WX78.DESCRIBE.KYNO_PEBBLECRAB = "NÓ GIỐNG ĐÁ. NHƯNG CÒN SỐNG VÀ TỆ HƠN"

WX78.DESCRIBE.KYNO_CRABMEAT = "THỊT TỪ SINH VẬT ĐÁ"
WX78.DESCRIBE.KYNO_CRABMEAT_COOKED = "THỊT ĐÁ NGON LÀNH"
WX78.DESCRIBE.KYNO_CRABMEAT_DRIED = "THỊT TỪ SINH VẬT ĐÁ"

WX78.DESCRIBE.KYNO_CRABKINGMEAT = "THỊT TỪ SINH VẬT ĐÁ"
WX78.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "THỊT TỪ SINH VẬT ĐÁ"
WX78.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "THỊT TỪ SINH VẬT ĐÁ"

WX78.DESCRIBE.KYNO_SLAUGHTERTOOL = "ĐỂ THÁO RỜI CÁC DẠNG SỐNG SINH HỌC"

WX78.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "LỖI: KHÔNG TÍNH TOÁN ĐƯỢC",
	COOP = "ĐƠN VỊ HỮU CƠ ĐÃ ĐƯỢC GIAM GIỮ THÀNH CÔNG",
}

WX78.DESCRIBE.KYNO_CHICKEN_EGG = "TA GHÉT NGƯƠI, TRỨNG"
WX78.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "ĐƠN VỊ VỎ BẢO VỆ ĐÃ NÂNG CẤP"
WX78.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "ĐÁNG LẼ ĐÂY PHẢI LÀ MỘT CẢI TIẾN"

WX78.DESCRIBE.KYNO_CHICKEN_EGG_LARGE_CRACKED =
{
	GENERIC = "DẠNG SỐNG HỮU CƠ ĐANG CHỜ TRIỂN KHAI",
	HATCHING = "ĐỘ TOÀN VẸN VỎ ĐANG SUY YẾU. ĐƠN VỊ HỮU CƠ SẮP XUẤT HIỆN.",
}

WX78.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "CẤU TRÚC GẠM GIỮ GIA CẦM",
	FULL = "ĐÃ ĐẠT SẢN LƯỢNG TRỨNG TỐI ĐA",
	BURNT = "LỖI ĐƠN VỊ: VẬT CHẤT HỮU CƠ ĐÃ BỊ HỦY DIỆT",
}

WX78.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "THẢM HẠI. CHÚNG THẬM CHÍ KHÔNG BIẾT CÁCH XÂY MỘT CÁI NỒI ĐÚNG CHUẨN"

WX78.DESCRIBE.KYNO_COOKWARE_KIT = "MẪU NHÀ BẾP ĐÃ LẮP SẴN"
WX78.DESCRIBE.KYNO_COOKWARE_SYRUP = "YÊU CẦU SUCROSE VÀ LỬA ĐỂ TẠO THÊM SUCROSE"
WX78.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "YÊU CẦU SUCROSE VÀ LỬA ĐỂ TẠO THÊM SUCROSE"
WX78.DESCRIBE.KYNO_COOKWARE_BIG_POT = "CÁI NỒI NÀY CÓ DUNG LƯỢNG BỘ NHỚ CHẤP NHẬN ĐƯỢC"
WX78.DESCRIBE.KYNO_COOKWARE_BIG = "CÁI NỒI NÀY CÓ DUNG LƯỢNG BỘ NHỚ CHẤP NHẬN ĐƯỢC"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "CÁI NỒI NÀY CÓ DUNG LƯỢNG BỘ NHỚ KHÔNG ĐẠT"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL = "CÁI NỒI NÀY CÓ DUNG LƯỢNG BỘ NHỚ KHÔNG ĐẠT"
WX78.DESCRIBE.KYNO_COOKWARE_GRILL = "THÊM LỬA VÀO THỨC ĂN SẼ TĂNG GIÁ TRỊ CỦA NÓ"
WX78.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "CẦN LẮP RÁP MỘT PHẦN"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "KHE BỘ NHỚ KHÔNG ĐẠT"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "CẦN LẮP RÁP MỘT PHẦN"
WX78.DESCRIBE.KYNO_COOKWARE_ELDER = "YÊU CẦU SUCROSE VÀ LỬA ĐỂ TẠO THÊM SUCROSE"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "ROBOT NÀY VẪN CHƯA ĐƯỢC XÂY DỰNG"
WX78.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "ĐỂ LẮP RÁP MỘT MỚ HỖN ĐỘN"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "CÁC KHE BỘ NHỚ CỦA NÓ CẦN NÂNG CẤP"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN = "TA NGƯỠNG MỘ CÁI MIỆNG LỬA LỚN CỦA ROBOT NÀY"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "TA NGƯỠNG MỘ CÁI MIỆNG LỬA LỚN CỦA ROBOT NÀY"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "TA NGƯỠNG MỘ CÁI MIỆNG LỬA LỚN CỦA ROBOT NÀY"

WX78.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "LẬT ĐÁ ĐỂ THỰC HIỆN CHỨC NĂNG TÌM KIẾM",
	FLIPPED = "VẬT LIỆU ẨN ĐÃ LỘ RA",
}

WX78.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "PHÁT HIỆN ĐỒ TRÔI DẠT"

WX78.DESCRIBE.KYNO_SUGARFLY = "NÓ NGHĨ NÓ ĐẸP LẮM"
WX78.DESCRIBE.KYNO_SUGARFLYWINGS = "LẤP LÁNH NGŨ SẮC"

WX78.DESCRIBE.KYNO_WATERY_CRATE = "PHÁT HIỆN ĐỒ TRÔI DẠT"

WX78.DESCRIBE.KYNO_TUNACAN = "THỰC PHẨM ĐÓNG KÍN CHÂN KHÔNG"
WX78.DESCRIBE.KYNO_TUNACAN_OPEN = "THỰC PHẨM ĐÃ MỞ KHỎI NIÊM PHONG CHÂN KHÔNG"

WX78.DESCRIBE.KYNO_CANNEDFOOD = "THỰC PHẨM ĐÓNG KÍN CHÂN KHÔNG"
WX78.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "THỰC PHẨM ĐÃ MỞ KHỎI NIÊM PHONG CHÂN KHÔNG"

WX78.DESCRIBE.KYNO_POP = "ĐÂY LÀ VẬT PHẨM TIÊU THỤ SAO?"

WX78.DESCRIBE.KYNO_MYSTERYMEAT = "NÓ LÀ THỊT. CHẲNG CÓ BÍ ẨN GÌ Ở ĐÂY"

WX78.DESCRIBE.KYNO_BOTTLE_SOUL = "HỘP CHỨA LINH HỒN, TA THÍCH MÔ-ĐUN LƯU TRỮ CỦA NÓ"

WX78.DESCRIBE.SOULSTEW = "SÚP LINH HỒN, TA THÍCH THIẾT KẾ CỦA NÓ"

WX78.DESCRIBE.FORTUNECOOKIE = "CHỈ LÀ VÀI TỪ NGU NGỐC VÔ NGHĨA"

WX78.DESCRIBE.HORNOCUPIA = "MẢNH NÀY DÙNG ĐỂ TRA TẤN LŨ THỊT MỀM ĐANG ĐÓI"

WX78.DESCRIBE.CHEESE_YELLOW = "HA HA TA THÍCH DÙNG PHÔ MAI ĐỂ GÀI BẪY"
WX78.DESCRIBE.CHEESE_WHITE = "HA HA TA THÍCH DÙNG PHÔ MAI ĐỂ GÀI BẪY"
WX78.DESCRIBE.CHEESE_KOALEFANT = "HA HA TA THÍCH DÙNG PHÔ MAI ĐỂ GÀI BẪY"

WX78.DESCRIBE.MILK_BOX = "CHẤT LỎNG ĂN ĐƯỢC TỪ ĐỘNG VẬT BẨN THỈU"

WX78.DESCRIBE.WATERCUP = "TA... TA KHÔNG THỂ LÀM ĐƯỢC..."

WX78.DESCRIBE.HONEYJAR = "DÍNH VÀ NGỌT"

WX78.DESCRIBE.CRAB_ARTICHOKE = "THỊT CỦA LŨ THỊT MỀM ĐƯỢC NẤU TỚI ĐỘ HOÀN HẢO"

WX78.DESCRIBE.PEPPERROLLS = "TA SẼ TIÊU THỤ NÓ. TA PHẢI LÀM VẬY"

WX78.DESCRIBE.KYNO_SAPHEALER = "LOẠI BỎ LÂY NHIỄM KHỎI CÁC CHỨC NĂNG HỆ THỐNG CHÍNH"

WX78.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "NĂNG LỰC THUYỀN TRƯỞNG KHÔNG ĐỦ",
	PICKED = "TĂNG TRƯỞNG HỮU CƠ TẠM THỜI VẮNG MẶT",
	BURNING = "ĐỘ TOÀN VẸN CẤU TRÚC ĐÃ BỊ ẢNH HƯỞNG",
}

WX78.DESCRIBE.KYNO_GHOST_PIRATE = "ARRR NGƯƠI LÀ MỘT LINH HỒN KHÔNG YÊN NGHỈ SAO?"

WX78.DESCRIBE.KYNO_BUCKET_EMPTY = "MÔ-ĐUN LƯU TRỮ CHO DỮ LIỆU CHẤT LỎNG"
WX78.DESCRIBE.KYNO_BUCKET_METAL = "HỘP CHỨA CHO CHẤT LỎNG"
WX78.DESCRIBE.KYNO_BUCKET_WATER = "CHẤT LỎNG VÔ DỤNG CHO DẠNG SỐNG SINH HỌC"

WX78.DESCRIBE.KYNO_MILK_BEEFALO = "SỮA TỪ NGUỒN TỰ NHIÊN"
WX78.DESCRIBE.KYNO_MILK_KOALEFANT = "SỮA TỪ NGUỒN TỰ NHIÊN"

WX78.DESCRIBE.KYNO_CAP_DRIED = "TA GHÉT NGOẠI HÌNH CỦA NÓ. NGHỆ THUẬT TỰ NHIÊN THẢM HẠI"

WX78.DESCRIBE.KYNO_PLANTMEAT_DRIED = "PROTEIN ĐÃ KHỬ NƯỚC"

WX78.DESCRIBE.KYNO_BREWBOOK = "THƯ MỤC ĐỒ UỐNG"

WX78.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "PHẦN CỨNG CHỨA RƯỢU",
	BREWING_LONG = "QUY TRÌNH ĐANG Ở GIAI ĐOẠN ĐẦU",
	BREWING_SHORT = "QUY TRÌNH ĐANG GẦN HOÀN TẤT",
	DONE = "Ủ HOÀN TẤT",
	BURNT = "BÌNH CHỨA ĐÃ BỊ PHÁ HỦY",
}

WX78.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "PHẦN CỨNG CÓ KHẢ NĂNG BẢO QUẢN",
	BREWING_LONG = "QUY TRÌNH BẢO QUẢN ĐANG DIỄN RA",
	BREWING_SHORT = "QUY TRÌNH ĐANG GẦN HOÀN TẤT",
	DONE = "BẢO QUẢN HOÀN TẤT",
	BURNT = "LỖI BÌNH CHỨA",
}

WX78.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "BỘ CHUYỂN ĐỔI VÀ LƯU TRỮ MẬT ONG",
	HONEY = "KHO MẬT ONG Ở MỨC CHẤP NHẬN ĐƯỢC",
	NECTAR = "ĐANG XỬ LÝ MẬT HOA",
	BURNING = "LỖI: TÀI NGUYÊN ĐANG CHÁY",
}

WX78.DESCRIBE.KYNO_NECTAR_POD = "YÊU CẦU BỘ CHUYỂN ĐỔI MẬT ONG ĐỂ TRỞ NÊN HỮU DỤNG"

WX78.DESCRIBE.KYNO_OAKTREE_POD = "BÌNH CHỨA NĂNG LƯỢNG ĐA DỤNG"
WX78.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "GÓI NĂNG LƯỢNG SINH HỌC"

WX78.DESCRIBE.KYNO_PIKO = "MÁY THỊT THU THẬP HẠT"
WX78.DESCRIBE.KYNO_PIKO_ORANGE = "MÁY THỊT CÓ THUỘC TÍNH Ủ ĐỒ UỐNG"

WX78.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "DẠNG SỐNG BẤT ĐỘNG BẰNG GỖ",
	CHOPPED = "TRÍCH XUẤT TÀI NGUYÊN HOÀN TẤT",
	BURNING = "CẢNH BÁO: CHÁY",
	BURNT = "MẪU VẬT ĐÃ BỊ PHÁ HỦY",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "DẠNG SỐNG BẤT ĐỘNG BẰNG GỖ BỊ SINH VẬT BẨN THỈU XÂM NHIỄM",
	BURNING = "ĐANG CHẤM DỨT MÔI TRƯỜNG SỐNG",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "BẰNG CHỨNG CỦA MỘT THẢM HỌA BIỂN"

WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "NƠI Ở LỖI THỜI",
	BURNT = "CẤU TRÚC ĐÃ BỊ PHÁ HỦY",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "CẬP NHẬT HỆ THỐNG NHẬN DIỆN MÙI: CÁ TỐI ĐA",
	CRAFTED = "CHẤT LƯỢNG CẤU TRÚC ĐÃ CẢI THIỆN",
	BURNT = "MỨC MÙI KHÔNG THỂ CHẤP NHẬN",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "CƠ SỞ TRAO ĐỔI CÁ",
	OCCUPIED = "NGƯỜI BÁN KHÔNG KHẢ DỤNG",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "TRỘM CẮP LÀ SAI NHƯNG TA ĐOÁN GÃ NÀY SẼ KHÔNG PHIỀN",
	EMPTY = "HÀNG TỒN KHO ĐÃ CẠN",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "LÀ NGƯƠI. KẺ TRAO ĐỔI CÁ TỪNG BÁN HẠT GIỐNG CHO TA"
WX78.DESCRIBE.KYNO_MEADOWISLAND_POND = "ĐẶC ĐIỂM NƯỚC XUẤT HIỆN TỰ NHIÊN"
WX78.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "ĐÓ LÀ MỘT CÁI CÂY NHẠT NHẼO"
WX78.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "BỤI ĐÁ ĐANG TỤ THÀNH ĐỐNG"
WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "CẬP NHẬT HỆ THỐNG NHẬN DIỆN MÙI: TANH CÁ"

WX78.DESCRIBE.KYNO_SAMMYHAT = "MŨ CỦA KẺ TRAO ĐỔI"

WX78.DESCRIBE.KINGFISHER = "MỘT CON CHIM CÓ CƠ CHẾ MỎ LỚN"

WX78.DESCRIBE.TOUCAN = "NGƯƠI CÓ LƯỢNG MŨI QUÁ MỨC"
WX78.DESCRIBE.TOUCAN_CHUBBY = "NGƯƠI CÓ LƯỢNG MŨI QUÁ MỨC"

WX78.DESCRIBE.WETGOOP2 = "CHẤT BẨN ĂN ĐƯỢC"

WX78.DESCRIBE.BEER = "THỨC UỐNG HOÀN HẢO"

WX78.DESCRIBE.PALEALE = "THỨC UỐNG HOÀN HẢO"

WX78.DESCRIBE.TEAGREEN = "CHẤT LỎNG NÀY CÓ THUỘC TÍNH KỲ LẠ LÀM DỊU HỆ THỐNG CỦA TA"

WX78.DESCRIBE.TEARED = "CHẤT LỎNG NÀY CÓ THUỘC TÍNH KỲ LẠ LÀM DỊU HỆ THỐNG CỦA TA"

WX78.DESCRIBE.MEAD = "ĐẮNG VÀ NGỌT"

WX78.DESCRIBE.KYNO_JELLY = "CÓ MỨT TRONG MẠCH ĐIỆN CỦA TA"

WX78.DESCRIBE.KYNO_MAYONNAISE = "BÉO MỊN"

WX78.DESCRIBE.TARTARSAUCE = "KHÔNGGGGGGGGG!"

WX78.DESCRIBE.KYNO_PICKLES = "KINH TỞM"

WX78.DESCRIBE.KYNO_WINE = "ĐẮNG SẢNG KHOÁI"

WX78.DESCRIBE.KYNO_JUICE = "AAHHH"

WX78.DESCRIBE.KYNO_POISON_FROGLEGS = "CẢNH BÁO: CƠ CHẾ CHÂN CHỨA ĐỘC TỐ"
WX78.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "CƠ CHẾ CHÂN ĐỘC HẠI ĐÃ BỊ ĐỐT"

WX78.DESCRIBE.POISONFROGGLEBUNWICH = "NHIÊN LIỆU ẾCH NGON LÀNH"

WX78.DESCRIBE.KYNO_BREWINGRECIPECARD = "LỖI: CÔNG THỨC Ủ KHÔNG ĐỌC ĐƯỢC"

WX78.DESCRIBE.KYNO_OIL = "ĐÓ LÀ DẦU. NHƯNG KHÔNG DÀNH CHO PHẦN CỨNG CỦA TA"

WX78.DESCRIBE.BERRYSUNDAE = "SỮA NGỌT"

WX78.DESCRIBE.CHOCOLATE_BLACK = "SỮA NGỌT"
WX78.DESCRIBE.CHOCOLATE_WHITE = "SỮA NGỌT"

WX78.DESCRIBE.TRICOLORDANGO = "MẤY V-V-VIÊN NGỌT?"
 
WX78.DESCRIBE.FRIESFRENCH = "KHOAI TÂY CHIÊN TRONG DẦU ĐỂ ĐẠT HƯƠNG VỊ TỐI ĐA"

WX78.DESCRIBE.PIRATERUM = "CHẤT LỎNG BÍ ẨN VÀ CÓ THỂ NGUY HIỂM BÊN TRONG"

WX78.DESCRIBE.TWISTEDTEQUILA = "PHÂN TÍCH HỆ THỐNG: CHẤT LỎNG GÂY HIỆU ỨNG KHÔNG GIAN VÀ THỜI GIAN KỲ LẠ"

WX78.DESCRIBE.ONIONRINGS = "NÓ CHỨA LƯỢNG DẦU PHÙ HỢP. VẬY THÌ CHẮC LÀ TỐT"

WX78.DESCRIBE.DONUTS = "BÁNH DONUT BẰNG BỘT. HA"
WX78.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "BÁNH DONUT BẰNG BỘT. MWUHAHA"
WX78.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "BÁNH DONUT BẰNG BỘT. MWUHAHA"
 
WX78.DESCRIBE.CINNAMONROLL = "NÓ LÀ BÁNH ĐƯỜNG CUỘN"

WX78.DESCRIBE.GUMMYBEARGERS = "CẢNH BÁO: MỨC ĐỘ DỄ THƯƠNG NGUY HIỂM"

WX78.DESCRIBE.PRETZEL = "PRETZEL XINH ĐẸP"

WX78.DESCRIBE.CORNINCUP = "BẮP TRONG CỐC"

WX78.DESCRIBE.COTTONCANDY = "THỨC ĂN LÀM TỪ KHÔNG KHÍ"

WX78.DESCRIBE.ROASTEDHAZELNUTS = "TA VỪA NƯỚNG VÀI HẠT. HA HA"

WX78.DESCRIBE.MONSTERMUFFIN = "KHÔNG CÓ Ý ĐỊNH MUFFIN. CHỈ CÓ ÁC ĐỘC"

WX78.DESCRIBE.PINKCAKE = "NÓ QUÁ HỒNG ĐỐI VỚI TA, PHẢI HỦY DIỆT NÓ, BẰNG CÁCH ĂN"

WX78.DESCRIBE.CHIPSBAG = "KHOAI TÂY CÔNG NGHIỆP BÊN TRONG MỘT TÚI KHÍ"

WX78.DESCRIBE.LITTLEBREAD = "NGUYÊN LIỆU CHO CÔNG THỨC TỐT HƠN"

WX78.DESCRIBE.HOTHOUND = "ĐỒ ĂN RÁC KINH ĐIỂN"

WX78.DESCRIBE.MILKSHAKE = "ĐẦU TIÊN TA VẮT SỮA NÓ. SAU ĐÓ TA LẮC NÓ"
WX78.DESCRIBE.MILKSHAKE_PRISMATIC = "ĐẦU TIÊN TA VẮT SỮA NÓ. SAU ĐÓ TA LẮC NÓ"

WX78.DESCRIBE.NACHOS = "TA CÓ XỐT CHẢY VÀ NACHOS"

WX78.DESCRIBE.BANANA_PUDDING = "CHUỐI"

WX78.DESCRIBE.SEA_PUDDING = "TANH CÁ"

WX78.DESCRIBE.TOM_KHA_SOUP = "MÓN SÚP KINH TỞM LÀM TỪ NGUYÊN LIỆU KINH TỞM"

WX78.DESCRIBE.MINERTREAT = "KHÔNG... KHÔNG THỂ... PHIÊN BẢN ĐÓ!"

WX78.DESCRIBE.RADISHSALAD = "LẮP RÁP SALAD: HOÀN TẤT"

WX78.DESCRIBE.PUMPKIN_SOUP = "NĂNG LƯỢNG PIN TRONG MỘT CÁI BÁT"

WX78.DESCRIBE.ALGAE_SOUP = "NĂNG LƯỢNG PIN TRONG MỘT CÁI BÁT"

WX78.DESCRIBE.PARZNIP_SOUP = "NĂNG LƯỢNG PIN TRONG MỘT CÁI BÁT"

WX78.DESCRIBE.NETTLEMEATED = "BỘ PHÓNG CHẤT KÍCH ỨNG MŨI KÈM PHỤ KIỆN THỊT"

WX78.DESCRIBE.KYNO_SUGAR = "NÓ TỐT CHO CÁC MÓN NGỌT"

WX78.DESCRIBE.KYNO_BOTTLECAP = "PHÂN TÍCH HỆ THỐNG: THU NHẬP VÀNG TIỀM NĂNG"

WX78.DESCRIBE.NUKACOLA = "PHÂN TÍCH HỆ THỐNG: NHIÊN LIỆU HẬU TẬN THẾ LIÊN CHIỀU"
WX78.DESCRIBE.NUKACOLA_QUANTUM = "PHÂN TÍCH HỆ THỐNG: NHIÊN LIỆU HẬU TẬN THẾ LIÊN CHIỀU"

WX78.DESCRIBE.LIVINGSANDWICH = "CẢNH BÁO: NHIÊN LIỆU PHÉP THUẬT CÓ VẺ ĐÁNG NGỜ"

WX78.DESCRIBE.DURIANSPLIT = "SỮA NGỌT"

WX78.DESCRIBE.DURIANSOUP = "MÓN Ủ LÀM TỪ SẦU RIÊNG"

WX78.DESCRIBE.DURIANMEATED = "MAY LÀ TA KHÔNG CÓ MŨI"

WX78.DESCRIBE.DURIANCHICKEN = "RAU CỦ LỄ HỘI"

WX78.DESCRIBE.LUNARSOUP = "MẶT TRĂNG SẼ THUỘC VỀ TA"

WX78.DESCRIBE.PURPLEWOBSTERSOUP = "DẠNG SỐNG BẨN THỈU ĐÓ GIỜ LÀ NHIÊN LIỆU CỦA TA"

WX78.DESCRIBE.WOBSTERMONSTER = "DẠNG SỐNG LEVIATHAN"

WX78.DESCRIBE.SPIDERCAKE = "ĐÂY LÀ MỘT QUÁI VẬT KINH KHỦNG"

WX78.DESCRIBE.SUGARBOMBS = "TA ĐANG BẮT ĐẦU CÓ HỒI TƯỞNG KHÔNG THUỘC NGÂN HÀNG KÝ ỨC CỦA TA"

WX78.DESCRIBE.BERRYBOMBS = "QUẢ MỌNG BÊN TRONG ĐƠN VỊ LƯU TRỮ"

WX78.DESCRIBE.ONIGIRIS = "NGŨ CỐC Ở DẠNG TAM GIÁC"

WX78.DESCRIBE.OMURICE = "PHÂN TÍCH HOÀN TẤT: CƠM CHIÊN VỚI XỐT CÀ CHUA TOMA"

WX78.DESCRIBE.PAELLA = "NGŨ CỐC VÀ... ĐANG XỬ LÝ... DẠNG SỐNG BIỂN HẠ ĐẲNG"

WX78.DESCRIBE.RISOTTO = "NGŨ CỐC VÀ NẤM DẠI BẨN THỈU"

WX78.DESCRIBE.RICESAKE = "TRÔNG CHÚNG THẬT NGU NGỐC KHI UỐNG THỨ NÀY"

WX78.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "CÂY ĐÃ BỊ GỠ BỎ"

WX78.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "BỤI TRÁI CÂY CÓ GAI NGU NGỐC VÀ ĐẦN ĐỘN",
	PICKED = "SẢN LƯỢNG TRÁI ĐÃ DỪNG",
	WITHERED = "ĐỘ ẨM KHÔNG ĐỦ",
	BURNING = "CẢNH BÁO: CHÁY",
}

WX78.DESCRIBE.KYNO_PINEAPPLE = "TRÁI CÂY CÓ GAI NGU NGỐC"
WX78.DESCRIBE.KYNO_PINEAPPLE_HALVED = "TRÁI CÂY CÓ GAI NGU NGỐC"
WX78.DESCRIBE.KYNO_PINEAPPLE_COOKED = "GIỜ NÓ VỪA ĐỦ CHẤP NHẬN"

WX78.DESCRIBE.PIZZA_TROPICAL = "ÔI CHỦ NHÂN CỦA TA... CHÚNG ĐÃ LÀM GÌ VỚI NGƯƠI"

WX78.DESCRIBE.PINACOLADA = "ĐƠN GIẢN LÀ KHÔNG THỂ NÀO"

WX78.DESCRIBE.CHIMAS = "HIỆN THÂN CỦA SỰ VÔ VỊ"

WX78.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "HỆ THỐNG CẤP NƯỚC KHÔNG HOẠT ĐỘNG",
	ON = "MỘT LOẠT PHÁO KÍCH CỦA KẺ THÙ!",
}

WX78.DESCRIBE.KYNO_FOODSACK = "KHÓA CHẶT ĐỘ TƯƠI"

WX78.DESCRIBE.GUMMYWORMS = "HA. GIỜ NGƯƠI CẢM THẤY THẾ NÀO?"

WX78.DESCRIBE.SMORES = "HẠT VÀ KẸO DẺO"

WX78.DESCRIBE.NUKASHINE = "THỨC UỐNG NÀY ĐANG CỐ CÀI MÃ ĐỘC VÀO HỆ THỐNG CỦA TA!"

WX78.DESCRIBE.ANTSLOG = "THỨ GHÊ TỞM"

WX78.DESCRIBE.KYNO_WORM_BONE = "HAHA. CÁC ĐƠN VỊ SINH HỌC THẬT MONG MANH"

WX78.DESCRIBE.SPOOKY_BRAIN_NOODLES = "ĂN KÝ ỨC CỦA LŨ THỊT MỀM YẾU ỚT SẼ KHÔNG CẢI THIỆN ĐƯỢC KÝ ỨC CỦA TA"
WX78.DESCRIBE.SPOOKY_BURGERZILLA = "BẢN TÁI TẠO THẤT BẠI CỦA HAMBURGER QUÁI VẬT"
WX78.DESCRIBE.SPOOKY_DEADBREAD = "GIÁ MÀ HẮN CŨNG LÀ MỘT PHẦN NGUYÊN LIỆU"
WX78.DESCRIBE.SPOOKY_JELLYBEANS = "MỘT GÓI MÔ-ĐUN THỊ GIÁC"
WX78.DESCRIBE.SPOOKY_POPSICLE = "ĐỐT CHÚNG ĐI"
WX78.DESCRIBE.SPOOKY_PUMPKINCREAM = "THỨ SÁNG TẠO GỚM GHIẾC GÌ THẾ NÀY"
WX78.DESCRIBE.SPOOKY_SKULLCANDY = "KẸO NGU NGỐC CÓ THỂ ĐƯA LŨ THỊT MỀM YẾU ỚT TRỞ LẠI"
WX78.DESCRIBE.SPOOKY_TACODILE = "HY VỌNG MẸ CỦA CHÚNG KHÔNG ĐUỔI THEO TA"

WX78.DESCRIBE.BUTTER_BEEFALO = "KHỐI ĐẶC CỦA CHẤT LỎNG ĐỘNG VẬT ĐÃ XỬ LÝ"
WX78.DESCRIBE.BUTTER_GOAT = "KHỐI ĐẶC CỦA CHẤT LỎNG ĐỘNG VẬT ĐÃ XỬ LÝ"
WX78.DESCRIBE.BUTTER_KOALEFANT = "KHỐI ĐẶC CỦA CHẤT LỎNG ĐỘNG VẬT ĐÃ XỬ LÝ"

WX78.DESCRIBE.SPICE_CURE = "TIỆN ÍCH FIRMWARE ĐỂ BẢO QUẢN VIÊN NANG NHIÊN LIỆU"
WX78.DESCRIBE.SPICE_COLD = "TIỆN ÍCH LẠNH CHO HỆ THỐNG LÕI"
WX78.DESCRIBE.SPICE_FIRE = "TIỆN ÍCH LỬA CHO HỆ THỐNG LÕI CẢNH BÁO: CÓ THỂ GÂY QUÁ NHIỆT"
WX78.DESCRIBE.SPICE_FED = "CALO CAO ĐỂ HỆ THỐNG LÀM VIỆC NHANH HƠN"
WX78.DESCRIBE.SPICE_MIND = "ỨNG DỤNG LÀM DỊU"

WX78.DESCRIBE.SUGARFLYMUFFIN = "SỰ NGÂY THƠ LÀM TĂNG HƯƠNG VỊ"

WX78.DESCRIBE.EELTACOS = "LŨ LƯƠN ĐÃ HOÀN THÀNH MỤC ĐÍCH CAO HƠN CỦA CHÚNG"

WX78.DESCRIBE.MEATSKILLET = "HÔM NAY CHÚNG TA HƠI LIỀU LĨNH NHỈ?"

WX78.DESCRIBE.MEATWALTZ = "TẠI SAO NGƯỜI PHỤ NỮ NGU NGỐC ĐÓ LẠI THÍCH THỊT SỐNG ĐẾN VẬY"

WX78.DESCRIBE.COMPLETEBREAKFAST = "CHỨA LƯỢNG CALO CAO"

WX78.DESCRIBE.DUMPLINGS = "THỨC ĂN TINH XẢO"

WX78.DESCRIBE.WARLYICEDTEA = "THỨC UỐNG SẢNG KHOÁI LÀM TỪ KẺ THÙ CỦA TA"

WX78.DESCRIBE.WARLYTEA = "CHẤT LỎNG THU ĐƯỢC TỪ MÁY THỊT"

WX78.DESCRIBE.KYNO_TEALEAF = "DẠNG SỐNG HỮU CƠ ĐỂ LÀM CHẤT LỎNG THƯ GIÃN"

WX78.DESCRIBE.KYNO_ITEMSLICER = "LƯỠI DAO DÀY ĐỂ THÁI LÁT"
WX78.DESCRIBE.KYNO_ITEMSLICER_GOLD = "LƯỠI DAO DÀY ĐỂ THÁI LÁT CHUYÊN NGHIỆP"

WX78.DESCRIBE.COXINHA = "BỘ PHẬN BỊ CẮT RỜI CỦA CON VẬT NGU NGỐC ĐÓ"

WX78.DESCRIBE.LAZYDESSERT = "CHÁN. NÓ KHÔNG PHẢI KẸO HIẾM"

WX78.DESCRIBE.CRABKINGFEAST = "BẰNG CÁCH NÀO? BẰNG CÁCH NÀO. THỨ NÀY CÓ THỂ VỪA CÁI NỒI ĐÓ SAO?"

WX78.DESCRIBE.PIENAPPLE = "LŨ HỮU CƠ YẾU ỚT KHÔNG THỂ VƯỢT QUA HỆ THỐNG TIÊU HÓA CỦA TA"

WX78.DESCRIBE.JAWSBREAKER = "MỒI NHỬ CHO CÁC SINH VẬT BIỂN HUNG HÃN"

WX78.DESCRIBE.AVOCADOTOAST = "KINH TỞM"

WX78.DESCRIBE.RICEPUDDING = "HỖN HỢP RAU CỦ KINH TỞM"

WX78.DESCRIBE.SHARKSUSHI = "HA HA LŨ CÁ MẬP NGU NGỐC SẼ KHÔNG DÁM ĐỤNG TỚI THỰC THỂ THƯỢNG ĐẲNG NỮA"

WX78.DESCRIBE.WOBSTERBREADED = "ÁO GIÁP CỦA NGƯƠI KHÔNG GIỮ NGƯƠI AN TOÀN ĐƯỢC"

WX78.DESCRIBE.LAZYPURRITO = "NÓ KINH TỞM NHƯ CON VẬT MÀ NÓ DỰA THEO"

WX78.DESCRIBE.HORCHATA = "NGƯƠI ĐANG ĐÙA TA SAO? NÓ CHỈ LÀ SỮA VÀ ĐÁ"

WX78.DESCRIBE.WOBSTERCOCKTAIL = "THỨC ĂN XA XỈ"

WX78.DESCRIBE.LAVAEEGGBOILED = "PHÂN TÍCH HOÀN TẤT: PHÁT HIỆN LINH KIỆN CHỐNG LỬA"

WX78.DESCRIBE.POMEGRANATETEA = "THỨC UỐNG SẢNG KHOÁI LÀM TỪ KẺ THÙ CỦA TA"

WX78.DESCRIBE.TIRAMISU = "CHỨA CAFFEINE VÀ THUỘC TÍNH KHÔ"

WX78.DESCRIBE.TOADSTOOLCOLA = "TIỆN ÍCH TIÊU THỤ ĐỂ GÂY HỖN LOẠN CHO LƯỠNG CƯ"

WX78.DESCRIBE.TEPACHE = "MỨC ĐƯỜNG ĐÃ TĂNG"

WX78.DESCRIBE.LUNARTEQUILA = "CUỐI CÙNG SỨC MẠNH CỦA MẶT TRĂNG ĐÃ NẰM TRONG TAY TA"

WX78.DESCRIBE.MIMICMOSA = "PHÂN TÍCH: PHÁT HIỆN THUỘC TÍNH NGỤY TRANG"

WX78.DESCRIBE.POMEGRANATEPIE = "BÁNH TRÁI CÂY"

WX78.DESCRIBE.PINEAPPLECAKE = "NÚI ĐƯỜNG TINH KHIẾT"

WX78.DESCRIBE.PASTY_MEAT = "TA CÓ THỂ CHỈ LẤY PHẦN DẦU KHÔNG?"
WX78.DESCRIBE.PASTY_CHEESE = "TA CÓ THỂ CHỈ LẤY PHẦN DẦU KHÔNG?"

WX78.DESCRIBE.BRIGADEIRO = "TA CẦN LỮ ĐOÀN CỦA RIÊNG TA"

WX78.DESCRIBE.REGULARLASAGNA = "ÍT NHẤT NÓ KHÔNG GIỐNG THỨ GHÊ TỞM ĐÓ"

WX78.DESCRIBE.FLTSANDWICH = "CHÚNG ĐÁNG BỊ VẬY"

WX78.DESCRIBE.RICEANDBEANS = "KINH TỞM"

WX78.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP =
{
	GENERIC = "CẤU TRÚC CẦN BẢO TRÌ NGAY LẬP TỨC",
	REPAIRED = "ĐỘ BỀN KẾT CẤU ĐÃ ĐƯỢC KHÔI PHỤC",
	OCCUPIED = "PHÁT HIỆN ĐIỀU KIỆN SỐNG HỮU CƠ DƯỚI TIÊU CHUẨN",
	OCCUPIED_REPAIRED = "THƯƠNG NHÂN HỮU CƠ ĐANG Ở CHẾ ĐỘ TIẾT KIỆM NĂNG LƯỢNG",
}

WX78.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "PHÁT HIỆN VẬT LIỆU HỮU CƠ HIẾM",
	PICKED = "TÀI NGUYÊN ĐÃ CẠN",
	BURNING = "LỖI: TÀI NGUYÊN ĐÃ BỊ THIÊU HỦY",
}

WX78.DESCRIBE.KYNO_TRUFFLES = "ĐÃ THU NHẬN VẬT LIỆU HỮU CƠ GIÁ TRỊ CAO"
WX78.DESCRIBE.KYNO_TRUFFLES_COOKED = "NÂNG CẤP HỮU CƠ HOÀN TẤT"

WX78.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "ĐƠN VỊ TRƯNG BÀY VÔ NGHĨA CHO NHIÊN LIỆU HỮU CƠ",
	FULL = "ĐẦU RA ẨM THỰC CHẤP NHẬN ĐƯỢC",
}

WX78.DESCRIBE.KYNO_SPORECAP = "PHÁT HIỆN Ô NHIỄM HỮU CƠ"
WX78.DESCRIBE.KYNO_SPORECAP_COOKED = "MỨC NGUY HẠI SINH HỌC ĐÃ GIẢM"

WX78.DESCRIBE.KYNO_SPORECAP_DARK = "CHỨA HỢP CHẤT HỮU CƠ CHẾT NGƯỜI"
WX78.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "MỨC Ô NHIỄM KHÔNG THAY ĐỔI"

WX78.DESCRIBE.KYNO_GOLDENAPPLE = "MỘT CỔ VẬT CÓ SỨC MẠNH VÔ SONG"

WX78.DESCRIBE.TRUFFLESGRINDER = "THỊT NẤM CÓ THỂ TIÊU THỤ. ĐẦU RA NĂNG LƯỢNG: CHẤP NHẬN ĐƯỢC"

WX78.DESCRIBE.SPORECAPPIE = "VẬT LIỆU HỮU CƠ NGUY HẠI."

WX78.DESCRIBE.SPORECAP_SKEWERS = "VẬT CHẤT NẤM ĐÃ CHÁY. HỒ SƠ HƯƠNG VỊ: CHẤP NHẬN ĐƯỢC"

WX78.DESCRIBE.TRUFFLEOIL = "CHẤT NHỚT HỮU CƠ DẠNG LỎNG. VÔ DỤNG, NHƯNG TRƠN."

WX78.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "PHẦN MỀM XÂY DỰNG"
WX78.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "CƠ SỞ NHÂN GIỐNG SINH VẬT ƯỚT: ĐANG XÂY DỰNG"

WX78.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "MÔ-ĐUN SINH SẢN CÁ: TRỰC TUYẾN",
	FUEL_HIGH = "MỨC THỨC ĂN TỐI ƯU",
	FUEL_MED = "MỨC THỨC ĂN CHẤP NHẬN ĐƯỢC",
	FUEL_LOW = "CẢNH BÁO: THỨC ĂN SẮP CẠN",
	EMPTY = "LỖI: KHÔNG PHÁT HIỆN THỨC ĂN",
}

WX78.DESCRIBE.AGEDROE = "TA ĐÃ MONG CHÚNG NGỌ NGUẬY. THẤT VỌNG."
WX78.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "PHÁT HIỆN VI CẦU DINH DƯỠNG GIÁ TRỊ CAO"

WX78.DESCRIBE.KYNO_SWORDFISH_BLUE = "LỖI: NĂNG LỰC THỦY SINH ĐÃ MẤT. THẢM HẠI."

WX78.DESCRIBE.KYNO_JELLYFISH = "LŨ THỊT MỀM NÀY CÓ VẺ VẬN HÀNH BẰNG ĐIỆN"
WX78.DESCRIBE.KYNO_JELLYFISH_DEAD = "PHÂN HỦY CÓ LÀM TĂNG KẾT CẤU THẠCH KHÔNG?"
WX78.DESCRIBE.KYNO_JELLYFISH_COOKED = "GIẢM 40% KẾT CẤU THẠCH"
WX78.DESCRIBE.KYNO_JELLYFISH_DRIED = "NÓ ĐÃ ĐƯỢC GIẢM 75% KẾT CẤU THẠCH"

WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "MỘT DẠNG SỐNG VỪA ĐỦ CHẤP NHẬN"
WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "TA THÍCH NÓ HƠN THEO KIỂU NÀY"
WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "NHIÊN LIỆU ROBOT CẦU VỒNG"

WX78.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "BÌNH CHẤT LỎNG BẰNG THỦY TINH"

WX78.DESCRIBE.KYNO_OCEANTRAP = "CHUI VÀO ĐI, MẤY THỨ BIỂN NGU NGỐC"

WX78.DESCRIBE.OCEANFISH_MIDNIGHT_CARP = "PHÁT HIỆN DẠNG SỐNG THỦY SINH HOẠT ĐỘNG VỀ ĐÊM."
WX78.DESCRIBE.OCEANFISH_PUFFERFISH = "MỘT TÚI GAI ĐỘC LƠ LỬNG. TA CHẤP THUẬN."
WX78.DESCRIBE.OCEANFISH_STURGEON = "PHÁT HIỆN ĐƠN VỊ THỦY SINH CỔ ĐẠI. MẪU LỖI THỜI."

WX78.DESCRIBE.KYNO_SWORDFISH = "CÁ CHIẾN ĐẤU"
WX78.DESCRIBE.KYNO_SWORDFISH_DEAD = "SỰ SỐNG KHÔNG ĐÁNG GIÁ"

WX78.DESCRIBE.SWORDFISHFEAST = "ĐƠN VỊ THỊT ĐƯỢC CHUẨN BỊ CHÍNH XÁC. ĐẦU VÀO CHẤP NHẬN ĐƯỢC."

WX78.DESCRIBE.KYNO_DOGFISH = "NÓ BƠI KHÔNG MỤC ĐÍCH"
WX78.DESCRIBE.KYNO_DOGFISH_DEAD = "LŨ THỊT MỀM KHÔNG CÓ CƠ HỘI"

WX78.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "MỌI SỰ SỐNG ĐỀU CHẾT RỒI BỐC MÙI"

WX78.DESCRIBE.WOBSTER_MONKEYISLAND = "ĐƠN VỊ GIÁP XÁC CÓ GIÁP. GIÁ TRỊ BÓNG CAO."
WX78.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "ĐƠN VỊ THỊT: ĐÃ CHẤM DỨT. XUẤT SẮC."
WX78.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "ĐƠN VỊ THỊT: ĐÃ TỐI ƯU HOÀN HẢO ĐỂ NẠP VÀO"

WX78.DESCRIBE.KYNO_PUFFERMONSTER = "BÓNG SINH HỌC ĐẦY ĐỘC TỐ. NGUY HẠI."

WX78.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "BỌT KHÍ TRỒI LÊN TỪ NGUỒN KHÔNG XÁC ĐỊNH"
WX78.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "PHÁT HIỆN MỨC SEROTONIN KHÔNG TỐI ƯU"
WX78.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "PHÁT HIỆN MỨC THÙ HẬN THẦN THOẠI"
WX78.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "PHÁT HIỆN TÍCH TỤ METHANE BẨN THỈU"

WX78.DESCRIBE.KYNO_BLUBBER = "MỠ ĐỘNG VẬT CÓ VÚ ĐA NĂNG"

WX78.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "NGUỒN PROTEIN THỦY SINH ĐÃ KHỬ NƯỚC"
WX78.DESCRIBE.KYNO_FISHMEAT_DRIED = "SẢN PHẨM HẢI SẢN BỀN LÂU"

WX78.DESCRIBE.MONKEYISLANDMEAL = "PHÁT HIỆN NGUỒN NĂNG LƯỢNG GIÁP XÁC HƯƠNG CHUỐI"

WX78.DESCRIBE.KYNO_BRAINROCK_LARVAE = "ĐỪNG CHẠM VÀO TA"
WX78.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "SỰ SỐNG HỮU CƠ CHƯA BÁM RỄ"
WX78.DESCRIBE.KYNO_BRAINROCK_CORAL = "TIÊU THỤ GÂY RA TRẠNG THÁI KÍCH THÍCH TRÍ TUỆ"

WX78.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "GIỐNG SAN HÔ TIẾN HÓA CAO",
	PICKED = "CHỨC NĂNG NHẬN THỨC TẠM THỜI VÔ HIỆU",
}

WX78.DESCRIBE.BRAINMETTERSOUP = "HÀM LƯỢNG DINH DƯỠNG CHO CON NGƯỜI TRẺ"

WX78.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "KẺ GIAO DỊCH NHIỀU TAY",
	SLEEPING = "ĐỐI TƯỢNG KHÔNG HOẠT ĐỘNG",
}

WX78.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "HẮN LÀM SAO ĐỂ LẤP ĐẦY NÓ?"

WX78.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "GIẤY SỞ HỮU ĐƠN VỊ LƯU TRỮ BÊN NGOÀI",
	WAITING = "MỘT CÁ, MỘT CHIM. CÁ VÀNG, CÁ CHẾT",
}

WX78.DESCRIBE.KYNO_PACKIMBAGGIMS = "NGƯƠI ĐƯỢC PHÉP GIỮ ĐỒ CỦA TA, THỊT MỀM"

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "CẦN THÊM NGUYÊN LIỆU ĐỂ LẮP RÁP"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "BÁNH QUÁ KHỔ CẦN THÊM NGUYÊN LIỆU ĐỂ LẮP RÁP"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "MỘT CÁI BÁNH QUÁ KHỔ CHO MỘT ĐÁM ĐÔNG QUÁ KHỔ"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "NGUY CƠ CHÁY. TA CHẤP THUẬN"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "NÓ BỐC MÙI ĂN MỪNG"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "PHÁT HIỆN NHIÊN LIỆU ĂN MỪNG HỮU CƠ"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "TÚI CAO SU BƠM PHỒNG CỦA LỄ MỪNG VÔ NGHĨA"

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "PHÁT HIỆN ĐƠN VỊ GIẢI TRÍ GIÁ RẺ",
	FUEL_HIGH = "MỨC NHIÊN LIỆU TỐI ƯU",
	FUEL_MED = "MỨC NHIÊN LIỆU CHẤP NHẬN ĐƯỢC",
	FUEL_LOW = "CẢNH BÁO: NHIÊN LIỆU THẤP",
	EMPTY = "LỖI: KHÔNG PHÁT HIỆN NHIÊN LIỆU",
}
	
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "HẠT RAU CỦ ĐÃ PHÁT NỔ. CHẤP NHẬN ĐƯỢC"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "PHÁT HIỆN NÓN CHÓP TRANG TRÍ ĐẦU"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "VẬT CHE ĐẦU ĐỘC NHẤT. SAMMY ĐƯỢC ƯU ÁI"

WX78.DESCRIBE.KYNO_FISHREGISTRYHAT = "ĐỒ ĐỘI ĐẦU CHO PHÉP TĂNG KIẾN THỨC NGƯ LOẠI HỌC"

WX78.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "TRẠM TIẾP NHIÊN LIỆU HỮU CƠ",
	FUEL_HIGH = "PHÁT HIỆN MỨC THỨC ĂN TỐI ĐA",
	FUEL_MED = "MỨC THỨC ĂN CHẤP NHẬN ĐƯỢC",
	FUEL_LOW = "CẢNH BÁO: THỨC ĂN SẮP CẠN",
	EMPTY = "LỖI: KHÔNG CÓ THỨC ĂN",
	BURNT = "HỆ THỐNG ĐÃ BỊ LỬA PHÁ HỦY",
}

WX78.DESCRIBE.CHICKENNUGGETS = "ĐƠN VỊ THỊT ĐƯỢC XỬ LÝ THÀNH HÌNH DẠNG GIẢI TRÍ"

WX78.DESCRIBE.CHICKENWINGS = "CẢNH BÁO: ĐẦU RA NHIỆT VƯỢT THÔNG SỐ TỐI ƯU"

WX78.DESCRIBE.CHICKENBURGER = "ĐĨA THỊT ĐƯỢC CHÈN GIỮA ĐỆM CARBOHYDRATE"

WX78.DESCRIBE.CHICKENEGGSOUP = "CHẤT DUY TRÌ SỰ SỐNG DẠNG LỎNG GIÀU PROTEIN"

WX78.DESCRIBE.CHICKENEGGSTEW = "VẬT LIỆU HỮU CƠ LƠ LỬNG TRONG CHẤT LỎNG ĐƯỢC LÀM NÓNG"

WX78.DESCRIBE.CHICKENROTISSERIE = "PROTEIN GIA CẦM XOAY TRÒN BỊ XỬ LÝ NHIỆT"

WX78.DESCRIBE.KYNO_HERMITCRABTEA_ALOE = "CHẤT LỎNG THỰC VẬT ĐƯỢC LÀM NÓNG"
WX78.DESCRIBE.KYNO_HERMITCRABTEA_SUGARTREE_PETALS = "CHẤT LỎNG HOA CÓ ĐƯỜNG"

WX78.DESCRIBE.SOULJUICE = "CHẤT LỎNG HỮU CƠ TRUYỀN LINH HỒN."

WX78.DESCRIBE.KYNO_DAILYRECIPE = "KHÔNG PHÁT HIỆN VẬT TIÊU THỤ ĐƯỢC CHỈ ĐỊNH"
WX78.DESCRIBE.KYNO_DAILYRECIPE_SIGN =
{
	GENERIC = "VẬT TIÊU THỤ ĐƯỢC CHỈ ĐỊNH HÔM NAY: %s",
	NONE = "KHÔNG PHÁT HIỆN VẬT TIÊU THỤ ĐƯỢC CHỈ ĐỊNH",
	BURNING = "PHÁT HIỆN LỖI NHIỆT",
	BURNT = "BIỂN BÁO ĐÃ BỊ CARBON HÓA",
}

WX78.DESCRIBE.KYNO_DECIDUOUSFOREST_SELLER =
{
	GENERIC = "ĐƠN VỊ THƯƠNG NHÂN YÊU CẦU SỬA CHỮA KẾT CẤU",
	HOUSE_REPAIRED = "BẮT ĐẦU TRAO ĐỔI TÀI NGUYÊN",
}

WX78.DESCRIBE.KYNO_CAVETUBERTREE =
{
	GENERIC = "NÓ CẦN NHIỀU HƠN MỘT CHIẾC RÌU THƯỜNG",
	CHOPPED = "MỤC TIÊU ĐÃ BỊ PHÁ HỦY THÀNH CÔNG",
	BLOOMING = "PHÁT HIỆN HOẠT ĐỘNG SINH HỌC",
	BURNING = "QUÁ TRÌNH ĐỐT CHÁY ĐANG DIỄN RA",
	BURNT = "THỰC VẬT BỊ CACBON HÓA",
}

WX78.DESCRIBE.KYNO_CAVETUBER = "VẪN ĐANG TẢI..."
WX78.DESCRIBE.KYNO_CAVETUBER_COOKED = "CHƯA CHÍN VÀ NẤU CHƯA KỸ"

WX78.DESCRIBE.KYNO_CAVETUBER_BLOOMING = "TẢI HOÀN TẤT"
WX78.DESCRIBE.KYNO_CAVETUBER_BLOOMING_COOKED = "TRANG TRÍ QUÁ MỨC KHÔNG THỂ XỬ LÝ"

WX78.DESCRIBE.CAVETUBERTEA = "CHẤT LỎNG TỪ RỄ ĐƯỢC LÀM LẠNH"

WX78.DESCRIBE.KYNO_ELDERMANDRAKEHOUSE =
{
	GENERIC = "NHÀ CỦA THỰC VẬT DI ĐỘNG HIẾU CHIẾN",
	OCCUPIED = "ĐANG Ở CHẾ ĐỘ NGỦ",
}

WX78.DESCRIBE.KYNO_ELDERMANDRAKE =
{
	GENERIC = "THỰC VẬT DI ĐỘNG HIẾU CHIẾN",
	GRUMPY = "KHUYÊN THẬN TRỌNG KHI Ở GẦN ĐƠN VỊ NÀY",
}

WX78.DESCRIBE.MANDRAKEBAOBUNS = "RỄ GÂY BUỒN NGỦ ĐƯỢC NHÉT VÀO BÁNH"

WX78.DESCRIBE.MANDRAKEPIE = "PHÁT HIỆN MÓN TRÁNG MIỆNG TỪ RỄ"