local WORMWOOD = STRINGS.CHARACTERS.WORMWOOD

WORMWOOD.ANNOUNCE_KYNO_COFFEEBUFF_START = "Zooomm!"
WORMWOOD.ANNOUNCE_KYNO_COFFEEBUFF_END = "Speed Out?"

WORMWOOD.ANNOUNCE_KYNO_HASTEBUFF_START = "Zuuum!"
WORMWOOD.ANNOUNCE_KYNO_HASTEBUFF_END = "Where Zooom Go?"

WORMWOOD.ANNOUNCE_KYNO_POPBUFF_START = "(Buurp)"
WORMWOOD.ANNOUNCE_KYNO_POPBUFF_END = "Bubbly Out?"

WORMWOOD.ANNOUNCE_KYNO_FROGBUFF_START = "Froggies!"
WORMWOOD.ANNOUNCE_KYNO_FROGBUFF_END = "No Froggy?"

WORMWOOD.ANNOUNCE_KYNO_PIRATEBUFF_START = "(Buurp)"
WORMWOOD.ANNOUNCE_KYNO_PIRATEBUFF_END = "Bubbly Out?"

WORMWOOD.ANNOUNCE_KYNO_FREEZEBUFF_START = "Brrr"
WORMWOOD.ANNOUNCE_KYNO_FREEZEBUFF_END = "Frost Gone"

WORMWOOD.ANNOUNCE_KYNO_FIREBUFF_START = "Hot!"
WORMWOOD.ANNOUNCE_KYNO_FIREBUFF_END = "Blaze Gone"

WORMWOOD.ANNOUNCE_KYNO_FISHINGBUFF_START = "Fishing Time!"
WORMWOOD.ANNOUNCE_KYNO_FISHINGBUFF_END = "Fish?"

WORMWOOD.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "Relaxing!"
WORMWOOD.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "Relaxing Gone"

WORMWOOD.ANNOUNCE_KYNO_EATERBUFF_START = "Strong Belly!"
WORMWOOD.ANNOUNCE_KYNO_EATERBUFF_END = "Belly Normal?"

WORMWOOD.ANNOUNCE_KYNO_WORMBUFF_START = "Yippie"
WORMWOOD.ANNOUNCE_KYNO_WORMBUFF_END = "Stop?"

WORMWOOD.ANNOUNCE_KYNO_CRABBUFF_START = "Yippie"
WORMWOOD.ANNOUNCE_KYNO_CRABBUFF_END = "Stop?"

WORMWOOD.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(Buurp)"
WORMWOOD.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "Bubbly Out?"

WORMWOOD.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "Feeling Strange"
WORMWOOD.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "Feeling Better"

WORMWOOD.ANNOUNCE_KYNO_STEALTHBUFF_START = "Quiet Now"
WORMWOOD.ANNOUNCE_KYNO_STEALTHBUFF_END = "No More Sneaking?"

WORMWOOD.ANNOUNCE_KYNO_FEARBUFF_START = "Feel... Calm"
WORMWOOD.ANNOUNCE_KYNO_FEARBUFF_END = "Bad Feeling... Here!"

WORMWOOD.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "Feeling Tingly!"
WORMWOOD.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "No More Shiny Power"

WORMWOOD.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "Make Twirly Tail Friends"
WORMWOOD.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "Twirly Tail Gone"

WORMWOOD.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "Rain No Hurt Anymore!"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WORMWOOD.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "No Sick! Feel good!"
WORMWOOD.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "Feel Icky Again"

WORMWOOD.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "Brain Go Big"
WORMWOOD.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "Brain Tired Now"

WORMWOOD.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "Buzz Buzz Are Friend! Yay!"
WORMWOOD.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "Buzz Buzz Mad!"

WORMWOOD.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "Feel Good! Very Good!"
WORMWOOD.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "No More Toughy..."

WORMWOOD.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "Belly grow bigger!"
WORMWOOD.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "Belly small again..."

WORMWOOD.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "Head feel good!"
WORMWOOD.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "Head spin again..."

WORMWOOD.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "Hard! Safe!"
WORMWOOD.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "Soft Again"

WORMWOOD.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "Nope"

WORMWOOD.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "Wants Rocky Glub Glub"

WORMWOOD.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "Friend Too Young?"

WORMWOOD.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "Don't Want?"

WORMWOOD.ANNOUNCE_KYNO_POTHANGER_FAIL = "Wants Something Else"

WORMWOOD.ANNOUNCE_KYNO_CASSEROLE_FAIL = "Not This?"

WORMWOOD.ANNOUNCE_KYNO_SAPHEALER_USED = "Juice Helps Friend!"

WORMWOOD.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "Oh... Stop moving now..."

WORMWOOD.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "All Gone."

WORMWOOD.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "Bubbles Gone?"
WORMWOOD.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "Water fell... Bubbles Gone"
WORMWOOD.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "Big Thing Swimming... Danger?"

WORMWOOD.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "Big Sweet Done!"

WORMWOOD.ANNOUNCE_KYNO_FISH_RESEARCHED = "Glub Glub Told Me Things!"
WORMWOOD.ANNOUNCE_KYNO_ROE_RESEARCHED = "Now Know About Little Glub Glubs"

WORMWOOD.DESCRIBE.KYNO_ROE = "Baby Glub Glubs"
WORMWOOD.DESCRIBE.KYNO_ROE_COOKED = "Tidy rows."

WORMWOOD.DESCRIBE.KYNO_SHARK_FIN = "Water Slicer"

WORMWOOD.DESCRIBE.KYNO_BEANBUGS = "Jumpies"
WORMWOOD.DESCRIBE.KYNO_BEANBUGS_COOKED = "Why not jumping?"

WORMWOOD.DESCRIBE.KYNO_GUMMYBUG = "Slimies"
WORMWOOD.DESCRIBE.KYNO_GUMMYBUG_COOKED = "Hello, teeny sticks!"

WORMWOOD.DESCRIBE.KYNO_WHEAT = "Oh! Pretty seeds!"
WORMWOOD.DESCRIBE.KYNO_WHEAT_COOKED = "Oh! Pretty seeds!"

WORMWOOD.DESCRIBE.KYNO_FLOUR = "Ground stuff"

WORMWOOD.DESCRIBE.KYNO_SPOTSPICE = "Makes belly stuff good"

WORMWOOD.DESCRIBE.KYNO_SAP = "Friend insides are out now"
WORMWOOD.DESCRIBE.KYNO_SAP_SPOILED = "No no no!"

WORMWOOD.DESCRIBE.KYNO_SYRUP = "Makes the sweet stuff"

WORMWOOD.DESCRIBE.KYNO_COFFEEBEANS = "Zoomberries!"
WORMWOOD.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "Smells good"

WORMWOOD.DESCRIBE.DUG_KYNO_COFFEEBUSH = "Zoomberry Friend Needs Dirt"

WORMWOOD.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "Zoomberry friend",
	PICKED = "Empty",
	WITHERED = "Friend Needs Help",
}

WORMWOOD.DESCRIBE.DUG_KYNO_SPOTBUSH = "Hello Friend"

WORMWOOD.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "Friend Has Purple Hair",
	PICKED = "Where Did Friend Hair Go?",
	BURNING = "Friend Hurt!",
}

WORMWOOD.DESCRIBE.KYNO_SPOTSPICE_LEAF = "Little Sprig"

WORMWOOD.DESCRIBE.KYNO_MUSSEL = "Hiding"
WORMWOOD.DESCRIBE.KYNO_MUSSEL_COOKED = "For belly"

WORMWOOD.DESCRIBE.KYNO_HUMANMEAT = "Belly Stuff"
WORMWOOD.DESCRIBE.KYNO_HUMANMEAT_COOKED = "Mmmm..."
WORMWOOD.DESCRIBE.KYNO_HUMANMEAT_DRIED = "Chewy"

WORMWOOD.DESCRIBE.COFFEE = "Wheee!!!"

WORMWOOD.DESCRIBE.BISQUE = "Swimmy belly stuff"

WORMWOOD.DESCRIBE.JELLYOPOP = "Cold Glub Glub Blob"

WORMWOOD.DESCRIBE.SHARKFINSOUP = "Still swimming"

WORMWOOD.DESCRIBE.TROPICALBOUILLABAISSE = "Glub Glubs?"

WORMWOOD.DESCRIBE.MUSSELBOUILLABAISE = "Good for belly"

WORMWOOD.DESCRIBE.SWEETPOTATOSOUFFLE = "Belly stuff"

WORMWOOD.DESCRIBE.FEIJOADA = "Full of Jumpies"

WORMWOOD.DESCRIBE.GUMMY_CAKE = "Squishy"

WORMWOOD.DESCRIBE.HARDSHELL_TACOS = "Crunchy Bzzters"

WORMWOOD.DESCRIBE.ICEDTEA = "Cold Zippy Water"

WORMWOOD.DESCRIBE.NETTLELOSANGE = "Mmm..."

WORMWOOD.DESCRIBE.SNAKEBONESOUP = "Squirmy water"

WORMWOOD.DESCRIBE.STEAMEDHAMSANDWICH = "Egads!"

WORMWOOD.DESCRIBE.TEA = "Warm Zippy Water"

WORMWOOD.DESCRIBE.BUBBLETEA = "Cold Zippy water"

WORMWOOD.DESCRIBE.FRENCHONIONSOUP = "Squirmy water"

WORMWOOD.DESCRIBE.SLAW = "Belly party!"

WORMWOOD.DESCRIBE.LOTUSBOWL = "Good in belly"

WORMWOOD.DESCRIBE.POI = "Belly stuff"

WORMWOOD.DESCRIBE.JELLYBEAN_HUNGER = "Mmmmm!"
WORMWOOD.DESCRIBE.JELLYBEAN_SUPER = "Mmmmm!"
WORMWOOD.DESCRIBE.JELLYBEAN_SANITY = "Mmmmm!"

WORMWOOD.DESCRIBE.BOWLOFGEARS = "Metal stuff"

WORMWOOD.DESCRIBE.LONGPIGMEAL = "Mmm...."

WORMWOOD.DESCRIBE.CUCUMBERSALAD = "Want To Eat It"

WORMWOOD.DESCRIBE.DUG_KYNO_WILDWHEAT = "Friend Needs Dirt"

WORMWOOD.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "Friend",
	PICKED = "Empty",
	WITHERED = "Friend Not Happy",
	BURNING = "Hurts!!",
}

WORMWOOD.DESCRIBE.KYNO_MEALGRINDER = "Stone Machine"

WORMWOOD.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "Friends! Party!",
	PICKED = "Oh. Friends Gone",
	BURNING = "Hurts!",
}

WORMWOOD.DESCRIBE.GORGE_BREAD = "Fluffly"
WORMWOOD.DESCRIBE.GORGE_SWEET_CHIPS = "Chips"
WORMWOOD.DESCRIBE.GORGE_VEGETABLE_SOUP = "Veggies!"
WORMWOOD.DESCRIBE.GORGE_JELLY_SANDWICH = "For Belly"
WORMWOOD.DESCRIBE.GORGE_FISH_STEW = "Fishy"
WORMWOOD.DESCRIBE.GORGE_MEAT_STEW = "For Belly"
WORMWOOD.DESCRIBE.GORGE_ONION_CAKE = "Cake!"
WORMWOOD.DESCRIBE.GORGE_POTATO_PANCAKES = "Where Potato Go?"
WORMWOOD.DESCRIBE.GORGE_POTATO_SOUP = "Swimmy belly stuff"
WORMWOOD.DESCRIBE.GORGE_FISHBALL_SKEWERS = "Fishy"
WORMWOOD.DESCRIBE.GORGE_MEAT_SKEWERS = "Meaty"
WORMWOOD.DESCRIBE.GORGE_STONE_SOUP = "Swimmy belly stuff"
WORMWOOD.DESCRIBE.GORGE_CROQUETTE = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_ROAST_VEGETABLES = "Green Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_MEATLOAF = "Meaty."
WORMWOOD.DESCRIBE.GORGE_CARROT_SOUP = "Swimmy belly stuff"
WORMWOOD.DESCRIBE.GORGE_FISHPIE = "Stuck Fish?"
WORMWOOD.DESCRIBE.GORGE_FISHCHIPS = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_MEATPIE = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_SLIDERS = "Small Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_JELLY_ROLL = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CARROT_CAKE = "Cake!"
WORMWOOD.DESCRIBE.GORGE_GARLICMASHED = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_GARLICBREAD = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_TOMATO_SOUP = "Swimmy belly stuff"
WORMWOOD.DESCRIBE.GORGE_SAUSAGE = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CANDIEDFISH = "Sweet Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_STUFFEDMUSHROOM = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_BRUSCHETTA = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_HAMBURGER = "Burger"
WORMWOOD.DESCRIBE.GORGE_FISHBURGER = "Burger"
WORMWOOD.DESCRIBE.GORGE_MUSHROOMBURGER = "Burger"
WORMWOOD.DESCRIBE.GORGE_FISH_STEAK = "Fishy"
WORMWOOD.DESCRIBE.GORGE_CURRY = "Warm Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_SPAGHETTI = "Balls of Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_POACHEDFISH = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_SHEPHERD_PIE = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CANDY = "Chewy Goo"
WORMWOOD.DESCRIBE.GORGE_BREAD_PUDDING = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_BERRY_TART = "Sweet Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_MACARONI = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_BAGEL_AND_FISH = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_GRILLED_CHEESE = "Yellow Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CREAMMUSHROOM = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_MANICOTTI = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CHEESEBURGER = "Burger"
WORMWOOD.DESCRIBE.GORGE_FETTUCCINE = "White Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_ONION_SOUP = "Stinky Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_BREADED_CUTLET = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CREAMY_FISH = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_PIZZA = "Hmm..."
WORMWOOD.DESCRIBE.GORGE_POT_ROAST = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CRAB_CAKE = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_STEAK_FRITES = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_SHOOTER_SANDWICH = "Shoot?"
WORMWOOD.DESCRIBE.GORGE_BACON_WRAPPED = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CRAB_ROLL = "Crab?"
WORMWOOD.DESCRIBE.GORGE_MEAT_WELLINGTON = "Belly Stuff"
WORMWOOD.DESCRIBE.GORGE_CRAB_RAVIOLI = "Crab?"
WORMWOOD.DESCRIBE.GORGE_CARAMEL_CUBE = "Sweet!"
WORMWOOD.DESCRIBE.GORGE_SCONE = "Sweet"
WORMWOOD.DESCRIBE.GORGE_TRIFLE = "Sweet"
WORMWOOD.DESCRIBE.GORGE_CHEESECAKE = "Cheesy Belly Stuff"

WORMWOOD.DESCRIBE.DUCKYOUGLERMZ = "Yum!"

WORMWOOD.DESCRIBE.KYNO_ALOE = "Clumpy Friend"
WORMWOOD.DESCRIBE.KYNO_ALOE_COOKED = "Squishy"
WORMWOOD.DESCRIBE.KYNO_ALOE_GROUND = "Clumpy Friend"
WORMWOOD.DESCRIBE.KYNO_ALOE_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_ALOE = "Clumpy Friend"
WORMWOOD.DESCRIBE.KYNO_ALOE_OVERSIZED = "Clumpy Friend"
WORMWOOD.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "Nooo!"

WORMWOOD.DESCRIBE.KYNO_CUCUMBER = "Belly Stuff?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_COOKED = "Mmmm... Slimy!"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_GROUND = "Belly Stuff?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "Belly Stuff?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "Belly Stuff?"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "Nooo!"

WORMWOOD.DESCRIBE.KYNO_RADISH = "Red Balls For Belly"
WORMWOOD.DESCRIBE.KYNO_RADISH_COOKED = "Where Green Part Go?"
WORMWOOD.DESCRIBE.KYNO_RADISH_GROUND = "Red Balls For Belly"
WORMWOOD.DESCRIBE.KYNO_RADISH_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_RADISH = "Red Balls For Belly"
WORMWOOD.DESCRIBE.KYNO_RADISH_OVERSIZED = "Red Balls For Belly"
WORMWOOD.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "Nooo!"

WORMWOOD.DESCRIBE.KYNO_FENNEL = "Hello!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_COOKED = "Slurpy"
WORMWOOD.DESCRIBE.KYNO_FENNEL_GROUND = "Hello!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "Hello!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_OVERSIZED = "Hello!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "Nooo!"

WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO = "Sweet Belly Stuff"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "Mmmm..."
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "Sweet Belly Stuff"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "Sweet Belly Stuff"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "Sweet Belly Stuff"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "Nooo!"

WORMWOOD.DESCRIBE.KYNO_PARZNIP = "Thanks, dirt!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_COOKED = "Thanks, dirt!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_EATEN = "Thanks, dirt!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_GROUND = "Thanks, dirt!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_BIG = "Wee Woo!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "Thanks, dirt!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "Thanks, dirt!"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "Nooo!"

WORMWOOD.DESCRIBE.KYNO_TURNIP = "Cute Little Dirt Friend"
WORMWOOD.DESCRIBE.KYNO_TURNIP_COOKED = "Makes Good Belly Stuff"
WORMWOOD.DESCRIBE.KYNO_TURNIP_GROUND = "Cute Little Dirt Friend"
WORMWOOD.DESCRIBE.KYNO_TURNIP_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "Cute Little Dirt Friend"
WORMWOOD.DESCRIBE.KYNO_TURNIP_OVERSIZED = "Cute Little Dirt Friend"
WORMWOOD.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "Nooo!"

WORMWOOD.DESCRIBE.KYNO_RICE = "Little Sprouts"
WORMWOOD.DESCRIBE.KYNO_RICE_COOKED = "Little Sprouts"
WORMWOOD.DESCRIBE.KYNO_RICE_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "Makes the orange belly stuff"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_RICE = "Cute Little Dirt Friend"
WORMWOOD.DESCRIBE.KYNO_RICE_OVERSIZED = "Cute Little Dirt Friend"
WORMWOOD.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "Nooo!"

WORMWOOD.DESCRIBE.KYNO_SEEDS_KIT = "Friends Inside?"

WORMWOOD.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "Rocks That Grows Stuff",
	PICKED = "Snails Gone",
	WITHERED = "No Life",
}

WORMWOOD.DESCRIBE.KYNO_LIMPETS = "Rock Glub Glubs"
WORMWOOD.DESCRIBE.KYNO_LIMPETS_COOKED = "Goes in Belly"

WORMWOOD.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "Hello!",
	PICKED = "Resting",
	BURNING = "Hurts!",
}

WORMWOOD.DESCRIBE.KYNO_LOTUS_ROOT = "Needs Sea"
WORMWOOD.DESCRIBE.KYNO_LOTUS_FLOWER = "Belly stuff!"
WORMWOOD.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "Good in belly"

WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "Yum",
	PICKED = "Gone For Now?",
	BURNING = "Hurts Bad!",
}

WORMWOOD.DESCRIBE.KYNO_SEAWEEDS = "Yum"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_COOKED = "Ball of Sea Yum"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_DRIED = "No More Sea in Sea Yum"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_ROOT = "Needs Sea"

WORMWOOD.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "Hello Friend!",
	PICKED = "Friend Growing Well",
	BURNING = "Hurts!!",
}

WORMWOOD.DESCRIBE.KYNO_TAROROOT_ROOT = "Needs Sea"
WORMWOOD.DESCRIBE.KYNO_TAROROOT = "Mmm... Purple"
WORMWOOD.DESCRIBE.KYNO_TAROROOT_COOKED = "Belly Likes It"

WORMWOOD.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "Hello",
	PICKED = "Friend Is Sleeping",
	BURNING = "Fire!!!",
}

WORMWOOD.DESCRIBE.KYNO_WATERYCRESS_ROOT = "Needs Sea"
WORMWOOD.DESCRIBE.KYNO_WATERYCRESS = "Hello"

WORMWOOD.DESCRIBE.WATERYCRESSBOWL = "Stick Water"

WORMWOOD.DESCRIBE.KYNO_SALT = "Hmm..."

WORMWOOD.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "Food Stick",
	PICKED = "Empty",
	BURNING = "Hurts Stick!",
}

WORMWOOD.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "Stick Is Swimming!"

WORMWOOD.DESCRIBE.CATFOOD = "Cat Food"

WORMWOOD.DESCRIBE.KATFOOD = "Cat Food"

WORMWOOD.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "Friend With Sweet Hair",
	PICKED = "Needs Rest",
	CHOPPED = "Friend Gone",
	BURNING = "Friend Hurts!",
	BURNT = "Gone Forever",
}

WORMWOOD.DESCRIBE.KYNO_BANANA = "Sweet Hair From Friend!"
WORMWOOD.DESCRIBE.KYNO_BANANA_COOKED = "Mmm..."

WORMWOOD.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "Nice Hair!",
	PICKED = "Friend Needs Rest",
	CHOPPED = "Oh No",
	BURNING = "Friend Hurts",
	BURNT = "Friend Is Gone",
}

WORMWOOD.DESCRIBE.KYNO_KOKONUT = "Ball Of Belly Stuff"
WORMWOOD.DESCRIBE.KYNO_KOKONUT_HALVED = "Stuff For Belly"
WORMWOOD.DESCRIBE.KYNO_KOKONUT_COOKED = "Warm."

WORMWOOD.DESCRIBE.BOWLOFPOPCORN = "Pop! Pop!"

WORMWOOD.DESCRIBE.FIGJUICE = "Cold Zippy Water"

WORMWOOD.DESCRIBE.COCONUTWATER = "Sweet Water"

WORMWOOD.DESCRIBE.EYEBALLSPAGHETTI = "Little Eye Food"

WORMWOOD.DESCRIBE.FORGETMELOTS_SEEDS = "Makes the orange belly stuff"

WORMWOOD.DESCRIBE.FIRENETTLES_SEEDS = "Makes the orange belly stuff"

WORMWOOD.DESCRIBE.TILLWEED_SEEDS = "Makes the orange belly stuff"

WORMWOOD.DESCRIBE.KYNO_FLOATILIZER = "Poop! Yay!"

WORMWOOD.DESCRIBE.KYNO_TWIGGYNUTS = "Hmmm..."

WORMWOOD.DESCRIBE.KYNO_REPAIRTOOL = "Fix It Stuff"

WORMWOOD.DESCRIBE.KYNO_KOI = "Pretty Glub Glub"
WORMWOOD.DESCRIBE.KYNO_KOI_COOKED = "Pretty Glub Glub"

WORMWOOD.DESCRIBE.KYNO_TROPICALFISH = "Pretty Glub Glub"
WORMWOOD.DESCRIBE.KYNO_TROPICALFISH_COOKED = "Glub?"

WORMWOOD.DESCRIBE.KYNO_NEONFISH = "Big Lip Glub Glub"
WORMWOOD.DESCRIBE.KYNO_NEONFISH_COOKED = "Fins Are Yummy"

WORMWOOD.DESCRIBE.KYNO_GROUPER = "Purple Glub Glub"
WORMWOOD.DESCRIBE.KYNO_GROUPER_COOKED = "No More Swimming"
 
WORMWOOD.DESCRIBE.KYNO_PIERROTFISH = "Glub Glub"
WORMWOOD.DESCRIBE.KYNO_PIERROTFISH_COOKED = "Glub Glub For Belly"

WORMWOOD.DESCRIBE.KYNO_SALMONFISH = "Glub Glub from ground"
WORMWOOD.DESCRIBE.KYNO_SALMONFISH_COOKED = "Glub Glub For Belly"

WORMWOOD.DESCRIBE.TURF_PINKPARK = "Pink"
WORMWOOD.DESCRIBE.TURF_STONECITY = "Not Dirt"
WORMWOOD.DESCRIBE.TURF_FIELDS = "Dirt"
WORMWOOD.DESCRIBE.TURF_TIDALMARSH = "Squishy Dirt"

WORMWOOD.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "Done!",
	PICKED = "Getting Tasty Rocks",
}

WORMWOOD.DESCRIBE.KYNO_SALTRACK_INSTALLER = "Gets The Tasty Rocks"

WORMWOOD.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "Mean Metal Thing"

WORMWOOD.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "Ground Pinchy Jail"

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "Wrapped Arm Twirly Tail",
	SLEEPING = "Sleeping",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "Sweet Friend!",
	CHOPPED = "Sorry!",
	SAPPED = "Full Of Friend Insides",
	PICKED = "Oh, Friend. Sorry",
	BURNING = "Hurts Bad!",
	BURNT = "Gone...",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "OUCH! Friend Hurt",
	CHOPPED = "Gone",
	SAPPED = "Bad Juice",
	PICKED = "Bugs Hurt friend!",
	BURNING = "Hurts",
	BURNT = "Gone Forever",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_BUD = "Want In Belly? Or Dirt?"

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_FLOWER = "Friend!"
WORMWOOD.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "Friend!"

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_PETALS = "Friend!"

WORMWOOD.DESCRIBE.KYNO_PEBBLECRAB = "Ground Pinchy!"

WORMWOOD.DESCRIBE.KYNO_CRABMEAT = "Branch From Ground Pinchy"
WORMWOOD.DESCRIBE.KYNO_CRABMEAT_COOKED = "Pinchy Makes Good Belly Stuff"
WORMWOOD.DESCRIBE.KYNO_CRABMEAT_DRIED = "Branch From Ground Pinchy"

WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT = "Branch From Ground Pinchy"
WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "Branch From Ground Pinchy"
WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "Branch From Ground Pinchy"

WORMWOOD.DESCRIBE.KYNO_SLAUGHTERTOOL = "Mean Things"

WORMWOOD.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "Ba-gawk!",
	COOP = "Ba-gawk Safe Now",
}

WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG = "Baby Click Click"
WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "Big Click Click Inside?"
WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "Goes In Belly"

WORMWOOD.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "Ba-gawk Home",
	FULL = "Eggs Ready!",
	BURNT = "Ba-gawk Gone?",
}

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "Broken"

WORMWOOD.DESCRIBE.KYNO_COOKWARE_KIT = "Wooden Box"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SYRUP = "Makes Sweet Blubbly"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "Makes Sweet Blubbly"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_BIG_POT = "Hoo! Makes Water Bubbly!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_BIG = "Hoo! Makes Water Bubbly!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "Hoo! Makes Water Bubbly!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL = "Hoo! Makes Water Bubbly!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_GRILL = "Hot Bars!"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "Needs Fire"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "Teeny Hot Bars"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "Needs Fire"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_ELDER = "Makes Sweet Blubbly"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "Makes Belly Stuff Hot"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "Make Belly Stuff Pretty"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "Put Belly Stuff Here"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN = "Gives Food Fire Bath"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "Gives Food Fire Bath"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "Gives Food Fire Bath"

WORMWOOD.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "Things hiding?",
	FLIPPED = "Found Things",
}

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "Wood Drowning!"

WORMWOOD.DESCRIBE.KYNO_SUGARFLY = "A Friend For Friends"
WORMWOOD.DESCRIBE.KYNO_SUGARFLYWINGS = "Not For Flying"

WORMWOOD.DESCRIBE.KYNO_WATERY_CRATE = "Wood Drowning!"

WORMWOOD.DESCRIBE.KYNO_TUNACAN = "Glub Glub Inside?"
WORMWOOD.DESCRIBE.KYNO_TUNACAN_OPEN = "Glub Glub Dead"

WORMWOOD.DESCRIBE.KYNO_CANNEDFOOD = "Belly Stuff Inside?"
WORMWOOD.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "Yum"

WORMWOOD.DESCRIBE.KYNO_POP = "Psht"

WORMWOOD.DESCRIBE.KYNO_MYSTERYMEAT = "Hmm... What Is It?"

WORMWOOD.DESCRIBE.KYNO_BOTTLE_SOUL = "Hmm..."

WORMWOOD.DESCRIBE.SOULSTEW = "Hmm..."

WORMWOOD.DESCRIBE.FORTUNECOOKIE = "Strange Belly Stuff"

WORMWOOD.DESCRIBE.HORNOCUPIA = "Belly Stuffs"

WORMWOOD.DESCRIBE.CHEESE_YELLOW = "Smelly Belly Stuff"
WORMWOOD.DESCRIBE.CHEESE_WHITE = "Smelly Belly Stuff"
WORMWOOD.DESCRIBE.CHEESE_KOALEFANT = "Smelly Belly Stuff"

WORMWOOD.DESCRIBE.MILK_BOX = "Belly Stuff?"

WORMWOOD.DESCRIBE.WATERCUP = "Water"

WORMWOOD.DESCRIBE.HONEYJAR = "Sweet Belly Stuff"

WORMWOOD.DESCRIBE.CRAB_ARTICHOKE = "Tiny Rocks Gone?"

WORMWOOD.DESCRIBE.PEPPERROLLS = "Yummy Bits"

WORMWOOD.DESCRIBE.KYNO_SAPHEALER = "Sick Fixer"

WORMWOOD.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "Save The Wood!",
	PICKED = "Waiting",
	BURNING = "Hurts",
}

WORMWOOD.DESCRIBE.KYNO_GHOST_PIRATE = "Floaty Man"

WORMWOOD.DESCRIBE.KYNO_BUCKET_EMPTY = "Wooden Thing"
WORMWOOD.DESCRIBE.KYNO_BUCKET_METAL = "Metal Thing"
WORMWOOD.DESCRIBE.KYNO_BUCKET_WATER = "Water for Friends"

WORMWOOD.DESCRIBE.KYNO_MILK_BEEFALO = "Moo Moo?"
WORMWOOD.DESCRIBE.KYNO_MILK_KOALEFANT = "Moo Moo?"

WORMWOOD.DESCRIBE.KYNO_CAP_DRIED = "Belly Stuff"

WORMWOOD.DESCRIBE.KYNO_PLANTMEAT_DRIED = "Dried Up Belly Stuff"

WORMWOOD.DESCRIBE.KYNO_BREWBOOK = "Belly Things"

WORMWOOD.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "Wooden Box?",
	BREWING_LONG = "Working",
	BREWING_SHORT = "Almost Ready?",
	DONE = "Ready!",
	BURNT = "Gone",
}

WORMWOOD.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "Wooden Box?",
	BREWING_LONG = "Working",
	BREWING_SHORT = "Almost Ready?",
	DONE = "Ready!",
	BURNT = "Gone",
}

WORMWOOD.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "Buzz juice! Where's Buzz?",
	HONEY = "Sweet Stuff!",
	NECTAR = "Not Ready",
	BURNING = "Hurts!",
}

WORMWOOD.DESCRIBE.KYNO_NECTAR_POD = "Sweet!"

WORMWOOD.DESCRIBE.KYNO_OAKTREE_POD = "Hello"
WORMWOOD.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "Not For Dirt Now"

WORMWOOD.DESCRIBE.KYNO_PIKO = "Fluffy Nabber"
WORMWOOD.DESCRIBE.KYNO_PIKO_ORANGE = "Fluffy Nabber"

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "Sleeping?",
	CHOPPED = "Friend Gave Pieces of Hair",
	BURNING = "Hurts!",
	BURNT = "Gone",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "Sleeping With Friends?",
	BURNING = "Hurts!",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "Wood Friends Made A Box!"

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "Glub Glub Man Home",
	BURNT = "Glub Glub Man Home Gone",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "Glub Glub Man Home",
	CRAFTED = "Better Home",
	BURNT = "Smells Bad",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "Has Many Stuff Inside",
	OCCUPIED = "Sleeping?",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "Stuff",
	EMPTY = "Nothing",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "Hello!"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_POND = "Home for Glub Glub"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "Hello, Little Guy"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "Pile Of Dirt"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "Glub Glub Man"

WORMWOOD.DESCRIBE.KYNO_SAMMYHAT = "Dusty"

WORMWOOD.DESCRIBE.KINGFISHER = "Poke Nose Tweeter"

WORMWOOD.DESCRIBE.TOUCAN = "Big Nose Tweeter"
WORMWOOD.DESCRIBE.TOUCAN_CHUBBY = "Big Nose Tweeter"

WORMWOOD.DESCRIBE.WETGOOP2 = "Yum"

WORMWOOD.DESCRIBE.BEER = "Funny Taste"

WORMWOOD.DESCRIBE.PALEALE = "Funny Taste"

WORMWOOD.DESCRIBE.TEAGREEN = "Mmmm... Ahh"

WORMWOOD.DESCRIBE.TEARED = "Mmmm... Ahh"

WORMWOOD.DESCRIBE.MEAD = "Sweet Belly Stuff"

WORMWOOD.DESCRIBE.KYNO_JELLY = "Sweet Belly Stuff"

WORMWOOD.DESCRIBE.KYNO_MAYONNAISE = "Mmm..."

WORMWOOD.DESCRIBE.TARTARSAUCE = "Spicy Belly Stuff"

WORMWOOD.DESCRIBE.KYNO_PICKLES = "Belly Stuff"

WORMWOOD.DESCRIBE.KYNO_WINE = "Bitter Water"

WORMWOOD.DESCRIBE.KYNO_JUICE = "Sweet Belly Stuff"

WORMWOOD.DESCRIBE.KYNO_POISON_FROGLEGS = "Leggy"
WORMWOOD.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "(sniff, sniff) Smells Okay"

WORMWOOD.DESCRIBE.POISONFROGGLEBUNWICH = "Fills Belly"

WORMWOOD.DESCRIBE.KYNO_BREWINGRECIPECARD = "Hmmm. No good"

WORMWOOD.DESCRIBE.KYNO_OIL = "Belly Stuff?"

WORMWOOD.DESCRIBE.BERRYSUNDAE = "Cool"

WORMWOOD.DESCRIBE.CHOCOLATE_BLACK = "Sweet!"
WORMWOOD.DESCRIBE.CHOCOLATE_WHITE = "Sweet!"

WORMWOOD.DESCRIBE.TRICOLORDANGO = "Sweet"
 
WORMWOOD.DESCRIBE.FRIESFRENCH = "Crunchy"

WORMWOOD.DESCRIBE.PIRATERUM = "Evil?"

WORMWOOD.DESCRIBE.TWISTEDTEQUILA = "Belly Stuff?"

WORMWOOD.DESCRIBE.ONIONRINGS = "Crunchy Onions"

WORMWOOD.DESCRIBE.DONUTS = "Sweet Belly Stuff"
WORMWOOD.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "Sweet Belly Stuff"
WORMWOOD.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "Sweet Belly Stuff"
 
WORMWOOD.DESCRIBE.CINNAMONROLL = "Belly Stuff"

WORMWOOD.DESCRIBE.GUMMYBEARGERS = "Odd"

WORMWOOD.DESCRIBE.PRETZEL = "Belly Stuff"

WORMWOOD.DESCRIBE.CORNINCUP = "Good For Belly"

WORMWOOD.DESCRIBE.COTTONCANDY = "Air?"

WORMWOOD.DESCRIBE.ROASTEDHAZELNUTS = "Nuts!"

WORMWOOD.DESCRIBE.MONSTERMUFFIN = "Strange Belly Stuff"

WORMWOOD.DESCRIBE.PINKCAKE = "Sugar Belly Stuff"

WORMWOOD.DESCRIBE.CHIPSBAG = "Belly Stuff"

WORMWOOD.DESCRIBE.LITTLEBREAD = "Fluffly"

WORMWOOD.DESCRIBE.HOTHOUND = "Where Dog?"

WORMWOOD.DESCRIBE.MILKSHAKE = "Shake!"
WORMWOOD.DESCRIBE.MILKSHAKE_PRISMATIC = "Shake!"

WORMWOOD.DESCRIBE.NACHOS = "Cheesy"

WORMWOOD.DESCRIBE.BANANA_PUDDING = "Nanas"

WORMWOOD.DESCRIBE.SEA_PUDDING = "Fishies?"

WORMWOOD.DESCRIBE.TOM_KHA_SOUP = "Veggies"

WORMWOOD.DESCRIBE.MINERTREAT = "Strange"

WORMWOOD.DESCRIBE.RADISHSALAD = "Want To Eat It"

WORMWOOD.DESCRIBE.PUMPKIN_SOUP = "Swimmy belly stuff"

WORMWOOD.DESCRIBE.ALGAE_SOUP = "Swimmy belly stuff"

WORMWOOD.DESCRIBE.PARZNIP_SOUP = "Swimmy belly stuff"

WORMWOOD.DESCRIBE.NETTLEMEATED = "Mmmm..."

WORMWOOD.DESCRIBE.KYNO_SUGAR = "Sweet Powder"

WORMWOOD.DESCRIBE.KYNO_BOTTLECAP = "Cap"

WORMWOOD.DESCRIBE.NUKACOLA = "Fuzzy"
WORMWOOD.DESCRIBE.NUKACOLA_QUANTUM = "Fuzzy"

WORMWOOD.DESCRIBE.LIVINGSANDWICH = "Strange Bun"

WORMWOOD.DESCRIBE.DURIANSPLIT = "Cool"

WORMWOOD.DESCRIBE.DURIANSOUP = "Squirmy water"

WORMWOOD.DESCRIBE.DURIANMEATED = "Smelly Belly Stuff"

WORMWOOD.DESCRIBE.DURIANCHICKEN = "Belly Stuff"

WORMWOOD.DESCRIBE.LUNARSOUP = "Moon!"

WORMWOOD.DESCRIBE.PURPLEWOBSTERSOUP = "Poor Wobster"

WORMWOOD.DESCRIBE.WOBSTERMONSTER = "Monster"

WORMWOOD.DESCRIBE.SPIDERCAKE = "Spooder Cake"

WORMWOOD.DESCRIBE.SUGARBOMBS = "Kaboom"

WORMWOOD.DESCRIBE.BERRYBOMBS = "Sweet Belly Stuff"

WORMWOOD.DESCRIBE.ONIGIRIS = "Grains"

WORMWOOD.DESCRIBE.OMURICE = "Fried Grains"

WORMWOOD.DESCRIBE.PAELLA = "Grains!"

WORMWOOD.DESCRIBE.RISOTTO = "Grains and Friends"

WORMWOOD.DESCRIBE.RICESAKE = "Grain Water?"

WORMWOOD.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "Friend Needs Soil"

WORMWOOD.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "Hi Friend!",
	PICKED = "Where Did Friend Spikes Go?",
	WITHERED = "Too Dry",
	BURNING = "Friend Hurt!",
}

WORMWOOD.DESCRIBE.KYNO_PINEAPPLE = "Spiky"
WORMWOOD.DESCRIBE.KYNO_PINEAPPLE_HALVED = "Belly Stuff"
WORMWOOD.DESCRIBE.KYNO_PINEAPPLE_COOKED = "Belly Stuff"

WORMWOOD.DESCRIBE.PIZZA_TROPICAL = "Friend?"

WORMWOOD.DESCRIBE.PINACOLADA = "Friend?"

WORMWOOD.DESCRIBE.CHIMAS = "Grass?"

WORMWOOD.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "Helps Friends",
	ON = "Friends Are Happy With Splashy Metal Thing",
}

WORMWOOD.DESCRIBE.KYNO_FOODSACK = "Keeps Belly Stuff Freshy"

WORMWOOD.DESCRIBE.GUMMYWORMS = "Worms?"

WORMWOOD.DESCRIBE.SMORES = "Choco?"

WORMWOOD.DESCRIBE.NUKASHINE = "Odd Drink"

WORMWOOD.DESCRIBE.ANTSLOG = "Woody"

WORMWOOD.DESCRIBE.KYNO_WORM_BONE = "Oh"

WORMWOOD.DESCRIBE.SPOOKY_BRAIN_NOODLES = "Mind?"
WORMWOOD.DESCRIBE.SPOOKY_BURGERZILLA = "Monster!"
WORMWOOD.DESCRIBE.SPOOKY_DEADBREAD = "Fluffy"
WORMWOOD.DESCRIBE.SPOOKY_JELLYBEANS = "Creepy"
WORMWOOD.DESCRIBE.SPOOKY_POPSICLE = "Tasty"
WORMWOOD.DESCRIBE.SPOOKY_PUMPKINCREAM = "Smelly Friend?"
WORMWOOD.DESCRIBE.SPOOKY_SKULLCANDY = "Scary"
WORMWOOD.DESCRIBE.SPOOKY_TACODILE = "Friend?"

WORMWOOD.DESCRIBE.BUTTER_BEEFALO = "Slimy"
WORMWOOD.DESCRIBE.BUTTER_GOAT = "Slimy?"
WORMWOOD.DESCRIBE.BUTTER_KOALEFANT = "Slimy!"

WORMWOOD.DESCRIBE.SPICE_CURE = "Keep Foods Safe"
WORMWOOD.DESCRIBE.SPICE_COLD = "Cold!"
WORMWOOD.DESCRIBE.SPICE_FIRE = "Burn!"
WORMWOOD.DESCRIBE.SPICE_FED = "Hungry"
WORMWOOD.DESCRIBE.SPICE_MIND = "Sleepy"

WORMWOOD.DESCRIBE.SUGARFLYMUFFIN = "Yummm..."

WORMWOOD.DESCRIBE.EELTACOS = "For Belly"

WORMWOOD.DESCRIBE.MEATSKILLET = "For Belly!"

WORMWOOD.DESCRIBE.MEATWALTZ = "For Belly?"

WORMWOOD.DESCRIBE.COMPLETEBREAKFAST = "Big Belly Food"

WORMWOOD.DESCRIBE.DUMPLINGS = "Belly Stuff"

WORMWOOD.DESCRIBE.WARLYICEDTEA = "Cold Zippy Water"

WORMWOOD.DESCRIBE.WARLYTEA = "Warm Zippy Water"

WORMWOOD.DESCRIBE.KYNO_TEALEAF = "Cozy Friend"

WORMWOOD.DESCRIBE.KYNO_ITEMSLICER = "Slicer. For Friend Haircuts"
WORMWOOD.DESCRIBE.KYNO_ITEMSLICER_GOLD = "Slicer. For Friend Haircuts"

WORMWOOD.DESCRIBE.COXINHA = "Belly Stuff"

WORMWOOD.DESCRIBE.LAZYDESSERT = "Rocky"

WORMWOOD.DESCRIBE.CRABKINGFEAST = "Giant!"

WORMWOOD.DESCRIBE.PIENAPPLE = "Friend Has Spiky Hair!"

WORMWOOD.DESCRIBE.JAWSBREAKER = "Hardy"

WORMWOOD.DESCRIBE.AVOCADOTOAST = "Tasty"

WORMWOOD.DESCRIBE.RICEPUDDING = "Blend"

WORMWOOD.DESCRIBE.SHARKSUSHI = "Belly Stuff"

WORMWOOD.DESCRIBE.WOBSTERBREADED = "Snappy Fried Glub Glub"

WORMWOOD.DESCRIBE.LAZYPURRITO = "Silly Cat"

WORMWOOD.DESCRIBE.HORCHATA = "Cold!"

WORMWOOD.DESCRIBE.WOBSTERCOCKTAIL = "Flaming Glub Glub"

WORMWOOD.DESCRIBE.LAVAEEGGBOILED = "Hot!"

WORMWOOD.DESCRIBE.POMEGRANATETEA = "Cold Zippy Water"

WORMWOOD.DESCRIBE.TIRAMISU = "Honk! Honk!"

WORMWOOD.DESCRIBE.TOADSTOOLCOLA = "Smelly Psht"

WORMWOOD.DESCRIBE.TEPACHE = "Sweet Friend Juice"

WORMWOOD.DESCRIBE.LUNARTEQUILA = "Moon Stuff?"

WORMWOOD.DESCRIBE.MIMICMOSA = "Dark Peep Juice"

WORMWOOD.DESCRIBE.POMEGRANATEPIE = "Red Belly Stuff"

WORMWOOD.DESCRIBE.PINEAPPLECAKE = "Belly Stuff"

WORMWOOD.DESCRIBE.PASTY_MEAT = "Crunchy"
WORMWOOD.DESCRIBE.PASTY_CHEESE = "Crunchy"

WORMWOOD.DESCRIBE.BRIGADEIRO = "Flakes"

WORMWOOD.DESCRIBE.REGULARLASAGNA = "For Belly"

WORMWOOD.DESCRIBE.FLTSANDWICH = "Froggy"

WORMWOOD.DESCRIBE.RICEANDBEANS = "Belly Stuff"

WORMWOOD.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "Old House... Maybe New Life... Soon?"

WORMWOOD.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "Friend Grows In Dirt!",
	PICKED = "Gone",
	BURNING = "Friend Hurt!",
}

WORMWOOD.DESCRIBE.KYNO_TRUFFLES = "Smelly friend food."
WORMWOOD.DESCRIBE.KYNO_TRUFFLES_COOKED = "Warm friend food!"

WORMWOOD.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "Show Food To Friends",
	FULL = "Food Looking Nice",
}

WORMWOOD.DESCRIBE.KYNO_SPORECAP = "Friend? Sick Friend..."
WORMWOOD.DESCRIBE.KYNO_SPORECAP_COOKED = "Hot Friend! Better Now?"

WORMWOOD.DESCRIBE.KYNO_SPORECAP_DARK = "Friend Hurts Other Friends"
WORMWOOD.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "Still Hurt Friends"

WORMWOOD.DESCRIBE.KYNO_GOLDENAPPLE = "Shiny!"

WORMWOOD.DESCRIBE.TRUFFLESGRINDER = "Yum! Groundy!"

WORMWOOD.DESCRIBE.SPORECAPPIE = "Mushy Pie"

WORMWOOD.DESCRIBE.SPORECAP_SKEWERS = "Bad Friends... Tasty Now!"

WORMWOOD.DESCRIBE.TRUFFLEOIL = "Smells Strong"

WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "Lake Plans"
WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "Water Home Growing!"

WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "Glub Glub Home",
	FUEL_HIGH = "Glub Glub Happy!",
	FUEL_MED = "Glub Glub Eating",
	FUEL_LOW = "Need Snacks Soon",
	EMPTY = "No More Snacks",
}

WORMWOOD.DESCRIBE.KYNO_ANTCHOVY = "Bug-fishy Friend! Hello!"
WORMWOOD.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "Many bug-fishy friends!"

WORMWOOD.DESCRIBE.AGEDROE = "Glub Glub Babies Trapped?"
WORMWOOD.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "Glub Glub Babies"

WORMWOOD.DESCRIBE.KYNO_SWORDFISH_BLUE = "No Swim Good?"

WORMWOOD.DESCRIBE.KYNO_JELLYFISH = "Glub Glub Blob"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_DEAD = "Poor Blob"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_COOKED = "Blob Hoops"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_DRIED = "Chewy Blob"

WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "Pretty Glub Glub Blob"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "Not Poofy Anymore"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "Pretty Rings"

WORMWOOD.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "Aw. Nothing inside."

WORMWOOD.DESCRIBE.KYNO_OCEANTRAP = "Wet Trap"

WORMWOOD.DESCRIBE.OCEANFISH_PUFFERFISH = "Pokey Glub Glub"
WORMWOOD.DESCRIBE.OCEANFISH_STURGEON = "Old Glub Glub"

WORMWOOD.DESCRIBE.KYNO_SWORDFISH = "Sharpnose Glub Glub"
WORMWOOD.DESCRIBE.KYNO_SWORDFISH_DEAD = "(sob)"

WORMWOOD.DESCRIBE.SWORDFISHFEAST = "Fancy Glub Glub"

WORMWOOD.DESCRIBE.KYNO_DOGFISH = "Glub Glub Woofer"
WORMWOOD.DESCRIBE.KYNO_DOGFISH_DEAD = "Hello, Glub Glub"

WORMWOOD.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "Smells Good. Mmmmm."

WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND = "Shiny Water Friend!"
WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "No More Shiny Moves..."
WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "Friend?"

WORMWOOD.DESCRIBE.KYNO_PUFFERMONSTER = "Pokey Fishy! Don't poke Friend!"

WORMWOOD.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "Glub Glub Or Barrooooo?"
WORMWOOD.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "Barrooooo!"
WORMWOOD.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "Pale Barrooooo"
WORMWOOD.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "Biiiiiig!"

WORMWOOD.DESCRIBE.KYNO_BLUBBER = "Squishy"

WORMWOOD.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "Dry Glub Glub, Mmm!"
WORMWOOD.DESCRIBE.KYNO_FISHMEAT_DRIED = "Dry Glub Glub"

WORMWOOD.DESCRIBE.MONKEYISLANDMEAL = "Glub Glub and Friend"

WORMWOOD.DESCRIBE.KYNO_BRAINROCK_LARVAE = "Needs Rock"
WORMWOOD.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "Cute Baby Wet Rock"
WORMWOOD.DESCRIBE.KYNO_BRAINROCK_CORAL = "Thinking..."

WORMWOOD.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "Thinky Rock",
	PICKED = "Thinky Rock Tired",
}

WORMWOOD.DESCRIBE.BRAINMETTERSOUP = "Thoughtful Belly Stuff"

WORMWOOD.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "Big Arms Guy",
	SLEEPING = "Sleeping",
}

WORMWOOD.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "Stuff From Big Arms Guy!"

WORMWOOD.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "Friend Tweeter Likes You!",
	WAITING = "Where Did Tweeter Go?",
}

WORMWOOD.DESCRIBE.KYNO_PACKIMBAGGIMS = "Friend Tweeter"

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "Needs Stuff"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "Needs More Stuff"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "Its Biiiiiig!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "Light for Biiig Cake"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "Friends..."
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "Sweet Belly Stuff!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "Floaty Friends! Hi!"

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "Pop Maker",
	FUEL_HIGH = "Pop Maker Is Happy",
	FUEL_MED = "Working",
	FUEL_LOW = "Pop Maker Looks Hungry",
	EMPTY = "Empty",
}

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "Pop Pop"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "Party Hat! Whee!"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "Friend Hat!"

WORMWOOD.DESCRIBE.KYNO_FISHREGISTRYHAT = "Fish Knowing Hat"

WORMWOOD.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "Food Place",
	FUEL_HIGH = "Lots Of Food",
	FUEL_MED = "Some Food",
	FUEL_LOW = "Little Food",
	EMPTY = "No Food",
	BURNT = "Gone",
}