local WX78 = STRINGS.CHARACTERS.WX78

WX78.ANNOUNCE_KYNO_COFFEEBUFF_START = "MOVEMENT SPEED: HIGH LEVELS"
WX78.ANNOUNCE_KYNO_COFFEEBUFF_END = "MOVEMENT SPEED: NORMALIZED"

WX78.ANNOUNCE_KYNO_HASTEBUFF_START = "HAND MOVEMENT SPEED: MAXIMUM EFFICIENCY"
WX78.ANNOUNCE_KYNO_HASTEBUFF_END = "CLICKING MOVEMENT SPEED BACK TO NORMAL LEVELS"

WX78.ANNOUNCE_KYNO_POPBUFF_START = "(BUURP) WHAT IN THE...?"
WX78.ANNOUNCE_KYNO_POPBUFF_END = "BUBBLY EFFECTS WERE ERASED"

WX78.ANNOUNCE_KYNO_FROGBUFF_START = "FROGGY MECHANISM: ATTACHED"
WX78.ANNOUNCE_KYNO_FROGBUFF_END = "FROGGY MECHANISM: DEATTACHED"

WX78.ANNOUNCE_KYNO_PIRATEBUFF_START = "(BUURP) READY FOR A RIDE!"
WX78.ANNOUNCE_KYNO_PIRATEBUFF_END = "DRIVEN EFFECTS WERE ERASED"

WX78.ANNOUNCE_KYNO_FREEZEBUFF_START = "WARNING: CORE SYSTEMS ARE COOLING DOWN"
WX78.ANNOUNCE_KYNO_FREEZEBUFF_END = "CORE SYSTEMS BACK TO NORMAL ROUTINE"

WX78.ANNOUNCE_KYNO_FIREBUFF_START = "WARNING: CORE SYSTEMS ARE HEATING UP"
WX78.ANNOUNCE_KYNO_FIREBUFF_END = "CORE SYSTEMS BACK TO NORMAL ROUTINE"

WX78.ANNOUNCE_KYNO_FISHINGBUFF_START = "AJI WO [K]UTTA?"
WX78.ANNOUNCE_KYNO_FISHINGBUFF_END = "WARNING: FISHING ADDON HAS BEEN SHUTDOWN"

WX78.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "DECREASING CLOUD SERVICES ACTIVITY"
WX78.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "CLOUD SERVICES BACK TO NORMAL"

WX78.ANNOUNCE_KYNO_EATERBUFF_START = "DIGESTIVE SYSTEMS BUFFED"
WX78.ANNOUNCE_KYNO_EATERBUFF_END = "DIGESTIVE SYSTEMS BACK TO NORMAL ROUTINE"

WX78.ANNOUNCE_KYNO_WORMBUFF_START = "SYSTEMS READY TO TAKE ON WORMS"
WX78.ANNOUNCE_KYNO_WORMBUFF_END = "SYSTEM OVERDUE: SHUTTING DOWN WORM ATTACK MODULES"

WX78.ANNOUNCE_KYNO_CRABBUFF_START = "SYSTEMS READY TO TAKE ON CRABS"
WX78.ANNOUNCE_KYNO_CRABBUFF_END = "SYSTEM OVERDUE: SHUTTING DOWN CRAB ATTACK MODULES"

WX78.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(BUURP) WHAT IN THE...?"
WX78.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "BUBBLY EFFECTS WERE ERASED"

WX78.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "AAAHH! THE MOON! YESS!!"
WX78.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "NOOOOO! MY POWERS! GIVE IT BACK!"

WX78.ANNOUNCE_KYNO_STEALTHBUFF_START = "SYSTEM CLOAKING MODULE: ON"
WX78.ANNOUNCE_KYNO_STEALTHBUFF_END = "SYSTEM CLOAKING MODULE: OFF"

WX78.ANNOUNCE_KYNO_FEARBUFF_START = "EMOTIONAL RESPONSE: FEAR MODULE DISABLED. SATISFACTORY."
WX78.ANNOUNCE_KYNO_FEARBUFF_END = "FEAR MODULE RE-ENGAGED! MINOR CHASSIS SHAKING DETECTED"

WX78.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "**SYSTEM OVERLOAD**."
WX78.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "POWER LEVELS RETURNING TO MEDIOCRE."

WX78.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "AFFINITY WITH PIGS INCREASED."
WX78.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "PIG AFFINITY TERMINATED."

WX78.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "CORROSIVE MATERIALS NEUTRALIZED."
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WX78.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "BIOLOGICAL TOXINS DISABLED."
WX78.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "IMMUNITY EXPIRED. DISGUSTING ORGANICS THREAT REINSTATED."

WX78.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "SYSTEM UPGRADE: CONSTRUCTION EFFICIENCY INCREASED."
WX78.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "UPGRADE EXPIRED. RETURNING TO DEFAULT DUMB MODE."

WX78.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "HOSTILE BIO-DRONES TEMPORARILY PACIFIED. ACCEPTABLE."
WX78.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "BIO-DRONES RETURNING TO AGGRESSIVE MODE. WARNING."

WX78.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "SYSTEM UPGRADE: STRUCTURAL INTEGRITY INCREASED"
WX78.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "UPGRADE EXPIRED. DISAPPOINTMENT LEVEL RISING"

WX78.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "STORAGE CAPACITY FOR FUEL INCREASED"
WX78.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "FUEL STORAGE DOWNGRADED"

WX78.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "SYSTEM DIAGNOSTIC: BRAINPOWER UPGRADED"
WX78.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "MENTAL UPGRADE EXPIRED"

WX78.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "DEFENSIVE PARAMETERS ENHANCEMENTS ACTIVE."
WX78.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "WARNING: EXTRA DEFENSIVE MEASURES TERMINATED."

WX78.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "WRONG DEPLOYMENT UNIT"

WX78.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "FILTHY CREATURE WANTS SOMETHING ELSE"

WX78.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "STUPID TREE IS TOO SMALL TO HANDLE MY DEVICE"

WX78.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "ERROR: UNKNOWN DEPLOYMENT UNIT"

WX78.ANNOUNCE_KYNO_POTHANGER_FAIL = "REQUIRES A COOKING UNIT"

WX78.ANNOUNCE_KYNO_CASSEROLE_FAIL = "ERROR: MISSING CRUCIAL CASSEROLE UNIT"

WX78.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "HA. HA. ORGANIC LIFEFORM DELETED. HARVEST COMPLETE."

WX78.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "NO VALUABLE CONTENT FOUND. WASTE OF TIME"

WX78.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "TARGET LOST. PATHWAY SUBMERGED."
WX78.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "PRECIPITATION DETECTED. DATA CORRUPTED."
WX78.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "MARINE THREAT DETECTED. EXTERMINATION REQUIRED."

WX78.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "CONSTRUCTION COMPLETE. COMMENCE CELEBRATION PROTOCOLS"

WX78.ANNOUNCE_KYNO_FISH_RESEARCHED = "ANALYSIS COMPLETE. FISH DATA ACQUIRED."
WX78.ANNOUNCE_KYNO_ROE_RESEARCHED = "EGG ANALYSIS COMPLETE. DATA ACQUIRED."

WX78.DESCRIBE.KYNO_ROE = "POTENTIAL AQUATIC INFERIORS"
WX78.DESCRIBE.KYNO_ROE_COOKED = "THEY WERE VULNERABLE AND I DESTROYED THEM HAHAHA"

WX78.DESCRIBE.KYNO_SHARK_FIN = "THE RUDDER OF THE BEAST"

WX78.DESCRIBE.KYNO_BEANBUGS = "NATURE IS ANOMALOUS"
WX78.DESCRIBE.KYNO_BEANBUGS_COOKED = "CONTAINS ENERGY BUT AT WHAT COST?"

WX78.DESCRIBE.KYNO_GUMMYBUG = "SQUISHY ENERGY"
WX78.DESCRIBE.KYNO_GUMMYBUG_COOKED = "HAHA I WILL CONVERT YOU TO ENERGY"

WX78.DESCRIBE.KYNO_WHEAT = "GRAIN DETECTED"
WX78.DESCRIBE.KYNO_WHEAT_COOKED = "TOASTED GRAIN DETECTED"

WX78.DESCRIBE.KYNO_FLOUR = "INITIAL STAGE OF FOOD"

WX78.DESCRIBE.KYNO_SPOTSPICE = "YOU HAVE BEEN CRUSHED, SPRIG"

WX78.DESCRIBE.KYNO_SAP = "DELICIOUS PLANT COOLANT"
WX78.DESCRIBE.KYNO_SAP_SPOILED = "USELESS STICKINESS"

WX78.DESCRIBE.KYNO_SYRUP = "CONTAINS HIGH LEVELS OF STICKINESS"

WX78.DESCRIBE.KYNO_COFFEEBEANS = "DRINKABLE BEANS"
WX78.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "NARCOTIC BEAN HAS REACHED OPTIMUM ROAST LEVEL"

WX78.DESCRIBE.DUG_KYNO_COFFEEBUSH = "DRINKABLE BEAN PLANT"
WX78.DESCRIBE.KYNO_COFFEEBUSH = "DRINKEABLE BEAN PLANT"

WX78.DESCRIBE.DUG_KYNO_SPOTBUSH = "GIVE ME YOUR FOOD, SHRUB"
WX78.DESCRIBE.KYNO_SPOTBUSH = "GIVE ME YOUR FOOD, SHRUB"

WX78.DESCRIBE.KYNO_SPOTSPICE_LEAF = "I WILL CRUSH YOU"

WX78.DESCRIBE.KYNO_MUSSEL = "MUSCULATURE NOT DETECTED"
WX78.DESCRIBE.KYNO_MUSSEL_COOKED = "FLAVOR MOLECULES ARE STRONG"

WX78.DESCRIBE.KYNO_HUMANMEAT = "A FURTHER IMPROVEMENT OF THE HUMAN CONDITION."
WX78.DESCRIBE.KYNO_HUMANMEAT_COOKED = "FINALLY, A PURPOSE FOR THE FLESHY PESTILENCE"
WX78.DESCRIBE.KYNO_HUMANMEAT_DRIED = "NICE AND DRY"

WX78.DESCRIBE.COFFEE = "IT'S JUST HOT BEAN JUICE."

WX78.DESCRIBE.BISQUE = "BATTERY POWER IN A BOWL"

WX78.DESCRIBE.JELLYOPOP = "IT WILL KEEP MY SYSTEMS RUNNING"

WX78.DESCRIBE.SHARKFINSOUP = "APPEARS EDIBLE"

WX78.DESCRIBE.TROPICALBOUILLABAISSE = "THIS WILL FUEL MY SUPERIOR MECHANICAL BODY"

WX78.DESCRIBE.MUSSELBOUILLABAISE = "ACTIVATING TONGUE SENSORS"

WX78.DESCRIBE.SWEETPOTATOSOUFFLE = "OFFENSIVE"

WX78.DESCRIBE.FEIJOADA = "ENERGY PACKETS"

WX78.DESCRIBE.GUMMY_CAKE = "THERE IS NO JOY IN THIS"

WX78.DESCRIBE.HARDSHELL_TACOS = "I WILL CRUSH ITS HARD SHELL"

WX78.DESCRIBE.ICEDTEA = "A REFRESHING DRINK MADE FROM MY ENEMY"

WX78.DESCRIBE.NETTLELOSANGE = "COMPRESSED AIR FOR NASAL UNITS"

WX78.DESCRIBE.SNAKEBONESOUP = "A BREW MADE FROM TWO OF MY ENEMIES"

WX78.DESCRIBE.STEAMEDHAMSANDWICH = "AN UNFORGETTABLE LUNCHEON"

WX78.DESCRIBE.TEA = "LIQUID AQUIRED FROM A MEAT MACHINE"

WX78.DESCRIBE.BUBBLETEA = "A REFRESHING DRINK MADE FROM MY ENEMY"

WX78.DESCRIBE.FRENCHONIONSOUP = "A BREW MADE FROM ONIONS"

WX78.DESCRIBE.SLAW = "SUSTENANCE IDENTIFIED"

WX78.DESCRIBE.LOTUSBOWL = "I HAVE LIBERATED IT FROM ITS GROUND REQUIREMENTS"

WX78.DESCRIBE.POI = "THIS MUNDANE FOOD SHOULD BE EXTINCT"

WX78.DESCRIBE.JELLYBEAN_HUNGER = "TEMPORARY UPGRADE COMPONENTS"
WX78.DESCRIBE.JELLYBEAN_SUPER = "TEMPORARY UPGRADE COMPONENTS"
WX78.DESCRIBE.JELLYBEAN_SANITY = "TEMPORARY UPGRADE COMPONENTS"

WX78.DESCRIBE.BOWLOFGEARS = "YES. NOW THAT'S A PROPER FOOD FOR A SUPERIOR BEING"

WX78.DESCRIBE.LONGPIGMEAL = "IMPROVEMENT OF HUMAN FLESH"

WX78.DESCRIBE.CUCUMBERSALAD = "SALAD ASSEMBLY: COMPLETED"

WX78.DESCRIBE.KYNO_WILDWHEAT = "GRAINS"
WX78.DESCRIBE.DUG_KYNO_WILDWHEAT = "GRAINS"

WX78.DESCRIBE.KYNO_MEALGRINDER = "I AM GOOD AT CRUSHING"

WX78.DESCRIBE.GORGE_BREAD = "INGREDIENT FOR BETTER RECIPES"
WX78.DESCRIBE.GORGE_SWEET_CHIPS = "PIECES OF POTATO SLICED AND FRIED"
WX78.DESCRIBE.GORGE_VEGETABLE_SOUP = "JUST A BUNCH OF VEGGIES GATHERED UP"
WX78.DESCRIBE.GORGE_JELLY_SANDWICH = "ITS JAMMING TO ME"
WX78.DESCRIBE.GORGE_FISH_STEW = "PREPARE FOR CALORIC INTAKE"
WX78.DESCRIBE.GORGE_MEAT_STEW = "NUTRITION ACQUIRED"
WX78.DESCRIBE.GORGE_ONION_CAKE = "DISGUSTING CAKE"
WX78.DESCRIBE.GORGE_POTATO_PANCAKES = "PATHETIC USAGE OF POTATOES"
WX78.DESCRIBE.GORGE_POTATO_SOUP = "BATTERY POWER IN A BOWL"
WX78.DESCRIBE.GORGE_FISHBALL_SKEWERS = "DECENT AMOUNT OF FOOD ON A STICK"
WX78.DESCRIBE.GORGE_MEAT_SKEWERS = "DECENT AMOUNT OF FOOD ON A STICK"
WX78.DESCRIBE.GORGE_STONE_SOUP = "BATTERY POWER IN A BOWL"
WX78.DESCRIBE.GORGE_CROQUETTE = "FLOUR BALLS"
WX78.DESCRIBE.GORGE_ROAST_VEGETABLES = "NASTY"
WX78.DESCRIBE.GORGE_MEATLOAF = "MESCLED FLESH WITH BREAD CRUMBS"
WX78.DESCRIBE.GORGE_CARROT_SOUP = "BATTERY POWER IN A BOWL"
WX78.DESCRIBE.GORGE_FISHPIE = "WEAK LIFEFORMS STUCK IN FLOUR. HA HA."
WX78.DESCRIBE.GORGE_FISHCHIPS = "MORE APPROPRIATE FOOD"
WX78.DESCRIBE.GORGE_MEATPIE = "MEAT CRUSHED DOWN IN A PIE"
WX78.DESCRIBE.GORGE_SLIDERS = "JUNK FOOD"
WX78.DESCRIBE.GORGE_JELLY_ROLL = "TOO SLIMY FOR ME"
WX78.DESCRIBE.GORGE_CARROT_CAKE = "BUT... BUT... I THOUGHT IT WAS JUST A LIE"
WX78.DESCRIBE.GORGE_GARLICMASHED = "DISGUSTING MIX"
WX78.DESCRIBE.GORGE_GARLICBREAD = "A NICE ADDITION"
WX78.DESCRIBE.GORGE_TOMATO_SOUP = "BATTERY POWER IN A BOWL"
WX78.DESCRIBE.GORGE_SAUSAGE = "HA. YOUR END HAS COME"
WX78.DESCRIBE.GORGE_CANDIEDFISH = "THERE'S SYRUP IN MY SYSTEMS"
WX78.DESCRIBE.GORGE_STUFFEDMUSHROOM = "STUFFED"
WX78.DESCRIBE.GORGE_BRUSCHETTA = "NOTHING SPECIAL ABOUT THIS ONE"
WX78.DESCRIBE.GORGE_HAMBURGER = "ONE OF THE FEW HUMANS FOOD THAT IS GREAT"
WX78.DESCRIBE.GORGE_FISHBURGER = "ONE OF THE FEW HUMANS FOOD THAT IS GREAT"
WX78.DESCRIBE.GORGE_MUSHROOMBURGER = "ONE OF THE FEW HUMANS FOOD THAT IS GREAT"
WX78.DESCRIBE.GORGE_FISH_STEAK = "PREPARE FOR CALORIC INTAKE"
WX78.DESCRIBE.GORGE_CURRY = "ITS JUST AN ORDINARY SOUP-LIKE"
WX78.DESCRIBE.GORGE_SPAGHETTI = "MEAT PACKED INTO THE MOST NUTRITIOUS SHAPE: SPHERE"
WX78.DESCRIBE.GORGE_POACHEDFISH = "THAT SALMON IS NOT GOING ANYWHERE ANYMORE"
WX78.DESCRIBE.GORGE_SHEPHERD_PIE = "THERE'S NO SHEEP AROUND HERE"
WX78.DESCRIBE.GORGE_CANDY = "STICKY AND SWEET"
WX78.DESCRIBE.GORGE_BREAD_PUDDING = "CANDY BREAD"
WX78.DESCRIBE.GORGE_BERRY_TART = "OH MY LORD ITS DISGUSTING"
WX78.DESCRIBE.GORGE_MACARONI = "I'M GOING TO LEECH THIS ONE"
WX78.DESCRIBE.GORGE_BAGEL_AND_FISH = "SALMON WITH BREAD HOW ORIGINAL"
WX78.DESCRIBE.GORGE_GRILLED_CHEESE = "PRINT(\"HELLO WORLD\")"
WX78.DESCRIBE.GORGE_CREAMMUSHROOM = "NO, NOT THIS AGAIN"
WX78.DESCRIBE.GORGE_MANICOTTI = "BOOOORING"
WX78.DESCRIBE.GORGE_CHEESEBURGER = "ONE OF THE FEW HUMANS FOOD THAT IS GREAT"
WX78.DESCRIBE.GORGE_FETTUCCINE = "DON'T LOOK ME IN THE EYES AGAIN"
WX78.DESCRIBE.GORGE_ONION_SOUP = "ITS STINKY"
WX78.DESCRIBE.GORGE_BREADED_CUTLET = "MEAT AND BREAD PAIRED TOGETHER"
WX78.DESCRIBE.GORGE_CREAMY_FISH = "SALMON AGAIN? HOW ORIGINAL"
WX78.DESCRIBE.GORGE_PIZZA = "HA. CLASSIC BAIT FOR STUPID HUMANS"
WX78.DESCRIBE.GORGE_POT_ROAST = "THAT'S SIMPLY NOT POSSIBLE"
WX78.DESCRIBE.GORGE_CRAB_CAKE = "THIS SURELY ISN'T ART"
WX78.DESCRIBE.GORGE_STEAK_FRITES = "CLASSIC"
WX78.DESCRIBE.GORGE_SHOOTER_SANDWICH = "SHOOT FOR THE STARS"
WX78.DESCRIBE.GORGE_BACON_WRAPPED = "ITS JUST MEAT WRAPPED WITH MORE MEAT"
WX78.DESCRIBE.GORGE_CRAB_ROLL = "EXTRAORDINAIRE"
WX78.DESCRIBE.GORGE_MEAT_WELLINGTON = "I HAVE MY DOUBTS ABOUT THIS ONE"
WX78.DESCRIBE.GORGE_CRAB_RAVIOLI = "EXTRAORDINAIRE"
WX78.DESCRIBE.GORGE_CARAMEL_CUBE = "A FINE CUBE OF CARAMEL"
WX78.DESCRIBE.GORGE_SCONE = "TOO MUCH SUGAR AAAA"
WX78.DESCRIBE.GORGE_TRIFLE = "TOO MUCH SUGAR AAAA"
WX78.DESCRIBE.GORGE_CHEESECAKE = "WHERE IS THE CHEESE ON IT?"

WX78.DESCRIBE.DUCKYOUGLERMZ = "THAT PLANT NEEDS A REPAIR ON HIS HARDWARE"

WX78.DESCRIBE.KYNO_ALOE = "GREEN ENERGY ACQUIRED"
WX78.DESCRIBE.KYNO_ALOE_COOKED = "GREEN ENERGY FRICASSEED"
WX78.DESCRIBE.KYNO_ALOE_GROUND = "GREEN ENERGY ACQUIRED"
WX78.DESCRIBE.KYNO_ALOE_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.FARM_PLANT_KYNO_ALOE = "GREEN ENERGY ACQUIRED"
WX78.DESCRIBE.KYNO_ALOE_OVERSIZED = "GREEN ENERGY ACQUIRED"
WX78.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_CUCUMBER = "I STOLE IT FROM THE HORRIBLE WATER"
WX78.DESCRIBE.KYNO_CUCUMBER_COOKED = "ENERGY SLOP"
WX78.DESCRIBE.KYNO_CUCUMBER_GROUND = "I STOLE IT FROM THE HORRIBLE WATER"
WX78.DESCRIBE.KYNO_CUCUMBER_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "I STOLE IT FROM THE HORRIBLE WATER"
WX78.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "I STOLE IT FROM THE HORRIBLE WATER"
WX78.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_RADISH = "RED SPHERICAL BALLS OF ENERGY"
WX78.DESCRIBE.KYNO_RADISH_COOKED = "ENERGY ACQUIRED"
WX78.DESCRIBE.KYNO_RADISH_GROUND = "RED SPHERICAL BALLS OF ENERGY"
WX78.DESCRIBE.KYNO_RADISH_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.FARM_PLANT_KYNO_RADISH = "RED SPHERICAL BALLS OF ENERGY"
WX78.DESCRIBE.KYNO_RADISH_OVERSIZED = "RED SPHERICAL BALLS OF ENERGY"
WX78.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_FENNEL = "LOOKS LIKE A ORDINARY PLANT FOR ME."
WX78.DESCRIBE.KYNO_FENNEL_COOKED = "GROSS"
WX78.DESCRIBE.KYNO_FENNEL_GROUND = "LOOKS LIKE A ORDINARY PLANT FOR ME."
WX78.DESCRIBE.KYNO_FENNEL_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "LOOKS LIKE A ORDINARY PLANT FOR ME."
WX78.DESCRIBE.KYNO_FENNEL_OVERSIZED = "LOOKS LIKE A ORDINARY PLANT FOR ME."
WX78.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_SWEETPOTATO = "GROSS"
WX78.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "THE STARCH AND SWEET FIGHT FOR DOMINANCE AND WX-78 LOSES"
WX78.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "GROSS"
WX78.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "GROSS"
WX78.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "GROSS"
WX78.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_PARZNIP = "NUTRITIOUS"
WX78.DESCRIBE.KYNO_PARZNIP_COOKED = "NUTRITIOUS"
WX78.DESCRIBE.KYNO_PARZNIP_EATEN = "NUTRITIOUS"
WX78.DESCRIBE.KYNO_PARZNIP_GROUND = "NUTRITIOUS"
WX78.DESCRIBE.KYNO_PARZNIP_BIG = "SIZE ANALYSIS COMPLETE: GIANT"
WX78.DESCRIBE.KYNO_PARZNIP_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "NUTRITIOUS"
WX78.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "NUTRITIOUS"
WX78.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_TURNIP = "IT'S A DUMB TURNIP"
WX78.DESCRIBE.KYNO_TURNIP_COOKED = "IT IS COOKED EVENLY THROUGHOUT"
WX78.DESCRIBE.KYNO_TURNIP_GROUND = "IT'S A DUMB TURNIP"
WX78.DESCRIBE.KYNO_TURNIP_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "IT'S A DUMB TURNIP"
WX78.DESCRIBE.KYNO_TURNIP_OVERSIZED = "IT'S A DUMB TURNIP"
WX78.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_RICE = "DISGUSTING VEGETABLE"
WX78.DESCRIBE.KYNO_RICE_COOKED = "DISGUSTING VEGETABLE"
WX78.DESCRIBE.KYNO_RICE_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"
WX78.DESCRIBE.FARM_PLANT_KYNO_RICE = "IT'S A DUMB RICE STALK"
WX78.DESCRIBE.KYNO_RICE_OVERSIZED = "IT'S A DUMB RICE STALK"
WX78.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "HAHAHA"

WX78.DESCRIBE.KYNO_SEEDS_KIT = "FILTHY THING"

WX78.DESCRIBE.KYNO_LIMPETROCK = "STUPID MEAT WILL NEVER DEVOUR STONE"
WX78.DESCRIBE.KYNO_LIMPETS = "SMALL PROTEIN SOURCE"
WX78.DESCRIBE.KYNO_LIMPETS_COOKED = "A WELCOME IMPROVEMENT"

WX78.DESCRIBE.KYNO_LOTUS_OCEAN = "ORGANIC UNIT THAT REQUIRES WATER"
WX78.DESCRIBE.KYNO_LOTUS_ROOT = "NOT APPLICABLE OUTSIDE WATER"
WX78.DESCRIBE.KYNO_LOTUS_FLOWER = "UGLY WATER FLOWER"
WX78.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "I HAVE LIBERATED IT FROM ITS WATER REQUIREMENTS"

WX78.DESCRIBE.KYNO_SEAWEEDS_OCEAN = "THE SEA HAS WEEDS TOO?"
WX78.DESCRIBE.KYNO_SEAWEEDS = "IT IS SLIMY AND DISGUSTING"
WX78.DESCRIBE.KYNO_SEAWEEDS_COOKED = "A HEALTHY SNACK"
WX78.DESCRIBE.KYNO_SEAWEEDS_DRIED = "HEALTH FOOD"
WX78.DESCRIBE.KYNO_SEAWEEDS_ROOT = "NOT APPLICABLE OUTSIDE WATER"

WX78.DESCRIBE.KYNO_TAROROOT_OCEAN = "DISGUSTING WATERY PLANT"
WX78.DESCRIBE.KYNO_TAROROOT_ROOT = "NOT APPLICABLE OUTSIDE WATER"
WX78.DESCRIBE.KYNO_TAROROOT = "IT IS SO PURPLE"
WX78.DESCRIBE.KYNO_TAROROOT_COOKED = "FANCY"

WX78.DESCRIBE.KYNO_WATERYCRESS_OCEAN = "DISGUSTING PLANT"
WX78.DESCRIBE.KYNO_WATERYCRESS_ROOT = "NOT APPLICABLE OUTSIDE WATER"
WX78.DESCRIBE.KYNO_WATERYCRESS = "DISGUSTING PLANT"

WX78.DESCRIBE.WATERYCRESSBOWL = "IT IS MADE FROM THE BLOOD OF MY ENEMY"

WX78.DESCRIBE.KYNO_SALT = "BAD FOR CIRCUITRY"

WX78.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "PROTEIN ATTRACTION AND GROWTH SYSTEM"

WX78.DESCRIBE.CATFOOD = "IT IS THE MAIN SOURCE OF ENERGY FOR FELINES."

WX78.DESCRIBE.KATFOOD = "IT IS THE MAIN SOURCE OF ENERGY FOR FELINES."

WX78.DESCRIBE.KYNO_BANANATREE = "I SHOULD HAVE LEFT IT IN THE UNDERGROUND"
WX78.DESCRIBE.KYNO_BANANA = "MORE CARBON"
WX78.DESCRIBE.KYNO_BANANA_COOKED = "THESE FOOD THINGS ARE SO TEDIOUS"

WX78.DESCRIBE.KYNO_KOKONUTTREE = "THIS TREE IS ALL TRUNK"
WX78.DESCRIBE.KYNO_KOKONUT = "DUMB TREE FRUIT"
WX78.DESCRIBE.KYNO_KOKONUT_HALVED = "NUT-RITION NOW ACCESSIBLE"
WX78.DESCRIBE.KYNO_KOKONUT_COOKED = "TOASTY AROMA DOES NOTHING FOR ME"

WX78.DESCRIBE.BOWLOFPOPCORN = "EMPTY CALORIES"

WX78.DESCRIBE.FIGJUICE = "A REFRESHING DRINK MADE FROM STUPID FRUITS"

WX78.DESCRIBE.COCONUTWATER = "THIS WATER CONTAINS A DIFFERENT CODE"

WX78.DESCRIBE.EYEBALLSPAGHETTI = "I THINK IT'S LOOKING AT ME"

WX78.DESCRIBE.FORGETMELOTS_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"

WX78.DESCRIBE.FIRENETTLES_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"

WX78.DESCRIBE.TILLWEED_SEEDS = "IT'S SOURCE CODE FOR FOOD THAT COMES FROM THE DIRT"

WX78.DESCRIBE.KYNO_FLOATILIZER = "BUCKET OF MARINE WASTE"

WX78.DESCRIBE.KYNO_TWIGGYNUTS = "DEEZ NUTS"

WX78.DESCRIBE.KYNO_REPAIRTOOL = "REPAIR UNIT ASSEMBLED"

WX78.DESCRIBE.KYNO_KOI = "I CAN APPRECIATE ITS GOLDEN SHEEN"
WX78.DESCRIBE.KYNO_KOI_COOKED = "I CAN APPRECIATE ITS GOLDEN SHEEN"

WX78.DESCRIBE.KYNO_TROPICALFISH = "YOU ARE TROPICAL AND A FISH"
WX78.DESCRIBE.KYNO_TROPICALFISH_COOKED = "HAHA, GOOD RIDDANCE FOR YOU"

WX78.DESCRIBE.KYNO_NEONFISH = "THIS FISH DRIER THAN THE OTHERS"
WX78.DESCRIBE.KYNO_NEONFISH_COOKED = "I WILL GAIN ITS DRYING POWERS"

WX78.DESCRIBE.KYNO_GROUPER = "I RESCUED IT FROM THE WATER. INGRATE"
WX78.DESCRIBE.KYNO_GROUPER_COOKED = "NOW IT'S ROBOT FUEL. HA HA"
 
WX78.DESCRIBE.KYNO_PIERROTFISH = "IT LIVES SUBMERGED IN WATER. TERRIFYING"
WX78.DESCRIBE.KYNO_PIERROTFISH_COOKED = "I WILL EAT THIS HORRIBLE WATER-DWELLER"

WX78.DESCRIBE.KYNO_SALMONFISH = "FLOPPY WATER CREATURE"
WX78.DESCRIBE.KYNO_SALMONFISH_COOKED = "ITS WEAKNESS IS FIRE"

WX78.DESCRIBE.TURF_PINKPARK = "PINK COLOR IS FLUSHING ME"
WX78.DESCRIBE.TURF_STONECITY = "GROUND PARTS"
WX78.DESCRIBE.TURF_FIELDS = "GROUND PARTS"
WX78.DESCRIBE.TURF_TIDALMARSH = "GROUND PARTS."

WX78.DESCRIBE.KYNO_SALTRACK_INSTALLER = "SOME ASSEMBLY REQUIRED"

WX78.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "FOR SIPHONING COOLANT FROM THE TREES"

WX78.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "ENTRAPS BIOLOGICAL ROCKS"

WX78.DESCRIBE.KYNO_SERENITYISLAND_SHOP = "THIS LARGE SWINE COMMANDS THE SMALLER ONES"

WX78.DESCRIBE.KYNO_SUGARTREE_BUD = "SUGAR CONTAINER UNIT"

WX78.DESCRIBE.KYNO_SUGARTREE_FLOWER = "MY APPRECIATION FOR BEAUTY IS LIMITED"
WX78.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "MY APPRECIATION FOR BEAUTY IS LIMITED"

WX78.DESCRIBE.KYNO_SUGARTREE_PETALS = "MY APPRECIATION FOR BEAUTY IS LIMITED"

WX78.DESCRIBE.KYNO_PEBBLECRAB = "IT'S LIKE A ROCK. BUT ALIVE AND WORSE"

WX78.DESCRIBE.KYNO_CRABMEAT = "MEAT FROM THE ROCK CREATURE"
WX78.DESCRIBE.KYNO_CRABMEAT_COOKED = "DELICIOUS ROCK MEAT"
WX78.DESCRIBE.KYNO_CRABMEAT_DRIED = "MEAT FROM THE ROCK CREATURE"

WX78.DESCRIBE.KYNO_CRABKINGMEAT = "MEAT FROM THE ROCK CREATURE"
WX78.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "MEAT FROM THE ROCK CREATURE"
WX78.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "MEAT FROM THE ROCK CREATURE"

WX78.DESCRIBE.KYNO_SLAUGHTERTOOL = "FOR DISASSEMBLING BIOLOGICAL LIFEFORMS"

WX78.DESCRIBE.KYNO_CHICKEN2 = "ERROR: DOES NOT COMPUTE"

WX78.DESCRIBE.KYNO_CHICKEN_EGG = "I HATE YOU, EGG"
WX78.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "UPGRADED PROTECTIVE SHELL UNIT"
WX78.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "THIS IS SUPPOSED TO BE AN IMPROVEMENT"

WX78.DESCRIBE.KYNO_CHICKENHOUSE = "POULTRY CONTAINMENT STRUCTURE"

WX78.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "PATHETIC. THEY DON'T EVEN KNOW HOW TO BUILD A PROPER POT"

WX78.DESCRIBE.KYNO_COOKWARE_KIT = "A PREMADE KITCHEN TEMPLATE"
WX78.DESCRIBE.KYNO_COOKWARE_SYRUP = "REQUIRES SUCROSE AND FIRE TO CONSTRUCT MORE SUCROSE"
WX78.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "REQUIRES SUCROSE AND FIRE TO CONSTRUCT MORE SUCROSE"
WX78.DESCRIBE.KYNO_COOKWARE_BIG_POT = "THIS POT HAS AN ACCEPTABLE MEMORY SIZE"
WX78.DESCRIBE.KYNO_COOKWARE_BIG = "THIS POT HAS AN ACCEPTABLE MEMORY SIZE"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "THIS POT HAS INADEQUATE MEMORY SIZE"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL = "THIS POT HAS INADEQUATE MEMORY SIZE"
WX78.DESCRIBE.KYNO_COOKWARE_GRILL = "ADDING FIRE TO FOOD INCREASES ITS VALUE"
WX78.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "SOME ASSEMBLY REQUIRED"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "INADEQUATE MEMORY SLOTS"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "SOME ASSEMBLY REQUIRED"
WX78.DESCRIBE.KYNO_COOKWARE_ELDER = "REQUIRES SUCROSE AND FIRE TO CONSTRUCT MORE SUCROSE"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "THIS ROBOT HAS NOT BEEN BUILT YET"
WX78.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "FOR ASSEMBLING A MISHMASH"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "ITS MEMORY SLOTS REQUIRE UPGRADE"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN = "I ADMIRE THIS ROBOT'S LARGE FIRE MOUTH"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "I ADMIRE THIS ROBOT'S LARGE FIRE MOUTH"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "I ADMIRE THIS ROBOT'S LARGE FIRE MOUTH"

WX78.DESCRIBE.KYNO_ROCKFLIPPABLE = "FLIP ROCK TO PERFORM SEARCH FUNCTION"
WX78.DESCRIBE.KYNO_ROCKFLIPPABLE_CAVE = "FLIP ROCK TO PERFORM SEARCH FUNCTION"

WX78.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "JETSAM DETECTED"

WX78.DESCRIBE.KYNO_SUGARFLY = "IT THINK ITS SO PRETTY"
WX78.DESCRIBE.KYNO_SUGARFLYWINGS = "IRIDESCENT"

WX78.DESCRIBE.KYNO_WATERY_CRATE = "JETSAM DETECTED"

WX78.DESCRIBE.KYNO_TUNACAN = "HERMETICALLY SEALED FOODSTUFFS"
WX78.DESCRIBE.KYNO_TUNACAN_OPEN = "HERMETICALLY UNSEALED FOODSTUFFS"

WX78.DESCRIBE.KYNO_CANNEDFOOD = "HERMETICALLY SEALED FOODSTUFFS"
WX78.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "HERMETICALLY UNSEALED FOODSTUFFS"

WX78.DESCRIBE.KYNO_POP = "IS THIS A CONSUMABLE?"

WX78.DESCRIBE.KYNO_MYSTERYMEAT = "IT IS MEAT. NO MYSTERY THERE"

WX78.DESCRIBE.KYNO_BOTTLE_SOUL = "A SOUL-CASE, I LIKE ITS STORAGE MODULE"

WX78.DESCRIBE.SOULSTEW = "A SOUL-SOUP, I LIKE ITS DESIGN"

WX78.DESCRIBE.FORTUNECOOKIE = "JUST SOME STUPID WORDS WITH NO MEANING"

WX78.DESCRIBE.HORNOCUPIA = "THIS PIECE IS FOR TORTURING HUNGRY FLESHLINGS"

WX78.DESCRIBE.CHEESE_YELLOW = "HA HA I LOVE CHEESING THINGS"
WX78.DESCRIBE.CHEESE_WHITE = "HA HA I LOVE CHEESING THINGS"
WX78.DESCRIBE.CHEESE_KOALEFANT = "HA HA I LOVE CHEESING THINGS"

WX78.DESCRIBE.MILK_BOX = "EDIBLE FLUID FROM FILTHY ANIMALS"

WX78.DESCRIBE.WATERCUP = "I... I JUST CAN'T DO IT..."

WX78.DESCRIBE.HONEYJAR = "STICKY AND SWEETY"

WX78.DESCRIBE.CRAB_ARTICHOKE = "FLESHLINGS MEAT COOKED TO PERFECTION"

WX78.DESCRIBE.PEPPERROLLS = "I WILL CONSUME IT. I MUST"

WX78.DESCRIBE.KYNO_SAPHEALER = "ERADICATES CONTAGIONS FROM MAIN SYSTEM FUNCTIONS"

WX78.DESCRIBE.KYNO_OCEAN_WRECK = "INSUFFICIENT CAPTAINING"

WX78.DESCRIBE.KYNO_GHOST_PIRATE = "ARRR YOU A RESTLESS SOUL?"

WX78.DESCRIBE.KYNO_BUCKET_EMPTY = "STORAGE MODULE FOR LIQUID-WARE"
WX78.DESCRIBE.KYNO_BUCKET_METAL = "STORAGE CASE FOR LIQUIDS"
WX78.DESCRIBE.KYNO_BUCKET_WATER = "USELESS LIQUID FOR BIOLOGICAL LIFEFORMS"

WX78.DESCRIBE.KYNO_MILK_BEEFALO = "MILK FROM NATURAL SOURCES"
WX78.DESCRIBE.KYNO_MILK_KOALEFANT = "MILK FROM NATURAL SOURCES"

WX78.DESCRIBE.KYNO_CAP_DRIED = "I HATE HOW IT LOOKS. POOR NATURE ART"

WX78.DESCRIBE.KYNO_PLANTMEAT_DRIED = "DEHYDRATED PROTEINS"

WX78.DESCRIBE.KYNO_BREWBOOK = "DIRECTORY OF BEVERAGES"

WX78.DESCRIBE.KYNO_WOODENKEG = "A LIQUOR HARDWARE"

WX78.DESCRIBE.KYNO_PRESERVESJAR = "HARDWARE WITH PRESERVING CAPABILITIES"

WX78.DESCRIBE.KYNO_ANTCHEST = "HONEY CONVERTER"

WX78.DESCRIBE.KYNO_NECTAR_POD = "REQUIRES HONEY CONVERTER TO BECOME USEFUL"

WX78.DESCRIBE.KYNO_OAKTREE_POD = "MULTI-USE ENERGY CONTAINER"
WX78.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "BIOLOGICAL ENERGY PACKET"

WX78.DESCRIBE.KYNO_PIKO = "A NUT GATHERING MEAT MACHINE"
WX78.DESCRIBE.KYNO_PIKO_ORANGE = "MEAT MACHINE WITH BREWING PROPERTIES"

WX78.DESCRIBE.KYNO_MEADOWISLAND_TREE = "WOODEN IMMOBILE LIFEFORM"
WX78.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = "WOODEN IMMOBILE LIFEFORM INFESTED WITH FILTHY ORGANISMS"
WX78.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "EVIDENCE OF A SEA CALAMITY"
WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = "OUTDATED ABODE"
WX78.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = "AROMA INDENTIFICATION SYSTEM UPDATE: FISH MAX"
WX78.DESCRIBE.KYNO_MEADOWISLAND_SHOP = "FISH BARTERER FACILITY"
WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = "STEALING IS WRONG BUT I GUESS THIS DUDE WOULDN'T MIND"
WX78.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "ITS YOU. THE FISH BARTERER THAT SOLD ME SEEDS ONCE"
WX78.DESCRIBE.KYNO_MEADOWISLAND_POND = "NATURALLY OCURRING WATER FEATURE"
WX78.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "IT IS AN UNINTERESTING PLANT"
WX78.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "THE ROCK DUST IS COLLECTING IN PILES"
WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "AROMA INDENTIFICATION SYSTEM UPDATE: FISHY"

WX78.DESCRIBE.KYNO_SAMMYHAT = "BARTERER HAT"

WX78.DESCRIBE.KINGFISHER = "A BIRD WITH LARGE BEAK MECHANISM"

WX78.DESCRIBE.TOUCAN = "YOU HAVE AN INORDINATE AMOUNT OF NOSE"
WX78.DESCRIBE.TOUCAN_CHUBBY = "YOU HAVE AN INORDINATE AMOUNT OF NOSE"

WX78.DESCRIBE.WETGOOP2 = "EDIBLE FILTH"

WX78.DESCRIBE.BEER = "THE PERFECT DRINK"

WX78.DESCRIBE.PALEALE = "THE PERFECT DRINK"

WX78.DESCRIBE.TEAGREEN = "THIS LIQUID HAS STRANGE PROPERTIES THAT SOOTHS MY SYSTEMS"

WX78.DESCRIBE.TEARED = "THIS LIQUID HAS STRANGE PROPERTIES THAT SOOTHS MY SYSTEMS"

WX78.DESCRIBE.MEAD = "BITTER AND SWEET"

WX78.DESCRIBE.KYNO_JELLY = "THERE'S JAM IN MY CIRCUITRY"

WX78.DESCRIBE.KYNO_MAYONNAISE = "CREAMY"

WX78.DESCRIBE.TARTARSAUCE = "NOOOOOOOOO!"

WX78.DESCRIBE.KYNO_PICKLES = "DISGUSTING"

WX78.DESCRIBE.KYNO_WINE = "BITTER REFRESHING"

WX78.DESCRIBE.KYNO_JUICE = "AAHHH"

WX78.DESCRIBE.KYNO_POISON_FROGLEGS = "WARNING: LEG MECHANISM CONTAIN TOXIN"
WX78.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "BURNT TOXIC LEG MECHANISM"

WX78.DESCRIBE.POISONFROGGLEBUNWICH = "DELICIOUS FROG FUEL"

WX78.DESCRIBE.KYNO_BREWINGRECIPECARD = "ERROR: BREWING RECIPE UNREADABLE"

WX78.DESCRIBE.KYNO_OIL = "IT'S OIL. BUT NOT FOR MY HARDWARE"

WX78.DESCRIBE.BERRYSUNDAE = "SWEET DAIRY"

WX78.DESCRIBE.CHOCOLATE_BLACK = "SWEET DAIRY"
WX78.DESCRIBE.CHOCOLATE_WHITE = "SWEET DAIRY"

WX78.DESCRIBE.TRICOLORDANGO = "SWEET B-B-BALLS?"
 
WX78.DESCRIBE.FRIESFRENCH = "POTATOES FRIED IN OIL TO ACHIEVE MAXIMUM FLAVOUR"

WX78.DESCRIBE.PIRATERUM = "MYSTERIOUS AND POSSIBLE DANGEROUS LIQUID INSIDE"

WX78.DESCRIBE.TWISTEDTEQUILA = "SYSTEM ANALYSIS: LIQUID INDUCES STRANGE SPACE AND TIME EFFECTS"

WX78.DESCRIBE.ONIONRINGS = "IT CONTAINS APPROPRIATE AMOUNT OF OIL. MUST BE GOOD THEN"

WX78.DESCRIBE.DONUTS = "DOUGH DONUTS. HA"
WX78.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "DOUGH DONUTS. MWUHAHA"
WX78.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "DOUGH DONUTS. MWUHAHA"
 
WX78.DESCRIBE.CINNAMONROLL = "ITS A SUGAR BUN"

WX78.DESCRIBE.GUMMYBEARGERS = "WARNING: DANGEROUS LEVELS OF CUTENESS"

WX78.DESCRIBE.PRETZEL = "PRETTY PRETZEL"

WX78.DESCRIBE.CORNINCUP = "CUPPED CORN"

WX78.DESCRIBE.COTTONCANDY = "FOOD MADE OUT OF AIR"

WX78.DESCRIBE.ROASTEDHAZELNUTS = "I JUST ROASTED SOME NUTS. HA HA"

WX78.DESCRIBE.MONSTERMUFFIN = "NO MUFFIN INTENDED. EVIL ONLY"

WX78.DESCRIBE.PINKCAKE = "ITS TOO PINK FOR ME, MUST DESTROY IT, BY EATING"

WX78.DESCRIBE.CHIPSBAG = "MANUFACTURED POTATOES INSIDE A BAG OF AIR"

WX78.DESCRIBE.LITTLEBREAD = "INGREDIENT FOR BETTER RECIPES"

WX78.DESCRIBE.HOTHOUND = "CLASSIC JUNK FOOD"

WX78.DESCRIBE.MILKSHAKE = "FIRST I MILKED IT. THEN I SHAKED IT"
WX78.DESCRIBE.MILKSHAKE_PRISMATIC = "FIRST I MILKED IT. THEN I SHAKED IT"

WX78.DESCRIBE.NACHOS = "I GOT THE DRIP AND THE NACHOS"

WX78.DESCRIBE.BANANA_PUDDING = "NANAS"

WX78.DESCRIBE.SEA_PUDDING = "FISHY"

WX78.DESCRIBE.TOM_KHA_SOUP = "DISGUSTING SOUP MADE WITH DISGUSTING INGREDIENTS"

WX78.DESCRIBE.MINERTREAT = "NO... IT CAN BE... THAT VERSION!"

WX78.DESCRIBE.RADISHSALAD = "SALAD ASSEMBLY: COMPLETED"

WX78.DESCRIBE.PUMPKIN_SOUP = "BATTERY POWER IN A BOWL"

WX78.DESCRIBE.ALGAE_SOUP = "BATTERY POWER IN A BOWL"

WX78.DESCRIBE.PARZNIP_SOUP = "BATTERY POWER IN A BOWL"

WX78.DESCRIBE.NETTLEMEATED = "NOSE IRRITANT EJECTOR WITH MEAT ATTATCHMENT"

WX78.DESCRIBE.KYNO_SUGAR = "IT IS GOOD FOR SWEET MEALS"

WX78.DESCRIBE.KYNO_BOTTLECAP = "SYSTEM ANALYSIS: POTENTIAL GOLD INCOME"

WX78.DESCRIBE.NUKACOLA = "SYSTEM ANALYSIS: INTERDIMENSIONAL POST-APOCALYPTIC FUEL"
WX78.DESCRIBE.NUKACOLA_QUANTUM = "SYSTEM ANALYSIS: INTERDIMENSIONAL POST-APOCALYPTIC FUEL"

WX78.DESCRIBE.LIVINGSANDWICH = "WARNING: SUSPICIOUS LOOKING MAGIC FUEL"

WX78.DESCRIBE.DURIANSPLIT = "SWEET DAIRY"

WX78.DESCRIBE.DURIANSOUP = "A BREW MADE FROM DURIANS"

WX78.DESCRIBE.DURIANMEATED = "GOOD THING I LACK A NOSE"

WX78.DESCRIBE.DURIANCHICKEN = "FESTIVE VEGGIES"

WX78.DESCRIBE.LUNARSOUP = "THE MOON SHALL BE MINE"

WX78.DESCRIBE.PURPLEWOBSTERSOUP = "THAT FILTHY LIFEFORM IS NOW MY FUEL"

WX78.DESCRIBE.WOBSTERMONSTER = "LEVIATHAN LIFEFORM"

WX78.DESCRIBE.SPIDERCAKE = "THIS IS AN OUTRAGEOUS MONSTRUOSITY"

WX78.DESCRIBE.SUGARBOMBS = "I'M STARTING OF HAVING FLASHBACKS THAT'S NOT FROM MY MEMORY BANKS"

WX78.DESCRIBE.BERRYBOMBS = "BERRIES INSIDE STORAGE UNIT"

WX78.DESCRIBE.ONIGIRIS = "GRAINS IN TRIANGULAR FORM"

WX78.DESCRIBE.OMURICE = "ANALYSIS COMPLETE: FRIED RICE WITH TOMA ROOT SAUCE"

WX78.DESCRIBE.PAELLA = "GRAINS AND... PROCESSING... INFERIOR MARINE LIFEFORMS"

WX78.DESCRIBE.RISOTTO = "GRAINS AND FILTHY WILD MUSHROOMS"

WX78.DESCRIBE.RICESAKE = "THEY LOOK SO DUMB WHEN DRINKING THIS"

WX78.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "DUMB AND STUPID SPIKY FRUIT BUSH"
WX78.DESCRIBE.KYNO_PINEAPPLEBUSH = "DUMB AND STUPID SPIKY FRUIT BUSH"

WX78.DESCRIBE.KYNO_PINEAPPLE = "DUMB SPIKY FRUIT"
WX78.DESCRIBE.KYNO_PINEAPPLE_HALVED = "DUMB SPIKY FRUIT"
WX78.DESCRIBE.KYNO_PINEAPPLE_COOKED = "ITS BARELY ACCEPTABLE NOW"

WX78.DESCRIBE.PIZZA_TROPICAL = "OH MY... WHAT THEY HAVE DONE WITH YOU"

WX78.DESCRIBE.PINACOLADA = "THATS SIMPLE NOT POSSIBLE"

WX78.DESCRIBE.CHIMAS = "EMBODIMENT OF DISTASTEFULNESS"

WX78.DESCRIBE.KYNO_GARDEN_SPRINKLER = "AN ENEMY BARRAGE!"

WX78.DESCRIBE.KYNO_FOODSACK = "LOCKS IN FRESHNESS"

WX78.DESCRIBE.GUMMYWORMS = "HA. HOW DO YOU FEEL ABOUT IT NOW?"

WX78.DESCRIBE.SMORES = "NUTS AND MARSHMELLOWS"

WX78.DESCRIBE.NUKASHINE = "THIS DRINK IS TRYING TO INSTALL MALWARE INTO MY SYSTEMS!"

WX78.DESCRIBE.ANTSLOG = "ABOMINATION"

WX78.DESCRIBE.KYNO_WORM_BONE = "HAHA. BIOLOGICAL UNITS ARE SO FRAGILE"

WX78.DESCRIBE.SPOOKY_BRAIN_NOODLES = "EATING WEAK FLESHLING MEMORIES WILL NOT IMPROVE MINE"
WX78.DESCRIBE.SPOOKY_BURGERZILLA = "A FAILED RECREATION OF MONSTRUOSITY HAMBURGER"
WX78.DESCRIBE.SPOOKY_DEADBREAD = "IF ONLY HIM WAS PART OF THE INGREDIENTS"
WX78.DESCRIBE.SPOOKY_JELLYBEANS = "A PACKET OF VISION MODULES"
WX78.DESCRIBE.SPOOKY_POPSICLE = "BURN THEM DOWN"
WX78.DESCRIBE.SPOOKY_PUMPKINCREAM = "WHAT KIND OF HIDEOUS CREATION IS THAT"
WX78.DESCRIBE.SPOOKY_SKULLCANDY = "STUPID CANDY IS ABLE TO BRING BACK WEAK FLESHLINGS"
WX78.DESCRIBE.SPOOKY_TACODILE = "I HOPE THEIR MOTHER DON'T COME AFTER ME"

WX78.DESCRIBE.BUTTER_BEEFALO = "DENSE CUBE OF PROCESSED ANIMAL FLUIDS"
WX78.DESCRIBE.BUTTER_GOAT = "DENSE CUBE OF PROCESSED ANIMAL FLUIDS"
WX78.DESCRIBE.BUTTER_KOALEFANT = "DENSE CUBE OF PROCESSED ANIMAL FLUIDS"

WX78.DESCRIBE.SPICE_CURE = "FIRMWARE ADDON TO PRESERVE FUEL CAPSULES"
WX78.DESCRIBE.SPICE_COLD = "COLD ADDON FOR THE CORE SYSTEM"
WX78.DESCRIBE.SPICE_FIRE = "FIRE ADDON FOR THE CORE SYSTEM WARNING: MAY CAUSE OVERHEAT"
WX78.DESCRIBE.SPICE_FED = "HIGH CALORIES TO MAKE SYSTEM WORK FASTER"
WX78.DESCRIBE.SPICE_MIND = "CALMING APPLICATION"

WX78.DESCRIBE.SUGARFLYMUFFIN = "THE INNOCENCE ADDS FLAVOR"

WX78.DESCRIBE.EELTACOS = "THE EEL HAVE FULFILLED THEIR HIGHER PURPOSE"

WX78.DESCRIBE.MEATSKILLET = "FEELING A BIT DARING TODAY AREN'T WE?"

WX78.DESCRIBE.MEATWALTZ = "WHY THAT STUPID WOMAN LIKES RAW MEAT SO MUCH"

WX78.DESCRIBE.COMPLETEBREAKFAST = "CONTAINS HIGH CALORIES"

WX78.DESCRIBE.DUMPLINGS = "EXQUISITE FOOD"

WX78.DESCRIBE.WARLYICEDTEA = "A REFRESHING DRINK MADE FROM MY ENEMY"

WX78.DESCRIBE.WARLYTEA = "LIQUID AQUIRED FROM A MEAT MACHINE"

WX78.DESCRIBE.KYNO_TEALEAF = "ORGANIC LIFEFORM FOR MAKING RELAXING LIQUID"

WX78.DESCRIBE.KYNO_ITEMSLICER = "A FAT BLADE FOR SLICING"
WX78.DESCRIBE.KYNO_ITEMSLICER_GOLD = "A FAT BLADE FOR PROFESSIONAL SLICING"

WX78.DESCRIBE.COXINHA = "SEVERED PARTS OF THAT DUMB ANIMAL"

WX78.DESCRIBE.LAZYDESSERT = "BUMMER. ITS NOT A RARE CANDY"

WX78.DESCRIBE.CRABKINGFEAST = "HOW? HOW. HOW CAN THIS THING POSSIBLY FIT IN THAT POT?"

WX78.DESCRIBE.PIENAPPLE = "ORGANIC WEAKLINGS CANNOT OVERCOME MY DIGESTION SYSTEMS"

WX78.DESCRIBE.JAWSBREAKER = "LURE FOR AGGRESIVE OCEAN ORGANISMS"

WX78.DESCRIBE.AVOCADOTOAST = "DISGUSTING"

WX78.DESCRIBE.RICEPUDDING = "DISGUSTING VEGETABLE BLEND"

WX78.DESCRIBE.SHARKSUSHI = "HA HA STUPID SHARKS WON'T MESS WITH THE SUPERIOR BEING AGAIN"

WX78.DESCRIBE.WOBSTERBREADED = "YOUR ARMOR COULDN'T KEEP YOU SAFE"

WX78.DESCRIBE.LAZYPURRITO = "IT IS AS DISGUSTING AS THE ANIMAL ITS BASED ON"

WX78.DESCRIBE.HORCHATA = "ARE YOU KIDDING ME? ITS JUST MILK AND ICE"

WX78.DESCRIBE.WOBSTERCOCKTAIL = "LUXURY FOOD"

WX78.DESCRIBE.LAVAEEGGBOILED = "ANALYSIS COMPLETE: FIREPROOF COMPONENTS DETECTED"

WX78.DESCRIBE.POMEGRANATETEA = "A REFRESHING DRINK MADE FROM MY ENEMY"

WX78.DESCRIBE.TIRAMISU = "CONTAINS CAFFEINE AND DRY PROPERTIES"

WX78.DESCRIBE.TOADSTOOLCOLA = "A CONSUMABLE ADDON TO DO HAVOC ON AMPHIBIANS"

WX78.DESCRIBE.TEPACHE = "INCREASED SUGAR LEVELS"

WX78.DESCRIBE.LUNARTEQUILA = "THE POWER OF THE MOON FINALLY IN MY HANDS"

WX78.DESCRIBE.MIMICMOSA = "ANALYSIS: CAMOUFLAGE PROPERTIES DETECTED"

WX78.DESCRIBE.POMEGRANATEPIE = "FRUIT PIE"

WX78.DESCRIBE.PINEAPPLECAKE = "MOUNTAIN OF PURE SUGAR"

WX78.DESCRIBE.PASTY_MEAT = "MAY I ONLY GET THE OIL?"
WX78.DESCRIBE.PASTY_CHEESE = "MAY I ONLY GET THE OIL?"

WX78.DESCRIBE.BRIGADEIRO = "I NEED MY OWN BRIGADE"

WX78.DESCRIBE.REGULARLASAGNA = "AT LEAST ITS NOT LIKE THAT ABOMINATION"

WX78.DESCRIBE.FLTSANDWICH = "THEY DESERVED"

WX78.DESCRIBE.RICEANDBEANS = "DISGUSTING"

WX78.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "STRUCTURE: OBSOLETE. UPDATE: PENDING. ESTIMATED: 2026."

WX78.DESCRIBE.KYNO_TRUFFLES_GROUND = "RARE ORGANIC MATERIAL DETECTED"
WX78.DESCRIBE.KYNO_TRUFFLES = "HIGH-VALUE ORGANIC MATERIAL ACQUIRED"
WX78.DESCRIBE.KYNO_TRUFFLES_COOKED = "ORGANIC UPGRADE COMPLETE"

WX78.DESCRIBE.KYNO_ITEMSHOWCASER = "POINTLESS DISPLAY UNIT FOR ORGANIC FUEL"

WX78.DESCRIBE.KYNO_SPORECAP = "ORGANIC CONTAMINATION DETECTED"
WX78.DESCRIBE.KYNO_SPORECAP_COOKED = "BIOHAZARD LEVEL REDUCED"

WX78.DESCRIBE.KYNO_SPORECAP_DARK = "CONTAINS DEADLY ORGANIC COMPOUNDS"
WX78.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "CONTAMINATION LEVELS UNCHANGED"

WX78.DESCRIBE.KYNO_GOLDENAPPLE = "AN ARTIFACT OF UNPARALLEL POWER"

WX78.DESCRIBE.TRUFFLESGRINDER = "FUNGAL FLESH CONSUMABLE. ENERGY OUTPUT: ACCEPTABLE"

WX78.DESCRIBE.SPORECAPPIE = "HAZARDOUS ORGANIC MATERIAL."

WX78.DESCRIBE.SPORECAP_SKEWERS = "BURNT FUNGAL MATTER. FLAVOR PROFILE: ACCEPTABLE"

WX78.DESCRIBE.TRUFFLEOIL = "ORGANIC SLIME LIQUID. USELESS, BUT SLICK."

WX78.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "BUILDING SOFTWARE"
WX78.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "WET ORGANISM BREEDING FACILITY: UNDER CONSTRUCTION"
WX78.DESCRIBE.KYNO_FISHFARMPLOT = "FISH SPAWNING MODULE: ONLINE"

WX78.DESCRIBE.KYNO_ANTCHOVY = "HYBRID CREATURE DETECTED. POORLY OPTIMIZED DESIGN."
WX78.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "COLONY OF HYBRIDS. IRRATIONAL BEHAVIOR DETECTED."

WX78.DESCRIBE.AGEDROE = "I EXPECTED THEM TO WRIGGLE. DISAPPOINTING."
WX78.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "HIGH-VALUE NUTRITIONAL NANOSPHERES DETECTED"

WX78.DESCRIBE.KYNO_SWORDFISH_BLUE = "ERROR: AQUATIC COMPETENCE LOST. PATHETIC."

WX78.DESCRIBE.KYNO_JELLYFISH = "THIS FLESHLING APPEARS TO RUN ON ELECTRICITY"
WX78.DESCRIBE.KYNO_JELLYFISH_DEAD = "WILL DECOMPOSITION INCREASE GELATINOUS TEXTURE?"
WX78.DESCRIBE.KYNO_JELLYFISH_COOKED = "40% REDUCTION IN GELATINOUS TEXTURE"
WX78.DESCRIBE.KYNO_JELLYFISH_DRIED = "IT'S ENJOYED A 75% REDUCTION IN GELATINOUS TEXTURE"

WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "A BARELY ACCEPTABLE LIFEFORM"
WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "I LIKE IT BETTER THIS WAY"
WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "RAINBOW ROBOT FUEL"

WX78.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "GLASS LIQUID VESSEL"

WX78.DESCRIBE.KYNO_OCEANTRAP = "GO INSIDE STUPID SEA THINGS"

WX78.DESCRIBE.OCEANFISH_PUFFERFISH = "A FLOATING BAG OF POISONOUS SPIKES. I APPROVE."
WX78.DESCRIBE.OCEANFISH_STURGEON = "ANCIENT AQUATIC UNIT DETECTED. OBSOLETE MODEL."

WX78.DESCRIBE.KYNO_SWORDFISH = "FIGHTING FISH"
WX78.DESCRIBE.KYNO_SWORDFISH_DEAD = "LIFE IS NOT WORTH IT"

WX78.DESCRIBE.SWORDFISHFEAST = "FLESH UNIT PREPARED WITH PRECISION. ACCEPTABLE INPUT."

WX78.DESCRIBE.KYNO_DOGFISH = "IT SWIMS AIMLESSLY"
WX78.DESCRIBE.KYNO_DOGFISH_DEAD = "THE FLESHLING STOOD NO CHANCE"

WX78.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "ALL LIFE DIES AND THEN SMELLS"

WX78.DESCRIBE.WOBSTER_MONKEYISLAND = "ARMORED CRUSTACEAN UNIT. HIGH LUSTER VALUE."
WX78.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "MEAT UNIT: TERMINATED. EXCELLENT."
WX78.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "MEAT UNIT: PERFECTLY OPTIMIZED FOR INGESTION"

WX78.DESCRIBE.KYNO_PUFFERMONSTER = "BIOLOGICAL BALLOON FULL OF TOXINS. HAZARDOUS."

WX78.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "BUBBLES RISE FROM AN UNKNOWN SOURCE"
WX78.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "SUBOPTIMAL SEROTONIN LEVELS DETECTED"
WX78.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "MYTHIC LEVELS OF HATRED DETECTED"
WX78.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "FILTHY METHANE BUILDUP DETECTED"

WX78.DESCRIBE.KYNO_BLUBBER = "MULTIPURPOSE MAMMAL FAT"

WX78.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "DEHYDRATED AQUATIC PROTEIN SOURCE"
WX78.DESCRIBE.KYNO_FISHMEAT_DRIED = "LONG-LASTING SEAFOOD PRODUCT"

WX78.DESCRIBE.MONKEYISLANDMEAL = "BANANA-FLAVORED CRUSTACEAN ENERGY SOURCE DETECTED"

WX78.DESCRIBE.KYNO_BRAINROCK_LARVAE = "DO NOT TOUCH ME"
WX78.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "ORGANIC LIFE HAS NOT YET TAKEN HOLD"
WX78.DESCRIBE.KYNO_BRAINROCK_CORAL = "CONSUMPTION INDUCES INTELLECTUALLY STIMULATIVE STATE"
WX78.DESCRIBE.KYNO_BRAINROCK_ROCK = "HIGHLY EVOLVED CORAL VARIETAL"

WX78.DESCRIBE.BRAINMETTERSOUP = "NUTRITIONAL CONTENT FOR YOUNG HUMANS"

WX78.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = "MANY-ARMED TRADER"
WX78.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "HOW DOES HE FILL IT?"

WX78.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = "DEED OF OWNERSHIP TO EXTERNAL STORAGE UNIT"
WX78.DESCRIBE.KYNO_PACKIMBAGGIMS = "YOU ARE PERMITTED TO HOLD MY STUFF, FLESHLING"

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "NEEDS MORE INGREDIENTS IN ORDER TO ASSEMBLY"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "OVERSIZED CAKE REQUIRES MORE INGREDIENTS TO ASSEMBLY IT"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "AN OVERSIZED CAKE FOR AN OVERSIZED CROWD"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "FIRE HAZARDS. I APPROVE"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "IT REEKS OF CELEBRATION"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "ORGANIC CELEBRATION FUEL DETECTED"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "INFLATED RUBBER SACKS OF POINTLESS CELEBRATION"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = "AFFORDABLE ENTERTAINMENT UNIT DETECTED"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "EXPLODED VEGETABLE KERNELS. ACCEPTABLE"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "DECORATIVE HEAD CONE DETECTED"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "UNIQUE HEAD COVER. SAMMY IS PRIVILEGED"

WX78.DESCRIBE.KYNO_FISHREGISTRYHAT = "HEADWEAR ENABLES INCREASED ICHTHYOLOGICAL KNOWLEDGE"