local TEMPLATE = STRINGS.CHARACTERS.TEMPLATE -- This is a template for character strings. Replace "GENERIC" with your character's name.

TEMPLATE.ANNOUNCE_KYNO_COFFEEBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_COFFEEBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_HASTEBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_HASTEBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_POPBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_POPBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_FROGBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_FROGBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_PIRATEBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_PIRATEBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_FREEZEBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_FREEZEBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_FIREBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_FIREBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_FISHINGBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_FISHINGBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_SANITYRATEBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_SANITYRATEBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_EATERBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_EATERBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_WORMBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_WORMBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_CRABBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_CRABBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_STEALTHBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_STEALTHBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_FEARBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_FEARBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_TRUFFLESBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_TRUFFLESBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START =
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

TEMPLATE.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_CRAFTINGBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_CRAFTINGBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_MAXHEALTHBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_MAXHEALTHBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_MAXHUNGERBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_MAXHUNGERBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_MAXSANITYBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_MAXSANITYBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_BERSERKERBUFF_START = 
TEMPLATE.ANNOUNCE_KYNO_BERSERKERBUFF_END = 

TEMPLATE.ANNOUNCE_KYNO_HUNGERRATEBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_HUNGERRATEBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_DARKNESSBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_DARKNESSBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_LUCKBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_GREENTHUMBBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_GREENTHUMBBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_WETNESSBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_WETNESSBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_NIGHTKILLBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_NIGHTKILLBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_PANICBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_PANICBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_CUREBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_CUREBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_KNOCKBACKBUFF_START =
TEMPLATE.ANNOUNCE_KYNO_KNOCKBACKBUFF_END =

TEMPLATE.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = 

TEMPLATE.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL =

TEMPLATE.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL =

TEMPLATE.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = 

TEMPLATE.ANNOUNCE_KYNO_POTHANGER_FAIL = 

TEMPLATE.ANNOUNCE_KYNO_CASSEROLE_FAIL = 

TEMPLATE.ANNOUNCE_KYNO_SAPHEALER_USED =

TEMPLATE.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED =

TEMPLATE.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY =

TEMPLATE.ANNOUNCE_KYNO_HUNT_LOST_TRAIL =
TEMPLATE.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN =
TEMPLATE.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY =

TEMPLATE.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = 

TEMPLATE.ANNOUNCE_KYNO_FISH_RESEARCHED =
TEMPLATE.ANNOUNCE_KYNO_ROE_RESEARCHED =

TEMPLATE.ANNOUNCE_KYNO_DAILYRECIPE_EATEN =

TEMPLATE.ANNOUNCE_KYNO_ICENETTLE_TOXIN_START =
{
	-- 1
	-- 2
}

TEMPLATE.ANNOUNCE_KYNO_ICENETTLE_TOXIN_END =

TEMPLATE.DESCRIBE.KYNO_ROE = 
TEMPLATE.DESCRIBE.KYNO_ROE_COOKED =

TEMPLATE.DESCRIBE.KYNO_SHARK_FIN =

TEMPLATE.DESCRIBE.KYNO_BEANBUGS = 
TEMPLATE.DESCRIBE.KYNO_BEANBUGS_COOKED = 

TEMPLATE.DESCRIBE.KYNO_GUMMYBUG = 
TEMPLATE.DESCRIBE.KYNO_GUMMYBUG_COOKED = 

TEMPLATE.DESCRIBE.KYNO_WHEAT = 
TEMPLATE.DESCRIBE.KYNO_WHEAT_COOKED = 

TEMPLATE.DESCRIBE.KYNO_FLOUR = 

TEMPLATE.DESCRIBE.KYNO_SPOTSPICE = 

TEMPLATE.DESCRIBE.KYNO_SAP = 
TEMPLATE.DESCRIBE.KYNO_SAP_SPOILED = 

TEMPLATE.DESCRIBE.KYNO_SYRUP = 

TEMPLATE.DESCRIBE.KYNO_COFFEEBEANS = 
TEMPLATE.DESCRIBE.KYNO_COFFEEBEANS_COOKED = 

TEMPLATE.DESCRIBE.DUG_KYNO_COFFEEBUSH =

TEMPLATE.DESCRIBE.KYNO_COFFEEBUSH =
{
	GENERIC =
	PICKED =
	WITHERED =
}

TEMPLATE.DESCRIBE.DUG_KYNO_SPOTBUSH =

TEMPLATE.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC =
	PICKED =
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_SPOTSPICE_LEAF = 

TEMPLATE.DESCRIBE.KYNO_MUSSEL = 
TEMPLATE.DESCRIBE.KYNO_MUSSEL_COOKED = 

TEMPLATE.DESCRIBE.KYNO_HUMANMEAT = 
TEMPLATE.DESCRIBE.KYNO_HUMANMEAT_COOKED = 
TEMPLATE.DESCRIBE.KYNO_HUMANMEAT_DRIED = 

TEMPLATE.DESCRIBE.COFFEE = 

TEMPLATE.DESCRIBE.BISQUE = 

TEMPLATE.DESCRIBE.JELLYOPOP = 

TEMPLATE.DESCRIBE.SHARKFINSOUP =

TEMPLATE.DESCRIBE.TROPICALBOUILLABAISSE = 

TEMPLATE.DESCRIBE.MUSSELBOUILLABAISE = 

TEMPLATE.DESCRIBE.SWEETPOTATOSOUFFLE = 

TEMPLATE.DESCRIBE.FEIJOADA = 

TEMPLATE.DESCRIBE.GUMMY_CAKE = 

TEMPLATE.DESCRIBE.HARDSHELL_TACOS = 

TEMPLATE.DESCRIBE.ICEDTEA = 

TEMPLATE.DESCRIBE.NETTLELOSANGE = 

TEMPLATE.DESCRIBE.SNAKEBONESOUP = 

TEMPLATE.DESCRIBE.STEAMEDHAMSANDWICH =

TEMPLATE.DESCRIBE.TEA = 

TEMPLATE.DESCRIBE.BUBBLETEA = 

TEMPLATE.DESCRIBE.FRENCHONIONSOUP = 

TEMPLATE.DESCRIBE.SLAW = 

TEMPLATE.DESCRIBE.LOTUSBOWL = 

TEMPLATE.DESCRIBE.POI = 

TEMPLATE.DESCRIBE.JELLYBEAN_HUNGER = 
TEMPLATE.DESCRIBE.JELLYBEAN_SUPER = 
TEMPLATE.DESCRIBE.JELLYBEAN_SANITY = 

TEMPLATE.DESCRIBE.BOWLOFGEARS = 

TEMPLATE.DESCRIBE.LONGPIGMEAL = 

TEMPLATE.DESCRIBE.CUCUMBERSALAD = 

TEMPLATE.DESCRIBE.DUG_KYNO_WILDWHEAT =

TEMPLATE.DESCRIBE.KYNO_WILDWHEAT =
{
	GENERIC =
	PICKED =
	WITHERED =
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_MEALGRINDER = 

TEMPLATE.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC =
	PICKED =
	BURNING =
}

TEMPLATE.DESCRIBE.GORGE_BREAD = 
TEMPLATE.DESCRIBE.GORGE_SWEET_CHIPS = 
TEMPLATE.DESCRIBE.GORGE_VEGETABLE_SOUP = 
TEMPLATE.DESCRIBE.GORGE_JELLY_SANDWICH = 
TEMPLATE.DESCRIBE.GORGE_FISH_STEW = 
TEMPLATE.DESCRIBE.GORGE_MEAT_STEW = 
TEMPLATE.DESCRIBE.GORGE_ONION_CAKE = 
TEMPLATE.DESCRIBE.GORGE_POTATO_PANCAKES = 
TEMPLATE.DESCRIBE.GORGE_POTATO_SOUP = 
TEMPLATE.DESCRIBE.GORGE_FISHBALL_SKEWERS = 
TEMPLATE.DESCRIBE.GORGE_MEAT_SKEWERS = 
TEMPLATE.DESCRIBE.GORGE_STONE_SOUP =
TEMPLATE.DESCRIBE.GORGE_CROQUETTE = 
TEMPLATE.DESCRIBE.GORGE_ROAST_VEGETABLES = 
TEMPLATE.DESCRIBE.GORGE_MEATLOAF = 
TEMPLATE.DESCRIBE.GORGE_CARROT_SOUP = 
TEMPLATE.DESCRIBE.GORGE_FISHPIE = 
TEMPLATE.DESCRIBE.GORGE_FISHCHIPS = 
TEMPLATE.DESCRIBE.GORGE_MEATPIE = 
TEMPLATE.DESCRIBE.GORGE_SLIDERS = 
TEMPLATE.DESCRIBE.GORGE_JELLY_ROLL = 
TEMPLATE.DESCRIBE.GORGE_CARROT_CAKE = 
TEMPLATE.DESCRIBE.GORGE_GARLICMASHED = 
TEMPLATE.DESCRIBE.GORGE_GARLICBREAD = 
TEMPLATE.DESCRIBE.GORGE_TOMATO_SOUP = 
TEMPLATE.DESCRIBE.GORGE_SAUSAGE = 
TEMPLATE.DESCRIBE.GORGE_CANDIEDFISH = 
TEMPLATE.DESCRIBE.GORGE_STUFFEDMUSHROOM = 
TEMPLATE.DESCRIBE.GORGE_BRUSCHETTA = 
TEMPLATE.DESCRIBE.GORGE_HAMBURGER = 
TEMPLATE.DESCRIBE.GORGE_FISHBURGER = 
TEMPLATE.DESCRIBE.GORGE_MUSHROOMBURGER = 
TEMPLATE.DESCRIBE.GORGE_FISH_STEAK = 
TEMPLATE.DESCRIBE.GORGE_CURRY = 
TEMPLATE.DESCRIBE.GORGE_SPAGHETTI = 
TEMPLATE.DESCRIBE.GORGE_POACHEDFISH = 
TEMPLATE.DESCRIBE.GORGE_SHEPHERD_PIE = 
TEMPLATE.DESCRIBE.GORGE_CANDY = 
TEMPLATE.DESCRIBE.GORGE_BREAD_PUDDING = 
TEMPLATE.DESCRIBE.GORGE_BERRY_TART = 
TEMPLATE.DESCRIBE.GORGE_MACARONI = 
TEMPLATE.DESCRIBE.GORGE_BAGEL_AND_FISH = 
TEMPLATE.DESCRIBE.GORGE_GRILLED_CHEESE = 
TEMPLATE.DESCRIBE.GORGE_CREAMMUSHROOM = 
TEMPLATE.DESCRIBE.GORGE_MANICOTTI = 
TEMPLATE.DESCRIBE.GORGE_CHEESEBURGER = 
TEMPLATE.DESCRIBE.GORGE_FETTUCCINE = 
TEMPLATE.DESCRIBE.GORGE_ONION_SOUP = 
TEMPLATE.DESCRIBE.GORGE_BREADED_CUTLET = 
TEMPLATE.DESCRIBE.GORGE_CREAMY_FISH = 
TEMPLATE.DESCRIBE.GORGE_PIZZA =
TEMPLATE.DESCRIBE.GORGE_POT_ROAST = 
TEMPLATE.DESCRIBE.GORGE_CRAB_CAKE = 
TEMPLATE.DESCRIBE.GORGE_STEAK_FRITES = 
TEMPLATE.DESCRIBE.GORGE_SHOOTER_SANDWICH = 
TEMPLATE.DESCRIBE.GORGE_BACON_WRAPPED = 
TEMPLATE.DESCRIBE.GORGE_CRAB_ROLL = 
TEMPLATE.DESCRIBE.GORGE_MEAT_WELLINGTON = 
TEMPLATE.DESCRIBE.GORGE_CRAB_RAVIOLI = 
TEMPLATE.DESCRIBE.GORGE_CARAMEL_CUBE = 
TEMPLATE.DESCRIBE.GORGE_SCONE = 
TEMPLATE.DESCRIBE.GORGE_TRIFLE = 
TEMPLATE.DESCRIBE.GORGE_CHEESECAKE = 

TEMPLATE.DESCRIBE.DUCKYOUGLERMZ = 

TEMPLATE.DESCRIBE.KYNO_ALOE = 
TEMPLATE.DESCRIBE.KYNO_ALOE_COOKED = 
TEMPLATE.DESCRIBE.KYNO_ALOE_DRIED =
TEMPLATE.DESCRIBE.KYNO_ALOE_GROUND = 
TEMPLATE.DESCRIBE.KYNO_ALOE_SEEDS = 
TEMPLATE.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS =
TEMPLATE.DESCRIBE.FARM_PLANT_KYNO_ALOE = 
TEMPLATE.DESCRIBE.KYNO_ALOE_OVERSIZED = 
TEMPLATE.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = 

TEMPLATE.DESCRIBE.KYNO_CUCUMBER = 
TEMPLATE.DESCRIBE.KYNO_CUCUMBER_COOKED = 
TEMPLATE.DESCRIBE.KYNO_CUCUMBER_GROUND = 
TEMPLATE.DESCRIBE.KYNO_CUCUMBER_SEEDS = 
TEMPLATE.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = 
TEMPLATE.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = 
TEMPLATE.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = 
TEMPLATE.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = 

TEMPLATE.DESCRIBE.KYNO_RADISH = 
TEMPLATE.DESCRIBE.KYNO_RADISH_COOKED = 
TEMPLATE.DESCRIBE.KYNO_RADISH_GROUND = 
TEMPLATE.DESCRIBE.KYNO_RADISH_SEEDS = 
TEMPLATE.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS =
TEMPLATE.DESCRIBE.FARM_PLANT_KYNO_RADISH = 
TEMPLATE.DESCRIBE.KYNO_RADISH_OVERSIZED = 
TEMPLATE.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = 

TEMPLATE.DESCRIBE.KYNO_FENNEL = 
TEMPLATE.DESCRIBE.KYNO_FENNEL_COOKED = 
TEMPLATE.DESCRIBE.KYNO_FENNEL_GROUND = 
TEMPLATE.DESCRIBE.KYNO_FENNEL_SEEDS =
TEMPLATE.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS =
TEMPLATE.DESCRIBE.FARM_PLANT_KYNO_FENNEL = 
TEMPLATE.DESCRIBE.KYNO_FENNEL_OVERSIZED = 
TEMPLATE.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = 

TEMPLATE.DESCRIBE.KYNO_SWEETPOTATO = 
TEMPLATE.DESCRIBE.KYNO_SWEETPOTATO_COOKED = 
TEMPLATE.DESCRIBE.KYNO_SWEETPOTATO_GROUND = 
TEMPLATE.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = 
TEMPLATE.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = 
TEMPLATE.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = 
TEMPLATE.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = 
TEMPLATE.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = 

TEMPLATE.DESCRIBE.KYNO_PARZNIP = 
TEMPLATE.DESCRIBE.KYNO_PARZNIP_COOKED = 
TEMPLATE.DESCRIBE.KYNO_PARZNIP_EATEN = 
TEMPLATE.DESCRIBE.KYNO_PARZNIP_GROUND = 
TEMPLATE.DESCRIBE.KYNO_PARZNIP_BIG = 
TEMPLATE.DESCRIBE.KYNO_PARZNIP_SEEDS =
TEMPLATE.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS =
TEMPLATE.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = 
TEMPLATE.DESCRIBE.KYNO_PARZNIP_OVERSIZED = 
TEMPLATE.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = 

TEMPLATE.DESCRIBE.KYNO_TURNIP =
TEMPLATE.DESCRIBE.KYNO_TURNIP_COOKED = 
TEMPLATE.DESCRIBE.KYNO_TURNIP_GROUND =
TEMPLATE.DESCRIBE.KYNO_TURNIP_SEEDS = 
TEMPLATE.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS =
TEMPLATE.DESCRIBE.FARM_PLANT_KYNO_TURNIP = 
TEMPLATE.DESCRIBE.KYNO_TURNIP_OVERSIZED =
TEMPLATE.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = 

TEMPLATE.DESCRIBE.KYNO_RICE = 
TEMPLATE.DESCRIBE.KYNO_RICE_COOKED = 
TEMPLATE.DESCRIBE.KYNO_RICE_SEEDS = 
TEMPLATE.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = 
TEMPLATE.DESCRIBE.FARM_PLANT_KYNO_RICE = 
TEMPLATE.DESCRIBE.KYNO_RICE_OVERSIZED = 
TEMPLATE.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = 

TEMPLATE.DESCRIBE.KYNO_SEEDS_KIT = 

TEMPLATE.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC =
	PICKED =
	WITHERED =
}

TEMPLATE.DESCRIBE.KYNO_LIMPETS = 
TEMPLATE.DESCRIBE.KYNO_LIMPETS_COOKED = 

TEMPLATE.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC =
	PICKED =
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_LOTUS_ROOT =
TEMPLATE.DESCRIBE.KYNO_LOTUS_FLOWER = 
TEMPLATE.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = 

TEMPLATE.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC =
	PICKED =
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_SEAWEEDS = 
TEMPLATE.DESCRIBE.KYNO_SEAWEEDS_COOKED = 
TEMPLATE.DESCRIBE.KYNO_SEAWEEDS_DRIED = 
TEMPLATE.DESCRIBE.KYNO_SEAWEEDS_ROOT = 

TEMPLATE.DESCRIBE.KYNO_TAROROOT_OCEAN =
{
	GENERIC =
	PICKED =
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_TAROROOT_ROOT =
TEMPLATE.DESCRIBE.KYNO_TAROROOT = 
TEMPLATE.DESCRIBE.KYNO_TAROROOT_COOKED =

TEMPLATE.DESCRIBE.KYNO_WATERYCRESS_OCEAN =
{
	GENERIC =
	PICKED =
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_WATERYCRESS_ROOT =
TEMPLATE.DESCRIBE.KYNO_WATERYCRESS = 

TEMPLATE.DESCRIBE.WATERYCRESSBOWL = 

TEMPLATE.DESCRIBE.KYNO_SALT = 

TEMPLATE.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC =
	PICKED =
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_MUSSELSTICK_ITEM =

TEMPLATE.DESCRIBE.CATFOOD = 

TEMPLATE.DESCRIBE.KATFOOD = 

TEMPLATE.DESCRIBE.KYNO_BANANATREE =
{
	GENERIC =
	PICKED =
	CHOPPED =
	BURNING =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_BANANA = 
TEMPLATE.DESCRIBE.KYNO_BANANA_COOKED = 

TEMPLATE.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC =
	PICKED =
	CHOPPED =
	BURNING =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_KOKONUT = 
TEMPLATE.DESCRIBE.KYNO_KOKONUT_HALVED = 
TEMPLATE.DESCRIBE.KYNO_KOKONUT_COOKED = 

TEMPLATE.DESCRIBE.BOWLOFPOPCORN = 

TEMPLATE.DESCRIBE.FIGJUICE = 

TEMPLATE.DESCRIBE.COCONUTWATER = 

TEMPLATE.DESCRIBE.EYEBALLSPAGHETTI = 

TEMPLATE.DESCRIBE.WEED_SEEDS =

TEMPLATE.DESCRIBE.KYNO_FLOATILIZER = 

TEMPLATE.DESCRIBE.KYNO_TWIGGYNUTS = 

TEMPLATE.DESCRIBE.KYNO_REPAIRTOOL = 

TEMPLATE.DESCRIBE.KYNO_KOI = 
TEMPLATE.DESCRIBE.KYNO_KOI_COOKED =

TEMPLATE.DESCRIBE.KYNO_TROPICALFISH = 
TEMPLATE.DESCRIBE.KYNO_TROPICALFISH_COOKED = 

TEMPLATE.DESCRIBE.KYNO_NEONFISH = 
TEMPLATE.DESCRIBE.KYNO_NEONFISH_COOKED = 

TEMPLATE.DESCRIBE.KYNO_GROUPER = 
TEMPLATE.DESCRIBE.KYNO_GROUPER_COOKED =
 
TEMPLATE.DESCRIBE.KYNO_PIERROTFISH = 
TEMPLATE.DESCRIBE.KYNO_PIERROTFISH_COOKED = 

TEMPLATE.DESCRIBE.KYNO_SALMONFISH = 
TEMPLATE.DESCRIBE.KYNO_SALMONFISH_COOKED = 

TEMPLATE.DESCRIBE.TURF_PINKPARK = 
TEMPLATE.DESCRIBE.TURF_STONECITY = 
TEMPLATE.DESCRIBE.TURF_FIELDS = 
TEMPLATE.DESCRIBE.TURF_TIDALMARSH = 

TEMPLATE.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC =
	PICKED =
}

TEMPLATE.DESCRIBE.KYNO_SALTRACK_INSTALLER = 

TEMPLATE.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = 

TEMPLATE.DESCRIBE.KYNO_CRABTRAP_INSTALLER = 

TEMPLATE.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC =
	SLEEPING =
}

TEMPLATE.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC =
	CHOPPED =
	SAPPED =
	PICKED =
	BURNING =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC =
	CHOPPED =
	SAPPED =
	PICKED =
	BURNING =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_SUGARTREE_BUD = 

TEMPLATE.DESCRIBE.KYNO_SUGARTREE_FLOWER =
TEMPLATE.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = 

TEMPLATE.DESCRIBE.KYNO_SUGARTREE_PETALS = 
TEMPLATE.DESCRIBE.KYNO_SUGARTREE_PETALS_DRIED =

TEMPLATE.DESCRIBE.KYNO_PEBBLECRAB =

TEMPLATE.DESCRIBE.KYNO_CRABMEAT = 
TEMPLATE.DESCRIBE.KYNO_CRABMEAT_COOKED = 
TEMPLATE.DESCRIBE.KYNO_CRABMEAT_DRIED = 

TEMPLATE.DESCRIBE.KYNO_CRABKINGMEAT = 
TEMPLATE.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = 
TEMPLATE.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = 

TEMPLATE.DESCRIBE.KYNO_SLAUGHTERTOOL = 

TEMPLATE.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC =
	COOP =
}

TEMPLATE.DESCRIBE.KYNO_CHICKEN_EGG = 
TEMPLATE.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = 
TEMPLATE.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = 

TEMPLATE.DESCRIBE.KYNO_CHICKEN_EGG_LARGE_CRACKED =
{
	GENERIC =
	HATCHING =
}

TEMPLATE.DESCRIBE.KYNO_CHICKENHOUSE =
{
	GENERIC =
	FULL =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = 

TEMPLATE.DESCRIBE.KYNO_COOKWARE_KIT = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_SYRUP = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_BIG_POT = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_BIG = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_SMALL_POT = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_SMALL = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_GRILL = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_ELDER = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_CASSEROLE = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_OVEN = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = 
TEMPLATE.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE =

TEMPLATE.DESCRIBE.KYNO_ROCKFLIPPABLE =
{
	GENERIC = 
	FLIPPED =
}

TEMPLATE.DESCRIBE.KYNO_SERENITYISLAND_CRATE = 

TEMPLATE.DESCRIBE.KYNO_SUGARFLY = 
TEMPLATE.DESCRIBE.KYNO_SUGARFLYWINGS = 

TEMPLATE.DESCRIBE.KYNO_WATERY_CRATE = 

TEMPLATE.DESCRIBE.KYNO_TUNACAN = 
TEMPLATE.DESCRIBE.KYNO_TUNACAN_OPEN = 

TEMPLATE.DESCRIBE.KYNO_CANNEDFOOD = 
TEMPLATE.DESCRIBE.KYNO_CANNEDFOOD_OPEN = 

TEMPLATE.DESCRIBE.KYNO_POP = 

TEMPLATE.DESCRIBE.KYNO_MYSTERYMEAT =

TEMPLATE.DESCRIBE.KYNO_BOTTLE_SOUL = 

TEMPLATE.DESCRIBE.SOULSTEW = 

TEMPLATE.DESCRIBE.FORTUNECOOKIE = 

TEMPLATE.DESCRIBE.HORNOCUPIA = 

TEMPLATE.DESCRIBE.CHEESE_YELLOW = 
TEMPLATE.DESCRIBE.CHEESE_WHITE = 
TEMPLATE.DESCRIBE.CHEESE_KOALEFANT = 

TEMPLATE.DESCRIBE.MILK_BOX = 

TEMPLATE.DESCRIBE.WATERCUP = 

TEMPLATE.DESCRIBE.HONEYJAR = 

TEMPLATE.DESCRIBE.CRAB_ARTICHOKE = 

TEMPLATE.DESCRIBE.PEPPERROLLS = 

TEMPLATE.DESCRIBE.KYNO_SAPHEALER =

TEMPLATE.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC =
	PICKED =
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_GHOST_PIRATE =

TEMPLATE.DESCRIBE.KYNO_BUCKET_EMPTY = 
TEMPLATE.DESCRIBE.KYNO_BUCKET_METAL =
TEMPLATE.DESCRIBE.KYNO_BUCKET_WATER = 

TEMPLATE.DESCRIBE.KYNO_MILK_BEEFALO = 
TEMPLATE.DESCRIBE.KYNO_MILK_KOALEFANT = 

TEMPLATE.DESCRIBE.KYNO_CAP_DRIED = 

TEMPLATE.DESCRIBE.KYNO_PLANTMEAT_DRIED = 

TEMPLATE.DESCRIBE.KYNO_BREWBOOK = 

TEMPLATE.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY =
	BREWING_LONG =
	BREWING_SHORT =
	DONE =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY =
	BREWING_LONG =
	BREWING_SHORT =
	DONE =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC =
	HONEY =
	NECTAR =
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_NECTAR_POD = 

TEMPLATE.DESCRIBE.KYNO_OAKTREE_POD = 
TEMPLATE.DESCRIBE.KYNO_OAKTREE_POD_COOKED =

TEMPLATE.DESCRIBE.KYNO_PIKO = 
TEMPLATE.DESCRIBE.KYNO_PIKO_ORANGE = 

TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC =
	CHOPPED =
	BURNING =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = 
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_CRATE = 

TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC =
	CRAFTED =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC =
	OCCUPIED =
}

TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC =
	EMPTY =
}

TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_SELLER = 
TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_POND = 
TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = 
TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = 
TEMPLATE.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = 

TEMPLATE.DESCRIBE.KYNO_SAMMYHAT = 

TEMPLATE.DESCRIBE.KINGFISHER = 

TEMPLATE.DESCRIBE.TOUCAN = 
TEMPLATE.DESCRIBE.TOUCAN_CHUBBY =

TEMPLATE.DESCRIBE.WETGOOP2 = 

TEMPLATE.DESCRIBE.BEER = 

TEMPLATE.DESCRIBE.PALEALE = 

TEMPLATE.DESCRIBE.TEAGREEN = 

TEMPLATE.DESCRIBE.TEARED = 

TEMPLATE.DESCRIBE.MEAD = 

TEMPLATE.DESCRIBE.KYNO_JELLY = 

TEMPLATE.DESCRIBE.KYNO_MAYONNAISE = 

TEMPLATE.DESCRIBE.TARTARSAUCE = 

TEMPLATE.DESCRIBE.KYNO_PICKLES = 

TEMPLATE.DESCRIBE.KYNO_WINE = 

TEMPLATE.DESCRIBE.KYNO_JUICE = 

TEMPLATE.DESCRIBE.KYNO_POISON_FROGLEGS = 
TEMPLATE.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = 

TEMPLATE.DESCRIBE.POISONFROGGLEBUNWICH = 

TEMPLATE.DESCRIBE.KYNO_BREWINGRECIPECARD =

TEMPLATE.DESCRIBE.KYNO_OIL = 

TEMPLATE.DESCRIBE.BERRYSUNDAE = 

TEMPLATE.DESCRIBE.CHOCOLATE_BLACK = 
TEMPLATE.DESCRIBE.CHOCOLATE_WHITE = 

TEMPLATE.DESCRIBE.TRICOLORDANGO =
 
TEMPLATE.DESCRIBE.FRIESFRENCH = 

TEMPLATE.DESCRIBE.PIRATERUM = 

TEMPLATE.DESCRIBE.TWISTEDTEQUILA = 

TEMPLATE.DESCRIBE.ONIONRINGS = 

TEMPLATE.DESCRIBE.DONUTS = 
TEMPLATE.DESCRIBE.DONUTS_CHOCOLATE_BLACK =
TEMPLATE.DESCRIBE.DONUTS_CHOCOLATE_WHITE =
 
TEMPLATE.DESCRIBE.CINNAMONROLL =

TEMPLATE.DESCRIBE.GUMMYBEARGERS = 

TEMPLATE.DESCRIBE.PRETZEL = 

TEMPLATE.DESCRIBE.CORNINCUP = 

TEMPLATE.DESCRIBE.COTTONCANDY = 

TEMPLATE.DESCRIBE.ROASTEDHAZELNUTS = 

TEMPLATE.DESCRIBE.MONSTERMUFFIN = 

TEMPLATE.DESCRIBE.PINKCAKE =

TEMPLATE.DESCRIBE.CHIPSBAG = 

TEMPLATE.DESCRIBE.LITTLEBREAD = 

TEMPLATE.DESCRIBE.HOTHOUND = 

TEMPLATE.DESCRIBE.MILKSHAKE = 
TEMPLATE.DESCRIBE.MILKSHAKE_PRISMATIC = 

TEMPLATE.DESCRIBE.NACHOS = 

TEMPLATE.DESCRIBE.BANANA_PUDDING = 

TEMPLATE.DESCRIBE.SEA_PUDDING = 

TEMPLATE.DESCRIBE.TOM_KHA_SOUP = 

TEMPLATE.DESCRIBE.MINERTREAT = 

TEMPLATE.DESCRIBE.RADISHSALAD = 

TEMPLATE.DESCRIBE.PUMPKIN_SOUP = 

TEMPLATE.DESCRIBE.ALGAE_SOUP = 

TEMPLATE.DESCRIBE.PARZNIP_SOUP = 

TEMPLATE.DESCRIBE.NETTLEMEATED = 

TEMPLATE.DESCRIBE.KYNO_SUGAR = 

TEMPLATE.DESCRIBE.KYNO_BOTTLECAP = 

TEMPLATE.DESCRIBE.NUKACOLA = 
TEMPLATE.DESCRIBE.NUKACOLA_QUANTUM = 

TEMPLATE.DESCRIBE.LIVINGSANDWICH = 

TEMPLATE.DESCRIBE.DURIANSPLIT = 

TEMPLATE.DESCRIBE.DURIANSOUP = 

TEMPLATE.DESCRIBE.DURIANMEATED = 

TEMPLATE.DESCRIBE.DURIANCHICKEN = 

TEMPLATE.DESCRIBE.LUNARSOUP = 

TEMPLATE.DESCRIBE.PURPLEWOBSTERSOUP = 

TEMPLATE.DESCRIBE.WOBSTERMONSTER =

TEMPLATE.DESCRIBE.SPIDERCAKE = 

TEMPLATE.DESCRIBE.SUGARBOMBS = 

TEMPLATE.DESCRIBE.BERRYBOMBS = 

TEMPLATE.DESCRIBE.ONIGIRIS = 

TEMPLATE.DESCRIBE.OMURICE = 

TEMPLATE.DESCRIBE.PAELLA = 

TEMPLATE.DESCRIBE.RISOTTO = 

TEMPLATE.DESCRIBE.RICESAKE = 

TEMPLATE.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH =

TEMPLATE.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC =
	PICKED =
	WITHERED =
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_PINEAPPLE = 
TEMPLATE.DESCRIBE.KYNO_PINEAPPLE_HALVED = 
TEMPLATE.DESCRIBE.KYNO_PINEAPPLE_COOKED = 

TEMPLATE.DESCRIBE.PIZZA_TROPICAL = 

TEMPLATE.DESCRIBE.PINACOLADA = 

TEMPLATE.DESCRIBE.CHIMAS = 

TEMPLATE.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF =
	ON = 
}

TEMPLATE.DESCRIBE.KYNO_FOODSACK = 

TEMPLATE.DESCRIBE.GUMMYWORMS = 

TEMPLATE.DESCRIBE.SMORES = 

TEMPLATE.DESCRIBE.NUKASHINE = 

TEMPLATE.DESCRIBE.ANTSLOG = 

TEMPLATE.DESCRIBE.KYNO_WORM_BONE = 

TEMPLATE.DESCRIBE.SPOOKY_BRAIN_NOODLES =
TEMPLATE.DESCRIBE.SPOOKY_BURGERZILLA = 
TEMPLATE.DESCRIBE.SPOOKY_DEADBREAD = 
TEMPLATE.DESCRIBE.SPOOKY_JELLYBEANS = 
TEMPLATE.DESCRIBE.SPOOKY_POPSICLE = 
TEMPLATE.DESCRIBE.SPOOKY_PUMPKINCREAM = 
TEMPLATE.DESCRIBE.SPOOKY_SKULLCANDY = 
TEMPLATE.DESCRIBE.SPOOKY_TACODILE = 

TEMPLATE.DESCRIBE.BUTTER_BEEFALO = 
TEMPLATE.DESCRIBE.BUTTER_GOAT = 
TEMPLATE.DESCRIBE.BUTTER_KOALEFANT = 

TEMPLATE.DESCRIBE.SPICE_CURE = 
TEMPLATE.DESCRIBE.SPICE_COLD = 
TEMPLATE.DESCRIBE.SPICE_FIRE = 
TEMPLATE.DESCRIBE.SPICE_FED = 
TEMPLATE.DESCRIBE.SPICE_MIND = 

TEMPLATE.DESCRIBE.SUGARFLYMUFFIN = 

TEMPLATE.DESCRIBE.EELTACOS = 

TEMPLATE.DESCRIBE.MEATSKILLET = 

TEMPLATE.DESCRIBE.MEATWALTZ = 

TEMPLATE.DESCRIBE.COMPLETEBREAKFAST = 

TEMPLATE.DESCRIBE.DUMPLINGS = 

TEMPLATE.DESCRIBE.WARLYICEDTEA = 

TEMPLATE.DESCRIBE.WARLYTEA = 

TEMPLATE.DESCRIBE.KYNO_TEALEAF = 

TEMPLATE.DESCRIBE.KYNO_ITEMSLICER = 
TEMPLATE.DESCRIBE.KYNO_ITEMSLICER_GOLD = 

TEMPLATE.DESCRIBE.COXINHA =

TEMPLATE.DESCRIBE.LAZYDESSERT = 

TEMPLATE.DESCRIBE.CRABKINGFEAST = 

TEMPLATE.DESCRIBE.PIENAPPLE = 

TEMPLATE.DESCRIBE.JAWSBREAKER = 

TEMPLATE.DESCRIBE.AVOCADOTOAST = 

TEMPLATE.DESCRIBE.RICEPUDDING = 

TEMPLATE.DESCRIBE.SHARKSUSHI = 

TEMPLATE.DESCRIBE.WOBSTERBREADED = 

TEMPLATE.DESCRIBE.LAZYPURRITO = 

TEMPLATE.DESCRIBE.HORCHATA = 

TEMPLATE.DESCRIBE.WOBSTERCOCKTAIL = 

TEMPLATE.DESCRIBE.LAVAEEGGBOILED = 

TEMPLATE.DESCRIBE.POMEGRANATETEA = 

TEMPLATE.DESCRIBE.TIRAMISU = 

TEMPLATE.DESCRIBE.TOADSTOOLCOLA = 

TEMPLATE.DESCRIBE.TEPACHE = 

TEMPLATE.DESCRIBE.LUNARTEQUILA = 

TEMPLATE.DESCRIBE.MIMICMOSA = 

TEMPLATE.DESCRIBE.POMEGRANATEPIE =

TEMPLATE.DESCRIBE.PINEAPPLECAKE = 

TEMPLATE.DESCRIBE.PASTY_MEAT = 
TEMPLATE.DESCRIBE.PASTY_CHEESE = 

TEMPLATE.DESCRIBE.BRIGADEIRO = 

TEMPLATE.DESCRIBE.REGULARLASAGNA =

TEMPLATE.DESCRIBE.FLTSANDWICH = 

TEMPLATE.DESCRIBE.RICEANDBEANS = 

TEMPLATE.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP =
{
	GENERIC =
	REPAIRED =
	OCCUPIED =
	OCCUPIED_REPAIRED =
}

TEMPLATE.DESCRIBE.KYNO_TRUFFLES_GROUND =
{
	GENERIC =
	PICKED =
	BURNING =
}

TEMPLATE.DESCRIBE.KYNO_TRUFFLES =
TEMPLATE.DESCRIBE.KYNO_TRUFFLES_COOKED =

TEMPLATE.DESCRIBE.KYNO_ITEMSHOWCASER =
{
	EMPTY =
	FULL =
}

TEMPLATE.DESCRIBE.KYNO_SPORECAP =
TEMPLATE.DESCRIBE.KYNO_SPORECAP_COOKED =

TEMPLATE.DESCRIBE.KYNO_SPORECAP_DARK =
TEMPLATE.DESCRIBE.KYNO_SPORECAP_DARK_COOKED =

TEMPLATE.DESCRIBE.KYNO_GOLDENAPPLE =

TEMPLATE.DESCRIBE.TRUFFLESGRINDER =

TEMPLATE.DESCRIBE.SPORECAPPIE =

TEMPLATE.DESCRIBE.SPORECAP_SKEWERS =

TEMPLATE.DESCRIBE.TRUFFLEOIL =

TEMPLATE.DESCRIBE.KYNO_FISHFARMPLOT_KIT =
TEMPLATE.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION =

TEMPLATE.DESCRIBE.KYNO_FISHFARMPLOT =
{
	GENERIC =
	FUEL_HIGH =
	FUEL_MED =
	FUEL_LOW =
	EMPTY =
}

TEMPLATE.DESCRIBE.AGEDROE =
TEMPLATE.DESCRIBE.AGEDROE_OCEANFISH_STURGEON =

TEMPLATE.DESCRIBE.KYNO_SWORDFISH_BLUE =

TEMPLATE.DESCRIBE.KYNO_JELLYFISH =
TEMPLATE.DESCRIBE.KYNO_JELLYFISH_DEAD =
TEMPLATE.DESCRIBE.KYNO_JELLYFISH_COOKED =
TEMPLATE.DESCRIBE.KYNO_JELLYFISH_DRIED =

TEMPLATE.DESCRIBE.KYNO_JELLYFISH_RAINBOW =
TEMPLATE.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD =
TEMPLATE.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED =

TEMPLATE.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY =

TEMPLATE.DESCRIBE.KYNO_OCEANTRAP =

TEMPLATE.DESCRIBE.OCEANFISH_MIDNIGHT_CARP =
TEMPLATE.DESCRIBE.OCEANFISH_PUFFERFISH =
TEMPLATE.DESCRIBE.OCEANFISH_STURGEON =

TEMPLATE.DESCRIBE.KYNO_SWORDFISH =
TEMPLATE.DESCRIBE.KYNO_SWORDFISH_DEAD =

TEMPLATE.DESCRIBE.SWORDFISHFEAST =

TEMPLATE.DESCRIBE.KYNO_DOGFISH =
TEMPLATE.DESCRIBE.KYNO_DOGFISH_DEAD =

TEMPLATE.DESCRIBE.KYNO_SPOILED_FISH_LARGE =

TEMPLATE.DESCRIBE.WOBSTER_MONKEYISLAND =
TEMPLATE.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD =
TEMPLATE.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED =

TEMPLATE.DESCRIBE.KYNO_PUFFERMONSTER =

TEMPLATE.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES =
TEMPLATE.DESCRIBE.KYNO_WHALE_BLUE_OCEAN =
TEMPLATE.DESCRIBE.KYNO_WHALE_WHITE_OCEAN =
TEMPLATE.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS =

TEMPLATE.DESCRIBE.KYNO_BLUBBER =

TEMPLATE.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED =
TEMPLATE.DESCRIBE.KYNO_FISHMEAT_DRIED =

TEMPLATE.DESCRIBE.MONKEYISLANDMEAL =

TEMPLATE.DESCRIBE.KYNO_BRAINROCK_LARVAE =
TEMPLATE.DESCRIBE.KYNO_BRAINROCK_NUBBIN =
TEMPLATE.DESCRIBE.KYNO_BRAINROCK_CORAL =

TEMPLATE.DESCRIBE.KYNO_BRAINROCK_ROCK =
{
	GENERIC =
	PICKED =
}

TEMPLATE.DESCRIBE.BRAINMETTERSOUP =

TEMPLATE.DESCRIBE.KYNO_OCTOPUSKING_OCEAN =
{
	GENERIC =
	SLEEPING =
}

TEMPLATE.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST =

TEMPLATE.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE =
{
	GENERIC =
	WAITING =
}

TEMPLATE.DESCRIBE.KYNO_PACKIMBAGGIMS =

TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION =
TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE =
TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE =
TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE =
TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER =
TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE =
TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS =

TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE =
{
	GENERIC =
	FUEL_HIGH =
	FUEL_MED =
	FUEL_LOW =
	EMPTY =
}

TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN =
TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_HAT =
TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT =
TEMPLATE.DESCRIBE.KYNO_HOFBIRTHDAY_PARTITIOHAT =

TEMPLATE.DESCRIBE.KYNO_FISHREGISTRYHAT = 

TEMPLATE.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC =
	FUEL_HIGH =
	FUEL_MED =
	FUEL_LOW =
	EMPTY =
	BURNT =
}

TEMPLATE.DESCRIBE.CHICKENNUGGETS =

TEMPLATE.DESCRIBE.CHICKENWINGS =

TEMPLATE.DESCRIBE.CHICKENBURGER =

TEMPLATE.DESCRIBE.CHICKENEGGSOUP =

TEMPLATE.DESCRIBE.CHICKENEGGSTEW =

TEMPLATE.DESCRIBE.CHICKENROTISSERIE = 

TEMPLATE.DESCRIBE.KYNO_HERMITCRABTEA_ALOE =
TEMPLATE.DESCRIBE.KYNO_HERMITCRABTEA_SUGARTREE_PETALS =
TEMPLATE.DESCRIBE.KYNO_HERMITCRABTEA_ICENETTLES =

TEMPLATE.DESCRIBE.SOULJUICE =

TEMPLATE.DESCRIBE.KYNO_DAILYRECIPE =
TEMPLATE.DESCRIBE.KYNO_DAILYRECIPE_SIGN =
{ 
	GENERIC =
	NONE =
	BURNING =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_DECIDUOUSFOREST_SELLER =
{
	GENERIC =
	HOUSE_REPAIRED =
}

TEMPLATE.DESCRIBE.KYNO_CAVETUBERTREE =
{
	GENERIC =
	CHOPPED =
	BLOOMING =
	BURNING =
	BURNT =
}

TEMPLATE.DESCRIBE.KYNO_CAVETUBER =
TEMPLATE.DESCRIBE.KYNO_CAVETUBER_COOKED =

TEMPLATE.DESCRIBE.KYNO_CAVETUBER_BLOOMING =
TEMPLATE.DESCRIBE.KYNO_CAVETUBER_BLOOMING_COOKED =

TEMPLATE.DESCRIBE.CAVETUBERTEA =

TEMPLATE.DESCRIBE.KYNO_ELDERMANDRAKEHOUSE =
{
	GENERIC =
	OCCUPIED =
}

TEMPLATE.DESCRIBE.KYNO_ELDERMANDRAKE =
{
	GENERIC =
	GRUMPY =
}

TEMPLATE.DESCRIBE.MANDRAKEBAOBUNS =

TEMPLATE.DESCRIBE.MANDRAKEPIE =

TEMPLATE.DESCRIBE.MANDRAKEBEER =

TEMPLATE.DESCRIBE.RAINPARFAIT =

TEMPLATE.DESCRIBE.MIDNIGHTFEAST =

TEMPLATE.DESCRIBE.KYNO_PLANTBOOSTER_GROWTH =
TEMPLATE.DESCRIBE.KYNO_PLANTBOOSTER_VITALITY =
TEMPLATE.DESCRIBE.KYNO_PLANTBOOSTER_YIELD =
TEMPLATE.DESCRIBE.KYNO_PLANTBOOSTER_SUPERGROWTH =

TEMPLATE.DESCRIBE.KYNO_PIGCOIN1 =
TEMPLATE.DESCRIBE.KYNO_PIGCOIN2 =
TEMPLATE.DESCRIBE.KYNO_PIGCOIN3 =

TEMPLATE.DESCRIBE.KYNO_ICENETTLES =
TEMPLATE.DESCRIBE.KYNO_ICENETTLES_DRIED =

TEMPLATE.DESCRIBE.KYNO_SEEDSBAG =
{
	GENERIC =
	FULL =
}

TEMPLATE.DESCRIBE.KYNO_FOODAMMO_TOMATO =

TEMPLATE.DESCRIBE.WX78MODULE_GOURMAND =
TEMPLATE.DESCRIBE.WX78MODULE_COOKER =
TEMPLATE.DESCRIBE.WX78MODULE_DRYER =
TEMPLATE.DESCRIBE.WX78MODULE_DRYER2 =

TEMPLATE.DESCRIBE.KYNO_WX78_INVENTORYCOOKER =
{
	HELD =
	NOPOWER =
	GENERIC =
}

TEMPLATE.DESCRIBE.KYNO_WX78_INVENTORYDRYER =
{
	HELD =
	NOPOWER =
	GENERIC =
}

TEMPLATE.DESCRIBE.KYNO_WX78_INVENTORYDRYER2 =
{
	HELD =
	NOPOWER =
	GENERIC =
}

TEMPLATE.DESCRIBE.KYNO_PIGGYBANK =
{
	FULL =
	UPGRADED =
	GENERIC =
}

TEMPLATE.DESCRIBE.MARSHMALLOWS =

TEMPLATE.DESCRIBE.KOKONUTCOOKIES = 

TEMPLATE.DESCRIBE.BBQRIBS =

TEMPLATE.DESCRIBE.BROWNIE =

TEMPLATE.DESCRIBE.CHOCOLATE_CAKE =

TEMPLATE.DESCRIBE.SWORDFISHBLUEDINNER =