local WANDA = STRINGS.CHARACTERS.WANDA

WANDA.ANNOUNCE_KYNO_COFFEEBUFF_START = "我觉得自己很年轻！"
WANDA.ANNOUNCE_KYNO_COFFEEBUFF_END = "我现在能感觉到我的真实年龄了……"

WANDA.ANNOUNCE_KYNO_HASTEBUFF_START = "加速！"
WANDA.ANNOUNCE_KYNO_HASTEBUFF_END = "我的匆忙已经结束了。"

WANDA.ANNOUNCE_KYNO_POPBUFF_START = "（嗝！）哦，好吧。请原谅我的举止。"
WANDA.ANNOUNCE_KYNO_POPBUFF_END = "喝了那杯酒后感觉又年轻了。"

WANDA.ANNOUNCE_KYNO_FROGBUFF_START = "我没有时间浪费在青蛙身上。"
WANDA.ANNOUNCE_KYNO_FROGBUFF_END = "气味终于消失了。"

WANDA.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝!) 哦，好吧。他们看不到我来了！"
WANDA.ANNOUNCE_KYNO_PIRATEBUFF_END = "喝完这杯酒，感觉又年轻了。"

WANDA.ANNOUNCE_KYNO_FREEZEBUFF_START = "这里越来越冷了。"
WANDA.ANNOUNCE_KYNO_FREEZEBUFF_END = "这是一次有趣的经历。"

WANDA.ANNOUNCE_KYNO_FIREBUFF_START = "火焰，把它们都烧了！"
WANDA.ANNOUNCE_KYNO_FIREBUFF_END = "这是一次有趣的经历。"

WANDA.ANNOUNCE_KYNO_FISHINGBUFF_START = "我希望没有垂钓者来找奇怪的鱼。"
WANDA.ANNOUNCE_KYNO_FISHINGBUFF_END = "至少没有垂钓者出现。"

WANDA.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "宁静的时光......"
WANDA.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "宁静的时光已经过去。"

WANDA.ANNOUNCE_KYNO_EATERBUFF_START = "我现在可以吃各种糖果了！"
WANDA.ANNOUNCE_KYNO_EATERBUFF_END = "甜食恢复正常。"

WANDA.ANNOUNCE_KYNO_WORMBUFF_START = "没有时间浪费！走吧。"
WANDA.ANNOUNCE_KYNO_WORMBUFF_END = "唉。时间已经结束了。"

WANDA.ANNOUNCE_KYNO_CRABBUFF_START = "没有时间可以浪费了！走吧。"
WANDA.ANNOUNCE_KYNO_CRABBUFF_END = "唉。时间已经结束了。"

WANDA.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝！) 哦，好吧。请原谅我的失礼。"
WANDA.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "喝了那杯酒后，感觉又年轻了。"

WANDA.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "充满了月亮的力量。"
WANDA.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "月亮的力量渐渐变小了。"

WANDA.ANNOUNCE_KYNO_STEALTHBUFF_START = "我看不见吗？我看不见！"
WANDA.ANNOUNCE_KYNO_STEALTHBUFF_END = "真倒霉。我喜欢不被发现的时候。"

WANDA.ANNOUNCE_KYNO_FEARBUFF_START = "我最终终于摆脱了恐惧！"
WANDA.ANNOUNCE_KYNO_FEARBUFF_END = "现在再次笼罩在恐惧之中！"

WANDA.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "时间……在我身边弯曲！"
WANDA.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "时间夺回了它赐予的……一如既往。"

WANDA.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "连猪也会跟随我穿越时空。"
WANDA.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "即便是猪，也无法永远跟随我。"

WANDA.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "这次，时间也腐蚀不了我。"
-- 没有 ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END，因为我们对此使用默认字符串。

WANDA.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "终于有件事是时间也毁不了的。"
WANDA.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "时间到了……真是字面意义上的。"

WANDA.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "太好了！我能清晰思考——现在不再浪费时间了。"
WANDA.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "注意力散了……真是浪费时间。"

WANDA.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "很好，不用再浪费时间拍愤怒的蜜蜂了。"
WANDA.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "平静没了……又要开始被蜇了。"

WANDA.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "再向命运借点时间……"
WANDA.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "时间又追上了……"

WANDA.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "饥饿加剧……问题更多。"
WANDA.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "时光赐予，时光夺走……"

WANDA.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "啊……终于，心安了。"
WANDA.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "理智从来不会停留太久……"

WANDA.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "很好。多加一层保护就能节省宝贵的时间。"
WANDA.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "就这样了。时机至关重要。"

WANDA.ANNOUNCE_KYNO_BERSERKERBUFF_START = "短暂的鲁莽爆发！"
WANDA.ANNOUNCE_KYNO_BERSERKERBUFF_END = "很好。我更喜欢经过计算的风险。"

WANDA.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "至少饥饿变慢了。"
WANDA.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "时间追了上来。饥饿也是如此。"

WANDA.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "不……我需要别的。"

WANDA.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "我想我还有时间给你弄只龙虾。"

WANDA.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "这需要一些时间，啊……"

WANDA.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "错了！"

WANDA.ANNOUNCE_KYNO_POTHANGER_FAIL = "该去找个锅来煮这个了。"

WANDA.ANNOUNCE_KYNO_CASSEROLE_FAIL = "找到正确的答案需要一些时间。"

WANDA.ANNOUNCE_KYNO_SAPHEALER_USED = "这解药会给你第二次机会。"

WANDA.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "时间终将耗尽，对所有人，对所有事物。"

WANDA.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "空的？真是浪费我宝贵的时间。"

WANDA.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "我既迷失了方向，又浪费了时间。真棒。"
WANDA.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "这场雨抹去了所有找到它的机会。"
WANDA.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "终于！让我们结束这场追捕吧。"

WANDA.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "正好！趁着这美好时光尚未溜走，让我们尽情享受吧。"

WANDA.ANNOUNCE_KYNO_FISH_RESEARCHED = "很好，又少了一条浪费我时间的鱼。"
WANDA.ANNOUNCE_KYNO_ROE_RESEARCHED = "如此多的未来，一次性展现。"

WANDA.DESCRIBE.KYNO_ROE = "这是我第一次看到这个。"
WANDA.DESCRIBE.KYNO_ROE_COOKED = "闻起来很香。"

WANDA.DESCRIBE.KYNO_SHARK_FIN = "一条鱼翅。"

WANDA.DESCRIBE.KYNO_BEANBUGS = "虫子。"
WANDA.DESCRIBE.KYNO_BEANBUGS_COOKED = "我猜，就是这样。"

WANDA.DESCRIBE.KYNO_GUMMYBUG = "虫子。"
WANDA.DESCRIBE.KYNO_GUMMYBUG_COOKED = "我猜，就是这样。"

WANDA.DESCRIBE.KYNO_WHEAT = "我可以做面包..."
WANDA.DESCRIBE.KYNO_WHEAT_COOKED = "面包仍然是最好的选择。"

WANDA.DESCRIBE.KYNO_FLOUR = "面包几乎是我的了……！"

WANDA.DESCRIBE.KYNO_SPOTSPICE = "太好了！太好了！"

WANDA.DESCRIBE.KYNO_SAP = "甜蜜！"
WANDA.DESCRIBE.KYNO_SAP_SPOILED = "现在只是个燃料。"

WANDA.DESCRIBE.KYNO_SYRUP = "啊哈。令人耳目一新。"

WANDA.DESCRIBE.KYNO_COFFEEBEANS = "咖啡豆！"
WANDA.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "我现在可以烤咖啡了。"

WANDA.DESCRIBE.DUG_KYNO_COFFEEBUSH = "那是咖啡灌木吗？！"

WANDA.DESCRIBE.KYNO_COFFEEBUSH =
{
	GENERIC = "一种人们依赖的植物。",
	PICKED = "它需要时间。",
	WITHERED = "这个时机不对。",
}

WANDA.DESCRIBE.DUG_KYNO_SPOTBUSH = "它的未来取决于它被种植的地方。"

WANDA.DESCRIBE.KYNO_SPOTBUSH =
{
	GENERIC = "一株灌木。",
	PICKED = "时间会修复它。",
	BURNING = "那本不必发生。",
}

WANDA.DESCRIBE.KYNO_SPOTSPICE_LEAF = "我猜，我可以用它来做点什么……"

WANDA.DESCRIBE.KYNO_MUSSEL = "我需要一些时间才能把这道菜做好。"
WANDA.DESCRIBE.KYNO_MUSSEL_COOKED = "看起来很好吃。"

WANDA.DESCRIBE.KYNO_HUMANMEAT = "呃。"
WANDA.DESCRIBE.KYNO_HUMANMEAT_COOKED = "我没时间做这个。"
WANDA.DESCRIBE.KYNO_HUMANMEAT_DRIED = "恶心！"

WANDA.DESCRIBE.COFFEE = "啊，好老咖啡。"

WANDA.DESCRIBE.BISQUE = "汤。"

WANDA.DESCRIBE.JELLYOPOP = "棒棒糖。"

WANDA.DESCRIBE.SHARKFINSOUP = "鲨鱼汤？我要了。"

WANDA.DESCRIBE.TROPICALBOUILLABAISSE = "有很多鱼的汤，很有趣。"

WANDA.DESCRIBE.MUSSELBOUILLABAISE = "我最喜欢的汤！"

WANDA.DESCRIBE.SWEETPOTATOSOUFFLE = "好吃！"

WANDA.DESCRIBE.FEIJOADA = "经典巴西菜。"

WANDA.DESCRIBE.GUMMY_CAKE = "甜蜜！"

WANDA.DESCRIBE.HARDSHELL_TACOS = "很难吃……"

WANDA.DESCRIBE.ICEDTEA = "提神醒脑。"

WANDA.DESCRIBE.NETTLELOSANGE = "这最好给我一些时间......"

WANDA.DESCRIBE.SNAKEBONESOUP = "用骨头做的汤，很新奇。"

WANDA.DESCRIBE.STEAMEDHAMSANDWICH = "汉堡！"

WANDA.DESCRIBE.TEA = "经典饮品。"

WANDA.DESCRIBE.BUBBLETEA = "它在冒泡......"

WANDA.DESCRIBE.FRENCHONIONSOUP = "我喜欢这个。"

WANDA.DESCRIBE.SLAW = "吃你的蔬菜！"

WANDA.DESCRIBE.LOTUSBOWL = "由大自然制成。"

WANDA.DESCRIBE.POI = "一种奇怪的食物。"

WANDA.DESCRIBE.JELLYBEAN_HUNGER = "它会满足我的饥饿感。"
WANDA.DESCRIBE.JELLYBEAN_SUPER = "这会让我再次年轻吗？"
WANDA.DESCRIBE.JELLYBEAN_SANITY = "帮助我思考。"

WANDA.DESCRIBE.BOWLOFGEARS = "只是一堆齿轮。"

WANDA.DESCRIBE.LONGPIGMEAL = "不！"

WANDA.DESCRIBE.CUCUMBERSALAD = "一份海沙拉。"

WANDA.DESCRIBE.DUG_KYNO_WILDWHEAT = "需要种在更好的地方。"

WANDA.DESCRIBE.KYNO_WILDWHEAT =
{
	GENERIC = "你在这儿附近能找到很多。",
	PICKED = "它需要时间。",
	WITHERED = "这个时机不对。",
	BURNING = "那是可以避免的。",
}

WANDA.DESCRIBE.KYNO_MEALGRINDER = "是时候研磨一些原料了！"

WANDA.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "生命以意想不到的方式延续。",
	PICKED = "只是时间问题。",
	BURNING = "这个结果是可以避免的。",
}

WANDA.DESCRIBE.GORGE_BREAD = "终于！面包！"
WANDA.DESCRIBE.GORGE_SWEET_CHIPS = "它们很不错。"
WANDA.DESCRIBE.GORGE_VEGETABLE_SOUP = "我们吃吧！"
WANDA.DESCRIBE.GORGE_JELLY_SANDWICH = "已经是这个时间了？"
WANDA.DESCRIBE.GORGE_FISH_STEW = "等不及要试试了。"
WANDA.DESCRIBE.GORGE_MEAT_STEW = "真的有必要把骨头留在里面吗？"
WANDA.DESCRIBE.GORGE_ONION_CAKE = "我更喜欢甜蛋糕。"
WANDA.DESCRIBE.GORGE_POTATO_PANCAKES = "软软的。"
WANDA.DESCRIBE.GORGE_POTATO_SOUP = "汤。"
WANDA.DESCRIBE.GORGE_FISHBALL_SKEWERS = "还可以更好。"
WANDA.DESCRIBE.GORGE_MEAT_SKEWERS = "真好吃！"
WANDA.DESCRIBE.GORGE_STONE_SOUP = "汤。"
WANDA.DESCRIBE.GORGE_CROQUETTE = "这很好。"
WANDA.DESCRIBE.GORGE_ROAST_VEGETABLES = "呃..."
WANDA.DESCRIBE.GORGE_MEATLOAF = "味道不错。"
WANDA.DESCRIBE.GORGE_CARROT_SOUP = "汤。"
WANDA.DESCRIBE.GORGE_FISHPIE = "食物就是食物。"
WANDA.DESCRIBE.GORGE_FISHCHIPS = "非常好！"
WANDA.DESCRIBE.GORGE_MEATPIE = "满载。"
WANDA.DESCRIBE.GORGE_SLIDERS = "我需要更多。"
WANDA.DESCRIBE.GORGE_JELLY_ROLL = "太美味了！"
WANDA.DESCRIBE.GORGE_CARROT_CAKE = "哦，我亲爱的上帝！"
WANDA.DESCRIBE.GORGE_GARLICMASHED = "香气扑鼻。"
WANDA.DESCRIBE.GORGE_GARLICBREAD = "我们需要一些肉。"
WANDA.DESCRIBE.GORGE_TOMATO_SOUP = "汤。"
WANDA.DESCRIBE.GORGE_SAUSAGE = "质地很好。"
WANDA.DESCRIBE.GORGE_CANDIEDFISH = "这很有趣。"
WANDA.DESCRIBE.GORGE_STUFFEDMUSHROOM = "外观和味道都不错。"
WANDA.DESCRIBE.GORGE_BRUSCHETTA = "这道菜很不错。"
WANDA.DESCRIBE.GORGE_HAMBURGER = "一个汉堡包！我好想念它们！"
WANDA.DESCRIBE.GORGE_FISHBURGER = "一个汉堡包！我好想念他们！"
WANDA.DESCRIBE.GORGE_MUSHROOMBURGER = "一个汉堡包！我好想念他们！"
WANDA.DESCRIBE.GORGE_FISH_STEAK = "等不及要试试了。"
WANDA.DESCRIBE.GORGE_CURRY = "很好!"
WANDA.DESCRIBE.GORGE_SPAGHETTI = "意大利面条，快速而切题。"
WANDA.DESCRIBE.GORGE_POACHEDFISH = "我开始喜欢鲑鱼菜肴了。"
WANDA.DESCRIBE.GORGE_SHEPHERD_PIE = "这是一个传奇！"
WANDA.DESCRIBE.GORGE_CANDY = "我永远不会忘记，爸爸过去常常在特殊场合为我们带这些回家。"
WANDA.DESCRIBE.GORGE_BREAD_PUDDING = "这一点不会错！"
WANDA.DESCRIBE.GORGE_BERRY_TART = "美味可口！"
WANDA.DESCRIBE.GORGE_MACARONI = "有品位！"
WANDA.DESCRIBE.GORGE_BAGEL_AND_FISH = "这里需要一些甜味。"
WANDA.DESCRIBE.GORGE_GRILLED_CHEESE = "我可以吃上一整天。"
WANDA.DESCRIBE.GORGE_CREAMMUSHROOM = "看起来可以吃。"
WANDA.DESCRIBE.GORGE_MANICOTTI = "有品位。"
WANDA.DESCRIBE.GORGE_CHEESEBURGER = "一个汉堡包！我好想念他们！"
WANDA.DESCRIBE.GORGE_FETTUCCINE = "不太喜欢这个。"
WANDA.DESCRIBE.GORGE_ONION_SOUP = "啊，这可不太好。"
WANDA.DESCRIBE.GORGE_BREADED_CUTLET = "很棒的三明治。"
WANDA.DESCRIBE.GORGE_CREAMY_FISH = "看起来不错。"
WANDA.DESCRIBE.GORGE_PIZZA = "披萨？！我不敢相信！"
WANDA.DESCRIBE.GORGE_POT_ROAST = "干得漂亮。"
WANDA.DESCRIBE.GORGE_CRAB_CAKE = "为什么要浪费时间把它弄成这个样子？"
WANDA.DESCRIBE.GORGE_STEAK_FRITES = "可爱！"
WANDA.DESCRIBE.GORGE_SHOOTER_SANDWICH = "需要一点胡椒粉。"
WANDA.DESCRIBE.GORGE_BACON_WRAPPED = "早餐就足够了。"
WANDA.DESCRIBE.GORGE_CRAB_ROLL = "这道菜不错。"
WANDA.DESCRIBE.GORGE_MEAT_WELLINGTON = "令人惊叹。"
WANDA.DESCRIBE.GORGE_CRAB_RAVIOLI = "这道菜不错。"
WANDA.DESCRIBE.GORGE_CARAMEL_CUBE = "我认识对的人，他喜欢这个。"
WANDA.DESCRIBE.GORGE_SCONE = "这也许是我的最爱！"
WANDA.DESCRIBE.GORGE_TRIFLE = "不，不，这才是我的最爱！"
WANDA.DESCRIBE.GORGE_CHEESECAKE = "我等不及要吃了!"

WANDA.DESCRIBE.DUCKYOUGLERMZ = "我无话可说。"

WANDA.DESCRIBE.KYNO_ALOE = "一种药用植物。"
WANDA.DESCRIBE.KYNO_ALOE_COOKED = "不再是药用。"
WANDA.DESCRIBE.KYNO_ALOE_GROUND = "一种药用植物。"
WANDA.DESCRIBE.KYNO_ALOE_SEEDS = "只是种子。"
WANDA.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "只是种子。"
WANDA.DESCRIBE.FARM_PLANT_KYNO_ALOE = "啊，芦荟。"
WANDA.DESCRIBE.KYNO_ALOE_OVERSIZED = "啊，芦荟，巨型的。"
WANDA.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "太糟糕了。"

WANDA.DESCRIBE.KYNO_CUCUMBER = "一条海参！"
WANDA.DESCRIBE.KYNO_CUCUMBER_COOKED = "呸！"
WANDA.DESCRIBE.KYNO_CUCUMBER_GROUND = "一条海参！"
WANDA.DESCRIBE.KYNO_CUCUMBER_SEEDS = "只是种子。"
WANDA.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "只是种子。"
WANDA.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "黄瓜..."
WANDA.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "嘿。一个大的。"
WANDA.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "哎呀。"

WANDA.DESCRIBE.KYNO_RADISH = "一个萝卜。"
WANDA.DESCRIBE.KYNO_RADISH_COOKED = "我的舌头现在更红了。"
WANDA.DESCRIBE.KYNO_RADISH_GROUND = "一个萝卜。"
WANDA.DESCRIBE.KYNO_RADISH_SEEDS = "只是种子。"
WANDA.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "只是种子。"
WANDA.DESCRIBE.FARM_PLANT_KYNO_RADISH = "一株萝卜。"
WANDA.DESCRIBE.KYNO_RADISH_OVERSIZED = "红萝卜！"
WANDA.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "太糟糕了。"

WANDA.DESCRIBE.KYNO_FENNEL = "看起来很好奇。"
WANDA.DESCRIBE.KYNO_FENNEL_COOKED = "热！"
WANDA.DESCRIBE.KYNO_FENNEL_GROUND = "看起来很好奇。"
WANDA.DESCRIBE.KYNO_FENNEL_SEEDS = "只是种子。"
WANDA.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "只是种子。"
WANDA.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "肯定是茴香！"
WANDA.DESCRIBE.KYNO_FENNEL_OVERSIZED = "肯定是茴香！"
WANDA.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "太糟糕了。"

WANDA.DESCRIBE.KYNO_SWEETPOTATO = "野土豆！"
WANDA.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "甜！"
WANDA.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "野土豆！"
WANDA.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "只是种子。"
WANDA.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "只是种子。"
WANDA.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "野土豆！"
WANDA.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "一个巨大的，红薯！"
WANDA.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "太糟糕了。"

WANDA.DESCRIBE.KYNO_PARZNIP = "一种地下欧洲防风草。"
WANDA.DESCRIBE.KYNO_PARZNIP_COOKED = "营养丰富。"
WANDA.DESCRIBE.KYNO_PARZNIP_EATEN = "我可以留一些供以后使用。"
WANDA.DESCRIBE.KYNO_PARZNIP_GROUND = "一种地下欧洲防风草。"
WANDA.DESCRIBE.KYNO_PARZNIP_BIG = "它们很大。"
WANDA.DESCRIBE.KYNO_PARZNIP_SEEDS = "只是种子。"
WANDA.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "只是种子。"
WANDA.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "欧洲防风草根。"
WANDA.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "一个大的欧洲防风草，就像地下的。"
WANDA.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "太糟糕了。"

WANDA.DESCRIBE.KYNO_TURNIP = "这是一种很受欢迎的蔬菜。"
WANDA.DESCRIBE.KYNO_TURNIP_COOKED = "营养丰富！"
WANDA.DESCRIBE.KYNO_TURNIP_GROUND = "这是一种很受欢迎的蔬菜。"
WANDA.DESCRIBE.KYNO_TURNIP_SEEDS = "只是种子。"
WANDA.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "只是种子。"
WANDA.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "萝卜。"
WANDA.DESCRIBE.KYNO_TURNIP_OVERSIZED = "超大萝卜。"
WANDA.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "太糟糕了。"

WANDA.DESCRIBE.KYNO_RICE = "太淡了。"
WANDA.DESCRIBE.KYNO_RICE_COOKED = "太淡了。"
WANDA.DESCRIBE.KYNO_RICE_SEEDS = "只是种子。"
WANDA.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "只是种子。"
WANDA.DESCRIBE.FARM_PLANT_KYNO_RICE = "只是米饭。"
WANDA.DESCRIBE.KYNO_RICE_OVERSIZED = "只是米饭。"
WANDA.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "太糟糕了。"

WANDA.DESCRIBE.KYNO_SEEDS_KIT = "种子。"

WANDA.DESCRIBE.KYNO_LIMPETROCK =
{
	GENERIC = "一块能产出食物的岩石？！",
	PICKED = "只是等待的问题。",
	WITHERED = "此刻一无所获。",
}

WANDA.DESCRIBE.KYNO_LIMPETS = "蜗牛。"
WANDA.DESCRIBE.KYNO_LIMPETS_COOKED = "再见，再见，蜗牛。"

WANDA.DESCRIBE.KYNO_LOTUS_OCEAN =
{
	GENERIC = "一种可食用的花。",
	PICKED = "它会及时回来的。",
	BURNING = "这个结果是可以避免的。",
}

WANDA.DESCRIBE.KYNO_LOTUS_ROOT = "植物的根，可以种在某个地方。"
WANDA.DESCRIBE.KYNO_LOTUS_FLOWER = "一朵可食用的花。"
WANDA.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "好吃！"

WANDA.DESCRIBE.KYNO_SEAWEEDS_OCEAN =
{
	GENERIC = "杂草。",
	PICKED = "假以时日，它会回来的。",
	BURNING = "那本不该发生。",
}

WANDA.DESCRIBE.KYNO_SEAWEEDS = "杂草。"
WANDA.DESCRIBE.KYNO_SEAWEEDS_COOKED = "烤熟的杂草。"
WANDA.DESCRIBE.KYNO_SEAWEEDS_DRIED = "来自海边的干枯海藻。"
WANDA.DESCRIBE.KYNO_SEAWEEDS_ROOT = "杂草根，可以在某处种植。"

WANDA.DESCRIBE.KYNO_TAROROOT_OCEAN =
{
	GENERIC = "奇怪的植物。",
	PICKED = "它会比预期更快回来。",
	BURNING = "这个结果是可以避免的。",
}

WANDA.DESCRIBE.KYNO_TAROROOT_ROOT = "植物的根，可以种在某个地方。"
WANDA.DESCRIBE.KYNO_TAROROOT = "嗯..."
WANDA.DESCRIBE.KYNO_TAROROOT_COOKED = "闻起来很香......"

WANDA.DESCRIBE.KYNO_WATERYCRESS_OCEAN =
{
	GENERIC = "短暂的片刻新鲜。",
	PICKED = "它应该很快就会回来。",
	BURNING = "那结束得比预期早。",
}

WANDA.DESCRIBE.KYNO_WATERYCRESS_ROOT = "杂草的根，可以种在某个地方。"
WANDA.DESCRIBE.KYNO_WATERYCRESS = "白菜，但是在这里？"

WANDA.DESCRIBE.WATERYCRESSBOWL = "我喜欢这汤！"

WANDA.DESCRIBE.KYNO_SALT = "只是盐。"

WANDA.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "随着时间的推移缓慢收获。",
	PICKED = "此刻一无所获。",
	BURNING = "那不是不可避免的。",
}

WANDA.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "迟早会有很多贻贝等着我。"

WANDA.DESCRIBE.CATFOOD = "是时候喂猫了。"

WANDA.DESCRIBE.KATFOOD = "是时候喂猫了。"

WANDA.DESCRIBE.KYNO_BANANATREE =
{
	GENERIC = "稀有的东西从来不会持久。",
	PICKED = "只是时间问题。",
	CHOPPED = "它的时间线在此终结。",
	BURNING = "这个结果是可以避免的。",
	BURNT = "现在太晚了。",
}

WANDA.DESCRIBE.KYNO_BANANA = "我喜欢没有大惊小怪的快餐。"
WANDA.DESCRIBE.KYNO_BANANA_COOKED = "我为什么要花时间做饭？"

WANDA.DESCRIBE.KYNO_KOKONUTTREE =
{
	GENERIC = "一棵棕榈树。",
	PICKED = "只是等待的问题。",
	CHOPPED = "它的时间在此终结。",
	BURNING = "这是可以避免的。",
	BURNT = "现在太晚了。",
}

WANDA.DESCRIBE.KYNO_KOKONUT = "需要一些时间才能打开它。"
WANDA.DESCRIBE.KYNO_KOKONUT_HALVED = "吃的时间加倍。"
WANDA.DESCRIBE.KYNO_KOKONUT_COOKED = "时间不多了！"

WANDA.DESCRIBE.BOWLOFPOPCORN = "它真的可以用一些黄油。"

WANDA.DESCRIBE.FIGJUICE = "提神醒脑。"

WANDA.DESCRIBE.COCONUTWATER = "提神醒脑。"

WANDA.DESCRIBE.EYEBALLSPAGHETTI = "现在不是这样做的时候。"

WANDA.DESCRIBE.FORGETMELOTS_SEEDS = "只是种子。"

WANDA.DESCRIBE.FIRENETTLES_SEEDS = "只是种子。"

WANDA.DESCRIBE.TILLWEED_SEEDS = "只是种子。"

WANDA.DESCRIBE.KYNO_FLOATILIZER = "肥料，方便地存放在桶中。"

WANDA.DESCRIBE.KYNO_TWIGGYNUTS = "你的家没了，小家伙。"

WANDA.DESCRIBE.KYNO_REPAIRTOOL = "它能修好我的手表吗？"

WANDA.DESCRIBE.KYNO_KOI = "这是一条锦鲤，如果我没记错的话。"
WANDA.DESCRIBE.KYNO_KOI_COOKED = "烤得恰到好处。"

WANDA.DESCRIBE.KYNO_TROPICALFISH = "对，另一条鱼。"
WANDA.DESCRIBE.KYNO_TROPICALFISH_COOKED = "好吧，又一条死鱼。"

WANDA.DESCRIBE.KYNO_NEONFISH = "对，另一条鱼。"
WANDA.DESCRIBE.KYNO_NEONFISH_COOKED = "更精致一点，我猜。"

WANDA.DESCRIBE.KYNO_GROUPER = "对，另一条鱼。"
WANDA.DESCRIBE.KYNO_GROUPER_COOKED = "一次咬一口。"

WANDA.DESCRIBE.KYNO_PIERROTFISH = "对，另一条鱼。"
WANDA.DESCRIBE.KYNO_PIERROTFISH_COOKED = "好！"

WANDA.DESCRIBE.KYNO_SALMONFISH = "对，另一条鱼。"
WANDA.DESCRIBE.KYNO_SALMONFISH_COOKED = "一条精致的鱼，我是一个精致的女人。"

WANDA.DESCRIBE.TURF_PINKPARK = "真可爱。"
WANDA.DESCRIBE.TURF_STONECITY = "道路..."
WANDA.DESCRIBE.TURF_FIELDS = "但愿时间能如此轻易地被培育出来。"
WANDA.DESCRIBE.TURF_TIDALMARSH = "沼泽。"

WANDA.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "为了些水晶玩这么久等待游戏。",
	PICKED = "这需要一些时间。",
}

WANDA.DESCRIBE.KYNO_SALTRACK_INSTALLER = "我必须先组装它。"

WANDA.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "从树上获取汁液需要一些时间。"

WANDA.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "他们的时代已经到来。"

WANDA.DESCRIBE.KYNO_SERENITYISLAND_SHOP =
{
	GENERIC = "我看到时间对你做了什么。",
	SLEEPING = "总有一天你会永远沉睡。",
}

WANDA.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "甜蜜与时间的循环。",
	CHOPPED = "它的未来被缩短了。",
	SAPPED = "现在是正确的时刻。",
	PICKED = "过程还在继续。",
	BURNING = "这不是不可避免的。",
	BURNT = "现在改变太晚了。",
}

WANDA.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "它的时间线出了问题。",
	CHOPPED = "这里没有未来可言。",
	SAPPED = "太晚修复了。",
	PICKED = "它不断重复错误。",
	BURNING = "这结束了循环。",
	BURNT = "时间在它身上闭合了。",
}

WANDA.DESCRIBE.KYNO_SUGARTREE_BUD = "我需要把它种在某个地方。"

WANDA.DESCRIBE.KYNO_SUGARTREE_FLOWER = "我有比采花更紧迫的事情要做。"
WANDA.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "我有比采花更紧迫的事情要做。"

WANDA.DESCRIBE.KYNO_SUGARTREE_PETALS = "我有比采花更紧迫的事情要做。"

WANDA.DESCRIBE.KYNO_PEBBLECRAB = "这是一只小螃蟹。"

WANDA.DESCRIBE.KYNO_CRABMEAT = "蟹肉，完美搭配精致菜肴。"
WANDA.DESCRIBE.KYNO_CRABMEAT_COOKED = "准备吃。"
WANDA.DESCRIBE.KYNO_CRABMEAT_DRIED = "一种蟹肉，非常适合制作精致菜肴。"

WANDA.DESCRIBE.KYNO_CRABKINGMEAT = "一种蟹肉，非常适合制作精致菜肴。"
WANDA.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "蟹肉，非常适合做精致的菜肴。"
WANDA.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "蟹肉，非常适合做精致的菜肴。"

WANDA.DESCRIBE.KYNO_SLAUGHTERTOOL = "我希望我没有空闲时间来使用它。"

WANDA.DESCRIBE.KYNO_CHICKEN2 =
{
	GENERIC = "啊。一只小鸡！",
	COOP = "被保护在这个时刻。",
}

WANDA.DESCRIBE.KYNO_CHICKEN_EGG = "什么，你这个蛋？"
WANDA.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "我可没时间等这么大的东西孵化。"
WANDA.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "每当我做鸡蛋时，它们要么未烤熟，要么被烧焦。"

WANDA.DESCRIBE.KYNO_CHICKENHOUSE =
{
	GENERIC = "一个时机恰到好处的解决方案，确保持续的鸡蛋供应。",
	FULL = "准时。",
	BURNT = "现在来不及救它了。",
}

WANDA.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "现在不是修理东西的时候！只有时钟。"

WANDA.DESCRIBE.KYNO_COOKWARE_KIT = "哦，这需要一些时间......"
WANDA.DESCRIBE.KYNO_COOKWARE_SYRUP = "现在我只需要找一些树液放在这里。"
WANDA.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "现在我只需要找到一些汁液放在这里。"
WANDA.DESCRIBE.KYNO_COOKWARE_BIG_POT = "大意味着更多，这意味着额外的时间。"
WANDA.DESCRIBE.KYNO_COOKWARE_BIG = "大意味着更多，这意味着额外的时间。"
WANDA.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "用于轻松烹饪食物。"
WANDA.DESCRIBE.KYNO_COOKWARE_SMALL = "轻松烹饪食物。"
WANDA.DESCRIBE.KYNO_COOKWARE_GRILL = "是时候做一些好的烤食物了。"
WANDA.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "我应该把这个放在哪里？"
WANDA.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "是时候做一些好的烤食物了。"
WANDA.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "我应该把这个放在哪里？"
WANDA.DESCRIBE.KYNO_COOKWARE_ELDER = "现在我只需要找一些树液放在这里。"
WANDA.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "乡村烤箱，哇。"
WANDA.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "进入烤箱。"
WANDA.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "用来放进烤箱的。"
WANDA.DESCRIBE.KYNO_COOKWARE_OVEN = "一个普通的旧烤箱。"
WANDA.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "一个普通的旧烤箱。"
WANDA.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "一个普通的旧烤箱。"

WANDA.DESCRIBE.KYNO_ROCKFLIPPABLE =
{
	GENERIC = "猜猜，下面有东西。",
	FLIPPED = "时间揭示一切。",
}

WANDA.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "让我们打开那个箱子。"

WANDA.DESCRIBE.KYNO_SUGARFLY = "不要去改变时间线！"
WANDA.DESCRIBE.KYNO_SUGARFLYWINGS = "小心那些！"

WANDA.DESCRIBE.KYNO_WATERY_CRATE = "让我们打开那个箱子。"

WANDA.DESCRIBE.KYNO_TUNACAN = "如果没有开罐器，打开它需要一些时间。"
WANDA.DESCRIBE.KYNO_TUNACAN_OPEN = "花费的时间比我预期的要少。"

WANDA.DESCRIBE.KYNO_CANNEDFOOD = "如果没有开罐器，打开它需要一些时间。"
WANDA.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "花费的时间比我预期的要少。"

WANDA.DESCRIBE.KYNO_POP = "啊，令人耳目一新……"

WANDA.DESCRIBE.KYNO_MYSTERYMEAT = "我不能。"

WANDA.DESCRIBE.KYNO_BOTTLE_SOUL = "我以前见过。不过不是这样的。"

WANDA.DESCRIBE.SOULSTEW = "我以前见过。不过不是这样的。"

WANDA.DESCRIBE.FORTUNECOOKIE = "又脆又甜。"

WANDA.DESCRIBE.HORNOCUPIA = "我突然觉得饿了......"

WANDA.DESCRIBE.CHEESE_YELLOW = "我确实喜欢它们，有点……"
WANDA.DESCRIBE.CHEESE_WHITE = "我确实喜欢它们，有点……"
WANDA.DESCRIBE.CHEESE_KOALEFANT = "我确实喜欢它们，有点……"

WANDA.DESCRIBE.MILK_BOX = "我真的很喜欢，有一点。"

WANDA.DESCRIBE.WATERCUP = "啊，令人耳目一新……"

WANDA.DESCRIBE.HONEYJAR = "甜蜜！"

WANDA.DESCRIBE.CRAB_ARTICHOKE = "花了一些时间，但值得。"

WANDA.DESCRIBE.PEPPERROLLS = "他们制作时间太长了......但他们很好吃！"

WANDA.DESCRIBE.KYNO_SAPHEALER = "这将及时修复树木。"

WANDA.DESCRIBE.KYNO_OCEAN_WRECK =
{
	GENERIC = "他们没有足够的时间逃脱。",
	PICKED = "时间会在这里修复一些东西。",
	BURNING = "那个结果现在确定了。",
}

WANDA.DESCRIBE.KYNO_GHOST_PIRATE = "真棒。简直棒极了。"

WANDA.DESCRIBE.KYNO_BUCKET_EMPTY = "太好了！"
WANDA.DESCRIBE.KYNO_BUCKET_METAL = "一个有用的工具。"
WANDA.DESCRIBE.KYNO_BUCKET_WATER = "挺方便的，只要别在不该洒的时候洒出来就行。"

WANDA.DESCRIBE.KYNO_MILK_BEEFALO = "味道很好。"
WANDA.DESCRIBE.KYNO_MILK_KOALEFANT = "味道很好。"

WANDA.DESCRIBE.KYNO_CAP_DRIED = "干燥食物需要相当长的时间。"

WANDA.DESCRIBE.KYNO_PLANTMEAT_DRIED = "一块又老又硬的肉。"

WANDA.DESCRIBE.KYNO_BREWBOOK = "酿造太费时间了，看看这些原料和方法！"

WANDA.DESCRIBE.KYNO_WOODENKEG =
{
	EMPTY = "这肯定需要很长时间才能生产出来。",
	BREWING_LONG = "这条时间线需要耐心。",
	BREWING_SHORT = "差不多了。",
	DONE = "准时。",
	BURNT = "来不及改变了。",
}

WANDA.DESCRIBE.KYNO_PRESERVESJAR =
{
	EMPTY = "这肯定需要很长时间才能生产出来。",
	BREWING_LONG = "这条时间线需要耐心。",
	BREWING_SHORT = "差不多了。",
	DONE = "完全按计划进行。",
	BURNT = "没有第二次机会。",
}

WANDA.DESCRIBE.KYNO_ANTCHEST =
{
	GENERIC = "感觉时间在里面都冻结了。",
	HONEY = "准时。",
	NECTAR = "仍在过程中。",
	BURNING = "现在来不及阻止了。",
}

WANDA.DESCRIBE.KYNO_NECTAR_POD = "需要一个地方和时间来成为蜂蜜。"

WANDA.DESCRIBE.KYNO_OAKTREE_POD = "需要时间长大。"
WANDA.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "烤得恰到好处！"

WANDA.DESCRIBE.KYNO_PIKO = "你是个可爱的小家伙。"
WANDA.DESCRIBE.KYNO_PIKO_ORANGE = "你的时间不多了，因为我正在和你泡茶！"

WANDA.DESCRIBE.KYNO_MEADOWISLAND_TREE =
{
	GENERIC = "只是一棵树。",
	CHOPPED = "它的目的已经过去了。",
	BURNING = "这不是不可避免的。",
	BURNT = "现在太晚了。",
}

WANDA.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE =
{
	GENERIC = "只是一棵茶树，上面有松鼠。",
	BURNING = "这不一定非要发生。",
}

WANDA.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "它只是一个木箱。"

WANDA.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT =
{
	GENERIC = "我没时间跟他们浪费。",
	BURNT = "来不及救它了。",
}

WANDA.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT =
{
	GENERIC = "也许有一天我应该学学怎么钓鱼。",
	CRAFTED = "显著的改进。",
	BURNT = "有些事情拖得太久了。",
}

WANDA.DESCRIBE.KYNO_MEADOWISLAND_SHOP =
{
	GENERIC = "我看得出来，其中一些物品并非来自这个位面。",
	OCCUPIED = "现在不是做那事的时候。",
}

WANDA.DESCRIBE.KYNO_MEADOWISLAND_MERMCART =
{
	GENERIC = "他在卖一堆杂七杂八的东西。",
	EMPTY = "这次什么也没剩下。",
}

WANDA.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "请告诉我，我们以前见过吗？"
WANDA.DESCRIBE.KYNO_MEADOWISLAND_POND = "我如果有空的话，可以从这个池塘里抓些鱼来。"
WANDA.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "植物。"
WANDA.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "我很好奇里面藏着什么……"
WANDA.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "他是个浪费时间的职业人士。"

WANDA.DESCRIBE.KYNO_SAMMYHAT = "我想他不会错过的。"

WANDA.DESCRIBE.KINGFISHER = "你是个很棒的捕手，对吧？"

WANDA.DESCRIBE.TOUCAN = "一种热带鸟类。"
WANDA.DESCRIBE.TOUCAN_CHUBBY = "你吃得太多了！"

WANDA.DESCRIBE.WETGOOP2 = "我从来没有声称自己擅长烹饪！"

WANDA.DESCRIBE.BEER = "不要喝太多。"

WANDA.DESCRIBE.PALEALE = "不要喝太多。"

WANDA.DESCRIBE.TEAGREEN = "有时间喝杯茶了..."

WANDA.DESCRIBE.TEARED = "有时间喝杯茶了..."

WANDA.DESCRIBE.MEAD = "不应该喝太多。"

WANDA.DESCRIBE.KYNO_JELLY = "一个罐子，这正是它所需要的！"

WANDA.DESCRIBE.KYNO_MAYONNAISE = "奶油味。"

WANDA.DESCRIBE.TARTARSAUCE = "只是一些塔塔酱，这里没什么可看的。"

WANDA.DESCRIBE.KYNO_PICKLES = "只是一些蔬菜泡菜。"

WANDA.DESCRIBE.KYNO_WINE = "我已经有一段时间没有喝过酒了。"

WANDA.DESCRIBE.KYNO_JUICE = "我更喜欢更甜的果汁。"

WANDA.DESCRIBE.KYNO_POISON_FROGLEGS = "吃掉我宝贵的时间。"
WANDA.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "我不认为这些已经无毒了。"

WANDA.DESCRIBE.POISONFROGGLEBUNWICH = "有人告诉我这是当地的美食。"

WANDA.DESCRIBE.KYNO_BREWINGRECIPECARD = "这里写的一切都已失传。"

WANDA.DESCRIBE.KYNO_OIL = "现在我只需要用它来做饭。"

WANDA.DESCRIBE.BERRYSUNDAE = "好吧，也许只有一两碗。"

WANDA.DESCRIBE.CHOCOLATE_BLACK = "好吧，也许只是一两口。"
WANDA.DESCRIBE.CHOCOLATE_WHITE = "好吧，也许只是一两口。"

WANDA.DESCRIBE.TRICOLORDANGO = "哇，他们真的很棒！"

WANDA.DESCRIBE.FRIESFRENCH = "我必须承认，它们非常好。"

WANDA.DESCRIBE.PIRATERUM = "一小口就能要了我的命。"

WANDA.DESCRIBE.TWISTEDTEQUILA = "很好，更多的是具有奇怪力量的普通饮料。"

WANDA.DESCRIBE.ONIONRINGS = "我不确定，但让我们尝试一下。"

WANDA.DESCRIBE.DONUTS = "啊啊！我昨天梦见了你！"
WANDA.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "啊啊！我昨天梦见了你！"
WANDA.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "啊啊！我昨天梦见了你！"

WANDA.DESCRIBE.CINNAMONROLL = "我非常想吃它。"

WANDA.DESCRIBE.GUMMYBEARGERS = "我喜欢小熊软糖！"

WANDA.DESCRIBE.PRETZEL = "这将是我第一次吃。"

WANDA.DESCRIBE.CORNINCUP = "这是一道美味的小吃。"

WANDA.DESCRIBE.COTTONCANDY = "我可以抵抗它！"

WANDA.DESCRIBE.ROASTEDHAZELNUTS = "这不是我最喜欢的食物。"

WANDA.DESCRIBE.MONSTERMUFFIN = "我知道这有问题，但我无法抗拒！"

WANDA.DESCRIBE.PINKCAKE = "这就是我的梦想！"

WANDA.DESCRIBE.CHIPSBAG = "吃点零食的时间到了。"

WANDA.DESCRIBE.LITTLEBREAD = "终于有了面包！"

WANDA.DESCRIBE.HOTHOUND = "其中之一不会造成伤害。"

WANDA.DESCRIBE.MILKSHAKE = "太棒了，太棒了！"
WANDA.DESCRIBE.MILKSHAKE_PRISMATIC = "太棒了，太棒了！"

WANDA.DESCRIBE.NACHOS = "我的手指现在很脏，是时候清理一下了。"

WANDA.DESCRIBE.BANANA_PUDDING = "味道不错。"

WANDA.DESCRIBE.SEA_PUDDING = "这不是我的强项，但也无所谓。"

WANDA.DESCRIBE.TOM_KHA_SOUP = "这……这是今天的午餐？真的吗？"

WANDA.DESCRIBE.MINERTREAT = "我无法抗拒！"

WANDA.DESCRIBE.RADISHSALAD = "萝卜沙拉。"

WANDA.DESCRIBE.PUMPKIN_SOUP = "汤。"

WANDA.DESCRIBE.ALGAE_SOUP = "汤。"

WANDA.DESCRIBE.PARZNIP_SOUP = "汤。"

WANDA.DESCRIBE.NETTLEMEATED = "虽然不甜，但我想也可以。"

WANDA.DESCRIBE.KYNO_SUGAR = "一点点东西来满足我对甜食的喜爱。"

WANDA.DESCRIBE.KYNO_BOTTLECAP = "普通瓶盖。"

WANDA.DESCRIBE.NUKACOLA = "我不怕奇怪的饮料！"
WANDA.DESCRIBE.NUKACOLA_QUANTUM = "我不怕奇怪的饮料！"

WANDA.DESCRIBE.LIVINGSANDWICH = "我应该避免这种情况。"

WANDA.DESCRIBE.DURIANSPLIT = "好吧，也许只是一两碗。"

WANDA.DESCRIBE.DURIANSOUP = "我喜欢这个。"

WANDA.DESCRIBE.DURIANMEATED = "我永远不会忘记那样的气味！"

WANDA.DESCRIBE.DURIANCHICKEN = "哦，这是新的。"

WANDA.DESCRIBE.LUNARSOUP = "我猜是一顿健康的月亮餐。"

WANDA.DESCRIBE.PURPLEWOBSTERSOUP = "我更喜欢甜食。"

WANDA.DESCRIBE.WOBSTERMONSTER = "就是这样。"

WANDA.DESCRIBE.SPIDERCAKE = "不是我喜欢的蛋糕。"

WANDA.DESCRIBE.SUGARBOMBS = "这就是一顿正式的早餐了。"

WANDA.DESCRIBE.BERRYBOMBS = "一个罐子！我忘了！"

WANDA.DESCRIBE.ONIGIRIS = "随时随地都能吃。"

WANDA.DESCRIBE.OMURICE = "我还挺自豪的。"

WANDA.DESCRIBE.PAELLA = "不能再浪费时间了，该吃饭了。"

WANDA.DESCRIBE.RISOTTO = "没时间了。"

WANDA.DESCRIBE.RICESAKE = "不是我喜欢的类型。"

WANDA.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "我明白了。到处都是刺。"

WANDA.DESCRIBE.KYNO_PINEAPPLEBUSH =
{
	GENERIC = "我明白了。到处都是刺。",
	PICKED = "它会及时回来的。",
	WITHERED = "这个时机不对。",
	BURNING = "它的时间线在此终结。",
}

WANDA.DESCRIBE.KYNO_PINEAPPLE = "我不能浪费时间去打开它。"
WANDA.DESCRIBE.KYNO_PINEAPPLE_HALVED = "客气。"
WANDA.DESCRIBE.KYNO_PINEAPPLE_COOKED = "美味可口。"

WANDA.DESCRIBE.PIZZA_TROPICAL = "我有疑问。"

WANDA.DESCRIBE.PINACOLADA = "啊，我正需要这个。"

WANDA.DESCRIBE.CHIMAS = "这不是我期待的茶话会！"

WANDA.DESCRIBE.KYNO_GARDEN_SPRINKLER =
{
	OFF = "它给我的植物浇水，节省我一些时间。",
	ON = "运行得完全符合预期。",
}

WANDA.DESCRIBE.KYNO_FOODSACK = "冷却食品的实用容器。"

WANDA.DESCRIBE.GUMMYWORMS = "这里终于有好吃的糖果了！"

WANDA.DESCRIBE.SMORES = "简单又美味的点心。"

WANDA.DESCRIBE.NUKASHINE = "沃托克斯能按照自己的意愿弯曲时间和空间，并得到这些东西，这真是太奇怪了。"

WANDA.DESCRIBE.ANTSLOG = "这不是我所期待的。"

WANDA.DESCRIBE.KYNO_WORM_BONE = "虫子的骨骼残骸。"

WANDA.DESCRIBE.SPOOKY_BRAIN_NOODLES = "呸。"
WANDA.DESCRIBE.SPOOKY_BURGERZILLA = "我能感觉到食物中散发出一股小小的邪恶气息。"
WANDA.DESCRIBE.SPOOKY_DEADBREAD = "我不怕食物。"
WANDA.DESCRIBE.SPOOKY_JELLYBEANS = "眼球糖果！"
WANDA.DESCRIBE.SPOOKY_POPSICLE = "不是很甜。"
WANDA.DESCRIBE.SPOOKY_PUMPKINCREAM = "哦，天哪。"
WANDA.DESCRIBE.SPOOKY_SKULLCANDY = "我不怕糖果。"
WANDA.DESCRIBE.SPOOKY_TACODILE = "一个塔科迪雷！哇哈！"

WANDA.DESCRIBE.BUTTER_BEEFALO = "不是蝴蝶吗？够奇怪的了。"
WANDA.DESCRIBE.BUTTER_GOAT = "这最好像普通的一样好。"
WANDA.DESCRIBE.BUTTER_KOALEFANT = "考拉象黄油，我还需要期待什么？"

WANDA.DESCRIBE.SPICE_CURE = "这可能对快速腐烂的糖果有好处。"
WANDA.DESCRIBE.SPICE_COLD = "如果我们早点有这个，夏天会更容易。"
WANDA.DESCRIBE.SPICE_FIRE = "我能感觉到这东西里的夏日阳光。"
WANDA.DESCRIBE.SPICE_FED = "让我饿了。"
WANDA.DESCRIBE.SPICE_MIND = "舒缓心灵。"

WANDA.DESCRIBE.SUGARFLYMUFFIN = "它有一种微妙的味道，轻盈而稍纵即逝。"

WANDA.DESCRIBE.EELTACOS = "我要去吃玉米卷！"

WANDA.DESCRIBE.MEATSKILLET = "像一团火焰。"

WANDA.DESCRIBE.MEATWALTZ = "今天有灵感吗？"

WANDA.DESCRIBE.COMPLETEBREAKFAST = "我想，这正是关键所在。"

WANDA.DESCRIBE.DUMPLINGS = "下次可以用奶酪"

WANDA.DESCRIBE.WARLYICEDTEA = "清爽。"

WANDA.DESCRIBE.WARLYTEA = "一杯传统的茶。"

WANDA.DESCRIBE.KYNO_TEALEAF = "我迫不及待地想把它变成茶杯。"

WANDA.DESCRIBE.KYNO_ITEMSLICER = "用于切割最坚硬的肉块。"
WANDA.DESCRIBE.KYNO_ITEMSLICER_GOLD = "用于切割最坚硬的肉块。"

WANDA.DESCRIBE.COXINHA = "里面的油对我来说太多了。"

WANDA.DESCRIBE.LAZYDESSERT = "我想糖果就是糖果。"

WANDA.DESCRIBE.CRABKINGFEAST = "真是一个螃蟹盛宴！"

WANDA.DESCRIBE.PIENAPPLE = "我们就把叶子当装饰，不用摘掉，我没有时间。"

WANDA.DESCRIBE.JAWSBREAKER = "这颗糖果对我来说太大了。"

WANDA.DESCRIBE.AVOCADOTOAST = "令人满意。"

WANDA.DESCRIBE.RICEPUDDING = "我想牛奶确实让它更好了一些。"

WANDA.DESCRIBE.SHARKSUSHI = "完美。"

WANDA.DESCRIBE.WOBSTERBREADED = "我告诉过你，开水要来了。"

WANDA.DESCRIBE.LAZYPURRITO = "嗯。味道很好。"

WANDA.DESCRIBE.HORCHATA = "温和的。"

WANDA.DESCRIBE.WOBSTERCOCKTAIL = "漂亮。"

WANDA.DESCRIBE.LAVAEEGGBOILED = "这个最好不错。"

WANDA.DESCRIBE.POMEGRANATETEA = "清爽。"

WANDA.DESCRIBE.TIRAMISU = "啊！一道美味的甜点。"

WANDA.DESCRIBE.TOADSTOOLCOLA = "清新但有些奇怪。"

WANDA.DESCRIBE.TEPACHE = "菠萝含糖量过高！"

WANDA.DESCRIBE.LUNARTEQUILA = "有趣..."

WANDA.DESCRIBE.MIMICMOSA = "抱歉，我得走了！"

WANDA.DESCRIBE.POMEGRANATEPIE = "红如鲜血。"

WANDA.DESCRIBE.PINEAPPLECAKE = "我迫不及待想吃它。"

WANDA.DESCRIBE.PASTY_MEAT = "零食时间！"
WANDA.DESCRIBE.PASTY_CHEESE = "零食时间！"

WANDA.DESCRIBE.BRIGADEIRO = "给我更多的糖果！"

WANDA.DESCRIBE.REGULARLASAGNA = "令人垂涎。"

WANDA.DESCRIBE.FLTSANDWICH = "用青蛙带我飞向月球。"

WANDA.DESCRIBE.RICEANDBEANS = "我明白，这很健康，但还是喜欢吃点甜食！"

WANDA.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "时间会告诉我们……我猜2026年它会大声说话。"

WANDA.DESCRIBE.KYNO_TRUFFLES_GROUND =
{
	GENERIC = "时光流逝，它们自己生长。令人印象深刻。",
	PICKED = "我得等下次机会了。",
	BURNING = "那个机会永远消失了。",
}

WANDA.DESCRIBE.KYNO_TRUFFLES = "好东西总是需要等待……就像这些。"
WANDA.DESCRIBE.KYNO_TRUFFLES_COOKED = "值得等待的美味。"

WANDA.DESCRIBE.KYNO_ITEMSHOWCASER =
{
	EMPTY = "一个空虚的时刻。",
	FULL = "提醒人们，即使是美丽也会随着时间而褪色。",
}

WANDA.DESCRIBE.KYNO_SPORECAP = "时间对它可不友好。"
WANDA.DESCRIBE.KYNO_SPORECAP_COOKED = "被时间和火焰共同烘烤。"

WANDA.DESCRIBE.KYNO_SPORECAP_DARK = "有毒而又永恒的邪恶。"
WANDA.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "真希望我能回到闻之前的那一刻。"

WANDA.DESCRIBE.KYNO_GOLDENAPPLE = "得克制住自己……别现在吃掉它！"

WANDA.DESCRIBE.TRUFFLESGRINDER = "永不过时的味道。"

WANDA.DESCRIBE.SPORECAPPIE = "就算时间也救不了我免于这种毒。"

WANDA.DESCRIBE.SPORECAP_SKEWERS = "制作快，吃得更快。时间花得值！"

WANDA.DESCRIBE.TRUFFLEOIL = "永恒的美味……如果你能忍受那味道的话。"

WANDA.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "再多捣点乱有什么关系？"
WANDA.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "很快就会完成……我能感觉到。"

WANDA.DESCRIBE.KYNO_FISHFARMPLOT =
{
	GENERIC = "鱼类未来开始的地方。",
	FUEL_HIGH = "暂时还不需要干预。",
	FUEL_MED = "时间在它们这边。",
	FUEL_LOW = "平衡正在消失。",
	EMPTY = "空的，正如所料。",
}

WANDA.DESCRIBE.KYNO_ANTCHOVY = "我哪有时间给鱼虫杂交体分类！"
WANDA.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "另一件怪事，我没时间研究。"

WANDA.DESCRIBE.AGEDROE = "这是我第一次见到这个。"
WANDA.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "恰到好处的陈年滋味……是我时间的绝佳回报。"

WANDA.DESCRIBE.KYNO_SWORDFISH_BLUE = "长时间呆在一个地方，谁都会这样……或者说，任何鱼都会这样。"

WANDA.DESCRIBE.KYNO_JELLYFISH = "它的时日不多了。"
WANDA.DESCRIBE.KYNO_JELLYFISH_DEAD = "我早就告诉过你。"
WANDA.DESCRIBE.KYNO_JELLYFISH_COOKED = "我更喜欢这样。"
WANDA.DESCRIBE.KYNO_JELLYFISH_DRIED = "有点嚼劲。"

WANDA.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "软糯又缤纷。"
WANDA.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "时间到了！"
WANDA.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "希望味道不错。"

WANDA.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "我不知道能不能用这个做一只玻璃手表。"

WANDA.DESCRIBE.KYNO_OCEANTRAP = "海洋生物的牢笼。"

WANDA.DESCRIBE.OCEANFISH_PUFFERFISH = "是时候消消气了，刺头。"
WANDA.DESCRIBE.OCEANFISH_STURGEON = "一条历经沧桑的鱼……我深有同感。"

WANDA.DESCRIBE.KYNO_SWORDFISH = "一位在水中纵横驰骋的侠客。"
WANDA.DESCRIBE.KYNO_SWORDFISH_DEAD = "你的时间到了，剑脸。"

WANDA.DESCRIBE.SWORDFISHFEAST = "一款永恒的食谱——鲜香醇厚。"

WANDA.DESCRIBE.KYNO_DOGFISH = "快逃命吧，鱼！"
WANDA.DESCRIBE.KYNO_DOGFISH_DEAD = "看来你的游泳生涯到此为止了。"

WANDA.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "它已过了黄金时段。"

WANDA.DESCRIBE.WOBSTER_MONKEYISLAND = "金色的龙虾？时间真是会造就奇妙的事物啊……"
WANDA.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "它的时日已尽，正如万物皆如此。"
WANDA.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "我平时没时间这样做饭……但值得。"

WANDA.DESCRIBE.KYNO_PUFFERMONSTER = "我可不想把时间浪费在那只带刺的气球上。"

WANDA.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "冒险正等待着你。"
WANDA.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "是时候让你长眠了！"
WANDA.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "传说中的野兽。"
WANDA.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "看起来像一枚定时炸弹，随时可能引爆。"

WANDA.DESCRIBE.KYNO_BLUBBER = "唉，正合我意。"

WANDA.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "为前路补充能量。"
WANDA.DESCRIBE.KYNO_FISHMEAT_DRIED = "方便又持久。正合我意。"

WANDA.DESCRIBE.MONKEYISLANDMEAL = "时间能治愈一切……或许，是这顿饭的功劳。"

WANDA.DESCRIBE.KYNO_BRAINROCK_LARVAE = "我没时间带孩子。"
WANDA.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "看孩子不是我最喜欢的消遣方式。"
WANDA.DESCRIBE.KYNO_BRAINROCK_CORAL = "少花时间思考，多花时间行动。"

WANDA.DESCRIBE.KYNO_BRAINROCK_ROCK =
{
	GENERIC = "你肯定有很多时间思考，对吧？",
	PICKED = "它的思绪暂停了。",
}

WANDA.DESCRIBE.BRAINMETTERSOUP = "将思考所需的时间缩短一半。"

WANDA.DESCRIBE.KYNO_OCTOPUSKING_OCEAN =
{
	GENERIC = "我们交易吧。我没有空闲时间可以浪费。",
	SLEEPING = "这个时机不对。",
}

WANDA.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "这奖励值得我花时间！"

WANDA.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE =
{
	GENERIC = "我希望这值得我花时间。",
	WAITING = "他的时间用完了。",
}

WANDA.DESCRIBE.KYNO_PACKIMBAGGIMS = "你挺可爱的。真的！"

WANDA.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "我打算花相当长的时间来处理这件事。"
WANDA.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "哎哟。烘焙真的要花时间。"
WANDA.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "又一次提醒，岁月流逝已太久！"
WANDA.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "更多蜡烛。更多时间压力。"
WANDA.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "我不确定我是否相信那些东西。"
WANDA.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "吃一块应该不会浪费太多时间……希望如此。"
WANDA.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "庆祝活动固然美好，但前提是时间允许……"

WANDA.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE =
{
	GENERIC = "及时的爆米花服务。",
	FUEL_HIGH = "暂时还不需要干预。",
	FUEL_MED = "时间正在流逝。",
	FUEL_LOW = "时间快到了。",
	EMPTY = "它的时刻已经过去。",
}

WANDA.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "最好趁新鲜时享用...就像时间本身一样。"
WANDA.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "嗯……我想，连时间旅行者也能庆祝吧。"
WANDA.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "时光眷顾那些独具风格之人，比如萨米。"

WANDA.DESCRIBE.KYNO_FISHREGISTRYHAT = "至少它能帮我记住已经学过的东西。"

WANDA.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "一个食物慢慢消失的地方。",
	FUEL_HIGH = "暂时不用担心。",
	FUEL_MED = "时间很快就会把它清空。",
	FUEL_LOW = "时间快到了……饲料也是。",
	EMPTY = "正如所料。",
	BURNT = "那个结果是不可避免的。",
}

WANDA.DESCRIBE.CHICKENNUGGETS = "我没时间吃这个。"

WANDA.DESCRIBE.CHICKENWINGS = "现在烫嘴，事后后悔。"

WANDA.DESCRIBE.CHICKENBURGER = "吃得快。不浪费时间。"

WANDA.DESCRIBE.CHICKENEGGSOUP = "舒心又高效。"

WANDA.DESCRIBE.CHICKENEGGSTEW = "做得慢。吃得快。"

WANDA.DESCRIBE.CHICKENROTISSERIE = "至少等待是值得的。"