local WORMWOOD = STRINGS.CHARACTERS.WORMWOOD

WORMWOOD.ANNOUNCE_KYNO_COFFEEBUFF_START = "爆开了！!"
WORMWOOD.ANNOUNCE_KYNO_COFFEEBUFF_END = "超速？"

WORMWOOD.ANNOUNCE_KYNO_HASTEBUFF_START = "速度!"
WORMWOOD.ANNOUNCE_KYNO_HASTEBUFF_END = "速度去哪儿了？"

WORMWOOD.ANNOUNCE_KYNO_POPBUFF_START = "(嗝)"
WORMWOOD.ANNOUNCE_KYNO_POPBUFF_END = "泡泡出来了？"

WORMWOOD.ANNOUNCE_KYNO_FROGBUFF_START = "青蛙！"
WORMWOOD.ANNOUNCE_KYNO_FROGBUFF_END = "没有青蛙？"

WORMWOOD.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝)"
WORMWOOD.ANNOUNCE_KYNO_PIRATEBUFF_END = "泡泡浴结束了？"

WORMWOOD.ANNOUNCE_KYNO_FREEZEBUFF_START = "哦"
WORMWOOD.ANNOUNCE_KYNO_FREEZEBUFF_END = "霜冻消失了"

WORMWOOD.ANNOUNCE_KYNO_FIREBUFF_START = "热！"
WORMWOOD.ANNOUNCE_KYNO_FIREBUFF_END = "火焰消失了"

WORMWOOD.ANNOUNCE_KYNO_FISHINGBUFF_START = "钓鱼时间！"
WORMWOOD.ANNOUNCE_KYNO_FISHINGBUFF_END = "鱼？"

WORMWOOD.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "令人放松的！"
WORMWOOD.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "放松消失了"

WORMWOOD.ANNOUNCE_KYNO_EATERBUFF_START = "我的胃现在感觉很好。"
WORMWOOD.ANNOUNCE_KYNO_EATERBUFF_END = "肚子正常了？"

WORMWOOD.ANNOUNCE_KYNO_WORMBUFF_START = "耶!"
WORMWOOD.ANNOUNCE_KYNO_WORMBUFF_END = "停止?"

WORMWOOD.ANNOUNCE_KYNO_CRABBUFF_START = "耶！"
WORMWOOD.ANNOUNCE_KYNO_CRABBUFF_END = "停止?"

WORMWOOD.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝)"
WORMWOOD.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "泡泡消失了？"

WORMWOOD.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "感觉奇怪"
WORMWOOD.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "感觉更好"

WORMWOOD.ANNOUNCE_KYNO_STEALTHBUFF_START = "安静点"
WORMWOOD.ANNOUNCE_KYNO_STEALTHBUFF_END = "不再偷偷摸摸？"

WORMWOOD.ANNOUNCE_KYNO_FEARBUFF_START = "感觉...很冷静"
WORMWOOD.ANNOUNCE_KYNO_FEARBUFF_END = "现在柑橘不好..."

WORMWOOD.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "好痒痒！好有趣！"
WORMWOOD.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "没有闪亮的力量了……"

WORMWOOD.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "交猪朋友"
WORMWOOD.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "小猪消失了"

WORMWOOD.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "雨不疼了！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WORMWOOD.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "没生病！感觉好！"
WORMWOOD.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "又不舒服了。"

WORMWOOD.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "大脑，放手一搏"
WORMWOOD.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "现在脑子累了"

WORMWOOD.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "嗡嗡朋友！耶！"
WORMWOOD.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "嗡嗡生气了！"

WORMWOOD.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "感觉真好！太棒了！"
WORMWOOD.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "再无硬骨头..."

WORMWOOD.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "肚子变大了！"
WORMWOOD.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "肚子又变小了……"

WORMWOOD.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "脑袋感觉真好！"
WORMWOOD.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "头又晕了……"

WORMWOOD.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "硬！安全！"
WORMWOOD.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "再次柔软"

WORMWOOD.ANNOUNCE_KYNO_BERSERKERBUFF_START = "Hit Harder! Get Hurt More!"
WORMWOOD.ANNOUNCE_KYNO_BERSERKERBUFF_END = "No More Big Hurting"

WORMWOOD.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "Not Hungry Fast"
WORMWOOD.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "Hungry Again"

WORMWOOD.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "不"

WORMWOOD.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "想要洛基咕噜咕噜"

WORMWOOD.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "朋友太小了？"

WORMWOOD.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "不要？"

WORMWOOD.ANNOUNCE_KYNO_POTHANGER_FAIL = "想要别的"

WORMWOOD.ANNOUNCE_KYNO_CASSEROLE_FAIL = "不要这个？"

WORMWOOD.ANNOUNCE_KYNO_SAPHEALER_USED = "Juice Helps Friend!"

WORMWOOD.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "哦……别再动啦……."

WORMWOOD.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "全都没了。"

WORMWOOD.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "泡泡消失了？"
WORMWOOD.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "水落下……气泡消失"
WORMWOOD.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "巨物在水中游动……有危险吗？"

WORMWOOD.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "大糖完成！"

WORMWOOD.ANNOUNCE_KYNO_FISH_RESEARCHED = "咕噜咕噜告诉我事情了！"
WORMWOOD.ANNOUNCE_KYNO_ROE_RESEARCHED = "现在知道小咕噜咕噜了"

WORMWOOD.DESCRIBE.KYNO_ROE = "宝宝咕噜咕噜"
WORMWOOD.DESCRIBE.KYNO_ROE_COOKED = "整齐的行。"

WORMWOOD.DESCRIBE.KYNO_SHARK_FIN = "水切片机"

WORMWOOD.DESCRIBE.KYNO_BEANBUGS = "跳跃者"
WORMWOOD.DESCRIBE.KYNO_BEANBUGS_COOKED = "为什么不跳？"

WORMWOOD.DESCRIBE.KYNO_GUMMYBUG = "粘液"
WORMWOOD.DESCRIBE.KYNO_GUMMYBUG_COOKED = "你好，小棒！"

WORMWOOD.DESCRIBE.KYNO_WHEAT = "哦！漂亮的种子！"
WORMWOOD.DESCRIBE.KYNO_WHEAT_COOKED = "哦！漂亮的种子！"

WORMWOOD.DESCRIBE.KYNO_FLOUR = "地面材料"

WORMWOOD.DESCRIBE.KYNO_SPOTSPICE = "让肚皮变好"

WORMWOOD.DESCRIBE.KYNO_SAP = "这些都是来自朋友的内部"
WORMWOOD.DESCRIBE.KYNO_SAP_SPOILED = "不不不！"

WORMWOOD.DESCRIBE.KYNO_SYRUP = "做甜的东西"

WORMWOOD.DESCRIBE.KYNO_COFFEEBEANS = "太棒了！"
WORMWOOD.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "闻起来很香"

WORMWOOD.DESCRIBE.DUG_KYNO_COFFEEBUSH = "Zoomberry Friend Needs Dirt"

WORMWOOD.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "Zoomberry friend",
	PICKED = "Empty",
	WITHERED = "Friend Needs Help",
}

WORMWOOD.DESCRIBE.DUG_KYNO_SPOTBUSH = "Hello Friend"

WORMWOOD.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "Friend Has Purple Hair",
	PICKED = "Where Did Friend Hair Go?",
	BURNING = "Friend Hurt!",
}

WORMWOOD.DESCRIBE.KYNO_SPOTSPICE_LEAF = "小枝"

WORMWOOD.DESCRIBE.KYNO_MUSSEL = "里面的肉藏起来了"
WORMWOOD.DESCRIBE.KYNO_MUSSEL_COOKED = "肚皮"

WORMWOOD.DESCRIBE.KYNO_HUMANMEAT = "肚腩"
WORMWOOD.DESCRIBE.KYNO_HUMANMEAT_COOKED = "嗯……"
WORMWOOD.DESCRIBE.KYNO_HUMANMEAT_DRIED = "耐嚼"

WORMWOOD.DESCRIBE.COFFEE = "哇！！！"

WORMWOOD.DESCRIBE.BISQUE = "美味的小吃。"

WORMWOOD.DESCRIBE.JELLYOPOP = "冷饮"

WORMWOOD.DESCRIBE.SHARKFINSOUP = "还在游泳"

WORMWOOD.DESCRIBE.TROPICALBOUILLABAISSE = "咕噜咕噜？"

WORMWOOD.DESCRIBE.MUSSELBOUILLABAISE = "对腹部有好处"

WORMWOOD.DESCRIBE.SWEETPOTATOSOUFFLE = "肚子的东西"

WORMWOOD.DESCRIBE.FEIJOADA = "充满活力"

WORMWOOD.DESCRIBE.GUMMY_CAKE = "软软的"

WORMWOOD.DESCRIBE.HARDSHELL_TACOS = "脆脆的"

WORMWOOD.DESCRIBE.ICEDTEA = "冰凉的水"

WORMWOOD.DESCRIBE.NETTLELOSANGE = "嗯..."

WORMWOOD.DESCRIBE.SNAKEBONESOUP = "蠕动的水"

WORMWOOD.DESCRIBE.STEAMEDHAMSANDWICH = "汉堡！！！"

WORMWOOD.DESCRIBE.TEA = "温热的水"

WORMWOOD.DESCRIBE.BUBBLETEA = "冷水"

WORMWOOD.DESCRIBE.FRENCHONIONSOUP = "我喜欢汤。"

WORMWOOD.DESCRIBE.SLAW = "肚皮派对！"

WORMWOOD.DESCRIBE.LOTUSBOWL = "嗯……好吃。"

WORMWOOD.DESCRIBE.POI = "经典夏威夷大餐。"

WORMWOOD.DESCRIBE.JELLYBEAN_HUNGER = "嗯嗯！"
WORMWOOD.DESCRIBE.JELLYBEAN_SUPER = "嗯嗯！"
WORMWOOD.DESCRIBE.JELLYBEAN_SANITY = "嗯嗯！"

WORMWOOD.DESCRIBE.BOWLOFGEARS = "金属材料"

WORMWOOD.DESCRIBE.LONGPIGMEAL = "嗯...."

WORMWOOD.DESCRIBE.CUCUMBERSALAD = "想吃"

WORMWOOD.DESCRIBE.DUG_KYNO_WILDWHEAT = "Friend Needs Dirt"

WORMWOOD.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "Friend",
	PICKED = "Empty",
	WITHERED = "Friend Not Happy",
	BURNING = "Hurts!!",
}

WORMWOOD.DESCRIBE.KYNO_MEALGRINDER = "石头机器"

WORMWOOD.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "Friends! Party!",
	PICKED = "Oh. Friends Gone",
	BURNING = "Hurts!",
}

WORMWOOD.DESCRIBE.GORGE_BREAD = "蓬松的"
WORMWOOD.DESCRIBE.GORGE_SWEET_CHIPS = "土豆片"
WORMWOOD.DESCRIBE.GORGE_VEGETABLE_SOUP = "蔬菜！"
WORMWOOD.DESCRIBE.GORGE_JELLY_SANDWICH = "为了肚子"
WORMWOOD.DESCRIBE.GORGE_FISH_STEW = "鱼腥味"
WORMWOOD.DESCRIBE.GORGE_MEAT_STEW = "为了肚皮"
WORMWOOD.DESCRIBE.GORGE_ONION_CAKE = "蛋糕！"
WORMWOOD.DESCRIBE.GORGE_POTATO_PANCAKES = "土豆去哪儿了？"
WORMWOOD.DESCRIBE.GORGE_POTATO_SOUP = "在腹部畅游"
WORMWOOD.DESCRIBE.GORGE_FISHBALL_SKEWERS = "鱼腥味"
WORMWOOD.DESCRIBE.GORGE_MEAT_SKEWERS = "肉味"
WORMWOOD.DESCRIBE.GORGE_STONE_SOUP = "在腹部畅游"
WORMWOOD.DESCRIBE.GORGE_CROQUETTE = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_ROAST_VEGETABLES = "绿色肚皮"
WORMWOOD.DESCRIBE.GORGE_MEATLOAF = "肉乎乎的。"
WORMWOOD.DESCRIBE.GORGE_CARROT_SOUP = "在腹部畅游"
WORMWOOD.DESCRIBE.GORGE_FISHPIE = "卡住的鱼？"
WORMWOOD.DESCRIBE.GORGE_FISHCHIPS = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_MEATPIE = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_SLIDERS = "腹部的小东西"
WORMWOOD.DESCRIBE.GORGE_JELLY_ROLL = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_CARROT_CAKE = "蛋糕！"
WORMWOOD.DESCRIBE.GORGE_GARLICMASHED = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_GARLICBREAD = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_TOMATO_SOUP = "在腹部畅游"
WORMWOOD.DESCRIBE.GORGE_SAUSAGE = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_CANDIEDFISH = "甜蜜的肚皮"
WORMWOOD.DESCRIBE.GORGE_STUFFEDMUSHROOM = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_BRUSCHETTA = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_HAMBURGER = "汉堡"
WORMWOOD.DESCRIBE.GORGE_FISHBURGER = "汉堡"
WORMWOOD.DESCRIBE.GORGE_MUSHROOMBURGER = "汉堡"
WORMWOOD.DESCRIBE.GORGE_FISH_STEAK = "鱼腥味"
WORMWOOD.DESCRIBE.GORGE_CURRY = "温暖的腹部"
WORMWOOD.DESCRIBE.GORGE_SPAGHETTI = "肚皮球"
WORMWOOD.DESCRIBE.GORGE_POACHEDFISH = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_SHEPHERD_PIE = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_CANDY = "有嚼劲的"
WORMWOOD.DESCRIBE.GORGE_BREAD_PUDDING = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_BERRY_TART = "腹部甜甜的"
WORMWOOD.DESCRIBE.GORGE_MACARONI = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_BAGEL_AND_FISH = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_GRILLED_CHEESE = "腹部的黄色东西"
WORMWOOD.DESCRIBE.GORGE_CREAMMUSHROOM = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_MANICOTTI = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_CHEESEBURGER = "汉堡"
WORMWOOD.DESCRIBE.GORGE_FETTUCCINE = "腹部的白色东西"
WORMWOOD.DESCRIBE.GORGE_ONION_SOUP = "腹部的臭东西"
WORMWOOD.DESCRIBE.GORGE_BREADED_CUTLET = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_CREAMY_FISH = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_PIZZA = "嗯..."
WORMWOOD.DESCRIBE.GORGE_POT_ROAST = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_CRAB_CAKE = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_STEAK_FRITES = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_SHOOTER_SANDWICH = "开枪吗？"
WORMWOOD.DESCRIBE.GORGE_BACON_WRAPPED = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_CRAB_ROLL = "螃蟹？"
WORMWOOD.DESCRIBE.GORGE_MEAT_WELLINGTON = "腹部的东西"
WORMWOOD.DESCRIBE.GORGE_CRAB_RAVIOLI = "螃蟹?"
WORMWOOD.DESCRIBE.GORGE_CARAMEL_CUBE = "甜！"
WORMWOOD.DESCRIBE.GORGE_SCONE = "甜的"
WORMWOOD.DESCRIBE.GORGE_TRIFLE = "甜的"
WORMWOOD.DESCRIBE.GORGE_CHEESECAKE = "腹部的奶酪东西"

WORMWOOD.DESCRIBE.DUCKYOUGLERMZ = "好吃！"

WORMWOOD.DESCRIBE.KYNO_ALOE = "笨拙的朋友"
WORMWOOD.DESCRIBE.KYNO_ALOE_COOKED = "黏糊糊的"
WORMWOOD.DESCRIBE.KYNO_ALOE_GROUND = "笨拙的朋友"
WORMWOOD.DESCRIBE.KYNO_ALOE_SEEDS = "制作橙色腹部的东西"
WORMWOOD.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "制作橙色腹部的东西"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_ALOE = "笨拙的朋友"
WORMWOOD.DESCRIBE.KYNO_ALOE_OVERSIZED = "笨拙的朋友"
WORMWOOD.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "不——————！"

WORMWOOD.DESCRIBE.KYNO_CUCUMBER = "肚腩？"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_COOKED = "嗯嗯……黏糊糊的！"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_GROUND = "肚腩？"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_SEEDS = "制作橙色肚皮"
WORMWOOD.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "制作橙色腹部的东西"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "肚腩？"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "肚腩？"
WORMWOOD.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "肚腩？"

WORMWOOD.DESCRIBE.KYNO_RADISH = "肚皮红球"
WORMWOOD.DESCRIBE.KYNO_RADISH_COOKED = "绿色部分去哪儿了？"
WORMWOOD.DESCRIBE.KYNO_RADISH_GROUND = "腹部红球"
WORMWOOD.DESCRIBE.KYNO_RADISH_SEEDS = "制作橘子肚皮"
WORMWOOD.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "制作橘子肚皮"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_RADISH = "腹部红球"
WORMWOOD.DESCRIBE.KYNO_RADISH_OVERSIZED = "腹部红球"
WORMWOOD.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "不——————！"

WORMWOOD.DESCRIBE.KYNO_FENNEL = "你好！"
WORMWOOD.DESCRIBE.KYNO_FENNEL_COOKED = "咕噜咕噜"
WORMWOOD.DESCRIBE.KYNO_FENNEL_GROUND = "你好！"
WORMWOOD.DESCRIBE.KYNO_FENNEL_SEEDS = "制作橘子肚皮"
WORMWOOD.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "制作橘子肚皮"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "你好!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_OVERSIZED = "你好!"
WORMWOOD.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "不——————！"

WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO = "甜食"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "嗯嗯..."
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "甜美的肚皮"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "制作橙色肚皮"
WORMWOOD.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "制作橙色肚皮"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "腹部甜甜的"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "腹部甜甜的"
WORMWOOD.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "不——————！"

WORMWOOD.DESCRIBE.KYNO_PARZNIP = "谢谢，土！"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_COOKED = "谢谢，土！"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_EATEN = "谢谢，土！"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_GROUND = "谢谢，土！"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_BIG = "呜呜！"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_SEEDS = "制作橙色肚皮"
WORMWOOD.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "制作橙色肚皮"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "谢谢，土！"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "谢谢，土！"
WORMWOOD.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "不——————！"

WORMWOOD.DESCRIBE.KYNO_TURNIP = "可爱的小土朋友"
WORMWOOD.DESCRIBE.KYNO_TURNIP_COOKED = "做好吃的肚皮"
WORMWOOD.DESCRIBE.KYNO_TURNIP_GROUND = "可爱的小土朋友"
WORMWOOD.DESCRIBE.KYNO_TURNIP_SEEDS = "制作橙色肚皮"
WORMWOOD.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "制作橙色肚皮"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "可爱的小泥土朋友"
WORMWOOD.DESCRIBE.KYNO_TURNIP_OVERSIZED = "可爱的小土朋友"
WORMWOOD.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "不——————！"

WORMWOOD.DESCRIBE.KYNO_RICE = "小萌芽"
WORMWOOD.DESCRIBE.KYNO_RICE_COOKED = "小萌芽"
WORMWOOD.DESCRIBE.KYNO_RICE_SEEDS = "制作橘子肚皮"
WORMWOOD.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "制作橘子肚皮"
WORMWOOD.DESCRIBE.FARM_PLANT_KYNO_RICE = "可爱的邋遢小伙伴"
WORMWOOD.DESCRIBE.KYNO_RICE_OVERSIZED = "可爱的邋遢小伙伴"
WORMWOOD.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "不——————！"

WORMWOOD.DESCRIBE.KYNO_SEEDS_KIT = "里面有朋友吗？"

WORMWOOD.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "Rocks That Grows Stuff",
	PICKED = "Snails Gone",
	WITHERED = "No Life",
}

WORMWOOD.DESCRIBE.KYNO_LIMPETS = "攀岩"
WORMWOOD.DESCRIBE.KYNO_LIMPETS_COOKED = "进肚子"

WORMWOOD.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "Hello!",
	PICKED = "Resting",
	BURNING = "Hurts!",
}

WORMWOOD.DESCRIBE.KYNO_LOTUS_ROOT = "需要海洋"
WORMWOOD.DESCRIBE.KYNO_LOTUS_FLOWER = "肚子的东西！"
WORMWOOD.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "肚子很好"

WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "Yum",
	PICKED = "Gone For Now?",
	BURNING = "Hurts Bad!",
}

WORMWOOD.DESCRIBE.KYNO_SEAWEEDS = "好吃"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_COOKED = "海百胜球"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_DRIED = "海百胜不再有海"
WORMWOOD.DESCRIBE.KYNO_SEAWEEDS_ROOT = "需要海洋"

WORMWOOD.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "Hello Friend!",
	PICKED = "Friend Growing Well",
	BURNING = "Hurts!!",
}

WORMWOOD.DESCRIBE.KYNO_TAROROOT_ROOT = "需要海洋"
WORMWOOD.DESCRIBE.KYNO_TAROROOT = "嗯...紫色"
WORMWOOD.DESCRIBE.KYNO_TAROROOT_COOKED = "肚皮喜欢它"

WORMWOOD.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "Belly Stuff",
	PICKED = "Friend Is Sleeping",
	BURNING = "Fire!!!",
}

WORMWOOD.DESCRIBE.KYNO_WATERYCRESS_ROOT = "需要海洋"
WORMWOOD.DESCRIBE.KYNO_WATERYCRESS = "肚腩"

WORMWOOD.DESCRIBE.WATERYCRESSBOWL = "粘水"

WORMWOOD.DESCRIBE.KYNO_SALT = "嗯..."

WORMWOOD.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "Food Stick",
	PICKED = "Empty",
	BURNING = "Hurts Stick!",
}

WORMWOOD.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "棍子在游泳！"

WORMWOOD.DESCRIBE.CATFOOD = "猫粮"

WORMWOOD.DESCRIBE.KATFOOD = "猫粮"

WORMWOOD.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "Friend With Sweet Hair",
	PICKED = "Needs Rest",
	CHOPPED = "Friend Gone",
	BURNING = "Friend Hurts!",
	BURNT = "Gone Forever",
}

WORMWOOD.DESCRIBE.KYNO_BANANA = "朋友的甜美头发！"
WORMWOOD.DESCRIBE.KYNO_BANANA_COOKED = "嗯..."

WORMWOOD.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "Nice Hair!",
	PICKED = "Friend Needs Rest",
	CHOPPED = "Oh No",
	BURNING = "Friend Hurts",
	BURNT = "Friend Is Gone",
}

WORMWOOD.DESCRIBE.KYNO_KOKONUT = "肚皮球"
WORMWOOD.DESCRIBE.KYNO_KOKONUT_HALVED = "肚子的东西"
WORMWOOD.DESCRIBE.KYNO_KOKONUT_COOKED = "温暖。"

WORMWOOD.DESCRIBE.BOWLOFPOPCORN = "流行！流行！"

WORMWOOD.DESCRIBE.FIGJUICE = "冰凉的水"

WORMWOOD.DESCRIBE.COCONUTWATER = "甜水"

WORMWOOD.DESCRIBE.EYEBALLSPAGHETTI = "小眼睛食物"

WORMWOOD.DESCRIBE.FORGETMELOTS_SEEDS = "制作橙色肚皮"

WORMWOOD.DESCRIBE.FIRENETTLES_SEEDS = "制作橙色肚皮"

WORMWOOD.DESCRIBE.TILLWEED_SEEDS = "制作橙色腹部的东西"

WORMWOOD.DESCRIBE.KYNO_FLOATILIZER = "大便！耶！"

WORMWOOD.DESCRIBE.KYNO_TWIGGYNUTS = "嗯..."

WORMWOOD.DESCRIBE.KYNO_REPAIRTOOL = "修复工具"

WORMWOOD.DESCRIBE.KYNO_KOI = "漂亮的咕噜咕噜"
WORMWOOD.DESCRIBE.KYNO_KOI_COOKED = "漂亮的咕噜咕噜"

WORMWOOD.DESCRIBE.KYNO_TROPICALFISH = "漂亮的咕噜咕噜"
WORMWOOD.DESCRIBE.KYNO_TROPICALFISH_COOKED = "咕噜?"

WORMWOOD.DESCRIBE.KYNO_NEONFISH = "大润唇膏"
WORMWOOD.DESCRIBE.KYNO_NEONFISH_COOKED = "鱼鳍很好吃"

WORMWOOD.DESCRIBE.KYNO_GROUPER = "紫色糖浆"
WORMWOOD.DESCRIBE.KYNO_GROUPER_COOKED = "不再游泳"
 
WORMWOOD.DESCRIBE.KYNO_PIERROTFISH = "咕噜咕噜"
WORMWOOD.DESCRIBE.KYNO_PIERROTFISH_COOKED = "为肚皮喝水"

WORMWOOD.DESCRIBE.KYNO_SALMONFISH = "从地面获取"
WORMWOOD.DESCRIBE.KYNO_SALMONFISH_COOKED = "为肚皮喝水"

WORMWOOD.DESCRIBE.TURF_PINKPARK = "粉红色"
WORMWOOD.DESCRIBE.TURF_STONECITY = "不是泥土"
WORMWOOD.DESCRIBE.TURF_FIELDS = "污垢"
WORMWOOD.DESCRIBE.TURF_TIDALMARSH = "黏糊糊的泥土"

WORMWOOD.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "Done!",
	PICKED = "Getting Tasty Rocks",
}

WORMWOOD.DESCRIBE.KYNO_SALTRACK_INSTALLER = "得到美味的岩石"

WORMWOOD.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "卑鄙的金属东西"

WORMWOOD.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "地牢监狱"

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "Wrapped Arm Twirly Tail",
	SLEEPING = "Sleeping",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "Sweet Friend!",
	CHOPPED = "Sorry!",
	SAPPED = "Full Of Friend Insides",
	PICKED = "Oh, Friend. Sorry",
	BURNING = "Hurts Bad!",
	BURNT = "Gone...",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "OUCH! Friend Hurt",
	CHOPPED = "Gone",
	SAPPED = "Bad Juice",
	PICKED = "Bugs Hurt friend!",
	BURNING = "Hurts",
	BURNT = "Gone Forever",
}

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_BUD = "想在肚子里？还是在泥土里？"

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_FLOWER = "朋友！"
WORMWOOD.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "朋友！"

WORMWOOD.DESCRIBE.KYNO_SUGARTREE_PETALS = "朋友！"

WORMWOOD.DESCRIBE.KYNO_PEBBLECRAB = "地捏！"

WORMWOOD.DESCRIBE.KYNO_CRABMEAT = "从地捏的分支"
WORMWOOD.DESCRIBE.KYNO_CRABMEAT_COOKED = "小肚腩是很好吃的东西"
WORMWOOD.DESCRIBE.KYNO_CRABMEAT_DRIED = "地面平奇树枝"

WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT = "地面平奇树枝"
WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "硬钳子夹"
WORMWOOD.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "硬钳子夹"

WORMWOOD.DESCRIBE.KYNO_SLAUGHTERTOOL = "卑鄙的事情"

WORMWOOD.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "Ba-gawk!",
	COOP = "Ba-gawk Safe Now",
}

WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG = "宝贝点击点击"
WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "Big Click Click Inside?"
WORMWOOD.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "进肚子"

WORMWOOD.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "Ba-gawk Home",
	FULL = "Eggs Ready!",
	BURNT = "Ba-gawk Gone?",
}

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "损坏"

WORMWOOD.DESCRIBE.KYNO_COOKWARE_KIT = "木盒"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SYRUP = "制作甜蜜的泡泡"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "制作甜蜜的泡泡"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_BIG_POT = "哇！让水起泡！"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_BIG = "哇！让水起泡！"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "哇！让水起泡！"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL = "哇！让水起泡！"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_GRILL = "热棒！"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "需要火"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "小热酒吧"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "需要开火"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_ELDER = "制作甜蜜的泡泡"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "让肚皮变热"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "让肚皮变得漂亮"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "把肚皮放在这里"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN = "提供食物火浴"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "食物要用火洗个澡。"
WORMWOOD.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "给食物提供火浴。"

WORMWOOD.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "Things hiding?",
	FLIPPED = "Found Things",
}

WORMWOOD.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "木头！淹死！"

WORMWOOD.DESCRIBE.KYNO_SUGARFLY = "朋友的朋友"
WORMWOOD.DESCRIBE.KYNO_SUGARFLYWINGS = "不适合飞行"

WORMWOOD.DESCRIBE.KYNO_WATERY_CRATE = "木头！淹死！"

WORMWOOD.DESCRIBE.KYNO_TUNACAN = "什么东西在里面？"
WORMWOOD.DESCRIBE.KYNO_TUNACAN_OPEN = "什么东西在里面？"

WORMWOOD.DESCRIBE.KYNO_CANNEDFOOD = "肚子里有东西？"
WORMWOOD.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "好吃"

WORMWOOD.DESCRIBE.KYNO_POP = "嘘"

WORMWOOD.DESCRIBE.KYNO_MYSTERYMEAT = "嗯……这是什么？"

WORMWOOD.DESCRIBE.KYNO_BOTTLE_SOUL = "嗯..."

WORMWOOD.DESCRIBE.SOULSTEW = "嗯..."

WORMWOOD.DESCRIBE.FORTUNECOOKIE = "奇怪的肚子东西"

WORMWOOD.DESCRIBE.HORNOCUPIA = "肚腩"

WORMWOOD.DESCRIBE.CHEESE_YELLOW = "臭肚皮"
WORMWOOD.DESCRIBE.CHEESE_WHITE = "臭肚皮"
WORMWOOD.DESCRIBE.CHEESE_KOALEFANT = "臭肚皮"

WORMWOOD.DESCRIBE.MILK_BOX = "肚腩？"

WORMWOOD.DESCRIBE.WATERCUP = "水"

WORMWOOD.DESCRIBE.HONEYJAR = "甜食"

WORMWOOD.DESCRIBE.CRAB_ARTICHOKE = "小石头不见了？"

WORMWOOD.DESCRIBE.PEPPERROLLS = "美味小块"

WORMWOOD.DESCRIBE.KYNO_SAPHEALER = "生病的修理工"

WORMWOOD.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "Save The Wood!",
	PICKED = "Waiting",
	BURNING = "Hurts",
}

WORMWOOD.DESCRIBE.KYNO_GHOST_PIRATE = "飘飘人"

WORMWOOD.DESCRIBE.KYNO_BUCKET_EMPTY = "木头东西"
WORMWOOD.DESCRIBE.KYNO_BUCKET_METAL = "金属材料"
WORMWOOD.DESCRIBE.KYNO_BUCKET_WATER = "水友"

WORMWOOD.DESCRIBE.KYNO_MILK_BEEFALO = "哞哞哞？"
WORMWOOD.DESCRIBE.KYNO_MILK_KOALEFANT = "哞哞哞？"

WORMWOOD.DESCRIBE.KYNO_CAP_DRIED = "肚腩"

WORMWOOD.DESCRIBE.KYNO_PLANTMEAT_DRIED = "干涸的肚皮"

WORMWOOD.DESCRIBE.KYNO_BREWBOOK = "肚子里的东西"

WORMWOOD.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "Wooden Box?",
	BREWING_LONG = "Working",
	BREWING_SHORT = "Almost Ready?",
	DONE = "Ready!",
	BURNT = "Gone",
}

WORMWOOD.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "Wooden Box?",
	BREWING_LONG = "Working",
	BREWING_SHORT = "Almost Ready?",
	DONE = "Ready!",
	BURNT = "Gone",
}

WORMWOOD.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "Buzz juice! Where's Buzz?",
	HONEY = "Sweet Stuff!",
	NECTAR = "Not Ready",
	BURNING = "Hurts!",
}

WORMWOOD.DESCRIBE.KYNO_NECTAR_POD = "甜蜜！"

WORMWOOD.DESCRIBE.KYNO_OAKTREE_POD = "你好"
WORMWOOD.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "现在不适合弄脏"

WORMWOOD.DESCRIBE.KYNO_PIKO = "蓬松的纳伯"
WORMWOOD.DESCRIBE.KYNO_PIKO_ORANGE = "蓬松的纳伯"

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "Sleeping?",
	CHOPPED = "Friend Gave Pieces of Hair",
	BURNING = "Hurts!",
	BURNT = "Gone",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "Sleeping With Friends?",
	BURNING = "Hurts!",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "木友们做了一个盒子！"

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "Glub Glub Man Home",
	BURNT = "Glub Glub Man Home Gone",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "Glub Glub Man Home",
	CRAFTED = "Better Home",
	BURNT = "Smells Bad",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "Has Many Stuff Inside",
	OCCUPIED = "Sleeping?",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "Stuff",
	EMPTY = "Nothing",
}

WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "你好！"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_POND = "咕噜咕噜的家"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "你好，小家伙"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "一堆泥土"
WORMWOOD.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "咕噜咕噜人"

WORMWOOD.DESCRIBE.KYNO_SAMMYHAT = "有灰尘"

WORMWOOD.DESCRIBE.KINGFISHER = "戳鼻子高音喇叭"

WORMWOOD.DESCRIBE.TOUCAN = "大鼻子高音喇叭"
WORMWOOD.DESCRIBE.TOUCAN_CHUBBY = "大鼻子高音喇叭"

WORMWOOD.DESCRIBE.WETGOOP2 = "美味！"

WORMWOOD.DESCRIBE.BEER = "有趣的味道"

WORMWOOD.DESCRIBE.PALEALE = "有趣的味道"

WORMWOOD.DESCRIBE.TEAGREEN = "嗯...啊"

WORMWOOD.DESCRIBE.TEARED = "嗯...啊"

WORMWOOD.DESCRIBE.MEAD = "甜食"

WORMWOOD.DESCRIBE.KYNO_JELLY = "甜美的肚皮"

WORMWOOD.DESCRIBE.KYNO_MAYONNAISE = "嗯..."

WORMWOOD.DESCRIBE.TARTARSAUCE = "辣肚"

WORMWOOD.DESCRIBE.KYNO_PICKLES = "肚腩"

WORMWOOD.DESCRIBE.KYNO_WINE = "苦水"

WORMWOOD.DESCRIBE.KYNO_JUICE = "甜食"

WORMWOOD.DESCRIBE.KYNO_POISON_FROGLEGS = "长腿"
WORMWOOD.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "（闻，闻）闻起来不错"

WORMWOOD.DESCRIBE.POISONFROGGLEBUNWICH = "填饱肚子"

WORMWOOD.DESCRIBE.KYNO_BREWINGRECIPECARD = "嗯。不好"

WORMWOOD.DESCRIBE.KYNO_OIL = "肚子里的东西？"

WORMWOOD.DESCRIBE.BERRYSUNDAE = "酷"

WORMWOOD.DESCRIBE.CHOCOLATE_BLACK = "好甜！"
WORMWOOD.DESCRIBE.CHOCOLATE_WHITE = "好甜！"

WORMWOOD.DESCRIBE.TRICOLORDANGO = "甜蜜"
 
WORMWOOD.DESCRIBE.FRIESFRENCH = "人类的垃圾食品。"

WORMWOOD.DESCRIBE.PIRATERUM = "邪恶？"

WORMWOOD.DESCRIBE.TWISTEDTEQUILA = "肚子里的东西？"

WORMWOOD.DESCRIBE.ONIONRINGS = "脆洋葱"

WORMWOOD.DESCRIBE.DONUTS = "甜甜的肚子里的东西"
WORMWOOD.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "甜甜的肚皮东西"
WORMWOOD.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "甜甜的肚皮东西"
 
WORMWOOD.DESCRIBE.CINNAMONROLL = "肚子里的东西"

WORMWOOD.DESCRIBE.GUMMYBEARGERS = "好！"

WORMWOOD.DESCRIBE.PRETZEL = "肚子里的东西"

WORMWOOD.DESCRIBE.CORNINCUP = "对腹部有好处"

WORMWOOD.DESCRIBE.COTTONCANDY = "空气？"

WORMWOOD.DESCRIBE.ROASTEDHAZELNUTS = "坚果！"

WORMWOOD.DESCRIBE.MONSTERMUFFIN = "奇怪的腹部东西"

WORMWOOD.DESCRIBE.PINKCAKE = "糖肚里的东西"

WORMWOOD.DESCRIBE.CHIPSBAG = "肚子里的东西"

WORMWOOD.DESCRIBE.LITTLEBREAD = "蓬松"

WORMWOOD.DESCRIBE.HOTHOUND = "狗去哪儿了？"

WORMWOOD.DESCRIBE.MILKSHAKE = "摇一摇！"
WORMWOOD.DESCRIBE.MILKSHAKE_PRISMATIC = "摇一摇！"

WORMWOOD.DESCRIBE.NACHOS = "俗气"

WORMWOOD.DESCRIBE.BANANA_PUDDING = "娜娜"

WORMWOOD.DESCRIBE.SEA_PUDDING = "鱼？"

WORMWOOD.DESCRIBE.TOM_KHA_SOUP = "蔬菜"

WORMWOOD.DESCRIBE.MINERTREAT = "奇怪"

WORMWOOD.DESCRIBE.RADISHSALAD = "想吃它"

WORMWOOD.DESCRIBE.PUMPKIN_SOUP = "游泳肚的东西"

WORMWOOD.DESCRIBE.ALGAE_SOUP = "游泳肚的东西"

WORMWOOD.DESCRIBE.PARZNIP_SOUP = "游泳肚的东西"

WORMWOOD.DESCRIBE.NETTLEMEATED = "嗯……"

WORMWOOD.DESCRIBE.KYNO_SUGAR = "甜粉"

WORMWOOD.DESCRIBE.KYNO_BOTTLECAP = "帽子"

WORMWOOD.DESCRIBE.NUKACOLA = "模糊"
WORMWOOD.DESCRIBE.NUKACOLA_QUANTUM = "模糊"

WORMWOOD.DESCRIBE.LIVINGSANDWICH = "奇怪的面包"

WORMWOOD.DESCRIBE.DURIANSPLIT = "酷"

WORMWOOD.DESCRIBE.DURIANSOUP = "蠕动的水"

WORMWOOD.DESCRIBE.DURIANMEATED = "臭肚皮的东西"

WORMWOOD.DESCRIBE.DURIANCHICKEN = "肚子里的东西"

WORMWOOD.DESCRIBE.LUNARSOUP = "月亮！"

WORMWOOD.DESCRIBE.PURPLEWOBSTERSOUP = "可怜的沃伯斯特"

WORMWOOD.DESCRIBE.WOBSTERMONSTER = "怪物"

WORMWOOD.DESCRIBE.SPIDERCAKE = "蜘蛛蛋糕"

WORMWOOD.DESCRIBE.SUGARBOMBS = "咔boom"

WORMWOOD.DESCRIBE.BERRYBOMBS = "甜甜的肚子里的东西"

WORMWOOD.DESCRIBE.ONIGIRIS = "谷物"

WORMWOOD.DESCRIBE.OMURICE = "炒谷物"

WORMWOOD.DESCRIBE.PAELLA = "谷物!"

WORMWOOD.DESCRIBE.RISOTTO = "谷物和朋友们"

WORMWOOD.DESCRIBE.RICESAKE = "谷物水？"

WORMWOOD.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "Friend Needs Soil"

WORMWOOD.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "Hi Friend!",
	PICKED = "Where Did Friend Spikes Go?",
	WITHERED = "Too Dry",
	BURNING = "Friend Hurt!",
}

WORMWOOD.DESCRIBE.KYNO_PINEAPPLE = "多刺"
WORMWOOD.DESCRIBE.KYNO_PINEAPPLE_HALVED = "腹部的东西"
WORMWOOD.DESCRIBE.KYNO_PINEAPPLE_COOKED = "腹部的东西"

WORMWOOD.DESCRIBE.PIZZA_TROPICAL = "朋友?"

WORMWOOD.DESCRIBE.PINACOLADA = "朋友?"

WORMWOOD.DESCRIBE.CHIMAS = "青草?"

WORMWOOD.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "Helps Friends",
	ON = "Friends Are Happy With Splashy Metal Thing",
}

WORMWOOD.DESCRIBE.KYNO_FOODSACK = "保持肚子里东西新鲜"

WORMWOOD.DESCRIBE.GUMMYWORMS = "虫子?"

WORMWOOD.DESCRIBE.SMORES = "巧克力?"

WORMWOOD.DESCRIBE.NUKASHINE = "奇特饮料"

WORMWOOD.DESCRIBE.ANTSLOG = "木质"

WORMWOOD.DESCRIBE.KYNO_WORM_BONE = "噢"

WORMWOOD.DESCRIBE.SPOOKY_BRAIN_NOODLES = "介意吗？"
WORMWOOD.DESCRIBE.SPOOKY_BURGERZILLA = "怪兽!"
WORMWOOD.DESCRIBE.SPOOKY_DEADBREAD = "毛茸茸的"
WORMWOOD.DESCRIBE.SPOOKY_JELLYBEANS = "让人毛骨悚然"
WORMWOOD.DESCRIBE.SPOOKY_POPSICLE = "好吃"
WORMWOOD.DESCRIBE.SPOOKY_PUMPKINCREAM = "奇怪的朋友？"
WORMWOOD.DESCRIBE.SPOOKY_SKULLCANDY = "害怕"
WORMWOOD.DESCRIBE.SPOOKY_TACODILE = "朋友?"

WORMWOOD.DESCRIBE.BUTTER_BEEFALO = "黏糊的"
WORMWOOD.DESCRIBE.BUTTER_GOAT = "黏糊的?"
WORMWOOD.DESCRIBE.BUTTER_KOALEFANT = "真好吃!"

WORMWOOD.DESCRIBE.SPICE_CURE = "确保食品安全"
WORMWOOD.DESCRIBE.SPICE_COLD = "冷！"
WORMWOOD.DESCRIBE.SPICE_FIRE = "燃烧！"
WORMWOOD.DESCRIBE.SPICE_FED = "感到饿的"
WORMWOOD.DESCRIBE.SPICE_MIND = "嗜睡"

WORMWOOD.DESCRIBE.SUGARFLYMUFFIN = "嗯......"

WORMWOOD.DESCRIBE.EELTACOS = "为了肚子"

WORMWOOD.DESCRIBE.MEATSKILLET = "为了肚子"

WORMWOOD.DESCRIBE.MEATWALTZ = "为了肚子?"

WORMWOOD.DESCRIBE.COMPLETEBREAKFAST = "大腹便便"

WORMWOOD.DESCRIBE.DUMPLINGS = "肚子里的东西"

WORMWOOD.DESCRIBE.WARLYICEDTEA = "清爽的迅捷水"

WORMWOOD.DESCRIBE.WARLYTEA = "温暖的迅捷水"

WORMWOOD.DESCRIBE.KYNO_TEALEAF = "温馨的朋友"

WORMWOOD.DESCRIBE.KYNO_ITEMSLICER = "切肉刀。给朋友理发"
WORMWOOD.DESCRIBE.KYNO_ITEMSLICER_GOLD = "切肉刀。给朋友理发"

WORMWOOD.DESCRIBE.COXINHA = "腹部的东西"

WORMWOOD.DESCRIBE.LAZYDESSERT = "坚硬"

WORMWOOD.DESCRIBE.CRABKINGFEAST = "巨兽！"

WORMWOOD.DESCRIBE.PIENAPPLE = "朋友有刺头发!"

WORMWOOD.DESCRIBE.JAWSBREAKER = "太硬"

WORMWOOD.DESCRIBE.AVOCADOTOAST = "好吃"

WORMWOOD.DESCRIBE.RICEPUDDING = "混合"

WORMWOOD.DESCRIBE.SHARKSUSHI = "肚子里的东西"

WORMWOOD.DESCRIBE.WOBSTERBREADED = "酥脆炸，咕噜咕噜"

WORMWOOD.DESCRIBE.LAZYPURRITO = "傻猫"

WORMWOOD.DESCRIBE.HORCHATA = "冷！"

WORMWOOD.DESCRIBE.WOBSTERCOCKTAIL = "火焰"

WORMWOOD.DESCRIBE.LAVAEEGGBOILED = "热！"

WORMWOOD.DESCRIBE.POMEGRANATETEA = "冷水"

WORMWOOD.DESCRIBE.TIRAMISU = "嘀嘀！嘀嘀！"

WORMWOOD.DESCRIBE.TOADSTOOLCOLA = "臭臭的"

WORMWOOD.DESCRIBE.TEPACHE = "甜蜜朋友果汁"

WORMWOOD.DESCRIBE.LUNARTEQUILA = "月亮的东西？"

WORMWOOD.DESCRIBE.MIMICMOSA = "暗黑窥视饮料"

WORMWOOD.DESCRIBE.POMEGRANATEPIE = "红色的肚子里的东西"

WORMWOOD.DESCRIBE.PINEAPPLECAKE = "肚子里的东西"

WORMWOOD.DESCRIBE.PASTY_MEAT = "酥脆的"
WORMWOOD.DESCRIBE.PASTY_CHEESE = "酥脆的"

WORMWOOD.DESCRIBE.BRIGADEIRO = "碎片"

WORMWOOD.DESCRIBE.REGULARLASAGNA = "肚子里的东西"

WORMWOOD.DESCRIBE.FLTSANDWICH = "青蛙"

WORMWOOD.DESCRIBE.RICEANDBEANS = "肚子里的东西"

WORMWOOD.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "老房子……也许很快会有新生命……"

WORMWOOD.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "Friend Grows In Dirt!",
	PICKED = "Gone",
	BURNING = "Friend Hurt!",
}

WORMWOOD.DESCRIBE.KYNO_TRUFFLES = "有味道的朋友食物。"
WORMWOOD.DESCRIBE.KYNO_TRUFFLES_COOKED = "温暖的朋友食物！"

WORMWOOD.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "Show Food To Friends",
	FULL = "Food Looking Nice",
}

WORMWOOD.DESCRIBE.KYNO_SPORECAP = "朋友……生病了……"
WORMWOOD.DESCRIBE.KYNO_SPORECAP_COOKED = "热热的朋友！好一点？"

WORMWOOD.DESCRIBE.KYNO_SPORECAP_DARK = "朋友伤害朋友……"
WORMWOOD.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "还会伤害朋友……"

WORMWOOD.DESCRIBE.KYNO_GOLDENAPPLE = "亮亮的！朋友果！"

WORMWOOD.DESCRIBE.TRUFFLESGRINDER = "嗯！地里的三明治！"

WORMWOOD.DESCRIBE.SPORECAPPIE = "软软派"

WORMWOOD.DESCRIBE.SPORECAP_SKEWERS = "朋友们……现在好吃了！"

WORMWOOD.DESCRIBE.TRUFFLEOIL = "味道好强。"

WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "湖泊规划"
WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "水培种植！"

WORMWOOD.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "Glub Glub Home",
	FUEL_HIGH = "Fish Happy!",
	FUEL_MED = "Fish Eating",
	FUEL_LOW = "Need Snacks Soon",
	EMPTY = "No More Snacks",
}

WORMWOOD.DESCRIBE.KYNO_ANTCHOVY = "虫虫怪怪的朋友！你好呀！"
WORMWOOD.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "许多虫虫鱼鱼的朋友！"

WORMWOOD.DESCRIBE.AGEDROE = "咕噜咕噜，宝宝被困住了？"
WORMWOOD.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "咕噜咕噜，宝宝。"

WORMWOOD.DESCRIBE.KYNO_SWORDFISH_BLUE = "不会游泳？"

WORMWOOD.DESCRIBE.KYNO_JELLYFISH = "咕嘟咕嘟泡泡"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_DEAD = "可怜的黏糊团"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_COOKED = "粘液圈圈"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_DRIED = "嚼嚼黏团"

WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "漂亮。咕噜"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "不再蓬松"
WORMWOOD.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "漂亮的戒指"

WORMWOOD.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "哎呀，里面什么都没有。"

WORMWOOD.DESCRIBE.KYNO_OCEANTRAP = "湿陷阱"

WORMWOOD.DESCRIBE.OCEANFISH_PUFFERFISH = "慢吞吞。咕噜咕噜"
WORMWOOD.DESCRIBE.OCEANFISH_STURGEON = "老。咕噜咕噜"

WORMWOOD.DESCRIBE.KYNO_SWORDFISH = "尖鼻。咕噜咕噜"
WORMWOOD.DESCRIBE.KYNO_SWORDFISH_DEAD = "（抽泣）"

WORMWOOD.DESCRIBE.SWORDFISHFEAST = "花式。咕噜咕噜"

WORMWOOD.DESCRIBE.KYNO_DOGFISH = "咕噜咕噜低音炮"
WORMWOOD.DESCRIBE.KYNO_DOGFISH_DEAD = "你好呀，咕噜咕噜"

WORMWOOD.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "闻起来真香。嗯嗯嗯。"

WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND = "闪亮的水中伙伴！"
WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "不再有炫技动作..."
WORMWOOD.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "朋友?"

WORMWOOD.DESCRIBE.KYNO_PUFFERMONSTER = "戳戳小鱼！别戳朋友！"

WORMWOOD.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "咕噜咕噜还是呜呜呜？"
WORMWOOD.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "呜呜呜呜！"
WORMWOOD.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "苍白"
WORMWOOD.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "超——大！"

WORMWOOD.DESCRIBE.KYNO_BLUBBER = "软趴趴的"

WORMWOOD.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "咕噜咕噜干，嗯！"
WORMWOOD.DESCRIBE.KYNO_FISHMEAT_DRIED = "干噗噗"

WORMWOOD.DESCRIBE.MONKEYISLANDMEAL = "咕噜咕噜和朋友"

WORMWOOD.DESCRIBE.KYNO_BRAINROCK_LARVAE = "需要岩石"
WORMWOOD.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "可爱宝宝湿石头"
WORMWOOD.DESCRIBE.KYNO_BRAINROCK_CORAL = "思考中..."

WORMWOOD.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "Thinky Rock",
	PICKED = "Thinky Rock Tired",
}

WORMWOOD.DESCRIBE.BRAINMETTERSOUP = "细腻的东西"

WORMWOOD.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "Big Arms Guy",
	SLEEPING = "Sleeping",
}

WORMWOOD.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "来自大块头的装备！"

WORMWOOD.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "Friend Tweeter Likes You!",
	WAITING = "Where Did Tweeter Go?",
}

WORMWOOD.DESCRIBE.KYNO_PACKIMBAGGIMS = "大嘴朋友"

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "需要东西"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "需要更多内容"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "它超——大！"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "为巨型蛋糕点亮"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "朋友们……"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "甜甜的肚子里的东西！"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "飘飘的朋友们！嗨！"

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "Pop Maker",
	FUEL_HIGH = "Pop Maker Is Happy",
	FUEL_MED = "Working",
	FUEL_LOW = "Pop Maker Looks Hungry",
	EMPTY = "Empty",
}

WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "砰砰"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "派对帽！哇！"
WORMWOOD.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "朋友帽！"

WORMWOOD.DESCRIBE.KYNO_FISHREGISTRYHAT = "懂鱼的帽子"

WORMWOOD.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "Food Place",
	FUEL_HIGH = "Lots Of Food",
	FUEL_MED = "Some Food",
	FUEL_LOW = "Little Food",
	EMPTY = "No Food",
	BURNT = "Gone",
}

WORMWOOD.DESCRIBE.CHICKENNUGGETS = "Ba-gawk Pieces"

WORMWOOD.DESCRIBE.CHICKENWINGS = "Hurts Belly"

WORMWOOD.DESCRIBE.CHICKENBURGER = "Ba-gawk Hug bread"

WORMWOOD.DESCRIBE.CHICKENEGGSOUP = "Warm Egg Water"

WORMWOOD.DESCRIBE.CHICKENEGGSTEW = "Ba-gawk Bath"

WORMWOOD.DESCRIBE.CHICKENROTISSERIE = "Hot Ba-gawk."