local WARLY = STRINGS.CHARACTERS.WARLY

WARLY.ANNOUNCE_KYNO_COFFEEBUFF_START = "天啊！它让我做饭更快！"
WARLY.ANNOUNCE_KYNO_COFFEEBUFF_END = "哎呀。回到我的正常行走。"

WARLY.ANNOUNCE_KYNO_HASTEBUFF_START = "更快的烹饪！"
WARLY.ANNOUNCE_KYNO_HASTEBUFF_END = "我的天哪！我需要休息一下我的手。"

WARLY.ANNOUNCE_KYNO_POPBUFF_START = "（嗝...）抱歉..."
WARLY.ANNOUNCE_KYNO_POPBUFF_END = "令人耳目一新，而且......"

WARLY.ANNOUNCE_KYNO_FROGBUFF_START = "事实上，一种奇怪的感觉。"
WARLY.ANNOUNCE_KYNO_FROGBUFF_END = "青蛙的感觉消失了。"

WARLY.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝...) 我已经准备好出海了！"
WARLY.ANNOUNCE_KYNO_PIRATEBUFF_END = "它让人耳目一新，..."

WARLY.ANNOUNCE_KYNO_FREEZEBUFF_START = "一场永恒的暴风雪！"
WARLY.ANNOUNCE_KYNO_FREEZEBUFF_END = "暴风雪退去了。"

WARLY.ANNOUNCE_KYNO_FIREBUFF_START = "小心！"
WARLY.ANNOUNCE_KYNO_FIREBUFF_END = "火焰渐渐熄灭了。"

WARLY.ANNOUNCE_KYNO_FISHINGBUFF_START = "这可能对水禽狩猎有用。"
WARLY.ANNOUNCE_KYNO_FISHINGBUFF_END = "今天不再有更多的鱼了。"

WARLY.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "一杯舒缓的茶来舒缓我的神经。"
WARLY.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "我的头脑已经休息够了。"

WARLY.ANNOUNCE_KYNO_EATERBUFF_START = "我的牙齿现在可以吃任何东西了！"
WARLY.ANNOUNCE_KYNO_EATERBUFF_END = "我的牙齿变弱了！"

WARLY.ANNOUNCE_KYNO_WORMBUFF_START = "又到了猎虫季节！"
WARLY.ANNOUNCE_KYNO_WORMBUFF_END = "我的天！我需要休息一会儿。"

WARLY.ANNOUNCE_KYNO_CRABBUFF_START = "捕蟹季节到了!"
WARLY.ANNOUNCE_KYNO_CRABBUFF_END = "我的天！我需要休息一会儿。"

WARLY.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝...) 对不起..."
WARLY.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "这令人耳目一新..."

WARLY.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "我来了。"
WARLY.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "恢复正常..."

WARLY.ANNOUNCE_KYNO_STEALTHBUFF_START = "偷偷摸摸！"
WARLY.ANNOUNCE_KYNO_STEALTHBUFF_END = "我不能再偷偷摸摸了。"

WARLY.ANNOUNCE_KYNO_FEARBUFF_START = "太棒了！这是真正勇气的秘诀！"
WARLY.ANNOUNCE_KYNO_FEARBUFF_END = "勇气消失了...留下真正平淡的回味。"

WARLY.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "神圣的味道……融入我体内！"
WARLY.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "啊，力量的滋味已经消失。"

WARLY.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "这些猪很欣赏好厨师！"
WARLY.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "猪不再留在我身边。"

WARLY.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "对一位温柔厨师来说，这是完美的防护！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WARLY.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "真是松了一口气！我又能自由地品尝了。"
WARLY.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "哎呀……得再次小心用料了。"

WARLY.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "啊，灵感！成功的秘诀如此清晰！"
WARLY.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "啊，我的缪斯又一次离开了厨房。"

WARLY.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "啊，蜜蜂们现在心情很好。"
WARLY.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "蜜蜂的脾气又变差了。"

WARLY.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "给身体注入一股强劲的活力！"
WARLY.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "我的韧性已逐渐消退..."

WARLY.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "啊！为美食佳肴腾出更多空间！"
WARLY.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "唉……烹饪梦想破灭了。"

WARLY.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "心性纯粹，品味高雅！"
WARLY.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "我的烹饪热情正在消退……"

WARLY.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "啊！一种极其强烈的保护感！"
WARLY.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "啊……保护作用已经消失了。"

WARLY.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "错了，错了……"

WARLY.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "你想吃点更美味的吗？"

WARLY.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "现阶段，它还不能做任何事情。"

WARLY.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "嗯……或许还有别的。"

WARLY.ANNOUNCE_KYNO_POTHANGER_FAIL = "啊！我忘了锅了！"

WARLY.ANNOUNCE_KYNO_CASSEROLE_FAIL = "我可不能忘了砂锅菜！"

WARLY.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "新鲜食材成就顶级佳肴。"

WARLY.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "空荡荡的储藏室……真不幸。"

WARLY.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "该死……我把晚餐的踪迹弄丢了！"
WARLY.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "没有踪迹，没有食物……糟糕！"
WARLY.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "啊，主菜上桌啦！"

WARLY.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "太棒了！值得庆祝的蛋糕！"

WARLY.ANNOUNCE_KYNO_FISH_RESEARCHED = "啊！现在我真正理解这种食材了。"
WARLY.ANNOUNCE_KYNO_ROE_RESEARCHED = "啊！这些鱼卵蕴含着如此精致的潜力。"

WARLY.DESCRIBE.KYNO_ROE = "我可以用小点心做鱼子酱！"
WARLY.DESCRIBE.KYNO_ROE_COOKED = "可以加一点新鲜柠檬。"

WARLY.DESCRIBE.KYNO_SHARK_FIN = "这看起来相当明亮。"

WARLY.DESCRIBE.KYNO_BEANBUGS = "跳跃的果冻豆！"
WARLY.DESCRIBE.KYNO_BEANBUGS_COOKED = "呃。看起来不好吃。"

WARLY.DESCRIBE.KYNO_GUMMYBUG = "生而带壳的蜗牛！"
WARLY.DESCRIBE.KYNO_GUMMYBUG_COOKED = "没有大蒜黄油就不太好吃了。"

WARLY.DESCRIBE.KYNO_WHEAT = "可以用它来做面粉。"
WARLY.DESCRIBE.KYNO_WHEAT_COOKED = "烤好了。"

WARLY.DESCRIBE.KYNO_FLOUR = "这肯定能做出美味佳肴！"

WARLY.DESCRIBE.KYNO_SPOTSPICE = "香料，终于！"

WARLY.DESCRIBE.KYNO_SAP = "嗯！"
WARLY.DESCRIBE.KYNO_SAP_SPOILED = "不能再食用了。"

WARLY.DESCRIBE.KYNO_SYRUP = "这肯定会是很好的糖果原料！"

WARLY.DESCRIBE.KYNO_COFFEEBEANS = "太棒了！"
WARLY.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "可以用热水...！"

WARLY.DESCRIBE.DUG_KYNO_COFFEEBUSH = "那棵灌木会长出……咖啡豆吗？！"
WARLY.DESCRIBE.KYNO_COFFEEBUSH = "那棵灌木会长出……咖啡豆吗？！"

WARLY.DESCRIBE.DUG_KYNO_SPOTBUSH = "哦！香料灌木。"
WARLY.DESCRIBE.KYNO_SPOTBUSH = "哦！香料灌木。"

WARLY.DESCRIBE.KYNO_SPOTSPICE_LEAF = "你会成为一个很好的调料！"

WARLY.DESCRIBE.KYNO_MUSSEL = "你可以去我的肚子里！"
WARLY.DESCRIBE.KYNO_MUSSEL_COOKED = "可以用小葱和柠檬草..."

WARLY.DESCRIBE.KYNO_HUMANMEAT = "我想我不能对我的配料挑剔，但是......"
WARLY.DESCRIBE.KYNO_HUMANMEAT_COOKED = "有些菜可能不应该做。"
WARLY.DESCRIBE.KYNO_HUMANMEAT_DRIED = "我觉得我已经没胃口了。"

WARLY.DESCRIBE.COFFEE = "好吃!!"

WARLY.DESCRIBE.BISQUE = "太棒了！"

WARLY.DESCRIBE.JELLYOPOP = "嗯……有趣的味道。"

WARLY.DESCRIBE.SHARKFINSOUP = "我使用了娜娜的秘方。"

WARLY.DESCRIBE.TROPICALBOUILLABAISSE = "好腐烂的菜！"

WARLY.DESCRIBE.MUSSELBOUILLABAISE = "这道菜让我精神振奋。"

WARLY.DESCRIBE.SWEETPOTATOSOUFFLE = "滋养灵魂和滋养身体的食物。"

WARLY.DESCRIBE.FEIJOADA = "我不得不即兴发挥。"

WARLY.DESCRIBE.GUMMY_CAKE = "比我平时喜欢的更耐嚼。"

WARLY.DESCRIBE.HARDSHELL_TACOS = "我用手头的材料凑合着用。"

WARLY.DESCRIBE.ICEDTEA = "啊。令人耳目一新。"

WARLY.DESCRIBE.NETTLELOSANGE = "具有药用价值的食物。"

WARLY.DESCRIBE.SNAKEBONESOUP = "珍贵食谱。"

WARLY.DESCRIBE.STEAMEDHAMSANDWICH = "尝起来像快餐。"

WARLY.DESCRIBE.TEA = "茶！我好想你！"

WARLY.DESCRIBE.BUBBLETEA = "啊。令人耳目一新。"

WARLY.DESCRIBE.FRENCHONIONSOUP = "我喜欢汤。"

WARLY.DESCRIBE.SLAW = "名副其实的蔬菜大杂烩！"

WARLY.DESCRIBE.LOTUSBOWL = "美味佳肴。"

WARLY.DESCRIBE.POI = "经典夏威夷大餐。"

WARLY.DESCRIBE.JELLYBEAN_HUNGER = "一点甜美的东西，可以照亮一天。"
WARLY.DESCRIBE.JELLYBEAN_SUPER = "一点甜美的东西，让一天变得明亮。"
WARLY.DESCRIBE.JELLYBEAN_SANITY = "一点甜美的东西，让一天变得明亮。"

WARLY.DESCRIBE.BOWLOFGEARS = "这不是食物！"

WARLY.DESCRIBE.LONGPIGMEAL = "有些菜可能不应该做。"

WARLY.DESCRIBE.CUCUMBERSALAD = "可食用的艺术品！"

WARLY.DESCRIBE.KYNO_WILDWHEAT = "这里常见的食材。"
WARLY.DESCRIBE.DUG_KYNO_WILDWHEAT = "这里常见的食材。"

WARLY.DESCRIBE.KYNO_MEALGRINDER = "太棒了！研磨机！"

WARLY.DESCRIBE.GORGE_BREAD = "这个！我可以用它做很多菜！"
WARLY.DESCRIBE.GORGE_SWEET_CHIPS = "土豆片。"
WARLY.DESCRIBE.GORGE_VEGETABLE_SOUP = "健康美味的蔬菜餐。"
WARLY.DESCRIBE.GORGE_JELLY_SANDWICH = "棒极了！"
WARLY.DESCRIBE.GORGE_FISH_STEW = "完美的鱼粉。"
WARLY.DESCRIBE.GORGE_MEAT_STEW = "温暖我的灵魂！"
WARLY.DESCRIBE.GORGE_ONION_CAKE = "每个蛋糕都值得欣赏。"
WARLY.DESCRIBE.GORGE_POTATO_PANCAKES = "我现在只需要糖浆。"
WARLY.DESCRIBE.GORGE_POTATO_SOUP = "绝对神圣！"
WARLY.DESCRIBE.GORGE_FISHBALL_SKEWERS = "日常快餐。"
WARLY.DESCRIBE.GORGE_MEAT_SKEWERS = "日常快餐。"
WARLY.DESCRIBE.GORGE_STONE_SOUP = "绝对神圣！"
WARLY.DESCRIBE.GORGE_CROQUETTE = "炸肉饼总是不错的补充。"
WARLY.DESCRIBE.GORGE_ROAST_VEGETABLES = "沙拉总是很受欢迎的。"
WARLY.DESCRIBE.GORGE_MEATLOAF = "一片美味的面包。"
WARLY.DESCRIBE.GORGE_CARROT_SOUP = "绝对神圣！"
WARLY.DESCRIBE.GORGE_FISHPIE = "不是很吸引人。"
WARLY.DESCRIBE.GORGE_FISHCHIPS = "这个组合不错。"
WARLY.DESCRIBE.GORGE_MEATPIE = "馅饼做得很好。"
WARLY.DESCRIBE.GORGE_SLIDERS = "这只是他们的第一阶段。"
WARLY.DESCRIBE.GORGE_JELLY_ROLL = "完美！"
WARLY.DESCRIBE.GORGE_CARROT_CAKE = "完美！"
WARLY.DESCRIBE.GORGE_GARLICMASHED = "啊！它看起来容光焕发。"
WARLY.DESCRIBE.GORGE_GARLICBREAD = "味道不错！"
WARLY.DESCRIBE.GORGE_TOMATO_SOUP = "绝对神圣！"
WARLY.DESCRIBE.GORGE_SAUSAGE = "烧烤的最佳项目。"
WARLY.DESCRIBE.GORGE_CANDIEDFISH = "一条完美的鱼淹没在糖浆里。"
WARLY.DESCRIBE.GORGE_STUFFEDMUSHROOM = "很好的馅料。"
WARLY.DESCRIBE.GORGE_BRUSCHETTA = "我为这个作品感到非常自豪！"
WARLY.DESCRIBE.GORGE_HAMBURGER = "天哪！"
WARLY.DESCRIBE.GORGE_FISHBURGER = "老天爷！"
WARLY.DESCRIBE.GORGE_MUSHROOMBURGER = "老天爷！"
WARLY.DESCRIBE.GORGE_FISH_STEAK = "完美的鱼粉。"
WARLY.DESCRIBE.GORGE_CURRY = "经典一餐。"
WARLY.DESCRIBE.GORGE_SPAGHETTI = "我很高兴！"
WARLY.DESCRIBE.GORGE_POACHEDFISH = "我也是一个非常出色的捕鱼人。"
WARLY.DESCRIBE.GORGE_SHEPHERD_PIE = "牧羊人的战利品"
WARLY.DESCRIBE.GORGE_CANDY = "我希望它永远不会从我的牙齿上掉下来！"
WARLY.DESCRIBE.GORGE_BREAD_PUDDING = "经典的甜点。"
WARLY.DESCRIBE.GORGE_BERRY_TART = "酸酸甜甜的水果味。"
WARLY.DESCRIBE.GORGE_MACARONI = "完美通心粉。"
WARLY.DESCRIBE.GORGE_BAGEL_AND_FISH = "面包圈与鲑鱼相得益彰。"
WARLY.DESCRIBE.GORGE_GRILLED_CHEESE = "烤得完美无瑕。"
WARLY.DESCRIBE.GORGE_CREAMMUSHROOM = "上好的蘑菇汤总是用香菇熬制。"
WARLY.DESCRIBE.GORGE_MANICOTTI = "我更喜欢意大利乳清干酪与切碎的大蒜混合在一起。"
WARLY.DESCRIBE.GORGE_CHEESEBURGER = "老天爷！"
WARLY.DESCRIBE.GORGE_FETTUCCINE = "完美！"
WARLY.DESCRIBE.GORGE_ONION_SOUP = "准备好你的嘴！"
WARLY.DESCRIBE.GORGE_BREADED_CUTLET = "我受宠若惊。"
WARLY.DESCRIBE.GORGE_CREAMY_FISH = "鲑鱼在很多方面都很美味。"
WARLY.DESCRIBE.GORGE_PIZZA = "完美。"
WARLY.DESCRIBE.GORGE_POT_ROAST = "一场盛宴！"
WARLY.DESCRIBE.GORGE_CRAB_CAKE = "美食艺术品。"
WARLY.DESCRIBE.GORGE_STEAK_FRITES = "说一个更有代表性的二人组合吧，我等着。"
WARLY.DESCRIBE.GORGE_SHOOTER_SANDWICH = "一块美味的菲力牛排配面包。"
WARLY.DESCRIBE.GORGE_BACON_WRAPPED = "漂亮又简单。"
WARLY.DESCRIBE.GORGE_CRAB_ROLL = "精彩！"
WARLY.DESCRIBE.GORGE_MEAT_WELLINGTON = "我每天都在改进这个食谱。"
WARLY.DESCRIBE.GORGE_CRAB_RAVIOLI = "精彩!"
WARLY.DESCRIBE.GORGE_CARAMEL_CUBE = "糖果多可爱啊。"
WARLY.DESCRIBE.GORGE_SCONE = "啊！完美。"
WARLY.DESCRIBE.GORGE_TRIFLE = "啊！完美。"
WARLY.DESCRIBE.GORGE_CHEESECAKE = "完美的奶酪蛋糕！"

WARLY.DESCRIBE.DUCKYOUGLERMZ = "我的天！"

WARLY.DESCRIBE.KYNO_ALOE = "也许是我在里面放了一杯饮料。"
WARLY.DESCRIBE.KYNO_ALOE_COOKED = "我可以把它加到一些东西上。"
WARLY.DESCRIBE.KYNO_ALOE_GROUND = "也许是我在里面放了一杯饮料。"
WARLY.DESCRIBE.KYNO_ALOE_SEEDS = "未来的食材，正等待种植！"
WARLY.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "未来的食材，正等待种植！"
WARLY.DESCRIBE.FARM_PLANT_KYNO_ALOE = "也许我可以把它放进一种饮料里。"
WARLY.DESCRIBE.KYNO_ALOE_OVERSIZED = "也许我可以把它放进一种饮料里。"
WARLY.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "噢 不。"

WARLY.DESCRIBE.KYNO_CUCUMBER = "海洋蔬菜！"
WARLY.DESCRIBE.KYNO_CUCUMBER_COOKED = "这……可能会好一点。"
WARLY.DESCRIBE.KYNO_CUCUMBER_GROUND = "海洋蔬菜！"
WARLY.DESCRIBE.KYNO_CUCUMBER_SEEDS = "未来的原料，正等待种植！"
WARLY.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "未来的成分，正等待种植！"
WARLY.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "海洋蔬菜！"
WARLY.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "海洋蔬菜！"
WARLY.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "海洋蔬菜！"

WARLY.DESCRIBE.KYNO_RADISH = "我在想一份美味的夏日沙拉……"
WARLY.DESCRIBE.KYNO_RADISH_COOKED = "用少许橄榄油烤制。"
WARLY.DESCRIBE.KYNO_RADISH_GROUND = "我在想一份不错的夏日沙拉……"
WARLY.DESCRIBE.KYNO_RADISH_SEEDS = "未来的原料，等待种植！"
WARLY.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "未来的原料，等待种植！"
WARLY.DESCRIBE.FARM_PLANT_KYNO_RADISH = "我想做一份美味的夏日沙拉..."
WARLY.DESCRIBE.KYNO_RADISH_OVERSIZED = "我想做一份美味的夏日沙拉..."
WARLY.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "噢 不。"

WARLY.DESCRIBE.KYNO_FENNEL = "会做一些很好的沙拉。"
WARLY.DESCRIBE.KYNO_FENNEL_COOKED = "可以用更多的东西让它变得更好......"
WARLY.DESCRIBE.KYNO_FENNEL_GROUND = "会做一些很好的沙拉。"
WARLY.DESCRIBE.KYNO_FENNEL_SEEDS = "未来的原料，正等待种植！"
WARLY.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "未来的原料，正等待种植！"
WARLY.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "可以做成美味的沙拉。"
WARLY.DESCRIBE.KYNO_FENNEL_OVERSIZED = "可以做成美味的沙拉。"
WARLY.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "噢 不。"

WARLY.DESCRIBE.KYNO_SWEETPOTATO = "淀粉从来没有这么甜过。"
WARLY.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "可以用点咖喱和法式奶油……"
WARLY.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "淀粉从来没有这么甜过。"
WARLY.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "未来的原料，正等待种植！"
WARLY.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "未来的原料，正等待种植！"
WARLY.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "淀粉从来没有这么甜过。"
WARLY.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "淀粉从来没有这么甜过。"
WARLY.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "噢 不。"

WARLY.DESCRIBE.KYNO_PARZNIP = "新鲜产品！"
WARLY.DESCRIBE.KYNO_PARZNIP_COOKED = "新鲜产品！"
WARLY.DESCRIBE.KYNO_PARZNIP_EATEN = "新鲜产品！"
WARLY.DESCRIBE.KYNO_PARZNIP_GROUND = "新鲜产品！"
WARLY.DESCRIBE.KYNO_PARZNIP_BIG = "天哪！我要烤一个巨大的欧洲防风草？！"
WARLY.DESCRIBE.KYNO_PARZNIP_SEEDS = "未来的原料，正等待种植！"
WARLY.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "未来的原料，正等待种植！"
WARLY.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "新鲜产品！"
WARLY.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "新鲜产品！"
WARLY.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "噢 不。"

WARLY.DESCRIBE.KYNO_TURNIP = "经典。"
WARLY.DESCRIBE.KYNO_TURNIP_COOKED = "闻起来很香！"
WARLY.DESCRIBE.KYNO_TURNIP_GROUND = "经典之作。"
WARLY.DESCRIBE.KYNO_TURNIP_SEEDS = "未来的原料，正等待种植！"
WARLY.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "未来的原料，正等待种植！"
WARLY.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "经典之作。"
WARLY.DESCRIBE.KYNO_TURNIP_OVERSIZED = "经典之作。"
WARLY.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "噢 不。"

WARLY.DESCRIBE.KYNO_RICE = "啊！太多可能性了。"
WARLY.DESCRIBE.KYNO_RICE_COOKED = "啊！太多可能性了。"
WARLY.DESCRIBE.KYNO_RICE_SEEDS = "未来的原料，等待种植！"
WARLY.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "未来的原料，等待种植！"
WARLY.DESCRIBE.FARM_PLANT_KYNO_RICE = "经典。"
WARLY.DESCRIBE.KYNO_RICE_OVERSIZED = "经典。"
WARLY.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "噢 不。"

WARLY.DESCRIBE.KYNO_SEEDS_KIT = "烹饪食材的初始阶段。"

WARLY.DESCRIBE.KYNO_LIMPETROCK = "一个小蜗牛农场！"
WARLY.DESCRIBE.KYNO_LIMPETS = "它们散发着咸味。"
WARLY.DESCRIBE.KYNO_LIMPETS_COOKED = "光滑、咸味、美味。"

WARLY.DESCRIBE.KYNO_LOTUS_OCEAN = "嗯，莲藕……"
WARLY.DESCRIBE.KYNO_LOTUS_ROOT = "我能种植它，作为可持续的莲花来源。"
WARLY.DESCRIBE.KYNO_LOTUS_FLOWER = "我应该用这个做点什么。"
WARLY.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "美味佳肴！"

WARLY.DESCRIBE.KYNO_SEAWEEDS_OCEAN = "我对这种成分没有太多经验。"
WARLY.DESCRIBE.KYNO_SEAWEEDS = "我对这种成分没有太多经验。"
WARLY.DESCRIBE.KYNO_SEAWEEDS_COOKED = "可以用烤芝麻……"
WARLY.DESCRIBE.KYNO_SEAWEEDS_DRIED = "可以使用 Tamari..."
WARLY.DESCRIBE.KYNO_SEAWEEDS_ROOT = "我可以种植它作为海藻的可持续来源。"

WARLY.DESCRIBE.KYNO_TAROROOT_OCEAN = "嗯……这和鱼很相配！"
WARLY.DESCRIBE.KYNO_TAROROOT_ROOT = "我能种植它作为可持续的芋头根源。"
WARLY.DESCRIBE.KYNO_TAROROOT = "茄子！"
WARLY.DESCRIBE.KYNO_TAROROOT_COOKED = "可以用辣椒酱和帕尔马干酪......"

WARLY.DESCRIBE.KYNO_WATERYCRESS_OCEAN = "那会是一份很棒的沙拉！"
WARLY.DESCRIBE.KYNO_WATERYCRESS_ROOT = "我可以种上它，作为西洋菜的可持续来源。"
WARLY.DESCRIBE.KYNO_WATERYCRESS = "那会是一份很棒的沙拉！"

WARLY.DESCRIBE.WATERYCRESSBOWL = "啊，一道特别的菜。"

WARLY.DESCRIBE.KYNO_SALT = "机会难得！我找到了盐！"

WARLY.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "贻贝的强度不足以抵抗这根棍子！"

WARLY.DESCRIBE.CATFOOD = "猫的美食。"

WARLY.DESCRIBE.KATFOOD = "猫的美食。"

WARLY.DESCRIBE.KYNO_BANANATREE = "猴子爬不上来，哈！"
WARLY.DESCRIBE.KYNO_BANANA = "正是我需要的味道！"
WARLY.DESCRIBE.KYNO_BANANA_COOKED = "可以用一些燕麦和一些巧克力片..."

WARLY.DESCRIBE.KYNO_KOKONUTTREE = "一棵好倾斜的树。"
WARLY.DESCRIBE.KYNO_KOKONUT = "它的包装很难打开。"
WARLY.DESCRIBE.KYNO_KOKONUT_HALVED = "美味。"
WARLY.DESCRIBE.KYNO_KOKONUT_COOKED = "可以用米饭和咖喱香料..."

WARLY.DESCRIBE.BOWLOFPOPCORN = "可以用味噌和猪油..."

WARLY.DESCRIBE.FIGJUICE = "啊。令人耳目一新。"

WARLY.DESCRIBE.COCONUTWATER = "啊。令人耳目一新。"

WARLY.DESCRIBE.EYEBALLSPAGHETTI = "这不是食物！"

WARLY.DESCRIBE.FORGETMELOTS_SEEDS = "未来的原料，正等待种植！"

WARLY.DESCRIBE.FIRENETTLES_SEEDS = "未来的成分，正等待种植！"

WARLY.DESCRIBE.TILLWEED_SEEDS = "未来的原料，正等待种植！"

WARLY.DESCRIBE.KYNO_FLOATILIZER = "我的花园酱！"

WARLY.DESCRIBE.KYNO_TWIGGYNUTS = "我可以用这些做点什么。"

WARLY.DESCRIBE.KYNO_REPAIRTOOL = "一个最明智的旅行伴侣"

WARLY.DESCRIBE.KYNO_KOI = "它的鳞片有如此可爱的光泽。"
WARLY.DESCRIBE.KYNO_KOI_COOKED = "它的鳞片有如此可爱的光泽。"

WARLY.DESCRIBE.KYNO_TROPICALFISH = "今天的渔获！"
WARLY.DESCRIBE.KYNO_TROPICALFISH_COOKED = "这样就行了。"

WARLY.DESCRIBE.KYNO_NEONFISH = "你喜欢被烧焦还是被炸裂？"
WARLY.DESCRIBE.KYNO_NEONFISH_COOKED = "叹气。它甚至没有经过调味。"

WARLY.DESCRIBE.KYNO_GROUPER = "再新鲜不过了！"
WARLY.DESCRIBE.KYNO_GROUPER_COOKED = "木豆煎石斑鱼！好吃！"
 
WARLY.DESCRIBE.KYNO_PIERROTFISH = "你想成为一个美味的杂烩吗？"
WARLY.DESCRIBE.KYNO_PIERROTFISH_COOKED = "啊，我应该把头留给汤喝！"

WARLY.DESCRIBE.KYNO_SALMONFISH = "嗯，新鲜鲑鱼。"
WARLY.DESCRIBE.KYNO_SALMONFISH_COOKED = "完美！"

WARLY.DESCRIBE.TURF_PINKPARK = "像棒棒糖一样的粉红色。"
WARLY.DESCRIBE.TURF_STONECITY = "它就像是地面的一种成分。"
WARLY.DESCRIBE.TURF_FIELDS = "它就像是地面的一种成分。"
WARLY.DESCRIBE.TURF_TIDALMARSH = "它就像是地面的一种成分。"

WARLY.DESCRIBE.KYNO_SALTRACK_INSTALLER = "从池塘里收集盐分。"

WARLY.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "用来收集树上糖果的桶。"

WARLY.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "是时候抓一些好螃蟹了！"

WARLY.DESCRIBE.KYNO_SERENITYISLAND_SHOP = "你有什么要给我的？"

WARLY.DESCRIBE.KYNO_SUGARTREE_BUD = "树比我的食谱更有用。"

WARLY.DESCRIBE.KYNO_SUGARTREE_FLOWER = "Charmant。我想知道我是否可以在我的食谱中使用它。"
WARLY.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "我想知道我是否可以在我的食谱中使用它。"

WARLY.DESCRIBE.KYNO_SUGARTREE_PETALS = "Charmant。我想知道我是否可以在我的食谱中使用它。"

WARLY.DESCRIBE.KYNO_PEBBLECRAB = "美味的螃蟹适合我的菜肴！"

WARLY.DESCRIBE.KYNO_CRABMEAT = "啊！上好的海肉！"
WARLY.DESCRIBE.KYNO_CRABMEAT_COOKED = "完美美味！"
WARLY.DESCRIBE.KYNO_CRABMEAT_DRIED = "啊！上好的海鲜！"

WARLY.DESCRIBE.KYNO_CRABKINGMEAT = "啊！上好的海鲜！"
WARLY.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "啊！海鲜！"
WARLY.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "啊！海鲜！"

WARLY.DESCRIBE.KYNO_SLAUGHTERTOOL = "最好的屠宰工具。"

WARLY.DESCRIBE.KYNO_CHICKEN2 = "我美味可口的朋友！"

WARLY.DESCRIBE.KYNO_CHICKEN_EGG = "大自然使食物变得完美。"
WARLY.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "可以使用几种不同的草药......"

WARLY.DESCRIBE.KYNO_CHICKENHOUSE = "啊！新鲜食材的可靠来源。"

WARLY.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "我见过更糟糕的厨房。"

WARLY.DESCRIBE.KYNO_COOKWARE_KIT = "啊！正是我准备好菜所需要的！"
WARLY.DESCRIBE.KYNO_COOKWARE_SYRUP = "用于制作美食。"
WARLY.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "制作好吃的东西。"
WARLY.DESCRIBE.KYNO_COOKWARE_BIG_POT = "一个大型锅具！我可以用它来做更好的菜！"
WARLY.DESCRIBE.KYNO_COOKWARE_BIG = "一个大型锅具！我可以用它来做更好的菜！"
WARLY.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "啊，精致的锅！正是我需要的！"
WARLY.DESCRIBE.KYNO_COOKWARE_SMALL = "啊，精致的锅！正是我需要的！"
WARLY.DESCRIBE.KYNO_COOKWARE_GRILL = "烧烤时间到了！"
WARLY.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "我需要尽快建造这个！"
WARLY.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "烧烤时间到了！"
WARLY.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "我需要尽快建造它！"
WARLY.DESCRIBE.KYNO_COOKWARE_ELDER = "制作好吃的东西。"
WARLY.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "完美的烘焙场所。"
WARLY.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "现在我只需要烤箱。"
WARLY.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "其实可以用些更大的。"
WARLY.DESCRIBE.KYNO_COOKWARE_OVEN = "啊，完美！"
WARLY.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "啊，完美！"
WARLY.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "啊，完美！"

WARLY.DESCRIBE.KYNO_ROCKFLIPPABLE = "下面可能有一些蛋白质。"
WARLY.DESCRIBE.KYNO_ROCKFLIPPABLE_CAVE = "下面可能有一些蛋白质。"

WARLY.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "让我们打开她。"

WARLY.DESCRIBE.KYNO_SUGARFLY = "你的空中舞姿令人心旷神怡……"
WARLY.DESCRIBE.KYNO_SUGARFLYWINGS = "我想知道我能用这些做些什么菜？"

WARLY.DESCRIBE.KYNO_WATERY_CRATE = "让我们打开她。"

WARLY.DESCRIBE.KYNO_TUNACAN = "金枪鱼，装在罐子里！"
WARLY.DESCRIBE.KYNO_TUNACAN_OPEN = "金枪鱼，装在罐子里！"

WARLY.DESCRIBE.KYNO_CANNEDFOOD = "食物，用油包装！"
WARLY.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "食物，用油包装！"

WARLY.DESCRIBE.KYNO_POP = "我更喜欢柠檬水...带一块粗布。"

WARLY.DESCRIBE.KYNO_MYSTERYMEAT = "那不可能是可食用的。"

WARLY.DESCRIBE.KYNO_BOTTLE_SOUL = "我不喜欢这里的发展方向。"

WARLY.DESCRIBE.SOULSTEW = "我不喜欢这里的发展方向。"

WARLY.DESCRIBE.FORTUNECOOKIE = "一个模糊的预言。"

WARLY.DESCRIBE.HORNOCUPIA = "人可以做梦。"

WARLY.DESCRIBE.CHEESE_YELLOW = "现在开始说话了！"
WARLY.DESCRIBE.CHEESE_WHITE = "完美。"
WARLY.DESCRIBE.CHEESE_KOALEFANT = "现在开始说话了！"

WARLY.DESCRIBE.MILK_BOX = "我可以用这个做其他饭菜，除了喝它。"

WARLY.DESCRIBE.WATERCUP = "煮冰。"

WARLY.DESCRIBE.HONEYJAR = "迫不及待想尝尝！"

WARLY.DESCRIBE.CRAB_ARTICHOKE = "啊！如此精致的一餐。"

WARLY.DESCRIBE.PEPPERROLLS = "我喜欢辣的菜！"

WARLY.DESCRIBE.KYNO_SAPHEALER = "可以派上用场。"

WARLY.DESCRIBE.KYNO_OCEAN_WRECK = "它不再航行了。"

WARLY.DESCRIBE.KYNO_GHOST_PIRATE = "他或许是个好人，但我没打算去了解。"

WARLY.DESCRIBE.KYNO_BUCKET_EMPTY = "这将帮助我。"
WARLY.DESCRIBE.KYNO_BUCKET_METAL = "我用其中一个给山羊挤奶。"
WARLY.DESCRIBE.KYNO_BUCKET_WATER = "淡水！"

WARLY.DESCRIBE.KYNO_MILK_BEEFALO = "我可以把它做成奶酪吗？"
WARLY.DESCRIBE.KYNO_MILK_KOALEFANT = "我可以把它做成奶酪吗？"

WARLY.DESCRIBE.KYNO_CAP_DRIED = "啊！上好的干蘑菇，非常适合我的新菜肴创意。"

WARLY.DESCRIBE.KYNO_PLANTMEAT_DRIED = "可以使用墨西哥辣椒..."

WARLY.DESCRIBE.KYNO_BREWBOOK = "啊，精美的葡萄酒目录。"

WARLY.DESCRIBE.KYNO_WOODENKEG = "迫不及待地想酿造一些淡啤酒！"

WARLY.DESCRIBE.KYNO_PRESERVESJAR = "我无法决定我应该先冲什么！"

WARLY.DESCRIBE.KYNO_ANTCHEST = "蜂蜜制造商！"

WARLY.DESCRIBE.KYNO_NECTAR_POD = "蜂蜜制作原料。"

WARLY.DESCRIBE.KYNO_OAKTREE_POD = "一颗树种子。"
WARLY.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "不是最好的食物。"

WARLY.DESCRIBE.KYNO_PIKO = "你好，朋友。"
WARLY.DESCRIBE.KYNO_PIKO_ORANGE = "我更喜欢英式早餐。"

WARLY.DESCRIBE.KYNO_MEADOWISLAND_TREE = "我可以用茶树叶做很多事情。"
WARLY.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = "我可以用茶树叶做很多事情。"
WARLY.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "我希望口粮在里面。"
WARLY.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = "这里住着渔民。我能闻到。"
WARLY.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = "渔民住在这里。我能闻到它。"
WARLY.DESCRIBE.KYNO_MEADOWISLAND_SHOP = "里面肯定有很多食材。"
WARLY.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = "也许我应该看看他的商品。"
WARLY.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "他看起来很体面，可以当交易员。"
WARLY.DESCRIBE.KYNO_MEADOWISLAND_POND = "它会困住零食。"
WARLY.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "我想知道它是否可以食用。"
WARLY.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "沙子形成了一小堆。"
WARLY.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "你带来了大海。"

WARLY.DESCRIBE.KYNO_SAMMYHAT = "还稍微有点。"

WARLY.DESCRIBE.KINGFISHER = "喙非常适合用来刺食。"

WARLY.DESCRIBE.TOUCAN = "你全身都是鼻子。"
WARLY.DESCRIBE.TOUCAN_CHUBBY = "你全身都是鼻子。"

WARLY.DESCRIBE.WETGOOP2 = "我很庆幸我的副厨师长没有在场目睹这种可憎的事......"

WARLY.DESCRIBE.BEER = "提神！"

WARLY.DESCRIBE.PALEALE = "清爽！"

WARLY.DESCRIBE.TEAGREEN = "啊...我感觉放松。"

WARLY.DESCRIBE.TEARED = "啊...我感觉放松了。"

WARLY.DESCRIBE.MEAD = "啊！我总是欢迎一些蜂蜜酒。"

WARLY.DESCRIBE.KYNO_JELLY = "简单、甜蜜、冻糕。"

WARLY.DESCRIBE.KYNO_MAYONNAISE = "想知道我是否可以将它们用作鞑靼酱的基础......"

WARLY.DESCRIBE.TARTARSAUCE = "辣到极致！"

WARLY.DESCRIBE.KYNO_PICKLES = "腌制至完美。"

WARLY.DESCRIBE.KYNO_WINE = "啊！精美的饮酒艺术。"

WARLY.DESCRIBE.KYNO_JUICE = "提神！"

WARLY.DESCRIBE.KYNO_POISON_FROGLEGS = "食用它不安全！"
WARLY.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "我觉得它仍然不能安全食用。"

WARLY.DESCRIBE.POISONFROGGLEBUNWICH = "啊，异国情调的法国美食。"

WARLY.DESCRIBE.KYNO_BREWINGRECIPECARD = "啊，不！我不知道食谱！"

WARLY.DESCRIBE.KYNO_OIL = "这不是我能拥有的最好的油，但它会起作用。"

WARLY.DESCRIBE.BERRYSUNDAE = "暖暖的！"

WARLY.DESCRIBE.CHOCOLATE_BLACK = "没有什么比巧克力更甜的了。"
WARLY.DESCRIBE.CHOCOLATE_WHITE = "没有什么比巧克力更甜的了。"

WARLY.DESCRIBE.TRICOLORDANGO = "我应该经常尝试日本料理......"
 
WARLY.DESCRIBE.FRIESFRENCH = "盐使它变得更好！"

WARLY.DESCRIBE.PIRATERUM = "朗姆酒，海盗们喝的。"

WARLY.DESCRIBE.TWISTEDTEQUILA = "我只需要一片柠檬就可以让它变得完美！"

WARLY.DESCRIBE.ONIONRINGS = "完美的油洋葱。"

WARLY.DESCRIBE.DONUTS = "啊，美妙！来一些甜甜圈来开始新的一天。"
WARLY.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "啊，太美妙了！来点甜甜圈来开始新的一天。"
WARLY.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "啊，精彩的！来点甜甜圈来开始新的一天。"
 
WARLY.DESCRIBE.CINNAMONROLL = "烘焙食品！温暖的肉桂和糖的催眠漩涡。"

WARLY.DESCRIBE.GUMMYBEARGERS = "用动物形状制作糖果是一门艺术！"

WARLY.DESCRIBE.PRETZEL = "很棒的椒盐卷饼！"

WARLY.DESCRIBE.CORNINCUP = "一杯甜甜的玉米。"

WARLY.DESCRIBE.COTTONCANDY = "我喜欢看到孩子们吃我做的东西时脸上的笑容。"

WARLY.DESCRIBE.ROASTEDHAZELNUTS = "简单易学的小吃！"

WARLY.DESCRIBE.MONSTERMUFFIN = "我做错了什么？"

WARLY.DESCRIBE.PINKCAKE = "今天对某个人来说是个特别的日子！"

WARLY.DESCRIBE.CHIPSBAG = "现在只是缺少一些好的浸泡。"

WARLY.DESCRIBE.LITTLEBREAD = "这个！我可以用它做很多菜！"

WARLY.DESCRIBE.HOTHOUND = "非常好！经典的美式食物。"

WARLY.DESCRIBE.MILKSHAKE = "我更喜欢冻糕。"
WARLY.DESCRIBE.MILKSHAKE_PRISMATIC = "我更喜欢冻糕。"

WARLY.DESCRIBE.NACHOS = "我喜欢墨西哥菜啊！"

WARLY.DESCRIBE.BANANA_PUDDING = "我喜欢做布丁！"

WARLY.DESCRIBE.SEA_PUDDING = "我喜欢做布丁！"

WARLY.DESCRIBE.TOM_KHA_SOUP = "我喜欢烹饪新美食"

WARLY.DESCRIBE.MINERTREAT = "一根煮熟的棒棒糖。"

WARLY.DESCRIBE.RADISHSALAD = "食用艺术！"

WARLY.DESCRIBE.PUMPKIN_SOUP = "太神圣了！"

WARLY.DESCRIBE.ALGAE_SOUP = "太神圣了！"

WARLY.DESCRIBE.PARZNIP_SOUP = "太神圣了！"

WARLY.DESCRIBE.NETTLEMEATED = "药用叶子，带有一些添加的味道。"

WARLY.DESCRIBE.KYNO_SUGAR = "诸神的粉末！"

WARLY.DESCRIBE.KYNO_BOTTLECAP = "我不需要瓶盖。"

WARLY.DESCRIBE.NUKACOLA = "不安全的饮料。"
WARLY.DESCRIBE.NUKACOLA_QUANTUM = "不安全的饮料。"

WARLY.DESCRIBE.LIVINGSANDWICH = "食用不安全！"

WARLY.DESCRIBE.DURIANSPLIT = "炎热的天气终于结束了！"

WARLY.DESCRIBE.DURIANSOUP = "对珍贵的食谱略有不同。"

WARLY.DESCRIBE.DURIANMEATED = "那种气味……"

WARLY.DESCRIBE.DURIANCHICKEN = "火鸡的再现。"

WARLY.DESCRIBE.LUNARSOUP = "我以前怎么没有想到这一点？"

WARLY.DESCRIBE.PURPLEWOBSTERSOUP = "每次尝试都会改进我的汤。"

WARLY.DESCRIBE.WOBSTERMONSTER = "我更喜欢普通的龙虾。"

WARLY.DESCRIBE.SPIDERCAKE = "威尔逊不应该再做饭了！"

WARLY.DESCRIBE.SUGARBOMBS = "我更喜欢其他类型的麦片。"

WARLY.DESCRIBE.BERRYBOMBS = "一个简单的冻糕。"

WARLY.DESCRIBE.ONIGIRIS = "啊！很好的日式料理！"

WARLY.DESCRIBE.OMURICE = "啊！很好的日式料理！"

WARLY.DESCRIBE.PAELLA = "一道精美的瓦伦西亚菜肴。"

WARLY.DESCRIBE.RISOTTO = "蒙瑟-拉姆齐会同意这种美味的。"

WARLY.DESCRIBE.RICESAKE = "啊！米饭的适度用途。非常适合小型团聚。"

WARLY.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "一种热带美食。"
WARLY.DESCRIBE.KYNO_PINEAPPLEBUSH = "一种热带美食。"

WARLY.DESCRIBE.KYNO_PINEAPPLE = "它的包装很难打开。"
WARLY.DESCRIBE.KYNO_PINEAPPLE_HALVED = "很好的菠萝！"
WARLY.DESCRIBE.KYNO_PINEAPPLE_COOKED = "我们需要用它制作更多的菜肴！"

WARLY.DESCRIBE.PIZZA_TROPICAL = "创造新的组合总是不错的！"

WARLY.DESCRIBE.PINACOLADA = "神清气爽。"

WARLY.DESCRIBE.CHIMAS = "完美的马黛茶！"

WARLY.DESCRIBE.KYNO_GARDEN_SPRINKLER = "它给植物浇水。"

WARLY.DESCRIBE.KYNO_FOODSACK = "越湿越好。"

WARLY.DESCRIBE.GUMMYWORMS = "这糖有点不对劲。"

WARLY.DESCRIBE.SMORES = "小孩子的最爱。"

WARLY.DESCRIBE.NUKASHINE = "不是来自这个世界。"

WARLY.DESCRIBE.ANTSLOG = "不是我喜欢的美食类型。"

WARLY.DESCRIBE.KYNO_WORM_BONE = "骨头总能做出美味的肉汤。"

WARLY.DESCRIBE.SPOOKY_BRAIN_NOODLES = "幽灵烹饪真的让我害怕！"
WARLY.DESCRIBE.SPOOKY_BURGERZILLA = "我想知道它是否比普通馒头更好吃。"
WARLY.DESCRIBE.SPOOKY_DEADBREAD = "当我说\"有一道改变生活的菜\"时，我并不是指这个..."
WARLY.DESCRIBE.SPOOKY_JELLYBEANS = "我敢肯定，孩子们会喜欢这个的！"
WARLY.DESCRIBE.SPOOKY_POPSICLE = "这种冰棒绝对是一种体验。"
WARLY.DESCRIBE.SPOOKY_PUMPKINCREAM = "至少还能吃。"
WARLY.DESCRIBE.SPOOKY_SKULLCANDY = "的确。是一种特殊的糖果。"
WARLY.DESCRIBE.SPOOKY_TACODILE = "一个很好的创作。"

WARLY.DESCRIBE.BUTTER_BEEFALO = "一种与许多菜肴搭配得很好的配料。"
WARLY.DESCRIBE.BUTTER_GOAT = "一种与许多菜肴搭配得很好的配料。"
WARLY.DESCRIBE.BUTTER_KOALEFANT = "一种与许多菜肴搭配得很好的配料。"

WARLY.DESCRIBE.SPICE_CURE = "我的这种香料，会让任何食物持续更长时间，并提高其质量！"
WARLY.DESCRIBE.SPICE_COLD = "对于夏天或我的敌人来说，这是一个很好的解脱！"
WARLY.DESCRIBE.SPICE_FIRE = "凝聚的火焰让一切触手可及！"
WARLY.DESCRIBE.SPICE_FED = "燃烧的卡路里越多，工作的时间就越多。"
WARLY.DESCRIBE.SPICE_MIND = "这应该能让每个人都玩得开心。"

WARLY.DESCRIBE.SUGARFLYMUFFIN = "太棒了！"

WARLY.DESCRIBE.EELTACOS = "把我带到边境以南！"

WARLY.DESCRIBE.MEATSKILLET = "太棒了！"

WARLY.DESCRIBE.MEATWALTZ = "哦，天哪，它需要更多的烹饪时间。"

WARLY.DESCRIBE.COMPLETEBREAKFAST = "希望这能满足他无止尽的食欲。"

WARLY.DESCRIBE.DUMPLINGS = "一包简单的饺子，带着爱。"

WARLY.DESCRIBE.WARLYICEDTEA = "啊，令人耳目一新。就像您以前的笑容一样......"

WARLY.DESCRIBE.WARLYTEA = "我非常想念您。"

WARLY.DESCRIBE.KYNO_TEALEAF = "来自伦敦的鲜嫩叶子。"

WARLY.DESCRIBE.KYNO_ITEMSLICER = "一把适合厨师的刀！"
WARLY.DESCRIBE.KYNO_ITEMSLICER_GOLD = "我早就想搞把专业切肉刀了！"

WARLY.DESCRIBE.COXINHA = "一种简单的鸡肉点心。"

WARLY.DESCRIBE.LAZYDESSERT = "我不明白。"

WARLY.DESCRIBE.CRABKINGFEAST = "漱口。"

WARLY.DESCRIBE.PIENAPPLE = "这是不是更像是一个挞？"

WARLY.DESCRIBE.JAWSBREAKER = "用牙齿咬开太难了。"

WARLY.DESCRIBE.AVOCADOTOAST = "我不相信能说出一个更好的组合。"

WARLY.DESCRIBE.RICEPUDDING = "米饭加牛奶！"

WARLY.DESCRIBE.SHARKSUSHI = "做这个真是个好主意。"

WARLY.DESCRIBE.WOBSTERBREADED = "完美的主菜！"

WARLY.DESCRIBE.LAZYPURRITO = "一种特殊的卷饼。"

WARLY.DESCRIBE.HORCHATA = "我总是喜欢扩大我的饮料种类。"

WARLY.DESCRIBE.WOBSTERCOCKTAIL = "一杯精致的酒饮。"

WARLY.DESCRIBE.LAVAEEGGBOILED = "别担心，它不会烫到你的舌头。"

WARLY.DESCRIBE.POMEGRANATETEA = "啊。清爽。"

WARLY.DESCRIBE.TIRAMISU = "如此精致的甜点，我的朋友！"

WARLY.DESCRIBE.TOADSTOOLCOLA = "从未想过用青蛙腿来制作饮料。"

WARLY.DESCRIBE.TEPACHE = "美洲的典型饮品。"

WARLY.DESCRIBE.LUNARTEQUILA = "疯狂引发的饮品！"

WARLY.DESCRIBE.MIMICMOSA = "看起来恶心。"

WARLY.DESCRIBE.POMEGRANATEPIE = "又一个成功的烤派。"

WARLY.DESCRIBE.PINEAPPLECAKE = "做蛋糕是一种艺术。"

WARLY.DESCRIBE.PASTY_MEAT = "下午茶点。"
WARLY.DESCRIBE.PASTY_CHEESE = "下午茶点。"

WARLY.DESCRIBE.BRIGADEIRO = "表面均匀地撒满了巧克力碎片。"

WARLY.DESCRIBE.REGULARLASAGNA = "啊！太棒了！"

WARLY.DESCRIBE.FLTSANDWICH = "如果没有培根，就用蛙腿代替吧！"

WARLY.DESCRIBE.RICEANDBEANS = "一道简单的午餐主菜。"

WARLY.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "嗯……闻起来充满潜力。2026年我会回来尝一尝。"

WARLY.DESCRIBE.KYNO_TRUFFLES_GROUND = "啊，鲜松露的香气……真诱人！"
WARLY.DESCRIBE.KYNO_TRUFFLES = "太棒了！光是香气就让我灵感大开！"
WARLY.DESCRIBE.KYNO_TRUFFLES_COOKED = "完美！大地的香气现在可口了。"

WARLY.DESCRIBE.KYNO_ITEMSHOWCASER = "啊，太棒了！每件杰作都该被欣赏。"

WARLY.DESCRIBE.KYNO_SPORECAP = "绝对不是上好料理的食材。"
WARLY.DESCRIBE.KYNO_SPORECAP_COOKED = "稍微安全了点，但还是不行。"

WARLY.DESCRIBE.KYNO_SPORECAP_DARK = "连我都没法让它好吃。"
WARLY.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "火焰也救不了这味道。"

WARLY.DESCRIBE.KYNO_GOLDENAPPLE = "传说果然是真的……"

WARLY.DESCRIBE.TRUFFLESGRINDER = "啊，松露的香气！真正的烹饪艺术。"

WARLY.DESCRIBE.SPORECAPPIE = "危险的甜点！不适合脆弱的味蕾。"

WARLY.DESCRIBE.SPORECAP_SKEWERS = "精致的林地串。简单却美味！"

WARLY.DESCRIBE.TRUFFLEOIL = "啊，太棒了！用来轻轻淋在烤蔬菜上再合适不过。"

WARLY.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "这是建造的秘诀！"
WARLY.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "很快，新鲜的鱼就来啦，准备做我最拿手的菜肴！"
WARLY.DESCRIBE.KYNO_FISHFARMPLOT = "制作鲜鱼高汤的绝佳配置。"

WARLY.DESCRIBE.KYNO_ANTCHOVY = "嗯……又脆又咸？太奇怪了！"
WARLY.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "一桌混乱的自助餐，不是吗？"

WARLY.DESCRIBE.AGEDROE = "用贝壳盛着吃，否则味道会变差。"
WARLY.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "陈年臻品，完美醇熟。真正的珍馐！"

WARLY.DESCRIBE.KYNO_SWORDFISH_BLUE = "啊，一条忘记海水滋味的鱼的悲剧故事……"

WARLY.DESCRIBE.KYNO_JELLYFISH = "晚餐来份电水母如何？"
WARLY.DESCRIBE.KYNO_JELLYFISH_DEAD = "哦，它的小脸蛋。"
WARLY.DESCRIBE.KYNO_JELLYFISH_COOKED = "可以使用芝麻油和辣椒..."
WARLY.DESCRIBE.KYNO_JELLYFISH_DRIED = "可以加点大蒜..."

WARLY.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "我看不出有什么理由去招惹它。"
WARLY.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "没必要让它白白浪费掉。"
WARLY.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "你真的能尝到 \"彩虹\"。" 

WARLY.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "真想知道这瓶子里曾经装过什么年份的酒……"

WARLY.DESCRIBE.KYNO_OCEANTRAP = "我能把一些美味的海鲜引诱到这里来！"

WARLY.DESCRIBE.OCEANFISH_PUFFERFISH = "啊，河豚鱼……处理不当的话非常危险。"
WARLY.DESCRIBE.OCEANFISH_STURGEON = "鱼子酱的梦想由此启航，我的朋友！"

WARLY.DESCRIBE.KYNO_SWORDFISH = "一种奢华而危险的成分！"
WARLY.DESCRIBE.KYNO_SWORDFISH_DEAD = "大鱼！"

WARLY.DESCRIBE.SWORDFISHFEAST = "海洋风味与精湛技艺的微妙平衡。"

WARLY.DESCRIBE.KYNO_DOGFISH = "你会成为一块上好的里脊肉。"
WARLY.DESCRIBE.KYNO_DOGFISH_DEAD = "别担心，我的朋友。我会让你变得美味可口。"

WARLY.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "真可惜啊……"

WARLY.DESCRIBE.WOBSTER_MONKEYISLAND = "天哪，这镀层真精美！我得试试涂黄油的效果。"
WARLY.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "一顿黄金大餐！我要做点惊艳的！"
WARLY.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "煎得恰到好处！香气真是美妙极了！"

WARLY.DESCRIBE.KYNO_PUFFERMONSTER = "天哪！这道菜我可不想做！"

WARLY.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "这到底是怎么回事？"
WARLY.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "怎么一脸苦瓜脸？"
WARLY.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "我看见魔鬼了！"
WARLY.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "那可真是不少死鲸。"

WARLY.DESCRIBE.KYNO_BLUBBER = "这油脂足以喂饱饥饿的火焰！"

WARLY.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "一抹海味，完美封存。"
WARLY.DESCRIBE.KYNO_FISHMEAT_DRIED = "来自海洋的肉干——简单却令人满足。"

WARLY.DESCRIBE.MONKEYISLANDMEAL = "海洋与甜美的绝妙融合。太美妙了！"

WARLY.DESCRIBE.KYNO_BRAINROCK_LARVAE = "你好，我的小可爱。"
WARLY.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "眼下没东西。或许稍后。"
WARLY.DESCRIBE.KYNO_BRAINROCK_CORAL = "这些真的是脑组织碎片吗？"
WARLY.DESCRIBE.KYNO_BRAINROCK_ROCK = "嚼劲十足的岩石，配以精妙的饰边。"

WARLY.DESCRIBE.BRAINMETTERSOUP = "这有助于你记住许多事情。"

WARLY.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = "尽量别去想他那美味的触手……"
WARLY.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "里面有冷饮吗？"

WARLY.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = "被洗劫一空……"
WARLY.DESCRIBE.KYNO_PACKIMBAGGIMS = "你真是个大嘴巴，先生。"

WARLY.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "嗯。这简直是烘焙的全新境界。"
WARLY.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "食材的世界里，组合方式无穷无尽，值得去探索。"
WARLY.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "太棒了！正是盛大庆典的完美之选！"
WARLY.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "完美的点睛之笔！"
WARLY.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "为我的食物注入庆典精神。"
WARLY.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "一道可爱的甜点，为这个特别时刻增添甜蜜！"
WARLY.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "至少，这真是赏心悦目！"
WARLY.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = "啊，一台美味的爆米花机器。"
WARLY.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "啊，简单却令人愉悦的美味！"
WARLY.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "优雅装扮，尽显庆典风采！"
WARLY.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "太独特了！来自我们最可爱的萨米的一顶帽子！"

WARLY.DESCRIBE.KYNO_FISHREGISTRYHAT = "理解鱼类，是烹饪好它们的第一步。"