local WICKERBOTTOM = STRINGS.CHARACTERS.WICKERBOTTOM

WICKERBOTTOM.ANNOUNCE_KYNO_COFFEEBUFF_START = "它帮助我保持清醒。"
WICKERBOTTOM.ANNOUNCE_KYNO_COFFEEBUFF_END = "我会想念咖啡因的。"

WICKERBOTTOM.ANNOUNCE_KYNO_HASTEBUFF_START = "我现在看书的速度是现在的两倍。"
WICKERBOTTOM.ANNOUNCE_KYNO_HASTEBUFF_END = "希望我能用更多的“青春之手”。"

WICKERBOTTOM.ANNOUNCE_KYNO_POPBUFF_START = "（嗝！）哦，亲爱的，对不起。"
WICKERBOTTOM.ANNOUNCE_KYNO_POPBUFF_END = "下次需要适量饮酒。"

WICKERBOTTOM.ANNOUNCE_KYNO_FROGBUFF_START = "也许我现在可以毫无恐惧地靠近他们了。"
WICKERBOTTOM.ANNOUNCE_KYNO_FROGBUFF_END = "青蛙香气不见了。"

WICKERBOTTOM.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝!) 哦，亲爱的，请原谅我。"
WICKERBOTTOM.ANNOUNCE_KYNO_PIRATEBUFF_END = "下次一定要适量饮用。"

WICKERBOTTOM.ANNOUNCE_KYNO_FREEZEBUFF_START = "气温下降得很快。"
WICKERBOTTOM.ANNOUNCE_KYNO_FREEZEBUFF_END = "回到我的日常生活。"

WICKERBOTTOM.ANNOUNCE_KYNO_FIREBUFF_START = "只需要小心不要引发野火。"
WICKERBOTTOM.ANNOUNCE_KYNO_FIREBUFF_END = "回到我的日常生活。"

WICKERBOTTOM.ANNOUNCE_KYNO_FISHINGBUFF_START = "钓鱼等着你！"
WICKERBOTTOM.ANNOUNCE_KYNO_FISHINGBUFF_END = "钓鱼需要耐心，不能再加快速度了。"

WICKERBOTTOM.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "舒缓心灵。"
WICKERBOTTOM.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "回到正常思维。"

WICKERBOTTOM.ANNOUNCE_KYNO_EATERBUFF_START = "我能感觉到我的消化系统发生了变化。"
WICKERBOTTOM.ANNOUNCE_KYNO_EATERBUFF_END = "我胃里那种奇怪的感觉消失了。"

WICKERBOTTOM.ANNOUNCE_KYNO_WORMBUFF_START = "它更容易对付虫子。"
WICKERBOTTOM.ANNOUNCE_KYNO_WORMBUFF_END = "现在撤退，我们之后再来战斗。"

WICKERBOTTOM.ANNOUNCE_KYNO_CRABBUFF_START = "击败螃蟹更容易。"
WICKERBOTTOM.ANNOUNCE_KYNO_CRABBUFF_END = "现在撤退，我们之后再来战斗。"

WICKERBOTTOM.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝！) 哦，亲爱的，对不起。"
WICKERBOTTOM.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "下次需要适量饮酒。"

WICKERBOTTOM.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "我已经开悟了。"
WICKERBOTTOM.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "月亮的力量现在没了。"

WICKERBOTTOM.ANNOUNCE_KYNO_STEALTHBUFF_START = "现在我可以毫不费力地看书了。"
WICKERBOTTOM.ANNOUNCE_KYNO_STEALTHBUFF_END = "我似乎不再是隐形的。"

WICKERBOTTOM.ANNOUNCE_KYNO_FEARBUFF_START = "边缘系统典型威胁反应的暂停。"
WICKERBOTTOM.ANNOUNCE_KYNO_FEARBUFF_END = "研究到此结束。心理恐怖已经按计划卷土重来。"

WICKERBOTTOM.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "非凡！具有强大神秘力量的果实。"
WICKERBOTTOM.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "哦，魔法的效力已消退。"

WICKERBOTTOM.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "太有趣了！我的存在吸引了猪伙伴。"
WICKERBOTTOM.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "唉，我的猪伙伴们散开了。"

WICKERBOTTOM.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "太有趣了！暂时的化学抗性！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WICKERBOTTOM.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "对毒素的极佳抵抗力！真是奇妙。"
WICKERBOTTOM.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "啊，效果消散了。又得小心行事了。"

WICKERBOTTOM.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "啊，我的脑海里简直充满了各种可能性！"
WICKERBOTTOM.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "唉，人总不能永远保持干劲。"

WICKERBOTTOM.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "真是值得注意。蜂类似乎完全温顺了。"
WICKERBOTTOM.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "它们的温顺已结束。是时候小心了。"

WICKERBOTTOM.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "我的活力明显提升。"
WICKERBOTTOM.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "活力已恢复至正常水平。"

WICKERBOTTOM.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "我的胃口似乎增大了。"
WICKERBOTTOM.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "胃容量已恢复默认值。"

WICKERBOTTOM.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "我的心智能力感觉有了很大提升。"
WICKERBOTTOM.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "我的认知能力已恢复到正常水平。"

WICKERBOTTOM.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "太棒了！这些能量正在增强我的身体。"
WICKERBOTTOM.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "可惜，我的援军已经撤离了。"

WICKERBOTTOM.ANNOUNCE_KYNO_BERSERKERBUFF_START = "攻击性与脆弱性的暂时性激增。"
WICKERBOTTOM.ANNOUNCE_KYNO_BERSERKERBUFF_END = "我的身体状态似乎稳定下来了。"

WICKERBOTTOM.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "热量消耗的暂时性减少。"
WICKERBOTTOM.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "我的新陈代谢率已恢复正常。"

WICKERBOTTOM.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "这还需要其他条件。"

WICKERBOTTOM.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "不，我想他说的好像是关于龙虾的。"

WICKERBOTTOM.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "我需要等它长一段时间。"

WICKERBOTTOM.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "不能放在这里。"

WICKERBOTTOM.ANNOUNCE_KYNO_POTHANGER_FAIL = "它需要一个烹饪锅。"

WICKERBOTTOM.ANNOUNCE_KYNO_CASSEROLE_FAIL = "哦，天哪，它需要一个砂锅来烹饪食物。"

WICKERBOTTOM.ANNOUNCE_KYNO_SAPHEALER_USED = "这剂药物，证明对消除潜在威胁颇为有效。"

WICKERBOTTOM.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "迅捷而必要的终结。自然向来务实。"

WICKERBOTTOM.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "它似乎已完全耗尽。"

WICKERBOTTOM.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "啊，潮水已抹去所有痕迹。可惜。"
WICKERBOTTOM.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "降水已完全掩盖了证据。"
WICKERBOTTOM.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "啊，看来我们的猎物就在附近！"

WICKERBOTTOM.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "一项辉煌的糕点成就！"

WICKERBOTTOM.ANNOUNCE_KYNO_FISH_RESEARCHED = "真是迷人，这个物种提供了新的见解。"
WICKERBOTTOM.ANNOUNCE_KYNO_ROE_RESEARCHED = "鱼卵蕴含着非凡的生物特性。"

WICKERBOTTOM.DESCRIBE.KYNO_ROE = "这个生命周期的第一个和最后一个阶段。"
WICKERBOTTOM.DESCRIBE.KYNO_ROE_COOKED = "这个生命周期的第一个和最后一个阶段。"

WICKERBOTTOM.DESCRIBE.KYNO_SHARK_FIN = "背鳍起到水流稳定器的作用。"

WICKERBOTTOM.DESCRIBE.KYNO_BEANBUGS = "天哪！一种会走路的豆科植物！"
WICKERBOTTOM.DESCRIBE.KYNO_BEANBUGS_COOKED = "我确定这里面含有大量蛋白质。"

WICKERBOTTOM.DESCRIBE.KYNO_GUMMYBUG = "我从未见过的腹足动物。"
WICKERBOTTOM.DESCRIBE.KYNO_GUMMYBUG_COOKED = "我怀疑它是否有营养。"

WICKERBOTTOM.DESCRIBE.KYNO_WHEAT = "新鲜小麦。"
WICKERBOTTOM.DESCRIBE.KYNO_WHEAT_COOKED = "烤熟的小麦。"

WICKERBOTTOM.DESCRIBE.KYNO_FLOUR = "我可以用它做一些食物。"

WICKERBOTTOM.DESCRIBE.KYNO_SPOTSPICE = "处理完毕，可以烹饪了。"

WICKERBOTTOM.DESCRIBE.KYNO_SAP = "这棵树液含有很多葡萄糖。"
WICKERBOTTOM.DESCRIBE.KYNO_SAP_SPOILED = "我可一点都不想尝它"

WICKERBOTTOM.DESCRIBE.KYNO_SYRUP = "甜味剂。"

WICKERBOTTOM.DESCRIBE.KYNO_COFFEEBEANS = "咖啡因含量很高。"
WICKERBOTTOM.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "啊，烤肉闻起来很香。"

WICKERBOTTOM.DESCRIBE.DUG_KYNO_COFFEEBUSH = "移植应当会是有益的。"

WICKERBOTTOM.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "咖啡属植物。",
	PICKED = "它会适时再生的。",
	WITHERED = "环境条件不适宜。",
}

WICKERBOTTOM.DESCRIBE.DUG_KYNO_SPOTBUSH = "应当立即重新栽种。"

WICKERBOTTOM.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "我对这种植物不熟悉。",
	PICKED = "它会适时再生的。",
	BURNING = "如此粗心大意！",
}

WICKERBOTTOM.DESCRIBE.KYNO_SPOTSPICE_LEAF = "它通过了通用可食用性测试。"

WICKERBOTTOM.DESCRIBE.KYNO_MUSSEL = "蛤蜊。非常有营养。"
WICKERBOTTOM.DESCRIBE.KYNO_MUSSEL_COOKED = "不要吃贝壳。"

WICKERBOTTOM.DESCRIBE.KYNO_HUMANMEAT = "我想我不能对我的配料挑剔，但是......"
WICKERBOTTOM.DESCRIBE.KYNO_HUMANMEAT_COOKED = "肌红蛋白赋予它独特的颜色。"
WICKERBOTTOM.DESCRIBE.KYNO_HUMANMEAT_DRIED = "干燥的人肉。"

WICKERBOTTOM.DESCRIBE.COFFEE = "我很喜欢一杯咖啡和一本好书。"

WICKERBOTTOM.DESCRIBE.BISQUE = "正是我需要的。"

WICKERBOTTOM.DESCRIBE.JELLYOPOP = "我感觉我变年轻了"

WICKERBOTTOM.DESCRIBE.SHARKFINSOUP = "我可能干预了一个微妙的生态系统来制作这个。"

WICKERBOTTOM.DESCRIBE.TROPICALBOUILLABAISSE = "传统马赛菜的创新风味。"

WICKERBOTTOM.DESCRIBE.MUSSELBOUILLABAISE = "蛤蜊汤。"

WICKERBOTTOM.DESCRIBE.SWEETPOTATOSOUFFLE = "非常美味。"

WICKERBOTTOM.DESCRIBE.FEIJOADA = "昆虫盛宴！"

WICKERBOTTOM.DESCRIBE.GUMMY_CAKE = "相当粘稠。"

WICKERBOTTOM.DESCRIBE.HARDSHELL_TACOS = "我很确定这些不是普通的炸玉米饼壳。"

WICKERBOTTOM.DESCRIBE.ICEDTEA = "提神醒脑。"

WICKERBOTTOM.DESCRIBE.NETTLELOSANGE = "药用营养品。"

WICKERBOTTOM.DESCRIBE.SNAKEBONESOUP = "丰盛的肉汤。"

WICKERBOTTOM.DESCRIBE.STEAMEDHAMSANDWICH = "我准备好迎接难忘的午餐了。"

WICKERBOTTOM.DESCRIBE.TEA = "我还需要一本好书。"

WICKERBOTTOM.DESCRIBE.BUBBLETEA = "提神醒脑。"

WICKERBOTTOM.DESCRIBE.FRENCHONIONSOUP = "丰盛的肉汤。"

WICKERBOTTOM.DESCRIBE.SLAW = "尼斯沙拉，营养丰富！"

WICKERBOTTOM.DESCRIBE.LOTUSBOWL = "健康益处很多。"

WICKERBOTTOM.DESCRIBE.POI = "在我的烹饪书中不会出现这种食物。"

WICKERBOTTOM.DESCRIBE.JELLYBEAN_HUNGER = "糖果，用蜂蜡乳化。"
WICKERBOTTOM.DESCRIBE.JELLYBEAN_SUPER = "糖果，用蜂蜡乳化。"
WICKERBOTTOM.DESCRIBE.JELLYBEAN_SANITY = "糖果，用蜂蜡乳化。"

WICKERBOTTOM.DESCRIBE.BOWLOFGEARS = "我猜这是 WX 的发明。"

WICKERBOTTOM.DESCRIBE.LONGPIGMEAL = "无话可说。"

WICKERBOTTOM.DESCRIBE.CUCUMBERSALAD = "营养丰富！"

WICKERBOTTOM.DESCRIBE.DUG_KYNO_WILDWHEAT = "适当的培育将使其受益。"

WICKERBOTTOM.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "一簇禾本植物的茎秆。",
	PICKED = "它会自然再生的。",
	WITHERED = "土壤条件不适宜。",
	BURNING = "如此浪费宝贵的资源！",
}

WICKERBOTTOM.DESCRIBE.KYNO_MEALGRINDER = "用于机械地将我们的原料粉末化。"

WICKERBOTTOM.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "一簇野生的可食用蘑菇。",
	PICKED = "菌丝体保持完好。",
	BURNING = "如此浪费一个有价值的样本！",
}

WICKERBOTTOM.DESCRIBE.GORGE_BREAD = "我可以把它变成好东西。"
WICKERBOTTOM.DESCRIBE.GORGE_SWEET_CHIPS = "烹饪的奇迹。"
WICKERBOTTOM.DESCRIBE.GORGE_VEGETABLE_SOUP = "这应该能让你很快补充饱。"
WICKERBOTTOM.DESCRIBE.GORGE_JELLY_SANDWICH = "一点果酱，瞧！"
WICKERBOTTOM.DESCRIBE.GORGE_FISH_STEW = "完美的菜肴。"
WICKERBOTTOM.DESCRIBE.GORGE_MEAT_STEW = "不像妈妈以前做的那样，但闻起来很香！"
WICKERBOTTOM.DESCRIBE.GORGE_ONION_CAKE = "这种蛋糕也值得欣赏。"
WICKERBOTTOM.DESCRIBE.GORGE_POTATO_PANCAKES = "煎饼是早晨的第一餐。"
WICKERBOTTOM.DESCRIBE.GORGE_POTATO_SOUP = "这正是我所需要的。"
WICKERBOTTOM.DESCRIBE.GORGE_FISHBALL_SKEWERS = "粘在棍子上的手工鱼丸。"
WICKERBOTTOM.DESCRIBE.GORGE_MEAT_SKEWERS = "粘在棍子上的肉块。"
WICKERBOTTOM.DESCRIBE.GORGE_STONE_SOUP = "这正是我所需要的。"
WICKERBOTTOM.DESCRIBE.GORGE_CROQUETTE = "一道不错的入门菜。"
WICKERBOTTOM.DESCRIBE.GORGE_ROAST_VEGETABLES = "健康又有活力的菜肴。"
WICKERBOTTOM.DESCRIBE.GORGE_MEATLOAF = "一块美味的肉饼"
WICKERBOTTOM.DESCRIBE.GORGE_CARROT_SOUP = "这正是我所需要的。"
WICKERBOTTOM.DESCRIBE.GORGE_FISHPIE = "用鱼做的馅饼，虽然不是很诱人。"
WICKERBOTTOM.DESCRIBE.GORGE_FISHCHIPS = "鱼和蔬菜的经典搭配。"
WICKERBOTTOM.DESCRIBE.GORGE_MEATPIE = "我得说，这馅饼真不错。"
WICKERBOTTOM.DESCRIBE.GORGE_SLIDERS = "通常用作快餐或入口。"
WICKERBOTTOM.DESCRIBE.GORGE_JELLY_ROLL = "果酱卷。"
WICKERBOTTOM.DESCRIBE.GORGE_CARROT_CAKE = "美味的胡萝卜蛋糕，营养丰富。"
WICKERBOTTOM.DESCRIBE.GORGE_GARLICMASHED = "土豆和大蒜的混合物，非常有营养。"
WICKERBOTTOM.DESCRIBE.GORGE_GARLICBREAD = "它还能与其他菜肴搭配。"
WICKERBOTTOM.DESCRIBE.GORGE_TOMATO_SOUP = "这正是我所需要的。"
WICKERBOTTOM.DESCRIBE.GORGE_SAUSAGE = "各种肉类下脚料放在一起。"
WICKERBOTTOM.DESCRIBE.GORGE_CANDIEDFISH = "糖浆的甜味让它更加美味。"
WICKERBOTTOM.DESCRIBE.GORGE_STUFFEDMUSHROOM = "香菇与各种蔬菜混合制成馅料。"
WICKERBOTTOM.DESCRIBE.GORGE_BRUSCHETTA = "一道非常特别的意大利菜。"
WICKERBOTTOM.DESCRIBE.GORGE_HAMBURGER = "经典午餐。"
WICKERBOTTOM.DESCRIBE.GORGE_FISHBURGER = "经典午餐。"
WICKERBOTTOM.DESCRIBE.GORGE_MUSHROOMBURGER = "经典午餐。"
WICKERBOTTOM.DESCRIBE.GORGE_FISH_STEAK = "完美的菜肴。"
WICKERBOTTOM.DESCRIBE.GORGE_CURRY = "这是一道非常流行的菜肴。"
WICKERBOTTOM.DESCRIBE.GORGE_SPAGHETTI = "一堆加工过的肉。谁知道里面有什么。"
WICKERBOTTOM.DESCRIBE.GORGE_POACHEDFISH = "水煮鲑鱼。"
WICKERBOTTOM.DESCRIBE.GORGE_SHEPHERD_PIE = "羊肉馅。"
WICKERBOTTOM.DESCRIBE.GORGE_CANDY = "我不太喜欢甜食，但......绝望的时候。"
WICKERBOTTOM.DESCRIBE.GORGE_BREAD_PUDDING = "一块甜面包。"
WICKERBOTTOM.DESCRIBE.GORGE_BERRY_TART = "水果和甜点的完美组合。"
WICKERBOTTOM.DESCRIBE.GORGE_MACARONI = "风味独特的面类食品。"
WICKERBOTTOM.DESCRIBE.GORGE_BAGEL_AND_FISH = "这种鲑鱼质量上乘。"
WICKERBOTTOM.DESCRIBE.GORGE_GRILLED_CHEESE = "在一些地方，这是一种很受欢迎的早餐选择。"
WICKERBOTTOM.DESCRIBE.GORGE_CREAMMUSHROOM = "汤品爱好者的美味佳肴。"
WICKERBOTTOM.DESCRIBE.GORGE_MANICOTTI = "意大利裔美国人中的一种面食。"
WICKERBOTTOM.DESCRIBE.GORGE_CHEESEBURGER = "经典午餐。"
WICKERBOTTOM.DESCRIBE.GORGE_FETTUCCINE = "奶油做的。"
WICKERBOTTOM.DESCRIBE.GORGE_ONION_SOUP = "吃完后最好漱漱口。"
WICKERBOTTOM.DESCRIBE.GORGE_BREADED_CUTLET = "精彩。"
WICKERBOTTOM.DESCRIBE.GORGE_CREAMY_FISH = "奶油配鲑鱼，味道不错。"
WICKERBOTTOM.DESCRIBE.GORGE_PIZZA = "经典。"
WICKERBOTTOM.DESCRIBE.GORGE_POT_ROAST = "等待是值得的。"
WICKERBOTTOM.DESCRIBE.GORGE_CRAB_CAKE = "有待改进。"
WICKERBOTTOM.DESCRIBE.GORGE_STEAK_FRITES = "牛排与薯条搭配得恰到好处。"
WICKERBOTTOM.DESCRIBE.GORGE_SHOOTER_SANDWICH = "来自英格兰的经典牛排三明治。"
WICKERBOTTOM.DESCRIBE.GORGE_BACON_WRAPPED = "如果再加点鸡蛋，这就成了面糊。"
WICKERBOTTOM.DESCRIBE.GORGE_CRAB_ROLL = "美味佳肴。"
WICKERBOTTOM.DESCRIBE.GORGE_MEAT_WELLINGTON = "完美地再现了威灵顿烤肉的风味。"
WICKERBOTTOM.DESCRIBE.GORGE_CRAB_RAVIOLI = "美味佳肴。"
WICKERBOTTOM.DESCRIBE.GORGE_CARAMEL_CUBE = "糖果太多可能不好。"
WICKERBOTTOM.DESCRIBE.GORGE_SCONE = "真是难以置信的美味。"
WICKERBOTTOM.DESCRIBE.GORGE_TRIFLE = "真是难以置信的美味。"
WICKERBOTTOM.DESCRIBE.GORGE_CHEESECAKE = "啊，奶酪蛋糕。午后美餐"

WICKERBOTTOM.DESCRIBE.DUCKYOUGLERMZ = "那只是……"

WICKERBOTTOM.DESCRIBE.KYNO_ALOE = "芦荟。一种用途广泛的植物。"
WICKERBOTTOM.DESCRIBE.KYNO_ALOE_COOKED = "已知它具有泻药特性。"
WICKERBOTTOM.DESCRIBE.KYNO_ALOE_GROUND = "芦荟。一种用途广泛的植物。"
WICKERBOTTOM.DESCRIBE.KYNO_ALOE_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_ALOE = "芦荟。一种用途广泛的植物。"
WICKERBOTTOM.DESCRIBE.KYNO_ALOE_OVERSIZED = "芦荟。一种用途广泛的植物。"
WICKERBOTTOM.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "多么糟糕的结果。"

WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER = "这是一种可食用的黄瓜。"
WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER_COOKED = "那肯定没有改善纹理。"
WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER_GROUND = "这是一种可食用的黄瓜。"
WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "这是一种可食用的黄瓜。"
WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "这是一种可食用的黄瓜。"
WICKERBOTTOM.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "这是一种可食用的黄瓜。"

WICKERBOTTOM.DESCRIBE.KYNO_RADISH = "我相信属于十字花科。"
WICKERBOTTOM.DESCRIBE.KYNO_RADISH_COOKED = "对我来说有点辣。"
WICKERBOTTOM.DESCRIBE.KYNO_RADISH_GROUND = "我相信属于十字花科。"
WICKERBOTTOM.DESCRIBE.KYNO_RADISH_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_RADISH = "我想应该属于十字花科。"
WICKERBOTTOM.DESCRIBE.KYNO_RADISH_OVERSIZED = "我想应该属于十字花科。"
WICKERBOTTOM.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "多么糟糕的结果。"

WICKERBOTTOM.DESCRIBE.KYNO_FENNEL = "小茴香。"
WICKERBOTTOM.DESCRIBE.KYNO_FENNEL_COOKED = "小茴香。"
WICKERBOTTOM.DESCRIBE.KYNO_FENNEL_GROUND = "小茴香。"
WICKERBOTTOM.DESCRIBE.KYNO_FENNEL_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "茴香。"
WICKERBOTTOM.DESCRIBE.KYNO_FENNEL_OVERSIZED = "茴香。"
WICKERBOTTOM.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "多么糟糕的结果。"

WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO = "库马拉！"
WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "烤库马拉。"
WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "库马拉！"
WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "库马拉!"
WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "库马拉!"
WICKERBOTTOM.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "多么糟糕的结果。"

WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP = "欧防风，可食用，美味。"
WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_COOKED = "欧防风，可食用，美味。"
WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_EATEN = "欧防风可食用，美味。"
WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_GROUND = "欧防风可食用，美味。"
WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_BIG = "一个巨大的苜蓿，好奇。"
WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "欧防风可食用，美味。"
WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "欧防风可食用，美味。"
WICKERBOTTOM.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "多么糟糕的结果。"

WICKERBOTTOM.DESCRIBE.KYNO_TURNIP = "可食用的芸苔根。"
WICKERBOTTOM.DESCRIBE.KYNO_TURNIP_COOKED = "烤芸苔。"
WICKERBOTTOM.DESCRIBE.KYNO_TURNIP_GROUND = "可食用的芸苔根。"
WICKERBOTTOM.DESCRIBE.KYNO_TURNIP_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "可食用的芸苔根。"
WICKERBOTTOM.DESCRIBE.KYNO_TURNIP_OVERSIZED = "可食用的芸苔根。"
WICKERBOTTOM.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "多么糟糕的结果。"

WICKERBOTTOM.DESCRIBE.KYNO_RICE = "它可以与基本菜肴搭配。"
WICKERBOTTOM.DESCRIBE.KYNO_RICE_COOKED = "它可以与基本菜肴搭配。"
WICKERBOTTOM.DESCRIBE.KYNO_RICE_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "在种下之前它不能开始生长，亲爱的。"
WICKERBOTTOM.DESCRIBE.FARM_PLANT_KYNO_RICE = "禾本科的食用根。"
WICKERBOTTOM.DESCRIBE.KYNO_RICE_OVERSIZED = "禾本科的食用根。"
WICKERBOTTOM.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "多么糟糕的结果。"

WICKERBOTTOM.DESCRIBE.KYNO_SEEDS_KIT = "一包方便携带的蔬菜种子。"

WICKERBOTTOM.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "这块巨石是多种腹足类生物的家园。",
	PICKED = "它们会适时回归的。",
	WITHERED = "环境条件不宜栖居。",
}

WICKERBOTTOM.DESCRIBE.KYNO_LIMPETS = "普通髌骨。"
WICKERBOTTOM.DESCRIBE.KYNO_LIMPETS_COOKED = "熟髌骨。"

WICKERBOTTOM.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "Nelumbo nucifera（莲），相当美丽。",
	PICKED = "它会适时再生的。",
	BURNING = "这是一场植物学灾难！",
}

WICKERBOTTOM.DESCRIBE.KYNO_LOTUS_ROOT = "我一直梦想成为一名水培园艺师。"
WICKERBOTTOM.DESCRIBE.KYNO_LOTUS_FLOWER = "莲花的花朵。非常鼓舞人心。"
WICKERBOTTOM.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "健康益处很多。"

WICKERBOTTOM.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "海洋藻类。",
	PICKED = "它会适时再生的。",
	BURNING = "极不寻常，且极度浪费。",
}

WICKERBOTTOM.DESCRIBE.KYNO_SEAWEEDS = "我承认，我不是什么植物学家。"
WICKERBOTTOM.DESCRIBE.KYNO_SEAWEEDS_COOKED = "蛋白质含量很高。"
WICKERBOTTOM.DESCRIBE.KYNO_SEAWEEDS_DRIED = "我已经把藻类晒干了。"
WICKERBOTTOM.DESCRIBE.KYNO_SEAWEEDS_ROOT = "我一直想成为一名水上园艺师。"

WICKERBOTTOM.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "Colocasia esculenta（芋）！",
	PICKED = "环境会加速它的再生长。",
	BURNING = "如此浪费一种有用的植物。",
}

WICKERBOTTOM.DESCRIBE.KYNO_TAROROOT_ROOT = "我一直梦想成为一名水培园艺师。"
WICKERBOTTOM.DESCRIBE.KYNO_TAROROOT = "芋头！"
WICKERBOTTOM.DESCRIBE.KYNO_TAROROOT_COOKED = "我介绍：熟芋头。"

WICKERBOTTOM.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "Nasturtium officinale（西洋菜）！",
	PICKED = "它应该会迅速再生的。",
	BURNING = "完全可以避免。",
}

WICKERBOTTOM.DESCRIBE.KYNO_WATERYCRESS_ROOT = "我一直梦想成为一名水培园艺师。"
WICKERBOTTOM.DESCRIBE.KYNO_WATERYCRESS = "金莲花！"

WICKERBOTTOM.DESCRIBE.WATERYCRESSBOWL = "臭，但很有营养。"

WICKERBOTTOM.DESCRIBE.KYNO_SALT = "氯化钠。也称为食盐。"

WICKERBOTTOM.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "一种简单而有效的水产养殖方法。",
	PICKED = "贻贝会适时再生的。",
	BURNING = "如此浪费资源！",
}

WICKERBOTTOM.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "收获，软体动物。"

WICKERBOTTOM.DESCRIBE.CATFOOD = "猫零食。"

WICKERBOTTOM.DESCRIBE.KATFOOD = "猫零食。"

WICKERBOTTOM.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "阳光有助于果实更好地生长。",
	PICKED = "它需要时间才能再生。",
	CHOPPED = "令人遗憾的植物学价值损失。",
	BURNING = "对稀有样本如此疏忽大意！",
	BURNT = "彻底毁了。",
}

WICKERBOTTOM.DESCRIBE.KYNO_BANANA = "一种芭蕉!"
WICKERBOTTOM.DESCRIBE.KYNO_BANANA_COOKED = "好一点。"

WICKERBOTTOM.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "我想坐在它下面，读一本好书。",
	PICKED = "它需要时间才能再生。",
	CHOPPED = "浪费了一个有用的样本。",
	BURNING = "如此粗心大意！",
	BURNT = "彻底毁了。",
}

WICKERBOTTOM.DESCRIBE.KYNO_KOKONUT = "多么巨大的种子！"
WICKERBOTTOM.DESCRIBE.KYNO_KOKONUT_HALVED = "我设法撬开了它的外部防御。"
WICKERBOTTOM.DESCRIBE.KYNO_KOKONUT_COOKED = "椰子肉，很好吃。"

WICKERBOTTOM.DESCRIBE.BOWLOFPOPCORN = "爆米花！"

WICKERBOTTOM.DESCRIBE.FIGJUICE = "提神醒脑。"

WICKERBOTTOM.DESCRIBE.COCONUTWATER = "提神醒脑。"

WICKERBOTTOM.DESCRIBE.EYEBALLSPAGHETTI = "我认为这种食物不安全。"

WICKERBOTTOM.DESCRIBE.FORGETMELOTS_SEEDS = "在种下之前它不能开始生长，亲爱的。"

WICKERBOTTOM.DESCRIBE.FIRENETTLES_SEEDS = "在种下之前它不能开始生长，亲爱的。"

WICKERBOTTOM.DESCRIBE.TILLWEED_SEEDS = "在种下之前它不能开始生长，亲爱的。"

WICKERBOTTOM.DESCRIBE.KYNO_FLOATILIZER = "一桶海洋动物粪便。Punget。"

WICKERBOTTOM.DESCRIBE.KYNO_TWIGGYNUTS = "来自小树枝的坚果。"

WICKERBOTTOM.DESCRIBE.KYNO_REPAIRTOOL = "延长物品寿命"

WICKERBOTTOM.DESCRIBE.KYNO_KOI = "它似乎是鲤鱼的一个亚种。"
WICKERBOTTOM.DESCRIBE.KYNO_KOI_COOKED = "它似乎是鲤鱼的一个亚种。"

WICKERBOTTOM.DESCRIBE.KYNO_TROPICALFISH = "多姿多彩。"
WICKERBOTTOM.DESCRIBE.KYNO_TROPICALFISH_COOKED = "热带美食。"

WICKERBOTTOM.DESCRIBE.KYNO_NEONFISH = "那个颜色不错"
WICKERBOTTOM.DESCRIBE.KYNO_NEONFISH_COOKED = "鲶鱼的表亲，准备晚餐。"

WICKERBOTTOM.DESCRIBE.KYNO_GROUPER = "家族的一部分。"
WICKERBOTTOM.DESCRIBE.KYNO_GROUPER_COOKED = "吃没有准备好的鱼是不安全的。"
 
WICKERBOTTOM.DESCRIBE.KYNO_PIERROTFISH = "嗯……我似乎无法识别这个物种。"
WICKERBOTTOM.DESCRIBE.KYNO_PIERROTFISH_COOKED = "鱼是各种寄生虫的宿主，你知道的。"

WICKERBOTTOM.DESCRIBE.KYNO_SALMONFISH = "嗯！嗯！"
WICKERBOTTOM.DESCRIBE.KYNO_SALMONFISH_COOKED = "烤鳗鱼。"

WICKERBOTTOM.DESCRIBE.TURF_PINKPARK = "有点漂亮。"
WICKERBOTTOM.DESCRIBE.TURF_STONECITY = "地面。你踩在上面。"
WICKERBOTTOM.DESCRIBE.TURF_FIELDS = "地面。你踩在上面。"
WICKERBOTTOM.DESCRIBE.TURF_TIDALMARSH = "地面。你踩在上面。"

WICKERBOTTOM.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "已有足够多的盐结晶，可以收获了。",
	PICKED = "盐的沉积物应该很快就会在架子上形成。",
}

WICKERBOTTOM.DESCRIBE.KYNO_SALTRACK_INSTALLER = "我们应该把它放在钠泉旁边。"

WICKERBOTTOM.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "一个简单的砍树工具。"

WICKERBOTTOM.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "用于诱捕海洋生物。"

WICKERBOTTOM.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "他们的社会有着鲜明的社会阶级角色划分。",
	SLEEPING = "他此刻正忙着睡觉。",
}

WICKERBOTTOM.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "多么独特的颜色。我真想把它的叶子压在我的书里！",
	CHOPPED = "我至少该研究一下它的年轮。",
	SAPPED = "没理由让它闲着。",
	PICKED = "树汁采集正在进行中。",
	BURNING = "如此浪费知识！",
	BURNT = "彻底毁了。",
}

WICKERBOTTOM.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "它的内部结构受损了，但仍可恢复。",
	CHOPPED = "已无法挽救。",
	SAPPED = "毁了，但仍可采集。",
	PICKED = "昆虫被葡萄糖吸引来了。",
	BURNING = "一个不幸的必要之举。",
	BURNT = "彻底没了。",
}

WICKERBOTTOM.DESCRIBE.KYNO_SUGARTREE_BUD = "一个混有糖的花蕾。"

WICKERBOTTOM.DESCRIBE.KYNO_SUGARTREE_FLOWER = "这是一种野花，我不熟悉这个物种。"
WICKERBOTTOM.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "这是野花，我不熟悉这个物种。"

WICKERBOTTOM.DESCRIBE.KYNO_SUGARTREE_PETALS = "这是一种野花，我不熟悉这个物种。"

WICKERBOTTOM.DESCRIBE.KYNO_PEBBLECRAB = "我想更仔细地研究它的外壳。"

WICKERBOTTOM.DESCRIBE.KYNO_CRABMEAT = "未加工的肉。"
WICKERBOTTOM.DESCRIBE.KYNO_CRABMEAT_COOKED = "它不再构成沙门氏菌病的威胁。"
WICKERBOTTOM.DESCRIBE.KYNO_CRABMEAT_DRIED = "生的蟹肉"

WICKERBOTTOM.DESCRIBE.KYNO_CRABKINGMEAT = "生的蟹肉"
WICKERBOTTOM.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "烤熟帝王蟹的肉"
WICKERBOTTOM.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "生的帝王蟹的肉"

WICKERBOTTOM.DESCRIBE.KYNO_SLAUGHTERTOOL = "可怕。"

WICKERBOTTOM.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "一只野生的 Gallus gallus（家鸡）。",
	COOP = "安全居留，妥善圈养。",
}

WICKERBOTTOM.DESCRIBE.KYNO_CHICKEN_EGG = "也许它受精了。"
WICKERBOTTOM.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "一枚异常巨大的 Gallus gallus（家鸡）蛋样本。"
WICKERBOTTOM.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "要是我有一些吐司就好了。"

WICKERBOTTOM.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "一个适合驯养家禽的简易围场。",
	FULL = "产蛋周期已完成。",
	BURNT = "农业资源的惨重损失。",
}

WICKERBOTTOM.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "它已经在这里很久了。"

WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_KIT = "这个工具包可以帮助我们布置厨房。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SYRUP = "它需要树液。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "它需要树液。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_BIG_POT = "更大的锅烤沸时间更长。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_BIG = "更大的锅烤沸时间更长。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "嗯，接下来我们要做什么？"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SMALL = "嗯，接下来我们要做什么？"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_GRILL = "也许一些烧烤是为了。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "它必须在地上。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "比平常小，但可以。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "我需要把它放在某个地方才能使用它。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_ELDER = "它需要树液。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "所有部件都是建造一个功能齐全的烤箱所必需的。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "我很喜欢美味的砂锅菜。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "一个人就够了。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_OVEN = "它最适合烘焙糖果。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "它最适合烘焙糖果。"
WICKERBOTTOM.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "它最适合烘焙糖果。"

WICKERBOTTOM.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "最有趣的昆虫，往往藏在石头底下。",
	FLIPPED = "不出所料，是些小型生物体。",
}

WICKERBOTTOM.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "我想知道它在海上漂流了多久？"

WICKERBOTTOM.DESCRIBE.KYNO_SUGARFLY = "粉红色的鳞翅目昆虫。"
WICKERBOTTOM.DESCRIBE.KYNO_SUGARFLYWINGS = "捕获的糖蝴蝶的翅膀"

WICKERBOTTOM.DESCRIBE.KYNO_WATERY_CRATE = "我想知道它在海上漂流了多久？"

WICKERBOTTOM.DESCRIBE.KYNO_TUNACAN = "腌制鱼。"
WICKERBOTTOM.DESCRIBE.KYNO_TUNACAN_OPEN = "腌制鱼。"

WICKERBOTTOM.DESCRIBE.KYNO_CANNEDFOOD = "腌制食品。"
WICKERBOTTOM.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "腌制食品。"

WICKERBOTTOM.DESCRIBE.KYNO_POP = "软饮料罐。"

WICKERBOTTOM.DESCRIBE.KYNO_MYSTERYMEAT = "反刍的海洋生物。对我来说没有，谢谢。"

WICKERBOTTOM.DESCRIBE.KYNO_BOTTLE_SOUL = "某物的灵魂，被困在一个瓶子里。"

WICKERBOTTOM.DESCRIBE.SOULSTEW = "某种东西的灵魂，现在是食物。"

WICKERBOTTOM.DESCRIBE.FORTUNECOOKIE = "它应该告诉一个人的幸运。"

WICKERBOTTOM.DESCRIBE.HORNOCUPIA = "丰富的象征。"

WICKERBOTTOM.DESCRIBE.CHEESE_YELLOW = "奶酪，由动物奶制成。"
WICKERBOTTOM.DESCRIBE.CHEESE_WHITE = "白奶酪，由动物奶制成。"
WICKERBOTTOM.DESCRIBE.CHEESE_KOALEFANT = "奶酪，由无袋面包牛奶制成。"

WICKERBOTTOM.DESCRIBE.MILK_BOX = "一盒普通的牛奶，他们在工厂大规模生产。"

WICKERBOTTOM.DESCRIBE.WATERCUP = "一些水。"

WICKERBOTTOM.DESCRIBE.HONEYJAR = "蜜蜂极其出色的工作成果。"

WICKERBOTTOM.DESCRIBE.CRAB_ARTICHOKE = "一道精美的蟹肉配蔬菜。"

WICKERBOTTOM.DESCRIBE.PEPPERROLLS = "对我来说有点辣！"

WICKERBOTTOM.DESCRIBE.KYNO_SAPHEALER = "这些内容应该是最有用的解毒剂。"

WICKERBOTTOM.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "这艘船遭遇了风暴。如今，它属于大海了。",
	PICKED = "海洋生物会适时地重新在此繁衍生息。",
	BURNING = "这加速了它的劣化过程。",
}

WICKERBOTTOM.DESCRIBE.KYNO_GHOST_PIRATE = "超自然海盗活动。"

WICKERBOTTOM.DESCRIBE.KYNO_BUCKET_EMPTY = "帮助我完成日常任务的精酿桶。"
WICKERBOTTOM.DESCRIBE.KYNO_BUCKET_METAL = "一个更结实的桶来完成日常任务。"
WICKERBOTTOM.DESCRIBE.KYNO_BUCKET_WATER = "一个简单的金属容器，内装有氢氧化物。"

WICKERBOTTOM.DESCRIBE.KYNO_MILK_BEEFALO = "诱人！"
WICKERBOTTOM.DESCRIBE.KYNO_MILK_KOALEFANT = "诱人！"

WICKERBOTTOM.DESCRIBE.KYNO_CAP_DRIED = "一种蘑菇干燥，以达到更高层次的品味。"

WICKERBOTTOM.DESCRIBE.KYNO_PLANTMEAT_DRIED = "咸但令人满意。"

WICKERBOTTOM.DESCRIBE.KYNO_BREWBOOK = "酿造观察的集合。"

WICKERBOTTOM.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "一个制作饮品的完美木桶。",
	BREWING_LONG = "酿造过程刚刚开始。",
	BREWING_SHORT = "已接近完成。",
	DONE = "此酿可以饮用了。",
	BURNT = "彻底毁了。",
}

WICKERBOTTOM.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "除了泡菜和果酱，它还有很多用途。",
	BREWING_LONG = "腌制过程进展缓慢。",
	BREWING_SHORT = "已接近完成。",
	DONE = "成功保存。",
	BURNT = "令人遗憾的损失。",
}

WICKERBOTTOM.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "一个格外黏稠的蜂蜜促成者。",
	HONEY = "蜂蜜储备似乎充足。",
	NECTAR = "花蜜正在转化中。",
	BURNING = "如此浪费宝贵的资源。",
}

WICKERBOTTOM.DESCRIBE.KYNO_NECTAR_POD = "我想知道这能不能变成蜂蜜。"

WICKERBOTTOM.DESCRIBE.KYNO_OAKTREE_POD = "一棵橡树种子。它会长成一棵非常大的树。"
WICKERBOTTOM.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "我想要一杯合适的茶。"

WICKERBOTTOM.DESCRIBE.KYNO_PIKO = "一个迷人的哺乳动物绒毛球。"
WICKERBOTTOM.DESCRIBE.KYNO_PIKO_ORANGE = "一个有趣的哺乳动物绒毛球。"

WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "一株优良的 Camellia Sinensis（茶树）样本。",
	CHOPPED = "所有可用的材料均已收集完毕。",
	BURNING = "这真是太不幸了！",
	BURNT = "完全的损失。",
}

WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "它被松鼠侵扰了。",
	BURNING = "一场不幸的生态干扰。",
}

WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "里面有什么？"

WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "原始但实用的住所。",
	BURNT = "令人遗憾的栖身之所的损失。",
}

WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "一座两栖棚屋。",
	CRAFTED = "更适合居住多了。",
	BURNT = "这臭味，实在令人不悦。",
}

WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "我猜，他就是把所有存货放那儿了。",
	OCCUPIED = "店主似乎在休息。",
}

WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "一辆装满货物的推车。",
	EMPTY = "似乎缺货了。",
}

WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "看来我们又见面了，亲爱的。"
WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_POND = "潮汐池是迷人的微生态系统！"
WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "一种栖息于沼泽的根茎。"
WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "沙丘的标志性形状是由风形成的。"
WICKERBOTTOM.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "这只拥有高超的收割技巧。"

WICKERBOTTOM.DESCRIBE.KYNO_SAMMYHAT = "一顶简单而古老的帽子。"

WICKERBOTTOM.DESCRIBE.KINGFISHER = "多么可爱的小绿萝亚马逊！"

WICKERBOTTOM.DESCRIBE.TOUCAN = "一种以其鲜艳的喙而闻名的物种。"
WICKERBOTTOM.DESCRIBE.TOUCAN_CHUBBY = "一种以其鲜艳的喙而闻名的物种。"

WICKERBOTTOM.DESCRIBE.WETGOOP2 = "哦，不。不，不，不。这根本行不通。"

WICKERBOTTOM.DESCRIBE.BEER = "酒精饮料，适量饮用。"

WICKERBOTTOM.DESCRIBE.PALEALE = "酒精饮料，适量饮用。"

WICKERBOTTOM.DESCRIBE.TEAGREEN = "这就是我需要阅读的全部内容，一杯好茶。"

WICKERBOTTOM.DESCRIBE.TEARED = "这就是我需要阅读的全部内容，一杯好茶。"

WICKERBOTTOM.DESCRIBE.MEAD = "我必须适度饮酒，喝多了会不好。"

WICKERBOTTOM.DESCRIBE.KYNO_JELLY = "我想吃点吐司来放这个果酱。哦，好吧。"

WICKERBOTTOM.DESCRIBE.KYNO_MAYONNAISE = "一种由鸡蛋和第戎制成的奶油。"

WICKERBOTTOM.DESCRIBE.TARTARSAUCE = "鞑靼酱，蛋黄酱的变种。"

WICKERBOTTOM.DESCRIBE.KYNO_PICKLES = "由植物制成的泡菜。"

WICKERBOTTOM.DESCRIBE.KYNO_WINE = "我现在就想要一块奶酪。"

WICKERBOTTOM.DESCRIBE.KYNO_JUICE = "蔬菜汁。"

WICKERBOTTOM.DESCRIBE.KYNO_POISON_FROGLEGS = "丽红眼蛙没有毒，但它可能不是丽红眼蛙。"
WICKERBOTTOM.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "我不确定毒药已经离开了。"

WICKERBOTTOM.DESCRIBE.POISONFROGGLEBUNWICH = "通常不放在三明治上，但我会试一试！"

WICKERBOTTOM.DESCRIBE.KYNO_BREWINGRECIPECARD = "天哪，我似乎无法理解它。"

WICKERBOTTOM.DESCRIBE.KYNO_OIL = "一种多用途油，适合烹饪菜肴。"

WICKERBOTTOM.DESCRIBE.BERRYSUNDAE = "没有什么比一本书和一碗圣代更好的了。"

WICKERBOTTOM.DESCRIBE.CHOCOLATE_BLACK = "奇怪，里面没有可可粉。"
WICKERBOTTOM.DESCRIBE.CHOCOLATE_WHITE = "奇怪，里面没有可可粉。"

WICKERBOTTOM.DESCRIBE.TRICOLORDANGO = "一种软糯的小吃。"
 
WICKERBOTTOM.DESCRIBE.FRIESFRENCH = "一道经典的快餐菜肴。快速且有点美味。"

WICKERBOTTOM.DESCRIBE.PIRATERUM = "这是朗姆酒，但为什么我对它感到如此不安全？"

WICKERBOTTOM.DESCRIBE.TWISTEDTEQUILA = "一款经典的鸡尾酒，实际上这款鸡尾酒还掺入了其他东西。"

WICKERBOTTOM.DESCRIBE.ONIONRINGS = "浸在油中的洋葱片，非常美味的下午点心。"

WICKERBOTTOM.DESCRIBE.DONUTS = "面团食品。这是美国各地的经典食品。"
WICKERBOTTOM.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "面团食品。这是美国各地的经典食品。"
WICKERBOTTOM.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "面团食品。这是美国各地的经典食品。"
 
WICKERBOTTOM.DESCRIBE.CINNAMONROLL = "面团上撒了一层薄薄的黄油。"

WICKERBOTTOM.DESCRIBE.GUMMYBEARGERS = "小熊造型的儿童糖果。"

WICKERBOTTOM.DESCRIBE.PRETZEL = "由面团制成的烘焙糕点，通常形状为结。"

WICKERBOTTOM.DESCRIBE.CORNINCUP = "这是一种传统的墨西哥小吃。"

WICKERBOTTOM.DESCRIBE.COTTONCANDY = "儿童中常见的菜肴，在节日时会大量烹制。"

WICKERBOTTOM.DESCRIBE.ROASTEDHAZELNUTS = "精心烹制的坚果，美味的下午点心。"

WICKERBOTTOM.DESCRIBE.MONSTERMUFFIN = "我能从中感受到邪恶的气息。"

WICKERBOTTOM.DESCRIBE.PINKCAKE = "派对蛋糕，很常见。"

WICKERBOTTOM.DESCRIBE.CHIPSBAG = "油炸土豆，通常作为开胃菜或小吃。"

WICKERBOTTOM.DESCRIBE.LITTLEBREAD = "我可以把它变成好东西。"

WICKERBOTTOM.DESCRIBE.HOTHOUND = "我仍然记得到处都有卖这个的推车。"

WICKERBOTTOM.DESCRIBE.MILKSHAKE = "自助餐厅非常受欢迎的选择。"
WICKERBOTTOM.DESCRIBE.MILKSHAKE_PRISMATIC = "自助餐厅非常受欢迎的选择。"

WICKERBOTTOM.DESCRIBE.NACHOS = "用奶酪制成的蘸酱让它变得更好！"

WICKERBOTTOM.DESCRIBE.BANANA_PUDDING = "简单但美味的香蕉布丁。"

WICKERBOTTOM.DESCRIBE.SEA_PUDDING = "呃。它的味道......"

WICKERBOTTOM.DESCRIBE.TOM_KHA_SOUP = "一道经典的泰国菜。"

WICKERBOTTOM.DESCRIBE.MINERTREAT = "我可以看到我内心的孩子在要求它。"

WICKERBOTTOM.DESCRIBE.RADISHSALAD = "营养充足！"

WICKERBOTTOM.DESCRIBE.PUMPKIN_SOUP = "正是我需要的。"

WICKERBOTTOM.DESCRIBE.ALGAE_SOUP = "正是我需要的。"

WICKERBOTTOM.DESCRIBE.PARZNIP_SOUP = "正是我需要的。"

WICKERBOTTOM.DESCRIBE.NETTLEMEATED = "药用营养品，添加蛋白质。"

WICKERBOTTOM.DESCRIBE.KYNO_SUGAR = "加糖调味品。"

WICKERBOTTOM.DESCRIBE.KYNO_BOTTLECAP = "后世界末日场景的潜在货币。"

WICKERBOTTOM.DESCRIBE.NUKACOLA = "即使在世界末日，我也会喝点好喝的。"
WICKERBOTTOM.DESCRIBE.NUKACOLA_QUANTUM = "即使在世界末日，我也会喝点好喝的。"

WICKERBOTTOM.DESCRIBE.LIVINGSANDWICH = "天哪，那不适合吃。"

WICKERBOTTOM.DESCRIBE.DURIANSPLIT = "没有什么比一本书和一碗冰淇淋更好的了。"

WICKERBOTTOM.DESCRIBE.DURIANSOUP = "丰盛的肉汤。"

WICKERBOTTOM.DESCRIBE.DURIANMEATED = "这味道……"

WICKERBOTTOM.DESCRIBE.DURIANCHICKEN = "烤得多好吃啊。"

WICKERBOTTOM.DESCRIBE.LUNARSOUP = "闻起来很香。"

WICKERBOTTOM.DESCRIBE.PURPLEWOBSTERSOUP = "一道精美而奢华的汤。"

WICKERBOTTOM.DESCRIBE.WOBSTERMONSTER = "这是一种要避免的食物，亲爱的。"

WICKERBOTTOM.DESCRIBE.SPIDERCAKE = "天啊，我们已经到了哪一步了。"

WICKERBOTTOM.DESCRIBE.SUGARBOMBS = "带有炸弹图案的麦片。"

WICKERBOTTOM.DESCRIBE.BERRYBOMBS = "我现在就想吃点吐司。"

WICKERBOTTOM.DESCRIBE.ONIGIRIS = "这道菜在海外很受欢迎。"

WICKERBOTTOM.DESCRIBE.OMURICE = "在海外，这道菜很受孩子们的欢迎。"

WICKERBOTTOM.DESCRIBE.PAELLA = "一个社区的象征！一道受人瞩目的菜肴。"

WICKERBOTTOM.DESCRIBE.RISOTTO = "在一些地方，这是一种非常流行的煮饭方式。"

WICKERBOTTOM.DESCRIBE.RICESAKE = "适量饮酒。"

WICKERBOTTOM.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "得找个地方把它种下。"

WICKERBOTTOM.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "一株 Ananas comosus（菠萝）灌木。难以置信。",
	PICKED = "它需要时间才能再生。",
	WITHERED = "土壤条件不适宜。",
	BURNING = "如此浪费一种有用的植物！",
}

WICKERBOTTOM.DESCRIBE.KYNO_PINEAPPLE = "好一个带刺的菠萝！"
WICKERBOTTOM.DESCRIBE.KYNO_PINEAPPLE_HALVED = "差不多可以吃了。"
WICKERBOTTOM.DESCRIBE.KYNO_PINEAPPLE_COOKED = "烤菠萝片"

WICKERBOTTOM.DESCRIBE.PIZZA_TROPICAL = "它是一个很好的补充。"

WICKERBOTTOM.DESCRIBE.PINACOLADA = "用菠萝和椰子制成的美味饮品。"

WICKERBOTTOM.DESCRIBE.CHIMAS = "这是来自南方的经典佳酿。"

WICKERBOTTOM.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "急需的水分补给。",
	ON = "它提供着持续的水分补给。",
}

WICKERBOTTOM.DESCRIBE.KYNO_FOODSACK = "保持我的补给凉爽！"

WICKERBOTTOM.DESCRIBE.GUMMYWORMS = "一种类似蚯蚓的糖状糖果。"

WICKERBOTTOM.DESCRIBE.SMORES = "棉花糖和巧克力的混合物。"

WICKERBOTTOM.DESCRIBE.NUKASHINE = "喝奇怪的饮料时要小心。"

WICKERBOTTOM.DESCRIBE.ANTSLOG = "仿制品。"

WICKERBOTTOM.DESCRIBE.KYNO_WORM_BONE = "有趣的标本。"

WICKERBOTTOM.DESCRIBE.SPOOKY_BRAIN_NOODLES = "人脑再造，变成面条。"
WICKERBOTTOM.DESCRIBE.SPOOKY_BURGERZILLA = "它就像一个怪物。"
WICKERBOTTOM.DESCRIBE.SPOOKY_DEADBREAD = "它含有奇怪的特性。"
WICKERBOTTOM.DESCRIBE.SPOOKY_JELLYBEANS = "眼球糖果。"
WICKERBOTTOM.DESCRIBE.SPOOKY_POPSICLE = "伪装成树精的柠檬冰棒"
WICKERBOTTOM.DESCRIBE.SPOOKY_PUMPKINCREAM = "我不知道蔬菜和冰淇淋结合在一起会不会好吃。"
WICKERBOTTOM.DESCRIBE.SPOOKY_SKULLCANDY = "一种具有魔力特性的糖果。"
WICKERBOTTOM.DESCRIBE.SPOOKY_TACODILE = "牙齿锋利的墨西哥卷饼。"

WICKERBOTTOM.DESCRIBE.BUTTER_BEEFALO = "用皮弗娄牛奶制成的黄油。"
WICKERBOTTOM.DESCRIBE.BUTTER_GOAT = "用伏特山羊奶制成的黄油。"
WICKERBOTTOM.DESCRIBE.BUTTER_KOALEFANT = "考拉象奶为其增添了独特的风味。"

WICKERBOTTOM.DESCRIBE.SPICE_CURE = "食品腌制是一种非常古老和传统的技术。"
WICKERBOTTOM.DESCRIBE.SPICE_COLD = "接触后能够冻结的制冷剂粉末。"
WICKERBOTTOM.DESCRIBE.SPICE_FIRE = "接触后会燃烧的闪耀水晶。"
WICKERBOTTOM.DESCRIBE.SPICE_FED = "高热量使菜肴更具吸引力。"
WICKERBOTTOM.DESCRIBE.SPICE_MIND = "放松心情的东西。"

WICKERBOTTOM.DESCRIBE.SUGARFLYMUFFIN = "谁知道糖蛾能做出如此美味的烘焙食品？"

WICKERBOTTOM.DESCRIBE.EELTACOS = "哦，我确实喜欢在我的鳗鱼上加点香料。"

WICKERBOTTOM.DESCRIBE.MEATSKILLET = "一块完美油炸的肉和蔬菜。"

WICKERBOTTOM.DESCRIBE.MEATWALTZ = "有些人喜欢他们的肉是中嫩的。"

WICKERBOTTOM.DESCRIBE.COMPLETEBREAKFAST = "沃尔夫冈有了食欲。"

WICKERBOTTOM.DESCRIBE.DUMPLINGS = "裹在肉上的熟面团。"

WICKERBOTTOM.DESCRIBE.WARLYICEDTEA = "令人振奋。"

WICKERBOTTOM.DESCRIBE.WARLYTEA = "给我茶和一本好书。"

WICKERBOTTOM.DESCRIBE.KYNO_TEALEAF = "啊，是的。制作甜茶的叶子。"

WICKERBOTTOM.DESCRIBE.KYNO_ITEMSLICER = "用来切肉块和其他配料。"
WICKERBOTTOM.DESCRIBE.KYNO_ITEMSLICER_GOLD = "用于切大肉及各类食材"

WICKERBOTTOM.DESCRIBE.COXINHA = "这是南半球常见的小吃。"

WICKERBOTTOM.DESCRIBE.LAZYDESSERT = "看起来像焦糖，但坚硬如石。"

WICKERBOTTOM.DESCRIBE.CRABKINGFEAST = "这顿盛宴打破了锅里烹饪的物理定律。"

WICKERBOTTOM.DESCRIBE.PIENAPPLE = "用热带食材做的馅饼。"

WICKERBOTTOM.DESCRIBE.JAWSBREAKER = "这个硬糖太大了，人类无法食用。"

WICKERBOTTOM.DESCRIBE.AVOCADOTOAST = "谁能想到这有多好！"

WICKERBOTTOM.DESCRIBE.RICEPUDDING = "不是我最初的选择，但也可以。"

WICKERBOTTOM.DESCRIBE.SHARKSUSHI = "如此珍贵的食物！"

WICKERBOTTOM.DESCRIBE.WOBSTERBREADED = "它应该奏效。"

WICKERBOTTOM.DESCRIBE.LAZYPURRITO = "我真的希望这个尾巴只是个装饰。"

WICKERBOTTOM.DESCRIBE.HORCHATA = "我听说这是世界上一些地方的当地饮料。"

WICKERBOTTOM.DESCRIBE.WOBSTERCOCKTAIL = "装饰性的龙虾鸡尾酒。"

WICKERBOTTOM.DESCRIBE.LAVAEEGGBOILED = "摸起来很热。"

WICKERBOTTOM.DESCRIBE.POMEGRANATETEA = "令人振奋。"

WICKERBOTTOM.DESCRIBE.TIRAMISU = "实际上...多头训鹿不叫麋鹿，而是叫训鹿。"

WICKERBOTTOM.DESCRIBE.TOADSTOOLCOLA = "一种软饮料……采用毒蛙腿制成。"

WICKERBOTTOM.DESCRIBE.TEPACHE = "不要在短时间内摄入过多糖分。"

WICKERBOTTOM.DESCRIBE.LUNARTEQUILA = "如此强大的能量，竟蕴含于如此小巧的饮品之中。"

WICKERBOTTOM.DESCRIBE.MIMICMOSA = "我可以利用它来躲避，给自己留点时间。"

WICKERBOTTOM.DESCRIBE.POMEGRANATEPIE = "这个关于石榴的双关语让我忍俊不禁。哈哈！"

WICKERBOTTOM.DESCRIBE.PINEAPPLECAKE = "一款搭配菠萝片的蛋糕。"

WICKERBOTTOM.DESCRIBE.PASTY_MEAT = "我听说这是南美非常受欢迎的零食。"
WICKERBOTTOM.DESCRIBE.PASTY_CHEESE = "我听说这是南美非常受欢迎的零食。"

WICKERBOTTOM.DESCRIBE.BRIGADEIRO = "这是南美洲非常受欢迎的生日派对糖果。"

WICKERBOTTOM.DESCRIBE.REGULARLASAGNA = "好，现在我们可以远离那件事了。"

WICKERBOTTOM.DESCRIBE.FLTSANDWICH = "蛙腿可以作为培根的良好替代品。"

WICKERBOTTOM.DESCRIBE.RICEANDBEANS = "一顿非常健康且营养丰富的午餐。"

WICKERBOTTOM.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "它破败的状态暗示着未来的修复。我预测2026年会有动静。"

WICKERBOTTOM.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "黑松露！珍贵的地下珍馐。",
	PICKED = "需要时间才能长出更多。",
	BURNING = "不可原谅的浪费。",
}

WICKERBOTTOM.DESCRIBE.KYNO_TRUFFLES = "真正的松露，在美食界备受推崇。"
WICKERBOTTOM.DESCRIBE.KYNO_TRUFFLES_COOKED = "烹饪增强了它们独特的香气。"

WICKERBOTTOM.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "展示精致美食的恰当方式。",
	FULL = "烹饪技术的优秀范例。",
}

WICKERBOTTOM.DESCRIBE.KYNO_SPORECAP = "真菌样本，呈现出严重的枯萎状态。"
WICKERBOTTOM.DESCRIBE.KYNO_SPORECAP_COOKED = "经过加热后略有改善。"

WICKERBOTTOM.DESCRIBE.KYNO_SPORECAP_DARK = "含有极强毒性的孢子，小心处理。"
WICKERBOTTOM.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "毒素耐高温，未被破坏。"

WICKERBOTTOM.DESCRIBE.KYNO_GOLDENAPPLE = "我推测这就是一切的起源之果。"

WICKERBOTTOM.DESCRIBE.TRUFFLESGRINDER = "由地下真菌制成的精致美食。十分高雅。"

WICKERBOTTOM.DESCRIBE.SPORECAPPIE = "充满毒素的真菌点心。真是迷人！"

WICKERBOTTOM.DESCRIBE.SPORECAP_SKEWERS = "即兴制作，但营养丰富的蘑菇串。"

WICKERBOTTOM.DESCRIBE.TRUFFLEOIL = "一种由地下真菌提炼的精致烹饪材料。"

WICKERBOTTOM.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "哦，我真喜欢这个样子。"
WICKERBOTTOM.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "一个受控水产养殖环境的良好开端。"

WICKERBOTTOM.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "用于水产养殖繁殖的人工环境。",
	FUEL_HIGH = "鱼类营养充足。",
	FUEL_MED = "投喂量仍保持充足。",
	FUEL_LOW = "很快便需要补充了。",
	EMPTY = "饲料供应已耗尽。",
}

WICKERBOTTOM.DESCRIBE.KYNO_ANTCHOVY = "一只极为奇特的节肢动物-鱼类混合标本！"
WICKERBOTTOM.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "罕见的跨物种群游行为！"

WICKERBOTTOM.DESCRIBE.AGEDROE = "与鱼子酱的主要区别在于盛装的罐子。"
WICKERBOTTOM.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "珍馐——腌渍鲟鱼子。精致。"

WICKERBOTTOM.DESCRIBE.KYNO_SWORDFISH_BLUE = "长期暴露在淡水环境中似乎已削弱了它的海洋本能。"

WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH = "水母，最古老的多器官生物。"
WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_DEAD = "当心别踩到那东西。"
WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_COOKED = "我通过可控的化学反应使其可食用。"
WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_DRIED = "多么别出心裁的果酱。"

WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "我认为它以当地的生物发光为食。"
WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "一只已死亡的水母动物。"
WICKERBOTTOM.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "一只彻底煮熟的水母动物标本。"

WICKERBOTTOM.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "我确实喜欢里面有手稿的时候。"

WICKERBOTTOM.DESCRIBE.KYNO_OCEANTRAP = "将其放置在生物巢穴附近。"

WICKERBOTTOM.DESCRIBE.OCEANFISH_PUFFERFISH = "啊，河豚科。务必极其谨慎地处理。"
WICKERBOTTOM.DESCRIBE.OCEANFISH_STURGEON = "鲟科！如此古老的谱系，令人着迷！"

WICKERBOTTOM.DESCRIBE.KYNO_SWORDFISH = "别惹恼大嘴鸟！"
WICKERBOTTOM.DESCRIBE.KYNO_SWORDFISH_DEAD = "这样看起来凶相倒是不那么猖狂了。"

WICKERBOTTOM.DESCRIBE.SWORDFISHFEAST = "剑鱼肉的精致呈现。"

WICKERBOTTOM.DESCRIBE.KYNO_DOGFISH = "鱼狗。"
WICKERBOTTOM.DESCRIBE.KYNO_DOGFISH_DEAD = "真可惜。"

WICKERBOTTOM.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "那条鱼正变成生物危害。"

WICKERBOTTOM.DESCRIBE.WOBSTER_MONKEYISLAND = "啊，一只色素沉着异常的甲壳类动物。真有意思。"
WICKERBOTTOM.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "即使在死亡中，它依然是尊贵的典范。"
WICKERBOTTOM.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "一道精心烹制的甲壳类美食典范。"

WICKERBOTTOM.DESCRIBE.KYNO_PUFFERMONSTER = "一种极不稳定的河豚科标本。"

WICKERBOTTOM.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "地下藏着什么大东西。"
WICKERBOTTOM.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "我确实热爱海洋哺乳动物！"
WICKERBOTTOM.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "一头白鲸！要是能有本关于这种生物的书就好了！"
WICKERBOTTOM.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "解体开始了。"

WICKERBOTTOM.DESCRIBE.KYNO_BLUBBER = "一种富含脂质的浮力物质。"

WICKERBOTTOM.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "鱼类蛋白质的保存部分。"
WICKERBOTTOM.DESCRIBE.KYNO_FISHMEAT_DRIED = "一块保存完好的水生蛋白质。"

WICKERBOTTOM.DESCRIBE.MONKEYISLANDMEAL = "水果与海鲜的迷人组合。出人意料地能有效抵御诅咒。"

WICKERBOTTOM.DESCRIBE.KYNO_BRAINROCK_LARVAE = "海洋无脊椎动物的水螅体。"
WICKERBOTTOM.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "未来的智慧花的底座。"
WICKERBOTTOM.DESCRIBE.KYNO_BRAINROCK_CORAL = "真有创意！"

WICKERBOTTOM.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "Mussidae Brainus（脑科·脑属）。",
	PICKED = "它似乎需要休养恢复。",
}

WICKERBOTTOM.DESCRIBE.BRAINMETTERSOUP = "啊，这是经典的儿童餐。"

WICKERBOTTOM.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "他是这个生态系统的核心。",
	SLEEPING = "它似乎处于休眠状态。",
}

WICKERBOTTOM.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "看起来像是沉在海底很久了。"

WICKERBOTTOM.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "这是什么种类的鱼？",
	WAITING = "我想，它需要一些时间。",
}

WICKERBOTTOM.DESCRIBE.KYNO_PACKIMBAGGIMS = "你好啊，羽毛学徒！"

WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "我们需要更多原料才能烤制它。"
WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "进展相当顺利。"
WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "我们的蛋糕看起来惊艳极了！"
WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "装饰性与传统庆典蜡烛。"
WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "这让我想起图书馆的庆祝活动。"
WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "一种传统的庆典点心。"
WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "乳胶气球。喜庆又可生物降解……但愿如此。"

WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "一台将玉米转化为可食用膨化零食的机器。",
	FUEL_HIGH = "燃料储备充足。",
	FUEL_MED = "它还会继续运作一段时间。",
	FUEL_LOW = "很快便需要补充燃料了。",
	EMPTY = "需要重新加注燃料。",
}

WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "高温导致内部水分迅速膨胀。真神奇！"
WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "一种传统的锥形庆典配饰。"
WICKERBOTTOM.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "一款定制派对配饰。"

WICKERBOTTOM.DESCRIBE.KYNO_FISHREGISTRYHAT = "用于系统研究鱼类物种的实用头饰。"

WICKERBOTTOM.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "一个简单但有效的饲槽。",
	FUEL_HIGH = "储备充足。",
	FUEL_MED = "供应量正在减少。",
	FUEL_LOW = "很快需要补充。",
	EMPTY = "必须立即重新填满。",
	BURNT = "现在完全没法用了。",
}

WICKERBOTTOM.DESCRIBE.CHICKENNUGGETS = "一种过度加工的禽类制品。"

WICKERBOTTOM.DESCRIBE.CHICKENWINGS = "富含辣椒素的鸟类附肢。"

WICKERBOTTOM.DESCRIBE.CHICKENBURGER = "对三明治的一种现代重新诠释。"

WICKERBOTTOM.DESCRIBE.CHICKENEGGSOUP = "经典的以汤为底的恢复剂。"

WICKERBOTTOM.DESCRIBE.CHICKENEGGSTEW = "富含蛋白质的滋补炖菜。"

WICKERBOTTOM.DESCRIBE.CHICKENROTISSERIE = "一种最高效的禽类炙烤方法。"