local WILLOW = STRINGS.CHARACTERS.WILLOW

WILLOW.ANNOUNCE_KYNO_COFFEEBUFF_START = "更快的燃烧速度！"
WILLOW.ANNOUNCE_KYNO_COFFEEBUFF_END = "继续走路，无聊！"

WILLOW.ANNOUNCE_KYNO_HASTEBUFF_START = "我的工作得很快。"
WILLOW.ANNOUNCE_KYNO_HASTEBUFF_END = "啊，茫然的手！"

WILLOW.ANNOUNCE_KYNO_POPBUFF_START = "（嗝）哈，多有趣的饮料！"
WILLOW.ANNOUNCE_KYNO_POPBUFF_END = "下次我需要适量饮酒。"

WILLOW.ANNOUNCE_KYNO_FROGBUFF_START = "为什么我闻起来像青蛙？"
WILLOW.ANNOUNCE_KYNO_FROGBUFF_END = "终于！那种恶心的气味消失了！"

WILLOW.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝) 哈, 大海呼唤着火！"
WILLOW.ANNOUNCE_KYNO_PIRATEBUFF_END = "我下次得喝的适量。"

WILLOW.ANNOUNCE_KYNO_FREEZEBUFF_START = "哇！真冷！"
WILLOW.ANNOUNCE_KYNO_FREEZEBUFF_END = "终于不冷了！"

WILLOW.ANNOUNCE_KYNO_FIREBUFF_START = "火在燃烧！"
WILLOW.ANNOUNCE_KYNO_FIREBUFF_END = "噢，现在不行！我需要更多！"

WILLOW.ANNOUNCE_KYNO_FISHINGBUFF_START = "钩、线和鱼！"
WILLOW.ANNOUNCE_KYNO_FISHINGBUFF_END = "钓鱼的臭味终于消失了！"

WILLOW.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "令人放松的......"
WILLOW.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "呼。大脑恢复思考。"

WILLOW.ANNOUNCE_KYNO_EATERBUFF_START = "我的牙齿好多了！"
WILLOW.ANNOUNCE_KYNO_EATERBUFF_END = "现在吃东西感觉很了。"

WILLOW.ANNOUNCE_KYNO_WORMBUFF_START = "那些虫子不会发现什么攻击了它们！"
WILLOW.ANNOUNCE_KYNO_WORMBUFF_END = "我厌倦了和虫子战斗，我们停一下吧。"

WILLOW.ANNOUNCE_KYNO_CRABBUFF_START = "那些螃蟹不知道什么攻击了他们！"
WILLOW.ANNOUNCE_KYNO_CRABBUFF_END = "我厌倦了和螃蟹战斗，我们停一下吧。"

WILLOW.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝) 哈，青蛙的饮料真有趣！"
WILLOW.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "下次我需要适量饮酒。"

WILLOW.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "我的头脑麻木了！"
WILLOW.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "哎哟。我头晕目眩。"

WILLOW.ANNOUNCE_KYNO_STEALTHBUFF_START = "你的眼睛欺骗了你。"
WILLOW.ANNOUNCE_KYNO_STEALTHBUFF_END = "啊！我现在能被发现了。"

WILLOW.ANNOUNCE_KYNO_FEARBUFF_START = "现在唯一让我害怕的是没有火！"
WILLOW.ANNOUNCE_KYNO_FEARBUFF_END = "啊。我讨厌这种感觉。我的打火机在哪里？"

WILLOW.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "我燃烧着力量！不是字面意思！"
WILLOW.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "嘿！谁偷了我的火力？！"

WILLOW.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "呵呵，小猪们喜欢我！"
WILLOW.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "啊，小猪们……已经走了。"

WILLOW.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "嘿嘿！酸雨，来试试吧！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WILLOW.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "嘿嘿，现在毒素奈何不了我了！"
WILLOW.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "唉，没有防毒的乐子了？"

WILLOW.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "嘿，我的大脑正在燃烧！让我们让东西燃烧——呃，建造吧！"
WILLOW.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "哎呀，大脑又开始降温了。"

WILLOW.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "嘿，蜜蜂不再想戳我了！不错嘛。"
WILLOW.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "太好了，会戳人的蜜蜂回来了。"

WILLOW.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "哈！现在试试看敢不敢伤害我！"
WILLOW.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "哎呀。又变成易燃品了……"

WILLOW.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "零食空间更大了！太棒了！"
WILLOW.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "唉，又遇到食物限制了。"

WILLOW.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "嘿！那些声音变安静了！怪怪的……"
WILLOW.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "很好，那些毛骨悚然的东西又回来了。"

WILLOW.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "呵呵！现在想伤到我可就难了！"
WILLOW.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "唉，那段时光真美好。"

WILLOW.ANNOUNCE_KYNO_BERSERKERBUFF_START = "耶！把一切都烧光！"
WILLOW.ANNOUNCE_KYNO_BERSERKERBUFF_END = "啊，火这就灭了？"

WILLOW.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "嘿，我饿得没那么快了！"
WILLOW.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "呃，饥饿这么快就回来了？"

WILLOW.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "我需要在这里填点东西！"

WILLOW.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "哎呀，搞错了！"

WILLOW.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "唉，这棵笨树就不能长快点吗？"

WILLOW.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "这不适合放在这里。"

WILLOW.ANNOUNCE_KYNO_POTHANGER_FAIL = "笨蛋，这需要一个锅。"

WILLOW.ANNOUNCE_KYNO_CASSEROLE_FAIL = "它需要的是烤箱，而不是那个。"

WILLOW.ANNOUNCE_KYNO_SAPHEALER_USED = "我会帮你，但回头也会烧了你。也许吧……"

WILLOW.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "嘿。火焰和鲜血——我最爱的两样东西。"

WILLOW.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "哎呀，没什么可烧的……也没什么可偷的。"

WILLOW.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "唉！那头野兽跑掉了，我连烧死它的机会都没有！"
WILLOW.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "太棒了！没有起火也没有冒泡！"
WILLOW.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "嘿……希望它冒出来的时候能烧得旺些！"

WILLOW.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "终于！现在点燃蜡烛吧！"

WILLOW.ANNOUNCE_KYNO_FISH_RESEARCHED = "嘿，我戳了这鱼几下，终于明白了。"
WILLOW.ANNOUNCE_KYNO_ROE_RESEARCHED = "鱼卵？哼，还是学到了点东西。"

WILLOW.DESCRIBE.KYNO_ROE = "啊啊啊！太恶心了！！"
WILLOW.DESCRIBE.KYNO_ROE_COOKED = "我煮了它们，但它们还是很糟糕。"

WILLOW.DESCRIBE.KYNO_SHARK_FIN = "鱼鳍掉了。"

WILLOW.DESCRIBE.KYNO_BEANBUGS = "哎呀，这看起来不好吃。"
WILLOW.DESCRIBE.KYNO_BEANBUGS_COOKED = "还是很恶心！"

WILLOW.DESCRIBE.KYNO_GUMMYBUG = "啊！"
WILLOW.DESCRIBE.KYNO_GUMMYBUG_COOKED = "火并没有使它更可口。"

WILLOW.DESCRIBE.KYNO_WHEAT = "你到底是怎么吃这个的？"
WILLOW.DESCRIBE.KYNO_WHEAT_COOKED = "你到底是怎么吃这个的？"

WILLOW.DESCRIBE.KYNO_FLOUR = "我可以点亮它。"

WILLOW.DESCRIBE.KYNO_SPOTSPICE = "香料......真正的生活香料。"

WILLOW.DESCRIBE.KYNO_SAP = "嗯！纯糖！"
WILLOW.DESCRIBE.KYNO_SAP_SPOILED = "嗯，这很愚蠢。"

WILLOW.DESCRIBE.KYNO_SYRUP = "嗯..."

WILLOW.DESCRIBE.KYNO_COFFEEBEANS = "这些可以用火。"
WILLOW.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "啊哈，香气。"

WILLOW.DESCRIBE.DUG_KYNO_COFFEEBUSH = "得把它挪到别处去。"

WILLOW.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "这灌木在火山的火焰边长得可好了！",
	PICKED = "现在没豆子了。",
	WITHERED = "太干了。没意思。",
}

WILLOW.DESCRIBE.DUG_KYNO_SPOTBUSH = "得找个新地方。"

WILLOW.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "闻起来有点胡椒味儿。",
	PICKED = "啥都不剩了。",
	BURNING = "哎呀。",
}

WILLOW.DESCRIBE.KYNO_SPOTSPICE_LEAF = "这是一片胡椒状灌木。"

WILLOW.DESCRIBE.KYNO_MUSSEL = "打开，伙计。"
WILLOW.DESCRIBE.KYNO_MUSSEL_COOKED = "火打开了它们的外壳。"

WILLOW.DESCRIBE.KYNO_HUMANMEAT = "你仍然可以火烤它！"
WILLOW.DESCRIBE.KYNO_HUMANMEAT_COOKED = "用火改良的死肉。"
WILLOW.DESCRIBE.KYNO_HUMANMEAT_DRIED = "我认为它还能燃烧。"

WILLOW.DESCRIBE.COFFEE = "我突然觉得很有动力。"

WILLOW.DESCRIBE.BISQUE = "我想我可以吃那个。"

WILLOW.DESCRIBE.JELLYOPOP = "我要二十个！"

WILLOW.DESCRIBE.SHARKFINSOUP = "我没有煮掉它！"

WILLOW.DESCRIBE.TROPICALBOUILLABAISSE = "呃，这里除了钓鱼还有什么吗？？"

WILLOW.DESCRIBE.MUSSELBOUILLABAISE = "嗯，闻起来很香！"

WILLOW.DESCRIBE.SWEETPOTATOSOUFFLE = "完美烹制！"

WILLOW.DESCRIBE.FEIJOADA = "哈！现在我可以吃那些混蛋了。"

WILLOW.DESCRIBE.GUMMY_CAKE = "比大多数蛋糕更耐嚼。"

WILLOW.DESCRIBE.HARDSHELL_TACOS = "我喜欢松脆的部分。"

WILLOW.DESCRIBE.ICEDTEA = "我更喜欢热的东西。"

WILLOW.DESCRIBE.NETTLELOSANGE = "它清除了我的鼻涕。"

WILLOW.DESCRIBE.SNAKEBONESOUP = "水和骨头配火更好。"

WILLOW.DESCRIBE.STEAMEDHAMSANDWICH = "这是一个火腿三明治。"

WILLOW.DESCRIBE.TEA = "火让一切变得更好。"

WILLOW.DESCRIBE.BUBBLETEA = "我更喜欢热的。"

WILLOW.DESCRIBE.FRENCHONIONSOUP = "没有什么比一碗热腾腾的汤更好的了。"

WILLOW.DESCRIBE.SLAW = "蔬菜。这么多蔬菜。"

WILLOW.DESCRIBE.LOTUSBOWL = "火让它变得更美味。"

WILLOW.DESCRIBE.POI = "这是什么？"

WILLOW.DESCRIBE.JELLYBEAN_HUNGER = "没有什么比一把软糖更好的了。"
WILLOW.DESCRIBE.JELLYBEAN_SUPER = "没有什么比一把软糖更好的了。"
WILLOW.DESCRIBE.JELLYBEAN_SANITY = "没有什么比一把软糖更好的了。"

WILLOW.DESCRIBE.BOWLOFGEARS = "呃，这还能吃吗？"

WILLOW.DESCRIBE.LONGPIGMEAL = "咦吽~~."

WILLOW.DESCRIBE.CUCUMBERSALAD = "我宁愿吃一碗火焰。"

WILLOW.DESCRIBE.DUG_KYNO_WILDWHEAT = "得找个新地方。"

WILLOW.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "又干又扎手。",
	PICKED = "现在啥都没了。",
	WITHERED = "太干了，懒得管。",
	BURNING = "噗！",
}

WILLOW.DESCRIBE.KYNO_MEALGRINDER = "我可以用它粉碎东西。"

WILLOW.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "它们丑得都快可爱了。",
	PICKED = "嘿！再给我点蘑菇啊！",
	BURNING = "烧起来了！",
}

WILLOW.DESCRIBE.GORGE_BREAD = "这只是一个愚蠢的面包。"
WILLOW.DESCRIBE.GORGE_SWEET_CHIPS = "我喜欢脆脆的。"
WILLOW.DESCRIBE.GORGE_VEGETABLE_SOUP = "啊。健康食品。"
WILLOW.DESCRIBE.GORGE_JELLY_SANDWICH = "果冻三明治，有点意思。"
WILLOW.DESCRIBE.GORGE_FISH_STEW = "呃。这是老人的食物！"
WILLOW.DESCRIBE.GORGE_MEAT_STEW = "给食物加点火，瞧！"
WILLOW.DESCRIBE.GORGE_ONION_CAKE = "这个蛋糕非常好吃。"
WILLOW.DESCRIBE.GORGE_POTATO_PANCAKES = "美味的传统早餐。"
WILLOW.DESCRIBE.GORGE_POTATO_SOUP = "我想我可以吃这个。"
WILLOW.DESCRIBE.GORGE_FISHBALL_SKEWERS = "啊！有些卡在牙齿里了！"
WILLOW.DESCRIBE.GORGE_MEAT_SKEWERS = "啊！有一些卡在牙齿里了！"
WILLOW.DESCRIBE.GORGE_STONE_SOUP = "我想我可以吃这个。"
WILLOW.DESCRIBE.GORGE_CROQUETTE = "味道很不错。"
WILLOW.DESCRIBE.GORGE_ROAST_VEGETABLES = "火让它变得更好一些。"
WILLOW.DESCRIBE.GORGE_MEATLOAF = "应该多烧一会的。"
WILLOW.DESCRIBE.GORGE_CARROT_SOUP = "我想我可以吃这个。"
WILLOW.DESCRIBE.GORGE_FISHPIE = "这不是个好主意。但食物就是食物。"
WILLOW.DESCRIBE.GORGE_FISHCHIPS = "好极了！"
WILLOW.DESCRIBE.GORGE_MEATPIE = "闻起来不错！"
WILLOW.DESCRIBE.GORGE_SLIDERS = "烤得不错。"
WILLOW.DESCRIBE.GORGE_JELLY_ROLL = "看起来很棒，只是需要更多的火。"
WILLOW.DESCRIBE.GORGE_CARROT_CAKE = "蛋糕是真的，而且是我亲手做的！"
WILLOW.DESCRIBE.GORGE_GARLICMASHED = "我必须说，这是一个不错的组合。"
WILLOW.DESCRIBE.GORGE_GARLICBREAD = "有进步。"
WILLOW.DESCRIBE.GORGE_TOMATO_SOUP = "我想我可以吃这个。"
WILLOW.DESCRIBE.GORGE_SAUSAGE = "看起来很时髦。"
WILLOW.DESCRIBE.GORGE_CANDIEDFISH = "被糖果淹没的鱼。"
WILLOW.DESCRIBE.GORGE_STUFFEDMUSHROOM = "只是需要多一点火候。"
WILLOW.DESCRIBE.GORGE_BRUSCHETTA = "番茄切片非常棒。"
WILLOW.DESCRIBE.GORGE_HAMBURGER = "我喜欢这个，真的！"
WILLOW.DESCRIBE.GORGE_FISHBURGER = "我喜欢这个，真的！"
WILLOW.DESCRIBE.GORGE_MUSHROOMBURGER = "我喜欢这个，真的！"
WILLOW.DESCRIBE.GORGE_FISH_STEAK = "呃。这是老人的食物！"
WILLOW.DESCRIBE.GORGE_CURRY = "这真是太棒了！"
WILLOW.DESCRIBE.GORGE_SPAGHETTI = "肉被制成球体并用火改良。"
WILLOW.DESCRIBE.GORGE_POACHEDFISH = "水煮的鱼片..."
WILLOW.DESCRIBE.GORGE_SHEPHERD_PIE = "我希望羊群不要来找我。"
WILLOW.DESCRIBE.GORGE_CANDY = "含糖燃烧的东西燃烧得很好，但我应该吃这个。"
WILLOW.DESCRIBE.GORGE_BREAD_PUDDING = "布丁！"
WILLOW.DESCRIBE.GORGE_BERRY_TART = "需要烤制水果。"
WILLOW.DESCRIBE.GORGE_MACARONI = "酪味。"
WILLOW.DESCRIBE.GORGE_BAGEL_AND_FISH = "鱼肉与面包相得益彰。"
WILLOW.DESCRIBE.GORGE_GRILLED_CHEESE = "你好，世界！"
WILLOW.DESCRIBE.GORGE_CREAMMUSHROOM = "全部为奶油色。"
WILLOW.DESCRIBE.GORGE_MANICOTTI = "意大利面管。"
WILLOW.DESCRIBE.GORGE_CHEESEBURGER = "我喜欢这个，真的！"
WILLOW.DESCRIBE.GORGE_FETTUCCINE = "满满的奶油让它看起来怪怪的。"
WILLOW.DESCRIBE.GORGE_ONION_SOUP = "噢 不。"
WILLOW.DESCRIBE.GORGE_BREADED_CUTLET = "我再也忍不住了！"
WILLOW.DESCRIBE.GORGE_CREAMY_FISH = "熏鱼似乎更好。"
WILLOW.DESCRIBE.GORGE_PIZZA = "我差点忘了这是什么。"
WILLOW.DESCRIBE.GORGE_POT_ROAST = "这东西是怎么放进锅里的？！"
WILLOW.DESCRIBE.GORGE_CRAB_CAKE = "为什么要把饼做成螃蟹的形状呢？"
WILLOW.DESCRIBE.GORGE_STEAK_FRITES = "炸薯条几乎可以与任何食物搭配。"
WILLOW.DESCRIBE.GORGE_SHOOTER_SANDWICH = "需要更多的火焰！"
WILLOW.DESCRIBE.GORGE_BACON_WRAPPED = "不错，但可以改进。"
WILLOW.DESCRIBE.GORGE_CRAB_ROLL = "我想，这很好。"
WILLOW.DESCRIBE.GORGE_MEAT_WELLINGTON = "沃利的表现着实让我吃惊！"
WILLOW.DESCRIBE.GORGE_CRAB_RAVIOLI = "我想，这很好。"
WILLOW.DESCRIBE.GORGE_CARAMEL_CUBE = "太棒了！"
WILLOW.DESCRIBE.GORGE_SCONE = "甜的!"
WILLOW.DESCRIBE.GORGE_TRIFLE = "甜的!"
WILLOW.DESCRIBE.GORGE_CHEESECAKE = "哼哼，没那么糟。"

WILLOW.DESCRIBE.DUCKYOUGLERMZ = "太臭了！"

WILLOW.DESCRIBE.KYNO_ALOE = "恶心。里面全是黏糊糊的。"
WILLOW.DESCRIBE.KYNO_ALOE_COOKED = "我把火烧了。"
WILLOW.DESCRIBE.KYNO_ALOE_GROUND = "恶心。里面全是黏糊糊的。"
WILLOW.DESCRIBE.KYNO_ALOE_SEEDS = "一些种子。"
WILLOW.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "一些种子。"
WILLOW.DESCRIBE.FARM_PLANT_KYNO_ALOE = "真恶心。里面都是黏糊糊的。"
WILLOW.DESCRIBE.KYNO_ALOE_OVERSIZED = "真恶心。里面都是黏糊糊的。"
WILLOW.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "哈，好恶心。"

WILLOW.DESCRIBE.KYNO_CUCUMBER = "嘿！谁敢让我生吃？"
WILLOW.DESCRIBE.KYNO_CUCUMBER_COOKED = "太好了，现在我不用咀嚼了。"
WILLOW.DESCRIBE.KYNO_CUCUMBER_GROUND = "嘿！谁敢让我生吃？"
WILLOW.DESCRIBE.KYNO_CUCUMBER_SEEDS = "一些种子。"
WILLOW.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "一些种子。"
WILLOW.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "嘿！谁敢让我生吃？"
WILLOW.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "嘿！谁敢让我生吃？"
WILLOW.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "嘿！谁敢让我生吃？"

WILLOW.DESCRIBE.KYNO_RADISH = "就像小火球。"
WILLOW.DESCRIBE.KYNO_RADISH_COOKED = "辣。就像火烧你的嘴。"
WILLOW.DESCRIBE.KYNO_RADISH_GROUND = "就像小火球。"
WILLOW.DESCRIBE.KYNO_RADISH_SEEDS = "一些种子。"
WILLOW.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "一些种子。"
WILLOW.DESCRIBE.FARM_PLANT_KYNO_RADISH = "像小火球一样。"
WILLOW.DESCRIBE.KYNO_RADISH_OVERSIZED = "像小火球一样。"
WILLOW.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "哈，好恶心。"

WILLOW.DESCRIBE.KYNO_FENNEL = "我敢打赌它不好吃。"
WILLOW.DESCRIBE.KYNO_FENNEL_COOKED = "外面的火烧得很好。"
WILLOW.DESCRIBE.KYNO_FENNEL_GROUND = "我敢打赌它不好吃。"
WILLOW.DESCRIBE.KYNO_FENNEL_SEEDS = "一些种子。"
WILLOW.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "一些种子。"
WILLOW.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "我打赌味道一定不好。"
WILLOW.DESCRIBE.KYNO_FENNEL_OVERSIZED = "我打赌味道一定不好。"
WILLOW.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "哈，好恶心。"

WILLOW.DESCRIBE.KYNO_SWEETPOTATO = "红色浆果的可喜变化。"
WILLOW.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "火焰确实改善了它。"
WILLOW.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "与红色浆果相比，这是一个可喜的变化。"
WILLOW.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "一些种子。"
WILLOW.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "一些种子。"
WILLOW.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "与红色浆果相比，这是一个可喜的变化。"
WILLOW.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "与红色浆果相比，这是一个可喜的变化。"
WILLOW.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "哈，好恶心。"

WILLOW.DESCRIBE.KYNO_PARZNIP = "全是蔬菜。"
WILLOW.DESCRIBE.KYNO_PARZNIP_COOKED = "全是蔬菜。"
WILLOW.DESCRIBE.KYNO_PARZNIP_EATEN = "全是蔬菜。"
WILLOW.DESCRIBE.KYNO_PARZNIP_GROUND = "全是蔬菜。"
WILLOW.DESCRIBE.KYNO_PARZNIP_BIG = "一种巨大的蔬菜，哎呀。"
WILLOW.DESCRIBE.KYNO_PARZNIP_SEEDS = "一些种子。"
WILLOW.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "一些种子。"
WILLOW.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "全是蔬菜。"
WILLOW.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "全是蔬菜。"
WILLOW.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "哈，好恶心。"

WILLOW.DESCRIBE.KYNO_TURNIP = "哈哈，恶心，我讨厌萝卜。"
WILLOW.DESCRIBE.KYNO_TURNIP_COOKED = "拿去吧，萝卜。"
WILLOW.DESCRIBE.KYNO_TURNIP_GROUND = "哈哈，恶心，我讨厌萝卜。"
WILLOW.DESCRIBE.KYNO_TURNIP_SEEDS = "一些种子。"
WILLOW.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "一些种子。"
WILLOW.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "哈哈，恶心，我讨厌萝卜。"
WILLOW.DESCRIBE.KYNO_TURNIP_OVERSIZED = "哈哈，恶心，我讨厌萝卜。"
WILLOW.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "哈，好恶心。"

WILLOW.DESCRIBE.KYNO_RICE = "我并不喜欢吃米饭。"
WILLOW.DESCRIBE.KYNO_RICE_COOKED = "我并不喜欢吃米饭。"
WILLOW.DESCRIBE.KYNO_RICE_SEEDS = "一些种子。"
WILLOW.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "一些种子。."
WILLOW.DESCRIBE.FARM_PLANT_KYNO_RICE = "哈，恶心。"
WILLOW.DESCRIBE.KYNO_RICE_OVERSIZED = "哈，恶心。"
WILLOW.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "哈，好恶心。"

WILLOW.DESCRIBE.KYNO_SEEDS_KIT = "里面有一些种子。"

WILLOW.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "那些恶心的食物正试图吃掉那块石头。",
	PICKED = "它们全跑光了。",
	WITHERED = "又干又无聊。",
}

WILLOW.DESCRIBE.KYNO_LIMPETS = "一点点火焰，你就会变得美味。"
WILLOW.DESCRIBE.KYNO_LIMPETS_COOKED = "非常好！"

WILLOW.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "能吃吗？还是烧了？",
	PICKED = "现在没花了。",
	BURNING = "这才有趣嘛！",
}

WILLOW.DESCRIBE.KYNO_LOTUS_ROOT = "一株湿漉漉的植物。"
WILLOW.DESCRIBE.KYNO_LOTUS_FLOWER = "只是一朵愚蠢的花。"
WILLOW.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "火让它变得更好。"

WILLOW.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "湿漉漉的海草。",
	PICKED = "暂时没了。",
	BURNING = "连海里这玩意儿都能烧起来！",
}

WILLOW.DESCRIBE.KYNO_SEAWEEDS = "湿透的海草。"
WILLOW.DESCRIBE.KYNO_SEAWEEDS_COOKED = "加火后还不错。"
WILLOW.DESCRIBE.KYNO_SEAWEEDS_DRIED = "健康的肉干。"
WILLOW.DESCRIBE.KYNO_SEAWEEDS_ROOT = "一堆湿透的杂草。"

WILLOW.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "它干嘛长在水里？",
	PICKED = "它会回来的。",
	BURNING = "好多了！",
}

WILLOW.DESCRIBE.KYNO_TAROROOT_ROOT = "湿漉漉的灯泡。"
WILLOW.DESCRIBE.KYNO_TAROROOT = "绝对不是鸟。"
WILLOW.DESCRIBE.KYNO_TAROROOT_COOKED = "对它使用火使它成为更美味的芋头根。"

WILLOW.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "我能烧了它吗？",
	PICKED = "它会回来的。",
	BURNING = "哎呀！",
}

WILLOW.DESCRIBE.KYNO_WATERYCRESS_ROOT = "一丛湿漉漉的杂草。"
WILLOW.DESCRIBE.KYNO_WATERYCRESS = "我可以烧掉它吗？"

WILLOW.DESCRIBE.WATERYCRESSBOWL = "即使是水和蔬菜在火上也更美味。"

WILLOW.DESCRIBE.KYNO_SALT = "我所有的食物都需要一两撮。"

WILLOW.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "黏糊糊的海鲜串在棍子上。",
	PICKED = "现在啥都没了。",
	BURNING = "海鲜烧烤！",
}

WILLOW.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "贻贝出于某种原因喜欢这个棒子。"

WILLOW.DESCRIBE.CATFOOD = "呃。猫粮。"

WILLOW.DESCRIBE.KATFOOD = "呃。猫粮。"

WILLOW.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "看起来能烧！",
	PICKED = "现在没香蕉了。",
	CHOPPED = "行吧，搞定了。",
	BURNING = "嘿！这才有趣嘛！",
	BURNT = "烤焦啦！",
}

WILLOW.DESCRIBE.KYNO_BANANA = "香蕉！"
WILLOW.DESCRIBE.KYNO_BANANA_COOKED = "好吃！"

WILLOW.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "你这树枝少得真奇怪。",
	PICKED = "现在没椰子了。",
	CHOPPED = "哎呀。",
	BURNING = "这样好多了！",
	BURNT = "脆了。",
}

WILLOW.DESCRIBE.KYNO_KOKONUT = "可食用的树。"
WILLOW.DESCRIBE.KYNO_KOKONUT_HALVED = "啊哈！现在你是食物！"
WILLOW.DESCRIBE.KYNO_KOKONUT_COOKED = "嗯，烤面包。"

WILLOW.DESCRIBE.BOWLOFPOPCORN = "这个一着火就会爆炸！"

WILLOW.DESCRIBE.FIGJUICE = "我更喜欢热的东西。"

WILLOW.DESCRIBE.COCONUTWATER = "我更喜欢热的东西。"

WILLOW.DESCRIBE.EYEBALLSPAGHETTI = "我不吃它。"

WILLOW.DESCRIBE.FORGETMELOTS_SEEDS = "一些种子。"

WILLOW.DESCRIBE.FIRENETTLES_SEEDS = "一些种子。"

WILLOW.DESCRIBE.TILLWEED_SEEDS = "一些种子。"

WILLOW.DESCRIBE.KYNO_FLOATILIZER = "一桶满满的脏东西。"

WILLOW.DESCRIBE.KYNO_TWIGGYNUTS = "脆脆的。"

WILLOW.DESCRIBE.KYNO_REPAIRTOOL = "这应该能解决一些问题。"

WILLOW.DESCRIBE.KYNO_KOI = "对于生活在水中的东西来说，这有点漂亮。"
WILLOW.DESCRIBE.KYNO_KOI_COOKED = "这对于生活在水中的东西来说有点漂亮。"

WILLOW.DESCRIBE.KYNO_TROPICALFISH = "好漂亮的颜色。"
WILLOW.DESCRIBE.KYNO_TROPICALFISH_COOKED = "火让一切变得更美好。"

WILLOW.DESCRIBE.KYNO_NEONFISH = "生活在水下真的像听起来那么可怕吗？"
WILLOW.DESCRIBE.KYNO_NEONFISH_COOKED = "火烧掉了大部分鱼腥味。"

WILLOW.DESCRIBE.KYNO_GROUPER = "你看起来有点傻。"
WILLOW.DESCRIBE.KYNO_GROUPER_COOKED = "火烧掉了最粗的部分。"
 
WILLOW.DESCRIBE.KYNO_PIERROTFISH = "找到你了！"
WILLOW.DESCRIBE.KYNO_PIERROTFISH_COOKED = "我烧得恰到好处。"

WILLOW.DESCRIBE.KYNO_SALMONFISH = "看它，像那样翻来覆去。"
WILLOW.DESCRIBE.KYNO_SALMONFISH_COOKED = "它只需要一些火。"

WILLOW.DESCRIBE.TURF_PINKPARK = "哇，我喜欢！"
WILLOW.DESCRIBE.TURF_STONECITY = "地面很无聊。"
WILLOW.DESCRIBE.TURF_FIELDS = "地面很无聊。"
WILLOW.DESCRIBE.TURF_TIDALMARSH = "吱吱声。"

WILLOW.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "得把盐捞出来了。",
	PICKED = "长快点啊，盐晶！",
}

WILLOW.DESCRIBE.KYNO_SALTRACK_INSTALLER = "我们可以用它来获取一些食盐。"

WILLOW.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "现在我们可以从树上提取树液了。"

WILLOW.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "这会显示那些螃蟹。"

WILLOW.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "它们跟咱那儿的猪人也没啥两样嘛。",
	SLEEPING = "呃。我就知道。",
}

WILLOW.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "黏糊糊的树。",
	CHOPPED = "现在它有点没用了。",
	SAPPED = "树液好了！",
	PICKED = "怎么要这么久！",
	BURNING = "这就对了！",
	BURNT = "挺好看。",
}

WILLOW.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "你看起来不太妙啊，树。",
	CHOPPED = "很好。",
	SAPPED = "呃。",
	PICKED = "蠢虫子。",
	BURNING = "终于！",
	BURNT = "好多了。",
}

WILLOW.DESCRIBE.KYNO_SUGARTREE_BUD = "我会烧掉它，但它会种下那棵糖树。"

WILLOW.DESCRIBE.KYNO_SUGARTREE_FLOWER = "我没有时间浪费在花上。"
WILLOW.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "我没有时间浪费在花上。"

WILLOW.DESCRIBE.KYNO_SUGARTREE_PETALS = "我没有时间浪费在花上。"

WILLOW.DESCRIBE.KYNO_PEBBLECRAB = "别担心，我不会踢你的。"

WILLOW.DESCRIBE.KYNO_CRABMEAT = "需要更多火力。"
WILLOW.DESCRIBE.KYNO_CRABMEAT_COOKED = "我敢打赌它很好吃。"
WILLOW.DESCRIBE.KYNO_CRABMEAT_DRIED = "需要更多火力。"

WILLOW.DESCRIBE.KYNO_CRABKINGMEAT = "需要更多火力。"
WILLOW.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "需要更多火力。"
WILLOW.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "需要更多火力。"

WILLOW.DESCRIBE.KYNO_SLAUGHTERTOOL = "我宁愿烧东西。"

WILLOW.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "一只丑鸡。",
	COOP = "嘿嘿，你现在是我的了！",
}

WILLOW.DESCRIBE.KYNO_CHICKEN_EGG = "闻起来像鸡屁股。"
WILLOW.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "我敢打赌，把它放在火上烤肯定会嘭的一声好大声！"
WILLOW.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "糟糕。黄色的部分都流鼻涕了。"

WILLOW.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "至少它现在还没着火。",
	FULL = "所有这些蛋……制造混乱的潜力可真大。",
	BURNT = "嘿嘿，我早就料到了。",
}

WILLOW.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "嘿，这就像我的老房子。"

WILLOW.DESCRIBE.KYNO_COOKWARE_KIT = "只是一些厨房用品。"
WILLOW.DESCRIBE.KYNO_COOKWARE_SYRUP = "里面有甜的东西。"
WILLOW.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "里面有甜的东西。"
WILLOW.DESCRIBE.KYNO_COOKWARE_BIG_POT = "我应该在它的屁股底下生火。"
WILLOW.DESCRIBE.KYNO_COOKWARE_BIG = "我应该在它的屁股底下生火。"
WILLOW.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "它着火了。"
WILLOW.DESCRIBE.KYNO_COOKWARE_SMALL = "它着火了。"
WILLOW.DESCRIBE.KYNO_COOKWARE_GRILL = "开火！"
WILLOW.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "呃，我想我应该设置一下。"
WILLOW.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "如果它更大，我可以用更多的火。"
WILLOW.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "我应该把它放在火坑上方。"
WILLOW.DESCRIBE.KYNO_COOKWARE_ELDER = "里面有甜食。"
WILLOW.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "我迫不及待想使用它！"
WILLOW.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "花式。"
WILLOW.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "好小。"
WILLOW.DESCRIBE.KYNO_COOKWARE_OVEN = "现在我们正在做饭。"
WILLOW.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "现在我们正在做饭。"
WILLOW.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "现在我们正在做饭。"

WILLOW.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "看看下面有啥呗。",
	FLIPPED = "呃。我就知道。",
}

WILLOW.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "这里有什么东西。"

WILLOW.DESCRIBE.KYNO_SUGARFLY = "飞走，糖蝴蝶！"
WILLOW.DESCRIBE.KYNO_SUGARFLYWINGS = "不再飞行！"

WILLOW.DESCRIBE.KYNO_WATERY_CRATE = "这里有问题。"

WILLOW.DESCRIBE.KYNO_TUNACAN = "但我更喜欢吃其他鱼！"
WILLOW.DESCRIBE.KYNO_TUNACAN_OPEN = "但我更喜欢吃其他鱼！"

WILLOW.DESCRIBE.KYNO_CANNEDFOOD = "只是罐头里的一些食物。"
WILLOW.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "噢，现在会变质的......"

WILLOW.DESCRIBE.KYNO_POP = "这是火水吗？很奇怪。"

WILLOW.DESCRIBE.KYNO_MYSTERYMEAT = "很恶心。"

WILLOW.DESCRIBE.KYNO_BOTTLE_SOUL = "可怜的灵魂。"

WILLOW.DESCRIBE.SOULSTEW = "可怜的灵魂。"

WILLOW.DESCRIBE.FORTUNECOOKIE = "让我们看看我今天是否走运！"

WILLOW.DESCRIBE.HORNOCUPIA = "哎呀！我想我切了一颗牙。"

WILLOW.DESCRIBE.CHEESE_YELLOW = "说奶酪。呃，随便吧……"
WILLOW.DESCRIBE.CHEESE_WHITE = "说奶酪。呃，随便吧……"
WILLOW.DESCRIBE.CHEESE_KOALEFANT = "说奶酪吧。呃，随便……"

WILLOW.DESCRIBE.MILK_BOX = "只是动物成熟的牛奶。"

WILLOW.DESCRIBE.WATERCUP = "我每天都喝水，这很健康。"

WILLOW.DESCRIBE.HONEYJAR = "呃。现在我的手一团糟。"

WILLOW.DESCRIBE.CRAB_ARTICHOKE = "更多螃蟹！"

WILLOW.DESCRIBE.PEPPERROLLS = "完全着火了！"

WILLOW.DESCRIBE.KYNO_SAPHEALER = "这会帮助那些中毒的树木！"

WILLOW.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "有人后悔了吧。",
	PICKED = "没啥可刮的了。",
	BURNING = "嘿嘿。这下行了。",
}

WILLOW.DESCRIBE.KYNO_GHOST_PIRATE = "你\"是··\"什么?"

WILLOW.DESCRIBE.KYNO_BUCKET_EMPTY = "只是一个愚蠢的精酿桶，看起来可以燃烧！"
WILLOW.DESCRIBE.KYNO_BUCKET_METAL = "没意思，我不能点燃它了。"
WILLOW.DESCRIBE.KYNO_BUCKET_WATER = "唉，水……我的天敌。"

WILLOW.DESCRIBE.KYNO_MILK_BEEFALO = "最后，这里有一些普通的牛奶......"
WILLOW.DESCRIBE.KYNO_MILK_KOALEFANT = "最后，这里有一些普通的牛奶......"

WILLOW.DESCRIBE.KYNO_CAP_DRIED = "尝起来比平常奇怪。"

WILLOW.DESCRIBE.KYNO_PLANTMEAT_DRIED = "多叶，但令人满意。"

WILLOW.DESCRIBE.KYNO_BREWBOOK = "呃，按照说明酿造可不好玩！"

WILLOW.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "看起来能烧，但我现在不会烧……",
	BREWING_LONG = "呃，怎么要这么久。",
	BREWING_SHORT = "快好了。终于啊。",
	DONE = "嘿！好了！",
	BURNT = "火又赢了！",
}

WILLOW.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "能烧，但挺重要的……呃。",
	BREWING_LONG = "呃，怎么要这么久。",
	BREWING_SHORT = "快好了。终于啊。",
	DONE = "嘿！真棒！",
	BURNT = "哈哈哈！",
}

WILLOW.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "我不会烧它，但仅仅是因为它能给我产蜂蜜。",
	HONEY = "到处都是黏糊糊的东西。嘿嘿。",
	NECTAR = "还是没火好玩。",
	BURNING = "这还差不多！",
}

WILLOW.DESCRIBE.KYNO_NECTAR_POD = "这有什么用吗？"

WILLOW.DESCRIBE.KYNO_OAKTREE_POD = "一颗树种。愚蠢。"
WILLOW.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "我把它放火了，现在我可以吃了。"

WILLOW.DESCRIBE.KYNO_PIKO = "松鼠小家伙。"
WILLOW.DESCRIBE.KYNO_PIKO_ORANGE = "松鼠小家伙。"

WILLOW.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "能烧。我只在乎这个。",
	CHOPPED = "就这样吧。",
	BURNING = "哎呀。",
	BURNT = "你这样还挺好看。",
}

WILLOW.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "能烧。我只在乎这个。",
	BURNING = "问题解决了。",
}

WILLOW.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "如果我把它烧掉，里面的东西也会烧掉......"

WILLOW.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "这玩意儿烧了也没人在乎。",
	BURNT = "好多了。",
}

WILLOW.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "卖鱼的。",
	CRAFTED = "哈。还行吧。",
	BURNT = "好多了。",
}

WILLOW.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "那是传说中的老钟吗？",
	OCCUPIED = "我就知道。没人在。",
}

WILLOW.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "我们就不能直接从他的车上拿吗？",
	EMPTY = "没劲。啥都没了。",
}

WILLOW.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "哦，太好了...我们又见面了。"
WILLOW.DESCRIBE.KYNO_MEADOWISLAND_POND = "我想知道如果你冲洗它会朝哪个方向旋转？"
WILLOW.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "全是植物。"
WILLOW.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "哦，看！是沙子。"
WILLOW.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "啊，我打赌你永远闻不到鱼的味道。"

WILLOW.DESCRIBE.KYNO_SAMMYHAT = "我有自己的帽子，但不知道它去了哪里。"

WILLOW.DESCRIBE.KINGFISHER = "你的脸怎么了？"

WILLOW.DESCRIBE.TOUCAN = "我喜欢你的鼻子。"
WILLOW.DESCRIBE.TOUCAN_CHUBBY = "我喜欢你的鼻子。"

WILLOW.DESCRIBE.WETGOOP2 = "它怎么出问题了？它被火和一切东西吞没了。"

WILLOW.DESCRIBE.BEER = "闻起来很香！"

WILLOW.DESCRIBE.PALEALE = "闻起来很香！"

WILLOW.DESCRIBE.TEAGREEN = "它有什么了不起的？它只是绿叶汁。"

WILLOW.DESCRIBE.TEARED = "它有什么了不起的？它只是红叶汁。"

WILLOW.DESCRIBE.MEAD = "这很甜蜜，但也......呃，我的脑袋感觉很有趣。"

WILLOW.DESCRIBE.KYNO_JELLY = "砰，砰，果酱！谢谢你，女士。"

WILLOW.DESCRIBE.KYNO_MAYONNAISE = "难以置信。鸡蛋变成了奶油。"

WILLOW.DESCRIBE.TARTARSAUCE = "停下！！鞑靼人，不！"

WILLOW.DESCRIBE.KYNO_PICKLES = "全部腌制。"

WILLOW.DESCRIBE.KYNO_WINE = "我更喜欢燃烧和苦涩的饮料。"

WILLOW.DESCRIBE.KYNO_JUICE = "我更喜欢燃烧和苦涩的饮料。"

WILLOW.DESCRIBE.KYNO_POISON_FROGLEGS = "我不确定我应该吃那个。"
WILLOW.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "只有一种方法可以确定它是否仍然有毒..."

WILLOW.DESCRIBE.POISONFROGGLEBUNWICH = "也许我不会注意到三明治里有青蛙腿。"

WILLOW.DESCRIBE.KYNO_BREWINGRECIPECARD = "无法读取，它会进入火中！"

WILLOW.DESCRIBE.KYNO_OIL = "油和火？真好！"

WILLOW.DESCRIBE.BERRYSUNDAE = "好吧，有时冷的东西还可以。"

WILLOW.DESCRIBE.CHOCOLATE_BLACK = "啊，我真的很想念那些！"
WILLOW.DESCRIBE.CHOCOLATE_WHITE = "啊，我真的很想念那些！"

WILLOW.DESCRIBE.TRICOLORDANGO = "非常甜的点心。"
 
WILLOW.DESCRIBE.FRIESFRENCH = "火和油让一切变得美好！"

WILLOW.DESCRIBE.PIRATERUM = "我不应该喝那个。"

WILLOW.DESCRIBE.TWISTEDTEQUILA = "它在灼伤我的舌头！"

WILLOW.DESCRIBE.ONIONRINGS = "油和火让一切变得更好！"

WILLOW.DESCRIBE.DONUTS = "哦，哇。我在想他们什么时候会出现。"
WILLOW.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "哦，哇。我想知道它们什么时候会出现。"
WILLOW.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "哦，哇。我想知道它们什么时候会出现。"
 
WILLOW.DESCRIBE.CINNAMONROLL = "一个小圆面包！"

WILLOW.DESCRIBE.GUMMYBEARGERS = "小熊糖果！"

WILLOW.DESCRIBE.PRETZEL = "松散的结。"

WILLOW.DESCRIBE.CORNINCUP = "勺子非常方便。"

WILLOW.DESCRIBE.COTTONCANDY = "这种食物应该燃烧得很好。"

WILLOW.DESCRIBE.ROASTEDHAZELNUTS = "东西烧焦比较好！"

WILLOW.DESCRIBE.MONSTERMUFFIN = "这个松饼有些奇怪。"

WILLOW.DESCRIBE.PINKCAKE = "我更喜欢燃烧时的蛋糕。"

WILLOW.DESCRIBE.CHIPSBAG = "比那个无聊的土豆好。"

WILLOW.DESCRIBE.LITTLEBREAD = "这只是一个愚蠢的面包。"

WILLOW.DESCRIBE.HOTHOUND = "我希望它不是用狗肉做的。"

WILLOW.DESCRIBE.MILKSHAKE = "我不知道牛奶可以这么好！"
WILLOW.DESCRIBE.MILKSHAKE_PRISMATIC = "我不知道牛奶可以这么好！"

WILLOW.DESCRIBE.NACHOS = "哎呀。我的手指现在沾满了奶酪。"

WILLOW.DESCRIBE.BANANA_PUDDING = "我更喜欢它被烧焦。"

WILLOW.DESCRIBE.SEA_PUDDING = "我更喜欢它被烧焦。"

WILLOW.DESCRIBE.TOM_KHA_SOUP = "味道鲜美。"

WILLOW.DESCRIBE.MINERTREAT = "这是给孩子们的。我是孩子。"

WILLOW.DESCRIBE.RADISHSALAD = "我宁愿吃一碗火焰。"

WILLOW.DESCRIBE.PUMPKIN_SOUP = "我想我可以吃那个。"

WILLOW.DESCRIBE.ALGAE_SOUP = "我想我可以吃那个。"

WILLOW.DESCRIBE.PARZNIP_SOUP = "我想我可以吃那个。"

WILLOW.DESCRIBE.NETTLEMEATED = "它能清除我的鼻涕。"

WILLOW.DESCRIBE.KYNO_SUGAR = "香甜可口！"

WILLOW.DESCRIBE.KYNO_BOTTLECAP = "来自哪里？"

WILLOW.DESCRIBE.NUKACOLA = "这饮料味道很奇怪。"
WILLOW.DESCRIBE.NUKACOLA_QUANTUM = "这饮料味道很奇怪。"

WILLOW.DESCRIBE.LIVINGSANDWICH = "不是说谎，这让我感到毛骨悚然。"

WILLOW.DESCRIBE.DURIANSPLIT = "嗯，有时候冷的东西也没关系。"

WILLOW.DESCRIBE.DURIANSOUP = "水和榴莲配火效果更好。"

WILLOW.DESCRIBE.DURIANMEATED = "这顿饭真臭，连火都烧不掉。"

WILLOW.DESCRIBE.DURIANCHICKEN = "蔬菜盛宴！"

WILLOW.DESCRIBE.LUNARSOUP = "月亮汤。"

WILLOW.DESCRIBE.PURPLEWOBSTERSOUP = "龙虾鱼汤。"

WILLOW.DESCRIBE.WOBSTERMONSTER = "呸。"

WILLOW.DESCRIBE.SPIDERCAKE = "如此怪物。"

WILLOW.DESCRIBE.SUGARBOMBS = "炸弹！"

WILLOW.DESCRIBE.BERRYBOMBS = "砰、砰、果酱！"

WILLOW.DESCRIBE.ONIGIRIS = "米饭。"

WILLOW.DESCRIBE.OMURICE = "火让它变得更加美好。"

WILLOW.DESCRIBE.PAELLA = "美味的米饭配上美味的烤鱼！"

WILLOW.DESCRIBE.RISOTTO = "沃利肯定有做谷物的绝活。"

WILLOW.DESCRIBE.RICESAKE = "我想威尔逊会喜欢这个的，嘿嘿。"

WILLOW.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "拔出来了。"

WILLOW.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "嗷呜！它有小刺。",
	PICKED = "现在没果子了。",
	WITHERED = "太干了，真可怜。",
	BURNING = "嘿嘿。脆了。",
}

WILLOW.DESCRIBE.KYNO_PINEAPPLE = "哎哟！"
WILLOW.DESCRIBE.KYNO_PINEAPPLE_HALVED = "看起来很好吃。"
WILLOW.DESCRIBE.KYNO_PINEAPPLE_COOKED = "火让一切变得更美好。"

WILLOW.DESCRIBE.PIZZA_TROPICAL = "就我个人而言，我更喜欢没有水果的披萨。"

WILLOW.DESCRIBE.PINACOLADA = "嗝。我敢打赌，火会让它变得更美味！"

WILLOW.DESCRIBE.CHIMAS = "草本。"

WILLOW.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "它最好别把我任何的火浇灭。",
	ON = "呃。太湿了。",
}

WILLOW.DESCRIBE.KYNO_FOODSACK = "我非得背着这湿漉漉的东西吗？"

WILLOW.DESCRIBE.GUMMYWORMS = "这最好是值得的。"

WILLOW.DESCRIBE.SMORES = "它们需要更多的火。"

WILLOW.DESCRIBE.NUKASHINE = "这才是一次难忘的旅行！"

WILLOW.DESCRIBE.ANTSLOG = "假蚂蚁。真无聊。"

WILLOW.DESCRIBE.KYNO_WORM_BONE = "哈哈。我有它的骨头。"

WILLOW.DESCRIBE.SPOOKY_BRAIN_NOODLES = "没煮熟。"
WILLOW.DESCRIBE.SPOOKY_BURGERZILLA = "这让我想起了一些事情，但具体是什么我记不清了。"
WILLOW.DESCRIBE.SPOOKY_DEADBREAD = "哎呀! 它不是用真正的死人做的。"
WILLOW.DESCRIBE.SPOOKY_JELLYBEANS = "时刻注意身后。"
WILLOW.DESCRIBE.SPOOKY_POPSICLE = "哎哟，味道像草。"
WILLOW.DESCRIBE.SPOOKY_PUMPKINCREAM = "我可以学着喜欢香草味。"
WILLOW.DESCRIBE.SPOOKY_SKULLCANDY = "这真的有效吗？"
WILLOW.DESCRIBE.SPOOKY_TACODILE = "它的身体哪去了?!"

WILLOW.DESCRIBE.BUTTER_BEEFALO = "也许只是舔一下？"
WILLOW.DESCRIBE.BUTTER_GOAT = "噢。别再做蝴蝶保姆了。"
WILLOW.DESCRIBE.BUTTER_KOALEFANT = "我讨厌考拉象，但这是它们的一大优点。"

WILLOW.DESCRIBE.SPICE_CURE = "一种防止我的饭菜过早变质的方法。"
WILLOW.DESCRIBE.SPICE_COLD = "我讨厌它。"
WILLOW.DESCRIBE.SPICE_FIRE = "我喜欢！"
WILLOW.DESCRIBE.SPICE_FED = "对懒惰的人不太有效。"
WILLOW.DESCRIBE.SPICE_MIND = "我的头脑需要它！"

WILLOW.DESCRIBE.SUGARFLYMUFFIN = "嘻嘻，看那只粘在松饼里的糖蛾。"

WILLOW.DESCRIBE.EELTACOS = "方便的墨西哥卷饼。"

WILLOW.DESCRIBE.MEATSKILLET = "胡椒的辣味让它变得更好！"

WILLOW.DESCRIBE.MEATWALTZ = "需要更多的时间燃烧！"

WILLOW.DESCRIBE.COMPLETEBREAKFAST = "吃了那个我就饱了！"

WILLOW.DESCRIBE.DUMPLINGS = "中国美食！"

WILLOW.DESCRIBE.WARLYICEDTEA = "我更喜欢热的东西。"

WILLOW.DESCRIBE.WARLYTEA = "火使一切变得更好。"

WILLOW.DESCRIBE.KYNO_TEALEAF = "用于泡茶。"

WILLOW.DESCRIBE.KYNO_ITEMSLICER = "也许可能找到我的路。"
WILLOW.DESCRIBE.KYNO_ITEMSLICER_GOLD = "也许可能找到我的路。"

WILLOW.DESCRIBE.COXINHA = "几乎是鸡腿！"

WILLOW.DESCRIBE.LAZYDESSERT = "我懒得为这件事评价。"

WILLOW.DESCRIBE.CRABKINGFEAST = "那东西怎么能放在这么小的锅里？"

WILLOW.DESCRIBE.PIENAPPLE = "哈！看起来像威尔逊的头发！"

WILLOW.DESCRIBE.JAWSBREAKER = "它可能需要采取一些激进的措施。"

WILLOW.DESCRIBE.AVOCADOTOAST = "我本可以再烧一点的。"

WILLOW.DESCRIBE.RICEPUDDING = "第一次感觉有点奇怪。"

WILLOW.DESCRIBE.SHARKSUSHI = "看起来很美味。"

WILLOW.DESCRIBE.WOBSTERBREADED = "需要更多的火焰。"

WILLOW.DESCRIBE.LAZYPURRITO = "哎呀！我觉得里面有毛球。"

WILLOW.DESCRIBE.HORCHATA = "啊。真的很冷。"

WILLOW.DESCRIBE.WOBSTERCOCKTAIL = "着火了！"

WILLOW.DESCRIBE.LAVAEEGGBOILED = "那位厨师太棒了！我喜欢它。"

WILLOW.DESCRIBE.POMEGRANATETEA = "我更喜欢热的东西。"

WILLOW.DESCRIBE.TIRAMISU = "嘀嘀嘀！"

WILLOW.DESCRIBE.TOADSTOOLCOLA = "这是火蛙水吗？真奇怪。"

WILLOW.DESCRIBE.TEPACHE = "太棒了！"

WILLOW.DESCRIBE.LUNARTEQUILA = "它那磅礴的能量在召唤着我。"

WILLOW.DESCRIBE.MIMICMOSA = "它散发着强大的气场！"

WILLOW.DESCRIBE.POMEGRANATEPIE = "也许我应该把这个派扔到某人的脸上。"

WILLOW.DESCRIBE.PINEAPPLECAKE = "我跟你说过，这看起来就像威尔逊的头发！"

WILLOW.DESCRIBE.PASTY_MEAT = "都是油！"
WILLOW.DESCRIBE.PASTY_CHEESE = "都是油！"

WILLOW.DESCRIBE.BRIGADEIRO = "这相当不错。"

WILLOW.DESCRIBE.REGULARLASAGNA = "终于有正常的千层饼。"

WILLOW.DESCRIBE.FLTSANDWICH = "里面没有生菜。"

WILLOW.DESCRIBE.RICEANDBEANS = "需要更多烤豆虫。"

WILLOW.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "呃，好旧好干……正适合烧掉。也许等到2026年再说。"

WILLOW.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "不就是蘑菇嘛……烧起来更好。",
	PICKED = "暂时全没了。",
	BURNING = "哎呀！",
}

WILLOW.DESCRIBE.KYNO_TRUFFLES = "高级蘑菇。也许我该把它们烧了。"
WILLOW.DESCRIBE.KYNO_TRUFFLES_COOKED = "火让一切更好。即便是蘑菇。"

WILLOW.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "总算有东西烧不着了……除非我想烧它。",
	FULL = "哈，还行吧。",
}

WILLOW.DESCRIBE.KYNO_SPORECAP = "也许烧掉是最安全的办法。"
WILLOW.DESCRIBE.KYNO_SPORECAP_COOKED = "火能解决一切问题！"

WILLOW.DESCRIBE.KYNO_SPORECAP_DARK = "一点火花就能把它烧没！"
WILLOW.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "还是一股死亡的味道，但更热了！"

WILLOW.DESCRIBE.KYNO_GOLDENAPPLE = "它炽热又让人平静。"

WILLOW.DESCRIBE.TRUFFLESGRINDER = "闻起来怪怪的，但烤热后挺不错。"

WILLOW.DESCRIBE.SPORECAPPIE = "嘿嘿，有毒的！正合我意的甜点。"

WILLOW.DESCRIBE.SPORECAP_SKEWERS = "火让一切更美味。即使是奇怪的蘑菇。"

WILLOW.DESCRIBE.TRUFFLEOIL = "呃，闻起来好高档……但我敢打赌它烧起来一定很棒！"

WILLOW.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "我宁可把东西烧毁，也不愿去建造它们。"
WILLOW.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "唉，这么多水……不能烧掉吗？"

WILLOW.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "哦，有小鱼在游来游去！",
	FUEL_HIGH = "吃得饱饱的。",
	FUEL_MED = "还在吃呢。",
	FUEL_LOW = "快没吃的了。",
	EMPTY = "没东西给它们吃了。",
}

WILLOW.DESCRIBE.KYNO_ANTCHOVY = "恶心！闻起来像烧焦的鱼和虫子内脏！"
WILLOW.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "哎呀，到处都是虫子和鱼！"

WILLOW.DESCRIBE.AGEDROE = "罐头鱼卵。太棒了。"
WILLOW.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "呕，发臭的鱼卵。有钱人怎么吃这个？"

WILLOW.DESCRIBE.KYNO_SWORDFISH_BLUE = "哈！看来大海也不想要你呢，小鱼！"

WILLOW.DESCRIBE.KYNO_JELLYFISH = "它正在干瘪。"
WILLOW.DESCRIBE.KYNO_JELLYFISH_DEAD = "现在不会再蜇人啦。"
WILLOW.DESCRIBE.KYNO_JELLYFISH_COOKED = "看起来居然能吃。"
WILLOW.DESCRIBE.KYNO_JELLYFISH_DRIED = "看起来很有嚼劲。"

WILLOW.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "喂，漂亮鱼，过来这儿！"
WILLOW.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "它还在移动。"
WILLOW.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "我好奇这些颜色是否增添了风味。"

WILLOW.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "这是一个瓶子。"

WILLOW.DESCRIBE.KYNO_OCEANTRAP = "快进来游泳吧！里面很暖和！"

WILLOW.DESCRIBE.OCEANFISH_PUFFERFISH = "嘿。这不过是满嘴跑火车，活脱脱一个麦克斯韦！"
WILLOW.DESCRIBE.OCEANFISH_STURGEON = "老鱼，气味更陈旧。"

WILLOW.DESCRIBE.KYNO_SWORDFISH = "准备！"
WILLOW.DESCRIBE.KYNO_SWORDFISH_DEAD = "唉，火能把那股味道烧掉。"

WILLOW.DESCRIBE.SWORDFISHFEAST = "终于有条鱼在被我吃掉时不盯着我看啦！"

WILLOW.DESCRIBE.KYNO_DOGFISH = "似乎不太聪明。"
WILLOW.DESCRIBE.KYNO_DOGFISH_DEAD = "该扔进火里烧了！"

WILLOW.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "恶心。"

WILLOW.DESCRIBE.WOBSTER_MONKEYISLAND = "它闪闪发亮……真想知道烤了会是什么滋味！"
WILLOW.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "最适合篝火晚会的点心。"
WILLOW.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "嗯，酥脆又熏香。正是我喜欢的味道！"

WILLOW.DESCRIBE.KYNO_PUFFERMONSTER = "嘿，我敢打赌要是点上火，它肯定会噼里啪啦炸得特别带劲！"

WILLOW.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "是什么在制造那些气泡呢？"
WILLOW.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "我真不知道他们居然能养出这么大的鱼。"
WILLOW.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "我看见它眼中燃着火焰！"
WILLOW.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "它开始变质了。真恶心。"

WILLOW.DESCRIBE.KYNO_BLUBBER = "我敢打赌这玩意儿会燃烧的更旺！"

WILLOW.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "烟熏味、嚼劲十足，还有点鱼腥味。完美！"
WILLOW.DESCRIBE.KYNO_FISHMEAT_DRIED = "有点硬，但味道好极了！"

WILLOW.DESCRIBE.MONKEYISLANDMEAL = "给猴子吃精致食物？怪怪的，但闻起来真香！"

WILLOW.DESCRIBE.KYNO_BRAINROCK_LARVAE = "哈哈，真恶心。"
WILLOW.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "不错的秃斑石头。"
WILLOW.DESCRIBE.KYNO_BRAINROCK_CORAL = "我或许能学会喜欢这种味道……"

WILLOW.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "真是天才的想法，跟这些蠢石头躲在一起。",
	PICKED = "估计是没想法了。",
}

WILLOW.DESCRIBE.BRAINMETTERSOUP = "适合小孩子。"

WILLOW.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "他看起来有点迷糊。",
	SLEEPING = "很好。他现在安静了。",
}

WILLOW.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "这里满是海味！"

WILLOW.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "这玩意儿看起来挺有意义。",
	WAITING = "还是太湿了，烧不了。",
}

WILLOW.DESCRIBE.KYNO_PACKIMBAGGIMS = "是友是敌？"

WILLOW.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "上面会有火吧？！"
WILLOW.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "我们应该增加更多层。"
WILLOW.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "吹灭蜡烛永远是最有趣的部分！"
WILLOW.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "终于！有东西可以烧了！"
WILLOW.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "这让我想起我的童年。"
WILLOW.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "蛋糕！火焰最好的朋友！"
WILLOW.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "要是它们能迸出火焰就好了！"

WILLOW.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "爆米花，火，完美组合！",
	FUEL_HIGH = "烧得挺好，挺稳。",
	FUEL_MED = "还在爆呢。",
	FUEL_LOW = "需要更多燃料。",
	EMPTY = "没火，就没爆米花。",
}

WILLOW.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "火烤得噼里啪啦响！这才是我的零食。"
WILLOW.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "着火的话更有趣。"
WILLOW.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "萨米有自己的帽子了？哼。好吧。挺可爱的。"

WILLOW.DESCRIBE.KYNO_FISHREGISTRYHAT = "在烧掉它们之前，得先了解这些鱼。"

WILLOW.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "让小家伙们有饭吃。",
	FUEL_HIGH = "好多食物啊。",
	FUEL_MED = "还剩一些。",
	FUEL_LOW = "快空了。",
	EMPTY = "没东西吃了。",
	BURNT = "哎呀。估计是着火了。",
}

WILLOW.DESCRIBE.CHICKENNUGGETS = "没着火。失望。"

WILLOW.DESCRIBE.CHICKENWINGS = "好！终于有会反烧的食物了！"

WILLOW.DESCRIBE.CHICKENBURGER = "还是没着火，但还行吧。"

WILLOW.DESCRIBE.CHICKENEGGSOUP = "温的，无聊，没着火。"

WILLOW.DESCRIBE.CHICKENEGGSTEW = "热炖菜。还是可以再多点火的。"

WILLOW.DESCRIBE.CHICKENROTISSERIE = "这才叫正确使用火嘛。"