local WOODIE = STRINGS.CHARACTERS.WOODIE

WOODIE.ANNOUNCE_KYNO_COFFEEBUFF_START = "速度越快，倒下的树越多！"
WOODIE.ANNOUNCE_KYNO_COFFEEBUFF_END = "我突然感觉很慢。"

WOODIE.ANNOUNCE_KYNO_HASTEBUFF_START = "加快捡起的速度。"
WOODIE.ANNOUNCE_KYNO_HASTEBUFF_END = "噢。我的手发呆了！"

WOODIE.ANNOUNCE_KYNO_POPBUFF_START = "（嗝！）哦，你看到了吗，露西？"
WOODIE.ANNOUNCE_KYNO_POPBUFF_END = "需要暂时戒掉那杯酒。"

WOODIE.ANNOUNCE_KYNO_FROGBUFF_START = "我和他们之间的和平时刻，嗯？"
WOODIE.ANNOUNCE_KYNO_FROGBUFF_END = "我现在需要远离青蛙。"

WOODIE.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝!) 准备好，露西！"
WOODIE.ANNOUNCE_KYNO_PIRATEBUFF_END = "我得歇会儿，别再喝了。"

WOODIE.ANNOUNCE_KYNO_FREEZEBUFF_START = "哎呀，冬天已经到了吗？"
WOODIE.ANNOUNCE_KYNO_FREEZEBUFF_END = "它持续的时候很有趣。"

WOODIE.ANNOUNCE_KYNO_FIREBUFF_START = "看火人！"
WOODIE.ANNOUNCE_KYNO_FIREBUFF_END = "它持续的时候很有趣。"

WOODIE.ANNOUNCE_KYNO_FISHINGBUFF_START = "是时候尝试一些新的活动了。"
WOODIE.ANNOUNCE_KYNO_FISHINGBUFF_END = "啊，来吧！还有一条鱼......"

WOODIE.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "现在很平静。"
WOODIE.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "我仍然觉得有点头晕。"

WOODIE.ANNOUNCE_KYNO_EATERBUFF_START = "准备好切些木头了吗，露西？"
WOODIE.ANNOUNCE_KYNO_EATERBUFF_END = "我的牙齿都惊呆了。"

WOODIE.ANNOUNCE_KYNO_WORMBUFF_START = "让我们开始战斗吧！"
WOODIE.ANNOUNCE_KYNO_WORMBUFF_END = "我需要休息一会儿。"

WOODIE.ANNOUNCE_KYNO_CRABBUFF_START = "让我们开始战斗吧!"
WOODIE.ANNOUNCE_KYNO_CRABBUFF_END = "我需要休息一会儿。"

WOODIE.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝！) 哦，露西，你看到了吗？"
WOODIE.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "需要休息一下，别喝青蛙饮料了。"

WOODIE.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "我能看到真相！"
WOODIE.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "我的头脑有点恍惚。"

WOODIE.ANNOUNCE_KYNO_STEALTHBUFF_START = "露西，安静点，好吗？"
WOODIE.ANNOUNCE_KYNO_STEALTHBUFF_END = "好吧，你抓住我了。"

WOODIE.ANNOUNCE_KYNO_FEARBUFF_START = "好吧，这不是让我如释重负吗！"
WOODIE.ANNOUNCE_KYNO_FEARBUFF_END = "哇，那种可怕的感觉又回来了！"

WOODIE.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "这股力量真是太猛了！"
WOODIE.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "嗯，没持续多久啊。"

WOODIE.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "看来我现在有了一整个小队！"
WOODIE.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "看来我们的猪小队已经离开。"

WOODIE.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "看来我不会被灼伤了，嗯？"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WOODIE.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "看来今天我比沼泽还要强壮！"
WOODIE.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "又回到脆弱状态了，是吧？"

WOODIE.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "看来我这脑子比刚砍下的原木还清醒呢，对吧？"
WOODIE.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "看来这绝妙的主意已经烧尽了，是吧？"

WOODIE.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "看样子蜜蜂不再找麻烦了。"
WOODIE.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "唉，蜜蜂又不爽了。”"

WOODIE.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "感觉很结实，是吧？"
WOODIE.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "好吧，这事儿结束了。"

WOODIE.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "看来现在能带更多食物了，是吧？"
WOODIE.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "唉，这好景不长。"

WOODIE.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "感觉脑子转得更灵光了，对吧？"
WOODIE.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "哎呀，美好的念头就这样溜走了。"

WOODIE.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "感觉现在没有什么能打倒我！"
WOODIE.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "好了，还是要小心谨慎。"

WOODIE.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "或许可以找个东西把它捡起来？"

WOODIE.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "不，他想要别的。"

WOODIE.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "她年纪太小，承受不了。"

WOODIE.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "这里没用。"

WOODIE.ANNOUNCE_KYNO_POTHANGER_FAIL = "嗯，也许这里可以放个锅。"

WOODIE.ANNOUNCE_KYNO_CASSEROLE_FAIL = "呃，不是这个。"

WOODIE.ANNOUNCE_KYNO_SAPHEALER_USED = "I'll help you only once, tree."

WOODIE.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "抱歉啦，小家伙。这就是生命的轮回，对吧？"

WOODIE.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "哎呀，看来萨米刚把补给用光了。"

WOODIE.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "露西，我们迷路了。周围水太多。"
WOODIE.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "雨下得太大了，露西。现在根本找不到任何踪迹。"
WOODIE.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "外面有东西在动……而且绝不是漂流木！"

WOODIE.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "搞定啦！看起来不错吧？"

WOODIE.ANNOUNCE_KYNO_FISH_RESEARCHED = "哎呀，还真学到了点东西。"
WOODIE.ANNOUNCE_KYNO_ROE_RESEARCHED = "看来连鱼蛋也能教点东西。"

WOODIE.DESCRIBE.KYNO_ROE = "一把未来的鱼，嗯？"
WOODIE.DESCRIBE.KYNO_ROE_COOKED = "最好在它们变坏之前吃掉它们。"

WOODIE.DESCRIBE.KYNO_SHARK_FIN = "我相信鲨鱼不会错过这个。"

WOODIE.DESCRIBE.KYNO_BEANBUGS = "真是个有趣的小家伙。"
WOODIE.DESCRIBE.KYNO_BEANBUGS_COOKED = "这不是枫糖焗豆。"

WOODIE.DESCRIBE.KYNO_GUMMYBUG = "落基山脉有很多这样的东西。"
WOODIE.DESCRIBE.KYNO_GUMMYBUG_COOKED = "我有多饿？"

WOODIE.DESCRIBE.KYNO_WHEAT = "好漂亮的金色。"
WOODIE.DESCRIBE.KYNO_WHEAT_COOKED = "好漂亮的金色。"

WOODIE.DESCRIBE.KYNO_FLOUR = "是用来做面包的，嗯？"

WOODIE.DESCRIBE.KYNO_SPOTSPICE = "你只需要捏一下就能尝到味道。"

WOODIE.DESCRIBE.KYNO_SAP = "树液。来自树。"
WOODIE.DESCRIBE.KYNO_SAP_SPOILED = "太可惜了"

WOODIE.DESCRIBE.KYNO_SYRUP = "甜味剂。"

WOODIE.DESCRIBE.KYNO_COFFEEBEANS = "我应该烤这些。"
WOODIE.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "加拿大人喜欢他们的咖啡。"

WOODIE.DESCRIBE.DUG_KYNO_COFFEEBUSH = "All set for replanting."

WOODIE.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "Coffee beans!",
	PICKED = "Needs more time.",
	WITHERED = "Needs more fertilizing.",
}

WOODIE.DESCRIBE.DUG_KYNO_SPOTBUSH = "Gotta plant it again."

WOODIE.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "Looks real flavourful.",
	PICKED = "Needs some time.",
	BURNING = "That's not good.",
}

WOODIE.DESCRIBE.KYNO_SPOTSPICE_LEAF = "它让我的手指闻起来像胡椒。"

WOODIE.DESCRIBE.KYNO_MUSSEL = "那些看起来很好吃。"
WOODIE.DESCRIBE.KYNO_MUSSEL_COOKED = "这些看起来很好吃。"

WOODIE.DESCRIBE.KYNO_HUMANMEAT = "你仍然可以火烤它！"
WOODIE.DESCRIBE.KYNO_HUMANMEAT_COOKED = "这并不是我们想要的。"
WOODIE.DESCRIBE.KYNO_HUMANMEAT_DRIED = "非常时期，耐嚼，嗯？"

WOODIE.DESCRIBE.COFFEE = "让我想起了老乔。"

WOODIE.DESCRIBE.BISQUE = "开心。"

WOODIE.DESCRIBE.JELLYOPOP = "我猜这是一个甜点，嗯？"

WOODIE.DESCRIBE.SHARKFINSOUP = "从现在开始他会在我的肚子里游泳。"

WOODIE.DESCRIBE.TROPICALBOUILLABAISSE = "这有点可疑。"

WOODIE.DESCRIBE.MUSSELBOUILLABAISE = "我见过的最好的一餐，嗯？"

WOODIE.DESCRIBE.SWEETPOTATOSOUFFLE = "相当奢侈。"

WOODIE.DESCRIBE.FEIJOADA = "这些小豆子肯定是美味的食物。"

WOODIE.DESCRIBE.GUMMY_CAKE = "我更喜欢纳尼亚莫酒吧。"

WOODIE.DESCRIBE.HARDSHELL_TACOS = "我喜欢紧缩。"

WOODIE.DESCRIBE.ICEDTEA = "不错，令人耳目一新。"

WOODIE.DESCRIBE.NETTLELOSANGE = "很适合清理鼻子，嗯？"

WOODIE.DESCRIBE.SNAKEBONESOUP = "没有什么比一碗热腾腾的汤更好的了。"

WOODIE.DESCRIBE.STEAMEDHAMSANDWICH = "令人垂涎的汉堡包。"

WOODIE.DESCRIBE.TEA = "我可以去喝点茶。"

WOODIE.DESCRIBE.BUBBLETEA = "不错，令人耳目一新。"

WOODIE.DESCRIBE.FRENCHONIONSOUP = "没有什么比一碗热腾腾的汤更好的了。"

WOODIE.DESCRIBE.SLAW = "就像碗里的森林。"

WOODIE.DESCRIBE.LOTUSBOWL = "嗯……好吃。"

WOODIE.DESCRIBE.POI = "这是什么东西？"

WOODIE.DESCRIBE.JELLYBEAN_HUNGER = "你几乎尝不到豆子的味道！"
WOODIE.DESCRIBE.JELLYBEAN_SUPER = "你几乎尝不到豆子的味道！"
WOODIE.DESCRIBE.JELLYBEAN_SANITY = "你几乎尝不到豆子的味道！"

WOODIE.DESCRIBE.BOWLOFGEARS = "不是给我们露西的，是吗？"

WOODIE.DESCRIBE.LONGPIGMEAL = "我应该把它放在某个地方。"

WOODIE.DESCRIBE.CUCUMBERSALAD = "健康，但不是很耐吃。"

WOODIE.DESCRIBE.DUG_KYNO_WILDWHEAT = "Best plant it somewhere else."

WOODIE.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "Looks harvestable, eh?",
	PICKED = "Needs more time.",
	WITHERED = "Dry as a bone.",
	BURNING = "Looks like kindling.",
}

WOODIE.DESCRIBE.KYNO_MEALGRINDER = "我们只需要磨。"

WOODIE.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "Those mushrooms look mighty tasty.",
	PICKED = "They'll be back soon enough.",
	BURNING = "That's a real shame.",
}

WOODIE.DESCRIBE.GORGE_BREAD = "一条面包，嗯？"
WOODIE.DESCRIBE.GORGE_SWEET_CHIPS = "我真的很喜欢他们这样。"
WOODIE.DESCRIBE.GORGE_VEGETABLE_SOUP = "我必须吃我的蔬菜。"
WOODIE.DESCRIBE.GORGE_JELLY_SANDWICH = "这对我来说是经典早餐。"
WOODIE.DESCRIBE.GORGE_FISH_STEW = "好吃，那个。"
WOODIE.DESCRIBE.GORGE_MEAT_STEW = "贴在你的肋骨上。"
WOODIE.DESCRIBE.GORGE_ONION_CAKE = "这个蛋糕味道不错！"
WOODIE.DESCRIBE.GORGE_POTATO_PANCAKES = "啊，我好想你！"
WOODIE.DESCRIBE.GORGE_POTATO_SOUP = "酣畅淋漓。"
WOODIE.DESCRIBE.GORGE_FISHBALL_SKEWERS = "食物简单易做，味道却很好。"
WOODIE.DESCRIBE.GORGE_MEAT_SKEWERS = "食物简单易做，味道却很好。"
WOODIE.DESCRIBE.GORGE_STONE_SOUP = "酣畅淋漓。"
WOODIE.DESCRIBE.GORGE_CROQUETTE = "它们闻起来很香。"
WOODIE.DESCRIBE.GORGE_ROAST_VEGETABLES = "平衡膳食，是吧？"
WOODIE.DESCRIBE.GORGE_MEATLOAF = "你想来一块吗，露西？"
WOODIE.DESCRIBE.GORGE_CARROT_SOUP = "酣畅淋漓。"
WOODIE.DESCRIBE.GORGE_FISHPIE = "我已经尽力了。"
WOODIE.DESCRIBE.GORGE_FISHCHIPS = "这多好啊！"
WOODIE.DESCRIBE.GORGE_MEATPIE = "看起来很有希望。"
WOODIE.DESCRIBE.GORGE_SLIDERS = "那时我经常吃。"
WOODIE.DESCRIBE.GORGE_JELLY_ROLL = "我们来点果酱吧，露西？"
WOODIE.DESCRIBE.GORGE_CARROT_CAKE = "营养丰富！"
WOODIE.DESCRIBE.GORGE_GARLICMASHED = "好闻。"
WOODIE.DESCRIBE.GORGE_GARLICBREAD = "我们现在只需要一些牛排。"
WOODIE.DESCRIBE.GORGE_TOMATO_SOUP = "酣畅淋漓。"
WOODIE.DESCRIBE.GORGE_SAUSAGE = "太好吃了!"
WOODIE.DESCRIBE.GORGE_CANDIEDFISH = "对我来说够甜了。"
WOODIE.DESCRIBE.GORGE_STUFFEDMUSHROOM = "酿香槟酒，是吗？"
WOODIE.DESCRIBE.GORGE_BRUSCHETTA = "味道不错。"
WOODIE.DESCRIBE.GORGE_HAMBURGER = "我以前在多伦多买过一些。"
WOODIE.DESCRIBE.GORGE_FISHBURGER = "我以前在多伦多买过一些。"
WOODIE.DESCRIBE.GORGE_MUSHROOMBURGER = "我以前在多伦多买过一些。"
WOODIE.DESCRIBE.GORGE_FISH_STEAK = "好吃，那个。"
WOODIE.DESCRIBE.GORGE_CURRY = "啊，美味的咖喱。"
WOODIE.DESCRIBE.GORGE_SPAGHETTI = "全是肉！"
WOODIE.DESCRIBE.GORGE_POACHEDFISH = "灿烂！"
WOODIE.DESCRIBE.GORGE_SHEPHERD_PIE = "闻起来不错。"
WOODIE.DESCRIBE.GORGE_CANDY = "甜甜的。很好。"
WOODIE.DESCRIBE.GORGE_BREAD_PUDDING = "可靠的好帮手。"
WOODIE.DESCRIBE.GORGE_BERRY_TART = "可以改进。"
WOODIE.DESCRIBE.GORGE_MACARONI = "这个真的很不错。"
WOODIE.DESCRIBE.GORGE_BAGEL_AND_FISH = "看上去不错吧？"
WOODIE.DESCRIBE.GORGE_GRILLED_CHEESE = "这在当时非常受欢迎。"
WOODIE.DESCRIBE.GORGE_CREAMMUSHROOM = "很不错吧？"
WOODIE.DESCRIBE.GORGE_MANICOTTI = "这太棒了！"
WOODIE.DESCRIBE.GORGE_CHEESEBURGER = "我以前在多伦多买过一些。"
WOODIE.DESCRIBE.GORGE_FETTUCCINE = "令人垂涎欲滴。"
WOODIE.DESCRIBE.GORGE_ONION_SOUP = "哦，吃完这顿饭，我的嘴巴一定会一团糟。"
WOODIE.DESCRIBE.GORGE_BREADED_CUTLET = "与其他东西一起吃，也是不错的点心。"
WOODIE.DESCRIBE.GORGE_CREAMY_FISH = "闻起来很香。"
WOODIE.DESCRIBE.GORGE_PIZZA = "嘿，这看起来不错，你不觉得吗，露西？"
WOODIE.DESCRIBE.GORGE_POT_ROAST = "它很大！"
WOODIE.DESCRIBE.GORGE_CRAB_CAKE = "可爱的蟹饼。"
WOODIE.DESCRIBE.GORGE_STEAK_FRITES = "这是一个经典食物。"
WOODIE.DESCRIBE.GORGE_SHOOTER_SANDWICH = "多好的三明治啊！"
WOODIE.DESCRIBE.GORGE_BACON_WRAPPED = "需要鸡蛋。"
WOODIE.DESCRIBE.GORGE_CRAB_ROLL = "蟹肉非常鲜美。"
WOODIE.DESCRIBE.GORGE_MEAT_WELLINGTON = "真不错。"
WOODIE.DESCRIBE.GORGE_CRAB_RAVIOLI = "蟹肉非常鲜美。"
WOODIE.DESCRIBE.GORGE_CARAMEL_CUBE = "我要咬一口。"
WOODIE.DESCRIBE.GORGE_SCONE = "一点也无妨，嗯。"
WOODIE.DESCRIBE.GORGE_TRIFLE = "一点也无妨，嗯。"
WOODIE.DESCRIBE.GORGE_CHEESECAKE = "要不要来一块，露西？"

WOODIE.DESCRIBE.DUCKYOUGLERMZ = "呃……好难闻的味道！"

WOODIE.DESCRIBE.KYNO_ALOE = "我听说芦荟对你有好处。"
WOODIE.DESCRIBE.KYNO_ALOE_COOKED = "我想我可以吃掉它。"
WOODIE.DESCRIBE.KYNO_ALOE_GROUND = "我听说芦荟对你有好处。"
WOODIE.DESCRIBE.KYNO_ALOE_SEEDS = "小种子。"
WOODIE.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "小种子。"
WOODIE.DESCRIBE.FARM_PLANT_KYNO_ALOE = "我听说芦荟对你有好处。"
WOODIE.DESCRIBE.KYNO_ALOE_OVERSIZED = "我听说芦荟对你有好处。"
WOODIE.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "哎呀。"

WOODIE.DESCRIBE.KYNO_CUCUMBER = "真的可以做得很好。"
WOODIE.DESCRIBE.KYNO_CUCUMBER_COOKED = "如果你问我，就在那儿吃得很好。"
WOODIE.DESCRIBE.KYNO_CUCUMBER_GROUND = "真的可以烤得很好。"
WOODIE.DESCRIBE.KYNO_CUCUMBER_SEEDS = "小种子。"
WOODIE.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "小种子。"
WOODIE.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "真的可以烤得很好。"
WOODIE.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "真的可以做得很好。"
WOODIE.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "真的可以做得很好。"

WOODIE.DESCRIBE.KYNO_RADISH = "有点小，不是吗？"
WOODIE.DESCRIBE.KYNO_RADISH_COOKED = "我必须吃我的蔬菜。"
WOODIE.DESCRIBE.KYNO_RADISH_GROUND = "有点小，不是吗？"
WOODIE.DESCRIBE.KYNO_RADISH_SEEDS = "小种子。"
WOODIE.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "小种子。"
WOODIE.DESCRIBE.FARM_PLANT_KYNO_RADISH = "有点小，不是吗？"
WOODIE.DESCRIBE.KYNO_RADISH_OVERSIZED = "有点小，不是吗？"
WOODIE.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "哎呀。"

WOODIE.DESCRIBE.KYNO_FENNEL = "我想要一些！"
WOODIE.DESCRIBE.KYNO_FENNEL_COOKED = "这些很好。"
WOODIE.DESCRIBE.KYNO_FENNEL_GROUND = "我想要一些！"
WOODIE.DESCRIBE.KYNO_FENNEL_SEEDS = "小种子。"
WOODIE.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "小种子。"
WOODIE.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "我想要一些！"
WOODIE.DESCRIBE.KYNO_FENNEL_OVERSIZED = "我想要一些！"
WOODIE.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "哎呀。"

WOODIE.DESCRIBE.KYNO_SWEETPOTATO = "我会把这个做好的！"
WOODIE.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "可以用一些棉花糖。"
WOODIE.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "我会把它做得很好吃！"
WOODIE.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "小种子。"
WOODIE.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "小种子。"
WOODIE.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "我会把它做得很好吃！"
WOODIE.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "我会把它做得很好吃！"
WOODIE.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "哎呀。"

WOODIE.DESCRIBE.KYNO_PARZNIP = "那是兔粮。"
WOODIE.DESCRIBE.KYNO_PARZNIP_COOKED = "那是兔粮。"
WOODIE.DESCRIBE.KYNO_PARZNIP_EATEN = "那是兔粮。"
WOODIE.DESCRIBE.KYNO_PARZNIP_GROUND = "那是兔粮。"
WOODIE.DESCRIBE.KYNO_PARZNIP_BIG = "那是地下的原因吧？"
WOODIE.DESCRIBE.KYNO_PARZNIP_SEEDS = "小种子。"
WOODIE.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "小种子。"
WOODIE.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "那是兔粮。"
WOODIE.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "那是兔粮。"
WOODIE.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "哎呀。"

WOODIE.DESCRIBE.KYNO_TURNIP = "来自社区花园。"
WOODIE.DESCRIBE.KYNO_TURNIP_COOKED = "烤得真香。"
WOODIE.DESCRIBE.KYNO_TURNIP_GROUND = "来自社区花园。"
WOODIE.DESCRIBE.KYNO_TURNIP_SEEDS = "小种子。"
WOODIE.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "小种子。"
WOODIE.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "来自社区花园。"
WOODIE.DESCRIBE.KYNO_TURNIP_OVERSIZED = "来自社区花园。"
WOODIE.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "哎呀。"

WOODIE.DESCRIBE.KYNO_RICE = "虽然不是我的首选，但也可以。"
WOODIE.DESCRIBE.KYNO_RICE_COOKED = "虽然不是我的首选，但也可以。"
WOODIE.DESCRIBE.KYNO_RICE_SEEDS = "小种子。"
WOODIE.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "小种子。"
WOODIE.DESCRIBE.FARM_PLANT_KYNO_RICE = "来自社区花园"
WOODIE.DESCRIBE.KYNO_RICE_OVERSIZED = "来自社区花园"
WOODIE.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "哎呀。"

WOODIE.DESCRIBE.KYNO_SEEDS_KIT = "我们得先拆开它，露西。"

WOODIE.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "I could make a snack out of those.",
	PICKED = "Gotta give them time.",
	WITHERED = "Dry as can be.",
}

WOODIE.DESCRIBE.KYNO_LIMPETS = "某种水栖蜗牛。"
WOODIE.DESCRIBE.KYNO_LIMPETS_COOKED = "晚餐开始了。"

WOODIE.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "Pretty nice, dontcha think Lucy?",
	PICKED = "Needs a bit more time.",
	BURNING = "That's not good!",
}

WOODIE.DESCRIBE.KYNO_LOTUS_ROOT = "应该把这个种在某个地方。"
WOODIE.DESCRIBE.KYNO_LOTUS_FLOWER = "那是个美女。"
WOODIE.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "烤得真好。"

WOODIE.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "It's slimy, eh?",
	PICKED = "Needs time to come back.",
	BURNING = "Didn't think that could happen.",
}

WOODIE.DESCRIBE.KYNO_SEAWEEDS = "黏糊糊的。"
WOODIE.DESCRIBE.KYNO_SEAWEEDS_COOKED = "它有一种奇怪的质地。"
WOODIE.DESCRIBE.KYNO_SEAWEEDS_DRIED = "它有点粘在我的舌头上。"
WOODIE.DESCRIBE.KYNO_SEAWEEDS_ROOT = "应该把它种在某个地方。"

WOODIE.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "Eh, I've seen this one before once.",
	PICKED = "Water'll help it grow back.",
	BURNING = "Well, that's ruined.",
}

WOODIE.DESCRIBE.KYNO_TAROROOT_ROOT = "应该把这个种在某个地方。"
WOODIE.DESCRIBE.KYNO_TAROROOT = "我敢打赌这会和辣椒搭配得很好。"
WOODIE.DESCRIBE.KYNO_TAROROOT_COOKED = "嗯！"

WOODIE.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "Just another vegetable, eh?",
	PICKED = "Give it time.",
	BURNING = "That's a shame.",
}

WOODIE.DESCRIBE.KYNO_WATERYCRESS_ROOT = "应该把这个种在某个地方。"
WOODIE.DESCRIBE.KYNO_WATERYCRESS = "只是另一种蔬菜，嗯？"

WOODIE.DESCRIBE.WATERYCRESSBOWL = "这是用那些小树做成的汤。"

WOODIE.DESCRIBE.KYNO_SALT = "它很咸。"

WOODIE.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "Seafood growin' on a stick, eh?",
	PICKED = "Gotta give it time.",
	BURNING = "That's a real shame.",
}

WOODIE.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "贻贝受够了这个东西。"

WOODIE.DESCRIBE.CATFOOD = "这里，这里，小猫。"

WOODIE.DESCRIBE.KATFOOD = "这里，这里，小猫。"

WOODIE.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "Now I have my own banana tree.",
	PICKED = "Needs a bit more time, eh?",
	CHOPPED = "Sorry about that, buddy.",
	BURNING = "Whoa! That's not good!",
	BURNT = "Burned right down.",
}

WOODIE.DESCRIBE.KYNO_BANANA = "它尝起来很热带。"
WOODIE.DESCRIBE.KYNO_BANANA_COOKED = "我出于某种原因烤了它。"

WOODIE.DESCRIBE.KYNO_KOKONUTTREE =
{
	GENERIC = "Makes me pine for the lumber yards.",
	PICKED = "Needs a bit more time.",
	CHOPPED = "Sorry about that.",
	BURNING = "Whoa! That's not good!",
	BURNT = "Burned right down.",
}

WOODIE.DESCRIBE.KYNO_KOKONUT = "这只是一个椰子。"
WOODIE.DESCRIBE.KYNO_KOKONUT_HALVED = "一个给我，一个给露西。"
WOODIE.DESCRIBE.KYNO_KOKONUT_COOKED = "准备吃。"

WOODIE.DESCRIBE.BOWLOFPOPCORN = "用玉米的美味烹制！"

WOODIE.DESCRIBE.FIGJUICE = "不错，令人耳目一新。"

WOODIE.DESCRIBE.COCONUTWATER = "不错，令人耳目一新。"

WOODIE.DESCRIBE.EYEBALLSPAGHETTI = "别看我，食物！"

WOODIE.DESCRIBE.FORGETMELOTS_SEEDS = "小种子。"

WOODIE.DESCRIBE.FIRENETTLES_SEEDS = "小种子。"

WOODIE.DESCRIBE.TILLWEED_SEEDS = "小种子。"

WOODIE.DESCRIBE.KYNO_FLOATILIZER = "便便属于桶，而不是在地上。"

WOODIE.DESCRIBE.KYNO_TWIGGYNUTS = "哦。我砍了树上的一些坚果。"

WOODIE.DESCRIBE.KYNO_REPAIRTOOL = "修补一下，嗯？"

WOODIE.DESCRIBE.KYNO_KOI = "对不起，伙计，但你的胡须对我来说不合适。"
WOODIE.DESCRIBE.KYNO_KOI_COOKED = "对不起，小伙子，但你的胡须对我来说不合适。"

WOODIE.DESCRIBE.KYNO_TROPICALFISH = "你准备好成为炸鱼薯条了吗？"
WOODIE.DESCRIBE.KYNO_TROPICALFISH_COOKED = "熏鱼，是吗？"

WOODIE.DESCRIBE.KYNO_NEONFISH = "那个颜色不错。"
WOODIE.DESCRIBE.KYNO_NEONFISH_COOKED = "看来我要吃一天了。"

WOODIE.DESCRIBE.KYNO_GROUPER = "看起来像晚餐。"
WOODIE.DESCRIBE.KYNO_GROUPER_COOKED = "自己抓来烤的。"
 
WOODIE.DESCRIBE.KYNO_PIERROTFISH = "一直很喜欢钓鱼。"
WOODIE.DESCRIBE.KYNO_PIERROTFISH_COOKED = "嗯……烤鱼。"

WOODIE.DESCRIBE.KYNO_SALMONFISH = "需要一块好的雪松木板来烹饪。"
WOODIE.DESCRIBE.KYNO_SALMONFISH_COOKED = "尝起来像家一样。"

WOODIE.DESCRIBE.TURF_PINKPARK = "一位美女。"
WOODIE.DESCRIBE.TURF_STONECITY = "只是一些地面，嗯？"
WOODIE.DESCRIBE.TURF_FIELDS = "只是一些地面，嗯？"
WOODIE.DESCRIBE.TURF_TIDALMARSH = "只是一些地面，嗯？"

WOODIE.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "It's ready.",
	PICKED = "Gonna be a bit longer.",
}

WOODIE.DESCRIBE.KYNO_SALTRACK_INSTALLER = "必须设置一下。"

WOODIE.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "我不是告诉大家树很好吃吗？"

WOODIE.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "让我们捕获一些螃蟹。"

WOODIE.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "Every society's gotta have a leader, I guess.",
	SLEEPING = "Guess I'll come back later.",
}

WOODIE.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "It's beautiful!",
	CHOPPED = "Cut down in its prime.",
	SAPPED = "Thanks for the sap, tree.",
	PICKED = "Fillin' up, slow as molasses.",
	BURNING = "That's not good!",
	BURNT = "Burned clean through.",
}

WOODIE.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "What troubles you, sister?",
	CHOPPED = "Had to be done.",
	SAPPED = "Still tappable, somehow.",
	PICKED = "Hey, get away from that tree will ya!",
	BURNING = "Probably best.",
	BURNT = "Nothing left.",
}

WOODIE.DESCRIBE.KYNO_SUGARTREE_BUD = "你会长成一棵好树的，嗯？"

WOODIE.DESCRIBE.KYNO_SUGARTREE_FLOWER = "真可爱。"
WOODIE.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "这很可爱。"

WOODIE.DESCRIBE.KYNO_SUGARTREE_PETALS = "真可爱。"

WOODIE.DESCRIBE.KYNO_PEBBLECRAB = "我看不出有什么理由打扰这个小家伙。"

WOODIE.DESCRIBE.KYNO_CRABMEAT = "这会做得很好。"
WOODIE.DESCRIBE.KYNO_CRABMEAT_COOKED = "我不介意尝尝。"
WOODIE.DESCRIBE.KYNO_CRABMEAT_DRIED = "那会煮得很好吃。"

WOODIE.DESCRIBE.KYNO_CRABKINGMEAT = "那会煮得很好吃。"
WOODIE.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "那会煮得很好。"
WOODIE.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "那会煮得很好。"

WOODIE.DESCRIBE.KYNO_SLAUGHTERTOOL = "露西脏了没用。"

WOODIE.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "A bird's a bird.",
	COOP = "I still hate them, but they're kind useful.",
}

WOODIE.DESCRIBE.KYNO_CHICKEN_EGG = "里面有只鸡在想鸡的想法。"
WOODIE.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "That's a lot of omelet, eh?"
WOODIE.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "嗯，它没有变成鸡。"

WOODIE.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "Nice little coop, eh? Keeps the chickens cozy.",
	FULL = "Plenty of eggs in there, beauty!",
	BURNT = "Ah... that's a real shame.",
}

WOODIE.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "我应该解决这个问题吗？"

WOODIE.DESCRIBE.KYNO_COOKWARE_KIT = "我不喜欢厨房里的东西，但我可以试试。"
WOODIE.DESCRIBE.KYNO_COOKWARE_SYRUP = "你必须有树液才能制作糖浆。"
WOODIE.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "你必须有树液才能制作糖浆。"
WOODIE.DESCRIBE.KYNO_COOKWARE_BIG_POT = "也许我可以测试一些新食谱。"
WOODIE.DESCRIBE.KYNO_COOKWARE_BIG = "也许我可以测试一些新食谱。"
WOODIE.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "我只知道一些食谱，但我真的很擅长。"
WOODIE.DESCRIBE.KYNO_COOKWARE_SMALL = "我只知道一些食谱，但我真的很擅长。"
WOODIE.DESCRIBE.KYNO_COOKWARE_GRILL = "准备好迎接五月二四。"
WOODIE.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "最好设置一下。"
WOODIE.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "想烧烤吗，露西？"
WOODIE.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "最好设置一下。"
WOODIE.DESCRIBE.KYNO_COOKWARE_ELDER = "你必须有树液才能制作糖浆。"
WOODIE.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "小心火，露西。"
WOODIE.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "这对烤箱有好处。"
WOODIE.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "我只会做点小东西。"
WOODIE.DESCRIBE.KYNO_COOKWARE_OVEN = "小心火，露西。"
WOODIE.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "小心火，露西。"
WOODIE.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "小心火，露西。"

WOODIE.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "I should flip it.",
	FLIPPED = "Yep. Figures.",
}

WOODIE.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "我希望永远不会如它一般。"

WOODIE.DESCRIBE.KYNO_SUGARFLY = "我从不相信那些东西，嗯？"
WOODIE.DESCRIBE.KYNO_SUGARFLYWINGS = "对不起！我是个糟糕的人！"

WOODIE.DESCRIBE.KYNO_WATERY_CRATE = "我希望永远不会如它一般。"

WOODIE.DESCRIBE.KYNO_TUNACAN = "露西会帮我打开它。"
WOODIE.DESCRIBE.KYNO_TUNACAN_OPEN = "露西会帮我打开它。"

WOODIE.DESCRIBE.KYNO_CANNEDFOOD = "露西会帮忙的。"
WOODIE.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "露西做得很好。"

WOODIE.DESCRIBE.KYNO_POP = "这可以安全食用吗？"

WOODIE.DESCRIBE.KYNO_MYSTERYMEAT = "这到底是什么东西！"

WOODIE.DESCRIBE.KYNO_BOTTLE_SOUL = "残忍。"

WOODIE.DESCRIBE.SOULSTEW = "残忍。"

WOODIE.DESCRIBE.FORTUNECOOKIE = "我不相信这样的事情。"

WOODIE.DESCRIBE.HORNOCUPIA = "盛宴！"

WOODIE.DESCRIBE.CHEESE_YELLOW = "啊，我想念那些。"
WOODIE.DESCRIBE.CHEESE_WHITE = "我以前从来没有吃过这些。"
WOODIE.DESCRIBE.CHEESE_KOALEFANT = "啊，我想念那些。"

WOODIE.DESCRIBE.MILK_BOX = "很好，嗯？"

WOODIE.DESCRIBE.WATERCUP = "只是一些水，嗯？"

WOODIE.DESCRIBE.HONEYJAR = "甜，甜，亲爱的！"

WOODIE.DESCRIBE.CRAB_ARTICHOKE = "我可以每天都吃这个。"

WOODIE.DESCRIBE.PEPPERROLLS = "呼！热！热！"

WOODIE.DESCRIBE.KYNO_SAPHEALER = "闻起来很糟糕，但很管用！"

WOODIE.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "A waste of good wood.",
	PICKED = "Give it time, it'll grow stuff again.",
	BURNING = "Well, that's the end of it.",
}

WOODIE.DESCRIBE.KYNO_GHOST_PIRATE = "也许他很友好？"

WOODIE.DESCRIBE.KYNO_BUCKET_EMPTY = "这可以派上用场。"
WOODIE.DESCRIBE.KYNO_BUCKET_METAL = "这可能会派上用场。"
WOODIE.DESCRIBE.KYNO_BUCKET_WATER = "干净的水，是吧？"

WOODIE.DESCRIBE.KYNO_MILK_BEEFALO = "你想要一些吗，露西？"
WOODIE.DESCRIBE.KYNO_MILK_KOALEFANT = "你想要一些吗，露西？"

WOODIE.DESCRIBE.KYNO_CAP_DRIED = "我现在不介意吃一个，嗯？"

WOODIE.DESCRIBE.KYNO_PLANTMEAT_DRIED = "尝起来像生存。"

WOODIE.DESCRIBE.KYNO_BREWBOOK = "非常方便。露西，你在我酿造的时候读出了成分？"

WOODIE.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "Now I can enjoy the making of beers.",
	BREWING_LONG = "Gonna take a few days, eh?",
	BREWING_SHORT = "Not much longer now.",
	DONE = "Looks good and ready!",
	BURNT = "Ah... That's a real shame.",
}

WOODIE.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "I want some jam, but what flavor?",
	BREWING_LONG = "Takes patience.", 
	BREWING_SHORT = "Not long now.",
	DONE = "Looks real tasty!",
	BURNT = "That's a shame.",
}

WOODIE.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "That's neat.",
	HONEY = "Plenty of honey in there, eh?",
	NECTAR = "They're still workin' on it.",
	BURNING = "Aw nuts, that's gone too far.",
}

WOODIE.DESCRIBE.KYNO_NECTAR_POD = "花蜜酿蜜，嗯。"

WOODIE.DESCRIBE.KYNO_OAKTREE_POD = "我最好现在种植你，这样我以后可以砍你，嗯。"
WOODIE.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "现在种植这个太晚了。"

WOODIE.DESCRIBE.KYNO_PIKO = "他们几乎和我一样喜欢树。"
WOODIE.DESCRIBE.KYNO_PIKO_ORANGE = "他们几乎和我一样喜欢树。"

WOODIE.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "Well. Better get choppin'.",
	CHOPPED = "Got what we needed.",
	BURNING = "Careful!",
	BURNT = "Burned clean through.",
}

WOODIE.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "Well. Better get choppin'.",
	BURNING = "Sorry, little guys.",
}

WOODIE.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "就是那个盒子。"

WOODIE.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "They're not the handiest.",
	BURNT = "Burned right down.",
}

WOODIE.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "I'd prefer a log cabin.",
	CRAFTED = "Not bad at all now.",
	BURNT = "That's awful.",
}

WOODIE.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "My eyes decieve me! The cursed bell is right there!",
	OCCUPIED = "Guess I'll come back later, eh?",
}

WOODIE.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "Is that...? I can't believe in my own eyes anymore.",
	EMPTY = "Guess I'll check back later.",
}

WOODIE.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "我想知道他是否在我不注意的时候和我们一起跳进了那个入口。"
WOODIE.DESCRIBE.KYNO_MEADOWISLAND_POND = "看起来像是一个很受欢迎的鱼群聚居地。"
WOODIE.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "植物。"
WOODIE.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "这是一大堆沙子。"
WOODIE.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "我不知道那个家伙。"

WOODIE.DESCRIBE.KYNO_SAMMYHAT = "这不是商人和邮差的帽子吗？"

WOODIE.DESCRIBE.KINGFISHER = "那个很牛，嗯？"

WOODIE.DESCRIBE.TOUCAN = "看起来很漂亮的鸟，那个。"
WOODIE.DESCRIBE.TOUCAN_CHUBBY = "看起来很漂亮的鸟，那个。"

WOODIE.DESCRIBE.WETGOOP2 = "比我吃过的一些东西好！"

WOODIE.DESCRIBE.BEER = "很高兴再次见到他们！"

WOODIE.DESCRIBE.PALEALE = "很高兴再次见到他们！"

WOODIE.DESCRIBE.TEAGREEN = "差点让我忘记我在哪里。"

WOODIE.DESCRIBE.TEARED = "差点让我忘记我在哪里。"

WOODIE.DESCRIBE.MEAD = "一小口不会太刺耳，是吗？"

WOODIE.DESCRIBE.KYNO_JELLY = "现在去找花生酱。"

WOODIE.DESCRIBE.KYNO_MAYONNAISE = "它很美味，很奶油。"

WOODIE.DESCRIBE.TARTARSAUCE = "不可能……"

WOODIE.DESCRIBE.KYNO_PICKLES = "我喜欢泡菜，尤其是南瓜。"

WOODIE.DESCRIBE.KYNO_WINE = "*嗝* 啊哈，神清气爽。"

WOODIE.DESCRIBE.KYNO_JUICE = "*咕噜* 啊，令人耳目一新。"

WOODIE.DESCRIBE.KYNO_POISON_FROGLEGS = "那些腿看起来有毒。"
WOODIE.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "我不知道，呃……？"

WOODIE.DESCRIBE.POISONFROGGLEBUNWICH = "你真的可以品尝到洞穴的味道。"

WOODIE.DESCRIBE.KYNO_BREWINGRECIPECARD = "看起来这里写了一些东西，但它消失了。"

WOODIE.DESCRIBE.KYNO_OIL = "也许是葵花籽油，嗯？"

WOODIE.DESCRIBE.BERRYSUNDAE = "只有在我切得足够多之后！"

WOODIE.DESCRIBE.CHOCOLATE_BLACK = "有时候吃块巧克力真好，嗯？"
WOODIE.DESCRIBE.CHOCOLATE_WHITE = "有时候吃块巧克力真好，嗯？"

WOODIE.DESCRIBE.TRICOLORDANGO = "从没听说过这些，但它们很棒！"
 
WOODIE.DESCRIBE.FRIESFRENCH = "垃圾食品，嗯？"

WOODIE.DESCRIBE.PIRATERUM = "危险！"

WOODIE.DESCRIBE.TWISTEDTEQUILA = "砍树时喝醉可不好。"

WOODIE.DESCRIBE.ONIONRINGS = "从没想过洋葱可以这样用。"

WOODIE.DESCRIBE.DONUTS = "直接放进我嘴里！"
WOODIE.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "直接送进我嘴里！"
WOODIE.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "直接送进我嘴里！"
 
WOODIE.DESCRIBE.CINNAMONROLL = "这是一个很重的面包。"

WOODIE.DESCRIBE.GUMMYBEARGERS = "这些家伙有些奇怪。"

WOODIE.DESCRIBE.PRETZEL = "它的格式很有趣。"

WOODIE.DESCRIBE.CORNINCUP = "我喜欢玉米，但一点也不喜欢。"

WOODIE.DESCRIBE.COTTONCANDY = "马戏团食物，嗯？"

WOODIE.DESCRIBE.ROASTEDHAZELNUTS = "我以前砍树时都吃过这个。"

WOODIE.DESCRIBE.MONSTERMUFFIN = "我一看到松饼就知道是真的松饼。这是个冒名顶替者！"

WOODIE.DESCRIBE.PINKCAKE = "我猜今天是某人的生日。"

WOODIE.DESCRIBE.CHIPSBAG = "想要一些吗，露西？"

WOODIE.DESCRIBE.LITTLEBREAD = "一条面包，嗯？"

WOODIE.DESCRIBE.HOTHOUND = "我觉得它很有品味。"

WOODIE.DESCRIBE.MILKSHAKE = "摇晃，摇晃，全部摇晃。"
WOODIE.DESCRIBE.MILKSHAKE_PRISMATIC = "摇晃，摇晃，全部摇晃。"

WOODIE.DESCRIBE.NACHOS = "小心，露西，你会把事情搞得一团糟！"

WOODIE.DESCRIBE.BANANA_PUDDING = "看起来很好吃！"

WOODIE.DESCRIBE.SEA_PUDDING = "呃，我不知道我是否想吃那个。"

WOODIE.DESCRIBE.TOM_KHA_SOUP = "呃，非常好！想要一块吗，露西？"

WOODIE.DESCRIBE.MINERTREAT = "喝几口不会有什么坏处，嗯？"

WOODIE.DESCRIBE.RADISHSALAD = "健康，但不太耐寒。"

WOODIE.DESCRIBE.PUMPKIN_SOUP = "丰盛。"

WOODIE.DESCRIBE.ALGAE_SOUP = "丰盛。"

WOODIE.DESCRIBE.PARZNIP_SOUP = "丰盛。"

WOODIE.DESCRIBE.NETTLEMEATED = "这不是培根，但也可以。"

WOODIE.DESCRIBE.KYNO_SUGAR = "嗯嗯嗯嗯嗯。"

WOODIE.DESCRIBE.KYNO_BOTTLECAP = "我敢打赌，如果我们得到更多的帽子，我们就可以买东西！"

WOODIE.DESCRIBE.NUKACOLA = "对于可乐来说还不错。一点也不差。"
WOODIE.DESCRIBE.NUKACOLA_QUANTUM = "对于可乐来说还不错。一点也不差。"

WOODIE.DESCRIBE.LIVINGSANDWICH = "我不知道每个人都在谈论它。这对我来说只是一个普通的三明治。"

WOODIE.DESCRIBE.DURIANSPLIT = "只有在我砍得够多之后！"

WOODIE.DESCRIBE.DURIANSOUP = "没有什么比一碗热腾腾的汤更好的了。"

WOODIE.DESCRIBE.DURIANMEATED = "闻起来很糟糕。"

WOODIE.DESCRIBE.DURIANCHICKEN = "我猜火鸡节又到了？"

WOODIE.DESCRIBE.LUNARSOUP = "带我飞向月球......"

WOODIE.DESCRIBE.PURPLEWOBSTERSOUP = "闻起来很香，嗯？"

WOODIE.DESCRIBE.WOBSTERMONSTER = "海洋怪物，嗯？"

WOODIE.DESCRIBE.SPIDERCAKE = "好吧，他们罪有应得。"

WOODIE.DESCRIBE.SUGARBOMBS = "小糖炸弹。"

WOODIE.DESCRIBE.BERRYBOMBS = "现在去找花生酱。"

WOODIE.DESCRIBE.ONIGIRIS = "你觉得呢，露西？"

WOODIE.DESCRIBE.OMURICE = "我喜欢在上面淋番茄酱！"

WOODIE.DESCRIBE.PAELLA = "我可以一整天都吃这个。"

WOODIE.DESCRIBE.RISOTTO = "非常细腻，你觉得呢，露西？"

WOODIE.DESCRIBE.RICESAKE = "适量饮用，好吗，露西？露西...？"

WOODIE.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "Pulled it right out."

WOODIE.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "Be careful with the spikes, Lucy!",
	PICKED = "Needs more time.",
	WITHERED = "Dry as a bone.",
	BURNING = "That's not good!",
}

WOODIE.DESCRIBE.KYNO_PINEAPPLE = "菠萝！"
WOODIE.DESCRIBE.KYNO_PINEAPPLE_HALVED = "菠萝!"
WOODIE.DESCRIBE.KYNO_PINEAPPLE_COOKED = "吃一片吧，露西。"

WOODIE.DESCRIBE.PIZZA_TROPICAL = "我不是这些的狂热爱好者。"

WOODIE.DESCRIBE.PINACOLADA = "啊哈，神清气爽！"

WOODIE.DESCRIBE.CHIMAS = "我已经习惯了。"

WOODIE.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "Good for watering.",
	ON = "Keeps things growin' nice, eh?",
}

WOODIE.DESCRIBE.KYNO_FOODSACK = "用来装我的宝贝。"

WOODIE.DESCRIBE.GUMMYWORMS = "不要害怕他们！"

WOODIE.DESCRIBE.SMORES = "这是一种不错的奶油饼干。"

WOODIE.DESCRIBE.NUKASHINE = "我觉得那杯酒散发着古怪的魔鬼气息。"

WOODIE.DESCRIBE.ANTSLOG = "我不知道我在看什么，露西..."

WOODIE.DESCRIBE.KYNO_WORM_BONE = "好骨头总是有好处的。"

WOODIE.DESCRIBE.SPOOKY_BRAIN_NOODLES = "呀。"
WOODIE.DESCRIBE.SPOOKY_BURGERZILLA = "嘿，这个还真不错。"
WOODIE.DESCRIBE.SPOOKY_DEADBREAD = "松软的面包，嗯？"
WOODIE.DESCRIBE.SPOOKY_JELLYBEANS = "很棒的万圣节礼物。"
WOODIE.DESCRIBE.SPOOKY_POPSICLE = "这真是太棒了！"
WOODIE.DESCRIBE.SPOOKY_PUMPKINCREAM = "多好的组合！"
WOODIE.DESCRIBE.SPOOKY_SKULLCANDY = "邪恶!"
WOODIE.DESCRIBE.SPOOKY_TACODILE = "闻起来不错。"

WOODIE.DESCRIBE.BUTTER_BEEFALO = "它的黄油！我想..."
WOODIE.DESCRIBE.BUTTER_GOAT = "确认。我希望我们得到它是值得的。"
WOODIE.DESCRIBE.BUTTER_KOALEFANT = "它与普通黄油相似，但味道比它好。"

WOODIE.DESCRIBE.SPICE_CURE = "这会让我们的食物保存的更久，露西，你不喜欢吗？"
WOODIE.DESCRIBE.SPICE_COLD = "冬天来了！"
WOODIE.DESCRIBE.SPICE_FIRE = "人间地狱！"
WOODIE.DESCRIBE.SPICE_FED = "我已经能感觉到气味了。"
WOODIE.DESCRIBE.SPICE_MIND = "每个人都需要放松一下，是吗？"

WOODIE.DESCRIBE.SUGARFLYMUFFIN = "松脆......但是软？"

WOODIE.DESCRIBE.EELTACOS = "尝起来像深海。"

WOODIE.DESCRIBE.MEATSKILLET = "需要更多的胡椒。"

WOODIE.DESCRIBE.MEATWALTZ = "未煮熟。"

WOODIE.DESCRIBE.COMPLETEBREAKFAST = "太多了，不能当我的早餐。"

WOODIE.DESCRIBE.DUMPLINGS = "它们相当不错，是吧。"

WOODIE.DESCRIBE.WARLYICEDTEA = "美味又清爽。"

WOODIE.DESCRIBE.WARLYTEA = "我可以去喝点茶。"

WOODIE.DESCRIBE.KYNO_TEALEAF = "露西，我们去泡点茶吧！"

WOODIE.DESCRIBE.KYNO_ITEMSLICER = "嚯，这可是剁肉神器！"
WOODIE.DESCRIBE.KYNO_ITEMSLICER_GOLD = "嚯，这可是剁肉神器！"

WOODIE.DESCRIBE.COXINHA = "不错，不错。.."

WOODIE.DESCRIBE.LAZYDESSERT = "假焦糖！"

WOODIE.DESCRIBE.CRABKINGFEAST = "它真的很大。"

WOODIE.DESCRIBE.PIENAPPLE = "吃东西前把尖刺拿掉。"

WOODIE.DESCRIBE.JAWSBREAKER = "我无法接受这个。"

WOODIE.DESCRIBE.AVOCADOTOAST = "我早餐想吃点别的。"

WOODIE.DESCRIBE.RICEPUDDING = "它是乳白色的。"

WOODIE.DESCRIBE.SHARKSUSHI = "看起来很美味。"

WOODIE.DESCRIBE.WOBSTERBREADED = "闻起来真香！"

WOODIE.DESCRIBE.LAZYPURRITO = "为什么我最近的食物看起来像动物？"

WOODIE.DESCRIBE.HORCHATA = "不是我最喜欢的。"

WOODIE.DESCRIBE.WOBSTERCOCKTAIL = "哇，这真美。"

WOODIE.DESCRIBE.LAVAEEGGBOILED = "炽热而燃烧。"

WOODIE.DESCRIBE.POMEGRANATETEA = "美味又清爽。"

WOODIE.DESCRIBE.TIRAMISU = "一举两得，我同意！"

WOODIE.DESCRIBE.TOADSTOOLCOLA = "我认为这不安全。"

WOODIE.DESCRIBE.TEPACHE = "一款清新的菠萝饮料。"

WOODIE.DESCRIBE.LUNARTEQUILA = "月亮...！"

WOODIE.DESCRIBE.MIMICMOSA = "我可以利用它来悄悄地躲过一些生物。"

WOODIE.DESCRIBE.POMEGRANATEPIE = "嗯。派总是不错的，对吧？"

WOODIE.DESCRIBE.PINEAPPLECAKE = "这块蛋糕能让我吃好几天！"

WOODIE.DESCRIBE.PASTY_MEAT = "它含油量比肉多。"
WOODIE.DESCRIBE.PASTY_CHEESE = "它含油量比奶酪多。"

WOODIE.DESCRIBE.BRIGADEIRO = "这个小家伙真好吃！"

WOODIE.DESCRIBE.REGULARLASAGNA = "我们不谈论怪物千层饼。"

WOODIE.DESCRIBE.FLTSANDWICH = "BLT三明治仿制版！"

WOODIE.DESCRIBE.RICEANDBEANS = "它只是缺少一些美味的牛排和薯条。"

WOODIE.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "见过更好的日子，对吧？我敢打赌2026年会变得热闹。"

WOODIE.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "Heh, nothing like finding food straight from the dirt.",
	PICKED = "Maybe more will pop up.",
	BURNING = "Ah, that's a real shame.",
}

WOODIE.DESCRIBE.KYNO_TRUFFLES = "闻起来有点怪，但味道不错。"
WOODIE.DESCRIBE.KYNO_TRUFFLES_COOKED = "这才叫好吃的东西。"

WOODIE.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "Nothing on it yet, eh?",
	FULL = "Looks nice, eh? Almost too nice to eat.",
}

WOODIE.DESCRIBE.KYNO_SPORECAP = "这可不是能吃的那种蘑菇，嗯？"
WOODIE.DESCRIBE.KYNO_SPORECAP_COOKED = "好一点了，但我还是不信任它。"

WOODIE.DESCRIBE.KYNO_SPORECAP_DARK = "这蘑菇真恶心，嗯？"
WOODIE.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "还是很臭，嗯？"

WOODIE.DESCRIBE.KYNO_GOLDENAPPLE = "太诱人、太稀有了……我都舍不得吃。"

WOODIE.DESCRIBE.TRUFFLESGRINDER = "从没想过我会吃泥巴还叫它高级。"

WOODIE.DESCRIBE.SPORECAPPIE = "看起来像是不该吃的东西，嗯？"

WOODIE.DESCRIBE.SPORECAP_SKEWERS = "没有什么比篝火蘑菇更棒了，对吧？"

WOODIE.DESCRIBE.TRUFFLEOIL = "这味道有点太高档了，嗯？"

WOODIE.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "好吧，还是赶紧动手吧。"
WOODIE.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "养鱼的好地方，对吧？"

WOODIE.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "A hatchery for little fishies.",
	FUEL_HIGH = "They're eatin' real good!",
	FUEL_MED = "Still doin' fine.",
	FUEL_LOW = "Better toss some more food in.",
	EMPTY = "All outta feed.",
}

WOODIE.DESCRIBE.KYNO_ANTCHOVY = "这下可有意思了，对吧？不过可别咬我的木头哦。"
WOODIE.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "那可是一大群呢，对吧？把你们的网准备好。"

WOODIE.DESCRIBE.AGEDROE = "哎呀，这可真够咸的。"
WOODIE.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "有点黏糊糊的，但时髦人士可喜欢了，对吧？"

WOODIE.DESCRIBE.KYNO_SWORDFISH_BLUE = "可怜的家伙被湖水浸软了，是吧？再也扛不住浪了。"

WOODIE.DESCRIBE.KYNO_JELLYFISH = "那是一只水母，你不知道吗？"
WOODIE.DESCRIBE.KYNO_JELLYFISH_DEAD = "这东西几乎没剩什么生命力了，是吧？"
WOODIE.DESCRIBE.KYNO_JELLYFISH_COOKED = "我觉得这已经算是能吃的极限了。"
WOODIE.DESCRIBE.KYNO_JELLYFISH_DRIED = "肉干！我族之食粮。"

WOODIE.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "随波逐流。"
WOODIE.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "我觉得我这小家伙一时半会儿是起不来了。"
WOODIE.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "吃起来和这儿其他东西一样好。"

WOODIE.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "里面有什么？"

WOODIE.DESCRIBE.KYNO_OCEANTRAP = "我期待着享用一顿海鲜晚餐。"

WOODIE.DESCRIBE.OCEANFISH_PUFFERFISH = "哎呀，这家伙身上的刺比豪猪还多呢，对吧？"
WOODIE.DESCRIBE.OCEANFISH_STURGEON = "这可真是条有故事的鱼啊，对吧？"

WOODIE.DESCRIBE.KYNO_SWORDFISH = "有一条尖尖的鱼。"
WOODIE.DESCRIBE.KYNO_SWORDFISH_DEAD = "抱歉，伙计。"

WOODIE.DESCRIBE.SWORDFISHFEAST = "珍奇鱼类，是吧？还带着码头的腥味呢。"

WOODIE.DESCRIBE.KYNO_DOGFISH = "乖狗狗。"
WOODIE.DESCRIBE.KYNO_DOGFISH_DEAD = "它想成为晚餐。"

WOODIE.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "我觉得是时候扔掉这个了。"

WOODIE.DESCRIBE.WOBSTER_MONKEYISLAND = "嘿。这小家伙还挺时髦的，对吧？"
WOODIE.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "嗯，这就是生命的轮回，对吧？"
WOODIE.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "这才是好吃的，对吧？"

WOODIE.DESCRIBE.KYNO_PUFFERMONSTER = "小心点，那家伙看起来像个麻烦精，对吧？"

WOODIE.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "我知道你就在下面，伙计。"
WOODIE.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "加油！"
WOODIE.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "它很强大，而且非常自由。"
WOODIE.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "那是个大块头，对吧。"

WOODIE.DESCRIBE.KYNO_BLUBBER = "别再哭哭啼啼了。"

WOODIE.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "尝起来像夏日湖水。不错吧？"
WOODIE.DESCRIBE.KYNO_FISHMEAT_DRIED = "这才是正宗的肉干，对吧？"

WOODIE.DESCRIBE.MONKEYISLANDMEAL = "这组合可真够奇特的，对吧？但效果意外地好！"

WOODIE.DESCRIBE.KYNO_BRAINROCK_LARVAE = "真是个小混蛋。"
WOODIE.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "不舒服的顺滑。"
WOODIE.DESCRIBE.KYNO_BRAINROCK_CORAL = "真聪明。"

WOODIE.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "What're you, some sort of keener?",
	PICKED = "Guess it's takin' a break, eh?",
}

WOODIE.DESCRIBE.BRAINMETTERSOUP = "虽然我已经长大了，但我还是喜欢它。"

WOODIE.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "How you holding up out here, guy?",
	SLEEPING = "Guess he's turning in.",
}

WOODIE.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "谢啦，兄弟！"

WOODIE.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "This better not attract any feathered vermin.",
	WAITING = "It was bound to happen soon or later.",
}

WOODIE.DESCRIBE.KYNO_PACKIMBAGGIMS = "我能忍受他。"

WOODIE.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "我最好开始准备些材料了。"
WOODIE.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "我还需要更多东西来完成它。"
WOODIE.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "这蛋糕可真够漂亮的，对吧？"
WOODIE.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "确实让气氛活跃起来了。"
WOODIE.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "让我不禁想起我们共同经历的那些欢庆时刻。"
WOODIE.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "周年庆蛋糕最棒了，对吧？"
WOODIE.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "没有气球，派对可就没意思了，对吧？"

WOODIE.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "Better not burn the forest, eh?",
	FUEL_HIGH = "Running smooth as butter.",
	FUEL_MED = "Still kicking.",
	FUEL_LOW = "Better toss in some fuel.",
	EMPTY = "She's outta fuel.",
}

WOODIE.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "庆祝活动再合适不过了，对吧？"
WOODIE.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "嗯，看起来真有节日气氛，对吧？"
WOODIE.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "这还挺好的。"

WOODIE.DESCRIBE.KYNO_FISHREGISTRYHAT = "帮我记住各种不同的鱼。"

WOODIE.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "Keeps the animals happy, eh?",
	FUEL_HIGH = "Full as can be!",
	FUEL_MED = "Still got some feed in there.",
	FUEL_LOW = "Better top it up soon.",
	EMPTY = "All outta feed.",
	BURNT = "Well, that's done for.",
}