local WILSON = STRINGS.CHARACTERS.GENERIC

WILSON.ANNOUNCE_KYNO_COFFEEBUFF_START = "快！"
WILSON.ANNOUNCE_KYNO_COFFEEBUFF_END = "我现在变慢了！"

WILSON.ANNOUNCE_KYNO_HASTEBUFF_START = "更快的制作！"
WILSON.ANNOUNCE_KYNO_HASTEBUFF_END = "我的手发呆了！"

WILSON.ANNOUNCE_KYNO_POPBUFF_START = "（嗝！）哦，抱歉。"
WILSON.ANNOUNCE_KYNO_POPBUFF_END = "我现在感觉好多了。"

WILSON.ANNOUNCE_KYNO_FROGBUFF_START = "我觉得有点...青蛙？"
WILSON.ANNOUNCE_KYNO_FROGBUFF_END = "噢，我有点喜欢当一只青蛙......"

WILSON.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝!) 我的海盗感觉很刺痛!"
WILSON.ANNOUNCE_KYNO_PIRATEBUFF_END = "我现在感觉好多了。"

WILSON.ANNOUNCE_KYNO_FREEZEBUFF_START = "手都凉了！"
WILSON.ANNOUNCE_KYNO_FREEZEBUFF_END = "哎哟，我想恢复正常了。"

WILSON.ANNOUNCE_KYNO_FIREBUFF_START = "手在发热！"
WILSON.ANNOUNCE_KYNO_FIREBUFF_END = "哎哟，我想恢复正常了。"

WILSON.ANNOUNCE_KYNO_FISHINGBUFF_START = "钓鱼时间到了！"
WILSON.ANNOUNCE_KYNO_FISHINGBUFF_END = "钓鱼力量结束了！"

WILSON.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "我感到很平静。"
WILSON.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "我可以重新开始思考。"

WILSON.ANNOUNCE_KYNO_EATERBUFF_START = "我的牙齿更强壮了！"
WILSON.ANNOUNCE_KYNO_EATERBUFF_END = "我的牙齿变弱了！"

WILSON.ANNOUNCE_KYNO_WORMBUFF_START = "我准备战斗了。"
WILSON.ANNOUNCE_KYNO_WORMBUFF_END = "结束了!"

WILSON.ANNOUNCE_KYNO_CRABBUFF_START = "我准备战斗了。"
WILSON.ANNOUNCE_KYNO_CRABBUFF_END = "结束了!"

WILSON.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝！) 青蛙们，准备好了！"
WILSON.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "我现在感觉好多了。"

WILSON.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "我能感觉到力量...!"
WILSON.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "啊，太令人窒息了。"

WILSON.ANNOUNCE_KYNO_STEALTHBUFF_START = "我消失了！"
WILSON.ANNOUNCE_KYNO_STEALTHBUFF_END = "啊，真糟糕！他们现在能发现我了。"

WILSON.ANNOUNCE_KYNO_FEARBUFF_START = "我无所畏惧！"
WILSON.ANNOUNCE_KYNO_FEARBUFF_END = "那种感觉...它回来了。"

WILSON.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "我的力量……被释放了！"
WILSON.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "唉，魔力消散了。"

WILSON.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "看起来我有了一些新朋友！"
WILSON.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "看起来我的猪朋友要离开了……"

WILSON.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "我的皮肤感觉……更坚韧了！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WILSON.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "我感觉奇怪地……免疫了。"
WILSON.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "呃……我想保护失效了。"

WILSON.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "我豁然开朗！随时随地都能创作！"
WILSON.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "看来我的天才运已经用尽了。"

WILSON.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "这些蜜蜂在我身边异常安静。"
WILSON.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "呃哦，蜜蜂又变得暴躁了。"

WILSON.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "我觉得自己……更强了！"
WILSON.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "唉，这好景不长。"

WILSON.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "我觉得我现在能吃得更多了！"
WILSON.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "哎呀，食欲又恢复正常了……"

WILSON.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "我现在头脑如此清醒！"
WILSON.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "又开始担心了……"

WILSON.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "我感觉有超自然的力量在加强我的防御！"
WILSON.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "保护作用正在减弱。"

WILSON.ANNOUNCE_KYNO_BERSERKERBUFF_START = "Fascinating! My strength has increased, though at a cost..."
WILSON.ANNOUNCE_KYNO_BERSERKERBUFF_END = "My heightened aggression seems to have subsided."

WILSON.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "Interesting! My metabolism seems more efficient."
WILSON.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "My hunger rate appears to be normal again."

WILSON.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "不是这个。"

WILSON.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "他想要别的东西。"

WILSON.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "还太小了。"

WILSON.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "没有。"

WILSON.ANNOUNCE_KYNO_POTHANGER_FAIL = "需要一个锅。"

WILSON.ANNOUNCE_KYNO_CASSEROLE_FAIL = "需要一个砂锅。"

WILSON.ANNOUNCE_KYNO_SAPHEALER_USED = "I must remind myself to not let this happen again."

WILSON.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "科学说……肉可不会树上长！"

WILSON.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "空了！萨米肯定把它清空了。"

WILSON.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "该死，小径消失在波涛中……"
WILSON.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "雨水冲刷了所有的一切……"
WILSON.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "海浪之下，有大事正在酝酿……"

WILSON.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "蛋糕烤好了！是时候庆祝啦！"

WILSON.ANNOUNCE_KYNO_FISH_RESEARCHED = "我对这条鱼有了新的了解。"
WILSON.ANNOUNCE_KYNO_ROE_RESEARCHED = "我对这些鱼卵有了新的了解。"

WILSON.DESCRIBE.KYNO_ROE = "是鱼宝宝们。"
WILSON.DESCRIBE.KYNO_ROE_COOKED = "鱼子，阳光面朝上。"

WILSON.DESCRIBE.KYNO_SHARK_FIN = "光滑的鱼鳍。"

WILSON.DESCRIBE.KYNO_BEANBUGS = "豆子，有腿。"
WILSON.DESCRIBE.KYNO_BEANBUGS_COOKED = "我敢肯定它的味道比看起来好。"

WILSON.DESCRIBE.KYNO_GUMMYBUG = "小小凝胶物。"
WILSON.DESCRIBE.KYNO_GUMMYBUG_COOKED = "我非常渴望食物。"

WILSON.DESCRIBE.KYNO_WHEAT = "看起来有点颗粒感。"
WILSON.DESCRIBE.KYNO_WHEAT_COOKED = "看起来有点颗粒感。"

WILSON.DESCRIBE.KYNO_FLOUR = "用于制作面包。"

WILSON.DESCRIBE.KYNO_SPOTSPICE = "美味。"

WILSON.DESCRIBE.KYNO_SAP = "它尝起来很甜。"
WILSON.DESCRIBE.KYNO_SAP_SPOILED = "不如把它扔进火里。"

WILSON.DESCRIBE.KYNO_SYRUP = "为食品添加甜味。"

WILSON.DESCRIBE.KYNO_COFFEEBEANS = "他们需要一些烘焙。"
WILSON.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "热量确实改善了它们。"

WILSON.DESCRIBE.DUG_KYNO_COFFEEBUSH = "Now it can grow somewhere better."

WILSON.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "This is a plant I could learn to love.",
	PICKED = "I'll need to wait for the beans to grow back.",
	WITHERED = "It's far too wet to produce anything.",
}

WILSON.DESCRIBE.DUG_KYNO_SPOTBUSH = "I should plant it somewhere suitable."

WILSON.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "It reminds me of those tentacle monsters.",
	PICKED = "It needs time to recover.",
	BURNING = "There goes the shrub.",
}

WILSON.DESCRIBE.KYNO_SPOTSPICE_LEAF = "我可以把它磨成香料。"

WILSON.DESCRIBE.KYNO_MUSSEL = "可以使用一些火。"
WILSON.DESCRIBE.KYNO_MUSSEL_COOKED = "我烤了一只贻贝。"

WILSON.DESCRIBE.KYNO_HUMANMEAT = "肉就是肉，我该在哪里下嘴？"
WILSON.DESCRIBE.KYNO_HUMANMEAT_COOKED = "烤得很好，呈粉红色，但在道德上仍然是灰色的。"
WILSON.DESCRIBE.KYNO_HUMANMEAT_DRIED = "呃。"

WILSON.DESCRIBE.COFFEE = "闻起来很香，很有活力！"

WILSON.DESCRIBE.BISQUE = "做的菜肯定让我喝得津津有味！"

WILSON.DESCRIBE.JELLYOPOP = "果冻，直接放进我嘴里！"

WILSON.DESCRIBE.SHARKFINSOUP = "这是鲨鱼加工的！"

WILSON.DESCRIBE.TROPICALBOUILLABAISSE = "传统马赛菜的创新风味。"

WILSON.DESCRIBE.MUSSELBOUILLABAISE = "嗯，闻起来很香！"

WILSON.DESCRIBE.SWEETPOTATOSOUFFLE = "完美烹制！"

WILSON.DESCRIBE.FEIJOADA = "欧式西餐！"

WILSON.DESCRIBE.GUMMY_CAKE = "耐嚼的糖果。"

WILSON.DESCRIBE.HARDSHELL_TACOS = "我很确定这些不是普通的炸玉米饼壳。"

WILSON.DESCRIBE.ICEDTEA = "啊……恰到好处。"

WILSON.DESCRIBE.NETTLELOSANGE = "药用营养品。"

WILSON.DESCRIBE.SNAKEBONESOUP = "没有什么比一碗热腾腾的汤更好的了。"

WILSON.DESCRIBE.STEAMEDHAMSANDWICH = "尝起来像快餐。"

WILSON.DESCRIBE.TEA = "下午茶时间！"

WILSON.DESCRIBE.BUBBLETEA = "我为珍奶尖叫！"

WILSON.DESCRIBE.FRENCHONIONSOUP = "洋葱菜制成的最佳方式。"

WILSON.DESCRIBE.SLAW = "蔬菜。这么多蔬菜。"

WILSON.DESCRIBE.LOTUSBOWL = "由大自然制成。"

WILSON.DESCRIBE.POI = "经典夏威夷大餐。"

WILSON.DESCRIBE.JELLYBEAN_HUNGER = "一份果冻，一份豆子。"
WILSON.DESCRIBE.JELLYBEAN_SUPER = "一份果冻，一份豆子。"
WILSON.DESCRIBE.JELLYBEAN_SANITY = "一份果冻，一份豆子。"

WILSON.DESCRIBE.BOWLOFGEARS = "不可食用。"

WILSON.DESCRIBE.LONGPIGMEAL = "这是个糟糕的主意。"

WILSON.DESCRIBE.CUCUMBERSALAD = "这就是我所说的健康食品。"

WILSON.DESCRIBE.DUG_KYNO_WILDWHEAT = "I should plant it somewhere better."

WILSON.DESCRIBE.KYNO_WILDWHEAT =
{
	GENERIC = "Wild grain, growing freely.",
	PICKED = "It needs time to grow back.",
	WITHERED = "It's far too dry to survive.",
	BURNING = "All that grain is lost.",
}

WILSON.DESCRIBE.KYNO_MEALGRINDER = "我可以用它粉碎东西。"

WILSON.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "Are those mushrooms? I'm stumped.",
	PICKED = "They will grow back, eventually.",
	BURNING = "Waste of precious mushrooms.",
}

WILSON.DESCRIBE.GORGE_BREAD = "蓬松的一块面包。"
WILSON.DESCRIBE.GORGE_SWEET_CHIPS = "脆脆的。"
WILSON.DESCRIBE.GORGE_VEGETABLE_SOUP = "所有蔬菜烹饪而成。"
WILSON.DESCRIBE.GORGE_JELLY_SANDWICH = "又甜又脆。"
WILSON.DESCRIBE.GORGE_FISH_STEW = "一大块鱼肉。"
WILSON.DESCRIBE.GORGE_MEAT_STEW = "一份炖肉，让我的骨头长肉。"
WILSON.DESCRIBE.GORGE_ONION_CAKE = "蛋糕是个谎言！"
WILSON.DESCRIBE.GORGE_POTATO_PANCAKES = "煎饼！"
WILSON.DESCRIBE.GORGE_POTATO_SOUP = "软软的。"
WILSON.DESCRIBE.GORGE_FISHBALL_SKEWERS = "需要多一点胡椒粉。"
WILSON.DESCRIBE.GORGE_MEAT_SKEWERS = "需要多一点胡椒粉。"
WILSON.DESCRIBE.GORGE_STONE_SOUP = "我不应该吃那个。"
WILSON.DESCRIBE.GORGE_CROQUETTE = "闻起来很香。"
WILSON.DESCRIBE.GORGE_ROAST_VEGETABLES = "很多蔬菜。"
WILSON.DESCRIBE.GORGE_MEATLOAF = "一条肉面包。"
WILSON.DESCRIBE.GORGE_CARROT_SOUP = "蔬菜汤。"
WILSON.DESCRIBE.GORGE_FISHPIE = "鱼做的馅饼。"
WILSON.DESCRIBE.GORGE_FISHCHIPS = "鱼腥味和脆脆的。"
WILSON.DESCRIBE.GORGE_MEATPIE = "一块肉馅饼！"
WILSON.DESCRIBE.GORGE_SLIDERS = "小汉堡。"
WILSON.DESCRIBE.GORGE_JELLY_ROLL = "水果卷。"
WILSON.DESCRIBE.GORGE_CARROT_CAKE = "蛋糕是个谎言！"
WILSON.DESCRIBE.GORGE_GARLICMASHED = "大蒜和土豆混合在一起。"
WILSON.DESCRIBE.GORGE_GARLICBREAD = "适合烘烤。"
WILSON.DESCRIBE.GORGE_TOMATO_SOUP = "所有番茄根。"
WILSON.DESCRIBE.GORGE_SAUSAGE = "嗯……"
WILSON.DESCRIBE.GORGE_CANDIEDFISH = "糖果鱼。"
WILSON.DESCRIBE.GORGE_STUFFEDMUSHROOM = "蘑菇与蔬菜混合。"
WILSON.DESCRIBE.GORGE_BRUSCHETTA = "我希望它很好。"
WILSON.DESCRIBE.GORGE_HAMBURGER = "汉堡包！"
WILSON.DESCRIBE.GORGE_FISHBURGER = "一个鱼汉堡。"
WILSON.DESCRIBE.GORGE_MUSHROOMBURGER = "蘑菇汉堡。"
WILSON.DESCRIBE.GORGE_FISH_STEAK = "一大块鱼肉。"
WILSON.DESCRIBE.GORGE_CURRY = "所有的蔬菜和肉类。"
WILSON.DESCRIBE.GORGE_SPAGHETTI = "经典之作。"
WILSON.DESCRIBE.GORGE_POACHEDFISH = "鱼腥味。"
WILSON.DESCRIBE.GORGE_SHEPHERD_PIE = "羊？"
WILSON.DESCRIBE.GORGE_CANDY = "如果我吃了这个，我的牙医会生气......但我没有。"
WILSON.DESCRIBE.GORGE_BREAD_PUDDING = "这是布丁。"
WILSON.DESCRIBE.GORGE_BERRY_TART = "水果糖果。"
WILSON.DESCRIBE.GORGE_MACARONI = "经典之作。"
WILSON.DESCRIBE.GORGE_BAGEL_AND_FISH = "鱼和面包。"
WILSON.DESCRIBE.GORGE_GRILLED_CHEESE = "早上好世界！"
WILSON.DESCRIBE.GORGE_CREAMMUSHROOM = "天然奶油汤。"
WILSON.DESCRIBE.GORGE_MANICOTTI = "闻起来超级香！"
WILSON.DESCRIBE.GORGE_CHEESEBURGER = "芝士汉堡！"
WILSON.DESCRIBE.GORGE_FETTUCCINE = "奶油味。"
WILSON.DESCRIBE.GORGE_ONION_SOUP = "全在洋葱上。"
WILSON.DESCRIBE.GORGE_BREADED_CUTLET = "面包和肉一起吃。"
WILSON.DESCRIBE.GORGE_CREAMY_FISH = "奶油味。"
WILSON.DESCRIBE.GORGE_PIZZA = "我不敢相信！这是披萨！"
WILSON.DESCRIBE.GORGE_POT_ROAST = "一大堆肉。"
WILSON.DESCRIBE.GORGE_CRAB_CAKE = "可爱。"
WILSON.DESCRIBE.GORGE_STEAK_FRITES = "美式风格。"
WILSON.DESCRIBE.GORGE_SHOOTER_SANDWICH = "嗯……"
WILSON.DESCRIBE.GORGE_BACON_WRAPPED = "经典早餐。"
WILSON.DESCRIBE.GORGE_CRAB_ROLL = "我已经闻到蟹肉的味道了！"
WILSON.DESCRIBE.GORGE_MEAT_WELLINGTON = "它来自威灵顿。"
WILSON.DESCRIBE.GORGE_CRAB_RAVIOLI = "螃蟹。"
WILSON.DESCRIBE.GORGE_CARAMEL_CUBE = "Kyno最喜欢的菜。"
WILSON.DESCRIBE.GORGE_SCONE = "经典甜点。"
WILSON.DESCRIBE.GORGE_TRIFLE = "几乎是冰淇淋。"
WILSON.DESCRIBE.GORGE_CHEESECAKE = "传说中的蛋糕！"

WILSON.DESCRIBE.DUCKYOUGLERMZ = "致我们心爱的主播Glermz，这是我制作的。"

WILSON.DESCRIBE.KYNO_ALOE = "我敢打赌这对我们有好处"
WILSON.DESCRIBE.KYNO_ALOE_COOKED = "我做的！"
WILSON.DESCRIBE.KYNO_ALOE_GROUND = "我敢打赌这对我们有好处"
WILSON.DESCRIBE.KYNO_ALOE_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.FARM_PLANT_KYNO_ALOE = "科学和营养。"
WILSON.DESCRIBE.KYNO_ALOE_OVERSIZED = "科学和营养。"
WILSON.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "坏掉了。"

WILSON.DESCRIBE.KYNO_CUCUMBER = "我的口袋都湿透了，恶心。"
WILSON.DESCRIBE.KYNO_CUCUMBER_COOKED = "它比固体更接近液体。"
WILSON.DESCRIBE.KYNO_CUCUMBER_GROUND = "我的口袋都湿透了，恶心。"
WILSON.DESCRIBE.KYNO_CUCUMBER_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "我的口袋都湿透了，恶心。"
WILSON.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "我的口袋都湿透了，恶心。"
WILSON.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "我的口袋都湿透了，恶心。"

WILSON.DESCRIBE.KYNO_RADISH = "看起来很萝卜。"
WILSON.DESCRIBE.KYNO_RADISH_COOKED = "我想知道这是否让它变得更好吃。"
WILSON.DESCRIBE.KYNO_RADISH_GROUND = "看起来很萝卜。"
WILSON.DESCRIBE.KYNO_RADISH_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.FARM_PLANT_KYNO_RADISH = "它看起来非常漂亮。"
WILSON.DESCRIBE.KYNO_RADISH_OVERSIZED = "它看起来非常漂亮。"
WILSON.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "坏掉了。"

WILSON.DESCRIBE.KYNO_FENNEL = "它像胡萝卜，但是是绿色的。"
WILSON.DESCRIBE.KYNO_FENNEL_COOKED = "它怎么没变成馅饼？"
WILSON.DESCRIBE.KYNO_FENNEL_GROUND = "它像胡萝卜，但是是绿色的。"
WILSON.DESCRIBE.KYNO_FENNEL_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "它就像胡萝卜，不过是绿色的。"
WILSON.DESCRIBE.KYNO_FENNEL_OVERSIZED = "它就像胡萝卜，不过是绿色的。"
WILSON.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "坏掉了。"

WILSON.DESCRIBE.KYNO_SWEETPOTATO = "看起来不错！"
WILSON.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "看起来更美味！"
WILSON.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "看起来不错！"
WILSON.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "看起来很好吃!"
WILSON.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "看起来很好吃!"
WILSON.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "坏掉了。"

WILSON.DESCRIBE.KYNO_PARZNIP = "全是蔬菜。"
WILSON.DESCRIBE.KYNO_PARZNIP_COOKED = "烤熟的欧洲防风草。"
WILSON.DESCRIBE.KYNO_PARZNIP_EATEN = "欧洲防风草。"
WILSON.DESCRIBE.KYNO_PARZNIP_GROUND = "欧洲防风草。"
WILSON.DESCRIBE.KYNO_PARZNIP_BIG = "哇。哇哦。"
WILSON.DESCRIBE.KYNO_PARZNIP_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "欧洲防风草。"
WILSON.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "欧洲防风草。"
WILSON.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "坏掉了。"

WILSON.DESCRIBE.KYNO_TURNIP = "这是一个生萝卜。"
WILSON.DESCRIBE.KYNO_TURNIP_COOKED = "烹饪是实践中的科学。"
WILSON.DESCRIBE.KYNO_TURNIP_GROUND = "这是一个生萝卜。"
WILSON.DESCRIBE.KYNO_TURNIP_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "这是一个生萝卜。"
WILSON.DESCRIBE.KYNO_TURNIP_OVERSIZED = "这是一个生萝卜。"
WILSON.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "坏掉了。"

WILSON.DESCRIBE.KYNO_RICE = "我想，这是一种很好的蔬菜。"
WILSON.DESCRIBE.KYNO_RICE_COOKED = "我想，这是一种很好的蔬菜。"
WILSON.DESCRIBE.KYNO_RICE_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "这是一粒种子。"
WILSON.DESCRIBE.FARM_PLANT_KYNO_RICE = "这是稻米植物。"
WILSON.DESCRIBE.KYNO_RICE_OVERSIZED = "这是稻米植物。"
WILSON.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "坏掉了。"

WILSON.DESCRIBE.KYNO_SEEDS_KIT = "满满一包种子"

WILSON.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "I could fill a pail with all those snails.",
	PICKED = "Will need to wait until the snails crawl back.",
	WITHERED = "Not going to grow anything in this state.",
}

WILSON.DESCRIBE.KYNO_LIMPETS = "也许挨饿不会那么糟糕。"
WILSON.DESCRIBE.KYNO_LIMPETS_COOKED = "蜗牛！"

WILSON.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "The science is blooming well this season.",
	PICKED = "Needs some time to regrow its flower.",
	BURNING = "Oh no, that's really bad.",
}

WILSON.DESCRIBE.KYNO_LOTUS_ROOT = "某种湿生植物，我能种下它来培育更多湿生植物。"
WILSON.DESCRIBE.KYNO_LOTUS_FLOWER = "一朵可爱的科学花。"
WILSON.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "美味佳肴。"

WILSON.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "Is that what passes for food around here?",
	PICKED = "They'll grow back. I hope.",
	BURNING = "Another marine plant lost to the fire.",
}

WILSON.DESCRIBE.KYNO_SEAWEEDS = "一种杂草。来自海洋。"
WILSON.DESCRIBE.KYNO_SEAWEEDS_COOKED = "脆皮。"
WILSON.DESCRIBE.KYNO_SEAWEEDS_DRIED = "咸！"
WILSON.DESCRIBE.KYNO_SEAWEEDS_ROOT = "我可以种植一些湿粘液来制造更多湿粘液。"

WILSON.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "So purple.",
	PICKED = "These waters will help it grow back faster.",
	BURNING = "Looks like I've lost another root.",
}

WILSON.DESCRIBE.KYNO_TAROROOT_ROOT = "有些湿球我能种下，再培育出更多湿球。"
WILSON.DESCRIBE.KYNO_TAROROOT = "看起来像紫胡椒。"
WILSON.DESCRIBE.KYNO_TAROROOT_COOKED = "它的紫色更少。"

WILSON.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "That's new.",
	PICKED = "I hope this grows back soon enough.",
	BURNING = "Well. That's unfortunate.",
}

WILSON.DESCRIBE.KYNO_WATERYCRESS_ROOT = "一些湿漉漉的杂草，我种下去还能长出更多湿漉漉的杂草。"
WILSON.DESCRIBE.KYNO_WATERYCRESS = "这是新的。"

WILSON.DESCRIBE.WATERYCRESSBOWL = "闻起来像它的味道。"

WILSON.DESCRIBE.KYNO_SALT = "里面全是盐。"

WILSON.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "Mussels are growing on it.",
	PICKED = "I'll need to wait for more mussels.",
	BURNING = "There go the mussels.",
}

WILSON.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "我真的要把它粘在那些贻贝上。"

WILSON.DESCRIBE.CATFOOD = "给我的猫吃的零食！"

WILSON.DESCRIBE.KATFOOD = "给我的猫吃的零食！"

WILSON.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "It's a rare banana tree.",
	PICKED = "Needs some time to regrow its product.",
	CHOPPED = "No more bananas for it or me.",
	BURNING = "Too bad we lost another rare tree.",
	BURNT = "Nothing but ashes left.",
}

WILSON.DESCRIBE.KYNO_BANANA = "它是糊状的。"
WILSON.DESCRIBE.KYNO_BANANA_COOKED = "好吃！"

WILSON.DESCRIBE.KYNO_KOKONUTTREE =
{
	GENERIC = "How tropical.",
	PICKED = "I need to wait a little bit if I want more coconuts.",
	CHOPPED = "It won't give me any coconuts now.",
	BURNING = "I could've prevented that.",
	BURNT = "Ashes to ashes.",
}

WILSON.DESCRIBE.KYNO_KOKONUT = "这种水果必须在它的盔甲下隐藏什么秘密？"
WILSON.DESCRIBE.KYNO_KOKONUT_HALVED = "当我同时点击它们时，它们会发出马蹄声。"
WILSON.DESCRIBE.KYNO_KOKONUT_COOKED = "现在我只需要一块蛋糕。"

WILSON.DESCRIBE.BOWLOFPOPCORN = "现在我只差一部电影。"

WILSON.DESCRIBE.FIGJUICE = "啊……好老的果汁。"

WILSON.DESCRIBE.COCONUTWATER = "水，但来自椰子。"

WILSON.DESCRIBE.EYEBALLSPAGHETTI = "这是不对的。"

WILSON.DESCRIBE.FORGETMELOTS_SEEDS = "这是一粒种子。"

WILSON.DESCRIBE.FIRENETTLES_SEEDS = "这是一粒种子。"

WILSON.DESCRIBE.TILLWEED_SEEDS = "这是一粒种子。"

WILSON.DESCRIBE.KYNO_FLOATILIZER = "这绝对是一桶海粪。"

WILSON.DESCRIBE.KYNO_TWIGGYNUTS = "一堆坚果。"

WILSON.DESCRIBE.KYNO_REPAIRTOOL = "一个简陋的修理包。"

WILSON.DESCRIBE.KYNO_KOI = "对于生活在水中的东西来说，这有点漂亮。"
WILSON.DESCRIBE.KYNO_KOI_COOKED = "这就是真正的热带麦柯伊！"

WILSON.DESCRIBE.KYNO_TROPICALFISH = "多么热带的鱼啊。"
WILSON.DESCRIBE.KYNO_TROPICALFISH_COOKED = "我喜欢红烧。"

WILSON.DESCRIBE.KYNO_NEONFISH = "它看起来像一条鱼，但感觉很湿。"
WILSON.DESCRIBE.KYNO_NEONFISH_COOKED = "炸薯条。"

WILSON.DESCRIBE.KYNO_GROUPER = "冲浪和草皮，抓住草皮。"
WILSON.DESCRIBE.KYNO_GROUPER_COOKED = "那条鱼已经吃完了。"
 
WILSON.DESCRIBE.KYNO_PIERROTFISH = "找到你了！"
WILSON.DESCRIBE.KYNO_PIERROTFISH_COOKED = "烤到完美。"

WILSON.DESCRIBE.KYNO_SALMONFISH = "嗯，新鲜的鱼。"
WILSON.DESCRIBE.KYNO_SALMONFISH_COOKED = "准备上餐桌。"

WILSON.DESCRIBE.TURF_PINKPARK = "太粉红了！"
WILSON.DESCRIBE.TURF_STONECITY = "如此明亮和白色。"
WILSON.DESCRIBE.TURF_FIELDS = "这是一块土地。"
WILSON.DESCRIBE.TURF_TIDALMARSH = "沼泽地。"

WILSON.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "Salt has gathered on the rope.",
	PICKED = "Science takes time.",
}

WILSON.DESCRIBE.KYNO_SALTRACK_INSTALLER = "用于从池塘中收获盐分。"

WILSON.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "我们可以用它来收集树上的汁液。"

WILSON.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "一个狡猾的陷阱。"

WILSON.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "I guess you're in charge around here?",
	SLEEPING = "Can't really wake up him right now.",
}

WILSON.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "It's full of delicious, delicious sap.",
	CHOPPED = "Where'd the tree go? I'm stumped.",
	SAPPED = "Sweet golden sap.",
	PICKED = "Here sappy, sappy, sap.",
	BURNING = "There goes the sap... and the tree.",
	BURNT = "Just a charred reminder of poor decisions.",
}

WILSON.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "It looks ill.",
	CHOPPED = "It wasn't much use anyway.",
	SAPPED = "The sap is ruined, but harvestable.",
	PICKED = "That's how you get ants.",
	BURNING = "Probably for the best.",
	BURNT = "No fixing for that.",
}

WILSON.DESCRIBE.KYNO_SUGARTREE_BUD = "它有糖味。"

WILSON.DESCRIBE.KYNO_SUGARTREE_FLOWER = "很漂亮。而且闻起来像糖。"
WILSON.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "很漂亮。而且闻起来像糖。"

WILSON.DESCRIBE.KYNO_SUGARTREE_PETALS = "很漂亮。而且闻起来像糖。"

WILSON.DESCRIBE.KYNO_PEBBLECRAB = "那块石头还活着！"

WILSON.DESCRIBE.KYNO_CRABMEAT = "这里没有模仿。"
WILSON.DESCRIBE.KYNO_CRABMEAT_COOKED = "我可以在紧要关头做一顿饭。"
WILSON.DESCRIBE.KYNO_CRABMEAT_DRIED = "这里没有仿制品。"

WILSON.DESCRIBE.KYNO_CRABKINGMEAT = "这里没有假货。"
WILSON.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "这里没有假货。"
WILSON.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "这里没有假货。"

WILSON.DESCRIBE.KYNO_SLAUGHTERTOOL = "用于外科屠宰的实验室工具。"

WILSON.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "It's a little chicken.",
	COOP = "My very own chicken!",
}

WILSON.DESCRIBE.KYNO_CHICKEN_EGG = "一枚小小的鸡蛋。"
WILSON.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "That is one impressively large breakfast."
WILSON.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "好喝！"

WILSON.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "A proper home for chickens.",
	FULL = "The eggs are ready for harvest!",
	BURNT = "The chickens got evicted.",
}

WILSON.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "全部损坏。"

WILSON.DESCRIBE.KYNO_COOKWARE_KIT = "厨房用品。"
WILSON.DESCRIBE.KYNO_COOKWARE_SYRUP = "我需要给这个锅加糖。"
WILSON.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "我需要给这个锅加糖。"
WILSON.DESCRIBE.KYNO_COOKWARE_BIG_POT = "这个有更多成分。"
WILSON.DESCRIBE.KYNO_COOKWARE_BIG = "这个有更多成分。"
WILSON.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "我们开始做饭吧！"
WILSON.DESCRIBE.KYNO_COOKWARE_SMALL = "我们开始做饭吧！"
WILSON.DESCRIBE.KYNO_COOKWARE_GRILL = "现在我只需要一个后院把它放进去。"
WILSON.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "我必须为此盘问某人。"
WILSON.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "烧烤。"
WILSON.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "用于烤小肉。"
WILSON.DESCRIBE.KYNO_COOKWARE_ELDER = "我需要给这个锅加糖。"
WILSON.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "用于科学燃烧东西。"
WILSON.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "适合所有调味料的菜肴。"
WILSON.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "用来做一些杂七杂八的小东西。"
WILSON.DESCRIBE.KYNO_COOKWARE_OVEN = "科学需要原料。"
WILSON.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "它需要原料才能发挥作用。"
WILSON.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "它需要原料才能发挥作用。"

WILSON.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "You never know what you'll find under a rock.",
	FLIPPED = "There was some stuff underneath it.",
}

WILSON.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "当然，我可以把它敲出来。"

WILSON.DESCRIBE.KYNO_SUGARFLY = "糖蝴蝶，飘过。"
WILSON.DESCRIBE.KYNO_SUGARFLYWINGS = "没有这些，什么都不是。"

WILSON.DESCRIBE.KYNO_WATERY_CRATE = "当然，我可以把它敲出来。但我应该吗？"

WILSON.DESCRIBE.KYNO_TUNACAN = "这是从哪里来的？"
WILSON.DESCRIBE.KYNO_TUNACAN_OPEN = "这是从哪里来的？"

WILSON.DESCRIBE.KYNO_CANNEDFOOD = "这是从哪里来的？"
WILSON.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "这是从哪里来的？"

WILSON.DESCRIBE.KYNO_POP = "这是什么物质？"

WILSON.DESCRIBE.KYNO_MYSTERYMEAT = "我没有剖析那个。"

WILSON.DESCRIBE.KYNO_BOTTLE_SOUL = "这很奇怪。"

WILSON.DESCRIBE.SOULSTEW = "这很奇怪。"

WILSON.DESCRIBE.FORTUNECOOKIE = "我今天运气怎么样？"

WILSON.DESCRIBE.HORNOCUPIA = "光是看着就让我肚子咕咕叫。"

WILSON.DESCRIBE.CHEESE_YELLOW = "这是奶酪！"
WILSON.DESCRIBE.CHEESE_WHITE = "一块白奶酪。"
WILSON.DESCRIBE.CHEESE_KOALEFANT = "这是一种无尾熊奶酪！"

WILSON.DESCRIBE.MILK_BOX = "牛奶是否装在盒子里？"

WILSON.DESCRIBE.WATERCUP = "最常见的饮料。"

WILSON.DESCRIBE.HONEYJAR = "一罐蜂蜜！"

WILSON.DESCRIBE.CRAB_ARTICHOKE = "所以，今晚的晚餐是螃蟹。"

WILSON.DESCRIBE.PEPPERROLLS = "满满一嘴！"

WILSON.DESCRIBE.KYNO_SAPHEALER = "我不喝那个。"

WILSON.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "Poor little boat.",
	PICKED = "The snails will eventually grow back by the crashed vessel.",
	BURNING = "Now I'm certain that it will sink.",
}

WILSON.DESCRIBE.KYNO_GHOST_PIRATE = "他遭遇了惨烈的结局。若我不逃离此地，我也将步其后尘。"

WILSON.DESCRIBE.KYNO_BUCKET_EMPTY = "一个桶。"
WILSON.DESCRIBE.KYNO_BUCKET_METAL = "一个结实的桶，比木制的好。"
WILSON.DESCRIBE.KYNO_BUCKET_WATER = "不过是一桶普通的水罢了。"

WILSON.DESCRIBE.KYNO_MILK_BEEFALO = "新鲜牛奶！"
WILSON.DESCRIBE.KYNO_MILK_KOALEFANT = "新鲜牛奶！"

WILSON.DESCRIBE.KYNO_CAP_DRIED = "上好的新鲜干蘑菇。"

WILSON.DESCRIBE.KYNO_PLANTMEAT_DRIED = "够生涩了。"

WILSON.DESCRIBE.KYNO_BREWBOOK = "我一直渴望知识。"

WILSON.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "I wonder what I can make using this.",
	BREWING_LONG = "This will take some days to brew.",
	BREWING_SHORT = "Only a couple hours left for my brew.",
	DONE = "Looks like my brew is already done!",
	BURNT = "Looks like I'm not going to see that brew anymore.",
}

WILSON.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "For the making of jams.",
	BREWING_LONG = "Cured goodies sure takes a long time to make.",
	BREWING_SHORT = "It's almost mine!",
	DONE = "All that waiting game was totally worth it!",
	BURNT = "That's a sad end.",
}

WILSON.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "Take its sweet time making honey.",
	HONEY = "Looks like it's full of honeyed goods.",
	NECTAR = "The nectar is being processed.",
	BURNING = "All that sweetness is going up in smoke!",
}

WILSON.DESCRIBE.KYNO_NECTAR_POD = "我可以用它来做蜂蜜。"

WILSON.DESCRIBE.KYNO_OAKTREE_POD = "一棵橡树种子，准备好生长了。"
WILSON.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "拿下它，小树！"

WILSON.DESCRIBE.KYNO_PIKO = "他有点疯狂。"
WILSON.DESCRIBE.KYNO_PIKO_ORANGE = "不知为何我想喝茶。"

WILSON.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "What a lovely tree.",
	CHOPPED = "All the tea leaves are mine now!",
	BURNING = "Oh no!",
	BURNT = "I could've prevented that.",
}

WILSON.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE =
{
	GENERIC = "It's full of squirrels!",
	BURNING = "Good riddance. Now they don't have a tree to call home.",
}

WILSON.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "一定有办法打开它。"

WILSON.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "Who would live here?",
	BURNT = "Crispy.",
}

WILSON.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "Doesn't smell very good.",
	CRAFTED = "It's actually kind of cute.",
	BURNT = "Ugh, the smell!",
}

WILSON.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "These are some quite rare items in your display.",
	OCCUPIED = "Seems like the shop is closed for now.",
}

WILSON.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "What are you selling today?",
	EMPTY = "Its all empty. I'll come back later, Sammy.",
}

WILSON.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "嘿！我记得你在那个可怕的地方。"
WILSON.DESCRIBE.KYNO_MEADOWISLAND_POND = "潮汐留下的水池。"
WILSON.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "这是一种植物。"
WILSON.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "你最好别碰我的鞋。"
WILSON.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "你最好不要尝试任何可疑的事情。"

WILSON.DESCRIBE.KYNO_SAMMYHAT = "让我感觉自己像个商人。"

WILSON.DESCRIBE.KINGFISHER = "多么尖刻的账单！"

WILSON.DESCRIBE.TOUCAN = "我抓不住他。"
WILSON.DESCRIBE.TOUCAN_CHUBBY = "我抓不住他。"

WILSON.DESCRIBE.WETGOOP2 = "它尝起来什么都没有。"

WILSON.DESCRIBE.BEER = "适度饮酒。"

WILSON.DESCRIBE.PALEALE = "适度饮酒。"

WILSON.DESCRIBE.TEAGREEN = "一杯好茶！"

WILSON.DESCRIBE.TEARED = "一杯好茶！"

WILSON.DESCRIBE.MEAD = "甜！适量饮酒。"

WILSON.DESCRIBE.KYNO_JELLY = "现在，在罐子里！"

WILSON.DESCRIBE.KYNO_MAYONNAISE = "它看起来可以涂抹。"

WILSON.DESCRIBE.TARTARSAUCE = "哦不！这是鞑靼酱！"

WILSON.DESCRIBE.KYNO_PICKLES = "一罐你自制的泡菜。"

WILSON.DESCRIBE.KYNO_WINE = "一瓶好酒。"

WILSON.DESCRIBE.KYNO_JUICE = "一瓶不错的果汁。"

WILSON.DESCRIBE.KYNO_POISON_FROGLEGS = "看起来很毒。"
WILSON.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "受污染的炖肉。"

WILSON.DESCRIBE.POISONFROGGLEBUNWICH = "一个非常长腿和致命的三明治。"

WILSON.DESCRIBE.KYNO_BREWINGRECIPECARD = "科学帮助我，我无法破译这份笔迹。"

WILSON.DESCRIBE.KYNO_OIL = "这是一种烹饪原料。"

WILSON.DESCRIBE.BERRYSUNDAE = "我在这个星期天为圣代尖叫！"

WILSON.DESCRIBE.CHOCOLATE_BLACK = "终于来点甜巧克力了！"
WILSON.DESCRIBE.CHOCOLATE_WHITE = "终于来点甜巧克力了！"

WILSON.DESCRIBE.TRICOLORDANGO = "那些是什么？总之，它们很好吃！"
 
WILSON.DESCRIBE.FRIESFRENCH = "煮土豆的最佳方式。"

WILSON.DESCRIBE.PIRATERUM = "它看起来很危险。"

WILSON.DESCRIBE.TWISTEDTEQUILA = "记住，适量。这是一种烈性酒。"

WILSON.DESCRIBE.ONIONRINGS = "我个人不喜欢含油的食物。但必须承认这个很好。"

WILSON.DESCRIBE.DONUTS = "这是甜甜圈！"
WILSON.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "这是甜甜圈！"
WILSON.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "这是甜甜圈！"
 
WILSON.DESCRIBE.CINNAMONROLL = "我喜欢它在我嘴里“滚动”的方式。"

WILSON.DESCRIBE.GUMMYBEARGERS = "可爱，但也致命。"

WILSON.DESCRIBE.PRETZEL = "一块上釉加盐的饼干。"

WILSON.DESCRIBE.CORNINCUP = "杯子里的玉米！"

WILSON.DESCRIBE.COTTONCANDY = "这只是空气和糖！"

WILSON.DESCRIBE.ROASTEDHAZELNUTS = "有总比没有好。"

WILSON.DESCRIBE.MONSTERMUFFIN = "一块松饼，但有些不对劲。"

WILSON.DESCRIBE.PINKCAKE = "一个小指蛋糕，但谁在举办派对？！"

WILSON.DESCRIBE.CHIPSBAG = "不健康的零食。"

WILSON.DESCRIBE.LITTLEBREAD = "一块面包。"

WILSON.DESCRIBE.HOTHOUND = "热狗...！猎犬？"

WILSON.DESCRIBE.MILKSHAKE = "奶昔！"
WILSON.DESCRIBE.MILKSHAKE_PRISMATIC = "奶昔！"

WILSON.DESCRIBE.NACHOS = "吃了那个之后我的手指会很滑。"

WILSON.DESCRIBE.BANANA_PUDDING = "闻起来像香蕉。"

WILSON.DESCRIBE.SEA_PUDDING = "闻起来像鱼。"

WILSON.DESCRIBE.TOM_KHA_SOUP = "这汤味道不一样。"

WILSON.DESCRIBE.MINERTREAT = "这简直就是小孩子的游戏。"

WILSON.DESCRIBE.RADISHSALAD = "一碗萝卜。"

WILSON.DESCRIBE.PUMPKIN_SOUP = "烹饪确实让我精力充沛！"

WILSON.DESCRIBE.ALGAE_SOUP = "烹饪确实让我精力充沛！"

WILSON.DESCRIBE.PARZNIP_SOUP = "烹饪确实让我精力充沛！"

WILSON.DESCRIBE.NETTLEMEATED = "通过科学的肉类包装技术进行了改进。"

WILSON.DESCRIBE.KYNO_SUGAR = "看起来很好吃。"

WILSON.DESCRIBE.KYNO_BOTTLECAP = "一件超凡脱俗的物品。"

WILSON.DESCRIBE.NUKACOLA = "一杯超凡脱俗的饮料。"
WILSON.DESCRIBE.NUKACOLA_QUANTUM = "一杯超凡脱俗的饮料。"

WILSON.DESCRIBE.LIVINGSANDWICH = "食用不安全！"

WILSON.DESCRIBE.DURIANSPLIT = "另一种冰淇淋。"

WILSON.DESCRIBE.DURIANSOUP = "供应榴莲的最佳方式。"

WILSON.DESCRIBE.DURIANMEATED = "有臭味！"

WILSON.DESCRIBE.DURIANCHICKEN = "看起来很棒，适合素食者。"

WILSON.DESCRIBE.LUNARSOUP = "月球汤？"

WILSON.DESCRIBE.PURPLEWOBSTERSOUP = "龙虾汤？"

WILSON.DESCRIBE.WOBSTERMONSTER = "我认为它不能安全食用。"

WILSON.DESCRIBE.SPIDERCAKE = "我希望生日聚会一切顺利。"

WILSON.DESCRIBE.SUGARBOMBS = "百分百的糖。"

WILSON.DESCRIBE.BERRYBOMBS = "我可能应该制作一个罐子。"

WILSON.DESCRIBE.ONIGIRIS = "谁能想到米饭会这么好吃呢？"

WILSON.DESCRIBE.OMURICE = "番茄是一个很好的补充。"

WILSON.DESCRIBE.PAELLA = "噢啦！"

WILSON.DESCRIBE.RISOTTO = "好极了！"

WILSON.DESCRIBE.RICESAKE = "再给我来一杯！*嗝*"

WILSON.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "I uprooted the whole thing."

WILSON.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "Spiky!",
	PICKED = "It needs time to grow another pineapple.",
	WITHERED = "It's far too dry to grow anything.",
	BURNING = "There goes the pineapple.",
}

WILSON.DESCRIBE.KYNO_PINEAPPLE = "它需要一个裂缝。"
WILSON.DESCRIBE.KYNO_PINEAPPLE_HALVED = "一片精致的菠萝！"
WILSON.DESCRIBE.KYNO_PINEAPPLE_COOKED = "现在更好了。"

WILSON.DESCRIBE.PIZZA_TROPICAL = "争论仍在继续。"

WILSON.DESCRIBE.PINACOLADA = "冰冰的。"

WILSON.DESCRIBE.CHIMAS = "清爽的香草饮料。"

WILSON.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "Water you think it's for?",
	ON = "Keeps my farm plants watered and healthy.",
}

WILSON.DESCRIBE.KYNO_FOODSACK = "最讨厌食物带着不新鲜的味道了。"

WILSON.DESCRIBE.GUMMYWORMS = "至少它们现在不会吃我了。"

WILSON.DESCRIBE.SMORES = "简单又美味。"

WILSON.DESCRIBE.NUKASHINE = "哦，糟糕。我的头脑一片空白。"

WILSON.DESCRIBE.ANTSLOG = "真不敢相信，这不是蚂蚁！"

WILSON.DESCRIBE.KYNO_WORM_BONE = "哈哈，虫子，你的骨头在我这儿。"

WILSON.DESCRIBE.SPOOKY_BRAIN_NOODLES = "这面条真不错。"
WILSON.DESCRIBE.SPOOKY_BURGERZILLA = "俏皮的镜头！"
WILSON.DESCRIBE.SPOOKY_DEADBREAD = "一个邪恶的面包。"
WILSON.DESCRIBE.SPOOKY_JELLYBEANS = "他们都在看我！"
WILSON.DESCRIBE.SPOOKY_POPSICLE = "树的冰棍。"
WILSON.DESCRIBE.SPOOKY_PUMPKINCREAM = "雕刻南瓜并用冰淇淋填满是个好主意。"
WILSON.DESCRIBE.SPOOKY_SKULLCANDY = "这远远超出了科学的范畴。"
WILSON.DESCRIBE.SPOOKY_TACODILE = "害怕塔科迪雷!"

WILSON.DESCRIBE.BUTTER_BEEFALO = "我简直不敢相信这是它的黄油！"
WILSON.DESCRIBE.BUTTER_GOAT = "我简直不敢相信这是它的黄油！"
WILSON.DESCRIBE.BUTTER_KOALEFANT = "我简直不敢相信这是它的黄油！"

WILSON.DESCRIBE.SPICE_CURE = "这应该有助于处理变质的食物。"
WILSON.DESCRIBE.SPICE_COLD = "哇！我的手冻僵了！"
WILSON.DESCRIBE.SPICE_FIRE = "哎哟！它烫伤了我的手！"
WILSON.DESCRIBE.SPICE_FED = "这可以帮助我更有效地工作。"
WILSON.DESCRIBE.SPICE_MIND = "我已经感觉到我的头脑麻木了。"

WILSON.DESCRIBE.SUGARFLYMUFFIN = "我把食谱扔掉了，只是稍微翻了一下。"

WILSON.DESCRIBE.EELTACOS = "又脆又好吃！"

WILSON.DESCRIBE.MEATSKILLET = "只有一个锅！"

WILSON.DESCRIBE.MEATWALTZ = "希望我不会因为这种食物而生病。"

WILSON.DESCRIBE.COMPLETEBREAKFAST = "我已经准备好迎接世界了！"

WILSON.DESCRIBE.DUMPLINGS = "我发誓我在某个地方见过这个......"

WILSON.DESCRIBE.WARLYICEDTEA = "我强烈要求冰茶。"

WILSON.DESCRIBE.WARLYTEA = "喝茶时间！"

WILSON.DESCRIBE.KYNO_TEALEAF = "茶叶。"

WILSON.DESCRIBE.KYNO_ITEMSLICER = "我喜欢这个切割工具。"
WILSON.DESCRIBE.KYNO_ITEMSLICER_GOLD = "我喜欢这个切割工具。"

WILSON.DESCRIBE.COXINHA = "这是一份鸡肉下午点心。"

WILSON.DESCRIBE.LAZYDESSERT = "哈！双关语是...哈。你知道的。"

WILSON.DESCRIBE.CRABKINGFEAST = "锅里小，外面大！"

WILSON.DESCRIBE.PIENAPPLE = "这看起来不像我的头发，薇洛。"

WILSON.DESCRIBE.JAWSBREAKER = "它非常迷人。"

WILSON.DESCRIBE.AVOCADOTOAST = "吐司和水果有点普通。"

WILSON.DESCRIBE.RICEPUDDING = "我猜很令人满意。"

WILSON.DESCRIBE.SHARKSUSHI = "我已经流口水了！"

WILSON.DESCRIBE.WOBSTERBREADED = "这顿饭真好吃。"

WILSON.DESCRIBE.LAZYPURRITO = "一只猫卷饼。"

WILSON.DESCRIBE.HORCHATA = "乳白色和寒冷。"

WILSON.DESCRIBE.WOBSTERCOCKTAIL = "龙虾绅士。"

WILSON.DESCRIBE.LAVAEEGGBOILED = "沃利最近有一些疯狂的想法。"

WILSON.DESCRIBE.POMEGRANATETEA = "我非常喜欢冰茶。"

WILSON.DESCRIBE.TIRAMISU = "沃利继续研究他的食谱......"

WILSON.DESCRIBE.TOADSTOOLCOLA = "有青蛙的味道。"

WILSON.DESCRIBE.TEPACHE = "与常见的菠萝饮料相比，这是一种令人耳目一新的选择。"

WILSON.DESCRIBE.LUNARTEQUILA = "太棒了。"

WILSON.DESCRIBE.MIMICMOSA = "隐蔽！"

WILSON.DESCRIBE.POMEGRANATEPIE = "别那样做，薇洛。"

WILSON.DESCRIBE.PINEAPPLECAKE = "薇洛，这是第二次了，这看起来不像我的头发！"

WILSON.DESCRIBE.PASTY_MEAT = "油炸小吃。"
WILSON.DESCRIBE.PASTY_CHEESE = "油炸小吃。"

WILSON.DESCRIBE.BRIGADEIRO = "巧克力球，表面覆盖着巧克力碎片。"

WILSON.DESCRIBE.REGULARLASAGNA = "我们花了很长时间才弄明白。"

WILSON.DESCRIBE.FLTSANDWICH = "这就像一个BLT三明治。但用蛙腿代替了！"

WILSON.DESCRIBE.RICEANDBEANS = "健康餐点选择。"

WILSON.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "里面藏着什么秘密？也许2026年我们会知道。"

WILSON.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "Wild truffles! Someone must have sniffed this out.",
	PICKED = "I hope I can get more of them soon!",
	BURNING = "Such waste of a delicacy!",
}

WILSON.DESCRIBE.KYNO_TRUFFLES = "一种稀有而芳香的美味。"
WILSON.DESCRIBE.KYNO_TRUFFLES_COOKED = "这香气太诱人了！"

WILSON.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "A perfect place to show my culinary triumphs!",
	FULL = "I'm very proud of myself for cooking such a magnificent dish.",
}

WILSON.DESCRIBE.KYNO_SPORECAP = "看起来……不太健康。"
WILSON.DESCRIBE.KYNO_SPORECAP_COOKED = "还是很恶心，但也许能吃？"

WILSON.DESCRIBE.KYNO_SPORECAP_DARK = "闻起来有毒。绝对不是食物。"
WILSON.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "加热并没有让它安全。"

WILSON.DESCRIBE.KYNO_GOLDENAPPLE = "科学无法解释它的力量。"

WILSON.DESCRIBE.TRUFFLESGRINDER = "浓郁又泥土的味道，好高级！"

WILSON.DESCRIBE.SPORECAPPIE = "看起来……危险又美味。"

WILSON.DESCRIBE.SPORECAP_SKEWERS = "烤蘑菇串！出乎意料的美味。"

WILSON.DESCRIBE.TRUFFLEOIL = "精致又芳香！我想知道能用它做些什么菜。"

WILSON.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "钓鱼装备！"
WILSON.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "看起来像是一家优质鱼苗场的开端。"

WILSON.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "A place for fish to multiply.",
	FUEL_HIGH = "They are well fed!",
	FUEL_MED = "They keep eating nicely.",
	FUEL_LOW = "Going to need some fish food soon.",
	EMPTY = "They have drained all the food.",
}

WILSON.DESCRIBE.KYNO_ANTCHOVY = "这……是鱼？还是虫？科学界都困惑了。"
WILSON.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "它们正成群结队地聚集！太神奇了！"

WILSON.DESCRIBE.AGEDROE = "我来这里之前从来没有过。"
WILSON.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "鱼子酱！味道比听起来更棒。"

WILSON.DESCRIBE.KYNO_SWORDFISH_BLUE = "一条忘记如何用剑……或游泳的剑鱼。"

WILSON.DESCRIBE.KYNO_JELLYFISH = "这生物简直是纯粹的科学！"
WILSON.DESCRIBE.KYNO_JELLYFISH_DEAD = "它过得挺好。也许吧。"
WILSON.DESCRIBE.KYNO_JELLYFISH_COOKED = "它浑身都在蠕动。"
WILSON.DESCRIBE.KYNO_JELLYFISH_DRIED = "不吃这个我就是个混蛋。"

WILSON.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "一团五彩斑斓的科学。"
WILSON.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "电击无法使其复苏。我试过了。"
WILSON.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "色彩缤纷的小吃！"

WILSON.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "仅仅是一个空瓶子。"

WILSON.DESCRIBE.KYNO_OCEANTRAP = "为了致命的一网。"

WILSON.DESCRIBE.OCEANFISH_PUFFERFISH = "小心！这东西看起来……危险地像充气玩具。"
WILSON.DESCRIBE.OCEANFISH_STURGEON = "一条非常古老的鱼……简直是史前生物！"

WILSON.DESCRIBE.KYNO_SWORDFISH = "我觉得这条鱼进化出来就是为了把我刺穿。"
WILSON.DESCRIBE.KYNO_SWORDFISH_DEAD = "我最好别碰这个。"

WILSON.DESCRIBE.SWORDFISHFEAST = "一道精致的剑鱼薄片料理。"

WILSON.DESCRIBE.KYNO_DOGFISH = "它带着湿狗的味道。"
WILSON.DESCRIBE.KYNO_DOGFISH_DEAD = "好狗。"

WILSON.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "我对气味倒不是特别好奇。"

WILSON.DESCRIBE.WOBSTER_MONKEYISLAND = "多精致的龙虾啊！看起来很贵。"
WILSON.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "它不再移动了。该吃晚饭了吗？"
WILSON.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "来自大海的精致盛宴！"

WILSON.DESCRIBE.KYNO_PUFFERMONSTER = "那玩意儿看起来随时要爆炸了！"

WILSON.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "下面有东西口臭得很。"
WILSON.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "那头鲸有情绪问题。"
WILSON.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "看起来像个战士。"
WILSON.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "恶心。我觉得腹胀开始了。"

WILSON.DESCRIBE.KYNO_BLUBBER = "软软的。"

WILSON.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "味道有点咸，不过凑合着吃吧。"
WILSON.DESCRIBE.KYNO_FISHMEAT_DRIED = "闻起来咸咸的，尝起来还不错。"

WILSON.DESCRIBE.MONKEYISLANDMEAL = "一道足以解除任何诅咒的皇家珍馐！"

WILSON.DESCRIBE.KYNO_BRAINROCK_LARVAE = "那是个婴儿脑！"
WILSON.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "我才不想碰那个小东西呢。"
WILSON.DESCRIBE.KYNO_BRAINROCK_CORAL = "值得深思。"

WILSON.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "I wonder what it's plotting...",
	PICKED = "It needs to rest its brain.",
}

WILSON.DESCRIBE.BRAINMETTERSOUP = "今天我感觉自己特别聪明。"

WILSON.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "I'm a sucker for this guy.",
	SLEEPING = "He's sleeping now. Won't be able to do any trades.",
}

WILSON.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "我希望那东西是防水的。"

WILSON.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "This seems something I should carry around.",
	WAITING = "Hmm, he must be around here somewhere...",
}

WILSON.DESCRIBE.KYNO_PACKIMBAGGIMS = "我敢打赌我能塞满一堆东西。"

WILSON.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "天哪！我等不及要组装它了！"
WILSON.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "它正在烤着呢。"
WILSON.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "一个纪念蛋糕！让我们彻夜狂欢！"
WILSON.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "为节日点亮！"
WILSON.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "好派对的精神！"
WILSON.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "一份庆祝！"
WILSON.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "为庆典增添节日氛围！"

WILSON.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "It pops corn magically!",
	FUEL_HIGH = "Fuel supply running smoothly.",
	FUEL_MED = "It can still produce some popcorn at this rate.",
	FUEL_LOW = "I'm going to need more fuel soon.",
	EMPTY = "No more popcorn until I refuel it.",
}

WILSON.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "爆米花，为盛大庆典准备！"
WILSON.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "没有什么比尖顶帽更能彰显派对氛围了！"
WILSON.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "等等。为什么只有他能戴特别的帽子？"

WILSON.DESCRIBE.KYNO_FISHREGISTRYHAT = "一顶实用的帽子，献给认真的渔夫。"

WILSON.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "A feeding trough for animals.",
	FUEL_HIGH = "Plenty of food to go around.",
	FUEL_MED = "It should last a while longer.",
	FUEL_LOW = "Running low on food.",
	EMPTY = "The animals must be hungry.",
	BURNT = "No more feeding happening here.",
}

WILSON.DESCRIBE.CHICKENNUGGETS = "Processed, breaded, and oddly fascinating."

WILSON.DESCRIBE.CHICKENWINGS = "Never underestimate the power of brand recognition."

WILSON.DESCRIBE.CHICKENBURGER = "A fascinating fusion of poultry and bread."

WILSON.DESCRIBE.CHICKENEGGSOUP = "A simple yet nourishing protein solution."

WILSON.DESCRIBE.CHICKENEGGSTEW = "A hearty combination of poultry and eggs."

WILSON.DESCRIBE.CHICKENROTISSERIE = "Rotational heat ensures even cooking."