local WATHGRITHR = STRINGS.CHARACTERS.WATHGRITHR

WATHGRITHR.ANNOUNCE_KYNO_COFFEEBUFF_START = "战斗速度！"
WATHGRITHR.ANNOUNCE_KYNO_COFFEEBUFF_END = "速度没了！"

WATHGRITHR.ANNOUNCE_KYNO_HASTEBUFF_START = "我的手在动！"
WATHGRITHR.ANNOUNCE_KYNO_HASTEBUFF_END = "我的手指变慢了！"

WATHGRITHR.ANNOUNCE_KYNO_POPBUFF_START = "（嗝！）这是一种奇怪的饮料！"
WATHGRITHR.ANNOUNCE_KYNO_POPBUFF_END = "奇怪的效果现在消失了！"

WATHGRITHR.ANNOUNCE_KYNO_FROGBUFF_START = "我不需要敌人的怜悯！来吧，青蛙！"
WATHGRITHR.ANNOUNCE_KYNO_FROGBUFF_END = "我的青蛙游戏结束了！"

WATHGRITHR.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝!) 这是一种奇怪的饮料！"
WATHGRITHR.ANNOUNCE_KYNO_PIRATEBUFF_END = "奇怪的效果现在已经消失了！"

WATHGRITHR.ANNOUNCE_KYNO_FREEZEBUFF_START = "为打雪仗做好准备！"
WATHGRITHR.ANNOUNCE_KYNO_FREEZEBUFF_END = "嘿，我还没说完呢！"

WATHGRITHR.ANNOUNCE_KYNO_FIREBUFF_START = "我的手被弄脏了。"
WATHGRITHR.ANNOUNCE_KYNO_FIREBUFF_END = "嘿，我还没说完呢！"

WATHGRITHR.ANNOUNCE_KYNO_FISHINGBUFF_START = "是啊！是时候抓点东西了。"
WATHGRITHR.ANNOUNCE_KYNO_FISHINGBUFF_END = "哦，嗯，最好停止钓鱼一段时间。"

WATHGRITHR.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "头脑逐渐......"
WATHGRITHR.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "我的思想绿洲已经消失了！"

WATHGRITHR.ANNOUNCE_KYNO_EATERBUFF_START = "准备吃了！"
WATHGRITHR.ANNOUNCE_KYNO_EATERBUFF_END = "嘴巴发呆了！"

WATHGRITHR.ANNOUNCE_KYNO_WORMBUFF_START = "英灵殿在等着你！"
WATHGRITHR.ANNOUNCE_KYNO_WORMBUFF_END = "现在战斗结束了！"

WATHGRITHR.ANNOUNCE_KYNO_CRABBUFF_START = "英灵殿在等着你！"
WATHGRITHR.ANNOUNCE_KYNO_CRABBUFF_END = "现在战斗结束了！"

WATHGRITHR.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝！) 这是一种奇怪的青蛙饮料！"
WATHGRITHR.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "奇怪的效果现在消失了！"

WATHGRITHR.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "它消耗了我的大脑！"
WATHGRITHR.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "一切恢复正常。"

WATHGRITHR.ANNOUNCE_KYNO_STEALTHBUFF_START = "他们不会看到它的到来！"
WATHGRITHR.ANNOUNCE_KYNO_STEALTHBUFF_END = "他们找到我了！"

WATHGRITHR.ANNOUNCE_KYNO_FEARBUFF_START = "战士的心不知道恐惧！现在，战斗！"
WATHGRITHR.ANNOUNCE_KYNO_FEARBUFF_END = "我强大的决心...再次阴云密布。"

WATHGRITHR.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "诸神赐予我金色盛宴！荣耀归于英灵殿！"
WATHGRITHR.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "诸神收回了他们的祝福！"

WATHGRITHR.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "猪们回应我的召唤！"
WATHGRITHR.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "猪们抛弃我了！"

WATHGRITHR.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "没有酸能融化战士的血肉！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WATHGRITHR.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "没有毒能击倒战士！"
WATHGRITHR.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "我的抗性消退了，但我的斗志依然不灭！"

WATHGRITHR.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "众神赐我智慧，铸就伟业！"
WATHGRITHR.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "众神赐予的智慧正在消逝！"

WATHGRITHR.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "蜜蜂视我为盟友，而非敌人！真是好兆头！"
WATHGRITHR.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "蜜蜂再次准备战斗了！"

WATHGRITHR.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "更强！战斗准备！"
WATHGRITHR.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "我的力量正在消退……"

WATHGRITHR.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "战斗的更多补给！"
WATHGRITHR.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "我的狂欢时光已经结束……暂时告一段落！"

WATHGRITHR.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "我的头脑比任何锋刃都更锐利！"
WATHGRITHR.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "我的心智再度钝化于战斗！"

WATHGRITHR.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "诸神赐予我盾牌！"
WATHGRITHR.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "他们的盾牌抛弃了我！"

WATHGRITHR.ANNOUNCE_KYNO_BERSERKERBUFF_START = "战斗的狂怒在我体内奔涌！"
WATHGRITHR.ANNOUNCE_KYNO_BERSERKERBUFF_END = "战意渐消……"

WATHGRITHR.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "我的身躯无需盛宴亦能支撑！"
WATHGRITHR.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "饥饿的呼唤，回来了！"

WATHGRITHR.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "错误的！"

WATHGRITHR.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "搞错了！野兽想要更美味的食物！"

WATHGRITHR.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "这棵树现在还什么都长不出来！真可惜！"

WATHGRITHR.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "不！"

WATHGRITHR.ANNOUNCE_KYNO_POTHANGER_FAIL = "我需要在这里放一个锅来做饭。"

WATHGRITHR.ANNOUNCE_KYNO_CASSEROLE_FAIL = "不是那个！"

WATHGRITHR.ANNOUNCE_KYNO_SAPHEALER_USED = "众神助我，让这棵倒下的战士之树重获新生！"

WATHGRITHR.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "盛宴的华美谢幕！"

WATHGRITHR.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "这只带轮子的箱子里已空无一物！"

WATHGRITHR.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "大海掩去了气息！猎物逃窜！"
WATHGRITHR.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "暴风雨掩盖了猎物的气味！该死！"
WATHGRITHR.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "野兽逼近！我勇往直前！"

WATHGRITHR.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "庆典高塔落成！狂欢盛宴开启！"

WATHGRITHR.ANNOUNCE_KYNO_FISH_RESEARCHED = "我已研究过这海中猛兽！"
WATHGRITHR.ANNOUNCE_KYNO_ROE_RESEARCHED = "未出生的海之战士，已被研究！"

WATHGRITHR.DESCRIBE.KYNO_ROE = "有一天你可能是真正的肉。"
WATHGRITHR.DESCRIBE.KYNO_ROE_COOKED = "你永远不会是真正的肉了。"

WATHGRITHR.DESCRIBE.KYNO_SHARK_FIN = "出自于堕落勇士。"

WATHGRITHR.DESCRIBE.KYNO_BEANBUGS = "四足食物。"
WATHGRITHR.DESCRIBE.KYNO_BEANBUGS_COOKED = "肉？"

WATHGRITHR.DESCRIBE.KYNO_GUMMYBUG = "很粘，但会填满我的肚子。"
WATHGRITHR.DESCRIBE.KYNO_GUMMYBUG_COOKED = "肉肉？"

WATHGRITHR.DESCRIBE.KYNO_WHEAT = "哦，光荣的小麦！"
WATHGRITHR.DESCRIBE.KYNO_WHEAT_COOKED = "哦，光荣的小麦！"

WATHGRITHR.DESCRIBE.KYNO_FLOUR = "不是肉！"

WATHGRITHR.DESCRIBE.KYNO_SPOTSPICE = "里面有调味料！"

WATHGRITHR.DESCRIBE.KYNO_SAP = "众神的甘露。"
WATHGRITHR.DESCRIBE.KYNO_SAP_SPOILED = "唉，甘露不再甜了！"

WATHGRITHR.DESCRIBE.KYNO_SYRUP = "众神甘露，献给众神。"

WATHGRITHR.DESCRIBE.KYNO_COFFEEBEANS = "我拿的是黑色。"
WATHGRITHR.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "闻起来充满活力。"

WATHGRITHR.DESCRIBE.DUG_KYNO_COFFEEBUSH = "需要炙热的土壤。"

WATHGRITHR.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "加点水就行了？",
	PICKED = "它的战利品沉睡了！",
	WITHERED = "它因软弱而枯萎！",
}

WATHGRITHR.DESCRIBE.DUG_KYNO_SPOTBUSH = "需要妥善栽种。"

WATHGRITHR.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "给最精致的食物用的香料。",
	PICKED = "它的战利品沉睡了！",
	BURNING = "被火焰斩杀了！",
}

WATHGRITHR.DESCRIBE.KYNO_SPOTSPICE_LEAF = "这是一根调味小枝。"

WATHGRITHR.DESCRIBE.KYNO_MUSSEL = "你看起来一点也不奇怪。"
WATHGRITHR.DESCRIBE.KYNO_MUSSEL_COOKED = "口味重。"

WATHGRITHR.DESCRIBE.KYNO_HUMANMEAT = "向你们阵亡的勇士致敬！"
WATHGRITHR.DESCRIBE.KYNO_HUMANMEAT_COOKED = "他们在熊熊烈火中死去，烤得一样。"
WATHGRITHR.DESCRIBE.KYNO_HUMANMEAT_DRIED = "即使在死亡中也坚韧不屈！"

WATHGRITHR.DESCRIBE.COFFEE = "苦涩和脉搏。"

WATHGRITHR.DESCRIBE.BISQUE = "不错的菜。"

WATHGRITHR.DESCRIBE.JELLYOPOP = "我可以对这些发疯！"

WATHGRITHR.DESCRIBE.SHARKFINSOUP = "好吃！"

WATHGRITHR.DESCRIBE.TROPICALBOUILLABAISSE = "这是一场鱼宴！"

WATHGRITHR.DESCRIBE.MUSSELBOUILLABAISE = "鲜，但温暖。"

WATHGRITHR.DESCRIBE.SWEETPOTATOSOUFFLE = "里面充满了美味的空气！"

WATHGRITHR.DESCRIBE.FEIJOADA = "我会吃掉你的肉豆子！"

WATHGRITHR.DESCRIBE.GUMMY_CAKE = "果冻蛋糕 - 准备被吃掉！"

WATHGRITHR.DESCRIBE.HARDSHELL_TACOS = "你脆脆的外壳不让我高兴！！！"

WATHGRITHR.DESCRIBE.ICEDTEA = "里面没有肉！"

WATHGRITHR.DESCRIBE.NETTLELOSANGE = "药用营养品。"

WATHGRITHR.DESCRIBE.SNAKEBONESOUP = "肉汤！"

WATHGRITHR.DESCRIBE.STEAMEDHAMSANDWICH = "这显然是烤的！"

WATHGRITHR.DESCRIBE.TEA = "我要吃掉你！"

WATHGRITHR.DESCRIBE.BUBBLETEA = "里面没有肉！"

WATHGRITHR.DESCRIBE.FRENCHONIONSOUP = "肉汤！"

WATHGRITHR.DESCRIBE.SLAW = "一堆蔬菜？不，谢谢。"

WATHGRITHR.DESCRIBE.LOTUSBOWL = "我不想吃这个。"

WATHGRITHR.DESCRIBE.POI = "不是肉。"

WATHGRITHR.DESCRIBE.JELLYBEAN_HUNGER = "勤劳的糖果农民的产量。"
WATHGRITHR.DESCRIBE.JELLYBEAN_SUPER = "勤劳的糖果是农民劳作成果。"
WATHGRITHR.DESCRIBE.JELLYBEAN_SANITY = "一个勤劳的糖果农民的产量。"

WATHGRITHR.DESCRIBE.BOWLOFGEARS = "这不是肉！"

WATHGRITHR.DESCRIBE.LONGPIGMEAL = "向你阵亡的勇士致敬！"

WATHGRITHR.DESCRIBE.CUCUMBERSALAD = "蔬菜是给动物吃的。动物是用来吃的。"

WATHGRITHR.DESCRIBE.DUG_KYNO_WILDWHEAT = "最好现在就种下！"

WATHGRITHR.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "或许能派上用场。",
	PICKED = "它的战利品沉睡了！",
	WITHERED = "它因软弱而枯萎！",
	BURNING = "被火焰斩杀了！",
}

WATHGRITHR.DESCRIBE.KYNO_MEALGRINDER = "小麦武器！"

WATHGRITHR.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "长着非肉的菌类。",
	PICKED = "已被征服。",
	BURNING = "被火焰摧毁了！",
}

WATHGRITHR.DESCRIBE.GORGE_BREAD = "啊哈。这可不适合像我这样的勇士！"
WATHGRITHR.DESCRIBE.GORGE_SWEET_CHIPS = "不适合勇士的食物！"
WATHGRITHR.DESCRIBE.GORGE_VEGETABLE_SOUP = "蔬菜是给弱者的！"
WATHGRITHR.DESCRIBE.GORGE_JELLY_SANDWICH = "呃。。."
WATHGRITHR.DESCRIBE.GORGE_FISH_STEW = "没有什么比多吃肉更好吃的了！"
WATHGRITHR.DESCRIBE.GORGE_MEAT_STEW = "好吃！"
WATHGRITHR.DESCRIBE.GORGE_ONION_CAKE = "弱者的蛋糕！"
WATHGRITHR.DESCRIBE.GORGE_POTATO_PANCAKES = "咦呕。"
WATHGRITHR.DESCRIBE.GORGE_POTATO_SOUP = "这道菜还不错。"
WATHGRITHR.DESCRIBE.GORGE_FISHBALL_SKEWERS = "最终, 恰当的食物!"
WATHGRITHR.DESCRIBE.GORGE_MEAT_SKEWERS = "最终, 恰当的食物!"
WATHGRITHR.DESCRIBE.GORGE_STONE_SOUP = "这道菜还不错。"
WATHGRITHR.DESCRIBE.GORGE_CROQUETTE = "真糟糕。"
WATHGRITHR.DESCRIBE.GORGE_ROAST_VEGETABLES = "呸。"
WATHGRITHR.DESCRIBE.GORGE_MEATLOAF = "这才像话嘛！"
WATHGRITHR.DESCRIBE.GORGE_CARROT_SOUP = "这道菜还不错。"
WATHGRITHR.DESCRIBE.GORGE_FISHPIE = "不可思议！"
WATHGRITHR.DESCRIBE.GORGE_FISHCHIPS = "这才是我能学会欣赏的组合。"
WATHGRITHR.DESCRIBE.GORGE_MEATPIE = "美味的肉！"
WATHGRITHR.DESCRIBE.GORGE_SLIDERS = "为什么这么小？！"
WATHGRITHR.DESCRIBE.GORGE_JELLY_ROLL = "恶心。"
WATHGRITHR.DESCRIBE.GORGE_CARROT_CAKE = "蛋糕不好吃！"
WATHGRITHR.DESCRIBE.GORGE_GARLICMASHED = "恶心。"
WATHGRITHR.DESCRIBE.GORGE_GARLICBREAD = "呸。"
WATHGRITHR.DESCRIBE.GORGE_TOMATO_SOUP = "这道菜还不错。"
WATHGRITHR.DESCRIBE.GORGE_SAUSAGE = "肉质鲜美！"
WATHGRITHR.DESCRIBE.GORGE_CANDIEDFISH = "美味！"
WATHGRITHR.DESCRIBE.GORGE_STUFFEDMUSHROOM = "不适合勇士！"
WATHGRITHR.DESCRIBE.GORGE_BRUSCHETTA = "如果有腌肉，我会更喜欢。"
WATHGRITHR.DESCRIBE.GORGE_HAMBURGER = "合适的勇士食物！"
WATHGRITHR.DESCRIBE.GORGE_FISHBURGER = "适合勇士的食物！"
WATHGRITHR.DESCRIBE.GORGE_MUSHROOMBURGER = "不是我喜欢的汉堡。"
WATHGRITHR.DESCRIBE.GORGE_FISH_STEAK = "没有什么比多吃肉更好吃的了！"
WATHGRITHR.DESCRIBE.GORGE_CURRY = "这是在倒春寒之夜享用的一顿大餐。"
WATHGRITHR.DESCRIBE.GORGE_SPAGHETTI = "小宴会球。"
WATHGRITHR.DESCRIBE.GORGE_POACHEDFISH = "美味可口！"
WATHGRITHR.DESCRIBE.GORGE_SHEPHERD_PIE = "美味的肉馅饼！"
WATHGRITHR.DESCRIBE.GORGE_CANDY = "这颗糖果的传奇将被讲述很久。"
WATHGRITHR.DESCRIBE.GORGE_BREAD_PUDDING = "不是我的菜。"
WATHGRITHR.DESCRIBE.GORGE_BERRY_TART = "不好。"
WATHGRITHR.DESCRIBE.GORGE_MACARONI = "没有肉那么好吃。"
WATHGRITHR.DESCRIBE.GORGE_BAGEL_AND_FISH = "面包不需要，但我还是要吃。"
WATHGRITHR.DESCRIBE.GORGE_GRILLED_CHEESE = "没有培根和鸡蛋好吃。"
WATHGRITHR.DESCRIBE.GORGE_CREAMMUSHROOM = "恶心。"
WATHGRITHR.DESCRIBE.GORGE_MANICOTTI = "无聊的食物！"
WATHGRITHR.DESCRIBE.GORGE_CHEESEBURGER = "适合勇士的食物！"
WATHGRITHR.DESCRIBE.GORGE_FETTUCCINE = "恶心。"
WATHGRITHR.DESCRIBE.GORGE_ONION_SOUP = "呃。"
WATHGRITHR.DESCRIBE.GORGE_BREADED_CUTLET = "适合勇士使用！"
WATHGRITHR.DESCRIBE.GORGE_CREAMY_FISH = "美味极了！"
WATHGRITHR.DESCRIBE.GORGE_PIZZA = "肉和意大利面...一起。"
WATHGRITHR.DESCRIBE.GORGE_POT_ROAST = "这是神铸造的。"
WATHGRITHR.DESCRIBE.GORGE_CRAB_CAKE = "他这样看起来更好。"
WATHGRITHR.DESCRIBE.GORGE_STEAK_FRITES = "我为此感到自豪。"
WATHGRITHR.DESCRIBE.GORGE_SHOOTER_SANDWICH = "最美味的三明治。"
WATHGRITHR.DESCRIBE.GORGE_BACON_WRAPPED = "这是一顿完美的早餐！"
WATHGRITHR.DESCRIBE.GORGE_CRAB_ROLL = "美味!"
WATHGRITHR.DESCRIBE.GORGE_MEAT_WELLINGTON = "是的！！"
WATHGRITHR.DESCRIBE.GORGE_CRAB_RAVIOLI = "美味可口!"
WATHGRITHR.DESCRIBE.GORGE_CARAMEL_CUBE = "嗯。味道确实不错。"
WATHGRITHR.DESCRIBE.GORGE_SCONE = "嗯..."
WATHGRITHR.DESCRIBE.GORGE_TRIFLE = "嗯..."
WATHGRITHR.DESCRIBE.GORGE_CHEESECAKE = "呃。"

WATHGRITHR.DESCRIBE.DUCKYOUGLERMZ = "多么邪恶的一餐！"

WATHGRITHR.DESCRIBE.KYNO_ALOE = "呸！这里没有肉！"
WATHGRITHR.DESCRIBE.KYNO_ALOE_COOKED = "它没有肉！"
WATHGRITHR.DESCRIBE.KYNO_ALOE_GROUND = "呸！这里没有肉！"
WATHGRITHR.DESCRIBE.KYNO_ALOE_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.FARM_PLANT_KYNO_ALOE = "呸！这里没有肉！"
WATHGRITHR.DESCRIBE.KYNO_ALOE_OVERSIZED = "呸！这里没有肉！"
WATHGRITHR.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "哈!"

WATHGRITHR.DESCRIBE.KYNO_CUCUMBER = "可笑的海菜。"
WATHGRITHR.DESCRIBE.KYNO_CUCUMBER_COOKED = "比以前更糟了。"
WATHGRITHR.DESCRIBE.KYNO_CUCUMBER_GROUND = "可笑的海菜。"
WATHGRITHR.DESCRIBE.KYNO_CUCUMBER_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "可笑的海菜。"
WATHGRITHR.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "可笑的海菜。"
WATHGRITHR.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "可笑的海菜。"

WATHGRITHR.DESCRIBE.KYNO_RADISH = "它对我没用！"
WATHGRITHR.DESCRIBE.KYNO_RADISH_COOKED = "火无助于改善它！"
WATHGRITHR.DESCRIBE.KYNO_RADISH_GROUND = "它对我没用！"
WATHGRITHR.DESCRIBE.KYNO_RADISH_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.FARM_PLANT_KYNO_RADISH = "它对我毫无用处！"
WATHGRITHR.DESCRIBE.KYNO_RADISH_OVERSIZED = "它对我毫无用处！"
WATHGRITHR.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "哈!"

WATHGRITHR.DESCRIBE.KYNO_FENNEL = "这是一种蔬菜！"
WATHGRITHR.DESCRIBE.KYNO_FENNEL_COOKED = "热腾腾的棕色糊状物。"
WATHGRITHR.DESCRIBE.KYNO_FENNEL_GROUND = "这是一种蔬菜！"
WATHGRITHR.DESCRIBE.KYNO_FENNEL_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "是一种蔬菜！"
WATHGRITHR.DESCRIBE.KYNO_FENNEL_OVERSIZED = "是一种蔬菜！"
WATHGRITHR.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "哈!"

WATHGRITHR.DESCRIBE.KYNO_SWEETPOTATO = "我从没听说过甜土豆！...恶心！"
WATHGRITHR.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "我不会吃，但我很欣赏它的颜色。"
WATHGRITHR.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "我从没听说过甜土豆！...恶心！"
WATHGRITHR.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "我从来没听说过马铃薯是甜的！...恶心"
WATHGRITHR.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "我从来没听说过马铃薯是甜的！...恶心"
WATHGRITHR.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "哈!"

WATHGRITHR.DESCRIBE.KYNO_PARZNIP = "蛋白质在哪里？"
WATHGRITHR.DESCRIBE.KYNO_PARZNIP_COOKED = "蛋白质在哪里？"
WATHGRITHR.DESCRIBE.KYNO_PARZNIP_EATEN = "蛋白质在哪里？"
WATHGRITHR.DESCRIBE.KYNO_PARZNIP_GROUND = "蛋白质在哪里？"
WATHGRITHR.DESCRIBE.KYNO_PARZNIP_BIG = "现在你是个不错的对手了！"
WATHGRITHR.DESCRIBE.KYNO_PARZNIP_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "蛋白质在哪里？"
WATHGRITHR.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "蛋白质在哪里？"
WATHGRITHR.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "哈!"

WATHGRITHR.DESCRIBE.KYNO_TURNIP = "众神有奇怪的口味。"
WATHGRITHR.DESCRIBE.KYNO_TURNIP_COOKED = "哎呀！我不会吃你的！"
WATHGRITHR.DESCRIBE.KYNO_TURNIP_GROUND = "众神有奇怪的口味。"
WATHGRITHR.DESCRIBE.KYNO_TURNIP_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "众神有奇怪的口味。"
WATHGRITHR.DESCRIBE.KYNO_TURNIP_OVERSIZED = "众神有奇怪的口味。"
WATHGRITHR.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "哈！"

WATHGRITHR.DESCRIBE.KYNO_RICE = "恶心！"
WATHGRITHR.DESCRIBE.KYNO_RICE_COOKED = "恶心！"
WATHGRITHR.DESCRIBE.KYNO_RICE_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "微小的自然碎片。"
WATHGRITHR.DESCRIBE.FARM_PLANT_KYNO_RICE = "众神的口味很奇怪。"
WATHGRITHR.DESCRIBE.KYNO_RICE_OVERSIZED = "众神的口味很奇怪。"
WATHGRITHR.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "哈!"

WATHGRITHR.DESCRIBE.KYNO_SEEDS_KIT = "恶心。"

WATHGRITHR.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "这肉石头！",
	PICKED = "它们逃离了收获！",
	WITHERED = "这石头毫无战利品！",
}

WATHGRITHR.DESCRIBE.KYNO_LIMPETS = "石头肉！"
WATHGRITHR.DESCRIBE.KYNO_LIMPETS_COOKED = "让我们大饱眼福！"

WATHGRITHR.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "弗雷娅眷顾着此物。",
	PICKED = "它在积蓄力量！",
	BURNING = "被火焰击倒了！",
}

WATHGRITHR.DESCRIBE.KYNO_LOTUS_ROOT = "我才不需要它！"
WATHGRITHR.DESCRIBE.KYNO_LOTUS_FLOWER = "它拥有芙蕾雅的绝美。"
WATHGRITHR.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "我不想吃这个。"

WATHGRITHR.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "一种我靴子碾不碎的杂草。",
	PICKED = "它们撤退了！",
	BURNING = "顶着浪头，竟被火焰吞噬了！",
}

WATHGRITHR.DESCRIBE.KYNO_SEAWEEDS = "水生植物污物！"
WATHGRITHR.DESCRIBE.KYNO_SEAWEEDS_COOKED = "海上小吃。"
WATHGRITHR.DESCRIBE.KYNO_SEAWEEDS_DRIED = "它很耐嚼......"
WATHGRITHR.DESCRIBE.KYNO_SEAWEEDS_ROOT = "我没有用它！"

WATHGRITHR.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "这是个水里的蔬菜，这怎么可能！",
	PICKED = "它在积蓄力量！",
	BURNING = "被火焰斩杀了！",
}

WATHGRITHR.DESCRIBE.KYNO_TAROROOT_ROOT = "我才不需要它！"
WATHGRITHR.DESCRIBE.KYNO_TAROROOT = "紫色和球根状。"
WATHGRITHR.DESCRIBE.KYNO_TAROROOT_COOKED = "弱者的食物。"

WATHGRITHR.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "我讨厌这玩意儿。",
	PICKED = "它必将卷土重来！",
	BURNING = "被火焰放倒了！",
}

WATHGRITHR.DESCRIBE.KYNO_WATERYCRESS_ROOT = "我才不需要它！"
WATHGRITHR.DESCRIBE.KYNO_WATERYCRESS = "我讨厌它。"

WATHGRITHR.DESCRIBE.WATERYCRESSBOWL = "我不会吃掉你！"

WATHGRITHR.DESCRIBE.KYNO_SALT = "它很咸。"

WATHGRITHR.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "壳中藏着的小块肉，静待收获！",
	PICKED = "它们撤退了！",
	BURNING = "被火焰斩杀了！",
}

WATHGRITHR.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "愚蠢的贻贝会爬上这根木棍。"

WATHGRITHR.DESCRIBE.CATFOOD = "这是勇敢的猫！"

WATHGRITHR.DESCRIBE.KATFOOD = "这是为了勇敢的猫！"

WATHGRITHR.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "一棵脆弱的猴子树。",
	PICKED = "它必须积蓄力量！",
	CHOPPED = "像砍翻弱敌一样放倒了！",
	BURNING = "它在战斗中燃烧！",
	BURNT = "被火焰征服了！",
}

WATHGRITHR.DESCRIBE.KYNO_BANANA = "猴子食物。"
WATHGRITHR.DESCRIBE.KYNO_BANANA_COOKED = "热猴粮。"

WATHGRITHR.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "你抛弃了树枝吗，树啊？",
	PICKED = "它必须积蓄力量！",
	CHOPPED = "像砍翻敌人一样放倒了！",
	BURNING = "它在战斗中燃烧！",
	BURNT = "被火焰征服了！",
}

WATHGRITHR.DESCRIBE.KYNO_KOKONUT = "最坚硬的水果。"
WATHGRITHR.DESCRIBE.KYNO_KOKONUT_HALVED = "我已经圈出了螺母，它向我展示了它的内部！"
WATHGRITHR.DESCRIBE.KYNO_KOKONUT_COOKED = "我要享用这颗大坚果。"

WATHGRITHR.DESCRIBE.BOWLOFPOPCORN = "爆米花闻起来很香。"

WATHGRITHR.DESCRIBE.FIGJUICE = "里面没有肉！"

WATHGRITHR.DESCRIBE.COCONUTWATER = "不是真正的水！"

WATHGRITHR.DESCRIBE.EYEBALLSPAGHETTI = "肉就是肉……"

WATHGRITHR.DESCRIBE.FORGETMELOTS_SEEDS = "微小的自然碎片。"

WATHGRITHR.DESCRIBE.FIRENETTLES_SEEDS = "微小的自然碎片。"

WATHGRITHR.DESCRIBE.TILLWEED_SEEDS = "微小的自然碎片。"

WATHGRITHR.DESCRIBE.KYNO_FLOATILIZER = "它的恶臭可以让倒下的人复活。"

WATHGRITHR.DESCRIBE.KYNO_TWIGGYNUTS = "像我这样真正的勇士不适合吃！"

WATHGRITHR.DESCRIBE.KYNO_REPAIRTOOL = "破碎的东西可以重新锻造。"

WATHGRITHR.DESCRIBE.KYNO_KOI = "你的倒霉我的好运，小动物。"
WATHGRITHR.DESCRIBE.KYNO_KOI_COOKED = "你的运气不好，我的好运，小动物。"

WATHGRITHR.DESCRIBE.KYNO_TROPICALFISH = "里面是肉的颜色！"
WATHGRITHR.DESCRIBE.KYNO_TROPICALFISH_COOKED = "完美！"

WATHGRITHR.DESCRIBE.KYNO_NEONFISH = "你不能再游泳了。"
WATHGRITHR.DESCRIBE.KYNO_NEONFISH_COOKED = "今天让我吃饱了。"

WATHGRITHR.DESCRIBE.KYNO_GROUPER = "今天艾吉尔不会救你。"
WATHGRITHR.DESCRIBE.KYNO_GROUPER_COOKED = "感谢 Njord 的礼物！"
 
WATHGRITHR.DESCRIBE.KYNO_PIERROTFISH = "我希望这肉没有那么大的眼睛。"
WATHGRITHR.DESCRIBE.KYNO_PIERROTFISH_COOKED = "谢谢你，鱼，你的肉礼物。"

WATHGRITHR.DESCRIBE.KYNO_SALMONFISH = "这是一条最美味的鱼！"
WATHGRITHR.DESCRIBE.KYNO_SALMONFISH_COOKED = "来自大海的盛宴。"

WATHGRITHR.DESCRIBE.TURF_PINKPARK = "这粉红打不过我！"
WATHGRITHR.DESCRIBE.TURF_STONECITY = "战场上的一块。"
WATHGRITHR.DESCRIBE.TURF_FIELDS = "战场的一部分。"
WATHGRITHR.DESCRIBE.TURF_TIDALMARSH = "战场的一部分。"

WATHGRITHR.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "这玩意儿准备好被掠夺了！",
	PICKED = "肉的盟友，静候在此！",
}

WATHGRITHR.DESCRIBE.KYNO_SALTRACK_INSTALLER = "我会好好利用你。"

WATHGRITHR.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "从树上掠夺。"

WATHGRITHR.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "它会捕获海肉。"

WATHGRITHR.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "你的君主在此。",
	SLEEPING =  "他正安眠！",
}

WATHGRITHR.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "众神的甘露蕴藏其中。",
	CHOPPED = "它已被砍伐。",
	SAPPED = "我已取得甘露！",
	PICKED = "我对你毫无耐心，树汁！",
	BURNING = "被火焰斩杀了！",
	BURNT = "被征服了！",
}

WATHGRITHR.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "它受伤了！",
	CHOPPED = "耻辱地被放倒了！",
	SAPPED = "腐化的战利品！",
	PICKED = "它被小兽们玷污了！",
	BURNING = "被火焰净化了！",
	BURNT = "永别了！",
}

WATHGRITHR.DESCRIBE.KYNO_SUGARTREE_BUD = "它没有肉让我很生气。"

WATHGRITHR.DESCRIBE.KYNO_SUGARTREE_FLOWER = "芙蕾雅的糖花。"
WATHGRITHR.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "来自芙蕾雅的糖花。"

WATHGRITHR.DESCRIBE.KYNO_SUGARTREE_PETALS = "来自芙蕾雅的糖花。"

WATHGRITHR.DESCRIBE.KYNO_PEBBLECRAB = "你不能躲着我！"

WATHGRITHR.DESCRIBE.KYNO_CRABMEAT = "被我吃掉真是荣幸，野兽！"
WATHGRITHR.DESCRIBE.KYNO_CRABMEAT_COOKED = "这是一道美味佳肴！"
WATHGRITHR.DESCRIBE.KYNO_CRABMEAT_DRIED = "被我吃掉是你的荣幸，野兽"

WATHGRITHR.DESCRIBE.KYNO_CRABKINGMEAT = "被我吃掉是你的荣幸，野兽"
WATHGRITHR.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "野兽，能被我吃掉真是太荣幸了！"
WATHGRITHR.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "野兽，能被我吃掉真是太荣幸了！"

WATHGRITHR.DESCRIBE.KYNO_SLAUGHTERTOOL = "这是一种残忍的屠杀武器！"

WATHGRITHR.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "此乃行走的肉。",
	COOP = "这野兽已被征服！",
}

WATHGRITHR.DESCRIBE.KYNO_CHICKEN_EGG = "鸡蛋。"
WATHGRITHR.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "一场配得上真正北方勇士的盛宴！"
WATHGRITHR.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "热鸡蛋。"

WATHGRITHR.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "产卵之兽的厅堂！",
	FULL = "鸡蛋正等待着它们光荣的宿命！",
	BURNT = "鸡舍已在战斗中陨落！",
}

WATHGRITHR.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "破东西！"

WATHGRITHR.DESCRIBE.KYNO_COOKWARE_KIT = "需要安装。"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_SYRUP = "用于制作神圣的花蜜！"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "用于制作神圣的花蜜！"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_BIG_POT = "还有更多肉的空间！"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_BIG = "还有更多肉的空间！"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "我们要给你吃肉！"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_SMALL = "我们要给你吃肉！"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_GRILL = "它用赫尔的火焰接触肉。"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "美味的乐器。"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "它会用赫尔的火焰接触肉。"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "它不能像这样工作。"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_ELDER = "用于制作神圣的花蜜！"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "这是一种征服食物的工具。"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "它可以装很多肉。"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "一个食物容器。"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_OVEN = "我要在你身上做饭！"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "我要在你里面做饭！"
WATHGRITHR.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "我要在你里面做饭！"

WATHGRITHR.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "石头！向我揭示你的秘密！",
	FLIPPED = "它们在我面前四散而逃！",
}

WATHGRITHR.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "掠夺！"

WATHGRITHR.DESCRIBE.KYNO_SUGARFLY = "这有点好。"
WATHGRITHR.DESCRIBE.KYNO_SUGARFLYWINGS = "一件漂亮的纪念品。"

WATHGRITHR.DESCRIBE.KYNO_WATERY_CRATE = "掠夺！"

WATHGRITHR.DESCRIBE.KYNO_TUNACAN = "可以在航行中存活的食物！"
WATHGRITHR.DESCRIBE.KYNO_TUNACAN_OPEN = "可以在航行中存活的食物！"

WATHGRITHR.DESCRIBE.KYNO_CANNEDFOOD = "可以在航行中存活的食物！"
WATHGRITHR.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "可以在航行中存活的食物！"

WATHGRITHR.DESCRIBE.KYNO_POP = "这是什么臭蜂蜜酒？"

WATHGRITHR.DESCRIBE.KYNO_MYSTERYMEAT = "我敌人孩子的食物是……对我来说是什么？"

WATHGRITHR.DESCRIBE.KYNO_BOTTLE_SOUL = "一个堕落勇士的灵魂......还是野兽......？"

WATHGRITHR.DESCRIBE.SOULSTEW = "一个堕落勇士的灵魂......还是野兽......？"

WATHGRITHR.DESCRIBE.FORTUNECOOKIE = "哈！我已经知道我的运气了！"

WATHGRITHR.DESCRIBE.HORNOCUPIA = "盛宴，盛宴，无处不在！"

WATHGRITHR.DESCRIBE.CHEESE_YELLOW = "勇士的食物......！"
WATHGRITHR.DESCRIBE.CHEESE_WHITE = "勇士的食物......！"
WATHGRITHR.DESCRIBE.CHEESE_KOALEFANT = "勇士的食物......！"

WATHGRITHR.DESCRIBE.MILK_BOX = "这是婴儿饮料！"

WATHGRITHR.DESCRIBE.WATERCUP = "只有水。"

WATHGRITHR.DESCRIBE.HONEYJAR = "我不确定。"

WATHGRITHR.DESCRIBE.CRAB_ARTICHOKE = "现在，这对勇士来说是一顿正餐！"

WATHGRITHR.DESCRIBE.PEPPERROLLS = "别靠近，蔬菜！"

WATHGRITHR.DESCRIBE.KYNO_SAPHEALER = "树木疾病的根源。"

WATHGRITHR.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "长船散落在通往英灵殿的路上。",
	PICKED = "战利品逃走了！",
	BURNING = "它葬身火海！",
}

WATHGRITHR.DESCRIBE.KYNO_GHOST_PIRATE = "去吧，灵魂！"

WATHGRITHR.DESCRIBE.KYNO_BUCKET_EMPTY = "一个伟大的收集工具！"
WATHGRITHR.DESCRIBE.KYNO_BUCKET_METAL = "一个结实的收集工具！"
WATHGRITHR.DESCRIBE.KYNO_BUCKET_WATER = "哼！我更喜欢我的敌人的鲜血！"

WATHGRITHR.DESCRIBE.KYNO_MILK_BEEFALO = "这是强力牛奶。"
WATHGRITHR.DESCRIBE.KYNO_MILK_KOALEFANT = "这是强力牛奶。"

WATHGRITHR.DESCRIBE.KYNO_CAP_DRIED = "糟糕。"

WATHGRITHR.DESCRIBE.KYNO_PLANTMEAT_DRIED = "优秀的战斗物资。"

WATHGRITHR.DESCRIBE.KYNO_BREWBOOK = "如果你问我，这里面的非肉类菜肴太多了。"

WATHGRITHR.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "众神的酿酒器！",
	BREWING_LONG = "此酒必须荣耀地陈化！",
	BREWING_SHORT = "盛宴即将开始！",
	DONE = "此酿已为勇士备好！",
	BURNT = "被火焰摧毁了！",
}

WATHGRITHR.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "这非我所好……",
	BREWING_LONG = "盛宴必须等待！",
	BREWING_SHORT = "盛宴很快就是我的了！",
	DONE = "战利品备好了！",
	BURNT = "被火焰摧毁了！",
}

WATHGRITHR.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "一个女武神用不着什么产蜜的家伙！",
	HONEY = "那些蜂蜜，我用不上。",
	NECTAR = "它们似乎在把那恶心的花蜜变成恶心的蜂蜜！",
	BURNING = "厅堂在荣耀的火焰中燃烧！",
}

WATHGRITHR.DESCRIBE.KYNO_NECTAR_POD = "昆虫的食物，不配当盾女。"

WATHGRITHR.DESCRIBE.KYNO_OAKTREE_POD = "只是一颗普通的树种。"
WATHGRITHR.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "即使被火触碰，我也不会吃掉它！"

WATHGRITHR.DESCRIBE.KYNO_PIKO = "你渴望战斗吗？"
WATHGRITHR.DESCRIBE.KYNO_PIKO_ORANGE = "我没有用它。"

WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "此树尚可。",
	CHOPPED = "它的战利品已被夺取！",
	BURNING = "它在战斗中燃烧！",
	BURNT = "被火焰放倒了！",
}

WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "此树尚可。",
	BURNING = "它们的厅堂葬身火海！",
}

WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "交出你的秘密，盒子！"

WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "这住处是鱼做的吗？",
	BURNT = "被火焰放倒了！",
}

WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "渔夫们住在此处。",
	CRAFTED = "配得上其居住者的厅堂！",
	BURNT = "这战败的恶臭！",
}

WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "挂着的香肠看起来真美味！",
	OCCUPIED = "商贩在打盹！",
}

WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "呃，肉都去哪儿了？",
	EMPTY = "萨米的车空空如也！",
}

WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "它是各种商品的优秀交易者。"
WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_POND = "一个小湖！"
WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "池塘植物。"
WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "我不会用沙丘造山。"
WATHGRITHR.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "我不和渔民吵架，只要他们不拿起武器。"

WATHGRITHR.DESCRIBE.KYNO_SAMMYHAT = "在战斗中没有帮助。"

WATHGRITHR.DESCRIBE.KINGFISHER = "拥有最强大的喙！"

WATHGRITHR.DESCRIBE.TOUCAN = "和我一起战斗吧，长鼻鸟！我们将一起在英灵殿大餐！"
WATHGRITHR.DESCRIBE.TOUCAN_CHUBBY = "和我一起战斗吧，长鼻鸟！我们将一起在英灵殿大餐！"

WATHGRITHR.DESCRIBE.WETGOOP2 = "脏。"

WATHGRITHR.DESCRIBE.BEER = "啊哈！我找到了酒！"

WATHGRITHR.DESCRIBE.PALEALE = "啊哈！我找到了酒！"

WATHGRITHR.DESCRIBE.TEAGREEN = "勇士不参加\"下午茶时间\"。"

WATHGRITHR.DESCRIBE.TEARED = "勇士不参加\"下午茶时间\"。"

WATHGRITHR.DESCRIBE.MEAD = "终于！适合勇士的饮料！"

WATHGRITHR.DESCRIBE.KYNO_JELLY = "黏糊糊的。"

WATHGRITHR.DESCRIBE.KYNO_MAYONNAISE = "这不是真正的勇士的食物！"

WATHGRITHR.DESCRIBE.TARTARSAUCE = "呃，看起来很糟糕。"

WATHGRITHR.DESCRIBE.KYNO_PICKLES = "这不适合勇士吃！"

WATHGRITHR.DESCRIBE.KYNO_WINE = "一杯好酒，适合勇士！"

WATHGRITHR.DESCRIBE.KYNO_JUICE = "这不是勇士的酒！"

WATHGRITHR.DESCRIBE.KYNO_POISON_FROGLEGS = "它的肉被污染了！"
WATHGRITHR.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "注意风，我会吞噬你！"

WATHGRITHR.DESCRIBE.POISONFROGGLEBUNWICH = "太棒了！"

WATHGRITHR.DESCRIBE.KYNO_BREWINGRECIPECARD = "这只是一堆乱七八糟的单词。"

WATHGRITHR.DESCRIBE.KYNO_OIL = "用于烹制美味的肉类！"

WATHGRITHR.DESCRIBE.BERRYSUNDAE = "我的大脑快冻僵了！"

WATHGRITHR.DESCRIBE.CHOCOLATE_BLACK = "这不是肉，而是……"
WATHGRITHR.DESCRIBE.CHOCOLATE_WHITE = "这不是肉，而是……"

WATHGRITHR.DESCRIBE.TRICOLORDANGO = "它似乎不是肉。"
 
WATHGRITHR.DESCRIBE.FRIESFRENCH = "这不是肉！"

WATHGRITHR.DESCRIBE.PIRATERUM = "闻起来很奇怪，散发出邪恶的气息。"

WATHGRITHR.DESCRIBE.TWISTEDTEQUILA = "这是注入了神秘力量的鸡尾酒！"

WATHGRITHR.DESCRIBE.ONIONRINGS = "烤蔬菜，恶心！"

WATHGRITHR.DESCRIBE.DONUTS = "为什么这么甜？我不明白！"
WATHGRITHR.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "为什么这么甜？我不明白！"
WATHGRITHR.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "为什么这么甜？我不明白！"
 
WATHGRITHR.DESCRIBE.CINNAMONROLL = "螺旋状的小圆面包。"

WATHGRITHR.DESCRIBE.GUMMYBEARGERS = "吃点糖果不会有什么坏处。"

WATHGRITHR.DESCRIBE.PRETZEL = "有点脆。"

WATHGRITHR.DESCRIBE.CORNINCUP = "一杯蔬菜，恶心。"

WATHGRITHR.DESCRIBE.COTTONCANDY = "都是含糖的，不是肉！"

WATHGRITHR.DESCRIBE.ROASTEDHAZELNUTS = "哎哟。弱肉强食。"

WATHGRITHR.DESCRIBE.MONSTERMUFFIN = "我想今天就这样了......"

WATHGRITHR.DESCRIBE.PINKCAKE = "我可以忍受……"

WATHGRITHR.DESCRIBE.CHIPSBAG = "这不是勇士的合适食物！"

WATHGRITHR.DESCRIBE.LITTLEBREAD = "啊哈。对于像我这样的勇士来说，这不是合适的食物！"

WATHGRITHR.DESCRIBE.HOTHOUND = "哈！这对勇士来说是合适的食物！"

WATHGRITHR.DESCRIBE.MILKSHAKE = "无用的食物！"
WATHGRITHR.DESCRIBE.MILKSHAKE_PRISMATIC = "无用的食物！"

WATHGRITHR.DESCRIBE.NACHOS = "呃。"

WATHGRITHR.DESCRIBE.BANANA_PUDDING = "不是勇士食物！"

WATHGRITHR.DESCRIBE.SEA_PUDDING = "这才是真正的布丁！"

WATHGRITHR.DESCRIBE.TOM_KHA_SOUP = "讨厌。"

WATHGRITHR.DESCRIBE.MINERTREAT = "哈！孩子们请客。"

WATHGRITHR.DESCRIBE.RADISHSALAD = "蔬菜是给动物吃的。动物是用来吃的。"

WATHGRITHR.DESCRIBE.PUMPKIN_SOUP = "不错的菜。"

WATHGRITHR.DESCRIBE.ALGAE_SOUP = "不错的菜。"

WATHGRITHR.DESCRIBE.PARZNIP_SOUP = "不错的菜。"

WATHGRITHR.DESCRIBE.NETTLEMEATED = "这块肉的质地很奇怪，但我的鼻窦很干净！"

WATHGRITHR.DESCRIBE.KYNO_SUGAR = "希望我能喝点咖啡。"

WATHGRITHR.DESCRIBE.KYNO_BOTTLECAP = "大写！"

WATHGRITHR.DESCRIBE.NUKACOLA = "为什么我的胃感觉很奇怪？"
WATHGRITHR.DESCRIBE.NUKACOLA_QUANTUM = "为什么我的胃感觉很奇怪？"

WATHGRITHR.DESCRIBE.LIVINGSANDWICH = "这一定是黑魔法！"

WATHGRITHR.DESCRIBE.DURIANSPLIT = "它冻结了我的大脑！"

WATHGRITHR.DESCRIBE.DURIANSOUP = "肉汤！"

WATHGRITHR.DESCRIBE.DURIANMEATED = "闻起来像我的战靴。"

WATHGRITHR.DESCRIBE.DURIANCHICKEN = "一个假先知！"

WATHGRITHR.DESCRIBE.LUNARSOUP = "只是一堆蔬菜，恶心。"

WATHGRITHR.DESCRIBE.PURPLEWOBSTERSOUP = "现在这是适合勇士的汤了！"

WATHGRITHR.DESCRIBE.WOBSTERMONSTER = "不安全的海洋肉类！"

WATHGRITHR.DESCRIBE.SPIDERCAKE = "啊哈！来自我击败的敌人的食物！"

WATHGRITHR.DESCRIBE.SUGARBOMBS = "麦片，嗯嗯。"

WATHGRITHR.DESCRIBE.BERRYBOMBS = "又粘又恶心。"

WATHGRITHR.DESCRIBE.ONIGIRIS = "不是我的菜。"

WATHGRITHR.DESCRIBE.OMURICE = "还不错。"

WATHGRITHR.DESCRIBE.PAELLA = "也许......只吃一点蔬菜也不错？不！"

WATHGRITHR.DESCRIBE.RISOTTO = "那是给弱者的食物！"

WATHGRITHR.DESCRIBE.RICESAKE = "神的饮料！"

WATHGRITHR.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "从地里扯出来的！"

WATHGRITHR.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "啊！它周身布满尖刺。",
	PICKED = "它的战利品耗尽了！",
	WITHERED = "它在落败中枯萎！",
	BURNING = "被火焰斩杀了！",
}

WATHGRITHR.DESCRIBE.KYNO_PINEAPPLE = "这种水果拥有高贵的盔甲。"
WATHGRITHR.DESCRIBE.KYNO_PINEAPPLE_HALVED = "你的盔甲早已不复存在！"
WATHGRITHR.DESCRIBE.KYNO_PINEAPPLE_COOKED = "不是我喜欢吃的水果。"

WATHGRITHR.DESCRIBE.PIZZA_TROPICAL = "现在很糟！"

WATHGRITHR.DESCRIBE.PINACOLADA = "呃。"

WATHGRITHR.DESCRIBE.CHIMAS = "茶！"

WATHGRITHR.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "雨从它的机关里来。",
	ON = "无雷之雨！",
}

WATHGRITHR.DESCRIBE.KYNO_FOODSACK = "恶心，但确实实用。"

WATHGRITHR.DESCRIBE.GUMMYWORMS = "我只是在等待一场大决战！"

WATHGRITHR.DESCRIBE.SMORES = "这个食物不适合真正的勇士！"

WATHGRITHR.DESCRIBE.NUKASHINE = "真正的挑战！宿醉！"

WATHGRITHR.DESCRIBE.ANTSLOG = "真恶心。"

WATHGRITHR.DESCRIBE.KYNO_WORM_BONE = "敌人的尸骨！"

WATHGRITHR.DESCRIBE.SPOOKY_BRAIN_NOODLES = "在我看来已经够诡异了。"
WATHGRITHR.DESCRIBE.SPOOKY_BURGERZILLA = "吓人!"
WATHGRITHR.DESCRIBE.SPOOKY_DEADBREAD = "真恶心。"
WATHGRITHR.DESCRIBE.SPOOKY_JELLYBEANS = "我打败的敌人的眼睛！"
WATHGRITHR.DESCRIBE.SPOOKY_POPSICLE = "非自然。"
WATHGRITHR.DESCRIBE.SPOOKY_PUMPKINCREAM = "呸。"
WATHGRITHR.DESCRIBE.SPOOKY_SKULLCANDY = "生存还是毁灭。"
WATHGRITHR.DESCRIBE.SPOOKY_TACODILE = "可怕的食物，当然！"

WATHGRITHR.DESCRIBE.BUTTER_BEEFALO = "哇。"
WATHGRITHR.DESCRIBE.BUTTER_GOAT = "讨厌。"
WATHGRITHR.DESCRIBE.BUTTER_KOALEFANT = "不狩猎考拉象是无趣的！"

WATHGRITHR.DESCRIBE.SPICE_CURE = "适合腌制肉类。"
WATHGRITHR.DESCRIBE.SPICE_COLD = "啊！这东西怎么这么冷？！"
WATHGRITHR.DESCRIBE.SPICE_FIRE = "啊！它在燃烧！"
WATHGRITHR.DESCRIBE.SPICE_FED = "装满了。"
WATHGRITHR.DESCRIBE.SPICE_MIND = "我在战斗中睡不着！"

WATHGRITHR.DESCRIBE.SUGARFLYMUFFIN = "松饼，脏兮兮的。"

WATHGRITHR.DESCRIBE.EELTACOS = "裹在毯子里的鳗鱼！"

WATHGRITHR.DESCRIBE.MEATSKILLET = "煎锅里的肉！"

WATHGRITHR.DESCRIBE.MEATWALTZ = "我受到了激励！"

WATHGRITHR.DESCRIBE.COMPLETEBREAKFAST = "准备好承担一切！"

WATHGRITHR.DESCRIBE.DUMPLINGS = "这很好！"

WATHGRITHR.DESCRIBE.WARLYICEDTEA = "它不含肉！"

WATHGRITHR.DESCRIBE.WARLYTEA = "我要喝掉你！"

WATHGRITHR.DESCRIBE.KYNO_TEALEAF = "呸。"

WATHGRITHR.DESCRIBE.KYNO_ITEMSLICER = "一把好刀。"
WATHGRITHR.DESCRIBE.KYNO_ITEMSLICER_GOLD = "一把好刀。"

WATHGRITHR.DESCRIBE.COXINHA = "滑油和鸡肉！"

WATHGRITHR.DESCRIBE.LAZYDESSERT = "怪物正在等待它的盛宴！"

WATHGRITHR.DESCRIBE.CRABKINGFEAST = "怎么可能...没关系。"

WATHGRITHR.DESCRIBE.PIENAPPLE = "长刺的水果在这场战斗中失败了，它不值得被吃掉。"

WATHGRITHR.DESCRIBE.JAWSBREAKER = "用于捕猎鲨鱼。"

WATHGRITHR.DESCRIBE.AVOCADOTOAST = "我更喜欢吃肉吐司。"

WATHGRITHR.DESCRIBE.RICEPUDDING = "这个食物不适合真正的勇士！"

WATHGRITHR.DESCRIBE.SHARKSUSHI = "现在我们在谈话！"

WATHGRITHR.DESCRIBE.WOBSTERBREADED = "哈！看看这个，傻乎乎的龙虾！"

WATHGRITHR.DESCRIBE.LAZYPURRITO = "无论如何，我都会继续杀死他们。"

WATHGRITHR.DESCRIBE.HORCHATA = "这个食物不适合真正的勇士！"

WATHGRITHR.DESCRIBE.WOBSTERCOCKTAIL = "美味的饮料！"

WATHGRITHR.DESCRIBE.LAVAEEGGBOILED = "温暖至心！"

WATHGRITHR.DESCRIBE.POMEGRANATETEA = "它不含肉！"

WATHGRITHR.DESCRIBE.TIRAMISU = "与那头野兽战斗真是太有成就感了！"

WATHGRITHR.DESCRIBE.TOADSTOOLCOLA = "这是什么臭烘烘的麦酒？"

WATHGRITHR.DESCRIBE.TEPACHE = "这不是我的专长，但勉强可以。"

WATHGRITHR.DESCRIBE.LUNARTEQUILA = "月球力量被限制。"

WATHGRITHR.DESCRIBE.MIMICMOSA = "只有懦夫才会趁战乱潜逃！"

WATHGRITHR.DESCRIBE.POMEGRANATEPIE = "这个食物不适合真正的勇士！"

WATHGRITHR.DESCRIBE.PINEAPPLECAKE = "这个食物不适合真正的勇士！"

WATHGRITHR.DESCRIBE.PASTY_MEAT = "美味的零食！"
WATHGRITHR.DESCRIBE.PASTY_CHEESE = "这个食物不适合真正的勇士！"

WATHGRITHR.DESCRIBE.BRIGADEIRO = "后天养成的口味。"

WATHGRITHR.DESCRIBE.REGULARLASAGNA = "终于有好的食物了！"

WATHGRITHR.DESCRIBE.FLTSANDWICH = "肉三明治！"

WATHGRITHR.DESCRIBE.RICEANDBEANS = "这个食物不适合真正的勇士！"

WATHGRITHR.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "曾经的殿堂，如今已陨落。命运之年——2026年，它将重生！"

WATHGRITHR.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "不是肉，但或许配得上一场盛宴！",
	PICKED = "已夺取！",
	BURNING = "被火焰斩杀了！",
}

WATHGRITHR.DESCRIBE.KYNO_TRUFFLES = "又是蘑菇……但也许适合盛宴。"
WATHGRITHR.DESCRIBE.KYNO_TRUFFLES_COOKED = "还是不是肉……但香气值得一战！"

WATHGRITHR.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "呸！我光荣的盛宴何须展示柜！",
	FULL = "一份荣耀的献礼！",
}

WATHGRITHR.DESCRIBE.KYNO_SPORECAP = "脆弱的真菌，不配战斗。"
WATHGRITHR.DESCRIBE.KYNO_SPORECAP_COOKED = "熟了也依然是软弱的真菌。"

WATHGRITHR.DESCRIBE.KYNO_SPORECAP_DARK = "肮脏的真菌！不配与我战斗！"
WATHGRITHR.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "火也救不了这孱弱的敌人。"

WATHGRITHR.DESCRIBE.KYNO_GOLDENAPPLE = "值得珍藏的战利品！"

WATHGRITHR.DESCRIBE.TRUFFLESGRINDER = "呸！真菌不是战士的食物！"

WATHGRITHR.DESCRIBE.SPORECAPPIE = "呸！这不是战士的盛宴！"

WATHGRITHR.DESCRIBE.SPORECAP_SKEWERS = "哼！蘑菇不是肉，但将就吧。"

WATHGRITHR.DESCRIBE.TRUFFLEOIL = "呸！我更喜欢战斗的气味，而不是蘑菇汁！"

WATHGRITHR.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "湖泊！准备好要建造了！"
WATHGRITHR.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "斗鱼池！赞同。"

WATHGRITHR.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "一个养育水中新战士的池塘！",
	FUEL_HIGH = "它们正享受着盛宴！",
	FUEL_MED = "它们有些饿了！",
	FUEL_LOW = "盛宴即将结束！",
	EMPTY = "没有食物了！",
}

WATHGRITHR.DESCRIBE.KYNO_ANTCHOVY = "半虫半鱼！双倍的盛宴！"
WATHGRITHR.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "值得我长矛刺穿的学校！"

WATHGRITHR.DESCRIBE.AGEDROE = "我宁愿吃鱼。"
WATHGRITHR.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "巨海怪兽之卵！勇士的零食！"

WATHGRITHR.DESCRIBE.KYNO_SWORDFISH_BLUE = "昔日海洋战士，如今不过是条瑟瑟发抖的孔雀鱼！"

WATHGRITHR.DESCRIBE.KYNO_JELLYFISH = "我原以为海怪会更大些。"
WATHGRITHR.DESCRIBE.KYNO_JELLYFISH_DEAD = "海怪奔赴英灵殿！"
WATHGRITHR.DESCRIBE.KYNO_JELLYFISH_COOKED = "海怪煮得真香！"
WATHGRITHR.DESCRIBE.KYNO_JELLYFISH_DRIED = "我的牙齿将与你交锋。"

WATHGRITHR.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "受弗雷尔女神亲授的美丽。"
WATHGRITHR.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "游泳，不再蜇人。"
WATHGRITHR.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "啊，正经的一顿饭！"

WATHGRITHR.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "既无讯息，亦无饮品。可惜。"

WATHGRITHR.DESCRIBE.KYNO_OCEANTRAP = "给我带来海上的战利品！"

WATHGRITHR.DESCRIBE.OCEANFISH_PUFFERFISH = "它披着尖刺盔甲！堪称海洋劲敌！"
WATHGRITHR.DESCRIBE.OCEANFISH_STURGEON = "传说中的巨鱼！我定要大快朵颐！"

WATHGRITHR.DESCRIBE.KYNO_SWORDFISH = "现在你可真是我心目中的理想伴侣！"
WATHGRITHR.DESCRIBE.KYNO_SWORDFISH_DEAD = "勇往直前，勇敢的鱼啊，奔赴英灵殿。"

WATHGRITHR.DESCRIBE.SWORDFISHFEAST = "勇士的盛宴！鱼自戟而亡！"

WATHGRITHR.DESCRIBE.KYNO_DOGFISH = "大海似乎正为我奉上一场盛宴。"
WATHGRITHR.DESCRIBE.KYNO_DOGFISH_DEAD = "在英灵殿安息吧。"

WATHGRITHR.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "你身上带着失败的气息。"

WATHGRITHR.DESCRIBE.WOBSTER_MONKEYISLAND = "一头金色的海兽！值得猎杀的猎物！"
WATHGRITHR.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "战役已胜！盛宴在前！"
WATHGRITHR.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "来自海洋的战士盛宴！"

WATHGRITHR.DESCRIBE.KYNO_PUFFERMONSTER = "哈！竟有敌人在战前就吹嘘自己！"

WATHGRITHR.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "某物潜伏在下方。"
WATHGRITHR.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "我将终结你的消沉，巨人！"
WATHGRITHR.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "能战胜你，将是我的荣幸。"
WATHGRITHR.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "我将在英灵殿为你举杯。"

WATHGRITHR.DESCRIBE.KYNO_BLUBBER = "这是我族人珍视之物！"

WATHGRITHR.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "干海肉！战士的旅行口粮！"
WATHGRITHR.DESCRIBE.KYNO_FISHMEAT_DRIED = "浓烈风味，专为勇者而生！"

WATHGRITHR.DESCRIBE.MONKEYISLANDMEAL = "堪称女王盛宴的美味！就算里面有……水果。"

WATHGRITHR.DESCRIBE.KYNO_BRAINROCK_LARVAE = "你是肉吗？"
WATHGRITHR.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "没有石中剑从其中心凸出。"
WATHGRITHR.DESCRIBE.KYNO_BRAINROCK_CORAL = "我吃了它，就能获得它的知识吗？"

WATHGRITHR.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "一块神秘而全知的水中之石！",
	PICKED = "它的心智沉睡了！",
}

WATHGRITHR.DESCRIBE.BRAINMETTERSOUP = "哼！给小鬼们的饭菜！"

WATHGRITHR.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "他看起来愿意交易。",
	SLEEPING = "海王安眠了！",
}

WATHGRITHR.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "圣柜存放着祭品。"

WATHGRITHR.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "一件有趣的小玩意儿。",
	WAITING = "一场战斗中的不幸伤亡。",
}

WATHGRITHR.DESCRIBE.KYNO_PACKIMBAGGIMS = "你可愿随我共赴英灵殿？"

WATHGRITHR.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "派对少不了美味蛋糕！"
WATHGRITHR.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "或许我如今成了个烘焙少女。"
WATHGRITHR.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "一场足以匹配伟大战士庆典的盛宴！"
WATHGRITHR.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "微火篝火，为盛宴添光彩！"
WATHGRITHR.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "乔尔的精髓！"
WATHGRITHR.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "这并非肉食...却也可为战斗加油！"
WATHGRITHR.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "勇士不拿气球作战！"

WATHGRITHR.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "一台值得一战的爆米花装置！",
	FUEL_HIGH = "它咆哮着，充满力量！",
	FUEL_MED = "依然强劲！",
	FUEL_LOW = "火焰在减弱！",
	EMPTY = "熔炉沉睡了！",
}

WATHGRITHR.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "玉米爆裂，热力开战！哈！"
WATHGRITHR.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "这顶帽子不承载战士的荣誉……但我仍将骄傲地戴上它！"
WATHGRITHR.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "战士的头盔！"

WATHGRITHR.DESCRIBE.KYNO_FISHREGISTRYHAT = "面对海中生物之人的思考之帽！"

WATHGRITHR.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "给野兽用的食槽！",
	FUEL_HIGH = "配得上勇士的盛宴！",
	FUEL_MED = "它们能撑下去！",
	FUEL_LOW = "盛宴即将结束！",
	EMPTY = "食槽空空如也！",
	BURNT = "被火焰斩杀了！",
}

WATHGRITHR.DESCRIBE.CHICKENNUGGETS = "这肉被塑成了有失荣誉的形状！"

WATHGRITHR.DESCRIBE.CHICKENWINGS = "烈焰鸡翅，配得上勇士！"

WATHGRITHR.DESCRIBE.CHICKENBURGER = "被囚禁在面包中的禽肉盛宴！"

WATHGRITHR.DESCRIBE.CHICKENEGGSOUP = "一碗温热的、蕴含禽类荣誉的肉汤！"

WATHGRITHR.DESCRIBE.CHICKENEGGSTEW = "配得上勇士饥饿的炖菜！"

WATHGRITHR.DESCRIBE.CHICKENROTISSERIE = "值得一战的烤禽，配得上勇士的盛宴。"