local WINONA = STRINGS.CHARACTERS.WINONA

WINONA.ANNOUNCE_KYNO_COFFEEBUFF_START = "工人的经典饮品。"
WINONA.ANNOUNCE_KYNO_COFFEEBUFF_END = "我需要更多咖啡。"

WINONA.ANNOUNCE_KYNO_HASTEBUFF_START = "更快的手速意味着工作完成得更快。"
WINONA.ANNOUNCE_KYNO_HASTEBUFF_END = "哎哟。我的手都放弃了。"

WINONA.ANNOUNCE_KYNO_POPBUFF_START = "（嗝！）糟糕。我喝多了！"
WINONA.ANNOUNCE_KYNO_POPBUFF_END = "我又感觉“正常”了。"

WINONA.ANNOUNCE_KYNO_FROGBUFF_START = "我现在完全闻起来像一只青蛙。"
WINONA.ANNOUNCE_KYNO_FROGBUFF_END = "青蛙味到了！"

WINONA.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝!) 哎呀，我喝多了！"
WINONA.ANNOUNCE_KYNO_PIRATEBUFF_END = "我觉得自己又\"正常\"了。"

WINONA.ANNOUNCE_KYNO_FREEZEBUFF_START = "霜冻来了。"
WINONA.ANNOUNCE_KYNO_FREEZEBUFF_END = "回到正常工作。"

WINONA.ANNOUNCE_KYNO_FIREBUFF_START = "只是一小撮火焰。"
WINONA.ANNOUNCE_KYNO_FIREBUFF_END = "回到正常工作。"

WINONA.ANNOUNCE_KYNO_FISHINGBUFF_START = "我们去钓鱼吧！"
WINONA.ANNOUNCE_KYNO_FISHINGBUFF_END = "我想是时候停止钓鱼了。"

WINONA.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "每个人都需要放松一下。"
WINONA.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "好吧，回去工作！"

WINONA.ANNOUNCE_KYNO_EATERBUFF_START = "工作既容易又轻松。"
WINONA.ANNOUNCE_KYNO_EATERBUFF_END = "一顿美餐需要耐心。"

WINONA.ANNOUNCE_KYNO_WORMBUFF_START = "是时候开始工作了。"
WINONA.ANNOUNCE_KYNO_WORMBUFF_END = "这些虫子不安分。"

WINONA.ANNOUNCE_KYNO_CRABBUFF_START = "工作的时间到了。"
WINONA.ANNOUNCE_KYNO_CRABBUFF_END = "这些螃蟹不安分。"

WINONA.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝！) 哎呀。我喝得太多了！"
WINONA.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "我感觉再次\"正常\"。"

WINONA.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "月亮的能量正在溢出！"
WINONA.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "回到我平常的思路。"

WINONA.ANNOUNCE_KYNO_STEALTHBUFF_START = "现在我看起来像你了吗，姐妹？"
WINONA.ANNOUNCE_KYNO_STEALTHBUFF_END = "我显身了！或者..."

WINONA.ANNOUNCE_KYNO_FEARBUFF_START = "我想我终于可以做点什么了，不用为每一个噪音而激动。"
WINONA.ANNOUNCE_KYNO_FEARBUFF_END = "好的。我想，是时候回到紧张混乱的状态了。"

WINONA.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "这果汁劲儿真大！"
WINONA.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "能量用完啦！回去干活！"

WINONA.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "看来有些帮手猪跟着我走。"
WINONA.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "看来猪们不会留下。"

WINONA.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "好啊，酸雨，放马过来！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WINONA.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "哈！在我值班时可没有毒素！"
WINONA.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "唉，免费的保护没了。"

WINONA.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "是时候全力以赴，仿佛明天不会到来！"
WINONA.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "看来忙乱终于结束了。回归日常工作吧！"

WINONA.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "蜜蜂撤下警戒了。干得好，小家伙们！"
WINONA.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "休息结束。蜜蜂们又开始上班了。"

WINONA.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "嘿，这真是个好助力！"
WINONA.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "恢复正常了……真倒霉。"

WINONA.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "消耗更多热量，完成更多工作！"
WINONA.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "看来休息时间现在缩短了。"

WINONA.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "别分心！是时候干活了！"
WINONA.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "注意力开始涣散……不太妙。"

WINONA.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "这又增加了一层很好的保护。"
WINONA.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "保护措施失效了！"

WINONA.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "不行。"

WINONA.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "不行，或许需要别的。"

WINONA.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "目前不打算用它，得再等等。"

WINONA.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "不行。"

WINONA.ANNOUNCE_KYNO_POTHANGER_FAIL = "它需要一个锅来做饭。"

WINONA.ANNOUNCE_KYNO_CASSEROLE_FAIL = "不行。它需要一个砂锅。"

WINONA.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "工具确实能让脏活更轻松。"

WINONA.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "什么都没剩下。萨米肯定已经收拾走了。"

WINONA.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "线索就此中断。一切又回到原点。"
WINONA.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "唉，所有努力——都白费了。"
WINONA.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "大家注意了，大麻烦来了！"

WINONA.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "蛋糕做好啦！干得漂亮，伙计们！"

WINONA.ANNOUNCE_KYNO_FISH_RESEARCHED = "嗯，这鱼确实教了我点有用的。"
WINONA.ANNOUNCE_KYNO_ROE_RESEARCHED = "不好看，但很有用。知识就是知识。"

WINONA.DESCRIBE.KYNO_ROE = "鱼子，鱼子，鱼子...我要疯了。"
WINONA.DESCRIBE.KYNO_ROE_COOKED = "至少他们没有脸。"

WINONA.DESCRIBE.KYNO_SHARK_FIN = "我唯一想看的鱼鳍。"

WINONA.DESCRIBE.KYNO_BEANBUGS = "你确实精力充沛。"
WINONA.DESCRIBE.KYNO_BEANBUGS_COOKED = "我不确定我应该吃那些。"

WINONA.DESCRIBE.KYNO_GUMMYBUG = "放轻松。"
WINONA.DESCRIBE.KYNO_GUMMYBUG_COOKED = "看起来不太好吃。"

WINONA.DESCRIBE.KYNO_WHEAT = "只要有可能，我就会违背常规。哈！"
WINONA.DESCRIBE.KYNO_WHEAT_COOKED = "只要有可能，我就会违背常规。哈！"

WINONA.DESCRIBE.KYNO_FLOUR = "嗯，这对做饭很有用。"

WINONA.DESCRIBE.KYNO_SPOTSPICE = "这应该会增加一些刺激。"

WINONA.DESCRIBE.KYNO_SAP = "好吧，这很不错。"
WINONA.DESCRIBE.KYNO_SAP_SPOILED = "现在不行了。"

WINONA.DESCRIBE.KYNO_SYRUP = "就像树上的蜂蜜。"

WINONA.DESCRIBE.KYNO_COFFEEBEANS = "过来找妈妈！"
WINONA.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "兴奋！"

WINONA.DESCRIBE.DUG_KYNO_COFFEEBUSH = "爪哇产地！"
WINONA.DESCRIBE.KYNO_COFFEEBUSH = "爪哇产地！"

WINONA.DESCRIBE.DUG_KYNO_SPOTBUSH = "是的，我们可能会吃掉那个。"
WINONA.DESCRIBE.KYNO_SPOTBUSH = "是的，我们可能会吃掉那个。"

WINONA.DESCRIBE.KYNO_SPOTSPICE_LEAF = "尝起来有点像……胡椒？"

WINONA.DESCRIBE.KYNO_MUSSEL = "我可以吃一百个。"
WINONA.DESCRIBE.KYNO_MUSSEL_COOKED = "需要一点葱段。"

WINONA.DESCRIBE.KYNO_HUMANMEAT = "这是个糟糕的主意。"
WINONA.DESCRIBE.KYNO_HUMANMEAT_COOKED = "谁认为这是个好主意？"
WINONA.DESCRIBE.KYNO_HUMANMEAT_DRIED = "不。"

WINONA.DESCRIBE.COFFEE = "闻起来很香！"

WINONA.DESCRIBE.BISQUE = "这实际上可能值得付出努力！"

WINONA.DESCRIBE.JELLYOPOP = "这是垃圾食品还是健康食品？我不知道。"

WINONA.DESCRIBE.SHARKFINSOUP = "我可以直接把脸塞进去。"

WINONA.DESCRIBE.TROPICALBOUILLABAISSE = "丰盛的鱼汤！"

WINONA.DESCRIBE.MUSSELBOUILLABAISE = "海鲜，​​我的最爱。"

WINONA.DESCRIBE.SWEETPOTATOSOUFFLE = "好好吃！"

WINONA.DESCRIBE.FEIJOADA = "嗯……你还能尝到泥土的味道。"

WINONA.DESCRIBE.GUMMY_CAKE = "蛋糕是个谎言！"

WINONA.DESCRIBE.HARDSHELL_TACOS = "我更喜欢玉米卷饼。"

WINONA.DESCRIBE.ICEDTEA = "啊……恰到好处。"

WINONA.DESCRIBE.NETTLELOSANGE = "药用营养品。"

WINONA.DESCRIBE.SNAKEBONESOUP = "不错的热汤。"

WINONA.DESCRIBE.STEAMEDHAMSANDWICH = "这是快餐。"

WINONA.DESCRIBE.TEA = "咖啡因！"

WINONA.DESCRIBE.BUBBLETEA = "啊……恰到好处。"

WINONA.DESCRIBE.FRENCHONIONSOUP = "好热的汤。"

WINONA.DESCRIBE.SLAW = "很多新鲜蔬菜。"

WINONA.DESCRIBE.LOTUSBOWL = "嗯……好吃。"

WINONA.DESCRIBE.POI = "我猜是热带食物。"

WINONA.DESCRIBE.JELLYBEAN_HUNGER = "我会一口气吃掉它们。"
WINONA.DESCRIBE.JELLYBEAN_SUPER = "我会一口气吃掉它们。"
WINONA.DESCRIBE.JELLYBEAN_SANITY = "我会一口气吃掉它们。"

WINONA.DESCRIBE.BOWLOFGEARS = "哇，这里有人非常需要装备，是吗？"

WINONA.DESCRIBE.LONGPIGMEAL = "这是个糟糕的主意。"

WINONA.DESCRIBE.CUCUMBERSALAD = "这就是我所说的健康食品。"

WINONA.DESCRIBE.KYNO_WILDWHEAT = "满足你对小麦的所有需求。"
WINONA.DESCRIBE.DUG_KYNO_WILDWHEAT = "满足你对小麦的所有需求。"

WINONA.DESCRIBE.KYNO_MEALGRINDER = "啊！一项可能需要艰苦的工作！"

WINONA.DESCRIBE.GORGE_BREAD = "经典，你不觉得吗？"
WINONA.DESCRIBE.GORGE_SWEET_CHIPS = "这可能会让某人工作几个小时。"
WINONA.DESCRIBE.GORGE_VEGETABLE_SOUP = "我可以使用更强大的东西。"
WINONA.DESCRIBE.GORGE_JELLY_SANDWICH = "看起来不错！"
WINONA.DESCRIBE.GORGE_FISH_STEW = "全是鱼眼。"
WINONA.DESCRIBE.GORGE_MEAT_STEW = "这顿饭看起来很丰盛。"
WINONA.DESCRIBE.GORGE_ONION_CAKE = "我想这样就可以了……"
WINONA.DESCRIBE.GORGE_POTATO_PANCAKES = "我怀念过去的时光。"
WINONA.DESCRIBE.GORGE_POTATO_SOUP = "这样的努力也许是值得的！"
WINONA.DESCRIBE.GORGE_FISHBALL_SKEWERS = "鱼球。"
WINONA.DESCRIBE.GORGE_MEAT_SKEWERS = "肉类。"
WINONA.DESCRIBE.GORGE_STONE_SOUP = "这样的努力也许是值得的！"
WINONA.DESCRIBE.GORGE_CROQUETTE = "小吃！"
WINONA.DESCRIBE.GORGE_ROAST_VEGETABLES = "午餐时间！"
WINONA.DESCRIBE.GORGE_MEATLOAF = "午餐时间。"
WINONA.DESCRIBE.GORGE_CARROT_SOUP = "这样的努力也许是值得的！"
WINONA.DESCRIBE.GORGE_FISHPIE = "我吃过更好的海鲜餐。"
WINONA.DESCRIBE.GORGE_FISHCHIPS = "小吃时间!"
WINONA.DESCRIBE.GORGE_MEATPIE = "我吃饱了！"
WINONA.DESCRIBE.GORGE_SLIDERS = "小吃！"
WINONA.DESCRIBE.GORGE_JELLY_ROLL = "让我们一起演奏！"
WINONA.DESCRIBE.GORGE_CARROT_CAKE = "精美的蛋糕。"
WINONA.DESCRIBE.GORGE_GARLICMASHED = "午餐时间。"
WINONA.DESCRIBE.GORGE_GARLICBREAD = "有品位！"
WINONA.DESCRIBE.GORGE_TOMATO_SOUP = "这样的努力也许是值得的！"
WINONA.DESCRIBE.GORGE_SAUSAGE = "我喜欢烤着吃。"
WINONA.DESCRIBE.GORGE_CANDIEDFISH = "真甜!"
WINONA.DESCRIBE.GORGE_STUFFEDMUSHROOM = "小吃。"
WINONA.DESCRIBE.GORGE_BRUSCHETTA = "小吃。"
WINONA.DESCRIBE.GORGE_HAMBURGER = "对我来说这不是合适的食物，但嘿，它有点东西。"
WINONA.DESCRIBE.GORGE_FISHBURGER = "对我来说不是合适的食物，但嘿，它是东西。"
WINONA.DESCRIBE.GORGE_MUSHROOMBURGER = "对我来说不是合适的食物，但嘿，它是东西。"
WINONA.DESCRIBE.GORGE_FISH_STEAK = "全是鱼眼。"
WINONA.DESCRIBE.GORGE_CURRY = "在我心中，有着特殊的地位。"
WINONA.DESCRIBE.GORGE_SPAGHETTI = "美味。"
WINONA.DESCRIBE.GORGE_POACHEDFISH = "味道不错。"
WINONA.DESCRIBE.GORGE_SHEPHERD_PIE = "嗯，真好吃！"
WINONA.DESCRIBE.GORGE_CANDY = "适当的食物粘在你的牙齿上！"
WINONA.DESCRIBE.GORGE_BREAD_PUDDING = "完美的甜品。"
WINONA.DESCRIBE.GORGE_BERRY_TART = "甜点心！"
WINONA.DESCRIBE.GORGE_MACARONI = "小吃！"
WINONA.DESCRIBE.GORGE_BAGEL_AND_FISH = "午餐时间！"
WINONA.DESCRIBE.GORGE_GRILLED_CHEESE = "啊，美味的早餐，美好的过去。"
WINONA.DESCRIBE.GORGE_CREAMMUSHROOM = "我不太喜欢喝汤。"
WINONA.DESCRIBE.GORGE_MANICOTTI = "午饭时间到了吧。"
WINONA.DESCRIBE.GORGE_CHEESEBURGER = "对我来说不是合适的食物，但嘿，它是东西。"
WINONA.DESCRIBE.GORGE_FETTUCCINE = "不是我最喜欢的那种饭菜。"
WINONA.DESCRIBE.GORGE_ONION_SOUP = "哦，好家伙。"
WINONA.DESCRIBE.GORGE_BREADED_CUTLET = "晚间小吃的佳品。"
WINONA.DESCRIBE.GORGE_CREAMY_FISH = "这下可好了。"
WINONA.DESCRIBE.GORGE_PIZZA = "有时我应该得到一顿美餐。"
WINONA.DESCRIBE.GORGE_POT_ROAST = "哇!"
WINONA.DESCRIBE.GORGE_CRAB_CAKE = "可爱的小家伙。"
WINONA.DESCRIBE.GORGE_STEAK_FRITES = "简单快捷。非常有品位。"
WINONA.DESCRIBE.GORGE_SHOOTER_SANDWICH = "小吃！"
WINONA.DESCRIBE.GORGE_BACON_WRAPPED = "我不能说我不喜欢。"
WINONA.DESCRIBE.GORGE_CRAB_ROLL = "嘿，真不错。"
WINONA.DESCRIBE.GORGE_MEAT_WELLINGTON = "我必须指出的是，这一个是最重要的。"
WINONA.DESCRIBE.GORGE_CRAB_RAVIOLI = "嘿，真不错。"
WINONA.DESCRIBE.GORGE_CARAMEL_CUBE = "这个很特别。"
WINONA.DESCRIBE.GORGE_SCONE = "似乎很贵。"
WINONA.DESCRIBE.GORGE_TRIFLE = "似乎很贵。"
WINONA.DESCRIBE.GORGE_CHEESECAKE = "准备进我的肚子！"

WINONA.DESCRIBE.DUCKYOUGLERMZ = "多么邪恶的一餐."

WINONA.DESCRIBE.KYNO_ALOE = "芦荟对一切都有好处。"
WINONA.DESCRIBE.KYNO_ALOE_COOKED = "好吃！"
WINONA.DESCRIBE.KYNO_ALOE_GROUND = "芦荟对一切都有好处。"
WINONA.DESCRIBE.KYNO_ALOE_SEEDS = "一把种子。"
WINONA.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "一把种子。"
WINONA.DESCRIBE.FARM_PLANT_KYNO_ALOE = "芦荟对一切都有好处。"
WINONA.DESCRIBE.KYNO_ALOE_OVERSIZED = "芦荟什么都好。"
WINONA.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "啊 当!"

WINONA.DESCRIBE.KYNO_CUCUMBER = "我会尝试一次。"
WINONA.DESCRIBE.KYNO_CUCUMBER_COOKED = "好吧，我不会这样准备的。"
WINONA.DESCRIBE.KYNO_CUCUMBER_GROUND = "我会尝试一次。"
WINONA.DESCRIBE.KYNO_CUCUMBER_SEEDS = "一把种子。"
WINONA.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "一把种子。"
WINONA.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "我会尝试一次。"
WINONA.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "我会尝试一次。"
WINONA.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "我会尝试一次。"

WINONA.DESCRIBE.KYNO_RADISH = "萝卜！"
WINONA.DESCRIBE.KYNO_RADISH_COOKED = "嗯..."
WINONA.DESCRIBE.KYNO_RADISH_GROUND = "萝卜！"
WINONA.DESCRIBE.KYNO_RADISH_SEEDS = "一把种子。"
WINONA.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "一把种子。"
WINONA.DESCRIBE.FARM_PLANT_KYNO_RADISH = "激进派！"
WINONA.DESCRIBE.KYNO_RADISH_OVERSIZED = "激进派！"
WINONA.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "啊 当!"

WINONA.DESCRIBE.KYNO_FENNEL = "我觉得可以吃。"
WINONA.DESCRIBE.KYNO_FENNEL_COOKED = "闻起来有春天的味道。"
WINONA.DESCRIBE.KYNO_FENNEL_GROUND = "我觉得可以吃。"
WINONA.DESCRIBE.KYNO_FENNEL_SEEDS = "一把种子。"
WINONA.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "一把种子。"
WINONA.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "我看可以吃。"
WINONA.DESCRIBE.KYNO_FENNEL_OVERSIZED = "我看可以吃。"
WINONA.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "啊 当!"

WINONA.DESCRIBE.KYNO_SWEETPOTATO = "甜点！"
WINONA.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "嗯，实际上没那么甜。"
WINONA.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "甜点！"
WINONA.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "一把种子。"
WINONA.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "一把种子。"
WINONA.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "甜点!"
WINONA.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "甜点!"
WINONA.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "啊 当!"

WINONA.DESCRIBE.KYNO_PARZNIP = "从地下免费食物。"
WINONA.DESCRIBE.KYNO_PARZNIP_COOKED = "免费提供地下食物。"
WINONA.DESCRIBE.KYNO_PARZNIP_EATEN = "免费提供地下食物。"
WINONA.DESCRIBE.KYNO_PARZNIP_GROUND = "从地下释放食物。"
WINONA.DESCRIBE.KYNO_PARZNIP_BIG = "这让我想吃一周的午餐！"
WINONA.DESCRIBE.KYNO_PARZNIP_SEEDS = "一把种子。"
WINONA.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "一把种子。"
WINONA.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "从地下释放食物。"
WINONA.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "免费提供地下食物。"
WINONA.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "啊 当!"

WINONA.DESCRIBE.KYNO_TURNIP = "新鲜成熟的萝卜。"
WINONA.DESCRIBE.KYNO_TURNIP_COOKED = "我不想自己吃。"
WINONA.DESCRIBE.KYNO_TURNIP_GROUND = "新鲜成熟的萝卜。"
WINONA.DESCRIBE.KYNO_TURNIP_SEEDS = "一把种子。"
WINONA.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "一把种子。"
WINONA.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "新鲜成熟的萝卜。"
WINONA.DESCRIBE.KYNO_TURNIP_OVERSIZED = "新鲜成熟的萝卜。"
WINONA.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "啊 当!"

WINONA.DESCRIBE.KYNO_RICE = "我可以接受。"
WINONA.DESCRIBE.KYNO_RICE_COOKED = "我可以接受。"
WINONA.DESCRIBE.KYNO_RICE_SEEDS = "一把种子。"
WINONA.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "一把种子。"
WINONA.DESCRIBE.FARM_PLANT_KYNO_RICE = "新鲜、成熟、未经碾磨的米。"
WINONA.DESCRIBE.KYNO_RICE_OVERSIZED = "新鲜、成熟、未经碾磨的米。"
WINONA.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "啊 当!"

WINONA.DESCRIBE.KYNO_SEEDS_KIT = "蔬菜种子。"

WINONA.DESCRIBE.KYNO_LIMPETROCK = "看看这些巴尼。"
WINONA.DESCRIBE.KYNO_LIMPETS = "他们摆脱了日常生活的喧嚣。"
WINONA.DESCRIBE.KYNO_LIMPETS_COOKED = "还是有点粘。"

WINONA.DESCRIBE.KYNO_LOTUS_OCEAN = "那些午餐会很棒！"
WINONA.DESCRIBE.KYNO_LOTUS_ROOT = "现在我可以在任何地方种植它了。"
WINONA.DESCRIBE.KYNO_LOTUS_FLOWER = "漂亮！"
WINONA.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "嗯……好吃。"

WINONA.DESCRIBE.KYNO_SEAWEEDS_OCEAN = "名字说明了一切。"
WINONA.DESCRIBE.KYNO_SEAWEEDS = "名字说明了一切。"
WINONA.DESCRIBE.KYNO_SEAWEEDS_COOKED = "我想稍微好一点..."
WINONA.DESCRIBE.KYNO_SEAWEEDS_DRIED = "吃点脆脆的会更好。"
WINONA.DESCRIBE.KYNO_SEAWEEDS_ROOT = "现在我可以把它种在我想要的地方。"

WINONA.DESCRIBE.KYNO_TAROROOT_OCEAN = "我可以在午餐时吃这个。"
WINONA.DESCRIBE.KYNO_TAROROOT_ROOT = "现在我可以在任何地方种植它了。"
WINONA.DESCRIBE.KYNO_TAROROOT = "看看有多奇怪！哈！"
WINONA.DESCRIBE.KYNO_TAROROOT_COOKED = "那是不是变得更好了？我不知道。"

WINONA.DESCRIBE.KYNO_WATERYCRESS_OCEAN = "看起来很好吃。"
WINONA.DESCRIBE.KYNO_WATERYCRESS_ROOT = "现在我可以在任何地方种植它了。"
WINONA.DESCRIBE.KYNO_WATERYCRESS = "看起来很好吃。"

WINONA.DESCRIBE.WATERYCRESSBOWL = "汤永远不会出错。"

WINONA.DESCRIBE.KYNO_SALT = "但是胡椒在哪里？"

WINONA.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "他们顺势而为。"

WINONA.DESCRIBE.CATFOOD = "给小伙伴的零食。"

WINONA.DESCRIBE.KATFOOD = "给小伙伴的零食。"

WINONA.DESCRIBE.KYNO_BANANATREE = "那是，呃，香蕉树。"
WINONA.DESCRIBE.KYNO_BANANA = "钾！"
WINONA.DESCRIBE.KYNO_BANANA_COOKED = "烤熟的钾！"

WINONA.DESCRIBE.KYNO_KOKONUTTREE = "酷头发，树。"
WINONA.DESCRIBE.KYNO_KOKONUT = "想象一下被其中一个人打到头上！"
WINONA.DESCRIBE.KYNO_KOKONUT_HALVED = "你花一个钱买两个。噗。"
WINONA.DESCRIBE.KYNO_KOKONUT_COOKED = "嗯。是的。现在已经烤好了。"

WINONA.DESCRIBE.BOWLOFPOPCORN = "我很快需要一根牙签。"

WINONA.DESCRIBE.FIGJUICE = "啊……恰到好处。"

WINONA.DESCRIBE.COCONUTWATER = "啊……恰到好处。"

WINONA.DESCRIBE.EYEBALLSPAGHETTI = "我想，这总比挨饿好。"

WINONA.DESCRIBE.FORGETMELOTS_SEEDS = "一把种子。"

WINONA.DESCRIBE.FIRENETTLES_SEEDS = "一把种子。"

WINONA.DESCRIBE.TILLWEED_SEEDS = "一把种子。"

WINONA.DESCRIBE.KYNO_FLOATILIZER = "地面食物。"

WINONA.DESCRIBE.KYNO_TWIGGYNUTS = "一些坚果。"

WINONA.DESCRIBE.KYNO_REPAIRTOOL = "维护至关重要！"

WINONA.DESCRIBE.KYNO_KOI = "看起来像那些有钱人在池塘里养的鱼。"
WINONA.DESCRIBE.KYNO_KOI_COOKED = "看起来像那些有钱人在池塘里放的鱼。"

WINONA.DESCRIBE.KYNO_TROPICALFISH = "好美味的颜色！"
WINONA.DESCRIBE.KYNO_TROPICALFISH_COOKED = "午餐时间！"

WINONA.DESCRIBE.KYNO_NEONFISH = "多么可爱的小家伙！"
WINONA.DESCRIBE.KYNO_NEONFISH_COOKED = "对不起。我还要吃饭。"

WINONA.DESCRIBE.KYNO_GROUPER = "他的笨拙有点讨人喜欢。"
WINONA.DESCRIBE.KYNO_GROUPER_COOKED = "对不起，伙计。是你还是我。"
 
WINONA.DESCRIBE.KYNO_PIERROTFISH = "我杀不了它！看它多可爱！"
WINONA.DESCRIBE.KYNO_PIERROTFISH_COOKED = "美味，美味的罪恶感。"

WINONA.DESCRIBE.KYNO_SALMONFISH = "不是粉红色的。是鲑鱼！哈！"
WINONA.DESCRIBE.KYNO_SALMONFISH_COOKED = "高档餐厅。"

WINONA.DESCRIBE.TURF_PINKPARK = "我喜欢。"
WINONA.DESCRIBE.TURF_STONECITY = "固体泥土。"
WINONA.DESCRIBE.TURF_FIELDS = "泥土。"
WINONA.DESCRIBE.TURF_TIDALMARSH = "沼泽。"

WINONA.DESCRIBE.KYNO_SALTRACK_INSTALLER = "让我们开始吧！"

WINONA.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "桶。最先进的农业技术。"

WINONA.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "这里是小螃蟹。"

WINONA.DESCRIBE.KYNO_SERENITYISLAND_SHOP = "你是个大个子，嘿？"

WINONA.DESCRIBE.KYNO_SUGARTREE_BUD = "我听说它尝起来像糖。"

WINONA.DESCRIBE.KYNO_SUGARTREE_FLOWER = "有点可爱。"
WINONA.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "有点可爱。"

WINONA.DESCRIBE.KYNO_SUGARTREE_PETALS = "有点可爱。"

WINONA.DESCRIBE.KYNO_PEBBLECRAB = "他不会对任何人构成威胁。"

WINONA.DESCRIBE.KYNO_CRABMEAT = "我饿的时候会发脾气。哈！"
WINONA.DESCRIBE.KYNO_CRABMEAT_COOKED = "这是一大块烤熟的螃蟹。"
WINONA.DESCRIBE.KYNO_CRABMEAT_DRIED = "我一饿就会发脾气。哈！"

WINONA.DESCRIBE.KYNO_CRABKINGMEAT = "我一饿就会发脾气。哈！"
WINONA.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "我饿的时候脾气暴躁。哈！"
WINONA.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "我饿的时候脾气暴躁。哈！"

WINONA.DESCRIBE.KYNO_SLAUGHTERTOOL = "不是我喜欢的工具。"

WINONA.DESCRIBE.KYNO_CHICKEN2 = "喜欢这个造型，小鸡。"

WINONA.DESCRIBE.KYNO_CHICKEN_EGG = "早餐。"
WINONA.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "Now that's a lot of heavy lifting for one hen."
WINONA.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "我总是不小心弄到一些贝壳。"

WINONA.DESCRIBE.KYNO_CHICKENHOUSE = "结构坚固，足以约束鸡群。"

WINONA.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "我想我可以解决这个问题。"

WINONA.DESCRIBE.KYNO_COOKWARE_KIT = "什么？一个工具包？我怀疑里面有厨师！"
WINONA.DESCRIBE.KYNO_COOKWARE_SYRUP = "糖浆让我变得更强壮。哈！"
WINONA.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "糖浆让我变得更强壮。哈！"
WINONA.DESCRIBE.KYNO_COOKWARE_BIG_POT = "可以在那个锅里做一道真正的大炖菜。"
WINONA.DESCRIBE.KYNO_COOKWARE_BIG = "可以在那个锅里做一道真正的大炖菜。"
WINONA.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "一个用来烹饪食物的锅。"
WINONA.DESCRIBE.KYNO_COOKWARE_SMALL = "一个用来烹饪食物的锅。"
WINONA.DESCRIBE.KYNO_COOKWARE_GRILL = "野餐时间到了！"
WINONA.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "我需要找到一个火坑才能让它工作。"
WINONA.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "足够大，适合小型野炊。"
WINONA.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "现在我可以把这个放在哪里..."
WINONA.DESCRIBE.KYNO_COOKWARE_ELDER = "糖浆让我变得更强壮。哈！"
WINONA.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "哎呀。又是一天，另一个项目。"
WINONA.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "我需要烤一下。"
WINONA.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "用于制作小炖菜之类的。"
WINONA.DESCRIBE.KYNO_COOKWARE_OVEN = "这是一个普通的烤箱。"
WINONA.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "这是一个普通的烤箱。"
WINONA.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "这是一个普通的烤箱。"

WINONA.DESCRIBE.KYNO_ROCKFLIPPABLE = "想知道这块岩石下面是什么吗？"
WINONA.DESCRIBE.KYNO_ROCKFLIPPABLE_CAVE = "想知道这块岩石下面是什么吗？"

WINONA.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "这里有什么东西。"

WINONA.DESCRIBE.KYNO_SUGARFLY = "多么漂亮的图案！"
WINONA.DESCRIBE.KYNO_SUGARFLYWINGS = "我感觉很糟糕。"

WINONA.DESCRIBE.KYNO_WATERY_CRATE = "这里有什么东西。"

WINONA.DESCRIBE.KYNO_TUNACAN = "哇！美味至极！"
WINONA.DESCRIBE.KYNO_TUNACAN_OPEN = "哇！美味至极！"

WINONA.DESCRIBE.KYNO_CANNEDFOOD = "哇！正义的非破坏！"
WINONA.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "哇！正义的非破坏！"

WINONA.DESCRIBE.KYNO_POP = "烈酒！"

WINONA.DESCRIBE.KYNO_MYSTERYMEAT = "总蘑菇汉堡。"

WINONA.DESCRIBE.KYNO_BOTTLE_SOUL = "我对此无话可说。"

WINONA.DESCRIBE.SOULSTEW = "我对此无话可说。"

WINONA.DESCRIBE.FORTUNECOOKIE = "哼。我不相信这行得通。"

WINONA.DESCRIBE.HORNOCUPIA = "我正在为它雕刻。"

WINONA.DESCRIBE.CHEESE_YELLOW = "现在只是少了一块好面包。"
WINONA.DESCRIBE.CHEESE_WHITE = "现在只是少了一块好面包。"
WINONA.DESCRIBE.CHEESE_KOALEFANT = "现在只是少了一块好面包。"

WINONA.DESCRIBE.MILK_BOX = "没有什么比早上喝牛奶更好的了。"

WINONA.DESCRIBE.WATERCUP = "水永远是受欢迎的饮品。"

WINONA.DESCRIBE.HONEYJAR = "我舔了一下..."

WINONA.DESCRIBE.CRAB_ARTICHOKE = "很好，很好，我喜欢螃蟹。"

WINONA.DESCRIBE.PEPPERROLLS = "他们在我嘴里开派对！"

WINONA.DESCRIBE.KYNO_SAPHEALER = "这会让病痛消失。"

WINONA.DESCRIBE.KYNO_OCEAN_WRECK = "短期内可能不会航行。"

WINONA.DESCRIBE.KYNO_GHOST_PIRATE = "哎呀。他本可以永远睡下去，但他回来了。"

WINONA.DESCRIBE.KYNO_BUCKET_EMPTY = "当然，这会派上用场！"
WINONA.DESCRIBE.KYNO_BUCKET_METAL = "一项精细的冶金工作。"
WINONA.DESCRIBE.KYNO_BUCKET_WATER = "适合给机器或人降温。"

WINONA.DESCRIBE.KYNO_MILK_BEEFALO = "下降的感觉刺痛。"
WINONA.DESCRIBE.KYNO_MILK_KOALEFANT = "下降的感觉刺痛。"

WINONA.DESCRIBE.KYNO_CAP_DRIED = "味道不错，我猜？"

WINONA.DESCRIBE.KYNO_PLANTMEAT_DRIED = "女孩，这肉干！"

WINONA.DESCRIBE.KYNO_BREWBOOK = "拥有蓝图肯定会让酿造变得更容易！"

WINONA.DESCRIBE.KYNO_WOODENKEG = "啊，我想念那些。"

WINONA.DESCRIBE.KYNO_PRESERVESJAR = "现在我只需要原料就可以开始酿造了。"

WINONA.DESCRIBE.KYNO_ANTCHEST = "它为我制作了所有的蜂蜜！"

WINONA.DESCRIBE.KYNO_NECTAR_POD = "我想知道我能不能用这个做蜂蜜。"

WINONA.DESCRIBE.KYNO_OAKTREE_POD = "需要把它种在某个地方。"
WINONA.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "不费吹灰之力的一顿美餐。"

WINONA.DESCRIBE.KYNO_PIKO = "这是一个小伙伴！"
WINONA.DESCRIBE.KYNO_PIKO_ORANGE = "哦，我明白了。"

WINONA.DESCRIBE.KYNO_MEADOWISLAND_TREE = "嘿，小树！"
WINONA.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = "我希望他们不要偷我的工具。"
WINONA.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "想知道里面有什么。"
WINONA.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = "我可以拆开它。"
WINONA.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = "工人们休息 5 分钟。"
WINONA.DESCRIBE.KYNO_MEADOWISLAND_SHOP = "那是苔藓之门的钥匙吗？"
WINONA.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = "那些是一些不错的巨大作物。"
WINONA.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "他怎么会来到这里？"
WINONA.DESCRIBE.KYNO_MEADOWISLAND_POND = "想知道它有多深......"
WINONA.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "一株小小的植物。"
WINONA.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "如果这个更大，我可以用沙盘。"
WINONA.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "你不介意以工作为生。"

WINONA.DESCRIBE.KYNO_SAMMYHAT = "哦！我以前有一个。"

WINONA.DESCRIBE.KINGFISHER = "粗糙的喙，伙计。"

WINONA.DESCRIBE.TOUCAN = "你可以用这样的鼻子捕捉海浪！"
WINONA.DESCRIBE.TOUCAN_CHUBBY = "你可以用这样的鼻子捕捉海浪！"

WINONA.DESCRIBE.WETGOOP2 = "这是干粘液吗？"

WINONA.DESCRIBE.BEER = "我过去常常在辛苦工作一天后喝它们。"

WINONA.DESCRIBE.PALEALE = "我过去常常在辛苦工作一天后喝它们。"

WINONA.DESCRIBE.TEAGREEN = "我没时间喝茶！还有工作要做，比如……呃……"

WINONA.DESCRIBE.TEARED = "我没时间喝茶！还有工作要做，比如……呃……"

WINONA.DESCRIBE.MEAD = "看起来很土气。"

WINONA.DESCRIBE.KYNO_JELLY = "保留那些果酱。"

WINONA.DESCRIBE.KYNO_MAYONNAISE = "很好，但需要一些东西。"

WINONA.DESCRIBE.TARTARSAUCE = "我有点喜欢，不知道为什么。"

WINONA.DESCRIBE.KYNO_PICKLES = "腌制！"

WINONA.DESCRIBE.KYNO_WINE = "我们今天很大胆。"

WINONA.DESCRIBE.KYNO_JUICE = "我更喜欢用水果做的果汁。"

WINONA.DESCRIBE.KYNO_POISON_FROGLEGS = "我不知道为什么，但我认为我不应该吃那些。"
WINONA.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "看起来有点好吃。"

WINONA.DESCRIBE.POISONFROGGLEBUNWICH = "不错的下午点心。"

WINONA.DESCRIBE.KYNO_BREWINGRECIPECARD = "我无法理解它的正反面。"

WINONA.DESCRIBE.KYNO_OIL = "非常适合烹饪。"

WINONA.DESCRIBE.BERRYSUNDAE = "你得在它融化之前吃掉它。"

WINONA.DESCRIBE.CHOCOLATE_BLACK = "我可以称之为工作休息。"
WINONA.DESCRIBE.CHOCOLATE_WHITE = "我可以说这是下班休息。"

WINONA.DESCRIBE.TRICOLORDANGO = "这是什么？某种甜点？"
 
WINONA.DESCRIBE.FRIESFRENCH = "嗯……味道不错。"

WINONA.DESCRIBE.PIRATERUM = "哇哦，这看起来确实是一种危险的饮料。"

WINONA.DESCRIBE.TWISTEDTEQUILA = "这是欢乐时光，宝贝！"

WINONA.DESCRIBE.ONIONRINGS = "我需要吃点快餐来继续工作。"

WINONA.DESCRIBE.DONUTS = "好吧，如果警察真的来了，别担心。我们有一些甜甜圈！"
WINONA.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "好吧，如果警察真的来了，别担心。我们有一些甜甜圈！"
WINONA.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "好吧，如果警察真的来了，别担心。我们有一些甜甜圈！"
 
WINONA.DESCRIBE.CINNAMONROLL = "一个糖面包，呵呵。"

WINONA.DESCRIBE.GUMMYBEARGERS = "查理小时候一直很喜欢这种糖果。"

WINONA.DESCRIBE.PRETZEL = "这些小家伙很快就会进入我的嘴里……"

WINONA.DESCRIBE.CORNINCUP = "这天没有什么比吃零食更好的了。"

WINONA.DESCRIBE.COTTONCANDY = "这道菜很懒！"

WINONA.DESCRIBE.ROASTEDHAZELNUTS = "嗯，它的味道不像我想象的那样，但确实提供了很多能量。"

WINONA.DESCRIBE.MONSTERMUFFIN = "反正我不太喜欢松饼。"

WINONA.DESCRIBE.PINKCAKE = "派对在哪儿，嗯？"

WINONA.DESCRIBE.CHIPSBAG = "吃点小吃的好时机。"

WINONA.DESCRIBE.LITTLEBREAD = "经典，你不觉得吗？"

WINONA.DESCRIBE.HOTHOUND = "天啊，热狗。"

WINONA.DESCRIBE.MILKSHAKE = "我觉得它们有点贵。"
WINONA.DESCRIBE.MILKSHAKE_PRISMATIC = "我觉得它们有点贵。"

WINONA.DESCRIBE.NACHOS = "工作还没有完成！"

WINONA.DESCRIBE.BANANA_PUDDING = "吃一大块不会造成伤害。"

WINONA.DESCRIBE.SEA_PUDDING = "吃一大块不会造成伤害。"

WINONA.DESCRIBE.TOM_KHA_SOUP = "我希望它能给我一些工作的能量。"

WINONA.DESCRIBE.MINERTREAT = "我打赌即使在今天她也会想要一个。"

WINONA.DESCRIBE.RADISHSALAD = "这就是我所说的健康食品。"

WINONA.DESCRIBE.PUMPKIN_SOUP = "这实际上可能值得付出努力！"

WINONA.DESCRIBE.ALGAE_SOUP = "这实际上是值得付出努力的！"

WINONA.DESCRIBE.PARZNIP_SOUP = "这实际上可能值得付出努力！"

WINONA.DESCRIBE.NETTLEMEATED = "肉有助于掩盖药味。"

WINONA.DESCRIBE.KYNO_SUGAR = "诚实工作的甜蜜成果。"

WINONA.DESCRIBE.KYNO_BOTTLECAP = "为什么有时我不明白？"

WINONA.DESCRIBE.NUKACOLA = "我以前听说过一些关于它的事情，但不记得是什么了。"
WINONA.DESCRIBE.NUKACOLA_QUANTUM = "我以前听说过一些关于它的事情，但不记得是什么了。"

WINONA.DESCRIBE.LIVINGSANDWICH = "我不吃那个东西。"

WINONA.DESCRIBE.DURIANSPLIT = "你必须在它融化之前把它吃掉。"

WINONA.DESCRIBE.DURIANSOUP = "好喝的热汤。"

WINONA.DESCRIBE.DURIANMEATED = "这味道简直要了我的命！"

WINONA.DESCRIBE.DURIANCHICKEN = "火鸡的完美再现。"

WINONA.DESCRIBE.LUNARSOUP = "午餐时间。"

WINONA.DESCRIBE.PURPLEWOBSTERSOUP = "猜猜今天就到这里了，是吧？"

WINONA.DESCRIBE.WOBSTERMONSTER = "看起来不太好。"

WINONA.DESCRIBE.SPIDERCAKE = "我宁愿吃石头也不愿吃那个！"

WINONA.DESCRIBE.SUGARBOMBS = "它在我嘴里爆炸了！"

WINONA.DESCRIBE.BERRYBOMBS = "保留这些果酱。"

WINONA.DESCRIBE.ONIGIRIS = "小吃时间！"

WINONA.DESCRIBE.OMURICE = "调味小吃。非常不错。"

WINONA.DESCRIBE.PAELLA = "美味的米饭！"

WINONA.DESCRIBE.RISOTTO = "它是如此细腻！"

WINONA.DESCRIBE.RICESAKE = "有点软。我可以多喝点。"

WINONA.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "不管付出什么代价，我都要得到那颗果实。"
WINONA.DESCRIBE.KYNO_PINEAPPLEBUSH = "不管付出什么代价，我都要得到那颗果实。"

WINONA.DESCRIBE.KYNO_PINEAPPLE = "想象一下被这样的东西砸到头的情景吧！"
WINONA.DESCRIBE.KYNO_PINEAPPLE_HALVED = "只要一片就够了。"
WINONA.DESCRIBE.KYNO_PINEAPPLE_COOKED = "只要一片就够了。"

WINONA.DESCRIBE.PIZZA_TROPICAL = "哼哼。这和普通披萨没什么区别。"

WINONA.DESCRIBE.PINACOLADA = "坐下来，放松心情..."

WINONA.DESCRIBE.CHIMAS = "虽然不是我的首选，但也不错。"

WINONA.DESCRIBE.KYNO_GARDEN_SPRINKLER = "帮我浇水。"

WINONA.DESCRIBE.KYNO_FOODSACK = "软乎乎的。"

WINONA.DESCRIBE.GUMMYWORMS = "几乎和它们一样真实。"

WINONA.DESCRIBE.SMORES = "点心时间到了！"

WINONA.DESCRIBE.NUKASHINE = "真是一次旅行，伙计！"

WINONA.DESCRIBE.ANTSLOG = "事实就是如此。"

WINONA.DESCRIBE.KYNO_WORM_BONE = "对不起，小虫子。"

WINONA.DESCRIBE.SPOOKY_BRAIN_NOODLES = "以前从没见过这样的面条！"
WINONA.DESCRIBE.SPOOKY_BURGERZILLA = "我确定我看到沃托克斯从传送门里拿着汉堡出来了..."
WINONA.DESCRIBE.SPOOKY_DEADBREAD = "我可以看出这款面包的用心之处。"
WINONA.DESCRIBE.SPOOKY_JELLYBEANS = "哇哦！这个很有趣。"
WINONA.DESCRIBE.SPOOKY_POPSICLE = "柠檬?"
WINONA.DESCRIBE.SPOOKY_PUMPKINCREAM = "还不错。"
WINONA.DESCRIBE.SPOOKY_SKULLCANDY = "如果我们的朋友死了，它可以把他们带回来。"
WINONA.DESCRIBE.SPOOKY_TACODILE = "太好吃了!"

WINONA.DESCRIBE.BUTTER_BEEFALO = "\我不敢相信它不是黄油！\" 至少我是这么想的。"
WINONA.DESCRIBE.BUTTER_GOAT = "希望它足够好。"
WINONA.DESCRIBE.BUTTER_KOALEFANT = "我的朋友一直给我做这些的好东西！"

WINONA.DESCRIBE.SPICE_CURE = "适合在下班后吃零食。"
WINONA.DESCRIBE.SPICE_COLD = "哎哟！已经冻僵了！"
WINONA.DESCRIBE.SPICE_FIRE = "永恒的火焰，凝结成食物香料。"
WINONA.DESCRIBE.SPICE_FED = "这正是我所需要的。"
WINONA.DESCRIBE.SPICE_MIND = "我用餐时的宁静调味品"

WINONA.DESCRIBE.SUGARFLYMUFFIN = "多漂亮的松饼啊！"

WINONA.DESCRIBE.EELTACOS = "所有时间都是炸玉米饼时间。"

WINONA.DESCRIBE.MEATSKILLET = "在冬天可能会派上用场。"

WINONA.DESCRIBE.MEATWALTZ = "好的。"

WINONA.DESCRIBE.COMPLETEBREAKFAST = "放松点，大个子。"

WINONA.DESCRIBE.DUMPLINGS = "嗯~，非常好！"

WINONA.DESCRIBE.WARLYICEDTEA = "啊......，沁人心脾。"

WINONA.DESCRIBE.WARLYTEA = "咖啡因！"

WINONA.DESCRIBE.KYNO_TEALEAF = "喝茶时间！"

WINONA.DESCRIBE.KYNO_ITEMSLICER = "我切分的方式。"
WINONA.DESCRIBE.KYNO_ITEMSLICER_GOLD = "我切分的方式。"

WINONA.DESCRIBE.COXINHA = "面团点心。"

WINONA.DESCRIBE.LAZYDESSERT = "石头做的糖果，真的吗？"

WINONA.DESCRIBE.CRABKINGFEAST = "太大了！"

WINONA.DESCRIBE.PIENAPPLE = "它和苹果押韵。"

WINONA.DESCRIBE.JAWSBREAKER = "太有趣了！"

WINONA.DESCRIBE.AVOCADOTOAST = "嗯，有点像那样。"

WINONA.DESCRIBE.RICEPUDDING = "我可以接受这个。"

WINONA.DESCRIBE.SHARKSUSHI = "垂涎欲滴!"

WINONA.DESCRIBE.WOBSTERBREADED = "嗯。有一些面包屑掉落。"

WINONA.DESCRIBE.LAZYPURRITO = "我希望这个小家伙还有更多的生命可以度过。"

WINONA.DESCRIBE.HORCHATA = "还好吧。"

WINONA.DESCRIBE.WOBSTERCOCKTAIL = "那会花很多铜板！幸运的是，这里是免费的。"

WINONA.DESCRIBE.LAVAEEGGBOILED = "我的手在烧，哎哟！"

WINONA.DESCRIBE.POMEGRANATETEA = "啊！...我太喜欢了。"

WINONA.DESCRIBE.TIRAMISU = "它看起来像拿铁。"

WINONA.DESCRIBE.TOADSTOOLCOLA = "气泡多且有异味。"

WINONA.DESCRIBE.TEPACHE = "令人耳目一新的变化。"

WINONA.DESCRIBE.LUNARTEQUILA = "他们正在呼唤我..."

WINONA.DESCRIBE.MIMICMOSA = "它具备某种隐形机制。"

WINONA.DESCRIBE.POMEGRANATEPIE = "那个小恶魔对石榴有着深厚的喜爱之情。"

WINONA.DESCRIBE.PINEAPPLECAKE = "这是谁的生日派对？"

WINONA.DESCRIBE.PASTY_MEAT = "它非常酥脆。"
WINONA.DESCRIBE.PASTY_CHEESE = "它非常酥脆。"

WINONA.DESCRIBE.BRIGADEIRO = "嗯，这些碎屑确实是个不错的点缀。"

WINONA.DESCRIBE.REGULARLASAGNA = "闻起来很香。"

WINONA.DESCRIBE.FLTSANDWICH = "嗯，是的。我当然更喜欢培根而不是蛙腿。"

WINONA.DESCRIBE.RICEANDBEANS = "午餐。"

WINONA.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "需要好好修一修。也许2026年会轮到我出手。"

WINONA.DESCRIBE.KYNO_TRUFFLES_GROUND = "地下宝藏，准备好收获了。"
WINONA.DESCRIBE.KYNO_TRUFFLES = "罕见的发现——大自然的美味佳肴。"
WINONA.DESCRIBE.KYNO_TRUFFLES_COOKED = "烹饪让它们变得更棒了。"

WINONA.DESCRIBE.KYNO_ITEMSHOWCASER = "挺整洁的架子。可惜不是用来干活的。"

WINONA.DESCRIBE.KYNO_SPORECAP = "这家伙的日子不太好过。"
WINONA.DESCRIBE.KYNO_SPORECAP_COOKED = "至少它不会再碎掉了。"

WINONA.DESCRIBE.KYNO_SPORECAP_DARK = "绝对不符合安全标准。"
WINONA.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "看起来熟了，但肯定被诅咒了。"

WINONA.DESCRIBE.KYNO_GOLDENAPPLE = "嗯……看起来好得不真实。"

WINONA.DESCRIBE.TRUFFLESGRINDER = "看起来太高级了，不过我吃！"

WINONA.DESCRIBE.SPORECAPPIE = "看起来像个裹着饼皮的健康隐患。"

WINONA.DESCRIBE.SPORECAP_SKEWERS = "不豪华，但填饱肚子。"

WINONA.DESCRIBE.TRUFFLEOIL = "哈，大概是有钱人用来煎东西的油吧。"

WINONA.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "让我们开始建造吧。"
WINONA.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "看起来是个不错的开端。只是需要多花些功夫。"
WINONA.DESCRIBE.KYNO_FISHFARMPLOT = "这个鱼苗场源源不断地供应鱼苗。"

WINONA.DESCRIBE.KYNO_ANTCHOVY = "这可真是奇怪的杂交啊！"
WINONA.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "这活儿看起来简直像个移动的烂摊子！"

WINONA.DESCRIBE.AGEDROE = "我把它们做得精致了，但终究还是鱼卵。"
WINONA.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "我想这就是时髦人所谓的晚餐吧。"

WINONA.DESCRIBE.KYNO_SWORDFISH_BLUE = "太久没工作了吧？这种事，谁都有可能遇到。"

WINONA.DESCRIBE.KYNO_JELLYFISH = "这家伙挺酷的。"
WINONA.DESCRIBE.KYNO_JELLYFISH_DEAD = "它或许仍会刺痛我。"
WINONA.DESCRIBE.KYNO_JELLYFISH_COOKED = "希望这不会刺痛我。"
WINONA.DESCRIBE.KYNO_JELLYFISH_DRIED = "看起来特别有嚼劲。"

WINONA.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "小家伙，看起来不错！"
WINONA.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "哎呀。"
WINONA.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "煮熟后也挺可爱的。"

WINONA.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "我需要你帮忙办点事。"

WINONA.DESCRIBE.KYNO_OCEANTRAP = "晚餐捕手！"

WINONA.DESCRIBE.OCEANFISH_PUFFERFISH = "看起来像个带刺的减压球。我不喜欢。"
WINONA.DESCRIBE.OCEANFISH_STURGEON = "那可是条硬骨头的老鱼。佩服。"

WINONA.DESCRIBE.KYNO_SWORDFISH = "我们能先谈谈吗？"
WINONA.DESCRIBE.KYNO_SWORDFISH_DEAD = "仔细一看，他体型还挺魁梧的。"

WINONA.DESCRIBE.SWORDFISHFEAST = "看起来太精致了，不像是午休时间能享用的……但我还是要了！"

WINONA.DESCRIBE.KYNO_DOGFISH = "可爱的小狗。"
WINONA.DESCRIBE.KYNO_DOGFISH_DEAD = "抱歉，老兄。"

WINONA.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "扔进垃圾桶！"

WINONA.DESCRIBE.WOBSTER_MONKEYISLAND = "看起来像是镀了金箔。真有格调。"
WINONA.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "好吧，让它白白浪费掉可就太可惜了。"
WINONA.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "晚餐上桌啦，热乎乎的！"

WINONA.DESCRIBE.KYNO_PUFFERMONSTER = "它鼓起腮帮子，准备开战了，是吗？"

WINONA.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "哎呀，水下潜伏着某种庞然大物。"
WINONA.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "怎么了，大块头？"
WINONA.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "哎呀。冷静点，大块头！"
WINONA.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "这可真是条臭鱼！"

WINONA.DESCRIBE.KYNO_BLUBBER = "让我口干舌燥。"

WINONA.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "快速零食，解决饥饿。"
WINONA.DESCRIBE.KYNO_FISHMEAT_DRIED = "优质蛋白质，助你高效工作。"

WINONA.DESCRIBE.MONKEYISLANDMEAL = "这可真是一顿豪华万能餐呢！"

WINONA.DESCRIBE.KYNO_BRAINROCK_LARVAE = "小黏液怪！"
WINONA.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "嘿。 \"小不点\"." 
WINONA.DESCRIBE.KYNO_BRAINROCK_CORAL = "或许我能设计出更棒的机器？"
WINONA.DESCRIBE.KYNO_BRAINROCK_ROCK = "那可真是个大脑啊！"

WINONA.DESCRIBE.BRAINMETTERSOUP = "儿童餐。"

WINONA.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = "你看起来是个很随和的人。"
WINONA.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "啊哈！属于我的宝藏。"

WINONA.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = "我会保管好这个。"
WINONA.DESCRIBE.KYNO_PACKIMBAGGIMS = "你这家伙嘴巴真大。"

WINONA.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "那将是一项艰巨的工作。"
WINONA.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "工作仍在继续。"
WINONA.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "这才是我心目中的团队福利！"
WINONA.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "来点火吧！"
WINONA.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "这让我想起查理。"
WINONA.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "辛苦工作一天后，理应享受的犒赏。"
WINONA.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "这确实让工作场所变得明亮起来！"
WINONA.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = "随时爆米花，真方便。"
WINONA.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "这才是真正的派对气氛！"
WINONA.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "是时候开始派对了！"
WINONA.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "量身定制！萨米真是团队的一员了，对吧？"

WINONA.DESCRIBE.KYNO_FISHREGISTRYHAT = "很适合学习规律，鱼可不少。"