local WENDY = STRINGS.CHARACTERS.WENDY

WENDY.ANNOUNCE_KYNO_COFFEEBUFF_START = "是时候加速我的死亡了。"
WENDY.ANNOUNCE_KYNO_COFFEEBUFF_END = "恢复正常，我猜。"

WENDY.ANNOUNCE_KYNO_HASTEBUFF_START = "我的制作现在快多了。"
WENDY.ANNOUNCE_KYNO_HASTEBUFF_END = "速度消失了，我的手还在颤抖。"

WENDY.ANNOUNCE_KYNO_POPBUFF_START = "（嗝！）唉……抱歉。"
WENDY.ANNOUNCE_KYNO_POPBUFF_END = "不要再喝那种饮料了。"

WENDY.ANNOUNCE_KYNO_FROGBUFF_START = "这味道真恶心。"
WENDY.ANNOUNCE_KYNO_FROGBUFF_END = "至少没有气味！"

WENDY.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝!) 那些海盗会知道我的厉害的！"
WENDY.ANNOUNCE_KYNO_PIRATEBUFF_END = "不能再喝了。"

WENDY.ANNOUNCE_KYNO_FREEZEBUFF_START = "感受死亡的冰冷触感！"
WENDY.ANNOUNCE_KYNO_FREEZEBUFF_END = "我的暴风雪已经结束了。"

WENDY.ANNOUNCE_KYNO_FIREBUFF_START = "感受我炽热的怒火！"
WENDY.ANNOUNCE_KYNO_FIREBUFF_END = "火焰熄灭了......"

WENDY.ANNOUNCE_KYNO_FISHINGBUFF_START = "是时候去钓鱼了。"
WENDY.ANNOUNCE_KYNO_FISHINGBUFF_END = "呃。我仍然能闻到鱼的臭味。"

WENDY.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "这让我耳目一新。"
WENDY.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "啊。我讨厌思考。"

WENDY.ANNOUNCE_KYNO_EATERBUFF_START = "我能感觉到我的牙齿越来越强壮."
WENDY.ANNOUNCE_KYNO_EATERBUFF_END = "普通的牙齿又回来了..."

WENDY.ANNOUNCE_KYNO_WORMBUFF_START = "虫子会感受到我的愤怒。"
WENDY.ANNOUNCE_KYNO_WORMBUFF_END = "我对虫子的愤怒暂时消失了。"

WENDY.ANNOUNCE_KYNO_CRABBUFF_START = "螃蟹会感受到我的愤怒。"
WENDY.ANNOUNCE_KYNO_CRABBUFF_END = "我对螃蟹的愤怒暂时消失了。"

WENDY.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝！) 很抱歉。"
WENDY.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "别再喝青蛙饮料了。"

WENDY.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "照亮我！"
WENDY.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "离开了。"

WENDY.ANNOUNCE_KYNO_STEALTHBUFF_START = "我消失了！"
WENDY.ANNOUNCE_KYNO_STEALTHBUFF_END = "我再次出现在你面前！"

WENDY.ANNOUNCE_KYNO_FEARBUFF_START = "恐惧是一种转瞬即逝的感觉。"
WENDY.ANNOUNCE_KYNO_FEARBUFF_END = "这一切又太可怕了，不是吗，阿比盖尔？"

WENDY.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "禁忌神力的滋味……"
WENDY.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "力量在消逝……如同一切。"

WENDY.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "连猪都被我吸引……"
WENDY.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "友谊的魔法消失了……"

WENDY.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "腐朽暂时无法触碰我。"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WENDY.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "死亡的触碰暂时避开了我……"
WENDY.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "病痛又回来了……就像往常一样。"

WENDY.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "清醒的瞬间，何其短暂。"
WENDY.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "脑雾如期而至。"

WENDY.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "连蜜蜂都决定饶我一命了……暂时。"
WENDY.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "平静从不会长久……"

WENDY.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "生命此刻仍紧紧依附着我..."
WENDY.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "于是我的力量如万物般消逝……"

WENDY.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "是天赐的福泽，还是永不满足的诅咒？"
WENDY.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "它永远不会持久……"

WENDY.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "黑暗中短暂的一丝清明..."
WENDY.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "明晰渐逝……黑暗重临。"

WENDY.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "即使是看不见的屏障也能保护我免受伤害。"
WENDY.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "那看不见的屏障已经消失了。"

WENDY.ANNOUNCE_KYNO_BERSERKERBUFF_START = "以痛还痛。一场公平的交易。"
WENDY.ANNOUNCE_KYNO_BERSERKERBUFF_END = "狂怒消逝，如同万物一般。"

WENDY.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "就连饥饿，也变得更安静了。"
WENDY.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "空虚，回来了。"

WENDY.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "或许可以收集些什么？"

WENDY.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "当然，这并非这只愚蠢的生物所希望的。"

WENDY.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "它还不能应对生活中的各种事情。"

WENDY.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "我为什么要把它放在这里？"

WENDY.ANNOUNCE_KYNO_POTHANGER_FAIL = "它需要的是一个锅，而不是这个，唉。"

WENDY.ANNOUNCE_KYNO_CASSEROLE_FAIL = "我需要在这里放一个砂锅菜盘。"

WENDY.ANNOUNCE_KYNO_SAPHEALER_USED = "生命再次绽放，循环往复，周而复始。"

WENDY.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "生命终将消逝，他们的生命也必将如此……"

WENDY.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "如同我的灵魂般空洞。"

WENDY.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "即便是小径，终将淹没……"
WENDY.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "雨水甚至淹没了希望……"
WENDY.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "死亡在深渊之下蠢动……"

WENDY.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "一场转瞬即逝的庆典……不过，我想，倒也挺愉快的。"

WENDY.ANNOUNCE_KYNO_FISH_RESEARCHED = "它的秘密浮出水面，万物终将如此。"
WENDY.ANNOUNCE_KYNO_ROE_RESEARCHED = "如此多的生命，本不该诞生。"

WENDY.DESCRIBE.KYNO_ROE = "生命的开始..."
WENDY.DESCRIBE.KYNO_ROE_COOKED = "我让他们免于孵化的痛苦。"

WENDY.DESCRIBE.KYNO_SHARK_FIN = "它不再需要这个了。"

WENDY.DESCRIBE.KYNO_BEANBUGS = "你的生命和我的一样微不足道。"
WENDY.DESCRIBE.KYNO_BEANBUGS_COOKED = "最好的场景：它要了我的命。"

WENDY.DESCRIBE.KYNO_GUMMYBUG = "咦哟。"
WENDY.DESCRIBE.KYNO_GUMMYBUG_COOKED = "它尝起来像它的样子。"

WENDY.DESCRIBE.KYNO_WHEAT = "我们可以把它磨成面粉。"
WENDY.DESCRIBE.KYNO_WHEAT_COOKED = "我们现在不能把它磨成面粉。"

WENDY.DESCRIBE.KYNO_FLOUR = "面粉，面粉面粉……地板。"

WENDY.DESCRIBE.KYNO_SPOTSPICE = "只是一个破折号。"

WENDY.DESCRIBE.KYNO_SAP = "树血。"
WENDY.DESCRIBE.KYNO_SAP_SPOILED = "人生苦乐参半。"

WENDY.DESCRIBE.KYNO_SYRUP = "不像阿比盖尔那么甜。"

WENDY.DESCRIBE.KYNO_COFFEEBEANS = "这些看起来很刺激。"
WENDY.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "生命的意志是以豆子的形式出现的？"

WENDY.DESCRIBE.DUG_KYNO_COFFEEBUSH = "被连根拔起，却未注定消亡。"

WENDY.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "这植物，从炽烈的死亡中汲取养分。",
	PICKED = "它已没什么能给予的了。",
	WITHERED = "生命正从它体内退去。",
}

WENDY.DESCRIBE.DUG_KYNO_SPOTBUSH = "被挪了地方，但并未消失。"

WENDY.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "想来，它应该是能吃的。",
	PICKED = "它已没什么能给予的了。",
	BURNING = "它的终结，来得如此之快。",
}

WENDY.DESCRIBE.KYNO_SPOTSPICE_LEAF = "我们把它从灌木上的家中撕了下来。"

WENDY.DESCRIBE.KYNO_MUSSEL = "你不能躲在海浪下，肉！"
WENDY.DESCRIBE.KYNO_MUSSEL_COOKED = "我肯定给这只贻贝配备了强力武器。"

WENDY.DESCRIBE.KYNO_HUMANMEAT = "你仍然可以火烤它！"
WENDY.DESCRIBE.KYNO_HUMANMEAT_COOKED = "灵魂会质疑你的目的吗？"
WENDY.DESCRIBE.KYNO_HUMANMEAT_DRIED = "取出来很久了。"

WENDY.DESCRIBE.COFFEE = "黑暗，苦涩..."

WENDY.DESCRIBE.BISQUE = "养活身体，饿死灵魂……"

WENDY.DESCRIBE.JELLYOPOP = "死亡降临到我们所有人身上。有时是在棍子上。"

WENDY.DESCRIBE.SHARKFINSOUP = "它尝到了人类解脱的滋味，我会尝尝的。"

WENDY.DESCRIBE.TROPICALBOUILLABAISSE = "暂时摆脱饥饿。"

WENDY.DESCRIBE.MUSSELBOUILLABAISE = "看着就流口水。"

WENDY.DESCRIBE.SWEETPOTATOSOUFFLE = "精致，但美味。"

WENDY.DESCRIBE.FEIJOADA = "有人为此而死。"

WENDY.DESCRIBE.GUMMY_CAKE = "这让我很不开心。"

WENDY.DESCRIBE.HARDSHELL_TACOS = "硬壳让我想起了生活。"

WENDY.DESCRIBE.ICEDTEA = "令人耳目一新，但仍然无法缓解我的悲伤。"

WENDY.DESCRIBE.NETTLELOSANGE = "暂时缓解生活的悲伤。"

WENDY.DESCRIBE.SNAKEBONESOUP = "用死动物制成的肉汤。"

WENDY.DESCRIBE.STEAMEDHAMSANDWICH = "家庭食谱。"

WENDY.DESCRIBE.TEA = "阿比盖尔喜欢茶会。"

WENDY.DESCRIBE.BUBBLETEA = "令人耳目一新，但仍然无法缓解我的悲伤。"

WENDY.DESCRIBE.FRENCHONIONSOUP = "一种植物制成的肉汤。"

WENDY.DESCRIBE.SLAW = "一大堆烤熟的蔬菜。引人入胜。"

WENDY.DESCRIBE.LOTUSBOWL = "它的死很美味。"

WENDY.DESCRIBE.POI = "热带食物。"

WENDY.DESCRIBE.JELLYBEAN_HUNGER = "永远不会知道生命的豆子。"
WENDY.DESCRIBE.JELLYBEAN_SUPER = "永远不会知道生命的豆子。"
WENDY.DESCRIBE.JELLYBEAN_SANITY = "永远不会知道生命的豆子。"

WENDY.DESCRIBE.BOWLOFGEARS = "如果我吃了这个，也许我会死。"

WENDY.DESCRIBE.LONGPIGMEAL = "曾经是人类，现在是食物。"

WENDY.DESCRIBE.CUCUMBERSALAD = "呃，更多蔬菜。"

WENDY.DESCRIBE.DUG_KYNO_WILDWHEAT = "被挪了地方，却仍怀希望。"

WENDY.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "比草高级一点的版本。",
	PICKED = "它现在什么也给不了。",
	WITHERED = "生命正从它身上退去。",
	BURNING = "它的终结，来得如此之快。",
}

WENDY.DESCRIBE.KYNO_MEALGRINDER = "磨碎生命的磨粉机。"

WENDY.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "它们在由死亡造就的树桩上繁茂生长。",
	PICKED = "它在等待，准备再次给予。",
	BURNING = "万物皆会死去。即便是菌类。",
}

WENDY.DESCRIBE.GORGE_BREAD = "你一个人做不了太多事情。"
WENDY.DESCRIBE.GORGE_SWEET_CHIPS = "全都进了我的嘴里。"
WENDY.DESCRIBE.GORGE_VEGETABLE_SOUP = "我觉得连死亡的味道都比这更好。"
WENDY.DESCRIBE.GORGE_JELLY_SANDWICH = "果酱看起来像血。"
WENDY.DESCRIBE.GORGE_FISH_STEW = "情况可能更糟。"
WENDY.DESCRIBE.GORGE_MEAT_STEW = "你会惊讶于从死亡和白骨中可以收集到多少生命。"
WENDY.DESCRIBE.GORGE_ONION_CAKE = "我更喜欢甜蛋糕。"
WENDY.DESCRIBE.GORGE_POTATO_PANCAKES = "现在我只需要找一些糖浆。"
WENDY.DESCRIBE.GORGE_POTATO_SOUP = "喂饱身体，饿死灵魂..."
WENDY.DESCRIBE.GORGE_FISHBALL_SKEWERS = "串烧是街头小吃。"
WENDY.DESCRIBE.GORGE_MEAT_SKEWERS = "串烧是街头小吃。"
WENDY.DESCRIBE.GORGE_STONE_SOUP = "喂饱身体，饿死灵魂..."
WENDY.DESCRIBE.GORGE_CROQUETTE = "没关系。"
WENDY.DESCRIBE.GORGE_ROAST_VEGETABLES = "他们都说它很棒，但我不得不同意。"
WENDY.DESCRIBE.GORGE_MEATLOAF = "肉配面包，多有创意。"
WENDY.DESCRIBE.GORGE_CARROT_SOUP = "喂饱身体，饿死灵魂..."
WENDY.DESCRIBE.GORGE_FISHPIE = "谁认为这会很棒？"
WENDY.DESCRIBE.GORGE_FISHCHIPS = "至少在这里还能吃到像样的食物。"
WENDY.DESCRIBE.GORGE_MEATPIE = "听起来不错。"
WENDY.DESCRIBE.GORGE_SLIDERS = "速度快，砸得好。"
WENDY.DESCRIBE.GORGE_JELLY_ROLL = "早餐的好选择。"
WENDY.DESCRIBE.GORGE_CARROT_CAKE = "这只是一个谎言。骗不了我！"
WENDY.DESCRIBE.GORGE_GARLICMASHED = "看起来还不错。"
WENDY.DESCRIBE.GORGE_GARLICBREAD = "对面包本身的改进。"
WENDY.DESCRIBE.GORGE_TOMATO_SOUP = "喂饱身体，饿死灵魂..."
WENDY.DESCRIBE.GORGE_SAUSAGE = "这是一堆肉放在一起屠宰。"
WENDY.DESCRIBE.GORGE_CANDIEDFISH = "溺水。"
WENDY.DESCRIBE.GORGE_STUFFEDMUSHROOM = "好极了。"
WENDY.DESCRIBE.GORGE_BRUSCHETTA = "我更喜欢加豆子或奶酪。"
WENDY.DESCRIBE.GORGE_HAMBURGER = "垃圾食品。"
WENDY.DESCRIBE.GORGE_FISHBURGER = "垃圾食品。"
WENDY.DESCRIBE.GORGE_MUSHROOMBURGER = "垃圾食品。"
WENDY.DESCRIBE.GORGE_FISH_STEAK = "情况可能更糟。"
WENDY.DESCRIBE.GORGE_CURRY = "带来了太多的回忆。"
WENDY.DESCRIBE.GORGE_SPAGHETTI = "肉丸子。真令人兴奋。"
WENDY.DESCRIBE.GORGE_POACHEDFISH = "水煮的，切片很好看。"
WENDY.DESCRIBE.GORGE_SHEPHERD_PIE = "浓郁的肉派。"
WENDY.DESCRIBE.GORGE_CANDY = "从没想过我能做出这么甜的东西。"
WENDY.DESCRIBE.GORGE_BREAD_PUDDING = "很甜!"
WENDY.DESCRIBE.GORGE_BERRY_TART = "哼，我还以为会更糟呢。"
WENDY.DESCRIBE.GORGE_MACARONI = "它带来了太多的回忆。"
WENDY.DESCRIBE.GORGE_BAGEL_AND_FISH = "还不如做个三明治。"
WENDY.DESCRIBE.GORGE_GRILLED_CHEESE = "一道经典的早餐菜肴。"
WENDY.DESCRIBE.GORGE_CREAMMUSHROOM = "不合我意。"
WENDY.DESCRIBE.GORGE_MANICOTTI = "足够体面。"
WENDY.DESCRIBE.GORGE_CHEESEBURGER = "垃圾食品。"
WENDY.DESCRIBE.GORGE_FETTUCCINE = "它的样子很奇怪。"
WENDY.DESCRIBE.GORGE_ONION_SOUP = "这并不令人愉快。"
WENDY.DESCRIBE.GORGE_BREADED_CUTLET = "这些都不会错。"
WENDY.DESCRIBE.GORGE_CREAMY_FISH = "我受宠若惊。"
WENDY.DESCRIBE.GORGE_PIZZA = "哦，好吧，回忆。"
WENDY.DESCRIBE.GORGE_POT_ROAST = "时间不会弯曲。"
WENDY.DESCRIBE.GORGE_CRAB_CAKE = "我试着做艺术。我已经后悔了。"
WENDY.DESCRIBE.GORGE_STEAK_FRITES = "一道好菜。"
WENDY.DESCRIBE.GORGE_SHOOTER_SANDWICH = "用于狩猎的便携式食物。"
WENDY.DESCRIBE.GORGE_BACON_WRAPPED = "闻起来像早晨。"
WENDY.DESCRIBE.GORGE_CRAB_ROLL = "太漂亮了。"
WENDY.DESCRIBE.GORGE_MEAT_WELLINGTON = "沃利先生很会烹饪。"
WENDY.DESCRIBE.GORGE_CRAB_RAVIOLI = "太漂亮了。"
WENDY.DESCRIBE.GORGE_CARAMEL_CUBE = "伤害身体，治愈心灵。"
WENDY.DESCRIBE.GORGE_SCONE = "甜的!"
WENDY.DESCRIBE.GORGE_TRIFLE = "甜的!"
WENDY.DESCRIBE.GORGE_CHEESECAKE = "没关系。没别的了。"

WENDY.DESCRIBE.DUCKYOUGLERMZ = "恶心又可怕。"

WENDY.DESCRIBE.KYNO_ALOE = "它死去是为了让其他人活下去。"
WENDY.DESCRIBE.KYNO_ALOE_COOKED = "熟仙人掌。"
WENDY.DESCRIBE.KYNO_ALOE_GROUND = "它死去是为了让其他人活下去。"
WENDY.DESCRIBE.KYNO_ALOE_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.FARM_PLANT_KYNO_ALOE = "它的死亡是为了他人的生存。"
WENDY.DESCRIBE.KYNO_ALOE_OVERSIZED = "它的死亡是为了他人的生存。"
WENDY.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "死亡。"

WENDY.DESCRIBE.KYNO_CUCUMBER = "这是……我不知道。叹息。"
WENDY.DESCRIBE.KYNO_CUCUMBER_COOKED = "我们为维持生计所做的事情。"
WENDY.DESCRIBE.KYNO_CUCUMBER_GROUND = "这是……我不知道。叹息。"
WENDY.DESCRIBE.KYNO_CUCUMBER_SEEDS = "这是一株等待生长的植物。"
WENDY.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "这是一株等待出现的植物。"
WENDY.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "这是……我不知道。叹息。"
WENDY.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "这是……我不知道。叹息。"
WENDY.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "这……我不知道。叹息。"

WENDY.DESCRIBE.KYNO_RADISH = "我血液的颜色。"
WENDY.DESCRIBE.KYNO_RADISH_COOKED = "烤熟后味道再糟糕不过了。"
WENDY.DESCRIBE.KYNO_RADISH_GROUND = "我血液的颜色。"
WENDY.DESCRIBE.KYNO_RADISH_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.FARM_PLANT_KYNO_RADISH = "我血液的颜色。"
WENDY.DESCRIBE.KYNO_RADISH_OVERSIZED = "我血液的颜色。"
WENDY.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "死亡。"

WENDY.DESCRIBE.KYNO_FENNEL = "等待死亡来临。"
WENDY.DESCRIBE.KYNO_FENNEL_COOKED = "它受热有点萎缩。我喜欢这样。"
WENDY.DESCRIBE.KYNO_FENNEL_GROUND = "等待死亡来临。"
WENDY.DESCRIBE.KYNO_FENNEL_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "只是在等待死亡的降临。"
WENDY.DESCRIBE.KYNO_FENNEL_OVERSIZED = "只是在等待死亡的降临。"
WENDY.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "死亡。"

WENDY.DESCRIBE.KYNO_SWEETPOTATO = "甜蜜。就像我一样。"
WENDY.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "我的绝望会不会尝到一半那么甜！"
WENDY.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "甜美。就像我一样！"
WENDY.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "甜美。就像我一样！"
WENDY.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "甜美。就像我一样！"
WENDY.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "死亡。"

WENDY.DESCRIBE.KYNO_PARZNIP = "这是一种欧洲防风草。"
WENDY.DESCRIBE.KYNO_PARZNIP_COOKED = "这是一种欧洲防风草。"
WENDY.DESCRIBE.KYNO_PARZNIP_EATEN = "这是一种欧洲防风草。"
WENDY.DESCRIBE.KYNO_PARZNIP_GROUND = "这是一种欧洲防风草。"
WENDY.DESCRIBE.KYNO_PARZNIP_BIG = "一个巨大的欧洲防风草。就是这样。"
WENDY.DESCRIBE.KYNO_PARZNIP_SEEDS = "这是一株正在等待的植物。"
WENDY.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "这是一株正在等待的植物。"
WENDY.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "这是一种欧洲防风草。"
WENDY.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "这是一种欧洲防风草。"
WENDY.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "死亡。"

WENDY.DESCRIBE.KYNO_TURNIP = "这是萝卜..."
WENDY.DESCRIBE.KYNO_TURNIP_COOKED = "萝卜烤熟了。"
WENDY.DESCRIBE.KYNO_TURNIP_GROUND = "这是萝卜..."
WENDY.DESCRIBE.KYNO_TURNIP_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "这是萝卜..."
WENDY.DESCRIBE.KYNO_TURNIP_OVERSIZED = "这是萝卜..."
WENDY.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "死亡。"

WENDY.DESCRIBE.KYNO_RICE = "稻米，对吗？"
WENDY.DESCRIBE.KYNO_RICE_COOKED = "稻米，对吗？"
WENDY.DESCRIBE.KYNO_RICE_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "这是一种正在等待的植物。"
WENDY.DESCRIBE.FARM_PLANT_KYNO_RICE = "这是一片稻田..."
WENDY.DESCRIBE.KYNO_RICE_OVERSIZED = "这是一片稻田..."
WENDY.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "死亡。"

WENDY.DESCRIBE.KYNO_SEEDS_KIT = "普通的种子。"

WENDY.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "那些看着能吃……大概吧。",
	PICKED = "它们撤退了。",
	WITHERED = "一种荒芜的存在。",
}

WENDY.DESCRIBE.KYNO_LIMPETS = "它们吃岩石。我吃它们。"
WENDY.DESCRIBE.KYNO_LIMPETS_COOKED = "令人沮丧。"

WENDY.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "它在悲伤的波浪上繁茂生长。",
	PICKED = "它必须等待，才能再次绽放。",
	BURNING = "它的终结，来得太早了。",
}

WENDY.DESCRIBE.KYNO_LOTUS_ROOT = "他们渴望水葬。"
WENDY.DESCRIBE.KYNO_LOTUS_FLOWER = "这位美女也会死。"
WENDY.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "它的死很美味。"

WENDY.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "一种顽强的杂草。",
	PICKED = "它终将归来。",
	BURNING = "连大海也无法保护它。",
}

WENDY.DESCRIBE.KYNO_SEAWEEDS = "即使是大海也长满了杂草。"
WENDY.DESCRIBE.KYNO_SEAWEEDS_COOKED = "更好，但它仍然是一种杂草。"
WENDY.DESCRIBE.KYNO_SEAWEEDS_DRIED = "这样可以保存更长时间。味道也更好。"
WENDY.DESCRIBE.KYNO_SEAWEEDS_ROOT = "他们想要一个水坟。"

WENDY.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "只是个普通的水里长的蔬菜。",
	PICKED = "假以时日，它自会归来。",
	BURNING = "假以时日，它自会归来。",
}

WENDY.DESCRIBE.KYNO_TAROROOT_ROOT = "他们渴望水葬。"
WENDY.DESCRIBE.KYNO_TAROROOT = "几乎是致命的茄属植物。几乎。"
WENDY.DESCRIBE.KYNO_TAROROOT_COOKED = "烹制这种茄属植物使其更不致命。"

WENDY.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "需要水才能活着。",
	PICKED = "它会回来的，短暂地。",
	BURNING = "在真正活过之前，就已消逝。",
}

WENDY.DESCRIBE.KYNO_WATERYCRESS_ROOT = "他们渴望水葬。"
WENDY.DESCRIBE.KYNO_WATERYCRESS = "需要水才能生存。"

WENDY.DESCRIBE.WATERYCRESSBOWL = "水汤。"

WENDY.DESCRIBE.KYNO_SALT = "它增加了风味......"

WENDY.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "生命在绝望地攀附。",
	PICKED = "它现在什么也给不了。",
	BURNING = "一切希望，尽失。",
}

WENDY.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "贻贝粘在这根棍子上。傻瓜。"

WENDY.DESCRIBE.CATFOOD = "猫粮。"

WENDY.DESCRIBE.KATFOOD = "猫粮。"

WENDY.DESCRIBE.KYNO_BANANATREE = 
{ 
	GENERIC = "你现在能感受到阳光吗，可怜的植物？",
	PICKED = "它必须等待，才能再次给予。",
	CHOPPED = "它的生命被截短了。",
	BURNING = "一份罕有的美丽，葬身火海。",
	BURNT = "什么都未留下，只余悲伤。",
}

WENDY.DESCRIBE.KYNO_BANANA = "果皮看起来很危险。"
WENDY.DESCRIBE.KYNO_BANANA_COOKED = "热香蕉泥好多了。"

WENDY.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "它的果实赋予生命，但只有杀死它才能获得。",
	PICKED = "它收回了自己的馈赠。",
	CHOPPED = "它的生命如此短暂。",
	BURNING = "又一个葬身火海的损失。",
	BURNT = "什么都不剩，唯余尘埃。",
}

WENDY.DESCRIBE.KYNO_KOKONUT = "这种水果必须在它的盔甲下隐藏什么秘密？"
WENDY.DESCRIBE.KYNO_KOKONUT_HALVED = "曾经完整的两半。你现在在哪里，阿比盖尔？"
WENDY.DESCRIBE.KYNO_KOKONUT_COOKED = "有点甜。"

WENDY.DESCRIBE.BOWLOFPOPCORN = "全部烧毁。"

WENDY.DESCRIBE.FIGJUICE = "令人耳目一新，但仍然无法缓解我的悲伤。"

WENDY.DESCRIBE.COCONUTWATER = "提神，但还是水。"

WENDY.DESCRIBE.EYEBALLSPAGHETTI = "危险而致命。"

WENDY.DESCRIBE.FORGETMELOTS_SEEDS = "这是一株正在等待的植物。"

WENDY.DESCRIBE.FIRENETTLES_SEEDS = "这是一种正在等待的植物。"

WENDY.DESCRIBE.TILLWEED_SEEDS = "这是一种正在等待的植物。"

WENDY.DESCRIBE.KYNO_FLOATILIZER = "一桶污垢。"

WENDY.DESCRIBE.KYNO_TWIGGYNUTS = "可食用的种子。"

WENDY.DESCRIBE.KYNO_REPAIRTOOL = "这可以使某些东西免于被毁。"

WENDY.DESCRIBE.KYNO_KOI = "它几乎太漂亮了，不能吃。差不多。"
WENDY.DESCRIBE.KYNO_KOI_COOKED = "简直美得不能吃。差不多。"

WENDY.DESCRIBE.KYNO_TROPICALFISH = "它太亮了。"
WENDY.DESCRIBE.KYNO_TROPICALFISH_COOKED = "死了。"

WENDY.DESCRIBE.KYNO_NEONFISH = "它想念它那水汪汪的家。"
WENDY.DESCRIBE.KYNO_NEONFISH_COOKED = "我……吃得更糟了……"

WENDY.DESCRIBE.KYNO_GROUPER = "一个可怜的生物。"
WENDY.DESCRIBE.KYNO_GROUPER_COOKED = "休息吧，鱼精。"
 
WENDY.DESCRIBE.KYNO_PIERROTFISH = "这些条纹象征着它的情感禁锢。"
WENDY.DESCRIBE.KYNO_PIERROTFISH_COOKED = "不要失去理智。"

WENDY.DESCRIBE.KYNO_SALMONFISH = "当它的生命慢慢地离开它的身体时，它会失败。"
WENDY.DESCRIBE.KYNO_SALMONFISH_COOKED = "现在没那么热闹了。"

WENDY.DESCRIBE.TURF_PINKPARK = "粉红色的地面，多么罕见。"
WENDY.DESCRIBE.TURF_STONECITY = "某地。"
WENDY.DESCRIBE.TURF_FIELDS = "某地。"
WENDY.DESCRIBE.TURF_TIDALMARSH = "它只是地面。"

WENDY.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "有盐可取。",
	PICKED = "还没有盐。",
}

WENDY.DESCRIBE.KYNO_SALTRACK_INSTALLER = "这是用来从池塘里收集盐分的。"

WENDY.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "用于收集树血。"

WENDY.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "生活是个陷阱。"

WENDY.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "您好啊，先生？",
	SLEEPING = "即便是权威，也需要休息。",
}

WENDY.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "它有一种病态的美。",
	CHOPPED = "万物终有尽时。",
	SAPPED = "我现在可以收获了。",
	PICKED = "匕首刺穿心脏。树的心里。",
	BURNING = "残酷的终结。",
	BURNT = "什么都不剩，唯余灰烬。",
}

WENDY.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "它的生命在消逝。",
	CHOPPED = "某种意义上，也算仁慈。",
	SAPPED = "内核已经腐朽。",
	PICKED = "所有的牺牲，都付诸东流。",
	BURNING = "终于，迎来了终结。",
	BURNT = "只剩灰烬。",
}

WENDY.DESCRIBE.KYNO_SUGARTREE_BUD = "让岛上的生活几乎不宜居。"

WENDY.DESCRIBE.KYNO_SUGARTREE_FLOWER = "他们是粉红色的，很开心。呸。"
WENDY.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "他们是粉红色的，很开心。呸。"

WENDY.DESCRIBE.KYNO_SUGARTREE_PETALS = "他们是粉红色的，很开心。呸。"

WENDY.DESCRIBE.KYNO_PEBBLECRAB = "如果我有这样的外壳，我永远不会出现。"

WENDY.DESCRIBE.KYNO_CRABMEAT = "它的内部和外部一样可怕。"
WENDY.DESCRIBE.KYNO_CRABMEAT_COOKED = "现在准备好了。"
WENDY.DESCRIBE.KYNO_CRABMEAT_DRIED = "它的内部和外部一样可怕。"

WENDY.DESCRIBE.KYNO_CRABKINGMEAT = "它的内部和外部一样可怕。"
WENDY.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "它的内部和外部一样可怕。"
WENDY.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "它的内部和外部一样可怕。"

WENDY.DESCRIBE.KYNO_SLAUGHTERTOOL = "所有的生命都不是屠杀吗？"

WENDY.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "丑陋的家禽。",
	COOP = "至少它现在有地方住了。",
}

WENDY.DESCRIBE.KYNO_CHICKEN_EGG = "生命在里面。"
WENDY.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "对一只鸡来说，太大了。"
WENDY.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "不会有鸡肉出来。"

WENDY.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "它们生下蛋，然后回到安静的窝里。",
	FULL = "又有更多的蛋，来到这个残酷的世界。",
	BURNT = "它们的苦难，结束了。",
}

WENDY.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "以前有人在这里有东西，现在没有了。"

WENDY.DESCRIBE.KYNO_COOKWARE_KIT = "工具包不会让生活更轻松。它们只是跳过了一步。"
WENDY.DESCRIBE.KYNO_COOKWARE_SYRUP = "甜蜜带来甜蜜。"
WENDY.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "甜蜜带来甜蜜。"
WENDY.DESCRIBE.KYNO_COOKWARE_BIG_POT = "我们做饭是为了避免死亡。"
WENDY.DESCRIBE.KYNO_COOKWARE_BIG = "我们做饭是为了避免死亡。"
WENDY.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "我们会做饭，否则我们会死。"
WENDY.DESCRIBE.KYNO_COOKWARE_SMALL = "我们会做饭，否则我们会死。"
WENDY.DESCRIBE.KYNO_COOKWARE_GRILL = "它不能让生活更美味。"
WENDY.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "我不想随身携带这个。"
WENDY.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "它做了一点食物。"
WENDY.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "只有我把它放在某个地方才有效。"
WENDY.DESCRIBE.KYNO_COOKWARE_ELDER = "甜蜜带来甜蜜。"
WENDY.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "唉……何必呢？"
WENDY.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "用于制作食物。"
WENDY.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "用这个烹饪一点点食物。"
WENDY.DESCRIBE.KYNO_COOKWARE_OVEN = "看起来不错。"
WENDY.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "看起来不错。"
WENDY.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "看起来不错。"

WENDY.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "要是我也能躲在石头下面就好了。",
	FLIPPED = "显露出来了，却也没什么意思。",
}

WENDY.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "我不会为了里面的东西毁掉箱子。"

WENDY.DESCRIBE.KYNO_SUGARFLY = "漂亮，但寿命短。"
WENDY.DESCRIBE.KYNO_SUGARFLYWINGS = "糖蝴蝶再也不能翱翔了。"

WENDY.DESCRIBE.KYNO_WATERY_CRATE = "我不会为了里面的东西毁掉箱子。"

WENDY.DESCRIBE.KYNO_TUNACAN = "这显然是虚假广告。"
WENDY.DESCRIBE.KYNO_TUNACAN_OPEN = "这显然是虚假广告。"

WENDY.DESCRIBE.KYNO_CANNEDFOOD = "这显然是虚假广告。"
WENDY.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "这明显是虚假广告。"

WENDY.DESCRIBE.KYNO_POP = "如果我喝了这些东西，我可能会回到我姐姐身边。"

WENDY.DESCRIBE.KYNO_MYSTERYMEAT = "这太奇怪了。"

WENDY.DESCRIBE.KYNO_BOTTLE_SOUL = "你的时代终于到来了，现在，你被永远困住了。"

WENDY.DESCRIBE.SOULSTEW = "你的时间终于到了。"

WENDY.DESCRIBE.FORTUNECOOKIE = "有待解开的秘密。"

WENDY.DESCRIBE.HORNOCUPIA = "喇叭里的食物。多么创新。"

WENDY.DESCRIBE.CHEESE_YELLOW = "它的气味难闻，但味道很好。"
WENDY.DESCRIBE.CHEESE_WHITE = "它的气味很难闻，但味道很好。"
WENDY.DESCRIBE.CHEESE_KOALEFANT = "它的气味很糟糕，但味道很好。"

WENDY.DESCRIBE.MILK_BOX = "牛奶。就这么简单。"

WENDY.DESCRIBE.WATERCUP = "普通，就像世俗生活中的一切。"

WENDY.DESCRIBE.HONEYJAR = "黏糊糊的。"

WENDY.DESCRIBE.CRAB_ARTICHOKE = "一道由蟹肉制成的美味佳肴。"

WENDY.DESCRIBE.PEPPERROLLS = "它们太棒了，我几乎忘记了极度的悲伤。"

WENDY.DESCRIBE.KYNO_SAPHEALER = "预防疾病的药水。"

WENDY.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "它的船员，大概都死了吧……",
	PICKED = "唯余耐心。",
	BURNING = "它的命运，已然注定。",
}

WENDY.DESCRIBE.KYNO_GHOST_PIRATE = "艾比盖尔的未来朋友？"

WENDY.DESCRIBE.KYNO_BUCKET_EMPTY = "帮助我的工具。"
WENDY.DESCRIBE.KYNO_BUCKET_METAL = "一个水桶来帮我。"
WENDY.DESCRIBE.KYNO_BUCKET_WATER = "就连水终究也会消逝……"

WENDY.DESCRIBE.KYNO_MILK_BEEFALO = "安全吗？"
WENDY.DESCRIBE.KYNO_MILK_KOALEFANT = "安全吗？"

WENDY.DESCRIBE.KYNO_CAP_DRIED = "干死。"

WENDY.DESCRIBE.KYNO_PLANTMEAT_DRIED = "肉变干了很好吃。"

WENDY.DESCRIBE.KYNO_BREWBOOK = "当我的心空空如也时，填饱肚子有什么意义……"

WENDY.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "一个用来酿酒或做其他好东西的桶。",
	BREWING_LONG = "时间无尽地拖曳着。",
	BREWING_SHORT = "等待，快结束了。",
	DONE = "至少，有件事成了。",
	BURNT = "一切努力，付诸东流。",
}

WENDY.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "一个用来做腌制品的罐子。",
	BREWING_LONG = "时间保存万物……短暂地。",
	BREWING_SHORT = "很快就要结束了。",
	DONE = "至少，它幸存了下来。",
	BURNT = "化为乌有。",
}

WENDY.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "仍不及阿比盖尔甜美。",
	HONEY = "所有这些蜂蜜……有何意义？",
	NECTAR = "向着蜂蜜的缓慢进程。",
	BURNING = "它的辛劳，终结于灰烬。",
}

WENDY.DESCRIBE.KYNO_NECTAR_POD = "把它变成蜂蜜值得吗？"

WENDY.DESCRIBE.KYNO_OAKTREE_POD = "原始阶段的生命。"
WENDY.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "我杀了它是为了延长自己的生命。"

WENDY.DESCRIBE.KYNO_PIKO = "太天真不知道痛苦。"
WENDY.DESCRIBE.KYNO_PIKO_ORANGE = "你的存在是为了取悦他人。"

WENDY.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "我可以坐在下面，思考生命的徒劳。",
	CHOPPED = "被剥去了存在的意义。",
	BURNING = "它的终结，来得很快。",
	BURNT = "什么都不剩了。",
}

WENDY.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "如果没有那些松鼠就好了。",
	BURNING = "因火焰而流离失所。",
}

WENDY.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "这只是一个盒子。"

WENDY.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "为孤独的生物准备的孤独的栖身之所。",
	BURNT = "又一个化为乌有的家。",
}

WENDY.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "真是别致。",
	CRAFTED = "稍有改进。",
	BURNT = "那股臭味，至今仍在。",
}

WENDY.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "我有点想要展示架上那个背包。",
	OCCUPIED = "就算是商人，也得休息。",
}

WENDY.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "里面全是好东西。",
	EMPTY = "没什么可拿的了。",
}

WENDY.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "那个小恶魔以为他能瞒着我们。"
WENDY.DESCRIBE.KYNO_MEADOWISLAND_POND = "当我凝视这个清澈的水池时，我梦想能看到阿比盖尔。"
WENDY.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "这是一种植物。"
WENDY.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "这看起来是无常的。"
WENDY.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "我赞扬这种生物对同类相食的承诺。"

WENDY.DESCRIBE.KYNO_SAMMYHAT = "有点脏。"

WENDY.DESCRIBE.KINGFISHER = "你那尖利的喙可能会将我从深海中刺穿。"

WENDY.DESCRIBE.TOUCAN = "它唱了一首受折磨的歌。"
WENDY.DESCRIBE.TOUCAN_CHUBBY = "它唱了一首受折磨的歌。"

WENDY.DESCRIBE.WETGOOP2 = "一团糟，就像生活一样。"

WENDY.DESCRIBE.BEER = "我不应该喝那个。"

WENDY.DESCRIBE.PALEALE = "我不应该喝那个。"

WENDY.DESCRIBE.TEAGREEN = "你愿意举办茶会吗，阿比盖尔？"

WENDY.DESCRIBE.TEARED = "你愿意举办茶会吗，阿比盖尔？"

WENDY.DESCRIBE.MEAD = "我不应该喝那个。"

WENDY.DESCRIBE.KYNO_JELLY = "完美的果酱量。"

WENDY.DESCRIBE.KYNO_MAYONNAISE = "可怜的鸡蛋，他们别无选择。"

WENDY.DESCRIBE.TARTARSAUCE = "蟹肉和美味。"

WENDY.DESCRIBE.KYNO_PICKLES = "被困食物。"

WENDY.DESCRIBE.KYNO_WINE = "与现实生活中的危机略有不同。"

WENDY.DESCRIBE.KYNO_JUICE = "只是与现实生活中的危机略有不同。"

WENDY.DESCRIBE.KYNO_POISON_FROGLEGS = "毒腿会加速我的死亡。"
WENDY.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "只能希望毒药还没有离开。"

WENDY.DESCRIBE.POISONFROGGLEBUNWICH = "我从没想过那个生物会这么好看。"

WENDY.DESCRIBE.KYNO_BREWINGRECIPECARD = "字迹已被弄脏，文字已被遗忘。"

WENDY.DESCRIBE.KYNO_OIL = "与其他东西一起放入火中。"

WENDY.DESCRIBE.BERRYSUNDAE = "圣代永远无法取代阿比盖尔。"

WENDY.DESCRIBE.CHOCOLATE_BLACK = "再甜的糖果也无法融化我的心。"
WENDY.DESCRIBE.CHOCOLATE_WHITE = "再甜的糖果也无法融化我的心。"

WENDY.DESCRIBE.TRICOLORDANGO = "一种不同寻常的甜点，多么经典。"
 
WENDY.DESCRIBE.FRIESFRENCH = "有点脆。"

WENDY.DESCRIBE.PIRATERUM = "死亡在等着我。"

WENDY.DESCRIBE.TWISTEDTEQUILA = "那杯鸡尾酒有点问题。"

WENDY.DESCRIBE.ONIONRINGS = "嗯。有点松脆、湿漉漉的。"

WENDY.DESCRIBE.DONUTS = "味道很甜。但没有我想要的那么甜。"
WENDY.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "味道很甜。但没有我想要的那么甜。"
WENDY.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "味道很甜。但没有我想要的那么甜。"
 
WENDY.DESCRIBE.CINNAMONROLL = "糖混合物看起来不错。"

WENDY.DESCRIBE.GUMMYBEARGERS = "我的嘴可以压碎小熊。"

WENDY.DESCRIBE.PRETZEL = "漂亮的椒盐卷饼！"

WENDY.DESCRIBE.CORNINCUP = "这只是咸玉米。"

WENDY.DESCRIBE.COTTONCANDY = "和我一样，里面是空的。"

WENDY.DESCRIBE.ROASTEDHAZELNUTS = "我猜这是食物……"

WENDY.DESCRIBE.MONSTERMUFFIN = "哼。没什么问题……"

WENDY.DESCRIBE.PINKCAKE = "我们总是为阿比盖尔的派对买一个大蛋糕......"

WENDY.DESCRIBE.CHIPSBAG = "它很容易坏掉。"

WENDY.DESCRIBE.LITTLEBREAD = "你一个人做不了多少事情。"

WENDY.DESCRIBE.HOTHOUND = "她非常喜欢热狗。"

WENDY.DESCRIBE.MILKSHAKE = "甜甜的，甜甜的。"
WENDY.DESCRIBE.MILKSHAKE_PRISMATIC = "甜甜的，甜甜的。"

WENDY.DESCRIBE.NACHOS = "我不能吃那个把事情弄得一团糟。"

WENDY.DESCRIBE.BANANA_PUDDING = "看起来可以吃。"

WENDY.DESCRIBE.SEA_PUDDING = "看起来可以吃。"

WENDY.DESCRIBE.TOM_KHA_SOUP = "没那么甜。"

WENDY.DESCRIBE.MINERTREAT = "幼稚的食物......但是很好吃！"

WENDY.DESCRIBE.RADISHSALAD = "呃，更多蔬菜。"

WENDY.DESCRIBE.PUMPKIN_SOUP = "喂饱身体，饿死灵魂……"

WENDY.DESCRIBE.ALGAE_SOUP = "喂饱身体，饿死灵魂……"

WENDY.DESCRIBE.PARZNIP_SOUP = "喂饱身体，饿死灵魂……"

WENDY.DESCRIBE.NETTLEMEATED = "暂时缓解生活中的悲伤……裹在肉里。"

WENDY.DESCRIBE.KYNO_SUGAR = "一种甜味调味品。"

WENDY.DESCRIBE.KYNO_BOTTLECAP = "我该怎么处理这个？"

WENDY.DESCRIBE.NUKACOLA = "我感觉到它散发出奇怪的气息。"
WENDY.DESCRIBE.NUKACOLA_QUANTUM = "我感觉到它散发出奇怪的气息。"

WENDY.DESCRIBE.LIVINGSANDWICH = "一个充满黑魔法的三明治。"

WENDY.DESCRIBE.DURIANSPLIT = "冰淇淋永远无法取代阿比盖尔。"

WENDY.DESCRIBE.DURIANSOUP = "由植物制成的肉汤。"

WENDY.DESCRIBE.DURIANMEATED = "有臭味。"

WENDY.DESCRIBE.DURIANCHICKEN = "不是贪吃者。"

WENDY.DESCRIBE.LUNARSOUP = "碗里有月亮之力。"

WENDY.DESCRIBE.PURPLEWOBSTERSOUP = "我需要他们死才能让我活着。"

WENDY.DESCRIBE.WOBSTERMONSTER = "这是什么，如果这不是通往死亡的下一步。"

WENDY.DESCRIBE.SPIDERCAKE = "恶心。"

WENDY.DESCRIBE.SUGARBOMBS = "浓缩核火。"

WENDY.DESCRIBE.BERRYBOMBS = "适量的浆果。"

WENDY.DESCRIBE.ONIGIRIS = "米堆。"

WENDY.DESCRIBE.OMURICE = "真奇怪。 这个酱汁笔画拼写出来是\"饥饿\"。"

WENDY.DESCRIBE.PAELLA = "死鱼配米饭，听起来不错。"

WENDY.DESCRIBE.RISOTTO = "我想，只吃米饭和蔬菜也不错..."

WENDY.DESCRIBE.RICESAKE = "蔬菜酒精饮料？唉。"

WENDY.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "从大地中剥离。"

WENDY.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "一株热带水果灌木。",
	PICKED = "它已没什么能给予的了。",
	WITHERED = "生命正从它身上退去。",
	BURNING = "它的终结，来得如此之快。",
}

WENDY.DESCRIBE.KYNO_PINEAPPLE = "装甲水果。"
WENDY.DESCRIBE.KYNO_PINEAPPLE_HALVED = "如果我能分享这些就好了。"
WENDY.DESCRIBE.KYNO_PINEAPPLE_COOKED = "如果我能分享这些就好了。"

WENDY.DESCRIBE.PIZZA_TROPICAL = "这样更好。"

WENDY.DESCRIBE.PINACOLADA = "冰凉爽口。"

WENDY.DESCRIBE.CHIMAS = "看起来很普通。"

WENDY.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "它浇灌不了我干涸的灵魂。",
	ON = "至少，植物们被照料着。",
}

WENDY.DESCRIBE.KYNO_FOODSACK = "它能延缓腐烂和衰变。"

WENDY.DESCRIBE.GUMMYWORMS = "不相信这些。"

WENDY.DESCRIBE.SMORES = "这不是应该在篝火上烤的吗？"

WENDY.DESCRIBE.NUKASHINE = "那个小恶魔... 都是他的错。又是..."

WENDY.DESCRIBE.ANTSLOG = "用真的蚂蚁会更好。"

WENDY.DESCRIBE.KYNO_WORM_BONE = "提醒我自己的死亡。"

WENDY.DESCRIBE.SPOOKY_BRAIN_NOODLES = "健脑食品。"
WENDY.DESCRIBE.SPOOKY_BURGERZILLA = "我发誓，如果那个小恶魔再搞恶作剧，我就会采取严厉措施。"
WENDY.DESCRIBE.SPOOKY_DEADBREAD = "永恒的!"
WENDY.DESCRIBE.SPOOKY_JELLYBEANS = "直盯着我的灵魂。"
WENDY.DESCRIBE.SPOOKY_POPSICLE = "我讨厌大自然。"
WENDY.DESCRIBE.SPOOKY_PUMPKINCREAM = "唉。多么糟糕的组合。"
WENDY.DESCRIBE.SPOOKY_SKULLCANDY = "死亡的甜蜜拥抱。"
WENDY.DESCRIBE.SPOOKY_TACODILE = "我只是不喜欢上面的小橄榄。"

WENDY.DESCRIBE.BUTTER_BEEFALO = "至少他们的牛奶有一些好处。"
WENDY.DESCRIBE.BUTTER_GOAT = "终于没有蝴蝶保姆了！"
WENDY.DESCRIBE.BUTTER_KOALEFANT = "那只野兽一直在逃离我们。我希望这个麻烦是值得的。"

WENDY.DESCRIBE.SPICE_CURE = "你无法逃脱死亡。"
WENDY.DESCRIBE.SPICE_COLD = "冰冷死亡的甜蜜拥抱。"
WENDY.DESCRIBE.SPICE_FIRE = "它们像蜡烛蜡一样燃烧。"
WENDY.DESCRIBE.SPICE_FED = "更多的东西要摄入。"
WENDY.DESCRIBE.SPICE_MIND = "用来缓和紧张时刻的东西。"

WENDY.DESCRIBE.SUGARFLYMUFFIN = "让我们看看你摆脱这个含糖陷阱！"

WENDY.DESCRIBE.EELTACOS = "我希望我把骨头都拔出来了。"

WENDY.DESCRIBE.MEATSKILLET = "像夏天的下午一样又热又辣。"

WENDY.DESCRIBE.MEATWALTZ = "今晚歌手们将一直唱歌。"

WENDY.DESCRIBE.COMPLETEBREAKFAST = "一个人是如何真正吃掉所有这些东西的？"

WENDY.DESCRIBE.DUMPLINGS = "小包子"

WENDY.DESCRIBE.WARLYICEDTEA = "清爽，但它仍然不能缓解我的悲伤。"

WENDY.DESCRIBE.WARLYTEA = "阿比盖尔喜欢茶会。"

WENDY.DESCRIBE.KYNO_TEALEAF = "我确实喜欢时不时地喝一杯茶。"

WENDY.DESCRIBE.KYNO_ITEMSLICER = "厨房工具。"
WENDY.DESCRIBE.KYNO_ITEMSLICER_GOLD = "精良厨具。"

WENDY.DESCRIBE.COXINHA = "所有的面团。"

WENDY.DESCRIBE.LAZYDESSERT = "摇滚糖"

WENDY.DESCRIBE.CRABKINGFEAST = "言语无法形容它有多大。"

WENDY.DESCRIBE.PIENAPPLE = "即使是这些尖刺也没能救它免于死亡。"

WENDY.DESCRIBE.JAWSBREAKER = "这些愚蠢的鲨鱼会学会不要招惹我！"

WENDY.DESCRIBE.AVOCADOTOAST = "从那颗石果上裂开了。"

WENDY.DESCRIBE.RICEPUDDING = "谁能想到是一种米做的布丁？"

WENDY.DESCRIBE.SHARKSUSHI = "我第一次听说鲨鱼握寿司。"

WENDY.DESCRIBE.WOBSTERBREADED = "压碎并裹上面包屑。"

WENDY.DESCRIBE.LAZYPURRITO = "有点可爱。"

WENDY.DESCRIBE.HORCHATA = "我认为我可以进一步改进它。"

WENDY.DESCRIBE.WOBSTERCOCKTAIL = "热，就像它死去的样子。"

WENDY.DESCRIBE.LAVAEEGGBOILED = "也许它会给我一些火的亲和力。"

WENDY.DESCRIBE.POMEGRANATETEA = "清爽，但它仍然不能缓解我的悲伤。"

WENDY.DESCRIBE.TIRAMISU = "我需要更多..."

WENDY.DESCRIBE.TOADSTOOLCOLA = "也许如果我喝了这个东西，我就能回到我姐姐身边。"

WENDY.DESCRIBE.TEPACHE = "清新的。"

WENDY.DESCRIBE.LUNARTEQUILA = "它在呼唤我！"

WENDY.DESCRIBE.MIMICMOSA = "威慑气息。"

WENDY.DESCRIBE.POMEGRANATEPIE = "最近我开始喜欢吃石榴了。"

WENDY.DESCRIBE.PINEAPPLECAKE = "蛋糕是最佳的甜点。"

WENDY.DESCRIBE.PASTY_MEAT = "我的手指上沾满了油。"
WENDY.DESCRIBE.PASTY_CHEESE = "我的手指上沾满了油。"

WENDY.DESCRIBE.BRIGADEIRO = "我...我想要更多..."

WENDY.DESCRIBE.REGULARLASAGNA = "中立善良。"

WENDY.DESCRIBE.FLTSANDWICH = "绿色和青蛙的元素太多了。"

WENDY.DESCRIBE.RICEANDBEANS = "这是一顿非常简单的饭菜，但足够了。"

WENDY.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "即便废墟也会记得它的使命……也许它会在2026年醒来。"

WENDY.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "即便在黑暗中，它们也在生长……",
	PICKED = "没了，如同大多数美好的事物。",
	BURNING = "在能被享用之前，就被摧毁了。",
}

WENDY.DESCRIBE.KYNO_TRUFFLES = "诞生于黑暗的美味。"
WENDY.DESCRIBE.KYNO_TRUFFLES_COOKED = "黑暗化为温暖与滋味。"

WENDY.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "展示着转瞬即逝的美。所有食物都会腐烂……终归如此。",
	FULL = "它很快就会消失的。",
}

WENDY.DESCRIBE.KYNO_SPORECAP = "连蘑菇也会慢慢腐烂。"
WENDY.DESCRIBE.KYNO_SPORECAP_COOKED = "火焰无法净化悲伤。"

WENDY.DESCRIBE.KYNO_SPORECAP_DARK = "来自大地的毒素……真合适。"
WENDY.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "火焰烧焦了它，但邪恶依旧。"

WENDY.DESCRIBE.KYNO_GOLDENAPPLE = "它能暂时洗去我所有的烦恼。"

WENDY.DESCRIBE.TRUFFLESGRINDER = "腐朽之中，也有滋味……"

WENDY.DESCRIBE.SPORECAPPIE = "腐朽之派……多么诗意。"

WENDY.DESCRIBE.SPORECAP_SKEWERS = "被刺穿和烧焦……万物终结的模样。"

WENDY.DESCRIBE.TRUFFLEOIL = "腐朽的精华，被封存在瓶中供人享受。"

WENDY.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "我还要费心建造这个吗？"
WENDY.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "水葬...多么富有诗意。"

WENDY.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "即便在孵化场里，生命也是安静地开始。",
	FUEL_HIGH = "它们的饥饿被满足了。",
	FUEL_MED = "循环，仍在继续。",
	FUEL_LOW = "饥饿，悄然逼近。",
	EMPTY = "唯余空虚。",
}

WENDY.DESCRIBE.KYNO_ANTCHOVY = "半鱼半蚁……一生困惑与痛苦。"
WENDY.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "一片嗡嗡作响、扭动蠕动的痛苦之海。"

WENDY.DESCRIBE.AGEDROE = "我夺走他们的性命来延续自己的生命。"
WENDY.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "死亡孕育生命……何等美妙的讽刺。"

WENDY.DESCRIBE.KYNO_SWORDFISH_BLUE = "就连大海也会拒绝那些在平静水域中停留太久的人。"

WENDY.DESCRIBE.KYNO_JELLYFISH = "如此奇特之物，竟能存活于世？"
WENDY.DESCRIBE.KYNO_JELLYFISH_DEAD = "这是一场无痛的死亡。那头野兽没有神经系统。"
WENDY.DESCRIBE.KYNO_JELLYFISH_COOKED = "它有点像明胶。"
WENDY.DESCRIBE.KYNO_JELLYFISH_DRIED = "所以……真够呛。"

WENDY.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "它看起来如此满足。"
WENDY.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "死亡已然降临。"
WENDY.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "美丽，即使在死亡中。"

WENDY.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "空荡。如同我的灵魂。"

WENDY.DESCRIBE.KYNO_OCEANTRAP = "来吧，海洋生灵！享用美味点心！"

WENDY.DESCRIBE.OCEANFISH_PUFFERFISH = "它因恐惧而鼓起...我懂这种感觉。"
WENDY.DESCRIBE.OCEANFISH_STURGEON = "它经历了漫长的岁月……或许太过漫长。"

WENDY.DESCRIBE.KYNO_SWORDFISH = "这条鱼用脸割断死亡！"
WENDY.DESCRIBE.KYNO_SWORDFISH_DEAD = "它的剑面也救不了它。"

WENDY.DESCRIBE.SWORDFISHFEAST = "海洋之刃，如今已被厨刀钝化……"

WENDY.DESCRIBE.KYNO_DOGFISH = "如此优雅的游姿。如此鲜美的鱼。"
WENDY.DESCRIBE.KYNO_DOGFISH_DEAD = "它已挣脱尘世的束缚。"

WENDY.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "再会了，朋友。"

WENDY.DESCRIBE.WOBSTER_MONKEYISLAND = "纵使黄金也难逃沸腾的锅。"
WENDY.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "即便是黄金也逃不过死亡。"
WENDY.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "即便在死亡中，它仍带来滋养。多么富有诗意。"

WENDY.DESCRIBE.KYNO_PUFFERMONSTER = "它膨胀着...如同我们为了生存而欺骗自我的谎言。"

WENDY.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "看起来像条胀气的鱼。"
WENDY.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "它看起来很悲伤。也许它也知道生命毫无意义。"
WENDY.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "它的眼中燃烧着对生命的憎恨！"
WENDY.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "这么大又死了的东西，肯定会发臭。"

WENDY.DESCRIBE.KYNO_BLUBBER = "为一个哭哭啼啼的傻瓜而准备的完美餐点。"

WENDY.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "即使干枯了，它仍散发着腐朽的气息。"
WENDY.DESCRIBE.KYNO_FISHMEAT_DRIED = "曾经鲜活，如今永恒保存。"

WENDY.DESCRIBE.MONKEYISLANDMEAL = "即使受诅咒之人，也配尝一口恩典。"

WENDY.DESCRIBE.KYNO_BRAINROCK_LARVAE = "多恶心的蠕虫啊。"
WENDY.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "赤裸裸的，完全没有生命迹象。"
WENDY.DESCRIBE.KYNO_BRAINROCK_CORAL = "这就是我内心的模样吗？"

WENDY.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "一株看起来挺聪明的植物。",
	PICKED = "它在休息，如同所有心智一样。",
}

WENDY.DESCRIBE.BRAINMETTERSOUP = "这是给孩子的。"

WENDY.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "我羡慕他的满足。",
	SLEEPING = "即便是王者，也必须休息。",
}

WENDY.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "那地方看起来不太适合存放东西。"

WENDY.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "一个死掉的鱼玩意儿。看起来挺重要。",
	WAITING = "它已回归自然状态。",
}

WENDY.DESCRIBE.KYNO_PACKIMBAGGIMS = "我连条鱼都不放心交给他，但或许我的破船……"

WENDY.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "那我们就开始烘焙吧。"
WENDY.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "我们需要更多原料才能完成它。"
WENDY.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "即使庆祝终有结束之时，但或许我该趁此刻尽情享受。"
WENDY.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "每一簇火焰，都是转瞬即逝的瞬间……"
WENDY.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "这让我想起和阿比盖尔一起过的生日派对。"
WENDY.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "甜蜜无法填补内心的空虚..."
WENDY.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "短暂的欢愉……注定要消散。"

WENDY.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "安静的爆裂声，配得上安静的思绪。",
	FUEL_HIGH = "它仍有存在的意义。",
	FUEL_MED = "它的时间不多了。",
	FUEL_LOW = "很快，它就会归于沉寂。",
	EMPTY = "只余寂静。",
}

WENDY.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "它迸发……然后被吞噬……就像所有短暂的欢愉。"
WENDY.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "强颜欢笑的象征……多么贴切。"
WENDY.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "致萨米……那个与众不同的人……"

WENDY.DESCRIBE.KYNO_FISHREGISTRYHAT = "它记录着波涛之下悄然漂流的生命。"

WENDY.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "对饥饿生灵的一点小小仁慈。",
	FUEL_HIGH = "它们今天不会挨饿了。",
	FUEL_MED = "食物正在减少。",
	FUEL_LOW = "饥饿正在逼近。",
	EMPTY = "唯余空虚。",
	BURNT = "灰烬喂不饱任何人。",
}

WENDY.DESCRIBE.CHICKENNUGGETS = "连鸡也被碎尸万段了。"

WENDY.DESCRIBE.CHICKENWINGS = "就连味道里，也带着痛楚。"

WENDY.DESCRIBE.CHICKENBURGER = "慰藉的食物，短暂地延缓着绝望。"

WENDY.DESCRIBE.CHICKENEGGSOUP = "寒冷世界中的一抹安静温暖。"

WENDY.DESCRIBE.CHICKENEGGSTEW = "生命，被熬煮在一口锅里。"

WENDY.DESCRIBE.CHICKENROTISSERIE = "无休止地转动，如同万物一般。"