local WEBBER = STRINGS.CHARACTERS.WEBBER

WEBBER.ANNOUNCE_KYNO_COFFEEBUFF_START = "哇！"
WEBBER.ANNOUNCE_KYNO_COFFEEBUFF_END = "噢，速度没了。"

WEBBER.ANNOUNCE_KYNO_HASTEBUFF_START = "哇！哇！"
WEBBER.ANNOUNCE_KYNO_HASTEBUFF_END = "我们的手需要休息一下。"

WEBBER.ANNOUNCE_KYNO_POPBUFF_START = "（嗝！）哈哈哈！"
WEBBER.ANNOUNCE_KYNO_POPBUFF_END = "泡泡不见了！"

WEBBER.ANNOUNCE_KYNO_FROGBUFF_START = "我们现在就像青蛙一样！"
WEBBER.ANNOUNCE_KYNO_FROGBUFF_END = "哇哦，我们喜欢青蛙的时光！"

WEBBER.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝!) 哈哈哈!"
WEBBER.ANNOUNCE_KYNO_PIRATEBUFF_END = "气泡消失了！"

WEBBER.ANNOUNCE_KYNO_FREEZEBUFF_START = "这双手，冻僵了！"
WEBBER.ANNOUNCE_KYNO_FREEZEBUFF_END = "噢，结束了。"

WEBBER.ANNOUNCE_KYNO_FIREBUFF_START = "我们着火了！"
WEBBER.ANNOUNCE_KYNO_FIREBUFF_END = "噢，结束了。"

WEBBER.ANNOUNCE_KYNO_FISHINGBUFF_START = "让我们去钓鱼探险吧！"
WEBBER.ANNOUNCE_KYNO_FISHINGBUFF_END = "现在不再有更多的鱼了。"

WEBBER.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "啊......！"
WEBBER.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "我们的大脑现在感觉好多了。"

WEBBER.ANNOUNCE_KYNO_EATERBUFF_START = "我们的胃感觉有点奇怪！"
WEBBER.ANNOUNCE_KYNO_EATERBUFF_END = "我们的胃有点头晕。"

WEBBER.ANNOUNCE_KYNO_WORMBUFF_START = "让我们抓些虫子吧！"
WEBBER.ANNOUNCE_KYNO_WORMBUFF_END = "我们和虫子的战斗暂时结束了。"

WEBBER.ANNOUNCE_KYNO_CRABBUFF_START = "让我们抓一些螃蟹。"
WEBBER.ANNOUNCE_KYNO_CRABBUFF_END = "我们和螃蟹的战斗暂时结束了。"

WEBBER.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝！) 哈哈哈！"
WEBBER.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "泡沫消失了！"

WEBBER.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "哦...！"
WEBBER.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "哇！真奇怪！"

WEBBER.ANNOUNCE_KYNO_STEALTHBUFF_START = "我们感觉自己像个忍者！"
WEBBER.ANNOUNCE_KYNO_STEALTHBUFF_END = "哇，我们不再是他们看不见的了。"

WEBBER.ANNOUNCE_KYNO_FEARBUFF_START = "我们什么都不怕！"
WEBBER.ANNOUNCE_KYNO_FEARBUFF_END = "一切又变得可怕了！躲在树上，朋友们！"

WEBBER.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "我们变强了！"
WEBBER.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "啊……已经结束了吗？"

WEBBER.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "我们觉得它们不会明白。"
WEBBER.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "我们的猪朋友离开了……"

WEBBER.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "我们觉得麻麻的……但很安全！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WEBBER.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "我们感觉怪怪的……但很好！"
WEBBER.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "呃哦……我们不安全了。"

WEBBER.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "哇！我们现在感觉超级聪明！"
WEBBER.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "哎呀，再也没有聪明的想法了……"

WEBBER.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "蜜蜂现在喜欢我们了！嗨，蜜蜂们！"
WEBBER.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "啊……蜜蜂不再友好了。"

WEBBER.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "我们感觉超级强壮！"
WEBBER.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "哎呀……我们喜欢变的强！"

WEBBER.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "现在我们可以吃得更多啦！耶！"
WEBBER.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "没地方了……"

WEBBER.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "我们的头脑感觉舒畅而平静！"
WEBBER.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "哎呀……情况又变得诡异起来了。"

WEBBER.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "哇！我们感觉比以前强壮多了！"
WEBBER.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "糟糕……我们感觉自己没那么坚强了。"

WEBBER.ANNOUNCE_KYNO_BERSERKERBUFF_START = "哇！我们现在打得超狠！"
WEBBER.ANNOUNCE_KYNO_BERSERKERBUFF_END = "我们觉得没那么猛了。"

WEBBER.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "我们饿得没那么快了！"
WEBBER.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "唔哦，我们又饿了。"

WEBBER.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "不是这个。"

WEBBER.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "我们认为这不是他想吃的饭菜。"

WEBBER.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "我们应该等到它完全长大。"

WEBBER.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "这里不合适。"

WEBBER.ANNOUNCE_KYNO_POTHANGER_FAIL = "唉，或许用个烹饪锅比较好。"

WEBBER.ANNOUNCE_KYNO_CASSEROLE_FAIL = "这不是应该放在那里的东西。"

WEBBER.ANNOUNCE_KYNO_SAPHEALER_USED = "耶！这棵树又活过来了！"

WEBBER.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "我们很抱歉……可是我们饿了……"

WEBBER.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "哎呀，空空的……"

WEBBER.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "糟了！小径不见了！"
WEBBER.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "雨水冲刷了所有东西！"
WEBBER.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "我们听到外面有可怕的声音……"

WEBBER.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "太棒了！蛋糕做好啦！"

WEBBER.ANNOUNCE_KYNO_FISH_RESEARCHED = "我们一起弄明白了！"
WEBBER.ANNOUNCE_KYNO_ROE_RESEARCHED = "我们学到了小鱼宝宝的事情！"

WEBBER.DESCRIBE.KYNO_ROE = "它们不是蜘蛛蛋。"
WEBBER.DESCRIBE.KYNO_ROE_COOKED = "不是我们习惯的那种鸡蛋。"

WEBBER.DESCRIBE.KYNO_SHARK_FIN = "我可一点都不想碰它"

WEBBER.DESCRIBE.KYNO_BEANBUGS = "这些家伙看起来很整洁！"
WEBBER.DESCRIBE.KYNO_BEANBUGS_COOKED = "对不起，小家伙们。"

WEBBER.DESCRIBE.KYNO_GUMMYBUG = "黏糊糊的小家伙。"
WEBBER.DESCRIBE.KYNO_GUMMYBUG_COOKED = "不确定我们应该吃这些。"

WEBBER.DESCRIBE.KYNO_WHEAT = "要是我回到磨坊就好了。"
WEBBER.DESCRIBE.KYNO_WHEAT_COOKED = "要是我回到磨坊就好了。"

WEBBER.DESCRIBE.KYNO_FLOUR = "妈妈用它为我们做披萨。"

WEBBER.DESCRIBE.KYNO_SPOTSPICE = "我们把它全部接地。"

WEBBER.DESCRIBE.KYNO_SAP = "黏糊糊的。"
WEBBER.DESCRIBE.KYNO_SAP_SPOILED = "啊这……已经不行了。"

WEBBER.DESCRIBE.KYNO_SYRUP = "甜蜜！"

WEBBER.DESCRIBE.KYNO_COFFEEBEANS = "这些气味非常……诱人。"
WEBBER.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "这些让我们觉得很有趣。"

WEBBER.DESCRIBE.DUG_KYNO_COFFEEBUSH = "我们可以把它种到别处去！"

WEBBER.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "这些看起来不好吃。",
	PICKED = "现在没豆子了。",
	WITHERED = "我们得给它施点灰。",
}

WEBBER.DESCRIBE.DUG_KYNO_SPOTBUSH = "我们得把它种在什么地方！"

WEBBER.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "好酷的紫色灌木啊。",
	PICKED = "现在没东西可摘了。",
	BURNING = "嘿！住手！",
}

WEBBER.DESCRIBE.KYNO_SPOTSPICE_LEAF = "它本身的味道不太好。"

WEBBER.DESCRIBE.KYNO_MUSSEL = "也许有一天我会吃到大贻贝。"
WEBBER.DESCRIBE.KYNO_MUSSEL_COOKED = "还是有点恶心。"

WEBBER.DESCRIBE.KYNO_HUMANMEAT = "这是个糟糕的主意。"
WEBBER.DESCRIBE.KYNO_HUMANMEAT_COOKED = "我们确定这是烤熟的人肉。"
WEBBER.DESCRIBE.KYNO_HUMANMEAT_DRIED = "干人肉。"

WEBBER.DESCRIBE.COFFEE = "苦涩。"

WEBBER.DESCRIBE.BISQUE = "美味到举起大拇指。"

WEBBER.DESCRIBE.JELLYOPOP = "好吃！"

WEBBER.DESCRIBE.SHARKFINSOUP = "嗯，嗯，汤！"

WEBBER.DESCRIBE.TROPICALBOUILLABAISSE = "嗯！尝起来像食物！"

WEBBER.DESCRIBE.MUSSELBOUILLABAISE = "和他们一样开胃。"

WEBBER.DESCRIBE.SWEETPOTATOSOUFFLE = "太精致了。"

WEBBER.DESCRIBE.FEIJOADA = "好吃！"

WEBBER.DESCRIBE.GUMMY_CAKE = "嘿嘿。​​它让我们的肚子在颤抖。"

WEBBER.DESCRIBE.HARDSHELL_TACOS = "好吃又脆！"

WEBBER.DESCRIBE.ICEDTEA = "好吃！"

WEBBER.DESCRIBE.NETTLELOSANGE = "有点辣。"

WEBBER.DESCRIBE.SNAKEBONESOUP = "有点像鸡肉面条的味道。"

WEBBER.DESCRIBE.STEAMEDHAMSANDWICH = "这些只是汉堡包。"

WEBBER.DESCRIBE.TEA = "来个茶话会吧！"

WEBBER.DESCRIBE.BUBBLETEA = "好吃！"

WEBBER.DESCRIBE.FRENCHONIONSOUP = "有点像鸡肉面条的味道。"

WEBBER.DESCRIBE.SLAW = "我们必须吃蔬菜吗？"

WEBBER.DESCRIBE.LOTUSBOWL = "这看起来很好吃。"

WEBBER.DESCRIBE.POI = "乌拉！"

WEBBER.DESCRIBE.JELLYBEAN_HUNGER = "它们会长成糖豆茎吗？"
WEBBER.DESCRIBE.JELLYBEAN_SUPER = "它们会长成糖豆茎吗？"
WEBBER.DESCRIBE.JELLYBEAN_SANITY = "它们会长成糖豆茎吗？"

WEBBER.DESCRIBE.BOWLOFGEARS = "只是一堆齿轮。"

WEBBER.DESCRIBE.LONGPIGMEAL = "呃。"

WEBBER.DESCRIBE.CUCUMBERSALAD = "一天五份。"

WEBBER.DESCRIBE.DUG_KYNO_WILDWHEAT = "我们可以再种一次！"

WEBBER.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "一种基础食物来源！",
	PICKED = "现在啥都没了。",
	WITHERED = "全枯了。",
	BURNING = "嘿！住手！",
}

WEBBER.DESCRIBE.KYNO_MEALGRINDER = "我们想做研磨！"

WEBBER.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "这些蘑菇好小啊。",
	PICKED = "它们晚点会再长出来的。",
	BURNING = "哦不！",
}

WEBBER.DESCRIBE.GORGE_BREAD = "妈妈总是说面包对大多数食物都有好处。"
WEBBER.DESCRIBE.GORGE_SWEET_CHIPS = "非常脆！"
WEBBER.DESCRIBE.GORGE_VEGETABLE_SOUP = "妈妈总是说要吃蔬菜。"
WEBBER.DESCRIBE.GORGE_JELLY_SANDWICH = "果酱三明治，耶！"
WEBBER.DESCRIBE.GORGE_FISH_STEW = "健康。"
WEBBER.DESCRIBE.GORGE_MEAT_STEW = "闻起来像周日晚餐。"
WEBBER.DESCRIBE.GORGE_ONION_CAKE = "这不是我们最喜欢的。"
WEBBER.DESCRIBE.GORGE_POTATO_PANCAKES = "能给我们来点糖浆吗？"
WEBBER.DESCRIBE.GORGE_POTATO_SOUP = "吃的时候，我们会翘起小指。"
WEBBER.DESCRIBE.GORGE_FISHBALL_SKEWERS = "我们喜欢它。"
WEBBER.DESCRIBE.GORGE_MEAT_SKEWERS = "我们喜欢它。"
WEBBER.DESCRIBE.GORGE_STONE_SOUP = "吃的时候，我们会翘起小指。"
WEBBER.DESCRIBE.GORGE_CROQUETTE = "我们认为这很好！"
WEBBER.DESCRIBE.GORGE_ROAST_VEGETABLES = "妈妈总是说要吃蔬菜。"
WEBBER.DESCRIBE.GORGE_MEATLOAF = "美味！"
WEBBER.DESCRIBE.GORGE_CARROT_SOUP = "吃的时候，我们会翘起小指。"
WEBBER.DESCRIBE.GORGE_FISHPIE = "看起来奇怪，但味道不错！"
WEBBER.DESCRIBE.GORGE_FISHCHIPS = "很棒的组合！"
WEBBER.DESCRIBE.GORGE_MEATPIE = "我们喜欢它。"
WEBBER.DESCRIBE.GORGE_SLIDERS = "我们需要更多这样的东西！"
WEBBER.DESCRIBE.GORGE_JELLY_ROLL = "我们爱果冻！"
WEBBER.DESCRIBE.GORGE_CARROT_CAKE = "味道不错，但我们更喜欢巧克力蛋糕！"
WEBBER.DESCRIBE.GORGE_GARLICMASHED = "闻起来不错！"
WEBBER.DESCRIBE.GORGE_GARLICBREAD = "美味！"
WEBBER.DESCRIBE.GORGE_TOMATO_SOUP = "吃的时候，我们会翘起小指。"
WEBBER.DESCRIBE.GORGE_SAUSAGE = "猪肉，他喜欢。"
WEBBER.DESCRIBE.GORGE_CANDIEDFISH = "加糖的鱼做得很好！"
WEBBER.DESCRIBE.GORGE_STUFFEDMUSHROOM = "糊糊的！"
WEBBER.DESCRIBE.GORGE_BRUSCHETTA = "也许我们还可以用其他配料？"
WEBBER.DESCRIBE.GORGE_HAMBURGER = "嗯！"
WEBBER.DESCRIBE.GORGE_FISHBURGER = "好吃！"
WEBBER.DESCRIBE.GORGE_MUSHROOMBURGER = "好吃！"
WEBBER.DESCRIBE.GORGE_FISH_STEAK = "健康。"
WEBBER.DESCRIBE.GORGE_CURRY = "那时候，妈妈经常给我们做这个。"
WEBBER.DESCRIBE.GORGE_SPAGHETTI = "我以前和爷爷一起做这些！"
WEBBER.DESCRIBE.GORGE_POACHEDFISH = "我们喜欢它！"
WEBBER.DESCRIBE.GORGE_SHEPHERD_PIE = "我们喜欢这个！"
WEBBER.DESCRIBE.GORGE_CANDY = "焦糖糖果！"
WEBBER.DESCRIBE.GORGE_BREAD_PUDDING = "甜到极致。"
WEBBER.DESCRIBE.GORGE_BERRY_TART = "甜美的水果！"
WEBBER.DESCRIBE.GORGE_MACARONI = "我们喜欢它的奶酪味。"
WEBBER.DESCRIBE.GORGE_BAGEL_AND_FISH = "它的味道很好。"
WEBBER.DESCRIBE.GORGE_GRILLED_CHEESE = "我们记得早餐就吃这个。"
WEBBER.DESCRIBE.GORGE_CREAMMUSHROOM = "汤。"
WEBBER.DESCRIBE.GORGE_MANICOTTI = "味道不错！"
WEBBER.DESCRIBE.GORGE_CHEESEBURGER = "好吃！"
WEBBER.DESCRIBE.GORGE_FETTUCCINE = "好极了。"
WEBBER.DESCRIBE.GORGE_ONION_SOUP = "我已经能感觉到里面有洋葱了！"
WEBBER.DESCRIBE.GORGE_BREADED_CUTLET = "美味可口"
WEBBER.DESCRIBE.GORGE_CREAMY_FISH = "美味的鲑鱼。"
WEBBER.DESCRIBE.GORGE_PIZZA = "披萨！披萨！"
WEBBER.DESCRIBE.GORGE_POT_ROAST = "哇!"
WEBBER.DESCRIBE.GORGE_CRAB_CAKE = "啊，他看起来真可爱！"
WEBBER.DESCRIBE.GORGE_STEAK_FRITES = "很棒的薯条。"
WEBBER.DESCRIBE.GORGE_SHOOTER_SANDWICH = "午后小点心！"
WEBBER.DESCRIBE.GORGE_BACON_WRAPPED = "包裹得很好的肉。"
WEBBER.DESCRIBE.GORGE_CRAB_ROLL = "好吃!"
WEBBER.DESCRIBE.GORGE_MEAT_WELLINGTON = "沃利的表现着实让我们吃惊！"
WEBBER.DESCRIBE.GORGE_CRAB_RAVIOLI = "好吃!"
WEBBER.DESCRIBE.GORGE_CARAMEL_CUBE = "噢耶！一块焦糖！"
WEBBER.DESCRIBE.GORGE_SCONE = "这些食物看起来很美，我们却不想吃！"
WEBBER.DESCRIBE.GORGE_TRIFLE = "这些食物看起来很美，我们却不想吃！"
WEBBER.DESCRIBE.GORGE_CHEESECAKE = "看起来不错。不知道味道是否也不错！"

WEBBER.DESCRIBE.DUCKYOUGLERMZ = "多么邪恶的一餐!"

WEBBER.DESCRIBE.KYNO_ALOE = "我敢打赌这对我们有好处！"
WEBBER.DESCRIBE.KYNO_ALOE_COOKED = "我做的！"
WEBBER.DESCRIBE.KYNO_ALOE_GROUND = "我敢打赌这对我们有好处！"
WEBBER.DESCRIBE.KYNO_ALOE_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.FARM_PLANT_KYNO_ALOE = "我打赌这对我们有好处！"
WEBBER.DESCRIBE.KYNO_ALOE_OVERSIZED = "我打赌这对我们有好处！"
WEBBER.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "哇!"

WEBBER.DESCRIBE.KYNO_CUCUMBER = "黏糊糊的，但令人满意。"
WEBBER.DESCRIBE.KYNO_CUCUMBER_COOKED = "他不太喜欢，但我觉得没关系。"
WEBBER.DESCRIBE.KYNO_CUCUMBER_GROUND = "黏糊糊的，但令人满意。"
WEBBER.DESCRIBE.KYNO_CUCUMBER_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "黏糊糊的，但令人满意。"
WEBBER.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "黏糊糊的，但令人满意。"
WEBBER.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "黏糊糊的，但令人满意。"

WEBBER.DESCRIBE.KYNO_RADISH = "这些有点辣。"
WEBBER.DESCRIBE.KYNO_RADISH_COOKED = "这将使我们长大壮大。"
WEBBER.DESCRIBE.KYNO_RADISH_GROUND = "这些有点辣。"
WEBBER.DESCRIBE.KYNO_RADISH_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.FARM_PLANT_KYNO_RADISH = "这些有点辣。"
WEBBER.DESCRIBE.KYNO_RADISH_OVERSIZED = "这些有点辣。"
WEBBER.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "哇!"

WEBBER.DESCRIBE.KYNO_FENNEL = "我们以前从未见过这个！"
WEBBER.DESCRIBE.KYNO_FENNEL_COOKED = "现在都暖和了。"
WEBBER.DESCRIBE.KYNO_FENNEL_GROUND = "我们以前从未见过这种情况！"
WEBBER.DESCRIBE.KYNO_FENNEL_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "我们以前从未见过！"
WEBBER.DESCRIBE.KYNO_FENNEL_OVERSIZED = "我们以前从未见过！"
WEBBER.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "哇!"

WEBBER.DESCRIBE.KYNO_SWEETPOTATO = "你说的是\"po-tat-o​​\",我说的是\"晚餐\"！"
WEBBER.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "橙色食物糊。"
WEBBER.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "你说的是\"po-tat-o​​\",我说的是\"晚餐\"！"
WEBBER.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "你说的是\"po-tat-o​​\",我说的是\"晚餐\"！"
WEBBER.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "你说的是\"po-tat-o​​\",我说的是\"晚餐\"！"
WEBBER.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "哇!"

WEBBER.DESCRIBE.KYNO_PARZNIP = "我们对被迫吃这些的小姐进行分类。"
WEBBER.DESCRIBE.KYNO_PARZNIP_COOKED = "我们很想念被迫吃这些东西。"
WEBBER.DESCRIBE.KYNO_PARZNIP_EATEN = "我们对被迫吃这些的小姐进行排序。"
WEBBER.DESCRIBE.KYNO_PARZNIP_GROUND = "我们想念被迫吃这些东西。"
WEBBER.DESCRIBE.KYNO_PARZNIP_BIG = "哇！"
WEBBER.DESCRIBE.KYNO_PARZNIP_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "我们很想念被迫吃这些东西。"
WEBBER.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "我们想念被迫吃这些东西。"
WEBBER.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "哇!"

WEBBER.DESCRIBE.KYNO_TURNIP = "哇！这是萝卜！"
WEBBER.DESCRIBE.KYNO_TURNIP_COOKED = "我们烤了萝卜。"
WEBBER.DESCRIBE.KYNO_TURNIP_GROUND = "哇！这是萝卜！"
WEBBER.DESCRIBE.KYNO_TURNIP_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "哇！这是萝卜！"
WEBBER.DESCRIBE.KYNO_TURNIP_OVERSIZED = "哇！这是萝卜！"
WEBBER.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "哇!"

WEBBER.DESCRIBE.KYNO_RICE = "我们喜欢它！"
WEBBER.DESCRIBE.KYNO_RICE_COOKED = "我们喜欢它！"
WEBBER.DESCRIBE.KYNO_RICE_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "我们可以用这些种植一些东西。"
WEBBER.DESCRIBE.FARM_PLANT_KYNO_RICE = "哇哦！是米饭！"
WEBBER.DESCRIBE.KYNO_RICE_OVERSIZED = "哇哦！是米饭！"
WEBBER.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "哇!"

WEBBER.DESCRIBE.KYNO_SEEDS_KIT = "我们需要种植它们！"

WEBBER.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "这块石头上全是能吃的东西！",
	PICKED = "它们需要时间才能长回来。",
	WITHERED = "啥也没长。",
}

WEBBER.DESCRIBE.KYNO_LIMPETS = "我们必须吃这些吗？"
WEBBER.DESCRIBE.KYNO_LIMPETS_COOKED = "尝起来像海洋。"

WEBBER.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "哇，它好粉啊！",
	PICKED = "现在没花了。",
	BURNING = "嘿！住手！",
}

WEBBER.DESCRIBE.KYNO_LOTUS_ROOT = "我们应该把这个种在海洋的某个地方。"
WEBBER.DESCRIBE.KYNO_LOTUS_FLOWER = "天哪，这太美了。"
WEBBER.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "这看起来很好吃。"

WEBBER.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "海里的沙拉……",
	PICKED = "它们会再长出来的，对吧？",
	BURNING = "哇！这东西怎么可能烧得起来？！",
}

WEBBER.DESCRIBE.KYNO_SEAWEEDS = "海洋沙拉。"
WEBBER.DESCRIBE.KYNO_SEAWEEDS_COOKED = "很咸。"
WEBBER.DESCRIBE.KYNO_SEAWEEDS_DRIED = "它粘在我们的上颚！"
WEBBER.DESCRIBE.KYNO_SEAWEEDS_ROOT = "我们应该把它种在海洋的某个地方。"

WEBBER.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "我们想吃这个！",
	PICKED = "它很快就会再长出来的。",
	BURNING = "嘿！住手！",
}

WEBBER.DESCRIBE.KYNO_TAROROOT_ROOT = "我们应该把这个种在海洋的某个地方。"
WEBBER.DESCRIBE.KYNO_TAROROOT = "废话，芋头。"
WEBBER.DESCRIBE.KYNO_TAROROOT_COOKED = "妈妈知道我喜欢烤熟的。"

WEBBER.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "是个水白菜！",
	PICKED = "希望它快点长回来。",
	BURNING = "嘿！那太不友好了！",
}

WEBBER.DESCRIBE.KYNO_WATERYCRESS_ROOT = "我们应该把这个种在海洋的某个地方。"
WEBBER.DESCRIBE.KYNO_WATERYCRESS = "这是水卷心菜！"

WEBBER.DESCRIBE.WATERYCRESSBOWL = "嗯……暖暖我们的肚子。"

WEBBER.DESCRIBE.KYNO_SALT = "我们不会在食物中使用太多盐。"

WEBBER.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "它们长在棍子上！",
	PICKED = "它们晚点会再回来的。",
	BURNING = "啊！我们得把火扑灭！",
}

WEBBER.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "贻贝在这上面做引体向上。"

WEBBER.DESCRIBE.CATFOOD = "给我们朋友最好的食物！"

WEBBER.DESCRIBE.KATFOOD = "给我们朋友最好的食物！"

WEBBER.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "是一棵热带树！上面全是香蕉！",
	PICKED = "还没香蕉呢。",
	CHOPPED = "啊……没了。",
	BURNING = "嘿！我得把火扑灭！",
	BURNT = "现在只剩灰了。",
}

WEBBER.DESCRIBE.KYNO_BANANA = "一捆香蕉。"
WEBBER.DESCRIBE.KYNO_BANANA_COOKED = "热香蕉！"

WEBBER.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "这棵树有礼物！",
	PICKED = "还没椰子呢。",
	CHOPPED = "啊呜，没了。",
	BURNING = "嘿！住手！",
	BURNT = "现在只剩灰了。",
}

WEBBER.DESCRIBE.KYNO_KOKONUT = "食物！来自树！"
WEBBER.DESCRIBE.KYNO_KOKONUT_HALVED = "现在我们每个人都有一个。"
WEBBER.DESCRIBE.KYNO_KOKONUT_COOKED = "只需要一把小雨伞。"

WEBBER.DESCRIBE.BOWLOFPOPCORN = "耶，爆米花！"

WEBBER.DESCRIBE.FIGJUICE = "好吃！"

WEBBER.DESCRIBE.COCONUTWATER = "好吃！"

WEBBER.DESCRIBE.EYEBALLSPAGHETTI = "噢，哇！"

WEBBER.DESCRIBE.FORGETMELOTS_SEEDS = "我们可以用这些种植一些东西。"

WEBBER.DESCRIBE.FIRENETTLES_SEEDS = "我们可以用这些种植一些东西。"

WEBBER.DESCRIBE.TILLWEED_SEEDS = "我们可以用这些种植一些东西。"

WEBBER.DESCRIBE.KYNO_FLOATILIZER = "我看到妈妈在她的花园里用这个。"

WEBBER.DESCRIBE.KYNO_TWIGGYNUTS = "我们认为，它们非常脆。"

WEBBER.DESCRIBE.KYNO_REPAIRTOOL = "出门必带。"

WEBBER.DESCRIBE.KYNO_KOI = "它好像有胡须！"
WEBBER.DESCRIBE.KYNO_KOI_COOKED = "它好像有胡须！"

WEBBER.DESCRIBE.KYNO_TROPICALFISH = "很漂亮。"
WEBBER.DESCRIBE.KYNO_TROPICALFISH_COOKED = "啊。"

WEBBER.DESCRIBE.KYNO_NEONFISH = "你太粘了！"
WEBBER.DESCRIBE.KYNO_NEONFISH_COOKED = "嗯，闻起来很香！"

WEBBER.DESCRIBE.KYNO_GROUPER = "哈哈！真是一张傻脸。"
WEBBER.DESCRIBE.KYNO_GROUPER_COOKED = "他喜欢鱼头。我不喜欢。"
 
WEBBER.DESCRIBE.KYNO_PIERROTFISH = "很滑！"
WEBBER.DESCRIBE.KYNO_PIERROTFISH_COOKED = "它不再那么可爱了。"

WEBBER.DESCRIBE.KYNO_SALMONFISH = "妈妈说鱼油对我们的大脑有好处。"
WEBBER.DESCRIBE.KYNO_SALMONFISH_COOKED = "闻起来很香！"

WEBBER.DESCRIBE.TURF_PINKPARK = "可爱！"
WEBBER.DESCRIBE.TURF_STONECITY = "我们挖出的一些土地。"
WEBBER.DESCRIBE.TURF_FIELDS = "我们挖出的一些土地。"
WEBBER.DESCRIBE.TURF_TIDALMARSH = "我们挖出的一些土地。"

WEBBER.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "盐准备好了。",
	PICKED = "我们得等更多的盐。",
}

WEBBER.DESCRIBE.KYNO_SALTRACK_INSTALLER = "我们应该把它安装在结晶的池塘里。"

WEBBER.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "这是一个大桶。"

WEBBER.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "我们可以把小螃蟹困在里面。"

WEBBER.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "你好，猪先生！",
	SLEEPING = "我觉得他睡着了。",
}

WEBBER.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "我在想，人们为什么离开了这个好地方。",
	CHOPPED = "怎么会有人干这种事？",
	SAPPED = "黏糊糊，黏糊糊的树液！",
	PICKED = "还没树液呢。",
	BURNING = "我们必须把火扑灭！",
	BURNT = "没了……",
}

WEBBER.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "啊，现在它没那么粉了。",
	CHOPPED = "也许这样反而更好。",
	SAPPED = "呕，还是黏糊糊的。",
	PICKED = "呕……虫子爬进去了。",
	BURNING = "这样也好。",
	BURNT = "全没了。",
}

WEBBER.DESCRIBE.KYNO_SUGARTREE_BUD = "糖！"

WEBBER.DESCRIBE.KYNO_SUGARTREE_FLOWER = "我们同意鲜花是美好的。"
WEBBER.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "我们同意花是好的。"

WEBBER.DESCRIBE.KYNO_SUGARTREE_PETALS = "我们同意花很好看。"

WEBBER.DESCRIBE.KYNO_PEBBLECRAB = "别害怕！"

WEBBER.DESCRIBE.KYNO_CRABMEAT = "螃蟹有点像蜘蛛。"
WEBBER.DESCRIBE.KYNO_CRABMEAT_COOKED = "我们不想吃它。"
WEBBER.DESCRIBE.KYNO_CRABMEAT_DRIED = "螃蟹长得有点像蜘蛛。"

WEBBER.DESCRIBE.KYNO_CRABKINGMEAT = "螃蟹长得有点像蜘蛛。"
WEBBER.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "螃蟹看起来有点像蜘蛛。"
WEBBER.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "螃蟹看起来有点像蜘蛛。"

WEBBER.DESCRIBE.KYNO_SLAUGHTERTOOL = "我不想用这个。"

WEBBER.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "哈哈！我们喜欢鸡！",
	COOP = "我们可以养着它！",
}

WEBBER.DESCRIBE.KYNO_CHICKEN_EGG = "一个硬壳鸡蛋。"
WEBBER.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "里面是不是有只大鸟？"
WEBBER.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "像妈妈一样煎。"

WEBBER.DESCRIBE.KYNO_CHICKEN_EGG_LARGE_CRACKED =
{
	GENERIC = "它在里面动呢！",
	HATCHING = "嗨，小鸡！出来吧！",
}

WEBBER.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "嘿嘿，就像是专门给鸡住的房子！",
	FULL = "哇！好多蛋啊！",
	BURNT = "啊……现在它们没家了。",
}

WEBBER.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "哇……好伤心。"

WEBBER.DESCRIBE.KYNO_COOKWARE_KIT = "里面有什么？"
WEBBER.DESCRIBE.KYNO_COOKWARE_SYRUP = "甜锅！"
WEBBER.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "甜锅！"
WEBBER.DESCRIBE.KYNO_COOKWARE_BIG_POT = "这个锅比另一个大一点。"
WEBBER.DESCRIBE.KYNO_COOKWARE_BIG = "这个锅比另一个大一点。"
WEBBER.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "你可以在里面做饭。"
WEBBER.DESCRIBE.KYNO_COOKWARE_SMALL = "你可以在里面做饭。"
WEBBER.DESCRIBE.KYNO_COOKWARE_GRILL = "我们做饭时必须小心。"
WEBBER.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "我们可以用它来制作美味的食物。"
WEBBER.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "我们应该烤什么？"
WEBBER.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "让我们找个地方放它。"
WEBBER.DESCRIBE.KYNO_COOKWARE_ELDER = "甜锅！"
WEBBER.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "我们必须进行设置。"
WEBBER.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "我们可以在里面做饭。"
WEBBER.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "它有点小。"
WEBBER.DESCRIBE.KYNO_COOKWARE_OVEN = "妈妈说我在烤箱周围要小心。"
WEBBER.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "妈妈说我在烤箱周围要小心。"
WEBBER.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "妈妈说我在烤箱周围要小心。"

WEBBER.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "这下面有什么呀？",
	FLIPPED = "哇！快看！",
}

WEBBER.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "泡泡糖。"

WEBBER.DESCRIBE.KYNO_SUGARFLY = "看看它，高兴地适应了。"
WEBBER.DESCRIBE.KYNO_SUGARFLYWINGS = "用糖蝴蝶骨头挑我们的牙齿。"

WEBBER.DESCRIBE.KYNO_WATERY_CRATE = "泡泡糖。"

WEBBER.DESCRIBE.KYNO_TUNACAN = "我们把开罐器忘在家里了。"
WEBBER.DESCRIBE.KYNO_TUNACAN_OPEN = "我们把开罐器忘在家里了。"

WEBBER.DESCRIBE.KYNO_CANNEDFOOD = "我们把开罐器忘在家里了。"
WEBBER.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "奇怪的气味。"

WEBBER.DESCRIBE.KYNO_POP = "今天是我们的生日吗！"

WEBBER.DESCRIBE.KYNO_MYSTERYMEAT = "真是一团糟。"

WEBBER.DESCRIBE.KYNO_BOTTLE_SOUL = "太悲伤了。"

WEBBER.DESCRIBE.SOULSTEW = "太悲伤了。"

WEBBER.DESCRIBE.FORTUNECOOKIE = "让我们看看我们的运气如何！"

WEBBER.DESCRIBE.HORNOCUPIA = "我们吃吧！"

WEBBER.DESCRIBE.CHEESE_YELLOW = "我喜欢奶酪，不知道他怎么样。"
WEBBER.DESCRIBE.CHEESE_WHITE = "我喜欢奶酪，不知道他怎么样。"
WEBBER.DESCRIBE.CHEESE_KOALEFANT = "我喜欢奶酪，不知道他怎么样。"

WEBBER.DESCRIBE.MILK_BOX = "我们总是会在早上喝一杯牛奶！"

WEBBER.DESCRIBE.WATERCUP = "妈妈总是说每天至少喝四杯水！"

WEBBER.DESCRIBE.HONEYJAR = "那个罐子里装满了蜂蜜！"

WEBBER.DESCRIBE.CRAB_ARTICHOKE = "晚餐准备好了！"

WEBBER.DESCRIBE.PEPPERROLLS = "对我们来说太热了！"

WEBBER.DESCRIBE.KYNO_SAPHEALER = "这是药？"

WEBBER.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "提醒我们要敬畏大海。",
	PICKED = "它们晚点会再来的。",
	BURNING = "嘿！住手！",
}

WEBBER.DESCRIBE.KYNO_GHOST_PIRATE = "普通海盗还不够可怕似的！"

WEBBER.DESCRIBE.KYNO_BUCKET_EMPTY = "我们过去每天都在家里打水桶。"
WEBBER.DESCRIBE.KYNO_BUCKET_METAL = "我们以前每天都要在家里使用水桶。"
WEBBER.DESCRIBE.KYNO_BUCKET_WATER = "我们可以在里面玩水！"

WEBBER.DESCRIBE.KYNO_MILK_BEEFALO = "一杯牛奶。"
WEBBER.DESCRIBE.KYNO_MILK_KOALEFANT = "一杯牛奶。"

WEBBER.DESCRIBE.KYNO_CAP_DRIED = "我们现在可以吃一些了！"

WEBBER.DESCRIBE.KYNO_PLANTMEAT_DRIED = "效果好于预期。"

WEBBER.DESCRIBE.KYNO_BREWBOOK = "现在我们永远不会忘记食谱！"

WEBBER.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "它也能做果汁吗？",
	BREWING_LONG = "还在工作呢。",
	BREWING_SHORT = "快好了！",
	DONE = "嘿，好了！",
	BURNT = "啊呜，没了。",
}

WEBBER.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "我们用这个做点泡菜吧！",
	BREWING_LONG = "还在工作呢。",
	BREWING_SHORT = "快好了！",
	DONE = "耶！好了！",
	BURNT = "啊……毁了。",
}

WEBBER.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "哇！看看它能装多少蜂蜜。",
	HONEY = "哇！好多蜂蜜！",
	NECTAR = "它们还在酿呢。",
	BURNING = "哦不！",
}

WEBBER.DESCRIBE.KYNO_NECTAR_POD = "蜘蛛不喜欢这个，但其他虫子喜欢！"

WEBBER.DESCRIBE.KYNO_OAKTREE_POD = "我们需要把它种在某个地方。"
WEBBER.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "好吃。"

WEBBER.DESCRIBE.KYNO_PIKO = "他是个忙碌的小家伙。"
WEBBER.DESCRIBE.KYNO_PIKO_ORANGE = "我想知道他是否喜欢茶会。"

WEBBER.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "嘿，树啊。",
	CHOPPED = "我们把叶子都拿到啦！",
	BURNING = "哦不！",
	BURNT = "没了……",
}

WEBBER.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "嘿，小松鼠们！",
	BURNING = "它们的家着火了！",
}

WEBBER.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "哇，一个板条箱。"

WEBBER.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "闻起来好腥啊。",
	BURNT = "它们的房子烧没了。",
}

WEBBER.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "我能进来吗？",
	CRAFTED = "嘿，现在看起来不错了！",
	BURNT = "呃！这味道更难闻了！",
}

WEBBER.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "看起来萨米现在有那个门的钥匙了。",
	OCCUPIED = "我觉得萨米睡着了。",
}

WEBBER.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "萨米喜欢展示他的货物。",
	EMPTY = "啊，啥都没了。",
}

WEBBER.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "很高兴再次见到你，萨米！"
WEBBER.DESCRIBE.KYNO_MEADOWISLAND_POND = "这就像一个鱼缸……没有鱼缸！"
WEBBER.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "那是一种口渴的植物。"
WEBBER.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "希望我们有桶和铲子。"
WEBBER.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "半人半兽。太奇怪了。"

WEBBER.DESCRIBE.KYNO_SAMMYHAT = "耶！我们以优惠的价格购得萨米的帽子！"

WEBBER.DESCRIBE.KINGFISHER = "对于这么小的鸟来说，它确实有一个大喙。"

WEBBER.DESCRIBE.TOUCAN = "你的喙多漂亮啊！"
WEBBER.DESCRIBE.TOUCAN_CHUBBY = "你的喙多漂亮啊！"

WEBBER.DESCRIBE.WETGOOP2 = "实验很有趣！"

WEBBER.DESCRIBE.BEER = "我们不应该喝那个。"

WEBBER.DESCRIBE.PALEALE = "我们不应该喝那个。"

WEBBER.DESCRIBE.TEAGREEN = "妈妈过去常常给我泡茶……至少我认为她是……"

WEBBER.DESCRIBE.TEARED = "妈妈过去常常给我泡茶……至少我认为她是……"

WEBBER.DESCRIBE.MEAD = "味道很有趣，哈哈。"

WEBBER.DESCRIBE.KYNO_JELLY = "呃……黏糊糊的手指。"

WEBBER.DESCRIBE.KYNO_MAYONNAISE = "梅奥！"

WEBBER.DESCRIBE.TARTARSAUCE = "呃……太苦了。"

WEBBER.DESCRIBE.KYNO_PICKLES = "妈妈总是说我们应该吃蔬菜！"

WEBBER.DESCRIBE.KYNO_WINE = "成人饮料。"

WEBBER.DESCRIBE.KYNO_JUICE = "没有什么比用别的东西喝果汁更好的了。"

WEBBER.DESCRIBE.KYNO_POISON_FROGLEGS = "我不确定这些能不能像这样吃。"
WEBBER.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "我想知道现在是不是所有的毒都从它们身上排出了。"

WEBBER.DESCRIBE.POISONFROGGLEBUNWICH = "三明治给我，青蛙腿给他。"

WEBBER.DESCRIBE.KYNO_BREWINGRECIPECARD = "我们看不懂它说的是什么！"

WEBBER.DESCRIBE.KYNO_OIL = "妈妈过去常常在厨房里好好利用它。"

WEBBER.DESCRIBE.BERRYSUNDAE = "我们梦想圣代。"

WEBBER.DESCRIBE.CHOCOLATE_BLACK = "巧克力棒！我们喜欢它！"
WEBBER.DESCRIBE.CHOCOLATE_WHITE = "巧克力棒！我们喜欢它！"

WEBBER.DESCRIBE.TRICOLORDANGO = "哦！我们还是第一次见到这种小吃。"
 
WEBBER.DESCRIBE.FRIESFRENCH = "松脆的！"

WEBBER.DESCRIBE.PIRATERUM = "我们不应该喝那个。"

WEBBER.DESCRIBE.TWISTEDTEQUILA = "这是注入了神秘力量的鸡尾酒！"

WEBBER.DESCRIBE.ONIONRINGS = "闻起来很香。我们喜欢它！"

WEBBER.DESCRIBE.DONUTS = "好吃！甜甜圈！"
WEBBER.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "好吃！甜甜圈！"
WEBBER.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "好吃！甜甜圈！"
 
WEBBER.DESCRIBE.CINNAMONROLL = "味道非常好，我们喜欢！"

WEBBER.DESCRIBE.GUMMYBEARGERS = "耶，小熊软糖！"

WEBBER.DESCRIBE.PRETZEL = "我们想知道它的味道如何。"

WEBBER.DESCRIBE.CORNINCUP = "杯子里有玉米！"

WEBBER.DESCRIBE.COTTONCANDY = "太棒了！"

WEBBER.DESCRIBE.ROASTEDHAZELNUTS = "我们不太喜欢它......"

WEBBER.DESCRIBE.MONSTERMUFFIN = "这个松饼闻起来很香！"

WEBBER.DESCRIBE.PINKCAKE = "一个巨大的蛋糕！等着我们吃！"

WEBBER.DESCRIBE.CHIPSBAG = "太脆了！"

WEBBER.DESCRIBE.LITTLEBREAD = "妈妈总是说面包可以搭配大多数食物。"

WEBBER.DESCRIBE.HOTHOUND = "热狗！"

WEBBER.DESCRIBE.MILKSHAKE = "哦！我们已经很久没有喝奶昔了。"
WEBBER.DESCRIBE.MILKSHAKE_PRISMATIC = "噢！我们已经很久没有喝奶昔了。"

WEBBER.DESCRIBE.NACHOS = "我们吃了它会弄得一团糟！"

WEBBER.DESCRIBE.BANANA_PUDDING = "我们想知道猴子是否也喜欢布丁。"

WEBBER.DESCRIBE.SEA_PUDDING = "臭，非常臭。"

WEBBER.DESCRIBE.TOM_KHA_SOUP = "妈妈总是说，多吃蔬菜。"

WEBBER.DESCRIBE.MINERTREAT = "我们喜欢它！"

WEBBER.DESCRIBE.RADISHSALAD = "每天五份。"

WEBBER.DESCRIBE.PUMPKIN_SOUP = "我们吃的时候会举起小指。"

WEBBER.DESCRIBE.ALGAE_SOUP = "我们吃的时候会举起小指。"

WEBBER.DESCRIBE.PARZNIP_SOUP = "我们吃的时候会举起小指。"

WEBBER.DESCRIBE.NETTLEMEATED = "这样更好吃。"

WEBBER.DESCRIBE.KYNO_SUGAR = "太棒了！"

WEBBER.DESCRIBE.KYNO_BOTTLECAP = "只是一个瓶盖。"

WEBBER.DESCRIBE.NUKACOLA = "苏打水！"
WEBBER.DESCRIBE.NUKACOLA_QUANTUM = "苏打水！"

WEBBER.DESCRIBE.LIVINGSANDWICH = "令人毛骨悚然！"

WEBBER.DESCRIBE.DURIANSPLIT = "我们梦想着分裂。"

WEBBER.DESCRIBE.DURIANSOUP = "有点像鸡肉面条。"

WEBBER.DESCRIBE.DURIANMEATED = "刺鼻。"

WEBBER.DESCRIBE.DURIANCHICKEN = "素火鸡！"

WEBBER.DESCRIBE.LUNARSOUP = "吃你的蔬菜，你的月球蔬菜……"

WEBBER.DESCRIBE.PURPLEWOBSTERSOUP = "我们以前从未见过这样的事情！"

WEBBER.DESCRIBE.WOBSTERMONSTER = "嗯嗯嗯嗯！"

WEBBER.DESCRIBE.SPIDERCAKE = "他不喜欢。"

WEBBER.DESCRIBE.SUGARBOMBS = "妈妈总是说那些不太健康。"

WEBBER.DESCRIBE.BERRYBOMBS = "粘手指……"

WEBBER.DESCRIBE.ONIGIRIS = "我们喜欢它！"

WEBBER.DESCRIBE.OMURICE = "我们不知道上面到底写了什么。"

WEBBER.DESCRIBE.PAELLA = "太好吃了！"

WEBBER.DESCRIBE.RISOTTO = "妈妈总是说，要吃蔬菜！"

WEBBER.DESCRIBE.RICESAKE = "唉。"

WEBBER.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "一棵菠萝灌木！"

WEBBER.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "菠萝！",
	PICKED = "现在没菠萝了。",
	WITHERED = "全枯了。",
	BURNING = "嘿！住手！",
}

WEBBER.DESCRIBE.KYNO_PINEAPPLE = "松果和苹果。"
WEBBER.DESCRIBE.KYNO_PINEAPPLE_HALVED = "松果和苹果!"
WEBBER.DESCRIBE.KYNO_PINEAPPLE_COOKED = "烫！烫！烫！"

WEBBER.DESCRIBE.PIZZA_TROPICAL = "反正我们喜欢！"

WEBBER.DESCRIBE.PINACOLADA = "我们已经能感受到海浪的气息！"

WEBBER.DESCRIBE.CHIMAS = "这很好！"

WEBBER.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "我们跑过去吧。",
	ON = "它在给所有东西浇水！",
}

WEBBER.DESCRIBE.KYNO_FOODSACK = "呃，又湿又软。"

WEBBER.DESCRIBE.GUMMYWORMS = "美味版的恶心蠕虫"

WEBBER.DESCRIBE.SMORES = "沃尔特告诉我们，这是童子军里常见的零食。"

WEBBER.DESCRIBE.NUKASHINE = "我们不喝那个！"

WEBBER.DESCRIBE.ANTSLOG = "虽然奇怪，但味道还可以。"

WEBBER.DESCRIBE.KYNO_WORM_BONE = "这些骨头有点锋利。"

WEBBER.DESCRIBE.SPOOKY_BRAIN_NOODLES = "呀！"
WEBBER.DESCRIBE.SPOOKY_BURGERZILLA = "必须面对我们的恐惧！"
WEBBER.DESCRIBE.SPOOKY_DEADBREAD = "好诡异！"
WEBBER.DESCRIBE.SPOOKY_JELLYBEANS = "吓人！"
WEBBER.DESCRIBE.SPOOKY_POPSICLE = "让我们想起森林的味道。"
WEBBER.DESCRIBE.SPOOKY_PUMPKINCREAM = "这种组合虽然奇怪，但味道还是不错的。"
WEBBER.DESCRIBE.SPOOKY_SKULLCANDY = "吓人的！"
WEBBER.DESCRIBE.SPOOKY_TACODILE = "味道不错！"

WEBBER.DESCRIBE.BUTTER_BEEFALO = "这和面包很配。"
WEBBER.DESCRIBE.BUTTER_GOAT = "看起来容光焕发！"
WEBBER.DESCRIBE.BUTTER_KOALEFANT = "讨厌。"

WEBBER.DESCRIBE.SPICE_CURE = "现在我们可以把零食留到以后吃了！"
WEBBER.DESCRIBE.SPICE_COLD = "制冷剂粉末!"
WEBBER.DESCRIBE.SPICE_FIRE = "热，热，热！"
WEBBER.DESCRIBE.SPICE_FED = "这种调料可能很有帮助。"
WEBBER.DESCRIBE.SPICE_MIND = "*打呵欠*吃零食的感觉很好。"

WEBBER.DESCRIBE.SUGARFLYMUFFIN = "你认识松饼蜘蛛吗？"

WEBBER.DESCRIBE.EELTACOS = "卷饼星期二！"

WEBBER.DESCRIBE.MEATSKILLET = "沃利总是做出最好的料理！"

WEBBER.DESCRIBE.MEATWALTZ = "食物就是食物！"

WEBBER.DESCRIBE.COMPLETEBREAKFAST = "噢！大量食物！"

WEBBER.DESCRIBE.DUMPLINGS = "它们非常美味！"

WEBBER.DESCRIBE.WARLYICEDTEA = "美味的"

WEBBER.DESCRIBE.WARLYTEA = "我们开个茶会吧！"

WEBBER.DESCRIBE.KYNO_TEALEAF = "请来一杯茶！"

WEBBER.DESCRIBE.KYNO_ITEMSLICER = "嗨，嗨！"
WEBBER.DESCRIBE.KYNO_ITEMSLICER_GOLD = "嗨，嗨！"

WEBBER.DESCRIBE.COXINHA = "很好吃！"

WEBBER.DESCRIBE.LAZYDESSERT = "哦，哦，哦！也许我们应该试着把它给蚁狮。"

WEBBER.DESCRIBE.CRABKINGFEAST = "如果它能放进锅里，那么它就能放进我们的嘴里！"

WEBBER.DESCRIBE.PIENAPPLE = "我们已经能感觉到它有多酸了！"

WEBBER.DESCRIBE.JAWSBREAKER = "哎呀，但我们想吃它啊！"

WEBBER.DESCRIBE.AVOCADOTOAST = "我们喜欢鳄梨！"

WEBBER.DESCRIBE.RICEPUDDING = "不错。"

WEBBER.DESCRIBE.SHARKSUSHI = "我们等不及要吃了!"

WEBBER.DESCRIBE.WOBSTERBREADED = "酥脆的。"

WEBBER.DESCRIBE.LAZYPURRITO = "哇，真可爱。"

WEBBER.DESCRIBE.HORCHATA = "呼, 太冷了！"

WEBBER.DESCRIBE.WOBSTERCOCKTAIL = "我们想知道这需要花多少钱。"

WEBBER.DESCRIBE.LAVAEEGGBOILED = "哎呀，真热！"

WEBBER.DESCRIBE.POMEGRANATETEA = "美味的！"

WEBBER.DESCRIBE.TIRAMISU = "耶！"

WEBBER.DESCRIBE.TOADSTOOLCOLA = "T感觉有点奇怪。"

WEBBER.DESCRIBE.TEPACHE = "太好了！"

WEBBER.DESCRIBE.LUNARTEQUILA = "太强大了！"

WEBBER.DESCRIBE.MIMICMOSA = "它能帮助我们偷偷摸摸地行动！"

WEBBER.DESCRIBE.POMEGRANATEPIE = "我们喜欢烤派！"

WEBBER.DESCRIBE.PINEAPPLECAKE = "我们喜欢蛋糕！"

WEBBER.DESCRIBE.PASTY_MEAT = "它几乎就是一个饺子。"
WEBBER.DESCRIBE.PASTY_CHEESE = "它几乎就是一个饺子。"

WEBBER.DESCRIBE.BRIGADEIRO = "里面是纯正的巧克力！"

WEBBER.DESCRIBE.REGULARLASAGNA = "嗯!"

WEBBER.DESCRIBE.FLTSANDWICH = "可怜的青蛙。"

WEBBER.DESCRIBE.RICEANDBEANS = "妈妈总是说：多吃蔬菜！"

WEBBER.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "现在看起来空空的……但我们2026年再回来看看！"

WEBBER.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "我们发现藏起来的蘑菇了！能摘吗？",
	PICKED = "我们还想吃！",
	BURNING = "啊，我们还没吃呢！",
}

WEBBER.DESCRIBE.KYNO_TRUFFLES = "看起来很好吃！我们能吃吗？"
WEBBER.DESCRIBE.KYNO_TRUFFLES_COOKED = "烤得香喷喷的！"

WEBBER.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "我们可以把零食展示给大家看！",
	FULL = "哇！快看我们做的东西！",
}

WEBBER.DESCRIBE.KYNO_SPORECAP = "它看起来好难过……可怜的小蘑菇。"
WEBBER.DESCRIBE.KYNO_SPORECAP_COOKED = "闻起来稍微好一点了！"

WEBBER.DESCRIBE.KYNO_SPORECAP_DARK = "光看着它我们就觉得难受。"
WEBBER.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "我们还是不吃！"

WEBBER.DESCRIBE.KYNO_GOLDENAPPLE = "闪闪发光的苹果！"

WEBBER.DESCRIBE.TRUFFLESGRINDER = "我们从没吃过这样的三明治！"

WEBBER.DESCRIBE.SPORECAPPIE = "我们最好别吃那个……对吧？"

WEBBER.DESCRIBE.SPORECAP_SKEWERS = "我们做了蘑菇串！好吃！"

WEBBER.DESCRIBE.TRUFFLEOIL = "闻起来怪怪的……但好像也有点香！"

WEBBER.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "我们应该建造这个。"
WEBBER.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "我们要养好多好多小鱼朋友！"

WEBBER.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "快看！我们可以把鱼养在这里！",
	FUEL_HIGH = "它们吃得好饱！",
	FUEL_MED = "还在吃呢。",
	FUEL_LOW = "快没食物了！",
	EMPTY = "唔哦，没食物了。",
}

WEBBER.DESCRIBE.KYNO_ANTCHOVY = "我们无法判断它属于陆地还是水生生物！"
WEBBER.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "它们无处不在！扭来扭去！"

WEBBER.DESCRIBE.AGEDROE = "真时髦！"
WEBBER.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "它们好小啊！我们真的能吃这些吗？"

WEBBER.DESCRIBE.KYNO_SWORDFISH_BLUE = "哎呀……他现在好像被这片浩瀚的大海吓到了呢！"

WEBBER.DESCRIBE.KYNO_JELLYFISH = "那个黏糊糊的东西活着！"
WEBBER.DESCRIBE.KYNO_JELLYFISH_DEAD = "它既不是果冻也不是鱼。它也不是活物。"
WEBBER.DESCRIBE.KYNO_JELLYFISH_COOKED = "我们原以为它会更...扎实些。"
WEBBER.DESCRIBE.KYNO_JELLYFISH_DRIED = "我们什么都愿意尝试一次。"

WEBBER.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "你看起来真漂亮！"
WEBBER.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "抱歉啦，小鱼。"
WEBBER.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "我们喜欢色彩鲜艳的食物！"

WEBBER.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "我们希望它装满汽水。"

WEBBER.DESCRIBE.KYNO_OCEANTRAP = "东西游进来。晚餐端出来。"

WEBBER.DESCRIBE.OCEANFISH_PUFFERFISH = "哎哟！我们可不想抱那个家伙。"
WEBBER.DESCRIBE.OCEANFISH_STURGEON = "它看起来好老啊！说不定知道不少渔夫的故事呢！"

WEBBER.DESCRIBE.KYNO_SWORDFISH = "我们喜欢你的剑脸，鱼！"
WEBBER.DESCRIBE.KYNO_SWORDFISH_DEAD = "我们该吃掉它还是用掉它？"

WEBBER.DESCRIBE.SWORDFISHFEAST = "切得真整齐！谢谢你，厨师！"

WEBBER.DESCRIBE.KYNO_DOGFISH = "嘿，你这家伙肉可真多啊！"
WEBBER.DESCRIBE.KYNO_DOGFISH_DEAD = "狗鱼都能上天堂，对吧？"

WEBBER.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "现在对谁都没用了。"

WEBBER.DESCRIBE.WOBSTER_MONKEYISLAND = "哇！它闪闪发亮！"
WEBBER.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "哎呀……它不再闪闪发亮了。"
WEBBER.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "我们为它感到难过……但同时也有些饿了。"

WEBBER.DESCRIBE.KYNO_PUFFERMONSTER = "他有点可爱……但带着点笨拙又刻薄的感觉！"

WEBBER.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "那些人从哪头过来的？"
WEBBER.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "打起精神来，大块头！"
WEBBER.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "他的双眼燃烧着仇恨！"
WEBBER.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "哦！它要爆炸啦！"

WEBBER.DESCRIBE.KYNO_BLUBBER = "胖乎乎的，很开心。"

WEBBER.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "嚼劲十足！就像鱼味口香糖！"
WEBBER.DESCRIBE.KYNO_FISHMEAT_DRIED = "嗯，嚼劲十足的鱼干！"

WEBBER.DESCRIBE.MONKEYISLANDMEAL = "香蕉和龙虾！我们原以为行不通，结果居然成功了！"

WEBBER.DESCRIBE.KYNO_BRAINROCK_LARVAE = "哎呀，你好呀。"
WEBBER.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "它很快就会长出毛发。"
WEBBER.DESCRIBE.KYNO_BRAINROCK_CORAL = "美味的头部肉！"

WEBBER.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "我想戳它，但又怕我们的手会被夹住。",
	PICKED = "它现在睡着了。",
}

WEBBER.DESCRIBE.BRAINMETTERSOUP = "就像妈妈以前给我们做的那个！"

WEBBER.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "它看起来挺友好的。",
	SLEEPING = "我觉得我们不该吵醒他。",
}

WEBBER.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "让我们看看里面吧！"

WEBBER.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "我们想知道这是什么？",
	WAITING = "他曾是我们的新朋友。",
}

WEBBER.DESCRIBE.KYNO_PACKIMBAGGIMS = "你好呀，大嘴巴的朋友！"

WEBBER.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "咱们最好赶紧开始烤了！"
WEBBER.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "我们没想到烘焙会这么有趣！"
WEBBER.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "哇！好大一块！能给我们切一块吗？！"
WEBBER.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "我们应该许个愿！"
WEBBER.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "它使我们充满平安与喜乐！"
WEBBER.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "太棒了！我们爱蛋糕！"
WEBBER.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "我们喜欢气球！"

WEBBER.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "好吃，我们一起做爆米花吧！",
	FUEL_HIGH = "好多好多爆米花！",
	FUEL_MED = "还在工作呢！",
	FUEL_LOW = "快没燃料了！",
	EMPTY = "没燃料了……",
}

WEBBER.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "它在我们嘴里噗噗地蹦！真有趣！"
WEBBER.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "我们喜欢派对帽！"
WEBBER.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "专为萨米准备的！"

WEBBER.DESCRIBE.KYNO_FISHREGISTRYHAT = "我们可以用它学到所有关于鱼的事！"

WEBBER.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "动物们会从这里吃东西！",
	FUEL_HIGH = "哇！好多食物！",
	FUEL_MED = "还剩一些。",
	FUEL_LOW = "快空了！",
	EMPTY = "唔哦，没食物了！",
	BURNT = "全烧光了！",
}

WEBBER.DESCRIBE.CHICKENNUGGETS = "我们喜欢这个！一口一个！"

WEBBER.DESCRIBE.CHICKENWINGS = "辣！辣！辣！"

WEBBER.DESCRIBE.CHICKENBURGER = "我们喜欢汉堡！这个是咯咯叫的汉堡！"

WEBBER.DESCRIBE.CHICKENEGGSOUP = "像一碗暖暖的拥抱！"

WEBBER.DESCRIBE.CHICKENEGGSTEW = "闻起来真香！"

WEBBER.DESCRIBE.CHICKENROTISSERIE = "它在转！闻起来太香了！"