local WALTER = STRINGS.CHARACTERS.WALTER

WALTER.ANNOUNCE_KYNO_COFFEEBUFF_START = "我们开始吧！"
WALTER.ANNOUNCE_KYNO_COFFEEBUFF_END = "等等我，沃比！我现在太慢了！"

WALTER.ANNOUNCE_KYNO_HASTEBUFF_START = "让我们看看你能不能跟上，沃比！"
WALTER.ANNOUNCE_KYNO_HASTEBUFF_END = "好的，让我们休息一下。"

WALTER.ANNOUNCE_KYNO_POPBUFF_START = "（嗝！）我敢打赌你不会像我一样吵闹！"
WALTER.ANNOUNCE_KYNO_POPBUFF_END = "那是多么疯狂的饮料！"

WALTER.ANNOUNCE_KYNO_FROGBUFF_START = "我们看起来够像青蛙吗，沃比？"
WALTER.ANNOUNCE_KYNO_FROGBUFF_END = "我想恢复正常了，沃比！"

WALTER.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝!) 沃比，我打赌你的噪音肯定比不上我！"
WALTER.ANNOUNCE_KYNO_PIRATEBUFF_END = "这是多么疯狂的饮料啊!"

WALTER.ANNOUNCE_KYNO_FREEZEBUFF_START = "是时候来一场打雪仗了！"
WALTER.ANNOUNCE_KYNO_FREEZEBUFF_END = "还有......它不见了。"

WALTER.ANNOUNCE_KYNO_FIREBUFF_START = "在燃烧！"
WALTER.ANNOUNCE_KYNO_FIREBUFF_END = "还有......他们走了。"

WALTER.ANNOUNCE_KYNO_FISHINGBUFF_START = "钓鱼和愤怒！"
WALTER.ANNOUNCE_KYNO_FISHINGBUFF_END = "我们现在必须有耐心地钓鱼了。"

WALTER.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "是时候放松一会儿了。"
WALTER.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "好了，沃比，我的思绪又回到了正轨。"

WALTER.ANNOUNCE_KYNO_EATERBUFF_START = "帮助我吃更多的食物。"
WALTER.ANNOUNCE_KYNO_EATERBUFF_END = "吃饭的时候要有耐心。"

WALTER.ANNOUNCE_KYNO_WORMBUFF_START = "猎虫开始了！"
WALTER.ANNOUNCE_KYNO_WORMBUFF_END = "狩猎结束了，沃比。"

WALTER.ANNOUNCE_KYNO_CRABBUFF_START = "螃蟹狩猎开始了！"
WALTER.ANNOUNCE_KYNO_CRABBUFF_END = "狩猎结束了，沃比。"

WALTER.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝！) 我希望你不能像我一样吵闹，沃比！"
WALTER.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "那是多么疯狂的青蛙饮料啊！"

WALTER.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "别害怕，沃比。"
WALTER.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "噢，它已经走了？"

WALTER.ANNOUNCE_KYNO_STEALTHBUFF_START = "嘘！现在安静，沃比！"
WALTER.ANNOUNCE_KYNO_STEALTHBUFF_END = "我的隐身不见了！"

WALTER.ANNOUNCE_KYNO_FEARBUFF_START = "我已经无所畏惧了！"
WALTER.ANNOUNCE_KYNO_FEARBUFF_END = "我仍然没有任何恐惧。"

WALTER.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "现在没有什么能阻止我了！"
WALTER.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "啊，我的超能力没了。"

WALTER.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "猪朋友！冒险伙伴！"
WALTER.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "我的猪朋友消失了。"

WALTER.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "幸好我带了……呃，隐形雨衣！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WALTER.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "连蛇咬都阻止不了我了！"
WALTER.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "看来又要执行危险任务了！"

WALTER.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "哇！我觉得我的大脑刚刚升级了！"
WALTER.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "看来我又恢复正常思维了。没关系！"

WALTER.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "看吧，沃比？蜜蜂现在一点都不可怕了！"
WALTER.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "看来蜜蜂不再那么友好了。"

WALTER.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "比以往更强大！对吧，沃比？"
WALTER.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "看来加力效果已经消退..."

WALTER.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "太棒了！额外的口粮容量！"
WALTER.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "我们又回到了常规限制！"

WALTER.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "头脑清醒最适合侦察！"
WALTER.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "喂！我当时可是头脑清醒的！"

WALTER.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "我现在感觉安全多了。"
WALTER.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "看来我不能再指望它了。"

WALTER.ANNOUNCE_KYNO_BERSERKERBUFF_START = "哇！我觉得自己无所畏惧！也许是太无所畏惧了..."
WALTER.ANNOUNCE_KYNO_BERSERKERBUFF_END = "好，深呼吸。恢复正常。"

WALTER.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "酷！不吃东西也能撑更久了！"
WALTER.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "看来又是吃零食的时间了。"

WALTER.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "做错了！"

WALTER.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "嗯，不是这个。"

WALTER.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "回到营地后，他们说只有高大的树木才适合做这个！"

WALTER.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "此处不适用。"

WALTER.ANNOUNCE_KYNO_POTHANGER_FAIL = "我们需要一个锅来煮它。"

WALTER.ANNOUNCE_KYNO_CASSEROLE_FAIL = "它还需要一些其他的东西。"

WALTER.ANNOUNCE_KYNO_SAPHEALER_USED = "搞定啦，大树！给你修补好了。"

WALTER.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "露营守则第12条：永远尊重你猎取的食物。"

WALTER.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "真倒霉。我还指望能有点意思呢。"

WALTER.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "该死，迷路了……童子军会失望的。"
WALTER.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "连侦察兵在这天气里都无法追踪。"
WALTER.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "沃比，你听见了吗？有客人来了！"

WALTER.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "蛋糕完成啦！这绝对会是史上最棒的庆祝活动！"

WALTER.ANNOUNCE_KYNO_FISH_RESEARCHED = "太酷了！我学到了好多关于这条鱼的事。"
WALTER.ANNOUNCE_KYNO_ROE_RESEARCHED = "看来我更懂鱼卵了。"

WALTER.DESCRIBE.KYNO_ROE = "我第一次看到其中一个。"
WALTER.DESCRIBE.KYNO_ROE_COOKED = "我烤了它们，呵呵。"

WALTER.DESCRIBE.KYNO_SHARK_FIN = "我还是想念鲨鱼！"

WALTER.DESCRIBE.KYNO_BEANBUGS = "啊，是的，这是一种非常常见的错误。"
WALTER.DESCRIBE.KYNO_BEANBUGS_COOKED = "好吧，它现在已经死了......"

WALTER.DESCRIBE.KYNO_GUMMYBUG = "这个非常罕见！"
WALTER.DESCRIBE.KYNO_GUMMYBUG_COOKED = "对不起，小家伙。"

WALTER.DESCRIBE.KYNO_WHEAT = "小麦！"
WALTER.DESCRIBE.KYNO_WHEAT_COOKED = "烤熟的小麦！"

WALTER.DESCRIBE.KYNO_FLOUR = "啊……让我想起了爸爸的面包店。"

WALTER.DESCRIBE.KYNO_SPOTSPICE = "给我的饭菜调味。"

WALTER.DESCRIBE.KYNO_SAP = "想要一点，沃比？"
WALTER.DESCRIBE.KYNO_SAP_SPOILED = "现在没法食用了。"

WALTER.DESCRIBE.KYNO_SYRUP = "太甜了！"

WALTER.DESCRIBE.KYNO_COFFEEBEANS = "可以放进锅里。"
WALTER.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "让我们准备它们，沃比！"

WALTER.DESCRIBE.DUG_KYNO_COFFEEBUSH = "这是一棵咖啡丛，我简直不敢相信！"

WALTER.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "闻起来有点冲。",
	PICKED = "它们很快就会长回来的。",
	WITHERED = "需要施肥了。",
}

WALTER.DESCRIBE.DUG_KYNO_SPOTBUSH = "我们得把它再种回去，对吧沃比？"

WALTER.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "只是一棵灌木而已。",
	PICKED = "猜猜它还会长回来的。",
	BURNING = "哇！糟透了！",
}

WALTER.DESCRIBE.KYNO_SPOTSPICE_LEAF = "嗯。我可以用这个来调味。"

WALTER.DESCRIBE.KYNO_MUSSEL = "吃生海鲜是一种冒险。"
WALTER.DESCRIBE.KYNO_MUSSEL_COOKED = "来自大海的小点心。"

WALTER.DESCRIBE.KYNO_HUMANMEAT = "肉即是肉。"
WALTER.DESCRIBE.KYNO_HUMANMEAT_COOKED = "太可怕了。"
WALTER.DESCRIBE.KYNO_HUMANMEAT_DRIED = "让它变干就不会来自人类，对吧？"

WALTER.DESCRIBE.COFFEE = "现在就是冒险的最佳时刻。"

WALTER.DESCRIBE.BISQUE = "我喜欢汤。"

WALTER.DESCRIBE.JELLYOPOP = "一根棒棒糖！"

WALTER.DESCRIBE.SHARKFINSOUP = "我喜欢汤。"

WALTER.DESCRIBE.TROPICALBOUILLABAISSE = "鱼汤，不错！"

WALTER.DESCRIBE.MUSSELBOUILLABAISE = "海鲜。"

WALTER.DESCRIBE.SWEETPOTATOSOUFFLE = "我的最爱之一。"

WALTER.DESCRIBE.FEIJOADA = "真正的童子军餐！"

WALTER.DESCRIBE.GUMMY_CAKE = "这是一个虫子蛋糕！"

WALTER.DESCRIBE.HARDSHELL_TACOS = "很脆很辣。"

WALTER.DESCRIBE.ICEDTEA = "放松和提神。"

WALTER.DESCRIBE.NETTLELOSANGE = "治疗只比疾病好一点。"

WALTER.DESCRIBE.SNAKEBONESOUP = "我喜欢汤。"

WALTER.DESCRIBE.STEAMEDHAMSANDWICH = "我喜欢它！"

WALTER.DESCRIBE.TEA = "我曾经参加过茶话会。"

WALTER.DESCRIBE.BUBBLETEA = "放松和提神。"

WALTER.DESCRIBE.FRENCHONIONSOUP = "我喜欢汤。"

WALTER.DESCRIBE.SLAW = "蔬菜。"

WALTER.DESCRIBE.LOTUSBOWL = "由大自然制成。"

WALTER.DESCRIBE.POI = "以前从未吃过。"

WALTER.DESCRIBE.JELLYBEAN_HUNGER = "软糖是给小孩子吃的......"
WALTER.DESCRIBE.JELLYBEAN_SUPER = "软糖是给小孩子吃的……"
WALTER.DESCRIBE.JELLYBEAN_SANITY = "软糖是给小孩子吃的……"

WALTER.DESCRIBE.BOWLOFGEARS = "一堆齿轮。"

WALTER.DESCRIBE.LONGPIGMEAL = "肉即肉。"

WALTER.DESCRIBE.CUCUMBERSALAD = "即使是黄瓜也可以成为荒野中的食物！"

WALTER.DESCRIBE.DUG_KYNO_WILDWHEAT = "我可以把它种在更好的地方。"

WALTER.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "一片小麦植株。",
	PICKED = "它最终还会长出谷粒来的。",
	WITHERED = "看起来干透了。",
	BURNING = "哇！糟透了！",
}

WALTER.DESCRIBE.KYNO_MEALGRINDER = "嗯……我今天应该磨什么？"

WALTER.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "这还挺酷的嘛！",
	PICKED = "估计它们还会长回来的。",
	BURNING = "哇！糟透了！",
}

WALTER.DESCRIBE.GORGE_BREAD = "想要一块吗，沃比？"
WALTER.DESCRIBE.GORGE_SWEET_CHIPS = "来点吧，沃比。"
WALTER.DESCRIBE.GORGE_VEGETABLE_SOUP = "吃你的蔬菜！"
WALTER.DESCRIBE.GORGE_JELLY_SANDWICH = "好吃！"
WALTER.DESCRIBE.GORGE_FISH_STEW = "太饱了！"
WALTER.DESCRIBE.GORGE_MEAT_STEW = "好吃！"
WALTER.DESCRIBE.GORGE_ONION_CAKE = "嗯，味道不错，但我更喜欢甜的！"
WALTER.DESCRIBE.GORGE_POTATO_PANCAKES = "非常有品位。"
WALTER.DESCRIBE.GORGE_POTATO_SOUP = "我喜欢喝汤。"
WALTER.DESCRIBE.GORGE_FISHBALL_SKEWERS = "这些鱼丸非常美味！"
WALTER.DESCRIBE.GORGE_MEAT_SKEWERS = "这些小肉块非常美味！"
WALTER.DESCRIBE.GORGE_STONE_SOUP = "我喜欢喝汤。"
WALTER.DESCRIBE.GORGE_CROQUETTE = "炸丸子不错。"
WALTER.DESCRIBE.GORGE_ROAST_VEGETABLES = "健康餐！"
WALTER.DESCRIBE.GORGE_MEATLOAF = "你想来一块吗，沃比？"
WALTER.DESCRIBE.GORGE_CARROT_SOUP = "我喜欢喝汤。"
WALTER.DESCRIBE.GORGE_FISHPIE = "我可以改良一下这个派。"
WALTER.DESCRIBE.GORGE_FISHCHIPS = "太脆了！"
WALTER.DESCRIBE.GORGE_MEATPIE = "厚重的馅饼。"
WALTER.DESCRIBE.GORGE_SLIDERS = "我们得多做点了，沃比。"
WALTER.DESCRIBE.GORGE_JELLY_ROLL = "要果冻吗，沃比？"
WALTER.DESCRIBE.GORGE_CARROT_CAKE = "我给你切一块，沃比。"
WALTER.DESCRIBE.GORGE_GARLICMASHED = "我们快吃吧。"
WALTER.DESCRIBE.GORGE_GARLICBREAD = "美味可口。"
WALTER.DESCRIBE.GORGE_TOMATO_SOUP = "我喜欢喝汤。"
WALTER.DESCRIBE.GORGE_SAUSAGE = "这个给你，沃比。"
WALTER.DESCRIBE.GORGE_CANDIEDFISH = "甜甜的鱼。"
WALTER.DESCRIBE.GORGE_STUFFEDMUSHROOM = "健康餐。"
WALTER.DESCRIBE.GORGE_BRUSCHETTA = "漂亮的滑杆。"
WALTER.DESCRIBE.GORGE_HAMBURGER = "酷！一个汉堡包。"
WALTER.DESCRIBE.GORGE_FISHBURGER = "酷！一个带鱼的汉堡包。"
WALTER.DESCRIBE.GORGE_MUSHROOMBURGER = "酷！一个蘑菇汉堡。"
WALTER.DESCRIBE.GORGE_FISH_STEAK = "太饱了！"
WALTER.DESCRIBE.GORGE_CURRY = "肉和一些蔬菜搭配在一起。"
WALTER.DESCRIBE.GORGE_SPAGHETTI = "啊，意大利面！"
WALTER.DESCRIBE.GORGE_POACHEDFISH = "纹理做得非常好。"
WALTER.DESCRIBE.GORGE_SHEPHERD_PIE = "我希望羊群不要来找我们。"
WALTER.DESCRIBE.GORGE_CANDY = "不要吃太多，否则你会胃痛。"
WALTER.DESCRIBE.GORGE_BREAD_PUDDING = "非常美味。"
WALTER.DESCRIBE.GORGE_BERRY_TART = "一道不错的浆果菜。"
WALTER.DESCRIBE.GORGE_MACARONI = "不错！"
WALTER.DESCRIBE.GORGE_BAGEL_AND_FISH = "闻起来不错，你觉得呢，沃比？"
WALTER.DESCRIBE.GORGE_GRILLED_CHEESE = "融化的奶酪让我口渴难耐。"
WALTER.DESCRIBE.GORGE_CREAMMUSHROOM = "营养汤！"
WALTER.DESCRIBE.GORGE_MANICOTTI = "上好的通心粉里有上好的奶酪。"
WALTER.DESCRIBE.GORGE_CHEESEBURGER = "酷！一个带鱼的汉堡包。"
WALTER.DESCRIBE.GORGE_FETTUCCINE = "好!"
WALTER.DESCRIBE.GORGE_ONION_SOUP = "哦，我希望这股味道不会持续太久。"
WALTER.DESCRIBE.GORGE_BREADED_CUTLET = "来一口吧，沃比"
WALTER.DESCRIBE.GORGE_CREAMY_FISH = "来，咬一口，沃比。"
WALTER.DESCRIBE.GORGE_PIZZA = "啊哈！即使在这里我们也有披萨！"
WALTER.DESCRIBE.GORGE_POT_ROAST = "帮我一把，沃比。"
WALTER.DESCRIBE.GORGE_CRAB_CAKE = "下次，我会做一些像你的东西，沃比。"
WALTER.DESCRIBE.GORGE_STEAK_FRITES = "薯条不能吃太多"
WALTER.DESCRIBE.GORGE_SHOOTER_SANDWICH = "做工精细的牛肉三明治。"
WALTER.DESCRIBE.GORGE_BACON_WRAPPED = "一顿简单的早餐。"
WALTER.DESCRIBE.GORGE_CRAB_ROLL = "美味的螃蟹！"
WALTER.DESCRIBE.GORGE_MEAT_WELLINGTON = "烹饪得很好。"
WALTER.DESCRIBE.GORGE_CRAB_RAVIOLI = "精彩的螃蟹!"
WALTER.DESCRIBE.GORGE_CARAMEL_CUBE = "我猜你想要一些，沃比？"
WALTER.DESCRIBE.GORGE_SCONE = "我喜欢！"
WALTER.DESCRIBE.GORGE_TRIFLE = "我喜欢！"
WALTER.DESCRIBE.GORGE_CHEESECAKE = "不要再浪费时间了!"

WALTER.DESCRIBE.DUCKYOUGLERMZ = "臭臭的。"

WALTER.DESCRIBE.KYNO_ALOE = "低价药。"
WALTER.DESCRIBE.KYNO_ALOE_COOKED = "我烤了一些药。"
WALTER.DESCRIBE.KYNO_ALOE_GROUND = "低价药。"
WALTER.DESCRIBE.KYNO_ALOE_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.FARM_PLANT_KYNO_ALOE = "低成本药品。"
WALTER.DESCRIBE.KYNO_ALOE_OVERSIZED = "低成本药品。"
WALTER.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "不能吃了。"

WALTER.DESCRIBE.KYNO_CUCUMBER = "海怪。很明显。"
WALTER.DESCRIBE.KYNO_CUCUMBER_COOKED = "它是……黏糊糊的。"
WALTER.DESCRIBE.KYNO_CUCUMBER_GROUND = "海怪。很明显。"
WALTER.DESCRIBE.KYNO_CUCUMBER_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "海怪。很明显。"
WALTER.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "海怪。很明显。"
WALTER.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "海怪。很明显。"

WALTER.DESCRIBE.KYNO_RADISH = "从地里长出来的小植物。"
WALTER.DESCRIBE.KYNO_RADISH_COOKED = "辣！我喜欢！"
WALTER.DESCRIBE.KYNO_RADISH_GROUND = "从地里长出来的小植物。"
WALTER.DESCRIBE.KYNO_RADISH_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.FARM_PLANT_KYNO_RADISH = "从地里长出来的小植物。"
WALTER.DESCRIBE.KYNO_RADISH_OVERSIZED = "从地里长出来的小植物。"
WALTER.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "不能吃了。"

WALTER.DESCRIBE.KYNO_FENNEL = "嗯……"
WALTER.DESCRIBE.KYNO_FENNEL_COOKED = "热！热！"
WALTER.DESCRIBE.KYNO_FENNEL_GROUND = "嗯……"
WALTER.DESCRIBE.KYNO_FENNEL_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "嗯..."
WALTER.DESCRIBE.KYNO_FENNEL_OVERSIZED = "嗯..."
WALTER.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "不能吃了。"

WALTER.DESCRIBE.KYNO_SWEETPOTATO = "比普通土豆甜十倍。"
WALTER.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "我可以吃一整天。"
WALTER.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "比普通土豆甜十倍。"
WALTER.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "比普通土豆甜十倍。"
WALTER.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "比普通土豆甜十倍。"
WALTER.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "不能吃了。"

WALTER.DESCRIBE.KYNO_PARZNIP = "当它不是一只老鼠时，我有点失望。"
WALTER.DESCRIBE.KYNO_PARZNIP_COOKED = "当它不是一只老鼠时，我有点失望。"
WALTER.DESCRIBE.KYNO_PARZNIP_EATEN = "当它不是一只老鼠时，我有点失望。"
WALTER.DESCRIBE.KYNO_PARZNIP_GROUND = "当它不是一只老鼠时，我有点失望。"
WALTER.DESCRIBE.KYNO_PARZNIP_BIG = "看看这个，沃比！"
WALTER.DESCRIBE.KYNO_PARZNIP_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "当它不是一只老鼠时，我有点失望。"
WALTER.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "当它不是一只老鼠时，我有点失望。"
WALTER.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "不能吃了。"

WALTER.DESCRIBE.KYNO_TURNIP = "我可以用这种蔬菜做点什么。"
WALTER.DESCRIBE.KYNO_TURNIP_COOKED = "事实证明，它真的很有品味。"
WALTER.DESCRIBE.KYNO_TURNIP_GROUND = "我可以用这种蔬菜做点什么。"
WALTER.DESCRIBE.KYNO_TURNIP_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "我可以用这种蔬菜做点什么。"
WALTER.DESCRIBE.KYNO_TURNIP_OVERSIZED = "我可以用这种蔬菜做点什么。"
WALTER.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "不能吃了。"

WALTER.DESCRIBE.KYNO_RICE = "健康简单。"
WALTER.DESCRIBE.KYNO_RICE_COOKED = "健康简单。"
WALTER.DESCRIBE.KYNO_RICE_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "是的，那些是种子！"
WALTER.DESCRIBE.FARM_PLANT_KYNO_RICE = "我可以用这种蔬菜做点什么。"
WALTER.DESCRIBE.KYNO_RICE_OVERSIZED = "我可以用这种蔬菜做点什么。"
WALTER.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "不能吃了。"

WALTER.DESCRIBE.KYNO_SEEDS_KIT = "打开包装！"

WALTER.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "那块石头上粘着些海洋生物。而且它们能吃！",
	PICKED = "它们之后还会长出来的。",
	WITHERED = "这里啥也不剩了。",
}

WALTER.DESCRIBE.KYNO_LIMPETS = "嗯……岩石上的食物。美食。"
WALTER.DESCRIBE.KYNO_LIMPETS_COOKED = "我听说最好的食物来自岩石。"

WALTER.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "一种水生花卉，看着挺不错。",
	PICKED = "猜猜它还会长回来的。",
	BURNING = "嘿！这样可不行！",
}

WALTER.DESCRIBE.KYNO_LOTUS_ROOT = "这需要被种植。"
WALTER.DESCRIBE.KYNO_LOTUS_FLOWER = "嗯！"
WALTER.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "整洁！"

WALTER.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "湿漉漉、软趴趴的杂草。",
	PICKED = "它们应该还会长回来吧，我觉得。",
	BURNING = "那玩意儿是怎么烧起来的？！",
}

WALTER.DESCRIBE.KYNO_SEAWEEDS = "湿漉漉的杂草。"
WALTER.DESCRIBE.KYNO_SEAWEEDS_COOKED = "一大堆美味的……食物？"
WALTER.DESCRIBE.KYNO_SEAWEEDS_DRIED = "也许我可以用它做一架纸飞机。"
WALTER.DESCRIBE.KYNO_SEAWEEDS_ROOT = "这需要种植。"

WALTER.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "也许我可以吃那个……",
	PICKED = "水能帮助它长得更快。",
	BURNING = "哦不！",
}

WALTER.DESCRIBE.KYNO_TAROROOT_ROOT = "这需要被种植。"
WALTER.DESCRIBE.KYNO_TAROROOT = "即使在荒野，你也必须吃蔬菜。"
WALTER.DESCRIBE.KYNO_TAROROOT_COOKED = "哦，烤熟了好多了！"

WALTER.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "这儿海里也能长植物？",
	PICKED = "希望它快点长回来。",
	BURNING = "哇……真没想到。",
}

WALTER.DESCRIBE.KYNO_WATERYCRESS_ROOT = "这需要被种植。"
WALTER.DESCRIBE.KYNO_WATERYCRESS = "卷心菜，但在这里？"

WALTER.DESCRIBE.WATERYCRESSBOWL = "含水蔬菜。嗯嗯...嗯嗯！"

WALTER.DESCRIBE.KYNO_SALT = "嘿，我想是盐！"

WALTER.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "这是获取食物的巧妙方法。",
	PICKED = "我们得等等，沃比。",
	BURNING = "嗯，糟透了。",
}

WALTER.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "我不知道那些海洋生物在这根木棍上看到了什么。"

WALTER.DESCRIBE.CATFOOD = "我想知道沃比是否也喜欢这个？"

WALTER.DESCRIBE.KATFOOD = "我想知道沃比是否也喜欢这个？"

WALTER.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "你在阳光下看起来更美！",
	PICKED = "估计它晚点还会长回来的。",
	CHOPPED = "真倒霉！",
	BURNING = "嘿！谁能拦着点！",
	BURNT = "啥也不剩了。",
}

WALTER.DESCRIBE.KYNO_BANANA = "我不介意停下来吃点零食。"
WALTER.DESCRIBE.KYNO_BANANA_COOKED = "嗯...这是一根热香蕉。"

WALTER.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "这些树从空中看不一样。",
	PICKED = "看来我得等等了。",
	CHOPPED = "现在只是个可以坐的树桩了。",
	BURNING = "嘿！谁能赶紧拦着点！",
	BURNT = "啥也不剩了。",
}

WALTER.DESCRIBE.KYNO_KOKONUT = "一个难以破解的椰子。"
WALTER.DESCRIBE.KYNO_KOKONUT_HALVED = "它现在适合弹弓了。"
WALTER.DESCRIBE.KYNO_KOKONUT_COOKED = "看起来不错！"

WALTER.DESCRIBE.BOWLOFPOPCORN = "我没什么可以募捐的了……"

WALTER.DESCRIBE.FIGJUICE = "放松和提神。"

WALTER.DESCRIBE.COCONUTWATER = "放松和提神。"

WALTER.DESCRIBE.EYEBALLSPAGHETTI = "哈哈哈，这食物太搞笑了！"

WALTER.DESCRIBE.FORGETMELOTS_SEEDS = "是的，那些是种子！"

WALTER.DESCRIBE.FIRENETTLES_SEEDS = "是的，这些是种子！"

WALTER.DESCRIBE.TILLWEED_SEEDS = "是的，那些是种子！"

WALTER.DESCRIBE.KYNO_FLOATILIZER = "植物喜欢便便。"

WALTER.DESCRIBE.KYNO_TWIGGYNUTS = "从树上掉下来的坚果。"

WALTER.DESCRIBE.KYNO_REPAIRTOOL = "把事情解决。"

WALTER.DESCRIBE.KYNO_KOI = "一条锦鲤！"
WALTER.DESCRIBE.KYNO_KOI_COOKED = "嗯！"

WALTER.DESCRIBE.KYNO_TROPICALFISH = "一条热带鱼！"
WALTER.DESCRIBE.KYNO_TROPICALFISH_COOKED = "味道还可以。"

WALTER.DESCRIBE.KYNO_NEONFISH = "一条霓虹鱼！"
WALTER.DESCRIBE.KYNO_NEONFISH_COOKED = "至少尾巴没了！"

WALTER.DESCRIBE.KYNO_GROUPER = "一条紫色的鱼！"
WALTER.DESCRIBE.KYNO_GROUPER_COOKED = "鱼鳍还在。"
 
WALTER.DESCRIBE.KYNO_PIERROTFISH = "一条黄色的鱼！"
WALTER.DESCRIBE.KYNO_PIERROTFISH_COOKED = "味道不错！"

WALTER.DESCRIBE.KYNO_SALMONFISH = "一条鲑鱼！"
WALTER.DESCRIBE.KYNO_SALMONFISH_COOKED = "你也喜欢鲑鱼吗，沃比？"

WALTER.DESCRIBE.TURF_PINKPARK = "我更喜欢蓝色的。"
WALTER.DESCRIBE.TURF_STONECITY = "我真的需要随身携带这些石头吗？"
WALTER.DESCRIBE.TURF_FIELDS = "我真的需要随身携带这些草皮吗？"
WALTER.DESCRIBE.TURF_TIDALMARSH = "我真的需要随身携带这些泥土吗？"

WALTER.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "盐可以收获了！",
	PICKED = "我们得等它晒干。",
}

WALTER.DESCRIBE.KYNO_SALTRACK_INSTALLER = "收集盐的架子！"

WALTER.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "从树上采集汁液，我知道怎么用！"

WALTER.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "你想要一些螃蟹当晚餐吗，沃比？"

WALTER.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "他跟其他猪很不一样！",
	SLEEPING = "来吧，沃比。我们得让老人家睡觉。",
}

WALTER.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "这还挺酷的嘛！",
	CHOPPED = "估计就这样了。",
	SAPPED = "看起来准备好了。",
	PICKED = "还在工作中。",
	BURNING = "小心！",
	BURNT = "啥也不剩，只有灰烬。",
}

WALTER.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "那看起来不安全。",
	CHOPPED = "也许这样最好。",
	SAPPED = "不知为何还在那儿。",
	PICKED = "还是一团糟。",
	BURNING = "这样最好。",
	BURNT = "抱歉。",
}

WALTER.DESCRIBE.KYNO_SUGARTREE_BUD = "足够吃了。比树好！"

WALTER.DESCRIBE.KYNO_SUGARTREE_FLOWER = "上面有虫子吗？"
WALTER.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "上面有虫子吗？"

WALTER.DESCRIBE.KYNO_SUGARTREE_PETALS = "上面有虫子吗？"

WALTER.DESCRIBE.KYNO_PEBBLECRAB = "一只形状像石头的螃蟹！"

WALTER.DESCRIBE.KYNO_CRABMEAT = "一块白肉？很好奇，不是吗，沃比？"
WALTER.DESCRIBE.KYNO_CRABMEAT_COOKED = "你想要一块吗，沃比？"
WALTER.DESCRIBE.KYNO_CRABMEAT_DRIED = "白肉？很好奇吧，沃比？"

WALTER.DESCRIBE.KYNO_CRABKINGMEAT = "白肉？很好奇吧，沃比？"
WALTER.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "熟肉？很好奇，不是吗，沃比？"
WALTER.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "熟肉？很好奇，不是吗，沃比？"

WALTER.DESCRIBE.KYNO_SLAUGHTERTOOL = "你不能看，沃比！"

WALTER.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "不会飞。但我也飞不起来。",
	COOP = "估计现在它是我的了！",
}

WALTER.DESCRIBE.KYNO_CHICKEN_EGG = "里面有一只小鸡！"
WALTER.DESCRIBE.KYNO_CHICKEN_LARGE = "哇！发现这个我该得个奖章！"
WALTER.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "闻起来像是早饭做好了！"

WALTER.DESCRIBE.KYNO_CHICKEN_EGG_LARGE_CRACKED =
{
	GENERIC = "大自然有时候真是不着急。",
	HATCHING = "哇！要孵出来了，沃比！",
}

WALTER.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "对鸡来说看起来足够安全。大概吧。",
	FULL = "好多蛋啊！真不错！",
	BURNT = "看来它不防火。",
}

WALTER.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "装修房子这事儿我也懂点！"

WALTER.DESCRIBE.KYNO_COOKWARE_KIT = "嘿，沃比，你能帮我解决这个问题吗？"
WALTER.DESCRIBE.KYNO_COOKWARE_SYRUP = "我们需要一些树液来做这件事。"
WALTER.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "我们需要一些树液来做这件事。"
WALTER.DESCRIBE.KYNO_COOKWARE_BIG_POT = "好大的锅！让我们看看我今天能做些什么，沃比。"
WALTER.DESCRIBE.KYNO_COOKWARE_BIG = "好大的锅！让我们看看我今天能做些什么，沃比。"
WALTER.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "你午餐想吃什么，沃比？"
WALTER.DESCRIBE.KYNO_COOKWARE_SMALL = "你午餐想吃什么，沃比？"
WALTER.DESCRIBE.KYNO_COOKWARE_GRILL = "你想吃\"烤肉\"吗，沃比？"
WALTER.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "首先，我们需要安装它。然后我们就可以用它做饭了！"
WALTER.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "你想吃\"烤肉\"吗，沃比？"
WALTER.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "首先，我们需要安装它。然后我们就可以用它做饭了！"
WALTER.DESCRIBE.KYNO_COOKWARE_ELDER = "我们需要一些树液来做这件事。"
WALTER.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "让我们做些面包吧，沃比！"
WALTER.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "现在，烤箱！"
WALTER.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "用这玩意要小心！"
WALTER.DESCRIBE.KYNO_COOKWARE_OVEN = "我应该烤什么，沃比？"
WALTER.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "我应该烤什么，沃比？"
WALTER.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "我应该烤什么，沃比？"

WALTER.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "我奶奶教过我，记得总往石头下面看看。",
	FLIPPED = "这下明白了。",
}

WALTER.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "这看起来我应该检查一下。"

WALTER.DESCRIBE.KYNO_SUGARFLY = "我想知道我能不能抓住它。"
WALTER.DESCRIBE.KYNO_SUGARFLYWINGS = "大自然非常奇妙，不是吗？"

WALTER.DESCRIBE.KYNO_WATERY_CRATE = "这看起来我应该检查一下。"

WALTER.DESCRIBE.KYNO_TUNACAN = "鱼罐头！多么美妙！"
WALTER.DESCRIBE.KYNO_TUNACAN_OPEN = "鱼罐头！多么冒险！"

WALTER.DESCRIBE.KYNO_CANNEDFOOD = "罐头食品！多么冒险！"
WALTER.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "鱼罐头！多么冒险！"

WALTER.DESCRIBE.KYNO_POP = "我不知道这是什么，但看起来令人耳目一新。"

WALTER.DESCRIBE.KYNO_MYSTERYMEAT = "我为什么害怕它？"

WALTER.DESCRIBE.KYNO_BOTTLE_SOUL = "灵魂总是这样吗？"

WALTER.DESCRIBE.SOULSTEW = "灵魂总是这样吗？"

WALTER.DESCRIBE.FORTUNECOOKIE = "你今天运气如何，沃比？"

WALTER.DESCRIBE.HORNOCUPIA = "光是看着就饿了！"

WALTER.DESCRIBE.CHEESE_YELLOW = "来，吃一口，沃比。"
WALTER.DESCRIBE.CHEESE_WHITE = "来，吃一口，沃比。"
WALTER.DESCRIBE.CHEESE_KOALEFANT = "来，吃一口，沃比。"

WALTER.DESCRIBE.MILK_BOX = "你想要一些吗，沃比？"

WALTER.DESCRIBE.WATERCUP = "清爽！"

WALTER.DESCRIBE.HONEYJAR = "来，吃一点，沃比。"

WALTER.DESCRIBE.CRAB_ARTICHOKE = "味道不错！"

WALTER.DESCRIBE.PEPPERROLLS = "为什么它尝起来有薄荷味……？"

WALTER.DESCRIBE.KYNO_SAPHEALER = "治疗过多的甜味。"

WALTER.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "一艘搁浅的船。我知道那种感觉。",
	PICKED = "这里啥也不剩了。",
	BURNING = "是啊……这肯定要沉了。",
}

WALTER.DESCRIBE.KYNO_GHOST_PIRATE = "你也是这船上的水手？大概吧。"

WALTER.DESCRIBE.KYNO_BUCKET_EMPTY = "现在我可以在里面装东西了。"
WALTER.DESCRIBE.KYNO_BUCKET_METAL = "现在我可以把东西放在里面了。"
WALTER.DESCRIBE.KYNO_BUCKET_WATER = "露营和清洁的完美之选！"

WALTER.DESCRIBE.KYNO_MILK_BEEFALO = "你想喝点牛奶吗，沃比？"
WALTER.DESCRIBE.KYNO_MILK_KOALEFANT = "你想喝点牛奶吗，沃比？"

WALTER.DESCRIBE.KYNO_CAP_DRIED = "有点难嚼。"

WALTER.DESCRIBE.KYNO_PLANTMEAT_DRIED = "那是一些美味的肉干！"

WALTER.DESCRIBE.KYNO_BREWBOOK = "看来我有新指南要背了！"

WALTER.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "你想要什么口味的果汁，沃比？",
	BREWING_LONG = "看来我得等等了。",
	BREWING_SHORT = "很快就好。",
	DONE = "完成了！",
	BURNT = "唉……没成功。",
}

WALTER.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "来点果酱怎么样，沃比？",
	BREWING_LONG = "看来我得等等了。",
	BREWING_SHORT = "快好了。",
	DONE = "太棒了！成功了！",
	BURNT = "太可惜了。",
}

WALTER.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "我需要储物空间，但也想要蜂蜜。",
	HONEY = "好多蜂蜜啊！",
	NECTAR = "估计还需要点时间。",
	BURNING = "那可不好。",
}

WALTER.DESCRIBE.KYNO_NECTAR_POD = "我需要找到能把它变成蜂蜜的东西。"

WALTER.DESCRIBE.KYNO_OAKTREE_POD = "让我们种下它吧，沃比！"
WALTER.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "用来嚼着吃……"

WALTER.DESCRIBE.KYNO_PIKO = "它的脸颊比沃比拥有更多的存储空间。"
WALTER.DESCRIBE.KYNO_PIKO_ORANGE = "嗯。它有一种奇怪的咖啡因气味......"

WALTER.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "这是一棵树，沃比。那儿啥也没有，除非……",
	CHOPPED = "你的叶子会很有用的。",
	BURNING = "小心，沃比！",
	BURNT = "啥也不剩，只有灰烬。",
}

WALTER.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "这是一棵树，沃比。那儿啥也没有，除非……",
	BURNING = "哇，这下糟了！",
}

WALTER.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "不是典型的宝箱，但它确实有效。"

WALTER.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "我敢打赌那木头里全是白蚁。",
	BURNT = "唉……就这样了。",
}

WALTER.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "我敢打赌那木头里全是白蚁。",
	CRAFTED = "嘿，它看起来还不错！",
	BURNT = "好臭！",
}

WALTER.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "我们该问问他有没有给你准备什么特别的东西，沃比。",
	OCCUPIED = "他的店现在没开门。",
}

WALTER.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "我好像看到里面有蛇油。",
	EMPTY = "已经卖光了。",
}

WALTER.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "这是我第一次看到一个会做生意的鱼人。"
WALTER.DESCRIBE.KYNO_MEADOWISLAND_POND = "需要一根钓鱼竿..."
WALTER.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "猜猜它会是什么，乐趣就在其中。"
WALTER.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "一堆均匀的沙粒。"
WALTER.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "生来就是鱼。"

WALTER.DESCRIBE.KYNO_SAMMYHAT = "我已经有自己的帽子了。"

WALTER.DESCRIBE.KINGFISHER = "多么符合空气动力学的喙！"

WALTER.DESCRIBE.TOUCAN = "好大的嘴！"
WALTER.DESCRIBE.TOUCAN_CHUBBY = "好大的嘴！"

WALTER.DESCRIBE.WETGOOP2 = "呃……也许沃比会想要它……"

WALTER.DESCRIBE.BEER = "我不确定我是否应该喝那个。"

WALTER.DESCRIBE.PALEALE = "我不确定我是否应该喝那个。"

WALTER.DESCRIBE.TEAGREEN = "让我感觉有点头晕......"

WALTER.DESCRIBE.TEARED = "让我的心有点模糊......"

WALTER.DESCRIBE.MEAD = "咕噜……咕噜……"

WALTER.DESCRIBE.KYNO_JELLY = "现在我们真的陷入困境了......"

WALTER.DESCRIBE.KYNO_MAYONNAISE = "你想要一些吗，沃比？"

WALTER.DESCRIBE.TARTARSAUCE = "嗯……我想你不会喜欢的，沃比。"

WALTER.DESCRIBE.KYNO_PICKLES = "你想要一些吗，沃比？"

WALTER.DESCRIBE.KYNO_WINE = "不是我喜欢的。"

WALTER.DESCRIBE.KYNO_JUICE = "我已经有一段时间没有了。"

WALTER.DESCRIBE.KYNO_POISON_FROGLEGS = "沃比，别吃那个！"
WALTER.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "沃比，别吃那个！"

WALTER.DESCRIBE.POISONFROGGLEBUNWICH = "如果你足够努力，你可以把任何东西做成三明治。"

WALTER.DESCRIBE.KYNO_BREWINGRECIPECARD = "如果你嚼卡片我就看不懂食谱了！"

WALTER.DESCRIBE.KYNO_OIL = "不，！这不是用来喝酒的！"

WALTER.DESCRIBE.BERRYSUNDAE = "不要吃太多，否则你会冻僵的！"

WALTER.DESCRIBE.CHOCOLATE_BLACK = "对不起沃比，你不能吃它，遗憾的是。"
WALTER.DESCRIBE.CHOCOLATE_WHITE = "对不起沃比，你不能吃它，很遗憾。"

WALTER.DESCRIBE.TRICOLORDANGO = "它比看起来好得多。"
 
WALTER.DESCRIBE.FRIESFRENCH = "想要一些吗，沃比？"

WALTER.DESCRIBE.PIRATERUM = "我必须对此保持谨慎。"

WALTER.DESCRIBE.TWISTEDTEQUILA = "我觉得这杯酒不适合你喝，沃比。"

WALTER.DESCRIBE.ONIONRINGS = "洋葱浸在油里，有趣！"

WALTER.DESCRIBE.DONUTS = "没想到会在这附近看到那些人。"
WALTER.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "没想到会在这附近看到那些人。"
WALTER.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "没想到会在这附近看到那些人。"
 
WALTER.DESCRIBE.CINNAMONROLL = "无法用言语来形容这个面包有多甜。"

WALTER.DESCRIBE.GUMMYBEARGERS = "我在这种食物中闻到了危险的味道！"

WALTER.DESCRIBE.PRETZEL = "你想要一些吗，沃比？"

WALTER.DESCRIBE.CORNINCUP = "杯子里放一些玉米听起来不错。"

WALTER.DESCRIBE.COTTONCANDY = "我不应该吃太多糖。"

WALTER.DESCRIBE.ROASTEDHAZELNUTS = "我想你可以吃一些，沃比……"

WALTER.DESCRIBE.MONSTERMUFFIN = "这需要进一步调查！"

WALTER.DESCRIBE.PINKCAKE = "只是给我和沃比的一小块。"

WALTER.DESCRIBE.CHIPSBAG = "为什么袋子的一半是空的？"

WALTER.DESCRIBE.LITTLEBREAD = "想要一块吗，沃比？"

WALTER.DESCRIBE.HOTHOUND = "我会为你再做一份，沃比！"

WALTER.DESCRIBE.MILKSHAKE = "对于牛奶来说非常甜。"
WALTER.DESCRIBE.MILKSHAKE_PRISMATIC = "对于牛奶来说非常甜。"

WALTER.DESCRIBE.NACHOS = "慢慢吃吧，沃比。"

WALTER.DESCRIBE.BANANA_PUDDING = "好吃！"

WALTER.DESCRIBE.SEA_PUDDING = "我更喜欢甜布丁。"

WALTER.DESCRIBE.TOM_KHA_SOUP = "迫不及待地想尝试一下！"

WALTER.DESCRIBE.MINERTREAT = "如果我这样做了，请不要介意。"

WALTER.DESCRIBE.RADISHSALAD = "即使是捡来的萝卜也可以成为荒野中的食物！"

WALTER.DESCRIBE.PUMPKIN_SOUP = "我喜欢汤。"

WALTER.DESCRIBE.ALGAE_SOUP = "我喜欢汤。"

WALTER.DESCRIBE.PARZNIP_SOUP = "我喜欢汤。"

WALTER.DESCRIBE.NETTLEMEATED = "肉有助于药物的吸收。"

WALTER.DESCRIBE.KYNO_SUGAR = "我现在可以喝点咖啡了！"

WALTER.DESCRIBE.KYNO_BOTTLECAP = "没有上限！"

WALTER.DESCRIBE.NUKACOLA = "我个人喜欢它。"
WALTER.DESCRIBE.NUKACOLA_QUANTUM = "我个人喜欢它。"

WALTER.DESCRIBE.LIVINGSANDWICH = "那个三明治有些奇怪。"

WALTER.DESCRIBE.DURIANSPLIT = "别吃太多，否则你会被冻住的！"

WALTER.DESCRIBE.DURIANSOUP = "我喜欢汤。"

WALTER.DESCRIBE.DURIANMEATED = "糟糕！"

WALTER.DESCRIBE.DURIANCHICKEN = "素食鸡腿！"

WALTER.DESCRIBE.LUNARSOUP = "难得的汤，我不怕！"

WALTER.DESCRIBE.PURPLEWOBSTERSOUP = "看起来不错，所以味道也应该不错！"

WALTER.DESCRIBE.WOBSTERMONSTER = "我对此不太确定。"

WALTER.DESCRIBE.SPIDERCAKE = "这太恶心了。"

WALTER.DESCRIBE.SUGARBOMBS = "糖太多了！"

WALTER.DESCRIBE.BERRYBOMBS = "现在我们真的陷入困境了......"

WALTER.DESCRIBE.ONIGIRIS = "这真是一道美味的点心。"

WALTER.DESCRIBE.OMURICE = "好了，沃比，再咬一口！"

WALTER.DESCRIBE.PAELLA = "谁能想到米饭会这么好吃呢？"

WALTER.DESCRIBE.RISOTTO = "好吧，沃比，我们停下来吃点东西怎么样？"

WALTER.DESCRIBE.RICESAKE = "我不确定这个。也许我应该放弃。"

WALTER.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "别碰它，沃比。让我来处理。"

WALTER.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "别碰它，沃比。让我来处理。",
	PICKED = "它最终还会长回来的。",
	WITHERED = "需要施肥了。",
	BURNING = "哇！糟透了！",
}

WALTER.DESCRIBE.KYNO_PINEAPPLE = "很好的热带水果!"
WALTER.DESCRIBE.KYNO_PINEAPPLE_HALVED = "很好的热带水果!"
WALTER.DESCRIBE.KYNO_PINEAPPLE_COOKED = "来，咬一口，沃比。"

WALTER.DESCRIBE.PIZZA_TROPICAL = "谁在乎呢？这是披萨！"

WALTER.DESCRIBE.PINACOLADA = "正中要害。"

WALTER.DESCRIBE.CHIMAS = "有点令人兴奋。"

WALTER.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "老实说，我可能会冲过去玩水。",
	ON = "保持花园健康！",
}

WALTER.DESCRIBE.KYNO_FOODSACK = "沃比也能胜任这项工作... 我觉得"

WALTER.DESCRIBE.GUMMYWORMS = "你看到了什么，沃比？"

WALTER.DESCRIBE.SMORES = "我们当时做了很多这样的零食!"

WALTER.DESCRIBE.NUKASHINE = "小恶魔告诉我，这是阿巴拉契亚的一种挑战饮料？我猜这就是它的名字。"

WALTER.DESCRIBE.ANTSLOG = "为了在这里生存，你必须做你需要做的..."

WALTER.DESCRIBE.KYNO_WORM_BONE = "这骨头里没有肉，但我想用来做汤一定不错。"

WALTER.DESCRIBE.SPOOKY_BRAIN_NOODLES = "不害怕它。"
WALTER.DESCRIBE.SPOOKY_BURGERZILLA = "嘿，沃比，你现在为什么这么害怕？"
WALTER.DESCRIBE.SPOOKY_DEADBREAD = "只是一个普通的面包。"
WALTER.DESCRIBE.SPOOKY_JELLYBEANS = "别紧张，这不是真的眼球。"
WALTER.DESCRIBE.SPOOKY_POPSICLE = "闻起来像雨林。"
WALTER.DESCRIBE.SPOOKY_PUMPKINCREAM = "这吓不倒我！"
WALTER.DESCRIBE.SPOOKY_SKULLCANDY = "不要困扰。"
WALTER.DESCRIBE.SPOOKY_TACODILE = "别担心，沃比。它不会咬你的。"

WALTER.DESCRIBE.BUTTER_BEEFALO = "它看起来很棒。"
WALTER.DESCRIBE.BUTTER_GOAT = "一块山羊黄油。"
WALTER.DESCRIBE.BUTTER_KOALEFANT = "一个明智的决定与成分。"

WALTER.DESCRIBE.SPICE_CURE = "这样我们就可以吃更少的罐头食品和更健康的食物。"
WALTER.DESCRIBE.SPICE_COLD = "好冷！"
WALTER.DESCRIBE.SPICE_FIRE = "小心点，沃比。它燃烧得很亮。"
WALTER.DESCRIBE.SPICE_FED = "多吃，多做。"
WALTER.DESCRIBE.SPICE_MIND = "一种放松身心的糖。"

WALTER.DESCRIBE.SUGARFLYMUFFIN = "我对糖蛾感到有点难过。"

WALTER.DESCRIBE.EELTACOS = "更多的鳗鱼菜肴！"

WALTER.DESCRIBE.MEATSKILLET = "它温暖了我的心。"

WALTER.DESCRIBE.MEATWALTZ = "其中使用了一些不安全的方法。"

WALTER.DESCRIBE.COMPLETEBREAKFAST = "沃比！你需要帮我完成这件事！我一个人受不了。"

WALTER.DESCRIBE.DUMPLINGS = "你也想咬一口吗，沃比？"

WALTER.DESCRIBE.WARLYICEDTEA = "放松和清爽。"

WALTER.DESCRIBE.WARLYTEA = "我过去常常去参加茶会。"

WALTER.DESCRIBE.KYNO_TEALEAF = "沃比，我们去泡点茶吧！"

WALTER.DESCRIBE.KYNO_ITEMSLICER = "你会用它切东西的。"
WALTER.DESCRIBE.KYNO_ITEMSLICER_GOLD = "你会用它切东西的。"

WALTER.DESCRIBE.COXINHA = "它有点油，但仍然很好。"

WALTER.DESCRIBE.LAZYDESSERT = "我认为我们不应该吃这个。"

WALTER.DESCRIBE.CRABKINGFEAST = "这个盛宴中每个人都有一份。"

WALTER.DESCRIBE.PIENAPPLE = "我在烘焙派方面还算不错。"

WALTER.DESCRIBE.JAWSBREAKER = "如果沃比吃得更多，她就能吃饱了？"

WALTER.DESCRIBE.AVOCADOTOAST = "可惜它们没有其他口味。"

WALTER.DESCRIBE.RICEPUDDING = "健康的甜点。"

WALTER.DESCRIBE.SHARKSUSHI = "啊，真没见过有人真的用鲨鱼做寿司。"

WALTER.DESCRIBE.WOBSTERBREADED = "一只裹面包屑的海虫！"

WALTER.DESCRIBE.LAZYPURRITO = "你想要吗，沃比？"

WALTER.DESCRIBE.HORCHATA = "健康的饮料！"

WALTER.DESCRIBE.WOBSTERCOCKTAIL = "这是一杯非常美丽的鸡尾酒。"

WALTER.DESCRIBE.LAVAEEGGBOILED = "我希望我的舌头不会烫！"

WALTER.DESCRIBE.POMEGRANATETEA = "放松和清爽。"

WALTER.DESCRIBE.TIRAMISU = "沃利的手艺真棒！"

WALTER.DESCRIBE.TOADSTOOLCOLA = "这里有某种品牌的汽水吗？"

WALTER.DESCRIBE.TEPACHE = "味道不错。"

WALTER.DESCRIBE.LUNARTEQUILA = "我能感受到一股强大的能量从它身上散发出来。"

WALTER.DESCRIBE.MIMICMOSA = "这真的能让我隐形吗？"

WALTER.DESCRIBE.POMEGRANATEPIE = "一种不错的派。"

WALTER.DESCRIBE.PINEAPPLECAKE = "看来你也想要一份，是吗，沃比？"

WALTER.DESCRIBE.PASTY_MEAT = "一款相当不错的零食，但油分含量较高。"
WALTER.DESCRIBE.PASTY_CHEESE = "一款相当不错的零食，但油分含量较高。"

WALTER.DESCRIBE.BRIGADEIRO = "抱歉，沃比。这个你不能要。"

WALTER.DESCRIBE.REGULARLASAGNA = "我待会儿给你做一份巨无霸千层饼，沃比。"

WALTER.DESCRIBE.FLTSANDWICH = "哦，真好！更多的蛙腿三明治。"

WALTER.DESCRIBE.RICEANDBEANS = "简单而均衡的菜肴。"

WALTER.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "被遗弃的地方总有故事……也许2026年我们会知道！"

WALTER.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "大自然总是藏着惊喜……甚至在地下！",
	PICKED = "希望之后能再长出更多。",
	BURNING = "啊，那是个稀有资源啊。",
}

WALTER.DESCRIBE.KYNO_TRUFFLES = "松露！来自野外的稀有宝藏。"
WALTER.DESCRIBE.KYNO_TRUFFLES_COOKED = "烤好了，准备就绪——香气扑鼻！"

WALTER.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "用来展示营地美食很棒！看起来很专业！",
	FULL = "嘿，这还挺酷的嘛！",
}

WALTER.DESCRIBE.KYNO_SPORECAP = "新物种！但可能有毒。"
WALTER.DESCRIBE.KYNO_SPORECAP_COOKED = "看起来没那么危险了。"

WALTER.DESCRIBE.KYNO_SPORECAP_DARK = "危险物种！靠近呼吸时要小心！"
WALTER.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "火没能中和毒素！"

WALTER.DESCRIBE.KYNO_GOLDENAPPLE = "我这辈子从没见过金苹果！"

WALTER.DESCRIBE.TRUFFLESGRINDER = "我读过关于松露的书！没想到真能尝到！"

WALTER.DESCRIBE.SPORECAPPIE = "我觉得沃比不该吃这个。"

WALTER.DESCRIBE.SPORECAP_SKEWERS = "完美的旅行食物！篝火上轻松烹饪。"

WALTER.DESCRIBE.TRUFFLEOIL = "这会是个绝佳的野营烹饪实验！"

WALTER.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "我擅长遵循指示！为此我还获得了一枚徽章呢！"
WALTER.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "就像搭建营地……但对象是鱼！"

WALTER.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "看起来像个正经的鱼苗养殖场！",
	FUEL_HIGH = "它们状态不错！",
	FUEL_MED = "食物还很充足。",
	FUEL_LOW = "食物快吃完了。",
	EMPTY = "我猜它们都吃光了。",
}

WALTER.DESCRIBE.KYNO_ANTCHOVY = "新物种！等沃比看到这个就知道了！"
WALTER.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "他们团结一致……像蚂蚁！或者鱼群！"

WALTER.DESCRIBE.AGEDROE = "哦，鱼卵。"
WALTER.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "原来鱼子酱是这种滋味啊……真棒！"

WALTER.DESCRIBE.KYNO_SWORDFISH_BLUE = "它一定在那个池塘里待了好几年！可怜的家伙。"

WALTER.DESCRIBE.KYNO_JELLYFISH = "如此灿烂又充满活力！"
WALTER.DESCRIBE.KYNO_JELLYFISH_DEAD = "安息吧。"
WALTER.DESCRIBE.KYNO_JELLYFISH_COOKED = "就像我的童子军口香糖。"
WALTER.DESCRIBE.KYNO_JELLYFISH_DRIED = "就像我的童子军口香糖一样嚼劲十足。"

WALTER.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "我好像找到了彩虹的尽头！"
WALTER.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "闪亮快乐的食物。"
WALTER.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "如此闪亮又绚丽多彩！"

WALTER.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "太好了。一个空瓶子。正是我想要的。"

WALTER.DESCRIBE.KYNO_OCEANTRAP = "看起来它能把鱼困在里面。"

WALTER.DESCRIBE.OCEANFISH_PUFFERFISH = "一种经典的海洋防御机制。太酷了！"
WALTER.DESCRIBE.OCEANFISH_STURGEON = "哇！活化石！太不可思议了！"

WALTER.DESCRIBE.KYNO_SWORDFISH = "他听起来有点不高兴。"
WALTER.DESCRIBE.KYNO_SWORDFISH_DEAD = "哎呀，他撑不了多久呢。"

WALTER.DESCRIBE.SWORDFISHFEAST = "哇！演示做得真棒。"

WALTER.DESCRIBE.KYNO_DOGFISH = "喂，沃比！我给你找了个朋友！"
WALTER.DESCRIBE.KYNO_DOGFISH_DEAD = "嗯，我想现在该是你吃晚饭的时候了，沃比。"

WALTER.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "它坏了，我该扔掉它。"

WALTER.DESCRIBE.WOBSTER_MONKEYISLAND = "哇，罕见的黄金龙虾！真是个了不起的发现！"
WALTER.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "我有点过意不去……但肯定好吃！"
WALTER.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "篝火海鲜大餐！别告诉沃比，她会嫉妒的。"

WALTER.DESCRIBE.KYNO_PUFFERMONSTER = "哇！一只真正的棘皮河豚！但它很生气！"

WALTER.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "瞧，沃比！一条鱼的踪迹正等着我们呢！"
WALTER.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "我从未见过如此近距离的鲸鱼！"
WALTER.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "就是它——白鲸！！我真的找到了！"
WALTER.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "死鲸鱼绝对臭气熏天！"

WALTER.DESCRIBE.KYNO_BLUBBER = "它又软又干。"

WALTER.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "露营旅行的完美之选！"
WALTER.DESCRIBE.KYNO_FISHMEAT_DRIED = "非常适合海上长途探险！"

WALTER.DESCRIBE.MONKEYISLANDMEAL = "哇，这简直是一场碗里的冒险！"

WALTER.DESCRIBE.KYNO_BRAINROCK_LARVAE = "婴儿般纯真的头脑，即将萌发新芽。"
WALTER.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "你还需要些水才能长大，对吧？"
WALTER.DESCRIBE.KYNO_BRAINROCK_CORAL = "嘿，沃比，你在想什么呢？"

WALTER.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "肯定比小体型的沃比脑子大。",
	PICKED = "估计它需要打个盹。",
}

WALTER.DESCRIBE.BRAINMETTERSOUP = "我想这能帮我想到更好的生存方案！"

WALTER.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "哇！我以前从未如此近距离地看过章鱼。",
	SLEEPING = "我待会儿再来。",
}

WALTER.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "他是怎么把东西放进去的？"

WALTER.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "一条死鱼。正是我需要的。",
	WAITING = "也许包扎一下能治好他？",
}

WALTER.DESCRIBE.KYNO_PACKIMBAGGIMS = "啊！沃比，你有个新朋友啦！"

WALTER.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "走吧，沃比。该去收集些食材了。"
WALTER.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "我猜它会不会和沃比一样高呢？"
WALTER.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "是时候庆祝了！"
WALTER.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "小心火焰，好吗？"
WALTER.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "看起来如此神奇！"
WALTER.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "没有什么比蛋糕更能代表周年纪念了！对吧，沃比？"
WALTER.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "气球总能让派对更有趣！"

WALTER.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "爆米花可以吃了！",
	FUEL_HIGH = "燃料还很充足。",
	FUEL_MED = "还在爆。",
	FUEL_LOW = "快没燃料了。",
	EMPTY = "我猜它是空的。",
}

WALTER.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "非常适合篝火晚会和派对！"
WALTER.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "欢聚时刻的完美之选！"
WALTER.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "来自我们特别小伙伴的特别装备！"

WALTER.DESCRIBE.KYNO_FISHREGISTRYHAT = "很适合记录你发现的鱼类。"

WALTER.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "一个动物饲料槽。",
	FUEL_HIGH = "它们够吃一阵子了。",
	FUEL_MED = "应该能维持一阵。",
	FUEL_LOW = "快没食物了。",
	EMPTY = "估计该喂食了。",
	BURNT = "这可不太妙。",
}

WALTER.DESCRIBE.CHICKENNUGGETS = "不太适合露营餐，但也凑合吧。"

WALTER.DESCRIBE.CHICKENWINGS = "辣，但值得一试！"

WALTER.DESCRIBE.CHICKENBURGER = "完美的徒步旅行食物！"

WALTER.DESCRIBE.CHICKENEGGSOUP = "漫长的一天过后，喝这个暖暖身子正合适。"

WALTER.DESCRIBE.CHICKENEGGSTEW = "感觉像真正的营地大餐。"

WALTER.DESCRIBE.CHICKENROTISSERIE = "这会是顿很棒的营地晚餐！"