local WURT = STRINGS.CHARACTERS.WURT

WURT.ANNOUNCE_KYNO_COFFEEBUFF_START = "咕噜咕噜！！！我很快！"
WURT.ANNOUNCE_KYNO_COFFEEBUFF_END = "没速度了，笨蛋。"

WURT.ANNOUNCE_KYNO_HASTEBUFF_START = "好快！！"
WURT.ANNOUNCE_KYNO_HASTEBUFF_END = "浮浪噗，手再也不快了？"

WURT.ANNOUNCE_KYNO_POPBUFF_START = "（嗝！）呵呵，有趣的声音，调情。"
WURT.ANNOUNCE_KYNO_POPBUFF_END = "呃……胃有点痛，小女孩。"

WURT.ANNOUNCE_KYNO_FROGBUFF_START = "发生甚么事了？"
WURT.ANNOUNCE_KYNO_FROGBUFF_END = "青蛙去哪儿了？"

WURT.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝!) 嘿嘿，有趣的声音，浮浪噗！"
WURT.ANNOUNCE_KYNO_PIRATEBUFF_END = "呃......胃有点疼，浮浪噗。"

WURT.ANNOUNCE_KYNO_FREEZEBUFF_START = "手感觉冷，浮浪噗。"
WURT.ANNOUNCE_KYNO_FREEZEBUFF_END = "再见，再见，寒冷！"

WURT.ANNOUNCE_KYNO_FIREBUFF_START = "手感觉到浅浅的温暖，浮浪噗。"
WURT.ANNOUNCE_KYNO_FIREBUFF_END = "再见，再见，火焰！"

WURT.ANNOUNCE_KYNO_FISHINGBUFF_START = "是时候结交新朋友了！"
WURT.ANNOUNCE_KYNO_FISHINGBUFF_END = "不！所有的鱼都去哪里了？"

WURT.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "噢，太放松了，浮浪噗。"
WURT.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "感觉有点头晕，浮浪噗。"

WURT.ANNOUNCE_KYNO_EATERBUFF_START = "牙齿摸起来很奇怪，很黏。"
WURT.ANNOUNCE_KYNO_EATERBUFF_END = "有趣的感觉消失了，浮浪噗。"

WURT.ANNOUNCE_KYNO_WORMBUFF_START = "浮浪噗，不想伤害暴躁的家伙！"
WURT.ANNOUNCE_KYNO_WORMBUFF_END = "耶，别再打架了！"

WURT.ANNOUNCE_KYNO_CRABBUFF_START = "浮浪噗, 不想伤害螃蟹"
WURT.ANNOUNCE_KYNO_CRABBUFF_END = "耶，别再打架了！"

WURT.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝!) 嘿嘿，奇怪的声音，浮浪噗。"
WURT.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "啊...胃有点疼，浮浪噗。"

WURT.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "哦...！"
WURT.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "哇...感觉有点累，浮浪噗。"

WURT.ANNOUNCE_KYNO_STEALTHBUFF_START = "嘿嘿，快躲起来吧!"
WURT.ANNOUNCE_KYNO_STEALTHBUFF_END = "已经走了？"

WURT.ANNOUNCE_KYNO_FEARBUFF_START = "哼！沃特什么都不怕！这恰恰证明了这一点！"
WURT.ANNOUNCE_KYNO_FEARBUFF_END = "可怕的感觉又回来了！别这样！！！"

WURT.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "咕噜！闪闪发光的水果让我感觉怪怪的！"
WURT.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "咕噜……闪亮的感觉没啦！"

WURT.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "我不和它们交朋友！"
WURT.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "呜呜……"

WURT.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "没有烫烫的雨了！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WURT.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "没有毒！咕噜好开心！"
WURT.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "咕噜……不舒服了！"

WURT.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "咕噜！我感觉自己聪明绝顶！"
WURT.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "咕噜，脑袋又晕乎乎的。"

WURT.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "嗡嗡虫变乖了，咕噜！"
WURT.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "嗡嗡虫又生气了，咕噜！"

WURT.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "现在好强！浮浪噗！"
WURT.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "又感觉软趴趴的……浮浪噗。"

WURT.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "咕噜！现在能吃好多啦！"
WURT.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "饥饿又变小了，浮浪噗……"

WURT.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "脑袋不再转圈圈！浮浪噗！"
WURT.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "大脑又开始怪怪的，咕噜..."

WURT.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "加油，小家伙！"
WURT.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "感觉虚弱，咕噜……"

WURT.ANNOUNCE_KYNO_BERSERKERBUFF_START = "强壮！但也是软软的！"
WURT.ANNOUNCE_KYNO_BERSERKERBUFF_END = "不再特别强壮了……"

WURT.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "饱得更久了！"
WURT.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "又饿了……"

WURT.ANNOUNCE_KYNO_CANTBUILDHERE_FISHERMERMHOUSE = "沼泽里有漂亮的鱼！"

WURT.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "咕噜……错误……"

WURT.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "咕噜……猪人总是很坏……！"

WURT.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "还没有？好吧……"

WURT.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "不？好吧。"

WURT.ANNOUNCE_KYNO_POTHANGER_FAIL = "呃，不想这样？"

WURT.ANNOUNCE_KYNO_CASSEROLE_FAIL = "咕噜……不是这个……"

WURT.ANNOUNCE_KYNO_SAPHEALER_USED = "树又好了，耶！"

WURT.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "咕噜……为什么所有事情都这么暴力？"

WURT.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "这里什么都没有，浮浪噗……"

WURT.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "泡泡消失了！野兽逃走了，浮浪噗！"
WURT.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "雨水冲刷万物，咕噜！"
WURT.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "大水怪逼近啦！好可怕，浮浪噗！"

WURT.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "蛋糕做好啦！开派对啦， 浮浪噗！"

WURT.ANNOUNCE_KYNO_FISH_RESEARCHED = "学到朋友的秘密了！！"
WURT.ANNOUNCE_KYNO_ROE_RESEARCHED = "鱼宝宝的秘密！咕噜！"

WURT.DESCRIBE.KYNO_ROE = "小朋友们！"
WURT.DESCRIBE.KYNO_ROE_COOKED = "不——————！"

WURT.DESCRIBE.KYNO_SHARK_FIN = "可怜的小鲨鱼，失去了鳍，浮浪噗。"

WURT.DESCRIBE.KYNO_BEANBUGS = "有趣的虫子，沃比！"
WURT.DESCRIBE.KYNO_BEANBUGS_COOKED = "我很抱歉......"

WURT.DESCRIBE.KYNO_GUMMYBUG = "嗨，小朋友！"
WURT.DESCRIBE.KYNO_GUMMYBUG_COOKED = "我很抱歉！"

WURT.DESCRIBE.KYNO_WHEAT = "它像草，但却是隐藏的零食！"
WURT.DESCRIBE.KYNO_WHEAT_COOKED = "它像草，有隐藏的零食！"

WURT.DESCRIBE.KYNO_FLOUR = "粉，小花。"

WURT.DESCRIBE.KYNO_SPOTSPICE = "哦哦，味道不错！"

WURT.DESCRIBE.KYNO_SAP = "嗯，好甜！！"
WURT.DESCRIBE.KYNO_SAP_SPOILED = "咕噜……不再那么好了。"

WURT.DESCRIBE.KYNO_SYRUP = "粘甜的！"

WURT.DESCRIBE.KYNO_COFFEEBEANS = "能给人能量的豆子。"
WURT.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "需要一些东西......"

WURT.DESCRIBE.DUG_KYNO_COFFEEBUSH = "需要土！"

WURT.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "热乎乎的豆子！",
	PICKED = "现在没豆子了。",
	WITHERED = "需要灰才能长，浮浪噗。",
}

WURT.DESCRIBE.DUG_KYNO_SPOTBUSH = "植物需要地！"

WURT.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "粉色的灌木，浮浪噗。",
	PICKED = "现在没东西了。",
	BURNING = "坏火！",
}

WURT.DESCRIBE.KYNO_SPOTSPICE_LEAF = "小装饰，小花。"

WURT.DESCRIBE.KYNO_MUSSEL = "带壳的肉，沃比。"
WURT.DESCRIBE.KYNO_MUSSEL_COOKED = "好！"

WURT.DESCRIBE.KYNO_HUMANMEAT = "唔-唔。"
WURT.DESCRIBE.KYNO_HUMANMEAT_COOKED = "咕噜咕噜，没有鳞片更难烤熟。"
WURT.DESCRIBE.KYNO_HUMANMEAT_DRIED = "不。"

WURT.DESCRIBE.COFFEE = "好吃!!!"

WURT.DESCRIBE.BISQUE = "这是汤，太棒了！"

WURT.DESCRIBE.JELLYOPOP = "可怜的朋友现在死了，沃比。"

WURT.DESCRIBE.SHARKFINSOUP = "不！"

WURT.DESCRIBE.TROPICALBOUILLABAISSE = "不~~~~!"

WURT.DESCRIBE.MUSSELBOUILLABAISE = "嗯！"

WURT.DESCRIBE.SWEETPOTATOSOUFFLE = "甜！"

WURT.DESCRIBE.FEIJOADA = "巴西食物，国菜！"

WURT.DESCRIBE.GUMMY_CAKE = "又香又甜，沃比。"

WURT.DESCRIBE.HARDSHELL_TACOS = "脆脆的！"

WURT.DESCRIBE.ICEDTEA = "冷，小声！"

WURT.DESCRIBE.NETTLELOSANGE = "治疗鼻子好东西，沃比！"

WURT.DESCRIBE.SNAKEBONESOUP = "骨头汤，沃比。"

WURT.DESCRIBE.STEAMEDHAMSANDWICH = "我不太喜欢它。"

WURT.DESCRIBE.TEA = "甜蜜而放松，沃比。"

WURT.DESCRIBE.BUBBLETEA = "冷，小声！"

WURT.DESCRIBE.FRENCHONIONSOUP = "骨头汤，花花公子。"

WURT.DESCRIBE.SLAW = "这是最好的！！"

WURT.DESCRIBE.LOTUSBOWL = "好花，小花！"

WURT.DESCRIBE.POI = "这是最好的！！"

WURT.DESCRIBE.JELLYBEAN_HUNGER = "一颗好豆子。"
WURT.DESCRIBE.JELLYBEAN_SUPER = "一颗好豆子。"
WURT.DESCRIBE.JELLYBEAN_SANITY = "一颗好豆子。"

WURT.DESCRIBE.BOWLOFGEARS = "不是食物，沃比。"

WURT.DESCRIBE.LONGPIGMEAL = "这是个糟糕的主意。."

WURT.DESCRIBE.CUCUMBERSALAD = "看起来不错，但味道..."

WURT.DESCRIBE.DUG_KYNO_WILDWHEAT = "一簇草，浮浪噗。"

WURT.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "草，浮浪噗。",
	PICKED = "现在没食物了。",
	WITHERED = "需要水。",
	BURNING = "得把火扑灭！！",
}

WURT.DESCRIBE.KYNO_MEALGRINDER = "咕噜咕噜……我该如何使用它？"

WURT.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "哦哦哦，蘑菇长在这儿！",
	PICKED = "没有蘑菇了……？",
	BURNING = "坏火！",
}

WURT.DESCRIBE.GORGE_BREAD = "哦……闻起来很香，沃比！"
WURT.DESCRIBE.GORGE_SWEET_CHIPS = "嘎吱……嘎吱……"
WURT.DESCRIBE.GORGE_VEGETABLE_SOUP = "好吃！"
WURT.DESCRIBE.GORGE_JELLY_SANDWICH = "好吃！"
WURT.DESCRIBE.GORGE_FISH_STEW = "不不不！"
WURT.DESCRIBE.GORGE_MEAT_STEW = "好吃！"
WURT.DESCRIBE.GORGE_ONION_CAKE = "好吃！"
WURT.DESCRIBE.GORGE_POTATO_PANCAKES = "好吃!"
WURT.DESCRIBE.GORGE_POTATO_SOUP = "这是汤，浮浪噗。"
WURT.DESCRIBE.GORGE_FISHBALL_SKEWERS = "不！鱼不见了！！"
WURT.DESCRIBE.GORGE_MEAT_SKEWERS = "格鲁格..."
WURT.DESCRIBE.GORGE_STONE_SOUP = "这是汤，浮浪噗。"
WURT.DESCRIBE.GORGE_CROQUETTE = "好吃！"
WURT.DESCRIBE.GORGE_ROAST_VEGETABLES = "真好吃！"
WURT.DESCRIBE.GORGE_MEATLOAF = "哎呀, 浮浪噗。"
WURT.DESCRIBE.GORGE_CARROT_SOUP = "这是汤，浮浪噗。"
WURT.DESCRIBE.GORGE_FISHPIE = "不——————！"
WURT.DESCRIBE.GORGE_FISHCHIPS = "不——————！"
WURT.DESCRIBE.GORGE_MEATPIE = "呸。"
WURT.DESCRIBE.GORGE_SLIDERS = "哼！"
WURT.DESCRIBE.GORGE_JELLY_ROLL = "好吃！"
WURT.DESCRIBE.GORGE_CARROT_CAKE = "看起来不错, 浮浪噗。"
WURT.DESCRIBE.GORGE_GARLICMASHED = "闻起来不错, 浮浪噗。"
WURT.DESCRIBE.GORGE_GARLICBREAD = "好吃!"
WURT.DESCRIBE.GORGE_TOMATO_SOUP = "这是汤，浮浪噗。"
WURT.DESCRIBE.GORGE_SAUSAGE = "呃..."
WURT.DESCRIBE.GORGE_CANDIEDFISH = "不——————！"
WURT.DESCRIBE.GORGE_STUFFEDMUSHROOM = "好吃，浮浪噗。"
WURT.DESCRIBE.GORGE_BRUSCHETTA = "好吃!"
WURT.DESCRIBE.GORGE_HAMBURGER = "咕噜……它有肉。"
WURT.DESCRIBE.GORGE_FISHBURGER = "...它有肉。"
WURT.DESCRIBE.GORGE_MUSHROOMBURGER = "...它有肉。"
WURT.DESCRIBE.GORGE_FISH_STEAK = "不不不！"
WURT.DESCRIBE.GORGE_CURRY = "咕噜..."
WURT.DESCRIBE.GORGE_SPAGHETTI = "...该死的大块头。"
WURT.DESCRIBE.GORGE_POACHEDFISH = "*嗅嗅*"
WURT.DESCRIBE.GORGE_SHEPHERD_PIE = "咕噜..."
WURT.DESCRIBE.GORGE_CANDY = "MMMMMMMMMM！太有嚼劲了！"
WURT.DESCRIBE.GORGE_BREAD_PUDDING = "很甜, 浮浪噗。"
WURT.DESCRIBE.GORGE_BERRY_TART = "浆果！"
WURT.DESCRIBE.GORGE_MACARONI = "美味可口"
WURT.DESCRIBE.GORGE_BAGEL_AND_FISH = "不——————！"
WURT.DESCRIBE.GORGE_GRILLED_CHEESE = "好吃, 浮浪噗。"
WURT.DESCRIBE.GORGE_CREAMMUSHROOM = "好吃!"
WURT.DESCRIBE.GORGE_MANICOTTI = "好吃!"
WURT.DESCRIBE.GORGE_CHEESEBURGER = "咕噜... 它有肉。"
WURT.DESCRIBE.GORGE_FETTUCCINE = "闻起来不错, 浮浪噗。"
WURT.DESCRIBE.GORGE_ONION_SOUP = "好吃!"
WURT.DESCRIBE.GORGE_BREADED_CUTLET = "咕噜..."
WURT.DESCRIBE.GORGE_CREAMY_FISH = "*嗅嗅* *嗅嗅*"
WURT.DESCRIBE.GORGE_PIZZA = "咕噜……不好吃……"
WURT.DESCRIBE.GORGE_POT_ROAST = "咕噜..."
WURT.DESCRIBE.GORGE_CRAB_CAKE = "可怜的螃蟹 *嗅嗅*"
WURT.DESCRIBE.GORGE_STEAK_FRITES = "咕噜..."
WURT.DESCRIBE.GORGE_SHOOTER_SANDWICH = "啧啧..."
WURT.DESCRIBE.GORGE_BACON_WRAPPED = "咕噜..."
WURT.DESCRIBE.GORGE_CRAB_ROLL = "不——————!"
WURT.DESCRIBE.GORGE_MEAT_WELLINGTON = "咕噜..."
WURT.DESCRIBE.GORGE_CRAB_RAVIOLI = "不——————!"
WURT.DESCRIBE.GORGE_CARAMEL_CUBE = "哇！！！"
WURT.DESCRIBE.GORGE_SCONE = "甜的!"
WURT.DESCRIBE.GORGE_TRIFLE = "甜的!"
WURT.DESCRIBE.GORGE_CHEESECAKE = "好吃!"

WURT.DESCRIBE.DUCKYOUGLERMZ = "...闻起来很难闻！！"

WURT.DESCRIBE.KYNO_ALOE = "绿色植物，花草。"
WURT.DESCRIBE.KYNO_ALOE_COOKED = "Fwooshed 植物！"
WURT.DESCRIBE.KYNO_ALOE_GROUND = "绿色植物，花草。"
WURT.DESCRIBE.KYNO_ALOE_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.FARM_PLANT_KYNO_ALOE = "绿色植物, 浮浪噗。"
WURT.DESCRIBE.KYNO_ALOE_OVERSIZED = "绿色植物，浮浪噗。"
WURT.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "啊呜！"

WURT.DESCRIBE.KYNO_CUCUMBER = "海鲜小吃！"
WURT.DESCRIBE.KYNO_CUCUMBER_COOKED = "黏糊糊的！"
WURT.DESCRIBE.KYNO_CUCUMBER_GROUND = "海鲜小吃！"
WURT.DESCRIBE.KYNO_CUCUMBER_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "海上小吃！"
WURT.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "海鲜小吃！"
WURT.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "海上小吃！"

WURT.DESCRIBE.KYNO_RADISH = "无数个球！"
WURT.DESCRIBE.KYNO_RADISH_COOKED = "烤熟了！"
WURT.DESCRIBE.KYNO_RADISH_GROUND = "无数个球！"
WURT.DESCRIBE.KYNO_RADISH_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.FARM_PLANT_KYNO_RADISH = "数字球!"
WURT.DESCRIBE.KYNO_RADISH_OVERSIZED = "数字球!"
WURT.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "啊呜！"

WURT.DESCRIBE.KYNO_FENNEL = "好吃！"
WURT.DESCRIBE.KYNO_FENNEL_COOKED = "好吃！"
WURT.DESCRIBE.KYNO_FENNEL_GROUND = "好吃！"
WURT.DESCRIBE.KYNO_FENNEL_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "好吃!"
WURT.DESCRIBE.KYNO_FENNEL_OVERSIZED = "好吃!"
WURT.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "啊呜！"

WURT.DESCRIBE.KYNO_SWEETPOTATO = "甜点！"
WURT.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "热腾腾的甜点，小花！"
WURT.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "甜点！"
WURT.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "甜点！"
WURT.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "甜点！"
WURT.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "啊呜！"

WURT.DESCRIBE.KYNO_PARZNIP = "美味的根！"
WURT.DESCRIBE.KYNO_PARZNIP_COOKED = "美味的根！"
WURT.DESCRIBE.KYNO_PARZNIP_EATEN = "美味的根！"
WURT.DESCRIBE.KYNO_PARZNIP_GROUND = "美味的根！"
WURT.DESCRIBE.KYNO_PARZNIP_BIG = "美味的巨根！！"
WURT.DESCRIBE.KYNO_PARZNIP_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "美味的根！"
WURT.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "美味的根！"
WURT.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "啊呜！"

WURT.DESCRIBE.KYNO_TURNIP = "嗯，萝卜！"
WURT.DESCRIBE.KYNO_TURNIP_COOKED = "热萝卜！"
WURT.DESCRIBE.KYNO_TURNIP_GROUND = "嗯，萝卜！"
WURT.DESCRIBE.KYNO_TURNIP_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "嗯，萝卜！"
WURT.DESCRIBE.KYNO_TURNIP_OVERSIZED = "嗯，萝卜！"
WURT.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "啊呜！"

WURT.DESCRIBE.KYNO_RICE = "它...很棒。"
WURT.DESCRIBE.KYNO_RICE_COOKED = "它...很棒。"
WURT.DESCRIBE.KYNO_RICE_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "制作更美味的零食！"
WURT.DESCRIBE.FARM_PLANT_KYNO_RICE = "嗯，米饭！"
WURT.DESCRIBE.KYNO_RICE_OVERSIZED = "嗯，米饭！"
WURT.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "啊呜！"

WURT.DESCRIBE.KYNO_SEEDS_KIT = "微小的碎片"

WURT.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "长着肉……咕噜。",
	PICKED = "肉躲起来了！",
	WITHERED = "太干了。",
}

WURT.DESCRIBE.KYNO_LIMPETS = "蜗牛..."
WURT.DESCRIBE.KYNO_LIMPETS_COOKED = "烤熟的蜗牛，小花。"

WURT.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "啊……",
	PICKED = "现在没花了，浮浪噗。",
	BURNING = "坏火！坏！",
}

WURT.DESCRIBE.KYNO_LOTUS_ROOT = "我得把它们种在水里，浮浪噗。"
WURT.DESCRIBE.KYNO_LOTUS_FLOWER = "哇……我喜欢它！"
WURT.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "我想吃它。"

WURT.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "杂草。",
	PICKED = "它们晚点会再长出来的。",
	BURNING = "火伤害海里的植物了！",
}

WURT.DESCRIBE.KYNO_SEAWEEDS = "很滑！"
WURT.DESCRIBE.KYNO_SEAWEEDS_COOKED = "嗯嗯嗯！"
WURT.DESCRIBE.KYNO_SEAWEEDS_DRIED = "持续时间更长..."
WURT.DESCRIBE.KYNO_SEAWEEDS_ROOT = "我要把它们种在水里，花花公子。"

WURT.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "漂亮！",
	PICKED = "水帮它长大，浮浪噗！",
	BURNING = "不——！",
}

WURT.DESCRIBE.KYNO_TAROROOT_ROOT = "我得把它们种在水里，浮浪噗。"
WURT.DESCRIBE.KYNO_TAROROOT = "大紫好吃！"
WURT.DESCRIBE.KYNO_TAROROOT_COOKED = "带出紫色的味道，小花。"

WURT.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "我想要！",
	PICKED = "快点长回来！",
	BURNING = "火对水里的植物不好！",
}

WURT.DESCRIBE.KYNO_WATERYCRESS_ROOT = "我得把它们种在水里，浮浪噗。"
WURT.DESCRIBE.KYNO_WATERYCRESS = "我要！"

WURT.DESCRIBE.WATERYCRESSBOWL = "臭水，小花。"

WURT.DESCRIBE.KYNO_SALT = "奇怪的小锅。"

WURT.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "朋友们被困住了！",
	PICKED = "现在没贻贝了！",
	BURNING = "坏火！",
}

WURT.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "咕噜……抓朋友……"

WURT.DESCRIBE.CATFOOD = "小猫的食物，咕噜咕噜。"

WURT.DESCRIBE.KATFOOD = "小猫的食物，咕噜咕噜。"

WURT.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "上面有水果！！",
	PICKED = "现在没黄色食物了。",
	CHOPPED = "树没了，浮浪噗。",
	BURNING = "坏火！",
	BURNT = "全没了。",
}

WURT.DESCRIBE.KYNO_BANANA = "嗯……好水果，花花公子。"
WURT.DESCRIBE.KYNO_BANANA_COOKED = "好吃！"

WURT.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "大叶子！",
	PICKED = "现在没椰子了，浮浪噗。",
	CHOPPED = "树没了。",
	BURNING = "坏火！！",
	BURNT = "全没了。*抽泣*",
}

WURT.DESCRIBE.KYNO_KOKONUT = "树坚果！"
WURT.DESCRIBE.KYNO_KOKONUT_HALVED = "一半的伟大，沃比。"
WURT.DESCRIBE.KYNO_KOKONUT_COOKED = "好吃！"

WURT.DESCRIBE.BOWLOFPOPCORN = "他们爆炸了！"

WURT.DESCRIBE.FIGJUICE = "冷，小声！"

WURT.DESCRIBE.COCONUTWATER = "它尝起来很甜，花花公子。"

WURT.DESCRIBE.EYEBALLSPAGHETTI = "咕噜咕噜……"

WURT.DESCRIBE.FORGETMELOTS_SEEDS = "制作更美味的零食！"

WURT.DESCRIBE.FIRENETTLES_SEEDS = "制作更美味的零食！"

WURT.DESCRIBE.TILLWEED_SEEDS = "制作更美味的零食！"

WURT.DESCRIBE.KYNO_FLOATILIZER = "什么？只是一些便便。"

WURT.DESCRIBE.KYNO_TWIGGYNUTS = "嗯！"

WURT.DESCRIBE.KYNO_REPAIRTOOL = "修补者，浮浪噗。"

WURT.DESCRIBE.KYNO_KOI = "你真漂亮，小花。"
WURT.DESCRIBE.KYNO_KOI_COOKED = "（嗅探）"

WURT.DESCRIBE.KYNO_TROPICALFISH = "你好，小家伙。"
WURT.DESCRIBE.KYNO_TROPICALFISH_COOKED = "不——————！"

WURT.DESCRIBE.KYNO_NEONFISH = "你好朋友！"
WURT.DESCRIBE.KYNO_NEONFISH_COOKED = "（嗅探）"

WURT.DESCRIBE.KYNO_GROUPER = "你好，紫色的朋友！"
WURT.DESCRIBE.KYNO_GROUPER_COOKED = "（嗅）可怜的鱼……"
 
WURT.DESCRIBE.KYNO_PIERROTFISH = "你好黄色朋友！"
WURT.DESCRIBE.KYNO_PIERROTFISH_COOKED = "（闻）可怜的小鱼……"

WURT.DESCRIBE.KYNO_SALMONFISH = "你好鱼！"
WURT.DESCRIBE.KYNO_SALMONFISH_COOKED = "不！"

WURT.DESCRIBE.TURF_PINKPARK = "粉色草坪！！！"
WURT.DESCRIBE.TURF_STONECITY = "石头..."
WURT.DESCRIBE.TURF_FIELDS = "地面。"
WURT.DESCRIBE.TURF_TIDALMARSH = "记得我回家，小花。"

WURT.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "上面长东西了！",
	PICKED = "这玩意儿怎么弄啊，浮浪噗？",
}

WURT.DESCRIBE.KYNO_SALTRACK_INSTALLER = "这会越过咸水池吗？"

WURT.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "装在甜树上的东西！"

WURT.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "看起来像小房子！"

WURT.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "那个猪人怪怪的！",
	SLEEPING = "嘘！猪人在睡觉。",
}

WURT.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "里面有甜甜的东西！",
	CHOPPED = "有人把树弄走了！不是我！",
	SAPPED = "嗯，里面装满了甜甜的东西！",
	PICKED = "啊……啥都没了。",
	BURNING = "坏火！",
	BURNT = "全没了。",
}

WURT.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "树还好吗？",
	CHOPPED = "树没了。",
	SAPPED = "坏黏黏。",
	PICKED = "噗呃，甜甜的东西里有虫子卡住了。",
	BURNING = "火清洁！"",
	BURNT = "全没了。",
}

WURT.DESCRIBE.KYNO_SUGARTREE_BUD = "小种子尝起来很有趣，花花公子。"

WURT.DESCRIBE.KYNO_SUGARTREE_FLOWER = "咕噜，好丑的植物。"
WURT.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "咕噜，好丑的植物。"

WURT.DESCRIBE.KYNO_SUGARTREE_PETALS = "咕噜咕噜，好丑的植物。"

WURT.DESCRIBE.KYNO_PEBBLECRAB = "哇，太可爱了，沃比！"

WURT.DESCRIBE.KYNO_CRABMEAT = "（闻）可怜的螃蟹……"
WURT.DESCRIBE.KYNO_CRABMEAT_COOKED = "咕噜……看不见……"
WURT.DESCRIBE.KYNO_CRABMEAT_DRIED = "(嗅嗅）可怜的螃蟹..."

WURT.DESCRIBE.KYNO_CRABKINGMEAT = "(嗅嗅）可怜的螃蟹..."
WURT.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "（嗅）可怜的螃蟹..."
WURT.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "（嗅）可怜的螃蟹..."

WURT.DESCRIBE.KYNO_SLAUGHTERTOOL = "嗯？这是为了什么？"

WURT.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "一只鸡！",
	COOP = "鸟现在住这儿了。",
}

WURT.DESCRIBE.KYNO_CHICKEN_EGG = "里面有小鸡？"
WURT.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "哦！大蛋好重！"
WURT.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "不要！"

WURT.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "鸡的家！里面可能有蛋，浮浪噗。",
	FULL = "一堆蛋！",
	BURNT = "鸟的房子坏了……",
}

WURT.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "咕噜……它坏了。"

WURT.DESCRIBE.KYNO_COOKWARE_KIT = "哦-哦-哦，礼物？送给我的？"
WURT.DESCRIBE.KYNO_COOKWARE_SYRUP = "用于甜食。"
WURT.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "用于甜食。"
WURT.DESCRIBE.KYNO_COOKWARE_BIG_POT = "只是普通的锅，沃比。"
WURT.DESCRIBE.KYNO_COOKWARE_BIG = "只是普通的锅，沃比。"
WURT.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "小锅。"
WURT.DESCRIBE.KYNO_COOKWARE_SMALL = "小锅。"
WURT.DESCRIBE.KYNO_COOKWARE_GRILL = "让食物变得又热又好吃。"
WURT.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "用于让食物变得又热又好吃！"
WURT.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "小厨具。"
WURT.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "小厨具。"
WURT.DESCRIBE.KYNO_COOKWARE_ELDER = "用于甜食。"
WURT.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "食物炊具。"
WURT.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "不擅长处理易碎的东西......"
WURT.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "太小了！"
WURT.DESCRIBE.KYNO_COOKWARE_OVEN = "想知道要烤什么..."
WURT.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "想知道要烤什么..."
WURT.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "想知道要烤什么..."

WURT.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "翻！翻！",
	FLIPPED = "找到东西了！",
}

WURT.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "里面有什么？"

WURT.DESCRIBE.KYNO_SUGARFLY = "它很丑，但追起来很有趣，笨蛋。"
WURT.DESCRIBE.KYNO_SUGARFLYWINGS = "采摘，采摘！"

WURT.DESCRIBE.KYNO_WATERY_CRATE = "里面有什么？"

WURT.DESCRIBE.KYNO_TUNACAN = "不！里面有鱼？！"
WURT.DESCRIBE.KYNO_TUNACAN_OPEN = "不！鱼友们，朋友们...（呜咽）"

WURT.DESCRIBE.KYNO_CANNEDFOOD = "里面有食物？"
WURT.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "小金属里的美味食物，小家伙。"

WURT.DESCRIBE.KYNO_POP = "咕噜，有趣的味道。"

WURT.DESCRIBE.KYNO_MYSTERYMEAT = "糟糕"

WURT.DESCRIBE.KYNO_BOTTLE_SOUL = "咕噜……这是什么……？"

WURT.DESCRIBE.SOULSTEW = "咕噜……这是什么……？"

WURT.DESCRIBE.FORTUNECOOKIE = "里面的小故事，笨蛋。"

WURT.DESCRIBE.HORNOCUPIA = "满满当当，吃货！"

WURT.DESCRIBE.CHEESE_YELLOW = "嗯！"
WURT.DESCRIBE.CHEESE_WHITE = "好吃！"
WURT.DESCRIBE.CHEESE_KOALEFANT = "嗯！"

WURT.DESCRIBE.MILK_BOX = "味道不错，小花。"

WURT.DESCRIBE.WATERCUP = "*恶心极了*"

WURT.DESCRIBE.HONEYJAR = "甜，好吃！"

WURT.DESCRIBE.CRAB_ARTICHOKE = "哇，不！"

WURT.DESCRIBE.PEPPERROLLS = "咦呕...辛辣！"

WURT.DESCRIBE.KYNO_SAPHEALER = "适合甜树的嘘声，花花公子。"

WURT.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "破船……",
	PICKED = "蜗牛现在没了。",
	BURNING = "坏火！",
}

WURT.DESCRIBE.KYNO_GHOST_PIRATE = "他飘着呢！！！"

WURT.DESCRIBE.KYNO_BUCKET_EMPTY = "把东西放在里面，小花。"
WURT.DESCRIBE.KYNO_BUCKET_METAL = "把东西放进去，浮浪噗。"
WURT.DESCRIBE.KYNO_BUCKET_WATER = "咕噜！新鲜又好喝！"

WURT.DESCRIBE.KYNO_MILK_BEEFALO = "好吃，花花公子。"
WURT.DESCRIBE.KYNO_MILK_KOALEFANT = "好吃，花花公子。"

WURT.DESCRIBE.KYNO_CAP_DRIED = "好吃！"

WURT.DESCRIBE.KYNO_PLANTMEAT_DRIED = "闻起来很臭。"

WURT.DESCRIBE.KYNO_BREWBOOK = "就像这个，有食物图片！"

WURT.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "好奇怪。",
	BREWING_LONG = "要好久，浮浪噗。",
	BREWING_SHORT = "快好了，浮浪噗！",
	DONE = "好了！",
	BURNT = "火毁了它……",
}

WURT.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "好臭，浮浪噗。",
	BREWING_LONG = "要好久。",
	BREWING_SHORT = "快是我的了！",
	DONE = "甜甜的东西！",
	BURNT = "火毁了它。",
}

WURT.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "做甜好吃的东西的机器！",
	HONEY = "装满了好吃的甜东西，浮浪噗。",
	NECTAR = "还在等。",
	BURNING = "坏火！毁了一切！",
}

WURT.DESCRIBE.KYNO_NECTAR_POD = "嗯嗯嗯！"

WURT.DESCRIBE.KYNO_OAKTREE_POD = "里面有树，花花公子？"
WURT.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "嘘！"

WURT.DESCRIBE.KYNO_PIKO = "在偷东西！！"
WURT.DESCRIBE.KYNO_PIKO_ORANGE = "哇！花式尾巴！"

WURT.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "好看的树！",
	CHOPPED = "叶子现在是我的了，浮浪噗。",
	BURNING = "坏火！",
	BURNT = "全没了，浮浪噗。",
}

WURT.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "好多松鼠，咕噜噗……",
	BURNING = "坏火！坏！",
}

WURT.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "一个盒子。"

WURT.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "家在沼泽的地方，浮浪噗。",
	BURNT = "家没了……",
}

WURT.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "家在沼泽的地方，浮浪噗。",
	CRAFTED = "家现在好看了！",
	BURNT = "好臭……！",
}

WURT.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "朋友家里面好多东西！",
	OCCUPIED = "朋友肯定在睡觉，浮浪噗。",
}

WURT.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "朋友的东西！",
	EMPTY = "全没了，浮浪噗。",
}

WURT.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "终于找到一个正常的人了！"
WURT.DESCRIBE.KYNO_MEADOWISLAND_POND = "鱼友的家！"
WURT.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "沼泽植物。"
WURT.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "沙丘，小花。"
WURT.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "新朋友！"

WURT.DESCRIBE.KYNO_SAMMYHAT = "朋友送的帽子很酷！"

WURT.DESCRIBE.KINGFISHER = "它有一个大喙，小花。"

WURT.DESCRIBE.TOUCAN = "大鼻子！"
WURT.DESCRIBE.TOUCAN_CHUBBY = "大鼻子！"

WURT.DESCRIBE.WETGOOP2 = "通常像湿粘的东西......"

WURT.DESCRIBE.BEER = "提神！"

WURT.DESCRIBE.PALEALE = "清爽！"

WURT.DESCRIBE.TEAGREEN = "嗯……很好，花花公子。"

WURT.DESCRIBE.TEARED = "嗯……很好，花花公子。"

WURT.DESCRIBE.MEAD = "它让头感觉很模糊......"

WURT.DESCRIBE.KYNO_JELLY = "爪子都粘了。"

WURT.DESCRIBE.KYNO_MAYONNAISE = "好吃！"

WURT.DESCRIBE.TARTARSAUCE = "咕噜咕噜……"

WURT.DESCRIBE.KYNO_PICKLES = "好吃！"

WURT.DESCRIBE.KYNO_WINE = "味道很奇怪……"

WURT.DESCRIBE.KYNO_JUICE = "*咕噜*味道好笑..."

WURT.DESCRIBE.KYNO_POISON_FROGLEGS = "（闻，闻）哇！"
WURT.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "（闻，闻）哇！"

WURT.DESCRIBE.POISONFROGGLEBUNWICH = "这是一个糟糕的三明治。"

WURT.DESCRIBE.KYNO_BREWINGRECIPECARD = "...无法阅读！"

WURT.DESCRIBE.KYNO_OIL = "品味不佳，笨蛋。"

WURT.DESCRIBE.BERRYSUNDAE = "冷饮！"

WURT.DESCRIBE.CHOCOLATE_BLACK = "好吃！"
WURT.DESCRIBE.CHOCOLATE_WHITE = "好吃！"

WURT.DESCRIBE.TRICOLORDANGO = "好甜！"
 
WURT.DESCRIBE.FRIESFRENCH = "好吃！"

WURT.DESCRIBE.PIRATERUM = "咕噜……别喝那个！"

WURT.DESCRIBE.TWISTEDTEQUILA = "闻起来很奇怪！"

WURT.DESCRIBE.ONIONRINGS = "咕噜咕噜！！脆脆的蔬菜真好吃！"

WURT.DESCRIBE.DONUTS = "太棒了！"
WURT.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "太棒了！"
WURT.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "太棒了！"
 
WURT.DESCRIBE.CINNAMONROLL = "太棒了！"

WURT.DESCRIBE.GUMMYBEARGERS = "可爱的小熊！！"

WURT.DESCRIBE.PRETZEL = "好吃，浮浪噗。"

WURT.DESCRIBE.CORNINCUP = "吃玉米棒子作为额外松脆的零食，小花。"

WURT.DESCRIBE.COTTONCANDY = "好吃！"

WURT.DESCRIBE.ROASTEDHAZELNUTS = "脆脆的小树东西，浮浪噗。"

WURT.DESCRIBE.MONSTERMUFFIN = "味道不错，浮浪噗。"

WURT.DESCRIBE.PINKCAKE = "就像童话故事里的蛋糕！！"

WURT.DESCRIBE.CHIPSBAG = "脆脆的土豆，扑通扑通。"

WURT.DESCRIBE.LITTLEBREAD = "噢……闻起来很香，浮浪噗！"

WURT.DESCRIBE.HOTHOUND = "天哪..."

WURT.DESCRIBE.MILKSHAKE = "非常非常亲爱的！！"
WURT.DESCRIBE.MILKSHAKE_PRISMATIC = "非常非常亲爱的！！"

WURT.DESCRIBE.NACHOS = "咕噜……手指脏了……"

WURT.DESCRIBE.BANANA_PUDDING = "好吃！"

WURT.DESCRIBE.SEA_PUDDING = "不哦哦哦！"

WURT.DESCRIBE.TOM_KHA_SOUP = "好吃！"

WURT.DESCRIBE.MINERTREAT = "啊！看起来很好吃！"

WURT.DESCRIBE.RADISHSALAD = "看起来不错，但味道还不错。"

WURT.DESCRIBE.PUMPKIN_SOUP = "这是汤，浮浪噗。"

WURT.DESCRIBE.ALGAE_SOUP = "这是汤，浮浪噗。"

WURT.DESCRIBE.PARZNIP_SOUP = "这是汤，浮浪噗。"

WURT.DESCRIBE.NETTLEMEATED = "咕噜……"

WURT.DESCRIBE.KYNO_SUGAR = "你好，亲爱的！"

WURT.DESCRIBE.KYNO_BOTTLECAP = "闪亮！"

WURT.DESCRIBE.NUKACOLA = "嗬！"
WURT.DESCRIBE.NUKACOLA_QUANTUM = "嗖！"

WURT.DESCRIBE.LIVINGSANDWICH = "浮浪噗..."

WURT.DESCRIBE.DURIANSPLIT = "冷食！"

WURT.DESCRIBE.DURIANSOUP = "榴莲汤，浮浪噗。"

WURT.DESCRIBE.DURIANMEATED = "美味，闻起来像沼泽！！"

WURT.DESCRIBE.DURIANCHICKEN = "啊哈！美味的盛宴！"

WURT.DESCRIBE.LUNARSOUP = "蔬菜！！"

WURT.DESCRIBE.PURPLEWOBSTERSOUP = "不哦哦哦！"

WURT.DESCRIBE.WOBSTERMONSTER = "咕噜……"

WURT.DESCRIBE.SPIDERCAKE = "呃呃呃呃。"

WURT.DESCRIBE.SUGARBOMBS = "好吃！"

WURT.DESCRIBE.BERRYBOMBS = "爪子都粘住了。"

WURT.DESCRIBE.ONIGIRIS = "零食!!"

WURT.DESCRIBE.OMURICE = "小吃时间! 浮浪噗。"

WURT.DESCRIBE.PAELLA = "好吃!"

WURT.DESCRIBE.RISOTTO = "很细腻, 浮浪噗。"

WURT.DESCRIBE.RICESAKE = "咕噜..."

WURT.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "咕噜！！有刺！！"

WURT.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "咕噜！！有刺！",
	PICKED = "现在没水果了，浮浪噗。",
	WITHERED = "太干了。",
	BURNING = "啊！！着火了！！",
}

WURT.DESCRIBE.KYNO_PINEAPPLE = "长满尖刺的水果!!"
WURT.DESCRIBE.KYNO_PINEAPPLE_HALVED = "带刺的水果!!"
WURT.DESCRIBE.KYNO_PINEAPPLE_COOKED = "闻起来不错, 浮浪噗。"

WURT.DESCRIBE.PIZZA_TROPICAL = "咕噜..."

WURT.DESCRIBE.PINACOLADA = "不错!"

WURT.DESCRIBE.CHIMAS = "太好了!"

WURT.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "对植物有帮助，浮浪噗。",
	ON = "水好！",
}

WURT.DESCRIBE.KYNO_FOODSACK = "保持食物新鲜"

WURT.DESCRIBE.GUMMYWORMS = "好吃!"

WURT.DESCRIBE.SMORES = "好吃!"

WURT.DESCRIBE.NUKASHINE = "浮浪噗!"

WURT.DESCRIBE.ANTSLOG = "奇怪的食物！"

WURT.DESCRIBE.KYNO_WORM_BONE = "可怜的虫子。"

WURT.DESCRIBE.SPOOKY_BRAIN_NOODLES = "不是害怕.....！"
WURT.DESCRIBE.SPOOKY_BURGERZILLA = "噢噢!"
WURT.DESCRIBE.SPOOKY_DEADBREAD = "可怕!"
WURT.DESCRIBE.SPOOKY_JELLYBEANS = "噢噢!"
WURT.DESCRIBE.SPOOKY_POPSICLE = "好的，冰的！"
WURT.DESCRIBE.SPOOKY_PUMPKINCREAM = "臭臭的！"
WURT.DESCRIBE.SPOOKY_SKULLCANDY = "吓人"
WURT.DESCRIBE.SPOOKY_TACODILE = "可怕!"

WURT.DESCRIBE.BUTTER_BEEFALO = "真好吃！"
WURT.DESCRIBE.BUTTER_GOAT = "真好吃！"
WURT.DESCRIBE.BUTTER_KOALEFANT = "很美味！"

WURT.DESCRIBE.SPICE_CURE = "有利于节省食物。"
WURT.DESCRIBE.SPICE_COLD = "哇!"
WURT.DESCRIBE.SPICE_FIRE = "哎哟！"
WURT.DESCRIBE.SPICE_FED = "美味的！"
WURT.DESCRIBE.SPICE_MIND = "ZzZZZzz......"

WURT.DESCRIBE.SUGARFLYMUFFIN = "美味的"

WURT.DESCRIBE.EELTACOS = "鳗鱼在里面不开心......"

WURT.DESCRIBE.MEATSKILLET = "呃"

WURT.DESCRIBE.MEATWALTZ = "呃......"

WURT.DESCRIBE.COMPLETEBREAKFAST = "好多食物, 浮浪噗!"

WURT.DESCRIBE.DUMPLINGS = "呃......"

WURT.DESCRIBE.WARLYICEDTEA = "清爽，好喝！"

WURT.DESCRIBE.WARLYTEA = "甜蜜而放松, 浮浪噗。"

WURT.DESCRIBE.KYNO_TEALEAF = "闻起来很奇怪,  浮浪噗。"

WURT.DESCRIBE.KYNO_ITEMSLICER = "湿漉漉的！"
WURT.DESCRIBE.KYNO_ITEMSLICER_GOLD = "湿漉漉的！"

WURT.DESCRIBE.COXINHA = "不喜欢这个。"

WURT.DESCRIBE.LAZYDESSERT = "很坚固。"

WURT.DESCRIBE.CRABKINGFEAST = "呃...一大堆肉。"

WURT.DESCRIBE.PIENAPPLE = "尖尖的，但味道非常好，浮浪噗!"

WURT.DESCRIBE.JAWSBREAKER = "浮浪噗...吃不下！"

WURT.DESCRIBE.AVOCADOTOAST = "美味的面包配水果，浮浪噗！"

WURT.DESCRIBE.RICEPUDDING = "很美味！浮浪噗。"

WURT.DESCRIBE.SHARKSUSHI = "不不不！可怜的鲨鱼！"

WURT.DESCRIBE.WOBSTERBREADED = "不要再捏了..."

WURT.DESCRIBE.LAZYPURRITO = "哇!"

WURT.DESCRIBE.HORCHATA = "好吃！"

WURT.DESCRIBE.WOBSTERCOCKTAIL = "不！"

WURT.DESCRIBE.LAVAEEGGBOILED = "哎呀。很烫，浮浪噗！"

WURT.DESCRIBE.POMEGRANATETEA = "冷，走开！"

WURT.DESCRIBE.TIRAMISU = "美味"

WURT.DESCRIBE.TOADSTOOLCOLA = "浮浪噗，味道怪怪的！"

WURT.DESCRIBE.TEPACHE = "真好喝！"

WURT.DESCRIBE.LUNARTEQUILA = "月亮？"

WURT.DESCRIBE.MIMICMOSA = "哦，真糟糕！"

WURT.DESCRIBE.POMEGRANATEPIE = "美味！"

WURT.DESCRIBE.PINEAPPLECAKE = "看起来真美味！"

WURT.DESCRIBE.PASTY_MEAT = "不吃那个，浮浪噗！"
WURT.DESCRIBE.PASTY_CHEESE = "美味!"

WURT.DESCRIBE.BRIGADEIRO = "我想要更多！"

WURT.DESCRIBE.REGULARLASAGNA = "这...是什么？"

WURT.DESCRIBE.FLTSANDWICH = "不喜欢！"

WURT.DESCRIBE.RICEANDBEANS = "真好吃！"

WURT.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "可怕的房子……不过也许以后里面有好吃的，咕噜？2026年？"

WURT.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "蘑菇！咕噜！我喜欢！",
	PICKED = "没食物了。",
	BURNING = "火毁了好东西！",
}

WURT.DESCRIBE.KYNO_TRUFFLES = "味道很浓……但很好吃！"
WURT.DESCRIBE.KYNO_TRUFFLES_COOKED = "现在闻起来真香！"

WURT.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "用来展示食物的，浮浪噗！但是……之后能吃吗？",
	FULL = "食物看着好高级，浮浪噗。",
}

WURT.DESCRIBE.KYNO_SPORECAP = "呱！味道好臭！"
WURT.DESCRIBE.KYNO_SPORECAP_COOKED = "还是难吃，咕噜。"

WURT.DESCRIBE.KYNO_SPORECAP_DARK = "咕噜！好臭！"
WURT.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "咕噜……不好吃！"

WURT.DESCRIBE.KYNO_GOLDENAPPLE = "噢噢！亮闪闪的，好吃！"

WURT.DESCRIBE.TRUFFLESGRINDER = "闻起来怪怪的……但好吃。"

WURT.DESCRIBE.SPORECAPPIE = "咕噜……闻起来不错，但里面坏坏的！"

WURT.DESCRIBE.SPORECAP_SKEWERS = "蘑菇串！美味！"

WURT.DESCRIBE.TRUFFLEOIL = "闻起来怪怪的，浮浪噗……但也许好吃？"

WURT.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "看起来很容易建造！"
WURT.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "这是鱼友们的乐园，浮浪噗！"

WURT.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "鱼鱼朋友的家！耶~",
	FUEL_HIGH = "鱼吃得好！",
	FUEL_MED = "还行。",
	FUEL_LOW = "需要更多食物！",
	EMPTY = "鱼饿了！",
}

WURT.DESCRIBE.KYNO_ANTCHOVY = "咕噜！鱼腥味……怪怪的……"
WURT.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "咕噜！鱼朋友们来得太猛啦！"

WURT.DESCRIBE.AGEDROE = "不！！！"
WURT.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "你为什么吃鱼宝宝啊，浮浪噗？！"

WURT.DESCRIBE.KYNO_SWORDFISH_BLUE = "咕噜？！鱼怎么会忘记游动，浮浪噗？！"

WURT.DESCRIBE.KYNO_JELLYFISH = "一只奇怪的软趴趴的鱼！"
WURT.DESCRIBE.KYNO_JELLYFISH_DEAD = "不——！"
WURT.DESCRIBE.KYNO_JELLYFISH_COOKED = "不——！"
WURT.DESCRIBE.KYNO_JELLYFISH_DRIED = "不——！*呜咽*"

WURT.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "这可真够可疑的！"
WURT.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "*呜呜*"
WURT.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "可怜的朋友啊……*呜咽*"

WURT.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "它缺东西，浮浪噗。"

WURT.DESCRIBE.KYNO_OCEANTRAP = "咕噜！对鱼类朋友可不好……"

WURT.DESCRIBE.OCEANFISH_PUFFERFISH = "鱼朋友身上有好多尖尖的刺，浮浪噗！"
WURT.DESCRIBE.OCEANFISH_STURGEON = "大老鱼！力气真大，浮浪噗！"

WURT.DESCRIBE.KYNO_SWORDFISH = "咕噜！可怕的鱼怪！"
WURT.DESCRIBE.KYNO_SWORDFISH_DEAD = "*抽泣*"

WURT.DESCRIBE.SWORDFISHFEAST = "咕噜……可怜的小鱼朋友……"

WURT.DESCRIBE.KYNO_DOGFISH = "狗和鱼？就像沃尔特那样的宠物！"
WURT.DESCRIBE.KYNO_DOGFISH_DEAD = "不——！*抽泣*"

WURT.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "可怜的朋友。*呜呜*"

WURT.DESCRIBE.WOBSTER_MONKEYISLAND = "咕噜！时髦的龙虾朋友！"
WURT.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "不——！可怜的龙虾朋友！"
WURT.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "咕噜！坏蛋！为什么大家都总爱煮我的鱼朋友？"

WURT.DESCRIBE.KYNO_PUFFERMONSTER = "咕噜！坏小鱼，鼓鼓的！"

WURT.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "咕噜！或许能找到漂亮的鱼儿？"
WURT.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "可怜的朋友看起来很伤心。"
WURT.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "咕噜！大坏鱼！"
WURT.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "咕噜！可怜的朋友越来越大了……."

WURT.DESCRIBE.KYNO_BLUBBER = "它呜咽着，浮浪噗。"

WURT.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "咕噜……可怜的小鱼……"
WURT.DESCRIBE.KYNO_FISHMEAT_DRIED = "浮浪噗，你为什么要这样对待鱼？"

WURT.DESCRIBE.MONKEYISLANDMEAL = "为什么那样对可怜的龙虾？ *抽泣*"

WURT.DESCRIBE.KYNO_BRAINROCK_LARVAE = "是小虫子，浮浪噗。"
WURT.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "水岩脑蛋。"
WURT.DESCRIBE.KYNO_BRAINROCK_CORAL = "咕噜！这食物伤大脑！"

WURT.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "是聪明的石头！",
	PICKED = "石头现在安静了。",
}

WURT.DESCRIBE.BRAINMETTERSOUP = "喝汤能促进思考，浮浪噗？"

WURT.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "你想要什么？",
	SLEEPING = "海王现在睡觉了，浮浪噗。",
}

WURT.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "里面有好多东西！！"

WURT.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "可怜的小鱼鱼！",
	WAITING = "在打盹？",
}

WURT.DESCRIBE.KYNO_PACKIMBAGGIMS = "哎呀……一只友好的小鸟儿！"

WURT.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "嘎！我们需要更多食材来烹饪，浮浪噗。"
WURT.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "蛋糕看起来超～大！"
WURT.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "盛宴配大蛋糕，浮浪噗！"
WURT.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "蛋糕用的火棒！真有趣！"
WURT.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "看起来很美味。"
WURT.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "嗯！更多糖果！"
WURT.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "漂浮的小东西，浮浪噗！"

WURT.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "爆米花，对沃特好！",
	FUEL_HIGH = "还在转，浮浪噗！",
	FUEL_MED = "暂时还行。",
	FUEL_LOW = "需要燃料，浮浪噗。",
	EMPTY = "没有爆米花爆了……",
}

WURT.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "玉米噼里啪啦！有趣的食物，浮浪噗！"
WURT.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "给我戴生日帽？浮浪噗！"
WURT.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "只有萨米戴这个？真走运，浮浪噗！"

WURT.DESCRIBE.KYNO_FISHREGISTRYHAT = "帽子帮忙了解鱼朋友！咕噜！"

WURT.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "可爱的动物们在这儿吃饭，浮浪噗。",
	FUEL_HIGH = "好多食物！好。",
	FUEL_MED = "还行。",
	FUEL_LOW = "很快需要更多食物。",
	EMPTY = "空了！",
	BURNT = "火毁了它！咕噜……",
}

WURT.DESCRIBE.CHICKENNUGGETS = "可怜的鸡……*抽泣*"

WURT.DESCRIBE.CHICKENWINGS = "为什么要对鸡做这种事？！"

WURT.DESCRIBE.CHICKENBURGER = "为什么要对鸡做这种事？！"

WURT.DESCRIBE.CHICKENEGGSOUP = "很暖和。"

WURT.DESCRIBE.CHICKENEGGSTEW = "恶心！"

WURT.DESCRIBE.CHICKENROTISSERIE = "不——！可怜的鸟！"