local WOLFGANG = STRINGS.CHARACTERS.WOLFGANG

WOLFGANG.ANNOUNCE_KYNO_COFFEEBUFF_START = "沃尔夫冈更快！"
WOLFGANG.ANNOUNCE_KYNO_COFFEEBUFF_END = "沃尔夫冈现在变慢了！"

WOLFGANG.ANNOUNCE_KYNO_HASTEBUFF_START = "快速工作！"
WOLFGANG.ANNOUNCE_KYNO_HASTEBUFF_END = "沃尔夫冈的手感到头晕。"

WOLFGANG.ANNOUNCE_KYNO_POPBUFF_START = "（嗝！）沃尔夫冈很抱歉。"
WOLFGANG.ANNOUNCE_KYNO_POPBUFF_END = "哈！沃尔夫冈足够强壮，喝点有趣的酒！"

WOLFGANG.ANNOUNCE_KYNO_FROGBUFF_START = "哈！沃尔夫冈现在会欺骗小动物了！"
WOLFGANG.ANNOUNCE_KYNO_FROGBUFF_END = "沃尔夫冈不再是青蛙。"

WOLFGANG.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝!) 大海在等着我们!"
WOLFGANG.ANNOUNCE_KYNO_PIRATEBUFF_END = "哈！沃尔夫冈的酒量够大！"

WOLFGANG.ANNOUNCE_KYNO_FREEZEBUFF_START = "严寒会阻止坏蛋！"
WOLFGANG.ANNOUNCE_KYNO_FREEZEBUFF_END = "严寒消失..."

WOLFGANG.ANNOUNCE_KYNO_FIREBUFF_START = "毁灭与燃烧！"
WOLFGANG.ANNOUNCE_KYNO_FIREBUFF_END = "火焰熄灭了......"

WOLFGANG.ANNOUNCE_KYNO_FISHINGBUFF_START = "渔具准备好了。"
WOLFGANG.ANNOUNCE_KYNO_FISHINGBUFF_END = "沃尔夫冈的捕鱼能力下降了！"

WOLFGANG.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "沃尔夫冈现在可以放松一下了......"
WOLFGANG.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "沃尔夫冈的大脑已经足够放松了。"

WOLFGANG.ANNOUNCE_KYNO_EATERBUFF_START = "沃尔夫冈的嘴巴准备好接受一切了！"
WOLFGANG.ANNOUNCE_KYNO_EATERBUFF_END = "沃尔夫冈的嘴巴累了。"

WOLFGANG.ANNOUNCE_KYNO_WORMBUFF_START = "沃尔夫冈已经准备好打败虫子了！"
WOLFGANG.ANNOUNCE_KYNO_WORMBUFF_END = "沃尔夫冈在与虫子搏斗后感到疲倦。"

WOLFGANG.ANNOUNCE_KYNO_CRABBUFF_START = "沃尔夫冈主备好击败一些螃蟹了!"
WOLFGANG.ANNOUNCE_KYNO_CRABBUFF_END = "与螃蟹搏斗后，沃尔夫冈感到疲倦。"

WOLFGANG.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝！) 沃尔夫冈很抱歉。"
WOLFGANG.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "哈！沃尔夫冈已经足够强壮，可以喝有趣的青蛙饮料了！"

WOLFGANG.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "沃尔夫冈能感觉到！"
WOLFGANG.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "沃尔夫冈变弱了！"

WOLFGANG.ANNOUNCE_KYNO_STEALTHBUFF_START = "沃尔夫冈藏起来了。"
WOLFGANG.ANNOUNCE_KYNO_STEALTHBUFF_END = "沃尔夫冈不再隐形了！"

WOLFGANG.ANNOUNCE_KYNO_FEARBUFF_START = "小孩子才害怕！沃尔夫冈不会害怕！"
WOLFGANG.ANNOUNCE_KYNO_FEARBUFF_END = "胆小鬼的颤抖又回来了！呸！"

WOLFGANG.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "沃尔夫冈变得强大！"
WOLFGANG.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "沃尔夫冈的力量消失了！不！"

WOLFGANG.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "沃尔夫冈强壮！猪朋友跟随！"
WOLFGANG.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "沃尔夫冈想念猪朋友！"

WOLFGANG.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "沃尔夫冈强壮！酸弱小！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WOLFGANG.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "沃尔夫冈不怕小小毒药！"
WOLFGANG.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "沃尔夫冈又变弱了……"

WOLFGANG.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "沃尔夫冈的大脑感觉好大！现在就动手创造一切吧！"
WOLFGANG.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "大脑又感觉变小了……"

WOLFGANG.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "嗡嗡的小朋友们不想再蜇沃尔夫冈了！"
WOLFGANG.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "蜜蜂又生气了！沃尔夫冈要跑！"

WOLFGANG.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "沃尔夫冈变得更加强大！"
WOLFGANG.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "沃尔夫冈现在感觉没那么强大了……"

WOLFGANG.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "沃尔夫冈的肚子越来越大啦！"
WOLFGANG.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "沃尔夫冈的胃缩小了！"

WOLFGANG.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "沃尔夫冈的大脑感觉很强！"
WOLFGANG.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "沃尔夫冈的大脑又糊涂起来！"

WOLFGANG.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "沃尔夫冈受到强大力量的保护！"
WOLFGANG.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "沃尔夫冈失去了力量……"

WOLFGANG.ANNOUNCE_KYNO_BERSERKERBUFF_START = "Wolfgang is UNSTOPPABLE! Smash all things!"
WOLFGANG.ANNOUNCE_KYNO_BERSERKERBUFF_END = "Wolfgang no longer feels mighty rage..."

WOLFGANG.ANNOUNCE_KYNO_HUNGERRATEBUFF_START = "Wolfgang stays full longer!"
WOLFGANG.ANNOUNCE_KYNO_HUNGERRATEBUFF_END = "Wolfgang is hungry again..."

WOLFGANG.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "不是正确的答案。"

WOLFGANG.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "强大的猪不希望这样。"

WOLFGANG.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "小树不够强壮！"

WOLFGANG.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "这里用不上这个。" 

WOLFGANG.ANNOUNCE_KYNO_POTHANGER_FAIL = "不，也许是个锅！"

WOLFGANG.ANNOUNCE_KYNO_CASSEROLE_FAIL = "烤箱需要一个小锅！"

WOLFGANG.ANNOUNCE_KYNO_SAPHEALER_USED = "Wolfgang uses medicine to help poor tree be mighty again!"

WOLFGANG.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "沃尔夫冈让肉质鲜美又饱满！"

WOLFGANG.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "小推车是空的。"

WOLFGANG.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "小气泡消失了！沃尔夫冈困惑了！"
WOLFGANG.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "雨下得太猛了！沃尔夫冈看不见了！"
WOLFGANG.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "大海怪！沃尔夫冈已准备就绪！"

WOLFGANG.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "巨型蛋糕完成！沃尔夫冈自豪！"

WOLFGANG.ANNOUNCE_KYNO_FISH_RESEARCHED = "沃尔夫冈现在很懂这种小水肉了！"
WOLFGANG.ANNOUNCE_KYNO_ROE_RESEARCHED = "沃尔夫冈现在懂小鱼蛋了！"

WOLFGANG.DESCRIBE.KYNO_ROE = "是鱼卵。"
WOLFGANG.DESCRIBE.KYNO_ROE_COOKED = "小鸡蛋现在臭味少了。"

WOLFGANG.DESCRIBE.KYNO_SHARK_FIN = "我失去了剩下的鲨鱼。"

WOLFGANG.DESCRIBE.KYNO_BEANBUGS = "看起来像带腿的食物。"
WOLFGANG.DESCRIBE.KYNO_BEANBUGS_COOKED = "沃尔夫冈什么都吃！"

WOLFGANG.DESCRIBE.KYNO_GUMMYBUG = "黏糊糊的……但沃尔夫冈还在吃！"
WOLFGANG.DESCRIBE.KYNO_GUMMYBUG_COOKED = "是食物吗？沃尔夫冈还是会吃的！"

WOLFGANG.DESCRIBE.KYNO_WHEAT = "面粉！沃尔夫冈可以徒手研磨！"
WOLFGANG.DESCRIBE.KYNO_WHEAT_COOKED = "好吃！"

WOLFGANG.DESCRIBE.KYNO_FLOUR = "食物不合适！"

WOLFGANG.DESCRIBE.KYNO_SPOTSPICE = "沃尔夫冈会做美味的东西。"

WOLFGANG.DESCRIBE.KYNO_SAP = "是美味的树胶！"
WOLFGANG.DESCRIBE.KYNO_SAP_SPOILED = "沃尔夫冈不能用恶心的污泥做饭。"

WOLFGANG.DESCRIBE.KYNO_SYRUP = "美味的糖浆！"

WOLFGANG.DESCRIBE.KYNO_COFFEEBEANS = "小豆子给沃尔夫冈力量！"
WOLFGANG.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "真苦，是苦豆！"

WOLFGANG.DESCRIBE.DUG_KYNO_COFFEEBUSH = "Plant will grow again in better place!"

WOLFGANG.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "Coffee bush is pround, strong.",
	PICKED = "No beans for now.",
	WITHERED = "Plant is weak.",
}

WOLFGANG.DESCRIBE.DUG_KYNO_SPOTBUSH = "Bush needs ground!"

WOLFGANG.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "Is little shrub for eating.",
	PICKED = "Bush empty.",
	BURNING = "Fire eats bush!",
}

WOLFGANG.DESCRIBE.KYNO_SPOTSPICE_LEAF = "很不错的小装饰。"

WOLFGANG.DESCRIBE.KYNO_MUSSEL = "我的肌肉更大了！"
WOLFGANG.DESCRIBE.KYNO_MUSSEL_COOKED = "贻贝变成了肌肉的蛋白质！"

WOLFGANG.DESCRIBE.KYNO_HUMANMEAT = "他们比沃尔夫冈更好。"
WOLFGANG.DESCRIBE.KYNO_HUMANMEAT_COOKED = "巴布西亚的秘方！"
WOLFGANG.DESCRIBE.KYNO_HUMANMEAT_DRIED = "就像鞋胶，但比起以前更适合下口了！"

WOLFGANG.DESCRIBE.COFFEE = "强壮，像沃尔夫冈！"

WOLFGANG.DESCRIBE.BISQUE = "它会助长强大的拳头！"

WOLFGANG.DESCRIBE.JELLYOPOP = "看起来像糖果，但尝起来像肉！"

WOLFGANG.DESCRIBE.SHARKFINSOUP = "里面有小鲨鱼吗？"

WOLFGANG.DESCRIBE.TROPICALBOUILLABAISSE = "沃尔夫冈不知道该怎么称呼它。"

WOLFGANG.DESCRIBE.MUSSELBOUILLABAISE = "它属于沃尔夫冈的嘴。"

WOLFGANG.DESCRIBE.SWEETPOTATOSOUFFLE = "沃尔夫冈的最爱！"

WOLFGANG.DESCRIBE.FEIJOADA = "沃尔夫冈什么都吃。"

WOLFGANG.DESCRIBE.GUMMY_CAKE = "有嚼劲。像沃尔夫冈。"

WOLFGANG.DESCRIBE.HARDSHELL_TACOS = "是松脆的蜗牛皮。"

WOLFGANG.DESCRIBE.ICEDTEA = "很酷。像沃尔夫冈。"

WOLFGANG.DESCRIBE.NETTLELOSANGE = "有强烈的气味。像沃尔夫冈。"

WOLFGANG.DESCRIBE.SNAKEBONESOUP = "对沃尔夫冈来说食物太少了。"

WOLFGANG.DESCRIBE.STEAMEDHAMSANDWICH = "是令人垂涎的汉堡包。"

WOLFGANG.DESCRIBE.TEA = "沃尔夫冈喜欢下午茶时间！"

WOLFGANG.DESCRIBE.BUBBLETEA = "很酷，像沃尔夫冈。"

WOLFGANG.DESCRIBE.FRENCHONIONSOUP = "沃尔夫冈的食物太少了。"

WOLFGANG.DESCRIBE.SLAW = "是食物。有点像。"

WOLFGANG.DESCRIBE.LOTUSBOWL = "沃尔夫冈现在吃掉你。"

WOLFGANG.DESCRIBE.POI = "沃尔夫冈 不知道是什么。"

WOLFGANG.DESCRIBE.JELLYBEAN_HUNGER = "小味豆。"
WOLFGANG.DESCRIBE.JELLYBEAN_SUPER = "小味豆。"
WOLFGANG.DESCRIBE.JELLYBEAN_SANITY = "小味豆。"

WOLFGANG.DESCRIBE.BOWLOFGEARS = "不是食物。"

WOLFGANG.DESCRIBE.LONGPIGMEAL = "是人...肉..."

WOLFGANG.DESCRIBE.CUCUMBERSALAD = "不是菠菜，但也许还能用！"

WOLFGANG.DESCRIBE.DUG_KYNO_WILDWHEAT = "Plant needs ground!"

WOLFGANG.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "Tall food grass!",
	PICKED = "Food gone for now.",
	WITHERED = "Plant is weak.",
	BURNING = "Fire eats grain!",
}

WOLFGANG.DESCRIBE.KYNO_MEALGRINDER = "我们必须研磨谷物来做面包！"

WOLFGANG.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "Wolfgang could use in soups.",
	PICKED = "Wolfgang must wait for more mushrooms.",
	BURNING = "Fire eats mushrooms!",
}

WOLFGANG.DESCRIBE.GORGE_BREAD = "是面包。"
WOLFGANG.DESCRIBE.GORGE_SWEET_CHIPS = "小脆土豆片！"
WOLFGANG.DESCRIBE.GORGE_VEGETABLE_SOUP = "沃尔夫冈喜欢蔬菜！"
WOLFGANG.DESCRIBE.GORGE_JELLY_SANDWICH = "加果酱的小三明治！"
WOLFGANG.DESCRIBE.GORGE_FISH_STEW = "很好。"
WOLFGANG.DESCRIBE.GORGE_MEAT_STEW = "炖的是浓肉。"
WOLFGANG.DESCRIBE.GORGE_ONION_CAKE = "强大的素食蛋糕会让沃尔夫冈变得更加强大！"
WOLFGANG.DESCRIBE.GORGE_POTATO_PANCAKES = "沃尔夫冈的美味早餐！"
WOLFGANG.DESCRIBE.GORGE_POTATO_SOUP = "它将为强有力的拳击提供动力！"
WOLFGANG.DESCRIBE.GORGE_FISHBALL_SKEWERS = "小鱼串，哈哈！"
WOLFGANG.DESCRIBE.GORGE_MEAT_SKEWERS = "小肉串，哈哈！"
WOLFGANG.DESCRIBE.GORGE_STONE_SOUP = "它将为强有力的拳击提供动力！"
WOLFGANG.DESCRIBE.GORGE_CROQUETTE = "是美味的小球。"
WOLFGANG.DESCRIBE.GORGE_ROAST_VEGETABLES = "沃尔夫冈会碾碎小蔬菜！"
WOLFGANG.DESCRIBE.GORGE_MEATLOAF = "美食！"
WOLFGANG.DESCRIBE.GORGE_CARROT_SOUP = "它将为强有力的拳击提供动力！"
WOLFGANG.DESCRIBE.GORGE_FISHPIE = "小鱼头卡在馅饼里。"
WOLFGANG.DESCRIBE.GORGE_FISHCHIPS = "美味！"
WOLFGANG.DESCRIBE.GORGE_MEATPIE = "沃尔夫冈会处理这件事的。"
WOLFGANG.DESCRIBE.GORGE_SLIDERS = "小汉堡包，沃尔夫冈会把它们捏碎！"
WOLFGANG.DESCRIBE.GORGE_JELLY_ROLL = "黏糊糊的卷子。"
WOLFGANG.DESCRIBE.GORGE_CARROT_CAKE = "沃尔夫冈会用嘴咬碎这个蛋糕！"
WOLFGANG.DESCRIBE.GORGE_GARLICMASHED = "美味！"
WOLFGANG.DESCRIBE.GORGE_GARLICBREAD = "好闻。"
WOLFGANG.DESCRIBE.GORGE_TOMATO_SOUP = "它将为强有力的拳击提供动力！"
WOLFGANG.DESCRIBE.GORGE_SAUSAGE = "哈！小猪香肠。"
WOLFGANG.DESCRIBE.GORGE_CANDIEDFISH = "小鱼身上沾满糖浆。"
WOLFGANG.DESCRIBE.GORGE_STUFFEDMUSHROOM = "是不错的小蘑菇。"
WOLFGANG.DESCRIBE.GORGE_BRUSCHETTA = "是小面包配番茄酱！"
WOLFGANG.DESCRIBE.GORGE_HAMBURGER = "是小三明治。"
WOLFGANG.DESCRIBE.GORGE_FISHBURGER = "小三明治。"
WOLFGANG.DESCRIBE.GORGE_MUSHROOMBURGER = "小三明治。"
WOLFGANG.DESCRIBE.GORGE_FISH_STEAK = "很好。"
WOLFGANG.DESCRIBE.GORGE_CURRY = "沃尔夫冈喜欢它。"
WOLFGANG.DESCRIBE.GORGE_SPAGHETTI = "肉球让我强壮！"
WOLFGANG.DESCRIBE.GORGE_POACHEDFISH = "鱼不错！"
WOLFGANG.DESCRIBE.GORGE_SHEPHERD_PIE = "小羊们在哪里？"
WOLFGANG.DESCRIBE.GORGE_CANDY = "是用来粉碎的糖果！"
WOLFGANG.DESCRIBE.GORGE_BREAD_PUDDING = "力量布丁!"
WOLFGANG.DESCRIBE.GORGE_BERRY_TART = "小水果片和糖果。"
WOLFGANG.DESCRIBE.GORGE_MACARONI = "沃尔夫冈喜欢它。"
WOLFGANG.DESCRIBE.GORGE_BAGEL_AND_FISH = "面包配鱼很不错。"
WOLFGANG.DESCRIBE.GORGE_GRILLED_CHEESE = "是不错的早餐选择。"
WOLFGANG.DESCRIBE.GORGE_CREAMMUSHROOM = "是小蘑菇汤。"
WOLFGANG.DESCRIBE.GORGE_MANICOTTI = "需要更多奶酪！"
WOLFGANG.DESCRIBE.GORGE_CHEESEBURGER = "小三明治。"
WOLFGANG.DESCRIBE.GORGE_FETTUCCINE = "它让沃尔夫冈感到饥饿。"
WOLFGANG.DESCRIBE.GORGE_ONION_SOUP = "烂汤！"
WOLFGANG.DESCRIBE.GORGE_BREADED_CUTLET = "是小面包配肉。"
WOLFGANG.DESCRIBE.GORGE_CREAMY_FISH = "闻起来不错！"
WOLFGANG.DESCRIBE.GORGE_PIZZA = "披萨时间！"
WOLFGANG.DESCRIBE.GORGE_POT_ROAST = "是一大堆肉！"
WOLFGANG.DESCRIBE.GORGE_CRAB_CAKE = "哈!是小螃蟹饼。"
WOLFGANG.DESCRIBE.GORGE_STEAK_FRITES = "需要加点盐！"
WOLFGANG.DESCRIBE.GORGE_SHOOTER_SANDWICH = "三明治不错！"
WOLFGANG.DESCRIBE.GORGE_BACON_WRAPPED = "小包肉。"
WOLFGANG.DESCRIBE.GORGE_CRAB_ROLL = "蟹肉很少，沃尔夫冈会把它压碎！"
WOLFGANG.DESCRIBE.GORGE_MEAT_WELLINGTON = "美味可口！"
WOLFGANG.DESCRIBE.GORGE_CRAB_RAVIOLI = "蟹肉很少，沃尔夫冈会把它压碎！"
WOLFGANG.DESCRIBE.GORGE_CARAMEL_CUBE = "小方块不错，哈哈！"
WOLFGANG.DESCRIBE.GORGE_SCONE = "是小甜甜面包。"
WOLFGANG.DESCRIBE.GORGE_TRIFLE = "是小甜甜杯。"
WOLFGANG.DESCRIBE.GORGE_CHEESECAKE = "是微不足道的小蛋糕。"

WOLFGANG.DESCRIBE.DUCKYOUGLERMZ = "难闻的食物！"

WOLFGANG.DESCRIBE.KYNO_ALOE = "沃尔夫冈什么都吃。"
WOLFGANG.DESCRIBE.KYNO_ALOE_COOKED = "它让沃尔夫冈变得又大又壮。"
WOLFGANG.DESCRIBE.KYNO_ALOE_GROUND = "沃尔夫冈什么都吃。"
WOLFGANG.DESCRIBE.KYNO_ALOE_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.FARM_PLANT_KYNO_ALOE = "沃尔夫冈什么都吃。"
WOLFGANG.DESCRIBE.KYNO_ALOE_OVERSIZED = "沃尔夫冈什么都吃。"
WOLFGANG.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "对沃尔夫冈没有用！"

WOLFGANG.DESCRIBE.KYNO_CUCUMBER = "黏糊糊的海参！"
WOLFGANG.DESCRIBE.KYNO_CUCUMBER_COOKED = "海参让沃尔夫冈坚强到最后。"
WOLFGANG.DESCRIBE.KYNO_CUCUMBER_GROUND = "黏糊糊的海参！"
WOLFGANG.DESCRIBE.KYNO_CUCUMBER_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "黏糊糊的海参！"
WOLFGANG.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "黏糊糊的海参！"
WOLFGANG.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "黏糊糊的海参！"

WOLFGANG.DESCRIBE.KYNO_RADISH = "很辣。"
WOLFGANG.DESCRIBE.KYNO_RADISH_COOKED = "让沃尔夫冈的气息变得又大又强。"
WOLFGANG.DESCRIBE.KYNO_RADISH_GROUND = "很辣。"
WOLFGANG.DESCRIBE.KYNO_RADISH_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.FARM_PLANT_KYNO_RADISH = "很辣。"
WOLFGANG.DESCRIBE.KYNO_RADISH_OVERSIZED = "很辣。"
WOLFGANG.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "对沃尔夫冈没有用！"

WOLFGANG.DESCRIBE.KYNO_FENNEL = "是小植物。"
WOLFGANG.DESCRIBE.KYNO_FENNEL_COOKED = "我烤你，小家伙！我是最强的沃尔夫冈"
WOLFGANG.DESCRIBE.KYNO_FENNEL_GROUND = "是小植物。"
WOLFGANG.DESCRIBE.KYNO_FENNEL_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "是小植物。"
WOLFGANG.DESCRIBE.KYNO_FENNEL_OVERSIZED = "是小植物。"
WOLFGANG.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "对沃尔夫冈没有用！"

WOLFGANG.DESCRIBE.KYNO_SWEETPOTATO = "非常甜蜜！"
WOLFGANG.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "可以吃啦！"
WOLFGANG.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "非常甜蜜！"
WOLFGANG.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "非常甜!"
WOLFGANG.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "非常甜!"
WOLFGANG.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "对沃尔夫冈没有用！"

WOLFGANG.DESCRIBE.KYNO_PARZNIP = "就像胡萝卜。哈哈！"
WOLFGANG.DESCRIBE.KYNO_PARZNIP_COOKED = "就像胡萝卜。哈哈！"
WOLFGANG.DESCRIBE.KYNO_PARZNIP_EATEN = "就像胡萝卜。哈哈！"
WOLFGANG.DESCRIBE.KYNO_PARZNIP_GROUND = "就像胡萝卜。哈哈！"
WOLFGANG.DESCRIBE.KYNO_PARZNIP_BIG = "是大食物！"
WOLFGANG.DESCRIBE.KYNO_PARZNIP_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "就像胡萝卜。哈哈！"
WOLFGANG.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "就像胡萝卜。哈哈！"
WOLFGANG.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "对沃尔夫冈没有用！"

WOLFGANG.DESCRIBE.KYNO_TURNIP = "我会用在许多菜肴中！是的！"
WOLFGANG.DESCRIBE.KYNO_TURNIP_COOKED = "闻起来很香。"
WOLFGANG.DESCRIBE.KYNO_TURNIP_GROUND = "我会用在很多菜肴中！是的！"
WOLFGANG.DESCRIBE.KYNO_TURNIP_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "我会用在很多菜肴中！是的！"
WOLFGANG.DESCRIBE.KYNO_TURNIP_OVERSIZED = "我会用在很多菜肴中！是的！"
WOLFGANG.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "对沃尔夫冈没有用！"

WOLFGANG.DESCRIBE.KYNO_RICE = "是小小的嫩芽。"
WOLFGANG.DESCRIBE.KYNO_RICE_COOKED = "是小小的嫩芽。"
WOLFGANG.DESCRIBE.KYNO_RICE_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "种子太小。"
WOLFGANG.DESCRIBE.FARM_PLANT_KYNO_RICE = "我会在很多菜肴中使用！是的！"
WOLFGANG.DESCRIBE.KYNO_RICE_OVERSIZED = "我会在很多菜肴中使用！是的！"
WOLFGANG.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "对沃尔夫冈没有用！"

WOLFGANG.DESCRIBE.KYNO_SEEDS_KIT = "里面有小小的种子"

WOLFGANG.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "Looks like tiny snails for eating!",
	PICKED = "Tiny food is gone.",
	WITHERED = "Nothing lives here.",
}

WOLFGANG.DESCRIBE.KYNO_LIMPETS = "是蜗牛吗？也许吧。"
WOLFGANG.DESCRIBE.KYNO_LIMPETS_COOKED = "下去很粘。"

WOLFGANG.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "Is puny pond plant.",
	PICKED = "Plant needs rest.",
	BURNING = "Bad fire!",
}

WOLFGANG.DESCRIBE.KYNO_LOTUS_ROOT = "软趴趴的。"
WOLFGANG.DESCRIBE.KYNO_LOTUS_FLOWER = "是微不足道的池塘花。"
WOLFGANG.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "沃尔夫冈现在吃掉你。"

WOLFGANG.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "Strange weeds from the seas.",
	PICKED = "No more food now.",
	BURNING = "Fire beat water weed!",
}

WOLFGANG.DESCRIBE.KYNO_SEAWEEDS = "一种来自大海的杂草。"
WOLFGANG.DESCRIBE.KYNO_SEAWEEDS_COOKED = "沃尔夫冈强壮的胃会毁掉这一切！"
WOLFGANG.DESCRIBE.KYNO_SEAWEEDS_DRIED = "可食用。"
WOLFGANG.DESCRIBE.KYNO_SEAWEEDS_ROOT = "软软的。"

WOLFGANG.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "Is little purple plant! Ha ha!",
	PICKED = "Water helps it grow.",
	BURNING = "Root is gone!",
}

WOLFGANG.DESCRIBE.KYNO_TAROROOT_ROOT = "软趴趴的。"
WOLFGANG.DESCRIBE.KYNO_TAROROOT = "不是胡椒！"
WOLFGANG.DESCRIBE.KYNO_TAROROOT_COOKED = "没有蛋黄！蛋黄是最强的部分！"

WOLFGANG.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "Is little wet vegetable.",
	PICKED = "Will grow again.",
	BURNING = "Fire beats water plant!",
}

WOLFGANG.DESCRIBE.KYNO_WATERYCRESS_ROOT = "软趴趴的。"
WOLFGANG.DESCRIBE.KYNO_WATERYCRESS = "是小湿蔬菜。"

WOLFGANG.DESCRIBE.WATERYCRESSBOWL = "沃尔夫冈的肚子很暖和。"

WOLFGANG.DESCRIBE.KYNO_SALT = "让食物变得美味。"

WOLFGANG.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "Stick attracts tiny food!",
	PICKED = "Tiny food gone, must wait.",
	BURNING = "Fire eats food!",
}

WOLFGANG.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "贻贝喜欢小棍子。"

WOLFGANG.DESCRIBE.CATFOOD = "是给小伙伴们的食物！"

WOLFGANG.DESCRIBE.KATFOOD = "是给小伙伴们的食物！"

WOLFGANG.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "Hello, upside-down tree.",
	PICKED = "Tree needs rest.",
	CHOPPED = "Tree is gone.",
	BURNING = "Fire is eating banana tree!",
	BURNT = "Tree is very gone.",
}

WOLFGANG.DESCRIBE.KYNO_BANANA = "好甜！"
WOLFGANG.DESCRIBE.KYNO_BANANA_COOKED = "又热又好吃！"

WOLFGANG.DESCRIBE.KYNO_KOKONUTTREE =
{
	GENERIC = "Such jovial tree.",
	PICKED = "Tree needs rest.",
	CHOPPED = "Tree is gone.",
	BURNING = "Fire eats coconut tree!",
	BURNT = "Tree is very gone.",
}

WOLFGANG.DESCRIBE.KYNO_KOKONUT = "沃尔夫冈 会赤手空拳碾碎。"
WOLFGANG.DESCRIBE.KYNO_KOKONUT_HALVED = "沃尔夫冈把硬壳敲开没有问题。"
WOLFGANG.DESCRIBE.KYNO_KOKONUT_COOKED = "椰子烤熟了。"

WOLFGANG.DESCRIBE.BOWLOFPOPCORN = "流行流行流行！"

WOLFGANG.DESCRIBE.FIGJUICE = "很酷。像沃尔夫冈。"

WOLFGANG.DESCRIBE.COCONUTWATER = "水的味道很有趣，呵呵。"

WOLFGANG.DESCRIBE.EYEBALLSPAGHETTI = "小眼球现在是食物，哈哈！"

WOLFGANG.DESCRIBE.FORGETMELOTS_SEEDS = "种子太小。"

WOLFGANG.DESCRIBE.FIRENETTLES_SEEDS = "种子太小。"

WOLFGANG.DESCRIBE.TILLWEED_SEEDS = "种子太小。"

WOLFGANG.DESCRIBE.KYNO_FLOATILIZER = "装满臭味的桶。"

WOLFGANG.DESCRIBE.KYNO_TWIGGYNUTS = "是树上的小坚果。"

WOLFGANG.DESCRIBE.KYNO_REPAIRTOOL = "恢复我的一切！"

WOLFGANG.DESCRIBE.KYNO_KOI = "是一条强大的鱼！"
WOLFGANG.DESCRIBE.KYNO_KOI_COOKED = "是一条强大的鱼！"

WOLFGANG.DESCRIBE.KYNO_TROPICALFISH = "看起来很好吃。"
WOLFGANG.DESCRIBE.KYNO_TROPICALFISH_COOKED = "是美味。"

WOLFGANG.DESCRIBE.KYNO_NEONFISH = "哈哈！好冷！"
WOLFGANG.DESCRIBE.KYNO_NEONFISH_COOKED = "烤鱼是很好的肌肉燃料。"

WOLFGANG.DESCRIBE.KYNO_GROUPER = "沃尔夫冈希望他像鱼一样游泳。"
WOLFGANG.DESCRIBE.KYNO_GROUPER_COOKED = "沃尔夫冈会吃到美味的鱼！"
 
WOLFGANG.DESCRIBE.KYNO_PIERROTFISH = "小鱼很干！"
WOLFGANG.DESCRIBE.KYNO_PIERROTFISH_COOKED = "小鱼会让沃尔夫冈变得强大！"

WOLFGANG.DESCRIBE.KYNO_SALMONFISH = "是软软的，软软的鱼。"
WOLFGANG.DESCRIBE.KYNO_SALMONFISH_COOKED = "鱼已经烤熟了。"

WOLFGANG.DESCRIBE.TURF_PINKPARK = "是小指。"
WOLFGANG.DESCRIBE.TURF_STONECITY = "阶梯石。"
WOLFGANG.DESCRIBE.TURF_FIELDS = "阶梯石。"
WOLFGANG.DESCRIBE.TURF_TIDALMARSH = "阶梯石。"

WOLFGANG.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "Is ready!",
	PICKED = "Is not ready yet.",
}

WOLFGANG.DESCRIBE.KYNO_SALTRACK_INSTALLER = "强大的双手可以快速完成工作。"

WOLFGANG.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "用于获取美味的树液。"

WOLFGANG.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "用于抓小钳子。"

WOLFGANG.DESCRIBE.KYNO_SERENITYISLAND_SHOP =
{
	GENERIC = "He seems like good fellow!",
	SLEEPING = "Boss is sleeping.",
}

WOLFGANG.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "Is little tree of yummy goop.",
	CHOPPED = "Tree has been cut down!",
	SAPPED = "Little bucket is full!",
	PICKED = "Little bucket needs to fill up.",
	BURNING = "Fire eats tree!",
	BURNT = "Tree is gone.",
}

WOLFGANG.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "Little tree has boo-boo.",
	CHOPPED = "Bad tree gone.",
	SAPPED = "Sticky bad stuff.",
	PICKED = "Wolfgang will crush tiny creatures.",
	BURNING = "Fire fix!",
	BURNT = "All gone!",
}

WOLFGANG.DESCRIBE.KYNO_SUGARTREE_BUD = "是小粉红树种子，哈哈！"

WOLFGANG.DESCRIBE.KYNO_SUGARTREE_FLOWER = "它们非常漂亮。"
WOLFGANG.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "它们非常漂亮。"

WOLFGANG.DESCRIBE.KYNO_SUGARTREE_PETALS = "它们非常漂亮。"

WOLFGANG.DESCRIBE.KYNO_PEBBLECRAB = "你好，小家伙！"

WOLFGANG.DESCRIBE.KYNO_CRABMEAT = "是小钳子的肉。"
WOLFGANG.DESCRIBE.KYNO_CRABMEAT_COOKED = "好吃，好吃的小钳子。"
WOLFGANG.DESCRIBE.KYNO_CRABMEAT_DRIED = "是小钳子的肉。"

WOLFGANG.DESCRIBE.KYNO_CRABKINGMEAT = "是大钳子的肉。"
WOLFGANG.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "是小钳子的肉。"
WOLFGANG.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "是小钳子的肉。"

WOLFGANG.DESCRIBE.KYNO_SLAUGHTERTOOL = "沃尔夫冈用来杀人。"

WOLFGANG.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "Little cluck bird.",
	COOP = "Chicken belongs to Wolfgang!",
}

WOLFGANG.DESCRIBE.KYNO_CHICKEN_EGG = "可怜的鸡。"
WOLFGANG.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "Is egg for giant chicken, or egg for mighty Wolfgang?"
WOLFGANG.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "好吃！"

WOLFGANG.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "Little house for tiny chickens!",
	FULL = "House is full of mighty eggs!",
	BURNT = "Chickens were not strong enough.",
}

WOLFGANG.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "坏了。"

WOLFGANG.DESCRIBE.KYNO_COOKWARE_KIT = "是我们厨房的小工具。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_SYRUP = "沃尔夫冈放入糖块。新的糖块出来了。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "沃尔夫冈放入糖块。新的糖块出来了。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_BIG_POT = "沃尔夫冈带来了最重要的成分：爱。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_BIG = "沃尔夫冈带来了最重要的成分：爱。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "朋友们，别看！锅需要烤沸。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_SMALL = "朋友们，别看！锅需要烤沸。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_GRILL = "正在烧食物。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "沃尔夫冈会把这个放在哪里？"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "在小食物上生火。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "沃尔夫冈需要把它放在某个地方。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_ELDER = "沃尔夫冈放入糖块。新的糖块出来了。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "是火箱位。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "沃尔夫冈忘记了卷心菜砂锅菜谱真是太丢脸了。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "可以用来做很少的食物。"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_OVEN = "朋友们！沃尔夫冈会为你做饭！"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "朋友们！沃尔夫冈会为你们做饭！"
WOLFGANG.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "朋友们！沃尔夫冈会为你做饭！"

WOLFGANG.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "Wolfgang strong. Wolfgang flip.",
	FLIPPED = "Tiny things were hiding!",
}

WOLFGANG.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "我不喜欢这个。太吓人了。"

WOLFGANG.DESCRIBE.KYNO_SUGARFLY = "很漂亮！"
WOLFGANG.DESCRIBE.KYNO_SUGARFLYWINGS = "没有翅膀就不能飞！"

WOLFGANG.DESCRIBE.KYNO_WATERY_CRATE = "我不喜欢这个。太吓人了。"

WOLFGANG.DESCRIBE.KYNO_TUNACAN = "我可以徒手打开！"
WOLFGANG.DESCRIBE.KYNO_TUNACAN_OPEN = "我可以徒手打开！"

WOLFGANG.DESCRIBE.KYNO_CANNEDFOOD = "我会徒手打开！"
WOLFGANG.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "我们现在吃吧。"

WOLFGANG.DESCRIBE.KYNO_POP = "沃尔夫冈不想喝酒。"

WOLFGANG.DESCRIBE.KYNO_MYSTERYMEAT = "我强大的胃可以承受！"

WOLFGANG.DESCRIBE.KYNO_BOTTLE_SOUL = "可怜的小灵魂，被困在里面了。"

WOLFGANG.DESCRIBE.SOULSTEW = "可怜的小灵魂。"

WOLFGANG.DESCRIBE.FORTUNECOOKIE = "有秘密的小饼干。"

WOLFGANG.DESCRIBE.HORNOCUPIA = "为强大的沃尔夫冈准备了满满当当的食物！"

WOLFGANG.DESCRIBE.CHEESE_YELLOW = "很臭！"
WOLFGANG.DESCRIBE.CHEESE_WHITE = "很臭！"
WOLFGANG.DESCRIBE.CHEESE_KOALEFANT = "很臭！"

WOLFGANG.DESCRIBE.MILK_BOX = "非常好！"

WOLFGANG.DESCRIBE.WATERCUP = "只是水。"

WOLFGANG.DESCRIBE.HONEYJAR = "粘滞的。"

WOLFGANG.DESCRIBE.CRAB_ARTICHOKE = "小石头这样好吃！"

WOLFGANG.DESCRIBE.PEPPERROLLS = "沃尔夫冈喜欢辛辣的挑战！"

WOLFGANG.DESCRIBE.KYNO_SAPHEALER = "沃尔夫冈会帮助小树！"

WOLFGANG.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "Not mighty enough to float.",
	PICKED = "No more tiny food.",
	BURNING = "Boat is finished!",
}

WOLFGANG.DESCRIBE.KYNO_GHOST_PIRATE = "啊啊啊！！"

WOLFGANG.DESCRIBE.KYNO_BUCKET_EMPTY = "小桶有助于沃尔夫冈的任务。"
WOLFGANG.DESCRIBE.KYNO_BUCKET_METAL = "小金属桶帮助沃尔福冈完成任务。"
WOLFGANG.DESCRIBE.KYNO_BUCKET_WATER = "装满了水！沃尔夫冈小心别洒了。"

WOLFGANG.DESCRIBE.KYNO_MILK_BEEFALO = "牛奶增肌！"
WOLFGANG.DESCRIBE.KYNO_MILK_KOALEFANT = "牛奶增肌！"

WOLFGANG.DESCRIBE.KYNO_CAP_DRIED = "沃尔夫冈肚皮干蘑菇！"

WOLFGANG.DESCRIBE.KYNO_PLANTMEAT_DRIED = "看起来像蔬菜，尝起来像肉。"

WOLFGANG.DESCRIBE.KYNO_BREWBOOK = "这是一本可以填满沃尔夫冈大肚子的东西！"

WOLFGANG.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "Little barrel makes good stuff for Wolfgang!",
	BREWING_LONG = "Strong brew needs strong patience.",
	BREWING_SHORT = "Brew almost ready!",
	DONE = "Ha! Drink is done!",
	BURNT = "No drink for Wolfgang.",
}

WOLFGANG.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "Little cask helps Wolfgang make sweet stuff!",
	BREWING_LONG = "Good food needs long time.",
	BREWING_SHORT = "Almost ready!",
	DONE = "Ha! Preserves are done!",
	BURNT = "All gone.",
}

WOLFGANG.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "Sweet stuff for Wolfgang!",
	HONEY = "Chest is full of sweet honey!",
	NECTAR = "Bees work hard on nectar.",
	BURNING = "Oh no! Sweet chest is burning!",
}

WOLFGANG.DESCRIBE.KYNO_NECTAR_POD = "像蜂蜜一样甜。"

WOLFGANG.DESCRIBE.KYNO_OAKTREE_POD = "是小树种。"
WOLFGANG.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "沃尔夫冈吃小树宝宝。"

WOLFGANG.DESCRIBE.KYNO_PIKO = "小而弱的绒毛。"
WOLFGANG.DESCRIBE.KYNO_PIKO_ORANGE = "微小的、微弱的橙色绒毛。"

WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "Is strong but not strong like Wolfgang.",
	CHOPPED = "Wolfgang take all leaves!",
	BURNING = "Fire bad!",
	BURNT = "Tree is gone.",
}

WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "Ha. It is infested with little guys!",
	BURNING = "Fire chase them away!",
}

WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "我可以粉碎。"

WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "Weird-looking people house.",
	BURNT = "The house was not strong enough.",
}

WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "Ugly house!",
	CRAFTED = "House looks nicer now.",
	BURNT = "Smell is very bad!",
}

WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "Fish buddy has many rare stuff in there.",
	OCCUPIED = "Shop man is sleeping.",
}

WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "Has many stuff selling.",
	EMPTY = "Nothing left to rummage.",
}

WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "很高兴见到你，伙计。"
WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_POND = "当我把鱼刺进去时，它们会咬脚趾。"
WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "是植物。"
WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "小而易碎的小山丘！"
WOLFGANG.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "让我们战斗！"

WOLFGANG.DESCRIBE.KYNO_SAMMYHAT = "小帽子保护沃尔夫冈的脑袋。"

WOLFGANG.DESCRIBE.KINGFISHER = "瘦鸟是大嘴。"

WOLFGANG.DESCRIBE.TOUCAN = "为什么鸟会飞离沃尔夫冈？"
WOLFGANG.DESCRIBE.TOUCAN_CHUBBY = "为什么鸟会飞离沃尔夫冈？"

WOLFGANG.DESCRIBE.WETGOOP2 = "沃尔夫冈毁了食物！"

WOLFGANG.DESCRIBE.BEER = "好清爽！沃尔夫冈喜欢！"

WOLFGANG.DESCRIBE.PALEALE = "好清爽！沃尔夫冈喜欢！"

WOLFGANG.DESCRIBE.TEAGREEN = "啊……很好。"

WOLFGANG.DESCRIBE.TEARED = "啊……很好。"

WOLFGANG.DESCRIBE.MEAD = "是甜酒！"

WOLFGANG.DESCRIBE.KYNO_JELLY = "像我捏碎的小敌人一样渗出液体。"

WOLFGANG.DESCRIBE.KYNO_MAYONNAISE = "好吃！"

WOLFGANG.DESCRIBE.TARTARSAUCE = "好吃！"

WOLFGANG.DESCRIBE.KYNO_PICKLES = "罐子里的小泡菜，哈哈。"

WOLFGANG.DESCRIBE.KYNO_WINE = "是好酒！"

WOLFGANG.DESCRIBE.KYNO_JUICE = "果汁很好喝！"

WOLFGANG.DESCRIBE.KYNO_POISON_FROGLEGS = "危险的青蛙部位！"
WOLFGANG.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "即使是危险的食物也会让沃尔夫冈变得强大。"

WOLFGANG.DESCRIBE.POISONFROGGLEBUNWICH = "是带有美味腿肉的三明治。"

WOLFGANG.DESCRIBE.KYNO_BREWINGRECIPECARD = "沃尔夫冈看不懂小字！"

WOLFGANG.DESCRIBE.KYNO_OIL = "是制作食物的原料！"

WOLFGANG.DESCRIBE.BERRYSUNDAE = "嗯，毕竟是星期天。"

WOLFGANG.DESCRIBE.CHOCOLATE_BLACK = "一小块巧克力！"
WOLFGANG.DESCRIBE.CHOCOLATE_WHITE = "一小块巧克力！"

WOLFGANG.DESCRIBE.TRICOLORDANGO = "是甜蜜的小球！"
 
WOLFGANG.DESCRIBE.FRIESFRENCH = "味道好又脆！"

WOLFGANG.DESCRIBE.PIRATERUM = "不安全！"

WOLFGANG.DESCRIBE.TWISTEDTEQUILA = "沃尔夫冈喝点酒还不够厉害！"

WOLFGANG.DESCRIBE.ONIONRINGS = "用油洗过的小洋葱。"

WOLFGANG.DESCRIBE.DONUTS = "是小糖球！"
WOLFGANG.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "是小糖球！"
WOLFGANG.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "是小糖球！"
 
WOLFGANG.DESCRIBE.CINNAMONROLL = "一个非常甜的小面包！"

WOLFGANG.DESCRIBE.GUMMYBEARGERS = "是小熊糖果，哈哈！"

WOLFGANG.DESCRIBE.PRETZEL = "是小结的食物！"

WOLFGANG.DESCRIBE.CORNINCUP = "小杯子里有一堆玉米小块。"

WOLFGANG.DESCRIBE.COTTONCANDY = "是小毛糖！"

WOLFGANG.DESCRIBE.ROASTEDHAZELNUTS = "热，热！"

WOLFGANG.DESCRIBE.MONSTERMUFFIN = "可怕的小松饼！"

WOLFGANG.DESCRIBE.PINKCAKE = "是个很棒的蛋糕，就像沃尔夫冈一样！"

WOLFGANG.DESCRIBE.CHIPSBAG = "现在更好了！"

WOLFGANG.DESCRIBE.LITTLEBREAD = "是面包。"

WOLFGANG.DESCRIBE.HOTHOUND = "是小面包加香肠和番茄酱。"

WOLFGANG.DESCRIBE.MILKSHAKE = "是一个强大的牛奶杯！"
WOLFGANG.DESCRIBE.MILKSHAKE_PRISMATIC = "是强大的乳白色杯子！"

WOLFGANG.DESCRIBE.NACHOS = "沃尔夫冈的手指一团糟！"

WOLFGANG.DESCRIBE.BANANA_PUDDING = "是一小碗布丁，哈哈！"

WOLFGANG.DESCRIBE.SEA_PUDDING = "是一小碗布丁，哈哈！"

WOLFGANG.DESCRIBE.TOM_KHA_SOUP = "强力汤会让沃尔夫冈变得更加强大！"

WOLFGANG.DESCRIBE.MINERTREAT = "是小孩子的零食。"

WOLFGANG.DESCRIBE.RADISHSALAD = "不是菠菜，但也许仍然有效！"

WOLFGANG.DESCRIBE.PUMPKIN_SOUP = "它将为强大的拳头提供燃料！"

WOLFGANG.DESCRIBE.ALGAE_SOUP = "它将助长强大的拳头！"

WOLFGANG.DESCRIBE.PARZNIP_SOUP = "它将助长强大的拳头！"

WOLFGANG.DESCRIBE.NETTLEMEATED = "肉食可以清除沃尔夫冈强大的鼻孔。"

WOLFGANG.DESCRIBE.KYNO_SUGAR = "好吃！"

WOLFGANG.DESCRIBE.KYNO_BOTTLECAP = "来自那杯饮料！"

WOLFGANG.DESCRIBE.NUKACOLA = "哈哈，是一种有趣的模糊饮料！"
WOLFGANG.DESCRIBE.NUKACOLA_QUANTUM = "哈哈，真是有趣的模糊饮料！"

WOLFGANG.DESCRIBE.LIVINGSANDWICH = "不健康的食物！"

WOLFGANG.DESCRIBE.DURIANSPLIT = "一点也不差。"

WOLFGANG.DESCRIBE.DURIANSOUP = "沃尔夫冈的食物太少了。"

WOLFGANG.DESCRIBE.DURIANMEATED = "尖刺臭餐！"

WOLFGANG.DESCRIBE.DURIANCHICKEN = "是火鸡形式的大蔬菜。"

WOLFGANG.DESCRIBE.LUNARSOUP = "是光滑的月菇汤！"

WOLFGANG.DESCRIBE.PURPLEWOBSTERSOUP = "是美味的小龙虾汤！"

WOLFGANG.DESCRIBE.WOBSTERMONSTER = "沃尔夫冈无论如何都会吃掉它！"

WOLFGANG.DESCRIBE.SPIDERCAKE = "这是小蜘蛛蛋糕！"

WOLFGANG.DESCRIBE.SUGARBOMBS = "小炸弹。"

WOLFGANG.DESCRIBE.BERRYBOMBS = "像我手中的小敌人一样渗出。"

WOLFGANG.DESCRIBE.ONIGIRIS = "是小三角形的米饭！"

WOLFGANG.DESCRIBE.OMURICE = "脆脆的。"

WOLFGANG.DESCRIBE.PAELLA = "小鱼配米饭。"

WOLFGANG.DESCRIBE.RISOTTO = "小蘑菇配米饭，沃尔夫冈很喜欢！"

WOLFGANG.DESCRIBE.RICESAKE = "哦..."

WOLFGANG.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "Needs transplant!"

WOLFGANG.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "Spiky fruit!",
	PICKED = "No fruit right now.",
	WITHERED = "Bush is weak.",
	BURNING = "Fire eats bush!",
}

WOLFGANG.DESCRIBE.KYNO_PINEAPPLE = "沃尔夫冈会徒手碾碎。"
WOLFGANG.DESCRIBE.KYNO_PINEAPPLE_HALVED = "沃尔夫冈喜欢它。"
WOLFGANG.DESCRIBE.KYNO_PINEAPPLE_COOKED = "闻起来不错。"

WOLFGANG.DESCRIBE.PIZZA_TROPICAL = "是带一片菠萝的小披萨！"

WOLFGANG.DESCRIBE.PINACOLADA = "好冷！"

WOLFGANG.DESCRIBE.CHIMAS = "奇怪的酿造，但沃尔夫冈还是喝了！"

WOLFGANG.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "Sprayer is sleeping.",
	ON = "Weeee! Wolfgang play in sprinkler!",
}

WOLFGANG.DESCRIBE.KYNO_FOODSACK = "沃尔夫冈能背更多东西了！"

WOLFGANG.DESCRIBE.GUMMYWORMS = "是甜的小虫子。"

WOLFGANG.DESCRIBE.SMORES = "是小小的棉花糖饼干。"

WOLFGANG.DESCRIBE.NUKASHINE = "奇怪的饮料让沃尔夫冈头脑一片空白。"

WOLFGANG.DESCRIBE.ANTSLOG = "哎呀!"

WOLFGANG.DESCRIBE.KYNO_WORM_BONE = "沃尔夫冈赢了。"

WOLFGANG.DESCRIBE.SPOOKY_BRAIN_NOODLES = "小脑筋。"
WOLFGANG.DESCRIBE.SPOOKY_BURGERZILLA = "是小怪物汉堡，沃尔夫冈会把它碾碎！"
WOLFGANG.DESCRIBE.SPOOKY_DEADBREAD = "小小的可怕面包"
WOLFGANG.DESCRIBE.SPOOKY_JELLYBEANS = "令人毛骨悚然！"
WOLFGANG.DESCRIBE.SPOOKY_POPSICLE = "味道怪怪的。"
WOLFGANG.DESCRIBE.SPOOKY_PUMPKINCREAM = "是美味的奶油小南瓜。"
WOLFGANG.DESCRIBE.SPOOKY_SKULLCANDY = "这是一种吓人的小糖果。"
WOLFGANG.DESCRIBE.SPOOKY_TACODILE = "是墨西哥卷饼小怪物，哈哈。"

WOLFGANG.DESCRIBE.BUTTER_BEEFALO = "咸的小块黄油。"
WOLFGANG.DESCRIBE.BUTTER_GOAT = "黄油是小山羊做的，哈哈！"
WOLFGANG.DESCRIBE.BUTTER_KOALEFANT = "这是来自考拉象的小黄油。"

WOLFGANG.DESCRIBE.SPICE_CURE = "将帮助沃尔夫冈保证食品安全！"
WOLFGANG.DESCRIBE.SPICE_COLD = "好冷！"
WOLFGANG.DESCRIBE.SPICE_FIRE = "很热！"
WOLFGANG.DESCRIBE.SPICE_FED = "将帮助沃尔夫冈实现强大！"
WOLFGANG.DESCRIBE.SPICE_MIND = "为了安抚沃尔夫冈的头脑！"

WOLFGANG.DESCRIBE.SUGARFLYMUFFIN = "沃尔夫冈不知道虫子松饼。我来尝尝。"

WOLFGANG.DESCRIBE.EELTACOS = "沃尔夫冈希望不要太辣。"

WOLFGANG.DESCRIBE.MEATSKILLET = "太辣了！"

WOLFGANG.DESCRIBE.MEATWALTZ = "几乎是生肉配面包。"

WOLFGANG.DESCRIBE.COMPLETEBREAKFAST = "至少开始我的早晨。"

WOLFGANG.DESCRIBE.DUMPLINGS = "沃尔夫冈喜欢饺子。"

WOLFGANG.DESCRIBE.WARLYICEDTEA = "很酷。就像沃尔夫冈。"

WOLFGANG.DESCRIBE.WARLYTEA = "沃尔夫冈爱喝茶！"

WOLFGANG.DESCRIBE.KYNO_TEALEAF = "是泡茶用的小叶子。"

WOLFGANG.DESCRIBE.KYNO_ITEMSLICER = "啊！ 很好！"
WOLFGANG.DESCRIBE.KYNO_ITEMSLICER_GOLD = "啊！ 很好！"

WOLFGANG.DESCRIBE.COXINHA = "这是一点小吃。"

WOLFGANG.DESCRIBE.LAZYDESSERT = "冰糖"

WOLFGANG.DESCRIBE.CRABKINGFEAST = "太大了！"

WOLFGANG.DESCRIBE.PIENAPPLE = "奇怪！沃尔夫冈看不到任何苹果。.."

WOLFGANG.DESCRIBE.JAWSBREAKER = "这是给鲨鱼的小零食。"

WOLFGANG.DESCRIBE.AVOCADOTOAST = "是小吐司。"

WOLFGANG.DESCRIBE.RICEPUDDING = "沃尔夫冈喜欢混合米饭！"

WOLFGANG.DESCRIBE.SHARKSUSHI = "沃尔夫冈迫不及待想吃了！"

WOLFGANG.DESCRIBE.WOBSTERBREADED = "别再捏了。"

WOLFGANG.DESCRIBE.LAZYPURRITO = "这是一个小猫卷饼。"

WOLFGANG.DESCRIBE.HORCHATA = "冰冻的！"

WOLFGANG.DESCRIBE.WOBSTERCOCKTAIL = "这是苦味的龙虾饮料。"

WOLFGANG.DESCRIBE.LAVAEEGGBOILED = "哎哟，热，热！"

WOLFGANG.DESCRIBE.POMEGRANATETEA = "很酷。就像沃尔夫冈。"

WOLFGANG.DESCRIBE.TIRAMISU = "鹅人饮料。"

WOLFGANG.DESCRIBE.TOADSTOOLCOLA = "沃尔夫冈不喜欢喝那个。"

WOLFGANG.DESCRIBE.TEPACHE = "这是一款非常甜美的水果饮料。"

WOLFGANG.DESCRIBE.LUNARTEQUILA = "这是一款功效强大的饮品！"

WOLFGANG.DESCRIBE.MIMICMOSA = "这是偷偷摸摸的饮料。"

WOLFGANG.DESCRIBE.POMEGRANATEPIE = "这是美味的红馅派！"

WOLFGANG.DESCRIBE.PINEAPPLECAKE = "这是大菠萝蛋糕。"

WOLFGANG.DESCRIBE.PASTY_MEAT = "滑溜溜的。"
WOLFGANG.DESCRIBE.PASTY_CHEESE = "滑溜溜的。"

WOLFGANG.DESCRIBE.BRIGADEIRO = "这是一颗小小的巧克力球！"

WOLFGANG.DESCRIBE.REGULARLASAGNA = "面条和肉！"

WOLFGANG.DESCRIBE.FLTSANDWICH = "蛙腿三明治，真好吃！"

WOLFGANG.DESCRIBE.RICEANDBEANS = "这是健康烹饪的小豆虫！"

WOLFGANG.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "小房子好弱……也许2026年会变强！"

WOLFGANG.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "Tiny mushrooms hiding in ground! Wolfgang found them!",
	PICKED = "Wolfgang wants more!",
	BURNING = "Fire ruin good food!",
}

WOLFGANG.DESCRIBE.KYNO_TRUFFLES = "味道好浓！沃尔夫冈饿了！"
WOLFGANG.DESCRIBE.KYNO_TRUFFLES_COOKED = "嗯！味道强烈又美味！"

WOLFGANG.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "Wolfgang show food! Make Wolfgang proud and hungry!",
	FULL = "Wolfgang made mighty meal!",
}

WOLFGANG.DESCRIBE.KYNO_SPORECAP = "小蘑菇生病了！"
WOLFGANG.DESCRIBE.KYNO_SPORECAP_COOKED = "沃尔夫冈让坏蘑菇变好一点！"

WOLFGANG.DESCRIBE.KYNO_SPORECAP_DARK = "坏蘑菇！会让沃尔夫冈生病！"
WOLFGANG.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "沃尔夫冈不吃这个。"

WOLFGANG.DESCRIBE.KYNO_GOLDENAPPLE = "强大的苹果！"

WOLFGANG.DESCRIBE.TRUFFLESGRINDER = "沃尔夫冈吃高级泥巴三明治会变强！"

WOLFGANG.DESCRIBE.SPORECAPPIE = "沃尔夫冈不确定是食物还是毒药……"

WOLFGANG.DESCRIBE.SPORECAP_SKEWERS = "Wolfgang喜欢蘑菇串！好吃！"

WOLFGANG.DESCRIBE.TRUFFLEOIL = "小瓶子，大味道！沃尔夫冈不知道是饿了还是怕了。"

WOLFGANG.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "若沃尔夫冈建造它，他们自会前来。"
WOLFGANG.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "沃尔夫冈要为小鱼们打造一个大池塘！"

WOLFGANG.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "Strong fish live here!",
	FUEL_HIGH = "Fish are very full!",
	FUEL_MED = "Fish eat good.",
	FUEL_LOW = "Fish need more food.",
	EMPTY = "No food for fish.",
}

WOLFGANG.DESCRIBE.KYNO_ANTCHOVY = "小鱼虫！沃尔夫冈不确定它究竟是美味还是可怕。"
WOLFGANG.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "好多小鱼虫！沃尔夫冈要砸碎它们？"

WOLFGANG.DESCRIBE.AGEDROE = "小蛋让沃尔夫冈觉得自己是个了不起的大人物。"
WOLFGANG.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "小小的蛋让沃尔夫冈感觉自己又大又精致！"

WOLFGANG.DESCRIBE.KYNO_SWORDFISH_BLUE = "鱼已经忘记如何游泳了！沃尔夫冈为这只弱小的鱼感到难过。"

WOLFGANG.DESCRIBE.KYNO_JELLYFISH = "如果我打果冻，它就会变成果酱。"
WOLFGANG.DESCRIBE.KYNO_JELLYFISH_DEAD = "它根本不是沃尔夫冈的对手。"
WOLFGANG.DESCRIBE.KYNO_JELLYFISH_COOKED = "果冻现在看起来真美味。"
WOLFGANG.DESCRIBE.KYNO_JELLYFISH_DRIED = "肉干很硬，就像沃尔夫冈一样！"

WOLFGANG.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "非常漂亮的果冻！"
WOLFGANG.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "好看果冻其实没那么好看。"
WOLFGANG.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "食物有许多漂亮的颜色！"

WOLFGANG.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "只是一瓶子。"

WOLFGANG.DESCRIBE.KYNO_OCEANTRAP = "小鱼毫无胜算。"

WOLFGANG.DESCRIBE.OCEANFISH_PUFFERFISH = "是条小鱼，但浑身是刺！沃尔夫冈可得小心了！"
WOLFGANG.DESCRIBE.OCEANFISH_STURGEON = "强壮的鱼！沃尔夫冈敬重强壮的鱼！"

WOLFGANG.DESCRIBE.KYNO_SWORDFISH = "沃尔夫冈向你发出决斗挑战！"
WOLFGANG.DESCRIBE.KYNO_SWORDFISH_DEAD = "这是一场精彩的战斗。"

WOLFGANG.DESCRIBE.SWORDFISHFEAST = "沃尔夫冈吃完巨型鱼后感觉精力充沛！"

WOLFGANG.DESCRIBE.KYNO_DOGFISH = "面对我吧，鱼！"
WOLFGANG.DESCRIBE.KYNO_DOGFISH_DEAD = "已死。"

WOLFGANG.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "不再美好。"

WOLFGANG.DESCRIBE.WOBSTER_MONKEYISLAND = "小小的金色贝壳生物！沃尔夫冈稍后会吃掉你。"
WOLFGANG.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "现在可以上锅了！"
WOLFGANG.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "小海虫美味极了！"

WOLFGANG.DESCRIBE.KYNO_PUFFERMONSTER = "小鱼气坏啦！沃尔夫冈要让你知道谁才是大鱼！"

WOLFGANG.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "大鱼在下面。"
WOLFGANG.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "我要吃掉你！"
WOLFGANG.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "白鲸！沃尔夫冈战斗！"
WOLFGANG.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "好一场激战，大鱼！"

WOLFGANG.DESCRIBE.KYNO_BLUBBER = "并非肌肉。"

WOLFGANG.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "小点心，给威猛的沃尔夫冈！"
WOLFGANG.DESCRIBE.KYNO_FISHMEAT_DRIED = "美味佳肴，强健肌肉！"

WOLFGANG.DESCRIBE.MONKEYISLANDMEAL = "强食弱猴之咒！"

WOLFGANG.DESCRIBE.KYNO_BRAINROCK_LARVAE = "体积小且无害。"
WOLFGANG.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "哈哈。石头光光的。"
WOLFGANG.DESCRIBE.KYNO_BRAINROCK_CORAL = "嘿嘿，它在沃尔夫冈触碰下发出噗嗤声。"

WOLFGANG.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "Wolfgang's brain will punch this brain.",
	PICKED = "Rock is tired.",
}

WOLFGANG.DESCRIBE.BRAINMETTERSOUP = "汤没有几个字母呢，哈哈。"

WOLFGANG.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "Strong creature! Give Wolfgang many good things!",
	SLEEPING = "King is sleeping.",
}

WOLFGANG.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "把你的宝藏交给沃尔夫冈！"

WOLFGANG.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "Is bone. I like it.",
	WAITING = "Bone looking way skinny.",
}

WOLFGANG.DESCRIBE.KYNO_PACKIMBAGGIMS = "你好啊，强壮的朋友！"

WOLFGANG.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "沃尔夫冈将制作史上最宏伟的蛋糕！"
WOLFGANG.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "沃尔夫冈制作的看起来相当不错。"
WOLFGANG.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "真是个了不起的蛋糕！"
WOLFGANG.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "小火柴点亮大蛋糕！"
WOLFGANG.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "让沃尔夫冈想起朋友们。"
WOLFGANG.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "虽然只有一小块蛋糕……但沃尔夫冈还是很开心！"
WOLFGANG.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "沃尔夫冈喜欢派对气球！它们让人开心！"

WOLFGANG.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "Wolfgang likes big popcorn!",
	FUEL_HIGH = "Plenty fuel for popcorn!",
	FUEL_MED = "Still popping good.",
	FUEL_LOW = "Fuel getting weak.",
	EMPTY = "No fuel. No popcorn.",
}

WOLFGANG.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "给沃尔夫冈的小小爆米花！"
WOLFGANG.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "为强大的沃尔夫冈献上庆贺之帽！"
WOLFGANG.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "萨米一定很厉害，才能戴上这顶特别的帽子！"

WOLFGANG.DESCRIBE.KYNO_FISHREGISTRYHAT = "帽子让沃尔夫冈更懂小鱼！"

WOLFGANG.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "Animals eat from this.",
	FUEL_HIGH = "Trough is very full!",
	FUEL_MED = "Still strong with food.",
	FUEL_LOW = "Food is getting weak.",
	EMPTY = "No food for animals.",
	BURNT = "Feeder is no more.",
}

WOLFGANG.DESCRIBE.CHICKENNUGGETS = "Tiny chicken pieces make Wolfgang slightly strong."

WOLFGANG.DESCRIBE.CHICKENWINGS = "Spicy wings make Wolfgang VERY STRONG!"

WOLFGANG.DESCRIBE.CHICKENBURGER = "Chicken sandwich make Wolfgang strong!"

WOLFGANG.DESCRIBE.CHICKENEGGSOUP = "Soup make Wolfgang feel strong and cozy!"

WOLFGANG.DESCRIBE.CHICKENEGGSTEW = "Big stew make Wolfgang very full!"

WOLFGANG.DESCRIBE.CHICKENROTISSERIE = "Spinning chicken make Wolfgang very hungry!"