local WORTOX = STRINGS.CHARACTERS.WORTOX

WORTOX.ANNOUNCE_KYNO_COFFEEBUFF_START = "我现在可以追坎普斯了！"
WORTOX.ANNOUNCE_KYNO_COFFEEBUFF_END = "我想我已经没那么快了。"

WORTOX.ANNOUNCE_KYNO_HASTEBUFF_START = "快爪子！"
WORTOX.ANNOUNCE_KYNO_HASTEBUFF_END = "爪子慢下来..."

WORTOX.ANNOUNCE_KYNO_POPBUFF_START = "（嗝...）多么有趣的人类饮料！！"
WORTOX.ANNOUNCE_KYNO_POPBUFF_END = "那肯定是一种有趣的人类饮料！"

WORTOX.ANNOUNCE_KYNO_FROGBUFF_START = "我要恶作剧青蛙吗？！"
WORTOX.ANNOUNCE_KYNO_FROGBUFF_END = "暂时不要再恶作剧青蛙了......"

WORTOX.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝...) 多么有趣的人类饮料啊！哼！"
WORTOX.ANNOUNCE_KYNO_PIRATEBUFF_END = "那肯定是一杯有趣的人类饮料！"

WORTOX.ANNOUNCE_KYNO_FREEZEBUFF_START = "冰冷的！"
WORTOX.ANNOUNCE_KYNO_FREEZEBUFF_END = "看来我再也不能冻结别人了。"

WORTOX.ANNOUNCE_KYNO_FIREBUFF_START = "是时候烧毁马戏团了！"
WORTOX.ANNOUNCE_KYNO_FIREBUFF_END = "火焰熄灭了！"

WORTOX.ANNOUNCE_KYNO_FISHINGBUFF_START = "水禽狩猎！"
WORTOX.ANNOUNCE_KYNO_FISHINGBUFF_END = "捕鱼能力逐渐减弱。"

WORTOX.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "头脑麻木了！"
WORTOX.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "安抚结束了。"

WORTOX.ANNOUNCE_KYNO_EATERBUFF_START = "我可以吃任何东西了！"
WORTOX.ANNOUNCE_KYNO_EATERBUFF_END = "回到正常的饮食计划。嗯哼！"

WORTOX.ANNOUNCE_KYNO_WORMBUFF_START = "他们不会看到接下来发生的事情！"
WORTOX.ANNOUNCE_KYNO_WORMBUFF_END = "我们已经完成了吗？"

WORTOX.ANNOUNCE_KYNO_CRABBUFF_START = "他们不会看到接下来发生的事情!"
WORTOX.ANNOUNCE_KYNO_CRABBUFF_END = "我们已经完成了吗？"

WORTOX.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝...) 多么有趣的人类饮料啊！嗯哼！"
WORTOX.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "那当然是一种有趣的人类饮料！"

WORTOX.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "不可估量的力量！"
WORTOX.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "现在力量已经消失了！"

WORTOX.ANNOUNCE_KYNO_STEALTHBUFF_START = "我们去捉弄别人吧！嘿嘿！"
WORTOX.ANNOUNCE_KYNO_STEALTHBUFF_END = "我需要更多看不见的机会来搞一些恶作剧！"

WORTOX.ANNOUNCE_KYNO_FEARBUFF_START = "嘿嘿！现在可怕的事情都是愚蠢的！"
WORTOX.ANNOUNCE_KYNO_FEARBUFF_END = "噢，乐趣结束了。大坏事再次令人恐惧。"

WORTOX.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "呵呵！充满不朽恶作剧的神圣果实！"
WORTOX.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "哎呀呀，乐趣结束啦！"

WORTOX.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "我觉得它们不友好！Hyuyu！"
WORTOX.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "我的猪崇拜者们走了。"

WORTOX.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "嘻嘻！现在没有刺痛能碰到我了！"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WORTOX.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "凡人的疾病无法困扰我！"
WORTOX.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "嘻嘻！又变回凡人了！"

WORTOX.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "我的脑海正翻腾着创意的浪花！噢噢！"
WORTOX.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "我的聪明才智全没了！呜呜！"

WORTOX.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "嗡嗡的小家伙不再带着刺来找我了！"
WORTOX.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "这些嗡嗡家伙又想戳我了，是吧！"

WORTOX.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "给我更多人类的耐力吧！噢噢噢！"
WORTOX.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "人类的脆弱再度来袭！嗯哼！"

WORTOX.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "哦嚯！腾出空间来装更多人类美食啦！"
WORTOX.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "哦，消失了？真没礼貌！"

WORTOX.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "何等令人欣喜的人间清明！"
WORTOX.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "哎呀呀，又搞混啦！"

WORTOX.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "你现在伤害不了我了！"
WORTOX.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "又变得有点软了。"

WORTOX.ANNOUNCE_KYNO_BERSERKERBUFF_START = "Such delicious danger!"
WORTOX.ANNOUNCE_KYNO_BERSERKERBUFF_END = "Aw, the risky fun is over!"

WORTOX.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "我需要别的。"

WORTOX.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "我知道这个恶作剧不错，但我们还是弄个真的吧。"

WORTOX.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "他们说，只有大树才能承受这种重量！"

WORTOX.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "不行！"

WORTOX.ANNOUNCE_KYNO_POTHANGER_FAIL = "为什么不挂个锅呢？"

WORTOX.ANNOUNCE_KYNO_CASSEROLE_FAIL = "有人告诉我需要一个砂锅。"

WORTOX.ANNOUNCE_KYNO_SAPHEALER_USED = "You should be good to go now, tree!"

WORTOX.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "咔嚓一声，人间的最后小憩！"

WORTOX.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "哎呀，一个带轮子的空盒子！"

WORTOX.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "噗通一声！小径突然断裂！"
WORTOX.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "噗通噗通！小径溅起水花！"
WORTOX.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "海宴临近！嘿咻！"

WORTOX.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "噢噢噢！盛大的蛋糕已准备就绪，尽情享用吧！"

WORTOX.ANNOUNCE_KYNO_FISH_RESEARCHED = "鱼的秘密揭晓啦！嘿嘿嘿！"
WORTOX.ANNOUNCE_KYNO_ROE_RESEARCHED = "蛋蛋的秘密！嘿嘿嘿！"

WORTOX.DESCRIBE.KYNO_ROE = "鱼卵。"
WORTOX.DESCRIBE.KYNO_ROE_COOKED = "烤鱼蛋。"

WORTOX.DESCRIBE.KYNO_SHARK_FIN = "鲨鱼失去了方向舵！"

WORTOX.DESCRIBE.KYNO_BEANBUGS = "跳豆！"
WORTOX.DESCRIBE.KYNO_BEANBUGS_COOKED = "死了。"

WORTOX.DESCRIBE.KYNO_GUMMYBUG = "陆鳗。"
WORTOX.DESCRIBE.KYNO_GUMMYBUG_COOKED = "我宁愿吃我的尾巴……"

WORTOX.DESCRIBE.KYNO_WHEAT = "人类会用大石头碾碎它。"
WORTOX.DESCRIBE.KYNO_WHEAT_COOKED = "人类用大石头碾碎它。"

WORTOX.DESCRIBE.KYNO_FLOUR = "食物的致命成分。"

WORTOX.DESCRIBE.KYNO_SPOTSPICE = "人类说研磨它会带来味道。"

WORTOX.DESCRIBE.KYNO_SAP = "黏黏的，恶心的树液！"
WORTOX.DESCRIBE.KYNO_SAP_SPOILED = "哎呀，不能再食用了！"

WORTOX.DESCRIBE.KYNO_SYRUP = "用于制作甜点。"

WORTOX.DESCRIBE.KYNO_COFFEEBEANS = "加水。"
WORTOX.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "没有热水？"

WORTOX.DESCRIBE.DUG_KYNO_COFFEEBUSH = "A weird plant."

WORTOX.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "Hot beans available!",
	PICKED = "Nothing left for now.",
	WITHERED = "It can't thrive like this.",
}

WORTOX.DESCRIBE.DUG_KYNO_SPOTBUSH = "It should be planted again."

WORTOX.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "Oh! A shrub.",
	PICKED = "Nothing to take right now.",
	BURNING = "That's unfortunate.",
}

WORTOX.DESCRIBE.KYNO_SPOTSPICE_LEAF = "我舔了一个。鱼友！"

WORTOX.DESCRIBE.KYNO_MUSSEL = "我喜欢贻贝！"
WORTOX.DESCRIBE.KYNO_MUSSEL_COOKED = "是的！这很好！鱼鱼！"

WORTOX.DESCRIBE.KYNO_HUMANMEAT = "人肉，喂。"
WORTOX.DESCRIBE.KYNO_HUMANMEAT_COOKED = "烤熟的人肉……"
WORTOX.DESCRIBE.KYNO_HUMANMEAT_DRIED = "干人肉。"

WORTOX.DESCRIBE.COFFEE = "好吃！"

WORTOX.DESCRIBE.BISQUE = "美味的小吃。"

WORTOX.DESCRIBE.JELLYOPOP = "耶！"

WORTOX.DESCRIBE.SHARKFINSOUP = "我可以直接把脸塞进去。"

WORTOX.DESCRIBE.TROPICALBOUILLABAISSE = "丰盛的鱼汤！"

WORTOX.DESCRIBE.MUSSELBOUILLABAISE = "美味佳肴。"

WORTOX.DESCRIBE.SWEETPOTATOSOUFFLE = "一块美味的松饼。"

WORTOX.DESCRIBE.FEIJOADA = "让我想起了巴西。"

WORTOX.DESCRIBE.GUMMY_CAKE = "蛋糕是个谎言！"

WORTOX.DESCRIBE.HARDSHELL_TACOS = "满满当当。"

WORTOX.DESCRIBE.ICEDTEA = "放心。"

WORTOX.DESCRIBE.NETTLELOSANGE = "一股新鲜空气！"

WORTOX.DESCRIBE.SNAKEBONESOUP = "丰盛的啤酒。"

WORTOX.DESCRIBE.STEAMEDHAMSANDWICH = "汉堡！！！"

WORTOX.DESCRIBE.TEA = "啊，好酒。"

WORTOX.DESCRIBE.BUBBLETEA = "放心。"

WORTOX.DESCRIBE.FRENCHONIONSOUP = "丰盛的啤酒。"

WORTOX.DESCRIBE.SLAW = "我不喜欢吃肉。"

WORTOX.DESCRIBE.LOTUSBOWL = "嗯……好吃。"

WORTOX.DESCRIBE.POI = "太粉红了！"

WORTOX.DESCRIBE.JELLYBEAN_HUNGER = "我不想要那些在我的肚皮里！"
WORTOX.DESCRIBE.JELLYBEAN_SUPER = "我不想要那些在我的肚皮里！"
WORTOX.DESCRIBE.JELLYBEAN_SANITY = "我不想要那些在我的肚皮里！"

WORTOX.DESCRIBE.BOWLOFGEARS = "不是人类食物。"

WORTOX.DESCRIBE.LONGPIGMEAL = "哦！人肉制成的食物。"

WORTOX.DESCRIBE.CUCUMBERSALAD = "我不太喜欢吃东西。"

WORTOX.DESCRIBE.DUG_KYNO_WILDWHEAT = "It should be planted again."

WORTOX.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "Wheat that grows from richest earth.",
	PICKED = "Nothing to take right now.",
	WITHERED = "It can't survive like this.",
	BURNING = "That's unfortunate.",
}

WORTOX.DESCRIBE.KYNO_MEALGRINDER = "一台用于研磨食物的机器！"

WORTOX.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "A mushroom metropolis!",
	PICKED = "They'll return in their own time.",
	BURNING = "That's unfortunate.",
}

WORTOX.DESCRIBE.GORGE_BREAD = "人类的食物看起来像这样？"
WORTOX.DESCRIBE.GORGE_SWEET_CHIPS = "这食物有特别之处！"
WORTOX.DESCRIBE.GORGE_VEGETABLE_SOUP = "只是一些蔬菜。"
WORTOX.DESCRIBE.GORGE_JELLY_SANDWICH = "果冻是它的核心。"
WORTOX.DESCRIBE.GORGE_FISH_STEW = "一顿美餐！"
WORTOX.DESCRIBE.GORGE_MEAT_STEW = "人类喜欢这样喝粘液。"
WORTOX.DESCRIBE.GORGE_ONION_CAKE = "人类的食物。没用。"
WORTOX.DESCRIBE.GORGE_POTATO_PANCAKES = "人类的食物。"
WORTOX.DESCRIBE.GORGE_POTATO_SOUP = "美味的小吃。"
WORTOX.DESCRIBE.GORGE_FISHBALL_SKEWERS = "似乎可以食用。"
WORTOX.DESCRIBE.GORGE_MEAT_SKEWERS = "似乎可以食用。"
WORTOX.DESCRIBE.GORGE_STONE_SOUP = "美味的小吃。"
WORTOX.DESCRIBE.GORGE_CROQUETTE = "不是我的首选。"
WORTOX.DESCRIBE.GORGE_ROAST_VEGETABLES = "蔬菜。"
WORTOX.DESCRIBE.GORGE_MEATLOAF = "还要面包吗？"
WORTOX.DESCRIBE.GORGE_CARROT_SOUP = "美味小吃 。"
WORTOX.DESCRIBE.GORGE_FISHPIE = "这个看起来很傻。哼！"
WORTOX.DESCRIBE.GORGE_FISHCHIPS = "脆脆的。"
WORTOX.DESCRIBE.GORGE_MEATPIE = "适当的人类膳食。"
WORTOX.DESCRIBE.GORGE_SLIDERS = "太少了！"
WORTOX.DESCRIBE.GORGE_JELLY_ROLL = "黏糊糊的！"
WORTOX.DESCRIBE.GORGE_CARROT_CAKE = "他们确实喜欢这种食物，对吗？"
WORTOX.DESCRIBE.GORGE_GARLICMASHED = "我已经迫不及待了。"
WORTOX.DESCRIBE.GORGE_GARLICBREAD = "这种面包有什么特别之处？"
WORTOX.DESCRIBE.GORGE_TOMATO_SOUP = "美味的小吃。"
WORTOX.DESCRIBE.GORGE_SAUSAGE = "有趣的食物。哼！"
WORTOX.DESCRIBE.GORGE_CANDIEDFISH = "对我来说太甜了。"
WORTOX.DESCRIBE.GORGE_STUFFEDMUSHROOM = "不是我的首选。"
WORTOX.DESCRIBE.GORGE_BRUSCHETTA = "肉类浇头会更好。"
WORTOX.DESCRIBE.GORGE_HAMBURGER = "这个很特别。"
WORTOX.DESCRIBE.GORGE_FISHBURGER = "这个很特别。"
WORTOX.DESCRIBE.GORGE_MUSHROOMBURGER = "坎普斯说这个很特别。"
WORTOX.DESCRIBE.GORGE_FISH_STEAK = "一顿美餐！"
WORTOX.DESCRIBE.GORGE_CURRY = "为什么它对某些人类如此特别？"
WORTOX.DESCRIBE.GORGE_SPAGHETTI = "物理食物太搞笑了。"
WORTOX.DESCRIBE.GORGE_POACHEDFISH = "水煮鱼配蘸酱。"
WORTOX.DESCRIBE.GORGE_SHEPHERD_PIE = "还行，差不多。"
WORTOX.DESCRIBE.GORGE_CANDY = "它非常耐嚼又甜。"
WORTOX.DESCRIBE.GORGE_BREAD_PUDDING = "人类的甜点。"
WORTOX.DESCRIBE.GORGE_BERRY_TART = "它很简单，但很棒。"
WORTOX.DESCRIBE.GORGE_MACARONI = "碗满了！"
WORTOX.DESCRIBE.GORGE_BAGEL_AND_FISH = "它很棒，但不足以满足我的饥饿感。"
WORTOX.DESCRIBE.GORGE_GRILLED_CHEESE = "这似乎是流行与人们之间。"
WORTOX.DESCRIBE.GORGE_CREAMMUSHROOM = "我不喜欢喝这种汤。"
WORTOX.DESCRIBE.GORGE_MANICOTTI = "几乎是一个煎饼卷。"
WORTOX.DESCRIBE.GORGE_CHEESEBURGER = "这个很特别。"
WORTOX.DESCRIBE.GORGE_FETTUCCINE = "普通。"
WORTOX.DESCRIBE.GORGE_ONION_SOUP = "有趣的食物。哼！"
WORTOX.DESCRIBE.GORGE_BREADED_CUTLET = "人类的食物满足不了我。"
WORTOX.DESCRIBE.GORGE_CREAMY_FISH = "我觉得味道不太好。"
WORTOX.DESCRIBE.GORGE_PIZZA = "人类说这种食物是最好的之一。"
WORTOX.DESCRIBE.GORGE_POT_ROAST = "饱餐!"
WORTOX.DESCRIBE.GORGE_CRAB_CAKE = "看起来很有趣。"
WORTOX.DESCRIBE.GORGE_STEAK_FRITES = "体面的人类食物"
WORTOX.DESCRIBE.GORGE_SHOOTER_SANDWICH = "午饭时间吧。"
WORTOX.DESCRIBE.GORGE_BACON_WRAPPED = "酷酷的外观。"
WORTOX.DESCRIBE.GORGE_CRAB_ROLL = "粗糙。"
WORTOX.DESCRIBE.GORGE_MEAT_WELLINGTON = "那位大厨的手艺肯定不错。"
WORTOX.DESCRIBE.GORGE_CRAB_RAVIOLI = "粗糙。"
WORTOX.DESCRIBE.GORGE_CARAMEL_CUBE = "伴侣方块？"
WORTOX.DESCRIBE.GORGE_SCONE = "我不喜欢人类的食物"
WORTOX.DESCRIBE.GORGE_TRIFLE = "我不喜欢人类的食物"
WORTOX.DESCRIBE.GORGE_CHEESECAKE = "我没看到奶酪..."

WORTOX.DESCRIBE.DUCKYOUGLERMZ = "太臭了！"

WORTOX.DESCRIBE.KYNO_ALOE = "黏糊糊的。"
WORTOX.DESCRIBE.KYNO_ALOE_COOKED = "好吃！"
WORTOX.DESCRIBE.KYNO_ALOE_GROUND = "黏糊糊的。"
WORTOX.DESCRIBE.KYNO_ALOE_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.FARM_PLANT_KYNO_ALOE = "黏糊糊的。"
WORTOX.DESCRIBE.KYNO_ALOE_OVERSIZED = "黏糊糊的。"
WORTOX.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "哎哟。"

WORTOX.DESCRIBE.KYNO_CUCUMBER = "黄瓜没用。"
WORTOX.DESCRIBE.KYNO_CUCUMBER_COOKED = "人类的口味真有趣。"
WORTOX.DESCRIBE.KYNO_CUCUMBER_GROUND = "黄瓜没有用。"
WORTOX.DESCRIBE.KYNO_CUCUMBER_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "黄瓜没用。"
WORTOX.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "黄瓜没有用。"
WORTOX.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "黄瓜没用。"

WORTOX.DESCRIBE.KYNO_RADISH = "红色！像我一样！"
WORTOX.DESCRIBE.KYNO_RADISH_COOKED = "蔬菜酿造。"
WORTOX.DESCRIBE.KYNO_RADISH_GROUND = "红色！像我一样！"
WORTOX.DESCRIBE.KYNO_RADISH_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.FARM_PLANT_KYNO_RADISH = "红色！像我一样！"
WORTOX.DESCRIBE.KYNO_RADISH_OVERSIZED = "红色！像我一样！"
WORTOX.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "哎哟。"

WORTOX.DESCRIBE.KYNO_FENNEL = "一根绿胡萝卜！"
WORTOX.DESCRIBE.KYNO_FENNEL_COOKED = "我要加一点肉桂。"
WORTOX.DESCRIBE.KYNO_FENNEL_GROUND = "一根绿胡萝卜！"
WORTOX.DESCRIBE.KYNO_FENNEL_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "一根绿萝卜！"
WORTOX.DESCRIBE.KYNO_FENNEL_OVERSIZED = "一根绿萝卜！"
WORTOX.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "哎哟。"

WORTOX.DESCRIBE.KYNO_SWEETPOTATO = "亲爱的！"
WORTOX.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "热食！"
WORTOX.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "亲爱的！"
WORTOX.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "亲爱的！"
WORTOX.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "亲爱的！"
WORTOX.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "哎哟。"

WORTOX.DESCRIBE.KYNO_PARZNIP = "非小鬼喜欢吃这种东西。"
WORTOX.DESCRIBE.KYNO_PARZNIP_COOKED = "非小鬼喜欢吃这样的东西。"
WORTOX.DESCRIBE.KYNO_PARZNIP_EATEN = "非小鬼喜欢吃这种东西。"
WORTOX.DESCRIBE.KYNO_PARZNIP_GROUND = "非小鬼喜欢吃这样的东西。"
WORTOX.DESCRIBE.KYNO_PARZNIP_BIG = "巨型欧洲防风草。"
WORTOX.DESCRIBE.KYNO_PARZNIP_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "非小鬼喜欢吃这种东西。"
WORTOX.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "非小鬼喜欢吃这样的东西。"
WORTOX.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "哎哟。"

WORTOX.DESCRIBE.KYNO_TURNIP = "那是一个小萝卜。"
WORTOX.DESCRIBE.KYNO_TURNIP_COOKED = "已烤熟，但未放入盘中。"
WORTOX.DESCRIBE.KYNO_TURNIP_GROUND = "那是一个小萝卜。"
WORTOX.DESCRIBE.KYNO_TURNIP_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "那是一个小萝卜。"
WORTOX.DESCRIBE.KYNO_TURNIP_OVERSIZED = "那是一个小萝卜。"
WORTOX.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "哎哟。"

WORTOX.DESCRIBE.KYNO_RICE = "不错，不错！"
WORTOX.DESCRIBE.KYNO_RICE_COOKED = "不错，不错！"
WORTOX.DESCRIBE.KYNO_RICE_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "种下一颗种子，你就可以喂饱了！"
WORTOX.DESCRIBE.FARM_PLANT_KYNO_RICE = "那是一粒小小的米。"
WORTOX.DESCRIBE.KYNO_RICE_OVERSIZED = "那是一粒小小的米。"
WORTOX.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "哎哟。"

WORTOX.DESCRIBE.KYNO_SEEDS_KIT = "只是一些种子。"

WORTOX.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "Covered in good eating!",
	PICKED = "Gone to hide, snails inside!",
	WITHERED = "Dry and dead, no more fed!",
}

WORTOX.DESCRIBE.KYNO_LIMPETS = "你很快就会在我的肚子里！鱼鱼！"
WORTOX.DESCRIBE.KYNO_LIMPETS_COOKED = "嗯！"

WORTOX.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "Pink flower!",
	PICKED = "Gone for now, take a bow!",
	BURNING = "What a gash!",
}

WORTOX.DESCRIBE.KYNO_LOTUS_ROOT = "海茎！"
WORTOX.DESCRIBE.KYNO_LOTUS_FLOWER = "一朵漂亮的粉红色花。"
WORTOX.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "闻起来很香，鱼友！"

WORTOX.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "Get's tangled in my rigging.",
	PICKED = "Nothing left right now.",
	BURNING = "That shouldn't be happening.",
}

WORTOX.DESCRIBE.KYNO_SEAWEEDS = "被我的索具缠住了。"
WORTOX.DESCRIBE.KYNO_SEAWEEDS_COOKED = "烹饪不能让它成为食物。"
WORTOX.DESCRIBE.KYNO_SEAWEEDS_DRIED = "这被认为是肉干？"
WORTOX.DESCRIBE.KYNO_SEAWEEDS_ROOT = "海茎！"

WORTOX.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "A taro root! Hyuyu!",
	PICKED = "It should grow back soon.",
	BURNING = "That's unfortunate.",
}

WORTOX.DESCRIBE.KYNO_TAROROOT_ROOT = "海茎！"
WORTOX.DESCRIBE.KYNO_TAROROOT = "我以前从未见过这样的东西！"
WORTOX.DESCRIBE.KYNO_TAROROOT_COOKED = "我最喜欢的款待......无与伦比！"

WORTOX.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "Another plant.",
	PICKED = "It will return in time.",
	BURNING = "That's unfortunate.",
}

WORTOX.DESCRIBE.KYNO_WATERYCRESS_ROOT = "海茎！"
WORTOX.DESCRIBE.KYNO_WATERYCRESS = "另一种植物。"

WORTOX.DESCRIBE.WATERYCRESSBOWL = "即使是人类食物，这也很奇怪。"

WORTOX.DESCRIBE.KYNO_SALT = "嘶嘶！"

WORTOX.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "Mussels waiting quietly.",
	PICKED = "Nothing to take right now.",
	BURNING = "That's unfortunate.",
}

WORTOX.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "为了把贻贝引到我的肚子里！鱼鱼！"

WORTOX.DESCRIBE.CATFOOD = "猫咪的食物！鱼鱼！"

WORTOX.DESCRIBE.KATFOOD = "猫咪的食物！鱼鱼！"

WORTOX.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "What do I see? A real banana tree!",
	PICKED = "No snacks for now.",
	CHOPPED = "Chopped down!",
	BURNING = "Flames everywhere!",
	BURNT = "Ashes at last!",
}

WORTOX.DESCRIBE.KYNO_BANANA = "一种最不令人反感的人类食物口味。"
WORTOX.DESCRIBE.KYNO_BANANA_COOKED = "现在烤好了。鱼友！"

WORTOX.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "This tree has a big trunk. Hyuyu!",
	PICKED = "No coconuts to be seen.",
	CHOPPED = "Downed!",
	BURNING = "It's burning, what a zap!",
	BURNT = "Just ashes now.",
}

WORTOX.DESCRIBE.KYNO_KOKONUT = "一颗坚果！"
WORTOX.DESCRIBE.KYNO_KOKONUT_HALVED = "一个椰子有两个？！"
WORTOX.DESCRIBE.KYNO_KOKONUT_COOKED = "比生的还要好。"

WORTOX.DESCRIBE.BOWLOFPOPCORN = "最棒的人类食物之一！"

WORTOX.DESCRIBE.FIGJUICE = "放心。"

WORTOX.DESCRIBE.COCONUTWATER = "放心。"

WORTOX.DESCRIBE.EYEBALLSPAGHETTI = "我知道这不会有好的结局。"

WORTOX.DESCRIBE.FORGETMELOTS_SEEDS = "种下一颗种子，你就可以喂饱了！"

WORTOX.DESCRIBE.FIRENETTLES_SEEDS = "种下一颗种子，你就可以喂饱了！"

WORTOX.DESCRIBE.TILLWEED_SEEDS = "种下一颗种子，你就可以喂饱了！"

WORTOX.DESCRIBE.KYNO_FLOATILIZER = "呼吁吁！那是一些便便！"

WORTOX.DESCRIBE.KYNO_TWIGGYNUTS = "坚果。"

WORTOX.DESCRIBE.KYNO_REPAIRTOOL = "有一个总是很方便。"

WORTOX.DESCRIBE.KYNO_KOI = "恐怕你的旅程被缩短了。"
WORTOX.DESCRIBE.KYNO_KOI_COOKED = "恐怕你的旅程被缩短了。"

WORTOX.DESCRIBE.KYNO_TROPICALFISH = "嗨！"
WORTOX.DESCRIBE.KYNO_TROPICALFISH_COOKED = "哦。它不见了"

WORTOX.DESCRIBE.KYNO_NEONFISH = "这是一条蓝色的鱼。"
WORTOX.DESCRIBE.KYNO_NEONFISH_COOKED = "一条精致的鱼！"

WORTOX.DESCRIBE.KYNO_GROUPER = "你看出来了。"
WORTOX.DESCRIBE.KYNO_GROUPER_COOKED = "准备吃我的肚子！"
 
WORTOX.DESCRIBE.KYNO_PIERROTFISH = "鱼腥味。"
WORTOX.DESCRIBE.KYNO_PIERROTFISH_COOKED = "放下嘴巴！"

WORTOX.DESCRIBE.KYNO_SALMONFISH = "它不喜欢空气，哦不。"
WORTOX.DESCRIBE.KYNO_SALMONFISH_COOKED = "再见，亲爱的鱼魂！"

WORTOX.DESCRIBE.TURF_PINKPARK = "像我一样几乎是红色的！"
WORTOX.DESCRIBE.TURF_STONECITY = "岩石地。"
WORTOX.DESCRIBE.TURF_FIELDS = "草路。"
WORTOX.DESCRIBE.TURF_TIDALMARSH = "非常柔软的地面。"

WORTOX.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "The minerals are ready.",
	PICKED = "The mortals crave these minerals.",
}

WORTOX.DESCRIBE.KYNO_SALTRACK_INSTALLER = "它是用来飞到池塘上方的。"

WORTOX.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "这是用来填满树液的。"

WORTOX.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "一旦我抓住他们，他们会觉得很傻！"

WORTOX.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "My oh my, you look ill! Low of spirit, green 'round the gill.",
	SLEEPING = "I should let him rest.",
}

WORTOX.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "Fweehee, what a special tree!",
	CHOPPED = "That's a wrap on the sap.",
	SAPPED = "Sweet, sugary sap!",
	PICKED = "The tap will soon make sap!",
	BURNING = "That's unfortunate.",
	BURNT = "Nothing left now.",
}

WORTOX.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "An unfortunate mishap befell the tree sap.",
	CHOPPED = "It served no purpose.",
	SAPPED = "Ruined, but available.",
	PICKED = "Those bugs are tree thugs!",
	BURNING = "That ends it.",
	BURNT = "Nothing remains.",
}

WORTOX.DESCRIBE.KYNO_SUGARTREE_BUD = "一颗树种。"

WORTOX.DESCRIBE.KYNO_SUGARTREE_FLOWER = "芳香花瓣可供采摘。"
WORTOX.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "芳香花瓣可供采摘。"

WORTOX.DESCRIBE.KYNO_SUGARTREE_PETALS = "芳香花瓣可供采摘。"

WORTOX.DESCRIBE.KYNO_PEBBLECRAB = "多么有趣的生物！"

WORTOX.DESCRIBE.KYNO_CRABMEAT = "人类喜欢，他们喜欢，他们喜欢！"
WORTOX.DESCRIBE.KYNO_CRABMEAT_COOKED = "他们更喜欢这样，我听说！"
WORTOX.DESCRIBE.KYNO_CRABMEAT_DRIED = "人类喜欢，他们喜欢，他们喜欢！"

WORTOX.DESCRIBE.KYNO_CRABKINGMEAT = "人类喜欢，他们喜欢，他们喜欢！"
WORTOX.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "人类喜欢它，他们喜欢，他们喜欢！"
WORTOX.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "人类喜欢它，他们喜欢，他们喜欢！"

WORTOX.DESCRIBE.KYNO_SLAUGHTERTOOL = "我不喜欢这种恶作剧。"

WORTOX.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "A tiny bird.",
	COOP = "Home sweet coop! Hyuyu!",
}

WORTOX.DESCRIBE.KYNO_CHICKEN_EGG = "一只鸡的蛋，至少我听说过。"
WORTOX.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "A big shell for a tiny soul!"
WORTOX.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "可能是人类。"

WORTOX.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "A never ending supply of eggs!",
	FULL = "Eggs galore!",
	BURNT = "No more coop, no more cluck!",
}

WORTOX.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "嗯，我从它身上感觉到一种奇怪的气息。"

WORTOX.DESCRIBE.KYNO_COOKWARE_KIT = "人类的烹饪材料。鱼鱼！"
WORTOX.DESCRIBE.KYNO_COOKWARE_SYRUP = "人类不喜欢原始的树内脏。"
WORTOX.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "人类不喜欢原始的树内脏。"
WORTOX.DESCRIBE.KYNO_COOKWARE_BIG_POT = "人类不喜欢你烧掉里面的东西。"
WORTOX.DESCRIBE.KYNO_COOKWARE_BIG = "人类不喜欢你烧掉里面的东西。"
WORTOX.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "一个装人类食物的小容器。"
WORTOX.DESCRIBE.KYNO_COOKWARE_SMALL = "一个装人类食物的小容器。"
WORTOX.DESCRIBE.KYNO_COOKWARE_GRILL = "人类有很多不同的烹饪方法。"
WORTOX.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "我们需要建造它，确实如此。"
WORTOX.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "人类在上面做饭。"
WORTOX.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "我们需要建造它，确实如此。"
WORTOX.DESCRIBE.KYNO_COOKWARE_ELDER = "人类不喜欢原始的树内脏。"
WORTOX.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "我们需要建造它，是的。"
WORTOX.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "我想知道这条巨龙是怎么尝到人类食物的。"
WORTOX.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "这道菜太小了！"
WORTOX.DESCRIBE.KYNO_COOKWARE_OVEN = "这是人类用来做饭的东西。"
WORTOX.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "这是人类做饭的东西。"
WORTOX.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "这是人类做饭的东西。"

WORTOX.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "Plenty of bugs can be found under rocks.",
	FLIPPED = "Now it's exposed.",
}

WORTOX.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "只是一个水上的箱子。"

WORTOX.DESCRIBE.KYNO_SUGARFLY = "美丽如日落。"
WORTOX.DESCRIBE.KYNO_SUGARFLYWINGS = "飞走吧，亲爱的灵魂。"

WORTOX.DESCRIBE.KYNO_WATERY_CRATE = "只是一个水上的箱子。"

WORTOX.DESCRIBE.KYNO_TUNACAN = "罐装鱼！"
WORTOX.DESCRIBE.KYNO_TUNACAN_OPEN = "罐装鱼！"

WORTOX.DESCRIBE.KYNO_CANNEDFOOD = "罐头食品！鱼友！"
WORTOX.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "罐头食品！鱼友！"

WORTOX.DESCRIBE.KYNO_POP = "我不知道那是什么。"

WORTOX.DESCRIBE.KYNO_MYSTERYMEAT = "今晚我会吃得很好！"

WORTOX.DESCRIBE.KYNO_BOTTLE_SOUL = "鱼鱼！看起来很好吃。"

WORTOX.DESCRIBE.SOULSTEW = "鱼鱼！看起来很好吃。"

WORTOX.DESCRIBE.FORTUNECOOKIE = "我总是很幸运！哦豁！"

WORTOX.DESCRIBE.HORNOCUPIA = "喇叭的用途真有趣！"

WORTOX.DESCRIBE.CHEESE_YELLOW = "臭！"
WORTOX.DESCRIBE.CHEESE_WHITE = "这个比黄色的更臭！鱼鱼！"
WORTOX.DESCRIBE.CHEESE_KOALEFANT = "臭！"

WORTOX.DESCRIBE.MILK_BOX = "味道很好。"

WORTOX.DESCRIBE.WATERCUP = "就是水。看来人类没有它就活不下去。"

WORTOX.DESCRIBE.HONEYJAR = "太粘了！哦豁吙！"

WORTOX.DESCRIBE.CRAB_ARTICHOKE = "它看起来很好吃。但我不能说同样的味道！"

WORTOX.DESCRIBE.PEPPERROLLS = "我会在 沃利不注意的时候用牙膏塞满它们。！"

WORTOX.DESCRIBE.KYNO_SAPHEALER = "苦涩难忍。"

WORTOX.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "Rest well.",
	PICKED = "Nothing left for now.",
	BURNING = "That seals its fate.",
}

WORTOX.DESCRIBE.KYNO_GHOST_PIRATE = "鬼魅般的面容！呜呜！"

WORTOX.DESCRIBE.KYNO_BUCKET_EMPTY = "人类用它来收集东西。"
WORTOX.DESCRIBE.KYNO_BUCKET_METAL = "人类用这个来收集东西。"
WORTOX.DESCRIBE.KYNO_BUCKET_WATER = "一桶液态生命！噗通噗通！"

WORTOX.DESCRIBE.KYNO_MILK_BEEFALO = "拜托，不用了，谢谢。"
WORTOX.DESCRIBE.KYNO_MILK_KOALEFANT = "拜托，不用了，谢谢。"

WORTOX.DESCRIBE.KYNO_CAP_DRIED = "干的人类食物。"

WORTOX.DESCRIBE.KYNO_PLANTMEAT_DRIED = "人类在潮湿时更喜欢这样。"

WORTOX.DESCRIBE.KYNO_BREWBOOK = "哦，接下来我要煮什么？鱼友！"

WORTOX.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "This machine makes the things that mortals likes.",
	BREWING_LONG = "Bubbling slow, nice and low!",
	BREWING_SHORT = "Almost done!",
	DONE = "It's finally ready!",
	BURNT = "Ash and gloom.",
}

WORTOX.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "They told me this make a good thing with pomegranates. I must try!",
	BREWING_LONG = "It is bubbling nicely.",
	BREWING_SHORT = "Almost done, from what I can tell.",
	DONE = "Sweet!",
	BURNT = "Oh no, its all gone!",
}

WORTOX.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "Making the sweet honey!",
	HONEY = "Its full of honey! What a show!",
	NECTAR = "Not ready yet?",
	BURNING = "No more honey making now.",
}

WORTOX.DESCRIBE.KYNO_NECTAR_POD = "甜蜜，甜蜜，蜜蜂的花蜜！"

WORTOX.DESCRIBE.KYNO_OAKTREE_POD = "可种植和可生长的树木机制。"
WORTOX.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "蛴螬。"

WORTOX.DESCRIBE.KYNO_PIKO = "我明白了，你喜欢像我一样恶作剧！"
WORTOX.DESCRIBE.KYNO_PIKO_ORANGE = "用于泡茶！"

WORTOX.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "You look nice!",
	CHOPPED = "Stripped of all it had to give.",
	BURNING = "That's unfortunate.",
	BURNT = "Nothing left now.",
}

WORTOX.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "You look nice!",
	BURNING = "Flee if you value your life.",
}

WORTOX.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "有一个板条箱。"

WORTOX.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "A stinky structure, to be sure.",
	BURNT = "Ashes and smoke.",
}

WORTOX.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "They smell worse than me!",
	CRAFTED = "Spruced up, nice!",
	BURNT = "Burnt and foul.",
}

WORTOX.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "Me and Sammy went through a lot of places to get these items!",
	OCCUPIED = "No trading right now.",
}

WORTOX.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "I hid a little thing in there. Hyuyu!",
	EMPTY = "No goodies left.",
}

WORTOX.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "不要告诉任何人是我带你来的！"
WORTOX.DESCRIBE.KYNO_MEADOWISLAND_POND = "我看到了我的未来……"
WORTOX.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "嘿！我在看这里！"
WORTOX.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "桑迪和少年。"
WORTOX.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "至少他在为我捕鱼，哼哼！"

WORTOX.DESCRIBE.KYNO_SAMMYHAT = "闻起来像鱼。"

WORTOX.DESCRIBE.KINGFISHER = "大钞！"

WORTOX.DESCRIBE.TOUCAN = "你的名字不会是山姆吧？"
WORTOX.DESCRIBE.TOUCAN_CHUBBY = "你的名字不会是山姆吧？"

WORTOX.DESCRIBE.WETGOOP2 = "咦呕！多么令人厌恶。"

WORTOX.DESCRIBE.BEER = "为什么人类这么喜欢它？"

WORTOX.DESCRIBE.PALEALE = "为什么人类这么喜欢它？"

WORTOX.DESCRIBE.TEAGREEN = "一小口就行了。"

WORTOX.DESCRIBE.TEARED = "一小口就行了。"

WORTOX.DESCRIBE.MEAD = "有趣的味道！鱼鱼！"

WORTOX.DESCRIBE.KYNO_JELLY = "哦不，它在我的皮毛里。"

WORTOX.DESCRIBE.KYNO_MAYONNAISE = "嗯！"

WORTOX.DESCRIBE.TARTARSAUCE = "我喜欢！"

WORTOX.DESCRIBE.KYNO_PICKLES = "嗯...所以他们是自己做的？"

WORTOX.DESCRIBE.KYNO_WINE = "有趣又苦涩的饮料。呼吁吁！"

WORTOX.DESCRIBE.KYNO_JUICE = "非常清爽！"

WORTOX.DESCRIBE.KYNO_POISON_FROGLEGS = "毒素！"
WORTOX.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "这是个笑话！"

WORTOX.DESCRIBE.POISONFROGGLEBUNWICH = "人类很奇怪。"

WORTOX.DESCRIBE.KYNO_BREWINGRECIPECARD = "多么神秘，卡片是空白的！"

WORTOX.DESCRIBE.KYNO_OIL = "一种食品制造原料！"

WORTOX.DESCRIBE.BERRYSUNDAE = "我可能能接受。"

WORTOX.DESCRIBE.CHOCOLATE_BLACK = "一种普通的人类甜点！"
WORTOX.DESCRIBE.CHOCOLATE_WHITE = "一种普通的人类甜点。！"

WORTOX.DESCRIBE.TRICOLORDANGO = "对我来说就像甜点。"
 
WORTOX.DESCRIBE.FRIESFRENCH = "人类的垃圾食品。"

WORTOX.DESCRIBE.PIRATERUM = "人类都无法抗拒想知道里面是什么的冲动！哼哼！"

WORTOX.DESCRIBE.TWISTEDTEQUILA = "人类的鸡尾酒。用蓝色植物制成。"

WORTOX.DESCRIBE.ONIONRINGS = "我想知道它是否像他们说的那么好。"

WORTOX.DESCRIBE.DONUTS = "人类似乎特别喜欢这个。"
WORTOX.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "人类似乎特别喜欢这个。"
WORTOX.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "人类似乎特别喜欢这个。"
 
WORTOX.DESCRIBE.CINNAMONROLL = "甜面包。呼吁吁！"

WORTOX.DESCRIBE.GUMMYBEARGERS = "想知道它是否带有一个小恶作剧？"

WORTOX.DESCRIBE.PRETZEL = "脆脆的！"

WORTOX.DESCRIBE.CORNINCUP = "我不喜欢很多人类的食物。"

WORTOX.DESCRIBE.COTTONCANDY = "这个人类的食物，听起来有点滑稽。呼吁吁！"

WORTOX.DESCRIBE.ROASTEDHAZELNUTS = "我可以用这个创造很多双关语！"

WORTOX.DESCRIBE.MONSTERMUFFIN = "我没发现这个松饼有什么热气。"

WORTOX.DESCRIBE.PINKCAKE = "为什么人类在庆祝自己的生日时总是吃这些？"

WORTOX.DESCRIBE.CHIPSBAG = "太脆了！呼吁吁！"

WORTOX.DESCRIBE.LITTLEBREAD = "人类的食物看起来像这样？"

WORTOX.DESCRIBE.HOTHOUND = "你喜欢我给它起的名字吗？我觉得很有趣。"

WORTOX.DESCRIBE.MILKSHAKE = "这确实是一种奇特的饮料。"
WORTOX.DESCRIBE.MILKSHAKE_PRISMATIC = "这确实是一种奇特的饮料。"

WORTOX.DESCRIBE.NACHOS = "那个奶酪酱看起来不错，够了……"

WORTOX.DESCRIBE.BANANA_PUDDING = "只是一串香蕉！"

WORTOX.DESCRIBE.SEA_PUDDING = "这只是一群鱼！"

WORTOX.DESCRIBE.TOM_KHA_SOUP = "蔬菜一起扔进碗里。"

WORTOX.DESCRIBE.MINERTREAT = "多么有趣又好奇的人类食物啊！呼吁吁！"

WORTOX.DESCRIBE.RADISHSALAD = "我不太喜欢吃东西。"

WORTOX.DESCRIBE.PUMPKIN_SOUP = "美味的小吃。"

WORTOX.DESCRIBE.ALGAE_SOUP = "美味的小吃。"

WORTOX.DESCRIBE.PARZNIP_SOUP = "美味的小吃。"

WORTOX.DESCRIBE.NETTLEMEATED = "一点点肉就能清除它！"

WORTOX.DESCRIBE.KYNO_SUGAR = "嗯！"

WORTOX.DESCRIBE.KYNO_BOTTLECAP = "它们到处都是！"

WORTOX.DESCRIBE.NUKACOLA = "你喜欢我从那里带来的食谱吗？"
WORTOX.DESCRIBE.NUKACOLA_QUANTUM = "你喜欢我从那里带来的食谱吗？"

WORTOX.DESCRIBE.LIVINGSANDWICH = "这是人类无法处理的面包！呼吁吁！"

WORTOX.DESCRIBE.DURIANSPLIT = "我可能可以接受这个。"

WORTOX.DESCRIBE.DURIANSOUP = "一杯丰盛的啤酒。"

WORTOX.DESCRIBE.DURIANMEATED = "我喜欢美味的臭食物！"

WORTOX.DESCRIBE.DURIANCHICKEN = "一场非常丰盛的人类盛宴。"

WORTOX.DESCRIBE.LUNARSOUP = "确实是一种奇怪的汤。"

WORTOX.DESCRIBE.PURPLEWOBSTERSOUP = "有臭味。"

WORTOX.DESCRIBE.WOBSTERMONSTER = "好恶作剧！呼吁吁！"

WORTOX.DESCRIBE.SPIDERCAKE = "威尔逊最理智的食物恶作剧！呼吁吁！"

WORTOX.DESCRIBE.SUGARBOMBS = "小爆炸！"

WORTOX.DESCRIBE.BERRYBOMBS = "哦不，它在我的毛皮里。"

WORTOX.DESCRIBE.ONIGIRIS = "磨碎的谷物。"

WORTOX.DESCRIBE.OMURICE = "我以前在一次旅行中见过这些符号！哼哼！"

WORTOX.DESCRIBE.PAELLA = "我听说这道菜在某个地方很受欢迎。"

WORTOX.DESCRIBE.RISOTTO = "味道非常有趣，但还不够，就像灵魂一样。哼哼！"

WORTOX.DESCRIBE.RICESAKE = "有趣的饮料，呀哈！"

WORTOX.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "Silly fruit bush. Hyuyu!"

WORTOX.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "Silly fruit. Hyuyu!",
	PICKED = "Nothing to take right now.",
	WITHERED = "It can't survive like this.",
	BURNING = "That's unfortunate.",
}

WORTOX.DESCRIBE.KYNO_PINEAPPLE = "傻瓜水果。"
WORTOX.DESCRIBE.KYNO_PINEAPPLE_HALVED = "傻瓜水果。"
WORTOX.DESCRIBE.KYNO_PINEAPPLE_COOKED = "愚蠢的水果。"

WORTOX.DESCRIBE.PIZZA_TROPICAL = "愚蠢的人类，他们是如何改变了你。"

WORTOX.DESCRIBE.PINACOLADA = "我必须承认，它非常好，令人神清气爽。"

WORTOX.DESCRIBE.CHIMAS = "一种奇怪的饮料，哼哼！"

WORTOX.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "Relief for the plants.",
	ON = "Its working nicely.",
}

WORTOX.DESCRIBE.KYNO_FOODSACK = "仅用于存放食物。"

WORTOX.DESCRIBE.GUMMYWORMS = "他们尝到了甜头。"

WORTOX.DESCRIBE.SMORES = "愚蠢的人类食物。"

WORTOX.DESCRIBE.NUKASHINE = "这是个小把戏！我应该偶尔回阿巴拉契亚去看看。哼哼！"

WORTOX.DESCRIBE.ANTSLOG = "下次麦斯威尔吃这个的时候，我应该把它换成真的蚂蚁。哼哼！"

WORTOX.DESCRIBE.KYNO_WORM_BONE = "来自虫子的宝藏。"

WORTOX.DESCRIBE.SPOOKY_BRAIN_NOODLES = "明心见性。"
WORTOX.DESCRIBE.SPOOKY_BURGERZILLA = "我不能告诉他们，这其实是一种生物！"
WORTOX.DESCRIBE.SPOOKY_DEADBREAD = "只是另一种常见的面包。"
WORTOX.DESCRIBE.SPOOKY_JELLYBEANS = "如果我下次把它们换成真正的眼球......？"
WORTOX.DESCRIBE.SPOOKY_POPSICLE = "这种人类的食物很奇怪。"
WORTOX.DESCRIBE.SPOOKY_PUMPKINCREAM = "奇怪。"
WORTOX.DESCRIBE.SPOOKY_SKULLCANDY = "我以为这些是为了音乐！"
WORTOX.DESCRIBE.SPOOKY_TACODILE = "别担心。它不会从我的传送门逃走的。"

WORTOX.DESCRIBE.BUTTER_BEEFALO = "这真的是黄油。"
WORTOX.DESCRIBE.BUTTER_GOAT = "这真的是山羊的黄油。"
WORTOX.DESCRIBE.BUTTER_KOALEFANT = "那只野兽有一些很好的用途！哼哼！"

WORTOX.DESCRIBE.SPICE_CURE = "一种巧妙的技巧。"
WORTOX.DESCRIBE.SPICE_COLD = "冬天已经到了吗？"
WORTOX.DESCRIBE.SPICE_FIRE = "人类需要对此保持警惕！哼哼！"
WORTOX.DESCRIBE.SPICE_FED = "只是更多的饥饿燃烧！"
WORTOX.DESCRIBE.SPICE_MIND = "放松粉！"

WORTOX.DESCRIBE.SUGARFLYMUFFIN = "亲爱的，松饼在这。"

WORTOX.DESCRIBE.EELTACOS = "人类的食物。"

WORTOX.DESCRIBE.MEATSKILLET = "人类的食物。"

WORTOX.DESCRIBE.MEATWALTZ = "最终会学会的。"

WORTOX.DESCRIBE.COMPLETEBREAKFAST = "他的胃一定是我的两倍大！哼哼！"

WORTOX.DESCRIBE.DUMPLINGS = "一种古老的人类食物。"

WORTOX.DESCRIBE.WARLYICEDTEA = "轻松是肯定的。"

WORTOX.DESCRIBE.WARLYTEA = "啊，一杯好茶。"

WORTOX.DESCRIBE.KYNO_TEALEAF = "它是用来泡茶的。"

WORTOX.DESCRIBE.KYNO_ITEMSLICER = "厨房用具。"
WORTOX.DESCRIBE.KYNO_ITEMSLICER_GOLD = "主厨厨具。"

WORTOX.DESCRIBE.COXINHA = "鸡肉零食！"

WORTOX.DESCRIBE.LAZYDESSERT = "这将是有史以来最好的恶作剧之一！嗯哼！"

WORTOX.DESCRIBE.CRABKINGFEAST = "我几乎无法将其放入口中！"

WORTOX.DESCRIBE.PIENAPPLE = "一个派！而且都是我的！哈哈！"

WORTOX.DESCRIBE.JAWSBREAKER = "我觉得我的嘴巴承受不了。"

WORTOX.DESCRIBE.AVOCADOTOAST = "我的胃不太饱。"

WORTOX.DESCRIBE.RICEPUDDING = "牛奶让一切变得更好。"

WORTOX.DESCRIBE.SHARKSUSHI = "他们说这是一顿顶级的餐。"

WORTOX.DESCRIBE.WOBSTERBREADED = "看起来像是晚餐。"

WORTOX.DESCRIBE.LAZYPURRITO = "我还需要再做八个这样的东西吗？"

WORTOX.DESCRIBE.HORCHATA = "我的爪子冻僵了！"

WORTOX.DESCRIBE.WOBSTERCOCKTAIL = "它像我一样鲜红！"

WORTOX.DESCRIBE.LAVAEEGGBOILED = "我的爪子在烧！呼呼！"

WORTOX.DESCRIBE.POMEGRANATETEA = "我最喜欢的人类饮料！"

WORTOX.DESCRIBE.TIRAMISU = "一杯咖啡装在漂亮的碗里。"

WORTOX.DESCRIBE.TOADSTOOLCOLA = "青蛙！"

WORTOX.DESCRIBE.TEPACHE = "桶装菠萝汁。"

WORTOX.DESCRIBE.LUNARTEQUILA = "它有相当大的副作用。"

WORTOX.DESCRIBE.MIMICMOSA = "完美的隐藏技巧！嗯哼！"

WORTOX.DESCRIBE.POMEGRANATEPIE = "我最喜欢的人类美食之一！"

WORTOX.DESCRIBE.PINEAPPLECAKE = "我真希望能够吃到石榴蛋糕。"

WORTOX.DESCRIBE.PASTY_MEAT = "听起来像是午餐。"
WORTOX.DESCRIBE.PASTY_CHEESE = "听起来像是午餐。"

WORTOX.DESCRIBE.BRIGADEIRO = "我有点想吃它。"

WORTOX.DESCRIBE.REGULARLASAGNA = "辛辣面条。"

WORTOX.DESCRIBE.FLTSANDWICH = "它是由明眼青蛙腿制成的。"

WORTOX.DESCRIBE.RICEANDBEANS = "人类的食物。"

WORTOX.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "呵呵！一座沉睡于时间中的房子……2026年再来偷看吧！"

WORTOX.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "Hidden, but not from me! Hyuyu!",
	PICKED = "Nothing left for now.",
	BURNING = "That's unfortunate.",
}

WORTOX.DESCRIBE.KYNO_TRUFFLES = "噢！来自地下的美味！"
WORTOX.DESCRIBE.KYNO_TRUFFLES_COOKED = "滋滋作响，现在完美了！"

WORTOX.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "Nothing in there yet.",
	FULL = "A feast for the eyes, hyuyu!",
}

WORTOX.DESCRIBE.KYNO_SPORECAP = "呵呵！腐败的美味！"
WORTOX.DESCRIBE.KYNO_SPORECAP_COOKED = "烤焦又邪恶的美味！"

WORTOX.DESCRIBE.KYNO_SPORECAP_DARK = "呵呵！有毒的小恶作剧！"
WORTOX.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "呵呵！恶作剧的盛宴！"

WORTOX.DESCRIBE.KYNO_GOLDENAPPLE = "呵呵！我在另一个方块世界见过它！"

WORTOX.DESCRIBE.TRUFFLESGRINDER = "呵呵！凡人做的泥土甜点！"

WORTOX.DESCRIBE.SPORECAPPIE = "嘻嘻！致命的美味，献给勇敢的凡人！"

WORTOX.DESCRIBE.SPORECAP_SKEWERS = "嘿嘿！孢子串，真是凡人的把戏！"

WORTOX.DESCRIBE.TRUFFLEOIL = "大自然的滑溜恶作剧！神圣……还是猪味？"

WORTOX.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "但即兴发挥更有趣！"
WORTOX.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "水洼化作鱼族宫殿！嗯哼！"

WORTOX.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "Tiny fish, rise and play!",
	FUEL_HIGH = "They're are full belly.",
	FUEL_MED = "It seems they are getting hungry.",
	FUEL_LOW = "Food keeps getting low.",
	EMPTY = "No more fish snacks, need to replenish it.",
}

WORTOX.DESCRIBE.KYNO_ANTCHOVY = "它在两个世界里蠕动扭摆！咿呀呀！"
WORTOX.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "一群欢快的混合鱼虫！"

WORTOX.DESCRIBE.AGEDROE = "傲慢的鱼卵！"
WORTOX.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "海洋的欢愉小珍珠，咿呀呀！"

WORTOX.DESCRIBE.KYNO_SWORDFISH_BLUE = "他忘了怎么游泳！嗯哼！"

WORTOX.DESCRIBE.KYNO_JELLYFISH = "它很软。"
WORTOX.DESCRIBE.KYNO_JELLYFISH_DEAD = "现在不觉得那么震惊了？"
WORTOX.DESCRIBE.KYNO_JELLYFISH_COOKED = "惊为天人的美味！咿呀呀！"
WORTOX.DESCRIBE.KYNO_JELLYFISH_DRIED = "嚼劲十足！"

WORTOX.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "它非常绚丽多彩。"
WORTOX.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "它不再移动了！"
WORTOX.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "依然色彩斑斓。嗯哼！"

WORTOX.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "她空空如也。"

WORTOX.DESCRIBE.KYNO_OCEANTRAP = "他们绝对想不到这一招。咻咻！"

WORTOX.DESCRIBE.OCEANFISH_PUFFERFISH = "如此充盈着空气，却又如此致命！嗯哼！"
WORTOX.DESCRIBE.OCEANFISH_STURGEON = "如此古老！我敢说它见识过世间种种凡人的恶作剧！"

WORTOX.DESCRIBE.KYNO_SWORDFISH = "一场充满战斗精神的激战！嗷呜！"
WORTOX.DESCRIBE.KYNO_SWORDFISH_DEAD = "你打得真不错。"

WORTOX.DESCRIBE.SWORDFISHFEAST = "哦嚯！一顿鲜美的佳肴，正撩拨我的味蕾！"

WORTOX.DESCRIBE.KYNO_DOGFISH = "咸狗！"
WORTOX.DESCRIBE.KYNO_DOGFISH_DEAD = "它不会再游泳了。"

WORTOX.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "臭烘烘的鱼尸。"

WORTOX.DESCRIBE.WOBSTER_MONKEYISLAND = "闪亮的贝壳，装点闪亮的灵魂！"
WORTOX.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "那闪亮的外壳里，再无火花。"
WORTOX.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "多么可爱的海鲜小点心呀！嗯哼！"

WORTOX.DESCRIBE.KYNO_PUFFERMONSTER = "噢噢！一条满腹怒火、烟雾缭绕的鱼！"

WORTOX.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "恶魔正等着我！呜呜！"
WORTOX.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "看起来很悲伤。"
WORTOX.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "恶魔再度现身！咿呀呀！"
WORTOX.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "马上就要爆炸了！"

WORTOX.DESCRIBE.KYNO_BLUBBER = "没人能看见我哭鼻子！"

WORTOX.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "来自深渊的致命诱惑，嘿嘿！"
WORTOX.DESCRIBE.KYNO_FISHMEAT_DRIED = "咸香可口的人类美味，嘿嘿！"

WORTOX.DESCRIBE.MONKEYISLANDMEAL = "一场释放野性的盛宴。嗷呜！"

WORTOX.DESCRIBE.KYNO_BRAINROCK_LARVAE = "并非最令人畏惧的海怪。"
WORTOX.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "那是一块光秃秃的石头！"
WORTOX.DESCRIBE.KYNO_BRAINROCK_CORAL = "你不能跳出自己的口袋来思考。"

WORTOX.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "Brain of the ocean.",
	PICKED = "No more thoughts, oh my!",
}

WORTOX.DESCRIBE.BRAINMETTERSOUP = "也许这能帮我想出更好的恶作剧？"

WORTOX.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "Ahoy, ye salty dog!",
	SLEEPING = "Not open for trades right now.",
}

WORTOX.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "深海之宝！"

WORTOX.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "A dead fish.",
	WAITING = "Nothing remains the same.",
}

WORTOX.DESCRIBE.KYNO_PACKIMBAGGIMS = "那是我兄弟！"

WORTOX.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "我等不及要看到它完工了。噢耶！"
WORTOX.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "我得再搞点东西。"
WORTOX.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "趁没人看见时，我偷偷吃一片！"
WORTOX.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "人人尽享欢乐时光！"
WORTOX.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "你会带来怎样的庆祝？"
WORTOX.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "人间美味，多么美味！嗯哼！"
WORTOX.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "砰！我最爱惊喜啦！"

WORTOX.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "Popcorn is a delightful treat, yes.",
	FUEL_HIGH = "Plenty of fuel still.",
	FUEL_MED = "It can still produce some.",
	FUEL_LOW = "Fuel running low.",
	EMPTY = "No fuel remaining.",
}

WORTOX.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "砰！一声欢庆的脆响零食！"
WORTOX.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "哦嚯！一顶专为节日恶作剧准备的帽子！"
WORTOX.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "哦嚯！专为萨米打造的帽子，独特又夸张！"

WORTOX.DESCRIBE.KYNO_FISHREGISTRYHAT = "充满鱼味知识的思考帽！嘿嘿嘿！"

WORTOX.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "Nibble and munch, a feeding hunch!",
	FUEL_HIGH = "Full to the brim!",
	FUEL_MED = "Not too bad, not too grim!",
	FUEL_LOW = "Low, oh low!",
	EMPTY = "No food left!",
	BURNT = "Ash and smoke!",
}

WORTOX.DESCRIBE.CHICKENNUGGETS = "Tiny chicken nuggets."

WORTOX.DESCRIBE.CHICKENWINGS = "Hot-hot wings, hot, hot!"