local WAXWELL = STRINGS.CHARACTERS.WAXWELL

WAXWELL.ANNOUNCE_KYNO_COFFEEBUFF_START = "啊哈。古老的咖啡因。"
WAXWELL.ANNOUNCE_KYNO_COFFEEBUFF_END = "咖啡因没有了。"

WAXWELL.ANNOUNCE_KYNO_HASTEBUFF_START = "工作速度增加。"
WAXWELL.ANNOUNCE_KYNO_HASTEBUFF_END = "我的手需要休息一下。"

WAXWELL.ANNOUNCE_KYNO_POPBUFF_START = "（嗝...）我的礼貌在哪里？我很抱歉。"
WAXWELL.ANNOUNCE_KYNO_POPBUFF_END = "哎哟，饮料掉了。"

WAXWELL.ANNOUNCE_KYNO_FROGBUFF_START = "这只是……"
WAXWELL.ANNOUNCE_KYNO_FROGBUFF_END = "如果我靠近他们，他们会注意到我不是青蛙。"

WAXWELL.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝...) 他们会认识我的。"
WAXWELL.ANNOUNCE_KYNO_PIRATEBUFF_END = "哎哟，饮料掉了。"

WAXWELL.ANNOUNCE_KYNO_FREEZEBUFF_START = "他们会感受到我的愤怒！"
WAXWELL.ANNOUNCE_KYNO_FREEZEBUFF_END = "我的愤怒早就没了。"

WAXWELL.ANNOUNCE_KYNO_FIREBUFF_START = "永恒的火焰吞噬了我。"
WAXWELL.ANNOUNCE_KYNO_FIREBUFF_END = "我的火焰！需要把它们带回来。"

WAXWELL.ANNOUNCE_KYNO_FISHINGBUFF_START = "我什么时候变得如此低落，以至于成为一名渔夫？"
WAXWELL.ANNOUNCE_KYNO_FISHINGBUFF_END = "啊！我的手气现在不适合钓鱼。"

WAXWELL.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "我的大脑正在得到舒缓。"
WAXWELL.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "回到我的思路。"

WAXWELL.ANNOUNCE_KYNO_EATERBUFF_START = "吃更多的东西在一段时间内会轻而易举。"
WAXWELL.ANNOUNCE_KYNO_EATERBUFF_END = "现在必须耐心地吃饭。"

WAXWELL.ANNOUNCE_KYNO_WORMBUFF_START = "讨厌的虫子不会知道接下来发生的事情。"
WAXWELL.ANNOUNCE_KYNO_WORMBUFF_END = "这些虫子比我预测的要硬。"

WAXWELL.ANNOUNCE_KYNO_CRABBUFF_START = "讨厌的螃蟹不会知道接下来会发生什么。"
WAXWELL.ANNOUNCE_KYNO_CRABBUFF_END = "这些螃蟹比我预测的要顽强。"

WAXWELL.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝...) 我的礼貌在哪里？我很抱歉。"
WAXWELL.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "哎哟，青蛙饮料的感觉消失了。"

WAXWELL.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "啊！我必须不惜一切代价抵挡它..!"
WAXWELL.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "天哪！终于消失了。"

WAXWELL.ANNOUNCE_KYNO_STEALTHBUFF_START = "你在看吗，查理？"
WAXWELL.ANNOUNCE_KYNO_STEALTHBUFF_END = "我的力量减弱了..."

WAXWELL.ANNOUNCE_KYNO_FEARBUFF_START = "我是自己思想的主人。"
WAXWELL.ANNOUNCE_KYNO_FEARBUFF_END = "似乎连我都无法永远控制深渊。"

WAXWELL.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "啊……纯粹的力量。我想念这种感觉。"
WAXWELL.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "哼，力量从不长久。"

WAXWELL.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "连猪都能感受到我的魅力……"
WAXWELL.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "连猪也无法再抵挡我的魅力……"

WAXWELL.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "啊，不可伤害的感觉，我怀念它。"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WAXWELL.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "免疫……真是奢侈的享受。"
WAXWELL.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "啧，美好的事物总是太短暂。"

WAXWELL.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "终于，我的智慧得以毫无阻碍地闪耀。"
WAXWELL.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "我的光芒已然黯淡……暂时如此。"

WAXWELL.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "啊，终于摆脱这些长翅膀的讨厌鬼了。"
WAXWELL.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "啊，停战结束了。"

WAXWELL.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "啊……力量再次在我体内奔涌。"
WAXWELL.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "力量从我手中滑落……"

WAXWELL.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "终于，有些改进啦！"
WAXWELL.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "哼。又回到局限性了。"

WAXWELL.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "啊……理智恢复了。至少现在是这样。"
WAXWELL.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "理智如此短暂……"

WAXWELL.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "阴影会保护我！"
WAXWELL.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "阴影已收回了它们的恩惠。"

WAXWELL.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "我还需要别的东西。"

WAXWELL.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "你可真不好对付，是不是？"

WAXWELL.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "哼，还没准备好吗？"

WAXWELL.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "错了，错了……"

WAXWELL.ANNOUNCE_KYNO_POTHANGER_FAIL = "现在我需要一个煮饭的锅，太好了。"

WAXWELL.ANNOUNCE_KYNO_CASSEROLE_FAIL = "错了，错了。"

WAXWELL.ANNOUNCE_KYNO_SAPHEALER_USED = "You're cured, at last!"

WAXWELL.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "残酷？或许吧。但完全必要。"

WAXWELL.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "空空如也。多么令人失望。"

WAXWELL.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "唉。猎物又从我手中溜走了。真烦人。"
WAXWELL.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "大自然本身都在与我作对。"
WAXWELL.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "嘿。终于有点意思了。"

WAXWELL.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "终于等到这一刻了。一场盛大的活动，配上一款盛大的蛋糕。"

WAXWELL.ANNOUNCE_KYNO_FISH_RESEARCHED = "知识即力量，哪怕来自一条鱼。"
WAXWELL.ANNOUNCE_KYNO_ROE_RESEARCHED = "潜力，却浪费在如此脆弱的形态中。"

WAXWELL.DESCRIBE.KYNO_ROE = "生鱼卵。太棒了。"
WAXWELL.DESCRIBE.KYNO_ROE_COOKED = "鱼蛋现在烤熟了。"

WAXWELL.DESCRIBE.KYNO_SHARK_FIN = "从最出色的击杀中获得的奖品。"

WAXWELL.DESCRIBE.KYNO_BEANBUGS = "令人兴奋的小动物，不是吗？"
WAXWELL.DESCRIBE.KYNO_BEANBUGS_COOKED = "我真的这么渴望食物吗？"

WAXWELL.DESCRIBE.KYNO_GUMMYBUG = "恶心。"
WAXWELL.DESCRIBE.KYNO_GUMMYBUG_COOKED = "呃！"

WAXWELL.DESCRIBE.KYNO_WHEAT = "这比面粉更有用。"
WAXWELL.DESCRIBE.KYNO_WHEAT_COOKED = "这比面粉更有用。"

WAXWELL.DESCRIBE.KYNO_FLOUR = "哼。"

WAXWELL.DESCRIBE.KYNO_SPOTSPICE = "辣。"

WAXWELL.DESCRIBE.KYNO_SAP = "我不想把它粘到我的手套上。"
WAXWELL.DESCRIBE.KYNO_SAP_SPOILED = "苦乐参半。"

WAXWELL.DESCRIBE.KYNO_SYRUP = "烹饪糖浆"

WAXWELL.DESCRIBE.KYNO_COFFEEBEANS = "看到这些颜色很奇怪。"
WAXWELL.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "比生的好，但也许有更好的方法来准备它们？"

WAXWELL.DESCRIBE.DUG_KYNO_COFFEEBUSH = "Hm. I'm unable to get a reading."

WAXWELL.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "A plant with purpose.",
	PICKED = "Temporarily exhausted.",
	WITHERED = "Unproductive.",
}

WAXWELL.DESCRIBE.DUG_KYNO_SPOTBUSH = "What an aromatic bush."

WAXWELL.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "Aromatic.",
	PICKED = "Depleted.",
	BURNING = "Predictable.",
}

WAXWELL.DESCRIBE.KYNO_SPOTSPICE_LEAF = "这会让事情变得更有趣。"

WAXWELL.DESCRIBE.KYNO_MUSSEL = "它们是美味佳肴……"
WAXWELL.DESCRIBE.KYNO_MUSSEL_COOKED = "现在看起来对健康的危害已经减少了。"

WAXWELL.DESCRIBE.KYNO_HUMANMEAT = "现在除了腐烂没有别的办法了。或者是吗？"
WAXWELL.DESCRIBE.KYNO_HUMANMEAT_COOKED = "走文明路线。"
WAXWELL.DESCRIBE.KYNO_HUMANMEAT_DRIED = "现在没有水分，也没有胃口..."

WAXWELL.DESCRIBE.COFFEE = "我期待这个。"

WAXWELL.DESCRIBE.BISQUE = "食物很棒，还能改进。"

WAXWELL.DESCRIBE.JELLYOPOP = "嗯...我觉得这和我不太吻合。"

WAXWELL.DESCRIBE.SHARKFINSOUP = "我精致的味觉享受着危险的滋味。"

WAXWELL.DESCRIBE.TROPICALBOUILLABAISSE = "嗯...需要更多的鱼。"

WAXWELL.DESCRIBE.MUSSELBOUILLABAISE = "我真的很期待一顿丰盛的晚餐。"

WAXWELL.DESCRIBE.SWEETPOTATOSOUFFLE = "为什么，这看起来有点好吃！"

WAXWELL.DESCRIBE.FEIJOADA = "我够饿了吗？"

WAXWELL.DESCRIBE.GUMMY_CAKE = "焦油质地的蛋糕。"

WAXWELL.DESCRIBE.HARDSHELL_TACOS = "至少贝壳是新鲜的。"

WAXWELL.DESCRIBE.ICEDTEA = "提神。"

WAXWELL.DESCRIBE.NETTLELOSANGE = "药用。"

WAXWELL.DESCRIBE.SNAKEBONESOUP = "这是一种比较淡的肉汤。"

WAXWELL.DESCRIBE.STEAMEDHAMSANDWICH = "它们显然是烤过的。"

WAXWELL.DESCRIBE.TEA = "一杯茶。"

WAXWELL.DESCRIBE.BUBBLETEA = "提神醒脑。"

WAXWELL.DESCRIBE.FRENCHONIONSOUP = "这是一种相当淡的肉汤。"

WAXWELL.DESCRIBE.SLAW = "粗粮。"

WAXWELL.DESCRIBE.LOTUSBOWL = "一个人到期了。"

WAXWELL.DESCRIBE.POI = "好诡异的食物。"

WAXWELL.DESCRIBE.JELLYBEAN_HUNGER = "我想里面有十七个。"
WAXWELL.DESCRIBE.JELLYBEAN_SUPER = "我想里面有十七个。"
WAXWELL.DESCRIBE.JELLYBEAN_SANITY = "我想里面有十七个。"

WAXWELL.DESCRIBE.BOWLOFGEARS = "恶心。"

WAXWELL.DESCRIBE.LONGPIGMEAL = "这是个糟糕的主意。"

WAXWELL.DESCRIBE.CUCUMBERSALAD = "黄瓜不错。"

WAXWELL.DESCRIBE.KYNO_WILDWHEAT = "簇生。"

WAXWELL.DESCRIBE.KYNO_WILDWHEAT =
{
	GENERIC = "Crude, but useful.",
	PICKED = "Depleted.",
	WITHERED = "Pathetic.",
	BURNING = "Ruined.",
}

WAXWELL.DESCRIBE.KYNO_MEALGRINDER = "这看起来需要艰苦的工作。"

WAXWELL.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "I could, perhaps, produce a makeshift garnish.",
	PICKED = "It's as hollow as this withered world.",
	BURNING = "Needlessly destroyed.",
}

WAXWELL.DESCRIBE.GORGE_BREAD = "哼。我需要用这个来做点什么。"
WAXWELL.DESCRIBE.GORGE_SWEET_CHIPS = "这很好，我必须承认。"
WAXWELL.DESCRIBE.GORGE_VEGETABLE_SOUP = "健康的一餐。"
WAXWELL.DESCRIBE.GORGE_JELLY_SANDWICH = "一个不错的果酱三明治。"
WAXWELL.DESCRIBE.GORGE_FISH_STEW = "我想是一顿非常均衡的饭菜。"
WAXWELL.DESCRIBE.GORGE_MEAT_STEW = "切勿闲置。"
WAXWELL.DESCRIBE.GORGE_ONION_CAKE = "比起这种蛋糕，我更喜欢甜蛋糕。"
WAXWELL.DESCRIBE.GORGE_POTATO_PANCAKES = "只是少了糖浆而已。"
WAXWELL.DESCRIBE.GORGE_POTATO_SOUP = "菜肴美味可口，但环境还需改善。"
WAXWELL.DESCRIBE.GORGE_FISHBALL_SKEWERS = "如果你赶时间，它是不错的选择。"
WAXWELL.DESCRIBE.GORGE_MEAT_SKEWERS = "如果你赶时间，它是不错的选择。"
WAXWELL.DESCRIBE.GORGE_STONE_SOUP = "菜肴美味可口，但环境还需改善。"
WAXWELL.DESCRIBE.GORGE_CROQUETTE = "虽然不是最好的，但我还是要了。嗯哼。"
WAXWELL.DESCRIBE.GORGE_ROAST_VEGETABLES = "不是我的首选。"
WAXWELL.DESCRIBE.GORGE_MEATLOAF = "配肉的上等面包。"
WAXWELL.DESCRIBE.GORGE_CARROT_SOUP = "菜肴美味可口，但环境还需改善。"
WAXWELL.DESCRIBE.GORGE_FISHPIE = "看起来可以吃。"
WAXWELL.DESCRIBE.GORGE_FISHCHIPS = "我觉得我做得很好。"
WAXWELL.DESCRIBE.GORGE_MEATPIE = "这是一道美味佳肴。"
WAXWELL.DESCRIBE.GORGE_SLIDERS = "我更喜欢传统的。"
WAXWELL.DESCRIBE.GORGE_JELLY_ROLL = "一卷不错的果酱。"
WAXWELL.DESCRIBE.GORGE_CARROT_CAKE = "我不敢相信蛋糕是真的。"
WAXWELL.DESCRIBE.GORGE_GARLICMASHED = "看起来可以吃。"
WAXWELL.DESCRIBE.GORGE_GARLICBREAD = "啊，我有时真的很怀念过去的烧烤美味。"
WAXWELL.DESCRIBE.GORGE_TOMATO_SOUP = "菜肴美味可口，但环境还需改善。"
WAXWELL.DESCRIBE.GORGE_SAUSAGE = "美味的传统香肠。"
WAXWELL.DESCRIBE.GORGE_CANDIEDFISH = "嗯哼。我想我也能体会到这一点。"
WAXWELL.DESCRIBE.GORGE_STUFFEDMUSHROOM = "美味佳肴。"
WAXWELL.DESCRIBE.GORGE_BRUSCHETTA = "一顿美餐。"
WAXWELL.DESCRIBE.GORGE_HAMBURGER = "查理...我知道你仍然喜欢这些..."
WAXWELL.DESCRIBE.GORGE_FISHBURGER = "查理......我知道你仍然喜欢这些......"
WAXWELL.DESCRIBE.GORGE_MUSHROOMBURGER = "查理......我知道你仍然喜欢这些......"
WAXWELL.DESCRIBE.GORGE_FISH_STEAK = "我想是一顿非常均衡的饭菜。"
WAXWELL.DESCRIBE.GORGE_CURRY = "温暖舒适的食物。"
WAXWELL.DESCRIBE.GORGE_SPAGHETTI = "向厨师致意！"
WAXWELL.DESCRIBE.GORGE_POACHEDFISH = "鲑鱼是独一无二的。"
WAXWELL.DESCRIBE.GORGE_SHEPHERD_PIE = "一个充满活力和力量的馅饼。"
WAXWELL.DESCRIBE.GORGE_CANDY = "它几乎全是糖。"
WAXWELL.DESCRIBE.GORGE_BREAD_PUDDING = "真可爱。"
WAXWELL.DESCRIBE.GORGE_BERRY_TART = "缺少一些东西。"
WAXWELL.DESCRIBE.GORGE_MACARONI = "那时候我会吃速食版的这个。"
WAXWELL.DESCRIBE.GORGE_BAGEL_AND_FISH = "对于鲑鱼菜肴来说，这已经足够了。"
WAXWELL.DESCRIBE.GORGE_GRILLED_CHEESE = "可惜了。"
WAXWELL.DESCRIBE.GORGE_CREAMMUSHROOM = "美味的蘑菇汤。"
WAXWELL.DESCRIBE.GORGE_MANICOTTI = "美味佳肴，适合国王享用。"
WAXWELL.DESCRIBE.GORGE_CHEESEBURGER = "查理......我知道你仍然喜欢这些......"
WAXWELL.DESCRIBE.GORGE_FETTUCCINE = "我受宠若惊。"
WAXWELL.DESCRIBE.GORGE_ONION_SOUP = "对我的嘴来说不是很舒服。"
WAXWELL.DESCRIBE.GORGE_BREADED_CUTLET = "精彩！"
WAXWELL.DESCRIBE.GORGE_CREAMY_FISH = "这已经很不错了。"
WAXWELL.DESCRIBE.GORGE_PIZZA = "哼。我要这个。"
WAXWELL.DESCRIBE.GORGE_POT_ROAST = "这可是一大坨肉啊！"
WAXWELL.DESCRIBE.GORGE_CRAB_CAKE = "这太可怕了，但我希望味道不会。"
WAXWELL.DESCRIBE.GORGE_STEAK_FRITES = "终于！至少吃了顿像样的饭。"
WAXWELL.DESCRIBE.GORGE_SHOOTER_SANDWICH = "需要一些蘑菇。"
WAXWELL.DESCRIBE.GORGE_BACON_WRAPPED = "真是可恶！"
WAXWELL.DESCRIBE.GORGE_CRAB_ROLL = "令人愉快。"
WAXWELL.DESCRIBE.GORGE_MEAT_WELLINGTON = "哼哼。我必须把这个功劳归于他。"
WAXWELL.DESCRIBE.GORGE_CRAB_RAVIOLI = "令人愉快。"
WAXWELL.DESCRIBE.GORGE_CARAMEL_CUBE = "我不应该……"
WAXWELL.DESCRIBE.GORGE_SCONE = "哼哼。"
WAXWELL.DESCRIBE.GORGE_TRIFLE = "哼哼。"
WAXWELL.DESCRIBE.GORGE_CHEESECAKE = "嗯哼。我必须承认，这很好。"

WAXWELL.DESCRIBE.DUCKYOUGLERMZ = "为什么这首先存在？"

WAXWELL.DESCRIBE.KYNO_ALOE = "我应该吃掉它。"
WAXWELL.DESCRIBE.KYNO_ALOE_COOKED = "我应该吃掉它。"
WAXWELL.DESCRIBE.KYNO_ALOE_GROUND = "我应该吃掉它。"
WAXWELL.DESCRIBE.KYNO_ALOE_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.FARM_PLANT_KYNO_ALOE = "我应该吃掉它。"
WAXWELL.DESCRIBE.KYNO_ALOE_OVERSIZED = "我应该吃掉它。"
WAXWELL.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "可惜了。"

WAXWELL.DESCRIBE.KYNO_CUCUMBER = "我可以吃一次不粘的东西吗？"
WAXWELL.DESCRIBE.KYNO_CUCUMBER_COOKED = "这不是改进。"
WAXWELL.DESCRIBE.KYNO_CUCUMBER_GROUND = "我可以吃一次不粘的东西吗？"
WAXWELL.DESCRIBE.KYNO_CUCUMBER_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "这样的劳动是我的下贱。"
WAXWELL.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "我可以吃一次不粘的东西吗？"
WAXWELL.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "我可以吃一次不粘的东西吗？"
WAXWELL.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "我可以吃一次不粘的东西吗？"

WAXWELL.DESCRIBE.KYNO_RADISH = "红萝卜。"
WAXWELL.DESCRIBE.KYNO_RADISH_COOKED = "它至少有一半开胃。"
WAXWELL.DESCRIBE.KYNO_RADISH_GROUND = "一个带红色的萝卜。"
WAXWELL.DESCRIBE.KYNO_RADISH_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.FARM_PLANT_KYNO_RADISH = "带红色的萝卜。"
WAXWELL.DESCRIBE.KYNO_RADISH_OVERSIZED = "带红色的萝卜。"
WAXWELL.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "可惜了。"

WAXWELL.DESCRIBE.KYNO_FENNEL = "普通。"
WAXWELL.DESCRIBE.KYNO_FENNEL_COOKED = "至少更精致一点。"
WAXWELL.DESCRIBE.KYNO_FENNEL_GROUND = "普通。"
WAXWELL.DESCRIBE.KYNO_FENNEL_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "普通。"
WAXWELL.DESCRIBE.KYNO_FENNEL_OVERSIZED = "普通。"
WAXWELL.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "可惜了。"

WAXWELL.DESCRIBE.KYNO_SWEETPOTATO = "准备烹饪。"
WAXWELL.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "商店买的味道不一样。"
WAXWELL.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "准备烹饪。"
WAXWELL.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "准备烹饪。"
WAXWELL.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "准备烹饪。"
WAXWELL.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "可惜了。"

WAXWELL.DESCRIBE.KYNO_PARZNIP = "我不喜欢蔬菜。"
WAXWELL.DESCRIBE.KYNO_PARZNIP_COOKED = "我不喜欢蔬菜。"
WAXWELL.DESCRIBE.KYNO_PARZNIP_EATEN = "我不喜欢蔬菜。"
WAXWELL.DESCRIBE.KYNO_PARZNIP_GROUND = "我不喜欢蔬菜。"
WAXWELL.DESCRIBE.KYNO_PARZNIP_BIG = "超大蔬菜。"
WAXWELL.DESCRIBE.KYNO_PARZNIP_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "我不喜欢蔬菜。"
WAXWELL.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "我不喜欢蔬菜。"
WAXWELL.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "可惜了。"

WAXWELL.DESCRIBE.KYNO_TURNIP = "这是一个大的球茎萝卜。"
WAXWELL.DESCRIBE.KYNO_TURNIP_COOKED = "几乎没有改善味道。"
WAXWELL.DESCRIBE.KYNO_TURNIP_GROUND = "这是一个大的球茎萝卜。"
WAXWELL.DESCRIBE.KYNO_TURNIP_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "这是一个大的球茎萝卜。"
WAXWELL.DESCRIBE.KYNO_TURNIP_OVERSIZED = "这是一个大的球茎萝卜。"
WAXWELL.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "可惜了。"

WAXWELL.DESCRIBE.KYNO_RICE = "一种健康的蔬菜。"
WAXWELL.DESCRIBE.KYNO_RICE_COOKED = "一种健康的蔬菜。"
WAXWELL.DESCRIBE.KYNO_RICE_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "这样的劳动有失我的身份。"
WAXWELL.DESCRIBE.FARM_PLANT_KYNO_RICE = "这是一个稻米茎。"
WAXWELL.DESCRIBE.KYNO_RICE_OVERSIZED = "这是一个稻米茎。"
WAXWELL.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "可惜了。"

WAXWELL.DESCRIBE.KYNO_SEEDS_KIT = "耕作是一项杂乱的工作。"

WAXWELL.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "Could be used as a food source in a pinch.",
	PICKED = "They've withdrawn.",
	WITHERED = "Utterly unproductive.",
}

WAXWELL.DESCRIBE.KYNO_LIMPETS = "黏糊糊的，难以消化。"
WAXWELL.DESCRIBE.KYNO_LIMPETS_COOKED = "美味佳肴？真的吗？"

WAXWELL.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "How dainty.",
	PICKED = "Temporarily depleted.",
	BURNING = "A careless loss.",
}

WAXWELL.DESCRIBE.KYNO_LOTUS_ROOT = "为几株湿漉漉的植物，竟要费这么大功夫。"
WAXWELL.DESCRIBE.KYNO_LOTUS_FLOWER = "我更喜欢深色的花朵。"
WAXWELL.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "一个人到期了。"

WAXWELL.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "Sea garbage.",
	PICKED = "Temporarily depleted.",
	BURNING = "An unnecessary loss.",
}

WAXWELL.DESCRIBE.KYNO_SEAWEEDS = "海洋垃圾。"
WAXWELL.DESCRIBE.KYNO_SEAWEEDS_COOKED = "我讨厌吃这个。"
WAXWELL.DESCRIBE.KYNO_SEAWEEDS_DRIED = "呃。"
WAXWELL.DESCRIBE.KYNO_SEAWEEDS_ROOT = "为一些湿草做的工作太多了。"

WAXWELL.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "I don't enjoy them.",
	PICKED = "It will recover.",
	BURNING = "Careless.",
}

WAXWELL.DESCRIBE.KYNO_TAROROOT_ROOT = "为几株湿漉漉的植物，竟要费这么大功夫。"
WAXWELL.DESCRIBE.KYNO_TAROROOT = "又一个无聊的植物。"
WAXWELL.DESCRIBE.KYNO_TAROROOT_COOKED = "至少更精致一点。"

WAXWELL.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "Interesting, at least.",
	PICKED = "Temporarily depleted.",
	BURNING = "Careless.",
}

WAXWELL.DESCRIBE.KYNO_WATERYCRESS_ROOT = "为几株湿漉漉的植物，竟要费这么大功夫。"
WAXWELL.DESCRIBE.KYNO_WATERYCRESS = "卷心菜。"

WAXWELL.DESCRIBE.WATERYCRESSBOWL = "我想你可以用任何东西做汤。"

WAXWELL.DESCRIBE.KYNO_SALT = "添加太多是感官上的盐。"

WAXWELL.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "Primitive, but functional.",
	PICKED = "Depleted.",
	BURNING = "Needlessly destroyed.",
}

WAXWELL.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "贻贝无法抗拒。"

WAXWELL.DESCRIBE.CATFOOD = "猫的食物。"

WAXWELL.DESCRIBE.KATFOOD = "猫粮。"

WAXWELL.DESCRIBE.KYNO_BANANATREE = 
{ 
	GENERIC = "Hmph. I know it's different from that one, but I'm not buying it yet.",
	PICKED = "Depleted, for now.",
	CHOPPED = "Disposed of.",
	BURNING = "A careless end.",
	BURNT = "Erased completely.",
}

WAXWELL.DESCRIBE.KYNO_BANANA = "哼。尝起来像香蕉。"
WAXWELL.DESCRIBE.KYNO_BANANA_COOKED = "现在好多了。"

WAXWELL.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "How luxurious.",
	PICKED = "Depleted.",
	CHOPPED = "Disposed of.",
	BURNING = "A careless end.",
	BURNT = "Gone.",
}

WAXWELL.DESCRIBE.KYNO_KOKONUT = "会对人的脑袋造成相当大的伤害。"
WAXWELL.DESCRIBE.KYNO_KOKONUT_HALVED = "我把一个椰子变成了两个......魔法！"
WAXWELL.DESCRIBE.KYNO_KOKONUT_COOKED = "现在我会坚持下去。"

WAXWELL.DESCRIBE.BOWLOFPOPCORN = "更精致一点，我猜。"

WAXWELL.DESCRIBE.FIGJUICE = "提神醒脑。"

WAXWELL.DESCRIBE.COCONUTWATER = "提神醒脑。"

WAXWELL.DESCRIBE.EYEBALLSPAGHETTI = "我为什么要这么做？"

WAXWELL.DESCRIBE.FORGETMELOTS_SEEDS = "这样的劳动有失我的身份。"

WAXWELL.DESCRIBE.FIRENETTLES_SEEDS = "这样的劳动有失我的身份。"

WAXWELL.DESCRIBE.TILLWEED_SEEDS = "这样的劳动有失我的身份。"

WAXWELL.DESCRIBE.KYNO_FLOATILIZER = "手拿粪肥不绅士。"

WAXWELL.DESCRIBE.KYNO_TWIGGYNUTS = "只是一堆坚果。"

WAXWELL.DESCRIBE.KYNO_REPAIRTOOL = "它能防止东西腐烂。"

WAXWELL.DESCRIBE.KYNO_KOI = "别跟我做锦鲤。"
WAXWELL.DESCRIBE.KYNO_KOI_COOKED = "别跟我做锦鲤。"

WAXWELL.DESCRIBE.KYNO_TROPICALFISH = "它属于烤串。"
WAXWELL.DESCRIBE.KYNO_TROPICALFISH_COOKED = "它属于烤串。"

WAXWELL.DESCRIBE.KYNO_NEONFISH = "你从来不眨眼吗？"
WAXWELL.DESCRIBE.KYNO_NEONFISH_COOKED = "别担心，海里有很多。"

WAXWELL.DESCRIBE.KYNO_GROUPER = "真是个丑陋的生物。"
WAXWELL.DESCRIBE.KYNO_GROUPER_COOKED = "外面是紫色，中间是粉红色。"
 
WAXWELL.DESCRIBE.KYNO_PIERROTFISH = "令人愉悦的细条纹。"
WAXWELL.DESCRIBE.KYNO_PIERROTFISH_COOKED = "我会用几周的时间从牙齿里剔骨头。"

WAXWELL.DESCRIBE.KYNO_SALMONFISH = "难闻的气味，但很好吃。"
WAXWELL.DESCRIBE.KYNO_SALMONFISH_COOKED = "我很喜欢熏鲑鱼。"

WAXWELL.DESCRIBE.TURF_PINKPARK = "哼。"
WAXWELL.DESCRIBE.TURF_STONECITY = "提供坚实的基础。"
WAXWELL.DESCRIBE.TURF_FIELDS = "草坪。"
WAXWELL.DESCRIBE.TURF_TIDALMARSH = "它似乎是一块草皮。"

WAXWELL.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "Ah. It's ready.",
	PICKED = "Any method to improve the food around here is welcome.",
}

WAXWELL.DESCRIBE.KYNO_SALTRACK_INSTALLER = "在我们组装之前只是没用的木棍。"

WAXWELL.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "它已经很粘了。"

WAXWELL.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "晚餐应该随时到。"

WAXWELL.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "Charmed, I'm sure.",
	SLEEPING = "Business is closed for today.",
}

WAXWELL.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "A sickly sweet aroma wafts from its branches.",
	CHOPPED = "It won't produce sap now.",
	SAPPED = "The sap is ready for collection.",
	PICKED = "It is filling. Ever so slowly.",
	BURNING = "Predictable.",
	BURNT = "Reduced to nothing.",
}

WAXWELL.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "This tree has seen better days.",
	CHOPPED = "Disposed of.",
	SAPPED = "Still exploitable.",
	PICKED = "Well it's ruined now.",
	BURNING = "Efficient.",
	BURNT = "Erased.",
}

WAXWELL.DESCRIBE.KYNO_SUGARTREE_BUD = "如果我想要更多的树，我需要这个。"

WAXWELL.DESCRIBE.KYNO_SUGARTREE_FLOWER = "我充满了踩踏它的非理性冲动。"
WAXWELL.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "我充满了踩踏它的非理性冲动。"

WAXWELL.DESCRIBE.KYNO_SUGARTREE_PETALS = "我充满了踩踏它的非理性冲动。"

WAXWELL.DESCRIBE.KYNO_PEBBLECRAB = "你不能躲着我。"

WAXWELL.DESCRIBE.KYNO_CRABMEAT = "啊，多么精致。"
WAXWELL.DESCRIBE.KYNO_CRABMEAT_COOKED = "加点黄油就完美了。"
WAXWELL.DESCRIBE.KYNO_CRABMEAT_DRIED = "啊，多么高雅。"

WAXWELL.DESCRIBE.KYNO_CRABKINGMEAT = "啊，多么高雅。"
WAXWELL.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "啊，多么精致。"
WAXWELL.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "啊，多么精致。"

WAXWELL.DESCRIBE.KYNO_SLAUGHTERTOOL = "我不介意弄脏我的手。"

WAXWELL.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "Foul fowl.",
	COOP = "At least it's productive.",
}

WAXWELL.DESCRIBE.KYNO_CHICKEN_EGG = "我喜欢把它想象成一个小鸡监狱。"
WAXWELL.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "I wonder if the bird inside is as oversized as its shell."
WAXWELL.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "阳光面朝上。"

WAXWELL.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "A humble shelter, but quite productive.",
	FULL = "They've been quite productive.",
	BURNT = "Reduced to ashes. How predictable.",
}

WAXWELL.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "我感觉很好。"

WAXWELL.DESCRIBE.KYNO_COOKWARE_KIT = "让我们开始吧。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_SYRUP = "我需要树液来制作糖浆。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "我需要树液来制作糖浆。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_BIG_POT = "你知道，魔法可以更快地把它烤沸。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_BIG = "你知道，魔法可以更快地把它烤沸。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "我不会让它和水壶说话。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_SMALL = "我不会让它和水壶说话。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_GRILL = "我相信我会烤肉。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "这里对我没用。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "我更喜欢更大的烤架。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "至少它是便携的。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_ELDER = "我需要树液来制作糖浆。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "这是一个烤箱。用于烹饪。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "温馨。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "一点点驯化。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_OVEN = "这让事情变得更方便了。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "这让事情变得更方便了。"
WAXWELL.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "事情变得更方便了。"

WAXWELL.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "What will this unearth?",
	FLIPPED = "Predictable.",
}

WAXWELL.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "并非所有人都能找到最后的安息之地。"

WAXWELL.DESCRIBE.KYNO_SUGARFLY = "这是一朵会飞的甜花。"
WAXWELL.DESCRIBE.KYNO_SUGARFLYWINGS = "哈哈哈。我抓住了她！"

WAXWELL.DESCRIBE.KYNO_WATERY_CRATE = "不是所有人都能找到最后的安息地。"

WAXWELL.DESCRIBE.KYNO_TUNACAN = "鱼可能在里面。"
WAXWELL.DESCRIBE.KYNO_TUNACAN_OPEN = "鱼可能在里面。"

WAXWELL.DESCRIBE.KYNO_CANNEDFOOD = "食物可能包含在里面。"
WAXWELL.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "哼。他们没有撒谎。"

WAXWELL.DESCRIBE.KYNO_POP = "来自海水的可喜变化。"

WAXWELL.DESCRIBE.KYNO_MYSTERYMEAT = "相当恶心。"

WAXWELL.DESCRIBE.KYNO_BOTTLE_SOUL = "这个小鬼没有限制，说到灵魂……"

WAXWELL.DESCRIBE.SOULSTEW = "当谈到灵魂时，那个小鬼没有限制......"

WAXWELL.DESCRIBE.FORTUNECOOKIE = "愚蠢。"

WAXWELL.DESCRIBE.HORNOCUPIA = "现在是晚餐时间。"

WAXWELL.DESCRIBE.CHEESE_YELLOW = "至少是一顿精致的饭菜！"
WAXWELL.DESCRIBE.CHEESE_WHITE = "至少是一顿精致的饭菜！"
WAXWELL.DESCRIBE.CHEESE_KOALEFANT = "至少是一顿精致的饭菜！"

WAXWELL.DESCRIBE.MILK_BOX = "我不太喜欢它，但还好。"

WAXWELL.DESCRIBE.WATERCUP = "我应该多喝点。"

WAXWELL.DESCRIBE.HONEYJAR = "甜美同时，粘稠。"

WAXWELL.DESCRIBE.CRAB_ARTICHOKE = "我会说它有点精致。"

WAXWELL.DESCRIBE.PEPPERROLLS = "直接塞进我嘴里！"

WAXWELL.DESCRIBE.KYNO_SAPHEALER = "治愈树木的方法。"

WAXWELL.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "It stood no chance.",
	PICKED = "Stripped clean.",
	BURNING = "Utterly ruined.",
}

WAXWELL.DESCRIBE.KYNO_GHOST_PIRATE = "我绝不会落得同样的下场！"

WAXWELL.DESCRIBE.KYNO_BUCKET_EMPTY = "嗯……我想即使是国王也需要。"
WAXWELL.DESCRIBE.KYNO_BUCKET_METAL = "好。我认为，即使是国王也需要它。"
WAXWELL.DESCRIBE.KYNO_BUCKET_WATER = "至少不是肮脏的池塘水。"

WAXWELL.DESCRIBE.KYNO_MILK_BEEFALO = "营养来源。"
WAXWELL.DESCRIBE.KYNO_MILK_KOALEFANT = "营养来源。"

WAXWELL.DESCRIBE.KYNO_CAP_DRIED = "干蔬菜，哼。"

WAXWELL.DESCRIBE.KYNO_PLANTMEAT_DRIED = "我的牙齿太老了，不适合这个。"

WAXWELL.DESCRIBE.KYNO_BREWBOOK = "很好。如果我能掌握黑暗艺术，那么酿造能有多难？"

WAXWELL.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "Sure, some wine will go nice around here.",
	BREWING_LONG = "A slow, tedious process.",
	BREWING_SHORT = "Nearly finished.",
	DONE = "At last.",
	BURNT = "A predictable failure.",
}

WAXWELL.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "Quality of ingredients makes no difference to the finished product.",
	BREWING_LONG = "This process drags on.",
	BREWING_SHORT = "Nearly finished.",
	DONE = "Acceptable results.",
	BURNT = "Ruined.",
}

WAXWELL.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "Endless labor for a bit of sweetness.",
	HONEY = "At least their efforts pay off.",
	NECTAR = "Still refining the product.",
	BURNING = "Reduced to charred excess.",
}

WAXWELL.DESCRIBE.KYNO_NECTAR_POD = "需要一个合适的容器来变成蜂蜜。"

WAXWELL.DESCRIBE.KYNO_OAKTREE_POD = "橡树...哼。"
WAXWELL.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "我会吃的。但我不喜欢它。"

WAXWELL.DESCRIBE.KYNO_PIKO = "嘘，害虫。"
WAXWELL.DESCRIBE.KYNO_PIKO_ORANGE = "真有趣。"

WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "It's a tree. What did I expect.",
	CHOPPED = "Useful, at least.",
	BURNING = "Careless.",
	BURNT = "Reduced to nothing.",
}

WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE =
{
	GENERIC = "It's a tree, full of squirrels. What did I expect.",
	BURNING = "Problem solved.",
}

WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "也许我可以撬开它。"

WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "They copied the pigs, but they're even less intelligent.",
	BURNT = "Utterly destroyed.",
}

WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "I suppose everyone needs to live somewhere...",
	CRAFTED = "An improvement, at least.",
	BURNT = "Disgusting, even now.",
}

WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "How did he acquire all of those items?",
	OCCUPIED = "Business is closed, it seems.",
}

WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "He sure knows how to make a proper showcase.",
	EMPTY = "Utterly depleted.",
}

WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "太好了，他不知怎么找到了进入这个领域的方法。"
WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_POND = "比它想象的要深得多。"
WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "多么普通的小植物。"
WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "一小堆黄沙。"
WAXWELL.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "我和他没有争吵。"

WAXWELL.DESCRIBE.KYNO_SAMMYHAT = "不适合一个花花公子。"

WAXWELL.DESCRIBE.KINGFISHER = "相当宽大的下颌骨。"

WAXWELL.DESCRIBE.TOUCAN = "彩色害虫。"
WAXWELL.DESCRIBE.TOUCAN_CHUBBY = "彩色害虫。"

WAXWELL.DESCRIBE.WETGOOP2 = "多么没文化。"

WAXWELL.DESCRIBE.BEER = "我想念他们，真的。"

WAXWELL.DESCRIBE.PALEALE = "我想念他们，真的。"

WAXWELL.DESCRIBE.TEAGREEN = "我什至不记得上一次喝上一杯像样的茶是什么时候了。"

WAXWELL.DESCRIBE.TEARED = "我什至不记得上次我喝了一杯像样的茶是什么时候。"

WAXWELL.DESCRIBE.MEAD = "野蛮人的饮料。"

WAXWELL.DESCRIBE.KYNO_JELLY = "弄脏了我的好手套。"

WAXWELL.DESCRIBE.KYNO_MAYONNAISE = "啊……我想念星期天的午餐吃这些。"

WAXWELL.DESCRIBE.TARTARSAUCE = "哼，我在这里，以为我再也见不到这个了。"

WAXWELL.DESCRIBE.KYNO_PICKLES = "呃，不是那么精致的食物，但它可以胜任。"

WAXWELL.DESCRIBE.KYNO_WINE = "最后，美术。"

WAXWELL.DESCRIBE.KYNO_JUICE = "提神醒脑。"

WAXWELL.DESCRIBE.KYNO_POISON_FROGLEGS = "美味，如果没有下毒的话。"
WAXWELL.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "我要冒这个险吗？"

WAXWELL.DESCRIBE.POISONFROGGLEBUNWICH = "有点刺激。"

WAXWELL.DESCRIBE.KYNO_BREWINGRECIPECARD = "字迹太模糊，无法阅读。"

WAXWELL.DESCRIBE.KYNO_OIL = "至少我们会在这里好好利用它。"

WAXWELL.DESCRIBE.BERRYSUNDAE = "圣代，圣代，圣代！"

WAXWELL.DESCRIBE.CHOCOLATE_BLACK = "我更喜欢酸的。"
WAXWELL.DESCRIBE.CHOCOLATE_WHITE = "我更喜欢酸的。"

WAXWELL.DESCRIBE.TRICOLORDANGO = "它们看起来还不错。"
 
WAXWELL.DESCRIBE.FRIESFRENCH = "有人不喜欢这样吗？"

WAXWELL.DESCRIBE.PIRATERUM = "我不应该喝那个。"

WAXWELL.DESCRIBE.TWISTEDTEQUILA = "只喝一口，我保证。"

WAXWELL.DESCRIBE.ONIONRINGS = "这是快餐......"

WAXWELL.DESCRIBE.DONUTS = "哼。别介意我选一个。"
WAXWELL.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "哼。别介意我选一个。"
WAXWELL.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "哼。别介意我选一个。"
 
WAXWELL.DESCRIBE.CINNAMONROLL = "至少是适当的食物！"

WAXWELL.DESCRIBE.GUMMYBEARGERS = "我希望它不会召唤怪物或类似的东西。"

WAXWELL.DESCRIBE.PRETZEL = "我打赌她也想念他们。"

WAXWELL.DESCRIBE.CORNINCUP = "果糖含量非常高。"

WAXWELL.DESCRIBE.COTTONCANDY = "他们在我们的节目中无处不在......"

WAXWELL.DESCRIBE.ROASTEDHAZELNUTS = "食物……至少是。"

WAXWELL.DESCRIBE.MONSTERMUFFIN = "没有什么新东西是我没见过的。"

WAXWELL.DESCRIBE.PINKCAKE = "好心。我打赌她一定会喜欢这样的。"

WAXWELL.DESCRIBE.CHIPSBAG = "我要一些。"

WAXWELL.DESCRIBE.LITTLEBREAD = "哼。我需要在某些东西上使用这个。"

WAXWELL.DESCRIBE.HOTHOUND = "总比没有好，但仍然是垃圾食品。"

WAXWELL.DESCRIBE.MILKSHAKE = "她曾经点过一份这样的...如果我能再做一次..."
WAXWELL.DESCRIBE.MILKSHAKE_PRISMATIC = "她曾经订购过其中一份...如果我能再做一次..."

WAXWELL.DESCRIBE.NACHOS = "我不想弄脏我的手指。"

WAXWELL.DESCRIBE.BANANA_PUDDING = "我更喜欢其他种类的布丁……"

WAXWELL.DESCRIBE.SEA_PUDDING = "我更喜欢其他种类的布丁……"

WAXWELL.DESCRIBE.TOM_KHA_SOUP = "看起来不错。"

WAXWELL.DESCRIBE.MINERTREAT = "我不再是孩子了。"

WAXWELL.DESCRIBE.RADISHSALAD = "萝卜好东西。"

WAXWELL.DESCRIBE.PUMPKIN_SOUP = "食物很棒，但氛围还有待改善。"

WAXWELL.DESCRIBE.ALGAE_SOUP = "食物很棒，但氛围还有待改善。"

WAXWELL.DESCRIBE.PARZNIP_SOUP = "食物很棒，但氛围还有待改善。"

WAXWELL.DESCRIBE.NETTLEMEATED = "肉味和药用。"

WAXWELL.DESCRIBE.KYNO_SUGAR = "美味佳肴。"

WAXWELL.DESCRIBE.KYNO_BOTTLECAP = "这是关于什么的？新货币？"

WAXWELL.DESCRIBE.NUKACOLA = "我早该看到这个的。"
WAXWELL.DESCRIBE.NUKACOLA_QUANTUM = "我应该预见到这一点。"

WAXWELL.DESCRIBE.LIVINGSANDWICH = "黑魔法。"

WAXWELL.DESCRIBE.DURIANSPLIT = "榴莲，榴莲，榴莲劈开！"

WAXWELL.DESCRIBE.DURIANSOUP = "这是一道相当淡的肉汤。"

WAXWELL.DESCRIBE.DURIANMEATED = "这是一种后天养成的品味。"

WAXWELL.DESCRIBE.DURIANCHICKEN = "多么简单。"

WAXWELL.DESCRIBE.LUNARSOUP = "我不太喜欢翻炒酱。"

WAXWELL.DESCRIBE.PURPLEWOBSTERSOUP = "多么美味啊！"

WAXWELL.DESCRIBE.WOBSTERMONSTER = "看起来不太好。"

WAXWELL.DESCRIBE.SPIDERCAKE = "这太恶心了。"

WAXWELL.DESCRIBE.SUGARBOMBS = "一种含糖谷物。"

WAXWELL.DESCRIBE.BERRYBOMBS = "它弄脏了我的好手套。"

WAXWELL.DESCRIBE.ONIGIRIS = "嗯哼。我想这里没有比这更好的了。"

WAXWELL.DESCRIBE.OMURICE = "幼稚！"

WAXWELL.DESCRIBE.PAELLA = "终于！这里终于有像样的食物了"

WAXWELL.DESCRIBE.RISOTTO = "呈奶油状。"

WAXWELL.DESCRIBE.RICESAKE = "进展顺利... *嗝*"

WAXWELL.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "I could plant some of them near my camping site."

WAXWELL.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "A fitting throne for the king of the fruits.",
	PICKED = "Depleted.",
	WITHERED = "Pathetic.",
	BURNING = "Predictable.",
}

WAXWELL.DESCRIBE.KYNO_PINEAPPLE = "水果之王。"
WAXWELL.DESCRIBE.KYNO_PINEAPPLE_HALVED = "水果之王。"
WAXWELL.DESCRIBE.KYNO_PINEAPPLE_COOKED = "好东西。"

WAXWELL.DESCRIBE.PIZZA_TROPICAL = "我想，这是一个很好的补充。"

WAXWELL.DESCRIBE.PINACOLADA = "这是给统治者的最佳饮料。"

WAXWELL.DESCRIBE.CHIMAS = "苦乐参半。"

WAXWELL.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "Good. Now I don't have to water by hand.",
	ON = "Efficient, at least.",
}

WAXWELL.DESCRIBE.KYNO_FOODSACK = "虽不能让我变强，但能多几个口袋。"

WAXWELL.DESCRIBE.GUMMYWORMS = "说什么可怜。"

WAXWELL.DESCRIBE.SMORES = "哼。儿童餐。"

WAXWELL.DESCRIBE.NUKASHINE = "那个小恶魔给这件事带来了秘方。这东西会给我们所有人带来不幸。"

WAXWELL.DESCRIBE.ANTSLOG = "我为什么要吃这种食物？"

WAXWELL.DESCRIBE.KYNO_WORM_BONE = "哦，我喜欢这个样子。"

WAXWELL.DESCRIBE.SPOOKY_BRAIN_NOODLES = "他们怎么能把这叫做幽灵餐呢？"
WAXWELL.DESCRIBE.SPOOKY_BURGERZILLA = "哼哼。我把这个给他。"
WAXWELL.DESCRIBE.SPOOKY_DEADBREAD = "哼哼。"
WAXWELL.DESCRIBE.SPOOKY_JELLYBEANS = "离得这么近，它们看起来很吓人。"
WAXWELL.DESCRIBE.SPOOKY_POPSICLE = "呃..."
WAXWELL.DESCRIBE.SPOOKY_PUMPKINCREAM = "这肯定是威尔逊最糟糕的想法之一。"
WAXWELL.DESCRIBE.SPOOKY_SKULLCANDY = "这正是我们所需要的。"
WAXWELL.DESCRIBE.SPOOKY_TACODILE = "至少能吃顿像样的饭！"

WAXWELL.DESCRIBE.BUTTER_BEEFALO = "他们正试图复制它。"
WAXWELL.DESCRIBE.BUTTER_GOAT = "愚蠢的山羊！他们不想和我们分享他们珍贵的牛奶。"
WAXWELL.DESCRIBE.BUTTER_KOALEFANT = "毕竟，让那只愚蠢的野兽活着是一个明智的决定。"

WAXWELL.DESCRIBE.SPICE_CURE = "一种让我继续吃饭的方法。"
WAXWELL.DESCRIBE.SPICE_COLD = "冷淡。"
WAXWELL.DESCRIBE.SPICE_FIRE = "火在燃烧！"
WAXWELL.DESCRIBE.SPICE_FED = "会让我吃饱一段时间。"
WAXWELL.DESCRIBE.SPICE_MIND = "一种在混乱中保持头脑清醒的方法。"

WAXWELL.DESCRIBE.SUGARFLYMUFFIN = "这应该能阻止它不停地摆动翅膀。"

WAXWELL.DESCRIBE.EELTACOS = "脆壳熟鳗鱼。"

WAXWELL.DESCRIBE.MEATSKILLET = "我必须承认，那个厨师有一些好手艺。"

WAXWELL.DESCRIBE.MEATWALTZ = "这是什么可恶的事？！"

WAXWELL.DESCRIBE.COMPLETEBREAKFAST = "他早上不停地吃东西。"

WAXWELL.DESCRIBE.DUMPLINGS = "至少有一些像样的食物。"

WAXWELL.DESCRIBE.WARLYICEDTEA = "清爽。"

WAXWELL.DESCRIBE.WARLYTEA = "一点茶叶。"

WAXWELL.DESCRIBE.KYNO_TEALEAF = "我真想念那杯好茶。"

WAXWELL.DESCRIBE.KYNO_ITEMSLICER = "说实话，我天生就是剁肉的料。"
WAXWELL.DESCRIBE.KYNO_ITEMSLICER_GOLD = "老实说，我天生就是剁肉的料。"

WAXWELL.DESCRIBE.COXINHA = "我的手指沾了油。"

WAXWELL.DESCRIBE.LAZYDESSERT = "我打赌那只愚蠢的蚁狮会喜欢这样的东西。"

WAXWELL.DESCRIBE.CRABKINGFEAST = "这里的食物最近越来越大了。"

WAXWELL.DESCRIBE.PIENAPPLE = "这是馅饼之王吗？"

WAXWELL.DESCRIBE.JAWSBREAKER = "以前的舔舔糖体积更小。"

WAXWELL.DESCRIBE.AVOCADOTOAST = "这不是我喜欢的菜。"

WAXWELL.DESCRIBE.RICEPUDDING = "健康的布丁选择。"

WAXWELL.DESCRIBE.SHARKSUSHI = "皇家美食。"

WAXWELL.DESCRIBE.WOBSTERBREADED = "现在他的爪子都没了，我可以放心地吃了。"

WAXWELL.DESCRIBE.LAZYPURRITO = "至少他们有一个用处!"

WAXWELL.DESCRIBE.HORCHATA = "这必须要有品味。"

WAXWELL.DESCRIBE.WOBSTERCOCKTAIL = "最后，这是一位绅士的饮品！"

WAXWELL.DESCRIBE.LAVAEEGGBOILED = "这个蛋最好不错，但那个幼虫就没什么意义了。"

WAXWELL.DESCRIBE.POMEGRANATETEA = "清爽。"

WAXWELL.DESCRIBE.TIRAMISU = "那个碗真的有必要吗？"

WAXWELL.DESCRIBE.TOADSTOOLCOLA = "与海水相比，这真是一大改进。"

WAXWELL.DESCRIBE.TEPACHE = "甜美清爽。"

WAXWELL.DESCRIBE.LUNARTEQUILA = "不！我必须抵抗它...！"

WAXWELL.DESCRIBE.MIMICMOSA = "这种力量，我能感受到！"

WAXWELL.DESCRIBE.POMEGRANATEPIE = "我更喜欢草莓派。"

WAXWELL.DESCRIBE.PINEAPPLECAKE = "情况没那么糟糕。"

WAXWELL.DESCRIBE.PASTY_MEAT = "农家小吃。"
WAXWELL.DESCRIBE.PASTY_CHEESE = "农家小吃。"

WAXWELL.DESCRIBE.BRIGADEIRO = "还不错。"

WAXWELL.DESCRIBE.REGULARLASAGNA = "或许我应该试一试。"

WAXWELL.DESCRIBE.FLTSANDWICH = "那些青蛙活该。"

WAXWELL.DESCRIBE.RICEANDBEANS = "下次我需要更好的东西。"

WAXWELL.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "耐心……一切都会随时间浮现。也许是2026年？"

WAXWELL.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "A delicacy fit for refined tastes, even here.",
	PICKED = "Gone for now.",
	BURNING = "A needless loss.",
}

WAXWELL.DESCRIBE.KYNO_TRUFFLES = "生活中的精致之物，即便在这里也有。"
WAXWELL.DESCRIBE.KYNO_TRUFFLES_COOKED = "啊，精致的准备方式。"

WAXWELL.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "Acceptable craftsmanship.",
	FULL = "A touch of sophistication for my culinary art.",
}

WAXWELL.DESCRIBE.KYNO_SPORECAP = "这世界的腐败体现在这蘑菇上。"
WAXWELL.DESCRIBE.KYNO_SPORECAP_COOKED = "即便烧了，腐败依旧。"

WAXWELL.DESCRIBE.KYNO_SPORECAP_DARK = "一个充满邪恶的标本。"
WAXWELL.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "火焰无法净化真正的腐败。"

WAXWELL.DESCRIBE.KYNO_GOLDENAPPLE = "我在想，是该吃掉它还是把它当作遗物保存。"

WAXWELL.DESCRIBE.TRUFFLESGRINDER = "啊，奢华的味道。终于有点格调了。"

WAXWELL.DESCRIBE.SPORECAPPIE = "精致的毒药。我欣赏这种艺术。"

WAXWELL.DESCRIBE.SPORECAP_SKEWERS = "质朴……但可以接受。"

WAXWELL.DESCRIBE.TRUFFLEOIL = "一丝奢华，即使在荒野中也能享受。"

WAXWELL.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "我想我应该建造这个。"
WAXWELL.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "一项相当...黏糊糊的企图，却有着卑微的开端。"

WAXWELL.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "How tedious... yet practical.",
	FUEL_HIGH = "An abundance of feed.",
	FUEL_MED = "Sufficient, for now.",
	FUEL_LOW = "Neglect is showing.",
	EMPTY = "Completely depleted.",
}

WAXWELL.DESCRIBE.KYNO_ANTCHOVY = "究竟是何等怪诞的实验造就了这东西？"
WAXWELL.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "自然界的小恶魔们又聚集起来了。"

WAXWELL.DESCRIBE.AGEDROE = "一顿与我的身份相称的盛宴。"
WAXWELL.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "啊，精致的滋味……终于。"

WAXWELL.DESCRIBE.KYNO_SWORDFISH_BLUE = "曾是深海生物，如今沦为水洼居民。何其可悲。"

WAXWELL.DESCRIBE.KYNO_JELLYFISH = "多么奇怪的小生物啊。"
WAXWELL.DESCRIBE.KYNO_JELLYFISH_DEAD = "我更喜欢它死了的样子。"
WAXWELL.DESCRIBE.KYNO_JELLYFISH_COOKED = "勉强可以吧。"
WAXWELL.DESCRIBE.KYNO_JELLYFISH_DRIED = "我其实并不介意这个？"

WAXWELL.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "嗯。它对生物发光情有独钟。"
WAXWELL.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "那家伙是爬不起来了。"
WAXWELL.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "搞定，就像晚餐一样。"

WAXWELL.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "只要时间足够，我就能在里面造一艘船。"

WAXWELL.DESCRIBE.KYNO_OCEANTRAP = "好奇心终将战胜你。"

WAXWELL.DESCRIBE.OCEANFISH_PUFFERFISH = "一个充满毒液的气球。多么可怕。"
WAXWELL.DESCRIBE.OCEANFISH_STURGEON = "它看起来就像是从化石记录中直接游出来的。"

WAXWELL.DESCRIBE.KYNO_SWORDFISH = "啊，一个切磋的对手！"
WAXWELL.DESCRIBE.KYNO_SWORDFISH_DEAD = "或许它本该多上几堂击剑课。"

WAXWELL.DESCRIBE.SWORDFISHFEAST = "优雅而致命，恰似我本人。"

WAXWELL.DESCRIBE.KYNO_DOGFISH = "闻起来像湿狗。"
WAXWELL.DESCRIBE.KYNO_DOGFISH_DEAD = "留下来。"

WAXWELL.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "我认为我应该处理掉这个。"

WAXWELL.DESCRIBE.WOBSTER_MONKEYISLAND = "黄金与利爪……两样令我心驰神往之物。"
WAXWELL.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "至少它死得富丽堂皇。"
WAXWELL.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "至少这座岛上有些东西懂得精致。"

WAXWELL.DESCRIBE.KYNO_PUFFERMONSTER = "一种自然防御机制的怪诞展现。"

WAXWELL.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "你暴露自己了，伙计。"
WAXWELL.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "向我臣服。"
WAXWELL.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "我们又见面了。"
WAXWELL.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "大小真的无关紧要！"

WAXWELL.DESCRIBE.KYNO_BLUBBER = "我相信我能……吃掉它……"

WAXWELL.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "危急关头的小点心。"
WAXWELL.DESCRIBE.KYNO_FISHMEAT_DRIED = "至少它经过精炼，可以食用。"

WAXWELL.DESCRIBE.MONKEYISLANDMEAL = "精致的餐点……终于，这世上也有点精致了。"

WAXWELL.DESCRIBE.KYNO_BRAINROCK_LARVAE = "你不可爱。"
WAXWELL.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "这可不是秃头！这是风度翩翩！"
WAXWELL.DESCRIBE.KYNO_BRAINROCK_CORAL = "现在我能为己所用，驾驭它的思维力量。"

WAXWELL.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "I wonder what's thinking?",
	PICKED = "Its thoughts have gone quiet.",
}

WAXWELL.DESCRIBE.BRAINMETTERSOUP = "算不上国王的盛宴，但勉强凑合吧。"

WAXWELL.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "I could use his generosity to my advantage.",
	SLEEPING = "Not interested in business right now.",
}

WAXWELL.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "看起来……烂透了。"

WAXWELL.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "I think I should hold onto it.",
	WAITING = "His spirit is free now.",
}

WAXWELL.DESCRIBE.KYNO_PACKIMBAGGIMS = "他惹人厌的外表，因其实用价值和甘愿效劳的姿态而稍显温和。"

WAXWELL.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "这将是我做过的最大的蛋糕。"
WAXWELL.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "我需要为它准备更多的原料。"
WAXWELL.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "啊。时间永不停歇地向前奔涌，这令人不禁感慨。"
WAXWELL.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "有点俗气，但尚可接受。"
WAXWELL.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "我更喜欢我的燃料充满噩梦般的色彩。"
WAXWELL.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "我想偶尔也该犒劳一下自己……"
WAXWELL.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "多么幼稚啊……*叹气*"

WAXWELL.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "Popcorn, delightful and convenient.",
	FUEL_HIGH = "It performs adequately.",
	FUEL_MED = "Still operational.",
	FUEL_LOW = "Efficiency is declining.",
	EMPTY = "Completely inert.",
}

WAXWELL.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "如此简单的食物竟带来如此惊喜的美味享受。"
WAXWELL.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "我真得穿这个吗？唉……"
WAXWELL.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "啊，这小家伙还以为自己很特别呢？"

WAXWELL.DESCRIBE.KYNO_FISHREGISTRYHAT = "知识就是力量，即使是关于鱼的。"

WAXWELL.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "A necessary chore made tangible.",
	FUEL_HIGH = "An excess of feed.",
	FUEL_MED = "Adequate, for now.",
	FUEL_LOW = "Neglect is showing.",
	EMPTY = "Completely drained.",
	BURNT = "Ruined beyond recovery.",
}