local WX78 = STRINGS.CHARACTERS.WX78

WX78.ANNOUNCE_KYNO_COFFEEBUFF_START = "移动速度：高等级"
WX78.ANNOUNCE_KYNO_COFFEEBUFF_END = "移动速度：正常化"

WX78.ANNOUNCE_KYNO_HASTEBUFF_START = "手部移动速度：最高效率"
WX78.ANNOUNCE_KYNO_HASTEBUFF_END = "手部移动速度恢复到正常水平"

WX78.ANNOUNCE_KYNO_POPBUFF_START = "（嗝）……里面有什么？"
WX78.ANNOUNCE_KYNO_POPBUFF_END = "泡泡效应已被清除"

WX78.ANNOUNCE_KYNO_FROGBUFF_START = "青蛙机制：已连接"
WX78.ANNOUNCE_KYNO_FROGBUFF_END = "青蛙机制：分离"

WX78.ANNOUNCE_KYNO_PIRATEBUFF_START = "(嗝) 准备出发！"
WX78.ANNOUNCE_KYNO_PIRATEBUFF_END = "消除了受驱动效应"

WX78.ANNOUNCE_KYNO_FREEZEBUFF_START = "警告：核心系统正在冷却"
WX78.ANNOUNCE_KYNO_FREEZEBUFF_END = "核心系统恢复正常运行"

WX78.ANNOUNCE_KYNO_FIREBUFF_START = "警告：核心系统正在升温"
WX78.ANNOUNCE_KYNO_FIREBUFF_END = "核心系统恢复正常运行"

WX78.ANNOUNCE_KYNO_FISHINGBUFF_START = "钓鱼插件已启用"
WX78.ANNOUNCE_KYNO_FISHINGBUFF_END = "警告：钓鱼插件已关闭"

WX78.ANNOUNCE_KYNO_SANITYRATEBUFF_START = "减少主机活动"
WX78.ANNOUNCE_KYNO_SANITYRATEBUFF_END = "主机恢复正常"

WX78.ANNOUNCE_KYNO_EATERBUFF_START = "消化系统抛光"
WX78.ANNOUNCE_KYNO_EATERBUFF_END = "消化系统恢复正常"

WX78.ANNOUNCE_KYNO_WORMBUFF_START = "系统已准备好应对蠕虫"
WX78.ANNOUNCE_KYNO_WORMBUFF_END = "系统过期：关闭蠕虫攻击模块"

WX78.ANNOUNCE_KYNO_CRABBUFF_START = "系统已准备好对付螃蟹"
WX78.ANNOUNCE_KYNO_CRABBUFF_END = "系统过期：关闭螃蟹攻击模块"

WX78.ANNOUNCE_KYNO_AMPHIBIANBUFF_START = "(嗝) 发生什么..?"
WX78.ANNOUNCE_KYNO_AMPHIBIANBUFF_END = "气泡效应被消除了"

WX78.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_START = "啊！月亮！是的！！"
WX78.ANNOUNCE_KYNO_ENLIGHTENMENTBUFF_END = "不！我的力量！还给我！"

WX78.ANNOUNCE_KYNO_STEALTHBUFF_START = "系统隐形模块：打开"
WX78.ANNOUNCE_KYNO_STEALTHBUFF_END = "系统隐形模块：关闭"

WX78.ANNOUNCE_KYNO_FEARBUFF_START = "情绪反应：恐惧模块禁用。令人满意。"
WX78.ANNOUNCE_KYNO_FEARBUFF_END = "恐惧模块重新填充！检测到轻微底盘抖动"

WX78.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_START = "【系统过载】"
WX78.ANNOUNCE_KYNO_GOLDENAPPLEBUFF_END = "能量水平恢复到平庸。"

WX78.ANNOUNCE_KYNO_TRUFFLESBUFF_START = "与猪的亲和力提升。"
WX78.ANNOUNCE_KYNO_TRUFFLESBUFF_END = "猪的亲和力终止。"

WX78.ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_START = "腐蚀性物质已被中和。"
-- No ANNOUNCE_KYNO_ACIDIMMUNITYBUFF_END, because we are using default strings for that.

WX78.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_START = "生物毒素已禁用。"
WX78.ANNOUNCE_KYNO_POISONIMMUNITYBUFF_END = "免疫结束。恶心的有机威胁重新激活。"

WX78.ANNOUNCE_KYNO_CRAFTINGBUFF_START = "系统升级：施工效率提升。"
WX78.ANNOUNCE_KYNO_CRAFTINGBUFF_END = "升级已过期。恢复默认笨拙模式。"

WX78.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_START = "敌对生物无人机已暂时被安抚。可接受。"
WX78.ANNOUNCE_KYNO_BEEFRIENDLYBUFF_END = "生物无人机恢复攻击模式。警告。"

WX78.ANNOUNCE_KYNO_MAXHEALTHBUFF_START = "系统升级：结构完整性提升"
WX78.ANNOUNCE_KYNO_MAXHEALTHBUFF_END = "升级已过期。失望值上升中"

WX78.ANNOUNCE_KYNO_MAXHUNGERBUFF_START = "燃料储存容量增加"
WX78.ANNOUNCE_KYNO_MAXHUNGERBUFF_END = "燃料储存设施降级"

WX78.ANNOUNCE_KYNO_MAXSANITYBUFF_START = "系统诊断：脑力升级"
WX78.ANNOUNCE_KYNO_MAXSANITYBUFF_END = "精神升级已过期"

WX78.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_START = "防御参数增强功能已激活。"
WX78.ANNOUNCE_KYNO_PLANARDEFENSEBUFF_END = "警告：额外防御措施已终止。"

WX78.ANNOUNCE_KYNO_COOKWAREINSTALLER_FAIL = "部署单位错误"

WX78.ANNOUNCE_KYNO_SERENITYISLAND_SHOP_FAIL = "这肮脏的生物还想要别的东西"

WX78.ANNOUNCE_KYNO_TREE_TOOSMALL_FAIL = "这棵愚蠢的树太小了，根本承受不住我的设备。"

WX78.ANNOUNCE_KYNO_FIREPITINSTALL_FAIL = "错误：未知部署单元"

WX78.ANNOUNCE_KYNO_POTHANGER_FAIL = "需要烹饪设备"

WX78.ANNOUNCE_KYNO_CASSEROLE_FAIL = "错误：缺少关键的砂锅单元"

WX78.ANNOUNCE_KYNO_SAPHEALER_USED = "RESTORATION PROCESS COMPLETE. UNIT STATUS: 100%"

WX78.ANNOUNCE_KYNO_SLAUGHTERTOOLS_USED = "哈哈!有机生命体已清除。收割完成。"

WX78.ANNOUNCE_KYNO_RUMMAGE_WAGON_EMPTY = "未发现有价值内容。纯属浪费时间。"

WX78.ANNOUNCE_KYNO_HUNT_LOST_TRAIL = "目标丢失。航道淹没。"
WX78.ANNOUNCE_KYNO_HUNT_LOST_TRAIL_RAIN = "检测到降水。数据损坏。"
WX78.ANNOUNCE_KYNO_HUNT_BEAST_NEARBY = "发现海洋威胁。必须予以消灭。"

WX78.ANNOUNCE_KYNO_HOFBIRTHDAY_CAKECOMPLETE = "施工完成。启动庆典程序。"

WX78.ANNOUNCE_KYNO_FISH_RESEARCHED = "分析完成。获取鱼类数据。"
WX78.ANNOUNCE_KYNO_ROE_RESEARCHED = "蛋类分析完成。数据已获取。"

WX78.DESCRIBE.KYNO_ROE = "潜在的水生生物"
WX78.DESCRIBE.KYNO_ROE_COOKED = "他们很脆弱，我已经摧毁了他们哈哈哈"

WX78.DESCRIBE.KYNO_SHARK_FIN = "野兽的舵"

WX78.DESCRIBE.KYNO_BEANBUGS = "自然异常"
WX78.DESCRIBE.KYNO_BEANBUGS_COOKED = "包含能量，但成本是多少？"

WX78.DESCRIBE.KYNO_GUMMYBUG = "柔软的能量"
WX78.DESCRIBE.KYNO_GUMMYBUG_COOKED = "哈哈，我会把你转化为能量"

WX78.DESCRIBE.KYNO_WHEAT = "检测到谷物"
WX78.DESCRIBE.KYNO_WHEAT_COOKED = "检测到烤谷物"

WX78.DESCRIBE.KYNO_FLOUR = "食物的初始阶段"

WX78.DESCRIBE.KYNO_SPOTSPICE = "你被压扁了，小树枝"

WX78.DESCRIBE.KYNO_SAP = "美味的植物液体"
WX78.DESCRIBE.KYNO_SAP_SPOILED = "无用的粘性"

WX78.DESCRIBE.KYNO_SYRUP = "含有高粘性和糖度"

WX78.DESCRIBE.KYNO_COFFEEBEANS = "可饮用豆类"
WX78.DESCRIBE.KYNO_COFFEEBEANS_COOKED = "咖啡豆已达到最佳烘焙水平"

WX78.DESCRIBE.DUG_KYNO_COFFEEBUSH = "SPECIMEN READY FOR RELOCATION"

WX78.DESCRIBE.KYNO_COFFEEBUSH = 
{
	GENERIC = "DRINKEABLE BEAN PLANT",
	PICKED = "BEAN OUTPUT HALTED",
	WITHERED = "INSUFFICIENT ASH LEVELS",
}

WX78.DESCRIBE.DUG_KYNO_SPOTBUSH = "STUPID SHRUB REQUIRES REPLANTING"

WX78.DESCRIBE.KYNO_SPOTBUSH = 
{
	GENERIC = "GIVE ME YOUR FOOD, SHRUB",
	PICKED = "RESOURCE OUTPUT HALTED",
	BURNING = "WARNING: COMBUSTION",
}

WX78.DESCRIBE.KYNO_SPOTSPICE_LEAF = "我会粉碎你"

WX78.DESCRIBE.KYNO_MUSSEL = "未检测到可食用肉"
WX78.DESCRIBE.KYNO_MUSSEL_COOKED = "风味分子很强"

WX78.DESCRIBE.KYNO_HUMANMEAT = "人类状况的进一步改善。"
WX78.DESCRIBE.KYNO_HUMANMEAT_COOKED = "终于，肉质变得可口了"
WX78.DESCRIBE.KYNO_HUMANMEAT_DRIED = "又美味又干净"

WX78.DESCRIBE.COFFEE = "这只是热豆汁。"

WX78.DESCRIBE.BISQUE = "电池的液体状态"

WX78.DESCRIBE.JELLYOPOP = "它将保持我的系统运行"

WX78.DESCRIBE.SHARKFINSOUP = "看起来可以吃"

WX78.DESCRIBE.TROPICALBOUILLABAISSE = "这将为高级机械身体提供能量"

WX78.DESCRIBE.MUSSELBOUILLABAISE = "激活舌头传感器"

WX78.DESCRIBE.SWEETPOTATOSOUFFLE = "进攻性"

WX78.DESCRIBE.FEIJOADA = "能量包"

WX78.DESCRIBE.GUMMY_CAKE = "这里没有乐趣"

WX78.DESCRIBE.HARDSHELL_TACOS = "我会粉碎它的硬壳"

WX78.DESCRIBE.ICEDTEA = "我的敌人制作的提神饮料"

WX78.DESCRIBE.NETTLELOSANGE = "药用营养品。"

WX78.DESCRIBE.SNAKEBONESOUP = "我的两个敌人酿制的酒"

WX78.DESCRIBE.STEAMEDHAMSANDWICH = "难忘的午餐"

WX78.DESCRIBE.TEA = "从植物种提取制成的液体"

WX78.DESCRIBE.BUBBLETEA = "我的敌人制作的提神饮料"

WX78.DESCRIBE.FRENCHONIONSOUP = "洋葱酿造"

WX78.DESCRIBE.SLAW = "已识别食物"

WX78.DESCRIBE.LOTUSBOWL = "嗯……好吃。"

WX78.DESCRIBE.POI = "这种平凡的食物应该除掉"

WX78.DESCRIBE.JELLYBEAN_HUNGER = "临时升级组件"
WX78.DESCRIBE.JELLYBEAN_SUPER = "临时升级组件"
WX78.DESCRIBE.JELLYBEAN_SANITY = "临时升级组件"

WX78.DESCRIBE.BOWLOFGEARS = "是的。现在这是一个适合高级存在的食物"

WX78.DESCRIBE.LONGPIGMEAL = "人类肉体的改进"

WX78.DESCRIBE.CUCUMBERSALAD = "沙拉组装：完成"

WX78.DESCRIBE.DUG_KYNO_WILDWHEAT = "READY FOR TRANSPLANT"

WX78.DESCRIBE.KYNO_WILDWHEAT = 
{
	GENERIC = "GRAINS",
	PICKED = "GRAIN OUTPUT HALTED",
	WITHERED = "INSUFFICIENT MOISTURE",
	BURNING = "WARNING: COMBUSTION",
}

WX78.DESCRIBE.KYNO_MEALGRINDER = "我擅长粉碎"

WX78.DESCRIBE.KYNO_MUSHSTUMP =
{
	GENERIC = "EDIBILITY CONFIRMED",
	PICKED = "LIFEFORM GROWTH RATE SUBOPTIMAL FOR MY NEEDS",
	BURNING = "WARNING: ORGANIC COMBUSTION",
}

WX78.DESCRIBE.GORGE_BREAD = "更好的食谱"
WX78.DESCRIBE.GORGE_SWEET_CHIPS = "土豆切片和油炸"
WX78.DESCRIBE.GORGE_VEGETABLE_SOUP = "一堆蔬菜收集起来"
WX78.DESCRIBE.GORGE_JELLY_SANDWICH = "这对我来说很糟糕"
WX78.DESCRIBE.GORGE_FISH_STEW = "准备热量摄入"
WX78.DESCRIBE.GORGE_MEAT_STEW = "获得营养"
WX78.DESCRIBE.GORGE_ONION_CAKE = "恶心的蛋糕"
WX78.DESCRIBE.GORGE_POTATO_PANCAKES = "土豆的可悲用途"
WX78.DESCRIBE.GORGE_POTATO_SOUP = "碗装电池"
WX78.DESCRIBE.GORGE_FISHBALL_SKEWERS = "棒状食物"
WX78.DESCRIBE.GORGE_MEAT_SKEWERS = "棒状食物"
WX78.DESCRIBE.GORGE_STONE_SOUP = "碗装电池"
WX78.DESCRIBE.GORGE_CROQUETTE = "面粉丸子"
WX78.DESCRIBE.GORGE_ROAST_VEGETABLES = "令人讨厌"
WX78.DESCRIBE.GORGE_MEATLOAF = "肉夹面包屑"
WX78.DESCRIBE.GORGE_CARROT_SOUP = "碗装电池"
WX78.DESCRIBE.GORGE_FISHPIE = "卡在面粉里的弱小生命体。哈哈哈。"
WX78.DESCRIBE.GORGE_FISHCHIPS = "更合适的食物"
WX78.DESCRIBE.GORGE_MEATPIE = "肉馅馅饼"
WX78.DESCRIBE.GORGE_SLIDERS = "垃圾食品"
WX78.DESCRIBE.GORGE_JELLY_ROLL = "对我来说太粘了"
WX78.DESCRIBE.GORGE_CARROT_CAKE = "但是...但是...我以为那只是个谎言"
WX78.DESCRIBE.GORGE_GARLICMASHED = "令人作呕的混合物"
WX78.DESCRIBE.GORGE_GARLICBREAD = "是个好补充"
WX78.DESCRIBE.GORGE_TOMATO_SOUP = "碗装电池"
WX78.DESCRIBE.GORGE_SAUSAGE = "哈。你的末日到了"
WX78.DESCRIBE.GORGE_CANDIEDFISH = "我的系统中有糖浆"
WX78.DESCRIBE.GORGE_STUFFEDMUSHROOM = "填充"
WX78.DESCRIBE.GORGE_BRUSCHETTA = "不特别的"
WX78.DESCRIBE.GORGE_HAMBURGER = "少数美味的人类食物之一"
WX78.DESCRIBE.GORGE_FISHBURGER = "为数不多的人类食物之一"
WX78.DESCRIBE.GORGE_MUSHROOMBURGER = "为数不多的人类食物之一"
WX78.DESCRIBE.GORGE_FISH_STEAK = "准备热量摄入"
WX78.DESCRIBE.GORGE_CURRY = "普通的汤样"
WX78.DESCRIBE.GORGE_SPAGHETTI = "肉包装成最有营养的形状：球体"
WX78.DESCRIBE.GORGE_POACHEDFISH = "鲑鱼哪也去不了"
WX78.DESCRIBE.GORGE_SHEPHERD_PIE = "周围没有羊"
WX78.DESCRIBE.GORGE_CANDY = "又粘又甜"
WX78.DESCRIBE.GORGE_BREAD_PUDDING = "甜面包"
WX78.DESCRIBE.GORGE_BERRY_TART = "哦，天哪，真恶心"
WX78.DESCRIBE.GORGE_MACARONI = "我要榨干这个"
WX78.DESCRIBE.GORGE_BAGEL_AND_FISH = "鲑鱼配面包"
WX78.DESCRIBE.GORGE_GRILLED_CHEESE = "打印(\"你好 世界\")"
WX78.DESCRIBE.GORGE_CREAMMUSHROOM = "不，又是这个"
WX78.DESCRIBE.GORGE_MANICOTTI = "无聊"
WX78.DESCRIBE.GORGE_CHEESEBURGER = "为数不多的人类食物之一"
WX78.DESCRIBE.GORGE_FETTUCCINE = "别再看着我的眼睛"
WX78.DESCRIBE.GORGE_ONION_SOUP = "好臭"
WX78.DESCRIBE.GORGE_BREADED_CUTLET = "肉饼配面包"
WX78.DESCRIBE.GORGE_CREAMY_FISH = "又是鲑鱼？多么原汁原味"
WX78.DESCRIBE.GORGE_PIZZA = "哈哈。愚蠢人类的经典诱饵"
WX78.DESCRIBE.GORGE_POT_ROAST = "不可能"
WX78.DESCRIBE.GORGE_CRAB_CAKE = "这肯定不是艺术"
WX78.DESCRIBE.GORGE_STEAK_FRITES = "经典"
WX78.DESCRIBE.GORGE_SHOOTER_SANDWICH = "向着星空进发"
WX78.DESCRIBE.GORGE_BACON_WRAPPED = "肉包裹肉"
WX78.DESCRIBE.GORGE_CRAB_ROLL = "额外的"
WX78.DESCRIBE.GORGE_MEAT_WELLINGTON = "我对此表示怀疑"
WX78.DESCRIBE.GORGE_CRAB_RAVIOLI = "额外的"
WX78.DESCRIBE.GORGE_CARAMEL_CUBE = "一个精致的焦糖立方体"
WX78.DESCRIBE.GORGE_SCONE = "糖太多"
WX78.DESCRIBE.GORGE_TRIFLE = "糖太多"
WX78.DESCRIBE.GORGE_CHEESECAKE = "奶酪在哪里？"

WX78.DESCRIBE.DUCKYOUGLERMZ = "该工厂的硬件需要维修"

WX78.DESCRIBE.KYNO_ALOE = "获得绿色能源"
WX78.DESCRIBE.KYNO_ALOE_COOKED = "绿色能量油炸玉米饼"
WX78.DESCRIBE.KYNO_ALOE_GROUND = "获得绿色能量"
WX78.DESCRIBE.KYNO_ALOE_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.KNOWN_KYNO_ALOE_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.FARM_PLANT_KYNO_ALOE = "绿色能源"
WX78.DESCRIBE.KYNO_ALOE_OVERSIZED = "绿色能源"
WX78.DESCRIBE.KYNO_ALOE_OVERSIZED_ROTTEN = "哈哈哈"

WX78.DESCRIBE.KYNO_CUCUMBER = "我从可怕的水中偷来的"
WX78.DESCRIBE.KYNO_CUCUMBER_COOKED = "能量流失"
WX78.DESCRIBE.KYNO_CUCUMBER_GROUND = "我从可怕的水中偷来的"
WX78.DESCRIBE.KYNO_CUCUMBER_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.KNOWN_KYNO_CUCUMBER_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.FARM_PLANT_KYNO_CUCUMBER = "我从可怕的水中偷来的"
WX78.DESCRIBE.KYNO_CUCUMBER_OVERSIZED = "我从可怕的水中偷来的"
WX78.DESCRIBE.KYNO_CUCUMBER_OVERSIZED_ROTTEN = "我从可怕的水中偷来的"

WX78.DESCRIBE.KYNO_RADISH = "红色能量球"
WX78.DESCRIBE.KYNO_RADISH_COOKED = "能量获取"
WX78.DESCRIBE.KYNO_RADISH_GROUND = "红色球形能量球"
WX78.DESCRIBE.KYNO_RADISH_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.KNOWN_KYNO_RADISH_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.FARM_PLANT_KYNO_RADISH = "红色球形能量球"
WX78.DESCRIBE.KYNO_RADISH_OVERSIZED = "红色球形能量球"
WX78.DESCRIBE.KYNO_RADISH_OVERSIZED_ROTTEN = "哈哈哈"

WX78.DESCRIBE.KYNO_FENNEL = "对我来说就像一株普通的植物。"
WX78.DESCRIBE.KYNO_FENNEL_COOKED = "GROSS"
WX78.DESCRIBE.KYNO_FENNEL_GROUND = "对我来说就像一株普通植物。"
WX78.DESCRIBE.KYNO_FENNEL_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.KNOWN_KYNO_FENNEL_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.FARM_PLANT_KYNO_FENNEL = "在我看来，这只是一株普通的植物。"
WX78.DESCRIBE.KYNO_FENNEL_OVERSIZED = "在我看来，这只是一株普通的植物。"
WX78.DESCRIBE.KYNO_FENNEL_OVERSIZED_ROTTEN = "哈哈哈"

WX78.DESCRIBE.KYNO_SWEETPOTATO = "毛的"
WX78.DESCRIBE.KYNO_SWEETPOTATO_COOKED = "争夺统治地位和 WX-78 失利"
WX78.DESCRIBE.KYNO_SWEETPOTATO_GROUND = "毛的"
WX78.DESCRIBE.KYNO_SWEETPOTATO_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.KNOWN_KYNO_SWEETPOTATO_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.FARM_PLANT_KYNO_SWEETPOTATO = "毛的"
WX78.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED = "毛的"
WX78.DESCRIBE.KYNO_SWEETPOTATO_OVERSIZED_ROTTEN = "哈哈哈"

WX78.DESCRIBE.KYNO_PARZNIP = "营养丰富"
WX78.DESCRIBE.KYNO_PARZNIP_COOKED = "营养丰富"
WX78.DESCRIBE.KYNO_PARZNIP_EATEN = "营养丰富"
WX78.DESCRIBE.KYNO_PARZNIP_GROUND = "营养丰富"
WX78.DESCRIBE.KYNO_PARZNIP_BIG = "尺寸分析完成：巨人"
WX78.DESCRIBE.KYNO_PARZNIP_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.KNOWN_KYNO_PARZNIP_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.FARM_PLANT_KYNO_PARZNIP = "营养丰富"
WX78.DESCRIBE.KYNO_PARZNIP_OVERSIZED = "营养丰富"
WX78.DESCRIBE.KYNO_PARZNIP_OVERSIZED_ROTTEN = "哈哈哈"

WX78.DESCRIBE.KYNO_TURNIP = "这是一个愚蠢的萝卜"
WX78.DESCRIBE.KYNO_TURNIP_COOKED = "它被彻底烤熟了"
WX78.DESCRIBE.KYNO_TURNIP_GROUND = "这是一个愚蠢的萝卜"
WX78.DESCRIBE.KYNO_TURNIP_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.KNOWN_KYNO_TURNIP_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.FARM_PLANT_KYNO_TURNIP = "这是一个愚蠢的萝卜"
WX78.DESCRIBE.KYNO_TURNIP_OVERSIZED = "这是一个愚蠢的萝卜"
WX78.DESCRIBE.KYNO_TURNIP_OVERSIZED_ROTTEN = "哈哈哈"

WX78.DESCRIBE.KYNO_RICE = "讨厌的蔬菜"
WX78.DESCRIBE.KYNO_RICE_COOKED = "讨厌的蔬菜"
WX78.DESCRIBE.KYNO_RICE_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.KNOWN_KYNO_RICE_SEEDS = "这是来自泥土的食物的源代码"
WX78.DESCRIBE.FARM_PLANT_KYNO_RICE = "这是个哑巴稻秆"
WX78.DESCRIBE.KYNO_RICE_OVERSIZED = "这是个哑巴稻秆"
WX78.DESCRIBE.KYNO_RICE_OVERSIZED_ROTTEN = "哈哈哈"

WX78.DESCRIBE.KYNO_SEEDS_KIT = "脏东西"

WX78.DESCRIBE.KYNO_LIMPETROCK = 
{
	GENERIC = "STUPID MEAT WILL NEVER DEVOUR STONE",
	PICKED = "ORGANICS TEMPORARILY UNAVAILABLE",
	WITHERED = "ENVIRONMENT UNSUITABLE FOR ORGANICS",
}

WX78.DESCRIBE.KYNO_LIMPETS = "小蛋白质来源"
WX78.DESCRIBE.KYNO_LIMPETS_COOKED = "欢迎改进"

WX78.DESCRIBE.KYNO_LOTUS_OCEAN = 
{
	GENERIC = "ORGANIC UNIT THAT REQUIRES WATER",
	PICKED = "FLOWER PRODUCTION HALTED",
	BURNING = "CRITICAL ERROR: COMBUSTION",
}

WX78.DESCRIBE.KYNO_LOTUS_ROOT = "不适用于水域之外"
WX78.DESCRIBE.KYNO_LOTUS_FLOWER = "丑陋的水花"
WX78.DESCRIBE.KYNO_LOTUS_FLOWER_COOKED = "我已经从它的水分需求中解放了它"

WX78.DESCRIBE.KYNO_SEAWEEDS_OCEAN = 
{
	GENERIC = "THE SEA HAS WEEDS TOO?",
	PICKED = "REGROWTH PENDING",
	BURNING = "ERROR: FIRE IN MARINE ENVIRONMENT",
}

WX78.DESCRIBE.KYNO_SEAWEEDS = "它又黏又恶心"
WX78.DESCRIBE.KYNO_SEAWEEDS_COOKED = "健康零食"
WX78.DESCRIBE.KYNO_SEAWEEDS_DRIED = "健康食品"
WX78.DESCRIBE.KYNO_SEAWEEDS_ROOT = "不适用于外部水域"

WX78.DESCRIBE.KYNO_TAROROOT_OCEAN = 
{
	GENERIC = "DISGUSTING WATERY PLANT",
	PICKED = "REGROWTH ACCELERATED BY WATER",
	BURNING = "WARNING: ORGANIC COMBUSTION",
}

WX78.DESCRIBE.KYNO_TAROROOT_ROOT = "不适用于水域之外"
WX78.DESCRIBE.KYNO_TAROROOT = "太紫了"
WX78.DESCRIBE.KYNO_TAROROOT_COOKED = "花式"

WX78.DESCRIBE.KYNO_WATERYCRESS_OCEAN = 
{
	GENERIC = "DISGUSTING PLANT",
	PICKED = "REGROWTH CYCLE INITIATED",
	BURNING = "SYSTEM ANOMALY: FIRE DETECTED",
}

WX78.DESCRIBE.KYNO_WATERYCRESS_ROOT = "不适用于水域之外"
WX78.DESCRIBE.KYNO_WATERYCRESS = "恶心的植物"

WX78.DESCRIBE.WATERYCRESSBOWL = "它是用我敌人的血制成的"

WX78.DESCRIBE.KYNO_SALT = "不利于电路"

WX78.DESCRIBE.KYNO_MUSSELSTICK =
{
	GENERIC = "AQUATIC ORGANICS ATTACHED",
	PICKED = "ORGANICS UNAVAILABLE",
	BURNING = "WARNING: RESOURCE COMBUSTION",
}

WX78.DESCRIBE.KYNO_MUSSELSTICK_ITEM = "蛋白质吸引和生长系统"

WX78.DESCRIBE.CATFOOD = "它是猫科动物的主要能量来源。"

WX78.DESCRIBE.KATFOOD = "它是猫科动物的主要能量来源。"

WX78.DESCRIBE.KYNO_BANANATREE = 
{
	GENERIC = "I SHOULD HAVE LEFT IT IN THE UNDERGROUND",
	PICKED = "FRUIT PRODUCTION TEMPORARILY HALTED",
	CHOPPED = "PLANT TERMINATED",
	BURNING = "WARNING: COMBUSTION DETECTED",
	BURNT = "PLANT REDUCED TO ASHES",
}

WX78.DESCRIBE.KYNO_BANANA = "更多碳"
WX78.DESCRIBE.KYNO_BANANA_COOKED = "这些食物太乏味了"

WX78.DESCRIBE.KYNO_KOKONUTTREE = 
{
	GENERIC = "THIS TREE IS ALL TRUNK",
	PICKED = "FRUIT PRODUCTION PAUSED",
	CHOPPED = "PLANT TERMINATED",
	BURNING = "WARNING: COMBUSTION",
	BURNT = "PLANT REDUCED TO ASHES",
}

WX78.DESCRIBE.KYNO_KOKONUT = "愚蠢的树果"
WX78.DESCRIBE.KYNO_KOKONUT_HALVED = "营养现在可以获取"
WX78.DESCRIBE.KYNO_KOKONUT_COOKED = "烤面包的香气对我没有任何作用"

WX78.DESCRIBE.BOWLOFPOPCORN = "空卡路里"

WX78.DESCRIBE.FIGJUICE = "用愚蠢的水果制成的提神饮料"

WX78.DESCRIBE.COCONUTWATER = "这水含有不同的代码"

WX78.DESCRIBE.EYEBALLSPAGHETTI = "我觉得它在看着我"

WX78.DESCRIBE.FORGETMELOTS_SEEDS = "这是来自泥土的食物的源代码"

WX78.DESCRIBE.FIRENETTLES_SEEDS = "这是来自泥土的食物的源代码"

WX78.DESCRIBE.TILLWEED_SEEDS = "这是来自泥土的食物的源代码"

WX78.DESCRIBE.KYNO_FLOATILIZER = "一桶海洋垃圾"

WX78.DESCRIBE.KYNO_TWIGGYNUTS = "DEEZ NUTS"

WX78.DESCRIBE.KYNO_REPAIRTOOL = "已组装好的维修装置"

WX78.DESCRIBE.KYNO_KOI = "我可以欣赏它的金色光泽"
WX78.DESCRIBE.KYNO_KOI_COOKED = "我可以欣赏它的金色光泽"

WX78.DESCRIBE.KYNO_TROPICALFISH = "你是热带鱼和鱼"
WX78.DESCRIBE.KYNO_TROPICALFISH_COOKED = "哈哈，你走好"

WX78.DESCRIBE.KYNO_NEONFISH = "这条鱼比其他鱼干"
WX78.DESCRIBE.KYNO_NEONFISH_COOKED = "我将获得它的干燥能力"

WX78.DESCRIBE.KYNO_GROUPER = "我把它从水里救了出来。"
WX78.DESCRIBE.KYNO_GROUPER_COOKED = "现在是机器人燃料。哈哈"
 
WX78.DESCRIBE.KYNO_PIERROTFISH = "它生活在水中。可怕"
WX78.DESCRIBE.KYNO_PIERROTFISH_COOKED = "我会吃掉这个可怕的水生"

WX78.DESCRIBE.KYNO_SALMONFISH = "软盘水生物"
WX78.DESCRIBE.KYNO_SALMONFISH_COOKED = "它的弱点是着火"

WX78.DESCRIBE.TURF_PINKPARK = "粉红色让我脸红"
WX78.DESCRIBE.TURF_STONECITY = "地面部分"
WX78.DESCRIBE.TURF_FIELDS = "地面部分"
WX78.DESCRIBE.TURF_TIDALMARSH = "地面部分。"

WX78.DESCRIBE.KYNO_SALTRACK =
{
	GENERIC = "CAUTION: AVOID SPLASHING LIQUID ON CIRCUITS",
	PICKED = "WATER CONTACT SUCCESSFULLY AVOIDED",
}

WX78.DESCRIBE.KYNO_SALTRACK_INSTALLER = "需要一些组装"

WX78.DESCRIBE.KYNO_SAPBUCKET_INSTALLER = "用于从树上吸取冷却液"

WX78.DESCRIBE.KYNO_CRABTRAP_INSTALLER = "捕获生物岩石"

WX78.DESCRIBE.KYNO_SERENITYISLAND_SHOP = 
{
	GENERIC = "THIS LARGE SWINE COMMANDS THE SMALLER ONES",
	SLEEPING = "DEEP SLEEP MODE ACTIVATED",
}

WX78.DESCRIBE.KYNO_SUGARTREE =
{
	GENERIC = "A HIDEOUS PINK TREE",
	CHOPPED = "THE SOURCE OF PLANT COOLANT HAS BEEN DESTROYED",
	SAPPED = "IT IS TIME TO COLLECT THE COOLANT",
	PICKED = "I DEMAND YOU FILL UP FASTER",
	BURNING = "WARNING: COMBUSTION",
	BURNT = "FILTHY ORGANISM DESTROYED",
}

WX78.DESCRIBE.KYNO_SUGARTREE_RUINED =
{
	GENERIC = "TRUNK HAS SUSTAINED DAMAGE",
	CHOPPED = "DEFECTIVE UNIT REMOVED",
	SAPPED = "RUINED SAP READY",
	PICKED = "TINY BIOLOGICAL UNITS HAVE FOILED COOLANT COLLECTION",
	BURNING = "PURGING CONTAMINANT",
	BURNT = "UNIT TERMINATED",
}

WX78.DESCRIBE.KYNO_SUGARTREE_BUD = "糖容器单元"

WX78.DESCRIBE.KYNO_SUGARTREE_FLOWER = "我对美丽的欣赏是有限的"
WX78.DESCRIBE.KYNO_SUGARTREE_FLOWER_PLANTED = "我对美丽的欣赏是有限的"

WX78.DESCRIBE.KYNO_SUGARTREE_PETALS = "我对美丽的欣赏是有限的"

WX78.DESCRIBE.KYNO_PEBBLECRAB = "它就像一块石头。但还活着而且更糟"

WX78.DESCRIBE.KYNO_CRABMEAT = "岩石生物的肉"
WX78.DESCRIBE.KYNO_CRABMEAT_COOKED = "美味的岩肉"
WX78.DESCRIBE.KYNO_CRABMEAT_DRIED = "石中肉"

WX78.DESCRIBE.KYNO_CRABKINGMEAT = "石中肉"
WX78.DESCRIBE.KYNO_CRABKINGMEAT_COOKED = "礁石生物的肉"
WX78.DESCRIBE.KYNO_CRABKINGMEAT_DRIED = "礁石生物的肉"

WX78.DESCRIBE.KYNO_SLAUGHTERTOOL = "用于分解生物生命体"

WX78.DESCRIBE.KYNO_CHICKEN2 = 
{
	GENERIC = "ERROR: DOES NOT COMPUTE",
	COOP = "ORGANIC UNIT SUCCESSFULLY CONTAINED",
}

WX78.DESCRIBE.KYNO_CHICKEN_EGG = "我恨你，蛋！"
WX78.DESCRIBE.KYNO_CHICKEN_EGG_LARGE = "UPGRADED PROTECTIVE SHELL UNIT"
WX78.DESCRIBE.KYNO_CHICKEN_EGG_COOKED = "这应该是一种改进"

WX78.DESCRIBE.KYNO_CHICKENHOUSE = 
{
	GENERIC = "POULTRY CONTAINMENT STRUCTURE",
	FULL = "MAXIMUM EGG PRODUCTION ACHIEVED",
	BURNT = "UNIT FAILURE: ORGANIC MATTER DESTROYED",
}

WX78.DESCRIBE.KYNO_SERENITYISLAND_DECOR2 = "可悲。他们甚至不知道如何建造一个合适的罐子"

WX78.DESCRIBE.KYNO_COOKWARE_KIT = "预制厨房模板"
WX78.DESCRIBE.KYNO_COOKWARE_SYRUP = "需要蔗糖和火来制造更多蔗糖"
WX78.DESCRIBE.KYNO_COOKWARE_SYRUP_POT = "需要蔗糖和火来制造更多的蔗糖"
WX78.DESCRIBE.KYNO_COOKWARE_BIG_POT = "这个锅有一个可接受的内存大小"
WX78.DESCRIBE.KYNO_COOKWARE_BIG = "这个锅有一个可接受的内存大小"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_POT = "这个锅的内存容量不足"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL = "这个锅的内存容量不足"
WX78.DESCRIBE.KYNO_COOKWARE_GRILL = "在食物中加火会增加其价值"
WX78.DESCRIBE.KYNO_COOKWARE_GRILL_ITEM = "需要一些组装"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL = "内存不足"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_GRILL_ITEM = "需要一些组装"
WX78.DESCRIBE.KYNO_COOKWARE_ELDER = "需要蔗糖和火来制造更多的蔗糖"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_ITEM = "这个机器人还没有建成"
WX78.DESCRIBE.KYNO_COOKWARE_CASSEROLE = "用于组装杂烩"
WX78.DESCRIBE.KYNO_COOKWARE_SMALL_CASSEROLE = "内存插槽需要升级"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN = "我欣赏这个机器人的大火嘴"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_CASSEROLE = "我欣赏这个机器人的大火嘴"
WX78.DESCRIBE.KYNO_COOKWARE_OVEN_SMALL_CASSEROLE = "我欣赏这个机器人的大火嘴"

WX78.DESCRIBE.KYNO_ROCKFLIPPABLE = 
{
	GENERIC = "FLIP ROCK TO PERFORM SEARCH FUNCTION",
	FLIPPED = "HIDDEN MATERIALS REVEALED",
}

WX78.DESCRIBE.KYNO_SERENITYISLAND_CRATE = "检测到废弃的货物"

WX78.DESCRIBE.KYNO_SUGARFLY = "它觉得它很漂亮"
WX78.DESCRIBE.KYNO_SUGARFLYWINGS = "彩虹色"

WX78.DESCRIBE.KYNO_WATERY_CRATE = "检测到废弃的货物"

WX78.DESCRIBE.KYNO_TUNACAN = "密封食品"
WX78.DESCRIBE.KYNO_TUNACAN_OPEN = "密封食品"

WX78.DESCRIBE.KYNO_CANNEDFOOD = "密封食品"
WX78.DESCRIBE.KYNO_CANNEDFOOD_OPEN = "密封未密封的食品"

WX78.DESCRIBE.KYNO_POP = "这是消耗品吗？"

WX78.DESCRIBE.KYNO_MYSTERYMEAT = "这是肉。没有神秘之处"

WX78.DESCRIBE.KYNO_BOTTLE_SOUL = "一个灵魂盒子，我喜欢它的存储模块"

WX78.DESCRIBE.SOULSTEW = "灵魂汤，我喜欢它的设计"

WX78.DESCRIBE.FORTUNECOOKIE = "只是一些毫无意义的愚蠢词"

WX78.DESCRIBE.HORNOCUPIA = "这件作品是用来折磨饥饿的肉体"

WX78.DESCRIBE.CHEESE_YELLOW = "哈哈，我喜欢吃奶酪"
WX78.DESCRIBE.CHEESE_WHITE = "哈哈，我喜欢吃奶酪"
WX78.DESCRIBE.CHEESE_KOALEFANT = "哈哈，我喜欢吃奶酪"

WX78.DESCRIBE.MILK_BOX = "肮脏动物的可食用液体"

WX78.DESCRIBE.WATERCUP = "我……我就是做不到……"

WX78.DESCRIBE.HONEYJAR = "黏糊糊的"

WX78.DESCRIBE.CRAB_ARTICHOKE = "肉煮至完美"

WX78.DESCRIBE.PEPPERROLLS = "我会吃掉它。我必须"

WX78.DESCRIBE.KYNO_SAPHEALER = "消除主要系统功能的传染"

WX78.DESCRIBE.KYNO_OCEAN_WRECK = 
{
	GENERIC = "INSUFFICIENT CAPTAINING",
	PICKED = "ORGANIC GROWTH TEMPORARILY ABSENT",
	BURNING = "STRUCTURAL INTEGRITY COMPROMISED",
}

WX78.DESCRIBE.KYNO_GHOST_PIRATE = "你是个不安分的灵魂吗？"

WX78.DESCRIBE.KYNO_BUCKET_EMPTY = "液体商品存储模块"
WX78.DESCRIBE.KYNO_BUCKET_METAL = "液体储存箱"
WX78.DESCRIBE.KYNO_BUCKET_WATER = "对生物体毫无用处的液体"

WX78.DESCRIBE.KYNO_MILK_BEEFALO = "天然来源的牛奶"
WX78.DESCRIBE.KYNO_MILK_KOALEFANT = "天然来源的牛奶"

WX78.DESCRIBE.KYNO_CAP_DRIED = "我讨厌它的样子。糟糕的自然艺术"

WX78.DESCRIBE.KYNO_PLANTMEAT_DRIED = "脱水蛋白质"

WX78.DESCRIBE.KYNO_BREWBOOK = "饮料目录"

WX78.DESCRIBE.KYNO_WOODENKEG = 
{
	EMPTY = "A LIQUOR HARDWARE",
	BREWING_LONG = "PROCESS AT EARLY STAGE",
	BREWING_SHORT = "PROCESS NEARING COMPLETION",
	DONE = "BREWING COMPLETE",
	BURNT = "CONTAINER DESTROYED",
}

WX78.DESCRIBE.KYNO_PRESERVESJAR = 
{
	EMPTY = "HARDWARE WITH PRESERVING CAPABILITIES",
	BREWING_LONG = "PRESERVATION PROCESS IN PROGRESS",
	BREWING_SHORT = "PROCESS NEARING COMPLETION",
	DONE = "PRESERVATION COMPLETE",
	BURNT = "CONTAINER FAILURE",
}

WX78.DESCRIBE.KYNO_ANTCHEST = 
{
	GENERIC = "HONEY CONVERTER AND STORAGE",
	HONEY = "HONEY STORAGE AT ACCEPTABLE LEVELS",
	NECTAR = "NECTAR PROCESSING IN PROGRESS",
	BURNING = "ERROR: COMBUSTION OF RESOURCES",
}

WX78.DESCRIBE.KYNO_NECTAR_POD = "需要蜂蜜转换器才能使用"

WX78.DESCRIBE.KYNO_OAKTREE_POD = "多用途能源容器"
WX78.DESCRIBE.KYNO_OAKTREE_POD_COOKED = "生物能量包"

WX78.DESCRIBE.KYNO_PIKO = "自动坚果采集机"
WX78.DESCRIBE.KYNO_PIKO_ORANGE = "具有酿造特性的采集机"

WX78.DESCRIBE.KYNO_MEADOWISLAND_TREE = 
{
	GENERIC = "WOODEN IMMOBILE LIFEFORM",
	CHOPPED = "RESOURCE EXTRACTION COMPLETE",
	BURNING = "WARNING: COMBUSTION",
	BURNT = "SPECIMEN DESTROYED",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_PIKOTREE = 
{
	GENERIC = "WOODEN IMMOBILE LIFEFORM INFESTED WITH FILTHY ORGANISMS",
	BURNING = "HABITAT TERMINATION IN PROGRESS",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_CRATE = "海难的证据"

WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMHUT = 
{
	GENERIC = "OUTDATED ABODE",
	BURNT = "STRUCTURE DESTROYED",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_FISHERMERMHUT = 
{
	GENERIC = "AROMA INDENTIFICATION SYSTEM UPDATE: FISH MAX",
	CRAFTED = "STRUCTURAL QUALITY IMPROVED",
	BURNT = "ODOR LEVELS UNACCEPTABLE",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_SHOP = 
{
	GENERIC = "FISH BARTERER FACILITY",
	OCCUPIED = "VENDOR UNAVAILABLE",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMCART = 
{
	GENERIC = "STEALING IS WRONG BUT I GUESS THIS DUDE WOULDN'T MIND IT",
	EMPTY = "INVENTORY DEPLETED",
}

WX78.DESCRIBE.KYNO_MEADOWISLAND_SELLER = "是你。曾经卖给我种子的鱼贩"
WX78.DESCRIBE.KYNO_MEADOWISLAND_POND = "自然发生的水特征"
WX78.DESCRIBE.KYNO_MEADOWISLAND_PLANTY = "这是一种无趣的植物"
WX78.DESCRIBE.KYNO_MEADOWISLAND_SANDHILL = "岩尘堆积如山"
WX78.DESCRIBE.KYNO_MEADOWISLAND_MERMFISHER = "气味识别系统更新：鱼腥味"

WX78.DESCRIBE.KYNO_SAMMYHAT = "交换者帽子"

WX78.DESCRIBE.KINGFISHER = "一只大喙机构的鸟"

WX78.DESCRIBE.TOUCAN = "你的鼻子太长了"
WX78.DESCRIBE.TOUCAN_CHUBBY = "你的鼻子太长了"

WX78.DESCRIBE.WETGOOP2 = "可食用的污物"

WX78.DESCRIBE.BEER = "完美饮品"

WX78.DESCRIBE.PALEALE = "完美饮品"

WX78.DESCRIBE.TEAGREEN = "这种液体有奇怪的特性可以舒缓我的系统"

WX78.DESCRIBE.TEARED = "这种液体有奇怪的特性可以舒缓我的系统"

WX78.DESCRIBE.MEAD = "苦与甜"

WX78.DESCRIBE.KYNO_JELLY = "我的电路有卡纸"

WX78.DESCRIBE.KYNO_MAYONNAISE = "奶油"

WX78.DESCRIBE.TARTARSAUCE = "不！！！！"

WX78.DESCRIBE.KYNO_PICKLES = "恶心"

WX78.DESCRIBE.KYNO_WINE = "苦涩清爽"

WX78.DESCRIBE.KYNO_JUICE = "啊啊啊啊"

WX78.DESCRIBE.KYNO_POISON_FROGLEGS = "警告：腿部装置含有毒素"
WX78.DESCRIBE.KYNO_POISON_FROGLEGS_COOKED = "烧伤毒腿装置"

WX78.DESCRIBE.POISONFROGGLEBUNWICH = "美味的青蛙燃料"

WX78.DESCRIBE.KYNO_BREWINGRECIPECARD = "错误：酿造配方不可读"

WX78.DESCRIBE.KYNO_OIL = "它是油。但不适用于我的硬件"

WX78.DESCRIBE.BERRYSUNDAE = "甜乳制品"

WX78.DESCRIBE.CHOCOLATE_BLACK = "甜乳制品"
WX78.DESCRIBE.CHOCOLATE_WHITE = "甜乳制品"

WX78.DESCRIBE.TRICOLORDANGO = "甜蜜的 B-B-球？"
 
WX78.DESCRIBE.FRIESFRENCH = "油炸马铃薯以达到最佳风味"

WX78.DESCRIBE.PIRATERUM = "里面有神秘且可能危险的液体"

WX78.DESCRIBE.TWISTEDTEQUILA = "系统分析：液体引起奇怪的空间和时间效应"

WX78.DESCRIBE.ONIONRINGS = "它含有适量的油。那么一定是好的"

WX78.DESCRIBE.DONUTS = "面团甜甜圈.哈"
WX78.DESCRIBE.DONUTS_CHOCOLATE_BLACK = "面团甜甜圈。唔呜哈哈"
WX78.DESCRIBE.DONUTS_CHOCOLATE_WHITE = "面团甜甜圈。哇哈哈"
 
WX78.DESCRIBE.CINNAMONROLL = "这是一个糖面包"

WX78.DESCRIBE.GUMMYBEARGERS = "警告：可爱程度危险"

WX78.DESCRIBE.PRETZEL = "漂亮的椒盐卷饼"

WX78.DESCRIBE.CORNINCUP = "杯状玉米"

WX78.DESCRIBE.COTTONCANDY = "空气制成的食物"

WX78.DESCRIBE.ROASTEDHAZELNUTS = "我刚刚烤了一些坚果。哈哈"

WX78.DESCRIBE.MONSTERMUFFIN = "没有松饼。只有邪恶"

WX78.DESCRIBE.PINKCAKE = "它对我来说太粉了，必须吃掉它"

WX78.DESCRIBE.CHIPSBAG = "在空气袋中生产的土豆"

WX78.DESCRIBE.LITTLEBREAD = "更好食谱的原料"

WX78.DESCRIBE.HOTHOUND = "经典垃圾食品"

WX78.DESCRIBE.MILKSHAKE = "我先挤奶，然后摇晃"
WX78.DESCRIBE.MILKSHAKE_PRISMATIC = "我先挤奶，然后摇晃"

WX78.DESCRIBE.NACHOS = "我得到了滴水和玉米片"

WX78.DESCRIBE.BANANA_PUDDING = "香蕉？"

WX78.DESCRIBE.SEA_PUDDING = "鱼！"

WX78.DESCRIBE.TOM_KHA_SOUP = "用令人厌恶的原料制成的令人厌恶的汤"

WX78.DESCRIBE.MINERTREAT = "不...可能是...那个版本！"

WX78.DESCRIBE.RADISHSALAD = "沙拉组装：已完成"

WX78.DESCRIBE.PUMPKIN_SOUP = "碗里的电池电量"

WX78.DESCRIBE.ALGAE_SOUP = "碗里的电池电量"

WX78.DESCRIBE.PARZNIP_SOUP = "碗里的电池电量"

WX78.DESCRIBE.NETTLEMEATED = "带肉附件的鼻子刺激性喷射器"

WX78.DESCRIBE.KYNO_SUGAR = "非常适合吃甜食"

WX78.DESCRIBE.KYNO_BOTTLECAP = "系统分析：潜在的黄金收入"

WX78.DESCRIBE.NUKACOLA = "系统分析：多维度后世界末日燃料"
WX78.DESCRIBE.NUKACOLA_QUANTUM = "系统分析：多维度后世界末日燃料"

WX78.DESCRIBE.LIVINGSANDWICH = "警告：看起来可疑的魔法燃料"

WX78.DESCRIBE.DURIANSPLIT = "甜蜜的乳制品"

WX78.DESCRIBE.DURIANSOUP = "用榴莲酿造的啤酒"

WX78.DESCRIBE.DURIANMEATED = "还好我没有鼻子"

WX78.DESCRIBE.DURIANCHICKEN = "节日蔬菜"

WX78.DESCRIBE.LUNARSOUP = "月亮是我的"

WX78.DESCRIBE.PURPLEWOBSTERSOUP = "那个肮脏的生命体现在是我的燃料"

WX78.DESCRIBE.WOBSTERMONSTER = "利维坦生命体"

WX78.DESCRIBE.SPIDERCAKE = "这是一个令人发指的怪物"

WX78.DESCRIBE.SUGARBOMBS = "我开始出现不是来自我的记忆库的闪回"

WX78.DESCRIBE.BERRYBOMBS = "存储单元内的浆果"

WX78.DESCRIBE.ONIGIRIS = "三角形颗粒"

WX78.DESCRIBE.OMURICE = "分析完毕：番茄酱炒饭"

WX78.DESCRIBE.PAELLA = "谷物和......加工... 低等海洋生物"

WX78.DESCRIBE.RISOTTO = "谷物和肮脏的野生蘑菇"

WX78.DESCRIBE.RICESAKE = "他们喝这个的时候看起来很傻"

WX78.DESCRIBE.DUG_KYNO_PINEAPPLEBUSH = "PLANT REMOVED"

WX78.DESCRIBE.KYNO_PINEAPPLEBUSH = 
{
	GENERIC = "DUMB AND STUPID SPIKY FRUIT BUSH",
	PICKED = "FRUIT OUTPUT HALTED",
	WITHERED = "INSUFFICIENT MOISTURE",
	BURNING = "WARNING: COMBUSTION",
}

WX78.DESCRIBE.KYNO_PINEAPPLE = "蠢果子。"
WX78.DESCRIBE.KYNO_PINEAPPLE_HALVED = "蠢果子"
WX78.DESCRIBE.KYNO_PINEAPPLE_COOKED = "现在勉强可以接受"

WX78.DESCRIBE.PIZZA_TROPICAL = "哦，我的... 他们对你做了什么"

WX78.DESCRIBE.PINACOLADA = "不可能"

WX78.DESCRIBE.CHIMAS = "讨厌的化身"

WX78.DESCRIBE.KYNO_GARDEN_SPRINKLER = 
{
	OFF = "HYDRATION SYSTEM INACTIVE",
	ON = "AN ENEMY BARRAGE!",
}

WX78.DESCRIBE.KYNO_FOODSACK = "锁住新鲜"

WX78.DESCRIBE.GUMMYWORMS = "哈. 你现在感觉如何？"

WX78.DESCRIBE.SMORES = "坚果和棉花糖"

WX78.DESCRIBE.NUKASHINE = "这个饮料试图在我的系统中安装恶意软件！"

WX78.DESCRIBE.ANTSLOG = "畸形"

WX78.DESCRIBE.KYNO_WORM_BONE = "哈哈。生物单位是如此脆弱"

WX78.DESCRIBE.SPOOKY_BRAIN_NOODLES = "吃弱肉强食不会改善我的记忆"
WX78.DESCRIBE.SPOOKY_BURGERZILLA = "畸形汉堡包的失败再现"
WX78.DESCRIBE.SPOOKY_DEADBREAD = "如果他是其中的一部分就好了"
WX78.DESCRIBE.SPOOKY_JELLYBEANS = "视觉模块包"
WX78.DESCRIBE.SPOOKY_POPSICLE = "烧掉它们"
WX78.DESCRIBE.SPOOKY_PUMPKINCREAM = "这是什么可怕的创作"
WX78.DESCRIBE.SPOOKY_SKULLCANDY = "愚蠢的糖果能够带回虚弱的身体"
WX78.DESCRIBE.SPOOKY_TACODILE = "我希望他们的妈妈不要来找我"

WX78.DESCRIBE.BUTTER_BEEFALO = "黏糊的动物奶制方块"
WX78.DESCRIBE.BUTTER_GOAT = "黏糊的动物奶制方块"
WX78.DESCRIBE.BUTTER_KOALEFANT = "黏糊的动物奶制方块"

WX78.DESCRIBE.SPICE_CURE = "保存燃料舱的固件插件"
WX78.DESCRIBE.SPICE_COLD = "核心系统的寒冷插件"
WX78.DESCRIBE.SPICE_FIRE = "核心系统火灾插件警告：可能导致过热"
WX78.DESCRIBE.SPICE_FED = "高热量使系统工作更快"
WX78.DESCRIBE.SPICE_MIND = "镇静应用"

WX78.DESCRIBE.SUGARFLYMUFFIN = "天真增添了味道"

WX78.DESCRIBE.EELTACOS = "鳗鱼已经完成了它们更高的使命"

WX78.DESCRIBE.MEATSKILLET = "我们今天感觉有点大胆，不是吗？"

WX78.DESCRIBE.MEATWALTZ = "为什么那个愚蠢的人这么喜欢生肉"

WX78.DESCRIBE.COMPLETEBREAKFAST = "含有高热量"

WX78.DESCRIBE.DUMPLINGS = "精致的食物"

WX78.DESCRIBE.WARLYICEDTEA = "提神饮料"

WX78.DESCRIBE.WARLYTEA = "人工获得的液体"

WX78.DESCRIBE.KYNO_TEALEAF = "用于制造舒缓液体的有机生命体"

WX78.DESCRIBE.KYNO_ITEMSLICER = "厚刃斩切刀：专为劈砍而铸"
WX78.DESCRIBE.KYNO_ITEMSLICER_GOLD = "厚刃斩切刀：专为劈砍而铸"

WX78.DESCRIBE.COXINHA = "那只哑巴动物的断肢"

WX78.DESCRIBE.LAZYDESSERT = "真倒霉。这不是一种罕见的糖果"

WX78.DESCRIBE.CRABKINGFEAST = "怎样？怎样。这东西怎么可能放进锅里？"

WX78.DESCRIBE.PIENAPPLE = "身体虚弱的人无法克服我的消化系统"

WX78.DESCRIBE.JAWSBREAKER = "吸引具攻击性的海洋生物的诱饵"

WX78.DESCRIBE.AVOCADOTOAST = "恶心"

WX78.DESCRIBE.RICEPUDDING = "恶心的蔬菜混合物"

WX78.DESCRIBE.SHARKSUSHI = "哈哈，愚蠢的鲨鱼不会再惹上级了"

WX78.DESCRIBE.WOBSTERBREADED = "你的盔甲无法保护你的安全"

WX78.DESCRIBE.LAZYPURRITO = "它和它所基于的动物一样令人厌恶"

WX78.DESCRIBE.HORCHATA = "你在开玩笑吧？只有牛奶和冰"

WX78.DESCRIBE.WOBSTERCOCKTAIL = "奢侈食品"

WX78.DESCRIBE.LAVAEEGGBOILED = "分析完成：检测到防火部件"

WX78.DESCRIBE.POMEGRANATETEA = "我敌人做的提神饮料"

WX78.DESCRIBE.TIRAMISU = "含有咖啡因和干燥特性"

WX78.DESCRIBE.TOADSTOOLCOLA = "一种可消耗的附加组件，专为对两栖动物造成破坏而设计。"

WX78.DESCRIBE.TEPACHE = "血糖水平升高"

WX78.DESCRIBE.LUNARTEQUILA = "月之力量，终归我手"

WX78.DESCRIBE.MIMICMOSA = "分析：伪装特性检测"

WX78.DESCRIBE.POMEGRANATEPIE = "水果派"

WX78.DESCRIBE.PINEAPPLECAKE = "纯糖山"

WX78.DESCRIBE.PASTY_MEAT = "我只能要油吗？"
WX78.DESCRIBE.PASTY_CHEESE = "我只能要油吗？"

WX78.DESCRIBE.BRIGADEIRO = "我需要自己的巧克力球。"

WX78.DESCRIBE.REGULARLASAGNA = "至少它不像那个怪物。"

WX78.DESCRIBE.FLTSANDWICH = "他们应得"

WX78.DESCRIBE.RICEANDBEANS = "不喜欢"

WX78.DESCRIBE.KYNO_DECIDUOUSFOREST_SHOP = "结构：过时。更新：待定。预计：2026年。"

WX78.DESCRIBE.KYNO_TRUFFLES_GROUND = 
{
	GENERIC = "RARE ORGANIC MATERIAL DETECTED",
	PICKED = "RESOURCE DEPLETED",
	BURNING = "ERROR: RESOURCE INCINERATED",
}

WX78.DESCRIBE.KYNO_TRUFFLES = "已获取高价值有机材料"
WX78.DESCRIBE.KYNO_TRUFFLES_COOKED = "有机升级完成"

WX78.DESCRIBE.KYNO_ITEMSHOWCASER = 
{
	EMPTY = "POINTLESS DISPLAY UNIT FOR ORGANIC FUEL",
	FULL = "CULINARY OUTPUT ACCEPTABLE",
}

WX78.DESCRIBE.KYNO_SPORECAP = "检测到有机污染物。"
WX78.DESCRIBE.KYNO_SPORECAP_COOKED = "污染等级下降。"

WX78.DESCRIBE.KYNO_SPORECAP_DARK = "检测到致命有机化合物。"
WX78.DESCRIBE.KYNO_SPORECAP_DARK_COOKED = "毒素水平无变化。"

WX78.DESCRIBE.KYNO_GOLDENAPPLE = "检测到无与伦比的能量核心"

WX78.DESCRIBE.TRUFFLESGRINDER = "真菌肉食。能量输出：可接受。"

WX78.DESCRIBE.SPORECAPPIE = "危险的有机物质。"

WX78.DESCRIBE.SPORECAP_SKEWERS = "烧焦的真菌物质。味道：可接受"

WX78.DESCRIBE.TRUFFLEOIL = "有机黏液液体。无用，但很滑。"

WX78.DESCRIBE.KYNO_FISHFARMPLOT_KIT = "构建软件"
WX78.DESCRIBE.KYNO_FISHFARMPLOT_CONSTRUCTION = "湿生生物培育设施：建设中"

WX78.DESCRIBE.KYNO_FISHFARMPLOT = 
{
	GENERIC = "FISH SPAWNING MODULE: ONLINE",
	FUEL_HIGH = "FEED LEVELS OPTIMAL",
	FUEL_MED = "FEED LEVELS ACCEPTABLE",
	FUEL_LOW = "WARNING: FOOD DEPLETION IMMINENT",
	EMPTY = "ERROR: NO FOOD DETECTED",
}

WX78.DESCRIBE.KYNO_ANTCHOVY = "发现混合生物。设计优化不足。"
WX78.DESCRIBE.KYNO_ANTCHOVY_SPAWNER = "杂交种殖民地。检测到非理性行为。"

WX78.DESCRIBE.AGEDROE = "我本以为它们会扭动挣扎。真令人失望。"
WX78.DESCRIBE.AGEDROE_OCEANFISH_STURGEON = "高价值营养纳米球被检测到"

WX78.DESCRIBE.KYNO_SWORDFISH_BLUE = "错误：水上能力丧失。可悲。"

WX78.DESCRIBE.KYNO_JELLYFISH = "这个血肉之躯似乎靠电力驱动"
WX78.DESCRIBE.KYNO_JELLYFISH_DEAD = "分解会增加凝胶质地吗？"
WX78.DESCRIBE.KYNO_JELLYFISH_COOKED = "凝胶质地减少40%"
WX78.DESCRIBE.KYNO_JELLYFISH_DRIED = "其凝胶质地减少了75%"

WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW = "勉强能接受的生命形态"
WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW_DEAD = "我更喜欢这样"
WX78.DESCRIBE.KYNO_JELLYFISH_RAINBOW_COOKED = "彩虹机器人燃料"

WX78.DESCRIBE.KYNO_MESSAGEBOTTLE_EMPTY = "玻璃液体容器"

WX78.DESCRIBE.KYNO_OCEANTRAP = "走进愚蠢的海底生物"

WX78.DESCRIBE.OCEANFISH_PUFFERFISH = "一袋漂浮的毒刺。赞。"
WX78.DESCRIBE.OCEANFISH_STURGEON = "探测到古代水生单位。已淘汰型号。"

WX78.DESCRIBE.KYNO_SWORDFISH = "斗鱼"
WX78.DESCRIBE.KYNO_SWORDFISH_DEAD = "活着毫无价值"

WX78.DESCRIBE.SWORDFISHFEAST = "精密制备的肉质单元。输入数据有效。"

WX78.DESCRIBE.KYNO_DOGFISH = "它漫无目的地游着"
WX78.DESCRIBE.KYNO_DOGFISH_DEAD = "血肉之躯毫无胜算"

WX78.DESCRIBE.KYNO_SPOILED_FISH_LARGE = "万物终将消亡，而后散发气味"

WX78.DESCRIBE.WOBSTER_MONKEYISLAND = "装甲甲壳类单位。高光泽度。"
WX78.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD = "肉类单元：终止。完美。"
WX78.DESCRIBE.WOBSTER_MONKEYISLAND_DEAD_COOKED = "肉类单元：完美优化以供摄入"

WX78.DESCRIBE.KYNO_PUFFERMONSTER = "生物气球充满毒素。危险。"

WX78.DESCRIBE.KYNO_WHALE_OCEAN_BUBBLES = "气泡从未知来源升起"
WX78.DESCRIBE.KYNO_WHALE_BLUE_OCEAN = "检测到血清素水平低于最佳值"
WX78.DESCRIBE.KYNO_WHALE_WHITE_OCEAN = "神话级仇恨值探测到"
WX78.DESCRIBE.KYNO_WHALE_OCEAN_CARCASS = "检测到污浊甲烷积聚"

WX78.DESCRIBE.KYNO_BLUBBER = "多用途哺乳动物脂肪"

WX78.DESCRIBE.KYNO_FISHMEAT_SMALL_DRIED = "脱水水生蛋白质来源"
WX78.DESCRIBE.KYNO_FISHMEAT_DRIED = "持久保鲜海产系列"

WX78.DESCRIBE.MONKEYISLANDMEAL = "香蕉味甲壳类能量源被探测到"

WX78.DESCRIBE.KYNO_BRAINROCK_LARVAE = "不要碰我"
WX78.DESCRIBE.KYNO_BRAINROCK_NUBBIN = "有机生命尚未扎根"
WX78.DESCRIBE.KYNO_BRAINROCK_CORAL = "消费引发智力刺激状态"

WX78.DESCRIBE.KYNO_BRAINROCK_ROCK = 
{
	GENERIC = "HIGHLY EVOLVED CORAL VARIETAL",
	PICKED = "COGNITIVE FUNCTIONS TEMPORARILY DISABLED",
}

WX78.DESCRIBE.BRAINMETTERSOUP = "幼童营养成分表"

WX78.DESCRIBE.KYNO_OCTOPUSKING_OCEAN = 
{
	GENERIC = "MANY-ARMED TRADER",
	SLEEPING = "SUBJECT INACTIVE",
}

WX78.DESCRIBE.KYNO_OCTOPUSKING_TREASURECHEST = "他是如何填满的？"

WX78.DESCRIBE.KYNO_PACKIMBAGGIMS_FISHBONE = 
{
	GENERIC = "DEED OF OWNERSHIP TO EXTERNAL STORAGE UNIT",
	WAITING = "ONE FISH, ONE BIRD. YELLOW FISH, DEAD FISH",
}

WX78.DESCRIBE.KYNO_PACKIMBAGGIMS = "允许你保管我的东西，肉身生物"

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_EMPTY_CONSTRUCTION = "需要更多组件才能组装"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_STAGE = "超大蛋糕需要更多配料才能组装完成"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE = "超大蛋糕，超多人享用"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CANDLE = "火灾隐患。我批准。"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CHEER = "这简直是庆祝的盛宴"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_CAKE_SLICE = "有机庆典燃料已探测到"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_BALLOONS = "虚张声势的橡胶袋，无意义的庆典"

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORNMACHINE = 
{
	GENERIC = "AFFORDABLE ENTERTAINMENT UNIT DETECTED",
	FUEL_HIGH = "FUEL LEVELS OPTIMAL",
	FUEL_MED = "FUEL LEVELS ACCEPTABLE",
	FUEL_LOW = "WARNING: LOW FUEL",
	EMPTY = "ERROR: NO FUEL DETECTED",
}

WX78.DESCRIBE.KYNO_HOFBIRTHDAY_POPCORN = "爆裂蔬菜籽粒。可接受"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_HAT = "检测到装饰性头锥"
WX78.DESCRIBE.KYNO_HOFBIRTHDAY_SAMMYHAT = "独特的头套。萨米享有特权。"

WX78.DESCRIBE.KYNO_FISHREGISTRYHAT = "头部装备启用。鱼类学知识提升。"

WX78.DESCRIBE.KYNO_ANIMALFEEDER =
{
	GENERIC = "ORGANIC REFUELING STATION",
	FUEL_HIGH = "MAXIMUM FEED LEVELS DETECTED",
	FUEL_MED = "FEED LEVELS ACCEPTABLE",
	FUEL_LOW = "WARNING: FEED DEPLETION IMMINENT",
	EMPTY = "ERROR: NO FEED PRESENT",
	BURNT = "SYSTEM DESTROYED BY FIRE",
}