-- Wspólne zależności.
-- local _G      = GLOBAL
-- local require = _G.require
-- local STRINGS = _G.STRINGS

-- Dane. (Nie używane)
STRINGS.SCRAPBOOK.DATA_BREWER = "MOŻE PRZYGOTOWAĆ NAPÓJ"
STRINGS.SCRAPBOOK.FOODTYPE.PREPAREDPOOP = "OKROPNY"
STRINGS.SCRAPBOOK.FOODTYPE.PREPAREDSOUL = "DUSZA"
STRINGS.SCRAPBOOK.FOODTYPE.ALCOHOLIC = "ALKOHOL"

-- Kategorie.
STRINGS.SCRAPBOOK.CATS.ARTISAN = "Rzemieślnicze\nWyroby"

-- Podkategorie.
STRINGS.SCRAPBOOK.SUBCATS.CHICKEN = "Kurczak"
STRINGS.SCRAPBOOK.SUBCATS.PIKO = "Piko"
STRINGS.SCRAPBOOK.SUBCATS.CANNED = "Konserwy"
STRINGS.SCRAPBOOK.SUBCATS.COOKWARE = "Naczynia kuchenne"
STRINGS.SCRAPBOOK.SUBCATS.SEASONALFOOD = "Sezonowe jedzenie"
STRINGS.SCRAPBOOK.SUBCATS.ARTISANGOODS = "Rzemieślnicze wyroby"
STRINGS.SCRAPBOOK.SUBCATS.WINE = "Wino"
STRINGS.SCRAPBOOK.SUBCATS.JUICE = "Sok"
STRINGS.SCRAPBOOK.SUBCATS.JAM = "Dżem"
STRINGS.SCRAPBOOK.SUBCATS.PICKLES = "Marynaty"

-- Efekty jedzenia.
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SPEED = "Zwiększona prędkość ruchu przez określony czas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_COFFEE = "Zwiększona prędkość ruchu przez określony czas.\nKrótko podnosi temperaturę.\n\nHasta la vista, baby!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SLEEP = "Zwiększona odporność na sen przez określony czas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HEALTHREGEN = "Regeneracja zdrowia przez krótki czas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HUNGERREGEN = "Regeneracja głodu przez krótki czas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SANITYREGEN = "Regeneracja poczytalności przez krótki czas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SUPERREGEN = "Super regeneracja ciała przez krótki czas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WORMLIGHT = "Daje zdrowy blask przez krótki czas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ALCOHOL = "Zwiększone obrażenia i zmniejszona prędkość ruchu przez określony czas. Pij z umiarem."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ALCOHOL2 = "Zwiększona odporność na obrażenia i zmniejszona prędkość ruchu przez określony czas. Pij z umiarem."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_RUM = "Zwiększone obrażenia przeciwko piratom przez określony czas.\n\nAni płomienie, ani głębiny nie mogły mnie pochłonąć."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_TEQUILA = "Teleportuje ocalałego w losowe miejsce na mapie."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKACOLA = "Unikalny smak Nuka-Coli to efekt połączenia siedemnastu esencji owocowych, zbalansowanych w celu podkreślenia klasycznego smaku coli. Ugasi pragnienie!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_QUANTUM = "Unikalny smak Nuka-Coli to efekt połączenia siedemnastu esencji owocowych, zbalansowanych w celu podkreślenia klasycznego smaku coli. Ugasi pragnienie!\n\nNuka-Cola Quantum ma dwa razy więcej kalorii, dwa razy więcej węglowodanów, dwa razy więcej kofeiny i dwa razy więcej smaku!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_INSANITY = "Powoduje szaleństwo na krótki czas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NIGHTVISION = "Daje widzenie w nocy przez określony czas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NAUGHTY = "Spożycie tego jedzenia, stworzonego z części niewinnej duszy, spowoduje pojawienie się „Jego” w pobliżu."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_HASTE = "Zwiększona prędkość wszystkich wykonywanych działań przez określony czas. Winona nie korzysta z tego efektu."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BLOOM = "Mieszanka kompostów wrzuconych do garnka, która może stymulować kwitnienie do jego maksymalnego potencjału.\n\n\"Sztuka!\" - Wormwood."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SOUL = "Specjalne jedzenie przygotowane z zebraną Duszą.\n\nWortox może zjeść to jedzenie, aby uzyskać pełne korzyści, bez kar w przeciwieństwie do innych zwykłych jedzeń."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_DEERCLOPS = "Zjedzenie tego jedzenia spowoduje pojawienie się Deerclopsa w pobliżu."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BEARGER = "Zjedzenie tego jedzenia spowoduje pojawienie się Beargera w pobliżu."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FORTUNE = "Złam jednego, aby sprawdzić, co los dla ciebie przygotował."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WATER = "Oczyści wszystkie aktywne efekty jedzenia przetrzymywane przez ocalałego."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FROG = "Zjedzenie tego jedzenia sprawi, że wszystkie żaby staną się przyjazne dla ciebie przez określony czas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_CURSE = "Woodie może zjeść to jedzenie, aby wymusić jedną ze swoich transformacji wybraną losowo."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FEARLESS = "To jedzenie może uczynić ocalałego nieustraszonym przez określony czas. Aurys szaleństwa nie będą miały wpływu w tym okresie."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MONSTERFOOD = "Webber może zjeść to jedzenie bez jakichkolwiek kar."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MONSTERFOOD2 = "Webber can eat this food without any penalties.\nBriefly increases the temperature."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WURTFOOD = "Wurt zyska dodatkowe korzyści z jedzenia tego jedzenia."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLAYERMONSTER = "Webber może zjeść to jedzenie bez jakichkolwiek kar.\nWurt zyska dodatkowe korzyści z jedzenia tego jedzenia."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLAYERMONSTER2 = "Webber can eat this food without any penalties.\nWurt will gain extra benefits from eating this food.\nBriefly decreases the temperature."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLAYERMONSTER3 = "Webber can eat this food without any penalties.\nWurt will gain extra benefits from eating this food.\nBriefly increases the temperature."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SPIDERCAKE = "Webber może zjeść to jedzenie bez jakichkolwiek kar.\n\nDon't Starve Together x Cult of the Lamb - Collab 2023."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SUGARBOMBS = "Paczka słodkich płatków, która zawiera 100% zalecanej dziennej dawki cukru, Sugar Bombs zostały zachowane przez 25 lat po Wielkiej Wojnie. Jednak spowodowało to, że niektóre z nich zawierają trochę promieniowania."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKASHINE = "Nukashine zostało stworzone przez Lewisa z bractwa Eta Psi na Uniwersytecie Vault-Tec w listopadzie 2076. Sam napój jest niezwykle silny, powoduje omdlenia, silne kacze bóle głowy i może być śmiertelny, co przekonało bractwo Pi Mu podczas ich 'imprezy wypróbowawczej'.\n\nWersja bez cukru również istniała, gdzie brak cukru pozwalał pić napój bez ryzyka omdleń."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_NUKASHINE2 = "Teraz bez ryzyka omdleń! Ciesz się imprezą!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BONESOUP = "Zwiększa obrażenia przeciwko robakom przez określony czas."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_REVIVER = "Natychmiastowo wskrzesza martwego gracza, gdy jest nawiedzony."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MOCHA = "Increased movement speed, sleep resistance and decreased hunger loss rate for a certain amount of time.\n\nBriefly increases the temperature."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_LESSFREEZING = "Briefly increases temperature and become less susceptible to Freezing."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_LESSOVERHEAT = "Briefly decreases temperature and become less susceptible to Overheat."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FISHING = "Increased fishing yields for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MIGHTINESS = "Slightly boosts mightiness."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_INSPIRATION = "Slightly boosts inspiration."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_WARLYTEA = "Decreased sanity loss for a certain amount of time.\n\Briefly increases the temperature."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_INCREASETEMP = "Briefly increases the temperature."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_DECREASETEMP = "Briefly decreases the temperature."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_BOUILLABAISSE = "Increased sleep resistance for a certain amount of time.\nBriefly decreases the temperature."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_MOISTURE = "Dries off the survivor and grants them immunity to Wetness for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_SUGARBOMBS_EXPLOSIVE = "These Sugar Bombs are filled with an explosive taste!"
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_EATER = "Makes food more soft and easy to eat for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_CRABKINGFEAST = "Increased damage against crabs for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ANTLION = "Satisfies the Antlion for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_JAWSBREAKER = "Allures and kills Rockjaws and Gnarwails when thrown into the ocean. Does not work if too close."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_FIREIMMUNITY = "This food can make a survivor immune to Fire for a certain amount of time. Briefly increases the temperature."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_TIRAMISU = "Increased movement speed for a certain amount of time.\n\nDries off the survivor and grants them immunity to Wetness for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_AMPHIBIAN = "Increased damage against amphibians for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_ENLIGHTENMENT = "Enlightens the survivor for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_STEALTH = "Renders the survivor unseen and undetectable from traps and creatures for a certain amount of time."
STRINGS.SCRAPBOOK.SPECIALINFO.FOODEFFECTS_PLANARDEFENSE = "Increased planar defense for a certain amount of time."

-- Spice Effects.
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_CURE = "Can be added to Crock Pot food using a Portable Seasoning Station.\n\nEating a dish spiced with Preserver Powder halves the spoilage time and negates spoiled food penalties."
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_MIND = "Can be added to Crock Pot food using a Portable Seasoning Station.\n\nEating a dish spiced with Soothing Sugar grants 25% more sanity."
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_FED = "Can be added to Crock Pot food using a Portable Seasoning Station.\n\nEating a dish spiced with Stuffed Starch grants 25% more hunger."
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_FIRE = "Can be added to Crock Pot food using a Portable Seasoning Station.\n\nEating a dish spiced with Blaze Crystals causes your attacks to ignite targets.\n\nDuration 4 minutes.\n\nAlso raises temperature 15 degrees for 15 seconds."
STRINGS.SCRAPBOOK.SPECIALINFO.SPICEEFFECTS_COLD = "Can be added to Crock Pot food using a Portable Seasoning Station.\n\nEating a dish spiced with Frozen Flakes causes your attacks to freeze targets.\n\nDuration 4 minutes.\n\nAlso lowers temperature 15 degrees for 15 seconds."

-- Items & Foods
STRINGS.SCRAPBOOK.SPECIALINFO.SALT = "Używając szczypty soli w jedzeniu z garnka, przedłużysz czas psucia się o 30%. Nie musisz już martwić się o jedzenie starych potraw!"
STRINGS.SCRAPBOOK.SPECIALINFO.SALTRACK = "Ta półka zbiera małą kostkę soli co kilka dni."
STRINGS.SCRAPBOOK.SPECIALINFO.CRABTRAP = "Po ustawieniu na ziemi, pułapka zostanie uruchomiona, gdy krab przejdzie obok, łapiąc go.\n\nZbierając złapaną pułapkę, umieścisz stworzenie w swoim ekwipunku.\n\nPułapki na kraby mogą być przynętowane mięsem."
STRINGS.SCRAPBOOK.SPECIALINFO.CARAMELCUBE = "To danie jest przysmakiem, stała kostka czystej słodyczy i miłości. To specjalna propozycja dla osób uzależnionych od cukru, bardzo, bardzo popularna wśród starszych osób."
STRINGS.SCRAPBOOK.SPECIALINFO.NECTAR = "Pszczoły, które zapylą wystarczająco dużo kwiatów, wypuszczą nektar po zabiciu.\n\nNektar zostanie przekształcony w miód, gdy zostanie przechowany w Pojemniku na Miód."
STRINGS.SCRAPBOOK.SPECIALINFO.BOTTLESOUL = "Butelkowana Dusza nie liczy się do całkowitej liczby w ekwipunku Wortoxa."
STRINGS.SCRAPBOOK.SPECIALINFO.BOTTLECAP = "Trwałe, przenośne i łatwo rozpoznawalne zakrętki od butelek Nuka-Cola Corporation!"
STRINGS.SCRAPBOOK.SPECIALINFO.CANNEDFOOD = "Znakomita awaryjna żywność. Nie zgnije, dopóki jej nie otworzysz!"
STRINGS.SCRAPBOOK.SPECIALINFO.BREWBOOK = "Rejestr wszystkich napojów uwarzonych i/lub wypitych, a także użytych składników."
STRINGS.SCRAPBOOK.SPECIALINFO.BUCKET = "Wiadro może być użyte do zbierania mleka od zwierząt.\n\nBądź ostrożny, ponieważ niektóre z nich mogą się zdenerwować, gdy spróbujesz to zrobić. Pamiętaj, aby zawsze nosić odpowiednią odzież ochronną.\n\nŁatwiej jest zdobyć mleko od udomowionych zwierząt, ponieważ produkują one więcej jednostek."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_HANGER_ITEM = "Ten wieszak może być zamontowany nad ogniskiem, aby trzymać garnki do gotowania."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_POT_ITEM = "Ten garnek do gotowania wymaga wieszaka zamontowanego nad ogniskiem."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_OVEN_ITEM = "Ten piekarnik można zamontować na ognisku, aby umieścić w nim dania zapiekane."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_CASSEROLE_ITEM = "To danie zapiekane wymaga piekarnika zamontowanego na ognisku."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_GRILL_ITEM = "Ten grill można zamontować na ognisku, aby przygotowywać potrawy."
STRINGS.SCRAPBOOK.SPECIALINFO.HUMANMEAT = "Kampania może poczekać, teraz woła rzeź.\n\nLog Ping można zebrać z ciał swoich towarzyszy."
STRINGS.SCRAPBOOK.SPECIALINFO.MUSSELSTICK_ITEM = "Można umieścić w wodzie, aby łapać małże z biegiem czasu."
STRINGS.SCRAPBOOK.SPECIALINFO.REPAIRTOOLKIT = "Używane do naprawy zniszczonych struktur."
STRINGS.SCRAPBOOK.SPECIALINFO.SAPBUCKET = "Odbieraj świeży sok co kilka dni z drzew Sugarwood."
STRINGS.SCRAPBOOK.SPECIALINFO.SLAUGHTERTOOL = "Narzędzia do rzezi, które natychmiastowo zabijają zwierzę."
STRINGS.SCRAPBOOK.SPECIALINFO.SAPHEALER = "Potężny antidotum z właściwościami leczniczymi dla drzew.\n\nUżywając go na zniszczonych drzewach Sugarwood, przywrócisz je do normalnego stanu."
STRINGS.SCRAPBOOK.SPECIALINFO.ITEMSLICER = "For slicing off meat chunks and other things."
STRINGS.SCRAPBOOK.SPECIALINFO.ITEMSLICER2 = "For slicing off meat chunks and other things, faster!"

-- Stworzenia.
STRINGS.SCRAPBOOK.SPECIALINFO.FEEDCHICKEN = "Można karmić nasionami, aby złożyła jajko."
STRINGS.SCRAPBOOK.SPECIALINFO.PIKO = "Puchate maluchy, które uwielbiają kraść twoje najcenniejsze przedmioty!"
STRINGS.SCRAPBOOK.SPECIALINFO.KINGFISHER = "Zimorodki często upuszczają Tropikalne Karpie z góry. Dosłownie padają ryby!"

-- Struktury, Różne i Miejsca Zainteresowania.
STRINGS.SCRAPBOOK.SPECIALINFO.PIGELDER = "Kupiec z odległego archipelagu. Chce wymieniać swoje najlepsze narzędzia kuchenne i inne przydatne przedmioty na pyszne posiłki.\n\nStarszy pragnie posiłku o ekstremalnej słodyczy lub masła zmieszanego z owocami morza. Nagrodzi cię odpowiednio.\n\nPrzyniesienie ulubionego posiłku Starszego odblokuje nowe oferty handlowe."
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMY = "A merchant from an otherworldly realm. He somehow ended stranded on one of the Constant islands and has built a shop for bartering in the meantime.\n\nSammy trades an array of rare items throughout the seasons and during some special occasions. Make sure to check his wares every now and then to see what he has to offer.\n\nSammy will reward you handsomely if you bring a gift that reminds him of home."
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMYHOUSE = "Sammy's Emporium houses a variety of odd items and antiquities from distant lands and otherworldly realms."
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMYWAGON = "Sammy's cherished wagon. Don't let its size fool you, a lot of things can be stored in there."
STRINGS.SCRAPBOOK.SPECIALINFO.SALTPOND = "Stawy bogate w sól. Stojaki na sól mogą być zainstalowane, aby łatwo pozyskiwać kamienie soli co kilka dni."
STRINGS.SCRAPBOOK.SPECIALINFO.MEALGRINDER = "Stojąc blisko tego urządzenia, survivor otrzyma nowe składniki, które może mielić.\n\nMusisz stać przy kamieniu do mielenia za każdym razem, gdy chcesz zmielić nowy składnik."
STRINGS.SCRAPBOOK.SPECIALINFO.PIKOTREE = "Stojąc blisko drzewa, oferuje to 35% ochrony przed deszczem i chłodzi survivors o niewielką ilość.\n\nTe drzewa herbaciane są zainfekowane małymi stworzonkami zwanymi Piko, które gotowe są do psot."
STRINGS.SCRAPBOOK.SPECIALINFO.ANTCHEST = "Ta specjalna skrzynia może przechowywać tylko przedmioty oparte na miodzie, do 7 przedmiotów jednocześnie. Wydziela również zdrowy blask.\n\nJeśli przechowasz w niej jedzenie na bazie miodu, skrzynia odświeży czas psucia się tych produktów oraz utrzyma je świeże na zawsze.\n\nNektar przechowywany w środku ostatecznie zamieni się w miód."
STRINGS.SCRAPBOOK.SPECIALINFO.BREWER = "Pojemnik na 3 sloty, który przyjmie składniki do warzenia.\n\nUmieszczając 3 przedmioty w pojemniku, umożliwi to ich warzenie i stworzenie jakiegoś rodzaju jedzenia w zależności od umieszczonych składników.\n\nTen proces zwykle trwa kilka dni."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_HANGER = "Użyj do trzymania garnka kuchennego."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_POT_SMALL = "A 3 slot container that will receive ingredients for food.\n\nPlacing 3 items in the container will allow them to be cooked creating some kind of food depending on the items put to begin with.\n\nThis cooking pot cooks faster than regular ones."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_POT = "A 4 slot container that will receive ingredients for food.\n\nPlacing 4 items in the container will allow them to be cooked creating some kind of food depending on the items put to begin with.\n\nThis cooking pot cooks faster than regular ones and yield an extra unit of the cooked food."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_SYRUP_POT = "Pojemnik na 4 sloty, który przyjmie składniki do przygotowania syropu.\n\nUmieszczając 4 soki w pojemniku, umożliwi to ich gotowanie i stworzenie syropu.\n\nTen garnek może gotować tylko syrop i zawsze daje dodatkową jednostkę."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_OVEN = "Użyj, aby umieścić w nim naczynie do zapiekania."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_CASSEROLE_SMALL = "A 3 slot container that will receive ingredients for food.\n\nPlacing 3 items in the container will allow them to be cooked creating some kind of food depending on the items put to begin with.\n\nThis cooking pot cooks faster than regular ones."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_CASSEROLE = "A 4 slot container that will receive ingredients for food.\n\nPlacing 4 items in the container will allow them to be cooked creating some kind of food depending on the items put to begin with.\n\nThis cooking pot cooks faster than regular ones and yield an extra unit of the cooked food."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_GRILL_SMALL = "A 3 slot container that will receive ingredients for food.\n\nPlacing 3 items in the container will allow them to be cooked creating some kind of food depending on the items put to begin with.\n\nThis cooking pot cooks faster than regular ones."
STRINGS.SCRAPBOOK.SPECIALINFO.COOKWARE_GRILL = "A 4 slot container that will receive ingredients for food.\n\nPlacing 4 items in the container will allow them to be cooked creating some kind of food depending on the items put to begin with.\n\nThis cooking pot cooks faster than regular ones and yield an extra unit of the cooked food."
STRINGS.SCRAPBOOK.SPECIALINFO.KOKONUTTREE = "Stojąc blisko drzewa, oferuje to 35% ochrony przed deszczem i chłodzi survivors o niewielką ilość.\n\nUważaj na spadające kokosy!"
STRINGS.SCRAPBOOK.SPECIALINFO.MUSSELSTICK = "Ten kij jest nieodparty dla małży, pozostaw go na chwilę, a wypełni się małżami, które możesz zebrać."
STRINGS.SCRAPBOOK.SPECIALINFO.MUSHSTUMP = "Ten pień ma specjalny rodzaj grzyba, uważany przez wielu za przysmak.\n\nWzrost zajmuje prawie 5 dni."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE = "Stojąc blisko drzewa, oferuje to 35% ochrony przed deszczem i chłodzi survivors o niewielką ilość.\n\nTe drzewa można naciąć za pomocą zestawu do nacięcia drzew, aby produkować świeży sok co kilka dni."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_SAPPED = "Stojąc blisko drzewa, oferuje to 35% ochrony przed deszczem i chłodzi survivors o niewielką ilość.\n\nProdukcja soku trwa prawie 3 dni.\n\nNie pozwól, aby sok się przepełnił, w przeciwnym razie stanie się zepsuty."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_RUINED = "Stojąc blisko drzewa, oferuje to 35% ochrony przed deszczem i chłodzi survivors o niewielką ilość.\n\nZrujnowane drzewa nie mogą produkować świeżego soku, będą produkować Zrujnowany Sok.\n\nMożesz uleczyć zrujnowane drzewa za pomocą Mustego Antidotum."
STRINGS.SCRAPBOOK.SPECIALINFO.SUGARTREE_RUINED2 = "Stojąc blisko drzewa, oferuje to 35% ochrony przed deszczem i chłodzi survivors o niewielką ilość.\n\nMożesz uleczyć zrujnowane drzewa za pomocą Mustego Antidotum."
STRINGS.SCRAPBOOK.SPECIALINFO.RUBBLE = "Starszy chce twojej pomocy w naprawieniu jego Starego Garnka, aby mógł znów zacząć robić pyszny syrop."
STRINGS.SCRAPBOOK.SPECIALINFO.PINEAPPLEBUSH = "Krzak ananasowy rośnie prawie 6 dni, aby osiągnąć pełny wzrost. Rośnie wolniej w każdych porach roku oprócz lata.\n\nLatem zaczynają rosnąć co 2 dni."
STRINGS.SCRAPBOOK.SPECIALINFO.GARDENSPRINKLER = "Może być włączony i wyłączony. Jeśli jest zasilany i włączony, automatycznie podleje rośliny uprawne w jego zasięgu."
STRINGS.SCRAPBOOK.SPECIALINFO.SAMMYHAT = "Reduces hunger by 15%."
STRINGS.SCRAPBOOK.SPECIALINFO.POTATOSACK = "A 6 slot container that can store potato-related items and keep them fresh for longer periods.\n\n\"Potatoes is strong for belly!\" - Wolfgang."