------------------------------------------------------------------------------------------------------------
-- World Generation
------------------------------------------------------------------------------------------------------------

-- WORLDGEN RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES = "Aloes"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES = "Szparagi"
STRINGS.UI.CUSTOMIZATIONSCREEN.COFFEEBUSHES = "Krzewy kawy"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS = "Koper włoski"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS = "Gigantyczne pasternaki"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS = "Pniaki grzybów"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES = "Trufle"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS = "Pasternaki"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES = "Rzodkiewki"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES = "Kamienne płyty"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES = "Bataty"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS = "Rzepy"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS = "Dzikie pszenice"

-- WORLDGEN OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.BRAINROCKS = "Mózgokiełki"
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS = "Kwiaty lotosu"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES = "Mokre skrzynie"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS = "Wraki"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS = "Ogórki morskie"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS = "Korzenie taro"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES = "Rzeżucha wodna"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA = "Wodorosty"

-- WORLDGEN SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.SERENITYISLAND = "Starszy Świniak"
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS = "Solne stawy"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES = "Cętkowane krzewy"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS = "Cukrowe kwiaty"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES = "Cukrowe drzewa"

-- WORLDGEN MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.MEADOWISLAND = "Sammy"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMHUTS = "Chaty rybołapów mermów"
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES = "Skrzynie"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES = "Palmy"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS = "Skały z przyssawkami"
STRINGS.UI.CUSTOMIZATIONSCREEN.MERMHUTS = "Chaty merenów"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOTREES = "Zainfekowane drzewa herbaciane"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES = "Krzewy ananasów"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS = "Piaszczyste kopce"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES = "Drzewa herbaciane"
STRINGS.UI.CUSTOMIZATIONSCREEN.TIDALPOOLS = "Baseny pływowe"

-- WORLDGEN CREATURES
STRINGS.UI.CUSTOMIZATIONSCREEN.ANTCHOVIES = "Mrówosardele"
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS = "Kury"
STRINGS.UI.CUSTOMIZATIONSCREEN.DOGFISHES = "Rekinopsowate"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS = "Rybołapacze mermów"
STRINGS.UI.CUSTOMIZATIONSCREEN.HERMITWOBSTERS = "Pustelnicze homary"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES = "Meduzy"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES2 = "Tęczowe meduzy"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS = "Kamykowe kraby"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS = "Pikosy"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE = "Pomarańczowe pikosy"
STRINGS.UI.CUSTOMIZATIONSCREEN.PUFFERMONSTERS = "Rozdymka"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES = "Cukromuchy"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWORDFISHES = "Mieczniki"

------------------------------------------------------------------------------------------------------------
-- World Settings
------------------------------------------------------------------------------------------------------------

-- GLOBALSETTINGS
STRINGS.UI.CUSTOMIZATIONSCREEN.HOFBIRTHDAY = "Rocznica Heap of Food"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANHUNTS_SETTING = "Oceaniczne łowy"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANHUNTALTS_SETTING = "Niespodzianki oceanicznych łowów"

-- WORLDSETTINGS RESOURCES
STRINGS.UI.CUSTOMIZATIONSCREEN.ALOES_SETTING = "Aloes"
STRINGS.UI.CUSTOMIZATIONSCREEN.ASPARAGUSES_SETTING = "Szparagi"
STRINGS.UI.CUSTOMIZATIONSCREEN.COFFEEBUSHES_SETTING = "Krzewy kawy"
STRINGS.UI.CUSTOMIZATIONSCREEN.FENNELS_SETTING = "Koper włoski"
STRINGS.UI.CUSTOMIZATIONSCREEN.GIANTPARZNIPS_SETTING = "Gigantyczne pasternaki"
STRINGS.UI.CUSTOMIZATIONSCREEN.MUSHSTUMPS_SETTING = "Pniaki grzybów"
STRINGS.UI.CUSTOMIZATIONSCREEN.TRUFFLES_SETTING = "Trufle"
STRINGS.UI.CUSTOMIZATIONSCREEN.PARZNIPS_SETTING = "Pasternaki"
STRINGS.UI.CUSTOMIZATIONSCREEN.RADISHES_SETTING = "Rzodkiewki"
STRINGS.UI.CUSTOMIZATIONSCREEN.ROCKFLIPPABLES_SETTING = "Kamienne płyty"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWEETPOTATOES_SETTING = "Bataty"
STRINGS.UI.CUSTOMIZATIONSCREEN.TURNIPS_SETTING = "Rzepy"
STRINGS.UI.CUSTOMIZATIONSCREEN.WILDWHEATS_SETTING = "Dzikie pszenice"

-- WORLDSETTINGS OCEAN
STRINGS.UI.CUSTOMIZATIONSCREEN.BRAINROCKS_SETTING = "Mózgokiełki"
STRINGS.UI.CUSTOMIZATIONSCREEN.LOTUSPLANTS_SETTING = "Kwiaty lotosu"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANCRATES_SETTING = "Mokre skrzynie"
STRINGS.UI.CUSTOMIZATIONSCREEN.OCEANWRECKS_SETTING = "Wraki"
STRINGS.UI.CUSTOMIZATIONSCREEN.SEACUCUMBERS_SETTING = "Ogórki morskie"
STRINGS.UI.CUSTOMIZATIONSCREEN.TAROROOTS_SETTING = "Korzenie taro"
STRINGS.UI.CUSTOMIZATIONSCREEN.WATERYCRESSES_SETTING = "Rzeżucha wodna"
STRINGS.UI.CUSTOMIZATIONSCREEN.WEEDSEA_SETTING = "Wodorosty"

-- WORLDSETTINGS SERENITYISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.SALTPONDS_SETTING = "Słony staw"
STRINGS.UI.CUSTOMIZATIONSCREEN.SPOTBUSHES_SETTING = "Cętkowane krzewy"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLOWERS_SETTING = "Słodkie kwiaty"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARTREES_SETTING = "Cukrodrewne drzewa"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAPSUGARTREES_SETTING = "Soki"
STRINGS.UI.CUSTOMIZATIONSCREEN.SAP2SUGARTREES_SETTING = "Zepsute soki"
STRINGS.UI.CUSTOMIZATIONSCREEN.RUINEDSUGARTREES_SETTING = "Zrujnowane cukrodrewne drzewa"

-- WORLDSETTINGS MEADOWISLAND
STRINGS.UI.CUSTOMIZATIONSCREEN.ISLANDCRATES_SETTING = "Skrzynie"
STRINGS.UI.CUSTOMIZATIONSCREEN.KOKONUTTREES_SETTING = "Palmy"
STRINGS.UI.CUSTOMIZATIONSCREEN.LIMPETROCKS_SETTING = "Skały z przyssawkami"
STRINGS.UI.CUSTOMIZATIONSCREEN.PINEAPPLEBUSHES_SETTING = "Krzewy ananasów"
STRINGS.UI.CUSTOMIZATIONSCREEN.SANDHILLS_SETTING = "Piaszczyste kopce"
STRINGS.UI.CUSTOMIZATIONSCREEN.TEATREES_SETTING = "Drzewa herbaciane"

-- WORLDSETTINGS CREATURES
STRINGS.UI.CUSTOMIZATIONSCREEN.CHICKENS_SETTING = "Kury"
STRINGS.UI.CUSTOMIZATIONSCREEN.DOGFISHES_SETTING = "Rekinopsowate"
STRINGS.UI.CUSTOMIZATIONSCREEN.FISHERMERMS_SETTING = "Rybo-merenowie"
STRINGS.UI.CUSTOMIZATIONSCREEN.HERMITWOBSTERS_SETTING = "Pustelnicze wobstery"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES_SETTING = "Meduzy"
STRINGS.UI.CUSTOMIZATIONSCREEN.JELLYFISHES2_SETTING = "Tęczowe meduzy"
STRINGS.UI.CUSTOMIZATIONSCREEN.PEBBLECRABS_SETTING = "Kamykowe kraby"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOS_SETTING = "Pikosy"
STRINGS.UI.CUSTOMIZATIONSCREEN.PIKOSORANGE_SETTING = "Pomarańczowe pikosy"
STRINGS.UI.CUSTOMIZATIONSCREEN.PUFFERMONSTERS_SETTING = "Puffernauty"
STRINGS.UI.CUSTOMIZATIONSCREEN.SUGARFLIES_SETTING = "Cukromuchy"
STRINGS.UI.CUSTOMIZATIONSCREEN.SWORDFISHES_SETTING = "Mieczniki"